### ISSUE TITLE
关于画布内容位置的调整，把画布的矩形内容放到画布中心而不是吧画布放到视口中心

### ISSUE THREAD

**Issue by Renato-Z** [antvis/X6#1002]
### 关于centerContent API 调整后的效果如下
红框是视口容器，蓝框是画布
![image](https://user-images.githubusercontent.com/50518861/119432582-2968e500-bd47-11eb-9de5-1c76d540b7d9.png)
使用 api 后画布位置被移动，这个时候拖拽节点到画布之外会无法正常显示
![image](https://user-images.githubusercontent.com/50518861/119432800-8fee0300-bd47-11eb-9e18-b0e8ab80f18a.png)

- 说明：关于其他几个 api 测试也是改变画布位置的

### 当前的解决方案
目前我在项目里是通过计算容器的宽度 / 2 加到每一个节点 x 坐标中，并做细微调整，高度同理

### 建议增加一个 api
- 只针对内容位置变更，吧画布内矩形内容放到画布中心即可

**Comment by NewByVector** [comment]
参考这个 dmeo： https://codesandbox.io/s/center-pos-n9ceb

**Comment by Renato-Z** [comment]
啊，好吧，我之前也是基于这个思路去实现的

但还是认为可以有这样的 API，感觉应该也会比较常用的，仅为个人建议
