### ISSUE TITLE
是否可以单独拖拽画布矩形内容，而不是整个画布

### ISSUE THREAD

**Issue by Renato-Z** [antvis/X6#1003]
我希望画布固定的状态下，可以直接在空白区域按下鼠标拖动画布的矩形（内容），不是通过框选后的拖动

目前我通过鼠标位置计算到每一个节点的坐标中动态修改，我不知道这种方法是否合适

**Comment by NewByVector** [comment]
想问一下你这边不使用 `panning` 开启画布平移的原因是什么？

**Comment by Renato-Z** [comment]
这个在另一条 issues 中有提到，https://github.com/antvis/X6/issues/1002

还是因为拖拽画布后，画布位置偏移，导致拖拽节点到相对应的 container 内显示有问题

**Comment by NewByVector** [comment]
感谢你的建议，这个在常见的图编辑场景并不常见，暂时没有计划实现。
