### ISSUE TITLE
自定义删除按钮

### ISSUE THREAD

**Issue by chrioseXX** [antvis/X6#1006]
自定义删除节点，阅读button-remove节点代码
copy了一份
在定义button时报错
代码如下：
import { Button } from "@antv/x6/es/registry/tool/button";

// eslint-disable-next-line
x6内部报错 
const RemoveBtn = Button.define<Button.Options>({
  name: 'remove-btn',
  markup: [
    {
      tagName: "rect",
      selector: "button",
      attrs: {
        width: 32,
        height: 28,
        rx: 0,
        ry: 0,
        fill: "white",
        stroke: "#fff",
        "stroke-width": 2,
        cursor: "pointer"
      }
    },
    {
      tagName: "text",
      selector: "text",
      textContent: "x",
      attrs: {
        fill: "black",
        "font-size": 14,
        "text-anchor": "middle",
        "pointer-events": "none",
        x: 16,
        y: 16
      }
    }
  ],
  onClick({ view, btn }) {
    btn.parent.remove();
    view.cell.remove({ ui: true, toolId: btn.cid });
  }
})
Graph.registerNodeTool('remove', RemoveBtn, true)

errorMsg: Uncaught TypeError: Cannot read property 'ToolItem' of undefined

### Expected Behavior
期望自定义删除节点可用

### Current Behavior
![Uploading image.png…]()

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [1.21.7]
- OS: [macOSBig Sur 11.2 ]
- Browser: [chrome 版本 90.0.4430.212（正式版本） (arm64)]

**Comment by w345731923** [comment]
你用的是ts还是js，再就是图片看不到，最好使用codesandbox示例自己代码，便于查错

**Comment by chrioseXX** [comment]
> 你用的是ts还是js，再就是图片看不到，最好使用codesandbox示例自己代码，便于查错

typescript 

https://codesandbox.io/s/competent-zhukovsky-pp9q3?file=/src/app.tsx
注册自定义删除节点的代码我贴到链接了

**Comment by w345731923** [comment]
> > 你用的是ts还是js，再就是图片看不到，最好使用codesandbox示例自己代码，便于查错
> 
> typescript
> 
> https://codesandbox.io/s/competent-zhukovsky-pp9q3?file=/src/app.tsx
> 注册自定义删除节点的代码我贴到链接了

参考api介绍 https://x6.antv.vision/zh/docs/tutorial/intermediate/custom-node

> > 你用的是ts还是js，再就是图片看不到，最好使用codesandbox示例自己代码，便于查错
> 
> typescript
> 
> https://codesandbox.io/s/competent-zhukovsky-pp9q3?file=/src/app.tsx
> 注册自定义删除节点的代码我贴到链接了

两个地方需要改，
第一个是把声明放到上面，初始化的时候就加载。
第二个是节点需要加载这个自定义组件，官方给的例子已经写了
      tools: [
        {
          name: 'my-btn',
          args: {
            x: '100%',
            y: '100%',
            offset: { x: -44, y: -24 },
          },
        },
      ]

具体详情看官方demo  https://x6.antv.vision/zh/docs/api/registry/node-tool

**Comment by w345731923** [comment]
![image](https://user-images.githubusercontent.com/10808170/120147923-05f7db80-c21a-11eb-9083-d1232bd4a4d8.png)
