### ISSUE TITLE
继承Node，注册的节点，graph.createNode，属性添加不上去。

### ISSUE THREAD

**Issue by 1637410810** [antvis/X6#1007]
import { Graph, Node } from "@antv/x6";

class Test extends Node {
  constructor() {
    super();
    this.collapsed = true;
  }
}
Test.config({
  shape: "rect",
  markup: [
    {
      tagName: "rect",
      selector: "body"
    }
  ],
  attrs: {
    body: {
      refWidth: 100,
      refHeight: 100,
      fill: "red"
    }
  }
});
Graph.registerNode("test", Test);

graph.createNode({
      shape: 'test',
      attrs: {
        body: {
          fill: 'blue',
        },
      }
    })

添加不上去

**Comment by w345731923** [comment]
上完整代码或者demo

**Comment by 1637410810** [comment]
@w345731923 
https://codesandbox.io/s/wonderful-roentgen-19u6z?file=/src/App.vue

**Comment by w345731923** [comment]
> @ w345731923
> https://codesandbox.io/s/wonderful-roentgen-19u6z?file=/src/App.vue

我尝试吸怪attrs('/body/fill',black)，发现demo并未出现异常，可以注册节点

**Comment by 1637410810** [comment]
@w345731923 
![image](https://user-images.githubusercontent.com/42006019/119591329-fc7d0680-be08-11eb-9c1d-366eba3c9139.png)

我设置的填充红色，并未生效

**Comment by w345731923** [comment]
> @w345731923
> ![image](https://user-images.githubusercontent.com/42006019/119591329-fc7d0680-be08-11eb-9c1d-366eba3c9139.png)
> 
> 我设置的填充红色，并未生效

使用继承确实没实现，我是用的下面方式声明的

> Graph.registerNode("test1", {
  shape: "test1",
  markup: [
    {
      tagName: "rect",
      selector: "body",
    },
  ],
  attrs: {
    body: {
      refWidth: "100",
      refHeight: "100",
      strokeWidth: 1,
      fill: "rgba(95,149,255,0.05)",
      stroke: "#5F95FF",
    },
  },
}, true);

**Comment by w345731923** [comment]
使用继承的方式，debugger时候，拿到新的attr，去进行isNode，得出的结果是不是cell，所以按照原始attr实例化

**Comment by 1637410810** [comment]
@w345731923 
https://codesandbox.io/s/flamboyant-glade-vljm4?file=/src/app.tsx
一个官方的demo  集成的   我改了，    新得attr又能用  。。。。。。

**Comment by w345731923** [comment]
> @w345731923
> https://codesandbox.io/s/flamboyant-glade-vljm4?file=/src/app.tsx
> 一个官方的demo 集成的 我改了， 新得attr又能用 。。。。。。

可能我遗漏了一个重要因素，就是不能重复注册，我也是import的shape。
Graph.registerNode("qwe", Group, true);这行代码放到shape.ts是不是好一点
Good job!

**Comment by 1637410810** [comment]
@w345731923 
重点来了，同样的代码  react好使，vue不好使。

**Comment by 1637410810** [comment]
@w345731923 
react https://codesandbox.io/s/flamboyant-glade-vljm4?file=/src/app.tsx
vue https://codesandbox.io/s/wonderful-roentgen-19u6z?file=/src/App.vue
