### ISSUE TITLE
scroller下画布的自动扩展

### ISSUE THREAD

**Issue by frienkiss** [antvis/X6#1009]
![image](https://user-images.githubusercontent.com/28303439/119476860-0824ea80-bd81-11eb-82d1-be87fe1e661c.png)

上侧是扩展出来的画布，点击时 y 的位置为什么是负的，而不是从上侧扩展出的page开始从0开始重新定位

**Comment by NewByVector** [comment]
这个坐标是以主 graph 为准计算的，如果要实现的你功能，可以对坐标进行转换：
```ts
const pos = graph.localToGraph(x, y)
```
