### ISSUE TITLE
自定义右键菜单如何传cell

### ISSUE THREAD

**Issue by w345731923** [antvis/X6#1010]
### Expected Behavior
我参考的案例 https://x6.antv.vision/zh/examples/edge/tool#context-menu
我的问题：
1、在menu中，我想处理cell的业务，如果把cell传给menu
2、我的demo有时候会卡，发出警告是[Violation] 'setTimeout' handler took 744ms

我的dmeo地址 https://codesandbox.io/s/x6-my-btn-x07ck

### Possible Solution

如果哪里写的不好，还请指教

**Comment by w345731923** [comment]
我把menu声明放到了cell:contextmenu就成功了
我很想为社区贡献，可是不知道demo应该怎么去部署

**Comment by NewByVector** [comment]
@w345731923 官网示例 demo 都在这个路径下面 https://github.com/antvis/X6/tree/master/sites/x6-sites/examples ，你可以提 PR

**Comment by w345731923** [comment]
> @w345731923 官网示例 demo 都在这个路径下面 https://github.com/antvis/X6/tree/master/sites/x6-sites/examples ，你可以提 PR

大部分的例子都跑不起来，yarn或者npm失败

**Comment by NewByVector** [comment]
@w345731923 能留个联系方式吗？

**Comment by w345731923** [comment]
> @w345731923 能留个联系方式吗？

我在钉钉群，群里那个截图就是我发的
