### ISSUE TITLE
文档问题：访问部署在 gitee 的镜像站，在上面的搜索框执行搜索操作，会定向到 x6.antv.vision …… 

### ISSUE THREAD

**Issue by iceytea** [antvis/X6#1019]
### Current Behavior

访问部署在 gitee 的镜像站，在上面的搜索框执行搜索操作，会定向到 x6.antv.vision ……

### Steps To Reproduce

具体情况请看下面的 gif 图片

![ts](https://user-images.githubusercontent.com/77133362/119640442-3242df00-be4b-11eb-884f-b67bb078eb60.gif)

以下是可复现网址
https://antv-x6.gitee.io/zh/docs/api/graph/interaction

**Comment by iceytea** [comment]
问题依然存在，麻烦解决一下

**Comment by NewByVector** [comment]
已经给官网提了 issue：https://github.com/antvis/gatsby-theme-antv/pull/332， 等待发布新的版本
