### ISSUE TITLE
期待补充Graph.registerGrid详细案列

### ISSUE THREAD

**Issue by ctrlands** [antvis/X6#1021]
### Expected Behavior
现在的Graph.registerGrid没有具体的案列说明，不清楚传参和返回类型是什么？希望补充案例说明，和[自定义背景重复方式](https://x6.antv.vision/zh/docs/api/registry/background/#register)一样案例一样

Graph.registerGrid('', (params????) => { return ? }, true);

**Comment by NewByVector** [comment]
已经补充：https://github.com/antvis/X6/pull/1035
