### ISSUE TITLE
导出png文件，react节点样式和属性失效

### ISSUE THREAD

**Issue by lgf196** [antvis/X6#1022]
代码如下
![image](https://user-images.githubusercontent.com/29600558/119806317-ae552980-bf14-11eb-9519-a09e02ec67d0.png)
预览模式
![image](https://user-images.githubusercontent.com/29600558/119806484-d2186f80-bf14-11eb-953e-949d96129b33.png)
导出png格式
![image](https://user-images.githubusercontent.com/29600558/119806580-e8263000-bf14-11eb-8aa0-3d8e967c1d69.png)

**Comment by NewByVector** [comment]
图片使用 base64 图标可以解决导出问题

**Comment by lgf196** [comment]
> 图片使用 base64 图标可以解决导出问题
但是我自定义的react组件样式都没有了

**Comment by Wangyizhi1** [comment]
I have the same problem. After exporting PNG, the style of Vue component is lost.
