### ISSUE TITLE
一个关于stencil的性能问题，加载太慢

### ISSUE THREAD

**Issue by cchhcui** [antvis/X6#1025]
我们的应用场景是stencil有20多个分组Group，每个分组有几个元件，累计大约200个元件，在使用this.stencil.load(nodes, groupName)的时候，加载时间竟然要100秒左右，这样的加载性能客户实在是无法接受，请问是否有更好的加载方法或者技巧？

想用点击分组Group的方式，点开展开时加载，可是找不到分组Group点击展开的事件。请问有这种展开事件吗？如何使用？

**Comment by NewByVector** [comment]
我本地测试了一下，100 节点大约 70ms，你这个 100s 给个 codesanbox 看下？

**Comment by cchhcui** [comment]
> 
> 
> 我本地测试了一下，100 节点大约 70ms，你这个 100s 给个 codesanbox 看下？

我不太会用codesanbox，所以给你126信箱发了部分代码，请查收

**Comment by NewByVector** [comment]
你在 stencil.load 方法前后打印时间，排除其他影响，看下实际 load 耗时多少，

**Comment by cchhcui** [comment]
> 
> 
> 你在 stencil.load 方法前后打印时间，排除其他影响，看下实际 load 耗时多少，

用你提供的方法，设置输出，找到问题了，确认不是架构的问题，是外围代码的问题，不好意思，给你添麻烦了！非常感谢！
