### ISSUE TITLE
画布是否可以在背景显示xy轴？

### ISSUE THREAD

**Issue by LHMing01** [antvis/X6#1026]
### Expected Behavior
画布开启panning后，拖动画布后，不知道最开始的xy轴（画布中心）到哪里了，我们有需求需要可以直接设置node的（x，y）坐标，但是拖动后无法看到画布中心，最终设置node的（x，y）后可能在很偏远的地方，甚至脱离可视范围。期望画布支持显示xy轴

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
可以调用 `graph.centerContent()` 将内容居中显示

**Comment by LHMing01** [comment]
能否支持下，不然用户在多次拖动画布可能就不知道画布中心到哪了

**Comment by LHMing01** [comment]
本来想用minimap的，但是必须要开始scroller，所以就舍弃了用panning。

**Comment by NewByVector** [comment]
@LHMing01 非 scroller 画布支持 minimap 已经在路上
