### ISSUE TITLE
Selection isn't notifying events and blocking node (cell) events

### ISSUE THREAD

**Issue by wael-mohamed** [antvis/X6#1027]
Selection isn't notifying events and blocking node events

### Expected Behavior

When a collection of selected nodes is moved by a user, the node that has been moved or clicked should emit events just like nodes, for example:

- "node:moved"
- "node:moving"
- "node:moved"
- "node:mouseup"
and more...

### Current Behavior

No event is handled by the graph.on(event, handler).

### Possible Solution

Add specific events for selection, for example:

- "selection:moved"
- "selection:moving"
- "selection:moved"
- "selection:mouseup"

### Steps To Reproduce

Select some nodes, and move the selection.

### Additional Context

React components has been used to render nodes

### Your Environment

- x6: 1.22.0
- OS: macOS 11.4
- Browser: chrome 90.0.4430.212

**Comment by NewByVector** [comment]
The `node:moved` `node:move` `node:moving`  event is emitted when moving colleciton
