### ISSUE TITLE
自定义节点 如何设置多个path

### ISSUE THREAD

**Issue by iamwelk** [antvis/X6#1028]
### 目标效果
![image](https://user-images.githubusercontent.com/6983075/120101975-7996db80-c17b-11eb-81c8-bf96792dbf51.png)

### 当前效果
![image](https://user-images.githubusercontent.com/6983075/120102012-96cbaa00-c17b-11eb-9120-f899d51e226f.png)

### 当前的节点属性配置如下：
```js
const option = {
  inherit: 'path',
  width: 30,
  height: 30,
  markup: [
    {
      tagName: 'path',
      selector: 'body'
    },
    {
      tagName: 'path',
      selector: 'inner'
    },
    {
      tagName: 'text',
      selector: 'label'
    }
  ],
  attrs: {
    body: {
      stroke: '#333',
      fill: '#fff',
      strokeWidth: 2,
      refD: 'M 0 15C 0 -5 30 -5 30 15C 30 35 0 35 0 15Z'
    },
    inner: {
      fill: '#333',
      refD: 'M 7.5 15C 7.5 5 22.5 5 22.5 15C 22.5 25 7.5 25 7.5 15Z'
    }
  }
};
```

如何才能实现目标图片中的效果呢

**Comment by OpportunityLiu** [comment]
反正我是自己写了个自定义特殊属性解决的。。。

**Comment by iamwelk** [comment]
> 反正我是自己写了个自定义特殊属性解决的。。。

大佬你是怎么写的，求赐教哇~

**Comment by OpportunityLiu** [comment]
你这个用圆就行了吧，也没必要非要弄个path

**Comment by iamwelk** [comment]
> 你这个用圆就行了吧，也没必要非要弄个path

这个是可以用圆形，保不准其他的形状可能会用到path，如果有通用的方案当然最好

**Comment by NewByVector** [comment]
参考 demo： https://codesandbox.io/s/circle2-cuy98

**Comment by iamwelk** [comment]
> 参考 demo： https://codesandbox.io/s/circle2-cuy98

用d属性是可以，但是用refD主要是为了可以跳转大小，用了d的话就没法调整了。。
大佬，有没有支持多个refD的方案？

**Comment by iamwelk** [comment]
这个还能被关注到吗，有没有大佬能给个方案的~

**Comment by NewByVector** [comment]
再看看这个呢？https://codesandbox.io/s/circle2-cuy98?file=/src/app.tsx

**Comment by iamwelk** [comment]
> 再看看这个呢？https://codesandbox.io/s/circle2-cuy98?file=/src/app.tsx

可以，谢谢大佬！！
