### ISSUE TITLE
运行「examples/x6-example-drawio」这个demo时，sideBar中的元素为空

### ISSUE THREAD

**Issue by huanyueyaoqin** [antvis/X6#103]
### Current Behavior

运行`example/x6-example-drawio`这个demo时，
左侧sideBar中的元素为空

svg中只有<g></g>，内容为空

### Steps To Reproduce

执行`example/x6-example-drawio`就可以发现

### Your Environment

- x6: [e.g. 0.3.4]
- OS: [e.g. macOS Sierra 10.15.2]
- Browser: [e.g. chrome 81.0.4044.113]

**Comment by NexxLuo** [comment]
0.3.2是正确的，新版本不对，需要如何处理？

**Comment by NexxLuo** [comment]
挺急的，望回复

**Comment by huanyueyaoqin** [comment]
> 0.3.2是正确的，新版本不对，需要如何处理？
我这边重新在官网下载了demo，改成了0.3.2版本，左边还是空白的

**Comment by NexxLuo** [comment]
真是让人苦恼，看了源码也找不到问题所在，处理不了。只能锁定版本了
