### ISSUE TITLE
 getCellsBBox()返回错误的矩形区域

### ISSUE THREAD

**Issue by 1637410810** [antvis/X6#1036]
getCellsBBox()返回指定节点和边构成的矩形区域。
带上边之后，返回的大小与实际不相符

**Comment by NewByVector** [comment]
有 demo 可以看下吗？

**Comment by 1637410810** [comment]
@NewByVector 
https://codesandbox.io/s/nameless-meadow-gw11n?file=/src/App.vue

**Comment by NewByVector** [comment]
实际连线区域是这里：
![image](https://user-images.githubusercontent.com/20186737/121006660-b7bb7d00-c7c3-11eb-9f35-3666402f9c15.png)

**Comment by 1637410810** [comment]
实际上，获得的区域比这个大的多

**Comment by NewByVector** [comment]
这个是因为你是克隆的边，已经失去了计算 bbox 的意义，可以修改成这样：https://codesandbox.io/s/late-dew-ihmt2?file=/src/graph.js
