### ISSUE TITLE
无限画布支持

### ISSUE THREAD

**Issue by happy-little-one** [antvis/X6#1037]
实例化时不必传入宽高，画布默认是无限的。container的尺寸只是代表视窗的大小，这样也无需滚动条了。

我觉得这个应该容易实现，这是svg默认的特性。

**Comment by NewByVector** [comment]
现在是已经支持的： https://x6.antv.vision/zh/docs/tutorial/basic/graph#%E7%94%BB%E5%B8%83%E5%B9%B3%E7%A7%BB

**Comment by happy-little-one** [comment]
我希望可以滚动和拖拽，但不想要滚动条。这样体验更好。可以看下这个 https://demo.bpmn.io/new

**Comment by NewByVector** [comment]
上面我发的链接就是支持这个功能的（并没有滚动条）

**Comment by happy-little-one** [comment]
这个仅仅是拖拽，如果设置了scroller为true，就会出现滚动条

**Comment by NewByVector** [comment]
![image](https://user-images.githubusercontent.com/20186737/120193770-5f2e3200-c24f-11eb-8568-dfbe06b2e5a3.png)
开启 panning 后支持拖拽平移，eventTypes 参数配置 mousewheel 后支持触摸板平移

**Comment by happy-little-one** [comment]
really nice!
