### ISSUE TITLE
线的undo时发现key:'data'也是单独Command，导致线undo后首次显示上没有任何效果，再次操作界面才撤销线

### ISSUE THREAD

**Issue by LHMing01** [antvis/X6#1038]
线的undo时发现key:'data'也是单独Command，导致线undo后首次显示上没有任何效果，再次操作界面才撤销线。如果在beforeAddCommand过滤掉这种Command，会导致redo后线没有data以至业务上异常

**Comment by NewByVector** [comment]
将修改 data 和后面的操作放在一个事务中，这样就只有一个历史记录 https://x6.antv.vision/zh/docs/api/graph/graph/#startbatch
