### ISSUE TITLE
项目中未使用到Typescript，有纯React版本的demo源码吗？

### ISSUE THREAD

**Issue by MoonShadow-MapleLeaf** [antvis/X6#1039]
项目中未使用到Typescript，有纯React版本的demo源码吗？

**Comment by MoonShadow-MapleLeaf** [comment]
流程图demo的例子 有纯react编写的吗? 项目现在未使用Typescript，语法不兼容

**Comment by NewByVector** [comment]
把类型定义删除就可以了。

**Comment by MoonShadow-MapleLeaf** [comment]
> > 把类型定义删除就可以了。
> 
> 试过，但是我修改无法之后页面样式和功能出现了问题，估计是哪里修改的不对

经过几次的尝试，在react老项目中加入了typescript，改造了一些代码，目前功能是可以了
