### ISSUE TITLE
关于以拖拽的方式添加节点

### ISSUE THREAD

**Issue by happy-little-one** [antvis/X6#1044]
大部分交互应该都是以拖拽的方式添加节点的，我目前是用原生的draggable实现的，但这样要考虑的问题有很多，包括：

-  因为要以drop时的鼠标坐标为中心点要生成节点，这样就必须根据节点的类型和鼠标坐标来计算新增节点的x和y(clintX和clientY只是右上角点)。
- 要考虑画布是否拖动过。
- 要考虑画布是否缩放过。

请问官方有内置或推荐的做法吗？谢谢！

**Comment by NewByVector** [comment]
看下这个：https://x6.antv.vision/zh/docs/tutorial/basic/dnd

**Comment by happy-little-one** [comment]
sorry,看文档的时候漏掉了
