### ISSUE TITLE
锚点被节点遮挡，修改锚点index无效

### ISSUE THREAD

**Issue by social-uni** [antvis/X6#1046]
![lALPDh0cPcCzQ8zNAqnNBDk_1081_681](https://user-images.githubusercontent.com/14007972/120308464-b5aa7780-c306-11eb-969b-9131dcb724db.png)

不知道该如何处理了

```

  static getPortMarkup(isLeft: boolean) {
    return {
      tagName: 'circle',
      attrs: {
        // 定义是否可以连接
        magnet: 'true',
        r: 20,
        fill: 'black',
        // stroke: '#000',
        cx: isLeft ? 5 : -5,
        stroke: '#ffa940',
        strokeWidth: 2,
        zIndex: 1000
      },
      zIndex: 1000
    }
  }

ports.push({
          // id: item.alias + '-' + PortType.out,
          id: item.columnName + '-' + PortType.out,
          group: PortType.out,
          no: index,
          attrs: {
            circle: {
              style: {
                visibility: PortVisibleType.visible,
                zIndex: 1000
              },
              zIndex: 1000
            }
          },
          zIndex: 1000
        })


```

能设置zindex的地方都设置了

**Comment by NewByVector** [comment]
能否提供一下节点的 markup 以及实际 dom 的截图

**Comment by social-uni** [comment]
> 能否提供一下节点的 markup 以及实际 dom 的截图

[最简复现版本代码](https://gitee.com/social-uni/vue-yoyo-init.git)

您好，上面链接是我提供的最简单的复现版本的代码， npm install，npm run serve启动就行，  8080端口。

windows上锚点正常，mac上锚点被遮挡

windows上的截图
![image](https://user-images.githubusercontent.com/14007972/120579197-b0aa0d00-c459-11eb-8eb1-6d5846f71505.png)

**Comment by social-uni** [comment]
mac上的截图

![image](https://user-images.githubusercontent.com/14007972/120579237-c1f31980-c459-11eb-93ac-884c43aa2589.png)

**Comment by NewByVector** [comment]
看了下是因为这个问题：https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99
现在的解决方案是：看下是否不使用上面提到的样式

**Comment by social-uni** [comment]
> 看了下是因为这个问题：https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99
> 现在的解决方案是：看下是否不使用上面提到的样式

好的，不再使用position，解决了这个问题

**Comment by saint3347** [comment]
> 看了下是因为这个问题：https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99
> 现在的解决方案是：看下是否不使用上面提到的样式

![image](https://user-images.githubusercontent.com/7347133/126973580-f1724b1f-0de6-4143-bb97-36d612cc001a.png)
使用滤镜也会导致这种问题……
