### ISSUE TITLE
钉钉群满了

### ISSUE THREAD

**Issue by Aaronphy** [antvis/X6#1048]
求扩钉钉群

**Comment by NewByVector** [comment]
![image](https://user-images.githubusercontent.com/20186737/120435728-ae3fa880-c3b0-11eb-893b-f334fb4d6320.png)

**Comment by luminous6** [comment]
钉钉群又满了 ，那里还能交流啊

**Comment by NewByVector** [comment]
@luminous6  可以直接在这里提 issue

**Comment by evelope** [comment]
引入 @antv/x6-react-components  报错 是为什么呢？
![image](https://user-images.githubusercontent.com/34190465/147727721-e4199c10-d90b-4f07-9c1f-5eb135dfb585.png)

**Comment by evelope** [comment]
@NewByVector  引入 @antv/x6-react-components 报错 是为什么呢？

**Comment by evelope** [comment]
@NewByVector Toolbar 引入以后出这个
