### ISSUE TITLE
graph.fromJSON没有完全恢复节点间的父子关系

### ISSUE THREAD

**Issue by tiancihe** [antvis/X6#1053]
https://codesandbox.io/s/graphfromjson-does-not-recover-parent-children-relationship-c2i0x?file=/index.js

示例中调用 `graph.fromJSON` 恢复画布后，删除 `child1` 不会删除 `child2`

**Comment by tiancihe** [comment]
Update: 调用 `graph.removeCell` 方法才会触发这种情况，直接调用 `cell.remove` 方法不会

**Comment by tiancihe** [comment]
通过一步步的打点发现，在 cell.remove 方法中，[调用 parent.removeChild](https://github.com/antvis/X6/blob/9fb3a514c2d34dee61d1ee5acd68416ae5bd5cfa/packages/x6/src/model/cell.ts#L1060) 时，parent 的 children 不包含 child ，导致 getChildIndex 得到的值为 -1 ，导致[没有正常执行 removeChildAt 方法，从而再次调用 child 的 remove 方法](https://github.com/antvis/X6/blob/9fb3a514c2d34dee61d1ee5acd68416ae5bd5cfa/packages/x6/src/model/cell.ts#L1041)。

于是我在[调用 this.collection.remove 方法前](https://github.com/antvis/X6/blob/ac594cb122b4e868b1527f9339de88b13c22051e/packages/x6/src/model/model.ts#L305)想打个 log 看下 parent 此时的 children 值(cell.parent?.children)，结果竟然直接修复了这个 bug 。。。

再看 children 这个 get 方法发现 getChildren 竟然有副作用，修改了 _children 值。。。想问一下这块是为了修复什么问题而引入的么，目前看下来这块的逻辑是有问题的

**Comment by NewByVector** [comment]
这里需要把 cell.remove 方法重新设计一下，先把你这个 PR 关了
