### ISSUE TITLE
mac上使用饿了么table渲染，将锚点设置在table上，锚点会被背景色遮挡

### ISSUE THREAD

**Issue by social-uni** [antvis/X6#1054]
windows正常，

![image](https://user-images.githubusercontent.com/14007972/120577401-e0a3e100-c456-11eb-8e86-62463937a955.png)

mac不行

**Comment by social-uni** [comment]
![image](https://user-images.githubusercontent.com/14007972/120577919-8e16f480-c457-11eb-9e8e-90a93a918c16.png)

mac上的效果，我尽量提供一个 最简单浮现版本

**Comment by social-uni** [comment]
目前发现是el-table有个白色背景色导致的，可是我用一个空白div加个背景色，就不会被遮挡。还没找到问题所在 还在查找

**Comment by social-uni** [comment]
[最简复现版本代码](https://gitee.com/social-uni/vue-yoyo-init.git)

您好，上面链接是我提供的最简单的复现版本的代码， npm install，npm run serve启动就行，  8080端口。

windows上锚点正常，mac上锚点被遮挡

windows上的截图
![image](https://user-images.githubusercontent.com/14007972/120579197-b0aa0d00-c459-11eb-8eb1-6d5846f71505.png)


mac上的截图

![image](https://user-images.githubusercontent.com/14007972/120579237-c1f31980-c459-11eb-93ac-884c43aa2589.png)

**Comment by NewByVector** [comment]
这个看起来也是渲染问题：https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99
