### ISSUE TITLE
如何禁用节点拖动？

### ISSUE THREAD

**Issue by etfired1** [antvis/X6#1055]
查找API时，发现只有 Selection有禁止拖动。
但是不选中的节点如何禁止拖动？

**Comment by NewByVector** [comment]
```ts
new Graph({
  interacting: {
    nodeMovable: false
  }
})
```

https://x6.antv.vision/zh/docs/tutorial/basic/interacting#%E5%AE%9A%E5%88%B6%E4%BA%A4%E4%BA%92%E8%A1%8C%E4%B8%BA

**Comment by EmiyaYang** [comment]
@NewByVector 启用 showNodeSelectionBox 后，选中节点仍可拖动。
