### ISSUE TITLE
autoResize设置不生效问题

### ISSUE THREAD

**Issue by fadeds** [antvis/X6#1056]
![2](https://user-images.githubusercontent.com/27796945/120597313-764f6880-c477-11eb-8bd8-379227c0f8ee.png)
![1](https://user-images.githubusercontent.com/27796945/120597326-7a7b8600-c477-11eb-9a1f-c9e5efcb9b3f.png)
设置了autoResize，但是只有高度可以自适应，宽度不行

**Comment by NewByVector** [comment]
应该是是宽度能自适应，高度不行吧？

**Comment by fadeds** [comment]
是的，看你flex的方向

**Comment by javanoclaw** [comment]
> 应该是是宽度能自适应，高度不行吧？

是的，我也发现了

**Comment by mfc6027** [comment]
> 
似乎这个问题还没有解决

**Comment by LittleboyHarry** [comment]
调试了下源码，发现“高度锁死”的问题逻辑：

1. 对象初始化记录了宽高，并写死到 `container.style` 内
2. 浏览器大小重置，触发 `resize` 事件
3. 事件函数读取长宽大小，`container.offsetHeight` 总是读取到步骤 1 的值（ 由于布局使 `container.style.width` 失效，`offsetWidth` 不受影响）

临时解决方法：

```js
window.addEventListener('resize', () => {
    container.style.height = '';
});
```

@NewByVector reopen 下这个问题，请考虑怎样解锁？

**Comment by hyy215** [comment]
这问题有解决方案了吗？

**Comment by laobieyi** [comment]
我这里设置`autoResize: true` 然后配合 `display: flex`  使用发现并没有效果。
![image](https://user-images.githubusercontent.com/110290751/202134720-0e9bd42f-a03c-451c-9a03-15140ce96078.png)
![image](https://user-images.githubusercontent.com/110290751/202134721-e6dd2b87-0023-4ac8-80bb-4a6e654762bb.png)
