### ISSUE TITLE
支持节点通过连接桩连接时使用dagre布局

### ISSUE THREAD

**Issue by cxnobug** [antvis/X6#1058]
目前节点间直接连线时，dagre布局有效，但是通过连接桩连接时，使用dagre布局报错。

**Comment by NewByVector** [comment]
这个是 x6 数据结构和 layout 的数据结构之间存在差异导致的，可以参考下面 demo 来进行数据转换：
https://codesandbox.io/s/layout-data-qlkg8

**Comment by qianjujie** [comment]
建议文档上能放上这个关于连接桩的内容
