### ISSUE TITLE
autoResize 设为 false 时 scroller content 的大小设置行为不稳定

### ISSUE THREAD

**Issue by OpportunityLiu** [antvis/X6#1065]
### Expected Behavior
scroller content 的大小固定为 `scroller.pageWidth * scroller.pageHeight`

### Current Behavior

scroller content 的大小会初始化为 `scroller.width * scroller.height`
之后如果进行更新 `Scroller.update`，大小会更新为 `m*scroller.pageWidth * n*scroller.pageHeight`，与 `autoResize` 效果一致
（此更新可以通过 `Graph.resize` 触发）

### Possible Solution

当 autoResize 设为 false 时 scroller content 的大小固定为 `scroller.pageWidth * scroller.pageHeight`

此时 `Graph.resizePage` 和 `Graph.resizeGraph` 行为保持一致

### Steps To Reproduce

https://codesandbox.io/s/romantic-meadow-vwp7f?file=/src/app.tsx

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: 1.23.1
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by OpportunityLiu** [comment]
> 此时 `Graph.resizePage` 和 `Graph.resizeGraph` 行为保持一致

这里还是有问题啊，现在调用 `Graph.resizeGraph` 会调整大小，但是一触发 `Scroller.update()` 就又变回去了；
调用 `Graph.resizePage` 则是仅更新了 page break，需要触发一次  `Scroller.update()`  才能把画布调到 `pageWidth * pageHeight`，

**Comment by OpportunityLiu** [comment]
虽然说连续调用 Graph.resizePage 和 Graph.resizeGraph 也不是不行吧。。

**Comment by NewByVector** [comment]
确实还要问题，先还原：https://github.com/antvis/X6/pull/1120

**Comment by OpportunityLiu** [comment]
这个还有计划吗

**Comment by NewByVector** [comment]
有的

**Comment by OpportunityLiu** [comment]
要不先改回去吧。。。掉两次就掉两次吧。。。

**Comment by gguuoojun** [comment]
我就问下，这个bug这么久了怎么还没解决，试了下1.23.13版本的还是正常的，现在都1.25.1版本了，这个bug竟然还在

**Comment by gguuoojun** [comment]
看来下这个bug的版本，是解决了，但之后的版本又出现了，我明明设置了autosize为false，但调用Graph.resize触发了autoResize 效果的效果
