### ISSUE TITLE
同一个节点的多个端口如果group不一样但是group的position一样，多个端口会重合到一起

### ISSUE THREAD

**Issue by codingwalker** [antvis/X6#1068]
同一个节点Node有多个端口，如果端口的group不一样，但是group的position一样，比如都是top，显示的时候多个端口会重合到一起，看起来只有一个端口。

如果多个端口的group一样，则次bug不会复现，多个端口会在节点的上边显示，并且均匀分布

### Expected Behavior

group不一样的时候，多个端口也应该分开显示，均匀分布

### Current Behavior

group不一样但是group的position一样的时候，比如都是top，多个端口会重合到一起，看起来只有一个端口。

### Steps To Reproduce

修改样例代码：https://codesandbox.io/s/quirky-rain-1uz7e?file=/src/app.tsx
如下，可以复现问题

import React from "react";
import { Graph, Shape } from "@antv/x6";
import "./app.css";

Shape.Rect.define({
  shape: "my-rect",
  width: 180,
  height: 80,
  ports: {
    groups: {
      in: {
        position: "top",
        attrs: {
          circle: {
            r: 6,
            magnet: true,
            stroke: "#31d0c6",
            strokeWidth: 2,
            fill: "#fff"
          }
        }
      },
      in2: {
        position: "top",
        attrs: {
          circle: {
            r: 6,
            magnet: true,
            stroke: "#31d0c6",
            strokeWidth: 2,
            fill: "#fff"
          }
        }
      },
    }
  }
});

export default class Example extends React.Component {
  private container: HTMLDivElement;

  componentDidMount() {
    const graph = new Graph({
      container: this.container,
      height: 200,
      grid: {
        visible: true
      }
    });

    graph.addNode({
      x: 60,
      y: 50,
      shape: "my-rect",
      label: "In&Out Ports",
      ports: [
        {
          id: "port1",
          group: "in"
        },
        {
          id: "port2",
          group: "in2"
        },
      ]
    });
  }

  refContainer = (container: HTMLDivElement) => {
    this.container = container;
  };

  render() {
    return (
      <div className="app">
        <div ref={this.refContainer} />
      </div>
    );
  }
}

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: 1.23.3
- OS: macOS Sierra 10.15.7
- Browser: Microsoft Edge Version 88.0.705.81 (Official build) (64-bit)

**Comment by codingwalker** [comment]
怎么给关了，这不是一个bug吗？

**Comment by NewByVector** [comment]
这不是一个 bug，`position` 是以同一个 group 内进行位置计算的

**Comment by ma-x-x** [comment]
感觉应该根据position方向有几个port去计算位置，而不是以组，不过可以通过position:'abaolute', 自己去设置位置。
