### ISSUE TITLE
English Translation for Documentation

### ISSUE THREAD

**Issue by dynamic-modeller** [antvis/X6#1075]
Hi,

The software looks great, any chance of english translation occuring for the docs?

Or is that still some time away?

**Comment by NewByVector** [comment]
We have plans to do that, but it's going to take a while.

**Comment by causalmodeller** [comment]
thanks for letting me know, its a bummer because i need to start using something, and while your software is the best, unfortunately i can't understand the documentation
thanks

**Comment by lreading** [comment]
I've been using Chrome's translate feature.  It's not perfect, but it's usually enough to help me find what I need.
