### ISSUE TITLE
官网上的文档严重不全

### ISSUE THREAD

**Issue by whr2349** [antvis/X6#1076]
刚开始学习x6，发现文档严重不全啊
自定义的节点如何实例化？怎么调用？
graph实例上有一个createNode方法吗？
看别人的代码上面有这么一句话const c5=graph.createNode({shape:'flow-chart-image-rect1'})

**Comment by w345731923** [comment]
自定义节点参考这个demo : https://codesandbox.io/s/44k8q

**Comment by NewByVector** [comment]
具体的文档文问题提到这里：https://github.com/antvis/X6/issues/334

**Comment by lanlanzhang523** [comment]
确实,文档也太垃圾了
