### ISSUE TITLE
使用 X6 过程中遇到的兼容性问题

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#1077]
在这个 issue 下面记录 X6 的兼容性问题，提 issue 请提供下面环境信息，最好附上复现 [codesanbox](https://codesandbox.io/dashboard)
- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by yx8899** [comment]
移动端,点击旋转按钮,报错,以下是重现
https://codesandbox.io/embed/vue-shape-forked-9cojh?codemirror=1
x6: [e.g. 1.23.1]
OS: [e.g. win10]
Browser: [e.g. chrome 86.0.4240.198]

**Comment by neverToStop** [comment]
移动端,节点连接桩创建线段 选中箭头无法拖拽位置
http://114.115.130.99/process/ap/exam?id=120&name=%E5%9B%BE%E5%BD%A2%E6%B5%8B%E8%AF%95
x6: [e.g. 1.21.5]
OS: [e.g. win10]
Browser: [e.g. chrome 86.0.4240.198]

**Comment by hqzh** [comment]
可以发现事件系统都是针对PC端的鼠标的。你这移动端整这个符合产品体验嘛

**Comment by hqzh** [comment]
https://github.com/antvis/X6/issues/1078

**Comment by flyfly6** [comment]
Safari 浏览器中 vue 组件相关的兼容性问题：

复现 [codesandbox](https://codesandbox.io/s/vue-shape-forked-k4l78)

1. input 组件定位问题
ChangeSize 组件中的输入框位置不对，需要将组件外层 container 设置为 position: fixed 才能正确定位
2. foreignObject 无法缩放
按住 command 键通过滚轮缩放画布时，foreignObject 中的 vue 组件无法缩放， 包括导出的 svg 图在 img 标签中也无法正常缩放，可能与这个 [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=23113)，不知能否兼容
3. input 输入框输入导致画布移动
在 input 中输入文本当文本超过 input 宽度时，画布会向右边移动

- x6: 1.12.14
- OS: macOS Big Sur 11.4
- Browser: Safari 版本14.1.1 (16611.2.7.1.4)

**Comment by NewByVector** [comment]
@yx8899 如果连在空白处时可以拖拽的，如果连在其他元素上，需要通过 `source-arrowhead`工具来修改位置

**Comment by NewByVector** [comment]
@flyfly6 这几个问题与 safari 渲染有关，暂时还没有想到办法修复

**Comment by NewByVector** [comment]
@yx8899 在这个 https://github.com/antvis/X6/pull/1387 PR 中修复
