### ISSUE TITLE
移动端 图形生成线段无法拖拽修改位置

### ISSUE THREAD

**Issue by neverToStop** [antvis/X6#1078]
### Steps To Reproduce

1.
2.
3.

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [1.21.5]
- OS: [pad microsoft]
- Browser: [114.115.130.99/]

**Comment by hqzh** [comment]
https://github.com/antvis/X6/issues/1077

**Comment by NewByVector** [comment]
移动端兼容性问题统一提到这里：https://github.com/antvis/X6/issues/1077
