### ISSUE TITLE
多层嵌套父子关系时，移动子节点会导致父子关系错乱

### ISSUE THREAD

**Issue by situ-wang** [antvis/X6#1081]
### Expected Behavior
移动'child1'节点，打印结果一直父节点为'parent'

### Current Behavior
第一次初始化及移动时，打印为'parent’，后面再次移动时child1的子节点变为'grandParent'

### Steps To Reproduce

1. 点击移动child1
2. 查看打印结果是否为parent

![parentNodeBug](https://user-images.githubusercontent.com/84897913/121462263-ed8a7c80-c9e2-11eb-916f-146aabb3cd6a.gif)

codesandbox：
https://codesandbox.io/s/vigorous-mestorf-29cqs?file=/src/app.tsx

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

antv/x6: latest,
macos:bigsur,
chrome: chorme 91.xx

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
这个不是问题，移动 child1 后，你观察高亮的节点，其实是最外层的 grandpa 节点，代表着此时 child1 已经成为了 grandpa 的子节点
