### ISSUE TITLE
设置分组并开启minimap，收起展开分组导致程序block卡死

### ISSUE THREAD

**Issue by situ-wang** [antvis/X6#1086]
### Expected Behavior
展开收起分组正常响应，minimap上同步显示内容

### Current Behavior
收起分组后展开，程序挂掉卡死，但是控制台无报错

### Steps To Reproduce

1. 点击组 a 的收起按钮
2. 点击组 a 的展开按钮
codesandbox：
https://codesandbox.io/s/trusting-field-izgzw

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Additional Context

可能是edge的visible有些问题，不能正确的显示和隐藏

### Your Environment

- x6: @latest
- OS: bigsur
- Browser: Chrome 91

**Comment by Ansel** [comment]
根据配置文档 https://x6.antv.vision/zh/docs/tutorial/basic/minimap#graphoptions 在graphOptions中配置不渲染edge就暂时解决了。

**Comment by Ansel** [comment]
根据配置文档 https://x6.antv.vision/zh/docs/tutorial/basic/minimap#graphoptions 在graphOptions中配置不渲染edge就暂时解决了。
