### ISSUE TITLE
调试用源文件缺失

### ISSUE THREAD

**Issue by OpportunityLiu** [antvis/X6#1094]
### Expected Behavior

正确加载 source map
### Current Behavior

```
WARNING in ./node_modules/@antv/x6/es/style/raw.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '***\node_modules\@antv\x6\src\style\raw.ts' file: Error: ENOENT: no such file or directory, open '***\node_modules\@antv\x6\src\style\raw.ts'
```

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Additional Context

related: #867 #877  https://github.com/antvis/X6/commit/b2f48fcb6a1d8472381fe5fe1a66556a6d6f53dd

### Your Environment

- x6: 1.23.8
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@OpportunityLiu 正在修复中，上次把 `raw.ts` 这个自动生成的文件加入到了 `.gitignore` 中，导致 npm 发布的时候文件缺失。
