### ISSUE TITLE
拖拽节点改变其大小

### ISSUE THREAD

**Issue by frienkiss** [antvis/X6#1109]
请问可以增加个功能，拖拽节点边角，来控制节点的大小吗

**Comment by bubkoo** [comment]
@frienkiss 看看文档 https://x6.antv.vision/zh/docs/tutorial/basic/interacting

**Comment by iceytea** [comment]
Graph 实例上有 resizing 配置，设置为 true 时，支持节点大小缩放

**Comment by GrubbyHunter** [comment]
實際上我是希望添加到画布上的一些节点能拖动改变大小，比如group节点之类，一些节点禁止拖动改变大小，有办法实现吗
