### ISSUE TITLE
使用X6渲染react组件，画布上执行graph.removeEdge(id)、graph.removeNode(id)，对应的react组件没有执行到销毁的方法（componentWillUnmount）

### ISSUE THREAD

**Issue by onlyOneStone** [antvis/X6#1117]
### Current Behavior
1、edge上的label使用react组件来渲染的，目前删除边的时候，执行了graph.removeEdge(id),但label组件没有执行到销毁的方法（componentWillUnmount）
2、node使用react组件来渲染的，目前删除节点的时候，执行了graph.removeNode(id),但react组件没有执行到销毁的方法（componentWillUnmount）

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- "@antv/x6": "^1.21.7",
- "@antv/x6-react-shape": "^1.4.1",
- OS: [e.g. macOS Sierra 11.1]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by Ansel** [comment]
Vue组件也是一样。。。。只好自己再去手动销毁一下。。。

**Comment by onlyOneStone** [comment]
> @onlyOneStone
> 
> 分支[fix/issue-1117](https://github.com/antvis/X6/tree/fix/issue-1117)是为此问题创建的。我们将调查此事并尽快回复您。
> 
> 感谢反馈问题或提供改进建议，我们创建了[修复/issue-1117](https://github.com/antvis/X6/tree/fix/issue-1117)分支来处理问题，你可以继续跟进这个问题的解决方案。
目前"@antv/x6-react-shape": "^1.4.4"上，删除react节点有执行componentWillUnmount，但是删除边时，边上的label也是react组件没有执行到componentWillUnmount
