### ISSUE TITLE
Graph going blank randomly after a while 

### ISSUE THREAD

**Issue by nikhil0295** [antvis/X6#1136]
Graph goes blank after a while randomly .  Console logs show the following error .

<img width="481" alt="Screenshot 2021-06-25 at 1 39 41 PM" src="https://user-images.githubusercontent.com/7566963/123435502-449b6e80-d5eb-11eb-9fe0-6e85ad145cee.png">

We currently have async rendering setting on for the graph .

### Expected Behavior

Graph shouldn't show any errors or handle the rendering by itself .

### Current Behavior

Graph goes blank , and user needs to refresh to load objects .

### Possible Solution

Is this a problem with async rendering ? Unsure on the fix as it seems native to the library.

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>
<img width="481" alt="Screenshot 2021-06-25 at 1 39 41 PM" src="https://user-images.githubusercontent.com/7566963/123435502-449b6e80-d5eb-11eb-9fe0-6e85ad145cee.png">
```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: ^1.21.5
- OS:  Not OS specific
- Browser: All browsers

**Comment by NewByVector** [comment]
Please provide a demo that can be reproduced.

**Comment by NewByVector** [comment]
无法重现，先关闭。
