### ISSUE TITLE
导出png的dataUri问题

### ISSUE THREAD

**Issue by DarrenYing** [antvis/X6#1144]
在Vue的BeforeDestroy生命周期钩子函数里调用graph.toPNG，获得的dataUri的图片是空白的，如果想在离开画布页面的时候，为当前画布生成png预览图，有什么办法吗？十分感谢。

**Comment by NewByVector** [comment]
这个需要你代码保证 `toPNG` 的时候画布内容始终存在。

**Comment by Val-istar-Guo** [comment]
我也遇到相同问题，虽然是在React中使用，但是框架应该对此没有影响。
导出PNG时，ICONFONT都丢失了
