### ISSUE TITLE
全局配置interacting.edgeMovable 设置为false之后，选中Edge仍然可以拖拽

### ISSUE THREAD

**Issue by chorin959** [antvis/X6#1148]
### Expected Behavior

```
全局配置interacting.edgeMovable（nodeMovable） 设置为false或者return false，选中后应该不能被拖拽
```

### Current Behavior

```
全局配置interacting.edgeMovable （nodeMovable）设置为false或者return false，选中后仍然可以被拖拽改变位置
```

### Possible Solution

暂无

### Steps To Reproduce

```
Step1： 全局配置

{
    interacting:{
      edgeMovable({cell}){
          return false;
      },
      nodeMovable(){
          return false
      }
    },
    selecting: {
      enabled: true,
      movable: true,
      showNodeSelectionBox: true,
      showEdgeSelectionBox: true,
    }
}

Step2：添加Edge/Node

Step3：选中Edge/Node

Step4：拖动Edge/Node

```

</p></details>

### Additional Context
codesanbox：https://codesandbox.io/s/c52j5?file=/src/components/Demo.vue

### Your Environment

- x6: [e.g. 1.24.4]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
我在本地测试，设置 edgeMovable: false 后，边无法被移动，你这边方便提供一个可以复现的 codesanbox?

**Comment by chorin959** [comment]
抱歉，配置漏了个细节。

**Comment by chorin959** [comment]
上面问题描述的配置漏了细节，需要这样才能复现：      
```
 selecting: {
   enabled: true,
   movable: true,  
  //以下设置为true之后，选中节点或边可移动
   showNodeSelectionBox: true,
   showEdgeSelectionBox: true,
},
```
详细DEMO见codesanbox地址：https://codesandbox.io/s/great-wildflower-c52j5?file=/src/components/Demo.vue:615-805

**Comment by chorin959** [comment]
@NewByVector

**Comment by NewByVector** [comment]
movable 一起设置成 false 即可
