### ISSUE TITLE
获取前序节点出错

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#1149]
### Current Behavior

复现 demo：https://codesandbox.io/s/predecessors-forked-xvq6z?file=/src/app.tsx
获取前序节点是少考虑了一个节点

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by blakeyoungc** [comment]
请问这个问题解决了吗
