### ISSUE TITLE
使用dagre布局，如果节点的width和height都不一样的话就会重叠错乱

### ISSUE THREAD

**Issue by Superkimi** [antvis/X6#1152]
在使用dagre布局时，传入的nodes的width和height都不相同时。最后布局出来的会有重叠错乱。求解

**Comment by NewByVector** [comment]
传入 `nodeSize` 属性: `nodeSize: [width, height]`

**Comment by Superkimi** [comment]
我的每个node size都不一样。nodeSize在实例化的时候传入。怎么传入不同的size？> 传入 `nodeSize` 属性: `nodeSize: [width, height]`

**Comment by Superkimi** [comment]
我的layout版本"@antv/layout": "^0.1.15",
按照如下方式引入使用
import { DagreLayout } from '@antv/layout'
const dagreLayout = new DagreLayout({
    rankdir: 'TB',
    ranksep: 50,
    nodesep: 50,
    controlPoints: true,
    nodeSize: [200, 200],
  })
  dagreLayout.layout(this.groupData)


布局的效果依然是有重叠的。看了源码dagre.js文件中如果传入nodeSize为数组则是以固定的size去渲染。如果传入的是function则会获取每个node的size来渲染，但是此时仍然会有重叠。

**Comment by NewByVector** [comment]
不好意思，理解错误。不全局设置 `nodeSize`，在每一个节点数据中增加 `size: [width, height]` 属性。

**Comment by Superkimi** [comment]
设置size也是一样会重叠的，我看了下@antv/layout内部使用的dagre.graphlib这个库，直接使用这个库也是有这个问题，不同size的node他布局也会有重叠。

**Comment by NewByVector** [comment]
能否提供一个可以复现的 codesanbox 看一下

**Comment by Superkimi** [comment]
https://codesandbox.io/s/serene-black-k3x30
我用的是x6图形案例里的组织结构里自动布局的示例写了一个。麻烦帮忙看下

**Comment by Superkimi** [comment]
我看了G6的TreeGraph中compactBox layout也是有同样的问题，如果节点大小不一样，会有重叠

**Comment by Superkimi** [comment]
这个修复不了了吗？

**Comment by NewByVector** [comment]
@Superkimi  看下这个呢 https://codesandbox.io/s/happy-star-ued5f?file=/src/App.vue

**Comment by Superkimi** [comment]
还是不行，我自己重写了布局
