### ISSUE TITLE
给Edge加上tool：'vertices', 'segments' 以后，捕捉不到edge:mouseup事件

### ISSUE THREAD

**Issue by rxdrag** [antvis/X6#1156]
现象如标题所示，临时我用edge:mouseleave变通代替， 希望以后能够改进一下把这个事件暴露出来。或者提供edge：change跟edege:changed两个事件，类似Node的resize跟resized事件。
因为项目特殊，需要自己记录操作记录，如果比提供类似这样的事件，会产生大量的只有细微差别的历史记录。
整体X6的使用体验非常棒，感谢开发者团队提供这么好的工具！
![image](https://user-images.githubusercontent.com/18096128/124592930-9a480480-de90-11eb-89bf-e8dda14d3f47.png)

**Comment by NewByVector** [comment]
这两个工具都有一个 `stopPropagation` 配置，设置为 `false` 就会触发 `edge:mouseup` 事件：
```ts
graph.addEdge({
  source,
  target,
  tools: [
    {
      name: 'vertices',
      args: {
        stopPropagation: false
      }
    }
  ]
})
```
