### ISSUE TITLE
在使用dagre布局时，节点对齐方式怎么居中？看源码和G6可以传入 align: undefined，但是不生效

### ISSUE THREAD

**Issue by xielingdm** [antvis/X6#1160]
![image](https://user-images.githubusercontent.com/23383297/124877142-63433180-dffd-11eb-82e9-7f1068588343.png)

期望是节点居中而不是靠左

**Comment by NewByVector** [comment]
这个是因为布局计算出来的 (x, y) 是节点中心位置，所以在布局计算之后，需要将 (x, y) 分别减去节点宽高的一般。这个功能我们也有规划在在布局算法层面兼容处理掉。
