### ISSUE TITLE
x6-vue-shape  support vue@3.1.x

### ISSUE THREAD

**Issue by elvisqi** [antvis/X6#1165]
https://github.com/antvis/X6/blob/master/packages/x6-vue-shape/package.json

```
"peerDependencies": {
    "@antv/x6": ">=1.0.0",
    "@vue/composition-api": "^1.0.0-rc.6",
    "vue": "^2.6.12 || ^3.0.0"
},
```

### Expected Behavior

```
"peerDependencies": {
    "@antv/x6": ">=1.0.0",
    "@vue/composition-api": "^1.0.0-rc.6",
    "vue": "^2.6.12 || ^3.1.0"
},
```

**Comment by elvisqi** [comment]
npm ERR! Found: vue@3.0.11
npm ERR! node_modules/vue
npm ERR!   vue@"3.0.11" from the root project
npm ERR!   peer vue@"^2.6.12 || ^3.0.0" from @antv/x6-vue-shape@1.2.8
npm ERR!   node_modules/@antv/x6-vue-shape
npm ERR!     @antv/x6-vue-shape@"1.2.8" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.0-rc.13
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.0.0-rc.6" from @antv/x6-vue-shape@1.2.8
npm ERR!   node_modules/@antv/x6-vue-shape
npm ERR!     @antv/x6-vue-shape@"1.2.8" from the root project

**Comment by NewByVector** [comment]
在 vue 3.x 中使用还有 bug，https://github.com/antvis/X6/issues/968。
