### ISSUE TITLE
drag and drop custom node problem in safari browser

### ISSUE THREAD

**Issue by BARMPlus** [antvis/X6#1166]
### Expected Behavior
In the safari browser, dragging and dropping custom nodes is normal。

### Current Behavior
Drag and drop the custom node in the safari browser, the node appears shaded, and the text disappears。

### Steps To Reproduce
1. Open Safari browser
2. Navigation bar input "https://x6.antv.vision/apps/dag/"

### Your Environment

- Browser: [safari 14.0.3]

**Comment by BARMPlus** [comment]
can he keep on

**Comment by mayrestinpeace** [comment]
I too am facing the same issue. 
Can someone please look into this issue ?

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/pull/1365  原因参考：https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99
