### ISSUE TITLE
 layoutClass is not a constructor

### ISSUE THREAD

**Issue by J-maxwell** [antvis/X6#1175]
2 | export class Layout {
  3 |     constructor(options) {
  4 |         const layoutClass = getLayoutByName(options.type);
> 5 |         this.layoutInstance = new layoutClass(options);
  6 |     }
  7 |     layout(data) {
  8 |         return this.layoutInstance.layout(data);

**Comment by NewByVector** [comment]
正确打开方式 https://x6.antv.vision/zh/docs/tutorial/advanced/layout
