### ISSUE TITLE
调用自定义节点的  `updateData` 方法没有更新节点

### ISSUE THREAD

**Issue by javanoclaw** [antvis/X6#1176]
### Expected Behavior
使用自定义节点且调用 `updateData` 方法应该更新节点
### Current Behavior

使用自定义节点且调用 `updateData` 方法没有更新节点

### Steps To Reproduce

https://codesandbox.io/s/jovial-hypatia-1lc2i?file=/src/app.tsx:319-328

### Additional Context
定义如下节点: 
```js
import { Graph, Node, ObjectExt } from "@antv/x6";
class CustomNode extends Node {}

CustomNode.config({
  width: 100,
  height: 100,
  markup: [
    {
      tagName: "rect",
      selector: "body"
    },
    {
      tagName: "text",
      selector: "title"
    }
  ],
  propHooks(metadata) {
    const { data, ...others } = metadata;
    ObjectExt.setByPath(others, "attrs/title/text", data?.name);
    return { data, ...others };
  }
});
Graph.registerNode("custom-node", CustomNode);
```

通过如下方式更新节点数据:
```js
graph.getNodes.forEach((node)=>{
  node.updateData({name:Math.random()});
});
```

### Your Environment

codesandbox.io

**Comment by EmiyaYang** [comment]
我也遇到了，这个没人关注吗？ @NewByVector

**Comment by zzjjbbaa** [comment]
me too 。。。。。

**Comment by NewByVector** [comment]
@EmiyaYang @zzjjbbaa 有复现的 demo 链接吗，可以新建一个 issue。

**Comment by zzjjbbaa** [comment]
[我创建了一个复现，App.tsx中有问题说明，辛苦帮忙看下](https://codesandbox.io/s/thirsty-sound-r844nl?file=/src/App.tsx) @NewByVector @EmiyaYang @javanoclaw

**Comment by quicklyfast** [comment]
```
//propHooks从名字看处理prop的，需要将node.updateData({name:Math.random()}); 写成
node.setProp({name:Math.random()， id: node.id});  # 之所以要传递id属性，是因为x6存在一个bug
```
具体处理流程看[/packages/x6/src/model/cell.ts](https://github.com/antvis/X6/blob/7687cb201a7b2be38b67524f99d4226b9e3e30d1/packages/x6/src/model/cell.ts)

![image](https://user-images.githubusercontent.com/69248473/186396280-de1a8759-4594-4f90-a3b9-abea9cbac7cf.png)

**Comment by psc0606** [comment]
这个问题竟然还没人修复，真奇葩

**Comment by alienzhangyw** [comment]
propHooks的metadata里解构出来的data老是undefined，没法通过这种方式改变属性

**Comment by superchenwb** [comment]
一年半了，这个bug依然存在

**Comment by notbucai** [comment]
怎么还有这个问题

**Comment by notbucai** [comment]
change:data 也没用
