### ISSUE TITLE
节点多时卡顿

### ISSUE THREAD

**Issue by frienkiss** [antvis/X6#1177]
graph中注册了多个vue节点，离开页面时也全部销毁了，但浏览器memory中依然存在graph中的节点信息，导致页面极为卡顿

**Comment by NewByVector** [comment]
是执行 `graph.dispose()` 方法销毁画布的吗

**Comment by frienkiss** [comment]
> 是执行 `graph.dispose()` 方法销毁画布的吗
对的，并且又手动销毁了注册的所有vue实例

**Comment by NewByVector** [comment]
这个问题在新版本中已经修复了，节点销毁的时候同时删除 vue 实例
