### ISSUE TITLE
使用batchupdate进行批量记录多层节点折叠无效

### ISSUE THREAD

**Issue by butterfly2sea** [antvis/X6#1180]
使用batchupdate，记录多层节点的折叠，无法直接undo到未折叠状态
### Expected Behavior
折叠后，执行undo

可以恢复到每层都未折叠状态

### Current Behavior

每次undo只能恢复一次操作，貌似batchupdate失效

### Steps To Reproduce

https://codesandbox.io/s/billowing-darkness-ycp8i
1. 折叠最外层的父节点
2. undo
<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [1.24.5]
- OS: [windows 10]
- Browser: [chrome 91.0]

**Comment by NewByVector** [comment]
在添加节点的配置中增加 `visible: true` 即可解决上面问题
