### ISSUE TITLE
x6的平移好像受滚动影响表现异常

### ISSUE THREAD

**Issue by SingleShadow** [antvis/X6#1183]
### Expected Behavior
按住shift向左平移后，当前视图节点c在中间，选中节点c开始移动，c应该以当前位置开始正常移动

### Current Behavior
按住shift向左平移后，当前视图节点c在中间，选中节点c开始移动，c的位置异常显示在a、b附近，审查元素发现是类名为x6-graph-svg-viewport的g元素的属性transform好像是先被重置为了matrix(1,0,0,1,0,0)

### Steps To Reproduce

https://codesandbox.io/s/v56ek?file=/index.ts

import { Graph } from '@antv/x6'

const container = document.getElementById('container')
const graph = new Graph({
  container: container,
  resizing: true,
  background: {
    color: '#f5f5f5',
  },
  grid: {
    visible: true,
  },
  scroller: {
    enabled: true,
    // pageVisible: true,
    pageBreak: true,
    // pannable: true,
  },
  mousewheel: {
    enabled: true,
    modifiers: ['ctrl', 'meta'],
    minScale: 0.5,
    maxScale: 2,
  },
  panning: {
    enabled: true,
    modifiers: 'shift',
  },
})

const rect = graph.addNode({
  shape: 'rect',
  x: 300,
  y: 300,
  width: 90,
  height: 60,
  attrs: {
    body: {
      fill: '#ff9c6e',
      stroke: '#ff7a45',
    },
    label: {
      text: 'A',
    },
  },
})

rect.on('removed', () => {
  console.log('rect was removed')
})

const circle = graph.addNode({
  shape: 'circle',
  x: 400,
  y: 400,
  width: 40,
  height: 40,
  attrs: {
    body: {
      fill: '#d3f261',
      stroke: '#bae637',
    },
    label: {
      text: 'B',
    },
  },
})

graph.addNode({
  shape: 'circle',
  x: 600,
  y: 400,
  width: 40,
  height: 40,
  attrs: {
    body: {
      fill: '#d3f261',
      stroke: '#bae637',
    },
    label: {
      text: 'C',
    },
  },
})

graph.addEdge({
  source: rect,
  target: circle,
})

graph.center()

1. 初始化画布的时候在scroller中不设置pannable
2. 设置panning为true，并且modifiers为shift
3. (ps.不在scroller中开启pannable是因为会跟框选的行为有冲突)

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
scroller 和 panning 是两种模式画布，不要一起使用
