### ISSUE TITLE
选中多个节点并移动它们的位置，不会触发各个节点的node:moved事件

### ISSUE THREAD

**Issue by DarrenYing** [antvis/X6#1187]
选中多个节点并移动它们的位置，不会触发各个节点的node:moved事件
### Expected Behavior

当选中多个节点并一起移动时，应该触发各个节点的node:moved事件
### Current Behavior

实际上没有触发任一节点的node:moved事件
### Steps To Reproduce

1. 选中多个节点
2. 移动它们
3. 监听node:moved事件

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: 1.13.1
- OS: Windows10 专业版
- Browser: Microsoft Edge  91.0.864.67

**Comment by NewByVector** [comment]
是不是开启了 `showNodeSelectionBox` 属性

**Comment by DarrenYing** [comment]
对，开了，请问这个会冲突吗？

**Comment by iceytea** [comment]
https://github.com/antvis/X6/issues/1159#issuecomment-877631157

**Comment by DarrenYing** [comment]
> [#1159 (comment)](https://github.com/antvis/X6/issues/1159#issuecomment-877631157)

谢谢你。
但我试了下，在创建graph时，在selecting里加了pointerEvents这个配置，如果是框选状态，仍然不会触发node:moved事件；
我又试了把showNodeSelectionBox改为false，多选节点状态移动就能触发node:moved事件了，但是这不符合我的需求。
如果您那加pointerEvents这个配置能成功的话，可能是我的x6版本问题？就是官方文档上也没找到这个配置项。

**Comment by iceytea** [comment]
> > [#1159 (comment)](https://github.com/antvis/X6/issues/1159#issuecomment-877631157)
> 
> 谢谢你。
> 但我试了下，在创建graph时，在selecting里加了pointerEvents这个配置，如果是框选状态，仍然不会触发node:moved事件；
> 我又试了把showNodeSelectionBox改为false，多选节点状态移动就能触发node:moved事件了，但是这不符合我的需求。
> 如果您那加pointerEvents这个配置能成功的话，可能是我的x6版本问题？就是官方文档上也没找到这个配置项。

我查了下，官方文档确实没有。
我使用的版本是 "@antv/x6": "^1.24.5"。这个版本配置 pointerEvents 两种确实效果不同

**Comment by DarrenYing** [comment]
> > > [#1159 (comment)](https://github.com/antvis/X6/issues/1159#issuecomment-877631157)
> > 
> > 
> > 谢谢你。
> > 但我试了下，在创建graph时，在selecting里加了pointerEvents这个配置，如果是框选状态，仍然不会触发node:moved事件；
> > 我又试了把showNodeSelectionBox改为false，多选节点状态移动就能触发node:moved事件了，但是这不符合我的需求。
> > 如果您那加pointerEvents这个配置能成功的话，可能是我的x6版本问题？就是官方文档上也没找到这个配置项。
> 
> 我查了下，官方文档确实没有。
> 我使用的版本是 "@antv/x6": "^1.24.5"。这个版本配置 pointerEvents 两种确实效果不同

我把'@antv/x6'版本更新到了^1.24.5，还是没效果 ;w;
selecting: {
    enabled: true,
    multiple: true,                     
    rubberband: true,                   
    modifiers: ['shift'],              
    movable: true,
    showNodeSelectionBox: true,        
    showEdgeSelectionBox: true,       
    pointerEvents: 'none' | 'auto',
},
请问是我的配置有问题吗？

**Comment by iceytea** [comment]
> > > > [#1159 (comment)](https://github.com/antvis/X6/issues/1159#issuecomment-877631157)
> > > 
> > > 
> > > 谢谢你。
> > > 但我试了下，在创建graph时，在selecting里加了pointerEvents这个配置，如果是框选状态，仍然不会触发node:moved事件；
> > > 我又试了把showNodeSelectionBox改为false，多选节点状态移动就能触发node:moved事件了，但是这不符合我的需求。
> > > 如果您那加pointerEvents这个配置能成功的话，可能是我的x6版本问题？就是官方文档上也没找到这个配置项。
> > 
> > 
> > 我查了下，官方文档确实没有。
> > 我使用的版本是 "@antv/x6": "^1.24.5"。这个版本配置 pointerEvents 两种确实效果不同
> 
> 我把'@antv/x6'版本更新到了^1.24.5，还是没效果 ;w;
> selecting: {
> enabled: true,
> multiple: true,
> rubberband: true,
> modifiers: ['shift'],
> movable: true,
> showNodeSelectionBox: true,
> showEdgeSelectionBox: true,
> pointerEvents: 'none' | 'auto',
> },
> 请问是我的配置有问题吗？

```js
selecting: {
    enabled: true,
    multiple: true,
    rubberband: true,
    modifiers: ['shift'],
    movable: true,
    showNodeSelectionBox: true,
    showEdgeSelectionBox: true,
    pointerEvents: 'none',
},
```

官方库默认是 auto，设置成 none 试试

**Comment by DarrenYing** [comment]
> > > > > [#1159 (comment)](https://github.com/antvis/X6/issues/1159#issuecomment-877631157)
> > > > 
> > > > 
> > > > 谢谢你。
> > > > 但我试了下，在创建graph时，在selecting里加了pointerEvents这个配置，如果是框选状态，仍然不会触发node:moved事件；
> > > > 我又试了把showNodeSelectionBox改为false，多选节点状态移动就能触发node:moved事件了，但是这不符合我的需求。
> > > > 如果您那加pointerEvents这个配置能成功的话，可能是我的x6版本问题？就是官方文档上也没找到这个配置项。
> > > 
> > > 
> > > 我查了下，官方文档确实没有。
> > > 我使用的版本是 "@antv/x6": "^1.24.5"。这个版本配置 pointerEvents 两种确实效果不同
> > 
> > 
> > 我把'@antv/x6'版本更新到了^1.24.5，还是没效果 ;w;
> > selecting: {
> > enabled: true,
> > multiple: true,
> > rubberband: true,
> > modifiers: ['shift'],
> > movable: true,
> > showNodeSelectionBox: true,
> > showEdgeSelectionBox: true,
> > pointerEvents: 'none' | 'auto',
> > },
> > 请问是我的配置有问题吗？
> 
> ```js
> selecting: {
>     enabled: true,
>     multiple: true,
>     rubberband: true,
>     modifiers: ['shift'],
>     movable: true,
>     showNodeSelectionBox: true,
>     showEdgeSelectionBox: true,
>     pointerEvents: 'none',
> },
> ```
> 
> 官方库默认是 auto，设置成 none 试试

谢谢你！可以触发了！
