### ISSUE TITLE
selection 中配置 pointerEvents 为 none，会导致 movable 为 true 的效果消失

### ISSUE THREAD

**Issue by iceytea** [antvis/X6#1188]
### Expected Behavior

说实话，我也不知道该达成什么效果。如果说按照 pointerEvents 为 none 的含义，选中 selection 的框，必然是无法有响应的。

### Current Behavior

新版本中，在 `selection` 中增加了配置：
```ts
{
  pointerEvents?: 'none' | 'auto'
}
```
可以既不影响节点事件，又可以多选移动。 @ue360 @SingleShadow

_Originally posted by @NewByVector in https://github.com/antvis/X6/issues/1159#issuecomment-877631157_

这个选项会导致 movable 为 true 的效果消失
https://x6.antv.vision/zh/docs/api/graph/selecting#movable

### Steps To Reproduce

selecting 配置如下：
```
  selecting: {
        enabled: false,
        multiple: true,
        rubberband: true,
        rubberNode: true,
        rubberEdge: true,
        showNodeSelectionBox: true,
        showEdgeSelectionBox: true,
        pointerEvents: "none",
      },
```

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0] 1.24.5
- OS: [e.g. macOS Sierra 10.12.3] -
- Browser: [e.g. chrome 78.0.3904.108] - chrome 78.0.3904.108

**Comment by NewByVector** [comment]
现在的现象是如果设置 `pointerEvents` 为 `none`, 默认是多选一起移动的效果。你这里是不是有问题？

**Comment by iceytea** [comment]
可能你说的对……我这边暂时没法给出一个可以复现的 demo。先关掉这个讨论，等发现问题时再打开吧……
