### ISSUE TITLE
Grindlayout 当传入的节点数量为 0 和 1时，gridLayout.layout 返回的model为undefined

### ISSUE THREAD

**Issue by yuguangde** [antvis/X6#1193]
### Expected Behavior

gridLayout.layout 返回正常的 model 对象

### Current Behavior

gridLayout.layout 返回的 model 为 undefined

### Steps To Reproduce
https://codesandbox.io/s/loving-moore-2nlfh
1.  gridlayout 接受到的nodes数量为 0 或者 1

**Comment by NewByVector** [comment]
已经提 PR 了：https://github.com/antvis/layout/pull/39

**Comment by NewByVector** [comment]
问题已经修复，更新 layout 版本到 0.1.18
