### ISSUE TITLE
1.23.8版本之后，node.addChild方法只能添加进最后一个child，其余的都会被覆盖。

### ISSUE THREAD

**Issue by Superkimi** [antvis/X6#1195]
1.23.8版本之后，node.addChild方法只能添加进最后一个child，其余的都会被覆盖。1.23.8以及之前的没问题

**Comment by NewByVector** [comment]
我验证了一下没有问题，这个是我的 demo：https://codesandbox.io/s/add-child-wi0df

**Comment by Superkimi** [comment]
我是new Node创建的节点，具体例子见下面，只会添加进去最后一个
https://codesandbox.io/s/add-child-forked-4s5q0?file=/src/app.tsx

**Comment by Superkimi** [comment]
有进展吗？

**Comment by bubkoo** [comment]
![image](https://user-images.githubusercontent.com/6045824/129298506-322451b4-ca6d-4b4a-9e21-00768a6a0b09.png)

@NewByVector 确实有问题。

**Comment by Superkimi** [comment]
想问下新版本有修复吗

**Comment by YanYuanFE** [comment]
这个问题修复了吗？我在1.30版本也遇到了

**Comment by NewByVector** [comment]
@YanYuanFE 使用 addNode 方法不会有问题。

**Comment by gitLPS** [comment]
"需要先把父节点 加到 gragh中 , addChild 的就正常了,这句话说的非常好"，我已经按照这个方法解决了，如果等addChild后再graph.addNode的话，会造成覆盖，但是先graph.addNode后，再addChild 就没问题
