### ISSUE TITLE
版本升级后节点连线总是不成功

### ISSUE THREAD

**Issue by PanClear** [antvis/X6#1196]
开发时安装使用的是 @antv/x6 ^1.23.6 ,实际使用版本是1.23.6
后面重新安装依赖，发现节点之间连线总是失败。连线函数正常运行，查看实际版本是1.24.6。然后重装了1.23.6，经测试，功能恢复正常
### Expected Behavior
期望正常升级x6版本，也能正确兼容

### Current Behavior
版本从1.23.6升级到1.24.6 后 ，节点连线功能出现异常
### Possible Solution
无

### Steps To Reproduce
无

### Additional Context
无

### Your Environment

- x6: [1.23.6]
- OS:  5.0 (Windows NT 10.0; WOW64)
- Browser: Chrome/70.0.3538.25

**Comment by NewByVector** [comment]
已经在 `1.24.7` 中修复了改问题
