### ISSUE TITLE
interacting设为false,使用selecting的movable平移，translating.restrict拿不到view信息

### ISSUE THREAD

**Issue by yu112500** [antvis/X6#1207]
### Expected Behavior
translating.restrict的参数中能获取当前view的信息

### Current Behavior
translating.restrict的参数返回的undefined
![image](https://user-images.githubusercontent.com/34147200/127123546-9c9bf4b3-d9eb-4575-93ec-ec22ebfe0c66.png)

### Steps To Reproduce

https://codesandbox.io/s/silly-khayyam-zqkzu?file=/src/App.tsx

**Comment by NewByVector** [comment]
在 selecting 中 restrict 中不返回 view，如果要实现你的功能，可以在 selecting 中配置 `pointerEvents: none`
