### ISSUE TITLE
router影响了edge的走向，为什么不顺便修改edge的vertices呢？

### ISSUE THREAD

**Issue by AngryChocobo** [antvis/X6#1212]
比如配置了orth路由，跟着源码发现实际上并不会修改edge的vertices，跟文档描述不太一致。

![image](https://user-images.githubusercontent.com/24283492/127324333-418da781-4661-4cdf-b863-ffd46b9b8c0b.png)

看文档感觉会自动生成路由影响后的vertices呢，但是实际上只能从view.routePoints里取到端点的坐标

**Comment by NewByVector** [comment]
vertices 是给外部设置的，内部不会去影响这个参数，如果需要拿到所有顶点，可以直接 `view.routePoints`
