### ISSUE TITLE
使用usePortal React Hook并开启minimap画布无法正常渲染

### ISSUE THREAD

**Issue by wsYdd** [antvis/X6#1213]
使用const [Portal, setGraph] = usePortal(UNIQ_GRAPH_ID)，并开启minmap，会导致节点渲染到了minmap上，画布上无法正常渲染；

![image](https://user-images.githubusercontent.com/11494521/127420771-526140a3-eaeb-4e5b-8abe-ce6a3b51af6f.png)

**Comment by baranwang** [comment]
现在有解决方案吗？

**Comment by qiufeihong2018** [comment]
+1
