### ISSUE TITLE
cell被选中以后，鼠标移开以后未触发mouseleave事件

### ISSUE THREAD

**Issue by AngryChocobo** [antvis/X6#1215]
一旦开启了Graph的配置 selecting， 点击cell，选中以后，就不会触发mouseleave事件了

### Possible Solution

应该是选中的标签，盖住了cell的标签，导致不触发相关事件吧

### Steps To Reproduce

demo里加了log，方便观察

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Additional Context

[https://codesandbox.io/s/x6-mouseleave-bug-h2ikx?file=/src/app.tsx](url)

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/issues/1199 是因为开启selecting后在节点上盖了一层，参考这个 issue 来避免这个问题。
