### ISSUE TITLE
x6-app-dag 项目无法画连接线

### ISSUE THREAD

**Issue by 402976791** [antvis/X6#1216]
x6-app-dag拉取完成，并成功运行之后，加入这些限制，cell与cell无法画连接线
// 显示可用的链接桩
        validateConnection({
          sourceView,
          targetView,
          sourceMagnet,
          targetMagnet,
        }) {
          // 不允许连接到自己
          if (sourceView === targetView) {
            return false
          }

          // 只能从输出链接桩创建连接
          if (
            !sourceMagnet ||
            sourceMagnet.getAttribute('port-group') === 'in'
          ) {
            return false
          }

          // 只能连接到输入链接桩
          if (
            !targetMagnet ||
            targetMagnet.getAttribute('port-group') !== 'in'
          ) {
            return true
          }

          // 判断目标链接桩是否可连接
          const portId = targetMagnet.getAttribute('port')!
          const node = targetView!.cell as X6DemoNode
          const port = node.getPort(portId)
          // return !(port && port.connected)
          if (port && port.connected) {
            return false
          }
    
          return true
        },

**Comment by NewByVector** [comment]
validateConnection 中在哪一步返回 false 了呢？

**Comment by NewByVector** [comment]
本地测试没有问题，先关闭 issue
