### ISSUE TITLE
x6-angular-shape 支持传入 @Input() 

### ISSUE THREAD

**Issue by msyesyan** [antvis/X6#1217]
x6-angular-shape 支持传入 @Input() 

### Expected Behavior

请问可以对 x6-angular-shape 支持修改 component 内的属性的支持么？还是已经支持了只是我没找到？ 比如 README.md 中的例子，只写了一个 NodeComponent, 不知道是如何根据不同的 node data 来显示具体的 label 内容的呢？

**Comment by NewByVector** [comment]
@Eve-Sama 有解决方法吗🧚🏼‍♀️

**Comment by Eve-Sama** [comment]
这个暂时可能没有办法, 在[这里](https://github.com/antvis/X6/pull/1185), 讨论过这个事情. 简单来说, 如果是`TemplateRef`应该还是很容易实现拿到data的信息. 而`Component`暂时没有办法, 这个需要调研一下.
