### ISSUE TITLE
TypeError: Class constructor ToolItem cannot be invoked without 'new'

### ISSUE THREAD

**Issue by J-maxwell** [antvis/X6#1218]
### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]
![image](https://user-images.githubusercontent.com/31434551/127628457-9d7dc4fa-2132-49f6-87b7-2ee3e6fb548f.png)

**Comment by NewByVector** [comment]
可以写个 class A extends B{} 测试一波，是不是你的环境不支持这种语法

**Comment by a136806** [comment]
如果你使用typescript， 请将compilerOptions-> target设置为“es6”;
归根节点要支持es6.

**Comment by EmiyaYang** [comment]
可以从 @antv/x6/lib 里引
