### ISSUE TITLE
router和connector放在attrs里外效果不一样

### ISSUE THREAD

**Issue by huangkaibo** [antvis/X6#1219]
```
router: {
     name: "manhattan"
},
connector: "smooth",
```

放在attrs外面, 效果如图, 会强制是个二阶曲线
![image](https://user-images.githubusercontent.com/19745373/127629734-ed1db5ad-bb7a-4e94-9209-8c04ba0faacf.png)

放在attrs里面则正常
![image](https://user-images.githubusercontent.com/19745373/127630153-6a998ee5-76d6-411a-8194-6e5b0276588d.png)

https://codesandbox.io/s/hopeful-visvesvaraya-dw1by?file=/src/app.tsx

**Comment by NewByVector** [comment]
放在 attrs 里面是没有效果的，所以是正常显示。

**Comment by huangkaibo** [comment]
> 放在 attrs 里面是没有效果的，所以是正常显示。

@NewByVector 了解,  不过放在attrs外面, 这效果也太奇怪了吧, 两个节点, 中间无阻碍, 也会拐两下, 拐的程度还很大

**Comment by NewByVector** [comment]
这个是 `manhattan` 路由和 `smooth` 连接器不要一起使用
