### ISSUE TITLE
泳道图支持

### ISSUE THREAD

**Issue by shenjo** [antvis/X6#1220]
有计划支持泳道图吗，我看之前有个 [enhancement](https://github.com/antvis/X6/issues/23),请问现在有进展吗

**Comment by ameol** [comment]
同求

**Comment by NewByVector** [comment]
已加入支持计划

**Comment by shenjo** [comment]
@NewByVector 非常感谢。请问有计划支持的时间吗，这边急着用，如果支持的快的话考虑先开发自定义节点，做个非常简单的框选功能，等X6支持在替换。（另外如果要自己实现有大致思路吗）

**Comment by NewByVector** [comment]
泳道图终于支持了 [PR](https://github.com/antvis/X6/pull/1575) 🥳

**Comment by shenjo** [comment]
> 泳道图终于支持了 [PR](https://github.com/antvis/X6/pull/1575) 🥳

谢谢大佬，马上试用！
