### ISSUE TITLE
重构下x6-app-dag项目里experiment-graph.tsx和graph-core.ts这两个文件

### ISSUE THREAD

**Issue by TomScavo** [antvis/X6#1226]
写的有些过于复杂了，改起来比较麻烦

- [ ] 去掉重复代码，比如 getter nodes 和 getNodes重复，graph-core.ts内调用experiment-graph.tsx的方法又重复的写了一堆，用 ts 的 abstract 表示要更好一些
- [ ] 降低复杂度，很简单的存储个 copyableNodeId 都是用的 rxjs 的 observable 来写的，graph 的 options 没有必要通过super传给 graph-core ，直接放在 graph-core 就可以
- [ ] 很多逻辑都是绕来绕去的，有很多感觉没有必要

**Comment by NewByVector** [comment]
有兴趣提个 PR？ 🧚🏼‍♀️

**Comment by TomScavo** [comment]
> 有兴趣提个 PR？ 🧚🏼‍♀️

可以的，这两周有空提一下
