### ISSUE TITLE
node 缩放和多选移动的 bug

### ISSUE THREAD

**Issue by limbowang** [antvis/X6#1231]
https://codesandbox.io/s/zen-sun-vzceb?file=/src/index.ts
1、开启 {selecting: { enabled: true }} 图片左上角进行大小缩放会抖动，关闭之后可以顺滑缩放
2、开启 snapline，多个 node 情况下，如果选中两个进行拖动，会导致部分node自动与snapline去对齐，其他不会，期望是整体进行拖动，整体对齐

**Comment by NewByVector** [comment]
第一个问题已经修复：https://github.com/antvis/X6/pull/1238
第二个问题：多选情况下单个node自动snapline对齐在很多场景中有用，整体对齐暂时不考虑支持。

**Comment by cuifn** [comment]
第二个问题比较严重， 开启 snapline，多选移动时，选中节点的相对位置会因为触发snapline发生错乱
期望：多选移动时，如果某个节点触发了snapline, 其它节点也跟着该节点动，维持选中节点的相对位置，不要发生错乱

**Comment by NewByVector** [comment]
多选整体对齐该版本不实现。

**Comment by MrMengJ** [comment]
> 第二个问题比较严重， 开启 snapline，多选移动时，选中节点的相对位置会因为触发snapline发生错乱 期望：多选移动时，如果某个节点触发了snapline, 其它节点也跟着该节点动，维持选中节点的相对位置，不要发生错乱

你好，请问你解决了这个问题吗
