### ISSUE TITLE
X6 SSR  `navigator is not defined`

### ISSUE THREAD

**Issue by bhabgs** [antvis/X6#1232]
### Expected Behavior
vitepress use x6

希望能在vitepress里正确的使用x6, 或者提供下 x6 ssr最佳实践

### Possible Solution
未知

### Steps To Reproduce
在vitepress 项目内引入 x6，dev 环境没问题，build环境下 会报错

#### 安装vite
``` bash
yarn add --dev vitepress
mkdir docs && echo '# Hello VitePress' > docs/index.md

```

#### 可直接运行
[vitevui](https://github.com/bhabgs/vite-vui)

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by devinhalladay** [comment]
Hi, I'm having the same issue using next.js 

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1934813/153738117-0e5f4a30-ff65-48f0-a410-d37b5eb0fffd.png">

**Comment by lichong-a** [comment]
我在nextjs上遇到了同样的问题，请问这个解决了吗？

**Comment by Euraxluo** [comment]
我在nextjs上遇到了同样的问题，请问这个解决了吗？

**Comment by Euraxluo** [comment]
我找到这个项目，好像解决了 https://github.com/devinhalladay/groves
