### ISSUE TITLE
rubberband 没选中 edge 的情况下，也触发了 edge 选中事件。

### ISSUE THREAD

**Issue by septlog** [antvis/X6#1234]
### Expected Behavior

graph 开启 **rubberEdge: true**，连线应当在选框选中后触发事件。

### Current Behavior

在选框未选中 edge 的情况下，触发了 **edge:selected** 事件。
![image](https://user-images.githubusercontent.com/25605220/128319035-970a05ad-85ac-4ca9-9855-4c6b67977bf7.png)
![image](https://user-images.githubusercontent.com/25605220/128319156-d0e74b69-62e8-45b0-ac2d-480d3cec8bdd.png)

### Possible Solution

修改对于折线的判断。

### Steps To Reproduce

[复现 codesandbox](https://codesandbox.io/s/holy-dawn-qx87f)
1. 设置 rubberEdge: true
2. 为 graph 添加 'edge:selected' 监听。

### Your Environment
- x6: 1.25.1
- OS: Windows 10
- Browser: chrome 92.0.4515.131

**Comment by NewByVector** [comment]
其实此时已经选中 edge 了，你可以开启 `showEdgeSelectionBox: true` 看到效果。
