### ISSUE TITLE
vitepress build x6 error

### ISSUE THREAD

**Issue by bhabgs** [antvis/X6#1235]
### Describe the bug

在 vitepress 文档环境中 引用x6 组件，会提示navigate不存在。

### Reproduction

``` bash
yarn build:docs
```

### Expected behavior

希望能够正常引入 x6, 或者提供一个 使用x6的最佳实践

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 891.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1.1
module
     "vite": "^2.4.4",
    "vitepress": "^0.15.6",
```

### Additional context

![image](https://user-images.githubusercontent.com/19221378/128308123-3b5a9649-2288-49a8-9f55-87c745277e2c.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

## 可以查看如下[issues](https://github.com/vuejs/vitepress/issues/349)

**Comment by NewByVector** [comment]
我在本地测试了一下,是能够运行 X6 的，关键文件信息：

CustomComponent.vue
```vue
<template>
  <div id="container"></div>
</template>

<script>
import { Graph } from '@antv/x6'

export default {
  mounted() {
    const graph = new Graph({
      container: document.getElementById('container'),
      width: 400,
      height: 400,
      grid: true,
    })
  }
}
</script>
```

index.md
```
<script setup>
import CustomComponent from '../components/CustomComponent.vue'
</script>

# Docs

This is a .md using a custom component

<CustomComponent />

## More docs

...
```

**Comment by bhabgs** [comment]
运行没问题，目前我的问题是在打包时，会出现

**Comment by NewByVector** [comment]
解决了 navigator 问题后，还有 lodash 问题，我继续看下。

**Comment by bhabgs** [comment]
你是用await import, 引用了吗？

**Comment by NewByVector** [comment]
@bhabgs 最后解决了这个问题吗，如果解决了，能否分享一下在 vitepress 中使用 x6 的踩坑历程
