### ISSUE TITLE
反序列化流程图数据渲染的边指向位置都变成了节点左上角

### ISSUE THREAD

**Issue by yuchao0204** [antvis/X6#1239]
graph.fromJSON(JSON.parse(oaStore.draftJson));
oaStore.draftJson是序列化后保存的object字符串。
![image](https://user-images.githubusercontent.com/68212456/128494743-718242f9-c636-4602-8674-963e246ee9af.png)

**Comment by NewByVector** [comment]
有 demo 看下吗？

**Comment by gushenyi123** [comment]
我也遇见了相同的问题，请问楼主有解决么

**Comment by maergaiyun** [comment]
同样的问题，反序列化之前是这样的
![image](https://user-images.githubusercontent.com/62786015/188114169-84a206af-0506-4ccc-bd0c-3dbbf085e4bc.png)

反序列话后边全部指向节点的左上角
![image](https://user-images.githubusercontent.com/62786015/188114353-33ae17a3-56d3-4a41-bfc7-7176d41ced01.png)

**Comment by zY-zhao** [comment]
遇到同样的问题，请问是否解决
