### ISSUE TITLE
vue自定义节点data改变，不会触发节点重新渲染，也不会触发change事件

### ISSUE THREAD

**Issue by daigang666** [antvis/X6#1240]
vue自定义节点data改变，不会触发节点重新渲染，也不会触发change事件

节点重新渲染

节点没有触发重新渲染，也没有触发change事件

### Steps To Reproduce
请查看示例代码 https://codesandbox.io/s/1hl21?file=/src/App.vue:479-492

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
数据传递参考这个 [demo](https://codesandbox.io/s/vue-shape-test-forked-sbuc0?file=/src/App.vue:550-563)

**Comment by daigang666** [comment]
收到，还有几个问题。
1.目前只能算规避方案？data改变不驱动节点更新，感觉比较违背x6的直觉。
2.我检查了几个部分的源码，data改变的触发更新和事件的逻辑，是通用的并不对自定义节点特殊处理。@antv/x6-vue-shape里只是注册了vue节点，根据vue版本进行渲染（ps：此处有个小问题，包中使用的vue实例与我项目中的不是同一个，取不到项目挂载的方法，如store，国际化之类的）
但是在HTML节点的逻辑中有注册change事件去重新渲染html
![image](https://user-images.githubusercontent.com/42136433/128965794-84afed26-f644-428b-8dd1-3cb97f1c0b0a.png)
是否vue节点可以这样触发更新
3.如无法实习节点rerender，至少建议这种方案添加到官网示例。

**Comment by NewByVector** [comment]
官网 demo 已经更新，使用了推荐的父子通信方式
