### ISSUE TITLE
fromJSON 长任务拆分，避免阻塞主线程

### ISSUE THREAD

**Issue by tiancihe** [antvis/X6#1244]
### Expected Behavior

当节点数量很多的时候，执行 `fromJSON` 会导致主线程被阻塞在这个长任务中，页面卡住不动

### Possible Solution

使用 `requestIdleCallback` 、 [react-scheduler](https://github.com/facebook/react/tree/main/packages/scheduler) 等，将调用 `Model.fromJSON` 后得到的 `cells` 逐步添加到 `graph` 中

[Demo](https://codesandbox.io/s/scheduled-x6-initialization-6hgtr?file=/index.js)

**Comment by NewByVector** [comment]
x6 已经有 `async` 渲染功能，而且我们也在优化异步渲染这一块内容，所以这块可以暂时外部去实现。
