### ISSUE TITLE
开启Scroller功能，滚动的宽度和高度莫名奇妙增加好几倍

### ISSUE THREAD

**Issue by duyu123** [antvis/X6#1249]
![image](https://user-images.githubusercontent.com/21079129/129129979-53683702-caa2-4753-9ad0-026d4b4982af.png)
代码配置如下：
![image](https://user-images.githubusercontent.com/21079129/129130040-005defaa-f3cd-47ab-82bc-9a3eaec6df4a.png)

**Comment by NewByVector** [comment]
这个应该是在画布远处有一个节点，自动扩展了画布，可以通过 `scroller: { autoResize: false }` 来关闭

**Comment by duyu123** [comment]
画布远处没有节点，画布只有一个节点也这样，并且scroller: { autoResize: false }配置也没啥用

**Comment by tiancihe** [comment]
我也碰到了这个问题，这里应该配置 scroller.pageWidth 和 scroller.pageHeight 吧，决定分页的宽高
