### ISSUE TITLE
请问在vue里如何在渲染链接桩的时候动态渲染tooltip

### ISSUE THREAD

**Issue by chris-mask** [antvis/X6#1251]
请问在vue里如何在渲染链接桩的时候动态渲染tooltip，文档上面react是这样的
const graph = new Graph({
  container: this.container,
  onPortRendered(args) {
    const selectors = args.contentSelectors
    const container = selectors && selectors.foContent
    if (container) {
      ReactDOM.render(
        <Tooltip title="port">
          <div className="my-port" />
        </Tooltip>,
        container,
      )
    }
  },
})

**Comment by chris-mask** [comment]
您好，这个问题比较紧急，请问可以解决吗

**Comment by chris-mask** [comment]
> 嗨！
> 
> 这个问题已经沉寂了。诡异的安静。👻
> 
> 我们遇到了很多问题，因此我们现在在 60 天不活动后关闭问题。上次更新已经过去了至少 20 天。如果我们远离了这个问题，或者如果想您保持打开状态，请在此处回复。您还可以添加标签“未过时”以保持此问题开放！
> 
> 友情提示：查看此问题或任何其他问题的最佳方法是打开一个拉取请求。查看[原文](https://github.com/antvis/X6/blob/master/CONTRIBUTING.md)以获取有关打开公关、分类问题和补充的更多信息！
> 
> 感谢您成为 AntV 社区的一员！ 💪💯

你好，这个问题比较紧急，请问可以解决吗

**Comment by NewByVector** [comment]
可以这样解决：
```ts
const vm = new Vue({
   el: '', // 你的内容模板
})
container.appendChild(vm.$el)
```

**Comment by chris-mask** [comment]
> 可以这样解决：
> 
> ```ts
> const  vm  =  new  Vue ( { 
>    el : '' ,  // 你的内容模板
> } ) 
> container . appendChild ( vm . $el )
> ```

可以详细点吗，我写ID或者HTML都不行，报错
![image](https://user-images.githubusercontent.com/21608359/134473220-200dad57-8a97-4311-b699-54d8fe779550.png)

**Comment by LZCaaT** [comment]
碰到一模一样的问题，感谢，已解决
