### ISSUE TITLE
循环线的样式和使用

### ISSUE THREAD

**Issue by luckjoke** [antvis/X6#1252]
1. 在之前的Issue中，看到有关于循环线的使用问题，但后续并没有回复，在官网的样例和教程中也没有相关回答，能否提供一个循环线的使用样例。
2. 在拖拽连线的过程中，是否会自动判断连的线是循环线？如果不会，又如何自行创建循环线。
3. 自定义connector时，如何判断是否是循环线？

**Comment by NewByVector** [comment]
循环连线使用方式参考：https://github.com/antvis/X6/blob/master/examples/x6-example-features/src/pages/edge/loop1.tsx
