### ISSUE TITLE
Multiple edges is created between the same link of start node to same end node.

### ISSUE THREAD

**Issue by Sanjeevraghav** [antvis/X6#1253]
We have the output link of the source node but no input link of the destination node. means we are connecting multiple output links of the source node with the destination node.

1.  Set Graph config 
   connecting: {
        allowMulti: 'withPort',
     }
2. Tried to connect the same output link of the source node to the same destination node multiple times. 
3. Output JSON look like-
[
  {
    "shape": "edge",
    "id": "22BXik3FQi",
    "source": {
      "cell": "51wOSq2l9n",
      "port": "7ZA6vsdYu7"
    },
    "target": {
      "cell": "8-qVxfQowa"
    }
  },
  {
    "shape": "edge",
    "id": "cCMDMVNKfY",
    "zIndex": 0,
    "source": {
      "cell": "51wOSq2l9n",
      "port": "7ZA6vsdYu7"
    },
    "target": {
      "cell": "8-qVxfQowa"
    }
  }
]

On both the edges, the Source and destination are the same.

How we can stop having multiple same edge connections.

### Your Environment

- x6: 1.25.3
- OS: macOS Big Sur 11.5.1
- Browser: chrome 92.0.4515.131

**Comment by NewByVector** [comment]
you can set allowMulti to false,so only one line can be connected between the start node and the destination node

**Comment by Sanjeevraghav** [comment]
@NewByVector if we set allowMulti to false. Then only one line can be connected between startnode to destination node. 
But our requirement is different. We need to have multiple connect from different port of start node to destination node but not allowed multiple connection from same port of start node to destination node. 

I think we need to add one more options in configuration. 
Please let us know how to solve such scenario?

**Comment by NewByVector** [comment]
you can config validateConnection like this:
```ts
const graph = new Graph({
  container: this.container,
  width: 800,
  height: 400,
  grid: true,
  connecting: {
    validateConnection({ sourcePort, targetPort, targetCell }) {
      if (targetCell) {
        const edges = graph.getIncomingEdges(targetCell)
        let exist = false
        // had a edge source is port and target is node?
        edges?.forEach(edge => {
          const sourcePortId = edge.getSourcePortId()
          const targetPortId = edge.getTargetPortId()
          if (sourcePortId === sourcePort && !targetPortId) {
            exist = true
          }
        })
        if (exist && !targetPort) {
          return false;
        }
      }
      return true
    }
  },
})
```
