### ISSUE TITLE
支持对横向和竖向设置不同的网格大小

### ISSUE THREAD

**Issue by LvWentao** [antvis/X6#1256]
现在网格的大小只支持一个值：
`const graph = new Graph({
  grid: 10,
})`

是否可以支持对横向和竖向设置不同的网格大小？

**Comment by bubkoo** [comment]
@LvWentao 参考这个文档 https://x6.antv.vision/zh/docs/api/registry/grid#registry 注册自己的网格吧

**Comment by LvWentao** [comment]
> @LvWentao 参考这个文档 https://x6.antv.vision/zh/docs/api/registry/grid#registry 注册自己的网格吧

@bubkoo 感谢回复。但是有个疑问，网格是移动节点的最小单位，可以起到限制节点拖动位置的作用。现在预置的网格只能设置一个大小值，导致移动节点时横向和纵向都只能限制一样的大小，但是我希望达到的效果是横向和纵向限制不同的大小。看你贴的这个示例好像是对网格渲染样式的自定义，不确定是否能够实现我希望的这个效果？

**Comment by NewByVector** [comment]
网格横向和纵横大小不一致的场景是什么？ X6 现在是不支持的。

**Comment by NewByVector** [comment]
上面的回复有没有解决你的疑惑？为了更高效处理 issue，我先关闭当前 issue，如果还有问题，请新开一个 issue。
