### ISSUE TITLE
自定义节点连接桩连线时出现问题

### ISSUE THREAD

**Issue by liuyonghuaaihcw** [antvis/X6#1257]
自定义节点连接桩位置之后，创建的连线位置计算错误
地址：[https://codesandbox.io/s/infallible-architecture-8r6cq?file=/src/components/HelloWorld.vue](url)
![20210816120046](https://user-images.githubusercontent.com/53337014/129510288-3a2ffd82-10cd-4e17-a842-0189cf65cb6a.png)

**Comment by NewByVector** [comment]
你把边的 `zIndex` 设置高一点，其实位置并没有计算错误，是被节点遮盖了。
