### ISSUE TITLE
开启 embedding 会误触发 change:parent 事件

### ISSUE THREAD

**Issue by tiancihe** [antvis/X6#1258]
### Expected Behavior

embedding 不会被异常触发

### Current Behavior

开启 embedding 后，移动子节点时，如果子节点存在连接它的边，会导致该边也被 embed 到父节点中

### Steps To Reproduce

https://codesandbox.io/s/cell-change-parent-is-unexpectedly-triggered-hc1sl

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
你监听的是 `cell:change:parent` 事件，当 embeeding 的时候，边的 `parent` 也同时被修改了，触发这个事件时正常的。如果只关注节点的，可以监听 `node:change:parent`，[示例](https://codesandbox.io/s/change-parent-zordl)

**Comment by tiancihe** [comment]
节点被 embed ，边也会被 embed 这个符合预期是吗，那如果我不想边作为 child 呢，加上

```
    validate({ child }) {
      return child.isNode();
    },
```

仍会触发边的 cell:change:parent 事件，一次被添加到父节点中，一次被移出

**Comment by NewByVector** [comment]
这个是符合预期的，没有办法做到不让边作为child，这个是内部机制决定的。对实际业务开发应该没有影响吧

**Comment by tiancihe** [comment]
> 这个是符合预期的，没有办法做到不让边作为child，这个是内部机制决定的。对实际业务开发应该没有影响吧

边作为 child 是不会影响，但有个问题是当边已经是 child 的时候，再拖拽连接的节点，边首先会被 unembed ，然后又一次被 embed ，触发了两次 change:parent 事件

**Comment by NewByVector** [comment]
业务中监听 node:change:parent 即可
