### ISSUE TITLE
怎么设置链接桩出线是直线然后在折呢

### ISSUE THREAD

**Issue by it5200** [antvis/X6#1259]
### Expected Behavior

![image](https://user-images.githubusercontent.com/19451694/129655474-85d0752f-c02b-410d-a7d4-33959c8989f0.png)

### Possible Solution

![image](https://user-images.githubusercontent.com/19451694/129655390-46f49d10-9e91-4ac4-88c7-042324ce7cb0.png)

### Additional Context

 目前是把每个edge加个vertices来实现，但是还是有点问题，需要手动调下，不然会出现重叠
![image](https://user-images.githubusercontent.com/19451694/129655474-85d0752f-c02b-410d-a7d4-33959c8989f0.png)

重叠的现象
![image](https://user-images.githubusercontent.com/19451694/129655660-3b4dbc1e-d21e-4204-9440-45c39c36f38b.png)

**Comment by NewByVector** [comment]
可以使用路由中的 `padding` 配置，参考[文档](https://x6.antv.vision/zh/docs/api/registry/router#orth)

**Comment by it5200** [comment]
试了下，不是我想要的效果

**Comment by it5200** [comment]
我期望manhattan可以有这个配置项

**Comment by NewByVector** [comment]
you can set `step` for manhattan:
```ts
router: {
  name: 'manhattan',
  args: {
    step: 20
  }
}
```

**Comment by GPXNB** [comment]
这个也是我想要的 这边有进展么?
