### ISSUE TITLE
支持CSP内容安全政策

### ISSUE THREAD

**Issue by SmileLifeIven** [antvis/X6#1260]
代码中存在不安全代码，new Function， 路劲 x6/src/util/object/inherit

### Expected Behavior

希望使用其他方式实现，避免CSP规范

### Possible Solution

暂无

### Additional Context

项目内CSP规范不允许进行调整

**Comment by NewByVector** [comment]
想问一下，你们的 script-src 是否可以设置为 unsafe-eval

**Comment by OpportunityLiu** [comment]
我觉得我提的那个解决方案没啥问题啊，是不是没看见

https://github.com/antvis/X6/pull/1266#issuecomment-906905929

**Comment by OpportunityLiu** [comment]
或者这招也可以

![image](https://user-images.githubusercontent.com/13471233/135716847-ae58ce70-5a6e-4ad6-8d53-703c1f9cfe79.png)

**Comment by NewByVector** [comment]
@OpportunityLiu  确实没看到你提的方案 👍👍 我先测试下效果

**Comment by konstagap** [comment]
![bug](https://user-images.githubusercontent.com/53840723/159358307-b17f9a2b-5ddc-4d59-81a1-1094222c7269.jpg)
having the same issue, I can not set Content-Security-Policy  to 'unsafe-eval' due to company restrictions, is there another way how to get it fixed?
