### ISSUE TITLE
vue shape 节点销毁时需要清除 vue 实例

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#1261]
### Expected Behavior

vue shape 节点销毁时需要清除 vue 实例

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by xinxincat** [comment]
vue shape节点是在画布删除这个节点的时候，进行实例销毁么？会执行vue的生命周期Destroy么
