### ISSUE TITLE
源码中存在不符合CSP内容安全策略规范代码

### ISSUE THREAD

**Issue by SmileLifeIven** [antvis/X6#1263]
代码中存在不安全代码，new Function， 路径 x6/src/util/object/inherit

### Expected Behavior

希望使用其他方式实现，避免CSP规范

通过策略规范，不修改规范内容

### Steps To Reproduce

1. 在前端服务器内添加安全策略规范内容，以nginx为例
server {
     listen xx.xx.xx.xx:8081;
     add_header Contetn-Security-Policy "default-src 'self';  style-src 'self'; "
     
     location xxx {}
}
2. 访问该服务，打开控制台，提示错误信息

<details><summary>
    Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'".
    at new Function(<amonymous>)
    ...
</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [1.25.4]
- Window: [win10 x64]
- Browser: [chrome 92.0.4515.159]

**Comment by NewByVector** [comment]
和 https://github.com/antvis/X6/issues/1260 重复，先关闭
