### ISSUE TITLE
连线不能自动避开节点的位置

### ISSUE THREAD

**Issue by liuyonghuaaihcw** [antvis/X6#1265]
自定义链接桩位置之后，在节点之间创建的边没有避开节点的位置
router为: manhattan
connector为：rounded
![image](https://user-images.githubusercontent.com/53337014/129837258-8fc18d99-515d-4e4f-a9bb-645e2cf190e3.png)
地址：[https://codesandbox.io/s/infallible-architecture-8r6cq?file=/src/components/HelloWorld.vue:917-1045](url)

**Comment by NewByVector** [comment]
在这个场景中，路由计算的起始元素和结束元素是两个连接桩，所以导致了上面问题。可以在边连接完成事件中将边的起始和结束元素指向节点本身。

**Comment by liuyonghuaaihcw** [comment]
> 在这个场景中，路由计算的起始元素和结束元素是两个连接桩，所以导致了上面问题。可以在边连接完成事件中将边的起始和结束元素指向节点本身。

没理解啥意思，可以在我的demo（https://codesandbox.io/s/infallible-architecture-8r6cq?file=/src/components/HelloWorld.vue）上改一下吗
