### ISSUE TITLE
首页可以添加一个'谁在使用'栏目吗?

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/X6#1268]
### Expected Behavior
很多开源项目都会有'谁在使用'的列表呈现在首页明显的位置, 这对于项目来说是非常好的背书. 比如著名的[antd](https://ant.design/docs/react/introduce-cn#%E8%B0%81%E5%9C%A8%E4%BD%BF%E7%94%A8)

**Comment by Eve-Sama** [comment]
进展如何?

**Comment by NewByVector** [comment]
我先提个 issue 收集一波

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/issues/1340
