### ISSUE TITLE
启用 scroller 可否实现类似 react-virtualized 的可视区域渲染

### ISSUE THREAD

**Issue by tiancihe** [antvis/X6#1269]
### Expected Behavior

调用 `graph.fromJSON` 在节点数量很多的情况下，页面的 TTI 指标很低（开启 async 并没有很大提升），我看到有个 checkView 的配置能够决定 view 是否要渲染到 DOM 中，文档提供的 [DEMO](https://codesandbox.io/s/boring-monad-ux5zw) 中没有使用 scroller ，请问如果启用 scroller 的情况下要如何实现类似 react-virtualized 那样的懒加载呢

**Comment by NewByVector** [comment]
同样可以 开启 async，并且在 checkView 中判断元素是否在当前可视窗口内。具体实现参考：https://github.com/antvis/X6/blob/master/examples/x6-example-features/src/pages/performance/async.tsx
