### ISSUE TITLE
批量移动节点时，无法触发node:moved事件。@antv/x6 @1.25.5

### ISSUE THREAD

**Issue by BarneyRoos** [antvis/X6#1271]
### Expected Behavior
批量移动节点时，应该仍能触发node:moved事件

### Current Behavior
批量移动节点时，无法触发node:moved事件。
**【官网示例中也是有这个问题，https://codesandbox.io/s/5ur29?file=/src/app.tsx】**
```ts
// 移动节点：更新chart_conf
graph.on('node:moved', (e) => {
  console.log(e);
  if (e.node.id.indexOf('#addition-info') === -1) { // 业务代码
    updateChartInfo(graph.toJSON().cells); // 业务代码
    rerenderVars(graph); //业务代码
    console.log(e.node.id);
  }
});
```
![image](https://user-images.githubusercontent.com/12667145/130198367-12245111-84fb-40e3-8def-4a80245e3797.png)

![image](https://user-images.githubusercontent.com/12667145/130197504-d1daab03-4fd2-471d-aa8f-614a4d354a7b.png)

![image](https://user-images.githubusercontent.com/12667145/130198549-0d4c6e41-3146-4bc2-8d8f-e1196079f527.png)

### Steps To Reproduce
1. 框选多个节点
2. 移动它们
3. 观察node:moved事件的触发情况

### Your Environment

- x6: [1.25.5]
- OS: [macOS Big Sur 11.4]
- Browser: [chrome 版本 92.0.4515.159（正式版本） (x86_64)]

**Comment by BarneyRoos** [comment]
> 👋 @BarneyRoos
> 
> Thanks for opening your first issue here! If you're reporting a 🐞 bug, please make sure you include steps to reproduce it.
> 
> To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/antvis/X6/blob/master/CONTRIBUTING.md).
> 
> We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.

thank you, bot and x6!

**Comment by NewByVector** [comment]
@antv/x6@1.26.1 更新到这个版本

**Comment by BarneyRoos** [comment]
> @antv/x6@1.26.1 更新到这个版本

官网、本地均测试OK，感谢🙏
