### ISSUE TITLE
使用Stencil，在画布外释放不触发拖拽结束事件

### ISSUE THREAD

**Issue by qq382724935** [antvis/X6#1279]
### Expected Behavior
在使用Stencil时，拖拽组件在画布外释放不会能触发拖拽结束事件

### Current Behavior
在使用Stencil时，拖拽组件在画布外释放应该能触发拖拽结束事件

### Steps To Reproduce

https://codesandbox.io/s/gallant-satoshi-y5dtp?file=/src/app.tsx

1. 拖拽codesandbox 中的rect节点到画布释放后可以触发getDropNode和validateNode事件
2. 拖拽codesandbox 中的rect节点在画布外释放释放后不触发getDropNode和validateNode事件

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
能描述一下使用场景吗？

**Comment by qq382724935** [comment]
> 能描述一下使用场景吗？
举个简单的业务场景例子：现在要创建一个营销活动，这个活动按顺序从下至下设置：活动开始时间，发送微信，发送短信。
每个节点在画布都是固定位置的，当我从Stencil拖拽节点时，通过getDragNode事件会在画布先生成一个空的节点， 提示用户把节点拖拽到该指定位置，当用户没有拖拽到指定位置释放了鼠标则本次操作无效，则删除这个空的节点。目前的情况是，当节点进入画布会触发getDropNode事件，我能删除空节点，但是节点在画布外释放，无法触发事件空的节点无法删除，用户使用起来会有引导错觉

**Comment by qq382724935** [comment]
如我现在创建了活动开始时间，发送微信，发送短信三个节点功能，当我从Stencil拖拽赠送积分节点时候会在活动开始时间和发送微信节点之间有一个空节点，在发送微信和发送短信节点之间也会有一个空节点，发送短信后也有一个空节点，用户拖拽到哪个空节点， 我就在用赠送积分节点替代该空节点，如此反复

**Comment by qq382724935** [comment]
用户只负责添加功能节点，其它的逻辑由开发处理，比如两节点边生成等

**Comment by NewByVector** [comment]
参考这个 [demo](https://codesandbox.io/s/validate-outer-graph-6vuet)
