### ISSUE TITLE
x6-app-draw 项目不符

### ISSUE THREAD

**Issue by web-ltc** [antvis/X6#1281]
这是文档上的图片说明
![image](https://user-images.githubusercontent.com/29110682/130380319-42b490e0-5efe-41ea-9490-da8a3e4098f7.png)
这是预览地址下的项目截图（下载源码本地运行也是这样）
![image](https://user-images.githubusercontent.com/29110682/130380370-77e5ed66-de0a-400d-b351-06081ff85d0d.png)

文档上的demo无法下载

**Comment by NewByVector** [comment]
这块 demo 已经更新过了。可以访问 https://github.com/antvis/X6/tree/%40antv/x6%401.23.0/examples/x6-app-draw 获取图上的代码。

**Comment by tomcatYH** [comment]
> 这块 demo 已经更新过了。可以访问 https://github.com/antvis/X6/tree/%40antv/x6%401.23.0/examples/x6-app-draw 获取图上的代码。

我下载下来,启动之后,还是楼主说的那个模板
