### ISSUE TITLE
edge不能自动规避node节点

### ISSUE THREAD

**Issue by yingchy1996** [antvis/X6#1283]
### Expected Behavior

希望edge可以自动规避node节点

### Current Behavior

edge不能自动规避node节点
edge是使用链接桩连接的

### Possible Solution

我router设置为manhattan但是并不会生效
![1629791206016_3DC70C39-C9AF-4759-8386-25B21E732E5C](https://user-images.githubusercontent.com/51258523/130582174-5221e044-d203-4539-b53c-956602a182ff.png)

### Steps To Reproduce

[https://github.com/yingchy1996/grid/blob/master/e-r](https://github.com/yingchy1996/grid/blob/master/e-r)

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Additional Context

![1629791017417_D6F8A1A4-C84F-4d57-BBF1-521241F8082B](https://user-images.githubusercontent.com/51258523/130581984-ca4242ab-be94-497e-a460-d24d849bace5.png)

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by yingchy1996** [comment]
已解决 不使用链接桩

**Comment by Spounds** [comment]
> 已解决 不使用链接桩

请问不适用连接桩，要如何处理？要根据不同的字段，连接到不同的位置。
