### ISSUE TITLE
自定义vue节点，鼠标悬浮至瞄点时，节点会出现闪烁，是因为使用了绝对定位么？

### ISSUE THREAD

**Issue by daigang666** [antvis/X6#1286]
自定义vue节点，鼠标悬浮至瞄点时，节点会出现闪烁

节点不应闪烁

是否是由于使用绝对定位出现

### Steps To Reproduce
![x6](https://user-images.githubusercontent.com/42136433/130718815-777965c9-bab7-4064-ab12-b7c70121cdbb.gif)

参考简单复现：https://codesandbox.io/s/vue-shape-forked-2sx2g?file=/src/components/Count.vue

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
看了下你的 demo，是因为使用了 position 属性造成的。可以参考：https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99

**Comment by xielingdm** [comment]
> 看了下你的 demo，是因为使用了 position 属性造成的。可以参考：https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99

请问什么时候可以解决vue节点不能使用position和transform的css样式，这两个不能用好多样式和效果写起来非常困难😭
