### ISSUE TITLE
开启scroller和panning，画布缩小后，不能自适应外部容器，内部图形超出隐藏

### ISSUE THREAD

**Issue by Azir1** [antvis/X6#1290]
### Expected Behavior
希望画布尺寸永远自适应外部容器大小

### Current Behavior
视图缩小后，画布也会缩小，内部图形溢出隐藏
![image](https://user-images.githubusercontent.com/59249690/130750341-a008c94f-91e9-4697-aa8e-3d0a14c33d8f.png)

### Steps To Reproduce

1. 如图设置scroller、mousewheel和panning属性
2. 滚轮缩小画布
3. 将图形向画布边缘拖动

**Comment by NewByVector** [comment]
开启 scroller 后，在 scroller 内部配置 pannable，不要与 `panning` 一起使用。
