### ISSUE TITLE
使用Stencil拖拽插件，拖拽热区可以设置么？

### ISSUE THREAD

**Issue by xinxincat** [antvis/X6#1292]
在实际开发过程中，左侧拖拽的组件库，有些图标比较大，好拖拽。有些icon只有一个长条，需要对准那个长条才可以拖拽到画布。
预期：期望左侧热区大小可以设置，便于拖拽
请问下  怎么设置啊？

**Comment by NewByVector** [comment]
拖拽热区不可以设置，可以换一种思路：像使用 edge 一样，通过两个元素实现，一个用于方便操作(比较大),一个用于显示。
