### ISSUE TITLE
Is there any way to make graph readonly so we will not allowed to modify graph

### ISSUE THREAD

**Issue by Sanjeevraghav** [antvis/X6#1296]
### Expected Behavior

We have a graph create and edit feature but based on permission, we are allowing the user to edit the graph.
There is one method freeze(...) which freeze view but output JSON will have all modified changes.
Can we have any feature to set graph read-only mode?
And only node click events should be allowed.

**Comment by Sanjeevraghav** [comment]
> Potential duplicates:
> 
> * [[Is there any way to make graph readonly so we can not modified graph ](https://github.com/antvis/X6/issues/1295)[ #1295](https://github.com/antvis/X6/issues/1295)] Is there any way to make graph readonly so we can not modified graph  (84.29%)[](https://github.com/antvis/X6/issues/1295)

**Comment by NewByVector** [comment]
[interacting](https://x6.antv.vision/zh/docs/tutorial/basic/interacting#%E5%AE%9A%E5%88%B6%E4%BA%A4%E4%BA%92%E8%A1%8C%E4%B8%BA) configuration can help you

**Comment by Sanjeevraghav** [comment]
Thanks, @NewByVector for reply. I will add an interacting configuration because we need custom behavior.
