### ISSUE TITLE
点选/框选 Selection

### ISSUE THREAD

**Issue by xiaoqufengdi** [antvis/X6#1297]
给节点添加选中效果后，把节点拖到边界外，节点不可见，但选中效果样式依然可见
demo： https://x6.antv.vision/demos/tutorial/basic/selection/playground/
![image](https://user-images.githubusercontent.com/31072438/130931500-a2804637-1a6f-49d0-84eb-78baebeb043a.png)

**Comment by xiaoqufengdi** [comment]
问题还没解决就想关掉，这水划得

**Comment by Sanjeevraghav** [comment]
@xiaoqufengdi Please let us know how you solved this issue? 
We are also facing the same issue.

**Comment by xiaoqufengdi** [comment]
Temporary schemes that change styles dynamically
` let selectedDOM = document.querySelector('.x6-widget-selection-box') 
// change style
...
`

**Comment by NewByVector** [comment]
这种场景更合理的做法是限制节点拖出画布：
```ts
new Graph({
  translating: {
    restrict: true,
  }
})
```
为了更高效处理 issue，当前 issue 我先关闭。

**Comment by xiaoqufengdi** [comment]
我这边的场景是拖动画布，有的节点被拖到画布外面去了。且不说在 restrict: true并不能限制拖动画布时节点被拖到外面去，即使可行，在节点数较多的时候总会有显示不下的节点，拖拽功能还被限制了。
