### ISSUE TITLE
antX6和antVuePro项目下有冲突

### ISSUE THREAD

**Issue by linkcoder** [antvis/X6#1300]
![image](https://user-images.githubusercontent.com/21972676/131107717-703b717d-9d3b-409a-b904-9a26d118a738.png)

正常情况下是这样
![image](https://user-images.githubusercontent.com/21972676/131108018-4ed8c762-e511-4c3e-a0fd-94d3bf92ad44.png)

### Possible Solution
感觉是css冲突的问题，如果使用原始的html标签，没有出现这个问题

### Steps To Reproduce
1.使用vue自定义渲染graph上的节点
2. 在使用链接桩时候，如果有使用a-card、a-button
在触发连接桩的horver事件时，第二个node会闪烁

`Graph.addNode({
        shape: 'vue-shape',
        width: 300,
        height: 100,
        x: location.x,
        y: location.y,
        component: {
          template: `<dag-node 
            :idx="idx" 
            >
            </dag-node>`,
           components: {
            DagNode,
          },
`
谷歌浏览器会出现，其他浏览器（firefox）不会出现
<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
看起来是这个问题，https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99
