### ISSUE TITLE
拖拽超出一定范围以后，箭头会指向另外一个锚点

### ISSUE THREAD

**Issue by xielingdm** [antvis/X6#1302]
正常的图：
![image](https://user-images.githubusercontent.com/23383297/131335870-e98bc404-9934-43b8-bef4-201eb09f122f.png)

拖拽范围小的图（此时定位的锚点是正常的）
![image](https://user-images.githubusercontent.com/23383297/131335940-b77bbce6-c898-43c2-b963-f1ab71e4462f.png)

拖拽范围变大之后（定位的锚点从上面变到左边，并且随着节点位置改变，锚点可能定位到上下左右任一个，需求是拖拽时不能变动锚点的位置，一直连接上面的锚点）
![image](https://user-images.githubusercontent.com/23383297/131336163-70a73ea1-6c74-4210-8168-7a00620e1ea0.png)

我的设置是这样的
 connecting: {
        snap: true,
        allowBlank: false,
        allowLoop: false,
        anchor: 'center',
        connectionPoint: 'anchor',
        highlight: true,
    },

edge的设置：
source: {
      ...source,
      anchor: {
        name: 'bottom'
      }
    },
    target: {
      ...target,
      anchor: {
        name: 'midSide'
      }
    },

请问需要怎么设置，锚点才不会随着拖拽位置变动？

**Comment by NewByVector** [comment]
`anchor` 和 `connectionPoint ` 一起决定连接点的位置，可以参考[文档](https://x6.antv.vision/zh/docs/api/registry/connection-point), 你这里如果要固定连接桩，需要在 edge 的 source 和 target 中制定连接桩。可以参考这个[demo](https://codesandbox.io/s/anchor-pos-4gtjy?file=/src/app.tsx)
