### ISSUE TITLE
Is there any way to check whether a graph is directed acyclic graph or not ?

### ISSUE THREAD

**Issue by Sanjeevraghav** [antvis/X6#1303]
### Expected Behavior

We have a marketing campaign automation tool. we just want to make sure there is no cycle in the graph. 
So is there any easy way to check the directed acyclic graph? 
otherwise, we need to check output JSON to validate the graph.

how can detect cycle during connect nodes?

**Comment by NewByVector** [comment]
X6 currently has no method for detecting rings, but you can use the method provided by this [repository](https://github.com/antvis/algorithm/blob/master/packages/graph/src/detect-cycle.ts)

**Comment by Sanjeevraghav** [comment]
@NewByVector thanks for the reply. The algorithms repo is very helpful.
