### ISSUE TITLE
开启 showNodeSelectionBox 并选中节点后 mouseenter 和 mouseleave 事件未正常触发

### ISSUE THREAD

**Issue by tiancihe** [antvis/X6#1307]
### Expected Behavior

鼠标移入节点会触发 mouseenter 事件，移出会触发 mouseleave 事件

### Current Behavior

mouseenter 和 mouseleave 事件没有触发， mouseover 事件正常触发

### Steps To Reproduce

https://codesandbox.io/s/selection-mouseenter-9qu6l

1. 选中节点
2. 鼠标移入移出

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
`showNodeSelectionBox` 后在节点上方盖了一层 div,可以通过设置：
```ts
selecting: {
  ...
  pointerEvents: 'none'
}
```
来捕捉节点上事件

**Comment by tiancihe** [comment]
@NewByVector 现在的疑问是 mouseover 事件能够正常触发

**Comment by NewByVector** [comment]
x6 所有事件都是绑定在 container 容器上, 当鼠标焦点发生转移时，都会触发 `mouseover` 事件，这就是 `mouseover` 能被触发的原因。
