### ISSUE TITLE
当节点有两条边时调用edge.toFront后	node:dblclick双击事件失效

### ISSUE THREAD

**Issue by 599218337** [antvis/X6#1308]
### 当节点有两条边时调用edge.toFront后	node:dblclick双击事件失效

![image](https://user-images.githubusercontent.com/56375648/131822534-42d968e6-b68d-48a7-ab2f-d876d67fc40e.png)
节点单击事件调用highPath方法，highPath方法中调用了edge.toFront(),之后双击事件失效
### BUG复现前提
![image](https://user-images.githubusercontent.com/56375648/131822876-f5d8aba1-b505-4f05-9db8-057fb63686ee.png)
需要存在两条边调用toFront方法

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
是不是一个 edge toFront 后将另一个 edge 挡在后面了，我本地测试是没有问题的，测试链接：https://codesandbox.io/s/edge-click-0qrtf。

**Comment by 599218337** [comment]
那我通过foreach循环所有edge调用toFront方法也会存在挡住的问题吗？也没有报错提示。 测试链接：[https://codesandbox.io/s/edge-click-forked-5zvfk](https://codesandbox.io/s/edge-click-forked-5zvfk)

**Comment by NewByVector** [comment]
出现上面现象的原因是：单击事件中调用了 `edge.toFront()`, 当边的 zIndex 修改的时候，svg 元素直接的 dom 结构发生了改变，所以没有触发 `dblclick` 事件。解决方案：
```ts
const graph = new Graph({
  sorting: 'approx'
});
```
