### ISSUE TITLE
router设置manhattan时，某些场景下不生效

### ISSUE THREAD

**Issue by comeonlll** [antvis/X6#1309]
**当router设置为manhattan，开始路由方向设置为right，结束路由方向设置为left，当开始节点和目标节点间距较短时，路由开始方向会变成top，结束方向也会变为top**
edge = graph.addEdge({
      source,
      target,
      router: {
        name: 'manhattan',
        args: {
          startDirections: ['right'],
          endDirections: ['left'],
        },
      },
    })

### Current Behavior
![image](https://user-images.githubusercontent.com/38073829/131850481-b439206e-e508-4448-bb1b-37d165e18bfc.png)

![image](https://user-images.githubusercontent.com/38073829/131850236-fabb093e-bfa0-424d-b0df-a40d4974b5d0.png)

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
可以通过使用 [NodeAnchor](https://x6.antv.vision/zh/docs/api/registry/node-anchor) 固定连接点位置.
