### ISSUE TITLE
fromJSON无法触发cell的事件

### ISSUE THREAD

**Issue by mosuzi** [antvis/X6#1313]
### Expected Behavior
在fromJSON后触发cell的added事件，监听该事件做一些处理。

### Current Behavior
fromJSON中，调用了prepareCell，但是指定了dryRun为true，使得cell.model为空，这会导致无法触发added事件，而cell.model在这时候才因为重新调用prepareCell被赋值。

### Possible Solution
尚不清楚如何修正

### Steps To Reproduce

1. 添加cell的added事件监听
2. 使用fromJSON绘制节点
3. 没有触发cell的added事件

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment
- x6: 1.25.0

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
暂时不会增加 fromJSON 后的 added事件，原因：
1. 这是 breakchange，影响其他项目
2. 意义不大，这部分逻辑可以直接写在 fromJSON 语句后面
