### ISSUE TITLE
How to control line drawing graphics on the page

### ISSUE THREAD

**Issue by cnbf** [antvis/X6#1320]
How to control line drawing graphics on the page

if this function can be realized

**Comment by NewByVector** [comment]
Could you be more specific？

**Comment by cnbf** [comment]
![929835-20180311165255827-1716214935](https://user-images.githubusercontent.com/89966976/132603648-2a74906d-ce2d-4f70-b31a-988293dd79a0.gif)

**Comment by cnbf** [comment]
like this

**Comment by cnbf** [comment]
i want to  draw it on the graph
