### ISSUE TITLE
设置router为manhattan时，节点靠近路径变形

### ISSUE THREAD

**Issue by wangyu142857** [antvis/X6#1321]
官方示例地址： https://x6.antv.vision/zh/examples/showcase/practices#flowchart
正常场景：
![image](https://user-images.githubusercontent.com/24771813/132473056-bd7c96da-e351-4fd4-b79d-60c455c7aab4.png)

异常场景：
![image](https://user-images.githubusercontent.com/24771813/132473129-11daabc3-33c2-4822-9208-7282979106ec.png)

问题？有什么办法可以让两个节点靠近时依然正常显示？

**Comment by NewByVector** [comment]
可以尝试减小 `manhattan` 中 `step` 配置
