### ISSUE TITLE
cell dnd拖拽节点drop后不能显示子孙节点

### ISSUE THREAD

**Issue by 13085989291** [antvis/X6#1322]
问题：
cell dnd拖拽节点drop后不能显示子孙节点，只显示了父节点。

代码：
// 创建放置图元的画布
var testGraph = new X6.Graph({
        container: document.getElementById('test'),
        scroller: false, // 滚动画布
        mousewheel: {
          enabled: true,
          minScale: 0.4,
          maxScale: 2
        }, // 缩放画布
        panning: false,
        grid: 10,
        interacting: {
          nodeMovable: false
        }
      })
      testGraph.on('cell:mousedown', ({ e, cell, view }) => {
        const cloneCell = cell
        dnd.start(cell, e)
      })
// 节点鼠标按下后，开始拖动
const dnd = new X6.Addon.Dnd({
        target: this.graph, // 这里是拖动后放置节点的画布
        scaled: false,
        animation: true,
        getDragNode:(node) => node.clone({ deep: true }),
        getDropNode:(node) => node.clone({ deep: true }),
        validateNode(droppingNode, options) {
          _this.idArrs.push(droppingNode.id)
          return true
        }
      })

**Comment by 13085989291** [comment]
can you speak chinese？？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/X6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/X6] cell dnd拖拽节点drop后不能显示子孙节点 (#1322)





 
👋 @13085989291
 
Thanks for opening your first issue here! If you're reporting a 🐞 bug, please make sure you include steps to reproduce it.
 
To help make it easier for us to investigate your issue, please follow the contributing guidelines.
 
We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NewByVector** [comment]
可以这样处理：
```ts
graph.on('node:added', ({ node }) => {
  if (node.children) {
    node.children.forEach((child: Node) => {
      child.position(0, 0, { relative: true })
    })
  }
})
```
