### ISSUE TITLE
导出图片bug

### ISSUE THREAD

**Issue by frienkiss** [antvis/X6#1323]
![1631092033(1)](https://user-images.githubusercontent.com/28303439/132480792-c13ec69f-7ac5-439f-8ae6-606926455224.png)
图中组件为vue组件，字体居中，有borderRadius
![1631092143(1)](https://user-images.githubusercontent.com/28303439/132481016-c1903005-0189-4eec-a263-b0afdc64254c.png)
导出的png中，文字位置，borderRadius就消失了

**Comment by NewByVector** [comment]
这个应该是是样式一部分样式没有导出，可以参考这个 [demo](https://codesandbox.io/s/stylesheet-0y2f1?file=/src/app.tsx)

**Comment by NewByVector** [comment]
为了更高效解决 issue，先关闭当前 issue，如果还有问题，再提个 issue。
