### ISSUE TITLE
无法通过 setAttr 系列方法独立设置文字大小

### ISSUE THREAD

**Issue by iceytea** [antvis/X6#1326]
### Expected Behavior

当执行 node.setAttr('label/fontSize', CUSTOM_VAL) 时，文字大小可以发生变化

### Current Behavior
只修改文字大小时，文字大小不发生变化

### Possible Solution
在设置文字大小时，同时设置一个和之前不同的文字内容

### Steps To Reproduce

1. 打开如下页面：https://x6.antv.vision/zh/examples/node/native-node#rect
2. 复制下列内容，并替换页面中的代码
```js
import { Graph } from '@antv/x6'

const graph = new Graph({
  container: document.getElementById('container'),
  grid: true,
})

const node = graph.addNode({
  x: 40,
  y: 40,
  width: 120,
  height: 60,
  label: 'rect',
})


node.attr({
  label: { fill: 'blue', fontSize: 16, text: 'my lable' },
})

node.attr({
  label: {fontSize: 28},  
})
// 文字大小没有发生变化

node.attr('label', {
  fontSize: 32, text: 'my lable'
})
// 文字大小没有发生变化

node.attr('label', {
  fontSize: 40, text: 'my new lable'
})
// 当文字内容发生变化时，文字大小才发生变化


```

### Your Environment

- x6: [1.26.0]

**Comment by pipinet** [comment]
初始化展示的时候是同样的问题，所有的字都是比较大，但是从dom上看到font-size是有的，而且我修改了下源码，强制加上style也都不生效。
![image](https://user-images.githubusercontent.com/6096680/147946081-8c2592cb-1f54-4e45-836d-081c8ebf24cb.png)
