### ISSUE TITLE
连接桩在manhattan路由下, 两个节点距离较近的情况下, 会有小揪揪

### ISSUE THREAD

**Issue by Nsym7112** [antvis/X6#1327]
![企业微信截图_336e6bdb-ef5f-458b-a347-b03db8a868fd](https://user-images.githubusercontent.com/40933108/132643680-07a04069-bbf8-4b54-a9e4-99294c8ccb0b.png)

**Comment by NewByVector** [comment]
可以通过减小 `manhattan` 的 `step` 来解决
