### ISSUE TITLE
如何按比例打印，類似於保存為 PNG Rúhé àn bǐlì dǎyìn, lèisì yú bǎocún wèi PNG

### ISSUE THREAD

**Issue by verron16** [antvis/X6#1338]
你好，我正在使用你的優秀庫，我有一個關於打印的問題，有沒有一個功能可以類比於將圖像保存在PNG中的功能，即考慮當前比例的選擇，以便整個圖表會自動放在工作表上，而不是剪掉？我什至在源代碼中找到了 printPreview 方法。
Nǐ hǎo, wǒ zhèngzài shǐyòng nǐ de yōuxiù kù, wǒ yǒu yīgè guānyú dǎyìn de wèntí, yǒu méiyǒu yīgè gōngnéng kěyǐ lèibǐ yú jiāng tú xiàng bǎocún zài PNG zhōng de gōngnéng, jí kǎolǜ dāngqián bǐlì de xuǎnzé, yǐbiàn zhěnggè túbiǎo huì zìdòng fàng zài gōngzuò biǎo shàng, ér bùshì jiǎn diào? Wǒ shén zhì zài yuán dàimǎ zhōng zhǎodàole printPreview fāngfǎ.

**Comment by NewByVector** [comment]
```ts
export interface Options {
    size?: string
    sheet: Size
    sheetUnit?: Unit
    area?: Rectangle.RectangleLike
    page?: Page
    margin?: NumberExt.SideOptions
    marginUnit?: Unit
    padding?: NumberExt.SideOptions
    ready: (
      $pages: JQuery<HTMLElement>[],
      readyToPrint: ($pages: JQuery<HTMLElement>[] | false) => any,
      options: {
        sheetSize: SheetSize
      },
    ) => any
  }
```
这个是 print 支持的配置，如果你要支持按比例打印，应该配置 size 属性

**Comment by NewByVector** [comment]
为了高效管理 issue，我们暂时关闭这个 issue，如果还有未解决的问题，请开启新的 issue
