### ISSUE TITLE
在节点copy的时候，能递归更新节点的id，而不是复制出来的节点id和之前的一样

### ISSUE THREAD

**Issue by gezhicui** [antvis/X6#1339]
### Expected Behavior
在节点copy的时候，能递归更新节点的id，而不是复制出来的节点id和之前的一样

### Possible Solution
复制时递归更新新节点的节点id

### Additional Context
每个节点的数据要存在服务器，并且节点生成的id作为主键，如果id有冲突会有问题

**Comment by NewByVector** [comment]
为了高效沟通，这个 issue 暂时关闭，如果还有疑问，请新开一个 issue。

**Comment by itwmike** [comment]
节点ID能否不要重新生成？
