### ISSUE TITLE
✈️谁在使用 X6

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#1340]
### Expected Behavior

收集使用 X6 的团队或者公司，后续有可能在官网首页展示。欢迎在下面评论。

**Comment by iceytea** [comment]
请问必须是公开到外部的项目吗？

**Comment by BrunaDeLafel** [comment]
盒马产品体验技术部，内部中后台项目

**Comment by Eve-Sama** [comment]
产品：轻析, BI业务线产品
公司：[轻流](https://qingflow.com)
截图：
![图片](https://user-images.githubusercontent.com/30228406/133194291-18bbb413-1519-433c-b93d-491e9337322b.png)
