### ISSUE TITLE
Clipboard 的粘贴复制未按照实际传值进行偏移

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#1343]
### Expected Behavior

执行 Clipboard.paste 严格按照options的偏移参数进行偏移 

### Current Behavior

第一次执行paste 方法时按照options参数进行偏移 ，再次执行paste 方法+传递新偏移值未按照要求偏移。
```
graph.copy(cells)  // 复制 cells
graph.paste({offset:10}) // 偏移 10 
graph.paste({offset:20}) // 偏移还是 10
```
![f9f4bdd9201a501d6880ed804db3536](https://user-images.githubusercontent.com/22650893/133215185-1f0aa916-38bc-4336-a68f-d74b1f8a8972.png)

### Steps To Reproduce

官方demo
1. 第一次offset 调为10，然后复制 
![image](https://user-images.githubusercontent.com/22650893/133215631-f5d31898-bbfc-4f5d-a91b-bd70af8965c1.png)

2. 第二次offset 调为80，然后复制 ，偏移效果和第一次一样，此时偏移值为80
![image](https://user-images.githubusercontent.com/22650893/133215719-9b29423d-cfc7-4d67-91c6-84a5089c5d73.png)

3.第三次复制，此时偏移值才变为80
![image](https://user-images.githubusercontent.com/22650893/133215837-6522a0dc-26b8-4c21-ade8-d47d4f9333f4.png)

</p></details>

### Your Environment

-@antv/x6: [1.26.2]

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/pull/1350
