### ISSUE TITLE
路径动画设置的Zindex过高？节点无法覆盖，动画出现在节点之上

### ISSUE THREAD

**Issue by daigang666** [antvis/X6#1344]
![image](https://user-images.githubusercontent.com/42136433/133216468-7114fdf4-3865-4e8a-97bc-27ced938621c.png)
view.sendToken 生成的路径动画，出现在节点之上，更连线的ZIndex不是同一个级别

连线动画应当与连线的层级属于同一水平

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
参考这个demo：https://codesandbox.io/s/token-sd2v9
