### ISSUE TITLE
通过 setChildren 设置的父子关系，在子节点无法获取父节点

### ISSUE THREAD

**Issue by iceytea** [antvis/X6#1352]
### Expected Behavior

可以从子节点的 getParent() 获取父节点

### Current Behavior

通过 setChildren 设置的父子关系，在子节点无法获取父节点

### Steps To Reproduce

代码清单：
```js
import { Graph } from '@antv/x6'

const graph = new Graph({
  container: document.getElementById('container'),
  grid: true,
})

// row 1
// -----
const node1 = graph.addNode({
  shape: 'circle',
  x: 40,
  y: 40,
  width: 60,
  height: 60,
  label: 'circle',
})

const node2 = graph.addNode({
  shape: 'circle',
  x: 200,
  y: 40,
  width: 60,
  height: 60,
  label: 'circle',
  attrs: {
    body: {
      fill: '#efdbff',
      stroke: '#9254de',
    },
  },
})

node1.setChildren([node2])
console.log(node1.children, node1.parent) //[Circle] undefined
console.log(node2.children, node2.parent) //undefined undefined
```
粘贴到 https://x6.antv.vision/zh/examples/node/native-node#circle

### Your Environment

- x6: [1.26.1]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
setChildren 只是单向绑定，如果需要双向的话使用 `addChild`

**Comment by iceytea** [comment]
1. 请问这里单向绑定的设计初衷是啥？有什么场景会出现单向绑定？

**Comment by NewByVector** [comment]
父子关系本身只要一方定义关系就行。如果要松散的关系，用 setParent和setChildren，如果需要双方都记录关系，用addChild

**Comment by NewByVector** [comment]
这个问题不知道还有没有疑惑，我先关闭 issue 了
