### ISSUE TITLE
strict: true 时无法框选面积为 0 的 cell

### ISSUE THREAD

**Issue by OpportunityLiu** [antvis/X6#1354]
### Expected Behavior
可以框选面积为 0 的 cell

### Current Behavior
strict: true 时无法框选面积为 0 的 cell

### Steps To Reproduce

https://codesandbox.io/s/agitated-blackburn-m2nie?file=/src/app.tsx
```
strict: true,
rubberband: true,
rubberEdge: true,
```
1. 无法框选水平连接线
2.  设置  useCellGeometry: true 后还无法框选左上角宽高均设为 0 的节点

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: 1.26.2
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by OpportunityLiu** [comment]
我看计算包含的时候这样写了，目的是啥呢？

https://github.com/antvis/X6/blob/4129ce94f0098b6451ed20dfe4e07827fc85a730/packages/x6/src/geometry/rectangle.ts#L466-L469

https://github.com/antvis/X6/blob/4129ce94f0098b6451ed20dfe4e07827fc85a730/packages/x6/src/geometry/rectangle.test.ts#L345-L350

**Comment by OpportunityLiu** [comment]
一条水平或垂直的连接线面积就是 0 啊

**Comment by OpportunityLiu** [comment]
线是平的就选不中，拐个弯就能选中，不是很奇怪吗。。

**Comment by daigang666** [comment]
这个我提了一个bug了，没想到你还查源码里面去了，哈哈哈哈哈
