### ISSUE TITLE
节点的visible属性对vue自定义组件生命周期的影响

### ISSUE THREAD

**Issue by xinxincat** [antvis/X6#1357]
### Expected Behavior
期望在画布添加vue自定义节点的时候，vue的生命周期只执行一次

### Current Behavior
在画布添加vue自定义节点，对节点进行visible的true和false切换，会发现 create和mounted 会重复执行

在实际应用中，我们会在create做eventbus 的监听，在进行节点的visible的切换，由于生命周期的重复执行，会导致eventbus的监听累加

**Comment by NewByVector** [comment]
因为 x6 在实现节点的 visible 是通过移除和新增节点来实现的，这就不可避免重新初始化组件了，外部设计的时候需要考虑到这一点，比如在实现 eventbus 监听的 时候，需要考虑监听之前取消监听等实现。
