### ISSUE TITLE
如何自定义图形圆角，自定义阴影

### ISSUE THREAD

**Issue by NexxLuo** [antvis/X6#136]
如何自定义图形圆角，rx、ry数值，目前只有rounded一个布尔属性，无法精确控制圆角弧度；
自定义阴影样式渲染，目前默认的阴影样式有点丑，能否自定义。

**Comment by NewByVector** [comment]
在图形的属性中可以设置rx和ry来配置圆角。如果有自定义图形阴影的场景，请描述一下场景，从新提一个issue。
