### ISSUE TITLE
uni-app 整合ANTV-X6

### ISSUE THREAD

**Issue by ldong1204** [antvis/X6#1360]
uni-app 整合ANTV-X6

网页端做了一个节点流程图，现在要把流程图搬运到移动端，做了很多准备工作，但是今天突然发现import { Graph } 的时候编译很慢，到了开发者工具发现没找到这个组件？请问现在antv-x6是不是不支持uni-app的整合，官网文档也没有相关说明，还是我引用的方式出错了，可不可以提供一个demo。

另外发现有一个相关的系列F6可以做这个，但是不支持html渲染，做不了我们的需求，请问有没有支持html渲染的移动端做流程图的库

**Comment by Tabris7777** [comment]
通过webview

**Comment by NewByVector** [comment]
在 H5 中使用 X6 应该是可以的，之前有社区伙伴实现过，能详细描述下你的问题吗，从上面描述看不出具体问题。
