### ISSUE TITLE
关于antv x6关于Node with name 'react-shape' does not exist.的错误

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1361]
我在同样的项目中,仅仅只是路径不同,其中一个报错这个
问题在于另一个项目也是同样的代码,却不报错
两个项目中都没有import '@antv/x6-react-shape'这个
问题已经解决, 我就是奇怪为什么同样的代码,一个报错,一个不报

![image](https://user-images.githubusercontent.com/33592850/133870041-62fb213f-2ba1-4f74-b00d-712d8c227d0b.png)

**Comment by superTigery** [comment]
我也遇到了这个错误 
你是自定义react节点吗?能看看代码吗?

**Comment by cheng-xiaofeng** [comment]
@superTigery 
顶部添加import '@antv/x6-react-shape  即可, 我就是不明白为什么

**Comment by superTigery** [comment]
@cheng-xiaofeng  你是直接往画布上添加的react节点吗?
我加了import '@antv/x6-react-shape 也报错,

**Comment by cheng-xiaofeng** [comment]
@superTigery 不是, createNode({shape: 'react-shape'}), 这个报错

**Comment by superTigery** [comment]
我也是这个报错~ 
然后试了下直接往画布添加react节点, 也是包错

**Comment by cheng-xiaofeng** [comment]
我是这么写的const r1 = graph.createNode({
      x: 320,
      y: 260,
      width: 150,
      height: 300,
      shape: 'react-shape',
      component: <NodeComponent graph={graph}></NodeComponent>
    })

参照这个
https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-react-%E8%8A%82%E7%82%B9

**Comment by superTigery** [comment]
是的 我也是这样,我检查下我的依赖

**Comment by cheng-xiaofeng** [comment]
没有,这个是新加的依赖. 我独立的那个项目不用引入也不报错, 这个不引入就报错

**Comment by NewByVector** [comment]
出现这个错误是因为项目没有引入 `@antv/x6-react-shape`, 如果引入还不能解决，可以尝试更新依赖。

**Comment by superTigery** [comment]
> 出现这个错误是因为项目没有引入 `@antv/x6-react-shape`, 如果引入还不能解决，可以尝试更新依赖。
   嗯  我更新了依赖 就好了
