### ISSUE TITLE
边Edge支持添加自定义组件（Vue组件）的label吗？

### ISSUE THREAD

**Issue by Hzw576816** [antvis/X6#1362]

**Comment by NewByVector** [comment]
x6 提供 onEdgeLabelRendered 接口，这里面支持 html/react/vue 来定义 label

**Comment by xieqingchun** [comment]
只看到了react的案例，有vue的案例吗

**Comment by Xu-Catherine** [comment]
请问是否支持vue来定义label？能提供个案例吗？

**Comment by Hxmic** [comment]
@NewByVector   有没有想过的案例？ 我们参考下
