### ISSUE TITLE
Making the graph/canvas fullscreen

### ISSUE THREAD

**Issue by e6vk4** [antvis/X6#1366]
### Expected Behavior
When the graph parent container is made full screen the graph should expand to the new width and height set

### Current Behavior
When the graph parent container is made full screen the graph retains its original width and height

```
<div ref="container" class="lineage">
    <div
       :style="{
                width: `${isFullscreen ? '100vw - 1px' : 'calc(100vw - 420px)'}`,
                height: `${isFullscreen ? '100vh - 1px' : 'calc(100vh - 150px)'}`,
            }"
        ref="graphContainer"
     ></div>
</div>
```

```
// when the fullscreen button is clicked this function gets called ... the container ref is passed to it
const fullscreen = (targetEle) => {
       isFullscreen.value = !isFullscreen.value
        targetEle.value.requestFullscreen()
}
```

**Comment by e6vk4** [comment]
Or is there a better way to make the graph fullscreen .... can't find a fullscreen implementation anywhere

Awesome library by the way

**Comment by e6vk4** [comment]
A suggestion is to provide a method on the graph if there is no existing way to do it

```
const height: number = 800
const width: number = 800

graph.updateHeight(height)
graph.updateWidth(width)
```

**Comment by iceytea** [comment]
> A suggestion is to provide a method on the graph if there is no existing way to do it
> 
> ```
> const height: number = 800
> const width: number = 800
> 
> graph.updateHeight(height)
> graph.updateWidth(width)
> ```

```js
graph.size(width, height)
```

try this?

**Comment by NewByVector** [comment]
@e6vk4 you can use `graph.resize(width, height)`
