### ISSUE TITLE
请问在vue里如何在渲染链接桩的时候动态渲染tooltip

### ISSUE THREAD

**Issue by chris-mask** [antvis/X6#1372]
请问在vue里如何在渲染链接桩的时候动态渲染tooltip，文档上面react是这样的
const graph = new Graph({
container: this.container,
onPortRendered(args) {
const selectors = args.contentSelectors
const container = selectors && selectors.foContent
if (container) {
ReactDOM.render(
<Tooltip title="port">
          <div className="my-port" />
        </Tooltip>,
container,
)
}
},
})

提出过此解决方法
const vm = new Vue({
   el: '', // 你的内容模板
})
container.appendChild(vm.$el)

但是尝试过不行，不知道是不是写法有问题，请问能不能详细点解释下
![image](https://user-images.githubusercontent.com/21608359/134480235-054dff4b-168c-44a5-acbe-168df6b08b61.png)
![image](https://user-images.githubusercontent.com/21608359/134480268-fb3cda81-4515-4041-bfd5-98f2b83009d6.png)

**Comment by NewByVector** [comment]
这个是我在 vue 中的实践，既能保持高性能，使用起来也挺方便。
https://codesandbox.io/s/vue-tooltip-jlx6n

**Comment by LZCaaT** [comment]
> 这个是我在 vue 中的实践，既能保持高性能，使用起来也挺方便。 https://codesandbox.io/s/vue-tooltip-jlx6n

感谢此贴，解决问题

**Comment by LuckyLucien** [comment]
> 这个是我在 vue 中的实践，既能保持高性能，使用起来也挺方便。 https://codesandbox.io/s/vue-tooltip-jlx6n

发现个问题，多次快速划过桩之后，tooltip就不能再显示了
