### ISSUE TITLE
关于父节点包裹子节点后绘制边的问题(bug)

### ISSUE THREAD

**Issue by Mr-clown2040** [antvis/X6#1376]
连接桩拉出来的边呈现效果会有偏差（ps:两个图的连接桩source和target的位置都是一致的）,没有外层节点包裹的是正常
![issue](https://user-images.githubusercontent.com/35453112/135014540-db75a9c7-afc2-40ec-b1ec-a5c26e4a6665.png)
的

**Comment by NewByVector** [comment]
可以使用 `manhattan` 路由中的配置，在计算路由的时候忽略父节点的存在。
