### ISSUE TITLE
点击节点时，为什么需要通过mouseup事件来阻止事件冒泡

### ISSUE THREAD

**Issue by frontendhz** [antvis/X6#1380]
背景：我们的graph在选中某个节点`graph.on('node:selected')`后会高亮这个节点。但对于内部包含按钮的节点，我们希望点击这个按钮后，只执行按钮上的逻辑，而不需要高亮这个节点。

一开始我们以为只需要阻止按钮上的click事件冒泡就可以了，但是后来翻阅issues才发现其实是要阻止mouseup事件。

一个问题❓：为什么node:click 和node: selected事件会绑定到mouseup事件上呢
一个建议❤️：官网上并没有地方明确指出阻止点击冒泡需要阻止mouseup事件，如果让大家自行翻阅issue来解决的话，效率太低，建议这块内容在官网上补充一下（也有可能我没发现，如果官网有写请告之一下~）

**Comment by NewByVector** [comment]
1. X6 中节点的 `click` 的事件是通过 `mousedown + mouseup` 模拟实现，
2. ndoe 的 `select` 触发也是在 `mouseup` 事件中
3. 你这个 issue 正好作为后面开发人员定位该问题查阅的资料
