### ISSUE TITLE
连接线起始点、终止点的位置坐标问题

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#1383]
### Expected Behavior
连接线起始点、终止点的位置问题

### Steps To Reproduce
strokeWidth = ‘1’ 终点坐标的是链接桩圆心位置
strokeWidth = ‘10’ 为什么终点坐标偏离链接桩圆心坐标？是否有问题？
strokeWidth = ‘50’ 偏离的更远了 。

目前使用的strokeWidth =‘4’ 导致连接线看上去没有连接到图形
![image](https://user-images.githubusercontent.com/22650893/135380997-26ff47e9-7f48-4dbd-b424-32492ac4575c.png)

![image](https://user-images.githubusercontent.com/22650893/135381652-9f722ca1-21d9-429e-8ad5-bc8562e469db.png)

![image](https://user-images.githubusercontent.com/22650893/135382045-7842ecd8-9a13-436e-a22f-7d617be22721.png)

### Your Environment

-@antv/x6: [1.26.2]

**Comment by NewByVector** [comment]
连线宽度修改，相应的箭头的 `size` 也需要修改：
```ts
graph.addEdge({
  source: [50, 50],
  target: {
    cell: source,
    port: '1'
  },
  attrs: {
    line: {
      strokeWidth: 30,
      targetMarker: {
        name: 'block',
        size: 30,
        offset: 0,
      }
    }
  }
})
```
