### ISSUE TITLE
怎么修改连线样式...

### ISSUE THREAD

**Issue by ThreeLambs** [antvis/X6#1385]
没有vue版本的吗？我现在用的umd模式。

- 选中Node（node:click）之后就无法触发 node:mouseleave 了。
- 怎么修改Router.
我尝试  this.graph.prop({ connecting: { router: _this.router}})没有此方法,，那么怎么全局修改连线样式，
总不能选中一个Edge改一个吧，太麻烦。
- 怎么实现下面这张图上的炫酷效果，没找到demo呢。
<img src="https://raw.githubusercontent.com/antvis/X6/8151c07909cf8ed648bad9e9ac1c78f0d2992e20/flow.svg">

**Comment by NewByVector** [comment]
1. selecting中配置 { pointerEvents: 'none' }
2. 修改 router 需要通过 edge.setRouter
3. 这个图就是一个 svg 呀，显示网页源代码就可以看到
