### ISSUE TITLE
当stencil里group的node超过四个时不显示滚动条

### ISSUE THREAD

**Issue by mjdxyr** [antvis/X6#1392]
我使用教程“拖拽 Dnd”里的示例进行修改，在group里面添加了一个node，这样group里有了五个node，但是不自动显示滚动条，我还是在搜索框里随便输入了字符才出现滚动条。
![2021-10-01 19-14-10 的屏幕截图](https://user-images.githubusercontent.com/36231427/135611121-86e5dc7a-ad52-4e44-ab1e-d76faaf38690.png)
![2021-10-01 19-15-03 的屏幕截图](https://user-images.githubusercontent.com/36231427/135611156-41dce04a-d01a-41c6-abd4-11821b7a8029.png)

**Comment by NewByVector** [comment]
这里是因为固定了 `stencilGraphHeight` 的高度所致，你可以修改这个配置 `stencilGraphHeight` 为 0，这样的话就可以自适应高度了。
