### ISSUE TITLE
能否根据data来改变节点或边的样式

### ISSUE THREAD

**Issue by CherishIt** [antvis/X6#1406]
希望能在不同data的情况下展示不同的样式。

节点的话，使用react渲染可以获取data来展示；但一直没找到根据data定制边样式的方法

**Comment by NewByVector** [comment]
改变边的样式通过修改其  `attr`，如果需要通过 data 来驱动的话，可以监听边的 `edge:change:data` 事件，在事件中修改边的 `attr`
