### ISSUE TITLE
node A 触发了node:mousedown  node B的node:mouseenter、node:mouseleave都不会触发

### ISSUE THREAD

**Issue by jjojunj** [antvis/X6#1407]
### Expected Behavior
预期的就是其他的事件不影响

### Current Behavior
现在是事件干扰了

### Steps To Reproduce

this.graph.on('node:mousedown', ({ e, x, y, node, view }) => {
    this.setState({isNodeClick: true})
})
this.graph.on('node:mouseenter', ({ e, x, y, node, view }) => {
    console.info(e.target.parentNode.textContent)
})
this.graph.on('node:mouseleave', ({ e, x, y, node, view }) => {
    console.info(e.target.parentNode.textContent)
})

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
提供一下可复现的 demo？

**Comment by jjojunj** [comment]
就这个&nbsp; 加了官网 demo的 "dagre": "^0.8.5",




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/X6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月8日(星期五) 晚上7:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/X6] node A 触发了node:mousedown  node B的node:mouseenter、node:mouseleave都不会触发 (#1407)





 
提供一下可复现的 demo？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jjojunj** [comment]
import React from "react";
import { Graph,Shape,Cell, Node, Color, Dom } from ***@***.***/x6';
import dagre from "dagre";

import "./Step.less"

class Step extends React.Component {
    state = {
        isNodeClick: false
    }
    refContainer = React.createRef();
    graph;
    componentDidMount() {
        this.graph = new Graph({
            container: this.refContainer.current,
            grid: {
                size: 10,      // 网格大小 10px
                visible: true, // 渲染网格背景
            },
            scroller: true,
            snapline: true,
            interacting: false,
        });

        // 自定义边
        Graph.registerEdge(
            'org-edge',
            {
                zIndex: -1,
                attrs: {
                    line: {
                        stroke: '#585858',
                        strokeWidth: 3,
                        sourceMarker: null,
                        targetMarker: null,
                    },
                },
            },
            true,
        )

        // 自定义节点
        Graph.registerNode(
            'org-node',
            {
                width: 200,
                height: 40,
                markup: [
                    {
                        tagName: 'rect',
                        attrs: {
                            class: 'card',
                        },
                    },
                    {
                        tagName: 'image',
                        attrs: {
                            class: 'image',
                        },
                    },
                    {
                        tagName: 'text',
                        attrs: {
                            class: 'rank',
                        },
                    },
                    {
                        tagName: 'text',
                        attrs: {
                            class: 'name',
                        },
                    },
                    {
                        tagName: 'g',
                        attrs: {
                            class: 'btn add',
                        },
                        children: [
                            {
                                tagName: 'circle',
                                attrs: {
                                    class: 'add',
                                },
                            },
                            {
                                tagName: 'text',
                                attrs: {
                                    class: 'add',
                                },
                            },
                        ],
                    },
                    {
                        tagName: 'g',
                        attrs: {
                            class: 'btn del',
                        },
                        children: [
                            {
                                tagName: 'circle',
                                attrs: {
                                    class: 'del',
                                },
                            },
                            {
                                tagName: 'text',
                                attrs: {
                                    class: 'del',
                                },
                            },
                        ],
                    },
                ],
                attrs: {
                    '.card': {
                        rx: 10,
                        ry: 10,
                        refWidth: '100%',
                        refHeight: '100%',
                        fill: '#FFF',
                        stroke: '#000',
                        strokeWidth: 0,
                        pointerEvents: 'visiblePainted',
                    },
                    '.name': {
                        refX: 0.55,
                        refY: 0.35,
                        fontFamily: 'Arial',
                        fontSize: 14,
                        fontWeight: '600',
                        textAnchor: 'end',
                    },
                    '.btn.add': {
                        refDx: -16,
                        refY: 20,
                        event: 'node:add',
                    },
                    '.btn.del': {
                        refDx: -44,
                        refY: 20,
                        event: 'node:delete',
                    },
                    '.btn &gt; circle': {
                        r: 10,
                        fill: 'transparent',
                        stroke: '#333',
                        strokeWidth: 1,
                    },
                    '.btn.add &gt; text': {
                        fontSize: 20,
                        fontWeight: 800,
                        stroke: '#000',
                        x: -5.5,
                        y: 7,
                        fontFamily: 'Times New Roman',
                        text: '+',
                    },
                    '.btn.del &gt; text': {
                        fontSize: 28,
                        fontWeight: 500,
                        stroke: '#000',
                        x: -4.5,
                        y: 6,
                        fontFamily: 'Times New Roman',
                        text: '-',
                    },
                },
            },
            true,
        )

        const parent = this.graph.addNode({
            width: 200,
            height: 40,
            zIndex: 1,
            attrs: {
                body: {
                    fill: 'transparent', // 背景颜色
                    stroke: '#ccc',  // 边框颜色
                }
            }
        })


        parent.addChild(this.createNode('主单据计费'));
        parent.addChild(this.createNode('主单据合并计费'));

        this.graph.on('node:add', ({ e, node }) =&gt; {
            e.stopPropagation()
            const bg = Color.randomHex()
            const member = this.createNode(
                'Employee'/*,
                Color.invert(bg, true),*/
            )
            this.graph.freeze()
            this.graph.addCell([member, this.createEdge(node, member)])
            this.layout()
        })

        this.graph.on('node:delete', ({ e, node }) =&gt; {
            e.stopPropagation()
            this.graph.freeze()
            this.graph.removeCell(node)
            this.layout()
        })

        this.graph.on('cell:mouseup', ({ e, x, y, node, view }) =&gt; {
            this.setState({isNodeClick: false})
        })
        this.graph.on('node:mousedown', ({ e, x, y, node, view }) =&gt; {
            this.setState({isNodeClick: true})
        })
        this.graph.on('node:mouseenter', ({ e, x, y, node, view }) =&gt; {
            console.info(e.target.parentNode.textContent)
        })
        this.graph.on('node:mouseleave', ({ e, x, y, node, view }) =&gt; {
            console.info(e.target.parentNode.textContent)
        })

        this.layout();
    }

    createNode = (
        name: string,
        background= '#31d0c6',
        textColor = '#000',
    ) =&gt; {
        return this.graph.createNode({
            shape: 'org-node',
            attrs: {
                '.card': { fill: background },
                '.name': {
                    fill: textColor,
                    text: Dom.breakText(name, { width: 160, height: 25 }),
                },
                '.btn &gt; circle': { stroke: textColor },
                '.btn &gt; text': { fill: textColor, stroke: textColor },
            },
        })
    }

    createEdge = (source: Cell, target: Cell) =&gt; {
        return this.graph.createEdge({
            shape: 'org-edge',
            source: source,
            target: target,
        })
    }

    male =
        'https://gw.alipayobjects.com/mdn/rms_43231b/afts/img/A*kUy8SrEDp6YAAAAAAAAAAAAAARQnAQ'
    female =
        'https://gw.alipayobjects.com/mdn/rms_43231b/afts/img/A*f6hhT75YjkIAAAAAAAAAAAAAARQnAQ'
// 布局方向
    dir = 'LR' // LR RL TB BT

    layout = () =&gt; {
        const nodes = this.graph.getNodes();
        const edges = this.graph.getEdges()
        const g = new dagre.graphlib.Graph()
        g.setGraph({ rankdir: this.dir, nodesep: 16, ranksep: 16 })
        g.setDefaultEdgeLabel(() =&gt; ({}))

        const width = 260
        const height = 90
        nodes.forEach((node) =&gt; {
            if (!node.children) {
                g.setNode(node.id, { width, height })
            }

        })

        edges.forEach((edge) =&gt; {
            const source = edge.getSource()
            const target = edge.getTarget()
            g.setEdge(source.cell, target.cell)
        })

        dagre.layout(g)

        this.graph.freeze()

        g.nodes().forEach((id) =&gt; {
            const node = this.graph.getCell(id);
            if (node) {
                const pos = g.node(id)
                node.position(pos.x, pos.y)
            }
        })

        edges.forEach((edge) =&gt; {
            const source = edge.getSourceNode();
            const target = edge.getTargetNode();
            const sourceBBox = source.getBBox();
            const targetBBox = target.getBBox();

            console.log(sourceBBox, targetBBox);

            if ((this.dir === 'LR' || this.dir === 'RL') &amp;&amp; sourceBBox.y !== targetBBox.y) {
                const gap =
                    this.dir === 'LR'
                        ? targetBBox.x - sourceBBox.x - sourceBBox.width
                        : -sourceBBox.x + targetBBox.x + targetBBox.width
                const fix = this.dir === 'LR' ? sourceBBox.width : 0
                const x = sourceBBox.x + fix + gap / 2
                edge.setVertices([
                    { x, y: sourceBBox.center.y },
                    { x, y: targetBBox.center.y },
                ])
            } else if (
                (this.dir === 'TB' || this.dir === 'BT') &amp;&amp;
                sourceBBox.x !== targetBBox.x
            ) {
                const gap =
                    this.dir === 'TB'
                        ? targetBBox.y - sourceBBox.y - sourceBBox.height
                        : -sourceBBox.y + targetBBox.y + targetBBox.height
                const fix = this.dir === 'TB' ? sourceBBox.height : 0
                const y = sourceBBox.y + fix + gap / 2
                edge.setVertices([
                    { x: sourceBBox.center.x, y },
                    { x: targetBBox.center.x, y },
                ])
            } else {
                edge.setVertices([])
            }
        })

        this.graph.unfreeze();
        //this.graph.centerContent()
    }

    render() {
        return (
            <div className="app-content" ref={this.refContainer} /&gt;
        );
    }
}

export default Step;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/X6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月9日(星期六) 上午9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/X6] node A 触发了node:mousedown  node B的node:mouseenter、node:mouseleave都不会触发 (#1407)





 
@jjojunj  提供一个 codesnabox 复现一下问题？你的描述看不出具体问题
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NewByVector** [comment]
我用你的代码在本地测试了一下是好的，检查一下是否其他因素影响了。

**Comment by jjojunj** [comment]
这个就奇怪了， 不过没事我其实就是做一个简单的思维导图， 我自己直接实现了一套，我需要做一个节点拖动到另外一个节点当子节点， 我自己搞了一套用svg加dnd搞了
