### ISSUE TITLE
重新绘制画布, 修改数据

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1413]
![image](https://user-images.githubusercontent.com/33592850/136760110-05359c72-ec5c-4ba1-82d0-4c8f2efdfb66.png)
我想在修改右边的时候, 画布中的数据也实时更新, 我调用了cell.setData(), 但是画布中的数据只修改了一次, 第二次就不变了, 这该怎么做

**Comment by cheng-xiaofeng** [comment]
> `setData` 方法需要每次传入的对象不一致，是不是传入了同一个对象？

![image](https://user-images.githubusercontent.com/33592850/136773164-c47c301f-1cdd-41d7-8465-52785bf13cff.png)
这样写的, fieldJson是数据组, 每一项就是一条数据

**Comment by cheng-xiaofeng** [comment]
> 搞个 codesanbox 看下，你这样给代码看不出问题

调用setData之后, 数据都没有进入node节点这个自定义的组件中(react组件)

**Comment by komagic** [comment]
onEdgeLabelRendered 的组件 setData后画面不会变，只有拖动了才能刷新。。

graph 的update 函数去哪里了
