### ISSUE TITLE
如何切换箭头，可更改箭头

### ISSUE THREAD

**Issue by 4color** [antvis/X6#1415]
比如要画了两个Node,也通过链接桩把线手动连起来了。

现在要要切其它中的一条线的类型，应该如何操作？

![image](https://user-images.githubusercontent.com/20277116/136791850-21e96a05-f2a9-4d5a-a532-7f2b97ed6dd0.png)

**Comment by NewByVector** [comment]
```ts
edge.attr('line/targetMarker', {
  // 箭头配置
})
```
