### ISSUE TITLE
registerVueComponent 注册的时候，如何在添加节点的时候，初始化赋值

### ISSUE THREAD

**Issue by 4color** [antvis/X6#1416]
我用registerVueComponent 注册一个组件
然后会用这个组件创建很多个node。

每个node的初始化数据都不一样，这样如何实现？

官方的count demo里是有事情的时候，才得到这个值。

`Graph.registerVueComponent(
  "count-component",
  {
    template: `<count></count>`,
    components: {
      Count,
    },
  },
  true
);`

`    graph.addNode({
      id: "1",
      shape: "vue-shape",
      x: 200,
      y: 150,
      width: 150,
      height: 100,
      component: "count-component",
      data: {
        num: 2,
      },
    });`

**Comment by mosuzi** [comment]
不是获取数据，而是在创建节点的时候直接赋予节点数据 @NewByVector
