### ISSUE TITLE
通过dnd拖拽生成的节点使用node-edit修改文字失败

### ISSUE THREAD

**Issue by 695648896** [antvis/X6#1420]
### Expected Behavior

希望修改文字成功

### Current Behavior

修改文字失败
复现链接：https://codesandbox.io/s/adoring-mahavira-5rlbc

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
更推荐的使用方式是：等节点添加完成，再在节点上添加工具。

**Comment by 695648896** [comment]
> 更推荐的使用方式是：等节点添加完成，再在节点上添加工具。

你好，新年快乐～，我按楼上的方式是成功改写了label的text，但是没太理解更推荐的使用方式，上面给出的代码里是在节点已经生成后，只有双击才会在节点上添加工具，这时候节点已经生成了。或许你指的更推荐的使用方式是？

**Comment by NewByVector** [comment]
@695648896 我理解错了你的问题，@tsunamiShi 给的解决方案是对的。
