### ISSUE TITLE
X6.min.js 中打入了 jQuery 库，如何去除 X6 中的 jQuery，和项目的jQuery冲突了，造成了不少问题？

### ISSUE THREAD

**Issue by yswang0927** [antvis/X6#1423]
在项目中引入 https://cdn.jsdelivr.net/npm/@antv/x6/dist/x6.js 后发现项目出现了不少问题，分析后发现是 X6 中自带的 jQuery 库和项目的 jQuery库冲突造成的， 如何去除 X6 中的 jQuery ?

**Comment by garygao12580** [comment]
同样的问题，能否去除jQuery的依赖呢？

**Comment by NewByVector** [comment]
@garygao12580 @yswang0927 下个版本会去掉 jquery 依赖，和 https://github.com/antvis/X6/issues/97 重复。
