### ISSUE TITLE
自定义react节点 shape: 'react-shape'在tsx中使用报错，js中正常

### ISSUE THREAD

**Issue by houyanmin** [antvis/X6#1428]
已经引入过x6-react-shape

Uncaught Error: Node with name 'react-shape' does not exist.
at Registry.onNotFound (registry.ts:97)
at Function.create (node.ts:1179)
at Model.createNode (model.ts:246)
at Model.addNode (model.ts:240)
at Graph.addNode (graph.ts:147)
at Example.startDrag (app.tsx:306)
at onMouseDown (app.tsx:336)
...

**Comment by edejin** [comment]
Same issue
https://codesandbox.io/s/hh7i6o

**Comment by edejin** [comment]
It looks like webpack or babel minification error.
Currently would be enough to add any usage of `ReactShape`
As example `console.log(ReactShape.name);`

**Comment by ruslanchek** [comment]
You can fix this by manually registering the react-shape node. 

```typescript
import { ReactShape } from '@antv/x6-react-shape';
Graph.registerNode('react-shape', ReactShape, true);```

**Comment by qiufeihong2018** [comment]
@qiufeihong2018 已解决
