### ISSUE TITLE
希望能提供方法能触发节点的resizing状态，目前windows下无法启动项目调试，希望官方提供

### ISSUE THREAD

**Issue by daigang666** [antvis/X6#1430]
希望能提供方法能触发节点的resizing状态

节点的resizing状态只能通过点击触发

**Comment by daigang666** [comment]
外部触发父节点进入resizing状态，调整大小之后将父节点覆盖范围的子节点建立父子关系，api能触发状态还是有必要的，只能插件写死点击触发还是有点僵硬

**Comment by iceytea** [comment]
https://github.com/antvis/X6/issues/809 
windows 可以用 wsl

**Comment by syvn** [comment]
如果需要取消节点的resizing状态呢? 应该怎么处理?
