### ISSUE TITLE
右键自定义菜单之后，tojson保存数据，然后根据json使用formjosn回显报错

### ISSUE THREAD

**Issue by MorningStarHu** [antvis/X6#1433]
<img width="1144" alt="111" src="https://user-images.githubusercontent.com/31729631/137241467-bb9d9338-46d7-44f5-880b-33da6a5225c9.png">

**Comment by MorningStarHu** [comment]
@https://x6.antv.vision/zh/examples/edge/tool#context-menu
直接把这里的案例cell使用toJSON使用保存，然后formJSON还原，控制台报错一样。 @NewByVector

**Comment by helloworldmygithub** [comment]
遇到了同样的问题，报错都一样，请问您是什么解决的呢 @MorningStarHu

**Comment by helloworldmygithub** [comment]
![image](https://user-images.githubusercontent.com/37649395/167232535-2463c942-6f12-41a4-883f-ca0eab8f5ee4.png)
@NewByVector
