### ISSUE TITLE
When the cell can be selected but the multi-select box is not displayed, moving the parent node will cause other nodes to move deviation

### ISSUE THREAD

**Issue by halodong** [antvis/X6#1435]
```js
this.graph = new Graph({
      container: this.container,
      grid: { visible: true },
      selecting: {
        enabled: true,
        rubberband: true,
        showNodeSelectionBox: false
      },
    })
```
### Expected Behavior
Select all nodes, drag the parent node, the coordinate changes normally

### Current Behavior

When the cell can be selected but the multi-select box is not displayed, moving the parent node will cause other nodes to move deviation

### Steps To Reproduce

Demo: [https://codesandbox.io/s/loving-hofstadter-v04ow?file=/src/app.tsx:286-391](https://codesandbox.io/s/loving-hofstadter-v04ow?file=/src/app.tsx:286-391)
1. ...Select all three nodes
2. ...Move the parent node
3. ...circle node abnormal coordinate changes

### Your Environment

- x6: [latest]
- OS: [e.g. Windows 10 Professional Edition 21H1]
- Browser: [e.g. chrome 94.0.4606.81]

**Comment by halodong** [comment]
> By default, x6 allows the parent node to move and the child node to follow, regardless of selection.

Box selects three nodes, among which the circle node is the node with no parent-child relationship. However, when the parent node is moved, the coordinates of the circle node are abnormal.

You can set `showNodeSelectionBox` to `true`, contrast behavior

**Comment by NewByVector** [comment]
There is a problem here, thank you for pointing it out.

**Comment by yahiaouik** [comment]
Hello !
I am facing the same problem.
When I'm moving multi-selected nodes, selected nodes position change anormaly.

https://user-images.githubusercontent.com/43521458/152003870-f813f0ee-a2b4-4bad-930b-18dd880417d8.mp4

Unlike the previous exemple, there is no parent-child relationship between nodes.
It is not a systematic behavior.

Here is my graph definition :

```
const newGraph: Graph = new Graph({
      autoResize: true,
      container: document.getElementById('Canvas'),
      keyboard: {
        enabled: true,
      },
      mousewheel: {
        enabled: true,
      },
      panning: {
        enable: true,
      },
      selecting: {
        enabled: true,
        multiple: true,
        rubberband: true,
        movable: true,
        modifiers: ['shift'],
      },
      scroller: {
        enabled: true,
        pannable: true,
      },
      snapline: true,
      clipboard: {
        enabled: true,
      }
    });
```
Is there any way to fix the problem ?

### Environment
x6: [latest]
OS: [ubuntu 20]
Browser: [chromium 97.0.4692.99  ]

**Comment by Benjaminrivard** [comment]
Please consider reopening this issue as it still occurs in our application
