### ISSUE TITLE
方法 printPreview

### ISSUE THREAD

**Issue by verron16** [antvis/X6#1437]
printPreview 方法的工作很奇怪，在打印時，圖表被工作表裁剪並且沒有縮放，圖表不適合併且沒有在工作表上縮放。是否可以通過類比以 PNG 保存圖形來使其工作？系統本身縮放和居中圖像的位置
PrintPreview fāngfǎ de gōngzuò hěn qíguài, zài dǎyìn shí, túbiǎo bèi gōngzuò biǎo cáijiǎn bìngqiě méiyǒu suōfàng, túbiǎo bùshì hébìng qiě méiyǒu zài gōngzuò biǎo shàng suōfàng. Shìfǒu kěyǐ tōngguò lèibǐ yǐ PNG bǎocún túxíng lái shǐ qí gōngzuò? Xìtǒng běnshēn suōfàng hé jūzhōng tú xiàng de wèizhì

**Comment by NewByVector** [comment]
能否提供一个可以复现的 demo ？

**Comment by NewByVector** [comment]
因为无法复现问题，先关闭 issue，如果还有问题，请再提一个新的 issue.
