### ISSUE TITLE
导出png图片bug

### ISSUE THREAD

**Issue by Trojanpa** [antvis/X6#1443]
`Graph.registerVueComponent('agv-node', {template: `<svg-icon icon-class="agv" class-name="agv" />`}, true);`
使用svg图片通过registerVueComponent注册vue-shape类型的节点，在导出png图片时节点被没有导出。

### Expected Behavior

![image](https://user-images.githubusercontent.com/42988574/137688128-a8c9a53e-f58d-4d7e-8203-2f82b618b32f.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/42988574/137688201-e160fd8f-f06d-49f7-b751-0e24aba7a4c9.png)

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by Trojanpa** [comment]
> 能否提供一个复现的 demo 看下？

我把demo项目放到了codesandbox上了，项目在本地运行没有问题，但放到codesandbox上就报require is not defined，之前没有用过codesandbox，找了很久没找到解决办法，可以顺便帮忙解决下吗

demo链接：https://codesandbox.io/s/vue-antvx6-app-v2fbx?file=/vue.config.js

**Comment by sunhangye** [comment]
> > > > 我导出png的时候也出现了该问题，请问解决了吗？
> > > 
> > > 
> > > 说图片要用base64格式
> > 
> > 
> > 节点组件样式我改成css样式就可以了，之前用的ant.design里的栅格。
> 
> 我一开始是想直接用shape: 'image'来显示svg图片作为节点，发现用官网的svg图片链接可以显示，用自己本地的svg就显示不出来，所以我换成shape: 'vue-shape'来显示svg，这时svg图片可以显示了，但导出png和svg图片都有问题。现在换成base64图片了，可以导出png图片了，又试了下导出svg图片，发现是一片空白。你的也是用svg图片作为节点吗，想看看你是怎么做的

 我这边试用vue自定义组件作为节点 导出图片不显示节点 能具体说下在哪里设置的吗 
 是在graph.addNode中设置shape: 'base64'吗 还是什么地方

**Comment by Trojanpa** [comment]
> > > > > 我导出png的时候也出现了该问题，请问解决了吗？
> > > > 
> > > > 
> > > > 说图片要用base64格式
> > > 
> > > 
> > > 节点组件样式我改成css样式就可以了，之前用的ant.design里的栅格。
> > 
> > 
> > 我一开始是想直接用shape: 'image'来显示svg图片作为节点，发现用官网的svg图片链接可以显示，用自己本地的svg就显示不出来，所以我换成shape: 'vue-shape'来显示svg，这时svg图片可以显示了，但导出png和svg图片都有问题。现在换成base64图片了，可以导出png图片了，又试了下导出svg图片，发现是一片空白。你的也是用svg图片作为节点吗，想看看你是怎么做的
> 
> 我这边试用vue自定义组件作为节点 导出图片不显示节点 能具体说下在哪里设置的吗 是在graph.addNode中设置shape: 'base64'吗 还是什么地方

就是你用Graph.registerVueComponent注册节点时的那个组件用<img />，img的src放base64图片（data:image/svg+xml;base64,.........................）
