### ISSUE TITLE
EdgeView 的 sendToken 方法页面加载后的第一次执行总是失败

### ISSUE THREAD

**Issue by upwell** [antvis/X6#1444]
### 问题描述

在我的电脑上能够稳定复现，官方的 demo 示例：

[官方示例](https://x6.antv.vision/demos/tutorial/advanced/animation/signal/)

页面加载后的第一次点击 **矩形A** 时，小球并不会出现在边上。但是之后的每次点击，小球都会出现在边上。

### 环境

浏览器：

![截屏2021-10-18 下午4 37 25](https://user-images.githubusercontent.com/728808/137697469-8a087dae-828b-4702-8c04-778042d5f2d9.png)

操作系统：macOS Big Sur 16.1

### 可能的原因

调试一下后，在下面的代码片段中找到了一些线索

https://github.com/antvis/X6/blob/77d3abeea251ac6241b4fb73b3c773e1b728afcb/packages/x6/src/view/edge.ts#L1541-L1565

动画的代码片段：

https://github.com/antvis/X6/blob/77d3abeea251ac6241b4fb73b3c773e1b728afcb/packages/x6/src/util/dom/geom.ts#L435-L451

在收到 endEvent 事件的时候，会执行 sendToken 里面的 `attrs.complete`，会把 token 的 svg 删除掉，这是期望的逻辑，本身没有什么问题。

但当页面第一次加载，首次调用 sendToken 时，比较奇怪的是 `ani.beginElement()` 会被 restart，这样就触发 `endEvent` 和 `beginEvent`，导致 token 闪了一下就消失了。

具体不知道什么原因会导致 animation 被 restart，这里有一段关于restart的描述，不知道是不是浏览器行为。

https://www.w3.org/TR/2001/REC-smil-animation-20010904/#Restart

**Comment by upwell** [comment]
Still here. Not stale.

**Comment by Tabris7777** [comment]
同样碰到了这个问题，找了一天找不到头绪。。

**Comment by NewByVector** [comment]
@Tabris7777 应该和 https://github.com/antvis/X6/issues/1952  这个有关。

**Comment by Tabris7777** [comment]
[X6/packages/x6/src/util/dom/geom.ts](https://github.com/antvis/X6/blob/77d3abeea251ac6241b4fb73b3c773e1b728afcb/packages/x6/src/util/dom/geom.ts#L435-L451)
setTimeout(() => {
      	ani.beginElement();
},10)
ani.beginElement()设置一个10ms的setTimeout可以解决这个问题，但是原因还不清楚，只是个暂时的解决方式
