### ISSUE TITLE
動態端口位置

### ISSUE THREAD

**Issue by sfmskywalker** [antvis/X6#1464]
你好！ 首先，感謝您提供這麼棒的圖書館。 它真的很完美。

我想知道是否可以根據現有連接動態定位端口，使端口位置最靠近另一個端口？

例如，參見 https://jsplumbtoolkit.com/community/demonstration/dynamic-anchors

當您在節點周圍移動時，端口的位置會更改為最靠近連接另一端的端口。

![dynamic-port-position](https://user-images.githubusercontent.com/938393/138718604-6920c7dd-99a0-487f-ab7f-6d66888c8bec.gif)

**Comment by sfmskywalker** [comment]
Just a brief message to keep this issue from becoming stale :)

**Comment by NewByVector** [comment]
you can refer to this [demo](https://codesandbox.io/s/port-pos-w5uyw)

**Comment by sfmskywalker** [comment]
@NewByVector amazing. Thank you!
