### ISSUE TITLE
请问如何给Edge设置连接桩Port？请问如何把Edge和Node组合成一个群组？

### ISSUE THREAD

**Issue by Qing-sq** [antvis/X6#1479]
预期不用从其他连接桩出发，直接画一条带连接桩的线，然后可以从其他Node的连接桩和这条线上的连接桩进行连接。而不是让线自动吸附一笔带过。
目前已实现鼠标点击开始画一条线，但是没有找到给Edge添加连接桩的方法。于是给Edge添加了两个小的Node，给Node添加了连接桩实现了功能，但是两个Node和Edge不是一个群组，拖动的时候会拆开。

**Comment by NewByVector** [comment]
Edge 中没有连接桩的概念

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/issues/1481
