### ISSUE TITLE
Edge添加连接桩

### ISSUE THREAD

**Issue by 15706421132** [antvis/X6#1481]
预期是直接在画布上画一条带连接桩的直线，不需要从其他Node的连接桩上出发。目前已实现可以鼠标点击画一条直线，但是没有找到给Edge添加连接桩的方法，于是给Edge添加了两个小Node，给Node添加了连接桩，但是鼠标拖动会把Edge和Node拆分了，不是一个整体，所以提出如题的问题

**Comment by NewByVector** [comment]
可以参考这个[demo](https://x6.antv.vision/zh/examples/showcase/practices#path-editor)
