### ISSUE TITLE
自定义组件，使用input输入框无法聚焦失焦，无法输入内容

### ISSUE THREAD

**Issue by overofheight** [antvis/X6#1487]
复现例子： 官网文档 X6 自定义vue节点， button下添加一个输入框就能复现。
复现地址：https://codesandbox.io/s/vue-shape-8ciig?file=/src/components/Count.vue
预期期望： 实现input的正常事件和功能。
- x6: 最新版本
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]
###

**Comment by Wing-Lo** [comment]
你是不是把复现地址贴错了呀？这个里面没有input呀

**Comment by overofheight** [comment]
复现地址里面，<el-button></el-button> 下面放置一个<el-input />
| |
花开无果
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月4日 ***@***.***> 写道：

你是不是把复现地址贴错了呀？这个里面没有input呀

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xushuosean** [comment]
你确认一下加v-model了吗，你的代码中没有input组件，不知道你是否加了v-model

**Comment by NewByVector** [comment]
@overofheight 在 demo 中增加 input 并没有重现你的问题，先关闭 issue， 如果还有问题，请新提一个 issue，并且提供可以复现的 demo。
