### ISSUE TITLE
NodeTool 中 文本编辑工具  在vue中位置不对

### ISSUE THREAD

**Issue by u1235** [antvis/X6#1494]
NodeTool 中 文本编辑工具  在vue中位置不对

**Comment by u1235** [comment]
`  mounted() {
    const graph = new Graph({
      //容器
      container: document.getElementById("container"),
      // // 画布大小
      width: 800,
      height: 600,
      grid: true,
      connecting: {
        connector: "smooth"
      }
      // snapline: true,
      // grid: 10,
      // 节点是否可拖动
      // interacting: {
      //   nodeMovable: false
      // },
      // panning: false
    });
    graph.fromJSON(this.datae);
    const source = graph.addNode({
      x: 40,
      y: 40,
      width: 80,
      height: 40,
      label: "source"
    });

    const target = graph.addNode({
      x: 350,
      y: 150,
      width: 80,
      height: 40,
      label: "target"
    });

    graph.addEdge({
      source,
      target,
      labels: [
        {
          position: 0.3,
          attrs: {
            label: {
              text: "edge1"
            }
          }
        },
        {
          position: 0.6,
          attrs: {
            label: {
              text: "edge2"
            }
          }
        }
      ]
    });
    // 文本编辑工具
    graph.on("cell:dblclick", ({ cell, e }) => {
      cell.addTools([
        {
          name: "node-editor",
        }
      ]);
    });

    // console.log("123", graph.toJSON());
  }`

**Comment by u1235** [comment]
https://codesandbox.io/s/musing-galois-jrgt0?file=/src/components/HelloWorld.vue

**Comment by u1235** [comment]
> 👋 @u1235
> 
> Thanks for opening your first issue here! If you're reporting a 🐞 bug, please make sure you include steps to reproduce it.
> 
> To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/antvis/X6/blob/master/CONTRIBUTING.md).
> 
> We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.

https://codesandbox.io/s/musing-galois-jrgt0?file=/src/components/HelloWorld.vue

**Comment by u1235** [comment]
项目地址：https://codesandbox.io/s/musing-galois-jrgt0
帮看一下，谢谢

**Comment by shui2464** [comment]
我有同样的问题

**Comment by NewByVector** [comment]
在你的 demo 中修改 editor 工具的样式：
```css
.x6-cell-tool-editor {
  position: absolute;
}
```
