### ISSUE TITLE
将组件组为节点拖拽会出现ERROR TypeError: Cannot read properties of null (reading 'getZIndex')

### ISSUE THREAD

**Issue by EnochGao** [antvis/X6#1497]
![image](https://user-images.githubusercontent.com/41459067/139629543-7dfc7e68-8a5b-4ecd-8fcf-d79552b08145.png)

### 在使用x6-angular-shape发现，进行1操作，将组件作为节点添加到画布中（或者拖拽），在进行2操作（或者再次拖拽组件节点到画布中）会抛出 ERROR TypeError: Cannot read properties of null (reading 'getZIndex')错误。

**Comment by Eve-Sama** [comment]
@NewByVector 这个应该不是我的库的问题, 我看报错都是底层相关的

**Comment by BubblyFace** [comment]
遇到了一样问题 可以麻烦，不过我是fromJson时出现的，可以麻烦解决下么

**Comment by NewByVector** [comment]
这里是因为项目中使用自己编写的 view 实现，这里实现有问题：https://github.com/Eve-Sama/ngx-x6-demo/blob/master/src/app/x6-angular-shape/view.ts#L58
请使用官方版本。

**Comment by EnochGao** [comment]
我自己改了一下这个，应该是存储组建的时候没经过store存储
https://github.com/EnochGao/ngx-x6-demo/tree/ng13
