### ISSUE TITLE
请问edge如何规避节点

### ISSUE THREAD

**Issue by Spounds** [antvis/X6#1501]
自定义节点
使用的是graph.addEdge来创建连线
![image](https://user-images.githubusercontent.com/17314868/139818023-edea95ff-d07d-4b32-b089-94b328e4dedf.png)
结果是，移动位置时，连线会穿过节点
![image](https://user-images.githubusercontent.com/17314868/139818104-6053f58e-d097-4936-9a7d-c27dc5a758df.png)

请问有什么办法能让连线规避节点吗?

**Comment by NewByVector** [comment]
有 demo 看下吗？

**Comment by Spounds** [comment]
> 有 demo 看下吗？

https://github.com/antvis/X6/issues/1265
与这个问题类似，不过我没有使用路由。
我的问题，官网上的简单demo也可以演示
![1635906363(1)](https://user-images.githubusercontent.com/17314868/140002243-5d4d3889-b64b-47f8-8d53-cb8fb2aa7412.jpg)

没有使用路由的情况下，与链接上的问题处理是一致的吗？
另外，关于问题编号1265，您的回复是：可以在边连接完成事件中将边的起始和结束元素指向节点本身。
对于您的回复，我有两点不太理解：
1、我们使用graph.addEdge()方式，怎么添加边连接完成事件，我使用graph.on('edge: connected')并不起作用
2、将边的起始和结束元素指向节点本身，是什么意思，如何实施，能不能提示一下？

**Comment by Spounds** [comment]
> 有 demo 看下吗？

问题的初始截图是用了路由的。
那么，请问，
使用了路由要如何来解决我的问题，没有使用路由，又如何解决。
我看其他issue上有说不用port的，但是，我们这个业务情景下，又好像只能使用连接桩。
所以，想请问的是，在使用连接桩的情况下，如何解决这个问题？

**Comment by imjamespond** [comment]
可以用oneside

**Comment by Wangyizhi1** [comment]
I solved it like this:
```
this.graph.on('edge:connected', ({ isNew, edge }) => {
  if (isNew) {
    const sourceNode = edge.getSourceNode()
    edge.setSource(sourceNode)
  }
})
```

**Comment by NewByVector** [comment]
@Spounds 按照 https://github.com/antvis/X6/issues/1265#issuecomment-927293128 这个思路可以解决你上面问题。

**Comment by SunyanLBJ23** [comment]
> > 有 demo 看下吗？
> 
> 问题的初始截图是用了路由的。 那么，请问， 使用了路由要如何来解决我的问题，没有使用路由，又如何解决。 我看其他issue上有说不用port的，但是，我们这个业务情景下，又好像只能使用连接桩。 所以，想请问的是，在使用连接桩的情况下，如何解决这个问题？

我有相同的问题
