### ISSUE TITLE
Gallery 页面顶部显式了一个 0

### ISSUE THREAD

**Issue by x-cold** [antvis/X6#1502]
![image](https://user-images.githubusercontent.com/6903313/139848510-af8dcdf0-44eb-4c75-870b-ae33cadbea3d.png)

### Expected Behavior
没有公告时不展示 0

### Current Behavior
没有公告时展示了 0

### Possible Solution
- 升级 gatsby-theme-antv 到最新版本，重新构建 Site
https://github.com/antvis/gatsby-theme-antv/commit/b7b47504ad0942b2af9cc78ada4905b49f0bcda2#diff-79a0c7a5db150e741f6eeba9e48cc7e0cb1b7b06bcc3dcd9f9adc7fa05858f7c

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
已升级解决。
