### ISSUE TITLE
DagreLayout布局打包之后报错

### ISSUE THREAD

**Issue by xinzi1990** [antvis/X6#1507]
"@antv/layout": "^0.1.19-beta.3",
"@antv/x6": "^1.26.0",

import {Graph} from '@antv/x6';
import {DagreLayout} from '@antv/layout';
在引入之后打包报错
**

> TypeError: Cannot read properties of undefined (reading 'Graph')
>     at dagrejs.a92a5347.js:1

**

npm run build的时候提示的
transforming (1230) node_modules/lodash-es/_Map.jsConflicting namespaces: "node_modules/@antv/g-webgpu-core/es/index.js" re-exports "Component" from both "node_modules/@antv/g-webgpu-core/es/index.js" and "node_modules/@antv/g-webgpu-core/es/ComponentManager.js" (will be ignored)

Conflicting namespaces: "node_modules/@antv/g-webgpu-core/es/index.js" re-exports "ComponentManager" from both "node_modules/@antv/g-webgpu-core/es/index.js" and "node_modules/@antv/g-webgpu-core/es/ComponentManager.js" (will be ignored)

**Comment by xinzi1990** [comment]
vite版本的原因

**Comment by notail** [comment]
> vite版本的原因

我也碰到这个问题了，build的时候没有报错，但是部署后访问页面的时候报这个，大佬咋解决的

**Comment by plutda** [comment]
vite 2.9.8也有这个问题
