### ISSUE TITLE
期望有 组合和解除组合 的功能

### ISSUE THREAD

**Issue by Trojanpa** [antvis/X6#1510]
### Expected Behavior

![group](https://user-images.githubusercontent.com/42988574/140466626-b0997c2a-e314-4880-b3a0-f1f1afd8683c.gif)

**Comment by NewByVector** [comment]
可以基于 [selecting](https://x6.antv.vision/zh/docs/tutorial/basic/selection) 来实现

**Comment by Trojanpa** [comment]
> 可以基于 [selecting](https://x6.antv.vision/zh/docs/tutorial/basic/selection) 来实现

有例子吗

**Comment by GreatAuk** [comment]
need a demo😅

**Comment by NewByVector** [comment]
这就是建立父子关系，可以参考官网 [demo](https://x6.antv.vision/zh/examples/node/group#embedding-nodes)

**Comment by wflixu** [comment]
> demo

你最后实现了吗，感觉给的示例和需要实现的功能有点缺别，如果实现的话，可以说说思路吗？

**Comment by Trojanpa** [comment]
> > demo
> 
> 你最后实现了吗，感觉给的示例和需要实现的功能有点缺别，如果实现的话，可以说说思路吗？

官网的群组和我想要的组合是两个东西。我尝试过给要组合的所有节点一个相同的组合id，然后点击或选中节点时判断节点有没有组合id，有的话就根据组合id将所有带有该组合id的节点设置选中，这样点击或选中某个或多个节点后，再拖动某个节点时其他节点也会跟着移动，这就会是我想要的效果。！！！但这有个问题，就是：在鼠标按下触发的事件mousedwn里给所有组合节点加上选中状态，然后拖动节点时，除了按下的那个节点之外，其他节点依旧没有以组合的方式一起移动。所以，我并没有真正实现我想要的组合功能，如果你想到更好地思路也请告诉我，谢谢！

**Comment by liu-leizhi** [comment]
> > > demo
> > 
> > 
> > 你最后实现了吗，感觉给的示例和需要实现的功能有点缺别，如果实现的话，可以说说思路吗？
> 
> 官网的群组和我想要的组合是两个东西。我尝试过给要组合的所有节点一个相同的组合id，然后点击或选中节点时判断节点有没有组合id，有的话就根据组合id将所有带有该组合id的节点设置选中，这样点击或选中某个或多个节点后，再拖动某个节点时其他节点也会跟着移动，这就会是我想要的效果。！！！但这有个问题，就是：在鼠标按下触发的事件mousedwn里给所有组合节点加上选中状态，然后拖动节点时，除了按下的那个节点之外，其他节点依旧没有以组合的方式一起移动。所以，我并没有真正实现我想要的组合功能，如果你想到更好地思路也请告诉我，谢谢！

可以特殊处理未选中的时候拖拽组合节点。监听moving事件让有共同id的节点跟着走。我目前是这样搞的。
