### ISSUE TITLE
我已经设置了allowNode , 为什么还是只能连接到桩上

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1519]
![image](https://user-images.githubusercontent.com/33592850/140687198-0a0b3786-f65d-46b8-ac29-e5015c55a638.png)
![image](https://user-images.githubusercontent.com/33592850/140687217-e6e87846-4e1d-4527-97e3-e682ab9855aa.png)

**Comment by NewByVector** [comment]
能被连线需要元素具备 `magnet: true` 属性。

**Comment by cheng-xiaofeng** [comment]
> 能被连线需要元素具备 `magnet: true` 属性。

这个属性怎么用呢?这样吗?这是节点的配置项, ports上的attrs也添加了magnet: true
![image](https://user-images.githubusercontent.com/33592850/140847685-4210823d-e7f4-448a-805f-cb7460e1b612.png)

这个例子上, 也是ports的attrs上有magnet: true, 但就能连到节点的边上
https://codesandbox.io/s/wj8de?file=/src/app.tsx:916-922

**Comment by cheng-xiaofeng** [comment]
> > 能被连线需要元素具备 `magnet: true` 属性。
> 
> 这个属性怎么用呢?这样吗?这是节点的配置项, ports上的attrs也添加了magnet: true ![image](https://user-images.githubusercontent.com/33592850/140847685-4210823d-e7f4-448a-805f-cb7460e1b612.png)
> 
> 这个例子上, 也是ports的attrs上有magnet: true, 但就能连到节点的边上 https://codesandbox.io/s/wj8de?file=/src/app.tsx:916-922

我的其实可以连接到边, 只是我拖得位置不对

**Comment by cheng-xiaofeng** [comment]
> 能被连线需要元素具备 `magnet: true` 属性。

我的可以连接到边, 只是我拖得位置不对
