### ISSUE TITLE
Graph创建Node节点之后，添加child，无法显示children

### ISSUE THREAD

**Issue by weiwei0901** [antvis/X6#1522]
<img width="458" alt="12" src="https://user-images.githubusercontent.com/47552189/140702198-9dfa5176-7b46-4c7f-a49d-d5422e143388.png">

<img width="805" alt="1" src="https://user-images.githubusercontent.com/47552189/140702222-e35c8c18-3a29-4795-8047-2209bf86894e.png">

上面的代码中，根据另外一个节点新建Node节点之后，setChildren()之后，在浏览器console中查看，没有children的值

**Comment by NewByVector** [comment]
使用 `addChild` api
