### ISSUE TITLE
从source连接到target节点时, 只能从桩连接到节点吗? 桩连接到节点只能一条边吗?(不连接到桩的情况下)

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1523]
像这样, edge1可以连接, edge2就连接不上, 为森么? 可以连多条边吗
![image](https://user-images.githubusercontent.com/33592850/140702470-0cbeb862-d699-4180-940c-39faf7663b2b.png)

**Comment by NewByVector** [comment]
提供一个 demo 看下？

**Comment by cheng-xiaofeng** [comment]
> 提供一个 demo 看下？

https://codesandbox.io/s/wj8de?file=/src/app.tsx
就这里,官网的例子
