### ISSUE TITLE
在Vue中点击事件右键node:contextmenu，获取的坐标不准确

### ISSUE THREAD

**Issue by chris-mask** [antvis/X6#1524]
在Vue中点击事件右键node:contextmenu，获取的坐标不准确，在画布上显示不正确
![image](https://user-images.githubusercontent.com/21608359/140714604-09560425-efb4-4aac-b017-68ba5ec8ce44.png)
![image](https://user-images.githubusercontent.com/21608359/140714724-427e29c1-208f-44fb-b211-d00a989fd5b5.png)

**Comment by NewByVector** [comment]
这里的 x y 是相对于画布的坐标，如果要转换为文档坐标，可以使用:
```
graph.localToClient(x, y)
```

**Comment by chris-mask** [comment]
> 这里的 x y 是相对于画布的坐标，如果要转换为文档坐标，可以使用:
> 
> ```
> graph.localToClient(x, y)
> ```

好的，感谢解答
