### ISSUE TITLE
使用node.setVisible 有几率会出现网页直接卡死。

### ISSUE THREAD

**Issue by tubie520** [antvis/X6#1525]
## 环境如下
vue3 + ts 节点使用的vue的组件。

## 具体情况说明
代码流程，全选节点 和 全不选功能， 当全不选的情况下 获取所有node 然后调用node.setVisible 全不选测试好几次都是正常，
然后使用全选， 跑几轮全部网页卡死。

`log`输出部分如下 在setVisible 使用的时候网页直接卡死。。。
```
aside.vue?3565:80 VueShape {listeners: {…}, id: 9, store: Store, animation: Animation, port: PortManager, …}
aside.vue?3565:82 visible
aside.vue?3565:83 9 false true
aside.vue?3565:87 设置checkedMap
aside.vue?3565:91 完成
aside.vue?3565:77 获取node
aside.vue?3565:80 VueShape {listeners: {…}, id: 11, store: Store, animation: Animation, port: PortManager, …}
aside.vue?3565:82 visible
aside.vue?3565:83 11 false true
```
## 调用代码
``` javascript
// 显示节点
function showNode(obj: SetupObjectBuilderObject, visible: boolean) {
  console.log("获取node");
  const node = props.objectCtrller.getNode(obj.id);
  // console.log(obj, node);
  console.log(node);
  if (!node) return;
  console.log("visible");
  console.log(obj.id, node.visible, visible);
  if (node.visible !== visible) {
    node?.setVisible(visible);
  }
  console.log("设置checkedMap");
  if (checkedMap.value[obj.id] !== visible) {
    checkedMap.value[obj.id] = visible;
  }
  console.log("完成");
}
// 全选
function checkAll() {
  props.objectList.forEach((i: SetupObjectBuilderObject) => {
    showNode(i, true);
  });
}

// 清空选择
function clearChecked() {
  props.objectList.forEach((i: SetupObjectBuilderObject) => {
    showNode(i, false);
  });
}
```

**Comment by NewByVector** [comment]
方便给个复现 demo 吗，看 log 看不出问题

**Comment by tubie520** [comment]
## 仓库
代码我上传到`github`了，大佬有空帮忙看看哈。 显示隐藏那个主要问题可以看看啊 网页卡死，有空可以看看下面次要 没空就算啦。
```
git clone https://github.com/tubie520/x6-demo.git
```
## Bug说明
> 主要问题
- 使用`api`方式创建连接桩后再连线后获取使用`node`调用 `node.visible`隐藏，后再使用显示会使页面卡死。不添加连线的情况下隐藏显示没问题。`Bug`重现启动项目后点击 **显示** 然后在点击 **隐藏** 按钮即会卡死。

> 竟然提了demo 有时间可以看看如下次要问题，可以不处理， 哈哈。
- 鼠标滚动到下面，然后拖动节点`id:9`移动位置，会造成节点在画布位置中跳动，不知道是不是设置有问题。
- 当`Graph` 设置添加`async: true`， 会造成连接线`zIndex`失效问题，当前`demo`创建的连线都是在`node`层级下显示。
- 有没有设置可以使节点不可控制，包括点击移动， 就是相当于只能操作画布移动之类的。

**Comment by Mr-clown2040** [comment]
> 方便给个复现 demo 吗，看 log 看不出问题

遇到同样的问题

**Comment by tubie520** [comment]
@Mr-clown2040  那你应该催管理员修复

**Comment by Mr-clown2040** [comment]
> 方便给个复现 demo 吗，看 log 看不出问题
@NewByVector 大佬应该在解决，毕竟你已经贴出了demo

**Comment by tubie520** [comment]
兄弟，来互相帮助下，我这还有其他问题 哈哈

**Comment by tubie520** [comment]
@Mr-clown2040  老兄我找了一个笨的解决办法。 代码发你，不代表`x6`的啊， 如果你有更好的办法可以告诉我哈。 大佬们太忙没时间解决**bug**
没办法了，用了最原始的办法， 隐藏`node` 和 `edge`
```javascript
  // 设置节点显示隐藏  获取node edge的element 再设置display
  setNodeVisible(nodeId: string, visible: boolean) {
    const node = this.graph.getCellById(nodeId);
    const edges = this.graph.getConnectedEdges(node);
    const graphEle = this.option.container as HTMLElement;
    const nodeEle = graphEle.querySelector(`.x6-cell[data-cell-id="${nodeId}"]`) as HTMLElement;
    if (!nodeEle) return;
    nodeEle.style.display = visible ? "block" : "none";
    edges.forEach((edge: Edge) => {
      const edgeEle = graphEle.querySelector(`.x6-edge[data-cell-id="${edge.id}"]`) as HTMLElement;
      edgeEle.style.display = visible ? "block" : "none";
    });
  }
```

**Comment by Mr-clown2040** [comment]
const cells = this.getCellsByLayerId(layerId);
    cells.forEach(item => {
      const graphEle = this.graph.config.container as HTMLElement;
      const nodeEle = graphEle.querySelector(`.x6-cell[data-cell-id="${item.id}"]`) as HTMLElement;
      if (!nodeEle) return;
      nodeEle.style.display = visible ? "block" : "none";
    })

其实不用区分node和edge的，你这种方法其实挺好的，给你点个赞

**Comment by Mr-clown2040** [comment]
还有一种方法就是用删除和回退操作，也可以实现

**Comment by tubie520** [comment]
官方的`setVisible`木有解决，我就只能找其他办法啊。

**Comment by Mr-clown2040** [comment]
哎，大佬们都比较忙，没办法

**Comment by NewByVector** [comment]
@tubie520 抱歉，现在才看到你的 issue，我验证过确实有问题，防止 issue 被机器人关闭，我重新提一个新的 [issue](https://github.com/antvis/X6/issues/1742)。
