### ISSUE TITLE
安装依赖报错这个怎么解决

### ISSUE THREAD

**Issue by sunlianglife** [antvis/X6#1529]
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock --no-ci exited 1 in 'x6'

**Comment by NewByVector** [comment]
windows 下面吗？

**Comment by Lin-Kangjing** [comment]
> windows 下面吗？

是的

**Comment by NewByVector** [comment]
yarn 版本问题，https://github.com/lerna/lerna/issues/1032，可以升级到稳定版本。
