### ISSUE TITLE
关于graph.getCellById的疑问. 这个方法返回的是节点/边, 但是却提示我没有size(getSize, setSize)方法, 但是在打印出的prototype上却找到了size(getSize, setSize)

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1535]
此外, 在官网搜索也搜索不到getSize和setSize方法, 这个是新方法所以还没更新吗?

![360截图20211110170225032](https://user-images.githubusercontent.com/33592850/141084195-19cc4302-af4b-49f3-b6d1-7e559c59041c.jpg)

![360截图20211110170256944](https://user-images.githubusercontent.com/33592850/141083475-45106b26-7980-4343-85f8-1a25902cdd24.jpg)
![360截图20211110170450040](https://user-images.githubusercontent.com/33592850/141083492-05b86aad-74c4-4a85-8d10-ed805c448c3f.jpg)
)

**Comment by NewByVector** [comment]
`getCellById` 返回的类型是 `Cell`,你这里如果确定是节点，可以将类型转换为节点。
```ts
graph.getCellById('1') as Node
```

**Comment by cheng-xiaofeng** [comment]
> `getCellById` 返回的类型是 `Cell`,你这里如果确定是节点，可以将类型转换为节点。
> 
> ```ts
> graph.getCellById('1') as Node
> ```

嗯嗯, 我是这么做的, 只是比较奇怪而已, 我以为还有getNodeById  getEdgeById方法的, 结果没有. 估计是曼德拉效应, 记错了
