### ISSUE TITLE
请问在vue中可以动态控制链接桩外围渲染的矩形框的颜色吗

### ISSUE THREAD

**Issue by chris-mask** [antvis/X6#1542]
请问如何动态控制 当链接桩可以被链接时，在链接桩外围渲染一个 2px 宽的红色矩形框，希望根据标识动态控制颜色

![image](https://user-images.githubusercontent.com/21608359/141251539-787f13ce-1e12-4f65-81e2-9dfdb07d5312.png)

**Comment by NewByVector** [comment]
可以通过配置 `connecting/magnetAvailable`,参考 [demo](https://x6.antv.vision/zh/examples/showcase/practices#validate-connection)

**Comment by chris-mask** [comment]
****

> magnetAvailable

magnetAvailable 这个只能固定高亮的颜色吧
![image](https://user-images.githubusercontent.com/21608359/141877906-816fa30f-b673-42e7-a97e-9fe02128a80c.png)

请问有方法可以动态控制高亮的颜色吗

**Comment by NewByVector** [comment]
在 `highlighting` 中可以配置连线不同时期的状态，可以看下文档：https://x6.antv.vision/zh/docs/api/graph/interaction/#highlighting

**Comment by chris-mask** [comment]
> 在 `highlighting` 中可以配置连线不同时期的状态，可以看下文档：https://x6.antv.vision/zh/docs/api/graph/interaction/#highlighting

感谢回答，但是在这个方法里面可以获取到节点的数据吗，因为我需要根据数据里面字段来判断显示什么颜色

**Comment by ginotao123** [comment]
@NewByVector  这个有好的解决办法吗，需要根据节点链接桩的属性动态高亮显示，
比如节点有A、B两个链接桩，A是必须连接需要红色高亮显示，B是非必须连接则不需要。

**Comment by ginotao123** [comment]
@NewByVector 此问题比较紧急，恳请帮忙解答，谢谢！

**Comment by NewByVector** [comment]
@chris-mask 可以通过 `graph.options.highlighting.magnetAvailable.attrs.xxx = xxx` 动态修改样式。
