### ISSUE TITLE
节点选中Bug

### ISSUE THREAD

**Issue by doresearch** [antvis/X6#1543]
调用 graph.cleanSelection() 后，再次点击之前选中的节点，无法点击，无法移动

### Expected Behavior

graph.cleanSelection() 后，同一个节点应该允许重复选中

### Current Behavior

节点无法选中无法移动

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
无法复现这个问题，如果还有问题，再提一个 issue，并且提供复现的 demo。
