### ISSUE TITLE
但我用自定义节点时, 用antd的Tree组件, 缺不能拖动, 是为什么

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1545]
这是演示 地址
https://codesandbox.io/s/angry-flower-2remy?file=/src/app.css

**Comment by NewByVector** [comment]
我在本地使用你的 demo 是可以拖动的，是不是因为在 codesanbox 里面导致的？

**Comment by cheng-xiaofeng** [comment]
> 我在本地使用你的 demo 是可以拖动的，是不是因为在 codesanbox 里面导致的？
我可能没有表达清楚, 我想说tree的节点不能拖动排序

**Comment by xushuosean** [comment]
可能是因为事件被x6捕获了，可以尝试阻止冒泡关键事件，避免被x6捕获

**Comment by NewByVector** [comment]
@cheng-xiaofeng 这个是我用你的例子在本地跑的现象，是可以拖动的，如果还有问题，请新提一个 issue。
![image](https://user-images.githubusercontent.com/20186737/148668438-6a1e1109-a54a-4ac6-99c6-31568d22f339.png)
