### ISSUE TITLE
变更改节点id

### ISSUE THREAD

**Issue by overofheight** [antvis/X6#1547]
希望可以有api去更新节点的id，类似这样的：node.setId(newId) / cell.updateId(newId)

变更后的节点  相关的连线的id 也会自动变更

**Comment by NewByVector** [comment]
你需要修改 id 的场景是什么？

**Comment by overofheight** [comment]
感谢回复。这个也应该是比较常用的api功能吧， jsPlumb也有类似的api。场景：画布中拖进一个空白节点，单击对这个节点A进行数据配置，然后右键修改节点，改为节点B。既然id代表唯一标识，data数据层就没有必要再添加一个唯一标识了，容易混淆。
| |
花开无果
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月12日 ***@***.***> 写道：

你需要修改 id 的场景是什么？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EmiyaYang** [comment]
+1，我也需要

**Comment by changehu** [comment]
+1

**Comment by UriasUdall** [comment]
+1，我也需要

**Comment by UriasUdall** [comment]
谢谢你的来信，这里是幸的邮箱，以后常联系！

**Comment by TheShining** [comment]
+1 发现改了id，removeNode(selectCell)无法删除节点，不知道算不算bug

**Comment by NewByVector** [comment]
自定义 ID 会造成很多不好定位的问题。大部分场景都不需要自定义ID。在 dnd 拖拽过程中，增加了保持 id 的[方法](https://x6.antv.vision/zh/docs/tutorial/basic/dnd#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。

**Comment by TheShining** [comment]
> 

嗯，因为这个id遇到好多bug了，这一块我还是重构下吧

**Comment by EmiyaYang** [comment]
https://github.com/antvis/x6/commit/78cdb3bd56e7655ffcb2e5046d00f5d4f932cd3c 

还是提供了。。。

**Comment by dlr188** [comment]
> +1 发现改了id，removeNode(selectCell)无法删除节点，不知道算不算bug

**Comment by dlr188** [comment]
+1，一般公司有自己的ID规则，x6的ID不适用，另外，提个bug，修改ID后撤销会报错

**Comment by dlr188** [comment]
> +1，一般公司有自己的ID规则，x6的ID不适用，另外，提个bug，复制粘贴时修改ID后，撤销会报错（我做的时候拖拽已支持自定义ID）

**Comment by XueMeijing** [comment]
> > +1，一般公司有自己的ID规则，x6的ID不适用，另外，提个bug，复制粘贴时修改ID后，撤销会报错（我做的时候拖拽已支持自定义ID）

加一 我也遇到了

**Comment by fearclear** [comment]
+1
