### ISSUE TITLE
ER 图期望展示字段之间的关系

### ISSUE THREAD

**Issue by samwangdd** [antvis/X6#1550]
### Expected Behavior
期望展示数据库表，两个字段之间的关系，如下：
![截屏2021-11-14 下午9 29 36](https://user-images.githubusercontent.com/29837369/141684123-392dc1f0-d993-4b16-9ee2-20b3aef1d0ef.png)

### Additional Context
我正在使用 ER 图，目前可以支持两个表之间的关系，但是我想更加细致的展示字段是来自某张表的某个字段，是否能支持这种场景？复现链接：https://x6.antv.vision/apps/er/

**Comment by NewByVector** [comment]
试试这个呢？https://x6.antv.vision/zh/examples/showcase/practices#er

**Comment by samwangdd** [comment]
> 试试这个呢？https://x6.antv.vision/zh/examples/showcase/practices#er

谢谢提醒，这个顶部是否支持自定义呢？比如我想改为一个 a 标签
<img width="726" alt="截屏2021-11-18 下午3 17 30" src="https://user-images.githubusercontent.com/29837369/142369846-05bf7529-a1e0-42e6-a38b-1b4789b433a4.png">

**Comment by search-inner** [comment]
同上，也有此需求

**Comment by NewByVector** [comment]
@samwangdd @search-inner 参考 https://codesandbox.io/s/link-8jrvv

**Comment by wangyueAI023** [comment]
我有同样的需求 你的表需要滚动条吗
