### ISSUE TITLE
dnd拖拽的时候怎么实时监听拖拽事件

### ISSUE THREAD

**Issue by changehu** [antvis/X6#1556]
项目里面拖拽用的dnd拖拽,由于项目中的节点需要进行碰撞检测,因此创建和拖拽的时候需要实时获取节点位置,用来设置节点能否拖拽创建以及碰撞,如果碰撞了就去设置鼠标样式,现在找不到 dnd 相关拖拽事件 实时监听

**Comment by Trojanpa** [comment]
是否碰撞可以用getNodesUnderNode这个api检测

**Comment by Trojanpa** [comment]
dnd拖拽有没有api我不知道，但我觉得你可以通过 node:added node:moved 等来判断是否添加/移动了节点的，再配合getNodesUnderNode检测碰撞应该就可以实现你的效果了
