### ISSUE TITLE
connecting 能否支持动态修改 createEdge里面的连线配置 

### ISSUE THREAD

**Issue by bingyuea** [antvis/X6#1558]
connecting 能否支持动态修改 createEdge里面的连线配置 ，现在是通过默认new StandardEdge() 这个类生成的，
现在我在其他像修改整体的 edge 配置 但是没有成功，请问我该如何修改
```
createEdge() {
    return new X6Line()
  },
```
------

```
setLineColor(color: string) {
    this.graph.createEdge = new X6Line({
      attrs: {
        line: {
          stroke: '#f0f',
          strokeWidth: 1,
          targetMarker: {
            name: 'classic',
            size: 8
          }
        }
      },
      router: {
        name: 'manhattan'
      }
    })
  }
```

**Comment by bingyuea** [comment]
> connecting 能否支持动态修改 createEdge里面的连线配置 ，现在是通过默认new StandardEdge() 这个类生成的， 现在我在其他像修改整体的 edge 配置 但是没有成功，请问我该如何修改
> 
> ```
> createEdge() {
>     return new X6Line()
>   },
> ```
> 
> ```
> setLineColor(color: string) {
>     this.graph.createEdge = new X6Line({
>       attrs: {
>         line: {
>           stroke: '#f0f',
>           strokeWidth: 1,
>           targetMarker: {
>             name: 'classic',
>             size: 8
>           }
>         }
>       },
>       router: {
>         name: 'manhattan'
>       }
>     })
>   }
> ```

找到了 set方法

**Comment by bingyuea** [comment]
```
createEdge: () => {
          this.line = new X6Line()
          return this.line
        },
        
  setLineColor(color: string) {
    this.line.setAttrByPath('line/stroke', '#f0f')
  }
```

但是这样只能作用于单条边 不能对新加入的边生效

**Comment by NewByVector** [comment]
在 `createEdge` 方法里面增加一个变量控制返回不同的 `edge`。
