### ISSUE TITLE
触发stage中的元素排序会导致node中的foreignObject中的div滚动条scrollTop回到0

### ISSUE THREAD

**Issue by imjamespond** [antvis/X6#1561]
如题,添加edge,node,或排序时想保持场景中已有的元素中foreignObject的滚动条位置的状态, 怎么破?

**Comment by NewByVector** [comment]
svg 节点排序的时候 dom 节点会重置，如果要保持滚动条位置，需要在排序之前记住滚动条位置，排序后恢复。
