### ISSUE TITLE
自定义事件

### ISSUE THREAD

**Issue by woshiwhy** [antvis/X6#1567]
查看文档发现自定义事件只支持点击事件。
希望能丰富自定义事件类型。
![image](https://user-images.githubusercontent.com/21192448/142338266-2d2a3493-784b-44f3-9af6-487395754062.png)

**Comment by NewByVector** [comment]
还没有需要支持其他事件的需求，暂时不考虑支持。

**Comment by Cosimac** [comment]
> 还没有需要支持其他事件的需求，暂时不考虑支持。

想问下react组件内触发的事件全局可以监听吗?

**Comment by NewByVector** [comment]
@Cosimac react组件内的事件直接用 react 的方式监听比较好。
