### ISSUE TITLE
某些情况下Graph.registerReactComponent为undefined

### ISSUE THREAD

**Issue by xiyangjun** [antvis/X6#1570]
### Expected Behavior
预期Graph.registerReactComponent是一个function

### Current Behavior
当前Graph.registerReactComponent是一个undefined

### Steps To Reproduce

```js
import { Graph } from "@antv/x6";
import { ReactShape } from "@antv/x6-react-shape";
```
当如上引用的时候Graph.registerReactComponent是一个undefined，如果是如下引用则GraphregisterReactComponent可以正确获取到
```js
import { Graph } from "@antv/x6";
import  "@antv/x6-react-shape";
```
https://codesandbox.io/s/blazing-sunset-pzo6z?file=/src/index.tsx:68-152

- x6: 1.28.1
- x6-react-shape： 1.5.2
- OS: macos 10.15.7 
- Browser: 95.0.4638.69

**Comment by NewByVector** [comment]
这个是因为你 `import { ReactShape } from "@antv/x6-react-shape";` 后面却没有用到 `ReactShape`,会被 `tree-shaking`
