### ISSUE TITLE
功能实现和报错

### ISSUE THREAD

**Issue by zsj0202** [antvis/X6#1573]
1. 鼠标放到链接桩上或边上再显示链接桩的名字的功能要怎么做（代码不是用的使用react渲染节点）
2. 使用graph.fromJSON反序列化，将图表显示在页面上后再进行拖动节点会报错：node.js:200 Error: <g> attribute transform: Expected ')', "translate(30-10,-1400)".
3. 有没有控制图表不可编辑的api

**Comment by NewByVector** [comment]
1. 参考：https://github.com/antvis/X6/blob/master/examples/x6-example-features/src/pages/tools/port-tooltip.tsx
2. 应该是节点的位置 x、y 是非数字类型
3. interacting 配置，请移步文档
