### ISSUE TITLE
target-arrowhead 使用有问题

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/X6#1586]
![图片](https://user-images.githubusercontent.com/30228406/142756051-9518ccbb-cf2d-413d-a86f-b92657552d9d.png)
可以看到我有这么几种节点. 我将节点和边的id通过手绘的方式画出来了.
![图片](https://user-images.githubusercontent.com/30228406/142756129-e3f53fae-5ec0-4bfa-8337-52ee76a81b37.png)
然后我尝试重连左下方的那条线, 从起点开始重连.
![图片](https://user-images.githubusercontent.com/30228406/142756145-0b62d2aa-aef7-45f1-844a-5042cb71c036.png)
然后发现激活了`validateConnection`, 因为业务要求`连接节点`只能连入2条线. 然而在触发的`validateConnection`方法中通过调试可以看到当前已经连了2条线了, 就是之前一开始自带的2条边.  那么问题就来了, 重连会触发这个方法, 那我这个方法判断已经有2条线了肯定是要抛业务错的, 提示用户最多只能连2条线. 但是从交互上来说, 用户就是尝试重新连, 结果你就报这么个错, 这是很奇怪的, 该怎么办呢? 
![图片](https://user-images.githubusercontent.com/30228406/142756170-89fddecb-da26-44bf-9c38-8f767286f40b.png)

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
触发 `validateConnection` 并不是问题。解决你问题的方案是：
1. 在 `edge:connected` 事件中给边加上标记-新添加的边
2. 然后在 validateConnection 根据这个标记能够判断是否是新添加的边

**Comment by Eve-Sama** [comment]
没理解, 他并不是新添加的边就算新的一条边的. `validateConnection`回调的参数`edge`, 就是原先的那条边.

**Comment by Eve-Sama** [comment]
而且`edge:connected`只有对新连接的线有触发, 已有的线重连因为id还是不变的 导致没触发.
