### ISSUE TITLE
连线到node节点的边的问题

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1587]
图1是官网连线到节点的边的样子, 是有黄色的边框在的, 
图2是我.连线到边的样子, 是一个node节点一样大小的蓝色方块
这种显示也是有某个属性配置的吗?

![image](https://user-images.githubusercontent.com/33592850/142797706-1a9c2198-6d05-4f9b-968f-b18bf5ce3513.png)
![360截图20211122114050084](https://user-images.githubusercontent.com/33592850/142797720-4ce7a1d1-9553-4be9-9d69-824044660f84.jpg)

**Comment by NewByVector** [comment]
有 `highlight` 配置。
