### ISSUE TITLE
鼠标移入给edge添加样式出现问题

### ISSUE THREAD

**Issue by pijiupaowanzi** [antvis/X6#1588]
### Expected Behavior
<img src='https://i.bmp.ovh/imgs/2021/11/abc6eb9dcef8b4d2.png' />
打印cell的下面是有port的，但是一直提示说 'port' does not exist on type 'TerminalData'

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
这个里推荐使用：`cell.getSourcePortId()`
