### ISSUE TITLE
使用vue渲染节点方式，toJSON是成功的，但是fromJSON会报错，

### ISSUE THREAD

**Issue by webpig** [antvis/X6#1590]
### Expected Behavior
使用 fromJSON 正常回显

### Current Behavior
使用 fromJSON 报错

![image](https://user-images.githubusercontent.com/24989439/142850983-da5ae01f-4a1f-427d-8b9f-ea978ba378be.png)

### Steps To Reproduce

组件定义如下：

![image](https://user-images.githubusercontent.com/24989439/142851094-8cb1b778-b2b9-4eff-b5b1-3ec48894cdc3.png)

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: 1.28.1
- OS: window10
- Browser: chrome  96.0.4664.45

**Comment by webpig** [comment]
toJSON 时 methods 和 data 未正确保存

**Comment by webpig** [comment]
解决了：通过 registerVueComponent + getData() 方式

**Comment by lijing666** [comment]
> 解决了：通过 registerVueComponent + getData() 方式

你好！请问有示例代码可以参考一下吗，我这边registerVueComponent 也是不行，只能手动渲染了而不使用fromJSON

**Comment by webpig** [comment]
> > 解决了：通过 registerVueComponent + getData() 方式
> 
> 你好！请问有示例代码可以参考一下吗，我这边registerVueComponent 也是不行，只能手动渲染了而不使用fromJSON

我明天贴一下代码，这两天没看到消息

**Comment by lijing666** [comment]
> > > 解决了：通过 registerVueComponent + getData() 方式
> > 
> > 
> > 你好！请问有示例代码可以参考一下吗，我这边registerVueComponent 也是不行，只能手动渲染了而不使用fromJSON
> 
> 我明天贴一下代码，这两天没看到消息

谢谢，个人觉得官方的方案是有问题的，比较好的方案应该是序列化toJSON时生成，而不是官方的序列化那些没用的组件定义出来
```json
{
"shape": "vue-shape",
"id": "uid-123",
"data": {
  "componentType": "com-custom",//Vue组件ID
  "props":{
     "prop1":"value1",
     "prop2":"value1",
     ......
  }
}
}
```
然后反序列化fromJSON时，利用componentType和props渲染组件
```json
<com-custom v-bind="data.props"></com-custom>
```

**Comment by webpig** [comment]
> > > > 解决了：通过 registerVueComponent + getData() 方式
> > > 
> > > 
> > > 你好！请问有示例代码可以参考一下吗，我这边registerVueComponent 也是不行，只能手动渲染了而不使用fromJSON
> > 
> > 
> > 我明天贴一下代码，这两天没看到消息
> 
> 谢谢，个人觉得官方的方案是有问题的，比较好的方案应该是序列化toJSON时生成类似下面的json：
> 
> ```json
> {
> "shape": "vue-shape",
> "id": "uid-123",
> "data": {
>   "componentType": "com-custom",//Vue组件ID
>   "props":{
>      "prop1":"value1",
>      "prop2":"value1",
>      ......
>   }
> }
> }
> ```
> 
> 然后反序列化fromJSON时，利用componentType和props渲染组件
> 
> ```json
> <com-custom v-bind="data.props"></com-custom>
> ```

已经解决了吗，我搞忘记了，不好意思

**Comment by lijing666** [comment]
> > > > > 解决了：通过 registerVueComponent + getData() 方式
> > > > 
> > > > 
> > > > 你好！请问有示例代码可以参考一下吗，我这边registerVueComponent 也是不行，只能手动渲染了而不使用fromJSON
> > > 
> > > 
> > > 我明天贴一下代码，这两天没看到消息
> > 
> > 
> > 谢谢，个人觉得官方的方案是有问题的，比较好的方案应该是序列化toJSON时生成类似下面的json：
> > ```json
> > {
> > "shape": "vue-shape",
> > "id": "uid-123",
> > "data": {
> >   "componentType": "com-custom",//Vue组件ID
> >   "props":{
> >      "prop1":"value1",
> >      "prop2":"value1",
> >      ......
> >   }
> > }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后反序列化fromJSON时，利用componentType和props渲染组件
> > ```json
> > <com-custom v-bind="data.props"></com-custom>
> > ```
> 
> 已经解决了吗，我搞忘记了，不好意思

没事，谢谢哈，目前比较靠谱的就是重新绘制，不用自带的fromJSON，后续我看看怎么给官方提个意见或者pr

**Comment by webpig** [comment]
> 

好的
