### ISSUE TITLE
2个node节点通过连线桩连接edge线后,怎么在edge线上插入添加自定义图标并且线图标可以增删改操作,随着线移动线上的小图标也跟着移动

### ISSUE THREAD

**Issue by qq454470755** [antvis/X6#1594]
2个node节点通过连线桩连接edge线后,怎么在edge线上插入添加自定义图标并且线图标可以增删改查操作,并且线移动线上的小图标跟着动

**Comment by pijiupaowanzi** [comment]
你可以试试在使用addTools方法，edge.addTools

**Comment by NewByVector** [comment]
参考[连线工具](https://x6.antv.vision/zh/docs/api/registry/edge-tool#button)
