### ISSUE TITLE
导出SVG bug

### ISSUE THREAD

**Issue by Della156** [antvis/X6#1595]
### Expected Behavior
<img width="671" alt="WX20211124-171027@2x" src="https://user-images.githubusercontent.com/40653619/143208817-d4d2aeae-695b-44b5-b6a5-463d8adabaeb.png">

### Current Behavior
![image](https://user-images.githubusercontent.com/40653619/143209105-21a0ec85-6ea2-4b6a-b650-9400dc19fb16.png)

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
参考这个[问题](https://x6.antv.vision/zh/docs/tutorial/epilog#%E5%AF%BC%E5%87%BA%E5%9B%BE%E7%89%87%E6%A0%B7%E5%BC%8F%E7%BC%BA%E5%A4%B1)
