### ISSUE TITLE
设置连接线和链接桩样式的时候，两个样式会产生冲突

### ISSUE THREAD

**Issue by pijiupaowanzi** [antvis/X6#1597]
### Expected Behavior
##鼠标移入连接线，连接线和对应连接的桩都变色
#功能代码
<img src='https://i.bmp.ovh/imgs/2021/11/653e626cf74f67b8.png'/>
#样式
<img src='https://i.bmp.ovh/imgs/2021/11/7e45f8ff0d2c3b53.png'/>

### Current Behavior
##当鼠标移入链接桩和连接线的交界处时，会一直闪动
#页面样式
<img src='https://i.bmp.ovh/imgs/2021/11/fda9673fa3223f87.jpg'/>
#连接线页面表现
<img src='https://i.bmp.ovh/imgs/2021/11/cb7d653aba47ffde.png'/>

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
参考这个 demo： https://codesandbox.io/s/edge-port-3w5b6
