### ISSUE TITLE
连接线上添加tool，并设置tool的位置，连接线竖向时会出现bug

### ISSUE THREAD

**Issue by pijiupaowanzi** [antvis/X6#1599]
### Expected Behavior

##如果不设置offset的话，我渲染的svg不会在连接线上,offset是设置为svg宽高的一半，此时svg在中心
#横向是正常的
<img src='https://i.bmp.ovh/imgs/2021/11/6e53e5529e445b3c.png'/>
### Current Behavior
#如果没有使用offset设置偏移量
<img src='https://i.bmp.ovh/imgs/2021/11/f7fb0e15eb212b19.png'/>

#竖向会有问题，产生了偏移
<img src='https://i.bmp.ovh/imgs/2021/11/c74823e625be4987.png'/>
### Steps To Reproduce

1. 代码
<img src='https://i.bmp.ovh/imgs/2021/11/4f6a188e0dee5f35.png'/>

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
参考这个 [demo](https://codesandbox.io/s/button-remove-eo449)
