### ISSUE TITLE
内置节点path

### ISSUE THREAD

**Issue by YJEthan** [antvis/X6#1604]
### Expected Behavior
我用的是path的a属性，页面最后显示替换成了path的c属性
![image](https://user-images.githubusercontent.com/46245616/143817119-9418ca09-281b-4368-9599-5e65585c78f1.png)
![image](https://user-images.githubusercontent.com/46245616/143817186-f09da9ee-f7b8-406d-b045-753cb503ee0b.png)

**Comment by zhangdi-123z** [comment]
这是自定义图形么   问一下那个path那里边的到底是什么意思啊   M  L Z 这些   谢谢！

**Comment by YJEthan** [comment]
> 这是自定义图形么 问一下那个path那里边的到底是什么意思啊 M L Z 这些 谢谢！

自定义节点，图形是按照svg格式定义的，你可以[在](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path)查看

**Comment by NewByVector** [comment]
@YJEthan https://x6.antv.vision/zh/examples/node/native-node#path  参考这个 demo，path 属性设置的是 refD，和单独设置 path 的 d 属性有区别的。
