### ISSUE TITLE
图表示例里面的路径编辑器，画直线时，线会变成斜线

### ISSUE THREAD

**Issue by Trojanpa** [antvis/X6#1606]
### Expected Behavior

期望画的直线不出现偏斜

### Current Behavior

![image](https://user-images.githubusercontent.com/42988574/143826989-a0ac8da0-ea2a-47eb-ab25-32e06e44556c.png)

### Steps To Reproduce

`
import { Graph, Node, Edge, EdgeView } from '@antv/x6'

let edge: Edge | null = null
let node: Node | null = null
const container = document.getElementById('container')!

const graph = new Graph({
  container,
  grid: {
    size: 2,
    visible: true,
  },
  mousewheel: {
    enabled: true,
    modifiers: ["ctrl", "meta"],
  },
})

const init = (pos: { x: number; y: number }) => {
  node = graph.addNode({
    shape: 'circle',
    width: 1,
    height: 1,
    ...pos,
    attrs: {
      body: {
        strokeWidth: 1,
        stroke: '#5F95FF',
        fill: '#EFF4FF',
      },
    },
  })
  edge = graph.addEdge({
    source: node,
    target: pos,
    attrs: {
      line: {
        targetMarker: null,
        stroke: 'red',
        strokeWidth: 0.3,
      },
    },
  })
}

const addVertices = (pos: { x: number; y: number }) => {
  if (edge) {
    edge.appendVertex(pos)
  }
}

const onMouseMove = (e: MouseEvent) => {
  if (edge) {
    const pos = graph.clientToLocal(e.clientX, e.clientY)
    edge.setTarget(pos)
  }
}

const print = () => {
  if (edge) {
    const view = graph.findViewByCell(edge) as EdgeView
    console.log(view.path.serialize())
  }
}

const finish = (closed: boolean) => {
  if (node && edge) {
    const vertices = edge.getVertices()
    if (closed) {
      if (vertices.length >= 2) {
        const center = node.getBBox().center
        edge.setSource(center)
        edge.setTarget(center)
        graph.removeNode(node)
        node = null
        print()
      } else {
        graph.removeCells([node, edge])
        node = null
        edge = null
      }
    } else {
      if (vertices.length >= 1) {
        const center = node.getBBox().center
        edge.setSource(center)
        edge.setTarget(vertices[vertices.length - 1])
        graph.removeNode(node)
        node = null
        print()
      } else {
        graph.removeCells([node, edge])
        node = null
        edge = null
      }
    }
    container.removeEventListener('mousemove', onMouseMove)
  }
}

graph.on('blank:click', ({ x, y }) => {
  init({ x, y })
  container.addEventListener('mousemove', onMouseMove)
})

graph.on('edge:click', ({ x, y }) => {
  const nodes = graph.getNodesFromPoint(x, y)
  if (nodes.length && nodes[0] === node) {
    finish(true)
  } else {
    addVertices({ x, y })
  }
})

graph.on('edge:contextmenu', () => {
  finish(false)
})
`

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
出现偏移是正常的，因为连线的 strokeWidth 是 2，当位置是奇数的时候就会出现。

**Comment by Trojanpa** [comment]
> 出现偏移是正常的，因为连线的 strokeWidth 是 2，当位置是奇数的时候就会出现。

不正常啊，strokeWidth改成1画的也不是直线啊。我发现是 graph.clientToLocal 这个方法造成的，它将客户端坐标转换画布本地坐标时出现了偏差。
