### ISSUE TITLE
safari 下 edge 有偏移

### ISSUE THREAD

**Issue by KevenYoung** [antvis/X6#1608]
在 safari 下打开 https://x6.antv.vision/apps/dag/ 可以看到所有连线都向右下偏移了

- OS: [macOS Sierra 16.6]
- Browser: [safari 版本15.1 (16612.2.9.1.30, 16612)]
![image](https://user-images.githubusercontent.com/2274547/143834841-284fd281-ce08-4f47-ad06-1aff62da3895.png)

**Comment by NewByVector** [comment]
不推荐使用 react 渲染 port，可以参考 [demo](https://x6.antv.vision/zh/examples/showcase/practices#dag) 实现，可以兼容 safari.
