### ISSUE TITLE
请问连接桩有没有hover或者click事件？

### ISSUE THREAD

**Issue by LZCaaT** [antvis/X6#1609]
### 能否像下图一样，hover显示当前连接桩的信息

![image](https://user-images.githubusercontent.com/28329423/143841860-8eaa439d-56c9-4ba9-91bf-0cf5895459f3.png)

**Comment by YJEthan** [comment]
有 
设置监听事件
graph.on("node:mouseenter", () => {
      const ports = container.querySelectorAll(".x6-port-body") as NodeListOf<
        SVGElement
      >;
      this.showPorts(ports, true);
    });
    graph.on("node:mouseleave", () => {
      const ports = container.querySelectorAll(".x6-port-body") as NodeListOf<
        SVGElement
      >;
      this.showPorts(ports, false);
    });

**Comment by YJEthan** [comment]
我好像理解错了...不过应该也能通过类似的方法实现

**Comment by LZCaaT** [comment]
> 我好像理解错了...不过应该也能通过类似的方法实现

我本意是想鼠标悬停连接桩的时候，出现tooltip提示框，翻x6文档，发现可以用vue自定义连接桩，就可以用element ui 的el-tooltip标签来实现此功能，但是怎么用vue定义连接桩？官网只有react的示例

**Comment by LZCaaT** [comment]
> 我好像理解错了...不过应该也能通过类似的方法实现

已解决

**Comment by MonkeySuncen** [comment]
如[LZCaaT]所说，我也希望鼠标放置在port上时出现tooltip（需求一），但我还有个需求，在连线时，置灰所有不能连的port（需求二）。
由于需求一需要用vue创建自定义port，它是通过onPortRendered方法重新渲染实现的。但结合需求二时，也会触发onPortRendered。
这导致两个负面效果：
1. tooltip在鼠标放置后，点击鼠标拖线，此时触发onPortRendered方法重新渲染port，**导致tooltip不再消失**。因为dom被重新渲染了，没有鼠标离开事件了。（该问题通过tooltip单例绑定事件，曲线救国解决了。。。）
2. 每次拖线时触发需求二，每个节点都会重新渲染三次（原理未知，可能是先去除port渲染一次，添加port渲染一次，置灰渲染一次）。这导致频繁重新渲染。如果使用自带circle的port，应该不会触发这么多无意义的渲染。

综上所述，若能对port添加鼠标进入。离开事件，搭配自带circle的port问题就能优雅的解决。**希望对port添加鼠标事件的监听**。

**Comment by lwstudy** [comment]
ReactDOM.render(
            (
              <Tooltip title={args.port.id}>
                <div className="my-port" />
              </Tooltip>
            ) as any,
            container as HTMLElement,
          )在Vue怎么渲染呢？

**Comment by Gaays** [comment]
@lwstudy vue中使用和main.js里面挂载vue实例一样的，记得有人在issue中回答过。

```js
onPortRendered(args) {
      const selectors = args.contentSelectors;
      const container = selectors && selectors.foContent;
      if (container) {
        new Vue({
          el: container,
          render: h => {
              return (
                <el-tooltip
                  effect='dark'
                  content='port'
                  placement='right'
                >
                  <div
                    class='my-port'
                    style='width: 100%;height:100%;border: 1px solid #5F95FF;border-radius: 100%;background: #fff;'
                  />
                </el-tooltip>
              );
          }
        });
      }
}
```

顺便抛个问题：如何优雅地动态更新port tooltip的content？
目前我是重新 `setPortProp` 赋原有的值来触发 `onPortRendered` 来更新content

**Comment by MonkeySuncen** [comment]
> @lwstudy vue中使用和main.js里面挂载vue实例一样的，记得有人在issue中回答过。
> 
> ```js
> onPortRendered(args) {
>       const selectors = args.contentSelectors;
>       const container = selectors && selectors.foContent;
>       if (container) {
>         new Vue({
>           el: container,
>           render: h => {
>               return (
>                 <el-tooltip
>                   effect='dark'
>                   content='port'
>                   placement='right'
>                 >
>                   <div
>                     class='my-port'
>                     style='width: 100%;height:100%;border: 1px solid #5F95FF;border-radius: 100%;background: #fff;'
>                   />
>                 </el-tooltip>
>               );
>           }
>         });
>       }
> }
> ```
> 
> 顺便抛个问题：如何优雅地动态更新port tooltip的content？ 目前我是重新 `setPortProp` 赋原有的值来触发 `onPortRendered` 来更新content

重新渲染会导致tooltip失去port的离开事件，结果就是tooltip不消失。
我的解决办法是自定义port组件，监听鼠标进入和离开事件。定义一个tooltip单例。所有port都共用一个tooltip。
触发鼠标进入事件时，在该位置显示tooltip，离开时tooltip消失。

**Comment by fengqingyundan1** [comment]
> @lwstudy vue中使用和main.js里面挂载vue实例一样的，记得有人在issue中回答过。
> 
> ```js
> onPortRendered(args) {
>       const selectors = args.contentSelectors;
>       const container = selectors && selectors.foContent;
>       if (container) {
>         new Vue({
>           el: container,
>           render: h => {
>               return (
>                 <el-tooltip
>                   effect='dark'
>                   content='port'
>                   placement='right'
>                 >
>                   <div
>                     class='my-port'
>                     style='width: 100%;height:100%;border: 1px solid #5F95FF;border-radius: 100%;background: #fff;'
>                   />
>                 </el-tooltip>
>               );
>           }
>         });
>       }
> }
> ```
> 
> 顺便抛个问题：如何优雅地动态更新port tooltip的content？ 目前我是重新 `setPortProp` 赋原有的值来触发 `onPortRendered` 来更新content

这么写的话，是不是得需要使用portMarkup,然后渲染之后链接桩就不在了，请问有人遇到吗？怎么解决呢？
