### ISSUE TITLE
有没有可能支持将dom对象池化？

### ISSUE THREAD

**Issue by Wing-Lo** [antvis/X6#1610]
### Expected Behavior
在节点比较多的时候，同时修改多个节点的自动布局会很卡，希望能够只修改当前已显示的节点的位置，这样是不是就效率高多了，不卡了。

### Possible Solution
但是现在底层有依赖jquery，会不会不太好实现？

**Comment by NewByVector** [comment]
现在是支持只显示可视区域内部节点的，参考[demo](https://github.com/antvis/X6/blob/master/examples/x6-example-features/src/pages/performance/async.tsx)

**Comment by Wing-Lo** [comment]
好的谢谢！我看看。
