### ISSUE TITLE
复制多个Node进行拖拽移动会发生偏移

### ISSUE THREAD

**Issue by cnbf** [antvis/X6#1613]
![start](https://user-images.githubusercontent.com/89966976/143978868-1efeaeb1-db0c-439f-9dce-d3d1393c0e61.png)
![1](https://user-images.githubusercontent.com/89966976/143978889-73bbc944-2ae4-42a1-a5db-1090aea855f0.png)

**Comment by NewByVector** [comment]
Selecting 模块导致的问题，接下来我们会重新设计 selecting 模块，并会同时修复这个问题。

**Comment by NewByVector** [comment]
提供一个 demo 看下？

**Comment by yissyoo** [comment]
我也遇到了这个问题，当时发现是对齐线的问题。解决办法是在 node:embed 事件中判断如果选中了多个节点，临时禁用对齐线。
