### ISSUE TITLE
vite项目下，使用官方实例：人工智能建模 DAG 时，浏览器报错

### ISSUE THREAD

**Issue by kent99821** [antvis/X6#1614]
### Expected Behavior
vite项目中直接使用官网实例时，浏览器报错，代码是直接使用实例的。
VM803:3 Uncaught TypeError: Class constructor ReactShape cannot be invoked without 'new'

<img width="656" alt="截屏2021-12-01 上午10 20 37" src="https://user-images.githubusercontent.com/61462124/144160495-012f1578-a1e1-43f9-b411-38a33f1ef6f1.png">

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by a136806** [comment]
we meet the same question when we use angular.

**Comment by JiquanWang99** [comment]
I meet the same question when I use vite@2.6.14

**Comment by AdmireWang** [comment]
用umd的包吧，vite配置文件加一个alias：
alias: {
        '@antv/x6-react-shape': '@antv/x6-react-shape/dist/x6-react-shape.js',
    },

**Comment by NewByVector** [comment]
需要在项目中将 Typescript 的 target 设置成 es6 或者更高的版本。

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/issues/1670#issuecomment-1002467478 可以参考这个。

**Comment by pfdgithub** [comment]
使用 webpack 遇到了同样的问题。  
发现是在 CRA@4.0.3 的开发模式下，X6 加载 x6-react-shape 插件时，使用了 function 方式去加载 class 风格的插件造成的。  
详细信息参见 https://github.com/antvis/X6/pull/2084
