### ISSUE TITLE
当调用formJson方法时，出现报错：TypeError: Cannot read properties of null (reading 'getZIndex') 

### ISSUE THREAD

**Issue by BubblyFace** [antvis/X6#1616]
当调用formJson方法时，出现报错：TypeError: Cannot read properties of null (reading 'getZIndex')

### Expected Behavior

预期节点正常更新

### Current Behavior

TypeError: Cannot read properties of null (reading 'getZIndex')

![image](https://user-images.githubusercontent.com/20941782/144449776-9e543165-1b3b-40dc-bf6e-7afcca4463de.png)

**Comment by NewByVector** [comment]
能否发一下数据？

**Comment by NewByVector** [comment]
无法复现问题，先关闭，如果有问题，请重新提 issue。
