### ISSUE TITLE
通过registerAngularContent等方式添加上vue/react/angular等组件，通过toPNG导出的图片中丢失了添加上去的组件内容（canvas图）

### ISSUE THREAD

**Issue by cow-Rong** [antvis/X6#1620]
通过registerAngularContent等方式添加上vue/react/angular等组件，我在组件中使用了echarts组件，内部其实渲染出来的是个echarts的canvas，这种情况很常见，但是此情况下通过toPNG导出的图片中丢失了添加上去的组件内容（canvas图）。

希望能将添加组件内的canvas内容也导出。

添加angular-echarts组件
![image](https://user-images.githubusercontent.com/31033412/144742709-20f691ad-f5b5-4e60-aa8b-ad60a954cccc.png)
![image](https://user-images.githubusercontent.com/31033412/144742744-6c7771f9-f0ee-4e96-bb4d-faae32e103d5.png)

导出黑色空白内容
![image](https://user-images.githubusercontent.com/31033412/144742717-9cd989d5-2dc3-48c8-aae5-27c092b26e11.png)

环境：windos10 
浏览器：谷歌

**Comment by NewByVector** [comment]
这个太黑科技了，暂时不支持的。

**Comment by GreatAuk** [comment]
@cow-Rong 因为 `echarts` 的 wrap 有 `position: relative` 样式，放置在 `foreignObject` 里浏览器兼容性特别差。有注意到这个问题吗

**Comment by RootJian** [comment]
节点中包含了canvas图形时 层级会出现问题
