### ISSUE TITLE
画布能否支持双指平移

### ISSUE THREAD

**Issue by Robin-front** [antvis/X6#1629]
画布能否支持双指平移

### Expected Behavior

画布能否支持双指平移

### Additional Context
目前只能单击拖动平移画布，对于只使用触摸板的用户不友好

**Comment by NewByVector** [comment]
支持的，可以查看[文档](https://x6.antv.vision/zh/docs/tutorial/basic/graph#%E5%B9%B3%E7%A7%BB%E3%80%81%E7%BC%A9%E6%94%BE%E3%80%81%E5%B1%85%E4%B8%AD)
