### ISSUE TITLE
调整节点大小，可以设置只调整宽度或者高度吗？

### ISSUE THREAD

**Issue by daughterRui** [antvis/X6#1630]
现在设置resizing后，宽度和高度都能调整。我现在需要的场景是只调整宽度,有什么方法吗？

**Comment by NewByVector** [comment]
可以使用样式隐藏部分控制点，只显示左右两侧的。

**Comment by daughterRui** [comment]
好的，谢谢，已解决

**Comment by MrMengJ** [comment]
> 可以使用样式隐藏部分控制点，只显示左右两侧的。

有没有什么方式设置特定的图形隐藏部分控制点，其它的图形不隐藏控制点

**Comment by MrMengJ** [comment]
> 可以使用样式隐藏部分控制点，只显示左右两侧的。

@NewByVector 请问有没有什么方式设置特定的图形隐藏部分控制点，其它的图形不隐藏控制点
