### ISSUE TITLE
自定义节点中输入框input导出图片文字不显示

### ISSUE THREAD

**Issue by sunhangye** [antvis/X6#1631]
### Expected Behavior

在官网示例https://x6.antv.vision/zh/examples/node/custom-node#custom-with-react
1. 在`render`函数增加
```
<input style={{
    border: '1px solid red',
    color: 'red'
  }} />
```
2. 增加点击事件
```
graph.on('node:click', () => {
  graph.toPNG(dataUrl => {
   console.log(dataUrl)
  }, {
  copyStyles: false
  })
});
```
### Current Behavior
预期效果
![image](https://user-images.githubusercontent.com/19857469/144978761-81523f28-fabb-4981-a22e-95839bf845bb.png)
实际导出效果
![image](https://user-images.githubusercontent.com/19857469/144978858-c125a7ce-1124-4e0c-85bf-ccb3229d5580.png)

**Comment by NewByVector** [comment]
导出的时候需要当前的 input 上有 value 属性。你可以这样操作：
```html
<input type="text" onInput={this.onChange}/>

onChange = (e) => {
  e.target.setAttribute('value', e.target.value)
}
```

**Comment by sunhangye** [comment]
![企业微信截图_1639623423935](https://user-images.githubusercontent.com/19857469/146300093-cc985c9b-c78f-4635-9912-470798a82ca6.png)
我这边按照您给的方法往input添加了value属性 图片导出跟我上面添加的实际导出的图片一样 没有变化

**Comment by NewByVector** [comment]
`copyStyle` 设置为 `true`

**Comment by sunhangye** [comment]
![企业微信截图_16396241303894](https://user-images.githubusercontent.com/19857469/146301169-b3f4b363-c31f-4dc3-8298-1203a909c513.png)
copyStyle设置为true 可以导出来了。不过copyStyle为true 导出会复制整个页面样式晃动 这个问题比上面的图片导出输入框文字不显示更加不能接受吧。。

**Comment by NewByVector** [comment]
这里是因为页面 dom 数量巨大所有会有抖动，你可以实际项目中试试。
