### ISSUE TITLE
请问如何使用onEdgeLabelRendered自定义vue label

### ISSUE THREAD

**Issue by Xu-Catherine** [antvis/X6#1632]
请问如何使用onEdgeLabelRendered自定义vue label，官网都是react的例子，请问是否能提供个vue的例子，试了好几次都没有成功

**Comment by NewByVector** [comment]
不推荐这么使用，如果必须这么用的话可以参考[demo](https://codesandbox.io/s/vue-label-ehiuz)

**Comment by Hxmic** [comment]
![image](https://user-images.githubusercontent.com/23522154/146893114-0b7aa377-ecf7-4e5b-89ec-4a5895a9d4de.png)
我们有个 这个使用的场景，但是没有找到更好的方法，现在使用的是 上面的demo，但是传递值，没有成功，请问下，有没有相关的例子。。   @NewByVector  感谢感谢

**Comment by mumujialiang** [comment]
> 

如何拿到类似 inject: ['getGraph', 'getNode'] 的方法呢

**Comment by mumujialiang** [comment]
> 不推荐这么使用，如果必须这么用的话可以参考[demo](https://codesandbox.io/s/vue-label-ehiuz)

如何拿到类似 inject: ['getGraph', 'getNode'] 的方法呢 @NewByVector
