### ISSUE TITLE
当画布过大时，单独使用小地图时，小地图内容展示不全，只展示部分可见画布内容

### ISSUE THREAD

**Issue by naanna** [antvis/X6#1633]
### Expected Behavior
当画布过大时，单独使用小地图时，画布内容小地图能够展示正常。

### Current Behavior
在1.28.1版本下，
当画布过大时，单独使用小地图时，小地图内容展示不全，只展示部分可见画布内容

```
   new Graph({
        container: document.getElementById('view'),
        mousewheel:true,
        panning: true,
        minimap: {
          enabled: true,
          container: document.getElementById('view-minimap'),
          width: 200,
          height: 150,
          padding: 20,
        },
      }).fromJSON(data);
      graph.zoomToFit({ padding: 50 });
```
![image](https://user-images.githubusercontent.com/23169712/145327190-704d52d7-cd55-4d73-af16-2c9330f433c2.png)

- x6: [e.g. 1.28.0]

**Comment by qq454470755** [comment]
scroller: {
					enabled: boolean,
					pannable: boolean,
					pageVisible: boolean,
					pageBreak: boolean,
				},

**Comment by NewByVector** [comment]
@naanna 提供一个 demo 看下？

**Comment by zhang-ning** [comment]
上图的原因是，非scroller模式（使用graph.panning 模式），minimap不能自动计算graph大小

**Comment by NINGyv179** [comment]
> 上图的原因是，非scroller模式（使用graph.panning 模式），minimap不能自动计算graph大小

怎么解决呀

**Comment by naanna** [comment]
> @naanna 提供一个 demo 看下？

我的demo耦合业务了。可以试试小框画布，节点相差距离超过画布的情况
