### ISSUE TITLE
滚轮缩放到很小的时候，如果鼠标位置不在svg元素上，则无法平移画布

### ISSUE THREAD

**Issue by hysma** [antvis/X6#1635]
### Expected Behavior
draw.io在画布缩放任何比例下，画布范围内都可以实现画布平移，期待x6也能支持这个功能

### Current Behavior
https://codesandbox.io/s/restless-architecture-tjfgi

效果如下图：
![mouse-wheel](https://user-images.githubusercontent.com/15029293/145506240-c731ca56-5c4c-4cf4-b1ee-804810022d0a.gif)

### Possible Solution
对比了一下draw.io和X6在放大缩小后平移问题：
1、draw.io的处理方式，他的画布是svg元素，缩小的时候是背景和各节点元素同步缩小。它background范围根据添加节点情况修改。
2、X6在这一块与draw.io的处理方式相反

目前是否可以内部处理一下使得鼠标放在backgroud上但不在svg元素范围内的时候也能实现拖拽操作

### Steps To Reproduce

1. 使用滚轮缩放到一定情况
2. 鼠标右键长按拖动（mac双指按下拖动）
3. 在svg元素范围内拖动，可正常拖动
4. 鼠标在画布范围内，但不在svg元素范围内，右键无法实现长按拖动

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.26.2]
- OS: [e.g. macOS Big Sur 11.2.3]
- Browser: [e.g. chrome 96.0.4664.55]

**Comment by OpportunityLiu** [comment]
其实框选也有这个问题。。。

**Comment by hysma** [comment]
> 其实框选也有这个问题。。。
是的，框选的时候会出现鼠标按下的落点在svg元素外时，第一次可正常框选，之后鼠标按下时落点在svg元素外时，则无法进行框选，我目前是把svg里的流程图上下各移动一个margin来简单处理了下

**Comment by hysma** [comment]
> 其实框选也有这个问题。。。

是的，框选的时候会出现鼠标按下的落点在svg元素外时，第一次可正常框选，之后鼠标按下时落点在svg元素外时，则无法进行框选，我目前是把svg里的流程图上下各移动一个margin来简单处理了下
