### ISSUE TITLE
如何对自定义节点的子项polyline类型的refPoints点进行固定，而不是随ref的宽高变化导致线段撑满

### ISSUE THREAD

**Issue by SHIXUNXUN** [antvis/X6#1636]
`      
      Graph.registerNode('Sampler',{
        inherit: 'rect',
        width: 200,
        height: 200,
        markup:[
          {
            tagName: 'rect',
            selector: 'body',
          },
          {
            tagName: 'ellipse',
            selector: 'ellipse1', 
          },
          {
            tagName: 'ellipse',
            selector: 'ellipse2', 
          },
          {
            tagName: 'polyline',
            selector: 'polyline1', 

          },
          // {
          //   tagName: 'polygon',
          //   selector: 'polygon2', 

          // },
          // {
          //   tagName: 'polygon',
          //   selector: 'polygon3', 
          // },
        ],
        attrs: {
          body: {
            stroke: '#5755a1',
            fill: 'none',
          },
          ellipse1: {
            ref: 'body',
            refCx:0.325,
            refCy:0.5,
            refRX: 0.05,
            refRy: 0.05,
            stroke: 'rgba(0,0,255)',
            fill: 'rgba(255,255,255)',
          },
          ellipse2: {
            ref: 'body',
            // refCx:135,
            // refCy:100,
            refCx:0.675,
            refCy:0.5,
            refRX: 0.05,
            refRy: 0.05,
            stroke: 'rgba(0,0,255)',
            fill: 'rgba(255,255,255)',
          },
          polyline1:{
            // ref: 'body',
            points:'0,100 55,100',
            stroke: 'rgba(0,0,255)',
          },
          polyline2:{
            ref: 'body',
            points:'145,100 200,100',
            stroke: 'rgba(0,0,255)',
          },
          polyline3:{
            ref: 'body',
            fill:'none',
            points:'65,100 130,65',
            stroke: 'rgba(0,0,255)',
          }
        },
      })
      const Sampler = graph.addNode({
          shape: 'Sampler',
          x: 200,
          y: 200,
          attrs: { 
            body: {
              fill: 'none',
              stroke: '#000',
            }
          }
      })
      Sampler.scale(0.5,0.5)

`
在对自定义节点缩放后，其中polyline进行随ref节点的宽高等比缩放，实际polyline1想实现0-55的一条线，结果缩放后被拉到了200的rect宽高，进行了同步放大。由0~55变为了0-200的线段
请问如何处理该类情况？

**Comment by NewByVector** [comment]
你给的 demo 实现的效果是：polyline1 的位置一直是 (0,100 55,100) 并没有随着缩放而缩放。这个 issue 我先关闭，如果还有疑问，请再提一个issue，并提供复现 demo。
