### ISSUE TITLE
怎么实现bpmn的中间/边界事件？

### ISSUE THREAD

**Issue by wangyu142857** [antvis/X6#1637]
![image](https://user-images.githubusercontent.com/24771813/145669733-4e7416b7-05ef-448e-8342-821d954d790a.png)
这种效果有没有示例或者思路什么的，只允许拖动到边界上，拖上去后合成一个整体

**Comment by NewByVector** [comment]
1. 监听箭头所指圆环的移动事件，如果和中间图形相交
2. 删除圆环并且修改中间图形的 markup，增加圆环
