### ISSUE TITLE
群组复制或剪切后粘贴显示异常

### ISSUE THREAD

**Issue by weiqianglin** [antvis/X6#1639]
### Expected Behavior
复制或剪切群组后进行粘贴，群组可以正常显示

### Current Behavior
复制或剪切群组后进行粘贴，群组显示不出来

### Steps To Reproduce

示例：https://codesandbox.io/s/copycut-u0n4k?file=/src/App.vue
1. 选中父节点“parent”
2. 复制（ctrl+c）并粘贴（ctrl+v）
3. 粘贴的节点无法正常显示

### Additional Context

复制粘贴群组后再复制粘贴下群组外的其他节点，群组这时候也可以显示出来了，但是粘贴的群组除了父节点位置偏移了之外，
父节点内部的子节点也偏移了，这里只偏移父节点的位置，子节点的位置相对于父节点不变是否更加合适
### Your Environment

- x6: [e.g. 1.28.1]
- OS: [e.g. windows 10]
- Browser: [e.g. chrome  96.0.4664.93]

**Comment by NewByVector** [comment]
这个是 codesanbox 的缺陷，在本地没有问题的。
