### ISSUE TITLE
像这种hello连接到world, world连接到hello的连线, 如何才能不重叠

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1643]
![image](https://user-images.githubusercontent.com/33592850/145917424-54a583f5-8d3e-4151-850c-5416ec6f778d.png)

**Comment by NewByVector** [comment]
可以使用 [NodeAnchor](https://x6.antv.vision/zh/docs/api/registry/node-anchor) 来解决中问题。

**Comment by cheng-xiaofeng** [comment]
> 可以使用 [NodeAnchor](https://x6.antv.vision/zh/docs/api/re
我用nodeAnchor了, 但是这三种特殊情况怎么解决呢?同一水平线 垂直线  还有斜下方这种, 还是重合的
![360截图20211215132931706](https://user-images.githubusercontent.com/33592850/146129206-46d7644c-b4be-49ca-8122-83dfda6be8fa.jpg)
![360截图20211215132943546](https://user-images.githubusercontent.com/33592850/146129213-2f776451-a117-45d4-834b-336e692edbc2.jpg)
![360截图20211215132954587](https://user-images.githubusercontent.com/33592850/146129221-ecaf9940-7aa3-4946-ba36-f0d1c3447049.jpg)

**Comment by NewByVector** [comment]
如果是使用所有场景，需要自定义连接器了。
