### ISSUE TITLE
vite项目下 打包部署生产环境 报错Cannot read properties of undefined (reading 'layout')

### ISSUE THREAD

**Issue by lemonly14** [antvis/X6#1644]
vite 2.6.12

**Comment by lemonly14** [comment]
@antv/x6 1.28.1

**Comment by lemonly14** [comment]
有点特殊的是借助dagre-d3@0.6.4进行自动布局

**Comment by NewByVector** [comment]
这个是 [layout](https://github.com/antvis/layout) 的问题。

**Comment by findjh** [comment]
@lemonly14  我部署到线上报readinh ' preorder '。请问你的解决方式是什么呢？help me

**Comment by NewByVector** [comment]
@findjh 完整报错信息发一下呢？

**Comment by mugo1993-ss** [comment]
vite 打包部署之后报 TypeError: Cannot read properties of undefined (reading 'constant')，请问怎么解决呢？
