### ISSUE TITLE
两个节点之间的连线不重叠

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1645]
当两个节点位于同一水平线或者垂直线或者斜下方时, 两条边不重叠
### Expected Behavior

![360截图20211215140943493](https://user-images.githubusercontent.com/33592850/146132937-bc39735b-a6d4-477c-b7f9-60b487fae5fa.jpg)

### Possible Solution
虽然有回复说要自定义连接器,我还是不大懂怎么写,

如果可以吧交接点的位置分开的话,那链接边应该也分开了吧
### Additional Context
我也会先找找方法, 看能不能做到, 不过如果官方直接就支持的话,就更好了

**Comment by NewByVector** [comment]
这个[demo](https://codesandbox.io/s/offset-edge-mrpwy)是否符合你要求。

**Comment by cheng-xiaofeng** [comment]
> 这个[demo](https://codesandbox.io/s/offset-edge-mrpwy)是否符合你要求。

这个是单向的, 我现在做的项目要求是双向的, 1 连到2, 2连到1, 这两条线不能重叠

**Comment by NewByVector** [comment]
方案是类似的
