### ISSUE TITLE
如何将图片作为一个节点拖拽到画布

### ISSUE THREAD

**Issue by 1134961980** [antvis/X6#1648]
在vue中如何将图片作为一个节点向拖拽到画布上，并且节点之间可以拖拽连线？期望得到回答，谢谢！

**Comment by NewByVector** [comment]
可以使用[图片节点](https://x6.antv.vision/zh/examples/node/native-node#image)

**Comment by 1134961980** [comment]
> 可以使用[图片节点](https://x6.antv.vision/zh/examples/node/native-node#image)

必须是svg格式的图片吗？

**Comment by 1134961980** [comment]
> 可以使用[图片节点](https://x6.antv.vision/zh/examples/node/native-node#image)

谢谢

**Comment by 1134961980** [comment]
> 可以使用[图片节点](https://x6.antv.vision/zh/examples/node/native-node#image)

在上下放大节点时，图片不随着image标签的放大而放大！
![image](https://user-images.githubusercontent.com/66771066/146492684-987adfe4-8f3f-406e-9efc-cf768beaf610.png)

**Comment by Haozhicong** [comment]
可以同过设置图片宽高100%

**Comment by NewByVector** [comment]
参考这个 [demo](https://codesandbox.io/s/resizing-image-oi57j)
