### ISSUE TITLE
路径动画无法设置成底层被其他组件阻挡

### ISSUE THREAD

**Issue by cnbf** [antvis/X6#1653]
![X 698`JL~(G4470_J1MGBE](https://user-images.githubusercontent.com/89966976/146481121-91031c27-3755-42ff-82f3-97862d98fc9b.png)
![EPV83X@CBQE9`V$5RP@~IJB](https://user-images.githubusercontent.com/89966976/146481135-32dea40a-e7b8-4412-aa8f-e59670396c9a.png)

**Comment by NewByVector** [comment]
参考这个：https://x6.antv.vision/zh/examples/animation/smil#animateAlongPath
