### ISSUE TITLE
我该如何获取连接桩的信息或者说获取节点的连接信息

### ISSUE THREAD

**Issue by Vergil-coder** [antvis/X6#1663]
### 功能描述

你好～如下图所示 这一条线我是不期望出现的 于是我应该去`validateConnection`进行处理 当判断到目标节点有其他连接时返回`false` 但是我没有找到`api`可以帮助我找到目标节点的已经连接情况（比如连接了哪些连接桩）
![image](https://user-images.githubusercontent.com/66655588/146667531-e37ad411-4fc6-415c-9da9-3d1056067363.png)

### 期望解决方案

是否有对应的`api`可以提供使用 又或者是有其他的方法可以解决该类问题？望回答

**Comment by NewByVector** [comment]
[文档](https://x6.antv.vision/zh/docs/api/graph/model/#getconnectededges)
