### ISSUE TITLE
连接桩的输入和输出

### ISSUE THREAD

**Issue by 1134961980** [antvis/X6#1664]
### 问题描述

如何规定一个连接桩只能输入，一个连接桩只能输出呢？

### 重现链接

https://antv-x6.gitee.io/zh/examples/edge/router#one-side

### 重现步骤

创建两个连接桩一个只能输入一个只能输出，类似于单侧路由这种

### 预期行为

希望得到帮助，谢谢

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以参考[demo](https://codesandbox.io/s/in-out-tdnm5)
