### ISSUE TITLE
Stencil 中使用 registerNode 添加的 shape 偏移计算似乎没正常触发

### ISSUE THREAD

**Issue by sarufarr** [antvis/X6#1666]
### 问题描述

自定义了一个 `rect`+`image` 的节点 `image` 垂直水平居中

在画布中 `image` 居中
在 `Stencil` 中 `attr` 的设置并没有被计算为二位偏移量
但是拖拽过程中的代理画布 和 拖拽结束的主画布 上的自定义节点却是正常的

### 重现链接

https://codesandbox.io/s/keen-cerf-pse92?file=/src/app.tsx

### 重现步骤

进入页面

### 预期行为

期望:
在 `Stencil` 中 `attr` 的设置被计算为二位偏移量
自定义节点的长宽被正确结算

实际:
both negative

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 1.29.0

### 屏幕截图或视频（可选）

`Stencil` 中的
![image](https://user-images.githubusercontent.com/14183804/146706893-f12b0854-6d8d-46f5-a2d8-defa0e31746d.png)
 
与 `canvas` 中的
![image](https://user-images.githubusercontent.com/14183804/146706992-26a506b6-3d1e-4dcd-8988-a1667572898c.png)

在本地 demo 中的错位
![image](https://user-images.githubusercontent.com/14183804/146707928-8291a96f-eff4-4c7c-8296-9b7f1193c09a.png)

**Comment by sarufarr** [comment]
更新
自定义组件  进入 `updateRelativeAttrs` 后获取的 `bbox` 是个 0000 的矩形
不是很明白 是因为还没有挂载到 DOM 上的原因吗

**Comment by NewByVector** [comment]
属性设置有误，我在你给的链接基础上做了修改：https://codesandbox.io/s/new-node-hdo3n
