### ISSUE TITLE
ER图 图表实例无法正常显示

### ISSUE THREAD

**Issue by Alt-er** [antvis/X6#1667]
### Describe the bug

https://codesandbox.io/s/6gmvn
官方提供的ER图示例无法正常显示，我本地编写相同代码也无法显示，div高度一直是0。

### Your Example Website or App

https://codesandbox.io/s/6gmvn

### Steps to Reproduce the Bug or Issue

打开地址后页面是空白的

### Expected behavior

希望能显示出官网的ER图效果

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Alt-er** [comment]
找到问题了，示例代码中没有设置宽高。
`const graph = new Graph({
      container: document.getElementById("container"),
      width: 800,
      height: 600,
      ...
     })`
请更新示例代码。

**Comment by NewByVector** [comment]
如果不传的 `width` 和 `height`,以容器的宽高来决定画布大小，所以官网示例是好的，你的场景应该是容器还没渲染就初始化画布了。

**Comment by Alt-er** [comment]
> 如果不传的`width`和`height`，以容器的宽高来决定画布的大小，所以官网的表现是好的，你的场景应该是容器尚未渲染就初始化画布了。

但是官网示例界面右上角链接的 CodeSandbox 与 StackBlitz 中都无法显示出正常的页面。像我这种初次使用者是否造成了困扰？会认为官方示例的代码有问题。至少在CodeSandbox中应该显示出官网示例的效果


我打开CodeSandbox 后的效果
![image](https://user-images.githubusercontent.com/18004903/146748399-895d3727-340d-4d1f-a20c-fba6112c417e.png)
