### ISSUE TITLE
能否直接使用通过registerVueComponent注册的vue自定义节点

### ISSUE THREAD

**Issue by lulei90** [antvis/X6#1670]
### 功能描述

使用`registerVueComponent`方法注册vue节点后，在画布上添加改节点的时候必须指明`shape`参数为`vue-shape`,以及`component`参数为对应使用`registerVueComponent`注册的名字，能否像使用`registerNode`方法注册的节点一样，直接能够通过对应注册名标注shape后使用

### 期望解决方案

期望registerNode方法能够直接支持vue组件节点的注册

**Comment by Hxmic** [comment]
使用这种的registerVueComponent， 大佬如何使用 @antv/layout  进行布局的？ 

我还是使用的dagre 这个进行布局。

**Comment by NewByVector** [comment]
@lulei90 原来方式给你带来了什么问题？

**Comment by NewByVector** [comment]
@Hxmic layout 参考官网示例

**Comment by Hxmic** [comment]
@NewByVector  我是参考官网了，然后好久没有找到  @antv/x6-vue-shape 生成node节点， 通过@antv/layout 进行布局渲染的demo

**Comment by Hxmic** [comment]
> @Hxmic layout 参考官网示例

大佬，有demo 吗？    是真心没有找到，这方面的。

**Comment by Hxmic** [comment]
> @Hxmic layout 参考官网示例

可以出个 @antv/layout  对createNode 生成的节点的布局的demo吗？ 现在只找到了， 这个老的demo(还是通过dagre)  [https://github.com/antvis/X6/blob/f2e674c0b4e5d8f682142410433f7a93226b233a/sites/x6-sites/examples/showcase/practices/demo/orgchart.ts](官网代码)

**Comment by lulei90** [comment]
> @lulei90 原来方式给你带来了什么问题？
项目里面用了特定的json结构来集中初始注册自定义的节点，在注册过程中得区分不同的自定义节点类型，比如html节点和vue节点，并且在实际的使用中没法想svg节点一样根据shape就能直接使用添加，还得区分shape、component以及html等字段，这种不一致的问题导致实际编码过程中得去处理这些差异

**Comment by NewByVector** [comment]
@lulei90 推荐的方式是：
```ts
Graph.registerNode(
    'custom-name',
    {
      inherit: 'react-shape',
      width: 60,
      height: 60,
      component: <Component />,
    },
    true,
  );
```
这样你使用节点的时候可以直接：
```ts
const node = graph.createNode({
  shape: 'custom-name'
})
```

**Comment by lulei90** [comment]
> 


> @lulei90 推荐的方式是：
> 
> ```ts
> Graph.registerNode(
>     'custom-name',
>     {
>       inherit: 'react-shape',
>       width: 60,
>       height: 60,
>       component: <Component />,
>     },
>     true,
>   );
> ```
> 
> 这样你使用节点的时候可以直接：
> 
> ```ts
> const node = graph.createNode({
>   shape: 'custom-name'
> })
> ```
使用`inherit: 'vue-shape'`这种写法会报错
![image](https://user-images.githubusercontent.com/10334832/147326535-3749a34b-5327-4bac-a340-b113a4707bb4.png)

**Comment by lijing666** [comment]
> > 
> 
> > @lulei90 推荐的方式是：
> > ```ts
> > Graph.registerNode(
> >     'custom-name',
> >     {
> >       inherit: 'react-shape',
> >       width: 60,
> >       height: 60,
> >       component: <Component />,
> >     },
> >     true,
> >   );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样你使用节点的时候可以直接：
> > ```ts
> > const node = graph.createNode({
> >   shape: 'custom-name'
> > })
> > ```
> 
> 使用`inherit: 'vue-shape'`这种写法会报错 ![image](https://user-images.githubusercontent.com/10334832/147326535-3749a34b-5327-4bac-a340-b113a4707bb4.png)

你需要对x6模块进行babel转换，x6的代码部分代码(class语法)并不能直接在浏览器端运行的

**Comment by lulei90** [comment]
> > > 
> > 
> > 
> > > @lulei90 推荐的方式是：
> > > ```ts
> > > Graph.registerNode(
> > >     'custom-name',
> > >     {
> > >       inherit: 'react-shape',
> > >       width: 60,
> > >       height: 60,
> > >       component: <Component />,
> > >     },
> > >     true,
> > >   );
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这样你使用节点的时候可以直接：
> > > ```ts
> > > const node = graph.createNode({
> > >   shape: 'custom-name'
> > > })
> > > ```
> > 
> > 
> > 使用`inherit: 'vue-shape'`这种写法会报错 ![image](https://user-images.githubusercontent.com/10334832/147326535-3749a34b-5327-4bac-a340-b113a4707bb4.png)
> 
> 你需要对x6模块进行babel转换，x6的代码部分代码(class语法)并不能直接在浏览器端运行的

报错是在谷歌浏览器96.0.4664.110，是支持class语法的
并且报错提示信息是 为使用new 关键字创建VueShape 和babel应该没撒关系

**Comment by lulei90** [comment]
@lijing666 有代码参考示例吗？

**Comment by lijing666** [comment]
> @lijing666 有代码参考示例吗？

我的项目是基于vuecli的，增加配置
```
transpileDependencies: [/[/\\]node_modules[/\\]@antv\/x6[/\\]/]
```
配合babel转换就可以了，因为默认webpack都是不转换node_modules的模块的

**Comment by lulei90** [comment]
> > @lijing666 有代码参考示例吗？
> 
> 我的项目是基于vuecli的，增加配置
> 
> ```
> transpileDependencies: [/[/\\]node_modules[/\\]@antv\/x6[/\\]/]
> ```
> 
> 配合babel转换就可以了，因为默认webpack都是不转换node_modules的模块的

试了下在vue-cli开发环境是正常的，本地的vite开发环境，引入x6的时候 参考了这条issues https://github.com/vitejs/vite/issues/3413
引入x6的路径替换成了‘@antv/x6/lib’;就会有这个问题，
如果配置了
```js
resolve: {
   alias: [
     {
        find: '@antv/x6',
        replacement: '@antv/x6/lib',
      },
     {
        find: '@antv/x6-vue-shape',
        replacement: '@antv/x6-vue-shape/lib',
      },
  ]
}
```
页面会报错
![image](https://user-images.githubusercontent.com/10334832/147430466-9b3b1d8b-8388-4ec5-941d-376244713c8e.png)
不知道这个问题在vite开发环境下要如何解决

**Comment by lijing666** [comment]
> > > @lijing666 有代码参考示例吗？
> > 
> > 
> > 我的项目是基于vuecli的，增加配置
> > ```
> > transpileDependencies: [/[/\\]node_modules[/\\]@antv\/x6[/\\]/]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 配合babel转换就可以了，因为默认webpack都是不转换node_modules的模块的
> 
> 试了下在vue-cli开发环境是正常的，本地的vite开发环境，引入x6的时候 参考了这条issues [vitejs/vite#3413](https://github.com/vitejs/vite/issues/3413) 引入x6的路径替换成了‘@antv/x6/lib’;就会有这个问题， 如果配置了
> 
> ```js
> resolve: {
>    alias: [
>      {
>         find: '@antv/x6',
>         replacement: '@antv/x6/lib',
>       },
>      {
>         find: '@antv/x6-vue-shape',
>         replacement: '@antv/x6-vue-shape/lib',
>       },
>   ]
> }
> ```
> 
> 页面会报错 ![image](https://user-images.githubusercontent.com/10334832/147430466-9b3b1d8b-8388-4ec5-941d-376244713c8e.png) 不知道这个问题在vite开发环境下要如何解决

vite开发模式是原生es6的，默认也应该用的es6版本的x6吧，按道理应该不会有问题，如果报错可能确实是bug，我没有在vite环境下使用，现在项目都用的webpack + vue2

**Comment by lijing666** [comment]
> > > @lijing666 有代码参考示例吗？
> > 
> > 
> > 我的项目是基于vuecli的，增加配置
> > ```
> > transpileDependencies: [/[/\\]node_modules[/\\]@antv\/x6[/\\]/]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 配合babel转换就可以了，因为默认webpack都是不转换node_modules的模块的
> 
> 试了下在vue-cli开发环境是正常的，本地的vite开发环境，引入x6的时候 参考了这条issues [vitejs/vite#3413](https://github.com/vitejs/vite/issues/3413) 引入x6的路径替换成了‘@antv/x6/lib’;就会有这个问题， 如果配置了
> 
> ```js
> resolve: {
>    alias: [
>      {
>         find: '@antv/x6',
>         replacement: '@antv/x6/lib',
>       },
>      {
>         find: '@antv/x6-vue-shape',
>         replacement: '@antv/x6-vue-shape/lib',
>       },
>   ]
> }
> ```
> 
> 页面会报错 ![image](https://user-images.githubusercontent.com/10334832/147430466-9b3b1d8b-8388-4ec5-941d-376244713c8e.png) 不知道这个问题在vite开发环境下要如何解决

vite开发模式是原生es6的，默认也应该用的es6版本的x6吧，按道理应该不会有问题，如果报错可能确实是bug，我没有在vite环境下使用，现在项目都用的webpack + vue2

**Comment by lulei90** [comment]
> > > > @lijing666 有代码参考示例吗？
> > > 
> > > 
> > > 我的项目是基于vuecli的，增加配置
> > > ```
> > > transpileDependencies: [/[/\\]node_modules[/\\]@antv\/x6[/\\]/]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 配合babel转换就可以了，因为默认webpack都是不转换node_modules的模块的
> > 
> > 
> > 试了下在vue-cli开发环境是正常的，本地的vite开发环境，引入x6的时候 参考了这条issues [vitejs/vite#3413](https://github.com/vitejs/vite/issues/3413) 引入x6的路径替换成了‘@antv/x6/lib’;就会有这个问题， 如果配置了
> > ```js
> > resolve: {
> >    alias: [
> >      {
> >         find: '@antv/x6',
> >         replacement: '@antv/x6/lib',
> >       },
> >      {
> >         find: '@antv/x6-vue-shape',
> >         replacement: '@antv/x6-vue-shape/lib',
> >       },
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 页面会报错 ![image](https://user-images.githubusercontent.com/10334832/147430466-9b3b1d8b-8388-4ec5-941d-376244713c8e.png) 不知道这个问题在vite开发环境下要如何解决
> 
> vite开发模式是原生es6的，默认也应该用的es6版本的x6吧，按道理应该不会有问题，如果报错可能确实是bug，我没有在vite环境下使用，现在项目都用的webpack + vue2

vite降级到`2.2.4`就正常了，建议排查下，用vite加x6貌似绕不过这个坑

**Comment by lulei90** [comment]
vite降级到2.2.4就正常了，建议排查下，用vite加x6貌似绕不过这个坑

**Comment by lijing666** [comment]
> vite降级到2.2.4就正常了，建议排查下，用vite加x6貌似绕不过这个坑

我今天也遇到报错的问题了，从堆栈可以看出是使用了nodejs的inherits库，所以还是babel转换的问题了，
![image](https://user-images.githubusercontent.com/26834700/147644239-16584a66-fdf3-45c3-9a1e-d9548866d04c.png)
我的vue-cli工程添加了下面的配置已经解决了，你的vite可以找一下相关配置看看
``transpileDependencies: [/[/\\]node_modules[/\\]@antv\/x6[/\\]/, /[/\\]node_modules[/\\]@antv\/x6-vue-shape[/\\]/]``

**Comment by NewByVector** [comment]
@lulei90 https://github.com/antvis/X6/pull/1723
