### ISSUE TITLE
导出png图片时报错，Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'

### ISSUE THREAD

**Issue by joze2016** [antvis/X6#1671]
### 问题描述

导出PNG的时候失败，报错信息如下
webpack:///./node_modules/@antv/x6/es/util/datauri/index.js:32 
Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.
    at window.FileReader.CHUNK_SZ (index.js:32)
    at MockXMLHttpRequest.<anonymous> (index.js:65)
    at MockXMLHttpRequest.dispatchEvent (mock.js:8472)
    at XMLHttpRequest.handle (mock.js:8304)

### 重现链接

x

### 重现步骤

1、绘制包含一个url图片的节点
2、使用toPNG导出
3、导出报错

### 预期行为

希望导出PNG，但是得到一个错误信息

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- X6 版本: [1.29.0]

**Comment by NewByVector** [comment]
给一个复现链接或者代码

**Comment by joze2016** [comment]
找到问题了，是因为我使用了Mockjs造成的
