### ISSUE TITLE
使用网格布局的防止重叠功能无效

### ISSUE THREAD

**Issue by Trojanpa** [antvis/X6#1673]
### 问题描述

点击打开官网中网格布局的CodeSandbox示例，添加了防止重叠的代码（preventOverlap: true, preventOverlapPadding: 10），发现节点还是可以重叠。

### 重现链接

https://codesandbox.io/s/sweet-engelbart-h9g88?file=/src/app.tsx:1207-1272

### 重现步骤

1.点击打开官网中网格布局的CodeSandbox示例；
2.添加防止重叠的代码（preventOverlap: true, preventOverlapPadding: 10），并保存；
3.拖动节点进行重叠；
4.最终发现节点还是可以重叠，并无防止重叠功能。

### 预期行为

期望网格布局的防止重叠功能可以生效。

### 平台

- 操作系统: [ Windows, , React Native ]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.29.0 ]

### 屏幕截图或视频（可选）

![Honeycam 2021-12-21 18-09-06](https://user-images.githubusercontent.com/42988574/146913806-bcd9a288-364d-417d-9000-e3b6b388b912.gif)

### 补充说明（可选）

业务场景：画布中部分节点不可重叠。

**Comment by NewByVector** [comment]
防重叠并不是指移动节点后自动避开，而是指一次布局期间节点之间不会覆盖。

**Comment by Trojanpa** [comment]
哦哦，原来是这样。
