### ISSUE TITLE
父节点设置自动扩展/收缩，但折叠/展开父节点之后，子节点可以拖出父节点

### ISSUE THREAD

**Issue by weiwei0901** [antvis/X6#1674]
### 问题描述

父节点设置自动扩展/收缩，但折叠/展开父节点之后，子节点可以拖出父节点

### 重现链接

https://codesandbox.io/s/focused-fast-tk431?file=/index.ts

### 重现步骤

1、进入页面，拖动父节点中的子节点
2、收缩/展开父节点
3、拖动子节点

### 预期行为

子节点不能拖出群组

### 平台

- 操作系统: [Windows, React Native]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.28.1 ]

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/47552189/147029780-24191638-b6b1-4701-b5cb-6346102bdefc.mp4

**Comment by NewByVector** [comment]
原因是 resize 父节点的时候会触发 Group 节点的 postprocess 事件，并且导致节点 resize 成原来大小。解决方案： https://codesandbox.io/s/group-g4z66

**Comment by zhangjutao** [comment]
> 原因是 resize 父节点的时候会触发 Group 节点的 postprocess 事件，并且导致节点 resize 成原来大小。解决方案： https://codesandbox.io/s/group-g4z66

按照这个方案解决后，会出现新的问题。父节点收缩后拖动时，节点大小不对(显示的是展开后的大小)

https://user-images.githubusercontent.com/15686684/176348152-bc5f3f7b-b49c-471c-9508-16288e5fd923.mp4
