### ISSUE TITLE
angular 中如何用tools 自定义tooltips 工具

### ISSUE THREAD

**Issue by mcWang66** [antvis/X6#1683]
### 问题描述

angular 中如何用tools 自定义tooltips 工具

x6/examples 基于react 框架 自定义 tooltip 工具的demo
请问，有没有 基于 angular 框架的demo
![1640228241(1)](https://user-images.githubusercontent.com/17886159/147181262-cefdde39-70ee-40f3-9506-e2d1cd46c7d2.png)

### 重现链接

ngular 中如何用tools 自定义tooltips 工具

### 重现步骤

ngular 中如何用tools 自定义tooltips 工具

### 预期行为

ngular 中如何用tools 自定义tooltips 工具

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以参考：https://github.com/antvis/X6/blob/master/packages/x6-angular-shape/src/view.ts#L46

**Comment by lifront** [comment]
请问angular自定义tool搞定了吗？
