### ISSUE TITLE
希望添加侧边栏 Stencil  节点浮窗功能

### ISSUE THREAD

**Issue by daughterRui** [antvis/X6#1688]
### 功能描述

希望 Stencil 里加节点的 popover 功能
<img width="581" alt="mx_screencap_20211224_174735" src="https://user-images.githubusercontent.com/18068805/147341797-567022e5-eefc-4ef7-be14-390121ee67cd.png">

### 期望解决方案

显示节点名称

**Comment by NewByVector** [comment]
这个用 [dnd](https://x6.antv.vision/zh/docs/tutorial/basic/dnd#dnd) 实现更合适
