### ISSUE TITLE
getConnectedEdges()参数中enclosed=true不生效

### ISSUE THREAD

**Issue by lhbvita** [antvis/X6#1690]
### Describe the bug

官网api文档：
![image](https://user-images.githubusercontent.com/29444839/147379564-06aabbf9-5e46-43b9-90ac-2f7f13860f91.png)
现有节点关系如下：
![image](https://user-images.githubusercontent.com/29444839/147379589-b610c364-64cb-43cc-b6da-3a5f12e3cd78.png)
那么``this.graph.getConnectedEdges(source,{deep:true,enclosed:true}``，其中soure为节点1，理论上应该返回2条边，实际上只返回了节点12之间的边。
![image](https://user-images.githubusercontent.com/29444839/147379672-ca4bf733-af71-49fd-aa7a-0ea052502887.png)

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

参见bug说明

### Expected behavior

返回子节点之间的边

### Platform

- OS:windows
- Browser: chrome 96.0.4664.110
- Version: @antv/x6 1.28.1

**Comment by NewByVector** [comment]
这里的子孙节点指的是 [child](https://x6.antv.vision/zh/docs/tutorial/basic/cell/#children-1) 节点，而不是下游节点。

**Comment by lhbvita** [comment]
> 这里的子孙节点指的是 [child](https://x6.antv.vision/zh/docs/tutorial/basic/cell/#children-1) 节点，而不是下游节点。

那如何一并获取下游节点之间的边？

**Comment by lhbvita** [comment]
@NewByVector 那如何一并获取下游节点之间的边？
