### ISSUE TITLE
节点之间的连线过短会变形

### ISSUE THREAD

**Issue by daughterRui** [antvis/X6#1692]
### 问题描述

节点之间的连线过短会变形
<img width="153" alt="mx_screencap_20211228_113755" src="https://user-images.githubusercontent.com/18068805/147531282-a63ff590-251d-4e59-9a5d-762f9022a7ac.png">

### 重现链接

暂无

### 重现步骤

示例中也能复现
<img width="142" alt="mx_screencap_20211228_133113" src="https://user-images.githubusercontent.com/18068805/147531459-e652bcc9-d7a2-4769-b4db-35e656873f32.png">

### 预期行为

希望能正常显示

### 平台

- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.1]

**Comment by NewByVector** [comment]
设置 padding 可以解决这个问题，参考这个 [PR](https://github.com/antvis/X6/pull/1694)

**Comment by daughterRui** [comment]
这个PR没有说明呀

**Comment by daughterRui** [comment]
好的，已解决，谢谢
