### ISSUE TITLE
群组中父子节点的大小和旋转角度行为不同步？

### ISSUE THREAD

**Issue by halodong** [antvis/X6#1702]
### Describe the bug

- 构建一对父子节点
- 修改父节点的角度或者大小
- 子节点没有相应的变化

### Your Example Website or App

https://codesandbox.io/s/red-grass-3fqdh?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

- 构建一对父子节点
- 修改父节点的角度或者大小
- 子节点没有相应的变化

### Expected behavior

- 构建一对父子节点
- 修改父节点的角度或者大小
- 子节点对应更改旋转角度或大小

### Platform

- OS: [Windows10 21H1]
- Browser: [Chrome 94.0.4606.81]
- Version: [latest]

**Comment by NewByVector** [comment]
X6 中没有这个功能的，需要自己实现，可以监听父节点的 `node:rotating` 事件，修改子节点的 `angle`。

**Comment by halodong** [comment]
如果子节点没有在父节点的中心，仅转动角度会导致子节点的错位
