### ISSUE TITLE
antV X6 文档 示例代码 错误

### ISSUE THREAD

**Issue by evelope** [antvis/X6#1703]
### Describe the bug

https://x6.antv.vision/zh/docs/api/registry/node-tool/#node-editor
node-editor 一栏
示例代码 错 误

// 双击进入编辑模式
graph.on('node:dblclick', ({ cell, e }) => {       // cell 应为node
  node.addTools({
    name: 'node-editor',
    args: {
      event: e,
    },
  })
})

### Your Example Website or App

https://x6.antv.vision/zh/docs/api/registry/node-tool/#node-editor

### Steps to Reproduce the Bug or Issue

打开文档
https://x6.antv.vision/zh/docs/api/registry/node-tool/#node-editor
node-editor 一栏
看 示例代码 部分

### Expected behavior

示例代码 为
// 双击进入编辑模式
graph.on('node:dblclick', ({ node, e }) => {
  node.addTools({
    name: 'node-editor',
    args: {
      event: e,
    },
  })
})

### Platform

all

**Comment by NewByVector** [comment]
具体报错贴下，我本地运行正常。

**Comment by evelope** [comment]
@NewByVector  没有报错哈 ，就是文档写错了应该。
https://x6.antv.vision/zh/docs/api/registry/node-tool/#node-editor
node-editor 一栏
你 看 示例代码 部分，
graph.on('node:dblclick', ({ cell, e }) => {      // 参数 cell 应为node
node.addTools({

**Comment by NewByVector** [comment]
@evelope 感谢，有兴趣提一个 PR 吗？

**Comment by evelope** [comment]
可以呀～
https://x6.antv.vision/zh/docs/api/registry/node-tool/#node-editor
这个文档的  github 地址是哪个呢 没找到
～

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/blob/master/sites/x6-sites/docs/api/registry/node-tool.zh.md 和 
https://github.com/antvis/X6/blob/master/sites/x6-sites/docs/api/registry/node-tool.en.md

**Comment by evelope** [comment]
https://github.com/antvis/X6/pull/1711

@NewByVector  好了
