### ISSUE TITLE
edge:added与edge:removed事件回调中edge.getTarget()返回结果不正确

### ISSUE THREAD

**Issue by joze2016** [antvis/X6#1706]
### 问题描述

连接两个节点，或者删除两个节点之间的连线后edge:added与edge:removed事件回调中edge.getTarget()返回结果不正确。有时返回的是画布上的空白点。

### 重现链接

x

### 重现步骤

1. 链接两个节点
2. 在edge:added的回调中通过edge.getTarget()获取target节点信息
3. 返回{x:100, y: 200}这种画布上的空白节点

### 预期行为

应该返回对应的节点信息，类似 { "cell": "c3282fb4-ffcc-4607-9f8c-7bbb8bcbf0c5"}

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
参考这个问题：https://x6.antv.vision/zh/docs/tutorial/epilog#%E5%9C%A8-edgeremoved-%E4%BA%8B%E4%BB%B6%E4%B8%AD%E6%80%8E%E4%B9%88%E8%8E%B7%E5%8F%96%E7%9B%AE%E6%A0%87%E8%8A%82%E7%82%B9

**Comment by joze2016** [comment]
我的问题关键点是edge:added或者edge:removed的回调函数返回的结果不准确，在回调中如果使用setTimeout会好一些，说明added回调与实际情况存在时间差的。
添加两个节点之间的连线后，added回调中获取target节点信息，如果没有setTimeout很可能获取的是画布上的一个空白位置。在setTimeout中有可能（取决于setTimeout的间隔时长）获取到正确的target节点信息。

**Comment by NewByVector** [comment]
edge:added 是边创建，你拉出新的边的时候就会触发这个事件，你连接到新的节点才有 target ，应该用事件：`edge:connected`

**Comment by wendao8469759** [comment]
我也遇到此问题。 实际上不能使用 edge:connected  因为这个事件监听不到撤销和反撤销
