### ISSUE TITLE
0.3.2升级到0.10 ，发生了天翻地覆的变化，完全不兼容老版本，是x6的定位变了吗

### ISSUE THREAD

**Issue by NexxLuo** [antvis/X6#171]
升级了版本导致原来做的功能完全不可用，x6的定位是变了吗？官网也没有比较完整的例子；
目前的0.10版本还会不会产生比较大的更改？

**Comment by CarterLi** [comment]
有谁知道升级0.1后怎样改node和edge的label的？

原来版本还有个 `graph.updateLabel`

**Comment by bubkoo** [comment]
先锁定版本使用吧，定位没有变化，API 有较多的更新。

**Comment by afc163** [comment]
升级文档的 break change 要补上来。
