### ISSUE TITLE
画布启用滚动和平移，鼠标拖动画布移动时会导致节点会被画布覆盖

### ISSUE THREAD

**Issue by v-wangjinjie** [antvis/X6#1713]
### Describe the bug

画布启用滚动和平移，鼠标拖动画布移动使得节点元素超出当前页的画布大小（此时画布并没有重新拓展大小，未超出屏幕），此时节点元素会被当前页的画布遮盖。

### Your Example Website or App

https://codesandbox.io/embed/peaceful-hamilton-bhv0o?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce the Bug or Issue

1.鼠标左键按住画布拖动画布至画布中节点元素超出当前画布
2.发现画布中节点元素被画布遮盖

### Expected behavior

做为使用者，我希望在我拖动画布时，不应该存在节点元素会被覆盖的场景出现，而是可以自动地去拓展画布大小

### Screenshots or Videos

![企业微信截图_16409347911905](https://user-images.githubusercontent.com/27995664/147809212-efcd0540-50e8-40af-a10e-6c02701ef87a.png)
![企业微信截图_16409348162987](https://user-images.githubusercontent.com/27995664/147809214-e2a366c6-2408-4d38-9d19-8ae91247aeff.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows 10 企业版 LTSC
Chrome 96.0.4664.110（正式版本）（32 位）

**Comment by NewByVector** [comment]
使用 scroller 画布，不要同时使用 panning，scroller 本身内部包含 `pannable` 配置。

**Comment by gossypol** [comment]
> 使用 scroller 画布，不要同时使用 panning，scroller 本身内部包含 `pannable` 配置。

阅读文档时确实会有这个疑惑，`panning` 属性和 `scroller.pannable` 同时存在时会怎么样？建议在文档加以说明，两个属性不应该同时配置。

**Comment by HeZhiMr** [comment]
> > 使用 scroller 画布，不要同时使用 panning，scroller 本身内部包含 `pannable` 配置。
> 
> 阅读文档时确实会有这个疑惑，`panning` 属性和 `scroller.pannable` 同时存在时会怎么样？建议在文档加以说明，两个属性不应该同时配置。

就算没有同时配置，只配置了Scroller中的滚动，也会出现这个节点被画布遮挡的问题，在鼠标拖动画布的时候，最起始定义的画布容器并不会跟着平移，所以拖动的节点超出原来画布的范围的时候就会被隐藏。鼠标松开时画布大小被重绘了，所以又可以显示出节点了。。。

**Comment by QAQLC** [comment]
> > > 使用 scroller 画布，不要同时使用 panning，scroller 本身内部包含 `pannable` 配置。
> > 
> > 
> > 阅读文档时确实会有这个疑惑，`panning` 属性和 `scroller.pannable` 同时存在时会怎么样？建议在文档加以说明，两个属性不应该同时配置。
> 
> 就算没有同时配置，只配置了Scroller中的滚动，也会出现这个节点被画布遮挡的问题，在鼠标拖动画布的时候，最起始定义的画布容器并不会跟着平移，所以拖动的节点超出原来画布的范围的时候就会被隐藏。鼠标松开时画布大小被重绘了，所以又可以显示出节点了。。。

我看很多人反馈了这个问题，我遇到这个问题了，解决不了，节点拖动过程中超出当前画布就会这样，放开鼠标就好了

**Comment by alamhubb** [comment]
2024.4.15，未找到解决办法
