### ISSUE TITLE
filter节点过滤器不生效

### ISSUE THREAD

**Issue by avrinfly** [antvis/X6#1716]
### 问题描述

官方的API文档里说selection的filter节点过滤器支持下面三种写法
```
string[] 节点类型数组，指定的节点类型不参与对齐计算
({ id: string })[] 节点（类节点）数组，指定的节点不参与对齐计算
(this: Graph, node: Node) => boolean 返回 true 的节点不参与对齐计算
```
但我在使用的使用，发现第二种和第三种不生效

### 重现链接

https://codesandbox.io/s/hungry-cache-rdcxs

### 重现步骤

1. 进入页面
2. 点击矩形（rect）节点
3. 点击圆形（circle）节点

### 预期行为

我期望我点击圆形节点，能显示被选中的状态，但实际没有显示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 补充说明（可选）

另外：我想知道这个filter的第二种写法的具体例子和第三种写法的具体例子，方便我们更好理解

**Comment by NewByVector** [comment]
参考 demo：https://codesandbox.io/s/selection-filter-tdogv?file=/src/app.tsx

**Comment by avrinfly** [comment]
> 参考 demo：https://codesandbox.io/s/selection-filter-tdogv?file=/src/app.tsx

![image](https://user-images.githubusercontent.com/30068005/148001373-2a8c1b54-0e8f-4f98-a4b8-ba31815ea2e4.png)
这里是文档截图，两点有误：
1、node.type 应为 node.shape
2、按照demo的写法，应该是**只有**filter数组中的类型节点可以被选中，和文档完全相反
