### ISSUE TITLE
节点重叠时,下方的tools也一直显示在最上方,没有相应的zIndex可以设置

### ISSUE THREAD

**Issue by Twelve-Jiang** [antvis/X6#1724]
### Describe the bug

两个节点的位置相交时或重叠时,各自添加的tools都会显示在最上方,没有相应的zIndex可以设置显示优先级,也不会根据父组件的优先级来显示

### Your Example Website or App

官方例子也是如此

### Steps to Reproduce the Bug or Issue

两个节点的位置相交时或重叠时,各自添加的tools都会显示在最上方,没有相应的zIndex可以设置显示优先级,也不会根据父组件的优先级来显示

### Expected behavior

两个节点的位置相交时或重叠时,各自添加的tools都会显示在最上方,没有相应的zIndex可以设置显示优先级,也不会根据父组件的优先级来显示

### Platform

- OS: [macOS, Windows]
- Browser: [ Chrome, Safari, Firefox]
- Version: [1.29.0]

**Comment by NewByVector** [comment]
svg 工具肯定会处于节点上方，这个层级无法修改。如果要实现你的功能，可以自定义 html 工具，可以根据 css 样式中的 z-index 修改显示层级。
