### ISSUE TITLE
有类似G6的节点代理功能配置项吗？比如拖动节点过程中不会一直渲染，只会在结束才后渲染一次

### ISSUE THREAD

**Issue by cjinhuo** [antvis/X6#1726]
### 功能描述

有类似G6的节点代理功能吗，比如拖动节点过程中不会一直渲染，只会在结束才后渲染一次

(g6节点代理)[https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#drag-node]

![](https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*hre9Qa7yCfQAAAAAAAAAAABkARQnAQ)

### 期望解决方案

期望有这种配置的方式来大幅减少节点拖拽过程中组件渲染的次数，以此提高性能

**Comment by NewByVector** [comment]
现在 selecting 中有 `following` 配置来实现类似功能。

**Comment by cjinhuo** [comment]
> 现在 selecting 中有 `following` 配置来实现类似功能。

可以再提示一下是用里面的哪个配置来实现改功能吗 🤔

**Comment by NewByVector** [comment]
https://x6.antv.vision/zh/docs/tutorial/basic/selection#following

**Comment by cjinhuo** [comment]
> https://x6.antv.vision/zh/docs/tutorial/basic/selection#following

这种是多选状态下可以  如果我是移动单个节点 或者 移动一个群组，这个有解决方案么

**Comment by NewByVector** [comment]
移动单个节点和群组应该不会有性能问题的，现在是遇到性能问题了吗？

**Comment by cjinhuo** [comment]
> 移动单个节点和群组应该不会有性能问题的，现在是遇到性能问题了吗？

现在移动一个大分组嵌套后里面的所有子节点都会在一秒内渲染好几次

**Comment by NewByVector** [comment]
可以提供一个 demo 吗，应该只有位置的修改，不会重新渲染的。

**Comment by cjinhuo** [comment]
> 

可以   等我精简一下代码  弄到sandbox上

**Comment by cjinhuo** [comment]
> 可以提供一个 demo 吗，应该只有位置的修改，不会重新渲染的。

https://codesandbox.io/s/icno7?file=/src/component.tsx

这个官网的例子改成hook然后移动就会重新渲染

**Comment by cjinhuo** [comment]
> > 可以提供一个 demo 吗，应该只有位置的修改，不会重新渲染的。
> 
> https://codesandbox.io/s/icno7?file=/src/component.tsx
> 
> 这个官网的例子改成hook然后移动就会重新渲染

![image](https://user-images.githubusercontent.com/22608658/148212840-7946b840-266c-4adc-8b0b-8426ff4d8632.png)

**Comment by cjinhuo** [comment]
> > 可以提供一个 demo 吗，应该只有位置的修改，不会重新渲染的。
> 
> https://codesandbox.io/s/icno7?file=/src/component.tsx
> 
> 这个官网的例子改成hook然后移动就会重新渲染

不过加个memo就好了

**Comment by cjinhuo** [comment]
> https://x6.antv.vision/zh/docs/tutorial/basic/selection#following
![Jan-05-2022 20-16-01](https://user-images.githubusercontent.com/22608658/148216260-1105df66-b306-4d38-81a8-0176984e1a86.gif)

单个节点被选中时，在移动过程中就没有黄色框框的轨迹

**Comment by cjinhuo** [comment]
> > https://x6.antv.vision/zh/docs/tutorial/basic/selection#following
> > ![Jan-05-2022 20-16-01](https://user-images.githubusercontent.com/22608658/148216260-1105df66-b306-4d38-81a8-0176984e1a86.gif)
> 
> 单个节点被选中时，在移动过程中就没有黄色框框的轨迹

怎么做才能做到单个组件  也有这种轨迹

**Comment by NewByVector** [comment]
还是增加 `memo` 吧，单个节点不支持的。
