### ISSUE TITLE
Need graph.on('nodes:added') event

### ISSUE THREAD

**Issue by Hfutsora** [antvis/X6#1738]
### 功能描述

```typecsript
graph.on('node:added', ({ cell }) => { console.log(cell });

graph.addNodes({ /** add complex nodes here */});
```
当我尝试使用 `addNodes` 一次性批量增加节点时，`node:added` 却会触发多次（`addNodes` 内的每个 `node` 分别触发一次）。因为我会在 `node:added` 内根据同时增加节点生成一条记录（批量管理），所以希望他们不要分开。

类似的还有 `node:moved` 是一样的。

### 期望解决方案

希望提供 `graph.on('nodes:added', ({ cells: Cell[] }))` 或者 `graph.on('node:added', ({ cell: Cell | Cell[] }))` 等供使用。

**Comment by NewByVector** [comment]
你的场景应该是在 `graph.addNodes(node)` 调用之后生成记录，不需要再 node:added 回调中。

**Comment by Hfutsora** [comment]
> 你的场景应该是在 `graph.addNodes(node)` 调用之后生成记录，不需要再 node:added 回调中。

请问 `node:moved` 怎么处理，当我开启多选时，我发现他们也是分开的。

**Comment by NewByVector** [comment]
可以结合 node:mvoe 和 node:moved 通过计数方式，在最后一个节点的 node:moved 事件回调中生成记录。

**Comment by Hfutsora** [comment]
> 可以结合 node:mvoe 和 node:moved 通过计数方式，在最后一个节点的 node:moved 事件回调中生成记录。

好的，虽然不是直接获取，但应该也是可以解决我的问题，谢谢。
