### ISSUE TITLE
期望能有节点碰撞检测的功能

### ISSUE THREAD

**Issue by avrinfly** [antvis/X6#1740]
### 功能描述

在一个知识图谱中，有多个主题的概念，现在使用node或者自定义cell来实现节点，在客观上，多个主题间不能有相互重叠，目前的实现方案中没有碰撞检测的概念，即我在拖动一个节点时，无法得知我是否已和同类型的节点有交集（即产生碰撞）

### 期望解决方案

我期望有一个开关，类似于节点过滤器一样，collide:['rect']，则意味着类型是rect的节点无法出现交集

**Comment by NewByVector** [comment]
不提供默认功能，可以自己实现，移动节点的时候先使用 `graph.getNodesUnderNode` api 获取相交的节点，然后将相交的节点移动相应的距离。
