### ISSUE TITLE
预发环境渲染骨架高频报错，dev不报错

### ISSUE THREAD

**Issue by LMLGM** [antvis/X6#1746]
### 问题描述

使用fromJSON(schema)渲染骨架，同一个schema时好时坏

### 重现链接

https://service-platform-web-prepub.alipay.com/templateCenter

### 重现步骤

1.进入页面
2.点击查看

### 预期行为

弹窗页面直接报错，页面不展示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
是不是没有等对话框加载完毕就初始化 graph 了，没有提供可用的复现信息，先关闭。

**Comment by LMLGM** [comment]
![image](https://user-images.githubusercontent.com/58587791/148873296-72cecff9-c98c-4a4a-b0c1-45e8e1585d2f.png)

**Comment by LMLGM** [comment]
又出现了这个问题，有可能是因为对话框加载完毕就初始化 graph 了，这个我们有解决方案吗？

**Comment by naanna** [comment]
> 

我也遇到了 怎么解决？目前设置延时加载
