### ISSUE TITLE
小地图的节点替换 和 获取倍数问题

### ISSUE THREAD

**Issue by NINGyv179** [antvis/X6#1748]
### 问题描述

VUE中，看官网demo的节点替换的SimpleNodeView是返回一个class，在vue2中是返回一个方法，请问这个一定要是vue3才能用么，还有就是小地图的缩放，怎么获取到缩放的倍数
![image](https://user-images.githubusercontent.com/56420939/148878598-e7e67a71-2bf3-469a-b456-4a0ded5639c3.png)

### 重现链接

无

### 重现步骤

无

### 预期行为

能获取到小地图的缩放倍数，还有在Vue中小地图节点替换的 方式

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
不管在 vue 还是在其他框架中，都是用类的方式，获取小地图画布缩放比例：`graph.minimap.widget.ratio`

**Comment by NINGyv179** [comment]
> 不管在 vue 还是在其他框架中，都是用类的方式，获取小地图画布缩放比例：`graph.minimap.widget.ratio`

有方法可以监听小地图缩放吗，有个场景就是画布中需要显示缩放比，小地图缩放时需要同步到画布中

**Comment by NINGyv179** [comment]
> 不管在 vue 还是在其他框架中，都是用类的方式，获取小地图画布缩放比例：`graph.minimap.widget.ratio`

可以监听到小地图缩放时候吗，现在有个场景是在画布中显示缩放比，需要在小地图缩放比画布中的一致
