### ISSUE TITLE
edge.hasLoop()方法一直返回false

### ISSUE THREAD

**Issue by fancyluo88** [antvis/X6#1752]
### 问题描述

```js 
connecting: {
          allowMulti: false,
          validateEdge({ edge, type, previous }) {
            setTimeout(()=>{
              console.log(edge.getSourceCell().getParent(), edge.hasLoop({deep: true}));
            }, 1000);
            return true;
          }
        }

```
连线验证节点是否形成循环时，edge.hasLoop()方法一直返回false

### 重现链接

https://stackblitz.com/edit/react-brsamn?file=src%2Findex.js

### 重现步骤

1. 进入页面；
2. 连接节点A->B->C->A;
3. 控制台查看edge.hasLoop()的结果；

### 预期行为

期望看到true，实际结果都是false

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.29.5]

**Comment by NewByVector** [comment]
这里的 loop 并不是指连线出现循环，具体含义可以看[文档](https://x6.antv.vision/zh/docs/api/model/edge/#hasloop)
