### ISSUE TITLE
新建节点，如何在可视区域内某一个坐标/中心生成节点

### ISSUE THREAD

**Issue by NINGyv179** [antvis/X6#1756]
### 问题描述

有个场景是用户拖动画布，然后点击生成一个节点，如何让节点在画布可视区域内生成，例如可视区域中心等

PS：想问下这个方法为啥一直返回{tx: 0, ty: 0}?

### 重现链接

无

### 重现步骤

无

### 预期行为

解答一下

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
通过画布的宽表就能计算出节点位置，issue 是提 bug 或者 feature 的地方，问题请到讨论区提问。
