### ISSUE TITLE
this.graph.translate()一直返回{tx:0,ty:0}

### ISSUE THREAD

**Issue by NINGyv179** [antvis/X6#1757]
### Describe the bug

滚动后调用this.graph.translate()一直返回{tx:0,ty:0}

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

滚动后调用this.graph.translate()一直返回{tx:0,ty:0}

### Expected behavior

获取到画布滚动的距离

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
滚动画布可以通过 [getscrollbarposition](https://x6.antv.vision/zh/docs/tutorial/basic/scroller#graphgetscrollbarposition) 获取滚动位置。还有，提问更高效的方式是到钉钉群或者 [discussions](https://github.com/antvis/X6/discussions)

**Comment by NINGyv179** [comment]
> 滚动画布可以通过 [getscrollbarposition](https://x6.antv.vision/zh/docs/tutorial/basic/scroller#graphgetscrollbarposition) 获取滚动位置。还有，提问更高效的方式是到钉钉群或者 [discussions](https://github.com/antvis/X6/discussions)

群都满人了。进不去呀
