### ISSUE TITLE
node.setData未生效

### ISSUE THREAD

**Issue by LMLGM** [antvis/X6#1759]
### 问题描述

values的edgePlugins数据只有一个
![image](https://user-images.githubusercontent.com/58587791/149454838-47fef1f7-79e5-47fa-a144-1c563f4a7ea7.png)
setData之后用getData获取的值还是原来的两个
![image](https://user-images.githubusercontent.com/58587791/149455019-69202e05-a7a0-4aad-bd93-a5871f5c7809.png)
![image](https://user-images.githubusercontent.com/58587791/149455164-d80a72db-40d0-4372-9745-758db1ad5e4d.png)
![image](https://user-images.githubusercontent.com/58587791/149455429-2153e5bf-6f57-48db-be61-c68952c5bb03.png)

### 重现链接

http://insmerchantprod-68.gz00b.dev.alipay.net/webapp#/yunfengdiesop/templatecenter

### 重现步骤

![image](https://user-images.githubusercontent.com/58587791/149455468-d9dc5aec-28d8-40d7-b56a-bc7962633425.png)
![image](https://user-images.githubusercontent.com/58587791/149455509-78360187-7fbb-4bfd-91b6-4995a125087b.png)
![image](https://user-images.githubusercontent.com/58587791/149455554-f1d4331d-dc74-48d4-9c22-06685e3e966d.png)
![Uploading image.png…]()

### 预期行为

已经setData了，正常get应该是set时的数据

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by LMLGM** [comment]
用replaceData解决了这个问题，但是想知道setData为什么不可以

**Comment by NewByVector** [comment]
`deep: true` 是进行数据 merge

**Comment by lance-li** [comment]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/21050392/175024416-6ccb670f-e018-4ae6-bc6f-c5547c0e61b4.png">

**Comment by Trojan0523** [comment]
> 用replaceData解决了这个问题，但是想知道setData为什么不可以



- 文档可能是藏的比较深的，具体链接在这([Cell](https://github1s.com/antvis/x6/blob/HEAD/sites/x6-sites/docs/api/model/cell.en.md))。用到Cell的setData里面的第二个参数对象options ,如果为默认设定的话， 会对对象或数组进行递归合并，由于前设定属性不为空，后续合并一个空数组或对象的话，原始数据不会被覆盖，所以要在调用`setData()`方法时对第二个参数进行设置:

```
nodeInstance.value.setData({
  ...data,
}, {
  deep: false, // 当 `options.overwrite` 为 `false` 时有效， 为 `true` 时进行深度 merge，否则进行浅 merge。由于这里需要覆盖数据，所以不能进行深度merge
  overWrite: true,  // 这里是对数据进行覆盖写入
})
```
- 楼主提到使用的`replaceData()`，本人也使用过，使用此方法可能会直接把原有的数据全部覆盖掉了，对于不想覆盖的数据可能会造成数据维护的负担，所以可以不需要使用此方法, 如果描述有误欢迎指正

**Comment by huyu456** [comment]
> > 用replaceData解决了这个问题，但是想知道setData为什么不可以
> 
> * 文档可能是藏的比较深的，具体链接在这([Cell](https://github1s.com/antvis/x6/blob/HEAD/sites/x6-sites/docs/api/model/cell.en.md))。用到Cell的setData里面的第二个参数对象options ,如果为默认设定的话， 会对对象或数组进行递归合并，由于前设定属性不为空，后续合并一个空数组或对象的话，原始数据不会被覆盖，所以要在调用`setData()`方法时对第二个参数进行设置:
> 
> ```
> nodeInstance.value.setData({
>   ...data,
> }, {
>   deep: false, // 当 `options.overwrite` 为 `false` 时有效， 为 `true` 时进行深度 merge，否则进行浅 merge。由于这里需要覆盖数据，所以不能进行深度merge
>   overWrite: true,  // 这里是对数据进行覆盖写入
> })
> ```
> 
> * 楼主提到使用的`replaceData()`，本人也使用过，使用此方法可能会直接把原有的数据全部覆盖掉了，对于不想覆盖的数据可能会造成数据维护的负担，所以可以不需要使用此方法, 如果描述有误欢迎指正

我设置了options，也不行，我已经尝试了replaceData,setData,updateData这些方法，都无法实现触发更新，我使用以下方式成功
```javascript
nodeRef.value.setData({
        ...form.value,
        timestamp: Date.now()
      })
```
