### ISSUE TITLE
求新群，两个群都满人了一直进不去

### ISSUE THREAD

**Issue by NINGyv179** [antvis/X6#1762]
### 问题描述

求新群，两个群都满人了一直进不去

### 重现链接

无

### 重现步骤

无

### 预期行为

求新群，两个群都满人了一直进不去

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
见 readme
