### ISSUE TITLE
Windows 下安装@antv/x6-react-shape 启动项目报错

### ISSUE THREAD

**Issue by 13371826981** [antvis/X6#1768]
### Describe the bug

![image](https://user-images.githubusercontent.com/20837054/149764986-97ba2f9b-869d-4689-98a0-2dedfdb0ddac.png)
WARNING in ./node_modules/@antv/x6-react-shape/es/registry.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\moonton\my-app\node_modules\@antv\x6-react-shape\src\registry.ts' file: Error: ENOENT: no such file or directory, open 'E:\moonton\my-app\node_modules\@antv\x6-react-shape\src\registry.ts'
 @ ./node_modules/@antv/x6-react-shape/es/index.js 4:0-27 4:0-27
 @ ./src/component/ReactRender/Rect.js 8:0-61 17:29-38 28:17-27 111:10-19
 @ ./src/App.js 11:0-48 212:35-39
 @ ./src/index.js 7:0-24 11:33-36

WARNING in ./node_modules/@antv/x6-react-shape/es/usePortal/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\moonton\my-app\node_modules\@antv\x6-react-shape\src\usePortal\index.ts' file: Error: ENOENT: no such file or directory, open 'E:\moonton\my-app\node_modules\@antv\x6-react-shape\src\usePortal\index.ts'
 @ ./node_modules/@antv/x6-react-shape/es/index.js 6:0-28 6:0-28
 @ ./src/component/ReactRender/Rect.js 8:0-61 17:29-38 28:17-27 111:10-19
 @ ./src/App.js 11:0-48 212:35-39
 @ ./src/index.js 7:0-24 11:33-36

WARNING in ./node_modules/@antv/x6-react-shape/es/view.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\moonton\my-app\node_modules\@antv\x6-react-shape\src\view.ts' file: Error: ENOENT: no such file or directory, open 'E:\moonton\my-app\node_modules\@antv\x6-react-shape\src\view.ts'
 @ ./node_modules/@antv/x6-react-shape/es/index.js 3:0-23 3:0-23
 @ ./src/component/ReactRender/Rect.js 8:0-61 17:29-38 28:17-27 111:10-19
 @ ./src/App.js 11:0-48 212:35-39
 @ ./src/index.js 7:0-24 11:33-36

WARNING in ./node_modules/@antv/x6-react-shape/es/wrap.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\moonton\my-app\node_modules\@antv\x6-react-shape\src\wrap.ts' file: Error: ENOENT: no such file or directory, open 'E:\moonton\my-app\node_modules\@antv\x6-react-shape\src\wrap.ts'
 @ ./node_modules/@antv/x6-react-shape/es/view.js 5:0-30 39:39-43
 @ ./node_modules/@antv/x6-react-shape/es/index.js 3:0-23 3:0-23
 @ ./src/component/ReactRender/Rect.js 8:0-61 17:29-38 28:17-27 111:10-19
 @ ./src/App.js 11:0-48 212:35-39
 @ ./src/index.js 7:0-24 11:33-36

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1、安装"@antv/x6-react-shape": "^1.6.0",
2、npm run start 时候报错

### Expected behavior

不报错

### Platform

Windows
"@antv/x6-react-shape": "^1.6.0",

**Comment by NewByVector** [comment]
能否提供一个可复现的 demo 看下？

**Comment by 13371826981** [comment]
#

**Comment by 13371826981** [comment]
https://github.com/13371826981/V6-Demo

**Comment by NewByVector** [comment]
我在本地试了下没有问题，请问这个问题后面有解决吗？

**Comment by Zhangzirui** [comment]
这个问题怎么解决的，我这边遇到了同样的问题。不是在 window 下，而是在 mac 下。很正常的 npx create-react-app，然后引入 x6 和 x6-react-shape，在 npm run start 就会出错

**Comment by 13371826981** [comment]
删除重新装一下吧

**Comment by dizzy-Lee** [comment]
我也遇到了这个问题
环境：
* Mac OS: 13.0.1
* node: v16.18.1
* react: 18.2.0
* antv/x6: 2.0.8
npx create-react-app引入x6-plugin-stencil后报warning
