### ISSUE TITLE
开启历史数据，当node.data设置为对象是，添加node报错

### ISSUE THREAD

**Issue by MXxuanxiao** [antvis/X6#1775]
### 问题描述

开启历史数据时，当node.data为对象时，添加node报错
报错信息
Error: Can only serialize node with plain-object props, but got a "[object Object]" type of key "data" on node "8e0f291a-e26a-8f6c-d287-475e914c"

### 重现链接

/

### 重现步骤

1、开启历史数据
2、将node.data设置为对象
3、添加node到画布,报错

### 预期行为

正常使用历史数据

### 平台

"@antv/x6": "^1.28.1",

**Comment by NewByVector** [comment]
这里的 data 只能设置成  plainObject
