### ISSUE TITLE
期望画布背景图能支持旋转

### ISSUE THREAD

**Issue by Trojanpa** [antvis/X6#1776]
### 功能描述

场景：用户上传一张图片，这张图片里有规整排布的的节点，但这些节点在图片里全部是倾斜的，所以这里需要能将图片旋转到图片内部节点正放的位置。

### 期望解决方案

BackgroundOptions 的 angle 仅当 repeat 为 'watermark' 时有效，期望 angle 能在 repeat 为 ‘’no-repeat‘ 也生效。

**Comment by NewByVector** [comment]
把图片用 PS 等工具旋转一下最快了，暂时不考虑支持这个功能。
