### ISSUE TITLE
自定义节点和自定义桩同时使用,自定义桩的拉线功能不起效,

### ISSUE THREAD

**Issue by skoll1** [antvis/X6#1777]
### 问题描述

同时使用自定义节点和自定义桩,发现自定义节点可以支持拖拽,但是桩的拖拽拉线无法生效,桩的mouseDown事件似乎没有响应,只会响应到节点上面

### 重现链接

https://codesandbox.io/s/lucid-goldberg-npfgp?file=/src/App.js

### 重现步骤

进入链接页面,点击桩拖拽,发现无法拉线

### 预期行为

桩和节点各自响应自己的拖拽事件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
Windos,Chrome最新版本,X61.28.1

**Comment by mjyg** [comment]
正好也在做这个功能，搜了下发现可以这样实现，在定义自定义节点的时候配置链接桩ports：
`const node = this.graph.createNode({
        width: 100,
        height: 40,
        attrs: {
          label: {
            text: "Rect",
            fill: "#6a6c8a",
          },
          body: {
            stroke: "#31d0c6",
            strokeWidth: 2,
            magnet: true,
          },
        },
        ports:{
          groups: {
            group1: {
              position: 'top',
              attrs: {
                circle: {
                  stroke: '#D06269',
                  strokeWidth: 1,
                  r: 4,
                  magnet: true
                }
              }
            },
            group2: {
              position: 'right',
              attrs: {
                circle: {
                  stroke: '#D06269',
                  strokeWidth: 1,
                  r: 4,
                  magnet: true
                }
              }
            },
            group3: {
              position: 'bottom',
              attrs: {
                circle: {
                  stroke: '#D06269',
                  strokeWidth: 1,
                  r: 4,
                  magnet: true
                }
              }
            },
            group4: {
              position: 'left',
              attrs: {
                circle: {
                  stroke: '#D06269',
                  strokeWidth: 1,
                  r: 4,
                  magnet: true
                }
              }
            }
          },
          items: [
            { group: 'group1' },
            { group: 'group2' },
            { group: 'group3' },
            { group: 'group4' }
          ]
        }`
参考：https://www.csdn.net/tags/MtTaAg2sOTM2ODY2LWJsb2cO0O0O.html

**Comment by NewByVector** [comment]
你给的复现连接没有 X6 相关内容，是不是给错了。

**Comment by NewByVector** [comment]
你给的链接无法复现你的问题，这个问题先关闭了，如果还有问题，请重新开一个 issue，并提供可复现的链接。
