### ISSUE TITLE
官方示例edge-editor编辑边label时位置向下偏移了

### ISSUE THREAD

**Issue by lijing666** [antvis/X6#1780]
### Describe the bug

官方示例使用edge-editor编辑边label时位置向下偏移了，链接：[https://x6.antv.vision/zh/docs/api/registry/edge-tool#edge-editor](url)，编辑器正常位置应该是在label的同位置覆盖，而不是出现在它的下方

### Your Example Website or App

https://x6.antv.vision/zh/docs/api/registry/edge-tool#edge-editor

### Steps to Reproduce the Bug or Issue

1：双击其中一个label编辑
2：立即双击另一个label编辑，编辑位置出现异常

### Expected behavior

编辑器正常位置应该是在label的同位置覆盖，而不是出现在它的下方

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/26834700/150095449-5040b6e7-5dbd-48d1-97ee-652355ae521b.png)

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [1.29.6]

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/pull/1783
