### ISSUE TITLE
使用edge-editor编辑边label时，如何拖拽修改label的位置？另外如何保证仅仅修改同一个label呢？

### ISSUE THREAD

**Issue by lijing666** [antvis/X6#1781]
### Describe the feature you'd like to request

1： 目前edge-editor是默认在点击的位置，生成新的label，每次点击位置不同都会生成新的label，如果点击多次不写文字，会生成n多个空的label出来，很冗余；大多数情况下，仅仅只需要一个label而已，因此希望优先提供限制编辑单个label的功能，这样避免产生很多空label
2：label一旦生成，位置便固定了，希望能提供可拖拽调整位置的功能

### Describe the solution you'd like

暂时无解决方案

### Describe alternatives you've considered

暂时无解决方案

**Comment by NewByVector** [comment]
1. https://github.com/antvis/X6/pull/1783
2. [edgeLabelMovable](https://x6.antv.vision/zh/docs/tutorial/basic/interacting#%E5%AE%9A%E5%88%B6%E4%BA%A4%E4%BA%92%E8%A1%8C%E4%B8%BA)
