### ISSUE TITLE
Path data 属性解析异常 Invalid path segment type "N"

### ISSUE THREAD

**Issue by LXang723** [antvis/X6#1787]
### Describe the bug

在 iconfont 上面复制的 svg 代码，解析出的 path data，显示 Error: Invalid path segment type "N" ，但是内容里面没有 N，在示例里面替换 path 也显示同样问题，refD 和 refDResetOffset 也是。

'M1037.604001 695.630632L901.935604 23.049513a28.804331 28.804331 0 0 0-28.80433-23.043464H165.696915a28.804331 28.804331 0 0 0-28.80433 23.043464L0.648101 695.630632a25.923897 25.923897 0 0 0 0 11.521732v288.043305a28.804331 28.804331 0 0 0 28.804331 28.804331h979.347239a28.804331 28.804331 0 0 0 28.80433-28.804331v-288.043305a25.923897 25.923897 0 0 0 0-11.521732zM189.316466 57.61471h662.499603l125.586881 620.733323H63.441542zM979.99534 966.391339H58.256762v-230.434645h921.738578z'

![image](https://user-images.githubusercontent.com/53211861/150721342-6e5eafc6-9491-45a3-af98-79fdba13254e.png)
![image](https://user-images.githubusercontent.com/53211861/150721675-15f1a2b9-74aa-409c-b0f6-adfc3bdf6b60.png)

### Your Example Website or App

https://antv-x6.gitee.io/zh/examples/node/native-node#path

### Steps to Reproduce the Bug or Issue

图标示例 内置节点 path 替换 成
'M1037.604001 695.630632L901.935604 23.049513a28.804331 28.804331 0 0 0-28.80433-23.043464H165.696915a28.804331 28.804331 0 0 0-28.80433 23.043464L0.648101 695.630632a25.923897 25.923897 0 0 0 0 11.521732v288.043305a28.804331 28.804331 0 0 0 28.804331 28.804331h979.347239a28.804331 28.804331 0 0 0 28.80433-28.804331v-288.043305a25.923897 25.923897 0 0 0 0-11.521732zM189.316466 57.61471h662.499603l125.586881 620.733323H63.441542zM979.99534 966.391339H58.256762v-230.434645h921.738578z'
即可复现问题

https://antv-x6.gitee.io/zh/examples/node/native-node#path

### Expected behavior

从iconfont 上面复制的 svg，不是所有的 path data 都能正常使用

### Platform

OS: [Windows]
Browser: [Chrome]

**Comment by NewByVector** [comment]
这个 path 放在：
```ts
graph.addNode({
  shape: 'path',
  x: 360,
  y: 70,
  width: 100,
  height: 80,
  label: 'path',
  attrs: {
    body: {
      fill: '#efdbff',
      stroke: '#9254de',
      d: 'M1037.604001 695.630632L901.935604 23.049513a28.804331 28.804331 0 0 0-28.80433-23.043464H165.696915a28.804331 28.804331 0 0 0-28.80433 23.043464L0.648101 695.630632a25.923897 25.923897 0 0 0 0 11.521732v288.043305a28.804331 28.804331 0 0 0 28.804331 28.804331h979.347239a28.804331 28.804331 0 0 0 28.80433-28.804331v-288.043305a25.923897 25.923897 0 0 0 0-11.521732zM189.316466 57.61471h662.499603l125.586881 620.733323H63.441542zM979.99534 966.391339H58.256762v-230.434645h921.738578z',
    },
  },
})
```

**Comment by LXang723** [comment]
> 

但是这样图标就太大了，换成 refDResetOffset 的话还会存在之前的问题

**Comment by LXang723** [comment]
> 这个 path 放在：
> 
> ```ts
> graph.addNode({
>   shape: 'path',
>   x: 360,
>   y: 70,
>   width: 100,
>   height: 80,
>   label: 'path',
>   attrs: {
>     body: {
>       fill: '#efdbff',
>       stroke: '#9254de',
>       d: 'M1037.604001 695.630632L901.935604 23.049513a28.804331 28.804331 0 0 0-28.80433-23.043464H165.696915a28.804331 28.804331 0 0 0-28.80433 23.043464L0.648101 695.630632a25.923897 25.923897 0 0 0 0 11.521732v288.043305a28.804331 28.804331 0 0 0 28.804331 28.804331h979.347239a28.804331 28.804331 0 0 0 28.80433-28.804331v-288.043305a25.923897 25.923897 0 0 0 0-11.521732zM189.316466 57.61471h662.499603l125.586881 620.733323H63.441542zM979.99534 966.391339H58.256762v-230.434645h921.738578z',
>     },
>   },
> })
> ```

但是这样图标就太大了，换成 refDResetOffset 的话还会存在之前的问题

**Comment by LXang723** [comment]
> 这个 path 放在：
> 
> ```ts
> graph.addNode({
>   shape: 'path',
>   x: 360,
>   y: 70,
>   width: 100,
>   height: 80,
>   label: 'path',
>   attrs: {
>     body: {
>       fill: '#efdbff',
>       stroke: '#9254de',
>       d: 'M1037.604001 695.630632L901.935604 23.049513a28.804331 28.804331 0 0 0-28.80433-23.043464H165.696915a28.804331 28.804331 0 0 0-28.80433 23.043464L0.648101 695.630632a25.923897 25.923897 0 0 0 0 11.521732v288.043305a28.804331 28.804331 0 0 0 28.804331 28.804331h979.347239a28.804331 28.804331 0 0 0 28.80433-28.804331v-288.043305a25.923897 25.923897 0 0 0 0-11.521732zM189.316466 57.61471h662.499603l125.586881 620.733323H63.441542zM979.99534 966.391339H58.256762v-230.434645h921.738578z',
>     },
>   },
> })
> ```

![image](https://user-images.githubusercontent.com/53211861/152721775-a3be3109-164a-45ef-ab66-73b23c2496b3.png)

直接使用 data 属性 ，偏移量太大会导致图标过大

![image](https://user-images.githubusercontent.com/53211861/152721928-832532cb-9f0d-45bc-ab40-fb7aa8455ff6.png)

使用 refDResetOffset 之后，还是会出现之前的问题

Invalid path segment type "N"

**Comment by NewByVector** [comment]
你从 iconfont 中复制的 path，需要放在 body/d 中(不能赋给 refD，这个是相对的)，而且需要调整它的数值大小

**Comment by LXang723** [comment]
> 你从 iconfont 中复制的 path，需要放在 body/d 中(不能赋给 refD，这个是相对的)，而且需要调整它的数值大小

refDResetOffset 作用不就是 设置 <path> 元素的 d 属性和移除 pathData 的 偏移量吗，而且并不是所有的图标都会报错。

**Comment by LXang723** [comment]
> 你从 iconfont 中复制的 path，需要放在 body/d 中(不能赋给 refD，这个是相对的)，而且需要调整它的数值大小

谢谢你的回复，iconfont  复制 的path，使用 refD 并不是都会出现问题。
