### ISSUE TITLE
调用edge.setData时onEdgeLabelRendered方法不会被执行

### ISSUE THREAD

**Issue by cjinhuo** [antvis/X6#1788]
### 问题描述

![image](https://user-images.githubusercontent.com/22608658/150726781-cfa3f57a-fa6b-48df-8976-0acc8499d5a0.png)

### 重现链接

*

### 重现步骤

![image](https://user-images.githubusercontent.com/22608658/150726790-59de37c6-db85-4959-bbb3-b21eb490d500.png)

### 预期行为

期望通过调用edge.updateData(...)方法触发onEdgeLabelRendered

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.1]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/22608658/150726781-cfa3f57a-fa6b-48df-8976-0acc8499d5a0.png)

**Comment by NewByVector** [comment]
只有修改label的时候才会触发这个函数执行，修改label方法参考[这里](https://x6.antv.vision/zh/docs/tutorial/intermediate/edge-labels)
