### ISSUE TITLE
new Graph设置selecting后，连线的时候会报错

### ISSUE THREAD

**Issue by miaocunzhi** [antvis/X6#179]
cell.js文件
getRootRotateMatrix方法
Error:cell.getAngle is not a function
![image](https://user-images.githubusercontent.com/20124199/86331192-561d9500-bc7b-11ea-8f8d-bd6082ceacab.png)

**Comment by bubkoo** [comment]
@miaocunzhi 提供一个 codesandbox 吧，就仅仅上面的描述我不知道怎么复现，或者贴上完整的代码。

**Comment by miaocunzhi** [comment]
@bubkoo 就拿官方的x6-example-features中edge的示例
```
const graph = new Graph({
      container: this.container,
      width: 800,
      height: 1400,
      grid: 10,
      selecting:{
        enabled:true
      },
    })
```
只要加上selecting效果，在节点上拖动添加连线时就会报错

**Comment by bubkoo** [comment]
@miaocunzhi 我在其他场景下遇到同样的错误，已经修复，请更新到最新版。
