### ISSUE TITLE
在两个已经连线的节点中间放置另外一个节点，该节点自动成为两个节点的中间节点

### ISSUE THREAD

**Issue by shui2464** [antvis/X6#1791]
### 功能描述

可以在不删除边或节点的情况下， 补充添加中间节点

### 期望解决方案

通过边/节点的配置或者代码实现

**Comment by NewByVector** [comment]
实现可以参考这个 [demo](https://codesandbox.io/s/intersect-with-edge-iollz)

**Comment by shui2464** [comment]
thanks!
