### ISSUE TITLE
dagre自动布局时，可不可以设置不同边不同的长度？

### ISSUE THREAD

**Issue by lhbvita** [antvis/X6#1793]
### Describe the feature you'd like to request

![image](https://user-images.githubusercontent.com/29444839/151684478-01e39250-4425-4bcc-b8d7-0226b0205dbd.png)
如何设置7-6和6-5边的不同长度？

### Describe the solution you'd like

分别设置长度

### Describe alternatives you've considered

无

**Comment by NewByVector** [comment]
可以使用 `nodesepFunc` 配置

**Comment by sy296565890** [comment]
> `nodesepFunc`

大佬，dagre自动布局时，可不可以设置同层级排序呢  设置了sort或_sort无效呢

**Comment by sy296565890** [comment]
@NewByVector 大佬，dagre自动布局时，可不可以设置同层级排序呢 设置了sort或_sort无效呢

**Comment by NewByVector** [comment]
@sy296565890 可以在 @antv/layout 仓库提 issue 咨询。
