### ISSUE TITLE
Default "grab" cursor is not showing for most recent Chrome navigator

### ISSUE THREAD

**Issue by dsalgador** [antvis/X6#1795]
### Describe the bug

With an X6 graph with basic settings like

![image](https://user-images.githubusercontent.com/33105574/152359989-17b3c74f-e02e-487a-b6ea-b0c5b24edb7a.png)

In the background of the canvas, the `cursor` style that we see by default varies in the newest Chrome version:
- In chrome `81.0.4044.138 (Official Build) (64-bit)`  the default cursor style we see is the "grab" (open hand) icon:
![image](https://user-images.githubusercontent.com/33105574/152360717-ee001ea3-daf1-487c-89a4-05896717062c.png)

- But after updating the chrome version to `98.0.4758.80 (Official Build) (64-bit)`, the cursor style turns to be the "default" black arrow cursor:

![image](https://user-images.githubusercontent.com/33105574/152361240-10461d34-5794-4d31-adc0-92025bda4166.png)

In both versions, when pressing `left click` to do panning in the canvas, the cursor style is as expected:
![image](https://user-images.githubusercontent.com/33105574/152360898-36821dc7-f224-41bb-b61e-616e9793b0c8.png)

Note also that for `Mozilla firefox 96.0 (64-bit)` is working as in `Chrome 81.0.4044.138 (Official Build) (64-bit)` .

### Your Example Website or App

Unavailable

### Steps to Reproduce the Bug or Issue

Create an X6 Graph canvas with the settings:
```
background: {
  color: "rgba(224, 230, 237, 0.5)",
},
grid: {
  size: 27,
  visible: true,
  args: {
      color: "#C0CCDA",
      thickness: 4,
      opacity: 0.5,
  },
},
scroller: {
  className: "x6-scroller",
  enabled: true,
  pannable: true,
  pageVisible: false,
},
mousewheel: {
  enabled: true,
  minScale: 0.2,
  maxScale: 1.5,
},
keyboard: { enabled: true, global: true },
selecting: {
  enabled: true,
  multiple: true,
  rubberband: true,
  movable: true,
  showNodeSelectionBox: true,
  modifiers: ["shift", "ctrl", "meta", "alt"] as ModifierKey[],
},
autoResize: true,
```

And compare with both Chrome versions.

### Expected behaviour

For Chrome version `98.0.4758.80 (Official Build) (64-bit)` the cursor style should not be the default one (black arrow), it should be the "grab" / white open hand as in version `81.0.4044.138 (Official Build) (64-bit)`.

### Platform

- OS: Ubuntu 20.04
- Browser: Chrome
- Version: 98.0.4758.80 (Official Build) (64-bit)

### Additional context

I have also read the documentation and saw that scroller, apparently had a "cursor" option ([URL](https://x6.antv.vision/en/docs/tutorial/basic/scroller#cursor)) but typescript marked me it as not available (I'm using the latest 1.30.0 X6 version; but this bug was also tested for version `1.23.10`):

![image](https://user-images.githubusercontent.com/33105574/152362298-24aec4a3-a33c-4134-98a2-1ba91eb26dea.png)

I tried also to force compilation of this code but the cursor style did not fix:
![image](https://user-images.githubusercontent.com/33105574/152362369-41efde91-183f-4f1e-aa91-481ba4a056d3.png)

**Comment by NewByVector** [comment]
Thank you for your question, but I tested it locally with Chrome and did not reproduce your question.
![image](https://user-images.githubusercontent.com/20186737/153547208-4c038faa-911d-4c72-8003-f641aa4c3338.png)
![image](https://user-images.githubusercontent.com/20186737/153547357-2aec0c14-a2a7-4f36-9ce7-05d1b6bd6b45.png)
The only difference is I test on macos.
