### ISSUE TITLE
边可以监听节点的移入移出吗

### ISSUE THREAD

**Issue by shui2464** [antvis/X6#1796]
### 功能描述

在拖拽节点经过边的时候，对边做一些属性的配置，因为是拖拽了节点，edge的鼠标移入移出事件不触发，所以无法使用edge的鼠标移入移出事件

### 期望解决方案

添加边监听节点移入移出事件

**Comment by NewByVector** [comment]
这个不支持的，因为这个事件并不合理，如果你要实现类型的功能，可以通过节点和边的几何位置相交来实现。这里有个类似的 [demo](https://codesandbox.io/s/intersect-with-edge-iollz) 希望能帮助到你。

**Comment by shui2464** [comment]
thanks

**Comment by JasonWang1998** [comment]
建议：view.path.toPoints()?.at(0)
