### ISSUE TITLE
设置边路由的orth（正交）时，移动节点时算法出现偏差

### ISSUE THREAD

**Issue by cjinhuo** [antvis/X6#1797]
### 问题描述

设置边路由为orth后，配置自带参数padding无法出现期望的效果

![image](https://user-images.githubusercontent.com/22608658/152770728-268e2ce9-4d99-473f-b87a-a94259cde478.png)

移动world节点至hello节点下方

### 重现链接

https://codesandbox.io/s/loving-field-qv8nq

### 重现步骤

![image](https://user-images.githubusercontent.com/22608658/152770728-268e2ce9-4d99-473f-b87a-a94259cde478.png)

移动world节点至hello节点下方

### 预期行为

期望可以算出线的转折点，不然边会与节点重叠

<img width="346" alt="image" src="https://user-images.githubusercontent.com/22608658/152772798-f9abe56d-300b-4d92-bd75-fcbd7e4246ea.png">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/22608658/152770728-268e2ce9-4d99-473f-b87a-a94259cde478.png)

**Comment by NewByVector** [comment]
我运行你的 demo，结果是这样的：
![image](https://user-images.githubusercontent.com/20186737/154922682-cd261cf6-af74-4a01-83e0-db7c27391cfd.png)

**Comment by cjinhuo** [comment]
> 我运行你的 demo，结果是这样的： ![image](https://user-images.githubusercontent.com/20186737/154922682-cd261cf6-af74-4a01-83e0-db7c27391cfd.png) 有没有更详细的复现步骤。
<img width="530" alt="image" src="https://user-images.githubusercontent.com/22608658/155078378-f0d2367e-356f-4562-9a44-788dd42219a8.png">

从manhattan改为orth，就会出现以上情况

**Comment by NewByVector** [comment]
orth 不会躲避障碍物，你的场景中连接元素是两个连接桩，现在的现象是符合 orth 路由的定义的。
