### ISSUE TITLE
Safari 浏览器访问官网中的图表示例加载不出来

### ISSUE THREAD

**Issue by Wing-Lo** [antvis/X6#1804]
### Describe the bug

访问官网https://x6.antv.vision/zh/examples/showcase/practices#dag页面呈现空白
<img width="1972" alt="3dc4e96fd93ae4785247189649e681e" src="https://user-images.githubusercontent.com/16633962/153107147-a93590ed-dc65-4f24-849e-535edb787f03.png">
报错SyntaxError: Invalid regular expression: invalid group specifier name

### Your Example Website or App

不需要

### Steps to Reproduce the Bug or Issue

访问官网https://x6.antv.vision/zh/examples/showcase/practices#dag

### Expected behavior

正常显示

### Platform

- OS: macOS 11.6
- Browser: Safari 15.0

**Comment by NewByVector** [comment]
这里 https://github.com/antvis/X6/issues/1885
