### ISSUE TITLE
node 节点 文字溢出的问题？

### ISSUE THREAD

**Issue by bigfishapple** [antvis/X6#1805]
### 功能描述

node 节点 文字溢出的问题，因为数据我是动态获取的。
能否自定义class 样式或 其他方式解决？

### 期望解决方案

![image](https://user-images.githubusercontent.com/2841954/153365231-ee597a9f-33d1-4265-bbe5-9de63a24bb28.png)

**Comment by avrinfly** [comment]
看你是想要自动换行还是省略号显示
如果是换行，可以在创建节点时加这个属性：
`
attrs: {
      label: { 
        textWrap: { width: '80%' }, // 内容超过节点宽度的80%会换行
      }
    },
`

**Comment by avrinfly** [comment]
> @avrinfly 我个人想实现的是省略号，但是我不知道怎么解决？感谢~

可以参考这个文档：https://x6.antv.vision/zh/docs/api/registry/attr#textwrap
