### ISSUE TITLE
节点支持边框模式和渐变模式吗

### ISSUE THREAD

**Issue by allenzoe** [antvis/X6#1806]
### 功能描述

![image](https://user-images.githubusercontent.com/48663314/153529885-14dda78c-2cf4-4f0b-932f-fa65b0e59a74.png)
比如这种图形支持吗

### 期望解决方案

支持自定义设置特殊属性

**Comment by NewByVector** [comment]
这个用 HTML/React/Vue 节点来实现会简单很多。

**Comment by webpig** [comment]
可以自定义节点的

**Comment by NewByVector** [comment]
自定义 path 节点，配合 fillOpacity 属性可以实现。可以参考 drawio 上这个图形：
![image](https://user-images.githubusercontent.com/20186737/153717444-69567497-1630-45f9-a324-7335bdcb3cdd.png)
