### ISSUE TITLE
文档打开太慢

### ISSUE THREAD

**Issue by uinio** [antvis/X6#1811]
### 功能描述

大白板
![image](https://user-images.githubusercontent.com/49021590/153701059-ce980195-63d6-4022-90f7-5963640c68c8.png)

### 期望解决方案

文档可以快速打开

**Comment by NewByVector** [comment]
使用国内镜像试试呢。
![image](https://user-images.githubusercontent.com/20186737/153702888-3211cdf8-8a25-4825-9bf7-1f90c3f85199.png)
