### ISSUE TITLE
设置群组中的父子节点位置只能用绝对定位手动指定吗？

### ISSUE THREAD

**Issue by lhbvita** [antvis/X6#1812]
### 问题描述

群组中通过api来设置父子关系，他们的位置只能手动指定x,y吗？如何与autoLayout配合使用？即autoLayout后自动布局为父子嵌套布局

### 重现链接

无

### 重现步骤

无

### 预期行为

如问题描述

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以这样实现：先布所有父节点，然后再布局子节点，布局范围设定为父节点内部。

**Comment by lhbvita** [comment]
有demo吗？分次调用autoLayout？如何设置布局范围

**Comment by OPBR** [comment]
有解决方案了么？
