### ISSUE TITLE
manhattan 路由出现的顶点不在 segments 的计算范围内

### ISSUE THREAD

**Issue by cjinhuo** [antvis/X6#1814]
### 功能描述

<img width="210" alt="image" src="https://user-images.githubusercontent.com/22608658/153860844-1b3ecebd-6d5c-4717-9745-22856ffc2344.png">

在线demo：https://codesandbox.io/s/loving-field-qv8nq?file=/src/app.tsx

### 期望解决方案

期望在移动节点后生成的的边有vertices和segments，可以拖拽边的segment

**Comment by NewByVector** [comment]
segments 工具拖拽后会产生 vertices，这些 vertices 会影响 manhattan 路由的走向，所以这块还是不合理的。
