### ISSUE TITLE
请问一下, 框架支持缓存吗

### ISSUE THREAD

**Issue by wu74** [antvis/X6#1824]
### 问题描述

就是页面切换过后,当前画布会被销毁,然后生成的节点 也会消失, 可以做状态保存吗

### 重现链接

null

### 重现步骤

1.在当前dag页面生成节点
2.点击页签切换到其他页面
3.再切回来, 画布和节点均被销毁

### 预期行为

希望可以有状态保存, 切换回来还是之前的画布和节点

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.25.5]

**Comment by NewByVector** [comment]
如果切换后页面销毁了，画布也会销毁，重新进入的时候需要重新初始化。
