### ISSUE TITLE
所有的 mousemove 事件都不生效

### ISSUE THREAD

**Issue by jiangjingmin** [antvis/X6#1825]
### 问题描述

鼠标事件的移动鼠标事件都不生效，包括：cell:mousemove、node:mousemove、edge:mousemove、blank:mousemove。
但是在拖拽node或画布时生效了

### 重现链接

https://codesandbox.io/s/gifted-ishizaka-c0x4qf?file=/src/App.js

### 重现步骤

1. 生成node节点
2. 鼠标在node节点上方移动
3. 移动鼠标事件（'node:mousemove'）未生效

### 预期行为

期望在里打印出xy的值，但是什么也没打印
```js
graph.on("node:mousemove", (args) => {
      const { x, y, node } = args;
      console.log("x, y: ", x, y);
      console.log("node: ", node);
 });
```

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
![image](https://user-images.githubusercontent.com/20186737/154424793-4efa64dc-97d3-40bb-8001-db55b935666f.png)

**Comment by jiangjingmin** [comment]
那不就是拖拽事件么？事件名称有歧义，建议修改为 drag
另外，能不能提供一个普通的鼠标移动事件啊？我感觉这个需求应该挺多的，辛苦大佬们

**Comment by NewByVector** [comment]
可以直接在画布容器上监听 mousemove 事件。
