### ISSUE TITLE
graph.history.on("change" event stop firing working after fast multiple node clicks and moves.

### ISSUE THREAD

**Issue by konstagap** [antvis/X6#1828]
### Describe the bug

I track graph changes and save them to DB by listening graph.history.on("change") event, at one point I have noticed that event is not firing and not responding to any changes. I have added graph.on(cell:change) and checked isHistoryEnabled() inside and it returns true, but graph.history.on("change") is not firing.  I have bumped into this problem when I was rearranging multiple nodes and they were not saved to DB because the events were not firing.

### Your Example Website or App

https://codesandbox.io/s/recursing-nova-4df57m?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1. Go to  https://codesandbox.io/s/recursing-nova-4df57m?file=/src/app.tsx
2. Open Console.log
3.  by pressing 'shift' select multiple nodes. 
4. Shake selected nodes and click on them multiple times fast. try to break them.
5.  See the logs, "isHistoryEnabled() true" is still working fine, but "I'm still running" is not firing anymore

### Expected behavior

graph.history.on('change')  event should not stop responding in any cases.

### Screenshots or Videos

![x6Bug](https://user-images.githubusercontent.com/53840723/154762731-890709ea-94bc-4dd7-bba5-9658e35bf1f5.jpg)
After "isHistoryEnabled() true"  there should be "Im still running" but its not responding nomore

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by konstagap** [comment]
![screen1](https://user-images.githubusercontent.com/53840723/155064741-e3ff8773-0ebd-4758-9eaf-2cef62517643.jpg)
![screen2](https://user-images.githubusercontent.com/53840723/155064750-2e648284-8d2b-4d68-bdaa-079d2b009dca.jpg)
![screen3](https://user-images.githubusercontent.com/53840723/155064752-0309b599-c1b1-494f-ab3d-290302fd3842.jpg)
I have replicated the behavior I am experiencing, nodes moved in three different positions but the historical event is not triggered. history.on("change" triggers when any event on any cell (node or edge) happens, I was using this event listeners to save the graph to DB wherever it has been changed, but it seems like it has a bug that will prevent this event to be triggered at some point (see my images, 3 positions changed but history event not triggered). I figure that I will need to have multiple event listeners on nodes and edges separate to listen for new nodes added, removed, edited, connected, disconnected, and so on. Could you recommend any event listener that will combine all the graph events so it will be easier to save the changed graph into DB?

**Comment by NewByVector** [comment]
I still can't reproduce your question. Could you describe the operation steps in more detail？
