### ISSUE TITLE
特定shape的节点监听到mouseenter事件

### ISSUE THREAD

**Issue by MisAudrey** [antvis/X6#1829]
### 功能描述

graph可能会register很多种shape的节点，使用node:mouseenter会导致频繁触发事件（其实很多其它shape类型的节点不需要监听）

### 期望解决方案

假如有个node的shape叫parent，另一个node的shape叫child, 两个节点有parent-child关系，只mouseenter child节点的时候会触发事件

**Comment by NewByVector** [comment]
`mouseenter` 事件中，对节点的 shape 做一个判断就行了。
