### ISSUE TITLE
mousewheel太灵敏，factor设置1.1以下（如1.05）不生效

### ISSUE THREAD

**Issue by xmy285** [antvis/X6#1833]
### Describe the feature you'd like to request

mousewheel太灵敏，factor设置1.1以下（如1.05）不生效，希望可以设置1.0x的缩放因子

### Describe the solution you'd like

mousewheel太灵敏，factor设置1.1以下（如1.05）不生效，希望可以设置1.0x的缩放因子

### Describe alternatives you've considered

mousewheel太灵敏，factor设置1.1以下（如1.05）不生效，希望可以设置1.0x的缩放因子

**Comment by NewByVector** [comment]
设置成 1.0.5 是生效的，明显比设置成 1.1 灵敏度低很多。
