### ISSUE TITLE
期望节点的宽高可支持设置小数

### ISSUE THREAD

**Issue by Trojanpa** [antvis/X6#1837]
### 功能描述

拖拽两个节点紧挨在一起，若节点的宽高存在小数时，两节点不会紧密挨在一起，两节点中间会存在缝隙。在多节点紧密排布时，有小数的与没有小数的节点之间存在明显的缝隙差异。

演示：
![demo](https://user-images.githubusercontent.com/42988574/155082398-d821af81-c27a-40bc-8ec0-5eafcf598ac4.gif)

demo：https://codesandbox.io/s/antvx6-test-zl2cc0?file=/src/App.vue

### 期望解决方案

期望节点的width, height可支持设置小数

**Comment by NewByVector** [comment]
看起来是浏览器的问题，渲染的 foreignObject 的大小相比 g 会小一点点(第一张图是 g 的大小，第二张是 foreignObject 的大小),
![image](https://user-images.githubusercontent.com/20186737/155317442-ce420b11-abfa-480c-a2e6-6459b39e6727.png)


![image](https://user-images.githubusercontent.com/20186737/155317412-bdd58aca-aa25-4256-a62e-ca6225c5bef5.png)

解决你问题的方案，可以设置 rect（因为 rect的尺寸是对的） 的背景色与你内容背景色一样，就看不到间隙了。
