### ISSUE TITLE
节点拖动时，不会触发边的mouseenter事件

### ISSUE THREAD

**Issue by Cxdhz** [antvis/X6#1854]
### Describe the bug

node: moving生效时 不会触发 edge: mouseenter事件
类似issue：https://github.com/antvis/X6/issues/1431

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1. graph.on('edge:mouseenter', callback)
2. 拖动节点，鼠标经过edge边
3. 不会触发callback

### Expected behavior

我希望有种方式能够触发这个callback

### Platform

- OS: [e.g. Windows]
- Browser: [e.g. Chrome]
- x6: [e.g. 1.28.1]

### Additional context

需求是：当我拖动节点时 ，如果经过某条边，那么这条边就会被高亮（选中）

**Comment by NewByVector** [comment]
这个比较好的方式是使用节点和边在图形上是否相交来实现，这里有个 [demo](https://codesandbox.io/s/node-edge-intersect-drt7vo)，希望能帮到你。

**Comment by Cxdhz** [comment]
> 这个比较好的方式是使用节点和边在图形上是否相交来实现，这里有个 [demo](https://codesandbox.io/s/node-edge-intersect-drt7vo)，希望能帮到你。

在节点和边较少的时候这个方法能很好的起作用。若边的数量较多且画布复杂时，可能会出现性能问题。所以想通过借鉴AOI算法的思想将监听设置在边上。

**Comment by NewByVector** [comment]
我先研究一下 AOI 算法。 ✊

**Comment by NewByVector** [comment]
@Cxdhz 如果边不是曲线的话，这种计算很快的，不用考虑性能问题。
