### ISSUE TITLE
开启snapline时，多选节点并移动，节点移动位置错误并有抖动现象

### ISSUE THREAD

**Issue by xyhxyw** [antvis/X6#1855]
### Describe the bug

1、开启snapline后，多选多个节点，同时移动时，节点移动位置错误，并有抖动现象。
2、复现地址

- 1、antv官网demo： [antv x6流程图](https://x6.antv.vision/zh/examples/showcase/practices#flowchart)
- 2、xflow官网demo：[xflow流程图解决方案](https://xflow.antv.vision/docs/tutorial/solutions/flow/)

### Your Example Website or App

https://x6.antv.vision/zh/examples/showcase/practices#flowchart

### Steps to Reproduce the Bug or Issue

1、antv官网demo，复现步骤：
1、修改68-73行代码如下：
```js
{
      resizing: false, // 关闭resizing
      rotating: false, // 关闭rotating
      selecting: {
        enabled: true,
        rubberband: true,
        showNodeSelectionBox: false, // 关闭showNodeSelectionBox
      },
}
```
并在**insertCss**中最后一行加入如下样式代码，主要用于标识节点的选中状态。
```
.x6-node-selected rect {
      stroke-width: 2px;
}
```
2、从左侧面板依次拖入`过程`、`开始`、`过程`3个节点，并**保证竖直对齐**。节点之间的垂直距离，可以拉开些，方便重现。
3、按住`shift`，框选这3个节点。鼠标放置到`第一个过程节点`，按下，开始上下左右拖动。
4、然后鼠标放到`中间的开始节点`，按下鼠标，轻轻上下拖动，会发现其他节点移动位置、方向不对。
5、然后鼠标放到`下面或者上面的开始节点`，按下鼠标，轻轻上下拖动，会发现其他节点移动位置、方向不对。同时，即使停止了移动，其他节点依然在移动。节点移动，有抖动现象。

### Expected behavior

1、期望开启snapline时，多选状态下，移动正常。

### Screenshots or Videos

antv官网demo复现截图：

![antv x6 flowchart2](https://user-images.githubusercontent.com/2510538/155945143-afbbf284-a1fd-49ed-b478-ceb973263e30.gif)

xflow官网demo复现截图：

![x6 XFlow 流程图解决返岗-多选移动](https://user-images.githubusercontent.com/2510538/155945184-7b021f0d-f3ab-49da-8850-2fe30c2be708.gif)

### Platform

- OS: [Windows10]
- Browser: [Chromex]
- Version: [98.0.4758.102]

**Comment by Mr-clown2040** [comment]
这个 一直存在这个现象，只要多选拖动就会出现 错位

**Comment by MrMengJ** [comment]
请问有解决方案了吗

**Comment by MrMengJ** [comment]
这个bug有点严重
![移动错位](https://user-images.githubusercontent.com/26325346/177516132-778d18ac-f1a9-4ce0-9ddb-475785c3e40e.gif)

**Comment by MrMengJ** [comment]
#1231 [原因](https://github.com/antvis/X6/issues/1231#issuecomment-911339927)

**Comment by NewByVector** [comment]
1.x 最新版本以及 2.x 版本中已经修复。
