### ISSUE TITLE
fromJSON会导致连线tool工具失效

### ISSUE THREAD

**Issue by syvn** [antvis/X6#1866]
### 问题描述

fromJSON会导致连线tool工具失效, 调整线段的节点没出来, 无法调整线段

### 重现链接

https://codesandbox.io/s/heuristic-phoebe-f4uwer?file=/src/app.tsx

### 重现步骤

注释代码的方式是可以的

### 预期行为

通过fromJSON渲染, 可以调整对应内容

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by syvn** [comment]
![b81247c88f9eba9b67b97364d722755](https://user-images.githubusercontent.com/23226732/156523642-84b82230-c55a-45d3-ac0b-aa1fb2d78848.png)
![image](https://user-images.githubusercontent.com/23226732/156523773-bef63787-6832-4c42-8f6a-b60d5cb351e0.png)

**Comment by NewByVector** [comment]
这个 segments 工具只有在连线的 source 和 target 在同一水平面的时候才出现。你把节点位置移到同一水平面，就可以看到啦。✈️

**Comment by syvn** [comment]
> 这个段工具只有在连线的源和目标在同一个水平面的时候才出现。你把节点位置移到同一个水平面，就可以看到啦。✈️

那如果选择路由是拐线, 我想手动修改下拐线的位置, 我应该怎样去调整呢?
![image](https://user-images.githubusercontent.com/23226732/156687852-065be5f1-556f-4840-a636-5ba0dd4256ee.png)

**Comment by syvn** [comment]
拖拽节点之后, 新的线段没有了可拖拽的点, 但是原来的线段上又有, 我看过node:move返回的参数, 并找到对应连线的数据, 发现没有拐点vertices的信息, 如果存在这些点信息, 我是否可以自己计算然后添加锚点, 进而操作线段变化?
还有就是, 我拖拽节点之后, 再次拖拽到一条水平线上, 对应的线也不会出现拖拽点了
![image](https://user-images.githubusercontent.com/23226732/156688629-8a99bf64-5cc4-4c6c-9702-a652039ce9ea.png)
![image](https://user-images.githubusercontent.com/23226732/156688677-f0b66438-8f56-4716-9a87-064013e161f4.png)

**Comment by NewByVector** [comment]
@syvn  vertices 与 manhattan 路由结合的时候有点问题，这个问题修复已经排进我们的工作计划中。感谢你的问题。
