### ISSUE TITLE
节点缩放支持过滤节点类型

### ISSUE THREAD

**Issue by avrinfly** [antvis/X6#1867]
### 功能描述

画布中有两种类型的节点，开启节点缩放后，我希望点其中一个节点会出现缩放框，点另一个不出现

### 期望解决方案

希望有一个配置项：类似于Selection的filter
![image](https://user-images.githubusercontent.com/30068005/156525216-997b80b7-1a1f-4360-9f80-3e4b7e9793c4.png)

**Comment by NewByVector** [comment]
`resizing` 的 `enable` 配置是支持函数的，可以在函数中针对节点做判断，返回 `true` 或者 `false` 来决定是否显示缩放框，相关[文档](https://x6.antv.vision/zh/docs/api/graph/transform#resizing)
