### ISSUE TITLE
fromJSON后，位置没有生效，节点再次拖动与线分离

### ISSUE THREAD

**Issue by mcdyzg** [antvis/X6#187]
https://codesandbox.io/s/x6-connect-edge3-1nmfw?file=/src/index.ts
![ytpox-t19o5](https://user-images.githubusercontent.com/14190768/86733691-fd2b7380-c063-11ea-8124-ccaed56b0861.gif)

**Comment by bubkoo** [comment]
fixed in x6@0.10.24

https://codesandbox.io/s/x6-fix-187-j6b45?file=/src/index.ts
