### ISSUE TITLE
启用框选多选功能后允许点击节点时可以做移动节点以外的操作, 比如编辑节点的内容

### ISSUE THREAD

**Issue by daodao90** [antvis/X6#1870]
### 功能描述

我在使用X6的时候通过如下配置启用了 框选功能： 
selecting: {
                enabled: true,
                multiple: true,
                rubberband: true,
                movable: true,
                showNodeSelectionBox: true,
                modifiers: 'ctrl'
            }
因为业务需求，我的节点带有输入框(2个input)。 但是因为启用了框选， 想输入内容时总是首先就框选节点以致于很难输入内容(必须反复点击，多次尝试让鼠标定位到输入框)

### 期望解决方案

希望能帮助我解决这个问题。 比如如何在启用框选功能后，在点击节点内的输入框时可以顺利输入内容而不是直接框选了节点（还有鼠标指针是移动节点状态）

**Comment by daodao90** [comment]
我的节点带有输入框(2个input)， 而且我在节点上已经绑定了dblclick事件(打开编辑页面)

**Comment by NewByVector** [comment]
可以添加样式：
```css
.x6-widget-selection-box {
  pointer-events: none;
}
```
