### ISSUE TITLE
getConnectedEdges indirect=true没有返回间接连接的边

### ISSUE THREAD

**Issue by lhbvita** [antvis/X6#1874]
### 问题描述

![image](https://user-images.githubusercontent.com/29444839/156962183-d640142a-4e5a-498e-b23b-b301c1613fb0.png)
![image](https://user-images.githubusercontent.com/29444839/156962237-34415d18-cce3-4380-9030-f965431812c2.png)

有如上的节点和代码，查询节点1的connectedEdges时，只返回了1-2的边，2-3，2-5，5-4都没有返回；
请问
![image](https://user-images.githubusercontent.com/29444839/156962319-900d61e7-c5c0-48b8-980a-ee99f21ab220.png)
这里的间接是指什么意思？2-3不是间接边吗

### 重现链接

无

### 重现步骤

见描述

### 预期行为

返回2-3……等边

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
`indirect` 是指连接到边上的边，和你理解的不是一个概念，你这里可以需要自己来实现上面功能。
