### ISSUE TITLE
使用dagre.layout布局，耗时太长

### ISSUE THREAD

**Issue by lhbvita** [antvis/X6#1876]
### 问题描述

for(let i=0;i<1001;i++){
  nodes.push(createNode('Founder & Chairman'+i, 'Pierre Omidyar'+i, male))
}

const edges = []
for(let i=0;i<500;i++){
  edges.push(createEdge(nodes[i], nodes[i+1]))
}
只是1000个节点和500条边，dagre.layout耗时 607 ms，渲染更慢，主要是edge耗时太久

### 重现链接

https://x6.antv.vision/zh/examples/showcase/practices#orgchart

### 重现步骤

1. https://x6.antv.vision/zh/examples/showcase/practices#orgchart
2. 修改成1000以上节点，500以上边
for(let i=0;i<1001;i++){
  nodes.push(createNode('Founder & Chairman'+i, 'Pierre Omidyar'+i, male))
}

const edges = []
for(let i=0;i<500;i++){
  edges.push(createEdge(nodes[i], nodes[i+1]))
}

### 预期行为

优化edge渲染速度

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
我们正在做 2.0 版本开发，会进行彻底的性能优化。

**Comment by lhbvita** [comment]
什么时候可以上线？

**Comment by NewByVector** [comment]
@lhbvita 你可以给个demo，我看下你的场景有没有优化空间

**Comment by lhbvita** [comment]
@NewByVector 官网demo就可以模拟，2000个节点和边，就崩了
import { Graph, Cell, Node, Color, Dom } from '@antv/x6'
import dagre from 'dagre'
import insertCss from 'insert-css'
// 定义样式
// 我们用 insert-css 演示引入自定义样式
// 推荐将样式添加到自己的样式文件中
// 若拷贝官方代码，别忘了 npm install insert-css
insertCss(`
  .x6-cell {
    cursor: default;
  }
  .x6-node .btn {
    cursor: pointer;
  }
`)
// 自定义节点
Graph.registerNode(
  'org-node',
  {
    width: 260,
    height: 88,
    markup: [
      {
        tagName: 'rect',
        attrs: {
          class: 'card',
        },
      },
      {
        tagName: 'image',
        attrs: {
          class: 'image',
        },
      },
      {
        tagName: 'text',
        attrs: {
          class: 'rank',
        },
      },
      {
        tagName: 'text',
        attrs: {
          class: 'name',
        },
      },
      {
        tagName: 'g',
        attrs: {
          class: 'btn add',
        },
        children: [
          {
            tagName: 'circle',
            attrs: {
              class: 'add',
            },
          },
          {
            tagName: 'text',
            attrs: {
              class: 'add',
            },
          },
        ],
      },
      {
        tagName: 'g',
        attrs: {
          class: 'btn del',
        },
        children: [
          {
            tagName: 'circle',
            attrs: {
              class: 'del',
            },
          },
          {
            tagName: 'text',
            attrs: {
              class: 'del',
            },
          },
        ],
      },
    ],
    attrs: {
      '.card': {
        rx: 10,
        ry: 10,
        refWidth: '100%',
        refHeight: '100%',
        fill: '#5F95FF',
        stroke: '#5F95FF',
        strokeWidth: 1,
        pointerEvents: 'visiblePainted',
      },
      '.image': {
        x: 16,
        y: 16,
        width: 56,
        height: 56,
        opacity: 0.7,
      },
      '.rank': {
        refX: 0.95,
        refY: 0.5,
        fill: '#fff',
        fontFamily: 'Courier New',
        fontSize: 13,
        textAnchor: 'end',
        textVerticalAnchor: 'middle',
      },
      '.name': {
        refX: 0.95,
        refY: 0.7,
        fill: '#fff',
        fontFamily: 'Arial',
        fontSize: 14,
        fontWeight: '600',
        textAnchor: 'end',
      },
      '.btn.add': {
        refDx: -16,
        refY: 16,
        event: 'node:add',
      },
      '.btn.del': {
        refDx: -44,
        refY: 16,
        event: 'node:delete',
      },
      '.btn > circle': {
        r: 10,
        fill: 'transparent',
        stroke: '#fff',
        strokeWidth: 1,
      },
      '.btn.add > text': {
        fontSize: 20,
        fontWeight: 800,
        fill: '#fff',
        x: -5.5,
        y: 7,
        fontFamily: 'Times New Roman',
        text: '+',
      },
      '.btn.del > text': {
        fontSize: 28,
        fontWeight: 500,
        fill: '#fff',
        x: -4.5,
        y: 6,
        fontFamily: 'Times New Roman',
        text: '-',
      },
    },
  },
  true,
)
// 自定义边
Graph.registerEdge(
  'org-edge',
  {
    zIndex: -1,
    attrs: {
      line: {
        strokeWidth: 2,
        stroke: '#A2B1C3',
        sourceMarker: null,
        targetMarker: null,
      },
    },
  },
  true,
)
const male =
  'https://gw.alipayobjects.com/mdn/rms_43231b/afts/img/A*kUy8SrEDp6YAAAAAAAAAAAAAARQnAQ'
const female =
  'https://gw.alipayobjects.com/mdn/rms_43231b/afts/img/A*f6hhT75YjkIAAAAAAAAAAAAAARQnAQ'
// 布局方向
const dir = 'LR' // LR RL TB BT
// 创建画布
const graph = new Graph({
  container: document.getElementById('container')!,
  scroller: true,
  interacting: false,
})
// 监听自定义事件
function setup() {
  graph.on('node:add', ({ e, node }) => {
    e.stopPropagation()
    const member = createNode(
      'Employee',
      'New Employee',
      Math.random() < 0.5 ? male : female,
    )
    graph.freeze()
    graph.addCell([member, createEdge(node, member)])
    layout()
  })
  graph.on('node:delete', ({ e, node }) => {
    e.stopPropagation()
    graph.freeze()
    graph.removeCell(node)
    layout()
  })
}
// 自动布局
function layout() {
  console.time('layout')
  const nodes = graph.getNodes()
  const edges = graph.getEdges()
  const g = new dagre.graphlib.Graph()
  g.setGraph({ rankdir: dir, nodesep: 16, ranksep: 16 })
  g.setDefaultEdgeLabel(() => ({}))
  const width = 260
  const height = 90
  nodes.forEach((node) => {
    g.setNode(node.id, { width, height })
  })
  edges.forEach((edge) => {
    const source = edge.getSource()
    const target = edge.getTarget()
    g.setEdge(source.cell, target.cell)
  })
  dagre.layout(g)
  graph.freeze()
  g.nodes().forEach((id) => {
    const node = graph.getCell(id) as Node
    if (node) {
      const pos = g.node(id)
      node.position(pos.x, pos.y)
    }
  })
  graph.unfreeze()
  console.timeEnd('layout')
}
function createNode(rank: string, name: string, image: string) {
  return graph.createNode({
    shape: 'org-node',
    attrs: {
      '.image': { xlinkHref: image },
      '.rank': {
        text: Dom.breakText(rank, { width: 160, height: 45 }),
      },
      '.name': {
        text: Dom.breakText(name, { width: 160, height: 45 }),
      },
    },
  })
}
function createEdge(source: Cell, target: Cell) {
  return graph.createEdge({
    shape: 'org-edge',
    source: { cell: source.id },
    target: { cell: target.id },
  })
}
const nodes = [];
const edges = [];
let length = 2000
for(let i=0;i<(length +1);i++){ 
  // nodes.push(createNode('Founder & Chairman'+i, 'Pierre Omidyar'+i, male)) 
} 
for(let i=0;i<length ;i++){ 
  //edges.push(createEdge(nodes[i], nodes[i+1])) 
}
graph.resetCells([...nodes, ...edges])
layout()
graph.zoomTo(0.8)
graph.centerContent()
setup()

**Comment by NewByVector** [comment]
这个是 dagre 的问题，测试代码：
```ts
import dagre from 'dagre'

const nodes = []
const edges = []
for(let i=0; i < 2001; i++){ 
  nodes.push({
    id: i + '',
  }) 
} 
for(let i=0; i < 2000; i++){ 
  edges.push({
    source: i + '',
    target: (i + 1) + ''
  }) 
} 
const g = new dagre.graphlib.Graph()
  g.setGraph({ rankdir: 'LR', nodesep: 16, ranksep: 16 })
  g.setDefaultEdgeLabel(() => ({}))
  const width = 260
  const height = 90
  nodes.forEach((node) => {
    g.setNode(node.id, { width, height })
  })
edges.forEach((edge) => {
  const source = edge.source
  const target = edge.target
  g.setEdge(source, target)
})
dagre.layout(g)
```
