### ISSUE TITLE
节点使用node-editor工具修改文字内容后 撤销及重做功能失效

### ISSUE THREAD

**Issue by zyz19951225** [antvis/X6#1879]
### 问题描述

节点使用node-editor工具修改文字内容后 撤销及重做功能全部失效

### 重现链接

https://codesandbox.io/s/0xy5j?file=/src/app.tsx

### 重现步骤

**1.**进入官方提供撤销及重做demo  https://codesandbox.io/s/0xy5j?file=/src/app.tsx
**2.**给节点添加node-editor工具代码
graph.on('cell:dblclick', ({ cell, e }) => {
      const name = cell.isEdge() ? 'edge-editor' : 'node-editor'
      cell.removeTool(name)
      cell.addTools([
          {
              name,
              args: {
                  event: e,
              },

          },
      ])
  })

**3.**测试回退及重做功能

### 预期行为

回退及重做功能失效，但显示可以回退

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
失效的原因：
1. 第一次 undo，返回编辑状态
2. 第二次 undo，因为点击了输入框以外的区域，会触发 editor 内部的 onDocumentMouseDown 事件，重新走了 setText 逻辑
暂时还没有好的解决方案

**Comment by NewByVector** [comment]
可以这样，组织添加 tools 行为进入 history。
```ts
history: {
  enabled: true,
  beforeAddCommand(event, args) {
    return args.key !== 'tools'
  },
}
```
