### ISSUE TITLE
safair浏览器 无法打开

### ISSUE THREAD

**Issue by stogefei** [antvis/X6#1885]
### Describe the bug

https://x6.antv.vision/zh/examples/showcase/practices/#dag

macbookpro 下safair浏览器无法打开 

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/23629710/157402690-54a19fc5-b204-4466-b55a-301e3cefdd47.png">

### Your Example Website or App

https://x6.antv.vision/zh/examples/showcase/practices/#dag

### Steps to Reproduce the Bug or Issue

https://x6.antv.vision/zh/examples/showcase/practices/#dag

macbookpro 下safair浏览器无法打开 

### Expected behavior

https://x6.antv.vision/zh/examples/showcase/practices/#dag

macbookpro 下safair浏览器无法打开 

### Screenshots or Videos

https://x6.antv.vision/zh/examples/showcase/practices/#dag

macbookpro 下safair浏览器无法打开 

### Platform

- OS: macOS
- Browser: Safari
- Version:15.3

### Additional context

https://x6.antv.vision/zh/examples/showcase/practices/#dag

macbookpro 下safair浏览器无法打开

**Comment by Eve-Sama** [comment]
+1

**Comment by NewByVector** [comment]
Related Issue：https://github.com/antvis/gatsby-theme-antv/issues/373

**Comment by JamesTing** [comment]
一个前端项目，官网在safari下打不开，有点说不过去啊...
虽然不是啥大问题，但伤害性不大，侮辱性极强。
希望X6越来越好！
<img width="1014" alt="截屏2022-03-11 下午11 34 12" src="https://user-images.githubusercontent.com/1875508/157898520-edb61516-1e09-48d2-8c2f-08b02658626f.png">

**Comment by NewByVector** [comment]
@JamesTing 这个和 x6 没有关系的，x6 是能够在 safari 下正常运行，这个报错是因为官网的框架.

**Comment by NewByVector** [comment]
新版[官网](http://x6.antv.antgroup.com/)已经可以在 safari 中访问了。
