### ISSUE TITLE
blank:mousemove不支持鼠标右键

### ISSUE THREAD

**Issue by zxtClick** [antvis/X6#1888]
### Describe the bug

按住鼠标右键后移动无法触发blank:mousemove事件,但左键和滑轮可以触发

### Your Example Website or App

https://stackblitz.com/edit/vue-tfofzf

### Steps to Reproduce the Bug or Issue

按住右键在blank区域滑动,无法触发mousemove事件

### Expected behavior

期望能触发mousemove

### Platform

- OS: [ Windows]
- Browser: [e.g. Chrome]
- Version: [1.30.2]

**Comment by NewByVector** [comment]
很抱歉我们的事件设计中右键点击后是不会触发 `mousemove` 事件的，如果业务中有需求的话，可以在画布容器上通过原生的事件来实现。

**Comment by zxtClick** [comment]
> 很抱歉我们的事件设计中右键点击后是不会触发 `mousemove` 事件的，如果业务中有需求的话，可以在画布容器上通过原生的事件来实现。

有点失望
1.能支持滚轮的mousemove却不能支持右键,就业务场景来说右键按住后move比滚轮按住后move体验好许多;
2.用原生事件比较麻烦,可能需要注意cell的冒泡;
3.文档中好像没有明确提到mousemove只支持左键和滚轮
