### ISSUE TITLE
toPNG/toJPEG 访问缓存图片跨域问题

### ISSUE THREAD

**Issue by jumodada** [antvis/X6#1893]
### 功能描述

```
toPNG(()=>{},{
 // .....
addSuffixHashToImageUrl(){
 return `nostore=${Date.now()}`
}
})
```
就是在一些情况下，未使用meta标签`no-cache`之类，假使之前画布访问过某个图片的url，生成缩略图的时候就会访问浏览器缓存图片而遇到跨域问题，这个普通请求是难以在外部修改x6去改变的。所以希望官方能提供一个方案可以解决这个问题，或者是提供一个参数支持传入函数去修改imageUrl的后缀而让浏览器去请求托管图片的服务器

### 期望解决方案

目前是在外部手动添加后缀名来处理这个问题，希望提pr内部api支持上述伪代码或官方能提供更好的方法，非常感谢

**Comment by NewByVector** [comment]
是指画布的背景图片还是 `image` 标签中的图片？

**Comment by jumodada** [comment]
> 是指画布的背景图片还是 `image` 标签中的图片？

是image标签的图片

**Comment by jumodada** [comment]
> 是指画布的背景图片还是 `image` 标签中的图片？

https://codesandbox.io/s/cool-paper-3xk75g?file=/src/App.js

copy简易写了一个demo
这样子点击按钮后打开控制台应该可以看到报错，

**Comment by NewByVector** [comment]
节点图片最好使用 base64 图片，这样也能解决导出样式问题。

**Comment by jumodada** [comment]
> 节点图片最好使用 base64 图片，这样也能解决导出样式问题。

嗯嗯，只是后端那边要求传回url，按这种解决方案我只能一开始转为base64，配置完上传的时候再重新赋值为原始url了
