### ISSUE TITLE
期望提供隐藏节点的能力

### ISSUE THREAD

**Issue by lhbvita** [antvis/X6#1897]
### 功能描述

希望能提供隐藏节点或边的能力，而不是删除

### 期望解决方案

希望能提供隐藏节点或边的能力，而不是删除

**Comment by NewByVector** [comment]
可以先这样实现，2.0 版本会提供这个能力。
```ts
const view = graph.findViewByCell(node)
view.container.style.display = 'none'
```

**Comment by Trojanpa** [comment]
![image](https://user-images.githubusercontent.com/42988574/160552768-4713a9e1-21f8-4edf-9184-638e9c418bf2.png)
可以通过cell.hide();这个方法来隐藏节点/边，不知道这是不是你想要的效果。

**Comment by NewByVector** [comment]
@Trojanpa 这里的隐藏会将节点从画布删除。
