### ISSUE TITLE
shape为image时，label 能否在图片下方

### ISSUE THREAD

**Issue by yuruotong1** [antvis/X6#1899]
### 问题描述

shape为image时，label 能否在图片下方，否则label会与图片重叠

### 重现链接

无

### 重现步骤

无

### 预期行为

label 在 image 下方

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/31992251/158916330-7e0d438d-7312-48bf-bc0c-fee3d2d0ae69.png)

**Comment by NewByVector** [comment]
可以这样：
```ts
graph.addNode({
  shape: 'image',
  x: 320,
  y: 120,
  width: 94,
  height: 28,
  imageUrl:
    'https://gw.alipayobjects.com/os/s/prod/antv/assets/image/logo-with-text-73b8a.svg',
  label: 'xxx',
  attrs: {
    label: {
      refY: '100%'
    }
  }
})
```
