### ISSUE TITLE
使用port后, 连线路由计算失去规避节点的功能

### ISSUE THREAD

**Issue by syvn** [antvis/X6#1901]
### 问题描述

使用port后, 连线路由计算失去规避节点的功能
![image](https://user-images.githubusercontent.com/23226732/158930525-cebc0c61-8913-47db-be4c-2458ed7af5b2.png)

### 重现链接

https://codesandbox.io/s/serverless-haze-xvwyi6?file=/src/app.tsx

### 重现步骤

直接看链接就可以复现

### 预期行为

连接到对应port并不会与其他节点重叠

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by SunyanLBJ23** [comment]
此问题有没有计划修复？

**Comment by NewByVector** [comment]
你这里的 `endDirections = 'bottom' `设置的有问题，从连接桩下面进入，并且规避节点，是不可能做到的。可以设置成 top，看下效果。
