### ISSUE TITLE
在画布外 无法监听 被拖拽元素的 类似原生dragend事件；在不可被放置的区域时，希望有鼠标not-allowed 手势提示

### ISSUE THREAD

**Issue by cc-ww** [antvis/X6#1902]
####  遇到的问题
使用 dnd 拖拽元素 到  画布中，当前x6 封装的一系列操作  都是监听拖拽元素在画布元素内的。当 拖拽元素，在画布之外，好多监听事件都会无效， 希望有类似原生的  dragend 事件，当拖拽元素在画布外结束拖拽时，可以监听到，也希望加上类似原生的鼠标手势变化的样式，在不可被放置时有cursor: not-allow手势

#### 场景如下
画布有 A\B\C\D四个区域，可拖拽元素有按A\B\C\D分四类，想拖拽元素A到画布中，只有对应的画布中的A区域会高亮，鼠标移开画布/或者拖拽结束 就会移除高亮，当拖拽元素在画布外结束拖拽时，无法监听到，此时会影响高亮的移除（在此处曾想监听document的mouseup事件的，但是mousemove触发的时候，mouseup无法被触发）；

### 期望解决方案

1.可以暴露一个可以监听拖拽元素 结束拖拽的事件，即使在画布外（例如原生的dragend事件）
2.提供一个属性配置来控制，是否显示，元素可被放入对应区域的鼠标手势

**Comment by cc-ww** [comment]
@NewByVector   是这样的

1.原生的拖拽事件，  当元素在拖拽时，document的mousemove和mouseup都被触发。
原生的可拖拽元素就是    <div class="box1" draggable="true" id="source"></div>  类似这种
监听事件如下：
document.addEventListener('mousemove', () => {
        console.log("mousemove")
 })
document.addEventListener('mouseup', () => {
        console.log("mouseup")
 })
元素正在被拖拽时，mousemove不会被触发，当松开左键 结束拖拽时mouseup也不会被触发



2.使用x6  dnd 拖拽元素,   当元素在拖拽时 ，document的mousemove 可以被触发，但是mouseup不能；

可拖拽元素  使用 new Stencil（） 创建，

监听事件

document.addEventListener('mousemove', () => {
        console.log("mousemove")
 })
document.addEventListener('mouseup', () => {
        console.log("mouseup")
 })
 
 元素正在被拖拽时，mousemove会被实时触发，当松开左键 结束拖拽时mouseup不会被触发
 
 单独用mousemove 来判断，要多写判断鼠标是否处于画布内的代码

**Comment by NewByVector** [comment]
我[这里](https://codesandbox.io/s/nostalgic-darkness-881k75?file=/src/app.tsx) 写了一个 demo，是可以触发的。

**Comment by cc-ww** [comment]
还真可以，估计是我触发监听的时机不对，感谢！

**Comment by cc-ww** [comment]
不是监听的时机不对，mousedown 后给 class = dragging  绑定一个  mouseup事件就可以了；
如果给document 绑定再取消后，再次绑定会触发不了。初步怀疑是 x6 有mouseevent 拦截的事件，导致冒泡不出来，后面就监听不到了，给正在拖拽的中元素绑定就好。

感谢启发！
