### ISSUE TITLE
通过点击一个按钮手动添加节点时，若节点角度为90度，节点在画布出现的位置不对

### ISSUE THREAD

**Issue by Trojanpa** [antvis/X6#1906]
### 问题描述

在一个角度为90度的节点的 上/下/左/右 方向通过按钮添加节点时，添加后的节点出现在画布中的的位置不对，添加的这个节点的坐标是对的，但与其他相同x或相同y坐标的节点位置不对。（其他角度我没有试过，不排除可能也存在这个问题）

### 重现链接

https://codesandbox.io/s/xuan-zhuan-hou-tian-jia-jie-dian-de-bug-j9is51?file=/src/App.vue

### 重现步骤

选中一个旋转90度的节点，点击 “在节点上/下/左/右方添加节点” 按钮，观察添加后的节点位置，对比计算基准节点和添加后的节点的坐标信息。

### 预期行为

期望修复添加节点后出现在画布中的位置能够准确。

### 平台

- 操作系统: [Windows.]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.30.2 ... ]

### 屏幕截图或视频（可选）
注意观察：x坐标相同，节点所处画布位置不同，y.....

![bug](https://user-images.githubusercontent.com/42988574/158983096-c5452568-79f4-4f68-be0c-7cf7a8291b37.gif)

**Comment by NewByVector** [comment]
pin

**Comment by NewByVector** [comment]
x6 的坐标是节点左上角的坐标，而不是中心点坐标，你的计算方式有问题。

**Comment by Trojanpa** [comment]
> x6 的坐标是节点左上角的坐标，而不是中心点坐标，你的计算方式有问题。

我用的就是节点左上角的坐标呀

**Comment by Trojanpa** [comment]
> x6 的坐标是节点左上角的坐标，而不是中心点坐标，你的计算方式有问题。
![screenshots](https://user-images.githubusercontent.com/42988574/215312342-206586c5-5a1c-4b02-a6bb-4c48e8f335fe.gif)

**Comment by NewByVector** [comment]
比如你中间那个图片，它的 position 是 { x: 100, y: 100 },旋转 90 度以后，它的 position 任然为 { x: 100, y: 100 },所以你的这段代码就有问题了。
![image](https://user-images.githubusercontent.com/20186737/215373365-78708b3e-70d4-41d1-a6de-d620e3bcc355.png)

**Comment by Trojanpa** [comment]
> 比如你中间那个图片，它的 position 是 { x: 100, y: 100 },旋转 90 度以后，它的 position 任然为 { x: 100, y: 100 },所以你的这段代码就有问题了。 ![image](https://user-images.githubusercontent.com/20186737/215373365-78708b3e-70d4-41d1-a6de-d620e3bcc355.png)

节点旋转后的坐标不变我是知道的。是不是我遗漏了什么，这种情况该怎么计算新节点的位置？

**Comment by NewByVector** [comment]
@Trojanpa 旋转 90 度以后，x y 已经不是左上角了，而是右上角。

**Comment by Trojanpa** [comment]
> @Trojanpa 左上角坐标已经不是 x 坐标了呀。

意思是旋转后节点的坐标不再是左上角了？感觉有点乱

**Comment by JoeWrights** [comment]
> > @Trojanpa 左上角坐标已经不是 x 坐标了呀。
> 
> 意思是旋转后节点的坐标不再是左上角了？感觉有点乱

我也遇到这个问题了，旋转后，左上角的坐标是不会转换的，依然是旋转前的坐标
