### ISSUE TITLE
cell.show()不生效

### ISSUE THREAD

**Issue by lhbvita** [antvis/X6#1915]
### Describe the bug

调用cell.hide()后，节点的visible变为false，节点隐藏，再次调用cell.show()，节点的visible已经变为true，但是节点并未显示

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1.调用cell.hide()
2.调用cell.show()

### Expected behavior

正常切换显隐

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by 992forever** [comment]
请问解决了吗？遇到了同样的问题
