### ISSUE TITLE
在 scale(0) 的元素中创建 graph 会报错

### ISSUE THREAD

**Issue by YiSiWang** [antvis/X6#1916]
### 问题描述

在元素（或其父元素）含有 scale(0) 样式（或其他导致 BBox 大小为0的样式）内，创建带有连接桩的 x6 graph 时，会报错：
```
InvalidStateError
Failed to execute 'inverse' on 'SVGMatrix': The matrix is not invertible.
```

### 重现链接

https://codesandbox.io/s/x6-with-scale-0-5d4uk7

### 重现步骤

上述 sandbox 打开即可复现。
代码为官网快速开始示例，加了 `transfrom: scale(0);` 和一个连接桩配置。

### 预期行为

正常渲染，不报错。

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: latest

### 补充说明（可选）

虽然是 edge case ，但实际发生在业务中，因为 antd 的 Popover 会有动画效果，初始化时包含 scale(0) 样式。

**Comment by NewByVector** [comment]
为啥有在 `scale(0)` 的元素中创建 graph 的场景？
