### ISSUE TITLE
对于polyline.intersectsWithLine方法的疑问

### ISSUE THREAD

**Issue by shui2464** [antvis/X6#1917]
### 功能描述

![无标题](https://user-images.githubusercontent.com/34205271/159420324-840f413f-1e1f-48f8-8a78-ed7f430d6790.png)
之前有个需求，监听边的节点移入移出，我参照这个例子：https://codesandbox.io/s/intersect-with-edge-iollz
发现一个问题如图，里面用到的方法只能算出直线与另一个几何形状的交点的数组，但是对于曲线，它就会返回错误的结果，如图2中，节点移到红色线就会触发连接

### 期望解决方案

希望提供一个方案

**Comment by NewByVector** [comment]
如果是曲线确实有问题，我思考下怎么解决这个问题，期待你能提出更好的方案。
