### ISSUE TITLE
checkView方法和 Selection 功能 是否存在冲突？

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#1918]
### 问题描述

async = true的时候，checkView 方法会一直执行，此时是可以通过view.cell获取到cell的信息。
但是如果框选节点，再进行拖动操作，会出现view.cell 是空的情况？不知道这个是不是bug？

### 重现链接

https://codesandbox.io/s/ecstatic-hooks-onjz49?file=/src/app.tsx

### 重现步骤

1. 正常进入页面，控制台是不会有任何打印信息
2. 框选任意节点
3. 移动框选的节点，此时控制台会输出 error

### 预期行为

1. 期望不存在view.cell 为空的情况

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.30.1]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/22650893/159436682-18f98fc4-b6d1-4e3a-a997-b067acf6acca.png)

**Comment by NewByVector** [comment]
`Selection` 也是继承于 `view` 的，所以会检测到，这里并没有问题。
