### ISSUE TITLE
事件cell:change:attrs回调执行JSON.stringify(graph.toJSON())报错——已补充复现demo

### ISSUE THREAD

**Issue by JamesTing** [antvis/X6#1922]
### 问题描述

需求：通过画布监听cell的变化，在回调中使用JSON.stringify(graph.toJSON())处理数据，以便上传到服务端。
问题：同样都是监听事件，对graph.toJSON()进行JSON.stringify，为什么时机不同会影响转换结果呢？
- 监听 cell:added，JSON.stringify(graph.toJSON())不报错
- 监听 cell:change:attrs，JSON.stringify(graph.toJSON())报错，信息如下：

>     Uncaught TypeError: Converting circular structure to JSON
>     --> starting at object with constructor 'HTMLDivElement'
>     |     property '__reactFiber$l4hyz4bfuf' -> object with constructor 'FiberNode'
>     --- property 'stateNode' closes the circle

   代码片段如下

>         graph.on('cell:added', ({ cell, index, options }) => { 
>             console.log('📸️新增cell'); 
>             console.log('📸️新增cell-字符串',JSON.stringify(graph.toJSON())); //这里不报错
>         })
>         graph.on('cell:change:attrs', ({ cell, current, previous, options }) => { 
>             console.log('📸️cell attrs变化', current, previous);  
>             console.log('📸️cell attrs变化-字符串',JSON.stringify(graph.toJSON())); // 这里报错
>         })

### 重现链接

https://codesandbox.io/s/antv-x6-issue-forked-pojhsy?file=/src/App.tsx

### 重现步骤

graph.on('cell:change:attrs', ({ cell, current, previous, options }) => { 
    console.log('📸️cell attrs变化', current, previous);  
    console.log('📸️cell attrs变化-字符串',JSON.stringify(graph.toJSON())); // **这里报错**
})

### 预期行为

cell:change:attrs的回调里，能正常执行JSON.stringify(graph.toJSON())

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Microsoft Edge]
- X6 版本: [1.30.2 ]

### 屏幕截图或视频（可选）

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/1875508/159516722-709b0f2a-f249-4468-b145-ccde1896404b.png">

### 补充说明（可选）

这似乎和node-editor有关，因为我按官网的例子实现了一个node-tool button，它也改了attr，并不会报错。

> node-editor代码片段如下
<img width="557" alt="image" src="https://user-images.githubusercontent.com/1875508/159528214-b17c5b21-2d3f-4b84-993c-9595aee554f3.png">

> 节点定义代码片段如下
<img width="410" alt="image" src="https://user-images.githubusercontent.com/1875508/159528489-826e8260-ee77-4525-9ef3-4e396fcd7786.png">

> node tool button实现代码片段如下
<img width="574" alt="image" src="https://user-images.githubusercontent.com/1875508/159528908-21540ef5-096d-46c6-99d5-6a7b0121831b.png">

**Comment by NewByVector** [comment]
可以用 [CodeSanbox](https://codesandbox.io/dashboard) 整理一个可以复现的 demo，这样可以快速定位问题。

**Comment by JamesTing** [comment]
> 可以用 [CodeSanbox](https://codesandbox.io/dashboard) 整理一个可以复现的 demo，这样可以快速定位问题。

这里是复现demo：https://codesandbox.io/s/antv-x6-issue-forked-pojhsy?file=/src/App.tsx

**Comment by NewByVector** [comment]
确实有问题，这里是因为 edge 上的工具传参 e 导致的，e 无法序列化。

**Comment by JamesTing** [comment]
@NewByVector 请问这个问题大概什么时间点修复呢？或者有没有临时解决方案？

**Comment by NewByVector** [comment]
@JamesTing 可以稍微延迟一点设置节点的文本，这样`editor` 工具就会在 `cell:change:attrs` 事件之前被删除：
```ts
cell.addTools([
  {
    name,
    args: {
      event: e,
      setText({ cell, value }){
        setTimeout(() => {
          cell.attr('text/text', value)
        })
      }
    }
  }
]);
```
