### ISSUE TITLE
darge自动布局的图开启history，新增节点或者操作后，使用redo或者undo布局会乱掉

### ISSUE THREAD

**Issue by YanYuanFE** [antvis/X6#1928]
### Describe the bug

darge自动布局的图开启history，新增节点或者操作后，使用redo或者undo布局会乱掉

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

复现步骤：
1、例子：https://x6.antv.vision/zh/examples/showcase/practices#orgchart
2、开启history，
3、增加一个redo和undo的功能按钮，
4、新增节点
5、点击undo，布局就乱了

### Expected behavior

使用redo或者undo，布局正常

### Platform

- OS: macOS
- Browser: Chrome
- Version: latest

**Comment by NewByVector** [comment]
这个有具体的例子吗，我按照你的步骤操作了一下，没有出现布局乱的现象。
