### ISSUE TITLE
导出SVG添加自定义属性

### ISSUE THREAD

**Issue by SunyanLBJ23** [antvis/X6#1935]
### 问题描述

是否可以在导出SVG时给特定得节点添加一些属性，比如单击事件或者data-*

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
首先感谢你的问题，但是不太理解导出的 svg 要加上事件的场景？

**Comment by SunyanLBJ23** [comment]
> 首先感谢你的问题，但是不太理解导出的 svg 要加上事件的场景？

比如说我要生成SVG到其他平台，但是我无法在这个平台上集成x6,所以要在生成的SVG上绑定事件
