### ISSUE TITLE
selecting 功能关闭，transforming 还可以使用

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#1938]
### 问题描述

selecting.enabled = false 
transforming.enabled = true
点击元件会出现以下效果。transform.ts 46行是不是手滑了？
![image](https://user-images.githubusercontent.com/22650893/160091396-7bc10f5d-8a66-4a3b-b6a3-d599cc111e02.png)
![image](https://user-images.githubusercontent.com/22650893/160091447-f6070ac4-49b5-483e-b6ae-88094955d422.png)

### 重现链接

https://codesandbox.io/s/fancy-cloud-bwz3tr?file=/src/app.tsx:343-350

### 重现步骤

1.直接点击元件

### 预期行为

1.点击元件没有任何效果

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chromex]
- X6 版本: [1.31.0 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/22650893/160091396-7bc10f5d-8a66-4a3b-b6a3-d599cc111e02.png)
![image](https://user-images.githubusercontent.com/22650893/160091447-f6070ac4-49b5-483e-b6ae-88094955d422.png)

**Comment by NewByVector** [comment]
transforming 和 selecting 是两个单独的配置，并不会相互影响的。
