### ISSUE TITLE
兄弟，用点心做文档！

### ISSUE THREAD

**Issue by kok-s0s** [antvis/X6#1940]
### Describe the bug

文档向下拉，侧边导航栏直接就遮挡了。
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/46289777/160176741-af5f9491-dc7f-41a1-8bec-1832976324ba.png">

### Your Example Website or App

https://x6.antv.vision/zh/docs/tutorial/getting-started

### Steps to Reproduce the Bug or Issue

直接点击这个 https://x6.antv.vision/zh/docs/tutorial/getting-started 链接查看

### Expected behavior

都挡住了，那些信息是不是就不用看的。用点心，好吗？

### Platform

- OS: macOS
- Browser: Chrome

**Comment by tonywu6** [comment]
Thank you for reporting the issue!

This isn't something we can fix in this repo. This issue appears in our documentation theme provider from upstream. I've made a fix, pending approval

**Comment by kok-s0s** [comment]
> 朋友，你言重了，这个团队已经很用心了。 虽然最开始我发现x6官网Safari加载不出来，也很不爽。 但看到NewByVector提交代码、回复issue的时间点，就感受到他们的努力了。

呃，也是，也希望这个项目做得好些，是最近自己有做思维导图软件的项目，对比了蛮多这类开源库，如果站在我这普通开发者来说，如果文档好些，我会优先选择文档做得不错的，看文档能否把他们所做的事情描述清楚，而不是先优先看项目代码，况且当时我一看居然有这种个人感觉蛮低级的错误，会感觉这不太好。
