### ISSUE TITLE
segments 工具的数据保存与恢复

### ISSUE THREAD

**Issue by rxdrag** [antvis/X6#1949]
### 功能描述

segments工具调整edge时，会产生一些数据，这些数据没法回复，每次关闭程序segments 调整的位置信息就丢失了。

### 期望解决方案

希望提供segments数据存取接口

**Comment by rxdrag** [comment]
![image](https://user-images.githubusercontent.com/18096128/160556744-076e14a1-fc72-4d1b-8601-96e03888fa6f.png)


上面是调好的数据，下面是重新加载丢失后的情况：
![image](https://user-images.githubusercontent.com/18096128/160556846-3a4c55b5-d3a3-48a8-9141-af39f45d5f67.png)

**Comment by rxdrag** [comment]
真的好想解决这个问题，有人管吗？

**Comment by NewByVector** [comment]
edge 数据中的 anchor 信息是不是没有保存起来。如果有 anchor 信息，是会恢复之前状态的。
```ts
{
    "source": {
        "cell": "35ef171b-f941-4fda-a6db-fe4235981c13",
        "anchor": {
            "name": "topLeft",
            "args": {
                "dx": "31%",
                "dy": "50%",
                "rotate": true
            }
        }
    },
    "target": {
        "cell": "bd05f0c6-4ff6-4b38-9e7a-28cae2586aa1",
        "anchor": {
            "name": "topLeft",
            "args": {
                "dx": "63%",
                "dy": "50%",
                "rotate": true
            }
        }
    },
}
```

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。
