### ISSUE TITLE
在火狐和safari的下载图片copyStyles不生效，节点会存在位置偏移

### ISSUE THREAD

**Issue by NINGyv179** [antvis/X6#1951]
### Describe the bug

在火狐和safari的下载图片copyStyles不生效，节点会存在位置偏移

### Your Example Website or App

https://codesandbox.io/s/stylesheet-0y2f1?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

复现链接：https://codesandbox.io/s/stylesheet-0y2f1?file=/src/app.tsx

### Expected behavior

下载样式正确

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
这个已经在最新版本中修复了，请更新到最新版本。
