### ISSUE TITLE
CellView.animate 方法的 complete 执行两次

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#1952]
### 问题描述

![image](https://user-images.githubusercontent.com/22650893/160756761-ca49162a-7d53-4488-82f0-346ca66d145b.png)
官方文档上面说动画结束后执行一次。但是第一次执行动画方法，立即执行了一次，动画结束后又执行一次。之后就正常了。

另外，animate的参数类型是不是有问题？
![image](https://user-images.githubusercontent.com/22650893/160757404-1a1fc5dd-5ab3-45ce-8a7b-0026374f6eb2.png)
![image](https://user-images.githubusercontent.com/22650893/160757438-7a0141e3-56d3-4400-94f5-9b3862b50984.png)

### 重现链接

https://codesandbox.io/s/ecstatic-poitras-ngxw73?file=/src/app.tsx:663-870

### 重现步骤

1.点击测试按钮，complete  方法会执行一次
2.动画结束又会执行一次

### 预期行为

只有动画结束后再执行。

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.31.0 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/22650893/160757296-23c04a4e-b889-4fdf-b5fc-bcece34160c8.png)

**Comment by NewByVector** [comment]
先修复一下类型问题(https://github.com/antvis/X6/pull/1989),触发两次 complete 在不同浏览器下还有不同的行为，继续看下这个问题。
