### ISSUE TITLE
Ceate semi-circle of Node bug

### ISSUE THREAD

**Issue by seejah** [antvis/X6#1956]
### Describe the bug

创建半圆形状的节点不正确，输出的图形是变形的。

### Your Example Website or App

not

## 以下代码，得到不正确的Node图形：
const mynode = new Shape.Path({
  id: "one-node",
  width: 50,
  height: 50,
  attrs: {
    body: {
      fill: '#efdbff',
      stroke: '#9254de',
      refD: 'M 60 60 A 20 20 0 1 1 60 20 Z'
    }
  },
  //path: 'M 60 60 A 20 20 0 1 1 60 20 Z',
})
![image](https://user-images.githubusercontent.com/46164427/160967832-104d8373-c323-46ee-bb14-b75c9a6230f2.png)
上面代码中注释掉的path语句，效果是相同的。

## 除非这么写才显得“正确”：
const mynode = new Shape.Path({
  id: "one-node",
  width: 50,
  height: 50,
  
  attrs: {
    body: {
      d:'M 60 60 A 20 20 0 1 1 60 20 Z',
      fill: '#efdbff',
      stroke: '#9254de',
    },
  },
})
![image](https://user-images.githubusercontent.com/46164427/160968244-b939dbe7-997a-4e71-919a-cf3357b90c01.png)

### Expected behavior

不知是否是我的操作方法不对，还是X6的一个bug？

### Platform

- OS:  Windows
- Browser: Chrome
- Version: X6 1.31.0

**Comment by seejah** [comment]
## I found a solution：
Use Adobe AI，path ’M130.24,12a119,119,0,1,0,119,119A119,119,0,0,0,130.24,12Zm1.26,237.05C66,249.05,13,196.2,13,131S66,13,131.5,13Z’
or，
path:'M564,185C0,185,445,0,445,304,445,0,0,423,564,423,0,423,683,0,683,304,683,0,0,185,564,185ZM0,0V0Z'

![image](https://user-images.githubusercontent.com/46164427/161029394-b28ea38e-cdf5-47da-9c42-6b82baa1d71e.png)

**Comment by NewByVector** [comment]
设置 refD 的时候需要将 path 的 d 缩放到与节点大小一致。
