### ISSUE TITLE
钢笔功能

### ISSUE THREAD

**Issue by Momo23015258** [antvis/X6#1964]
### 功能描述

x6不支持canvas，我想在x6原本的功能上增加自由画线的功能，就很困难，希望能增加钢笔功能或者兼容canvas，内置一些canvas的属性使用方式

### 期望解决方案

期望能开发钢笔功能，或者增加边的绘制功能

**Comment by Qujh97** [comment]
个人认为这个功能不属于该项目的范围。可以新建一个图层覆盖，x6和画笔的数据分开保存，不过缺陷就是要隐藏画笔才能继续对x6图表进行操作。
另外，求好用的画笔工具。目前已知[Painter](https://github.com/yanhaijing/Painter)
