### ISSUE TITLE
为什么拖拽添加的节点会被删除zIndex

### ISSUE THREAD

**Issue by wkd313** [antvis/X6#1967]
### 问题描述

我注册了一些自定义节点并且设置了zIndex，我发现当我想通过Dnd拖拽添加这些节点时，拖拽过程中的代理节点的zIndex还是我设置的值，但最后被添加到画布上的节点的zIndex值却变成了添加到画布中的顺序的值。
我看了Dnd的源码，发现被被拖拽的节点会被移除zIndex，请问这么做的原因是什么。

### 重现链接

https://github.com/antvis/X6/blob/c51043d4682b031a6a41362e78892bfe24a5a589/packages/x6/src/addon/dnd/index.ts#L399

### 重现步骤

1. 拖拽添加节点，输出拖拽过程中代理节点的zIndex
2. 输出最终添加到画布的节点，zIndex的值与代理节点不同

### 预期行为

被拖拽添加到画布的节点zIndex值应与注册该自定义节点时设置的zIndex值相同，但实际上添加到画布的节点zIndex值为添加到画布的顺序。

### 平台

- 操作系统: Windows
- 网页浏览器: Edge
- X6 版本: 1.30.1

**Comment by NewByVector** [comment]
一般场景，节点在 dnd 画布中的 zIndex 和在被放置画布的 zIndex 不一致。如果要实现你的功能，可以在节点被放置到画布后修改 zIndex：
```ts
graph.on('node:added', ({ node }) => {
  node.setZIndex(x)
})
```
