### ISSUE TITLE
使用装饰器修饰实列属性时，由于x6进行深拷贝导致属性丢失

### ISSUE THREAD

**Issue by lhbvita** [antvis/X6#1968]
### 问题描述

给自定义节点传递数据时，该数据对象中有一个属性使用了装饰器修饰，将该实列化的对象传递到Node，创建node时，对该实列化的对象进行了深拷贝，导致装饰器修饰的属性值丢失，造成功能不可用。

### 重现链接

无

### 重现步骤

![image](https://user-images.githubusercontent.com/29444839/161377021-70a67e68-d3dc-421f-9f67-6fe7d265b62e.png)
![image](https://user-images.githubusercontent.com/29444839/161377098-83dd8f7a-6f05-490a-b869-3571791afbed.png)
![image](https://user-images.githubusercontent.com/29444839/161377129-57a38074-b52c-4f58-9f51-f69905cdaaba.png)
![image](https://user-images.githubusercontent.com/29444839/161377137-1c4ff5b2-f3a7-401a-904c-de09af9e0036.png)
![image](https://user-images.githubusercontent.com/29444839/161377244-db6ba14b-f053-4cba-8903-f48e161dc4af.png)
![image](https://user-images.githubusercontent.com/29444839/161377247-58569ec1-78d0-46d5-add9-f30795e90a21.png)
原因就是深拷贝了原有的实列对象，新对象丢失了metaData

### 预期行为

功能正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
节点的 data 里面只支持 plainObject.
