### ISSUE TITLE
API文档中SelectionOptions缺少rubberNode和rubberEdge说明

### ISSUE THREAD

**Issue by georgezhu08** [antvis/X6#1970]
### 问题描述

在API的文档中，关于SelectionOptions是说明中缺失了rubberNode和rubberEdge

### 重现链接

https://x6.antv.vision/zh/docs/api/graph/selecting

### 重现步骤

https://x6.antv.vision/zh/docs/api/graph/selecting

### 预期行为

补充文档

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 1.31.0

**Comment by NewByVector** [comment]
selecting 正在重构，这两个配置是实验性质的，下个版本不一定存在，先不在文档透出。
