### ISSUE TITLE
连接桩问题

### ISSUE THREAD

**Issue by LMLGM** [antvis/X6#1979]
### 问题描述

当连接桩上已有一条边后，想从这个链接桩上再生成一条边时，连接桩很难被选中，是哪里的配置问题呢
![image](https://user-images.githubusercontent.com/58587791/161947875-964c334d-a572-4e08-9fd7-e14f37bf8032.png)

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

太难选中，使用感差

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
因为你的边在连接桩之上，你选中的很可能是边了，可以把边的 zIndex 设置低一点。

**Comment by LMLGM** [comment]
好的，谢谢
