### ISSUE TITLE
vue2使用x6-vue-shape,1.3.1版本提示createApp（）is not funciton

### ISSUE THREAD

**Issue by social-uni** [antvis/X6#1984]
### Describe the bug

x6-vue-shape,1.1.6版本使用正常
x6-vue-shape,1.3.1引入了vue-demi，导致此错误，可能与vue-demi的这个issues有关 [https://github.com/vueuse/vue-demi/issues/136](https://github.com/vueuse/vue-demi/issues/136) https://github.com/vueuse/vue-demi/issues/136

### Your Example Website or App

https://github.com/vueuse/vue-demi/issues/136

### Steps to Reproduce the Bug or Issue

https://github.com/vueuse/vue-demi/issues/136

### Expected behavior

not error

### Platform

vue2

**Comment by NewByVector** [comment]
因为没有提供可以复现的 demo，这个 issue 先关闭了，如果还有问题，请重新提一个新的 issue。
