### ISSUE TITLE
批量添加图形

### ISSUE THREAD

**Issue by MrMengJ** [antvis/X6#1996]
### 功能描述

1. 现在复制了多个图形，粘贴的时候只能遍历调用 `addNode` 去添加图形，此时撤销操作也是对 `addNode` 操作的撤销，无法一次性撤销刚才做的 **粘贴** 动作。比如：一次性复制粘贴了3个图形，那么撤销操作就得做三次才能回到初始状态
2. 

### 期望解决方案

1. 新增批量添加的api，`addNodes`,`addEdges` 等等
2. 撤销操作可以撤销批量添加行为

**Comment by NewByVector** [comment]
已经有 `addNodes、addEdges` 的 api，如果想能一次性撤销，可以将多次操作动作放在一个事务中，参考[batchupdate](https://x6.antv.vision/zh/docs/api/graph/graph/#batchupdate)。
