### ISSUE TITLE
拖拽连接边时，鼠标抬起，如何让连接边一直黏着光标，后在点击目标连接桩，完成连接？

### ISSUE THREAD

**Issue by zhanghanguang-git** [antvis/X6#2010]
### 问题描述

问题：从源连接桩按下鼠标左键拖拽出一条边，未拖拽至目标连接桩时鼠标抬起，边就会消失；如何实现未拖拽至目标连接桩时鼠标抬起，边不会消失，连接的边一直黏着光标，在鼠标移动至目标连接桩并点击目标连接桩后完成连接。

使用场景：当我们的要画的图元很多，一个屏幕展示不全，需要连接的连个图元之间的距离较远，想一边拉出连接边，一边右键拖拽画布，直至看到目标连接桩，后完成连接。

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.1 ... ]

**Comment by NewByVector** [comment]
拖拽边的时候画布会自动滚动的，这个不满足需求吗？

**Comment by zhanghanguang-git** [comment]
> 拖拽边的时候画布会自动滚动的，这个不满感谢

**Comment by zhanghanguang-git** [comment]
感谢您的回复，配置画板成可滚动，拖拽边的时候画布会自动滚动可以解决超屏连线问题，不过在不允许画板滚动的情况下就就实现不了了。

**Comment by NewByVector** [comment]
@zhanghanguang-git  不允许画布滚动情况下节点不会超出画布范围吧。

**Comment by zhanghanguang-git** [comment]
> @zhanghanguang-git 不允许画布滚动情况下节点不会超出画布范围吧。

是的，没滚动情况下不会超出画布，不过由于设置画布的尺寸大于屏幕，拖动画布时，很多图元就会超出屏幕并被遮挡（并不超出画布），这时候如果不设置置滚动或缩小画布就无法进行连线，但这两种方式都不太方便。因此想出的解决想法就是拖拽画布的同时可以保持连线。

**Comment by jayce712** [comment]
当前想实现一个类似的功能点:
1.点击(click)链接桩后出现一条边；
2.边需要跟随鼠标移动；
3.点击画布空白地方，连线失败；
4.点击节点的链接桩，校验是否连线合法；

大佬们有没有好的实现思路？

**Comment by xueshixiang** [comment]
我也需要这个功能类似G6的点击连线

当前想实现一个类似的功能点:
1.点击(click)链接桩后出现一条边；
2.边需要跟随鼠标移动；
3.点击画布空白地方，连线失败；
4.点击节点的链接桩，校验是否连线合法；

**Comment by NewByVector** [comment]
这种交互方式和设计同学沟通后，不符合图编辑应用的规范，不考虑这种方案了。
