### ISSUE TITLE
vue项目打包后新建节点报错

### ISSUE THREAD

**Issue by baguosiji** [antvis/X6#2014]
### 问题描述

本地调试没有问题、build后新建节点时报错Uncaught (in promise) TypeError: e is not a function。

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: [1.31.3]

**Comment by NewByVector** [comment]
能否提供一个可以复现 demo，这样会加快问题定位。

**Comment by mlsjla** [comment]
view.js?1718:58 Uncaught TypeError: Object(...) is not a function
    at VueShapeView.renderVueComponent (view.js?1718:58:1)
    at eval (view.js?1718:25:1)
    at flushTask (index.js?56ac:25:1)
    at eval (index.js?56ac:11:1)
    at Array.forEach (<anonymous>)
    at MessagePort.cb (index.js?56ac:11:1)

**Comment by mlsjla** [comment]
疑似与vue版本切换有关。  
这边可能识别到的vue版本是3.x  而实际上是用的2.x

**Comment by baguosiji** [comment]
已经解决了 问题出在了 lodash ，我们的项目中用了lodash 按需引入。     但是vue的报错指向了jquery。

**Comment by one-superman** [comment]
> 已经解决了 问题出在了 lodash ，我们的项目中使用了 lodash 按需导入。 但是 vue 的报错指向了 jquery。
请问是怎么解决的

**Comment by one-superman** [comment]
> 已经解决了 问题出在了 lodash ，我们的项目中使用了 lodash 按需导入。 但是 vue 的报错指向了 jquery。

请问是怎么解决的呢

**Comment by baguosiji** [comment]
@one-superman vue-config.js里面lodash按需引入去掉
