### ISSUE TITLE
自定义edge，通过prop设置label属性，不触发cell:click事件

### ISSUE THREAD

**Issue by xyhxyw** [antvis/X6#2016]
### Describe the bug

在`selection:changed`事件中，通过`prop`方法来修改边的`label`的属性，不触发`cell:click`事件。

### Your Example Website or App

https://codesandbox.io/s/compassionate-resonance-4khcr0?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1、开启`selecting`，并注册自定义边`custom-edge`，同时配置边的`defaultLabell`属性。
2、监听`cell:click`和`selection:changed`事件。单击`label`，当我们在在`selection:changed`事件中，通过`prop`方法来修改边的`label`的属性时，此时没有触发`cell:click`事件。

```js
cell.prop({
	attrs: {
		line: {
			stroke: "red",
		},
	},
	defaultLabel: {
		attrs: {
			body: {
				stroke: "red",
			},
		},
	},
});
```
3、当我们在代码中注释掉`defaultLabel`的配置时，`cell:click`事件正常触发。如下所示：
```js
cell.prop({
	attrs: {
		line: {
			stroke: "red",
		},
	}
});
```
或者，不监听`selection:changed`事件，`cell:click`事件也能正常触发。

### Expected behavior

通过`prop`设置`label`属性，依然可以正常触发`cell:click`事件。

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [ 100.0.4896.88]

**Comment by NewByVector** [comment]
@xyhxyw 这个现象的原因：`selection:changed` 里面修改了边的 label，会导致边重新渲染，重新渲染后已经无法捕获到 `click` 事件
解决方案：将 `click` 事件修改成 `mousedown` 事件，在 `selection:changed` 之前捕获到鼠标按下事件。
