### ISSUE TITLE
Property 'getLabel' does not exist on type 'Node<Properties>'

### ISSUE THREAD

**Issue by eensander** [antvis/X6#2020]
### 问题描述 (problem description)

First and foremost: obviously and unfortunately I don't speak Chinese, so hopefully I'm describing my problem as expected.

When executing `graph.getNodes()` on a graph, typescript interprets the type as `Node<Node<Properties extends Node.Properties = Node.Properties>.Properties>[]`
According to typescript, on this property I can't use `getLabel()`.

However, when I cast the nodes as `Base` (from "@antv/x6/lib/shape/base"), I _can_ use .getLabel() and more functions. For reference, please look in my example repository at [src/HelloWorld.vue:29](https://github.com/eensander/antv-issue-getlabel-example/blob/master/src/components/HelloWorld.vue#L29):
```ts
import { Base as BaseShape } from "@antv/x6/lib/shape/base";
// ...
for(const node of graph.value?.getNodes()) {
  // Property 'getLabel' does not exist on type 'Node<Properties>'.
  console.log(node.getLabel())

  // works:
  console.log((node as BaseShape).getLabel())
}
```

#### Questions
1. What is the recommended method of getting a label from a node?
2. Should I cast Node objects to Base (in shape)
3. If you think this problem is not the cause of X6, please let me know what you think the root of the problem could be.

#### Notes 
- I forked my example repository to codesandbox, but for some reason that is throwing different errors than in my local environment.
- In my real project, I am getting the error in the compilation result. In the test project, I am only getting the error in VSCode (volar).

#### Extra info

Example repository: https://github.com/eensander/antv-issue-getlabel-example
File and line: `src/components/HelloWorld.vue:29`

### 重现链接 (reproduce link)

https://codesandbox.io/s/youthful-sea-1jpocu?file=/src/components/HelloWorld.vue:753-761

### 重现步骤 (steps to reproduce)

1. Clone repository
2. Checkout with VSCode or compile
3. See error at src/HelloWorld.vue:29

### 预期行为 (expected behavior)

To be able to access the getLabel() method on Node.Properties typed objects, or in another way get the label of a Node.

### 平台 (environment)

- 操作系统 / OS: [Linux - Ubuntu 20.04.4]
- 网页浏览器 / Browser: Firefox (irrelevant)
- X6 版本 / X6 Version: [1.31.3 ]

### 屏幕截图或视频（可选）(screenshot or video)

Screenshot of VSCode in example repository (https://github.com/eensander/antv-issue-getlabel-example)
![image](https://user-images.githubusercontent.com/50321538/163822523-09257f61-dbfd-4209-bf29-3c62e2306413.png)

Compilation error in my real project:
```
ERROR in src/components/graph/transformer.ts:81:35
TS2339: Property 'getLabel' does not exist on type 'Node<Properties>'.
    79 |                 id: loc_node.id,
    80 |                 // content: (loc_node as ShapeBase).getLabel() ?? '',
  > 81 |                 content: loc_node.getLabel() ?? '',
       |                                   ^^^^^^^^
    82 |                 node_type: loc_node.getData()?.node_type ?? 'default',
    83 |                 appearance: {
    84 |                     
```

**Comment by NewByVector** [comment]
True, the getLabel method is not in Node, but in Base, the correct way to get a label is：
```ts
node.attr('text/text') 
```
![image](https://user-images.githubusercontent.com/20186737/164359900-d67bd804-ceea-42f0-adb9-3c6c9321977e.png)

**Comment by eensander** [comment]
Thanks, I will use this method to get the label.
