### ISSUE TITLE
群组：折叠/展开父节点示例中graph无法序列化

### ISSUE THREAD

**Issue by johnnylc** [antvis/X6#2026]
### Describe the bug

在官网“群组：折叠/展开父节点”示例中，graph无法调用graph.toJSON()序列化
执行序列化报错：
    Unable to serialize node missing "shape" prop, check the node "Group"

### Your Example Website or App

https://antv-x6.gitee.io/zh/examples/node/group#collapsable

### Steps to Reproduce the Bug or Issue

1. 打开示例地址：
    https://antv-x6.gitee.io/zh/examples/node/group#collapsable
2. 在示例代码最末添加：
    console.log('data', graph.toJSON())
3. 运行示例报错：
    Unable to serialize node missing "shape" prop, check the node "Group"

### Expected behavior

可正常序列化graph

### Screenshots or Videos

<img width="983" alt="image" src="https://user-images.githubusercontent.com/12717523/164132691-d0960be6-ca98-4bc0-8e9b-bf51403f2efb.png">

### Platform

- OS: macOS, Windows
- Browser: Chrome
- Version: 99.0.4844.84

**Comment by yaojin2070** [comment]
你是如何解决的?

**Comment by oyal** [comment]
> 你是如何解决的?

加上这个 `const group = new Group({ shape: 'rect', ...})`
