### ISSUE TITLE
使用angular 组件定义自定义节点，在组件内部使用antd 发现不生效

### ISSUE THREAD

**Issue by mcWang66** [antvis/X6#2028]
### Describe the bug

使用angular 组件定义自定义节点，在组件内部使用antd 发现不生效
![FYAA$7ZRYF@OS QV`7T7 1M](https://user-images.githubusercontent.com/17886159/164154764-56f85d17-b43d-4e8d-9633-fb7faf70e338.png)
![ZC} NG)$}6$}48{PBH@NVRC](https://user-images.githubusercontent.com/17886159/164154815-0f0b2d15-d2c9-431b-bde2-74bee260ec40.png)

### Your Example Website or App

web

### Steps to Reproduce the Bug or Issue

使用angular 组件定义自定义节点，在组件内部使用antd 发现不生效，是需要什么配置吗

### Expected behavior

使用angular 组件定义自定义节点，在组件内部使用antd 发现不生效，是需要什么配置吗

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
chrome

**Comment by mcWang66** [comment]
已解决

**Comment by mcWang66** [comment]
已解决

**Comment by NewByVector** [comment]
@mcWang66 解决经验可以分享下么
