### ISSUE TITLE
连接桩上的边支持平均分布吗？怎么实现呢？

### ISSUE THREAD

**Issue by gpxCode** [antvis/X6#2029]
### 问题描述

 connectionPoint: 'anchor',
'boundary' 默认值，与链接图形的边框的交点。
'bbox' 与链接元素的包围盒的交点。
'rect' 与链接元素的旋转后的矩形区域的交点。
'anchor' 使用锚点作为连接点。
        sourceAnchor: {
            name: 'bottom',
            args: {
                dx: 5,
                dy: -5,
            },
        },
        targetAnchor: {
            name: 'bottom',
            args: {
                dx: -5,
                dy: -5,
            },
        },
已实现功能，但是边的连接点都在连接桩的中心：
![image](https://user-images.githubusercontent.com/45168755/164160712-eddddaea-00bd-4fd9-9980-475dfbc82ebc.png)
要实现的功能如下：
![image](https://user-images.githubusercontent.com/45168755/164161001-75b92c9c-76cb-4f9e-98be-e73ad58758b1.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以使用 [nodeAnchor](https://x6.antv.vision/zh/docs/api/registry/node-anchor/#gatsby-focus-wrapper) 来实现连接点偏移。

**Comment by cuidong626** [comment]
你要的是这种效果么？图形两侧的连接桩都是均匀分布的
![image](https://user-images.githubusercontent.com/22650893/166627985-b2256162-a8fc-44b3-a8e3-70bd32179fd1.png)
![image](https://user-images.githubusercontent.com/22650893/166628110-704eed23-4d94-46a1-a2bf-245ebfcab56a.png)

**Comment by GPXNB** [comment]
> 你要的是这种效果么？图形两侧的连接桩都是均匀分布的 ![image](https://user-images.githubusercontent.com/22650893/166627985-b2256162-a8fc-44b3-a8e3-70bd32179fd1.png) ![image](https://user-images.githubusercontent.com/22650893/166628110-704eed23-4d94-46a1-a2bf-245ebfcab56a.png)

是的 你这边是怎么实现的呢？
