### ISSUE TITLE
EdgeAnchor 中的 'orth'  参数 'fallbackAt' 不工作

### ISSUE THREAD

**Issue by lyon-liao** [antvis/X6#2030]
### Describe the bug

在使用orth anchor 时，设置fallbackAt 不符合预期。
```
line.setTarget(line1, {anchor: {name: 'orth',  args: {fallbackAt: 50}}})
```

### Your Example Website or App

https://codesandbox.io/s/jovial-framework-gs70lt?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

View the line to get the demo

### Expected behavior

希望符合文档描述：

|fallbackAt | number \| string | 否 | undefined | 当没有正交点时，使用 fallbackAt 指定的点作为锚点。当 fallbackAt 为百分比字符串时，表示锚点位于距离起点多少比例位置处。当 fallbackAt 为数字时，表示锚点位于距离起点多少长度位置处。
-- | -- | -- | -- | --

### Platform

- OS:  Windows
- Browser: Chrome

**Comment by NewByVector** [comment]
这个配置是没有正交点的时候才会使用，你的案例并不会出现这种现象。
