### ISSUE TITLE
使用 SVG 自定义图标时，节点不能正常缩放

### ISSUE THREAD

**Issue by wtjperi2003** [antvis/X6#2033]
### 问题描述

使用官方示例：https://x6.antv.vision/zh/examples/node/custom-node#custom-icon-with-svg  ，定义出来的svg图标，在画布开启resizing,也就是允许节点缩放的配置后。该图标节点不能缩放

### 重现链接

https://x6.antv.vision/zh/examples/node/custom-node#custom-icon-with-svg 

### 重现步骤

1.https://x6.antv.vision/zh/examples/node/custom-node#custom-icon-with-svg 
2.代码里，graph配置项添加resizing:true
![微信截图_20220421152625](https://user-images.githubusercontent.com/10322892/164400210-294d0b2a-241e-4abe-9d24-059f8f610852.png)

3.自动刷新后，左侧图标选中，鼠标点右下角进行缩放操作

### 预期行为

能看到图标随着选框进行缩放

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by georgezhu08** [comment]
根据我的经验，只有使用相对参数才能自动缩放。也就是说，需要使用refX，refY，refWidth，refHeight，refD等才能做到你希望的自动缩放。

**Comment by Hubmayun123** [comment]
@wtjperi2003 请问这个问题你解决了吗,可以分享一下吗

**Comment by NewByVector** [comment]
@georgezhu08 说的很对，如果图形支持缩放，需要使用 refXXX 属性。

**Comment by wtjperi2003** [comment]
> 根据我的经验，只有使用相对参数才能自动缩放。也就是说，需要使用refX，refY，refWidth，refHeight，refD等才能做到你希望的自动缩放。

要看图标的类型，如果是单笔的图标，就能正常缩放

**Comment by chengup-git** [comment]
> @georgezhu08 说的很对，如果图形支持缩放
需要使用 refXXX 属性。
attrs设置refXXX属性无效
![1](https://user-images.githubusercontent.com/57739679/186370612-30507679-eee5-4d0c-a0d8-cbf728a71de9.png)

**Comment by chengup-git** [comment]
> > 根据我的经验，只有使用相对参数才能自动缩放。也就是说，需要使用refX，refY，refWidth，refHeight，refD等才能做到你希望的自动缩放。
> 
> 要看图标的类型，如果是单笔的图标，就能正常缩放

path类型的有方法设置成自动缩放吗？

**Comment by Noah-Ywh** [comment]
> 



> > > 根据我的经验，只有使用相对参数才能自动缩放。也就是说，需要使用refX，refY，refWidth，refHeight，refD等才能做到你希望的自动缩放。
> > 
> > 
> > 要看图标的类型，如果是单笔的图标，就能正常缩放
> 
> path类型的有方法设置成自动缩放吗？

使用 `refD`

```ts
{
  markup: [
    {
      tagName: 'path',
      selector: 'path',
    },
  ],
  attrs: {
    path: {
      refD: 'M 0 36 L 0 0 L 66 0 L 66 36 Q 50 26,33 36 Q 13 46,0 36',
    },
  },
}
```

**Comment by wh356667852** [comment]
> > 根据我的经验，只有使用相对参数才能自动缩放。也就是说，需要使用refX，refY，refWidth，refHeight，refD等才能做到你希望的自动缩放。
> 
> 要看图标的类型，如果是单笔的图标，就能正常缩放

我也遇到了这个问题，请问你解决了吗？

**Comment by wtjperi2003** [comment]
> > > 根据我的经验，只有使用相对参数才能自动缩放。也就是说，需要使用refX，refY，refWidth，refHeight，refD等才能做到你希望的自动缩放。
> > 
> > 
> > 要看图标的类型，如果是单笔的图标，就能正常缩放
> 
> 我也遇到了这个问题，请问你解决了吗？

最终是使用html类型节点，里面钳svg图标，图标高宽设成100%。这样就能适应所有了
