### ISSUE TITLE
根据锚点id获取该锚点连接的节点的api有吗 

### ISSUE THREAD

**Issue by LZCaaT** [antvis/X6#2034]
### 问题描述

想实现一个source port只能连接一个target port的功能,
<img width="491" alt="image" src="https://user-images.githubusercontent.com/28329423/164412463-feabeba0-2063-4472-b2c9-4554c6713b4b.png">

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
希望这个 [demo](https://codesandbox.io/s/xian-zhi-lian-jie-bian-shu-liang-ytk2rd) 能帮到你。

**Comment by LZCaaT** [comment]
> 希望这个 [demo](https://codesandbox.io/s/xian-zhi-lian-jie-bian-shu-liang-ytk2rd) 能帮到你。

感谢，已解决
