### ISSUE TITLE
使用`jumpover` connector, Edge 和Edge 的连接点会显示错误

### ISSUE THREAD

**Issue by lyon-liao** [antvis/X6#2035]
### Describe the bug

使用`jumpover` connector, Edge 和Edge 的连接点会显示错误

![image](https://user-images.githubusercontent.com/3927282/164415738-d0e5f00a-2b04-486a-aa49-dd3b87442808.png)

**Comment by NewByVector** [comment]
如果连接目标是连线的话，不能使用 `jumpover`.
