### ISSUE TITLE
一次选中多个节点时，node:selected 和 cell:selected 事件触发多次

### ISSUE THREAD

**Issue by Trojanpa** [antvis/X6#2037]
### 问题描述

一次性选中多个节点时，node:selected 和 cell:selected 事件都触发多次

### 重现链接

https://codesandbox.io/s/jie-dian-duo-xuan-shi-selectedshi-jian-chu-fa-duo-ci-forked-fkyh3s

### 重现步骤

1.进入页面
2.一次选中多个节点
3.查看控制台打印

### 预期行为

期望一次选中行为只触发一次选中事件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.31.4]

### 屏幕截图或视频（可选）

![Honeycam 2022-04-22 10-19-45](https://user-images.githubusercontent.com/42988574/164584009-35f02546-10e4-4e17-9bc2-c4d710b5977a.gif)

**Comment by Hfutsora** [comment]
看起来，需求与这个类似 #1738

**Comment by georgezhu08** [comment]
我看目前这个事件是针对单个节点选中后触发，而Node是从Cell继承的，于是就会先触发Cell选中事件，然后再触发Node选中事件。所以要么在Cell中处理，要么在Node中处理，一般不同时在两种事件中处理同一种节点。

也许可以考虑增加一个nodes:selected事件，专门处理通过框选选中的多个节点。

**Comment by NewByVector** [comment]
这个触发多次是正常的，你的场景是什么。

**Comment by Trojanpa** [comment]
> 这个触发多次是正常的，你的场景是什么。

我的场景是：当选中节点时，如果是单选就执行单选的业务逻辑，如果是多选就执行多选的业务逻辑。但现在多选时，选中方法触发多次，所以也导致我的多选逻辑也触发多次。

**Comment by NewByVector** [comment]
@Trojanpa 如果是要区分多选和单选的话，可以使用 [selection:changed](https://x6.antv.vision/zh/docs/tutorial/basic/selection#selectionchanged) 事件。
