### ISSUE TITLE
TypeError nodeSize is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by J-maxwell** [antvis/X6#2039]
### Describe the bug

TypeError
nodeSize is not a function or its return value is not iterable

### Your Example Website or App

https://codesandbox.io/s/x6w0z3?file=/index.ts

### Steps to Reproduce the Bug or Issue

直接点开就看到了

### Expected behavior

显示正常，不报错

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
使用 `@antv/layout 0.1.18` 版本就好了。
