### ISSUE TITLE
Reactshape 不可以单独使用布局吗？？

### ISSUE THREAD

**Issue by Richard-vip** [antvis/X6#2041]
### 问题描述

创建自定义的 reactshap 组件 ，又单独使用的布局，计算出的 x y 为NaN ，或者说 自定义的 reactShape 如何使用布局呢？？

### 重现链接

https://codesandbox.io/s/elated-villani-hbjy1u?file=/src/App.tsx

### 重现步骤

1. 进入 CodeSandbox
2. 点开 console

![image](https://user-images.githubusercontent.com/102498666/164646843-cc5c0c13-e696-42e7-83ba-64ce61e1471a.png)

### 预期行为

期望  使用ReactShape 自定义节点，并且使用布局

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
布局所需要的数据格式参考[文档](https://x6.antv.vision/zh/docs/tutorial/advanced/layout#%E5%B8%83%E5%B1%80%E6%B5%81%E7%A8%8B)

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。
