### ISSUE TITLE
画布滚动留白过多

### ISSUE THREAD

**Issue by lhbvita** [antvis/X6#2048]
### 问题描述

![image](https://user-images.githubusercontent.com/29444839/164954615-fb3f69f6-a6b1-477e-a59e-c2d6865dd0a2.png)
开启画布滚动时，上下的留白过多，如何设置从节点开始滚动，即不需要多余的空白，比如只有少量节点时，即使开启了滚动也不会出现滚动条；另外如何设置不出现横向滚动？

### 重现链接

https://x6.antv.vision/zh/docs/api/graph/scroller

### 重现步骤

![Uploading image.png…]()

### 预期行为

更精细化控制滚动行为

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 补充说明（可选）

类似问题   (https://github.com/antvis/X6/issues/1249)

**Comment by Hfutsora** [comment]
可以使用 [graph.zoomToFit](https://x6.antv.vision/zh/docs/api/graph/transform#zoomtofit)

**Comment by lhbvita** [comment]
@Hfutsora 

> 可以使用 [graph.zoomToFit](https://x6.antv.vision/zh/docs/api/graph/transform#zoomtofit)

![image](https://user-images.githubusercontent.com/29444839/165015904-593bcf13-612c-4eb5-a2e8-af7552f3b0ef.png)
不行吧，还没有解决宽高非常大的问题

**Comment by xfwinne** [comment]
可以添加padding属性，如 padding:20

**Comment by xfwinne** [comment]
可以配置padding属性：


scroller: {
            // width: 500,
            enabled: true,
            pannable: true,
            // 设置画布四周的 padding 边距。默认根据 minVisibleWidth 和 minVisibleHeight 自动计算得到，保证画布滚动时，在宽度和高度方向至少有 minVisibleWidth 和 minVisibleHeight 大小的画布可见。
            padding: 20 // 设置之后会有top 、left值（设置后不会离谱的默认扩大左右两边滚动范围）
          }

**Comment by Ivan-hl** [comment]
hi 你的问题解决了吗

**Comment by xfwinne** [comment]
XF：收到来信啦~~

**Comment by Ivan-hl** [comment]
我在x6的dagdemo中发现不会出现横纵向滚动条， 自己写的却有， 开启padding后确实会好一些， 但还是会出现滚动条， 如何处理呢？我并没有在dag-demo中发现任何关于滚动条的处理， 难道是跟画布上的节点有关吗？

**Comment by NewByVector** [comment]
@lhbvita scroller 模式肯定有滚动条，如果不想用滚动条的话，可以使用 `panning` 模式。

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。
