### ISSUE TITLE
添加网格时报错

### ISSUE THREAD

**Issue by Kang127** [antvis/X6#205]
代码：
            graph = new Graph({
                container: canvasDom,
                grid: {
                    enabled: true,    // 是否启用网格系统
                    visible: true,    // 是否渲染网格背景
                    size: 10,         // 网格大小
                    minSize: 4,       // 最小网格大小
                    step: 4,          // 只对 line 类型网格有效，用于指定双线网格的间隔
                    type: 'line',     // 'line' | 'dot'
                    color: '#e0e0e0', // 网格颜色
                },
            })
错误信息：Grid with name 'line' does not exist.

-

**Comment by bubkoo** [comment]
网格配置有一些调整，参考文档 https://x6.antv.vision/zh/docs/tutorial/basic/grid 和下面代码
```ts
const graph = new Graph({
  grid: {
    size: 10,
    visible: true,
    type: 'doubleMesh',
    args: [
      { 
        color: '#a0a0a0', // 主网格线颜色
        thickness: 1,     // 主网格线宽度
      },
      { 
        color: '#a0a0a0', // 次网格线颜色
        thickness: 1,     // 次网格线宽度
        factor: 4,        // 主次网格线间隔
      },
    ],
  },
})
```
