### ISSUE TITLE
新建群组，群组内节点不会随群组移动

### ISSUE THREAD

**Issue by LMLGM** [antvis/X6#2054]
### 问题描述

新建群组，群组内节点不会随群组移动
![image](https://user-images.githubusercontent.com/58587791/165034055-e7638460-fba9-4e77-a957-5fec978760c4.png)
![image](https://user-images.githubusercontent.com/58587791/165034113-007aad58-d2d8-4350-b6e6-1b4e962d8844.png)

### 重现链接

无

### 重现步骤

无

### 预期行为

移动父节点时子节点也会跟着移动

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
有可以复现的 demo 吗？
