### ISSUE TITLE
期望E-R图可以增加折叠和嵌套功能

### ISSUE THREAD

**Issue by menghaoG** [antvis/X6#2055]
### 功能描述

E-R图列表右上角有折叠按钮；E-R图里面还可以嵌套E-R图

### 期望解决方案

期望E-R图列表可以像下拉框一样折叠内容；E-R图中嵌套E-R图，可以通过这种方式把E-R图归类到一张表中

**Comment by NewByVector** [comment]
ER 图嵌套是什么样的效果，有设计图吗？

**Comment by lloydzhou** [comment]
@menghaoG 
你或许可以关注一下[展开折叠父节点](https://x6.antv.vision/en/docs/tutorial/basic/group#%E5%B1%95%E5%BC%80%E6%8A%98%E5%8F%A0%E7%88%B6%E8%8A%82%E7%82%B9)
