### ISSUE TITLE
增加框选功能导致 blank:click 事件不执行

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#2059]
### 问题描述

增加框选功能导致 blank:click 事件不执行

### 重现链接

https://codesandbox.io/s/empty-sun-il9ej1

### 重现步骤

官方demo，点击会变色。修改代码，增加框选，事件就失效了
![image](https://user-images.githubusercontent.com/22650893/165245098-e98eb5ed-7300-4e38-ae61-5b25b254f202.png)
![image](https://user-images.githubusercontent.com/22650893/165245257-e4fb54cf-48d7-471b-9fd0-bb6727b4b29c.png)

### 预期行为

1.事件执行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.31.4 ... ]

**Comment by NewByVector** [comment]
我用你的链接，是好的呀，还需要什么步骤吗？

**Comment by cuidong626** [comment]
@NewByVector  你多试试几次，这个是偶发现象。我也是后来才发现的，很郁闷

**Comment by lloydzhou** [comment]
可能是增加`selecting`支持之后，点击空白画布的过程中鼠标有轻微移动，才导致`blank:click`事件没有触发

**Comment by NewByVector** [comment]
@lloydzhou 如果是这样的话，可以增加 `moveThreshold` 配置来解决。

**Comment by liu-leizhi** [comment]
@NewByVector 现在还是有这个问题，原因是单击就出了框选，框选很小，但还是导致blank:click事件不触发，上面那个重现的链接就可以复现。

**Comment by liu-leizhi** [comment]
https://user-images.githubusercontent.com/45058642/185280340-1a34dbcc-c57b-4957-9f21-e216832e1d0a.mp4

**Comment by liu-leizhi** [comment]
现在又好了，不知道啥原因，时好时坏😥

**Comment by liu-leizhi** [comment]
看上面的视频，我鼠标也没动，有时候怎么点都不触发这个事件。

**Comment by liu-leizhi** [comment]
感觉像是有缓存，重新打开一个无痕浏览器就好了，原浏览器一旦出现这个问题，刷新也没用。

**Comment by long-t-t** [comment]
同样出现此情况，开启框选后，无法监听到blank:click事件
