### ISSUE TITLE
怎么将ClientX和ClientY的坐标转化为画布坐标，G6提供了转换方法，X6没找到。

### ISSUE THREAD

**Issue by Kang127** [antvis/X6#206]
还有一个问题，我全部的节点都使用shape: 'react-shape'类型，是不是页面会卡顿，刚才在页面渲染了9个节点，页面打开之前有明显等待，这个有没有提高性能的办法。

**Comment by bubkoo** [comment]
1. `graph.clientToLocalPoint(x, y)`
2. 我们使用的时候没有明显的性能问题，如果你觉得确实很卡，你可以给我一个 codesandbox demo 链接，我去看看是什么原因。
