### ISSUE TITLE
node:selected 在移动端事件无法触发

### ISSUE THREAD

**Issue by viewweiwu** [antvis/X6#2060]
### Describe the bug

graph.on('node:selected', () => alert(1))
在移动端并不会有效果

### Your Example Website or App

https://stackblitz.com/edit/typescript-zelme5?file=index.ts

### Steps to Reproduce the Bug or Issue

https://stackblitz.com/edit/typescript-zelme5?file=index.ts

### Expected behavior

希望能够支持移动端事件触发

### Platform

- OS: macOs
- Browser: Chrome
- Version: 100

**Comment by wulinsheng123** [comment]
@NewByVector 这个有什么好的方案吗
我这边移动端需要使用

**Comment by NewByVector** [comment]
在移动端验证， node:selected 是可以触发的，请提供一个可以复现的 demo 重新提一个 issue。
