### ISSUE TITLE
X6 注册Vue组件渲染时，提供更完善的功能

### ISSUE THREAD

**Issue by gavinwyf** [antvis/X6#2064]
### 功能描述

1. Vue组件 运行时编译性能问题
2. 只有getVueComponent钩子，扩展性太差，无法注入createApp全局配置，也无法获取到app实例。
3. 规范注册节点方式， Graph.registerNode注册Vue component，addNode就会报错。Graph.registerVueComponent 目前没有问题。
![image](https://user-images.githubusercontent.com/11659339/165435467-031f3e1f-7ab5-4388-85c8-84e824d31297.png)
4. 由于不能注入全局配置，使用第三方库或全局扩展库，类似element3，需要单独手动引入组件，找不到全局变量会报错。“[Vue warn]: Property "$ELEMENT" was accessed during render but is not defined on instance. ”

### 期望解决方案

1. 提供灵活的 Vue组件接入方式
2. 提供更多的hook，或者可扩展模式。方便用户做更细粒度的操作和扩展。
3. 问题也一起提了。

**Comment by lloydzhou** [comment]
@gavinwyf 
我认为可以通过提供Teleport的方式解决问题
https://github.com/antvis/X6/issues/2075

1. 使用Teleport可以避免生成多个Vue App，提升渲染性能
2. 不再注册多个Vue App的时候，组件内部想要使用第三方库以及一些全局配置的时候，应该可以直接使用
3. 节点内部组件实际上是在整个全局的Vue App内运行，节点内部组件渲染更新应该也会更加及时。

这里有一个在线的demo，里面有提供一个`useTeleport`的方法应该可以用。
https://codesandbox.io/s/pensive-goldstine-ltvb3q?file=/src/App.vue:3762-3815

思路就是
1. 直接注册一个View，这个View会绑定一个动态的TeleportContainer返回出去。
2. View在初始化的时候，会把对应cell传进来的Component挂到TeleportContainer上面去。而View自己只需要负责按照id生成一个Teleport对应的target地址就好了
3. `new VueShape`的时候指定相同的viewId
4. 最后挂载TeleportContainer

**Comment by NewByVector** [comment]
推荐使用 @lloydzhou 贡献的 teleport 的使用方式。
