### ISSUE TITLE
filter滤镜对部分edge不生效

### ISSUE THREAD

**Issue by avrinfly** [antvis/X6#2065]
### Describe the bug

我在画布中画图时，给边增加了一些滤镜，发现有些边生效，有些边（直线边）就不见了

### Your Example Website or App

https://codesandbox.io/s/aged-breeze-eo5srt

### Steps to Reproduce the Bug or Issue

1.打开示例地址
2.能发现hello到world1中间没有线，但实际上有设置
3.拖动world1，会发现边又出现了

### Expected behavior

预期：
边为直线的情况下也能出现

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 1.31.4]

**Comment by gossypol** [comment]
这个是因为 x6 把 svg 的 `filterUnits` 属性默认设置为 `objectBoundingBox ` 了，你可以先像我这样修改该属性达到达到这个效果。不过我对这个属性的作用了解不深，不确定这样做会不会存在什么副作用，但目前还没有发现有什么问题。
<img width="819" alt="image" src="https://user-images.githubusercontent.com/31892817/174268329-965363a9-9275-48df-b3e3-d90a48d51c0b.png">

**Comment by bakaEGO** [comment]
使用了以上属性，无法在画布所有的分页上正常显示连线和滤镜

**Comment by bakaEGO** [comment]
<img width="197" alt="image" src="https://github.com/antvis/X6/assets/37462687/7ba585cd-65ba-4b57-b743-7cd16a2b2118">
