### ISSUE TITLE
我通过edge:change:target来改变edge的样式时，发现会卡住

### ISSUE THREAD

**Issue by GPXNB** [antvis/X6#2071]
### 问题描述

graph.on('edge:change:target', ({ edge })=> {
    if (edge.getTargetNode()) {
        edge?.attr('line/stroke', '#30BF13');
        const sourceNode = edge?.getSourceNode();
        const sourcePortId = edge?.getSourcePortId();
        sourceNode?.setPortProp(sourcePortId, ['attrs', 'circle'], {fill: '#30BF13', r: 6, stroke: '#A5E693', strokeWidth: 2});
    } else {
        edge?.attr('line/strokeDasharray', 5);
        edge?.attr('line/stroke', 'red');
        const sourceNode = edge.getSourceNode();
        const sourcePortId = edge.getSourcePortId();
        sourceNode?.setPortProp(sourcePortId, ['attrs', 'circle'], {fill: 'red', r: 6, stroke: '#91bcf4', strokeWidth: 2});
    }
})
复制这段监听代码到https://x6.antv.vision/zh/examples/showcase/faq#validate-connection可复现问题

1、第一次添加边时拖拽吸附都是正常的
<img width="227" alt="image" src="https://user-images.githubusercontent.com/45168755/165675714-19f6fb97-9ae1-4c24-838a-c2a584081552.png">
2、点击修改边时时会卡住
<img width="233" alt="image" src="https://user-images.githubusercontent.com/45168755/165675893-df7f79c5-f900-4ada-9a99-d00c34b233d8.png">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
不要在 `edge:change:target` 事件里面去修改 edge 的属性，这样会造成 edge update.

**Comment by GPXNB** [comment]
@NewByVector 那我要实现这种脱离连接桩后，改变边的样式要怎么做呢？😊

**Comment by NewByVector** [comment]
@GPXNB 你这个场景确实特殊，我先研究一下。

**Comment by GPXNB** [comment]
@NewByVector  嗯呢 期待你的回复～
