### ISSUE TITLE
根据锚点的状态改变锚点的颜色或形状

### ISSUE THREAD

**Issue by chris-mask** [antvis/X6#2072]
### 功能描述

可以根据锚点的状态参数批量改变锚点的颜色或者状态，可以在画布初始化的时候去决定

### 期望解决方案

期望可以根据状态显示锚点的颜色或状态，这样用户可以一眼看出哪些锚点是必须连接的或锚点涉及的参数哪里不符合也无需求的

**Comment by NewByVector** [comment]
这个可以实现的呀，具体的卡点在哪里？

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。
