### ISSUE TITLE
vite 打包部署报错

### ISSUE THREAD

**Issue by xinzi1990** [antvis/X6#2077]
### Describe the bug

<img width="364" alt="image" src="https://user-images.githubusercontent.com/19815987/165989058-13757b33-50c7-4949-a42b-85e1d12ba43b.png">
我也是通过Issues找到的这段代码加到，vite.config.js里面
<img width="500" alt="image" src="https://user-images.githubusercontent.com/19815987/165989492-671df878-0e67-440e-977a-06847ac3c90d.png">

### Your Example Website or App

https://user-images.githubusercontent.com/19815987/165989075-7685b8e6-7c93-4210-8696-20f771d7c760.png

### Steps to Reproduce the Bug or Issue

<img width="364" alt="image" src="https://user-images.githubusercontent.com/19815987/165989075-7685b8e6-7c93-4210-8696-20f771d7c760.png">

### Expected behavior

<img width="364" alt="image" src="https://user-images.githubusercontent.com/19815987/165989058-13757b33-50c7-4949-a42b-85e1d12ba43b.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
加了那个配置还报错吗？

**Comment by qq897425998** [comment]
我的不报错， 但是 打包后的 vue的组件渲染不出来 console也不报错 渲染出来一片白 有解决的兄弟吗help

**Comment by NewByVector** [comment]
@qq897425998 节点内部空白还是整个都是空白？

**Comment by qq897425998** [comment]
> @qq897425998 节点内部空白还是整个都是空白？

节点空白

**Comment by qq897425998** [comment]
@NewByVector 打包后 节点内部空白

**Comment by qq897425998** [comment]
https://github.com/vitejs/vite/issues/3413#issuecomment-1113565557
将template改为render函数渲染解决了 但仍不知道具体为什么template打包后是不行的

**Comment by ZATER-PRO** [comment]
我也是存在报错,本地调试没问题,使用nginx部署后报错
![image](https://user-images.githubusercontent.com/52991757/168544116-4de33412-9d0c-4f13-86a8-f5716cd7a99b.png)

**Comment by ZATER-PRO** [comment]
> 我也是存在报错，本地调试没问题，使用nginx部署后报错 ![图片](https://user-images.githubusercontent.com/52991757/168544116-4de33412-9d0c-4f13-86a8-f5716cd7a99b.png)

我好了,看了楼上后改了下vite.config.js
![image](https://user-images.githubusercontent.com/52991757/168568612-ed81e594-f204-4c29-ba2f-e0cc77c4875e.png)

**Comment by zwwmin** [comment]
How did you solve it, I have this problem too

**Comment by yangxin1** [comment]
> [vitejs/vite#3413 (comment)](https://github.com/vitejs/vite/issues/3413#issuecomment-1113565557) 将template改为render函数渲染解决了 但仍不知道具体为什么template打包后是不行的

你好，请问能不能详细说一下解决方案呢，我也遇到了这个问题

**Comment by NewByVector** [comment]
解决方案参考 https://github.com/vitejs/vite/issues/3413#issuecomment-1107804641
