### ISSUE TITLE
node parent 无效

### ISSUE THREAD

**Issue by itwmike** [antvis/X6#2081]
### Describe the bug

const nodes = [
{
height: 200
id: "SubProcess1"
label: "子流程容器"
parent: ""
shape: "SubProcess"
width: 900
x: 380
y: 430
},
  {
  id: "ApprovalTask2"
  label: "审批2"
  parent: "SubProcess1"
  shape: "ApprovalTask"
  x: 670
  y: 520
  }
]

graph.fromJSON({nodes})

采用这种方式 设置 节点的 parent 不起作用

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

如题

### Expected behavior

如题

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

"@antv/x6": "^1.30.1",
"@antv/x6-vue-shape": "^1.3.2",

**Comment by NewByVector** [comment]
使用 `children` 属性来指定父子关系。`parent` 会在下个版本删除。

**Comment by itwmike** [comment]
收到！
