### ISSUE TITLE
目前支持react多少版本

### ISSUE THREAD

**Issue by BrickerZou** [antvis/X6#2093]
### 功能描述

目前支持react最新多少版本？
用react18好像有一些报错

### 期望解决方案

![image](https://user-images.githubusercontent.com/73508461/167281997-d3dfbc32-9bd0-4770-93d9-e2b4c6711d62.png)
使用某些组件时，显示接口未定义children属性

**Comment by NewByVector** [comment]
x6-react-components 是基于 React 18 之前版本开发，在 React 18 中有一些兼容问题，我们会在 2.0 版本兼容 React 18。

**Comment by Mrheqiang** [comment]
**package.json**
"react": "^18.2.0",
"react-dom": "^18.2.0",

**index.tsx**
`<div className={styles.middle}>`
    `<ContextMenu menu={menu}>`
        `<div id='container' style={{ height: '100%' }}></div>`
    `</ContextMenu>`
`</div>`

**报错：**
没有与此调用匹配的重载。
  第 1 个重载(共 2 个)，“(props: Props | Readonly<Props>): ContextMenu”，出现以下错误。
    不能将类型“{ children: Element; menu: Element; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<ContextMenu> & Readonly<Props>”。
      类型“IntrinsicAttributes & IntrinsicClassAttributes<ContextMenu> & Readonly<Props>”上不存在属性“children”。
  第 2 个重载(共 2 个)，“(props: Props, context: any): ContextMenu”，出现以下错误。
    不能将类型“{ children: Element; menu: Element; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<ContextMenu> & Readonly<Props>”。
      类型“IntrinsicAttributes & IntrinsicClassAttributes<ContextMenu> & Readonly<Props>”上不存在属性“children”。ts(2769)

**目前修改方案**
降低react版本到18以下

**期望**
尽快推出支持react18的2.0版本，有时间点吗？
