### ISSUE TITLE
antv/x6-react-components npm start后warning

### ISSUE THREAD

**Issue by BrickerZou** [antvis/X6#2094]
### Describe the bug

![image](https://user-images.githubusercontent.com/73508461/167283060-6bd72b78-5b02-4cb5-9d27-a4c81e389b7b.png)

### Your Example Website or App

https://stackblitz.com/edit/react-ts-crfnou?file=App.tsx

### Steps to Reproduce the Bug or Issue

![image](https://user-images.githubusercontent.com/73508461/167283136-0390a858-97c3-45f3-be58-a6e8f72c1861.png)

### Expected behavior

貌似文件找不到，怎么解决

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/73508461/167283136-0390a858-97c3-45f3-be58-a6e8f72c1861.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
是不是环境配置问题？这个 [demo](https://codesandbox.io/s/fy7ysk?file=/src/app.tsx) 是好的。

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。
