### ISSUE TITLE
图表示例中 “限制子元素移动范围”  

### ISSUE THREAD

**Issue by jianxiny** [antvis/X6#2096]
### Describe the bug

快速移动子元素到边界会产生报错，此时子元素无法再次移动
link：[https://x6.antv.vision/zh/examples/node/group#restrict-movement](https://x6.antv.vision/zh/examples/node/group#restrict-movement)

### Your Example Website or App

https://x6.antv.vision/zh/examples/node/group#restrict-movement

### Steps to Reproduce the Bug or Issue

1. Go to [example site](https://x6.antv.vision/zh/examples/node/group#restrict-movement)
2. drag the child node, quick move to boundary
3. then the (F12) console pane will show the error, such as "Uncaught TypeError: t.tagName is undefined..."

### Expected behavior

when drag node and quick child node, it shouldn't emit error

### Screenshots or Videos

![Uploading windows 截图 - 搜索 — Mozilla Firefox 2022_5_9 20_41_49.png…]()

### Platform

- OS: Windows
- Browser: Firefox
- Version: 100

**Comment by NewByVector** [comment]
I did not find any error information according to your operation. Do you have more input information?
