### ISSUE TITLE
群组下，增加子节点layout

### ISSUE THREAD

**Issue by treesen** [antvis/X6#2104]
### 功能描述

群组下面也有很多节点，需要通过layout来摆放

### 期望解决方案

类似现在的layout

**Comment by 1634228212** [comment]
这个问题 请问有解决吗

**Comment by refuse-c** [comment]
使用x6的 layout  DagreLayout   带有群组节点  渲染后  样式错乱

**Comment by NewByVector** [comment]
@treesen @xiaoyixin-cmd @refuse-c  希望这个 [demo](https://codesandbox.io/s/ceng-ci-bu-ju-4xbm4s) 能帮到你们。
