### ISSUE TITLE
windows某些电脑会出现闪动

### ISSUE THREAD

**Issue by hejianwen1** [antvis/X6#2105]
### 问题描述

在windows某一些电脑上JsonForm 配置式表单头部会出现闪动

### 重现链接

CodeSandbox

### 重现步骤

https://user-images.githubusercontent.com/102499589/167848276-66008d5d-3fa1-4361-93ec-e3fce5ffb04e.mp4

### 预期行为

https://user-images.githubusercontent.com/102499589/167848544-d5dbfc42-22e8-4a2a-a186-21c460dfa6cf.mp4

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

Uploading ME1652271571650.mp4…

### 补充说明（可选）

当时本地出现这个问题   但是上官方demo一看也有这个问题

**Comment by NewByVector** [comment]
这个是 XFlow 的问题吧，可以到 XFlow 下面提 issue.

**Comment by hejianwen1** [comment]
抱歉 搞错了
