### ISSUE TITLE
vue3 inject error

### ISSUE THREAD

**Issue by mioxs** [antvis/X6#2113]
### Describe the bug

vue3 无法注入inject

### Steps to Reproduce the Bug or Issue
```ts
<script setup lang="ts">
import { inject, onMounted, ref } from 'vue';
import { Node } from '@antv/x6';
const node = inject<Node>('getNode');
const labelRef = ref('');

onMounted(() => {
  if (node) {
    const { label } = node.getData();
    if (label) {
      labelRef.value = label;
    }
  }
});
</script>
```

### Screenshots or Videos
控制台node打印值为
![image](https://user-images.githubusercontent.com/49021590/168791120-66ce91a3-eb8b-49b5-85de-c01c72e01063.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lloydzhou** [comment]
getNode是一个function不是Node对象

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。
