### ISSUE TITLE
复制黏贴时，启用localStorage后，出现错误

### ISSUE THREAD

**Issue by wendao8469759** [antvis/X6#2114]
### Describe the bug

节点是使用vue组件自定义渲染的node，使用copy复制node节点，使用paste后出现如下错误

Property or method "tableData" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See

### Your Example Website or App

www.aliyun.com

### Steps to Reproduce the Bug or Issue

节点是使用vue组件自定义渲染的node，使用copy复制node节点，使用paste后出现如下错误

Property or method "tableData" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See

### Expected behavior

期望可以解决此问题或者通过其他方式来解决此问题

### Platform

- windows

**Comment by NewByVector** [comment]
有可以复现的 demo 看下吗？

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。

**Comment by wendao8469759** [comment]
这段时间忘记关注邮件了。 我测试中发现确实是数据不能序列化。 因为我使用了vue组件渲染，然后数据时动态渲染上去的，复制的时候，不能复制渲染时的数据，所以复制的时候出现了错误

**Comment by NewByVector** [comment]
@wendao8469759 vue节点的序列化方式在[文档](https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-vue-%E8%8A%82%E7%82%B9)上有说明。

**Comment by wendao8469759** [comment]
好的
