### ISSUE TITLE
toJSON取出画布数据data后， 使用fromJSON方法渲染data数据到画布出错

### ISSUE THREAD

**Issue by SillyBoyXZH** [antvis/X6#2120]
### Describe the bug

在画中做出某些操作后，使用toJSON取出画布数据data，
再使用fromJSON放啊，将全部data数据渲染到画布中出错。

报错信息如下图：
![cellon](https://user-images.githubusercontent.com/82207908/168987656-44001a57-85cb-401c-89c4-93e78efd5b4f.png)

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

1、使用toJSON方法啊导出画布中全部数据
2、清空画布
3、用该数据，通过fromJSON方法渲染到画布中

### Expected behavior

希望能够傻瓜式的把toJSON导出的数据。再使用fromJSON方法渲染到画布中，且无实际差异

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SillyBoyXZH** [comment]
节点是使用的React自定义节点，可以正常导出数据，就是没办法再渲染回去

**Comment by SillyBoyXZH** [comment]
测试情况为：
1、第一步，导出toJSON得出的数据，存为maJsonData
2、第二部，清空画布全部数据
3、两秒后，将toJSON导出的数据maJsonData使用fromJSON方法渲染回去

问题：单个节点或多个节点（React自定义节点），都可以渲染回去，几点钟附带的data数据中有表单数据，也能正常返回；但是，只要有“边”连接，则报错如下图，不知是什么原因，是边无法渲染吗


<img width="925" alt="image" src="https://user-images.githubusercontent.com/82207908/168996059-e1408078-cb10-4db3-bb36-f4d5da16f959.png">

**Comment by NewByVector** [comment]
又复现的 demo 吗，或者提供完整的 json 数据。你上面的节点数据中 componet 其实是有问题的，这个无法序列化，可以在[官网](https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-react-%E8%8A%82%E7%82%B9)找到解决方案。

**Comment by SillyBoyXZH** [comment]
> 

换了其他方式解决了，在渲染之前根据数据里面的某个自定义类型又配置了一下节点
