### ISSUE TITLE
自定义节点，使用toJSON导出后，使用fromJSON二次渲染，和自定内容不符合

### ISSUE THREAD

**Issue by LMLGM** [antvis/X6#2121]
### 问题描述

自定义节点，使用toJSON导出后，使用fromJSON二次渲染，和自定内容不符合

### 重现链接

https://codesandbox.io/embed/pedantic-dirac-s6rwy7?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

https://codesandbox.io/embed/pedantic-dirac-s6rwy7?fontsize=14&hidenavigation=1&theme=dark

### 预期行为

![image](https://user-images.githubusercontent.com/58587791/169012624-c2d769cb-f5db-421e-baa8-988d5696568c.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
重复注册节点导致。
