### ISSUE TITLE
请教  :  同时打开 selecting 和 panning , 鼠标显示问题

### ISSUE THREAD

**Issue by a982246809** [antvis/X6#2124]
### 功能描述

![image](https://user-images.githubusercontent.com/56909676/169229389-c3949671-26df-439f-8347-ad5d3698942b.png)
![image](https://user-images.githubusercontent.com/56909676/169229940-3b8cdb96-8e20-41ce-a0b9-53afe122b314.png)

希望在按下ctrl 时 , 鼠标变成 "手"
松开时 , 变指针
而不是一直处于"手"的状态
不知道有没有办法解决

### 期望解决方案

希望在按下ctrl 时 , 鼠标变成 "手"
松开时 , 变指针
而不是一直处于"手"的状态

**Comment by NewByVector** [comment]
这个已经加入到我们的功能计划中了。

**Comment by ZHUYUANWEI** [comment]
想问一下这个问题，目前进度怎么样

**Comment by NewByVector** [comment]
与 https://github.com/antvis/X6/issues/2134 重复，先关闭。

**Comment by NewByVector** [comment]
@ZHUYUANWEI 是的 这个配置是无效的 我优化一下文档。
