### ISSUE TITLE
国内开x6的官网很慢，vpn就很快，求国内部署

### ISSUE THREAD

**Issue by li-yinan** [antvis/X6#2125]
### 功能描述

国内开x6的官网很慢，vpn就很快，求国内部署

### 期望解决方案

国内开x6的官网很慢，vpn就很快，求国内部署

**Comment by klren0312** [comment]
不是有国内的吗 https://antv-x6.gitee.io/zh/

**Comment by NewByVector** [comment]
暂时可以使用国内镜像，速度会好一点。也可以把仓库 clone 到本地，看本地的 md 文档。
