### ISSUE TITLE
节点文本溢出hover时能给出提示

### ISSUE THREAD

**Issue by mjyg** [antvis/X6#2127]
### 功能描述

![1653036488910](https://user-images.githubusercontent.com/22444521/169491181-e35536c0-0fdd-4e27-85e3-a5a2332be35d.jpg)
如图，鼠标hover时能显示省略文本的提示框

### 期望解决方案

希望文本溢出时鼠标hover时能显示省略文本的提示框

**Comment by mjyg** [comment]
有没有大佬回复一下，现在有这种配置了吗

**Comment by Mark-1994** [comment]
+1

**Comment by NewByVector** [comment]
可以参考这个 [demo](https://x6.antv.vision/zh/examples/edge/tool#tooltip) 写个边上 tooltip 工具

**Comment by mjyg** [comment]
> 

有没有内部方法可以判断文字是否溢出了吗

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。
