### ISSUE TITLE
场景：拖动节点到达边上的时候，可以直接连接该节点。类似：1 -------> 2 ，  拖过来一个 3 到边上后变成：1 ----> 3 ----> 2

### ISSUE THREAD

**Issue by Selinalemon** [antvis/X6#2130]
场景：拖动节点到达边上的时候，可以直接连接该节点。类似：1 -------> 2 ，  拖过来一个 3 到边上后变成：1 ----> 3 ----> 2
请问实现这种场景应该用哪个api，是否可以提供节点（边）拖动到其他节点（边）上面时的事件
![2021-10-13 10 35 46](https://user-images.githubusercontent.com/6457155/137057396-4596f475-f315-4f61-81e7-96e6462a0db1.gif)

@NewByVector 谢谢，辛苦帮忙看一下
@[hy-pillow](https://github.com/hy-pillow)嗨，你这边的问题解决了么，请问上述场景使用的哪个api

_Originally posted by @hy-pillow in https://github.com/antvis/X6/issues/332#issuecomment-941854816_

**Comment by NewByVector** [comment]
希望这个[示例](https://codesandbox.io/s/yu-lian-xian-xiang-jiao-zi-dong-lian-jie-boh3jk)能帮到你。

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。

**Comment by Selinalemon** [comment]
> 你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。

不好意思最近有点忙，回复的不是很及时，已经解决了，谢谢
