### ISSUE TITLE
minmap的‘x6-widget-minimap-viewport’本地开发环境和生产环境显示不一致

### ISSUE THREAD

**Issue by zwzlovedh** [antvis/X6#2131]
### 问题描述

minmap的‘x6-widget-minimap-viewport’本地开发环境和生产环境显示不一致，第一张本地的，第二张生产环境的
![image](https://user-images.githubusercontent.com/75016090/169784537-2b06ae04-1c88-41b5-b5be-2824aff1002d.png)
![image](https://user-images.githubusercontent.com/75016090/169784702-bfc67fed-b4fe-40f0-94ef-6c6d010b576c.png)

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

初始化小地图本地开发环境正常，上生产不符合预期，本地小地图viewport宽高正常，上产环境宽高和画布的大小一样

### 预期行为

期望一样

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
有可以复现的 demo 吗，minimap 最近有两次修改 https://github.com/antvis/X6/pull/2117 https://github.com/antvis/X6/pull/2111，你先确认下本地 x6 版本和线上的区别。

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。
