### ISSUE TITLE
selection框选不支持边

### ISSUE THREAD

**Issue by damnright** [antvis/X6#2132]
### 功能描述

selection框选不支持边，边不在框选范围内

### 期望解决方案

有什么办法可支持框选cell，包括边

**Comment by MrMengJ** [comment]
可通过配置项开启是否框选中边 [更新日志](https://x6.antv.vision/zh/docs/tutorial/log#121x)

```
selecting: {
    enabled: true,
    rubberband: true,
    rubberEdge: true, // 框选可以选中edge
    rubberNode: true, // 框选可以选中node
 }
```

**Comment by mjyg** [comment]
` rubberEdge: true, // 框选可以选中edge
    rubberNode: true, // 框选可以选中node`
楼主试过有用吗，我加了好像没有用，边还是不能选中

**Comment by NewByVector** [comment]
@mjyg 是不是没有设置 showEdgeSelectionBox

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。
