### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'findViewByElem')

### ISSUE THREAD

**Issue by moogy1** [antvis/X6#2141]
### 问题描述

vue3,开发环境没问题，生产环境报错

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/44360367/170464779-3dbd7c10-0d95-47b5-bebd-b4da81850fa2.png)

**Comment by moogy1** [comment]
![image](https://user-images.githubusercontent.com/44360367/170905399-09ad6b91-00ad-408f-af38-ba12ea71bf95.png)
鼠标事件mouseOver mouseOut时控制台报错，开发环境没报错，测试环境报错

**Comment by moogy1** [comment]
![image](https://user-images.githubusercontent.com/44360367/170906506-9f86e5be-3760-462f-ba0d-9a01977cd319.png)
这里的代码加了 还是有其他配置

**Comment by NewByVector** [comment]
可以看下两个环境的具体差别在哪里，版本号有区别吗？

**Comment by moogy1** [comment]
> 可以看下两个环境的具体差别在哪里，版本号有区别吗？

开发和测试都更新到最新版本1.32.2了，测试环境vite构建测试版本，开发环境正常运行，测试环境涉及到鼠标移入移出和滚轮事件会报错，我把代码贴下

**Comment by moogy1** [comment]
https://codesandbox.io/s/adoring-babycat-hhwkk4?file=/index.vue

**Comment by NewByVector** [comment]
@moogy1 你这个 demo 报错呀。

**Comment by moogy1** [comment]
解决了 #2077 vite打包得问题，谢谢

**Comment by zwwmin** [comment]
How did you solve it, I have this problem too

**Comment by 981433814** [comment]
@moogy1  同问

**Comment by 981433814** [comment]
@zwwmin 这样就行了，好像
      {
        find: '@antv/x6',
        replacement: '@antv/x6/dist/x6.js',
      },
      {
        find: '@antv/x6-vue-shape',
        replacement: '@antv/x6-vue-shape/lib',
      },
