### ISSUE TITLE
vue2自定义节点this.graph.fromJSON()渲染时报错

### ISSUE THREAD

**Issue by yinguniang** [antvis/X6#2142]
### 问题描述

使用vue2自定义节点this.graph.fromJSON()渲染时报错，Error in beforeCreate hook: "TypeError: Cannot read properties of null (reading 'call')"
Graph.registerNode('start', {
  inherit: 'vue-shape',
  x: 500,
  y: 100,
  width: 32,
  height: 32,
  component: {
    template: `<Start />`,
    components: {
      Start
    }
  }
})
this.graph.addNode({
  x: 500,
  y: 100,
  width: 32,
  height: 32,
  shape: 'start'
})
<template>
  <div class="startNode">
    <img :src="getImg" />
  </div>
</template>

<script>
export default {
  data() {
    return {
      getImg: require('@/assets/image/flow/start.png')
    }
  },
  name: 'start',
  inject: ['getGraph', 'getNode'],
  props: [],
  mounted() {
    const self = this
  }
}
</script>

### 重现链接

暂无

### 重现步骤

1、Graph.registerNode
2、this.graph.addNode
3、this.graph.toJSON()
4、this.graph.fromJSON()

### 预期行为

不报错

### 平台

- 操作系统: [Windows, "vue": "^2.6.10"]
- 网页浏览器: [Google Chrome]
- X6 版本: [@antv/x6": "^1.29.0", "@antv/x6-vue-shape": "^1.0.25",]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/37579873/170474885-8f806c67-d713-46fe-8efc-d1fc4e64701f.png)

**Comment by wflixu** [comment]
之前好像遇到过类似的问题，可能是template 后面标签大小写的问题，你写成这样试试
```
 template: `<start/>`,
      components: {
        'start': Start,
      },
```

**Comment by yinguniang** [comment]
> start

感谢回复啊。我刚刚试了下，发现还是不行~~

> 之前好像遇到过类似的问题，可能是template 后面标签大小写的问题，你写成这样试试
> 
> ```
>  template: `<start/>`,
>       components: {
>         'start': Start,
>       },
> ```

**Comment by NewByVector** [comment]
应该是节点注册出错了，可以参考这个 [demo](https://codesandbox.io/s/vue-shape-8ciig?file=/src/App.vue)

**Comment by NewByVector** [comment]
为了提高沟通效率，我们先关闭这个 issue，如果还有问题，请重新提一个新的 issue，并附上可以复现的 demo。

**Comment by tanxuxu** [comment]
我用的时候也出现了这个问题，请问最后是怎么解决的？

**Comment by zhoupIT** [comment]
这个是啥问题啊 我也出现了

**Comment by tanxuxu** [comment]
您的邮件我已经查收，我会尽快给您回复

**Comment by YinglunYin95** [comment]
有什么解决方案吗

**Comment by tanxuxu** [comment]
您的邮件我已经查收，我会尽快给您回复

**Comment by 993318936** [comment]
换成用registerVueComponent注册组件

**Comment by tanxuxu** [comment]
您的邮件我已经查收，我会尽快给您回复

**Comment by thiagoalvernaz** [comment]
@yinguniang I believe you are using the toJSON method and then using the JSON.stringify, in this case the beforeCreate and beforeDestroy methods, which was a function, ends up becoming an array in the conversion, and then when the fromJSON is executed it tries to execute as a function, so it is generated the error.
To resolve I am doing:
`const saveJson = JSON.stringify(this.graph.toJSON());
const loadGraph = JSON.parse(saveJson );
for (const cell of loadGraph.cells) {
  try {
    if (cell.component.components) {
      delete cell.component.components.options.beforeCreate;
      delete cell.component.components.options.beforeDestroy;
    }
  } catch (error) {
    console.log(error);
  }
}
this.graph.fromJSON(loadGraph);`

**Comment by tanxuxu** [comment]
您的邮件我已经查收，我会尽快给您回复
