### ISSUE TITLE
通过mousewheel缩放画布报错 #639--补充

### ISSUE THREAD

**Issue by liubai678** [antvis/X6#2143]
@Doifo 在 win10 + chrome(版本 88.0.4324.146（正式版本） （64 位）) 测试没有报错，这是测试连接 https://codesandbox.io/s/new-moon-cbtmm?file=/package.json

你那边给一个可以复现的 codesandbox 吧

_Originally posted by @bubkoo in https://github.com/antvis/X6/issues/639#issuecomment-772237772_

---codesanbox确实不会报错，这个我已经尝试过了，但本地开发还是会报错，环境：
win10+chrome101.0.4951.67+angular13+@antv/x6@1.32.2
报错指向mousewheel.js onwheel方法第41行：e.preventDefault();
报错内容：Unable to preventDefault inside passive event listener invocation.

**Comment by NewByVector** [comment]
有本地的报错 demo 看下吗？
