### ISSUE TITLE
自定义edge设置router在manhattan模式下，设置args.startDirections和args.endDirections不符合预期

### ISSUE THREAD

**Issue by lemonly14** [antvis/X6#2150]
### Describe the bug

自定义edge设置router在manhattan模式下，设置args.startDirections和args.endDirections不符合预期
 如我设置startDirections为['right', 'left']，但是却表现为bottom.

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

1.自定义edge的router为manhattan
2.设置args.startDirections为['right', 'left']
3.图像上呈现的结果为bottom

### Expected behavior

自定义edge设置router在manhattan模式下，设置args.startDirections为['right', 'left'] 。edge应从左右开始

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/41465479/170900380-3033fb8a-9a28-449f-8cd5-0a9c073950f4.png)
![image](https://user-images.githubusercontent.com/41465479/170900402-b231cfe5-804c-45f4-a14b-e13b0ca116d1.png)

### Platform

- OS:  Windows10
- Browser: Chrome
- Version: 101.0.4951.67

**Comment by NewByVector** [comment]
你提的问题无法重现，有可以复现的 demo 看下吗？

**Comment by lemonly14** [comment]
> 

好的  不好意思今天才看到恢复。我准备一下demo

**Comment by lemonly14** [comment]
> 你提的问题无法重现，有可以复现的 demo 看下吗？

https://github.com/lemonly14/useX6.git    大佬看一下

**Comment by NewByVector** [comment]
@lemonly14 看了下，首先不从左侧和右侧出来是因为你的 step 设置过大，猜想你 step 设置比较大是因为解决路径比较扭曲， 因为你的边里面包含了 vertices，而且 vertices 点在节点的正下方，所以如果想从左右出来，而且还需要 vertices，扭曲是无法避免的。

**Comment by lemonly14** [comment]
> @lemonly14 看了下，首先不从左侧和右侧出来是因为你的 step 设置过大，猜想你 step 设置比较大是因为解决路径比较扭曲， 因为你的边里面包含了 vertices，而且 vertices 点在节点的正下方，所以如果想从左右出来，而且还需要 vertices，扭曲是无法避免的。

好的 大佬    调整之后没有问题了！！！！ 谢谢大佬
