### ISSUE TITLE
safari导出png 图片节点内容导出空

### ISSUE THREAD

**Issue by wzc570738205** [antvis/X6#2151]
### Describe the bug

在safari浏览器上，拓补图渲染正常。如下：
<img width="717" alt="image" src="https://user-images.githubusercontent.com/21350874/170928095-63618d69-dfe8-474a-b928-938bf600b5e4.png">
各节点图片采用png url和base64都有尝试过，发现导出图片的方法回调里返回的base64图片流丢失了图片
<img width="707" alt="image" src="https://user-images.githubusercontent.com/21350874/170928241-46650efd-7e1f-4edc-a036-f57c9314f279.png">

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

safa的导出图片方法失效

### Expected behavior

请问这个问题怎么解决？

### Platform

- OS: [macOS]
- Browser: [Safari]
- Version: [15.4 ]

**Comment by NewByVector** [comment]
这个有可以复现的 demo 可以看下吗？
