### ISSUE TITLE
IE11 使用渲染 HTML 节点不支持

### ISSUE THREAD

**Issue by wangyonghua** [antvis/X6#2155]
### Describe the bug

我们在IE11 使用渲染 HTML 节点，但是不支持，将你们官网demo
https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-html-%E8%8A%82%E7%82%B9
也出现loading，无法正常展示在ie11，请问你们这块兼容IE11吗

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

直接查看官网demo，一直loading

### Expected behavior

官网查看
https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-html-%E8%8A%82%E7%82%B9

### Platform

- OS: Windows,
- Browser: IE
- Version: 11

**Comment by wangyonghua** [comment]
请问有什么推荐的办法解决类？

**Comment by NewByVector** [comment]
用 svg 节点呢？你们节点内容复杂吗？

**Comment by wangyonghua** [comment]
节点内容倒是不复杂，svg里面不也需要用foreignObject标签么，你们html渲染底层不是转换成svg渲染的吗？svg与html渲染在你们实现上会有什么差别类？

**Comment by lloydzhou** [comment]
@wangyonghua 

1. `foreignObject`是一个svg的元素(IE实现的svg不支持这个标签)，
2. html渲染底层是将html放到一个`foreignObject`里面进行渲染。所以在IE11上面不支持。
3. 如果你的节点内容不复杂，可以通过定制markup来实现，不使用html渲染。

**Comment by wyl1112** [comment]
@lloydzhou @NewByVector 
我的项目中也遇到此问题，html渲染的节点在IE下无法显示，使用html渲染的初衷是想实现文字段落内容，能通过输入Enter健达到换行效果，而不是让客户输入换行符代码，如果通过定制markup来实现，是否有办法能实现这个需求呢？

**Comment by lloydzhou** [comment]
1. IE实在是浏览器限制了，可以试试然客户升级到edge，毕竟微软都不维护了...
