### ISSUE TITLE
求指教，拖拽组件Addon，怎么自定义边，或者自定义一条直线？

### ISSUE THREAD

**Issue by wjs0406** [antvis/X6#2156]
### 问题描述

new Addon.Stencil
groups中添加的节点有什么方式可以添加流程图的线，或者自定义一条直线？

### 重现链接

https://x6.antv.vision/zh/docs/tutorial/basic/dnd

### 重现步骤

const stencil = new Addon.Stencil({
......
groups: [
  node1, node2
]
})

stencil.load([node1, node2],  'node1');

### 预期行为

![image](https://user-images.githubusercontent.com/29083182/171075674-5f1d545d-6a97-4c52-ba83-8c21debb2ce9.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.32.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/29083182/171075453-fc261851-81ae-4168-9963-422f4d37334d.png)

**Comment by cuidong626** [comment]
node 节点是可以自定义的，在自定义节点里面画一个线就好了

**Comment by wjs0406** [comment]
> node 节点是可以自定义的，在自定义节点里面画一个线就好了

但是那个线只能是直线，不能像边那样可以弯曲吧

**Comment by cuidong626** [comment]
path 画一个

**Comment by cuidong626** [comment]
> > node 节点是可以自定义的，在自定义节点里面画一个线就好了
> 
> 但是那个线只能是直线，不能像边那样可以弯曲吧

[可以使用path随便的画路径](https://x6.antv.vision/zh/docs/tutorial/intermediate/custom-node#%E7%AC%AC%E4%BA%8C%E6%AD%A5%EF%BC%9A%E9%85%8D%E7%BD%AE)

你看下这个

**Comment by cuidong626** [comment]
> > node 节点是可以自定义的，在自定义节点里面画一个线就好了
> 
> 但是那个线只能是直线，不能像边那样可以弯曲吧

我之前直接在节点里面放图片，x6有内置可以放图片的节点。你也可以自己造
![image](https://user-images.githubusercontent.com/22650893/171086594-008735a9-7707-4e58-a477-79b460fcff14.png)
不知道满不满足你的需求

**Comment by wjs0406** [comment]
> > > node 节点是可以自定义的，在自定义节点里面画一个线就好了
> > 
> > 
> > 但是那个线只能是直线，不能像边那样可以弯曲吧
> 
> 我之前直接在节点里面放图片，x6有内置可以放图片的节点。你也可以自己造 ![image](https://user-images.githubusercontent.com/22650893/171086594-008735a9-7707-4e58-a477-79b460fcff14.png) 不知道满不满足你的需求

可以截图看下你里面的实现吗？

**Comment by cuidong626** [comment]
我是自己画的html，没有用Addon.Stencil，他那个不符合我的需求

**Comment by cuidong626** [comment]
你的需求是不是就是在节点里面有条线？

**Comment by cuidong626** [comment]
![image](https://user-images.githubusercontent.com/22650893/171096135-f785c4ce-3fda-4fec-a3f9-cb9b34a95b7f.png)
这样就可以了  https://codesandbox.io/s/confident-currying-ldp8bq?file=/src/app.tsx

**Comment by wjs0406** [comment]
> 你的需求是不是就是在节点里面有条线？

看懂了，我的节点是只要线，不要边框，我试试，多谢

**Comment by NewByVector** [comment]
你好，请问这个问题解决了吗？为了更高效的沟通，我们先关闭当前 issue，如果还有问题，请重新提 issue。

**Comment by MrMengJ** [comment]
> > 你的需求是不是就是在节点里面有条线？
> 
> 看懂了，我的节点是只要线，不要边框，我试试，多谢

朋友，和你有一样的需求，请问你实现了吗

**Comment by curryz** [comment]
> 朋友，和你有一样的需求，请问你实现了吗

请问你实现了吗

**Comment by MrMengJ** [comment]
> > 朋友，和你有一样的需求，请问你实现了吗
> 
> 请问你实现了吗

没有。。。

**Comment by NewByVector** [comment]
@curryz @MrMengJ 使用 path 节点可以实现。
