### ISSUE TITLE
connectionPoint的args.selector 不起作用，未达到预期效果 

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#2163]
### 问题描述

官方文档描述
selector：选择器，用于标识一个元素，使用该元素的边框来计算交点。默认使用节点中第一个不在 <g> 元素内的子元素。
![image](https://user-images.githubusercontent.com/22650893/171095184-20d4919c-90d1-4e41-a74d-07809576a6a5.png)

我的预期效果是绕着里面的小正方形旋转，我理解错了？还是用法错了？
![image](https://user-images.githubusercontent.com/22650893/171095320-d479e9cd-8a43-42a2-bfff-8a981cd1eae9.png)

### 重现链接

https://codesandbox.io/s/confident-currying-ldp8bq?file=/src/app.tsx:865-873

### 重现步骤

1.进入页面

### 预期行为

我的预期效果是绕着里面的小正方形旋转

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.32.2 ... ]

**Comment by cuidong626** [comment]
有效果可以达到，只是对 connectionPoint 有点疑惑
![image](https://user-images.githubusercontent.com/22650893/171102082-129122d1-398a-4ea2-8b29-ee7eeff6a40b.png)

**Comment by NewByVector** [comment]
因为你的连线本身不是指向这个 rect(test) , `connectionPoint` 是你指向这个元素，和这个元素的交点坐标。
