### ISSUE TITLE
从俩节点拉出的线直接相连时，两条边的target source其中之一， 会互相指向对方 。fromJSON先渲染哪一条都会找不到另一个边，因为它是按照数组顺序渲染节点和边的

### ISSUE THREAD

**Issue by linktoword** [antvis/X6#2175]
### Describe the bug

从俩节点拉出的线直接相连时，两条边的target source其中之一， 会互相指向对方 。fromJSON先渲染哪一条都会找不到另一个边，因为它是按照数组顺序渲染节点和边的（个人分析），

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1. 节点A，节点B
2.  从节点A拉出一条边 终点是空白处一个点 这条边为 C
3. 从节点B拉出一条边，和边C相连， 此边为边D
4. 鼠标移动到边C上，使用辅助工具'source-arrowhead', 'target-arrowhead'，改变边C的链接点从空白处一个点变为和边D直接相连
5. 保存JSON数据
6. 
![lQLPJxZdc_pfXZ3NAZnNAyGw_beDeoztPXoCmi4EpoDTAA_801_409](https://user-images.githubusercontent.com/37545695/171542794-5ec17670-386d-4013-b34b-a5f307c95660.png)

### Expected behavior

应该如何解决这个问题？

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by linktoword** [comment]
![image](https://user-images.githubusercontent.com/37545695/171543046-c80789a5-f906-4171-bf6f-2023857c7c87.png)

**Comment by linktoword** [comment]
![动画3](https://user-images.githubusercontent.com/37545695/171543207-45eb1048-a5a7-4d86-9443-e37ca486fcae.gif)

**Comment by lloydzhou** [comment]
# 分析
看这个图，感觉是下面的边先连到水平这一条边了
然后通过调整上面这条边，最终两条边互相连到一起了。
最终合并到一起的时候，可以直接将两条边直接合并成一条就好了
 
# 方案
处理连线那里有好几个validate函数。你可以试试在validateEdge 里面写一下这个处理逻辑。
1. 检查一下，如果当前这一条边(E1)连接的target是另一条边(E2)，并且另一条边的target正好是自己。
2. 那么就获取一下另一条边(E2)的路径信息。
3. 将另一条边(E2)的路径信息加到当前这一条边(E1)前面（应该可以通过设置自己这条边(E1)的vertices来达到目的）。
4. 然后，将当前这条边(E1)的target设置成另一条边(E2)的source，同时将另一条边(E2)移除。

**Comment by linktoword** [comment]
```
validateEdge({ edge }) {
    let id = edge.target?.cell
    if (id) {
	let targetCell = graph.value.getCellById(id)
	if (graph.value.isEdge(targetCell) && targetCell.target.cell == edge.id) {
		edge.setVertices([...edge.vertices, ...targetCell.vertices.reverse()])
		edge.target = targetCell.source
		graph.value.removeCell(id)
	}
    }
    return true
}
```
