### ISSUE TITLE
左键框选范围的时候 线  不会被选中， getSelectedCells拿不到应该选中的线

### ISSUE THREAD

**Issue by angular-nz** [antvis/X6#2190]
### Describe the bug

左键框选范围的时候 线  不会被选中， getSelectedCells拿不到应该选中的线，只能选中节点。目前我的节点是自定义的vue节点，节点可以选中，线不行

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

左键框选范围的时候 线  不会被选中， getSelectedCells拿不到应该选中的线，只能选中节点。目前我的节点是自定义的vue节点，节点可以选中，线不行

### Expected behavior

左键框选范围的时候 线  不会被选中， getSelectedCells拿不到应该选中的线，只能选中节点。目前我的节点是自定义的vue节点，节点可以选中，线不行

### Screenshots or Videos

![lQLPJxZhiQig5hbNAZXNApywHjQStIovrtYCoN48TEDnAA_668_405](https://user-images.githubusercontent.com/66048180/172322536-625b831f-f608-40a2-bc44-53fd3a8ad6ba.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows   Chrome 应该都有

**Comment by NewByVector** [comment]
需要开启 [rubberEdge](https://x6.antv.vision/zh/docs/tutorial/basic/selection#rubberband) 配置，才能选中连线。
