### ISSUE TITLE
选择多个的时候  移动单个节点整体会移动

### ISSUE THREAD

**Issue by meikang123** [antvis/X6#2192]
### Describe the bug

movable: false,
showNodeSelectionBox: true,
pointerEvents: 'none'

movable这个必须有这个showNodeSelectionBox才能移动单个节点，但是pointerEvents加上这个  就不起作用了

### Your Example Website or App
https://codesandbox.io/s/k3f7cp?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

可以单独移动节点

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
加上 `pointerEvents:none` 其实就不是移动选框了，而是直接操作节点，效果是正确的。
