### ISSUE TITLE
‘arrowheadMovable’配置不起作用

### ISSUE THREAD

**Issue by mjyg** [antvis/X6#2193]
### Describe the bug

想移动边的起始或终止箭头，如下配置，使用’arrowheadMovable‘属性不起作用

```
const graph = new Graph({
  container: document.getElementById('graph-container')!,
  interacting: {
    arrowheadMovable: true
  }...,
```
在官网上配置也一样，拖不动，如下图：
![image](https://user-images.githubusercontent.com/22444521/172546712-8ab6ee1f-3d70-4ecf-949f-7b714352da29.png)

### Your Example Website or App

https://x6.antv.vision/zh/examples/showcase/practices#flowchart

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

想移动边的起始或终止箭头

### Platform

- OS:macOS
- Browser: Chrome

**Comment by mjyg** [comment]
是不是少配置了什么，求大佬指教

**Comment by NewByVector** [comment]
移动起始和终止箭头，使用 [arrowhead](https://x6.antv.vision/zh/docs/api/registry/edge-tool#source-arrowhead-%E5%92%8C-target-arrowhead) 工具。

**Comment by TalorCC** [comment]
`//鼠标移入显示关闭（注意把里面的edge换成你自己定义的变量）
graph.on('edge:mouseenter', ({ edge }) => {
	edge.addTools([
		{
			name: 'source-arrowhead',
		},
		{
			name: 'target-arrowhead',
			args: {
				attrs: {
					fill: 'red',
				},
			},
		},
	])
})
//鼠标移出隐藏关闭
graph.on('edge:mouseleave', ({ edge }) => {
	edge.removeTools()
})
`
