### ISSUE TITLE
markup中attrs属性名被强行转换成蛇行命名风格

### ISSUE THREAD

**Issue by Blueria** [antvis/X6#2199]
### 问题描述

![image](https://user-images.githubusercontent.com/7038130/172750646-d25b613e-8459-4be7-a171-cee58d35e2f0.png)

上图是通过markup添加svg **path节点**，以及其**子节点animateTransform**，但是在浏览器中看到的是下面这样

![image](https://user-images.githubusercontent.com/7038130/172750719-4acb038b-c034-40c7-990b-bc93e46f9fe9.png)

其中，原本的驼峰命名的属性，变成了蛇行命名，这**直接导致了动画失效**

### 重现链接

--

### 重现步骤

--

### 预期行为

有什么办法能保持属性名大小写

### 平台

--

### 屏幕截图或视频（可选）

--

### 补充说明（可选）

--

**Comment by tonywu6** [comment]
<a href="https://twitter.com/dan_abramov/status/802236725712060416"><img width="594" alt="Screen Shot 2022-06-10 at 11 20 39" src="https://user-images.githubusercontent.com/93302820/172983875-7cde285a-2252-4149-b837-2a20a9ec9054.png"></a>

#1993 的延续。

当前我们的行为是在 JSON markup 声明中对**所有** camelCase 书写的属性名进行转写，这一点在文档中有提到，但是没有强调是“所有”

> [值得一提的是，支持使用小驼峰(camelCase)格式的属性名，如 'fontSize'，这就避免了 'font-size' 这种属性名作为对象 Key 时需要加引号的麻烦。](https://x6.antv.vision/zh/docs/api/model/cell#:~:text=%E5%80%BC%E5%BE%97%E4%B8%80%E6%8F%90%E7%9A%84%E6%98%AF%EF%BC%8C%E6%94%AF%E6%8C%81%E4%BD%BF%E7%94%A8%E5%B0%8F%E9%A9%BC%E5%B3%B0(camelCase)%E6%A0%BC%E5%BC%8F%E7%9A%84%E5%B1%9E%E6%80%A7%E5%90%8D%EF%BC%8C%E5%A6%82%20%27fontSize%27%EF%BC%8C%E8%BF%99%E5%B0%B1%E9%81%BF%E5%85%8D%E4%BA%86%20%27font%2Dsize%27%20%E8%BF%99%E7%A7%8D%E5%B1%9E%E6%80%A7%E5%90%8D%E4%BD%9C%E4%B8%BA%E5%AF%B9%E8%B1%A1%20Key%20%E6%97%B6%E9%9C%80%E8%A6%81%E5%8A%A0%E5%BC%95%E5%8F%B7%E7%9A%84%E9%BA%BB%E7%83%A6%E3%80%82)

https://github.com/antvis/X6/blob/8f7617a6de8ffaeb508ad7996a79aadee18b8389/packages/x6/src/view/markup.ts#L140-L143

在这里我们没有考虑到的问题是：虽然在 HTML 中属性名是不区分大小写，但是 SVG [继承自 XML](https://www.w3.org/TR/SVG11/intro.html) 而不是 HTML, 而 XML 的属性名是[区分大小写](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Introduction#:~:text=SVG%20elements%20and%20attributes%20should%20all%20be%20entered%20in%20the%20case%20shown%20here%20since%20XML%20is%20case%2Dsensitive%20(unlike%20HTML).)的。这时「自动转换 camelCase」的行为就会变得不可预测。

在 #1993 中，我们引入了一个“白名单”，在白名单中的属性将不会被转写。目前白名单里只有一项 `viewBox`, 我们可以将它扩展到所有可能的 camelCase 属性名（从 [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) 拿到）。

但是这样写死的方式不太美观，而且不能保证符合规范的正确性，需要后期不断去维护 —— 虽然之后大概率[不会](https://wiki.mozilla.org/SVG:Language:Regrets#Mixed_case_element_and_attribute_names)有新的大小写混写的元素和属性 —— 在之后的 2.0 版本中，取决于 markup 功能的去向，我们*可能*不会继续自动对 SVG 元素的属性进行大小写转写。

@NewByVector

**Comment by IVVII** [comment]
const loadingSvg = document.getElementsByTagName('animateTransform')
loadingSvg && loadingSvg.forEach((t) => {
      t && t.setAttribute('attributeType', 'xml' )
      t && t.setAttribute('attributeName', 'transform' )
      t && t.setAttribute('repeatCount', 'indefinite' )
})
手动添加动画属性，让他们动起来。
我之前也遇到这个问题了，想来提个bug 来着，忙忘了！！！

**Comment by IVVII** [comment]
@Blueria 

const loadingSvg = document.getElementsByTagName('animateTransform')

loadingSvg && loadingSvg.forEach((t) => {
      t.setAttribute('attributeType', 'xml' )
      t.setAttribute('attributeName', 'transform' )
       t.setAttribute('repeatCount', 'indefinite' )
 })

渲染完成之后，手动获取animateTransform 元素，并添加正确的动画属性，可以作为临时解决方案。

**Comment by tonywu6** [comment]
这里不如直接把 MDN 上所有混合大小写的 attributes 一次性加进来？不然之后可能还会有 issues

```js
// https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute
const MIXED_CASE_SVG_ATTRIBUTES = new Set([
  'attributeName',
  'attributeType',
  'baseFrequency',
  'baseProfile',
  'calcMode',
  'clipPathUnits',
  'contentScriptType',
  'contentStyleType',
  'diffuseConstant',
  'edgeMode',
  'filterRes',
  'filterUnits',
  'glyphRef',
  'gradientTransform',
  'gradientUnits',
  'kernelMatrix',
  'kernelUnitLength',
  'keyPoints',
  'keySplines',
  'keyTimes',
  'lengthAdjust',
  'limitingConeAngle',
  'markerHeight',
  'markerUnits',
  'markerWidth',
  'maskContentUnits',
  'maskUnits',
  'numOctaves',
  'pathLength',
  'patternContentUnits',
  'patternTransform',
  'patternUnits',
  'pointsAtX',
  'pointsAtY',
  'pointsAtZ',
  'preserveAlpha',
  'preserveAspectRatio',
  'primitiveUnits',
  'referrerPolicy',
  'refX',
  'refY',
  'repeatCount',
  'repeatDur',
  'requiredExtensions',
  'requiredFeatures',
  'specularConstant',
  'specularExponent',
  'spreadMethod',
  'startOffset',
  'stdDeviation',
  'stitchTiles',
  'surfaceScale',
  'systemLanguage',
  'tableValues',
  'targetX',
  'targetY',
  'textLength',
  'viewBox',
  'viewTarget',
  'xChannelSelector',
  'yChannelSelector',
  'zoomAndPan',
])
```
