### ISSUE TITLE
提供最佳视图功能

### ISSUE THREAD

**Issue by avrinfly** [antvis/X6#2202]
### 功能描述

场景：
在Scroller下，在滚动后，确定当前视图中心的点对应画布上的x和y

在找到这个坐标后，查找距离这个坐标一定范围内的节点集合

### 期望解决方案

提供基础api能够查找视图中心和四个位置对应的坐标

后续查找节点的集合可以通过坐标间距计算

**Comment by tonywu6** [comment]
目前我们有一个 `Graph.scroller.widget.getVisibleArea()` 函数，没有记录在文档中，但是有 TS 类型，它会返回当前 viewport 的几何信息，返回类型是一个 `Rectangle`

https://github.com/antvis/X6/blob/6b0259c42e78205fb9e213250f8d109375894ae8/packages/x6/src/geometry/rectangle.ts#L10-L13

其中 `x, y` 为 viewport 左上角的图坐标，`width, height` 为 viewport 投影到图上的尺寸，可以使用 `Rectangle.center()` 等方法获取中心点等其他位置。

我们可以将这个方法在 Graph 实例上公开，在那之前你可以先用 `getVisibleArea` 这个函数。

**Demo: https://codesandbox.io/s/antv-x6-viewport-projection-b97g03?file=/src/app.tsx:1129-1198**

**Comment by NewByVector** [comment]
可以使用 [graphToLocal](https://x6.antv.vision/zh/docs/api/graph/coordinate/#graphtolocal) 将视口中心点坐标转换为画布上的坐标。

**Comment by lexoring** [comment]
Hello. And how now to get the center of the graph in version 2?
