### ISSUE TITLE
ie11中不能拖动连接两个连接桩，会提示错误“DOMMatrix”未定义

### ISSUE THREAD

**Issue by yangxianxian** [antvis/X6#2203]
### Describe the bug

使用官网的图标实列中的流程图实例。拖动两个节点到画布中，然后拖动某个连接桩后报错，错误信息为：“DOMMatrix”未定义

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

暂无

### Expected behavior

暂无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
ie11

**Comment by tonywu6** [comment]
Hello!

x6 对 IE 11 的支持目前暂不完善，DOMMatrix 的问题之前已有报告。如果需要，可在 #1001 下查看讨论和 polyfill 解决。

关于 IE 支持，欢迎到讨论区主题 #2212 进行回复

**Comment by yangxianxian** [comment]
> Hello!
> 
> x6 对 IE 11 的支持目前暂不完善，DOMMatrix 的问题之前已有报告。如果需要，可在 #1001 下查看讨论和 polyfill 解决。
> 
> 关于 IE 支持，欢迎到讨论区主题 #2212 进行回复

可以提示一下如何使用polyfill 解决吗？

**Comment by tonywu6** [comment]
> 可以提示一下如何使用polyfill 解决吗？

https://github.com/antvis/X6/issues/1001#issuecomment-998421935
