### ISSUE TITLE
第二次调用fromJSON 报错  Cannot read properties of null (reading 'getZIndex')

### ISSUE THREAD

**Issue by thorin8** [antvis/X6#2210]
### 问题描述
经调试发现是renderer.js 828行，如下代码问题
this.sortElements(elems, (a, b) => {
    // 重写代码
    // let indexA = a.zIndex;
    // let indexB = b.zIndex;
    // return indexA==indexB?0:indexA<indexB?-1:1;

    const cellA = model.getCell(a.getAttribute('data-cell-id') || '');
    const cellB = model.getCell(b.getAttribute('data-cell-id') || '');
    //报错问题是cellA、cellB为null
    if(cellA && cellB){
        const z1 = cellA.getZIndex() || 0;
        const z2 = cellB.getZIndex() || 0;
        return z1 === z2 ? 0 : z1 < z2 ? -1 : 1;
    }
    return 0;
});

### 重现链接

无

### 重现步骤

1. 第一次调用fromJSON 正常
2. clearCells
3. 再次调用fromJSON报错

### 预期行为

我期望不报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by thorin8** [comment]
已通过重写方法解决
    
    let renderer = this.g.renderer
    renderer.sortViewsExact = () => {
      const elems = renderer.view
        .$(renderer.view.stage)
        .children('[data-cell-id]')
        .toArray()
      const placements = elems.map((elem) => {
        const parentNode = elem.parentNode
        const nextSibling = parentNode.insertBefore(
          document.createTextNode(''),
          elem.nextSibling
        )
        return (targetNode) => {
          if (parentNode === targetNode) {
            throw new Error(
              "You can't sort elements if any one is a descendant of another."
            )
          }
          parentNode.insertBefore(targetNode, nextSibling)
          parentNode.removeChild(nextSibling)
        }
      })
      elems
        .sort((a: any, b: any) => {
          // 重写代码
          let indexA = a.zIndex
          let indexB = b.zIndex
          return indexA == indexB ? 0 : indexA < indexB ? -1 : 1
        })
        .forEach((elem, index) => placements[index](elem))
    }

**Comment by tonywu6** [comment]
Hello! 可以提供一个代码重现吗？可以使用这个 [CodeSandbox 模版](https://codesandbox.io/s/antv-x6-minimal-application-6fzpvu?file=/src/index.ts)
