### ISSUE TITLE
 Vue 2 + vite throws a component rendering error due to missing as it was in vue cli - runtimeCompiler

### ISSUE THREAD

**Issue by verron16** [antvis/X6#2213]
### Describe the bug

![image](https://user-images.githubusercontent.com/61470621/173224323-e7362751-7dbe-4081-818d-65a4dfffedc3.png)

I use vue-shape to render nodes, but this is what vite gives me when loading the scheme, the nodes are not rendered

![image](https://user-images.githubusercontent.com/61470621/173224516-41722091-6aab-488e-a79e-dd56ae598250.png)

![image](https://user-images.githubusercontent.com/61470621/173224669-e1781b78-e895-45e9-8e8f-d001994dc11c.png)

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

Use vite with vue 2 and try rendering nodes with vue shape

### Expected behavior

So that vite + vue 2 can render quietly vue nodes

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lloydzhou** [comment]
@verron16 
https://github.com/vitejs/vite/discussions/4158

![image](https://user-images.githubusercontent.com/1826685/173740099-3bf76dae-7b9b-42eb-b6ea-8474a26929d6.png)

**Comment by NewByVector** [comment]
希望这个[链接](https://stackoverflow.com/questions/47332728/you-are-using-the-runtime-only-build-of-vue-where-the-template-compiler-is-not-a)能帮到你。

**Comment by verron16** [comment]
> @verron16 [vitjs/vite#4158](https://github.com/vitejs/vite/discussions/4158)
> 
> ![изображение](https://user-images.githubusercontent.com/1826685/173740099-3bf76dae-7b9b-42eb-b6ea-8474a26929d6.png)

Very good, thanks!
