### ISSUE TITLE
validateMagnet 返回false，拖拽port可以移动node

### ISSUE THREAD

**Issue by fanmingfei** [antvis/X6#2216]
### Describe the bug

如题

### Your Example Website or App

https://codesandbox.io/s/vibrant-glitter-opl1r4

### Steps to Reproduce the Bug or Issue

如题

### Expected behavior

拖拽port无响应

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
更新到 v1.32.4 版本。

**Comment by naanna** [comment]
> 更新到 v1.32.4 版本。

为什么升级完了也还是会？最新版本了

**Comment by fanmingfei** [comment]
点我发的demo是有问题的吗 @naanna

**Comment by wflixu** [comment]
> > 更新到 v1.32.4 版本。
> 
> 为什么升级完了也还是会？最新版本了

你确定是v1.32.4 版本

**Comment by naanna** [comment]
> > > 更新到 v1.32.4 版本。
> > 
> > 
> > 为什么升级完了也还是会？最新版本了
> 
> 你确定是v1.32.4 版本

是最新的，升级后在业务里发现的

**Comment by NewByVector** [comment]
@naanna 有可以复现的 demo 帮助排查问题吗，有的话可以开一个新的 issue.
