### ISSUE TITLE
力导向布局增加动态布局

### ISSUE THREAD

**Issue by yaojin2070** [antvis/X6#2223]
### 功能描述

之前也有issue提过 https://github.com/antvis/X6/issues/845, 就是拖动某个节点,其他节点会随之变动
不知道如何实现这个需求呢, 而且例子中,我尝试将shape改成html, 无法实现
![image](https://user-images.githubusercontent.com/48686959/173815607-2b7f6526-6c23-4888-a87b-49df95556cdb.png)

我在想是否可以尝试使用d3-force https://github.com/d3/d3-force 来实现这个需求? 奈何我技术有限, 期待出一个demo

### 期望解决方案

期待增加力导向动态布局, 可以使用html来自定义节点

**Comment by NewByVector** [comment]
布局和 html 节点都是支持的，不知道你的问题具体在？

**Comment by yaojin2070** [comment]
> 布局和 html 节点都是支持的，不知道你的问题具体在？
![image](https://user-images.githubusercontent.com/48686959/173826120-1122bbf2-b727-4bc5-87c6-167c42fec8ed.png)
不支持html类型的shape, 还有不支持节点拖动的时候, 会改变它的位置
![image](https://user-images.githubusercontent.com/48686959/173826474-a819bb8d-06a2-4c78-a4de-8c1031410c65.png)

**Comment by NewByVector** [comment]
你这个使用方式有问题， html 节点需要通过注册的方式才能反序列化，可以先看下 html 节点渲染[文档](https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-html-%E8%8A%82%E7%82%B9)。

**Comment by yaojin2070** [comment]
> 你这个使用方式有问题， html 节点需要通过注册的方式才能反序列化，可以先看下 html 节点渲染[文档](https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-html-%E8%8A%82%E7%82%B9)。

大哥, 能出一个动态改变位置的demo或者代码吗? 就是拖动某个节点,其他节点会变动, https://g6.antv.vision/zh/examples/net/forceDirected#forceDirectedConfigurationTranslate 类似于这个, 实在是无从下手了

**Comment by yaojin2070** [comment]
> 你这个使用方式有问题， html 节点需要通过注册的方式才能反序列化，可以先看下 html 节点渲染[文档](https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-html-%E8%8A%82%E7%82%B9)。


![image](https://user-images.githubusercontent.com/48686959/173982203-62e08419-2a74-4246-a533-23c8f3500300.png)

我看了一下force布局的一些源码还有d3-force的文档, 我看是改给仿真节点添加fx, 和fy就可以改变它的位置, 在设置为null, 可是并没有效果, 这个仿真节点到底是谁
![image](https://user-images.githubusercontent.com/48686959/173982231-5d3a9061-ad7a-4c29-ad79-23e70bd8ad57.png)
![image](https://user-images.githubusercontent.com/48686959/173982287-560b27ac-db7c-4e07-945d-38a0e5730488.png)

**Comment by NewByVector** [comment]
力导向布局的文档参考[这里](https://g6.antv.vision/zh/docs/api/graphLayout/force)。
