### ISSUE TITLE
回撤 edge目标点 错误

### ISSUE THREAD

**Issue by angular-nz** [antvis/X6#2225]
### Describe the bug

回撤 edge目标点 错误

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

1：创建两个节点 2： 连接一条线 3：ctrl z 4： ctrl shift z

### Expected behavior

应该连接上

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/66048180/173990617-7a175f54-d31a-4921-9d19-0f640a282f02.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
有可以复现的 demo 看下吗？

**Comment by NewByVector** [comment]
因为没有可以复现的 demo，我们暂时关闭这个 issue，如果还有问题，请重新提一个 issue，并附上可以复现的 codesanbox 链接。
