### ISSUE TITLE
使用JSON.parse(JSON.stringify())格式化画布节点toJSON导出的数据时，爆栈错误

### ISSUE THREAD

**Issue by SillyBoyXZH** [antvis/X6#2231]
### Describe the bug

使用JSON.parse(JSON.stringify())格式化画布节点toJSON导出的数据时，爆栈错误。

使用graph.toJSON()生成的画布节点数据，进行深拷贝时报错

![0PHddgt57g](https://user-images.githubusercontent.com/82207908/174214349-8ff4c76e-cb70-4f1f-b8de-2668cb061f3b.png)

<img width="716" alt="image" src="https://user-images.githubusercontent.com/82207908/174214326-2547a353-e172-436f-bce6-55bb42e6becc.png">

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

like the picture

### Expected behavior

find and deal with the question

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
有可以复现的 demo 吗？

**Comment by SillyBoyXZH** [comment]
> 

我拆分一下试试

**Comment by NewByVector** [comment]
因为没有可以复现的 demo，我们暂时关闭这个 issue，如果还有问题，请重新提一个 issue，并附上可以复现的 codesanbox 链接。

**Comment by nanfb** [comment]
> > 
> 
> 我拆一下试

解决了吗？

**Comment by xiazhaohui** [comment]
> > > 
> > 
> > 
> > 我拆一下试
> 
> 解决了吗？

在执行JSON.stringify()格式化前，将存在循环引用的graph数据给过滤掉了，这样下来就不再报错

**Comment by nanfb** [comment]
> > > > 
> > > 
> > > 
> > > 我拆下试
> > 
> > 
> > 解决了吗？
> 
> 在执行JSON.stringify()格式化前，将存在于循环引用的图表数据给过滤掉了，这样下去就不会再报错@nanfb

只有edge的数据序列化会造成栈溢出，您说的循环引用我在edge数据里找不到，可以详细说下吗

**Comment by xiazhaohui** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 我拆下试
> > > 
> > > 
> > > 解决了吗？
> > 
> > 
> > 在执行JSON.stringify()格式化前，将存在于循环引用的图表数据给过滤掉了，这样下去就不会再报错@nanfb
> 
> 只有edge的数据序列化会造成栈溢出，您说的循环引用我在edge数据里找不到，可以详细说下吗

https://github.com/antvis/X6/issues/2257这个

**Comment by nanfb** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 我拆下试
> > > > 
> > > > 
> > > > 解决了吗？
> > > 
> > > 
> > > 在执行JSON.stringify()格式化前，将存在于循环引用的图表数据给过滤掉了，这样下去就不会再报错@nanfb
> > 
> > 
> > 只有edge的数据序列化会造成栈溢出，您说的循环引用我在edge数据里找不到，可以详细说下吗
> 
> #2257
> 
> 看这个issue

不太一样，我们是vue项目，我采用自定义节点的方式注册节点，如果你有空的话我可以发你gitee链接你拉下来
看看

**Comment by xiazhaohui** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 我拆下试
> > > > > 
> > > > > 
> > > > > 解决了吗？
> > > > 
> > > > 
> > > > 在执行JSON.stringify()格式化前，将存在于循环引用的图表数据给过滤掉了，这样下去就不会再报错@nanfb
> > > 
> > > 
> > > 只有edge的数据序列化会造成栈溢出，您说的循环引用我在edge数据里找不到，可以详细说下吗
> > 
> > 
> > #2257
> > 看这个issue
> 
> 不太一样，我们是vue项目，我采用自定义节点的方式注册节点，如果你有空的话我可以发你gitee链接你拉下来 看看

你可以先用这个思路试试，就是在格式化过程中，哪个数据出现爆栈就把哪个数据给过滤掉。

**Comment by nanfb** [comment]
> 

是这样的，如果全是节点的话不会爆栈，一旦创建链接桩把两个节点链接起来，所有的节点都会爆栈，包括之前不会爆栈的节点，但是如果边链接在空地方是不会爆栈的，就很离谱

**Comment by xiazhaohui** [comment]
> > 
> 
> 是这样的，如果全是节点的话不会爆栈，一旦创建链接桩把两个节点链接起来，所有的节点都会爆栈，包括之前不会爆栈的节点，但是如果边链接在空地方是不会爆栈的，就很离谱

这个场景没遇到过 不太懂 哈哈

**Comment by nanfb** [comment]
> > > 
> > 
> > 
> > 是这样的，如果全是节点的话不会爆栈，一旦创建链接桩把两个节点链接起来，所有的节点都会爆栈，包括之前不会爆栈的节点，但是如果边链接在空地方是不会爆栈的，就很离谱
> 
> 这个场景没遇到过 不太懂 哈哈

好吧~我再研究研究

**Comment by nanfb** [comment]
> > > > 
> > > 
> > > 
> > > 是这样的，如果全是节点的话不会爆栈，一旦创建链接桩把两个节点链接起来，所有的节点都会爆栈，包括之前不会爆栈的节点，但是如果边链接在空地方是不会爆栈的，就很离谱
> > 
> > 
> > 这个场景没遇到过 不太懂 哈哈
> 
> 好吧~我再研究研究

大概定位什么问题了，我把监听链接事件把节点放到attrs中去了

**Comment by xiazhaohui** [comment]
> 

那解决了吧

**Comment by nanfb** [comment]
> > 
> 
> 那解决了吧

差不多，我用nodeid来代替了
