### ISSUE TITLE
The Errror About History Module

### ISSUE THREAD

**Issue by oxiran** [antvis/X6#2238]
#### 场景

通过拖动某个节点到目标节点，形成嵌套关系，在撤销时无法回到拖动节点前的状态。
***
 
其实在这里有好几个操作会被放进 **commands** 里面，包括 `cell:change:isParent`、`cell:change:isChild`、`cell:change:visible`、`cell:change:position`等等。
 
我想把它们合并成一个 **history command**，通过 `history.undo` 回到拖动嵌入前的状态，我尝试过把 `node:embedded` 后的操作包在一个 `batch` 里面，配合 `history. beforeAddCommand ` 实现这个功能，但都达不到预期效果，调用 `history.undo` 后历史操作错乱。

### Your Example Website or App

https://codesandbox.io/s/vigilant-sea-37wlpg?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

+ 打开上面的 [codesandbox](https://codesandbox.io/s/vigilant-sea-37wlpg?file=/src/app.tsx) 链接
+ 拖动 **node1** 进入 **node2** 形成嵌套关系，此时 **node2** 变成父节点并收起子节点
+ 点击 **Undo** 按钮撤销以上的操作

点击 **Undo** 按钮后并没有到达期望的行为

### Expected behavior

点击 **Undo** 按钮或调用 `history.undo` 后，撤回到节点拖动嵌入前的状态

### Screenshots or Videos

<img width="722" alt="image" src="https://user-images.githubusercontent.com/31892817/174250243-787ca865-63c1-445e-8a4a-53d3d428dcc6.png">

### Platform

- OS: [macOS, Windows]
- Browser: [Chrome, Safari, Firefox]
- Version: [latest]

**Comment by NewByVector** [comment]
Fix in https://github.com/antvis/X6/pull/2197

**Comment by oxiran** [comment]
> Fix in #2197

Which version for 1.x ? [#2197](https://github.com/antvis/X6/pull/2197) was fixed another bug by me.
