### ISSUE TITLE
connecting 的createEdge 参数中添加port 数据

### ISSUE THREAD

**Issue by lyon-liao** [antvis/X6#2241]
### 功能描述

一个Node 上有类型A, 和类型B 两种port,  当类型A 的port 拉出的线需要是实线，类型B 拉出的线应该为虚线。

然而现在的参数中只有以下几个值，都没法获取到对应的port 的类型。
![image](https://user-images.githubusercontent.com/3927282/174432236-ef49bd38-16d6-4d3d-a71b-76e33c0977b3.png)

### 期望解决方案

期望在参数中天加port 的数据。

**Comment by lyon-liao** [comment]
`sourceMagnet` 上有个`port` 属性，值为 `port` 的ID

**Comment by Aiamjay** [comment]
老哥 你这个地方是怎么做到的，能给一个demo吗？ 我的magnet 里面没有id

**Comment by lyon-liao** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/3927282/185793538-7b5869cd-42d7-439b-b33d-e2d9c04024b9.png">
