### ISSUE TITLE
怎么配置图形节点移动的距离

### ISSUE THREAD

**Issue by MrMengJ** [antvis/X6#2244]
### 功能描述

现在节点移动的阈值好像是20px，每次拖拽动作会让图形移动20px，有配置项配置每次移动的距离吗

![move distance](https://user-images.githubusercontent.com/26325346/174547746-0e8923ea-15a4-4f5e-9eb0-4cb6ec48bbfc.gif)

### 期望解决方案

看是否有配置项配置，若无配置项希望提供下关键代码所在位置，看能不能提一个pr

**Comment by MrMengJ** [comment]
@NewByVector 想将每次移动是否对齐网格这个特性配置化，由使用者自己决定，接受PR吗

**Comment by NewByVector** [comment]
暂时还没有计划优化这块。改动比较大。

**Comment by MrLiuleizhi** [comment]
需求+1，能不能把grid的size和每次节点移动的距离分成两个属性配置，想保留表格，但是表格会限制节点移动
