### ISSUE TITLE
如何编辑框内内容

### ISSUE THREAD

**Issue by zaizizaizai** [antvis/X6#2247]
### 功能描述

是否可以支持编辑框内内容，并将内容写回json

### 期望解决方案

是否可以支持编辑框内内容，并将内容写回json

**Comment by NewByVector** [comment]
@zaizizaizai 上面的回复是否解决了你的问题，我们暂时关闭这个 issue，如果还有问题，请重新提一个 issue，并附上可以复现的 codesanbox 链接。
