### ISSUE TITLE
shift键多选图形

### ISSUE THREAD

**Issue by MrMengJ** [antvis/X6#2248]
### 功能描述

现在多选只能是ctrl键多选图形，是否支持shift键多选图形呢

### 期望解决方案

若现在不支持shfit键多选图形，是否接受pr来实现这种特性呢。
接受的话麻烦指一下关键代码所在位置，谢谢啦

**Comment by NewByVector** [comment]
使用 [modifiers](https://x6.antv.vision/zh/docs/tutorial/basic/selection#modifiers) 配置可以支持 shift 多选。

**Comment by MrMengJ** [comment]
> 你是指点选是吧？可以看下[这里](https://github.com/antvis/X6/blob/df47d90889703cc3d421069b1859eadc2c30916b/packages/x6/src/graph/selection.ts#L83)

好的，是指点选多选，我看看
