### ISSUE TITLE
自定义节点组件调用graph

### ISSUE THREAD

**Issue by BrickerZou** [antvis/X6#2257]
### Describe the bug

我通过props传递graph到自定义节点组件，进行一些graph的方法，但这似乎不是正确的做法
![image](https://user-images.githubusercontent.com/73508461/175193349-f6a773ea-cb24-4223-a4f4-11ea157a8395.png)

当我打印出ToJson()时，其props中的graph**无限递归**。
![image](https://user-images.githubusercontent.com/73508461/175193349-f6a773ea-cb24-4223-a4f4-11ea157a8395.png)

### Your Example Website or App

https://codesandbox.io/s/restless-cdn-21ulm3?file=/src/MyComponent.ts

### Steps to Reproduce the Bug or Issue

yarn start

### Expected behavior

如何才是正确的做法，自定义节点组件中调用graph的一些方法？

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/73508461/175193327-dfdaf5fc-c5be-46ac-bd8b-6ae6ef7f92fd.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SillyBoyXZH** [comment]
Demo好像有点问题

**Comment by BrickerZou** [comment]
> Demo好像有点问题

https://codesandbox.io/s/restless-cdn-21ulm3?file=/src/MyCompoment.tsx

**Comment by BrickerZou** [comment]
接上面的截图一样的问题
![image](https://user-images.githubusercontent.com/73508461/175251299-da4cf33e-d6cd-48c8-9eb9-b6e4bbd6962e.png)

![image](https://user-images.githubusercontent.com/73508461/175251237-cf4e8a57-ff1d-4c78-86b3-5ca8930ec9b8.png)
无限递归

**Comment by BrickerZou** [comment]
> 我也遇到此类似问题，toJSON之后，使用JSON.stringify()序列化，报错爆栈。检查之后发现也是递归循环导致的
> 
> <img alt="image" width="1053" src="https://user-images.githubusercontent.com/82207908/175254058-e5255fa9-d734-407e-84da-822019071c05.png">
> 
> <img alt="image" width="603" src="https://user-images.githubusercontent.com/82207908/175253622-6216ed12-a2c0-4ced-8bbe-1d551a812fd9.png">

和你一样的问题，不知道哪出bug了

**Comment by SillyBoyXZH** [comment]
> 

循环引用了

**Comment by BrickerZou** [comment]
没找到在哪

**Comment by SillyBoyXZH** [comment]
> 你是怎么解决的

目前只是异常捕获，还没做处理，还没定位到具体哪里

**Comment by BrickerZou** [comment]
好兄弟，解决了后指点指点。

**Comment by SillyBoyXZH** [comment]
> 好兄弟，解决了后指点指点。

同是天涯沦落人，同指点。
感觉关键还是多理解一下API，看透了应该就知道问题出在哪里

**Comment by tonywu6** [comment]
Hello! React 组件配合 `toJSON()` 使用需要注意的事情以及一些解决方法，在[文档的这里](https://x6.antv.vision/zh/docs/tutorial/advanced/react#:~:text=%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F%E7%9A%84%E6%98%AF%EF%BC%8C%E5%BD%93%20component%20%E4%B8%BA%20React%20%E7%BB%84%E4%BB%B6%E6%88%96%E5%87%BD%E6%95%B0%E6%97%B6%EF%BC%8C%E5%B0%86%E4%B8%8D%E8%83%BD%E9%80%9A%E8%BF%87%20graph.toJSON()%20%E6%96%B9%E6%B3%95%E5%AF%BC%E5%87%BA%E7%94%BB%E5%B8%83%E6%95%B0%E6%8D%AE%E3%80%82%E6%89%80%E4%BB%A5%E6%88%91%E4%BB%AC%E6%8F%90%E4%BE%9B%E4%BA%86%E4%BB%A5%E4%B8%8B%E4%B8%A4%E7%A7%8D%E6%96%B9%E6%A1%88%E6%9D%A5%E8%A7%A3%E5%86%B3%E6%95%B0%E6%8D%AE%E5%AF%BC%E5%87%BA%E9%97%AE%E9%A2%98%E3%80%82)有提到：

<img width="964" alt="Screen Shot 2022-06-24 at 5 30 32 PM" src="https://user-images.githubusercontent.com/93302820/175507384-f86555da-d692-4a2e-9f0e-50ec51b8f812.png">

大概的建议做法是将 React 组件函数/类事先注册到全局 `Graph` 下，然后在 `addNode` 时使用字符串形式引用注册好的组件（具体见文档）

```tsx
// 使用 Graph.registerNode(...) 方法将 React 组件注册到系统中。

Graph.registerNode('my-node', {
  inherit: 'react-shape',
  x: 200,
  y: 150,
  width: 150,
  height: 100,
  component: <MyComponent />
})

// 然后将节点的 shape 属性指定为注册的节点名称

graph.addNode({
  x: 40,
  y: 40,
  width: 100,
  height: 40,
  shape: 'my-node',
})
```

---

#### 技术细节

具体来讲，发生堆栈溢出的原因在于 1) `Graph` 被作为 props 传给了 React 元素 + 2) `Graph.toJSON()` 输出的内容包含 React 元素 + 3) `toJSON()` 方法在 native JavaScript 中有特殊语义：

1. 如 @SillyBoyXZH 提到的，React element 和 Graph 存在循环引用，这是因为 React element 会将 Graph 作为 props, 但是 Graph 又需要将这个 element 保存在内部的 model 里；
2. 在 native JavaScript 中，[`JSON.stringify()` 对任何 object 带有的 `toJSON()` 作特殊处理](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior)：如果一个 object 带有 `toJSON()`, 那么 `JSON.stringify` 使用这个方法返回的值进行序列化

当我们进行 `JSON.stringify(graph.toJSON())` 时：

`stringify` 对序列化的数据做递归处理
→ `stringify` 遇到自定义的 React 元素
→ 对 React 元素做递归处理
→ `stringify` 遇到 graph 对象（在 props 里）
→ `stringify` 调用 `graph.toJSON()`
→ `stringify` 对序列化的数据做递归处理
→ （...循环）

如果我们采用「事先注册元素」的方法，那么 React 元素就不会在 graph 内部保存（只是保存了它的名字），那么就不会出现这样的循环调用（当然，如果存在其它的循环引用，还是会出现堆栈溢出的）.

**Comment by SillyBoyXZH** [comment]
> 

下周我试试。
之前写的时候也注意到这点了，要注册一下组件再使， 但是当时有侥幸心理，感觉不注册也能正常使用且没有任何报错等信息。

@tonywu6 如君所言，我再试试，兄弟你也试试 @BrickerZou ，有任何情况我来同步

**Comment by BrickerZou** [comment]
试了，似乎没变化

> > 
> 
> 下周我试试。 之前写的时候也注意到这点了，要注册一下组件再使， 但是当时有侥幸心理，感觉不注册也能正常使用且没有任何报错等信息。
> 
> @tonywu6 如君所言，我再试试，兄弟你也试试 @BrickerZou ，有任何情况我来同步

试了下，似乎没变化

**Comment by BrickerZou** [comment]
不过我找了原因，就是因为graph 被作为 props 传给了 React 元素
![image](https://user-images.githubusercontent.com/73508461/175557560-8dcb978e-e469-4de2-ab55-37795fb7a6b9.png)
删去就没这个错误了。
但是如果不用prop传graph 那么我该如何调用graph的方法。
![image](https://user-images.githubusercontent.com/73508461/175557698-5bc41be5-35c5-46cc-8085-d841feecedc0.png)

**Comment by SillyBoyXZH** [comment]
> 

so 注册之后还是使用toJSON()到处数据是吧

**Comment by BrickerZou** [comment]
> 

是的

**Comment by SillyBoyXZH** [comment]
我是用第二个注册到系统的方法，试了下，也不行，还是有那种报错
@tonywu6 

```
Graph.registerReactComponent('custom-trigger-cell', <TouchConditionGraphDom/>)
Graph.registerReactComponent('custom-judge-cell', <JudgeConditionGraphDom/>)
Graph.registerReactComponent('custom-execute-cell', <ExecuteActionGraphDom/>)
```

how about you? @BrickerZou

**Comment by NewByVector** [comment]
@BrickerZou 不推荐在 react 组件内部再使用 graph，如果实在有必要的话，可以这样：
```ts
const graph = node.model.graph;
```
