### ISSUE TITLE
disableSelection()和disableSelectionMovable()方法无效

### ISSUE THREAD

**Issue by fangchenyong** [antvis/X6#2264]
### Describe the bug

disableSelection()和disableSelectionMovable()方法无效，我禁用了选择还是能够选择。
https://antv-x6.gitee.io/zh/docs/api/graph/selecting#%E6%96%B9%E6%B3%95
提供的demo中Selection Movable选项关闭了但还是能够移动选中的节点

### Your Example Website or App

https://antv-x6.gitee.io/zh/docs/api/graph/selecting#%E6%96%B9%E6%B3%95

### Steps to Reproduce the Bug or Issue

https://antv-x6.gitee.io/zh/docs/api/graph/selecting#%E6%96%B9%E6%B3%95

### Expected behavior

希望能够对画布进行操作限制，能够禁用dnd拖拽，能够实现不能选中节点或者不能选中节点进行移动，

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
有可以复现的链接可以看下吗？
