### ISSUE TITLE
miniMap如何预览真实图形

### ISSUE THREAD

**Issue by MrMengJ** [antvis/X6#2267]
### 功能描述

![image](https://user-images.githubusercontent.com/26325346/175882441-95677023-43b0-45ad-9643-0543f019f805.png)
如图所示，如何让miniMap显示流程图真实的样子

### 期望解决方案

如何让miniMap显示流程图真实的样子

**Comment by NewByVector** [comment]
不设置 getCellView 配置，默认就是显示原来图形。
