### ISSUE TITLE
请问这种连线怎么设置不重合

### ISSUE THREAD

**Issue by web-xp** [antvis/X6#2268]
### 问题描述

连线

### 重现链接

连线

### 重现步骤

![image](https://user-images.githubusercontent.com/59134195/175893475-8c0acfef-84a4-4cf2-9723-02ad9e2dcc8e.png)

### 预期行为

连线

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以参考这个 [demo](https://codesandbox.io/s/bi-mian-lian-xian-chong-he-kezrfm)

**Comment by NewByVector** [comment]
请问上面的回答有解决你的问题吗，为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。
