### ISSUE TITLE
希望能支持粘贴节点时新生成的节点在鼠标的位置生成

### ISSUE THREAD

**Issue by mjyg** [antvis/X6#2274]
### 功能描述

希望能支持粘贴节点时新生成的节点在鼠标的位置生成

### 期望解决方案

鼠标右键粘贴节点时，生成的节点在鼠标的位置生成

**Comment by web-xp** [comment]
我昨天实现了

**Comment by web-xp** [comment]
![image](https://user-images.githubusercontent.com/59134195/176115339-09dc7a49-b2b3-44cb-9e61-022cdb9787e7.png)
![image](https://user-images.githubusercontent.com/59134195/176115486-5b698ae6-0479-42d0-a3fc-411810916630.png)
右击保存x,y 粘贴把x,y给position

**Comment by 15643701048a** [comment]
那么如果复制了多个节点与连线，怎么粘贴呢

**Comment by 15643701048a** [comment]
那样不就都复制到同一处地方，重叠了吗，如果取消选中，也没法再复制了

**Comment by web-xp** [comment]
![image](https://user-images.githubusercontent.com/59134195/176405276-ef4238cb-699e-434f-bc6f-a9e853945452.png)
这样可以粘贴多个节点

**Comment by NewByVector** [comment]
请问上面的回答有解决你的问题吗，为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。
