### ISSUE TITLE
connecting allowNode 如果使用函数的话，返回false，也无法连接到port上

### ISSUE THREAD

**Issue by fanmingfei** [antvis/X6#2275]
### Describe the bug

connecting allowNode 如果使用函数的话，返回false，无法连接到Node的同时，也无法连接到port上。但是如果不使用函数的方式设置，直接使用boolean类型设置的话，是可以连接到port上的。理论上是可以连接到port上的

### Your Example Website or App

https://codesandbox.io/s/magical-swanson-0qwq9t?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

见上述demo网站
```js
  connecting: {
        allowNode: ()=>false,
        // allowNode: false, // 直接使用值是可以的
        validateConnection: ()=>true,
        validateMagnet: ()=>true,
        validateEdge: ()=>true
      }
```

### Expected behavior

希望能够表现一致，和直接设置boolean一样。

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.32.3

**Comment by NewByVector** [comment]
升级到新的版本 1.32.5
