### ISSUE TITLE
如果node链接桩过多，且设置了链接桩吸附，会出现部分桩无法链接的问题

### ISSUE THREAD

**Issue by vsdde** [antvis/X6#2276]
### Describe the bug

如上
![22339](https://user-images.githubusercontent.com/49269295/176131238-e6f04cd2-f641-4a88-a8b4-091584b0d87c.png)

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

暂无

### Expected behavior

暂无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
按照经验可以把吸附范围缩小一点，有可以复现的 demo 吗？

**Comment by NewByVector** [comment]
为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。
