### ISSUE TITLE
连接线文本编辑位置不正确

### ISSUE THREAD

**Issue by MrMengJ** [antvis/X6#2277]
### 问题描述

在节点图形进入编辑态时，再点击连接线进入编辑态，连接线编辑态位置不正确

### 重现链接

https://codesandbox.io/s/pw48wi

### 重现步骤

1、双击节点图形，进入文本编辑态
2、双击连接线文本进入文本编辑态，编辑态位置不正确

### 预期行为

连接线文本编辑态位置正确

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.32.4]

### 屏幕截图或视频（可选）

![edgeLabelPosition](https://user-images.githubusercontent.com/26325346/176140664-224b013e-41f4-4ba8-983e-307d5ca75523.gif)

**Comment by NewByVector** [comment]
这个只能外部去实现，在 dbclick 的时候，删除其他 editor 工具:
```ts
graph.on('cell:dblclick', ({ cell, e }) => {
  const name = cell.isEdge() ? 'edge-editor' : 'node-editor'
  const cells = graph.getCells()
  cells.forEach(cell => {
    cell.removeTool('node-editor')
    cell.removeTool('edge-editor')
  })
  cell.addTools([
    {
      name,
      args: {
        event: e,
      },
    },
  ])
})
```
