### ISSUE TITLE
如何设置画布大小

### ISSUE THREAD

**Issue by MrMengJ** [antvis/X6#2278]
### 功能描述

你好，请问如何设置画布大小?
现在需要将画布设置为指定大小，请问我是该设置[graph#width](https://antv-x6.gitee.io/zh/docs/api/graph/graph#width)，还是设置[scroller#pagewidth](https://antv-x6.gitee.io/zh/docs/api/graph/scroller#pagewidth)呢？
这两个的区别是啥呢

### 期望解决方案

正确设置画布大小

**Comment by NewByVector** [comment]
使用方法,下面方法会根据是普通画布还是 scroller 画布，有不同的行为。
```
graph.resize(width, height)
```
