### ISSUE TITLE
移动链接点时不会触发cell:mouseenter事件

### ISSUE THREAD

**Issue by qinqiuxia** [antvis/X6#2284]
### 问题描述

我为edge添加了target-arrowhead类型的tool，然后按住target-arrowhead的点拖动切换要链接的cell。鼠标经过cell时未触发cell:mouseenter事件

### 重现链接

https://codesandbox.io/s/affectionate-bose-y9mxzn?file=/src/index.js

### 重现步骤

1. 鼠标移入链接线出现链接点
2. 拖动链接点到某个cell
3. 未触发cell:mouseenter事件

### 预期行为

正常触发cell:mouseenter事件

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.32.2]

**Comment by NewByVector** [comment]
因为拖动过程中鼠标是悬浮于 arrowhead 工具上，而不是节点上面，所以不会触发节点的 mouseenter 事件。

**Comment by NewByVector** [comment]
请问上面的回答有解决你的问题吗，为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。
