### ISSUE TITLE
不使用port直接连接两个node

### ISSUE THREAD

**Issue by recolzhao** [antvis/X6#2293]
### 功能描述

1、前置条件：画布、node不可移动
2、点击一个node连接到另一个node，不使用port连接

### 期望解决方案

未找到相应api，使用createEdge可以解决，但是没有鼠标移动时绘制的路径

**Comment by fanmingfei** [comment]
给 node 的 attrs body 里面加magnet属性
```
 attrs: {
    body: {
      magnet: true,
      strokeWidth: 0,
      fill: '#ccc',
    }
  }
```

**Comment by recolzhao** [comment]
> 给 node 的 attrs body 里面加magnet属性
> 
> ```
>  attrs: {
>     body: {
>       magnet: true,
>       strokeWidth: 0,
>       fill: '#ccc',
>     }
>   }
> ```

**Comment by recolzhao** [comment]
>这个在以前的issue看到了，加上了以后不好使。可能我哪里的条件设置的不对，我再看看。感谢

**Comment by recolzhao** [comment]
> 给 node 的 attrs body 里面加magnet属性
> 
> ```
>  attrs: {
>     body: {
>       magnet: true,
>       strokeWidth: 0,
>       fill: '#ccc',
>     }
>   }
> ```
这个在以前的issue看到了，加上了以后不好使。可能我哪里的条件设置的不对，我再看看。感谢

**Comment by 695648896** [comment]
@recolzhao 你好，请问问题解决了吗 我也碰到类似的问题 按 @fanmingfei 给的方式并没有生效

**Comment by recolzhao** [comment]
> @recolzhao 你好，请问问题解决了吗 我也碰到类似的问题 按 @fanmingfei 给的方式并没有生效
用了其他的方法，把port放大，将node包裹，调整port的z-index，这样就可以拖拽node，用node边缘的port连线

**Comment by recolzhao** [comment]
> @recolzhao 你好，请问问题解决了吗 我也碰到类似的问题 按 @fanmingfei 给的方式并没有生效
用了其他的方法，把port放大，将node包裹，调整port的z-index，这样就可以拖拽node，用node边缘的port连线
