### ISSUE TITLE
dag流程图如何更据节点的运行状态切换不同的图标还有动态链路

### ISSUE THREAD

**Issue by kuokay** [antvis/X6#2297]
### 问题描述

dag流程图如何更据节点的运行状态切换不同的图标还有动态流动链路如何实现，呢个是需要改配置就行还是需要自己写一个函数实现。

### 重现链接

无

### 重现步骤

无

### 预期行为

![image](https://user-images.githubusercontent.com/60090512/176824758-606e2dbc-bb23-4fe6-8d9a-b56dd907c5f9.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/60090512/176824758-606e2dbc-bb23-4fe6-8d9a-b56dd907c5f9.png)

**Comment by lloydzhou** [comment]
这需要自己依据数据变化，去更新对应节点和边的属性

**Comment by kuokay** [comment]
> 好吧，我还以为源码就有，我说咋出不来呢

**Comment by kuokay** [comment]
> 这需要自己依据数据变化，去更新对应节点和边的属性

我看官方示例有，还以为写好了，调用就行

**Comment by NewByVector** [comment]
请问上面的回答有解决你的问题吗，为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。

**Comment by hcf1997** [comment]
大佬   我使用react hooks一直转圈圈，可以请教下吗
