### ISSUE TITLE
关于链接桩的点击事件

### ISSUE THREAD

**Issue by lvxiansen** [antvis/X6#2305]
### 问题描述

希望在链接桩上也可以配置链接桩的一些数据，例如node是路由器，链接桩是路由器端口，可以配置端口的ip地址等属性。
问题如下：
我看之前的issue提到通过graph.on("port:click", e => {{}）可以触发port的点击事件。但我试了下只会触发node的点击事件，而无法触发链接桩的点击事件。

### 重现链接

无

### 重现步骤

无

### 预期行为

点击链接桩触发点击事件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
chrome

**Comment by zhanghanguang-git** [comment]
graph.addNode({
  x: 60,
  y: 50,
  width: 180,
  height: 100,
  ports: [
    {
      id: "port1",
      attrs: {
        circle: {
          event: "port:click", // 添加自定义属性 event 来监听该元素的点击事件
        }
      }
    }
  ]
});

graph.on("port:click", () => {
  // handle
});

**Comment by NewByVector** [comment]
可以参考[常见问题](https://www.yuque.com/antv/x6/be9pfx#OV0kP)
