### ISSUE TITLE
按照解决方案： https://codesandbox.io/s/group-g4z66 调整后，出现拖动父节点时父节点大小变化的问题

### ISSUE THREAD

**Issue by zhangjutao** [antvis/X6#2306]
> 原因是 resize 父节点的时候会触发 Group 节点的 postprocess 事件，并且导致节点 resize 成原来大小。解决方案： https://codesandbox.io/s/group-g4z66

按照这个方案解决后，会出现新的问题。父节点收缩后拖动时，节点大小不对

https://user-images.githubusercontent.com/15686684/176348152-bc5f3f7b-b49c-471c-9508-16288e5fd923.mp4

_Originally posted by @zhangjutao in https://github.com/antvis/X6/issues/1674#issuecomment-1169506398_

**Comment by natsul** [comment]
这个暂时有解决方案吗

**Comment by NewByVector** [comment]
已经在 [demo](https://codesandbox.io/s/group-g4z66?file=/index.ts) 中更新。
