### ISSUE TITLE
validateMagnet返回false的时候，从链接桩拉线出来会报错

### ISSUE THREAD

**Issue by dayangege** [antvis/X6#2318]
### 问题描述

很奇怪的是，如果先移动该节点，再从拉链接桩拉线，就不会报错了。但是拉链接桩会变成移动节点，也拉不出线来。

### 重现链接

无

### 重现步骤

validateMagnet return false
画布中拖入一个带链接桩的节点
从链接桩拉线

### 预期行为

node不应该被移动且不应该报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.32.7 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/13084821/177584090-40b11f46-064f-43dd-8435-29f7731dc81d.png)

### 补充说明（可选）

1.32.3版本不会报错，但是拉链接桩会移动节点。

**Comment by lloydzhou** [comment]
刚刚按照步骤复现了一下这个bug
发现在1.32.3版本不报错。但是从1.32.4一直到1.32.7都报错。
所以能确定是在**1.32.4**版本引入的bug

另外期望节点不被拖走这个，应该在所有版本里面都会被拖走。
