### ISSUE TITLE
多选框显示反应非常慢

### ISSUE THREAD

**Issue by dayangege** [antvis/X6#2319]
### 问题描述

当画布上有很多节点的时候(4个及以上)，鼠标框选选中这些节点，最外层的那个选择框会非常慢的才会显示出来，通常要5秒以上。
但是第二次再框选就会快很多，如果第一次和第二框选之间移动过节点，第二次框选又会变得很慢

### 重现链接

https://x6.antv.vision/zh/examples/showcase/practices#flowchart

### 重现步骤

1,拉4及以上的节点到画布，并适当的移动。
2.用鼠标框选2-3个或更多的节点，看看多选框何时显示出来？
3.取消多选，随意移动几个节点。
4.再次用鼠标框选3个以上的节点，看看多选框何时显示出来？

### 预期行为

多选框应该秒显出

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.32.7 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/13084821/177587099-b116072e-2347-4571-9dbb-1eaec341d5ee.png)

### 补充说明（可选）

1.32.3版本就没这个问题，怎么选，多选框都会秒显出来，从1.32.4到最新的版本都有这个问题。

**Comment by damnright** [comment]
同样遇到了   1.32.3后面的版本都有这个延迟显示选择框的问题    期待解决

**Comment by damnright** [comment]
我遇到的情况是：第一次加载进入画布后，拖动某个cell，然后再点击那个cell，selection box要延迟4秒左右显示出来

**Comment by somnusx** [comment]
> 延迟
大佬有没有详细点的解决方案

**Comment by somnusx** [comment]
把snapline: true,设置成false他就好了

**Comment by dayangege** [comment]
> 把snapline: true,设置成false他就好了

这个功能有用啊，不能关掉。

**Comment by somnusx** [comment]
多选之前关掉，多选之后开启

**Comment by NewByVector** [comment]
selection 的交互性能已经在我们的工作计划中，而且优先级很靠前，希望能尽快解决你们的问题。

**Comment by NewByVector** [comment]
最新版本已经修复了这个问题，请更新到最新版本。
