### ISSUE TITLE
拖拽面板 NodeDndPanel 节点 只能展示两层，怎么展示多层级，拖拽它的子节点

### ISSUE THREAD

**Issue by wendaoshuai66** [antvis/X6#2321]
### 功能描述

如图所示，只能加两层数据
![image](https://user-images.githubusercontent.com/31531781/177673437-ca512406-9529-49a7-82bd-defa603108f3.png)

### 期望解决方案

期望能添加多层级

**Comment by lloydzhou** [comment]
我看和XFlow的demo非常相似，所以，你是不是看的那边的文档？
如果是那边的问题，可以到xflow的的issue页面去提issue

![image](https://user-images.githubusercontent.com/1826685/178019917-5dea0736-49ba-40c6-a79b-b0c8c56bac05.png)

**Comment by NewByVector** [comment]
这个 issue 和 x6 应该关系，先关闭了。
