### ISSUE TITLE
自定义Node，添加边时不居中显示

### ISSUE THREAD

**Issue by bingxueyinlian** [antvis/X6#2336]
### 问题描述

使用vue自定义组件的节点，添加边线时，没有垂直居中.

### 重现链接

https://codesandbox.io/s/vue-shape-8ciig

### 重现步骤

在上面的连接中，添加一行边线的代码：
```
    graph.addEdge({
      shape: "edge", // 指定使用何种图形，默认值为 'edge'
      source: "1",
      target: "2",
      label: "edge",
    });
```
![image](https://user-images.githubusercontent.com/1235035/177976964-3de23428-0dfa-4fa3-9fc8-010b9b4a82c0.png)

### 预期行为

边线的在垂直方向与两按钮对齐。

### 平台

- 操作系统: [ Windows 10]
- 网页浏览器: [Google Chrome]
- X6 版本: 1.32.7
- x6-vue-shape 版本: 1.4.0

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/1235035/177976477-38f81c3b-905b-4a4f-86f0-c451946c44c5.png)

**Comment by bingxueyinlian** [comment]
@lloydzhou 
您好，感谢您的回复。还想请教一下，Node可以不设置高度吗，让Node的高度自适应按钮的高度。我把addNode中的width和heigth注释了，也不是居中的，而且起点变成了0坐标，不是从开始节点的后面开始连接。
![image](https://user-images.githubusercontent.com/1235035/178387105-d0d74c2b-b591-47e9-b554-3b3b82ec9f40.png)

```
    graph.addNode({
      id: '1',
      shape: 'vue-shape',
      x: 50,
      y: 150,
      // width: 150,
      // height: 100,
      component: 'count',
      data: {
        num: 0,
      },
    });
    graph.addNode({
      id: '2',
      shape: 'my-count',
      x: 400,
      y: 150,
      // width: 150,
      // height: 100,
      data: {
        num: 0,
      },
    });

**Comment by lloydzhou** [comment]
1. x6里面必须设置大小（可能是宽x高，也可能是半径之类的）
2. 至于自定义组件要适配大小。react-shape可以通过getNode拿到当前节点，在componentUpdated里面更新node的大小。

**Comment by sunyonghua** [comment]
@bingxueyinlian @lloydzhou 
有解决自定义组件适配大小的问题吗？
如果不设置默认宽度的话，在react-shape中，子节点宽度全部是0,没办法根据子节点宽度设置容器宽度
而在svg中直接获取dom的BBox拿到的宽高也是不正确的。

**Comment by NewByVector** [comment]
请问上面的回答有解决你的问题吗，为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。
