### ISSUE TITLE
批量删除边之后再添加边导致渲染出错

### ISSUE THREAD

**Issue by lloydzhou** [antvis/X6#2343]
### 问题描述

批量删除边之后再添加边导致渲染出错
> 来源于x6钉钉群的讨论

### 重现链接

无

### 重现步骤

1. 先初始化一个图
2. 批量删除图上的边
3. 删除的时候，同时添加一条新的边

### 预期行为

展示新添加的边

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/1826685/178201705-156e7511-c4eb-437b-9690-e9b4b06cefc3.png)

![image](https://user-images.githubusercontent.com/1826685/178201726-1a95c56d-da30-4998-9300-efdfe69477a0.png)

### 补充说明（可选）

这个bug来源于x6钉钉群
怀疑是x6内部数据更新和调度方面处理得不好导致的问题。

**Comment by NewByVector** [comment]
这个并不能复现呀，需要什么特殊条件吗？

**Comment by lloydzhou** [comment]
![image](https://user-images.githubusercontent.com/1826685/178275821-fca7db54-6204-4c17-a5d2-cd3abb506fdf.png)

所以看起来可能是一个feature，并不算一个bug...

**Comment by lloydzhou** [comment]
另外，那天群里出现问题的人说：
把addEdge放到forEach removeEdge后面报错，但是顺序调换，把addEdge放前面就不报错。
