### ISSUE TITLE
x6编写思维导图时，小图与画布展示的不一致

### ISSUE THREAD

**Issue by snowrain0722** [antvis/X6#2351]
### 问题描述

用x6+React编写的思维导图，发现小地图展示的和画布的不一样

### 重现链接

https://x6.antv.vision/zh/examples/showcase/practices#mindmap

### 重现步骤

使用React搭建例子，然后设置开启小地图，即可重现

### 预期行为

我期望看到的：
小地图要与画布一致

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.32.1 ... ]

### 屏幕截图或视频（可选）

![小地图与画布不一致](https://user-images.githubusercontent.com/48642074/178532672-e7d1492c-e685-41cf-b3d3-b508e209aea3.png)

**Comment by snowrain0722** [comment]
三群人员满，其余的二维码过期，有需求要开发，遇到很多的坑，能不能扩容一下，把我拉进去。

**Comment by NewByVector** [comment]
@snowrain0722 群里解决的问题往往不能留存，还是在 github 上交流吧。

**Comment by snowrain0722** [comment]
不要设置固定宽高，我改文字的话会显示不全。

**Comment by NewByVector** [comment]
@snowrain0722 react 节点的话你直接用  dom 的方法来获取内容宽高。

**Comment by NewByVector** [comment]
@snowrain0722 给小地图的画布增加一个配置(保持和主画布的配置一致):
```ts
graphOptions: {
  connecting: {
    connectionPoint: 'anchor',
  },
}
```
