### ISSUE TITLE
节点可以让用户输入文本内容，需要脑图连线功能

### ISSUE THREAD

**Issue by PZ-18664918826** [antvis/X6#2354]
### 功能描述

节点可以让用户输入文本内容，节点里面相当于放了一个输入框，输入完之后高度自适应换行
连线：点击选中节点，点击连线按钮，可以将2个节点连续连起来 

### 期望解决方案

期望能解决

**Comment by NewByVector** [comment]
@PZ-18664918826 第一个问题是否是需要 [node-editor](https://x6.antv.vision/zh/docs/api/registry/node-tool#node-editor) 工具。

**Comment by PZ-18664918826** [comment]
三级节点拖拽到二级节点，如何将三级节点变成二级节点，二级变成三级这种功能

**Comment by tonywu6** [comment]
这个需要开发者自己实现，因为它超出了框架的功能范围

思路可以是这样：
- 使用[事件系统](https://x6.antv.vision/zh/docs/tutorial/intermediate/events)监听拖拽
- 在事件过程中使用 [`getBBox()` 方法](https://x6.antv.vision/zh/docs/api/view/cellview/#getbbox)获得节点范围，然后使用bbox 的 [`intersectsWithRect()` 方法](https://github.com/antvis/X6/blob/master/packages/x6/src/geometry/rectangle.ts#L539) 判断节点是否重叠 —— 重叠视为“拖拽到节点”
- 如果重叠，那么使用 [`addEdge()`](https://x6.antv.vision/zh/docs/api/graph/model/#addedge)等方法重新连接边。

这个 issue 原本的问题已经被解决了，因此我们会关闭这个 issue. 如果有新的问题，欢迎到[讨论区](https://github.com/antvis/X6/discussions) 提问
