### ISSUE TITLE
halo中的link功能无法拖拽edge

### ISSUE THREAD

**Issue by 1160809039** [antvis/X6#2356]
### 问题描述

通过halo中的link功能创建的edge，无法移动也不能点击，无法拖拽到另一个节点上

### 重现链接

https://codesandbox.io/s/serene-marco-hxcopd?file=/src/App.vue

### 重现步骤

1、创建graph
2、graph监听node:mouseup事件，创建Halo
3、人为创建一个新的Node，并选中Node
4、点击link按钮，创建edge

edge创建后无法拖拽到另一个节点上

### 预期行为

通过link创建的edge可以拖拽并链接到另外的节点上去

### 平台

- 操作系统:  Windows
- 网页浏览器: Google 
- X6 版本: [1.32.6]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/31716498/178959390-2c5a469d-d0d2-4281-a0de-04d4468ec5d7.png)

**Comment by NewByVector** [comment]
@1160809039 @babachao 给 edge 添加一个 [tools](https://x6.antv.vision/zh/docs/api/registry/edge-tool#source-arrowhead-%E5%92%8C-target-arrowhead) 搭配使用。

**Comment by NewByVector** [comment]
请问上面的回答有解决你的问题吗，为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。
