### ISSUE TITLE
节点旋转问题，旋转节点后再旋转回去会导致回不到原位

### ISSUE THREAD

**Issue by MrLiuleizhi** [antvis/X6#2361]
### Describe the bug

grid如果设置不被360整除的值，例如grid设为11，第一次逆时针旋转，然后停止。再次顺时针旋转就回不到原位了。
必须顺时针旋转超过原位置后，再重新逆时针旋转，才能够回到原位。

### Your Example Website or App

https://codesandbox.io/s/aged-rgb-kbs9mn?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

第一次逆时针旋转，然后停止
顺时针旋转就回不到原位了

### Expected behavior

旋转到0，90，180，270角度的时候做处理，达到即使grid非360整除，依然能够在这几个位置停留。

### Screenshots or Videos

https://user-images.githubusercontent.com/45058642/179168045-1484fa75-19ca-45bb-b2dc-30dfd9b97055.mp4

### Platform

- OS: [ Windows]
- Browser: [Chrome]
- Version: [latest]

**Comment by lloydzhou** [comment]
![image](https://user-images.githubusercontent.com/1826685/179179759-5415467e-85ac-4695-9732-13cb17f99b4a.png)

rotating.grid 表示每次旋转的角度。
按照这个定义，如果用户配置了一个素数，逻辑上并没有问题，如果强行在一些关键位置对角度进行一个人为的修正，或许会导致一些别的问题。反而会导致出现用户意料之外的一些表现。

所以，我的建议就是，开发者自己按照场景配置一个比较合适的数值。

**Comment by MrLiuleizhi** [comment]
> 
逆时针旋转一次后，再顺时针旋转一次，这两次转的角度不一样，这个感觉有点奇怪

**Comment by MrLiuleizhi** [comment]
> ![image](https://user-images.githubusercontent.com/1826685/179179759-5415467e-85ac-4695-9732-13cb17f99b4a.png)
> 
> rotating.grid 表示每次旋转的角度。 按照这个定义，如果用户配置了一个素数，逻辑上并没有问题，如果强行在一些关键位置对角度进行一个人为的修正，或许会导致一些别的问题。反而会导致出现用户意料之外的一些表现。
> 
> 所以，我的建议就是，开发者自己按照场景配置一个比较合适的数值。

主要是做的东西需要给用户提供配置网格和每次旋转角度的，但是配完之后旋转节点发现就有这个问题，转完了之后有偏差，回不去了。

**Comment by lloydzhou** [comment]
那是不是可以尝试自己监听这几个事件自己做一些修正呢，比如监听`node:rotated`事件，用户释放鼠标的时候，如果发现停留在你说的这几个关键位置附近，那就修正一下旋转角度？

![image](https://user-images.githubusercontent.com/1826685/179186126-4111a18d-8959-49fe-bc3e-15fbe9ddb7e8.png)
