### ISSUE TITLE
连接桩创建边的时候希望能够使用自定义边

### ISSUE THREAD

**Issue by hanqiufeng** [antvis/X6#2367]
### 问题描述

自定义了一个边，但是在通过连接桩创建边的时候，无法指定边的类型，拖出来还是一条基础线，只能在拖完之后去变更线的样式
![image](https://user-images.githubusercontent.com/35101809/179475931-4a830795-7b15-498e-af7c-f8359b0dc924.png)

### 重现链接

无

### 重现步骤

Graph.registerEdge(
  'custom-edge-label',
  {
    inherit: 'edge',
    defaultLabel: {
      markup: [
        {
          tagName: 'rect',
          selector: 'body',
        },
        {
          tagName: 'text',
          selector: 'label',
        },
      ],
      attrs: {
        label: {
          fill: '#000',
          fontSize: 14,
          textAnchor: 'middle',
          textVerticalAnchor: 'middle',
          pointerEvents: 'none',
        },
        body: {
          ref: 'label',
          fill: '#ffd591',
          stroke: '#ffa940',
          strokeWidth: 3,
          rx: 4,
          ry: 4,
          refWidth: '140%',
          refHeight: '140%',
          refX: '-20%',
          refY: '-20%',
        },
      },
      position: {
        distance: 200,
        options: {
          absoluteDistance: true,
          reverseDistance: true,
        },
      },
    },
  },
  true,
);

const that = this;
const graph = new Graph({
        container: document.getElementById('containerChart'),
        grid: that.grid,
        panning: true,
        resizing: {
          enabled: true,
          orthogonal: false,
        },
        selecting: true, // 可选
        snapline: true,
        interacting: {
          edgeLabelMovable: true,
        },
        connecting: {
          anchor: 'center',
          connectionPoint: 'anchor',
          allowBlank: false,
          snap: true,
          createEdge() {
            return new Shape.Edge({
              shape: 'custom-edge-label',
              attrs: {
                line: {
                  stroke: '#1890ff',
                  strokeWidth: 3,
                  targetMarker: {
                    name: 'classic',
                    size: 8,
                  },
                  strokeDasharray: 0,
                  style: {
                    animation: 'ant-line 30s infinite linear',
                  },
                },
              },
              labels: [{
                attrs: {
                  line: {
                    stroke: '#73d13d',
                  },
                  label: {
                    text: '关系',
                  },
                },
                fontSize: 16,
                fill: '#333',
                textAnchor: 'middle',
                textVerticalAnchor: 'middle',
              }],
              connector: 'normal',
              router: {
                name: '',
              },
              zIndex: 0,
            });
          },
        },
        highlighting: {
          magnetAvailable: {
            name: 'stroke',
            args: {
              padding: 4,
              attrs: {
                strokeWidth: 4,
                stroke: '#6a6c8a',
              },
            },
          },
        },
      });

### 预期行为

希望能够在连接桩上能够正确展示自定义边的样式

### 平台

- 操作系统: [Windows10]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.31.0]

**Comment by NewByVector** [comment]
createEdge 里面新的边这样配置：
```ts
createEdge() {
  return this.createEdge({
    //
  })
}
```

**Comment by NewByVector** [comment]
createEdge 里面新的边这样配置：
```ts
createEdge() {
  return this.createEdge({
    //
  })
}
```

**Comment by No54** [comment]
createEdge()这个方法的文档，确实写的有点简略了

**Comment by NewByVector** [comment]
@No54 感谢提出问题，文档已经更新。https://github.com/antvis/X6/pull/2473
