### ISSUE TITLE
在render:done中使用graph.centerContent，第一次不会使内容居中，第二次才会

### ISSUE THREAD

**Issue by yangxianxian** [antvis/X6#2371]
### Describe the bug

在render:done中使用graph.centerContent，第一次不会使内容居中，第二次才会

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Platform

- Browser: [e.g. Chrome, Safari, Firefox]

### Additional context

无

**Comment by babachao** [comment]
有具体的demo吗？

**Comment by yangxianxian** [comment]
> 有具体的demo吗？

![image](https://user-images.githubusercontent.com/52057330/179873527-6a3184ee-9903-45d1-a30b-9d2b29752fbd.png)
![image](https://user-images.githubusercontent.com/52057330/179873565-14000231-1fa3-4947-9426-9b3262e5e8e8.png)

使用接口返回的数据在实例化graph后直接使用centerContent和在render:done中使用都没法使内容居中

**Comment by NewByVector** [comment]
@yangxianxian 能否提供一个可以复现的 codesanbox 链接呢？

**Comment by yangxianxian** [comment]
> 

问题已找到，如果在画布实例外包裹了右键菜单Dropdown并且添加了visible,且visible由usestate控制的情况下就会发生第一次不能居中的情况

**Comment by yangxianxian** [comment]
> 

问题已找到，如果在画布实例外包裹了右键菜单Dropdown并且添加了visible,且visible由usestate控制的情况下就会发生第一次不能居中的情况
