### ISSUE TITLE
egde会压盖node的markup上配置的元素，导致markup上配置的事件不能响应。zindex设置无效

### ISSUE THREAD

**Issue by AnitaTang** [antvis/X6#2374]
### 问题描述

点击节点的markup配置的+按钮隐藏该节点的所有后继节点,
 再显示之后，该节点与直接后继节点的连线（edge）会压盖该节点上配置的要素，导致不能正确响应隐藏后继节点的事件

### 重现链接

编译失败

### 重现步骤

1. 参考https://antv-x6.gitee.io/zh/examples/showcase/practices#mindmap中mindmap实现点击节点markup配置的+按钮显示或隐藏该节点的所有后继节点,通过node.toggleVisible()实现
2. 隐藏再显示之后，该节点与直接后继节点的连线（edge）会压盖该节点上配置的要素，导致不能正确响应隐藏后继节点的事件
![20220719230706](https://user-images.githubusercontent.com/4083548/179788926-ed5f5a6d-4430-43cf-98c3-8bcd7ee371a3.jpg)
![20220719230806](https://user-images.githubusercontent.com/4083548/179788961-b128ea9d-4ddd-40c8-b5f2-4a6d1299a2d5.jpg)

### 预期行为

edge在最底层绘制，不影响节点的事件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
你的场景可以将 edge 的 zIndex 设置最低(比如 -1)，这样就不会影响了。

**Comment by AnitaTang** [comment]
前面忘记说了，zIndex设置了-1也没达到预期效果。
![20220720141644](https://user-images.githubusercontent.com/4083548/179910255-6d4212fa-178d-4e72-a48d-f4cd1a60952f.jpg)

**Comment by NewByVector** [comment]
将 sorting 配置为 approx 即可解决你的问题。
