### ISSUE TITLE
使用 addChild 添加多个后，通过父节点的 getChildren() 只能获取到一个子节点

### ISSUE THREAD

**Issue by caihuascript** [antvis/X6#2376]
### 问题描述

当使用 addChild 给某个父节点添加子节点的时候， getChildren()  只可以获取一个子节点。

### 重现链接

https://codesandbox.io/s/recursing-firefly-mvy4xt?file=/src/app.tsx

### 重现步骤

1. 进入页面
2. 查看 console.log(parent.getChildren()); 

### 预期行为

应该显示出 [child1, child2] 

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.32.7]

**Comment by babachao** [comment]
<img width="419" alt="WechatIMG599" src="https://user-images.githubusercontent.com/26959793/179893155-6e305e9f-f4a5-4376-bbf6-790465dcdf15.png">
你好，我尝试了使用异步添加，或者将addChild封装成一个异步方法调用，等所有需要被添加的节点都完成后，再调用getChildren()方法拿到所有的子节点

**Comment by NewByVector** [comment]
@caihuascript 需要先将 parent 和 child 加到画布上。再调用 addChild 方法。

**Comment by NewByVector** [comment]
请问上面的回答有解决你的问题吗，为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。
