### ISSUE TITLE
MiniMap显示的连接线Edge不对

### ISSUE THREAD

**Issue by MrMengJ** [antvis/X6#2378]
### 问题描述

MiniMap显示的连接线Edge不对

### 重现链接

https://codesandbox.io/s/inspiring-cache-mtolqo

### 重现步骤

如图所示，连接线配置的是Manhattan路由，MiniMap中显示的却是直线

### 预期行为

在MiniMap中，连接线和画布上的显示一致

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.32.8]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/26325346/179885760-f6db3568-f242-4a33-9d07-14f9f59c7565.png)

**Comment by NewByVector** [comment]
需要在 minimap 的 graphOptions 中增加 connecting 的配置。
