### ISSUE TITLE
求大佬提供下思路

### ISSUE THREAD

**Issue by PZ-18664918826** [antvis/X6#2379]
### 功能描述

![First](https://user-images.githubusercontent.com/64340432/179918856-f5fbe50b-d022-45d4-8277-cae24542edef.png)
![Second](https://user-images.githubusercontent.com/64340432/179918999-d7bc53f0-5bd7-496d-8215-9ff799445aa7.png)

需求：
1、整个ui图分为四行，每行底部有个分割线，每行的高宽是动态的。
2、整个ui图又可分为左侧是固定宽度，右侧节点整个画布高宽是动态的
3、新增节点排列需求
(1)：假如我在财务这一行，新建很多一级节点的时候是靠左排列
(2)：假如在某个一级节点新建了一个二级节点，对齐父节点排列
(3)：假如又新建了很多二级节点，这时候整个节点宽度会变宽，一级节点会根据整个节点宽度居中

不知道如何还原UI背景图
新建节点不知道如何实现上述排列规则

### 期望解决方案

求思路

**Comment by babachao** [comment]
1、初始化时，将默认的那些节点添加，左侧就正常渲染
2、向左排列可以参考[自动布局](https://antv-x6.gitee.io/zh/examples/showcase/practices#orgchart)功能
3、向下排列4行，渲染4个画布，因为你的横向是需要滚动的。（注意的是：需要自己将节点禁止拖动，只可右击操作添加删除，并且添加子节点时布局需要重新计算）
4、高度的话，如果需求不允许开启竖向滚动，可以根据你的节点的层数来计算，动态设置当前的画布高度
@PZ-18664918826
