### ISSUE TITLE
求大佬提供思路

### ISSUE THREAD

**Issue by PZ-18664918826** [antvis/X6#2380]
### 功能描述

![First](https://user-images.githubusercontent.com/64340432/179928777-293e7982-de0c-4065-92d1-9a7c9ed1ca8e.png)
![Second](https://user-images.githubusercontent.com/64340432/179928798-f8040e14-cb67-42bf-806c-ad22604e8c77.png)
![Third](https://user-images.githubusercontent.com/64340432/179928812-70ade05c-7d19-45bd-8df4-ebfe0ed2cfab.png)
![Fourth](https://user-images.githubusercontent.com/64340432/179928823-2e26c488-6c91-4fe8-bb0b-ef73a4978d7c.png)
![Fifth](https://user-images.githubusercontent.com/64340432/179928838-bdf5ce30-2de9-478f-9cb9-868905cbc09b.png)

完整的节点图
![完整节点图](https://user-images.githubusercontent.com/64340432/179957507-7b81bc4c-281a-4237-bbaf-77a16a232241.png)

需求
1、ui图分为左右俩侧，左侧宽度固定，右侧是画布 宽高不固定。
2、ui图又分为四行 每行底部又有分割线。
3、每行随着节点增多 宽高会变 宽度可以无限增加 高度一样
4、新建节点排列规则
 都是靠左排列节点
 子节点排列如上图

我的问题点
1、不知道如何还原UI背景图
2、 没有思路如何排列节点 

### 期望解决方案

绝望了，求大佬提供思路

**Comment by yaojin2070** [comment]
每行是一个父级,左侧内容也有一个包括的父级和右侧内容也有一个包括的父级  对应内容是属于它的子级, 当子级增加的时候,调用size(获取大小), 计算出大小,改变父级宽高, 父级是html形式编写的边框

**Comment by PZ-18664918826** [comment]
四行是一个大画布，不是4个画布，后面还有一些需求 比如第二行的三级节点拖拽到第一行的二级节点，可以交换位置。
这时候三级节点变成二级节点 二级变成三级节点 所以是一个画布

**Comment by PZ-18664918826** [comment]
> 1、初始化默认的节点（需要将节点都固定，不可移动） 2、四行的话，渲染四个画布，都需要开启横向滚动 3、节点布局的话可以参考[自动布局](https://antv-x6.gitee.io/zh/examples/showcase/practices#orgchart) 4、画布的高度可以根据节点的层数计算，动态设置画布的高

四行是一个大画布，不是4个画布，后面还有一些需求 比如第二行的三级节点拖拽到第一行的二级节点，可以交换位置。
这时候三级节点变成二级节点 二级变成三级节点 所以是一个画布

**Comment by PZ-18664918826** [comment]
> 



> 每行是一个父级,左侧内容也有一个包括的父级和右侧内容也有一个包括的父级 对应内容是属于它的子级, 当子级增加的时候,调用size(获取大小), 计算出大小,改变父级宽高, 父级是html形式编写的边框

感谢感谢思路 知道了怎么改变父节点的宽高

**Comment by babachao** [comment]
如果是放在一整个画布的话可以看一下[泳道图](https://antv-x6.gitee.io/zh/examples/showcase/practices#swimlane)

**Comment by PZ-18664918826** [comment]
> 如果是放在一整个画布的话可以看一下[泳道图](https://antv-x6.gitee.io/zh/examples/showcase/practices#swimlane)

感谢 我先试试

**Comment by PZ-18664918826** [comment]
> 如果是放在一整个画布的话可以看一下[泳道图](https://antv-x6.gitee.io/zh/examples/showcase/practices#swimlane)



> 1、初始化默认的节点（需要将节点都固定，不可移动） 2、四行的话，渲染四个画布，都需要开启横向滚动 3、节点布局的话可以参考[自动布局](https://antv-x6.gitee.io/zh/examples/showcase/practices#orgchart) 4、画布的高度可以根据节点的层数计算，动态设置画布的高



> 如果是放在一整个画布的话可以看一下[泳道图](https://antv-x6.gitee.io/zh/examples/showcase/practices#swimlane)

![image](https://user-images.githubusercontent.com/64340432/181903983-d6fc5482-10f5-499f-898d-8cfacaa76ff0.png)
怎么改变旁边父节点的位置，我是根据官方的[https://antv-x6.gitee.io/zh/examples/showcase/practices#orgchart](自动布局)进行排列

**Comment by PZ-18664918826** [comment]
> 大佬求 想怎么改变父节点的位置，我是根据官方的布局进行自动排列 如UI图所示 ![图片](https://user-images.githubusercontent.com/64340432/181903983-d6fc5482-10f5-499f-898d-8cfacaa76ff0.png) ![节点](https://user-images.githubusercontent.com/64340432/181904196-c5093469-e5ce-433a-ab01-0ccf9448a729.png)

**Comment by PZ-18664918826** [comment]
> 如果是放在一整个画布的话可以看一下[泳道图](https://antv-x6.gitee.io/zh/examples/showcase/practices#swimlane)

大佬求思路
![image](https://user-images.githubusercontent.com/64340432/181903983-d6fc5482-10f5-499f-898d-8cfacaa76ff0.png)
怎么改变旁边父节点的位置，我是根据官方的自动布局进行排列
如UI图所示
![node](https://user-images.githubusercontent.com/64340432/181904196-c5093469-e5ce-433a-ab01-0ccf9448a729.png)

**Comment by NewByVector** [comment]
@PZ-18664918826 你这个是 dagre 布局。

**Comment by PZ-18664918826** [comment]
[画布.pdf](https://github.com/antvis/X6/files/9282116/default.pdf)
对   dagre 布局
