### ISSUE TITLE
线段工具 + manhattan 路由会出现不理想的路径

### ISSUE THREAD

**Issue by mugo1993-ss** [antvis/X6#2385]
### 问题描述

![image](https://user-images.githubusercontent.com/73928245/179949004-4b8cce81-e117-48a9-a5fc-f6e7e0233624.png)

### 重现链接

需求

### 重现步骤

进行线段工具的拉动时，出现了很奇怪路径

### 预期行为

希望时平滑的线段

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/73928245/179949398-bd43fce5-601c-4521-b84f-9e013b84a41a.png)

**Comment by tonywu6** [comment]
https://codesandbox.io/s/antv-x6-manhattan-routing-edge-tools-w67o06?file=/src/app.tsx

推测是线段工具不能很好地兼容 manhattan 路由

**Comment by mugo1993-ss** [comment]
感谢！！改成正交路由后orth，可以出现较理想的路径。

**Comment by neeker007** [comment]
manhattan路由确实有bug，建议修复

**Comment by mugo1993-ss** [comment]
线段工具 + manhattan 路由希望能修复一下，感谢大佬们。正交会出现贴线问题：
![image](https://user-images.githubusercontent.com/73928245/181401544-cf2c077b-1464-45c8-94e1-37ca4443b00a.png)

**Comment by NewByVector** [comment]
@mugo1993-ss 可以设置 orth 的 [padding](https://x6.antv.vision/zh/docs/api/registry/router#orth) 配置解决你的问题。
