### ISSUE TITLE
x6怎么回事，拖拽的时候明显掉帧啊？

### ISSUE THREAD

**Issue by komagic** [antvis/X6#2388]
### Describe the bug

x6 物体拖拽的时候有明显卡顿情况

### Your Example Website or App

code

### Steps to Reproduce the Bug or Issue

任意一个demo

### Expected behavior

拖拽物体，理论上不应该掉帧这么严重

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by babachao** [comment]
如果有明显卡顿，需要看一下具体的代码，可以放个[codesandbox](https://codesandbox.io/)的demo么？或者上传一个视频

**Comment by komagic** [comment]
https://x6.antv.vision/zh/examples/node/group#expand-shrink

就是随便打开一个，拖拽物体，都不流畅，没有canvas库abricjs流畅，一卡一卡的，掉帧

**Comment by komagic** [comment]
我看了下代码，敢肯定，这个东西多了，页面会出现明显停顿，都完全没有优化的点
没有提前计算
没有web worker
大量使用数组
大量使用unshift这种很不好的方法
数据存储没有优化

**Comment by babachao** [comment]
> https://x6.antv.vision/zh/examples/node/group#expand-shrink
> 
> 就是随便打开一个，一个拉拉的水库，没有一个简单的拖拉，可以拖着一卡一卡的，都不是随便拖拖拉拉的

说的是fabric.js？

**Comment by babachao** [comment]
> 我下代码，敢肯定，这个东西顿时，页面会出现明显的停顿，都 没有缓存计算 没有工人 大量使用动态显示大量使用没有 转移这种操作的方法数据存储完全 优化 没有检测到离屏渲染

建议你可以先了解一下X6的定位，[可以看下这个](https://www.yuque.com/antv/x6/ecngdf)
X6是基于SVG，性能肯定是不如Canvas的，但是自定义节点成本低，像制作流程图之类的，而且流程图场景一般不需要渲染大量的节点

**Comment by babachao** [comment]
如果你有大量数据可视化场景，可以了解一下[G6](https://g6.antv.vision/zh)

**Comment by komagic** [comment]
我就随便扯扯淡，别在意我说的，宣泄一下。
产品要各种环图，要手动可操作，还要能动态动，并和表单大量交互，能变化，ui还得像x6...
我就怕东西多了怕她说我技术不行，怎么卡卡的。。。哎😌

**Comment by komagic** [comment]
为啥不用 canvas +blob 渲染svg

**Comment by babachao** [comment]
😌我做了营销活动的流程图，也是有大量表单交互，可以自己写HTML定义节点，我觉得很方便

**Comment by babachao** [comment]
用canvas的话想自定义实现产品要的图形节点就会比较复杂了

**Comment by NewByVector** [comment]
@komagic @babachao 拖动过程中一直动态修改 dom 元素位置，掉帧现在肯定存在，但是一卡一卡的我猜想是因为移动是以网格为单位，而不是像素为单位，你可以将网格大小分别设大或者小一点查看效果。

**Comment by babachao** [comment]
> 



> @komagic @babachao 拖动过程中一直动态修改 dom 元素位置，掉帧现在肯定存在，但是一卡一卡的我猜想是因为移动是以网格为单位，而不是像素为单位，你可以将网格大小分别设大或者小一点查看效果。

嗦嘎，明白了😌

**Comment by komagic** [comment]
我的眼 能够分辨电脑的144帧和60帧，所以对这些有些敏感。
哈哈，可以，这个讨论起到了效果。不错，不错。

脱离文档流，减少reflow 有可能不

**Comment by komagic** [comment]
用transform 行不

**Comment by NewByVector** [comment]
请问上面的回答有解决你的问题吗，为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。
