### ISSUE TITLE
Vue自定义的组件使用DagreLayout布局，报错TypeError: Cannot read properties of undefined (reading 'width')

### ISSUE THREAD

**Issue by CYBoys** [antvis/X6#2389]
### Describe the bug

注册Node代码如下：
```
    Graph.registerNode(ERNodeKey, {
      inherit: 'vue-shape',
      // x: 200,
      // y: 150,
      width: 300,
      height: 100,
      component: {
        template: `<er-node />`,
        components: {
          'er-node': ERNode
        }
      }
    });
```
添加Node代码如下：
```
    this.graph.clearCells();
    const allDatas = cloneDeep(this.datas);
    allDatas.forEach((data: DataModelDataSet, index: number) => {
      this.viewDatas.nodes.push({
        // this.graph.addNode({
        id: data.id,
        shape: ERNodeKey,
        width: 150,
        height: 100,
        data: {
          data: data
        }
      });
    });
    const dagreLayout = new DagreLayout({
      type: 'dagre',
      rankdir: 'TB',
      align: 'UR',
      ranksep: 30,
      nodesep: 15,
      // nodeSize: [300, 200],
      controlPoints: true
    });
    const model = dagreLayout.layout(this.viewDatas);
    this.graph.fromJSON(model);
```
错误如下：
<img width="971" alt="image" src="https://user-images.githubusercontent.com/15981638/180109083-10e1ed31-be47-4abf-a01d-90d2fb6269c3.png">

### Your Example Website or App

请见描述错误！

### Steps to Reproduce the Bug or Issue

请见描述错误！

### Expected behavior

正常渲染

### Platform

- OS: macOS 12.4
- Browser: Chrome
- Version: 103.0.5060.114（正式版本） (x86_64)

**Comment by lloydzhou** [comment]
```
const allDatas = cloneDeep(this.datas);

// 报错
[Vue warnl : Error in callback for watcher "datas": "TypeError: Cannot read properties of underined (reading 'width')
```
报错信息写的是对datas进行watch的时候不能访问width，但是我看代码片段是对cloneDeep之后的viewDatas操作的时候，才将width和height进行赋值，所以之前的datas数据里面应该本身就没有width把？
看起来是一个正常行为，你是不是需要再检查一下自己的数据？

**Comment by CYBoys** [comment]
> 给一个可以复现的 codesanbox 链接呢，我使用你给的代码片段试了下，没有报错行为。

我测试了一下，用官方给的数据没有问题，但是使用我自己的数据就有这个问题，不知道是为什么。数据源如下。
```
const test = [
      {
        id: 1,
        name: 'velit veniam magna laborum consectetur',
        columns: [
          {
            id: 11,
            tableId: 111,
            name: 'reprehenderit dolore in ad',
            enName: 'cupidatat ut veniam consequat nulla',
            type: 'DATETIME'
          }
        ]
      },
      {
        id: 2,
        name: 'qui officia anim et',
        columns: [
          {
            id: 21,
            tableId: 211,
            name: 'minim est Ut',
            enName: 'tempor nisi',
            type: 'DATE'
          },
          {
            id: 22,
            tableId: 222,
            name: 'do aliquip ut',
            enName: 'est Ut in ex magna',
            type: 'BOOLEAN'
          },
          {
            id: 23,
            tableId: 233,
            name: 'labore id',
            enName: 'consectetur cupidatat exercitation dolor',
            type: 'CHAR'
          },
          {
            id: 24,
            tableId: 244,
            name: 'Lorem',
            enName: 'eu ut',
            type: 'VARCHAR'
          },
          {
            id: 25,
            tableId: 244,
            name: 'culpa consectetur sunt ut in',
            enName: 'in minim',
            type: 'BIGINT'
          }
        ]
      }
    ];
```

**Comment by CYBoys** [comment]
> ```
> const allDatas = cloneDeep(this.datas);
> 
> // 报错
> [Vue warnl : Error in callback for watcher "datas": "TypeError: Cannot read properties of underined (reading 'width')
> ```
> 
> 报错信息写的是对datas进行watch的时候不能访问width，但是我看代码片段是对cloneDeep之后的viewDatas操作的时候，才将width和height进行赋值，所以之前的datas数据里面应该本身就没有width把？ 看起来是一个正常行为，你是不是需要再检查一下自己的数据？

貌似和数据有关系？没看出来这个数据哪儿有问题，求大佬帮忙解答。
```
const test = [
      {
        id: 1,
        name: 'velit veniam magna laborum consectetur',
        columns: [
          {
            id: 11,
            tableId: 111,
            name: 'reprehenderit dolore in ad',
            enName: 'cupidatat ut veniam consequat nulla',
            type: 'DATETIME'
          }
        ]
      },
      {
        id: 2,
        name: 'qui officia anim et',
        columns: [
          {
            id: 21,
            tableId: 211,
            name: 'minim est Ut',
            enName: 'tempor nisi',
            type: 'DATE'
          },
          {
            id: 22,
            tableId: 222,
            name: 'do aliquip ut',
            enName: 'est Ut in ex magna',
            type: 'BOOLEAN'
          },
          {
            id: 23,
            tableId: 233,
            name: 'labore id',
            enName: 'consectetur cupidatat exercitation dolor',
            type: 'CHAR'
          },
          {
            id: 24,
            tableId: 244,
            name: 'Lorem',
            enName: 'eu ut',
            type: 'VARCHAR'
          },
          {
            id: 25,
            tableId: 244,
            name: 'culpa consectetur sunt ut in',
            enName: 'in minim',
            type: 'BIGINT'
          }
        ]
      }
    ];
```

**Comment by CYBoys** [comment]
定位到是在执行`findSmallestWidthAlignment`函数，获取`halfWidth`时抱错。但是不知道怎么解决
<img width="550" alt="image" src="https://user-images.githubusercontent.com/15981638/180672094-7e45854e-bac2-43e0-b38e-f72e9a4eed46.png">

**Comment by lloydzhou** [comment]
> 定位到是在执行`findSmallestWidthAlignment`函数，获取`halfWidth`时抱错。但是不知道怎么解决 <img alt="image" width="550" src="https://user-images.githubusercontent.com/15981638/180672094-7e45854e-bac2-43e0-b38e-f72e9a4eed46.png">

你确定是X6里面报错吗？我在x6的仓库没有搜索到这样名字的函数！

**Comment by CYBoys** [comment]
> > 定位到是在执行`findSmallestWidthAlignment`函数，获取`halfWidth`时抱错。但是不知道怎么解决 <img alt="image" width="550" src="https://user-images.githubusercontent.com/15981638/180672094-7e45854e-bac2-43e0-b38e-f72e9a4eed46.png">
> 
> 你确定是X6里面报错吗？我在x6的仓库没有搜索到这样名字的函数！

是在layout仓库，https://github.com/antvis/layout/blob/master/src/layout/dagre/src/position/bk.ts

**Comment by lloydzhou** [comment]
@CYBoys 
要不你试试把代码中的forEach循环插入数组这里改成一个map的方式试试看？
```
    const allDatas = cloneDeep(this.datas);
    allDatas.forEach((data: DataModelDataSet, index: number) => {
      this.viewDatas.nodes.push({
        // this.graph.addNode({
        id: data.id,
        shape: ERNodeKey,
        width: 150,
        height: 100,
        data: {
          data: data
        }
      });
    });
```
改成
```
    const allDatas = cloneDeep(this.datas);
    this.viewDatas.nodes = allDatas.map((data: DataModelDataSet, index: number) => {
      return {
        id: data.id,
        shape: ERNodeKey,
        width: 150,
        height: 100,
        data: {
          data: data
        }
      };
    });
```

**Comment by CYBoys** [comment]
> @CYBoys 要不你试试把代码中的forEach循环插入数组这里改成一个map的方式试试看？
> 
> ```
>     const allDatas = cloneDeep(this.datas);
>     allDatas.forEach((data: DataModelDataSet, index: number) => {
>       this.viewDatas.nodes.push({
>         // this.graph.addNode({
>         id: data.id,
>         shape: ERNodeKey,
>         width: 150,
>         height: 100,
>         data: {
>           data: data
>         }
>       });
>     });
> ```
> 
> 改成
> 
> ```
>     const allDatas = cloneDeep(this.datas);
>     this.viewDatas.nodes = allDatas.map((data: DataModelDataSet, index: number) => {
>       return {
>         id: data.id,
>         shape: ERNodeKey,
>         width: 150,
>         height: 100,
>         data: {
>           data: data
>         }
>       };
>     });
> ```
还是有问题，大佬方便加个VX吗？ LaiYoung_
