### ISSUE TITLE
怎么改变label的字体？

### ISSUE THREAD

**Issue by FelicityGao** [antvis/X6#2390]
### 问题描述

想通过fontFamily改变字体但是没有效果。

### 重现链接

无

### 重现步骤

text: {
        fontSize: '12px',
        fill: '#262626',
        fontFamily: 'Arial',
      }
这样设置没效果

### 预期行为

选择下拉内容可以改变框内的字体
![image](https://user-images.githubusercontent.com/27398232/180150196-0f2af30c-47ff-4b21-96f5-a278f73b9393.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
我尝试了一下，有效果的。这个是效果图：
![image](https://user-images.githubusercontent.com/20186737/180383956-f311be7f-f2b2-4393-b36f-679ffa3af2c6.png)
具体代码：
```ts
graph.addNode({
  x: 40,
  y: 40,
  width: 120,
  height: 60,
  label: 'rect',
  attrs: {
    text: {
      fontFamily: 'Times New Roman',
    }
  }
})

graph.addNode({
  x: 140,
  y: 40,
  width: 120,
  height: 60,
  label: 'rect',
})
```

**Comment by NewByVector** [comment]
请问上面的回答有解决你的问题吗，为了高效沟通，我们暂时关闭这个 issue，如果有必要，请重新开一个新的 issue。
