### ISSUE TITLE
node中的textarea无法聚焦

### ISSUE THREAD

**Issue by gmj-ll** [antvis/X6#2391]
### Describe the bug

在textarea的mouseup事件冒泡到cell上时，cell会通知事件进入到keyboard.js的focus回调中，这里的isInputEvent只会判断事件源是否是input，textarea不符合，所以就会失去焦点

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

node中添加textarea标签，无法聚焦

### Expected behavior

希望textarea在mouseup之后不会失去焦点

### Platform

- OS:Windows
- Browser: Chrome

**Comment by NewByVector** [comment]
升级到 1.32.10 版本。
