### ISSUE TITLE
官网的文本编辑bug

### ISSUE THREAD

**Issue by Trojanpa** [antvis/X6#2396]
### Describe the bug

开启对齐线，将节点拖动对齐另一个节点，再双击节点进行文本编辑，会突然出现以下问题：节点从视口位置移开、画布出现滚动条，以及出现编辑光标位置变更。

### Your Example Website or App

https://x6.antv.vision/zh/examples/node/tool#editable

### Steps to Reproduce the Bug or Issue

1.打开 https://x6.antv.vision/zh/examples/node/tool#editable
2.Graph配置项配置开启对齐线，新增以下两行代码：
autoResize: true,
snapline: true,
3.将一个节点拖动到另一个节点下方对齐，显示对齐线
4.双击文本节点
5.观察出现的现象

### Expected behavior

期望节点在视口上不偏移，不出现滚动条，编辑光标位置在编辑节点上。

### Screenshots or Videos

![bug](https://user-images.githubusercontent.com/42988574/180351485-f38e3b50-0787-43e5-9319-409b13516aa2.gif)

### Platform

- OS: [Windows]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/pull/2310  这里已经修复了这个问题，请升级到 1.32.8 版本，我把官网更新一下。
