### ISSUE TITLE
怎么自定义拖拽节点的样式？

### ISSUE THREAD

**Issue by dajun1230** [antvis/X6#2401]
### 问题描述

在拖动的过程中，我们可以自定拖拽那个节点的样式吗？

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
macOs

**Comment by NewByVector** [comment]
查看[常见问题](https://x6.antv.vision/zh/docs/tutorial/basic/dnd#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。

**Comment by NewByVector** [comment]
与 https://github.com/antvis/X6/issues/2405 重复，先关闭。
