### ISSUE TITLE
能够自定义拖动节点的样式

### ISSUE THREAD

**Issue by dajun1230** [antvis/X6#2405]
### 功能描述

在画布中对某个节点进行拖动到某条边上的时候，由于这个节点的宽高都很大，在拖动的时候又将这个节点置于高层，导致无法看到具体的边在哪里，被节点遮住了，希望能通过自定义拖动节点样式，将拖动节点的样式设置为一个很小的方框或者其他。

### 期望解决方案

期望能做到这个拖动节点的样式完全可以作为组件自己定义。

**Comment by lloydzhou** [comment]
这里说的拖动，是指从Dnd或者Stencil拖动到画布？还是仅仅在画布中拖动节点？

如果是拖拽生成新节点，在拖动过程中的节点是可以定制的。

如果是拖动画布中节点位置，应该是不支持直接定义节点样式的。

**Comment by NewByVector** [comment]
@dajun1230 @lloydzhou 的回答有解答你的问题吗？

**Comment by dajun1230** [comment]
> 拖动画布中节点位置，应

目前已经解决了，谢谢大家。

**Comment by dajun1230** [comment]
> 这里说的拖动，是指从Dnd或者Stencil拖动到画布？还是仅仅在画布中拖动节点？
> 
> 如果是拖拽生成新节点，在拖动过程中的节点是可以定制的。
> 
> 如果是拖动画布中节点位置，应该是不支持直接定义节点样式的。

说的是在你拖动过程中，跟随你光标所移动的那个节点样式，光标在哪，那个就在哪，鼠标松开即消失的那个。目前已经解决了，谢谢。

**Comment by basala** [comment]
@dajun1230 你好，遇到了一样的问题，请问你是怎么解决的

**Comment by dajun1230** [comment]
> 

已经过去太久了，忘了怎么解决的了。好像是克隆了一个，然后在新增的，graph.cloneCells(nodes)在 graph.addCell(克隆后的id)；不知道对不对哈

**Comment by dajun1230** [comment]
> @dajun1230 你好，遇到了一样的问题，请问你是怎么解决的

已经过去太久了，忘了怎么解决的了。好像是克隆了一个，然后在新增的，graph.cloneCells(nodes)在 graph.addCell(克隆后的id)；不知道对不对哈

**Comment by basala** [comment]
> > @dajun1230 你好，遇到了一样的问题，请问你是怎么解决的
> 
> 已经过去太久了，忘了怎么解决的了。好像是克隆了一个，然后在新增的，graph.cloneCells(nodes)在 graph.addCell(克隆后的id)；不知道对不对哈

好的，我试试，非常感谢
