### ISSUE TITLE
Cannot use "this" here

### ISSUE THREAD

**Issue by miniliupeng** [antvis/X6#2406]
### Describe the bug

vite project dev run

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

yarn dev

### Expected behavior

no terminal error

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
你的 issue没有给出可以定位问题的信息，提供一些有用的信息？

**Comment by NewByVector** [comment]
因为问题无法复现，先关闭这个 issue。

**Comment by gsw945** [comment]
复现了:
![image](https://user-images.githubusercontent.com/6281968/185276423-24e2f9bc-82c8-4342-9c25-0063769fa1ff.png)

**Comment by favorite58** [comment]
请问这个问题有解决吗？目前我在项目中也遇到了，虽然对功能使用没啥影响，报错截图：
![image](https://user-images.githubusercontent.com/25808314/186562709-23a95ec9-aa79-4093-9c9a-011f0d21107b.png)
