### ISSUE TITLE
怎么样让连接桩随着鼠标的移出 连接桩消失 鼠标移入连接桩显现

### ISSUE THREAD

**Issue by PZ-18664918826** [antvis/X6#2412]
### 功能描述

![image](https://user-images.githubusercontent.com/64340432/180645005-77b9e1d2-d8af-4fcd-9527-727f523fd095.png)

### 期望解决方案

希望给个解决方案

**Comment by babachao** [comment]
可以看这个[例子](https://x6.antv.vision/zh/examples/showcase/practices#flowchart)呀

**Comment by PZ-18664918826** [comment]
> 可以看这个[例子](https://x6.antv.vision/zh/examples/showcase/practices#flowchart)呀

感谢 哈哈哈

**Comment by PZ-18664918826** [comment]
> 可以看这个[例子](https://x6.antv.vision/zh/examples/showcase/practices#flowchart)呀
![1658805192922](https://user-images.githubusercontent.com/64340432/180915221-6974390f-939d-4433-ade5-2a7655d66b5b.jpg)
大佬，当二个节点对齐的时候，怎么让这个线变直

**Comment by babachao** [comment]
我只是用的早一些，不是啥大佬😴😴

https://github.com/antvis/X6 可以在首页里面扫码进钉钉群一起讨论

如果希望拉下来是水平垂直的话，可以不使用自定义连接器。
使用智能正交路由[manhattan](https://x6.antv.vision/zh/docs/api/registry/router/#orth)
使用圆角连接器[rounded](https://x6.antv.vision/zh/docs/api/registry/connector#rounded)
可以[参考这个例子](https://x6.antv.vision/zh/examples/showcase/practices#flowchart)

**Comment by tonywu6** [comment]
有更多其他的问题，欢迎到讨论区、钉群，或者新建 issue
