### ISSUE TITLE
在画布之外input框选获得焦点时，点击画布空白地方失去焦点，没有触发input框的onBlur事件，怎么解决？

### ISSUE THREAD

**Issue by dajun1230** [antvis/X6#2425]
### 问题描述

目前有这么一种场景：有一个 X6 绘制的画布，画布之外的右侧有一个input输入框，我希望能在input框失去焦点的时候能触发做一些事情，同时又能做到让画布中的节点由原本的选中状态变为非选中状态。但是从实际操作来看，在选中画布中的节点之后，去输入框输入内容，然后点击画布空白处使其输入框失去焦点，但是实际值只触发了画布中的 unselected时间，没有使输入框失去焦点，从而并未触发onBlur事件。希望的结果是 失去焦点后，要先触发input的onBlur事件，然后再去触发画布中的unselected事件。

### 重现链接

无

### 重现步骤

具体重现步骤，问题描述中已详细描述。

### 预期行为

input框失去焦点后，要先触发input的onBlur事件，然后再去触发画布中的unselected事件。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
macOS

**Comment by DanielLeefu** [comment]
可以在点击空白画布的事件中[blank:click](https://x6.antv.vision/zh/docs/tutorial/intermediate/events)手动调用input输入框的blur()方法

**Comment by dajun1230** [comment]
> 

这个不失为一种方式，我先试试，希望能有更好的方式

**Comment by tonywu6** [comment]
Hello! 可以提供一个复现 demo 吗，这里有可能是一个画布事件的缺陷

**Comment by dajun1230** [comment]
> Hello! 可以提供一个复现 demo 吗，这里有可能是一个画布事件的缺陷
通过在unselectd事件中主动触发input标签的onBlur事件，已经能解决该问题了。
