### ISSUE TITLE
在版本1.32.7发现，snapline的sharp参数配置失效

### ISSUE THREAD

**Issue by zycfighting** [antvis/X6#2429]
### Describe the bug

在版本1.32.7发现，snapline的sharp参数配置失效

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

在版本1.32.7发现，snapline的sharp参数配置失效

### Expected behavior

在版本1.32.7发现，snapline的sharp参数配置生效

### Platform

- OS:Windows
- Browser:Chrome
- Version: 1.32.11

**Comment by tonywu6** [comment]
Hello! Snapline 的 `sharp` 选项计划在未来的一个版本中会被去除，届时 `sharp: true` 将会成为默认的行为，也就是说对齐线将会默认对齐各个节点；

<img width="616" alt="Screen Shot 2022-07-27 at 7 19 07 PM" src="https://user-images.githubusercontent.com/93302820/181234614-48a95096-7ac7-435d-9ea1-b13ddcef8e2e.png">

<img width="397" alt="Screen Shot 2022-07-27 at 7 21 13 PM" src="https://user-images.githubusercontent.com/93302820/181235288-08b4281e-0930-4e19-ad5a-cdf0146e1f16.png">

这样做的原因是 Snapline 在 1.32.7 引入了新的渲染方式，去除了 jQuery 的使用并解决了之前的一个性能问题，其中默认 `sharp: true` 的做法反而在代码设计及性能上比复原 `snapline: false` 更占优势，加之我们认为 `sharp: true` 在 UI 上也更加友好，因为此时可以看出某个节点具体是和哪些其他的节点对齐的，因此我们采取了弃用的策略。

具体的 PR 内容可见 #2195 

这个变化在文档上没有体现，这一点我们会尽快完善。同时这个变化是在一个 patch 版本中引入的，这违背了 semver 的原则，这一点我们表示抱歉。

---

**如果对之前 `sharp: false` 的行为有强烈的需求，可以提供一个更详细的解释（最好有 demo），我们*可能*会恢复这一选项**

**Comment by zycfighting** [comment]
> 
在使用时以及在官网的示例上发现了这个问题，非常感谢解答
