### ISSUE TITLE
Vue3+vite 本地运行正常 上线到服务器自定义节点内容为空（registerVueComponent）

### ISSUE THREAD

**Issue by DianaYako** [antvis/X6#2431]
### 问题描述

![image](https://user-images.githubusercontent.com/65520240/181193567-3cf40ce2-79f6-446f-b10d-5ba662496042.png)
就像这样，无论是addNode还是拖入到操作面板，都是空的情况
本地运行没有问题 是我配置有问题吗
![image](https://user-images.githubusercontent.com/65520240/181193704-56cdae1a-cc57-4b00-b5dc-97944a784532.png)

### 重现链接

https://monster-qi.com:8888/openGuass-workflow-vue3/data-model/index

### 重现步骤

进入页面，addNode生成的以及拖进来的都是空的

### 预期行为

我希望和开发环境一样

### 平台

Google chrome

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/65520240/181193992-ccfadc3a-59c5-4bf4-9202-d028caa164e4.png)
![image](https://user-images.githubusercontent.com/65520240/181194015-40ce9847-a9b2-4ac3-926f-466ec4542c4c.png)
![image](https://user-images.githubusercontent.com/65520240/181194080-9f10a017-dbf6-47e5-9a91-5afbde8d0cd5.png)
![image](https://user-images.githubusercontent.com/65520240/181194102-a7a9593b-14e7-42dd-b93f-c4b5bb5503bf.png)

**Comment by lloydzhou** [comment]
@DianaYako 
你注册到x6的组件是不是使用`defineAsyncComponent`定义的异步组件？

如果是异步组件，那么以上的问题或许可以这样解释：

1. 正式环境不渲染内容
  a. X6对每一个node都会createApp渲染注册进去的组件。
  b. 注册组件到X6的时候这个异步的组件并没有初始化好，直接把这个没有初始化好的组件挂到一个全新的Vue App上面就渲染不出来。
  c. 你可以试试更换为普通的Component，或者使用`useTeleport`（更换`VueShapeView`让所有的节点都挂到全局唯一的Vue App上面）。

2.  关于dev模式下和正式打包后不一致的问题？
  a. vite在dev模式下只编译每一个module，让浏览器去处理依赖关系。
  b. 所有我怀疑在dev模式下面浏览器处理依赖的时候，会等待这个异步组件初始化成功之后才开始渲染节点。

**Comment by DianaYako** [comment]
![image](https://user-images.githubusercontent.com/65520240/181404961-92e2b565-4178-4293-9a40-a8c5ddc66c26.png)

![image](https://user-images.githubusercontent.com/65520240/181404912-6727c93e-92fc-4fe3-a8cc-873c46b3f197.png)

@lloydzhou  您好 如图，1 addNode 可以出来，2就不可以了，1的shape用的是官方的图形示例，没有用registerVueComponent

2改了一下 改为直接引入了 还是出不来 在本地开发环境能渲染出来 打包后到线上出不来

**Comment by lloydzhou** [comment]
我前面建议你试一试使用useTeleport，这个有尝试吗？

另外，你这个牵涉到使用vite进行打包，估计也不好使用codesandbox进行测试。
你能否在github开启一个能复现的最小的demo（最好不要包含你自己的项目相关信息）。把这个能复现的demo链接发这里，我们下载下来调试一下？

**Comment by DianaYako** [comment]
这是我刚刚创建的一个demo https://github.com/DianaYako/openGuass-workflow-vue3-test

**Comment by DianaYako** [comment]
麻烦您了 @lloydzhou 

这是我创建的一个demo https://github.com/DianaYako/openGuass-workflow-vue3-test
![image](https://user-images.githubusercontent.com/65520240/181413693-3b6860f2-2395-4d97-b590-a5a471cda638.png)
这里可以看到这个还是空的 单纯的注册了一个组件并且addNode加了一个 下边那个是普通的正方形形状（shape）


我再试一下useTeleport  看看怎么用。。

**Comment by mugo1993-ss** [comment]
写法问题，可以试试render：
![image](https://user-images.githubusercontent.com/73928245/181433936-4e7f35c9-8a31-4652-8a91-c8d96febd43e.png)

**Comment by DianaYako** [comment]
@mugo1993-ss 您好
我问一下是这么写吗。
![image](https://user-images.githubusercontent.com/65520240/181441117-2e39bc4b-d572-4ce6-ad38-ead96bf1d679.png)
我报错了。。

**Comment by mugo1993-ss** [comment]
> @mugo1993-ss 您好 我问一下是这么写吗。 ![image](https://user-images.githubusercontent.com/65520240/181441117-2e39bc4b-d572-4ce6-ad38-ead96bf1d679.png) 我报错了。。

需要改成jsx语法
1、 .vue文件在script添加lang="jsx"：
![image](https://user-images.githubusercontent.com/73928245/181442116-fdf36319-4862-442e-a47c-50b0776201aa.png)
2、如果是.js文件直接改为.jsx

**Comment by DianaYako** [comment]
@mugo1993-ss 
可以了 大哥牛逼 谢谢谢谢！！

**Comment by mugo1993-ss** [comment]
> @mugo1993-ss 可以了 大哥牛逼 谢谢谢谢！！

不客气~正好最近我也在弄这个。

**Comment by oushu1tanqiang1** [comment]
+1

**Comment by oushu1tanqiang1** [comment]
@tonywu6 官方文档中的Vue示例不适用于Vue3

**Comment by ZHUYUANWEI** [comment]
> > @mugo1993-ss 您好 我问一下是这么写吗。 ![image](https://user-images.githubusercontent.com/65520240/181441117-2e39bc4b-d572-4ce6-ad38-ead96bf1d679.png) 我报错了。。
> 
> 需要改成jsx语法 1、 .vue文件在script添加lang="jsx"： ![image](https://user-images.githubusercontent.com/73928245/181442116-fdf36319-4862-442e-a47c-50b0776201aa.png) 2、如果是.js文件直接改为.jsx

这个方案完美解决，大哥牛逼！

**Comment by ZHUYUANWEI** [comment]
> @tonywu6 官方文档中的Vue示例不适用于Vue3

确实发现文档中有一些不太适用的，不光是vue3，还有一些参数需要更新

**Comment by lloydzhou** [comment]
@DianaYako 
抱歉这么久没处理这个问题！

感觉这个问题的根本原因还是在于如果使用了动态的模板生成vue的组件，就需要开启`vue runtime compiler`
