### ISSUE TITLE
autoResize 无法同时监听容器宽度和高度变化并自动更新画布大小

### ISSUE THREAD

**Issue by wb-wenbei** [antvis/X6#2438]
### Describe the bug

autoResize属性设置为true,外容器设置css属性display:flex;
容器宽度变化时可以自动更新画布大小，但是容器高度变化时无法自动更新画布大小

### Your Example Website or App

https://codesandbox.io/s/adoring-resonance-i3tfxv?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1.打开测试页面：[地址](https://codesandbox.io/s/adoring-resonance-i3tfxv)
2.拖动页面中黄色横条改变下方容器大小；
3.画布并没有跟着下方容器尺寸改变而自动更新画布大小；

### Expected behavior

随下方容器尺寸改变而自动更新画布大小。

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [103.0.5060.114]

### Additional context

外部容器设置css属性：display:flex时，画布只能自动更新宽度，
外部容器设置css属性：display:flex;flex-direction: column;时，画布只能自动更新高度，
无法宽高同时自动更新。

**Comment by NewByVector** [comment]
这是一个 bug，我们尽快修复。

**Comment by lloydzhou** [comment]
我最近也发现这个bug，所有在做组件封装的时候，放弃了x6提供的`autoResize`配置项，而是使用`resize-detector`这个包重新写的逻辑

https://github.com/lloydzhou/antv-x6-react/blob/master/src/lib/Graph.tsx#L44

**Comment by zzjjbbaa** [comment]
> 这是一个 bug，我们尽快修复。

修复了吗

**Comment by mtiger95** [comment]
同样遇到了这个问题，画布高度无法自适应更新。

**Comment by pfdgithub** [comment]
> 同样遇到了这个问题，画布高度无法自适应更新。

别等了，等不到官方修复的。你自己覆盖下 x6 所在容器样式就可以了。
```
width: auto !important;
height: auto !important;
```

**Comment by hujinbo** [comment]
我也遇到了同样的问题

**Comment by NewByVector** [comment]
已经在 2.x 中修复。相关[文档](http://x6.antv.antgroup.com/tutorial/basic/graph#%E7%94%BB%E5%B8%83%E5%A4%A7%E5%B0%8F)。

**Comment by zeffon** [comment]
我发现在火狐93版本复现了该bug，使用的是2.11.4版本的。

**Comment by noxxxxxxxx** [comment]
> 已经在 2.x 中修复。相关[文档](http://x6.antv.antgroup.com/tutorial/basic/graph#%E7%94%BB%E5%B8%83%E5%A4%A7%E5%B0%8F)。

1.x 还有这么多用户在使用，不考虑修复的么？如果1.x要废弃，那就在官方文档上体现！

**Comment by Asiakinglhh** [comment]
版本使用是 v1.31.0，本人亲测可解决，如果只能用旧版开发的可参考这个：

<div style="width:100%; height:100%; display:flex">
  <div id="container" style="width:100% !important; height:100% !important; flex: 1"></div>
</div>

**Comment by Asiakinglhh** [comment]
版本使用是 v1.31.0，本人亲测可解决，如果只能用旧版开发的可参考这个：

`<div style="width:100%; height:100%; display: flex">`
`  <div id="container" style="width:100% !important; height:100% !important; flex: 1"></div>`
`</div>`
