### ISSUE TITLE
缺少画布拖拽事件的监听

### ISSUE THREAD

**Issue by viewweiwu** [antvis/X6#2440]
### 功能描述

节点和边的监听是有的，但是画布暂时没有看到。

### 期望解决方案

希望画布能够提供拖拽相关事件，如 graph.on('canvas:dragstart')、 graph.on('canvas:dragging')、 graph.on('canvas:dragend') 事件。

**Comment by NewByVector** [comment]
首先感谢你的 issue，请问一下画布的这几个事件的使用场景是在哪里？如果有必要的话，我们会补充这些事件。✈️

**Comment by viewweiwu** [comment]
画布的联动，拖动一定距离展示某个按钮
不允许拖出屏幕外
等等

**Comment by komagic** [comment]
感觉你是不是应该判断的是拖拽的canvas的container，如果有多个画布，而不是画布本身？

**Comment by NewByVector** [comment]
@viewweiwu 这个可以用 [translate](https://x6.antv.vision/zh/docs/tutorial/intermediate/events#%E7%94%BB%E5%B8%83%E7%BC%A9%E6%94%BE%E5%B9%B3%E7%A7%BB) 事件来实现，其中不允许拖出屏幕，可以使用 [trasnlate](https://x6.antv.vision/zh/docs/api/graph/transform/#translating)。
