### ISSUE TITLE
报错：Converting circular structure to JSON

### ISSUE THREAD

**Issue by FelicityGao** [antvis/X6#2444]
### 问题描述

当给节点添加了双击可编辑的功能时，监听节点变化并把序列化数据转为字符串时报错：Converting circular structure to JSON

### 重现链接

https://codesandbox.io/s/silent-sound-ok2on6

### 重现步骤

1. 节点添加双击事件
`graph.on('cell:dblclick', (p: any) => {
      let { cell, e } = p;
      let name = p.node ? 'node-editor' : 'edge-editor';
      cell.addTools({
        name: name,
        args: {
          event: e,
        },
      });
    });`
2. 监听节点变化得到数据并保存为json字符串
`
graph.on('cell:mouseleave', () => {
      JSON.stringify(graph.toJSON())
});
`

### 预期行为

我希望在每进行一步操作的时候系统都可以把该操作的数据保存起来，那样的话再次打开系统就可以保存修改内容了。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/27398232/182087448-079f8697-87de-4e63-ab19-076e19aadb80.png)

**Comment by NewByVector** [comment]
问题出现原因是 event: e 参数无法序列化，但是这里的改动会有 break change，所以我们会在 2.0 版本中修复该问题。
