### ISSUE TITLE
在 React useEffect 中管理图的事件监听函数

### ISSUE THREAD

**Issue by lajamoqifa** [antvis/X6#2445]
### Describe the bug

react  监听代码中每次重置事件无效
const clickNode = ({ node }: { node: Node }) => {
    const meta = node.getAttrs().meta
    const menu = meta.menu
    if (!menu) {
      setVisible(true)
      setActiveNode(node)
    }
  }
  useEffect(() => {
    if (graph) {

      graph
      .off('node:click', clickNode)

      graph.on('node:click', clickNode)
  
    }
  }, [activeNode, graph, menuNode])

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
无

**Comment by tonywu6** [comment]
Hello!

- 按照你的示例代码：
```tsx
const clickNode = ({ node }: { node: Node }) => { /* ... */ }
```
这里，每次这个 React Component 重新渲染时，`clickNode` 都会被重新定义，因此在下文中 `graph.off(..., clickNode)` 尝试解绑的是重新定义的**新的 `clickNode`, 而不是已经绑定的，来自上一次渲染的 `clickNode`**, 那么 `graph.off` 没有效果，因为新的 `clickNode` 从来没有被绑定过；如果不希望 `clickNode` 在每次重新渲染时都被重新定义，参见 [`useCallback`](https://zh-hans.reactjs.org/docs/hooks-reference.html#usecallback)
- 无论是否使用 `useCallback`, 如果想要达到“在重新渲染时销毁事件/清除订阅”的效果，正确的做法是使用 [`useEffect` 的返回函数](https://zh-hans.reactjs.org/docs/hooks-reference.html#cleaning-up-an-effect)：
```tsx
useEffect(() => {
  graph.on('node:click', clickNode)
  return () => {
    graph.off('node:click', clickNode)
  }
}, [...])
这个返回的函数将在下一次 `useEffect` 再次运行**之前** 运行
