### ISSUE TITLE
希望对port添加鼠标事件的监听

### ISSUE THREAD

**Issue by MonkeySuncen** [antvis/X6#2447]
如[LZCaaT]所说，我也希望鼠标放置在port上时出现tooltip（需求一），但我还有个需求，在连线时，置灰所有不能连的port（需求二）。
由于需求一需要用vue创建自定义port，它是通过onPortRendered方法重新渲染实现的。但结合需求二时，也会触发onPortRendered。
这导致两个负面效果：
1. tooltip在鼠标放置后，点击鼠标拖线，此时触发onPortRendered方法重新渲染port，**导致tooltip不再消失**。因为dom被重新渲染了，没有鼠标离开事件了。（该问题通过tooltip单例绑定事件，曲线救国解决了。。。）
2. 每次拖线时触发需求二，每个节点都会重新渲染三次（原理未知，可能是先去除port渲染一次，添加port渲染一次，置灰渲染一次）。这导致频繁重新渲染。如果使用自带circle的port，应该不会触发这么多无意义的渲染。

综上所述，若能对port添加鼠标进入。离开事件，搭配自带circle的port问题就能优雅的解决。**希望对port添加鼠标事件的监听**。

_Originally posted by @MonkeySuncen in https://github.com/antvis/X6/issues/1609#issuecomment-1201948135_

**Comment by NewByVector** [comment]
增加 port 上的 `mosueenter`、`mouseleave`、`click`、`dblclick` 事件确实能简化一些代码，我们计划是在 2.0 版本中补齐这些事件。

**Comment by fengqingyundan1** [comment]
增加 port 上的 mosueenter、mouseleave、click、dblclick 事件确实能简化一些代码，我们计划是在 2.0 版本中补齐这些事件。2.0貌似没有加这些功能吧？
