### ISSUE TITLE
连接桩动态配置

### ISSUE THREAD

**Issue by Sharang-heng** [antvis/X6#2448]
### 功能描述

连接桩的数量根据用户在流程图中对节点进行条件配置的数量动态生成

### 期望解决方案

提供一个动态配置的api

**Comment by NewByVector** [comment]
连接桩是通过 ports 配置生成的，而且可以动态增、删、改，所以你的需求其实当前以及满足的。

**Comment by Sharang-heng** [comment]
通过ports 配置生成之后这个配置还能改变嘛？我这边的需求是通过外部配置的条件数量生成对应数量的连接桩
