### ISSUE TITLE
导出图片各种bug

### ISSUE THREAD

**Issue by komagic** [antvis/X6#2456]
### Describe the bug

话不多说，看图

![iShot_2022-08-03_15 39 37](https://user-images.githubusercontent.com/13415767/182552678-58a4fb9d-7bcf-4c3a-9c1a-7644be172d3a.png)
![Aug-03-2022 15-44-05](https://user-images.githubusercontent.com/13415767/182552740-c4cbb11a-d102-4538-b4d6-6664260cff8a.gif)

<img width="483" alt="image" src="https://user-images.githubusercontent.com/13415767/182552885-679ab444-a436-49ff-a288-528359630ffb.png">

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

```

    "@antv/x6": "^1.32.11",
    "@antv/x6-react-components": "^1.1.15",
    "@antv/x6-react-shape": "1.6.0",
```

### Expected behavior

编辑完页面后，导出，先是闪一下，然后图片奇形怪状

你是不是要等整个页面加载完了再保存dom？

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

d

**Comment by komagic** [comment]
加了transition ，颜色都可以没了

**Comment by komagic** [comment]
你的graph加载完了->然后监听all dom loaded->然后再导出？

闪一下你不能用个别的页面完成你的screenshot？非要在用户的页面上搞一下？

**Comment by NewByVector** [comment]
这个可以提供一个可以复现的 demo 吗，我们定位一下具体原因？

**Comment by NewByVector** [comment]
因为无法复现，先关闭了，如果可以提供一个可以复现的 demo，请重新提一个 issue。
