### ISSUE TITLE
文档：在 iPad OS 14.6 上 Safari 浏览，左侧菜单无法展开子菜单

### ISSUE THREAD

**Issue by onlyling** [antvis/X6#2458]
### Describe the bug

在 iPad OS 14.6 上 Safari 浏览文档，左侧菜单无法展开子菜单。

在 Antd 文档上试「内嵌菜单」没有问题。

### Your Example Website or App

https://x6.antv.vision/zh/docs/tutorial/about

### Steps to Reproduce the Bug or Issue

1. iPad OS 14.6 Safari 打开链接
2. 点击「基础教程」等可以折叠的菜单

### Expected behavior

.

### Platform

- OS: iPad OS 14.6
- Browser: Safari
- Version: 14.1.1
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15

**Comment by qq406601626** [comment]
I have the same problem，I tried both my pad and my mobile phone, but they failed

**Comment by NewByVector** [comment]
这个是官网项目的问题，我们尽快定位修复。

**Comment by qq406601626** [comment]
> 这个是官网项目的问题，我们尽快定位修复。

Will it be fixed?

**Comment by NewByVector** [comment]
@qq406601626 Yes, but we are working on version 2.0 and will fix it later.

**Comment by qq406601626** [comment]
> @qq406601626 Yes, but we are working on version 2.0 and will fix it later.

okay，thanks~

**Comment by NewByVector** [comment]
[2.x 官网](http://x6.antv.antgroup.com/tutorial/about) 已经修复了该问题。
