### ISSUE TITLE
请教一下，如何使得连接桩的label hover上去才显示

### ISSUE THREAD

**Issue by Sharang-heng** [antvis/X6#2459]
### 功能描述

官网中找到的只有控制连接桩显示/隐藏，没能找到控制连接桩label的方式
    const showPorts = (ports: NodeListOf<SVGElement>, show: boolean) => {
      for (let i = 0, len = ports.length; i < len; i = i + 1) {
        ports[i].style.visibility = show ? 'visible' : 'hidden';
      }
    };
    graph.on('node:mouseenter', () => {
      const container = document.getElementById('graph-container')!;
      const ports = container.querySelectorAll('.x6-port-body') as NodeListOf<SVGElement>;
      showPorts(ports, true);
    });

### 期望解决方案

请问有没有哪个属性能控制显示？

**Comment by NewByVector** [comment]
实现思路和上面的连接桩隐藏/显示类似，鼠标进入连接桩时，将 label dom 显示出来。但是你这个场景是不是用 [port tooltip](https://x6.antv.vision/zh/examples/node/tool#port-tooltip) 更合适？
