### ISSUE TITLE
markup 的 attrs 配置未正确被设置在标签属性上

### ISSUE THREAD

**Issue by bigbigbo** [antvis/X6#2461]
### Describe the bug

我尝试给内置的 `button-remove` tool 增加一个 `title` 提示，所以我使用到了 `args.markup`，并设置如下:

```js
{
markup: [
      {
        tagName: 'title',
        textContent: '删除',
      },
      {
        tagName: 'circle',
        attrs: {
          r: 7,
          fill: '#FF1D00',
          cursor: 'pointer',
        },
      },
      {
        tagName: 'path',
        attrs: {
          d: 'M -3 -3 3 3 M -3 3 3 -3',
          stroke: '#FFFFFF',
          strokeWidth: 2,
          pointerEvents: 'none',
          fill: 'none',
        },
      },
    ],
}
```

但是最终体现在节点上面的属性竟然是如下图所示：
![image](https://user-images.githubusercontent.com/19587016/182804754-e41e0bb1-9ef9-48b4-bfb4-75d1cd92dded.png)

这应该是 bug 吧?

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

能正确设置 attrs

### Platform

- OS: Windows
- Browser: Chrome
- Version: 103.0

**Comment by NewByVector** [comment]
我使用你的例子，产出的 dom 元素如下：
```html
<g class="x6-cell-tool x6-node-tool x6-cell-tool-button" data-cell-id="8100b1b6-d5b2-4b62-a477-5bd60fb53972" data-tool-name="button" transform="matrix(1,0,0,1,320,320)">
  <title>删除</title>
  <circle r="7" fill="#FF1D00" cursor="pointer"></circle>
  <path d="M -3 -3 3 3 M -3 3 3 -3" stroke="#FFFFFF" stroke-width="2" pointer-events="none" fill="none"></path>
</g>
```
是符合预期的。

**Comment by bigbigbo** [comment]
> 

我创建了一个可复现的例子：
https://codesandbox.io/s/reverent-ramanujan-h3yyqr?file=/src/App.js

**Comment by bigbigbo** [comment]
![image](https://user-images.githubusercontent.com/19587016/183546590-5cbb77e3-131f-4696-9a28-55aee3f96b24.png)

**Comment by NewByVector** [comment]
边上确实有问题，我们排查一下。

**Comment by NewByVector** [comment]
这里不要使用 `button-remove` 工具，因为这个工具的 markup 是内部已经定义好的，你配置后只是会 merge 进原来配置。可以直接使用 `button` 工具。
