### ISSUE TITLE
节点隐藏后再显示，对应连线的显示层级不正确

### ISSUE THREAD

**Issue by bigbigbo** [antvis/X6#2465]
### Describe the bug

1. 一开始创建连线的时候，设置 zIndex 为 -1,
2. 使用 toggleVisible 切换节点的显隐状态
3. 隐藏节点后，对应的连线也会消失
4. 再显示节点的时候，连线的zIndex 还是 -1 没有问题，但是连线却跑到了节点上方去了

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1. createEdge({zIndex: -1})，此时连线在节点下方
![image](https://user-images.githubusercontent.com/19587016/183069785-cc69c4ae-862a-42b6-9324-48e803fd0ac1.png)
![image](https://user-images.githubusercontent.com/19587016/183069831-464d62ca-c9c3-46c1-9cb4-3f2b06c081e0.png)
2. 第一次 node.toggleVisible 隐藏节点
3. 再一次 node.toggleVisible 显示节点
4. 此时连线跑到了节点上方
![image](https://user-images.githubusercontent.com/19587016/183069952-cbc59c4c-2b6a-44e6-a344-1320a501caa7.png)

### Expected behavior

节点切换显隐不改变连线的显示

### Screenshots or Videos

![demo](https://user-images.githubusercontent.com/19587016/183070967-e00a3426-ce32-4081-9a66-95bbd8a5f5e1.gif)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 103.0

**Comment by bigbigbo** [comment]
我使用unfreeze触发了画布的更新，暂时解决了该问题

**Comment by NewByVector** [comment]
更新到 1.33.0 版本。

**Comment by bigbigbo** [comment]
> 更新到 1.33.0 版本。

问题还是存在

**Comment by NewByVector** [comment]
@bigbigbo 有 demo 可以看下吗？

**Comment by bigbigbo** [comment]
> @bigbigbo 有 demo 可以看下吗？

https://codesandbox.io/s/determined-panini-zqmkmf?file=/src/App.js

**Comment by bigbigbo** [comment]
@NewByVector 当我从桩点再拖出一条线准备连接的时候，连线的层级又会更新成正确的

**Comment by NewByVector** [comment]
@bigbigbo 你好，这里确实是一个问题，我们会在 2.0 版本彻底修复这个缺陷。

**Comment by NewByVector** [comment]
@bigbigbo 其实 1.x 版本中配置 sorting: [approx](https://x6.antv.vision/zh/docs/api/graph/view/#sorting) 即可解决你的问题。
