### ISSUE TITLE
selection:changed event handler returns cells already removed in the graph

### ISSUE THREAD

**Issue by xushangning** [antvis/X6#2466]
### Describe the bug

When a node and an edge are deleted together with `Graph.removeCells`, the `selected` property passed by `Graph`'s `selection:changed` event contains cells that don't exist in the graph.

### Your Example Website or App

See the minimal reproducible example below.

### Steps to Reproduce the Bug or Issue

1. Paste the following code into an HTML file and run.
    ```html
    <html>
        <head>
            <script src="https://unpkg.com/@antv/x6/dist/x6.js"></script>
        </head>
        <body>
            <div id="container" style="width: 400px; height: 300px"></div>
            <script>
                const graph = new X6.Graph({
                    container: document.getElementById('container'),
                    resizing: true,
                    selecting: {
                        enabled: true,
                    },
                    keyboard: true,
                });

                graph.on('selection:changed', ({ selected }) => {
                    console.log(
                        'Cells returned by selection:changed',
                        selected.map(cell => graph.getCellById(cell.id))
                    )
                })

                graph.bindKey(['delete', 'backspace'], () => {
                    graph.removeCells(graph.getSelectedCells())
                })

                const data = {
                    nodes: [
                        {
                            id: 'node1',
                            x: 40,
                            y: 40,
                            width: 80,
                            height: 40,
                            label: 'Hello',
                        },
                        {
                            id: 'node2',
                            x: 160,
                            y: 180,
                            width: 80,
                            height: 40,
                            label: 'World',
                        },
                    ],
                    edges: [
                        {
                            source: 'node1',
                            target: 'node2',
                        },
                    ],
                }
                graph.fromJSON(data)
            </script>
        </body>
    </html>
    ```
2. Open the developer console. In the graph, use command or Ctrl to **first select a node** and then an edge. Then, press Backspace or Delete to delete them.
3. In the console, one array of cells returned by `selection:changed` should contain a `null` returned by `getCellById`, indicating that the cell is no longer in the graph.

### Expected behavior

`selection:changed` should always return cells that exist in the graph.

### Screenshots or Videos

The following screenshot shows the developer console after a bug is reproduced:

<img width="1666" alt="Screen Shot 2022-08-06 at 19 16 34" src="https://user-images.githubusercontent.com/32517059/183272252-729a4e74-49bf-4f7d-b360-98e2711593ab.png">

### Platform

- OS: macOS
- Browser: Chrome 103.0.5060.134

### Additional context

The bug is likely caused by a corner case in `Model.removeConnectedEdges`. Because a node's connected edges are removed after the node itself but before unselecting the node, the selection still contains the already-removed node. When the `selection:changed` event is fired by the removal of connected edges, the removed node is contained in the `selected` property.

**Comment by NewByVector** [comment]
更新到 1.33.0 版本。

**Comment by Aiamjay** [comment]
已更新
