### ISSUE TITLE
官网ER路由示例中，将target变量名修改后，连线就会错乱

### ISSUE THREAD

**Issue by zeusxs** [antvis/X6#2474]
### Describe the bug

链接：https://x6.antv.vision/zh/examples/edge/router#er-normal
背景：想在官网的示例代码中做一些实验，看看展现效果 

正常样式：
![image](https://user-images.githubusercontent.com/30338668/183545912-82595702-8e9a-4d3f-9b9c-7f526629d5c7.png)

将变量名从target修改成target2后的展现样式
![image](https://user-images.githubusercontent.com/30338668/183545981-8f7d8ba9-9aa1-414c-9c4a-a5c95f678f38.png)

### Your Example Website or App

https://x6.antv.vision/zh/examples/edge/router#er-normal

### Steps to Reproduce the Bug or Issue

1. 去官网链接：https://x6.antv.vision/zh/examples/edge/router#er-normal
2. 将代码中的target变量名修改成target2
3. 观察预览窗口，会发现连线错乱

### Expected behavior

![image](https://user-images.githubusercontent.com/30338668/183545912-82595702-8e9a-4d3f-9b9c-7f526629d5c7.png)

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 103.0.5060.134

**Comment by NewByVector** [comment]
应该是:
```ts
{
  target: target2
}
```
