### ISSUE TITLE
大数据量visible产生的性能问题

### ISSUE THREAD

**Issue by struggleRoue** [antvis/X6#2487]
### 问题描述

最近一次commit 在visible改变的时候 加了this.sortViews()
性能问题很大
而且目前X6没有支持批节点隐藏，
所以在调几十个节点同时隐藏的时候 我理解会排序很多次？
所以页面非常卡顿。

### 重现链接

https://codesandbox.io/s/vigorous-feather-swq4ht?file=/src/App.js

### 重现步骤

1. 进入页面
2. 点击change visible

### 预期行为

希望正常展示、消失
但是经常由于计算量太大死机

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 1.33.0

### 补充说明（可选）

看performance感觉每隐藏一个节点就要排序一下， 是不是可以合并啊？

**Comment by babachao** [comment]
你好，用官方的hide()和show()，其实是全部删除和再次创建，节点多了，是必然会卡顿的。
如果只是单纯的希望展示和隐藏，可以参考一下我写的这个方法[使用style中的visibility的方式去隐藏和显示节点](https://codesandbox.io/s/polished-shape-6bz5gs?file=/src/App.js)
我是通过data-id这个属性去查找对应的dom节点，然后去操作show和hide，
但是这样的方式，只是将dom不可见，但仍然会影响布局

**Comment by NewByVector** [comment]
升级到 1.33.1 版本。

**Comment by struggleRoue** [comment]
哈哈哈 有没有除了这种注释这种 更优雅的解决方案呢？

比如隐藏、展示的批处理？

**Comment by struggleRoue** [comment]
> 你好，用官方的hide()和show()，其实是全部删除和再次创建，节点多了，是必然会卡顿的。 如果只是单纯的希望展示和隐藏，可以参考一下我写的这个方法[使用style中的visibility的方式去隐藏和显示节点](https://codesandbox.io/s/polished-shape-6bz5gs?file=/src/App.js) 我是通过data-id这个属性去查找对应的dom节点，然后去操作show和hide， 但是这样的方式，只是将dom不可见，但仍然会影响布局

这样很多场景是行不通的，例如现在是用visible进行节点展开收起的从新布局 和 使用visible实现的懒加载和虚拟渲染，所以还是要官方优化一下这个比较好
