### ISSUE TITLE
validateEdge 方法，不支持Promise

### ISSUE THREAD

**Issue by world56** [antvis/X6#2489]
### 功能描述

在线DEMO：https://codesandbox.io/s/trusting-cohen-mwh9rn?file=/index.ts:1963-1975

<img width="454" alt="image" src="https://user-images.githubusercontent.com/37354312/183859052-2cb7b2a0-079a-4b19-90a5-edfbcfac58c9.png">

### 期望解决方案

可以增加对promise的支持吗？
感谢🙏

**Comment by DanielLeefu** [comment]
可以监听边的连接事件edge:connected实现与服务端交互，链接后如果接口失败，再将线删除

**Comment by world56** [comment]
> 如果这里是连线交互场景的话‘可以监听边的连接事件edge:connected实现与服务端交互，链接后如果接口失败，再将线删除

嗯，这样也行，validateEdge也可以这样实现，我在加个删除吧。
