### ISSUE TITLE
连接桩自定义id，无法删除

### ISSUE THREAD

**Issue by world56** [antvis/X6#2500]
### 问题描述

<img width="646" alt="image" src="https://user-images.githubusercontent.com/37354312/184111034-cddf4e63-17c1-4598-a47d-39bd43e5743d.png">

这里使用了自定义id则无法删除，连接桩对象如何使用 **updateCellId**  方法？

### 重现链接

https://codesandbox.io/s/trusting-cohen-mwh9rn?file=/index.ts

### 重现步骤

1.进入页面
2. 点击 “Remove Port” 按钮
    该按钮会立即调用 “addPorts” 方法创建一个 ER连接桩，然后用调用 “removePort” 传入自定义id， 缺无法删除。

### 预期行为

怎么样做到自定义id删除连接桩？
连接桩对象没有 updateCellId 方法。

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome 104.0.5112.79
- X6 版本: 1.30.0

**Comment by babachao** [comment]
<img width="616" alt="55555" src="https://user-images.githubusercontent.com/26959793/184140938-54ac39c7-70ce-42dd-b9e8-6621da1d45ec.png">
你好~，id使用字符串可以解决你的问题

**Comment by world56** [comment]
> <img alt="55555" width="616" src="https://user-images.githubusercontent.com/26959793/184140938-54ac39c7-70ce-42dd-b9e8-6621da1d45ec.png">
> 
> 你好~，id使用字符串可以解决你的问题

感谢🙏，突然想到x6自己生成的id都是string，可能跟这个有关系。👍

**Comment by babachao** [comment]
嘿嘿 我也是看的文档的 [removeport](https://x6.antv.vision/zh/docs/api/model/node/#removeport)
<img width="1102" alt="WechatIMG717" src="https://user-images.githubusercontent.com/26959793/184143043-931abe61-9cd5-450e-9576-df97a0f10d42.png">

**Comment by world56** [comment]
> 嘿嘿 我也是看的文档的 [removeport](https://x6.antv.vision/zh/docs/api/model/node/#removeport) <img alt="WechatIMG717" width="1102" src="https://user-images.githubusercontent.com/26959793/184143043-931abe61-9cd5-450e-9576-df97a0f10d42.png">

看来我确实得多看看文档🤣

**Comment by babachao** [comment]
哈哈 加油
