### ISSUE TITLE
自定义继承自VueShape 的 Node

### ISSUE THREAD

**Issue by Aiamjay** [antvis/X6#2502]
### 功能描述

我想自定义一个Node
这个Node 渲染的内容来自VueComponent，同时继在Node 类上，新加了几个独特的方法， 比如 isGroup, isCollapsed 这种

### 期望解决方案

CustomeVueNode extend VueShape 
从VueShape继承过来，同时拥有自己的 特有的函数

**Comment by NewByVector** [comment]
直接定义：
```ts
class A extends VueShape{
  isGroup: false
}
Graph.registerNode('custom-vue-shape', A, true)
```
