### ISSUE TITLE
yarn bootstrap failed

### ISSUE THREAD

**Issue by loveJasmine** [antvis/X6#2506]
### Describe the bug

PS C:\react-graph\X6> yarn bootstrap

。。。。

warning "workspace-aggregator-cafc37dd-58aa-4778-990e-049307772e2a > @antv/x6-sites > gatsby > eslint-plugin-graphql > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
[4/4] Building fresh packages...
[7/24] ⠈ @antv/eslint-config
[9/24] ⠈ @antv/stylelint-config
[8/24] ⠈ @antv/x6-package-json
[10/24] ⠈ core-js
error C:\react-graph\X6\node_modules\@antv\x6-package-json: Command failed.
Exit code: 1
Command: run-s build
Arguments:
Directory: C:\react-graph\X6\node_modules\@antv\x6-package-json
Output:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\react-graph\X6\node_modules\node_modules\npm-run-all\bin\run-s\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {

lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock --no-ci exited 1 in 'x6'
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock --no-ci exited 1 in 'x6'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\react-graph\X6>

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

just follow the readme

### Expected behavior

no error

### Platform

windows 10

**Comment by yaojin2070** [comment]
一样的问题, 解决了吗

**Comment by loveJasmine** [comment]
显然没有

**Comment by zColorful** [comment]
看来是没有人处理这个问题

**Comment by NewByVector** [comment]
参考这个回答 https://github.com/antvis/X6/issues/809#issuecomment-946608085。
