### ISSUE TITLE
画布冻结后，拖动节点导致选中框异常

### ISSUE THREAD

**Issue by wb-wenbei** [antvis/X6#2507]
### Describe the bug

画布冻结后，拖动节点应该是无效的，实际结果也是无效的，但是拖动节点后，再点击节点选中，该节点的选中框出现在节点拖动后的位置了。

### Your Example Website or App

https://codesandbox.io/s/nostalgic-mahavira-butfps?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1.打开测试页面：[链接](https://codesandbox.io/s/nostalgic-mahavira-butfps?file=/src/app.tsx)
2.点击【Hello】节点并拖动到任意位置
3.点击选中【Hello】节点，发现节点的选中框出现在了拖动后的位置上

### Expected behavior

【Hello】节点的选中框应该出现在节点位置上

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by wb-wenbei** [comment]
又发现一个画布冻结到问题，和选择框的异常应该是一类问题：

1.画布冻结后拖动节点
2.画布解除冻结状态
结果：拖动的节点位置发生了变化（变化到拖动到的位置了）
预期结果：节点位置应该不变化

**Comment by babachao** [comment]
的确是有这个问题[吃瓜]

**Comment by babachao** [comment]
![image](https://user-images.githubusercontent.com/26959793/185350906-34e09a7c-aba5-4114-8e57-4d473bc7a37c.png)
freeze()功能是为了处理大量节点时场景使用的；
你是想实现啥功能呀？是希望将画布不可编辑吗？

**Comment by wb-wenbei** [comment]
对，想让画布变为不可编辑状态

**Comment by wb-wenbei** [comment]
> ![image](https://user-images.githubusercontent.com/26959793/185350906-34e09a7c-aba5-4114-8e57-4d473bc7a37c.png) freeze()功能是为了处理大量节点时场景使用的； 你是想实现啥功能呀？是希望将画布不可编辑吗？

对

**Comment by babachao** [comment]
https://x6.antv.vision/zh/docs/tutorial/basic/interacting/#%E5%AE%9A%E5%88%B6%E4%BA%A4%E4%BA%92%E8%A1%8C%E4%B8%BA
![image](https://user-images.githubusercontent.com/26959793/185535324-2e43e520-9c5c-4ad1-895e-1951546e29b4.png)
可以结合禁用节点移动，做一个预览模式

**Comment by wb-wenbei** [comment]
> 

好的，多谢！之前也看过这种方式实现，不过要不止要禁用节点/边的移动，还有节点/边的添加、删除、选中等行为，感觉比较麻烦，就找了下有没有其他方式做预览，看到了freeze方法，理解不到位，以为是bug
