### ISSUE TITLE
fromJSON捕获异常和错误。

### ISSUE THREAD

**Issue by Kefeng2017** [antvis/X6#2508]
### 功能描述

通过toJSON存储了旧版本的画布数据，新版本的画布删除了一些自定义形状和组件，此时在新画布上通过fromJSON渲染旧画布的数据可能会出现component not exist的报错。
![image](https://user-images.githubusercontent.com/33170776/184566646-b5e80084-506d-4c14-9dc8-01c2e0ae9206.png)
导致画布无法正常渲染或者渲染出错。

如果可以监听fromJSON过程中产生的错误并提示用户，可以优化用户体验。

### 期望解决方案

希望可以添加 render:error 事件

**Comment by NewByVector** [comment]
这个提示已经比较明显了。
