### ISSUE TITLE
Edge在重新绘制时，zIndex的效果失效

### ISSUE THREAD

**Issue by AricZhu** [antvis/X6#2511]
### Describe the bug

下图是第一次绘制的时候，edge 可以正确的展示在 port 下面
<img width="272" alt="image" src="https://user-images.githubusercontent.com/34393362/184586825-b1af4994-3b0c-418d-a856-9c985210903d.png">

但在节点进行“展开/收起”交互后，edge 重新绘制完，就跑到了 port 上面了，如下：
<img width="222" alt="image" src="https://user-images.githubusercontent.com/34393362/184586937-a5013fc4-88d6-4b03-9d34-faaa02a497db.png">

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

edge 再重新绘制后，不应该更改 zIndex 的效果

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Chrome

**Comment by NewByVector** [comment]
将 graph 的配置 [sorting](https://x6.antv.vision/zh/docs/api/graph/view#sorting) 修改为 approx 即可。
