### ISSUE TITLE
使用stencil时，如何异步设置groups

### ISSUE THREAD

**Issue by Mrheqiang** [antvis/X6#2512]
### 功能描述

由于事先不清楚整个数据，需要去后台请求然后动态设置groups（也就是说groups是后台获取的）  目前不能在初始化后修改。

### 期望解决方案

希望可以出现类似与 resizeGroup 的API  用来修改或者设置组信息

**Comment by NewByVector** [comment]
数据异步加载后可以使用 `stencil.load()` 方法来动态加载内容。你的问题是怎么做到 group 大小的自适应吗？如果是的话，可以将 `graphHeight` 设置为 0 达到目的。
