### ISSUE TITLE
能否支持超大数据量node/edge渲染？

### ISSUE THREAD

**Issue by king-peach** [antvis/X6#2513]
### 功能描述

当遇到需要渲染上万条的node/edge时，直接使用resetCells()、addNode()、addEdge()都会导致页面卡死

### 期望解决方案

如果能提供能直接展示万条数据以上的api或示例就好了，谢谢！

**Comment by lloydzhou** [comment]
超大数据量的场景，可以尝试使用 [@antv/g6 ](https://github.com/antvis/g6) G6针对大图的场景有做针对性的优化
https://g6.antv.vision/en/examples/gallery#category-PerformanceCase

![image](https://user-images.githubusercontent.com/1826685/184603627-9679d1d3-d70c-4d12-b441-7fcba95a5850.png)

**Comment by struggleRoue** [comment]
如果是标准布局可以考虑自己实现一下虚拟渲染？

**Comment by lloydzhou** [comment]
x6是以svg来渲染画布，每一个节点都是svg的元素，当元素比较多的时候性能比较差，而且比较难实现“脏矩阵”渲染逻辑。
就算能实现对应的算法，那也会牵涉到大量的dom元素操作，性能也好不了。

所以在渲染大量元素的时候canvas就比较有优势。

**Comment by king-peach** [comment]
@lloydzhou 感谢您的建议，svg渲染大数据量的时候确实有点吃力，后来我发现耗时主要在布局上，当使用tree布局时需要不断调整节点位置，所以导致渲染时间很长，页面卡死，后面可能会找一下canvas的实现方式，x6目前没找到合适的渲染方式😢

**Comment by king-peach** [comment]
@struggleRoue 请问虚拟渲染是指？

**Comment by struggleRoue** [comment]
> @struggleRoue 请问虚拟渲染是指？

尝试使用visible 只显示视口三屏内的元素。
当然会有一些其他问题
1. 你不能控制visible了
2. 布局比较奇怪的可能会有问题

**Comment by lloydzhou** [comment]
@struggleRoue 这里还是会有一些比较现实的问题

**Comment by lloydzhou** [comment]
> @lloydzhou 感谢您的建议，svg渲染大数据量的时候确实有点吃力，后来我发现耗时主要在布局上，当使用tree布局时需要不断调整节点位置，所以导致渲染时间很长，页面卡死，后面可能会找一下canvas的实现方式，x6目前没找到合适的渲染方式cry

@king-peach 如果已经定位到问题出在布局上面，那可以建议你使用布局的时候不要一直等布局成功之后再进行渲染。可以尝试，一边布局一边渲染。

例如：[@antv/layout gForce](https://github.com/antvis/layout/blob/master/src/layout/gForce.ts#L106)布局支持`tick`回调会在每次布局算法迭代结束的时候调用这个回调函数（其实就可以在这个回调里面更新节点位置）。另外`gForce`布局算法还支持`workerEnabled`使用`web worker`进行计算，这样不至于因为大量CPU计算导致主线程卡住，UI自然也就顺畅了。

这些布局算法的文档可以参考　https://g6.antv.vision/zh/docs/api/graphLayout/gforce

**Comment by king-peach** [comment]
> > @lloydzhou 感谢您的建议，svg渲染大数据量的时候确实有点吃力，后来我发现耗时主要在布局上，当使用tree布局时需要不断调整节点位置，所以导致渲染时间很长，页面卡死，后面可能会找一下canvas的实现方式，x6目前没找到合适的渲染方式cry
> 
> @king-peach 如果已经定位到问题出在布局上面，那可以建议你使用布局的时候不要一直等布局成功之后再进行渲染。可以尝试，一边布局一边渲染。
> 
> 例如：[@antv/layout gForce](https://github.com/antvis/layout/blob/master/src/layout/gForce.ts#L106)布局支持`tick`回调会在每次布局算法迭代结束的时候调用这个回调函数（其实就可以在这个回调里面更新节点位置）。另外`gForce`布局算法还支持`workerEnabled`使用`web worker`进行计算，这样不至于因为大量CPU计算导致主线程卡住，UI自然也就顺畅了。
> 
> 这些布局算法的文档可以参考　[https://g6.antv.vision/zh/docs/api/graphLayout/gforce　](https://g6.antv.vision/zh/docs/api/graphLayout/gforce%E3%80%80)

@lloydzhou 感谢您的建议，我会进行尝试的，我的问题暂时已解决👍

**Comment by king-peach** [comment]
> > @struggleRoue 请问虚拟渲染是指？
> 
> 尝试使用visible 只显示视口三屏内的元素。 当然会有一些其他问题
> 
> 1. 你不能控制visible了
> 2. 布局比较奇怪的可能会有问题

@struggleRoue 感谢您的建议，我的问题已解决🙏；visible应该可以控制，主要是写树形布局之类的算法，对node进行定位就可以

**Comment by struggleRoue** [comment]
> > @lloydzhou 感谢您的建议，svg渲染大数据量的时候确实有点吃力，后来我发现耗时主要在布局上，当使用tree布局时需要不断调整节点位置，所以导致渲染时间很长，页面卡死，后面可能会找一下canvas的实现方式，x6目前没找到合适的渲染方式cry
> 
> @king-peach 如果已经定位到问题出在布局上面，那可以建议你使用布局的时候不要一直等布局成功之后再进行渲染。可以尝试，一边布局一边渲染。
> 
> 例如：[@antv/layout gForce](https://github.com/antvis/layout/blob/master/src/layout/gForce.ts#L106)布局支持`tick`回调会在每次布局算法迭代结束的时候调用这个回调函数（其实就可以在这个回调里面更新节点位置）。另外`gForce`布局算法还支持`workerEnabled`使用`web worker`进行计算，这样不至于因为大量CPU计算导致主线程卡住，UI自然也就顺畅了。
> 
> 这些布局算法的文档可以参考　[https://g6.antv.vision/zh/docs/api/graphLayout/gforce　](https://g6.antv.vision/zh/docs/api/graphLayout/gforce%E3%80%80)

可是我发现X6 节点的setProp 更新一个节点的位置也需要5-20ms，就算这样我针对性1000个节点进行位置更新也需要10几秒。

**Comment by lloydzhou** [comment]
@struggleRoue 
这里更新一个节点也需要这么长时间，是没有预料到的！！！

你可以试一试以下的操作：
1. 开启异步渲染[async](https://x6.antv.vision/en/docs/api/graph/view#async)
2. 使用事务 [startBatch](https://x6.antv.vision/en/docs/api/graph/graph/#startbatch) + [stopBatch](https://x6.antv.vision/en/docs/api/graph/graph/#stopbatch)

**Comment by struggleRoue** [comment]
> @struggleRoue 这里更新一个节点也需要这么长时间，是没有预料到的！！！
> 
> 你可以试一试以下的操作：
> 
> 1. 开启异步渲染[async](https://x6.antv.vision/en/docs/api/graph/view#async)
> 2. 使用事务 [startBatch](https://x6.antv.vision/en/docs/api/graph/graph/#startbatch) + [stopBatch](https://x6.antv.vision/en/docs/api/graph/graph/#stopbatch)

我试了一下用处感觉不是很大
因为我也在优化布局以及首屏渲染速度。
根据您的启发，我在使用webworker + 边布局边渲染的方式
但是效果并不如意， 我发现使用webworker + 变布局边渲染的方式，很大一部分时间都用在了setProp上面，我甚至是用了你们没有抛出来的this.store.set方法，速度还是比较慢的。
所以总体来说
webworker + 变布局边渲染的方式  在任何方式下都不如 直接布局后渲染。
不知道有没有什么好一点的解决方式？

**Comment by struggleRoue** [comment]
![20220817152428](https://user-images.githubusercontent.com/47975400/185059483-e17c8d5d-1cce-4e1f-a6df-96ff774d4d64.gif)
![20220817152506](https://user-images.githubusercontent.com/47975400/185059615-5ed77480-8e8d-45d0-83af-4bd2cfc4cff7.gif)
两种方式分别的效果

**Comment by lloydzhou** [comment]
最后再发一条，不知道这个demo会不会有帮助

https://x6.antv.vision/demos/api/graph/checkview/

**Comment by rainbowcv** [comment]
> 

你好，请问图一是边布局边渲染+webwork嘛，能否看看代码

**Comment by rainbowcv** [comment]
> ![20220817152428](https://user-images.githubusercontent.com/47975400/185059483-e17c8d5d-1cce-4e1f-a6df-96ff774d4d64.gif) [ ![20220817152428](https://user-images.githubusercontent.com/47975400/185059483-e17c8d5d-1cce-4e1f-a6df-96ff774d4d64.gif) ](https://user-images.githubusercontent.com/47975400/185059483-e17c8d5d-1cce-4e1f-a6df-96ff774d4d64.gif) [ ](https://user-images.githubusercontent.com/47975400/185059483-e17c8d5d-1cce-4e1f-a6df-96ff774d4d64.gif) ![20220817152506](https://user-images.githubusercontent.com/47975400/185059615-5ed77480-8e8d-45d0-83af-4bd2cfc4cff7.gif) [ ![20220817152506](https://user-images.githubusercontent.com/47975400/185059615-5ed77480-8e8d-45d0-83af-4bd2cfc4cff7.gif) ](https://user-images.githubusercontent.com/47975400/185059615-5ed77480-8e8d-45d0-83af-4bd2cfc4cff7.gif) [ ](https://user-images.githubusercontent.com/47975400/185059615-5ed77480-8e8d-45d0-83af-4bd2cfc4cff7.gif) 两种方式分别的效果

你好，图一是边布局边渲染+webworker的例子嘛，能否看看代码学习一下

**Comment by xiazhaohui** [comment]
> 

实现思路是什么呢？
