### ISSUE TITLE
通过深度克隆来比较数据更新，性能太差

### ISSUE THREAD

**Issue by willzhanglala** [antvis/X6#2516]
### 问题描述

store.ts 中
```ts
  protected mutate<K extends keyof D>(
    data: Partial<D>,
    options: Store.MutateOptions = {},
  ) {
    const unset = options.unset === true
    const silent = options.silent === true
    const changes: K[] = []
    const changing = this.changing

    this.changing = true

//此处作 cloneDeep，性能无法控制
    if (!changing) {
      this.previous = ObjectExt.cloneDeep(this.data)
      this.changed = {}
    }

    const current = this.data
    const previous = this.previous
    const changed = this.changed

    // ...
}
```

我们将利用x6 的 setData 存储一些用户对象，这些对象内又会引用其它对象，预期的引用会将我们整个project引用到。
这个导致x6性能非常不理想！

这部分代码应当仅仅是为了查找变更的属性。请不要这么暴力地使用deepClone。
通过深度遍历，就可以做到这点，如果在key上有发生变化，就可以提前结束遍历。如果存储的是对象，那么若 objA === objB，引用相同的情况下，就连深度遍历也不需要。何必如此大费周章？

### 重现链接

无

### 重现步骤

let data= {
    __referToProject : project
}

node.setData({entity: data } )

### 预期行为

mutate 时，不再出现 deepClone

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
这里的 data 建议保存和节点相关的业务数据，一般都不会太大。

**Comment by willzhanglala** [comment]
我们是把x6当作纯粹的渲染器，在每个x6
Node上我们需要保存一个userObject是我们真正的数据。当x6的数据发生变化时，我们通过回调更改自身userObject内的数据。我们的userObject是个树状结构，通过parent和children，可以遍历整棵树，通过
this.project可以遍历整个我们的项目。很显然，你不能假设一个userObject是 数值型的，不会引用项目内容。



Will Zhang


vector ***@***.***> 于2022年9月2日周五 15:41写道：

**Comment by NewByVector** [comment]
@willzhanglala 提个 PR？

**Comment by dragooncjw** [comment]
我这里也碰到了类似的问题：
我发现将mutate的cloneDeep替换成clone的影响。
cloneDeep的时候，在大量node、edge的场景下，v1版本，使用position 去设置节点位置的时候，会有大量mutate cloneDeep耗时。
![acb49844-2705-4ceb-9bd9-9cef79616489](https://user-images.githubusercontent.com/13393433/218991501-b4352139-7cc9-42bd-b8bb-1e37dec4d077.jpeg)
将mutate里的几个cloneDeep都改成clone可以大大优化性能。
https://github.com/antvis/X6/blob/v1/packages/x6/src/model/store.ts#L33
但是想问一下影响：我切换成clone后，我们这里交互渲染都正常。这里使用cloneDeep的原因是因为什么？

**Comment by luics** [comment]
> 我这里也碰到了类似的问题： 我发现将mutate的cloneDeep替换成clone的影响。 cloneDeep的时候，在大量node、edge的场景下，v1版本，使用position 去设置节点位置的时候，会有大量mutate cloneDeep耗时。 <img alt="image" width="1129" src="https://user-images.githubusercontent.com/13393433/218992005-3657a0a2-dae0-492a-ad38-ee0523a39899.png"> 将mutate里的几个cloneDeep都改成clone可以大大优化性能。 https://github.com/antvis/X6/blob/v1/packages/x6/src/model/store.ts#L33 但是想问一下影响：我切换成clone后，我们这里交互渲染都正常。这里使用cloneDeep的原因是因为什么？

同问，有同学帮忙看下不~

**Comment by NewByVector** [comment]
@dragooncjw @luics 节点里面如果没有存储大对象的话，一般不会出现性能问题。是不是将 component 等组件对象也放在了节点内部呀？

**Comment by NewByVector** [comment]
最佳实践是在 data 中只存储一些简单的对象，如果是复杂对象的话不可避免的会有性能问题。
