### ISSUE TITLE
【自定义节点渲染】节点的渲染顺序

### ISSUE THREAD

**Issue by webzmj530** [antvis/X6#2521]
### 问题描述

自定义节点渲染的时候，通过addNode和addEdge的时候，节点的连接桩和edge边，先出现，节点的数据会延迟渲染。如下图：
![1660566455886](https://user-images.githubusercontent.com/39976433/184635276-b9e47057-4371-4e6a-8d13-4439f0fa4299.jpg)

### 重现链接

无

### 重现步骤

这边再去取到节点数据之后，通过
cells.filter(item => item.shape == 'dag-node').map(e=>{
        this.graph.addNode(e);
      })
cells.filter(item => ['edge', 'dag-edge'].includes(item.shape)).map(e=>{
        this.graph.addEdge(e);
    })
去添加节点和边，发现 节点的port和先渲染出来，节点的数据会延迟渲染
    
![image](https://user-images.githubusercontent.com/39976433/184634153-048c8ed8-1e10-41b9-beed-c1df977a2f24.png)
之后节点里面的其他信息才会渲染出来
在自定义节点里面是这么获取数据的
    const node = this.getNode()
    this.data  = _.cloneDeep({...node.data})

### 预期行为

怎么让节点的数据和节点的ports和edges同一时间渲染

### 平台

- 操作系统: Windows
- 网页浏览器: Google 
- X6 版本: 1.28.1

**Comment by lloydzhou** [comment]
自定义节点（不管是react/vue/html的节点）渲染都会比连接桩和边框要晚。
以vueshape为例：

https://github.com/antvis/X6/blob/02579cb1c1/packages/x6-vue-shape/src/view.ts#L26

`VueShapeView.renderVueComponent`函数每次都会调用`createApp`生成一个新的`App`然后`mount`到`foContent`节点内部。
这里的createApp＋mount自然会比较耗时的操作。会明显的比边框和port要晚。

如果想要一起出现，这里有两个办法可以试一试：
1. 给节点设置一个fadeIn的动画，自己调试一下，尽量让fadeIn的时间和自定义节点渲染的时间一致。这样看起来就像是一起渲染的了。
2. 先给节点设置`visibility: hidden;`等自定义节点mounted之后，再把当前节点的这个css样式改成`visibility: visible;`
