### ISSUE TITLE
连接桩port区分类型

### ISSUE THREAD

**Issue by chennh** [antvis/X6#2523]
### 功能描述

**使用场景**
做一个数据流的配置，实现配置1 + 1，逻辑计算后输出2。
通过antv x6拖拽配置实现加法操作，需要区分port为输入port、输出port。两个1连接到加法Node的输入port，加法Node的输出port连接到结果Node。
输入port：edge连接到这个port，不能发起edge连接
输出port：发起edge连接到其他输入port，不能被其他edge连接

**尝试过**
1、在输入port上配置magnet: false。不允许发起edge连接，同时导致不能被连接
2、通过validateMagnet判断，无法知晓当前点击了哪个port

### 期望解决方案

1、port的magnet配置能区分是发起连接还是被动连接，不要同时启用/禁用
2、validateMagnet中能提供当前被点击的port，而不是manage的dom对象

**Comment by DanielLeefu** [comment]
链接的时候使用这个判断https://x6.antv.vision/zh/docs/api/graph/interaction#validateconnection

**Comment by NewByVector** [comment]
`magnet.getAttribute('port')` 能拿到 port 的 id，根据 id 来做判断。
