### ISSUE TITLE
用Firefox ESR版本的浏览器，打不开X6，但是G6可以

### ISSUE THREAD

**Issue by anyone0034** [antvis/X6#2525]
### 问题描述

用Firefox ESR版本的浏览器，打不开X6，但是G6可以。

### 重现链接

https://codesandbox.io/s/xenodochial-moser-eec8xf?file=/src/App.js

### 重现步骤

1. chrome下可以打开，forefix ser打不开。

### 预期行为

希望有正确的结果显示。

### 平台

- 操作系统: [ubuntu]
- 网页浏览器: [Firefox SER 52.3.0 64位]
- X6 版本: [1.33.1]
    "@antv/x6": "^1.32.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",

**Comment by NewByVector** [comment]
你给的链接不对呢。
