### ISSUE TITLE
x6在低版本浏览器中，无法正常的渲染自定义节点

### ISSUE THREAD

**Issue by hanqiufeng** [antvis/X6#2526]
### 问题描述

在低版本浏览器中，无法正常的渲染自定义节点

### 重现链接

无

### 重现步骤

1.首次渲染时不会正常显示
2.当移动节点时，偶尔能正常渲染出自定义的vue节点

### 预期行为

期望能在低版本浏览器中正常渲染

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Firefox 52.3.0]
- X6 版本: [1.32.7 ]

### 屏幕截图或视频（可选）

![微信图片_20220816142138](https://user-images.githubusercontent.com/35101809/184811688-3abae9f2-8954-45b4-891c-5ed818801b63.png)
![微信图片_20220816142157](https://user-images.githubusercontent.com/35101809/184811687-82d6a199-fa63-40ae-9732-7dfc72264e6a.png)
期望如下图所示
![微信图片_20220816142219](https://user-images.githubusercontent.com/35101809/184811717-32e11acf-390f-4568-9c15-d55e309ac9f6.png)

**Comment by mioxs** [comment]
一样的问题

**Comment by komagic** [comment]
用 html-to-image toBlob 导出即可。

**Comment by hanqiufeng** [comment]
> 谷歌62出现的同样的问题，应该是使用vue自定义显示位置问题。

自定义节点在页面中并没有渲染出来，dom节点也是不存在

**Comment by hanqiufeng** [comment]
> 用 html-to-image 把 Blob 导出即可。

这个不是导出的问题，而是渲染的问题

**Comment by NewByVector** [comment]
有可以复现的 demo 看下吗，我在 chrome 低版本上访问 vue demo，没有复现你的问题。
