### ISSUE TITLE
示例代码拼写错误

### ISSUE THREAD

**Issue by wb-wenbei** [antvis/X6#2531]
### Describe the bug

![image](https://user-images.githubusercontent.com/38773084/184886191-3df7a0d8-3285-4d38-8944-a904661aaf51.png)

https://codesandbox.io/s/ju0s7v

### Your Example Website or App

https://codesandbox.io/s/ju0s7v

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/ju0s7v

### Expected behavior

fontSize

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lloydzhou** [comment]
@NewByVector 
pr里面忘记写close，这个issue需要手动合并
