### ISSUE TITLE
Dnd拖拽，一次性增加多个node在画布上

### ISSUE THREAD

**Issue by Mrheqiang** [antvis/X6#2532]
### 功能描述

左侧列表展示最基本的node，当拖拽到画布上时，**需要完整显示整个数据（包括children里面的node和edge）**，这样可以完整的展示整个graph的数据

### 期望解决方案

提供一种可以一次性增加多个node的方案，类似dnd.start(nodes， e）nodes表示node数组

**Comment by lloydzhou** [comment]
可以参考这个回复 https://github.com/antvis/X6/issues/2349#issuecomment-1185422192

`validateNode`的时候直接在画布添加`nodes`（包含`chidren`），最后返回一个`Promise.resolve(false)`（拖拽过程中的节点不会被添加到画布上）
