### ISSUE TITLE
流程图中怎样判断边/rect节点的任意一条边，和另外的边是否有交点？

### ISSUE THREAD

**Issue by LiuyingAudrey** [antvis/X6#2539]
### Describe the bug

流程图中怎样判断边/rect节点的任意一条边，和另外的边是否有交点？

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
可以使用 path 相交来计算，可以参考这个 [项目](http://www.kevlindev.com/geometry/2D/intersections/index.htm)
