### ISSUE TITLE
npm缺少 @antv/x6-react-components 1.1.16版本

### ISSUE THREAD

**Issue by heerake** [antvis/X6#2545]
### Describe the bug

@antv/x6-react-components版本号是1.1.16，但是npm上只有1.1.15

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

npm有1.1.16

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
1.1.16 误发了一个 beta 版本，但和 1.115 相比，没有改动，对你造成的困扰深感抱歉。
