### ISSUE TITLE
x6-react-shape输入框和按钮等触发selecting

### ISSUE THREAD

**Issue by lloydzhou** [antvis/X6#2549]
### Describe the bug

x6-react-shape输入框和按钮等错误的触发selecting

### Your Example Website or App

https://codesandbox.io/s/x6-react-shape-click-bug-report-176glw

### Steps to Reproduce the Bug or Issue

1. 点击inputnumber输入框，准备输入
2. 触发选择框
3. 点击inputnumber增加减少按钮
4. 触发选择框

### Expected behavior

1. 对于输入框，点击输入的时候不触发选择框
2. 对于按钮（或者一些span/i实现的类似按钮的组件）点击的时候不触发选择框

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome]
- Version: [e.g. 91.1]

### Additional context

感觉针对自定义组件内部的，输入框以及能点击标签需要屏蔽`onMouseUp`以及`onMouseDown`两个事件，才能表现正常
https://github.com/lloydzhou/antv-x6-html2/blob/master/src/html2.ts#L61

这个demo也是使用了相同的InputNumber组件
https://codesandbox.io/s/antv-x6-react-demo-jjvcv0

**Comment by NewByVector** [comment]
确实，有很多地方都需要用到，可以抽取出一个公共的 util 方法来处理这种场景。
