### ISSUE TITLE
想问一下按需引用怎么配置？

### ISSUE THREAD

**Issue by kaiziwen** [antvis/X6#2553]
### 问题描述

想问一下按需引用怎么配置？

### 重现链接

无

### 重现步骤

无

### 预期行为

Graph， Addon， Shape只想引入这三个模块

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by lloydzhou** [comment]
@kaiziwen 

这里有一个可能和你说的“按需加载小地图”类似的处理逻辑。
https://github.com/lloydzhou/antv-x6-vue/blob/master/src/widgets/MiniMap.tsx

1. 这个vue的库将小地图当成一个vue组件进行封装。
2. 如果在Graph内部挂载这个MiniMap组件，就会动态的去更新x6 graph.options中关于小地图的配置。
3. 同时调用graph.hook.createMiniMap方法生成小地图组件
4. 当然卸载组件的时候，也会调用graph.minimap.widget.dispose方法销毁小地图

当然，还有一个react版本的封装，代码逻辑是一样的
https://github.com/lloydzhou/antv-x6-react/blob/master/src/lib/widgets/MiniMap.tsx

**Comment by NewByVector** [comment]
2.0 版本会以核心功能、扩展工能的设计来组织，到时候只要从不同包中导入新需要的功能。大概 10 月初发布。

**Comment by NewByVector** [comment]
2.x 中已经通过插件机制将配套功能分离，可以做到按需引入。
