### ISSUE TITLE
dnd拖拽的时候,如何触发graph的监听事件

### ISSUE THREAD

**Issue by zxtClick** [antvis/X6#2555]
### 问题描述

如题

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
拖拽期间是不会触发的，当元素被放置到目标画布时，会触发 `node:added` 事件。

**Comment by wangyong991** [comment]
拖拽中想监听鼠标移入到指定node节点上，能捕获到该节点信息。有什么方式吗

**Comment by zxtClick** [comment]
查找事件
https://x6.antv.vision/zh/docs/tutorial/intermediate/events/#gatsby-focus-wrapper


GTO鬼冢
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/X6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月1日(星期二) 中午11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/X6] dnd拖拽的时候,如何触发graph的监听事件 (Issue #2555)





 
拖拽中想监听鼠标移入到指定node节点上，能捕获到该节点信息。有什么方式吗

**Comment by huangwentai** [comment]
同问，我有个需求是拖动dnd的内容，触碰到节点时，显示可丢放的区域，丢进去之后把节点克隆过去
