### ISSUE TITLE
1.33.0版本渲染vue节点报错

### ISSUE THREAD

**Issue by chengup-git** [antvis/X6#2557]
### 问题描述

![1](https://user-images.githubusercontent.com/57739679/186113271-856c7ec6-1d75-448c-8db6-687012986520.png)
![2](https://user-images.githubusercontent.com/57739679/186113428-3e2a9f6b-74b2-4690-a2ca-4fdecd986cf9.png)
![3](https://user-images.githubusercontent.com/57739679/186113439-a1ddebe7-5a98-4e1a-a526-0f3a5ac13438.png)

### 重现链接

暂无

### 重现步骤

进入引用该画布页面即报错

### 预期行为

可以正常渲染vue节点

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.33.0 ]

**Comment by lloydzhou** [comment]
请检查一下，当前项目的node_modules文件夹下面以及@antv/x6-vue-shape这个包下面的node_modules文件夹下面是不是都有一份x6的代码？

如果存在两份代码，那么就会导致项目引用的x6并不是注册了`vue-shape`这个内置节点的x6。

**Comment by chengup-git** [comment]
> 请检查一下，当前项目的node_modules文件夹下面以及@antv/x6-vue-shape这个包下面的node_modules文件夹下面是不是都有一份x6的代码？
> 
> 如果存在两份代码，那么就会导致项目引用的x6并不是注册了`vue-shape`这个内置节点的x6。

确实是这个原因导致的，删除那个node_modules文件后就可以了，但是为什么@antv/x6-vue-shape这个包下会有一份x6的代码呢？

**Comment by chengup-git** [comment]
> 请检查一下，当前项目的node_modules文件夹下面以及@antv/x6-vue-shape这个包下面的node_modules文件夹下面是不是都有一份x6的代码？
> 
> 如果存在两份代码，那么就会导致项目引用的x6并不是注册了`vue-shape`这个内置节点的x6。

虽然现在没报错，但是vue节点没有渲染

**Comment by lloydzhou** [comment]
@chengup-git 

`@antv/x6-vue-shape`以及`@antv/x6-react-shape`等库的`package.json`是使用`peerDependencies`来处理对`@antv/x6`的依赖关系。通常不会在`@antv/x6-vue-shape`内部强制安装`@antv/x6`

然而不同的npm版本对`peerDependencies`的处理逻辑有区别，旧版的npm会强制安装，新版的npm不安装，仅仅输出一个提示信息...

**Comment by chengup-git** [comment]
> @chengup-git
> 
> `@antv/x6-vue-shape`以及`@antv/x6-react-shape`等库的`package.json`是使用`peerDependencies`来处理对`@antv/x6`的依赖关系。通常不会在`@antv/x6-vue-shape`内部强制安装`@antv/x6`
> 
> 然而不同的npm版本对`peerDependencies`的处理逻辑有区别，旧版的npm会强制安装，新版的npm不安装，仅仅输出一个提示信息...

我npm的版本8.11.0

**Comment by lloydzhou** [comment]
> > 请检查一下，当前项目的node_modules文件夹下面以及@antv/x6-vue-shape这个包下面的node_modules文件夹下面是不是都有一份x6的代码？
> > 如果存在两份代码，那么就会导致项目引用的x6并不是注册了`vue-shape`这个内置节点的x6。
> 
> 虽然现在没报错，但是vue节点没有渲染，会提示 ![4](https://user-images.githubusercontent.com/57739679/186129049-1d35cdfd-cf2d-46b7-850b-6546dd35c476.png)

这个问题你查看一下这个issue，文档里面也有提的。
https://github.com/antvis/X6/issues/507

**Comment by chengup-git** [comment]
> > > 请检查一下，当前项目的node_modules文件夹下面以及@antv/x6-vue-shape这个包下面的node_modules文件夹下面是不是都有一份x6的代码？
> > > 如果存在两份代码，那么就会导致项目引用的x6并不是注册了`vue-shape`这个内置节点的x6。
> > 
> > 
> > 虽然现在没报错，但是vue节点没有渲染，会提示 ![4](https://user-images.githubusercontent.com/57739679/186129049-1d35cdfd-cf2d-46b7-850b-6546dd35c476.png)
> 
> 这个问题你查看一下这个issue，文档里面也有提的。 #507
根据 #507 评论处理，已解决
