### ISSUE TITLE
centerContent 的效果不是很理想

### ISSUE THREAD

**Issue by bigbigbo** [antvis/X6#2558]
### 问题描述

想通过缩放和平移居中显示画布内容，调用 `centerContent ` api 达不到期望的效果

### 重现链接

https://codesandbox.io/s/wild-currying-3dpio1?file=/src/App.js

### 重现步骤

1. 通过 flex: 1 和 height: 100vh 设置画布大小
2. 设置 graph 的 autoResize 为 true
3. 从截图1可以看出demo中画布的大小是正确的，但实际居中效果不理想，截图2是在实际项目中的效果，更不理想
![image](https://user-images.githubusercontent.com/19587016/186132553-77460cce-44c5-40ec-8e8a-68e44e56ed5f.png)
![image](https://user-images.githubusercontent.com/19587016/186133179-13872d26-45ec-4a8d-b519-4da95317d584.png)

### 预期行为

期望能最大限度的居中画布内容，如demo中想达到如下效果：
![image](https://user-images.githubusercontent.com/19587016/186133691-bee22ebf-6e95-4f63-92c6-f15e9b756c7a.png)

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.33.1]

**Comment by NewByVector** [comment]
这个是 autoResize 的问题，我们会在 2.0 版本中修改该问题。

**Comment by NewByVector** [comment]
[autoResize](http://x6.antv.antgroup.com/tutorial/basic/graph) 问题已经在 2.x 版本中修复。
