### ISSUE TITLE
节点工具文本编辑的bug

### ISSUE THREAD

**Issue by xiaozengtest01** [antvis/X6#2560]
### Describe the bug

第一次输入较长的文本信息，取消编辑状态，然后再次进入编辑状态，从中间删除某些字符，出现字符重影。

![](https://s3.bmp.ovh/imgs/2022/08/24/d07b4b6e1f5e1d36.gif)

### Your Example Website or App

https://x6.antv.vision/zh/examples/node/tool#editable

### Steps to Reproduce the Bug or Issue

编辑文本

### Expected behavior

没有旧文本的重影

### Platform

- OS: [ Windows, ]
- Browser: [Chrome, ]
- Version: [1.33.0]

**Comment by NewByVector** [comment]
这里确实有一个问题，我们会尽快修复。
