### ISSUE TITLE
两个节点重叠的时候，连线发生变化

### ISSUE THREAD

**Issue by chengup-git** [antvis/X6#2561]
### 问题描述

连接线的起始点与终点在同一节点上，并与其他节点重叠，导致连接线发生变化

### 重现链接

暂无

### 重现步骤

无

### 预期行为

连接线不发生变化

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- X6 版本: [1.33.0]

### 屏幕截图或视频（可选）

![5](https://user-images.githubusercontent.com/57739679/186303606-49d5f45a-e73b-4243-a2bb-9cf8b63f4f01.png)
![6](https://user-images.githubusercontent.com/57739679/186303613-3068c63e-0b12-4010-8f75-4e08018c67c6.png)

### 补充说明（可选）

使用的router是manhattan

**Comment by NewByVector** [comment]
有可以复现的 demo 吗？

**Comment by chengup-git** [comment]
![Snipaste_2022-09-01_08-03-08](https://user-images.githubusercontent.com/57739679/187805508-28a0b45d-6b09-4f2b-8c6e-b9b2fd34c708.png)

![Snipaste_2022-09-01_08-03-19](https://user-images.githubusercontent.com/57739679/187805548-b329fd80-5652-4c17-980d-5bb4fa831c5b.png)
在图标实例的demo中拖拽出两个节点就可以复现了

**Comment by chengup-git** [comment]
好像发现怎么回事了，节点重叠之后，智能正交路由变成了正交路由

**Comment by chengup-git** [comment]
> 有可以复现的 demo 吗？

好像发现怎么回事了，节点重叠之后，智能正交路由变成了正交路由，有没有方法让他重叠的时候还是只能正交路由

**Comment by NewByVector** [comment]
重叠后已经无法避开障碍物了，不过你可以使用 [excludeNodes](http://x6.antv.antgroup.com/api/registry/router#manhattan) 来排除一些影响的节点。
