### ISSUE TITLE
node x6-demo.js 怎么引入x6.js

### ISSUE THREAD

**Issue by wuxiaochong111** [antvis/X6#2567]
### 问题描述

const test = require("./x6.js");
console.log("222"+test)

![image](https://user-images.githubusercontent.com/107900516/186354087-573cbb23-488c-486f-b91b-063e105c5ca7.png)
![image](https://user-images.githubusercontent.com/107900516/186355999-f2d46c4c-f137-45c5-8c60-25e07c696d19.png)
![image](https://user-images.githubusercontent.com/107900516/186355824-2cb3a56f-d683-4dd0-a5a6-6fc3f885e57a.png)

### 重现链接

node x6-demo.js

### 重现步骤

node x6-demo.js

### 预期行为

能正常打印test对象

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
x6 不能使用 node 运行，你是要在 ssr 中使用？
