### ISSUE TITLE
Stencil面板如果在画布中，在面板上drop节点也会添加到画布上

### ISSUE THREAD

**Issue by chen-i** [antvis/X6#2572]
### 问题描述

Stencil面板如果在画布中，在面板上drop节点也会添加到画布。
有什么方法可以确定drop节点是落在面板上的吗？
这样可以通过validateNode来验证节点是否可以放置到目标画布中。

### 重现链接

https://codesandbox.io/s/romantic-knuth-7jy908?file=/src/app.css

### 重现步骤

如描述

### 预期行为

可以判断drop节点是否落在stencil面板上

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
-

**Comment by lloydzhou** [comment]
应该和这个问题是一样的 https://github.com/antvis/X6/issues/2562
