### ISSUE TITLE
clipboard 开启 useLocalStorage 后 getCellsInClipboard 和 isClipboardEmpty 返回结果不符合预期

### ISSUE THREAD

**Issue by whinc** [antvis/X6#2573]
### Describe the bug

使用 clipboard 时，如果未开启`useLocalStorage`，则仅限同一个 graph 中进行复制和粘贴操作。开启`useLocalStorage`后，多个 graph 实例可以共享复制的内容，例如从 graphA 中 copy 的内容，可以调用 graphB 的 paste 粘贴，但是调用 graphB 的 `getCellsInClipboard`和`isClipboardEmpty`却返回空或者返回旧数据

### Your Example Website or App

https://codesandbox.io/s/vigilant-borg-q3d7yc?file=/src/app.tsx:2064-2105

### Steps to Reproduce the Bug or Issue

1. 选中上图中的 "hello" 节点，并点击“copy selected cells”
2. 点击下图中的"show clipboard"，提示`[]`（不符合预期，期望 `[{"position":{"x":62,"y":62},"size":{"width":100,"height":40},"attrs":{"text":{"text":"Hello"}},"visible":true,"shape":"rect","id":"c237b8ef-dbcc-47eb-8636-3a21c1103d19","zIndex":5}]`）
3. 点击下图中的"paste"，下图中成功粘贴了一个"hello“节点（符合预期）
4. 再次选中上图中的 "world" 节点，并点击“copy selected cells”
5. 再次点击下图中的"show clipboard"，提示`[{"position":{"x":62,"y":62},"size":{"width":100,"height":40},"attrs":{"text":{"text":"Hello"}},"visible":true,"shape":"rect","id":"c237b8ef-dbcc-47eb-8636-3a21c1103d19","zIndex":5}]`（不符合预期，期望`[{"position":{"x":210,"y":190},"size":{"width":60,"height":60},"attrs":{"text":{"text":"World"}},"visible":true,"shape":"circle","id":"52ae8d5d-7456-45b2-bd05-821f6db70d13","zIndex":5}]`）

### Expected behavior

见上面重现步骤的备注

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

查看 clipboard 源码 [paste](https://github.com/antvis/X6/blob/59919533ce468bf44597a5089933c957277df56e/packages/x6/src/addon/clipboard/index.ts#L43) 内部在开启 useLocalStorage 后会调用 [deserialize](https://github.com/antvis/X6/blob/59919533ce468bf44597a5089933c957277df56e/packages/x6/src/addon/clipboard/index.ts#L89) 先将 storage 数据反序列化到内部的 cells 中，而 [isEmpty](https://github.com/antvis/X6/blob/59919533ce468bf44597a5089933c957277df56e/packages/x6/src/addon/clipboard/index.ts#L98) 则没有这个反序列化操作，导致未能读取到最新的 storage 数据，从而导致返回的结果在开启 useLocalStorage 的情况下不正确

**Comment by NewByVector** [comment]
按照你的操作步骤，我的结果是：
![image](https://user-images.githubusercontent.com/20186737/187073547-19d6c489-b4c2-4e31-9e2e-12df15d3000f.png)

**Comment by whinc** [comment]
> 按照你的操作步骤，我的结果是：
> 
> ![image](https://user-images.githubusercontent.com/20186737/187073547-19d6c489-b4c2-4e31-9e2e-12df15d3000f.png)
> 
> 

上面图中复制，下面图中展示剪切板（注意是查看不是粘贴，粘贴是没问题的）内容是否与上图复制的内容一致？

**Comment by NewByVector** [comment]
@whinc 
1. 点击 graph1 的 hellow 节点，点击 copy selected cells
2. 然后点击 graph2 下面的工具 show clipborad，展示内容见上图

**Comment by whinc** [comment]
> @whinc
> 
> 1. 点击 graph1 的 hellow 节点，点击 copy selected cells
> 2. 然后点击 graph2 下面的工具 show clipborad，展示内容见上图

这就很奇怪了，这是我给的 demo 的示例截图
1.  graph1 中选中 rect 形状的 hello 节点，点击 copy selected cells，显示复制成功
2. graph2 中点击 showClipbord，显示 circle 形状（期望是 rect 形状）
![image](https://user-images.githubusercontent.com/5096493/187112669-9b9dd7e4-82f2-4fe1-81b7-bc47474b22a1.png)
![image](https://user-images.githubusercontent.com/5096493/187113002-310f0f0b-a649-46f8-b6a8-c78466095661.png)

![image](https://user-images.githubusercontent.com/5096493/187112702-5dc6afe8-2c7a-486e-9744-cf3fbe5d363a.png)

**Comment by NewByVector** [comment]
是我这边历史的 localstorage 导致的，如果多个画布确实有问题，https://github.com/antvis/X6/pull/2574#pullrequestreview-1088418872 有点小的建议。
