### ISSUE TITLE
节点工具是否有鼠标事件监听，希望鼠标悬浮到节点工具上时，改变节点工具的背景颜色

### ISSUE THREAD

**Issue by 695648896** [antvis/X6#2577]
### 问题描述

1.节点工具是否有onMove相关的鼠标事件监听，在源码中只看到了onClick
2.如何动态设置节点工具的attrs属性，用于改变背景颜色，

### 重现链接

https://codesandbox.io/s/proud-sea-uys8t4?file=/src/app.tsx:861-868

### 重现步骤

1.悬浮在节点工具上，无法获取hover或者mousemove事件

### 预期行为

鼠标悬浮到节点工具上时，可以改变节点工具的背景颜色 

### 平台

Windows

**Comment by 695648896** [comment]
@lloydzhou  (｡･∀･)ﾉﾞ嗨，需要您的帮助。 现在的做法是去算节点工具的位置，通过cell:mousemove监听节点鼠标事件进入节点工具范围了 了就修改相关节点工具的markup ，是否有更好的办法来做这个事情，还是说只能通过自定义节点工具来增加mousemove方法

**Comment by 695648896** [comment]
@NewByVector (｡･∀･)ﾉﾞ嗨，您能帮助我吗

**Comment by lloydzhou** [comment]
@695648896 

https://codesandbox.io/s/proud-sea-uys8t4?file=/src/app.tsx

1. MyButton继承Button，添加onMouseOver和onMouseOut事件
2. 使用MyButton.config定义markup以及events，其中events包含mouseover和mouseout分别指向前面定义的回调事件
3. 然后你应该就可以在hover的时候去处理更改背景颜色之类的逻辑....

**Comment by 695648896** [comment]
> 2\. mouseover



> @695648896
> 
> https://codesandbox.io/s/proud-sea-uys8t4?file=/src/app.tsx
> 
> 1. MyButton继承Button，添加onMouseOver和onMouseOut事件
> 2. 使用MyButton.config定义markup以及events，其中events包含mouseover和mouseout分别指向前面定义的回调事件
> 3. 然后你应该就可以在hover的时候去处理更改背景颜色之类的逻辑....

@lloydzhou 
谢谢您的回复，但我按照下面配置后，鼠标移到按钮上并没有触发相应事件，是否我的配置有不对的地方，地址详见https://codesandbox.io/s/proud-sea-uys8t4?file=/src/app.tsx
![image](https://user-images.githubusercontent.com/30861990/187336706-431d39c1-9b11-41d4-810d-6ac4840a7128.png)

**Comment by lloydzhou** [comment]
@lloydzhou 
按照我说的步骤，用继承(extends)加上config
不要用define

**Comment by 695648896** [comment]
> @lloydzhou 按照我说的步骤，用继承(extends)加上config 不要用define

![image](https://user-images.githubusercontent.com/30861990/187360953-72c716a1-ef4c-4cf3-b618-7cc386259466.png)
按照您给的步骤，成功运行了，实现了hover的需求，多谢！！！

**Comment by 695648896** [comment]
@lloydzhou (｡･∀･)ﾉﾞ嗨打扰了，自定义按钮后又爆出了新的问题 Uncaught TypeError: Cannot read property 'ToolItem' of undefined  我参照了 https://github.com/vitejs/vite/issues/3413 
![image](https://user-images.githubusercontent.com/30861990/187588636-cb383a5d-8c70-4ed5-afe7-cfa196e42b74.png)
但是又引出了以下错误
![image](https://user-images.githubusercontent.com/30861990/187588687-d56a95df-57e9-49a3-85e7-2d62318a6a56.png)
以下是我的vite相关配置
![image](https://user-images.githubusercontent.com/30861990/187588862-bba13016-4246-4f4b-9df7-4df696488051.png)

**Comment by 695648896** [comment]
ok，我能正确运行了，配置如下，将x6和x6-vue-shape 移除预构建，然后将他们的commonjs依赖加入预构建
![image](https://user-images.githubusercontent.com/30861990/187613535-76c10024-e789-40ae-a422-5c9a4bd7a495.png)

**Comment by 695648896** [comment]
@lloydzhou 老哥，我在自定义按钮时候碰到了类型的问题，我用自己定义的this.options.onMouseOver方法就会报类型错误，但是换成this.options.onClick就正常
![image](https://user-images.githubusercontent.com/30861990/187869565-e2d9ac5f-fdfa-4d1d-b001-4de37ac91d37.png)

**Comment by 695648896** [comment]
然后有还有钉钉群可以进嘛，省的一直打扰您~

**Comment by 695648896** [comment]
![image](https://user-images.githubusercontent.com/30861990/187871008-d21d1cbd-4d35-413c-ae29-4559030df299.png)
老哥，这是我完整的MyButton
@lloydzhou

**Comment by xiangch** [comment]
> [695648896](/695648896)

@695648896 这个问题解决了吗，我也遇到同样的问题

**Comment by 695648896** [comment]
> > [695648896](/695648896)
> 
> @695648896 这个问题解决了吗，我也遇到同样的问题
@xiangch 
![image](https://user-images.githubusercontent.com/30861990/191247613-9ee47b47-fd94-4339-adbc-5ae52171d50d.png)
目前是通过any来欺骗ts编译器解决了 有什么更好的办法 记得回来教教我~

**Comment by xiangch** [comment]
> > > [695648896](/695648896)
> > 
> > 
> > @695648896 这个问题解决了吗，我也遇到同样的问题
> > @xiangch
> > ![image](https://user-images.githubusercontent.com/30861990/191247613-9ee47b47-fd94-4339-adbc-5ae52171d50d.png)
> > 目前是通过any来欺骗ts编译器解决了 有什么更好的办法 记得回来教教我~

@695648896  主要是因为 cellview 在 ToolsView 里并且是 protected 因此到了 Button 后就变成了 private 这时就不能被 Button 的子类引用了。我的解决办法就是直接继承 ToolsView，即把 Button 的代码抄过来，改成MyButton

**Comment by AMhehe** [comment]
你好，请问你是怎么在onMouseOver里改的背景色啊，我用了this.options.markup.attrs.fill = '#fff' 没好使，看到麻烦回复下，谢谢拉

**Comment by 695648896** [comment]
> 你好，请问你是怎么在onMouseOver里改的背景色啊，我用了this.options.markup.attrs.fill = '#fff' 没好使，看到麻烦回复下，谢谢拉

![image](https://github.com/antvis/X6/assets/30861990/408b440b-9320-46a3-94fe-99153c128454)
我是直接加了class样式

**Comment by AMhehe** [comment]
你好，看代码你的onMouseOver是写在tools里的，想问下你是怎么做到写到tools里也能让onMouseOver好使的，而且看你代码，你的节点工具也不是自定义的节点工具，我在上面的例子中https://codesandbox.io/s/proud-sea-uys8t4?file=/src/app.tsx，在tools里直接用onMouseOver没好使，看到麻烦回复下，谢谢拉
![image](https://github.com/antvis/X6/assets/30047724/5e8267f3-1f4c-449f-b3ad-a8dde930df7d)

**Comment by 695648896** [comment]
> https://codesandbox.io/s/proud-sea-uys8t4?file=/src/app.tsx，在tools里直接用onMouseOver没好使，看到麻烦回复下，谢谢拉

@AMhehe 我是自定义的 我自定义了MyButton按钮

**Comment by 695648896** [comment]
/* eslint-disable @typescript-eslint/no-namespace */
import { Button } from '@antv/x6/es/registry/tool/button.js'
import { FunctionExt, Cell, CellView } from '@antv/x6'
export class MyButton extends Button {
  onMouseOver(e: any) {
    if (this.guard(e)) {
      return
    }
    e.stopPropagation()
    e.preventDefault()
    const options: any = this.options
    const onMouseOver = options.onMouseOver
    if (typeof onMouseOver === 'function') {
      FunctionExt.call(onMouseOver, this.cellView, {
        e,
        view: this.cellView,
        cell: this.cellView.cell,
        btn: this
      })
    }
  }
  onMouseOut(e: any) {
    if (this.guard(e)) {
      return
    }
    e.stopPropagation()
    e.preventDefault()
    const options: any = this.options
    const onMouseOut = options.onMouseOut
    if (typeof onMouseOut === 'function') {
      FunctionExt.call(onMouseOut, this.cellView, {
        e,
        view: this.cellView,
        cell: this.cellView.cell,
        btn: this
      })
    }
  }
}

export namespace MyButton {
  MyButton.config<MyButton.Options>({
    events: {
      mouseover: 'onMouseOver',
      mouseout: 'onMouseOut'
    }
  })
}
export namespace MyButton {
  export interface Options extends Button.Options {
    onMouseOver?: (
      this: CellView,
      args: {
        e: any
        cell: Cell
        view: CellView
        btn: MyButton
      }
    ) => any
    onMouseOut?: (
      this: CellView,
      args: {
        e: any
        cell: Cell
        view: CellView
        btn: MyButton
      }
    ) => any
  }
}

**Comment by 695648896** [comment]
然后节点工具注册时候 是注册的我自定义的节点工具按钮
![image](https://github.com/antvis/X6/assets/30861990/fe5b9371-cb41-4872-8522-91c9680210d0)

**Comment by AMhehe** [comment]
不好意思啊，再问下，你用的是X6是哪个版本啊，我按照你的写法来，结果报Class constructor Button cannot be invoked without 'new' ，我现在用的X6是1.34.5，看到麻烦回复下，谢谢拉

**Comment by 695648896** [comment]
> 不好意思啊，再问下，你用的是X6是哪个版本啊，我按照你的写法来，结果报Class constructor Button cannot be invoked without 'new' ，我现在用的X6是1.34.5，看到麻烦回复下，谢谢拉

![image](https://github.com/antvis/X6/assets/30861990/5e20635c-2f19-44bb-85ff-e63a5da5d8d1)
