### ISSUE TITLE
x6-vue-shape 自定义组件内部使用全局注册的组件和动态组件无法进行正常渲染

### ISSUE THREAD

**Issue by shy123123** [antvis/X6#2579]
### 问题描述

<img width="958" alt="image" src="https://user-images.githubusercontent.com/21299254/186622610-09d2d441-5a88-4b05-93a4-192fce21b1e9.png">
在这个自定义的vue节点内部使用动态组件无法正常渲染
<img width="677" alt="image" src="https://user-images.githubusercontent.com/21299254/186622857-502b383d-fc62-484e-b1c7-d6ddf2aa463b.png">
![image](https://user-images.githubusercontent.com/21299254/186623003-c33785de-d02f-4232-aaf5-fe0d8e88cb53.png)
但是同时在内部使用element-plus所注册的全局组件接可以正常渲染，不知如何解决

### 重现链接

..

### 重现步骤

全局注册的组件如果不通过import重新引入 无法渲染

### 预期行为

希望解决掉动态组件渲染的问题

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.32.3 ]

**Comment by lloydzhou** [comment]
https://github.com/antvis/X6/blob/master/packages/x6-vue-shape/src/view.ts#L58

x6-vue-shape默认会将注册的组件createApp之后挂载到每一个节点的foreignObject标签内部，已经算是一个全新的Vue的App，所以全局注册的组件是无法渲染的（跨App了）

如果你现在使用的是vue3，你可以尝试使用`useTeleport`应该可以使用全局注册的组件。

https://x6.antv.vision/en/docs/tutorial/advanced/react/#%E6%B8%B2%E6%9F%93-vue-%E8%8A%82%E7%82%B9
