### ISSUE TITLE
@antv/x6-react-components不支持react18版本

### ISSUE THREAD

**Issue by Mrheqiang** [antvis/X6#2583]
### 功能描述

**package.json**
"react": "^18.2.0",
"react-dom": "^18.2.0",

**index.tsx**
`<div className={styles.middle}>`
   `<ContextMenu menu={menu}>`
        `<div id='container' style={{ height: '100%' }}></div>`
   `</ContextMenu>`
`</div>`

**报错：**
没有与此调用匹配的重载。
第 1 个重载(共 2 个)，“(props: Props | Readonly): ContextMenu”，出现以下错误。
不能将类型“{ children: Element; menu: Element; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes & Readonly”。
类型“IntrinsicAttributes & IntrinsicClassAttributes & Readonly”上不存在属性“children”。
第 2 个重载(共 2 个)，“(props: Props, context: any): ContextMenu”，出现以下错误。
不能将类型“{ children: Element; menu: Element; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes & Readonly”。
类型“IntrinsicAttributes & IntrinsicClassAttributes & Readonly”上不存在属性“children”。ts(2769)

**目前修改方案**
降低react版本到18以下

### 期望解决方案

尽快推出支持react18的2.0版本，有时间点吗？

**Comment by NewByVector** [comment]
2.0 版本会升级到 react 18，预计时间点在 10 月初。

**Comment by zhangbaojia** [comment]
> 2.0 版本会升级到 react 18，预计时间点在 10 月初。

国庆已经结束了， 升级兼容react18.2.0+ 是否已经提上行程了。

**Comment by zhangbaojia** [comment]
@NewByVector 2.0版本调整的内容挺多的， 请问有明确大致的发布时间吗？

**Comment by NewByVector** [comment]
已经支持 react18 了。
