### ISSUE TITLE
vue2/自定义vue组件节点，调用inject错误：Injection "getGraph" not found

### ISSUE THREAD

**Issue by lt717** [antvis/X6#2594]
### 问题描述

主要报错：
![image](https://user-images.githubusercontent.com/84703888/187388263-5339a750-bc66-44c9-8179-7d1d76fb2c10.png)
Injection "getGraph" not found
Injection "getNode" not found

### 重现链接

无

### 重现步骤

1、使用自定义组件graph-tool做节点，确实写了inject声明
![image](https://user-images.githubusercontent.com/84703888/187387410-6d7681c2-8c13-4a5c-a824-2346347c50ef.png)

2、主vue文件中调用
![image](https://user-images.githubusercontent.com/84703888/187387724-5e36a15e-c6f1-495f-9bd6-8d01b513469c.png)

![image](https://user-images.githubusercontent.com/84703888/187387578-d08f0f9c-1917-4fcd-8def-18680ddf3800.png)

需要引入的依赖包：@antv/x6-vue-shape、@vue/composition-api均安装，并且查看x6-vue-shape中的js文件能找到provide写有getGraph、getNode方法
vue.config.js配置中也添加了  runtimeCompiler: true,
![image](https://user-images.githubusercontent.com/84703888/187388785-be703a79-f93e-4e42-b7fb-8c5cc72ba337.png)

### 预期行为

理解而为什么出现这个问题
修改为不报错，并且能正确调用到getNode()方法

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- X6 版本: 1.32.11

**Comment by NewByVector** [comment]
看你截图没有看出有什么问题，可以对照 https://codesandbox.io/s/vue-shape-8ciig 看下有什么区别。另外，有擅长 vue 的小伙伴可以一起帮忙看下。

**Comment by lt717** [comment]
> 看你截图没有看出有什么问题，可以对照 https://codesandbox.io/s/vue-shape-8ciig 看下有什么区别。另外，有擅长 vue 的小伙伴可以一起帮忙看下。

已经参照比对过，但是我没看出什么问题……所以现在比较迷茫，我再看看

**Comment by lt717** [comment]
**已解决。**
试验后发现是本身代码逻辑问题：主vue中有一个节点列表，**直接**调用了组件graph-tool，而主vue自然是没有provide编写的，也自然没有getNode等方法；**并非X6层的问题**。

打扰各位了。

**Comment by noenif** [comment]
我发现版本地狱1.1.4的也有这个问题,而且他的registerVueComponent
![image](https://user-images.githubusercontent.com/25174520/203682586-421c51d1-0f11-4f12-ba11-811f8acd005a.png)
看版本直接上npm 看,github的release实在一言难尽

**Comment by ricarduuu** [comment]
> 看你截图没有看出有什么问题，可以对照 https://codesandbox.io/s/vue-shape-8ciig 看下有什么区别。另外，有擅长 vue 的小伙伴可以一起帮忙看下。

您好 问一下 现在 x6-vue-shape v2版本不再提供 getGraph的注入了么为什么，还有就是有一个场景，

我在自定义的vue节点中获取到node, 想通过自定义事件来区分 （是删除/增加/编辑）这就不能简单的通过 dbclick来区分，

在v1中我可以通过      graph.trigger('node-delete') 来触发，在最外层画布graph.value?.on('node-delete' 来监听，


目前在v2不知道怎么定义这种自定义事件了

**Comment by ricarduuu** [comment]
> 

https://github.com/antvis/X6/blob/master/packages/x6-vue-shape/src/view.ts#L42

**Comment by Alimjan2013** [comment]
楼上提的问题原来在最新版解决了，目前用的 vue shape 插件是 2.0.9

**Comment by 941477276** [comment]
> **已解决。** 试验后发现是本身代码逻辑问题：主vue中有一个节点列表，**直接**调用了组件graph-tool，而主vue自然是没有provide编写的，也自然没有getNode等方法；**并非X6层的问题**。
> 
> 打扰各位了。

楼主怎么解决的，我也遇到这个问题了，我用的也是vue2.7.x，下面是我的代码，麻烦楼主帮忙分析下：
![image](https://github.com/antvis/X6/assets/20528541/4eb90415-72f2-4d1a-ae76-6c04960c866b)
![image](https://github.com/antvis/X6/assets/20528541/63c76088-ac4c-4e57-8d0d-ac18a9dd73fa)

**Comment by lt717** [comment]
> > **已解决。** 试验后发现是本身代码逻辑问题：主vue中有一个节点列表，**直接**调用了组件graph-tool，而主vue自然是没有provide编写的，也自然没有getNode等方法；**并非X6层的问题**。
> > 打扰各位了。
> 
> 楼主怎么解决的，我也遇到这个问题了，我用的也是vue2.7.x，下面是我的代码，麻烦楼主帮忙分析下： ![image](https://user-images.githubusercontent.com/20528541/267028500-4eb90415-72f2-4d1a-ae76-6c04960c866b.png) ![image](https://user-images.githubusercontent.com/20528541/267028589-63c76088-ac4c-4e57-8d0d-ac18a9dd73fa.png)

我没有看出具体的问题，你可以先查看一下自己是否正确注册了组件。

**Comment by lt717** [comment]
> > **已解决。** 试验后发现是本身代码逻辑问题：主vue中有一个节点列表，**直接**调用了组件graph-tool，而主vue自然是没有provide编写的，也自然没有getNode等方法；**并非X6层的问题**。
> > 打扰各位了。
> 
> 楼主怎么解决的，我也遇到这个问题了，我用的也是vue2.7.x，下面是我的代码，麻烦楼主帮忙分析下： ![image](https://user-images.githubusercontent.com/20528541/267028500-4eb90415-72f2-4d1a-ae76-6c04960c866b.png) ![image](https://user-images.githubusercontent.com/20528541/267028589-63c76088-ac4c-4e57-8d0d-ac18a9dd73fa.png)

我没有看出具体的问题，你可以先看下自己是否正确注册了组件，然后我说下我的代码以及问题，你可以看看是否符合你的逻辑情况。
我的main.vue主要内容是一个右侧节点（自定义节点node.vue）列表，左侧为x6图，用户可以从右侧将节点拖动至左侧的x6网格图中渲染出来。
这里存在逻辑就是，右侧node为component直接调用，但是左侧是被包在x6中的，而inject在node中声明了getNode，getGraph这两个方法，就说明调用node的父组件应该provide这两个方法，而x6中已经定义，所以为了直接调用不报错，我必须在我的main.vue里也加上provide这两个方法，随便定义一下return内容即可，毕竟不会使用到。

希望对你有所帮助。
