### ISSUE TITLE
vue3路由到画布页面后，画布样式混乱

### ISSUE THREAD

**Issue by zhangxuewei1263944101** [antvis/X6#2598]
### 问题描述

本地运行正常，打包部署到线上出现了这个问题

我在使用vue3+X6构建项目时，用vue router路由到 画布页面， 样式变得混乱起来
第一次进来是好的
![{$JF 2 S1$UGZ80}H}LORN](https://user-images.githubusercontent.com/41711703/187653401-bc9f767e-92d4-4ed0-89dc-d128ee5f99bb.jpg)

当我点击登陆，再点击首页时页面变成了这样
![O3SXB5)AOIRX)F$}I ZWF`W](https://user-images.githubusercontent.com/41711703/187653622-24aacc3d-c243-408b-8016-0a343bc2908c.jpg)

这是我代码的地址 https://gitee.com/zxwAdd_admin/flow-tools    
请求大佬指正

### 重现链接

www.flowcloud.work

### 重现步骤

1、进入页面
2、点击登陆
3、点击首页

### 预期行为

我得预期结果路由过后样式不发生改变，和第一次进入页面时一样

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by lloydzhou** [comment]
1. 这个应该不是x6的问题。
2. 原因是vue3开启keepalive之后，你又在自己的组件里面使用了createElement，导致重新路由的时候，在zxwcontainer内部生成了重复的stencil和graph-container导致flex布局把前面的两个div挤到前面了
3. 你可以尝试移除App.vue组件中的`keep-alive`组件，或者将route/index.ts中首页的路由meta.keepAlive设置成false
4. 不过还是建议你把`createElement`去掉使用其他方式去实现。

**Comment by zhangxuewei1263944101** [comment]
谢谢，是代码的逻辑问题，
我在创建之前先判断，页面有没有 stencil和graph-container这两个元素就，再决定是否创建就好了。

**Comment by zhangxuewei1263944101** [comment]
谢谢您回复我
我直接将这两个stencil和graph-container 元素 在页面自己写上就好了，不再使用document.createElement("div")
