### ISSUE TITLE
隐藏节点后，撤销操作后节点或边不能正常显示

### ISSUE THREAD

**Issue by mht1993** [antvis/X6#2599]
### Describe the bug

1. 批量操作隐藏多个节点（x6会自动隐藏node间的连线）
2. 撤销操作后，node可以显示，但是edge不会显示（不知道为啥codesandbox上连node也不能正常显示）

### Your Example Website or App

https://codesandbox.io/s/vue-shape-forked-0zlhke?file=/src/App.vue

### Steps to Reproduce the Bug or Issue

点击隐藏按钮，隐藏了node和边
然后节点撤销按钮
node 和edge没有显示（但是我工作中的工程node能显示，就是边不会显示）

### Expected behavior

期望edge和node都能显示

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
windows
chrome

### Additional context

猜测是因为这里，撤销的时候，先show 边，此时 边的source和tartget 可能没有显示，就不会触发边的视图刷新
if (cell.isEdge()) {
      if (
        !this.isEdgeTerminalVisible(cell, 'source') ||
        !this.isEdgeTerminalVisible(cell, 'target')
      ) {
        return
      }
    }

**Comment by NewByVector** [comment]
你好，这个确实是一个问题，我们会在 2.0 版本中修复这个缺陷，大概在 10 月初发布。

**Comment by NewByVector** [comment]
2.x 版本已经修复。
