### ISSUE TITLE
ER图坐标问题

### ISSUE THREAD

**Issue by pj001** [antvis/X6#2600]
### 问题描述

![image](https://user-images.githubusercontent.com/39849195/187670660-f5a1dd61-42f5-4196-bf59-6c6323c29416.png)

er图坐标可以自动渲染吗？不需要传入x,y

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

https://codesandbox.io/s/new

### 预期行为

![image](https://user-images.githubusercontent.com/39849195/187670771-5b0f53b2-cd9b-49ef-a740-5ee51fd56809.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
暂时没有针对 ER 图场景的布局。

**Comment by pj001** [comment]
有什么好的方式呢？目前只能想到随机生成。但是很凌乱



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月31日(星期三) 晚上8:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antvis/X6] ER图坐标问题 (Issue #2600)





 
暂时没有针对 ER 图场景的布局。

**Comment by NewByVector** [comment]
可以搜搜有没有现成的 er 图布局算法。

**Comment by NewByVector** [comment]
@antv/layout 中就有 ER 布局。
