### ISSUE TITLE
vue3 teleport 渲染问题

### ISSUE THREAD

**Issue by mht1993** [antvis/X6#2602]
### Describe the bug

关联问题[vue-shape teleport渲染问题](https://github.com/antvis/X6/issues/2505)

使用teleport 渲染一个NODE，画布开启`clipboard: {
        enabled: true,
        useLocalStorage: true
      }` 前提：同时存在多个画布，在画布1剪切node1，粘贴在画布2上，回到画布1进行撤销操作node1重现显示，然后直接删除画布2，卸载整个graph，此时画布1上的node1也跟着消失了

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1. 在画布1剪切node1，
2. 粘贴在画布2上
3. 回到画布1进行撤销操作node1重现显示
4. 删除画布2（卸载整个graph）
5. 此时画布1上的node1也跟着消失了

### Expected behavior

期望删除画布2 不会影响画布1

### Platform

Windows 
Chrome

### Additional context

不用teleport 就不会有这个问题

**Comment by lloydzhou** [comment]
复现步骤较多，能否提供一个codesandbox的复现的demo呢？

**Comment by mht1993** [comment]
不好意思，可能是我自己的问题，`<TeleportContainer />` 容器放的位置不同表现不一样
