### ISSUE TITLE
previousCell is null in edge:connected event

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#261]
### Expected Behavior
graph的edge:connected事件中获取previousCell是空的

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@NewByVector 可能存在不兼容的情况，在 beta 分支上修复这个问题

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/pull/341
