### ISSUE TITLE
希望EdgeTool、NodeTool 增加交互功能

### ISSUE THREAD

**Issue by xiangch** [antvis/X6#2613]
### 功能描述

最近在用X6来实现钉钉[宜搭](http://www.aliwork.com)DAG时发现缺少以下功能
1，动画效果
场景：edge 上增加一个 + 工具用于增加一个新的Node。这个 + 工具当鼠标进入 edge 时出现，鼠标离开时消失。此时出现和消失能增加渐变动画就会比较友好。出现：渐渐变大；消失：渐渐变小

2，鼠标进入、离开事件
场景1：同上。鼠标进入 + 时显示一个菜单，此菜单用于决定增加的 Node 的类型
场景2：在 Node 增加 i 工具，当鼠标进入 i 时显示 tips 介绍 node 描述

### 期望解决方案

Tool 作为 Cell 的子类与 Edge 和 Node 同级。拥有 mouseenter 、mouseleave 事件及动画能力。在实践中，Tool 的重要性一点不比Node 、 Cell 轻，它往往承担很多交互能力

**Comment by xiangch** [comment]
宜搭 DAG 路径 ： 我的应用 -> 点击进入某个应用 ->集成&自动化

**Comment by lloydzhou** [comment]
https://github.com/antvis/X6/issues/2577#issuecomment-1230432924

这里有通过继承的方式对tool增加onMouseOver和onMouseOut事件的方法

**Comment by xiangch** [comment]
> [#2577 (comment)](https://github.com/antvis/X6/issues/2577#issuecomment-1230432924)
> 
> 这里有通过继承的方式对tool增加onMouseOver和onMouseOut事件的方法

感谢回复。我试了一下，Button 是可以实现 onMouseOver 但是 boundary 是不行的。 我想实现一个功能就是当鼠标靠近 edge 时就在 edge 上增加一个 + 工具 而不用等鼠标进入 edge 时才出现 。因此我想到了 boundary 。当鼠标进入 boundary 在 edge 增加 + 工具

https://codesandbox.io/s/hungry-newton-pfzx5s?file=/src/app.tsx

**Comment by xiangch** [comment]
>

感谢回复，这的确是可以解决靠近功能
