### ISSUE TITLE
反序列化cell数据，画布上渲染的边全部指向位置cell的左上角

### ISSUE THREAD

**Issue by maergaiyun** [antvis/X6#2616]
### Describe the bug

反序列化之前
![image](https://user-images.githubusercontent.com/62786015/188115026-f8eb01cf-b2ff-4d61-b483-f64d7bd58341.png)

反序列化之后（fromJson）
![image](https://user-images.githubusercontent.com/62786015/188115091-53b1eae1-9177-4fbe-9d08-7da1e8a5fffb.png)

### Steps to Reproduce the Bug or Issue

1、画布上摆放几个节点，并用边连接
2、序列化（toJson）的数据再反序列化（fromJson）
3、画布上重新渲染

**Comment by maergaiyun** [comment]
@NewByVector

**Comment by maergaiyun** [comment]
发现反序列化之后，重新连接边时，只能选中节点的左上角

**Comment by maergaiyun** [comment]
将画布中反序列化之后的所有节点全选剪贴再粘贴，就正常了

**Comment by NewByVector** [comment]
@maergaiyun 能否写个可以复现的 demo 看下？

**Comment by zY-zhao** [comment]
@NewByVector 使用v-show切换画布时会出现这个问题

**Comment by NewByVector** [comment]
@maergaiyun @zY-zhao 这个是因为在画布隐藏情况下，浏览器 api `elem.getBBox()` 无法返回正确的元素包围盒，所以出现上面情况，在 1.x 版本中需要我们自己来保证在画布显示完成之后，再 fromJSON，这个在 2.0 版本中已经解决了这个问题。

**Comment by maergaiyun** [comment]
![image](https://user-images.githubusercontent.com/62786015/205229381-3810a908-1051-42e6-a52d-7e9373cb83be.png)
直接将原始的json数据反序列化到画布上，很容易复现

**Comment by maergaiyun** [comment]
全选画布上的节点数据，ctrl+x，ctrl+v能恢复

**Comment by maergaiyun** [comment]
已经升级2.0版本，未解决

**Comment by maergaiyun** [comment]
> @maergaiyun @zY-zhao 这个是因为在画布隐藏情况下，浏览器 api `elem.getBBox()` 无法返回正确的元素包围盒，所以出现上面情况，在 1.x 版本中需要我们自己来保证在画布显示完成之后，再 fromJSON，这个在 2.0 版本中已经解决了这个问题。

已经升级2.0版本，未解决

**Comment by NewByVector** [comment]
@maergaiyun 一定要保证画布容器渲染完成之后再 fromJSON

**Comment by maergaiyun** [comment]
> @maergaiyun 一定要保证画布容器渲染完成之后再 fromJSON

有没有一个状态判断画布是否渲染完成

**Comment by NewByVector** [comment]
这个要你自己来保证的

**Comment by maergaiyun** [comment]
> @maergaiyun 一定要保证画布容器渲染完成之后再 

> 这个要你自己来保证的

我是用的v-show切换的局部组件，从A组件引用json数据，切换回B组件（画布在B组件）,切换回B组件 fromJson就会出现这个问题
