### ISSUE TITLE
添加节点、边的可操作状态配置

### ISSUE THREAD

**Issue by lulei90** [antvis/X6#2617]
### 功能描述

在实际图编辑场景中为了方便用户快速创建流程，通常会提供一个初始模板，模板中包含一套固定的节点以及对应边的连线关系，模板中的节点和边是不可被编辑和删除的，后续新增的节点已经边是可编辑的。目前x6没有针对单个节点的能否被删除、移动、选中等相关配置，只能在业务代码中通过各种事件去实现

### 期望解决方案

在创建Cell时能提供对应能否被操作的相关配置 例如
```js
 createNode({
   canRemove: false,
   canSelected: true,
   canMove: true
 })
```

**Comment by NewByVector** [comment]
可以查看 [常见问题2](https://www.yuque.com/antv/x6/be9pfx)

**Comment by lulei90** [comment]
> 可以查看 [常见问题2](https://www.yuque.com/antv/x6/be9pfx)

目前项目中也是这样实现的，可以考虑下这种针对单个节点的操作配置能否在x6中直接内置支持
