### ISSUE TITLE
可以出一个完整的x6编辑器案例吗？

### ISSUE THREAD

**Issue by xiaqiuchu** [antvis/X6#2623]
## 原因
最近有一个新需求需要用到 图编辑器引擎，需要在线编辑并导入导出 json 数据，但是前端能力还很欠缺，自己实现有比较大的难度。

## 问题
看到 【场景案例->业务场景->流程图】https://antv-x6.gitee.io/zh/examples/showcase/practices#flowchart 这里有一个简单的编辑器案例，当然由于是案例并不能满足实际业务使用需求，但是看到别的如：bpmn-js 就提供了一个比较完整的编辑器界面拿来直接使用

## 期望
希望可以出一个完整基于x6编辑器的案例，可以拿来就用的那种。然后支持按钮导入导出或者说留下导出事件可以暴露给使用者，可以从数据库里面导入到页面，或者将页面的数据导入到数据库。

## 最后
感谢开发者开源这么棒的产品

**Comment by lloydzhou** [comment]
@xiaqiuchu 
你可以关注一下　https://github.com/antvis/xflow 
这个项目也是antvis团队的项目，是基于x6开发的react库，内置了开箱即用的三个解决方案

**Comment by xiaqiuchu** [comment]
> @xiaqiuchu 你可以关注一下　https://github.com/antvis/xflow 这个项目也是antvis团队的项目，是基于x6开发的react库，内置了开箱即用的三个解决方案

谢谢，有vue版的或者 直接js引入的那种吗？

**Comment by lloydzhou** [comment]
> > @xiaqiuchu 你可以关注一下　https://github.com/antvis/xflow 这个项目也是antvis团队的项目，是基于x6开发的react库，内置了开箱即用的三个解决方案
> 
> 谢谢，有vue版的或者 直接js引入的那种吗？

xflow没有vue版本，不过我可以给你推荐一个我自己写的，也在我自己项目中使用了挺长时间的一个库
https://github.com/lloydzhou/antv-x6-vue

这个库思路和xflow不一样，实际上是借鉴了antv/graphin的思路。将Graph，内置的shape这些都抽象成**原生**的vue组件使用。

本质上是把x6这个**MVC**的库，退化成一个类似**UI**库的存在。让用户自己管理数据和逻辑。

另外，你也可以多等一段时间，据我所知x6团队是有计划出一个功能类似的**react**/**vue**的封装版本。

**Comment by xiaqiuchu** [comment]
> 的思路。将Graph，内置的shape这些都抽象成**原生**的vue组

谢谢你
