### ISSUE TITLE
自定义react节点，拖拽生成节点无法更新节点描述

### ISSUE THREAD

**Issue by fainWang** [antvis/X6#2624]
### 问题描述

1. 采用自定义react 节点时，拖拽生成的新节点无法通过修改attrs来更新节点属性，如节点描述
2. 已测试setArrtes等方法，仅能更新画布已渲染节点，对于拖拽新增节点无法更新

### 重现链接

1

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
1

**Comment by NewByVector** [comment]
能提供一个可以复现的 demo 看下吗？

**Comment by NewByVector** [comment]
因为无法复现，先关闭这个 issue，如果可以提供可以复现的 demo，请重新提一个 issue。
