### ISSUE TITLE
可以设定节点的链接桩规则嘛？

### ISSUE THREAD

**Issue by IcarusRyy** [antvis/X6#2625]
### 问题描述

最近项目需求需要设定几个规则，比如矩形要设定为单进单出，（我已经设定为2个链接桩了，但是不知道怎么进行入口和出口限定）。

### 重现链接

https://codesandbox.io/s/ph3c65?file=/src/app.tsx

### 重现步骤

1、进入页面；
2、设定矩形为单进单出规则，定义链接桩只能一个进，一个出

### 预期行为

设定矩形为单进单出规则，定义链接桩只能一个进，一个出

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by babachao** [comment]
可以在[validateConnection](https://x6.antv.vision/zh/docs/api/graph/interaction/#validateconnection)做判断
也可参考这个[例子](https://x6.antv.vision/zh/examples/showcase/faq#validate-connection)

**Comment by IcarusRyy** [comment]
那个判断的没弄懂咋写&nbsp;。 我利用这个监听创建新的edge的 connected事件， 在回调函数里对开始节点和结束节点进行的判断，如果是我想要的，该edge遵守连线规则，就保留，如果不遵守我们的规则，就调用edge.remove方法移除掉。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/X6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 中午12:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/X6] 可以设定节点的链接桩规则嘛？ (Issue #2625)





 
可以在validateConnection做判断
 也可参考这个例子
