### ISSUE TITLE
使用react自定义节点后，节点无法手动连线，节点只能拖拽，改为非自定义的节点就正常。

### ISSUE THREAD

**Issue by misslinge** [antvis/X6#2626]
### Describe the bug

使用react自定义节点后，节点无法手动连线，节点只能拖拽，改为非自定义的节点就正常。

### Your Example Website or App

https://codesandbox.io/s/upbeat-wood-tvnvub?file=/src/App.js

### Steps to Reproduce the Bug or Issue

鼠标连线两个节点，没法生成连线

### Expected behavior

期望使用react的节点可以手动连线。

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lloydzhou** [comment]
我尝试把这个节点内部样式（宽和高）改动了一下，就可以在节点边缘部分拉出连接线

![image](https://user-images.githubusercontent.com/1826685/188403620-361da86d-e202-4130-982f-3f593d3e4e84.png)

x6这边连线是在`.x6-node [magnet='true']`的元素上监听事件进行处理的。
而你的demo里面，react定义的在`foreignObject`内部的元素，把这个节点内部的rect这个`[magnet='true']`的元素给盖住了。导致不能响应拖拽的事件。

你可以尝试将自己定义的react节点内部的元素控制一下大小，不要盖住rect这个元素。就正常了。

**Comment by misslinge** [comment]
> 我尝试把这个节点内部样式（宽和高）改动了一下，就可以在节点边缘部分拉出连接线
> 
> ![image](https://user-images.githubusercontent.com/1826685/188403620-361da86d-e202-4130-982f-3f593d3e4e84.png)
> 
> x6这边连线是在`.x6-node [magnet='true']`的元素上监听事件进行处理的。 而你的demo里面，react定义的在`foreignObject`内部的元素，把这个节点内部的rect这个`[magnet='true']`的元素给盖住了。导致不能响应拖拽的事件。
> 
> 你可以尝试将自己定义的react节点内部的元素控制一下大小，不要盖住rect这个元素。就正常了。

这样改了在边缘部分连线挺不友好的，官方是不是使用react节点本身就不支持手动连线。

**Comment by lloydzhou** [comment]
我不是要你把样式改成我这样，我这样改动只是为了好演示！

你可以通过自己处理css样式，尽量不让react渲染出来的元素覆盖到rect，这样就不会影响连线操作了。

**Comment by misslinge** [comment]
> 我不是要你把样式改成我这样，我这样改动只是为了好演示！
> 
> 你可以通过自己处理css样式，尽量不让react渲染出来的元素覆盖到rect，这样就不会影响连线操作了。

好的，谢谢。
