### ISSUE TITLE
如果节点设置toFront后，再从stencil拖动的节点会在这个节点的后面

### ISSUE THREAD

**Issue by XueMeijing** [antvis/X6#2640]
### Describe the bug

如果节点设置toFront后，再从stencil拖动的节点会在这个节点的下面，会被挡到。对于group嵌套节点来说，直接从stencil拖到嵌套节点里面算是很常见的操作吧，所以这应该算是个bug？

刚拖动出来的节点是没有zIndex的，但是它node.store.data.previous有zIndex。 我尝试过给getDropNode后的节点setZIndex，但是getMaxZIndex都是0。
```
getDropNode(node) {
  let shortIdNode = graph.updateCellId(node, node.id.substring(0, 8))
  const size = shortIdNode.size();
  
 // 拖动到画布后再设置zIndex
  setTimeout(() => {
    graph.getCellById(shortIdNode.id).setZIndex(graph.model.getMaxZIndex() + 1)
    console.log(graph.getCellById(shortIdNode.id))
  }, 300)

  if (shortIdNode?.store?.data?.type === 'NESTED_LOOP') {
    return shortIdNode.size(size.width * 3, size.height * 4);
  }
  return shortIdNode.size(size.width * 1, size.height * 1);
},
```

视频如下：点击节点会给它设置toFront，然后拖动新节点就在下面。

https://user-images.githubusercontent.com/35559153/188798244-16c56cfc-e0a3-49be-826e-4f21e86e8160.mp4

### Your Example Website or App

如上视频

### Steps to Reproduce the Bug or Issue

1. 点击当前节点给他设置toFront
2. 从stencil拖动节点到当前节点，会出现在这个节点下面
3. 如果所有节点都是一样大小，是问题不大的。但是如果当前节点是嵌套节点，就会被面积大的嵌套节点挡住

### Expected behavior

从stencil拖出来的节点应该显示在最上层

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by XueMeijing** [comment]
> @XueMeijing 可以用 `node:added` 事件监听节点被添加到画布上，然后使用 `node.setZIndex` 方法来修改节点的 zIndex。

试了一下可以的，谢谢大佬～

**Comment by qiufeihong2018** [comment]
> > @XueMeijing 可以用 `node:added` 事件监听节点被添加到画布上，然后使用 `node.setZIndex` 方法来修改节点的 zIndex。
> 
> 试了一下可以的，谢谢大佬～

请问是怎么处理各个节点的层级关系的，最佳实践是什么？

**Comment by XueMeijing** [comment]
> 请问是怎么处理各个节点的层级关系的，最佳实践是什么？

我就是给嵌套节点加个nestedParent属性，从stencil拖过来的时候如果是嵌套节点尺寸就变普通节点的三倍，然后拖动的时候 embedding 检测嵌套节点，另外就是做了嵌套节点连线 validateConnection 的检测：子节点连接嵌套节点是尾连尾，嵌套节点连接子节点是头连头，看个人需求

```
embedding: {
  enabled: true,
  findParent({ node }) {
    const bbox = node.getBBox();
    return this.getNodes().filter((parentNode) => {
      // 只有 data.nestedParent 为 true 的节点才是父节点
      if (parentNode?.store?.data?.nestedParent) {
        const targetBBox = parentNode.getBBox();
        return bbox.isIntersectWithRect(targetBBox);
      }
      return false;
    });
  },
},
```
