### ISSUE TITLE
x6使用群组后绘制边贴着节点走，有偏差

### ISSUE THREAD

**Issue by A-llian** [antvis/X6#2641]
### 问题描述

![image](https://user-images.githubusercontent.com/41275150/188813211-4b134a51-5801-49fa-9bfb-80fed0115b24.png)

### 重现链接

[demo](https://codesandbox.io/s/7nunv2)

### 重现步骤

无

### 预期行为

![image](https://user-images.githubusercontent.com/41275150/188813407-b5253a5c-255a-4f8d-bb08-95f9a74d2326.png)

### 平台

Windows

**Comment by NewByVector** [comment]
其实控制台已经打印错误了：`Unable to execute manhattan algorithm, use orth instead `,因为两个节点在父节点内部，已经无法避开障碍物了，所以路由降级为 orth 路由。这里可以通过 manhattan 路由配置排除掉父节点的影响。
