### ISSUE TITLE
复制粘贴修改ID后的节点，撤销粘贴会报错

### ISSUE THREAD

**Issue by XueMeijing** [antvis/X6#2642]
### Describe the bug

复制粘贴修改ID后的节点，撤销粘贴会报错，undoStack里面的节点id，有一部分是修改前的id，所以excuteCommand里面获取的节点是undefined, 所以报错。我看issue里其他人也遇到了，截图如下

### Your Example Website or App

如上描述

### Steps to Reproduce the Bug or Issue

1. 修改节点id
2. 复制粘贴节点
3. 撤销报错，undoStack里面的节点id，有一部分是修改前的id

### Expected behavior

可以正常撤销

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/35559153/188818682-3a50e6c1-f38c-4bf9-b937-0aca6381c18f.png)

![image](https://user-images.githubusercontent.com/35559153/188818454-a5ac17db-8420-47ab-8c7a-d3752dac8ccd.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
是怎么修改节点的 ID 的呢？

**Comment by NewByVector** [comment]
2.x 版本中已经没有了这个问题。
