### ISSUE TITLE
display:none;时渲染画布，之后再转为display:block;连接线的连接点会出现在左上角

### ISSUE THREAD

**Issue by 1057189519** [antvis/X6#2647]
### Describe the bug

display:none;时渲染画布，之后再转为display:block;连接线的连接点会出现在左上角，点击的选择框会变为一个点，而不是框选节点

### Your Example Website or App

https://codesandbox.io/s/unruffled-chebyshev-bkwcsf?file=/index.html

### Steps to Reproduce the Bug or Issue

1. 运行代码

https://codesandbox.io/s/unruffled-chebyshev-bkwcsf?file=/index.html
![image](https://user-images.githubusercontent.com/75262115/189012643-310b8056-debe-4e03-a6c6-27da5fad1cb0.png)

2. 会发现连线的接点在左上角，而正常情况应该是在中间 

### Expected behavior

![image](https://user-images.githubusercontent.com/75262115/189012709-b6e8f654-a9a3-4a28-96aa-31fdf408a411.png)
正确的显示方式应该是这样

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/75262115/189012795-3923bd76-9e20-4b05-86bc-0bb0a6a614b8.png)
正常表现应该像上图，连线接点指向中间，且随节点的移动改变位置

但是当display:none时渲染画布，之后改为display:block; 会出现下图的情况，连线接点在左上角，且节点移动时一直指向左上角，这并不是想要的
![image](https://user-images.githubusercontent.com/75262115/189013178-68856ab1-7477-46dd-9691-2668f775d600.png)

### Platform

- OS: Windows
- Browser: Chrome

**Comment by 1057189519** [comment]
@vector

**Comment by 1057189519** [comment]
@vector

**Comment by babachao** [comment]
阔以搞个demo么

**Comment by 1057189519** [comment]
> 阔以搞个demo么

[demo.txt](https://github.com/antvis/X6/files/9524380/demo.txt)
因为上传文件不支持html，所以用了txt，复现后缀换成html就可以了，感谢！

**Comment by 1057189519** [comment]
@babachao
请问可以找到是哪里的问题吗？可以解决吗？

**Comment by 1057189519** [comment]
@babachao
应该是这里获取节点宽高的函数获取方法不适合display：none时，父元素为display：none时，
`        console.log($("#div1").width())
        console.log($("#div1").height()) `
这种可以获取到子元素的宽高，其他方式获取的结果是0

**Comment by 1057189519** [comment]
![image](https://user-images.githubusercontent.com/75262115/189298260-637ab3a9-8cdf-4ca9-9022-76216de2700a.png)

**Comment by 1057189519** [comment]
![image](https://user-images.githubusercontent.com/75262115/189793025-291e2cef-952a-4eb6-a058-4b1687843446.png)
这个位置改成200%可以解决display:none情况下画布显示不全的问题

**Comment by 1057189519** [comment]
> 阔以搞个demo么

https://codesandbox.io/s/unruffled-chebyshev-bkwcsf?file=/index.html

**Comment by 1057189519** [comment]
@NewByVector

**Comment by 1057189519** [comment]
@babachao

**Comment by 1057189519** [comment]
hello！请问是否有好的解决方法呢？麻烦告知一下，谢谢！ @babachao @NewByVector

**Comment by zhenghan2017** [comment]
我也碰到了这个问题，在你的demo上我尝试用visibility属性去控制可以先饶过这个问题

**Comment by 1057189519** [comment]
> 

请问你是怎么加的呢，为什么我使用visibility属性还是有这个问题
@zhenghan2017

**Comment by 1057189519** [comment]
@zhenghan2017 OK，我明白了，但是实际应用我是要配合v-show使用的，如果使用动态绑定visibility属性的话，隐藏不彻底，visibility: hidden仍旧会占用空间，依旧绕不过去这个问题的

**Comment by zhenghan2017** [comment]
> @zhenghan2017 OK，我明白了，但是实际应用我是要配合v-show使用的，如果使用动态绑定visibility属性的话，隐藏不彻底，visibility: hidden仍旧会占用空间，依旧绕不过去这个问题的

抱歉，忘记看了，更新了一下解决方案，我现在是用visibility + height为0的方案解决的，具体可以看我写的这个[x6宽高问题](https://codesandbox.io/s/modest-williams-4vcqgt?file=/src/App.js)

**Comment by 1057189519** [comment]
> 

@zhenghan2017  很感谢，在我的方案中是要求第一次是不显示的，所以对于您的第三个按钮display的切换如果是这样`<div ref={containerRef} style={{ height: 100,display:'none' }}>`就会出现和我一样的问题。但是使用您的第二个按钮就可以解决这个问题，非常感谢。

**Comment by NewByVector** [comment]
@1057189519 @zhenghan2017 @babachao 这个是因为在画布隐藏情况下，浏览器 api `elem.getBBox()` 无法返回正确的元素包围盒，所以出现上面情况，在 1.x 版本中需要我们自己来保证在画布显示完成之后，再添加元素，这个在 2.0 版本中已经解决了这个问题。

**Comment by 1057189519** [comment]
> 

我引用[https://cdn.jsdelivr.net/npm/@antv/x6/dist/index.js](url)的x6，官网说是最新版本，依旧是会出现这个问题的

**Comment by 1057189519** [comment]
> 

我引用[https://cdn.jsdelivr.net/npm/@antv/x6/dist/index.js](https://github.com/antvis/X6/issues/url)的x6，官网说是最新版本，依旧是会出现这个问题的

**Comment by 1057189519** [comment]
@NewByVector 我引用[https://cdn.jsdelivr.net/npm/@antv/x6/dist/index.js](https://github.com/antvis/X6/issues/url)的x6，官网说是最新版本，依旧是会出现这个问题的
