### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by FreeFrags** [antvis/X6#2654]
### Describe the bug

@antv/x6-react-components uses "react-resize-detector": "^6.6.4"

https://github.com/antvis/X6/blob/3a79c686cd4c405290e97872a18c4b96a44fc0fb/packages/x6-react-components/package.json#L74

react-resize-detector  ^6.6.4 has the following:
`"peerDependencies": {
    "react": "^16.0.0 || ^17.0.0",
    "react-dom": "^16.0.0 || ^17.0.0"
  },`

Now there is a react-resize-detector which supports react 18
https://github.com/maslianok/react-resize-detector/blob/0d0ca11dbff556d3831a9a186e12075f381cab13/package.json#L48

Please update so there will be proper react 18 support

### Your Example Website or App

---

### Steps to Reproduce the Bug or Issue

1. none everything can be found in the package.json

### Expected behavior

React 18 should be supported. and the correct dependencies added

### Platform

Any platform as it is only versions

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/pull/2684

**Comment by NewByVector** [comment]
please update to @antv/x6-react-components@1.1.17
