### ISSUE TITLE
graph的container不够大，导致卡片显示被遮挡

### ISSUE THREAD

**Issue by zwb234** [antvis/X6#2661]
### 问题描述

graph的container自动计算的大小不够，导致图的部分内容被遮挡。
请问用何种方式可以控制这个container的宽高？
下边有复现链接，也有操作指引。

### 重现链接

https://codesandbox.io/s/graphde-containerbu-gou-da-sn62dl

### 重现步骤

1、进入页面
2、拉到最下边的卡片
3、鼠标hover名为“老五”或者“老六”的卡片
4、一共有六个删除，分别是’删除1‘、’删除2‘、...‘删除6’。
5、但是最下边的删除只能显示到‘删除4’，无法全部展示。
6、排查原因发现是container的大小限制了显示，请问用何种方式可以控制这个container的宽高？

### 预期行为

期望看到全部工具栏，但实际上部分被遮挡。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）
![image](https://user-images.githubusercontent.com/57169366/189127483-92f38b24-e147-4b49-88aa-600b88e078e3.png)

**Comment by lloydzhou** [comment]
使用ItemTool实现的菜单本质上还是在svg内部，svg内部的元素不会超出其范围（拖动画布的时候，就算节点也会被隐藏）。

关于这一点，你可以参考svg的[viewBox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox)属性。



如果想要实现可以超出范围的，可以参考其他的实现方式。
例如x6内置的selection功能，还有minimap等功能都是实现了一个独立于svg的组件。这些组件不会随着画布拖动被隐藏。
但是，这种类型的组件也有另一个特性就算不会随着画布缩放。
