### ISSUE TITLE
路由中的manhattan算法有哪里可以看解析吗

### ISSUE THREAD

**Issue by donghuizhou** [antvis/X6#2664]
### 问题描述

想了解下manhattan算法，哪里可以看具体解析

### 重现链接

none

### 重现步骤

none

### 预期行为

manhattan算法

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
暂时没有相关的文档介绍，可以查看[源代码](https://github.com/antvis/X6/tree/master/packages/x6/src/registry/router/manhattan)
