### ISSUE TITLE
请问下这个路由的连线规则怎么设定的

### ISSUE THREAD

**Issue by donghuizhou** [antvis/X6#2673]
### 问题描述

下图上只配置了几个点、连线和router设为 manhattan，看上去符合预期
![image](https://user-images.githubusercontent.com/31002949/189843277-6042426f-8b8c-4d1e-82ca-201f9d103d88.png)
但是当我把【节点234】都移到【节点1】下面后，连线不符合预期，**我的预期希望是图右边手绘那样**
![image](https://user-images.githubusercontent.com/31002949/189844130-06387206-128d-4c3a-b215-2f4bb8ac5518.png)
请问这种路由模式下的连线规则是怎么设定的？并且如何才能实现我**下面预期行为里的效果**

### 重现链接

none

### 重现步骤

如上面描述

### 预期行为

1. 希望target节点都移动到source节点下面之后，连线如上图右侧手绘部分
2. **除了设置【连接桩的出/入】，【设置拐点】两种方式外，有无其他更智能方式**，因为节点一多，那我就要为每条连线去设置连接桩和拐点了，感觉比较麻烦

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
目前还没有这么智能的路由，感谢你的提出，我们会带下来研究。
