### ISSUE TITLE
如何让里面的线重叠

### ISSUE THREAD

**Issue by donghuizhou** [antvis/X6#2680]
### 问题描述

下图是我经过dagre布局，并且做了如下设置后的效果
```javascript
...
align: "UL",
...

setRouter({
    name: "manhattan",
    args: {
        padding: 20,
        startDirections: "bottom",
        endDirections: "top"
    }
})
```
![image](https://user-images.githubusercontent.com/31002949/190074261-f59ad6b5-bb73-458c-b77c-40c3657b758d.png)
然后我增加了【节点8】，并且连线链接了【节点5】到【节点8】，为什么【连线5->8】没有和【连线5->7】重合，这样连显得不好看
![image](https://user-images.githubusercontent.com/31002949/190075561-7c72ea79-ec69-4cc3-95cd-299fe6e2ba22.png)

### 重现链接

none

### 重现步骤

如上面所述

### 预期行为

【连线5->8】与【连线5->7】重合

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
如果重合岂不是 5-7 那条线完全无法判断是否存在？

**Comment by donghuizhou** [comment]
> 如果重合岂不是 5-7 那条线完全无法判断是否存在？

那如果我希望 5-7 和 5-8 连线重叠，有什么办法优化连线吗

**Comment by NewByVector** [comment]
在 2.x 版本中可以使用 manhattan 的 `snapToGrid` 配置解决。
