### ISSUE TITLE
定义了两个链接桩组在同一侧，若每个连接桩组只使用一次，则两个链接桩位置重合，有一个链接桩组使用两次，则

### ISSUE THREAD

**Issue by ZHUYUANWEI** [antvis/X6#2682]
### Describe the bug

异常情况：定义了两个链接桩组在同一侧，若每个连接桩组只使用一次，则两个链接桩位置重合，不均匀分布。

1、若有一个链接桩组使用两次，则能够均匀分布，显示正常。
2、又测试了一下，发现好像是两个链接桩组是分别进行均匀分布的，所以会导致重合。想问一下是否支持两个组的连接桩合在一起进行均匀分布。

### Your Example Website or App

https://x6.antv.vision/zh/examples/node/port#label

### Steps to Reproduce the Bug or Issue

请将下方代码替换到上方链接中，就可以复现问题
```
ports: {
    groups: {
      in_1: {
        position: "left",
      },
      in_2: {
        position: "left",
      },
    },
    items: [
      {
        group: 'in_1',
        attrs: {
          text: {
            text: 'in_1-1', // 标签文本
          },
        },
      },
      {
        group: 'in_2',
        attrs: {
          text: {
            text: 'in_2-1', // 标签文本
          },
        },
      },
    ],
  },
```

### Expected behavior

希望，当定义两个在一侧的链接桩组，每个只使用一次时，能够均匀分布。

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/26238890/190108328-8ca2da0c-e7bd-4c5b-9f26-1c844018ec32.png)
![image](https://user-images.githubusercontent.com/26238890/190108614-7c2b961d-d864-48ab-96dc-f982f57ae2c3.png)

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [1.34.0]

**Comment by NewByVector** [comment]
这个是正常现象，group 默认的是 left 布局，也就是定义成一个 group 内的连接桩均匀分布在左侧。

**Comment by NewByVector** [comment]
那就使用同一个 group，如果有样式的区别，可以使用其他手段来实现。

**Comment by ZHUYUANWEI** [comment]
我的最终目的是为了，通过group来区分不同的输入桩，当连接不同的输入桩时，进行不同的操作。有没有其他方案

**Comment by NewByVector** [comment]
可以用 port 的 id 来区分吧

**Comment by ZHUYUANWEI** [comment]
因为可能有多个相同节点，id写死可能不行，想使用随机的生成的id。目前的解决方案，是将链接桩绝对定位，来使显示正常
