### ISSUE TITLE
 边与边 之间连接样式美化

### ISSUE THREAD

**Issue by JasonWang1998** [antvis/X6#2686]
### 功能描述

X6 是否可以支持桑基图中边的连接方式

### 期望解决方案

X6 是否可以支持桑基图中边的连接方式
![image](https://user-images.githubusercontent.com/24191303/190329564-ae9c4873-7b94-4603-8b21-3f9cbaa9620d.png)

**Comment by NewByVector** [comment]
可以参考这个[案例](https://github.com/antvis/X6/tree/v1/sites/x6-sites-demos/packages/scene/sankey)。
