### ISSUE TITLE
如何实现定位

### ISSUE THREAD

**Issue by ganchaolian** [antvis/X6#2687]
### 功能描述

我现在做了一个树布局，里面有几百个节点，如果实现定位到某个节点时居中在画布中间

### 期望解决方案

想知道定位怎么实现，谢谢解答~

**Comment by lloydzhou** [comment]
https://x6.antv.vision/en/docs/tutorial/basic/scroller/#centercelloptions-centeroptions
![image](https://user-images.githubusercontent.com/1826685/191739866-0293a473-ac5b-40c8-b4d5-11f49eb76400.png)
