### ISSUE TITLE
有没有检测连线经过节点的方法

### ISSUE THREAD

**Issue by donghuizhou** [antvis/X6#2688]
### 问题描述

给edge增加拐点后，如果拐线经过了某个节点，有没有方法可以检测连线遇到了障碍物

### 重现链接

none

### 重现步骤

见上

### 预期行为

有方法可以检测连线经过了障碍物

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by chengwenxin** [comment]
m

**Comment by NewByVector** [comment]
没有这个功能的。
