### ISSUE TITLE
app/draw 使用原生 SVG 能力渲染节点

### ISSUE THREAD

**Issue by bubkoo** [antvis/X6#269]
### Expected Behavior

在这个 demo 中不要全部使用 React 渲染节点，应该大部分使用 SVG 来渲染节点，展示 SVG 原本的能力。使用 SVG 渲染出基础节点，就可以在右侧提供统一的样式设置面板，比如修改节点边框的颜色/大小等。

另外，页面布局和样式有点丑，参考一下 app/dag 的样式。

**Comment by NewByVector** [comment]
demo已经更新
