### ISSUE TITLE
父子节点在dom上为同级，是否可以有配置项使其在dom层级上形成嵌套

### ISSUE THREAD

**Issue by lhC0** [antvis/X6#2691]
### 问题描述

##问题
父子节点在dom上为同级，是否可以有配置项使其在dom层级上形成嵌套
## 目的
使用html2canvas 对某一个父节点及其所有子节点以及边 生成一个缩略图

### 重现链接

暂无

### 重现步骤

非bug

### 预期行为

使用html2canvas 对某一个父节点及其所有子节点以及边 生成一个缩略图

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.34.0 ... ]
- 框架: [ ant design pro]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/29115820/190363794-fa45ea5e-6153-4f5f-8dd1-ce6462641d6d.png)

**Comment by NewByVector** [comment]
svg 渲染顺序是根据 dom 的先后顺序的，所以 x6 中层级是根据 dom 先后顺序来的，而不是嵌套。

**Comment by zk923852367** [comment]
如果不能按dom的方式形成嵌套，那么能否支持节点嵌套后锁定
