### ISSUE TITLE
Edge 连接bug  显示错误，具体看图

### ISSUE THREAD

**Issue by JasonWang1998** [antvis/X6#2694]
### 问题描述

![image](https://user-images.githubusercontent.com/24191303/190550637-2df55a19-5049-40dd-ba6f-d6e3588a3857.png)
validateConnection({ type, edgeView, sourceView, targetView, targetMagnet }) {
          return true
}

### 重现链接

no

### 重现步骤

看图

### 预期行为

显示正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/24191303/190550637-2df55a19-5049-40dd-ba6f-d6e3588a3857.png)

**Comment by Angelii** [comment]
可否提供一个在线 demo？复现一下问题场景哈

**Comment by NewByVector** [comment]
是不是设置了 filter，可以参考这个 [demo](https://codesandbox.io/s/lian-xian-de-lu-jing-xiao-guo-s1k011?file=/src/App.tsx)。你的问题暂时无法复现，请提供一个可以复现的 demo，重新提一个 issue。
