### ISSUE TITLE
文档中关于zIndex的描述是否存在歧义的问题描述

### ISSUE THREAD

**Issue by JUST-Limbo** [antvis/X6#2696]
### 问题描述

- https://antv-x6.gitee.io/zh/docs/tutorial/basic/cell#zindex
- https://antv-x6.gitee.io/zh/docs/api/model/cell/#zindex
上述文档中关于zIndex的描述都提到了“调用 cell.toFront() 和 cell.toBack() 来将其移到最顶层或对底层”，此处“对底层”是否指“最底层”？

### 重现链接

https://antv-x6.gitee.io/zh/docs/api/model/cell/#zindex

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]

**Comment by lloydzhou** [comment]
提pr把文档改掉
