### ISSUE TITLE
安装X6依赖后，启动项目会报错，提示“Cannot find namespace 'JQuery'”

### ISSUE THREAD

**Issue by 246369** [antvis/X6#2697]
### 问题描述

在项目中执行 “yarn add @antv/x6”，安装X6依赖后，在页面中导入X6（“import { Graph } from '@antv/x6';”），启动项目时会报错，提示“Cannot find namespace 'JQuery'”。

这时尝试创建一个新的angular项目，安装X6依赖，启动项目时依然报错。步骤如下：
1、执行 “ng new my-project --style less --routing --package-manager yarn”，创建一个新的angular项目
2、执行 “yarn add @antv/x6”，安装X6依赖
3、在页面中导入X6（“import { Graph } from '@antv/x6';”）
4、执行 “yarn start” 启动项目时，会报错，提示“Cannot find namespace 'JQuery'”

### 重现链接

暂没

### 重现步骤

创建一个新的angular项目，安装X6依赖，启动项目时报错。步骤如下：
1、执行 “ng new my-project --style less --routing --package-manager yarn”，创建一个新的angular项目
2、执行 “yarn add @antv/x6”，安装X6依赖
3、在页面中导入X6（“import { Graph } from '@antv/x6';”）
4、执行 “yarn start” 启动项目时，会报错，提示“Cannot find namespace 'JQuery'”

### 预期行为

会报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![捕获](https://user-images.githubusercontent.com/62083771/190842221-2f1280f6-0465-4991-ae95-8b6fb546a16a.PNG)
![111](https://user-images.githubusercontent.com/62083771/190842308-435b8a5c-cf86-4cb9-9402-8b4339317605.PNG)

**Comment by codezzc** [comment]
请问下这个问题解决了吗
