### ISSUE TITLE
vue3 inject getData undefine

### ISSUE THREAD

**Issue by wanghaotian2022** [antvis/X6#2698]
### 问题描述

inject获取getNode后，调用出错，说this.getNode不是一个函数，于是我打印了这个this，getNode是Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.s

### 重现链接

none

### 重现步骤

none

### 预期行为

none

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![Screenshot from 2022-09-17 15-08-35](https://user-images.githubusercontent.com/110762479/190845212-0f6488e3-1446-44aa-8de3-6162e06c205f.png)
![Screenshot from 2022-09-17 15-13-37](https://user-images.githubusercontent.com/110762479/190845264-34d1e7af-72f3-48d2-8125-8068860c8d57.png)

**Comment by damnright** [comment]
猜测应该是节点没有正确register

**Comment by NewByVector** [comment]
请问该问题解决了吗，是否可以提供一个可以复现的 demo？
