### ISSUE TITLE
如何实现边连接节点的边框的任意位置？

### ISSUE THREAD

**Issue by WhySuddenly** [antvis/X6#2702]
### 问题描述

像语雀一样，边箭头拖动到节点的边缘时，边框的任意位置都可连接，不依赖链接桩

![image](https://user-images.githubusercontent.com/22953885/190971833-f0b8b56f-ad31-4329-9b2c-3c18b0dcde5d.png)

![image](https://user-images.githubusercontent.com/22953885/190971874-75bde8ef-5b0c-4a4a-8083-a62e16182fb5.png)

### 重现链接

none

### 重现步骤

none

### 预期行为

期望边可以连接节点边框的任意位置

### 平台

none

**Comment by NewByVector** [comment]
这个可以通过 nodeAnchor 来自己实现的，等我空了我写个 demo。

**Comment by WhySuddenly** [comment]
> 这个可以通过 nodeAnchor 来自己实现的，等我空了我写个 demo。

好的，感谢。一直在等着你的demo

**Comment by WhySuddenly** [comment]
> 这个可以通过 nodeAnchor 来自己实现的，等我空了我写个 demo。

请问demo出了吗 :) 实在不知道nodeAnchor 要怎么实现

**Comment by NewByVector** [comment]
重复问题，先关闭。
