### ISSUE TITLE
节点间的拖动能否限制范围

### ISSUE THREAD

**Issue by donghuizhou** [antvis/X6#2703]
### 问题描述

能否给每个节点外添加个区域，使得任意节点拖动时，始终拖不进其他节点的设定的区域内？也就是无论画布中的节点如何布局、拖动，**任意节点间始终都有一定的距离，不存在重叠。**

### 重现链接

none

### 重现步骤

拖动任意节点

### 预期行为

任意节点之间始终保持一定距离，不能重叠

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以使用 [restrict 配置](https://x6.antv.vision/zh/docs/tutorial/basic/interacting/#restrict) 来实现。
