### ISSUE TITLE
如何让图中这一部分连线重叠

### ISSUE THREAD

**Issue by donghuizhou** [antvis/X6#2705]
### 问题描述

![image](https://user-images.githubusercontent.com/31002949/190991411-1c9ebbfb-6ede-449c-bc87-39ac8e3887cf.png)
如上图所示，红色箭头指向部分是连线【节点1-4】，绿色箭头指向部分是连线【节点1-6】,根据 [issue#2680](https://github.com/antvis/X6/issues/2680)，如果重合，那被覆盖的线就无法判断是否存在。逻辑上没问题，但是视觉上觉得不是很好看，请问下如何让这两条线重合？
并且我们项目中节点布局和连线由用户任意拖动连接决定，需要在代码中找到有两条线平行的情况并让它们重合，有办法吗？

### 重现链接

none

### 重现步骤

如图

### 预期行为

让图上红色箭头所指和绿色箭头所指的两条线重合。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
修改 manhattan 路由的 step 配置试试？
