### ISSUE TITLE
How to nest node without ports

### ISSUE THREAD

**Issue by ourdark** [antvis/X6#2708]
### 问题描述

I'm working on a ERD development, and X6 er diagram example use port for entity fields. I am wondering if I can define a nest node hierarchy for an entity, a entity rectangle with many field rectangles dynamically, is that possible?  

### 重现链接

https://codesandbox.io/s/new)

### 重现步骤

https://x6.antv.vision/en/examples/showcase/practices#er

### 预期行为

https://x6.antv.vision/en/examples/showcase/practices#er

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by ourdark** [comment]
@NewByVector, good to know that, do you have any idea in mind to draw a Entity(with fields)?

**Comment by ourdark** [comment]
@NewByVector I've also working on custom node(Entity), the shortcut of custom node is working but regular extends not. I also considering custom node will take too much efforts on it, what would you think?

**Comment by NewByVector** [comment]
If you are familiar with the React stack, check out this [demo](https://github.com/antvis/X6/blob/master/examples/x6-example-features/src/pages/react/table/index.tsx)

![image](https://user-images.githubusercontent.com/20186737/191465159-db6b77fd-580a-43a8-a5e3-f0411443d3e2.png)
