### ISSUE TITLE
【创建Node节点】添加contenteditable属性后，还是不可编辑

### ISSUE THREAD

**Issue by alexwjj** [antvis/X6#2710]
### Describe the bug

Graph.registerNode 创建节点时，添加contenteditable: 'true'属性后，还是不可编辑，复现地址：https://codesandbox.io/s/compassionate-monad-xnp6gt?file=/src/app.tsx:348-372 

### Your Example Website or App

https://codesandbox.io/s/compassionate-monad-xnp6gt?file=/src/app.tsx:348-372

### Steps to Reproduce the Bug or Issue

1、打开地址：https://codesandbox.io/s/compassionate-monad-xnp6gt?file=/src/app.tsx:348-372
2、点击文本，还是不可编辑。控制台显示contenteditable已加上

### Expected behavior

可编辑文本

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/29943063/191219364-182610fa-9465-4033-9f13-ae1fe8ad0ade.png)

_No response_

### Platform

- OS: [macOS]
- Browser: [Chrome]

**Comment by alexwjj** [comment]
有node-tool支持~~~搞定

**Comment by noenif** [comment]
![image](https://user-images.githubusercontent.com/25174520/204436950-bc8f3395-87a3-4cad-90f8-e7533503838a.png)
