### ISSUE TITLE
节点通过Vue来自定义，连线位置如何修改？

### ISSUE THREAD

**Issue by zhouxinyong** [antvis/X6#2712]
### 问题描述

1. 节点是通过vue来自定义的，darge布局后，连线位置永远是在左上角，怎么修改位置？
![image](https://user-images.githubusercontent.com/15569753/191410125-b52afb8b-7955-433b-8956-8fc35eb1abba.png)

2. 根节点的连线还会遮挡节点内容，如下所示：
![image](https://user-images.githubusercontent.com/15569753/191410386-70f87ee4-e8cb-43e5-a541-4424bb33b677.png)

### 重现链接

https://codesandbox.io/s/vue-shape-forked-yrvgxn?file=/src/App.vue

### 重现步骤

直接打开codesandbox链接即可看到

### 预期行为

连线能够自动居中，更美观，节点内容不被遮挡

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 1.34.1

**Comment by lloydzhou** [comment]
请给节点加上width和height属性。
![image](https://user-images.githubusercontent.com/1826685/191434587-3d81ec2b-cdbe-4304-9053-be98cb2539b4.png)
