### ISSUE TITLE
选择父节点之后再选择子节点的边会出现报错

### ISSUE THREAD

**Issue by start-point** [antvis/X6#2713]
### Describe the bug

Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1.点击父节点
2.点击子节点的边
2.出现报错，编辑器崩塌了。。。

### Expected behavior

我不想出现这个报错

### Platform

无

**Comment by NewByVector** [comment]
提供一个可以复现的 demo 看下？

**Comment by start-point** [comment]
> 
内网。。。
给不了

**Comment by NewByVector** [comment]
因为无法复现，暂时关闭，如果可以提供一个可以复现的 demo，请重新提一个新的 issue。
