### ISSUE TITLE
history 设置 ignoreRemove: true 无效

### ISSUE THREAD

**Issue by CYBoys** [antvis/X6#2717]
### Describe the bug

history 设置 `ignoreRemove: true` 之后在执行`this.graph.undo()`的时候仍然会去查找该cell，此时这个cell不应该没忽略吗？
```
 history: {
        enabled: true,
        ignoreAdd: true,
        ignoreRemove: true
      },
```
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/15981638/191694522-ec8f9c88-d4c9-4fb8-a96d-0fb877162d97.png">

### Your Example Website or App

https://codesandbox.io/s/antx-x6-removenode-error-w8l78m?file=/src/App.vue

### Steps to Reproduce the Bug or Issue

codesandbox 里面的 x6 和 vue-shape 版本不影响测试，我在本地的版本是
```
"@antv/x6": "^1.34.1",
"@antv/x6-vue-shape": "^1.5.1",
```

由于该版本在codesandbox有问题，故降低了版本

### Expected behavior

history 设置 ignoreRemove: true 之后在执行this.graph.undo()，不应该去查找该cell（不会crash）

### Screenshots or Videos

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/15981638/191694522-ec8f9c88-d4c9-4fb8-a96d-0fb877162d97.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 版本 105.0.5195.125（正式版本） (x86_64)

```
"@antv/x6": "^1.34.1",
"@antv/x6-vue-shape": "^1.5.1",
```

**Comment by NewByVector** [comment]
在这个 https://github.com/antvis/X6/pull/2802 已经修复，请更新到最新版本。
