### ISSUE TITLE
多个Edge连接在同一个node上，移动node卡顿

### ISSUE THREAD

**Issue by Mrheqiang** [antvis/X6#2719]
### 问题描述

当使用反序列化`graph.fromJSON(cells: (Node.Metadata | Edge.Metadata)[])`时，**当一个node上同时作用了多个edge**，在移动该node时候，页面会出现明显卡顿，页面在不断进行渲染计算

### 重现链接

https://codesandbox.io/s/dazzling-darwin-kes86t?file=/src/app.tsx

### 重现步骤

当使用反序列化`graph.fromJSON(cells: (Node.Metadata | Edge.Metadata)[])`时，**当一个node上同时作用了多个edge**，在移动该node时候，页面会出现明显卡顿，页面在不断进行渲染计算

### 预期行为

我期望可以正常移动不出现卡顿，结果移动会有明显卡顿

### 平台

- 操作系统: [macOS, Windows, Linux]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [^1.32.3-beta.1]

**Comment by NewByVector** [comment]
看你的 demo，卡顿来源主要是 `graph.on("cell:change:*", parse)` ，在你移动节点的时候，一直会触发 `cell:change`, 而且 `parse` 执行时间也比较久。比较合理的做法是在这里加一个 debounce。
