### ISSUE TITLE
minimap显示重影

### ISSUE THREAD

**Issue by AKIRAGuo** [antvis/X6#2723]
### 问题描述

minimap显示重影

### 重现链接

https://stackblitz.com/edit/vue-vsiqjl?file=package.json,public%2Findex.html,src%2FApp.vue,src%2Fcomponents%2FBaseGraph.vue

### 重现步骤

进入页面

### 预期行为

预期minimap正常显示，实际显示minimap重复出现

### 平台

操作系统: Windows
网页浏览器: Google Chrome
X6 版本: 1.31.0

### 屏幕截图或视频（可选）

minimap显示重影
![image](https://user-images.githubusercontent.com/7629219/192410499-114129e4-88d4-433a-9183-2fbd37937a89.png)
F12显示有两个x6-widget-minimap
![image](https://user-images.githubusercontent.com/7629219/192410552-201f00cc-38f8-44d6-9500-d5c64ac67449.png)
使用vue。graph设置为

**Comment by lloydzhou** [comment]
为啥要写这样的逻辑？每次生成一个新的？

![image](https://user-images.githubusercontent.com/1826685/193233487-3f1b8fca-d174-4258-a4cc-aed27fab1059.png)

如果真的需要重新生成，那清除的时候，是不是需要主动调用一下graph.dispose()

**Comment by NewByVector** [comment]
多次初始化画布所致，使用问题，先关闭。
