### ISSUE TITLE
文档问题：应该是示例链接失效

### ISSUE THREAD

**Issue by lloydzhou** [antvis/X6#2724]
### Describe the bug

文档问题：应该是示例链接失效

![image](https://user-images.githubusercontent.com/1826685/192475238-8974a4d5-66d9-4f1c-ae60-76f8e30f2a79.png)

### Your Example Website or App

https://x6.antv.vision/en/docs/tutorial/advanced/react/#%E6%B8%B2%E6%9F%93-react-%E8%8A%82%E7%82%B9

### Steps to Reproduce the Bug or Issue

文档问题：应该是示例链接失效

### Expected behavior

文档问题：应该是示例链接失效

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
已经修复。
