### ISSUE TITLE
使用react渲染label不会自动居中与线中间

### ISSUE THREAD

**Issue by Sharang-heng** [antvis/X6#2725]
### 问题描述

每次都要手动设置自定义label的位置很反人类

### 重现链接

https://codesandbox.io/s/7d504w

### 重现步骤

无

### 预期行为

我期望看到react渲染的label像普通label一样居中显示

### 平台

- 网页浏览器: [Google Chrome,]

**Comment by NewByVector** [comment]
因为无法计算自定义 label 的内容宽高，所以要自定义宽高以及 x、y，增加属性就可以：
```ts
attrs: {
  fo: {
    width: 120,
    height: 30,
    x: -60, // 宽度的一半
    y: -15, // 高度的一半
  },
},
```

**Comment by Sharang-heng** [comment]
但是像用布局这种就不可能每一个都自己算吧
