### ISSUE TITLE
如何在可视区域内预览整个画布

### ISSUE THREAD

**Issue by lizibeite** [antvis/X6#2730]
### 问题描述

如果x6的流程图画布很大，如何在可视区域内预览整个画布

### 重现链接

.

### 重现步骤

如何在可是区域内预览整个画布

### 预期行为

可视区域内预览整个画布

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
其实就是将整个画布缩放到正好讲所有元素显示在可视区域内部，可以使用以下的方法：
```ts
graph.zoomToFit({ maxScale: 1 })
```
