### ISSUE TITLE
画布设置渐变色背景不成功，应该如何设置？

### ISSUE THREAD

**Issue by lt717** [antvis/X6#2731]
### 问题描述

根据文档设置画布背景渐变色不成功
![截图1](https://user-images.githubusercontent.com/84703888/192670049-6f5748c9-f60d-4f83-89ec-e3c4d56bca4b.jpg)
![截图2](https://user-images.githubusercontent.com/84703888/192670081-108158b3-ab32-4faf-8dda-7d32c4f213ed.jpg)

应该怎么设置呢？

### 重现链接

无

### 重现步骤

如问题描述

### 预期行为

设置画布背景为渐变色

### 平台

- 操作系统:Windows
- 网页浏览器: Google Chrome
- X6 版本: 1.32.11

**Comment by NewByVector** [comment]
不好意思，color 是不支持渐变色的，可以使用带有渐变色的图片来实现背景渐变的效果。
