### ISSUE TITLE
为啥连接线上的标签会移动

### ISSUE THREAD

**Issue by itwmike** [antvis/X6#2733]
### Describe the bug

为啥连接线上的标签会移动？
版本：1.30.1
自定义连接线：
![image](https://user-images.githubusercontent.com/6613191/192733601-58e27d20-c2d3-4c48-a881-f66341abd33c.png)
效果：
![image](https://user-images.githubusercontent.com/6613191/192733695-ba751db2-a40e-4a88-b6b1-5f0c7847b42b.png)

![image](https://user-images.githubusercontent.com/6613191/192733836-499268ca-6c3f-46a2-b0c4-9b9de3bab402.png)

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Platform

无

**Comment by NewByVector** [comment]
有可以复现的 demo 看下吗？

**Comment by itwmike** [comment]
![image](https://user-images.githubusercontent.com/6613191/193178621-c311cb42-2cb8-492a-8f87-9935957baf84.png)
通过这个配置解决

**Comment by itwmike** [comment]
有出现新问题了，设置连线标签的时候报错：
Cannot read property 'markup' of undefined
代码：
(cell as Edge).setLabels([data.name])
![image](https://user-images.githubusercontent.com/6613191/193179693-1bb38577-c1a5-45ab-87e3-8813a5c8c633.png)

**Comment by itwmike** [comment]
已解决
