### ISSUE TITLE
替换svg为canvas

### ISSUE THREAD

**Issue by mioxs** [antvis/X6#2736]
### 功能描述

svg 数据量大时会卡死，参考[cytoscape.js](https://github.com/cytoscape/cytoscape.js)使用canvas实现。

### 期望解决方案

使用canvas性能更高

**Comment by NewByVector** [comment]
x6 面对是图编辑场景，和图分析有些区别，如果是图分析场景，建议使用 antv 下的 G6，X6 使用 svg 是为了提供简单易用的节点定制能力，具体选型可以参考[这篇文章](https://www.zhihu.com/question/435855401)。
