### ISSUE TITLE
Snapline对齐线，默认是截断的对齐线，且无法设置完整

### ISSUE THREAD

**Issue by xingxiang1227** [antvis/X6#2739]
### 问题描述

问题：Snapline对齐线，默认是截断的对齐线，且无法设置完整
1. 出现问题版本1.32.x、1.33.x、1.34.x
```javascript
const graph = new Graph({
  snapline: true,
})
```
![image](https://user-images.githubusercontent.com/20619652/193231153-e60a569f-9d55-49ea-ac23-782d992f43b0.png)

2. 相同代码，1.31.x版本无此现象
![image](https://user-images.githubusercontent.com/20619652/193231198-e2586117-b8c7-47d6-bd39-7a7dcc216059.png)

### 重现链接

https://codesandbox.io/s/pfhhjj?file=/index.ts

### 重现步骤

1. 官网案例可复现：文档是1.31.0版本，无上述现象
![image](https://user-images.githubusercontent.com/20619652/193231563-98fc9983-dda0-4ff8-817d-3090602157c4.png)

### 预期行为

![image](https://user-images.githubusercontent.com/20619652/193231198-e2586117-b8c7-47d6-bd39-7a7dcc216059.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: 1.32.x、1.33.x、1.34.x

**Comment by NewByVector** [comment]
这个还是需要支持的，应该是我们上次重构给漏了。
