### ISSUE TITLE
vite打包部署后，X6不显示

### ISSUE THREAD

**Issue by chen-i** [antvis/X6#2741]
配置问题，已解决

**Comment by notbucai** [comment]
配置可以放出来嘛，我也碰到这个问题

**Comment by chen-i** [comment]
> 配置可以放出来嘛，我也碰到这个问题

应该就是vite配置问题，我是把下面的配置改成这样就好了
`'@antv/x6': '@antv/x6/dist/x6.js',`
如果还有问题可以参考[https://github.com/vitejs/vite/issues/3413#issuecomment-1107804641](url)
