### ISSUE TITLE
如何实现边连接节点的边框的任意位置？

### ISSUE THREAD

**Issue by WhySuddenly** [antvis/X6#2754]
### 问题描述

像语雀一样，边箭头拖动到节点的边缘时，边框的任意位置都可连接，不依赖链接桩

![image](https://user-images.githubusercontent.com/22953885/194746801-a0ff78ba-9610-49d1-a648-63e31a4c658c.png)

![image](https://user-images.githubusercontent.com/22953885/194746810-2bc37306-a8ce-48f2-9023-6b394416475a.png)

### 重现链接

none

### 重现步骤

none

### 预期行为

期望边可以连接节点边框的任意位置

### 平台

none

**Comment by NewByVector** [comment]
可以使用 [NodeAnchor](https://x6.antv.vision/zh/docs/api/registry/node-anchor) 来实现，具体参考这个 [demo](https://codesandbox.io/s/lian-jie-dao-ren-yi-wei-zhi-hdd9m7)

**Comment by WhySuddenly** [comment]
谢谢
