### ISSUE TITLE
节点输入10万栈溢出

### ISSUE THREAD

**Issue by wangyonghua** [antvis/X6#2755]
### Describe the bug

https://codesandbox.io/s/t5t374?file=/src/settings.tsx
<Slider
              min={10}
              max={100000}
              step={1}
              value={this.state.count}
              onChange={this.onCountChanged}
            />

使用这个地址修改max参数10万进行测试，依然会栈溢出。

背景：
我们项目有10万节点数据渲染到页面的需求
请问是否可以懒加载或者栈溢出是否可以解决

### Your Example Website or App

https://codesandbox.io/s/t5t374?file=/src/settings.tsx:929-1108

### Steps to Reproduce the Bug or Issue

10万数据

### Expected behavior

10万数据栈溢出报错，是否布局使用了递归

### Screenshots or Videos

![栈溢出](https://user-images.githubusercontent.com/6871558/194751417-9523630e-f8fd-4239-885a-fec86e94fc7b.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by xingxiang1227** [comment]
svg很难达到这个数据量，大数据应该选G6

**Comment by wangyonghua** [comment]
请问有懒加载方式吗？一次性不加载那么多？

**Comment by xingxiang1227** [comment]
> 请问有懒加载方式吗？一次性不加载那么多？

我估计没有，只要你全渲染到页面肯定会卡，svg属于dom操作，正常也就支持个1000多节点，所以选型很重要，大数据首选canvas绘图

**Comment by wangyonghua** [comment]
感谢，我看看g6

**Comment by lloydzhou** [comment]
也可以参考一下这个issue: https://github.com/antvis/X6/issues/2513

**Comment by NewByVector** [comment]
10w 节点如果使用 x6 的话，可以使用可视区域渲染的方案，参考这个 [demo](https://x6.antv.vision/zh/docs/api/graph/view/#checkview)，这个会在 2.0 版本默认支持。

**Comment by NewByVector** [comment]
X6 2.0 已经支持虚拟渲染了。
