### ISSUE TITLE
manhattan 路由没有避开节点

### ISSUE THREAD

**Issue by itwmike** [antvis/X6#2766]
### Describe the bug

![image](https://user-images.githubusercontent.com/6613191/194986697-b84ea370-4574-432a-9cd6-5e2f9f362c81.png)
实际业务场景
![image](https://user-images.githubusercontent.com/6613191/194986784-ebd0ad6f-92c7-4e48-9aa4-6e65a137cef7.png)

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Screenshots or Videos

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
无

**Comment by NewByVector** [comment]
有可用复现的 demo 看下吗，可以使用这个[模板](https://codesandbox.io/s/que-xian-mo-ban-wchooy?file=/src/App.tsx)复现问题。

**Comment by itwmike** [comment]
你们的API示例里就能复现，拖到我图里的位置就复现了。
https://antv-x6.gitee.io/zh/docs/api/registry/router

**Comment by NewByVector** [comment]
这个是因为设定了 `startDirections: ['top'], 出发点只能是上方，但是 `padding` 配置默认是 `20`，因为上方距离节点 obstacle 太近，没办法做到，所以 manhantan 路由被降级到 orth 路由了。

**Comment by NewByVector** [comment]
你可以将路由配置 padding 缩小一点看下效果。
