### ISSUE TITLE
ForceLayout（力引导布局）下如果源数据中edges的target在nodes中找不到，会导致绘图失败，但没有异常捕获或者异常过滤处理

### ISSUE THREAD

**Issue by wufang95** [antvis/X6#2769]
### 问题描述

ForceLayout（力引导布局）下如果源数据中edges的target在nodes中找不到，会导致绘图失败，但没有异常捕获或者异常过滤处理
参考官网示例，如果将
/....
edges: [
    { source: 'node0', target: 'node1' },
    { source: 'node0', target: 'node2' },
];
.../
修改为：
/...
edges: [
    { source: 'node0', target: 'node1' },
    { source: 'node0', target: 'node2dd' },
];
.../
这样无效的target会导致程序内部某些处理失败并且没有抛出异常
由于没有ForceLayout的相关文档，并且在实际业务中数据生成不会完全符合程序要求数据格式，所以在这种情况下能否添加异常捕获并抛出呢？
感谢~

### 重现链接

https://x6.antv.vision/zh/examples/layout/general#force

### 重现步骤

1.进入页面
2.将
/....
edges: [
    { source: 'node0', target: 'node1' },
    { source: 'node0', target: 'node2' },
];
.../
修改为：
/...
edges: [
    { source: 'node0', target: 'node1' },
    { source: 'node0', target: 'node2dd' },
];
.../

### 预期行为

希望对于这样异常的数据能有异常捕获并抛出以便于问题调试，在实际业务中上千上万条数据不可能由人工完全保证数据正常。

### 平台

网页浏览器: [Google Chrome, Firefox]

**Comment by NewByVector** [comment]
你好，这个在 [antv/layout](https://github.com/antvis/layout) 中抛出异常更合理。

**Comment by wufang95** [comment]
> 你好，这个在 [antv/layout](https://github.com/antvis/layout) 中抛出异常更合理。

不是很明白，是建议我使用G6的ForceLayout布局吗？

**Comment by NewByVector** [comment]
X6 和 G6 共用的是同一个布局库 @antv/layout，这个错误应该从 layout 库中抛出来更合理，可以给 layout 提一个 issue。

**Comment by wufang95** [comment]
> X6 和 G6 共用的是同一个布局库 @antv/layout，这个错误应该从 layout 库中抛出来更合理，可以给 layout 提一个 issue。

嗷，好的
