### ISSUE TITLE
Overlapping edges labels hidden

### ISSUE THREAD

**Issue by harshaktg** [antvis/X6#2770]
### Describe the bug

When there are two edges in the graph, when two overlaps each other and both of them has labels, the edge which is last added, only that label is visible

### Your Example Website or App

https://codesandbox.io/s/youthful-bash-3oqdm0?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1. Visit the sandbox, the bug is visible

### Expected behavior

As a user, I need to see both the labels when the edges overlap. Or atleast have an option to control the opacity and make both visible.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
you can set text area fill attr as transparent,like this:
```ts
graph.addEdge({
  source: rect2,
  target: rect1,
  label: "world",
  attrs: {
    rect: {
      fill: 'transparent'
    }
  }
});
```
