### ISSUE TITLE
Safari 下连线有误差

### ISSUE THREAD

**Issue by slc3a2** [antvis/X6#2773]
### Describe the bug

Safari 

<img src="https://s2.loli.net/2022/10/14/9v2M36GpWEKFXJ4.png" width=300  align=center />  

Chrome 

<img src="https://s2.loli.net/2022/10/14/LGBlhESoQdNRM8T.png" width=300 align=center />  

可以看到，两个节点连接，`Safari`的连线没有准确在预期位置上。`Chrome`上没有这个问题

### Your Example Website or App

https://codesandbox.io/s/x6-pai-edge-nq3hl?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

 打开`codesandbox`地址即可

### Expected behavior

 预期：可以准确连接两个节点

### Platform

- OS: MacBook Pro Big Sur 11.6.5
- browser: 
   - Chrome 105.0.5195.125 (x86_64)
   - Safari 15.5 (16613.2.5, 16613)

**Comment by slc3a2** [comment]
用 Safari 打开官网下 react 渲染链接桩最下面的 `Hello` 示例也会有这个问题：

https://x6.antv.vision/zh/docs/tutorial/advanced/react#渲染链接桩

**Comment by NewByVector** [comment]
safari 下面确实连接位置有偏差，这是由于浏览器兼容性问题导致的，而且无法从 x6 中抹平这层差别，所以推荐的解决方式是在代码中做个判断，参考 https://github.com/antvis/X6/blob/%40antv/x6%401.20.0/sites/x6-sites/examples/showcase/practices/demo/algo-flow.tsx#L128

**Comment by Damon99999** [comment]
> 

这个链接失效了
