### ISSUE TITLE
开启选择，存在部分区域重叠的两个节点，选中节点的问题

### ISSUE THREAD

**Issue by lizige** [antvis/X6#2774]
### 问题描述

开启选择，存在部分区域重叠的两个节点，先点选下面的节点，再点选上面节点与下面节点重叠的区域，还是选中的是下面的节点。

### 重现链接

无

### 重现步骤

1.graph配置开启选择
2.画布上存在两个节点，两个节点之间存在重叠区域。先点击下面的节点选中状态。
3.点击上面的节点与下面节点重叠的区域后，还是下面的节点处于选中状态。

### 预期行为

预期是点击重叠区域，应该是选中的是处于上面的节点。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
1

### 屏幕截图或视频（可选）

![1665735042151](https://user-images.githubusercontent.com/9366426/195796929-ff47c575-0157-4ec1-b5f3-af2772fd013f.png)

### 补充说明（可选）

1

**Comment by NewByVector** [comment]
[pointerEvents](https://x6.antv.vision/zh/docs/tutorial/basic/selection#pointerevents) 应该能解决你的问题。
