### ISSUE TITLE
自定义vue节点，firfox，缩小画布时border消失

### ISSUE THREAD

**Issue by lanseliuyiya** [antvis/X6#2775]
### 问题描述

自定义vue节点，firfox，缩小画布时border消失

### 重现链接

1

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [ Firefox]
- X6 版本: [1.32.7 ... ]

### 屏幕截图或视频（可选）

1

### 补充说明（可选）

1

**Comment by NewByVector** [comment]
能否给个可以复现的 demo ？

**Comment by lanseliuyiya** [comment]
demo地址：[https://github.com/lanseliuyiya/demo-X6.git](url)

**Comment by lanseliuyiya** [comment]
已增加demo

 

发件人: ***@***.*** ***@***.***> 代表 vector
发送时间: 2022年10月18日 7:55
收件人: antvis/X6 ***@***.***>
抄送: Lady-Marmala ***@***.***>; Mention ***@***.***>
主题: Re: [antvis/X6] 自定义vue节点，firfox，缩小画布时border消失 (Issue #2775)

 

能否给个可以复现的 demo ？

**Comment by lanseliuyiya** [comment]
https://github.com/lanseliuyiya/demo-X6.git

 

发件人: ***@***.*** ***@***.***> 代表 vector
发送时间: 2022年10月18日 7:55
收件人: antvis/X6 ***@***.***>
抄送: Lady-Marmala ***@***.***>; Mention ***@***.***>
主题: Re: [antvis/X6] 自定义vue节点，firfox，缩小画布时border消失 (Issue #2775)

 

能否给个可以复现的 demo ？

**Comment by lanseliuyiya** [comment]
demo: [https://github.com/lanseliuyiya/demo-X6.git](url)

**Comment by NewByVector** [comment]
不好意思这么晚才来看你的问题，不过你给的例子跑不起来，如果还有问题并且有可以跑的例子，请重新提一个新的 issue。
