### ISSUE TITLE
segments位置错乱

### ISSUE THREAD

**Issue by WhySuddenly** [antvis/X6#2786]
### 问题描述

在 [如何实现边连接节点的边框的任意位置](https://github.com/antvis/X6/issues/2754) 的demo基础上，边加了 segments后，发现segments不显示，看代码发现位置错乱，且display始终为“none”

![image](https://user-images.githubusercontent.com/22953885/196592710-c2ce747e-ebc8-4ede-981c-62e45f263b4d.png)
![image](https://user-images.githubusercontent.com/22953885/196592752-a33631da-5778-418a-a04d-b9b164d3e724.png)

### 重现链接

https://codesandbox.io/s/lian-jie-dao-ren-yi-wei-zhi-forked-dcjvug?file=/src/App.tsx

### 重现步骤

控制台查看segments 元素的属性

### 预期行为

期望segments 能正确显示在边上

### 平台

none

**Comment by NewByVector** [comment]
因为你是自由锚点，两个锚点之间很难是一条直线，你可以设置 precision 大一点，这样在不是直线的情况下也能出现 segments 工具。
