### ISSUE TITLE
请问如何修改所有cell的ID生成方式？

### ISSUE THREAD

**Issue by taoxiongfeng** [antvis/X6#2789]
### 功能描述

请问如何修改所有cell的ID生成方式？我想修改包括边 节点 连接线 连接桩等ID，简单点就是如何替换全局的UUID的生成方式 

### 期望解决方案

请问如何修改所有cell的ID生成方式？我想修改包括边 节点 连接线 连接桩等ID，简单点就是如何替换全局的UUID的生成方式

**Comment by lloydzhou** [comment]
我感觉没有必要做这个事情：

1. 通常业务上面会有一些自己的规则，但是大多数时候，id其实是由后端生成的。拿到后端数据之后再使用业务生成好的id去生成节点就好了。
2. 就算是通过页面交互生成节点和边，也是可以通过一些回调来生成节点的。
3. 例如dnd里面拖拽的时候，options.validateNode可以异步返回，可以在这个回调里面调接口生成节点，然后返回一个Promise.resolve(false)（这里返回false会丢弃拖动过程中创建的节点）然后手动创建一个按照自己规则生成id的节点。
4. 同样的，针对创建边，也有一个validateEdge函数，（不过这个函数不能返回Promise）这个函数返回false，会丢弃拖动的时候创建的那一条边，然后你自己调用createEdge用自己的规则生成边就可以了。

**Comment by damnright** [comment]
创建时手动赋予自己生成的id可以吗

**Comment by NewByVector** [comment]
创建节点的时候是可以通过配置 id 属性自定义 id 的，如果是 dnd 拖拽场景，请参考 [常见问题](http://x6.antv.antgroup.com/tutorial/plugins/dnd#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
