### ISSUE TITLE
两个自定义节点的锚点，不能拖拽到同一水平线上，导致边是歪的。

### ISSUE THREAD

**Issue by zhuhaoming8080** [antvis/X6#2792]
### 问题描述

两个自定义节点的锚点，不能拖拽到同一水平线上，导致边是歪的。

### 重现链接

https://codesandbox.io/s/inspiring-brown-cz5ekl?file=/src/App.vue

### 重现步骤

1、进入页面如图，从第一个节点的右侧锚点引出边，链接向第二个节点的左上侧锚点。
2、拖拽右侧节点使边保持为一条直线。边的结束点始终是歪的。

不知道是哪里的问题麻烦请指教，谢谢

### 预期行为

期望通过拖拽的方式使两节点之间的边连成水平直线

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/114203111/197154389-07c09f93-bfaa-4714-bb6a-995236c78e6a.png)

### 补充说明（可选）

demo 图片没有显示不影响问题复现。如果进入看不到demo，麻烦刷新一下试试。谢谢

**Comment by lloydzhou** [comment]
我看了看，你配置的port group使用了百分比计算位置（这里难免出现浮点数）。
同时grid.size默认是10px起步。
拖动的时候，对不齐是很正常的事情。
我试了试把grid.size配置为1px，就能对齐了。

![image](https://user-images.githubusercontent.com/1826685/197231300-8865d9f4-9754-4e0f-8673-8f40179894b9.png)

**Comment by zhuhaoming8080** [comment]
> 我看了看，你配置的port group使用了百分比计算位置（这里难免出现浮点数）。 同时grid.size默认是10px起步。 拖动的时候，对不齐是很正常的事情。 我试了试把grid.size配置为1px，就能对齐了。
> 
> ![image](https://user-images.githubusercontent.com/1826685/197231300-8865d9f4-9754-4e0f-8673-8f40179894b9.png)

![image](https://user-images.githubusercontent.com/114203111/197444678-884ef67d-e83e-407d-aabf-11f2908bae17.png)

>你好通过提示，改变了grid.size 1px 解决了边拖不直的问题。但好像又出现了上图中的绘制问题。感谢指导，感谢开源。谢谢

**Comment by NewByVector** [comment]
@zhuhaoming8080 如果保持 grid size，其实也可以稍微调整下节点高度，让计算不要出现浮点数，应该能解决你的问题。

**Comment by pfdgithub** [comment]
我遇到了一个类似问题，但解决方案是通过调整“链接桩”位置解决的。

现象如下（点开大图看的比较清晰）：

在编辑模式下，自定义节点（此时高度为X），辅助线和连接线均已对齐。
![image](https://user-images.githubusercontent.com/3262762/201105143-fd225020-2cc2-477e-ab9a-1032c583ab76.png)

但在查看模式下，自定义节点（此时高度为Y），链接线却无法对齐。
开启辅助线后，发现辅助线对节点高度的计算有误，造成连接线无法对齐。
![image](https://user-images.githubusercontent.com/3262762/201105613-3085de17-2b3b-45f0-9a29-117ae5b5a360.png)

经排查，发现对于带有“链接桩”的节点，布局算法对于节点高度的计算，是包含了“链接桩”占用的高度。
一旦两端的节点携带了不同数量/位置的“链接桩”，就会造成计算的高度不一致，进而造成连接线无法对齐。
![image](https://user-images.githubusercontent.com/3262762/201108074-c9fb3a33-4c58-4c6d-a5e6-55a450543c5b.png)
![image](https://user-images.githubusercontent.com/3262762/201108204-72900732-644a-4d4c-87a1-43637e67c321.png)
![image](https://user-images.githubusercontent.com/3262762/201108359-2e0e512e-b12c-458c-9def-9440b2c061af.png)
![image](https://user-images.githubusercontent.com/3262762/201108489-fbfb79cd-15ce-4bc6-a7e5-d57b72cecdfc.png)

解决方案有点麻烦，需要调整各“链接桩”的位置，将其向内偏移，避免撑开节点高度。

参考文档：
[Node](https://x6.antv.vision/zh/docs/api/model/node#ports)
[PortLayout](https://x6.antv.vision/zh/docs/api/registry/port-layout#left-right-top-bottom)

最终效果如下所示：
![image](https://user-images.githubusercontent.com/3262762/201110356-0131e3bf-ae65-45c5-8551-a5d87a237eec.png)

**Comment by pfdgithub** [comment]
@NewByVector 是否可以考虑支持一下，在计算节点高度时，忽略“链接桩”高度？

**Comment by wozien** [comment]
> @zhuhaoming8080 如果保持 grid size，其实也可以稍微调整下节点高度，让计算不要出现浮点数，应该能解决你的问题。

请问下要调到多少？怎么判断呢

**Comment by cangsnage** [comment]
> @NewByVector 是否可以考虑支持一下，在计算节点高度时，忽略“链接桩”高度？

楼主要调到多少，具体怎么计算呢？有没有开源的源码供参考
