### ISSUE TITLE
downloadDataUri时引起页面样式闪动问题

### ISSUE THREAD

**Issue by zhangxilong-43** [antvis/X6#2793]
### 问题描述

1、向官网实例的代码中插入以下代码：
setTimeout(() => {
  graph.toPNG((dataUri: string) => {
    DataUri.downloadDataUri(dataUri, 'chart.png')
  })
}, 3000)
2、3秒后观察发现此函数的调用会引起页面样式的闪动

### 重现链接

https://x6.antv.vision/zh/examples/showcase/practices#dag

### 重现步骤

1、进入页面
2、在该页面调用DataUri.downloadDataUri(); 或者复制下列代码：
setTimeout(() => {
  graph.toPNG((dataUri: string) => {
    DataUri.downloadDataUri(dataUri, 'chart.png')
  })
}, 3000) 
3、3秒后观察，页面样式会闪动

### 预期行为

预期：所述问题不存在

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome, Edge]
- X6 版本: [1.34.2]

**Comment by lloydzhou** [comment]
和这个issue是一样的问题
https://github.com/antvis/X6/issues/2061

**Comment by lloydzhou** [comment]
https://github.com/antvis/X6/issues/474

**Comment by NewByVector** [comment]
与 https://github.com/antvis/X6/issues/2984 重复。

**Comment by NewByVector** [comment]
@damnright 期待你的 PR 呀。

**Comment by favorite58** [comment]
将 copyStyle 设置为 false并不能解决大部分场景，流程节点中样式会出现丢失，还有其他的可行方案解决该问题吗？
