### ISSUE TITLE
开启snapline，多个节点同时移动的时候，节点位置偏移

### ISSUE THREAD

**Issue by struggleRoue** [antvis/X6#2794]
### Describe the bug

开启snapline：true
选中读逻辑和逻辑回归两个节点
同时移动两个节点
两节点的相对位置发生偏移

https://antv-x6.gitee.io/zh/examples/showcase/practices#dag

### Your Example Website or App

https://antv-x6.gitee.io/zh/examples/showcase/practices#dag

### Steps to Reproduce the Bug or Issue

1.  进入页面
2. 选中读逻辑和逻辑回归两个节点
3. 同时移动两个节点

### Expected behavior

我期待移动节点的时候位置不偏移

### Platform

- OS: macOS
- Browser: Chrome
- Version: lastest

**Comment by struggleRoue** [comment]
猜一下你们是不是做了对齐 的辅助能力（自动偏移帮我们对齐）？

**Comment by struggleRoue** [comment]
> 

能帮忙介绍下问题产生原因吗？
感谢

**Comment by NewByVector** [comment]
@struggleRoue snapline 中移动节点与 selection 中监听节点移动来同时移动多个框选节点，这两个地方有冲突。
