### ISSUE TITLE
节点复制的时候对应连接桩的ID不会发生变换

### ISSUE THREAD

**Issue by struggleRoue** [antvis/X6#2795]
### Describe the bug

节点复制的时候
粘贴之后对应连接桩的ID不会发生变换

### Your Example Website or App

https://antv-x6.gitee.io/zh/examples/showcase/practices#flowchart

### Steps to Reproduce the Bug or Issue

1. 进入页面
2. 拖动 ‘过程’ 节点到画布中
3. 复制节点
4. 粘贴
5. 去DOM中查看对应Port的ID

### Expected behavior

粘贴时候用户可以自定义节点ID和对应连接桩ID

### Screenshots or Videos

![Uploading image.png…]()

### Platform

- OS: macOS
- Browser: Chrome
- Version: lastest

**Comment by NewByVector** [comment]
你好，这个功能暂时不支持，我们已经加入到开发计划中。

**Comment by oyal** [comment]
> 你好，这个功能暂时不支持，我们已经加入到开发计划中。

你好，粘贴选项的 `nodeProps` 只能写额外的属性吗，我的连接桩是动态添加的，我想粘贴后返回默认连接桩，事实上却把连接桩都拷贝了（同时连接桩id也相同）
```js
graph.paste({
  offset: 32,
  nodeProps: {
    ports: {
      items: [{group: 'group1'}, {group: 'group2'}]
    }
  }
})
```
[![xoqIF1.png](https://s1.ax1x.com/2022/10/31/xoqIF1.png)](https://imgse.com/i/xoqIF1)

**Comment by NewByVector** [comment]
@oyal 拷贝内容是拷贝时候节点的状态，动态添加的连接桩也会被拷贝。
