### ISSUE TITLE
使用Port后, 边的 manhattan router 失去规避节点的功能

### ISSUE THREAD

**Issue by wangpengfeido** [antvis/X6#2796]
### 问题描述

使用Port后, 边的 manhattan router 失去规避节点的功能

下方Demo修改自官方示例。添加了Port。**已去掉`startDirections`和`endDirections`选项。**

https://codesandbox.io/s/stoic-raman-5qdjqv?file=/src/app.tsx

<img width="438" alt="image" src="https://user-images.githubusercontent.com/20836277/197495041-c5401c3c-58cc-4711-8d65-b6e401d5bb05.png">

<img width="782" alt="image" src="https://user-images.githubusercontent.com/20836277/197494757-49dae0dc-0b59-41fb-9c91-f84cdf305dd3.png">

### 重现链接

https://codesandbox.io/s/stoic-raman-5qdjqv?file=/src/app.tsx

### 重现步骤

打开Demo页面，拖动obstacle节点到边上。

### 预期行为

边可以自动避让节点

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 1.34.5

**Comment by NewByVector** [comment]
你这个场景，因为连接桩外面有个节点，无法使用 manhattan 路由，你可以使用[配置](https://x6.antv.vision/zh/docs/api/registry/router#manhattan) 排除掉外面的节点。因为这个问题经常出现，所以在代码中加了 warn 提示，方便定位问题。https://github.com/antvis/X6/pull/2799

**Comment by wangpengfeido** [comment]
> 你这个场景，因为连接桩外面有个节点，无法使用 manhattan 路由，你可以使用[配置](https://x6.antv.vision/zh/docs/api/registry/router#manhattan) 排除掉外面的节点。因为这个问题经常出现，所以在代码中加了 warn 提示，方便定位问题。#2799

了解了，感谢
