### ISSUE TITLE
segments位置错乱

### ISSUE THREAD

**Issue by WhySuddenly** [antvis/X6#2800]
### 问题描述

在 https://github.com/antvis/X6/issues/2754 的demo基础上，边加了 segments后，发现segments不显示，看代码发现位置错乱，且display始终为“none”
![image](https://user-images.githubusercontent.com/22953885/197665707-53d3cb27-5224-4597-b73f-788c263d704b.png)
![image](https://user-images.githubusercontent.com/22953885/197665720-8b027b47-14c1-4109-b74b-01028e16be6e.png)

### 重现链接

https://codesandbox.io/s/lian-jie-dao-ren-yi-wei-zhi-forked-dcjvug?file=/src/App.tsx

### 重现步骤

控制台查看segments 元素的属性

### 预期行为

期望segments 能正确显示在边上

### 平台

none

**Comment by NewByVector** [comment]
和 https://github.com/antvis/X6/issues/2786 重复。
