### ISSUE TITLE
node.insertPort方法执行报错

### ISSUE THREAD

**Issue by wb-wenbei** [antvis/X6#2801]
### Describe the bug

运行node.insertPort方法时报错：Duplicitied port id.
v1和v2版本都有这个bug

### Your Example Website or App

https://codesandbox.io/s/keen-gauss-gr7tto?file=/index.ts

### Steps to Reproduce the Bug or Issue

1.打开示例链接：https://codesandbox.io/s/keen-gauss-gr7tto?file=/index.ts
2.点击add按钮，可以正常添加一个port
3.点击insert按钮，报错

### Expected behavior

点击insert按钮正常添加port

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [1.34.5]

**Comment by NewByVector** [comment]
你好，你给的复现链接并没有使用 insertPort 方法，是链接给错了？

**Comment by wb-wenbei** [comment]
> 你好，你给的复现链接并没有使用 insertPort 方法，是链接给错了？

https://codesandbox.io/s/keen-gauss-gr7tto?file=/index.ts

**Comment by NewByVector** [comment]
@wb-wenbei insertPort 需要给定一个唯一的 portId。这个我会在文档上标记一下。
