### ISSUE TITLE
是否可以支持通过点击其它元素间接触发链接桩的创建连线

### ISSUE THREAD

**Issue by helloworldmygithub** [antvis/X6#2809]
### 功能描述

https://user-images.githubusercontent.com/37649395/198204952-b90dca90-1933-4fa0-b292-343496f6701d.mp4

希望能够达到类似这样的效果，如果直接使用链接桩当箭头的话，连线的起始位置会和图元有一定距离，不太好看

### 期望解决方案

能否暴露出一个可以触发连线的api,比如startLink的这种方法呢

**Comment by helloworldmygithub** [comment]
又或者说，现在有没有一个方法，可以使手动触发连线时，source不是port而是cell本身呢

我知道由于图元需要mousedown支持拖拽，所以不能同时让图元mousedown支持连线。因此才有了设置magnet的链接桩

那是不是可以不使用链接桩在某个悬浮的图标上点击同样触发连线呢）

**Comment by xiaojueji** [comment]
有相同的需求+1

**Comment by lloydzhou** [comment]
可以参考这个issue里面的讨论，或许有帮助　https://github.com/antvis/X6/issues/2317　至于点击的是节点，还是port，又或者是其他的tool，应该关系都不大。

**Comment by NewByVector** [comment]
只要设置 `magnet` 属性的元素都可以触发连线。
