### ISSUE TITLE
如何用vue渲染连接桩实现tooltip

### ISSUE THREAD

**Issue by freshGi** [antvis/X6#2811]
### 问题描述

如何用vue渲染连接桩实现tooltip，鼠标悬浮连接桩是实现tooltip显示。官网中只有react的示例。之前的issues中提到过解决办法，但是有报错，没有继续解决。

### 重现链接

https://github.com/antvis/X6/issues/864

### 重现步骤

>
![Snipaste_2022-10-27_16-51-21](https://user-images.githubusercontent.com/34728297/198239170-bf780bdd-52aa-4105-8288-0208dd2af861.png)

### 预期行为

可以解决vue渲染问题，或者是否有svg方式的示例？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by lloydzhou** [comment]
vue使用问题，建议去vue社区问。

vue初始化的时候 el需要是一个dom元素，你写的那个需要放到template里面

**Comment by chl1860** [comment]
according to official sample, in fact an html elem is just needed.  no matter what ui lib is used. so with VUE you can do it like this
<img width="786" alt="image" src="https://github.com/antvis/X6/assets/7414187/566f2b5d-312e-4597-abae-ef67ea66dd70">
