### ISSUE TITLE
label重叠

### ISSUE THREAD

**Issue by liuyao552** [antvis/X6#2812]
### 问题描述

两条边上的label会重叠

### 重现链接

无

### 重现步骤

无

### 预期行为

希望不重叠，或者有获取label坐标的api

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![0D5EE89E-742B-4521-AD38-4C73A42094EB](https://user-images.githubusercontent.com/23089192/198556550-4d436acd-1221-49b9-8fcd-28e79ab51029.png)

**Comment by NewByVector** [comment]
这个暂时还没有好的方法做到 label 之间避免重叠，有好的方式请给我们提 PR。
