### ISSUE TITLE
求助，双指缩放与画布拖拽有冲突，怎么办？

### ISSUE THREAD

**Issue by gitofzach** [antvis/X6#2813]
### 问题描述

issue产生的背景：x6项目是一个平台web项目，有一个app项目通过webView访问该平台web项目。平台web项目为了让app的用户用户体验更好，增加了双指缩放画布大小的功能。但实际效果是，app上使用双指缩放时与画布本身的拖拽功能产生冲突。具体可以看下我上传的视频。

### 重现链接

无

### 重现步骤

1、将x6的web项目做成响应式，并在画布容器上绑定touchstart、 touchend、 touchmove事件（利用这3个事件制作双指缩放功能），画布本身的可拖拽选项为打开状态；
2、手机端通过webView访问web项目，并使用双指缩放功能

### 预期行为

我期望看到，在移动端，利用双指进行缩放的时候不会与拖拽功能产生冲突

### 平台

- 操作系统: [安卓，ios]
- X6 版本: [1.34.5 ... ]

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/75466727/198960446-635444bf-8afa-415d-af4d-297bfae4b0a6.mp4

**Comment by curiousbabyMz** [comment]
如果只是浏览，直接用viewport scalable

**Comment by NewByVector** [comment]
在 2.x 版本中已经将画布设置为无法双指缩放。https://github.com/antvis/X6/blob/master/packages/x6/src/style/index.less#L9

**Comment by TANGYICONG** [comment]
请问问题解决了吗？我也遇到了类似问题

**Comment by NewByVector** [comment]
@TANGYICONG 将画布设置为不可缩放
```css
.x6-graph {
  touch-action: none;
}
```

**Comment by cooljser** [comment]
+1，求解

**Comment by cooljser** [comment]
我解决了，自己手动实现了画布的缩放和组件的拖动

**Comment by yeyaolong** [comment]
> 我解决了，自己手动实现了画布的缩放和组件的拖动

老哥有demo吗，怎么实现的，页面加按钮吗？

**Comment by yanjiez** [comment]
为什么X6不做移动端的适配呢？
自己手动的加event的话，如何判断是否pan的是组件，或者是连接桩？

**Comment by yanjiez** [comment]
> @TANGYICONG 将画布设置为不可缩放
> 
> ```css
> .x6-graph {
>   touch-action: none;
> }
> ```

@NewByVector 设为不可缩放的原因是什么？底层有什么冲突么？如果硬要加这双指缩放的功能呢？
