### ISSUE TITLE
求助，x6web项目在移动端拖拽时有残影，怎么办？

### ISSUE THREAD

**Issue by gitofzach** [antvis/X6#2814]
### 问题描述

issue产生的背景：x6项目是一个平台web项目（其中节点是用的vue框架写的），有一个app项目通过webView访问该平台web项目。当在app端拖拽画布时，产生残影，残影只在最右侧产生，具体可以看下图片。

Ps：同一款app在访问x6项目时，残影的情况只在ios上发生，安卓端正常。

### 重现链接

无

### 重现步骤

1、将x6的web项目做成响应式，画布本身的可拖拽选项为打开状态；
2、手机端通过webView访问web项目，并左右拖拽画布

### 预期行为

我期望看到拖拽画布，没有残影产生

### 平台

- 操作系统: [ios]
- 网页浏览器: [Safari]
- X6 版本: [1.34.5 ... ]

### 屏幕截图或视频（可选）

![file-read-9530](https://user-images.githubusercontent.com/75466727/198962569-e1b83e64-0ed0-4d81-90b9-1a5e694ce0e1.png)

**Comment by lloydzhou** [comment]
我映像中g6使用canvas绘图的时候，拖动的时候，有的时候计算重新渲染的“脏矩阵”可能导致残影。
x6使用svg，这个浏览器原生支持的矢量图形，应该不会出现残影。

**Comment by gitofzach** [comment]
> 使用
事实上这种情况确实出现了。目前我并没有能找到原因，同一台mac，用谷歌浏览器没有残影，用safari就有。

**Comment by gitofzach** [comment]
@lloydzhou 事实上这种情况确实出现了。目前我并没有能找到原因，同一台mac，用谷歌浏览器没有残影，用safari就有。

**Comment by NewByVector** [comment]
@gitofzach 是否内容超过节点宽高  https://github.com/antvis/X6/issues/751

**Comment by gitofzach** [comment]
@NewByVector 确实存在这种情况。 当我将内容宽高调整低于节点宽高，解决了部分节点的残影问题。但是那个后面带有层叠效果的节点，层叠效果是用css的box-shadow写的，残影还是存在（宽高已经确保小予等于节点宽高），我猜测是box-shadow倒置的还有残影。
