### ISSUE TITLE
节点旋转后bbox没有变化

### ISSUE THREAD

**Issue by damnright** [antvis/X6#2817]
### 问题描述

节点旋转后bbox没有变化，导致embed、框选元素等功能出现问题

### 重现链接

节点旋转后bbox没有变化，导致embed、框选元素等功能出现问题

### 重现步骤

节点旋转后bbox没有变化，导致embed、框选元素等功能出现问题

### 预期行为

节点旋转后bbox相应变化

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by light-years-run** [comment]
问题解决了吗？ 我也遇到这个问题了

**Comment by hexianggui** [comment]
我也是

**Comment by damnright** [comment]
> 我也是

解决了
