### ISSUE TITLE
addCells方法不存在

### ISSUE THREAD

**Issue by damnright** [antvis/X6#2823]
### 问题描述

addCells方法不存在，调用报错

### 重现链接

addCells方法不存在，调用报错

### 重现步骤

addCells方法不存在，调用报错

### 预期行为

addCells方法不存在，调用报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
只有 addCell 方法，可以传数组。
