### ISSUE TITLE
node_modules/@antv/x6/src/view/tool.ts:424:36: ERROR: Cannot use "this" here:

### ISSUE THREAD

**Issue by ZephyrTan** [antvis/X6#2824]
你的 issue没有给出可以定位问题的信息，提供一些有用的信息？

_Originally posted by @NewByVector in https://github.com/antvis/X6/issues/2406#issuecomment-1193033930_
      使用vite直接创建项目，然后引入x6搭建页面就会提示无法使用 this

**Comment by lloydzhou** [comment]
搜索了一下x6源码里面定义函数的位置带有this的地方
```
grep -E "(protected|public)" -Rn | grep this
```
![image](https://user-images.githubusercontent.com/1826685/199871130-9cfff77f-942a-48a9-843d-27c49af3c8cb.png)


使用protected定义成员函数的时候，函数的默认值直接写`this.container`看起来这个写法不太规范！

**Comment by Tangchony** [comment]
请问这个commit会提交到正式版吗?我也遇到了相同的问题

**Comment by NewByVector** [comment]
@Tangchony 不好意思，上次代码只合并到了 v2 版本，我已经在 v1 版本中发布了新的版本 1.34.11，修复了该问题，请更新一下。
