### ISSUE TITLE
graph's position was not reset when dispose was performed

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#285]
当执行scroller的dispose方法时，容器的位置能保持住

https://codesandbox.io/s/x6-scroller-753on?file=/src/App.js

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@NewByVector 测试一下 v1.0.1 中是否还有这个问题，我在这个版本中修复了一些 `dispose` 相关的行为

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/pull/342
