### ISSUE TITLE
快捷键绑定问题

### ISSUE THREAD

**Issue by ajesses** [antvis/X6#2856]
### 问题描述

问题1：当绑定快捷键 `ctrl + a` 时，功能为选中所有节点时，会选中图区域之外的所有元素（当前页面所有元素）
问题2：当绑定快捷键 `ctrl + s` 时，功能为暂存所有节点时，会弹出浏览器弹窗

### 重现链接

https://codesandbox.io/s/m9fzwi

### 重现步骤

1. 进入示例页面（如果 codesandbox 打不开，可查看官方示例 [https://x6.antv.vision/zh/examples/showcase/practices#flowchart](https://x6.antv.vision/zh/examples/showcase/practices#flowchart) ）
2. 按快捷键 ctrl + a 或者 meta + a
3. 会把页面所有元素都选中

### 预期行为

事件只触发在图区域内，不冒泡到外层

### 平台
- 网页浏览器: Google Chrome
- X6 版本: 1.34.0
- vscode

- 操作系统: Windows
- 网页浏览器: Google Chrome
- X6 版本: 1.34.0
- vscode

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/20083799/200487178-3a2346c5-732b-4781-ab9a-11c3473513b5.png)
![image](https://user-images.githubusercontent.com/20083799/200494794-960e103a-9618-469c-ba77-92e6714eb69d.png)
![image](https://user-images.githubusercontent.com/20083799/200494841-d6c9de8e-4d66-4eb4-b7db-9f2cee58ea61.png)

**Comment by damnright** [comment]
这个问题应该和X6没有关系

**Comment by alienzhangyw** [comment]
就像你图中ctrl+z那样回调最后加个return false就行了

**Comment by ajesses** [comment]
> 就像你图中ctrl+z那样回调最后加个return false就行了

确实可以，谢谢
