### ISSUE TITLE
Node如何不通过链接桩引出边，直接通过Node引出

### ISSUE THREAD

**Issue by zxkf-newWorld** [antvis/X6#2862]
### 功能描述

Node如何不通过链接桩引出边，直接通过Node引出

### 期望解决方案

由鼠标直接通过Node拖出线

**Comment by jiubanqingchen** [comment]
我貌似做过和你这个需求相同的功能 我的做法是每个node节点都有一个连接桩 ，连接桩大小、位置和 node 大小、位置保持一致，这样可以实现鼠标移动到node上，可以拖出连接线

**Comment by zxkf-newWorld** [comment]
> 我貌似做过和你这个需求相同的功能 我的做法是每个node节点都有一个连接桩 ，连接桩大小、位置和 node 大小、位置保持一致，

**Comment by zxkf-newWorld** [comment]
> 我貌似做过和你这个需求相同的功能 我的做法是每个node节点都有一个连接桩 ，连接桩大小、位置和 node 大小、位置保持一致，这样可以实现鼠标移动到node上，可以拖出连接线

是可以解决从node拖出连线，
但是业务场景：单击、 双击node均有涉及，这样添加了同node大小的port后，zIndex会高于node自身，会影响到单击和双击节点
，所以还是不能很好的解决

**Comment by Wrong2014** [comment]
const r1 = graph.addNode({
      shape: 'rect',
      width: 70,
      height: 30,
      x: 200,
      y: 50,
      attrs: {
        body: { fill: '#1890ff', stroke: '#1890ff' },
        text: { text: 'box', fill: '#fff', magnet: true },
      },
    }) 试试

**Comment by TLovers** [comment]
> const r1 = graph.addNode({ shape: 'rect', width: 70, height: 30, x: 200, y: 50, attrs: { body: { fill: '#1890ff', stroke: '#1890ff' }, text: { text: 'box', fill: '#fff', magnet: true }, }, }) 试试

这样多条线会重叠在一起
