### ISSUE TITLE
Safari 下自定义node 有定位position 会样式错乱

### ISSUE THREAD

**Issue by yueer12138** [antvis/X6#2863]
### 问题描述

Safari 下自定义node 有定位position：relative / absolute 就会失效 ，导致页面错乱，重现里面可以看到 box 去掉position 属性会没有问题

### 重现链接

https://codesandbox.io/s/practical-fermi-x0b07w?file=/src/App.js

### 重现步骤

1. 进入页面，加载显示错乱
2. 打开css 去掉 divage 的定位熟悉 保存刷新，正常显示

### 预期行为

在自定义节点里面难免会有定位属性，期望就是在safari下能正常显示，现在实际上 自定义的node 节点 具有positon 属性的都会使transform 属性失效

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Safari]
- X6 版本: [1.32.3 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/37522612/201032438-7e4e094d-6b8e-468f-83ff-43fa91868659.png)
![image](https://user-images.githubusercontent.com/37522612/201032536-3e199132-7fb5-4aa7-a65c-9b3c828eeae9.png)

**Comment by NewByVector** [comment]
参考[常见问题1](https://www.yuque.com/antv/x6/be9pfx)。

**Comment by CavinHuang** [comment]
...自定义节点，很多时候会用到positon特别是某些框架组件时，有什么更好的解决方法吗
