### ISSUE TITLE
lib 包中依赖的 lodash-es 换成 lodash/xxx

### ISSUE THREAD

**Issue by tolerance-go** [antvis/X6#2871]
### 问题描述

哈喽，我发现 lib 中依赖的 lodash-es 不是 cjs 规范，我需要额外配置转换，比如使用 jest 的时候，而不是 webpack 打包，希望改为 lodash 统一模块规范，同时我注意到 https://github.com/antvis/X6/pull/101 这个 PR 为了解决全量引入问题，在使用 lodash 下，按需引入建议用 [babel-plugin-import](https://www.npmjs.com/package/babel-plugin-import) 统一处理，减少改动

### 平台

- X6 版本: 1.34.2

**Comment by damnright** [comment]
es是为了tree-shaking吧

**Comment by alienzhangyw** [comment]
> es是为了tree-shaking吧

import XXX from 'lodash/xxx'的方式自动就是了，只导入了用到的函数，其实就不存在tree-shaking的说法了。

**Comment by damnright** [comment]
> > es是为了tree-shaking吧
> 
> import XXX from 'lodash/xxx'的方式自动就是了，只导入了用到的函数，其实就不存在tree-shaking的说法了。

tree-shaking 依赖于 es module
[https://webpack.js.org/guides/tree-shaking/](url)

**Comment by alienzhangyw** [comment]
> > > es是为了tree-shaking吧
> > 
> > 
> > import XXX from 'lodash/xxx'的方式自动就是了，只导入了用到的函数，其实就不存在tree-shaking的说法了。
> 
> tree-shaking 依赖于 es module [https://webpack.js.org/guides/tree-shaking/](url) 同时引入多个时 esm更方便： import {chunk, join, sortBy} from 'lodash-es'; cjs就要每个都单独一行引用，太麻烦

难道你们写代码的时候import语句都是手动写的吗🤣？我都是用到的时候tab一下vscode自动导入了

**Comment by lijing666** [comment]
> > > > es是为了tree-shaking吧
> > > 
> > > 
> > > import XXX from 'lodash/xxx'的方式自动就是了，只导入了用到的函数，其实就不存在tree-shaking的说法了。
> > 
> > 
> > tree-shaking 依赖于 es module [https://webpack.js.org/guides/tree-shaking/](url) 同时引入多个时 esm更方便： import {chunk, join, sortBy} from 'lodash-es'; cjs就要每个都单独一行引用，太麻烦
> 
> 难道你们写代码的时候import语句都是手动写的吗🤣？我都是用到的时候tab一下vscode自动导入了

其实他用lodash-es有个好处就是我框架自带了lodash完整版，这样我可以配置alias，lodash-es为lodash即可，但是如果用lodash/xx的方式就会没那么好处理

**Comment by NewByVector** [comment]
确实，lodash-es 配合 webpack 才能发挥优势，其他场景下好像没有多大必要。

**Comment by Oscar-ren** [comment]
目前lib目录里是require('lodash-es')，导致无法按需加载，nextjs最新版本会报错；可以的话换成 lodash/xxx 的形式比较好

**Comment by NewByVector** [comment]
@Oscar-ren 欢迎提 PR。
