### ISSUE TITLE
selecting 点选和框选快捷键不一样

### ISSUE THREAD

**Issue by struggleRoue** [antvis/X6#2879]
### Describe the bug

selecting 的修饰键只能框选使用
点选只能按着command进行多节点的点选

### Your Example Website or App

https://codesandbox.io/s/k3f7cp?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1. 进页面
2. 选择快捷键
3. 按着快捷键框选
4. 按着快捷键点选
5. 框选生效，点选不生效

### Expected behavior

期待框选和点选使用的快捷键一样

### Platform

- OS:macOS
- Browser:chrome
- Version: last

**Comment by NewByVector** [comment]
有两个配置，分别对应点选和框选的快捷键，multipleSelectionModifiers 和 multiple。
