### ISSUE TITLE
minimap有个bug！

### ISSUE THREAD

**Issue by Xjinzz** [antvis/X6#2889]
### 问题描述

问题出现背景是，我在vue2中使用【用vue渲染node】，用到on('change:*', cb)时候，发现cb执行了两次，进而发现mounted执行了两次

_最终确定问题为以下配置项_
```
minimap: {
      enabled: true
},
```

### 重现链接

无

### 重现步骤

无

### 预期行为

希望minimap开启不要触发两次mounted，或者在官方文档标注清楚minimap会导致什么样的后果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by lloydzhou** [comment]
这个不算bug
