### ISSUE TITLE
曼哈顿路由 manhattan 在一个节点链接多个edge的情况下，拖动会出现卡顿

### ISSUE THREAD

**Issue by WangYJEE** [antvis/X6#2892]
### 问题描述

曼哈顿路由 manhattan 在一个节点链接多个edge的情况下，拖动会出现卡顿，官网的流程图图表示例可以重现，希望可以优化下

### 重现链接

https://x6.antv.vision/zh/examples/showcase/practices#flowchart

### 重现步骤

1. 给多个节点
2. source节点链接其他所有节点
3. 快速拖动source节点

### 预期行为

流畅拖动

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以升级到 v2.x 试试。
