### ISSUE TITLE
点选/框选 Selection的filter配置是函数时，实际结果和文档描述相反

### ISSUE THREAD

**Issue by XueMeijing** [antvis/X6#2894]
### 问题描述

![image](https://user-images.githubusercontent.com/35559153/202348615-5e54543c-ee8c-4740-a11a-f547d43ca19e.png)

实际结果是return node.shape !== 'rect' 才能禁止选中

### 重现链接

如上描述

### 重现步骤

如上描述

### 预期行为

像文档一样，filter函数return true时禁止选中

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
这个修改是 breakchange，已经在 2.x 版本中修复，而且 filter 的定义与 javascript 中 filter 语义保持一致。
