### ISSUE TITLE
 节点位置自动适应

### ISSUE THREAD

**Issue by 19991122** [antvis/X6#2901]
### 功能描述

有时候会希望我这边只有数据，但是根据数据和数据之间的关系能够给一个比较好的布局后的流程图，有时并不想后端自己写x,y坐标再传给前端渲染再手动调整

### 期望解决方案

虽然可以通过节点来进行调整节点位置，但是有的场景是根据数据生成图，希望能够更加智能一些

**Comment by damnright** [comment]
本质都是改变x,y
[https://github.com/antvis/hierarchy](url)

**Comment by NewByVector** [comment]
可以使用布局 @antv/layout
