### ISSUE TITLE
mouseup事件问题

### ISSUE THREAD

**Issue by pig0045** [antvis/X6#2908]
### Describe the bug

使用manhattan路由时，当鼠标在node或者边上抬起鼠标左键时候，触发大量的重新路由事件，请问是什么问题？

### Your Example Website or App

Stack

### Steps to Reproduce the Bug or Issue

node 和 edge连接完毕
在node或edge上点鼠标左键
抬起鼠标左键
触发大量manhattan路由重新绘制

### Expected behavior

希望能有关闭这个触发的地方

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
macos, chrome

**Comment by NewByVector** [comment]
这个有复现的 demo 吗？

**Comment by NewByVector** [comment]
因为该问题无法复现，先关闭，如果可以提供一个可以复现的 demo，请重新提一个新的 issue。

**Comment by lxy920912** [comment]
相同问题，本地点击触发mouseover 速度很快，但是编译后触发mouseup 触发大量计算，速度很慢
