### ISSUE TITLE
downloadDataUri导出的图片节点不存在或丢失部分样式

### ISSUE THREAD

**Issue by zhangxilong-43** [antvis/X6#2909]
### Describe the bug

1、向官网实例的代码中插入以下代码：
setTimeout(() => {
graph.toPNG((dataUri: string) => {
DataUri.downloadDataUri(dataUri, 'chart.png')
})
}, 3000)
2、观察导出的图片，不完整；
3、在官网的这段代码后面追加一段代码
fetch('../data/dag.json')
  .then((response) => response.json())
  .then((data) => {
    init(data)
    showNodeStatus(nodeStatusList)
    graph.centerContent();
  }) // 在此后追加
.then(() => {
    graph.toPNG((dataUri: string) => {
      DataUri.downloadDataUri(dataUri, 'chart.png')
    })
  })
4、观察导出的图片，仅有edge；

### Your Example Website or App

https://x6.antv.vision/zh/examples/showcase/practices#dag

### Steps to Reproduce the Bug or Issue

1、向官网实例的代码中插入以下代码：
setTimeout(() => {
graph.toPNG((dataUri: string) => {
DataUri.downloadDataUri(dataUri, 'chart.png')
})
}, 3000)
2、观察导出的图片，不完整；
3、在官网的这段代码后面追加一段代码
fetch('../data/dag.json')
  .then((response) => response.json())
  .then((data) => {
    init(data)
    showNodeStatus(nodeStatusList)
    graph.centerContent();
  }) // 在此后追加
.then(() => {
    graph.toPNG((dataUri: string) => {
      DataUri.downloadDataUri(dataUri, 'chart.png')
    })
  })
4、观察导出的图片，仅有edge；

### Expected behavior

预期：所述问题不存在

### Platform

操作系统: [macOS]
网页浏览器: [Google Chrome, Edge]
X6 版本: [1.34.2]

**Comment by scootDai** [comment]
也有类似问题，字体图标无法出来，一般样式丢失好像可以用stylesheet自定义加上，不清楚为啥字体图标样式加不上

**Comment by damnright** [comment]
样式复制下   加到stylesheet参数里

**Comment by NewByVector** [comment]
@zhangxilong-43 这个问题已经有好几个 issue 了，丢失的样式先用 stylesheet 补上，@scootDai 字体图标可以用 base64 图片。这个 issue 先关闭了。
