### ISSUE TITLE
destory function support 

### ISSUE THREAD

**Issue by zmaoo** [antvis/X6#291]
卸载画布，清除 graph 渲染的所有内容，还原原始 dom 结构

### Additional Context

场景是切换页面时希望卸载掉画布的东西，以及画布带来的内存消耗

**Comment by bubkoo** [comment]
@zmaoo 调用 `graph.dispose()` 方法销毁画布并还原 DOM 结构

**Comment by zmaoo** [comment]
> @zmaoo 调用 `graph.dispose()` 方法销毁画布并还原 DOM 结构

之前问过 dispose 并不是作为 destory 的目的存在的，而且好像是说只有在 scroller 模式下才有这样的行为，并且 Node 节点的 XML 节点没有清除掉

**Comment by bubkoo** [comment]
@zmaoo 使用最新版测试一下，回复你之前我已经修复了，可以清除 Node 节点。

**Comment by NewByVector** [comment]
dispose方法满足你的需求
