### ISSUE TITLE
反序列化文字大小出现问题

### ISSUE THREAD

**Issue by Lyong0216** [antvis/X6#2910]
### Describe the bug

在使用 X6 进行反序列化时（graph.fromJSON()）数据是从先序列化之后存取到后端接口，然后再使用时根据接口的数据进行序列化加载，第一次会出现序列化文字大小显示异常问题，第二次就正常显示。如下图：
![image](https://user-images.githubusercontent.com/72903238/202890427-0e09b97f-d740-417f-8258-d5c80330f9d2.png)

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

序列化显示正常

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Lyong0216** [comment]
而且使用 graph.centerContent() 也会出现画布不居中显示的异常

**Comment by NewByVector** [comment]
提供一个可以复现的 demo 看下呢?

**Comment by NewByVector** [comment]
因为没有可以复现的例子，我们本地也无法复现，暂时关闭这个 issue，如果有可以复现的 demo，请 reopen。
