### ISSUE TITLE
safari下渲染html自定义节点，拖动时候会有重影

### ISSUE THREAD

**Issue by codinglobster** [antvis/X6#2911]
### Describe the bug

chrome下，hello图形不会有重影，只在safari下会有残影。

### Your Example Website or App

https://codesandbox.io/s/weathered-bush-3m56sm

### Steps to Reproduce the Bug or Issue

1.打开网站
2.拖动hello节点

### Expected behavior

chrome下，hello图形不会有重影，只在safari下会有残影。

### Platform

- OS: [macOS]
- Browser: [Safari]
- Version: [版本16.1 (18614.2.9.1.12)]

**Comment by lloydzhou** [comment]
#2814

**Comment by NewByVector** [comment]
可以检查一些是否是内容大小超过了节点的尺寸 https://github.com/antvis/X6/issues/751
