### ISSUE TITLE
当节点的source和target过多，导致拖动节点页面卡动

### ISSUE THREAD

**Issue by ly0502** [antvis/X6#2917]
### 问题描述

节点过多，导致拖动节点页面卡动

### 重现链接

https://gitee.com/luyin-0502/demo-react.git

### 重现步骤

拉下项目，打开项目拖动中间NODE3节点移动

### 预期行为

希望提供优化方案，windows严重卡顿，严重影响使用体验

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- @antv/xflow:1.0.51

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/87859495/203288187-c5b85404-a50a-4b84-880f-3d3091d25b2e.png)

**Comment by g0ngjie** [comment]
我的是页面全部都是 **自定义节点** 元素超过两个以上，框选时会异常卡顿，当时使用的版本为 1.32.0， 升级1.32.3以后就没有这种卡顿现象了。希望对你有帮助。

**Comment by ly0502** [comment]
> 我页面**自定义节点**个个个个个个个个，框选，框选个个，框选异常卡顿异常卡顿异常卡顿卡顿卡顿卡顿以上个个卡顿个，当时候当会个个个个个个个个个个个个个个个个个个有帮助。

我用的是xflow1.0.51
