### ISSUE TITLE
使用html注册节点 执行setData数据更新 节点不触发重绘 数据不变

### ISSUE THREAD

**Issue by sterculiaSeed** [antvis/X6#2919]
### 问题描述

使用html注册节点 执行setData数据更新 节点不触发重绘 数据不变

### 重现链接

1111

### 重现步骤

// 注册自定义节点
Graph.registerHTMLComponent(
  'nodeHTML',
  (node) => {
    var wrap = document.createElement('div')
    const render = () => {
      const data = node.getData()
      wrap = `<div class="databox">
      <div style="display: flex; align-items: center">
        <div class="svgbox" style="background: #b26aff ">
          <span> ${node.getData().name.substring(0, 1)}</span>
        </div>
        <div class="textbox"> ${data.name} ${data.index > 0 ? '_' + data.index : ''}</div>
      </div>
      <div class="progress" style="display:${data.drillPran ? '' : 'none'}">
        <div class="sonProgress" style="width:${data.drillPran}%;background:#0887FF"></div>
      </div>
      <div style="display:${data.loading ? '' : 'none'};margin-left:15px;" >
      <i class="lls-icon-loading"></i>
      </div>
    </div>`
    }
    return wrap
  }

### 预期行为

节点数据更新后 视图也改变

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/91403779/203467207-ed60f1ba-abba-447d-95e1-80e806b1fdce.png)
![image](https://user-images.githubusercontent.com/91403779/203467254-0cbb0ed1-da2b-4854-b05e-397b6ccffe1c.png)

**Comment by sterculiaSeed** [comment]
数据更改了 视图不更新

**Comment by NewByVector** [comment]
使用这种方式可以实现刷新。
![image](https://user-images.githubusercontent.com/20186737/203805085-8b88647f-3b89-458a-b11f-404027cfa866.png)
另外，可以升级到 2.0 版本，提供了更简单的方式，http://x6.antv.antgroup.com/tutorial/intermediate/html#%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0

**Comment by sterculiaSeed** [comment]
> 使用这种方式可以实现刷新。 ![image](https://user-images.githubusercontent.com/20186737/203805085-8b88647f-3b89-458a-b11f-404027cfa866.png) 另外，可以升级到 2.0 版本，提供了更简单的方式，http://x6.antv.antgroup.com/tutorial/intermediate/html#%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0

使用这种方式 无法使用fromJSON重新载入画布数据

**Comment by NewByVector** [comment]
@sterculiaSeed 先注册，就可以
```ts
Graph.registerHTMLComponent({
  render: xxx,
  shouldComponentUpdate: xxx
})
```

**Comment by sterculiaSeed** [comment]
> @sterculiaSeed 先注册，就可以
> 
> ```ts
> Graph.registerHTMLComponent({
>   render: xxx,
>   shouldComponentUpdate: xxx
> })
> ```
这种是什么写法 是这样吗
![image](https://user-images.githubusercontent.com/91403779/203898283-fdf1d4c9-a7a3-4d53-ab75-43dab436ae76.png)
