### ISSUE TITLE
new Graph() 多次，dom 结构挂载错误

### ISSUE THREAD

**Issue by tongxueliha** [antvis/X6#292]
![image](https://user-images.githubusercontent.com/29720531/98944212-ab23be80-252b-11eb-8f41-c2777e98a683.png)

**Comment by bubkoo** [comment]
@tongxueliha 调用 `graph.dispose()` 方法销毁画布并还原 DOM 结构

**Comment by qdgcswy** [comment]
api文档里有个clearCells方法，初始化的时候判断画布是否存在，存在就清掉再初始化

**Comment by bubkoo** [comment]
@qdgcswy 这个判断可以具体的业务自己做吧，`graph.dispose()` 只负责销毁画布。

**Comment by NewByVector** [comment]
在业务中防止多次初始化

**Comment by hemiaoio** [comment]
针对不同的dom id, new Graph() 多次 也是不允许的么? 对一个实例dispose后,其他的都没了.
