### ISSUE TITLE
使用 `toPNG` 导出的图片比较模糊

### ISSUE THREAD

**Issue by awpsawps12** [antvis/X6#2938]
### 问题描述

使用 `graph.toPng` 方法导出的图片比较模糊，`quality` 已设置为 `1`。

### 重现链接

https://x6.antv.vision/zh/examples/showcase/practices#tree

### 重现步骤

打开上面的例子，在右边代码里加如下代码，更改其中一个节点的文字内容为“文字有点模糊”：

```
setTimeout(()=>{
    graph.toPNG(
        (dataUri) => {
          DataUri.downloadDataUri(dataUri, 'a.png');
        },
      );
  }, 3000)
```

### 预期行为

图片能够更加清晰

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.34.5]

### 屏幕截图或视频（可选）

<img width="340" alt="截屏2022-11-24 23 14 16" src="https://user-images.githubusercontent.com/12215558/203819565-2de96558-1694-4cf7-b113-9b34da634b9c.png">

**Comment by NewByVector** [comment]
可以通过调整 `width` 和 `height` 配置(调大一点)，达到清晰的效果。
