### ISSUE TITLE
I use vite + vue3 and use custom components, but after using formJSON, the canvas cannot display custom components

### ISSUE THREAD

**Issue by li522021642** [antvis/X6#2946]
### 问题描述

My project version is vite + vue3 + antv x6(1.x)
Custom component used based on @antv/x6-vue-shape
```
Graph.registerVueComponent(
    'ItemStart',
    {
      template: `<ItemStart />`,
      components: {
        ItemStart,
      },
    },
    true
  )
```
or
```
Graph.registerVueComponent(
    'ItemStart',
     {
       render: () => {
         return createVNode(ItemStart)
       },
     },
    true
  )
```

### 重现链接

no url

### 重现步骤

Custom components can be displayed and dragged normally, but after saving json and using formJSON, the custom components in the canvas cannot be displayed

### 预期行为

Hope to get a solution soon

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/18386302/204067521-46723b8b-f3c4-4cf9-b2a6-5a8505e5c8b1.png)
![image](https://user-images.githubusercontent.com/18386302/204067547-00560c7d-71ea-4db0-85c3-f737fb885311.png)

**Comment by li522021642** [comment]
used anvt x6(1.x)

**Comment by lloydzhou** [comment]
如果是1.x 的新版可以参考这个issue #2566

**Comment by li522021642** [comment]
> 如果是1.x 的新版可以参考这个issue #2566

正常使用和显示 都是没问题的，但是 在使用fromJSON后 画布里面的自定义组件没法显示出来

**Comment by NewByVector** [comment]
@li522021642 Can you give a demo that you can reproduce?

**Comment by NewByVector** [comment]
因为没有可以复现的 demo，这个 issue 先关闭了，后面能提供可以复现的示例，可以重新提一个 issue。
