### ISSUE TITLE
With version 2.0 of the minimap, custom vue components cannot be displayed in the canvas

### ISSUE THREAD

**Issue by li522021642** [antvis/X6#2947]
### Describe the bug

With version 2.0 of the minimap, custom vue components cannot be displayed in the canvas
But it can be displayed in the small map

### Your Example Website or App

no url

### Steps to Reproduce the Bug or Issue

use miniMap
![image](https://user-images.githubusercontent.com/18386302/204078762-5bce0937-4839-490e-b720-1842d0fcaa03.png)

no use miniMap
![image](https://user-images.githubusercontent.com/18386302/204078781-0f93bb4e-41b4-4efa-9dff-d929189647b4.png)

### Expected behavior

Hope to get a solution soon

### Platform

- OS:Windows
- Browser: Chrome
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
Upgrade @antv/x6-vue-shape to version 2.0.4.

**Comment by lake2** [comment]
@antv/x6-react-shap 存在同样的问题

**Comment by qiufeihong2018** [comment]
这个问题在react上也有同样的表现，能否解决下呢？谢谢
目前x6是1.32.3，x6-react-shape是1.6.0

**Comment by lloydzhou** [comment]
fixed on @antv/x6-react-shap
https://github.com/antvis/X6/pull/3591
