### ISSUE TITLE
在2.x版本的Transform在节点移动停止就会出现操作框而1.x版本的resizing不会

### ISSUE THREAD

**Issue by shayyee** [antvis/X6#2953]
### 问题描述

官网流程图的示例，1.x版本的移动节点停下之后不会显示resizing的操作框，点击节点后才会出现，而2.x的版本使用Transform插件移动节点停止后就会出现尺寸调整操作框
1.x版本：https://x6.antv.vision/zh/examples/showcase/practices#flowchart
2.x版本：https://x6.antv.antgroup.com/examples/showcase/practices/#flowchart

### 重现链接

https://x6.antv.antgroup.com/examples/showcase/practices/#flowchart

### 重现步骤

打开2.x流程图示例 https://x6.antv.antgroup.com/examples/showcase/practices/#flowchart 

### 预期行为

2.x版本中表现得和1.x中一样，移动节点结束不出现尺寸操作框

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.0.0]

**Comment by NewByVector** [comment]
升级包 @antv/x6-plugin-transform@2.0.3 即可。https://github.com/antvis/X6/pull/2956
