### ISSUE TITLE
2.x版本复制节点后，节点边框展示不正确

### ISSUE THREAD

**Issue by zY-zhao** [antvis/X6#2955]
### Describe the bug

![微信截图_20221128154514](https://user-images.githubusercontent.com/52238947/204223648-1fc81207-2268-4b96-b41d-74f7d169e260.png)

### Your Example Website or App

https://x6.antv.antgroup.com/tutorial/plugins/clipboard

### Steps to Reproduce the Bug or Issue

https://x6.antv.antgroup.com/tutorial/plugins/clipboard
使用官方文档演示中的粘贴即可复现

### Expected behavior

应当正确展示边框

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
更新到最新版本即可。
