### ISSUE TITLE
[doc] 需要在官网表明 x6-react-shape 2.x 只支持 react 18

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#2959]
### Describe the bug

需要在官网表明 x6-react-shape 2.x 只支持 react 18

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lloydzhou** [comment]
有没有可能以一种方式同时支持react 18 和18之前的版本？

**Comment by lloydzhou** [comment]
> 有没有可能以一种方式同时支持react 18 和18之前的版本？

写一个这样的兼容的方法，能让x6的2.x版本同时运行在react 17和react 18的环境？

![image](https://user-images.githubusercontent.com/1826685/204262744-6c72981d-a141-4449-a3f2-a1367d98a782.png)

**Comment by lloydzhou** [comment]
next.js有一个版本的代码是这样处理的

https://github.com/vercel/next.js/blob/12c5693ef55709ee7380ee89a1d228cfdf06ca2d/packages/next/client/index.tsx#L509-L525

![image](https://user-images.githubusercontent.com/1826685/204266606-62354cae-a557-4d3c-a899-4c5de668094a.png)

**Comment by lloydzhou** [comment]
@NewByVector 找到一个比较有意思的库（这个库把react component挂载到webcomponents内部，其实场景和咱们将react component挂载到foreignObject内部是很像的）

https://github.com/WTW-IM/react-html-element

这里也使用了类似的方式对react 18做兼容处理
https://github.com/WTW-IM/react-html-element/blob/react18/src/ReactHTMLElement.ts#L51

**Comment by NewByVector** [comment]
@lloydzhou 我研究一下

**Comment by lloydzhou** [comment]
我觉得如果能实现的话，还是有必要的，毕竟有的人可能由于一些库不能升级react 18，但是这些人，我们其实还是希望能升级到x6 2.x版本使用的。

**Comment by NewByVector** [comment]
来啦来啦，按照 @lloydzhou 提供的思路 https://github.com/antvis/X6/pull/2968 ，升级到 2.0.5 就可以支持 react17，

**Comment by qianlongdoit** [comment]
+1
写了半天发现不支持低版本react，头秃
