### ISSUE TITLE
用JSON导入的节点 无法使用自定义工具

### ISSUE THREAD

**Issue by Alimjan2013** [antvis/X6#2960]
### 问题描述

用JSON导入的节点 无法使用自定义工具

### 重现链接

https://codesandbox.io/s/funny-sunset-kes99t?file=/src/App.vue

### 重现步骤

1.新增多个节点
2.点击节点上的按钮（会有相应反应）
2.导出节点为json文件，并自动下载
3.导入下载的json 文件
4.点击节点上的按钮（没有任何反应）

### 预期行为

我期望看到，导入进来的节点也可以正常使用

### 平台

- 操作系统: [macOS,]
- 网页浏览器: [Google Chrome, EDGE]
- X6 版本: [ 2.0.3... ]
- Vue 版本 2

**Comment by g0ngjie** [comment]
> ### 问题描述
> 用JSON导入的节点 无法使用自定义工具
> 
> ### 重现链接
> https://codesandbox.io/s/funny-sunset-kes99t?file=/src/App.vue
> 
> ### 重现步骤
> 1.新增多个节点2.点击节点上的按钮（会有相应反应）2.导出节点为json文件，并自动下载3.导入下载的json 文件4.点击节点上的按钮（没有任何反应）
> 
> ### 预期行为
> 我期望看到，导入进来的节点也可以正常使用
> 
> ### 平台
> * 操作系统： [macOS，]
> * 网页浏览器： [Google Chrome， EDGE]
> * X6 版本： [ 2.0.3... ]
> * Vue 版本 2
> 
> ### 屏幕截图或视频（可选）
> _无响应_
> 
> ### 补充说明（可选）
> _无响应_

函数是无法序列化的，可以看下我这种解决方案 https://codesandbox.io/s/serene-darkness-zhgw55?file=/src/App.vue

**Comment by Alimjan2013** [comment]
> > ### 问题描述
> > 用JSON导入的节点 无法使用自定义工具
> > ### 重现链接
> > https://codesandbox.io/s/funny-sunset-kes99t?file=/src/App.vue
> > ### 重现步骤
> > 1.新增多个节点2.点击节点上的按钮（会有相应反应）2.导出节点为json文件，并自动下载3.导入下载的json 文件4.点击节点上的按钮（没有任何反应）
> > ### 预期行为
> > 我期望看到，导入进来的节点也可以正常使用
> > ### 平台
> > 
> > * 操作系统： [macOS，]
> > * 网页浏览器： [Google Chrome， EDGE]
> > * X6 版本： [ 2.0.3... ]
> > * Vue 版本 2
> > 
> > ### 屏幕截图或视频（可选）
> > _无响应_
> > ### 补充说明（可选）
> > _无响应_
> 
> 函数是无法序列化的，可以看下我这种解决方案 https://codesandbox.io/s/serene-darkness-zhgw55?file=/src/App.vue

谢谢，Demo里确实解决问题了，我继续吸收一下
