### ISSUE TITLE
Double-click events cannot be triggered when an element is selected

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#297]
### Current Behavior

Double-click events cannot be triggered when an element is selected

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
应该是所有节点上的交互事件都失效了，因为当选框覆盖在节点上时，所有的交互都在与选框进行。
