### ISSUE TITLE
dnd 插件 v2.0.6-beta.26 无法拖拽

### ISSUE THREAD

**Issue by qianlongdoit** [antvis/X6#2971]
### Describe the bug

v2.0.6-beta.26 插件安装无法拖拽，会报如下错误
this.snapline.isSnaplineEnabled is not a function
经过排查这里可能有错误
https://github.com/antvis/X6/blob/v2.0.6-beta.26/packages/x6-plugin-dnd/src/index.ts#L93-L95
https://github.com/antvis/X6/blob/%40antv/x6%402.0.2/packages/x6-plugin-dnd/src/index.ts#L106-L108

### Your Example Website or App

https://codesandbox.io/s/cool-framework-gp6w12?file=/package.json

### Steps to Reproduce the Bug or Issue

把官网给的例子更改版本就报错了，[在线例子](https://codesandbox.io/s/cool-framework-gp6w12?file=/package.json)

### Expected behavior

修复错误

### Platform

全平台

### Additional context

排查错误看的头秃

**Comment by NewByVector** [comment]
请使用正式版本，不要使用 beta 版本，之前有的 beta 版本中插件并没有抽取出来。
