### ISSUE TITLE
升级到2.x后，库里报错跑不起来，是缺少什么依赖吗？

### ISSUE THREAD

**Issue by yeyuliang2015** [antvis/X6#2976]
### Describe the bug

升级到2.x后，库里报错跑不起来，是缺少什么依赖吗？
TypeError: Cannot read properties of undefined (reading 'ToolItem')  at button.ts:10:39
<img width="669" alt="image" src="https://user-images.githubusercontent.com/10381702/204724329-c9b1a0b4-b764-42d2-84ff-ce40798cdd4f.png">

### Your Example Website or App

https://www.baidu.com

### Steps to Reproduce the Bug or Issue

升级到2.x后，库里报错跑不起来，是缺少什么依赖吗？
TypeError: Cannot read properties of undefined (reading 'ToolItem')  at button.ts:10:39
<img width="669" alt="image" src="https://user-images.githubusercontent.com/10381702/204724329-c9b1a0b4-b764-42d2-84ff-ce40798cdd4f.png">

### Expected behavior

升级到2.x后，库里报错跑不起来，是缺少什么依赖吗？
TypeError: Cannot read properties of undefined (reading 'ToolItem')  at button.ts:10:39
<img width="669" alt="image" src="https://user-images.githubusercontent.com/10381702/204724329-c9b1a0b4-b764-42d2-84ff-ce40798cdd4f.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
chrome

**Comment by yeyuliang2015** [comment]
升级到2.x后，库里报错跑不起来，是缺少什么依赖吗？
TypeError: Cannot read properties of undefined (reading 'ToolItem')  at button.ts:10:39
<img width="669" alt="image" src="https://user-images.githubusercontent.com/10381702/204724329-c9b1a0b4-b764-42d2-84ff-ce40798cdd4f.png">

**Comment by yeyuliang2015** [comment]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/10381702/204724659-7763a061-2b3f-4be4-ac98-92621c5649b0.png">

**Comment by NewByVector** [comment]
参考这个 https://github.com/antvis/X6/issues/1704

**Comment by yeyuliang2015** [comment]
升级2.0.4版本后，代码跑起来了，当根节点的关系很多的时候，拖动根节点的时候还是会卡住，拖动关系少的节点还是很流畅的，是否还可以优化一下呢？ @NewByVector
<img width="911" alt="image" src="https://user-images.githubusercontent.com/10381702/204749273-c5cf49ba-a802-4ccd-8a8f-4257fa6d39c0.png">

**Comment by lloydzhou** [comment]
边太多的时候，试试把grid取消掉。如果想要grid的背景，可以自己设置一个css 的background背景。

**Comment by NewByVector** [comment]
性能问题可以重新提一个 issue，这个 issue 先关闭了。
