### ISSUE TITLE
2.x版本官方图标示例，决策节点调整大小报错

### ISSUE THREAD

**Issue by zY-zhao** [antvis/X6#2982]
### Describe the bug

![微信截图_20221201165114](https://user-images.githubusercontent.com/52238947/205008345-b925e4b2-f3dd-4480-8bbd-9e3eb911c6b5.png)

### Your Example Website or App

https://x6.antv.antgroup.com/zh/examples/showcase/practices/#flowchart

### Steps to Reproduce the Bug or Issue

1.打开2.x官网图表示例
2.选择使用场景流程图
3.拖拽一个决策节点

### Expected behavior

决策节点正常放大缩小

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by zhangchenna** [comment]
@jeggy

**Comment by NewByVector** [comment]
升级到最新版本即可。
