### ISSUE TITLE
2.x版本框选组件后复制，复制后的组件未正确框选

### ISSUE THREAD

**Issue by njshuisheng** [antvis/X6#2987]
### 问题描述

![image](https://user-images.githubusercontent.com/34205271/205210902-ef516f26-3c9a-43eb-97a4-fa62eab24e78.png)

### 重现链接

https://codesandbox.io/s/objective-sunset-n8ed60

### 重现步骤

1.框选多个组件
2.复制
3.粘贴，复制后的组件框选样式异常

### 预期行为

复制后的组件框选样式正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
升级到 @antv/x6-plugin-selection@2.1.5

**Comment by NewByVector** [comment]
升级到 @antv/x6-plugin-selection@2.1.5
