### ISSUE TITLE
期望增加可视区域外视图节点的移除行为

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#2988]
### 功能描述

virtual 属性目前只对可视区域内的view进行渲染，如果已经完成过渲染，会永久保留，尽管他已经在可视区域外。
期望增加可视区域外view的移除行为。

![image](https://user-images.githubusercontent.com/22650893/205215798-4f688a70-f08f-4475-a9c3-733835008741.png)

### 期望解决方案

希望增加配置选项

**Comment by NewByVector** [comment]
如果已经渲染好了，为啥还要删除呢，这样做的理由是什么呢？

**Comment by lloydzhou** [comment]
不建议做这个事情，如果做了这个事情，对于拖动画布这个动作来说会有很大的性能损失。

**Comment by cuidong626** [comment]
> 如果已经渲染好了，为啥还要删除呢，这样做的理由是什么呢？
 
可能会存在一个场景，用户一口气肝了一天，绘制了10k个节点，越往后，画布拖拽变得卡顿怎么办？
我觉得是不是可以提供一种方式给我们开发选择？

**Comment by NewByVector** [comment]
@cuidong626 如果按照你的思路，其实在拖动过程中一直删除元素，可能会更加卡。
