### ISSUE TITLE
多边形阔缩异常，chunk-libs.14a6e223.js:19 Uncaught TypeError: a.shape.clone is not a function

### ISSUE THREAD

**Issue by cqhuangch** [antvis/X6#2989]
### Describe the bug

使用@antv/x6-plugin-transform"插件进行图形缩放，方形，圆形，椭圆等正常缩放没问题，多边形polygon，或复杂路径形Path，都无法正常缩放，异常信息：
Uncaught TypeError: cache.shape.clone is not a function
    at eval (ref.js?ab4a:159:1)
    at NodeView.eval (ref.js?ab4a:193:1)
    at apply (function.js?3b73:10:1)
    at Module.call (function.js?3b73:26:1)
    at eval (attr.js?1a6f:166:1)
    at Array.forEach (<anonymous>)
    at AttrManager.updateRelativeAttrs (attr.js?1a6f:162:1)
    at eval (attr.js?1a6f:341:1)
    at Array.forEach (<anonymous>)

版本号："@antv/x6-plugin-transform": "^2.0.3","@antv/x6": "^2.0.5",

<img width="622" alt="image" src="https://user-images.githubusercontent.com/32635574/205221262-ab6f6444-96a5-4502-bd97-6c0f75866cfe.png">

### Your Example Website or App

国外网站访问不通，没法上传本地代码

### Steps to Reproduce the Bug or Issue

点击形状，进行拖放。

### Expected behavior

希望修改后，多边形能像方形、圆形、椭圆等形状一样，可以缩放

### Screenshots or Videos

<img width="1838" alt="image" src="https://user-images.githubusercontent.com/32635574/205218303-b3909540-832d-445c-9f10-aaa40520b751.png">

### Platform

Chrome

**Comment by NewByVector** [comment]
更新到最新版本应该就好了，重新安装一下依赖。

**Comment by cqhuangch** [comment]
> 更新到最新版本应该就好了，重新安装一下依赖。

666，@antv/x6-plugin-transform升级到2.12版本果然好了，多谢大神指教
