### ISSUE TITLE
X6 导出时，能否按照画布大小导出？

### ISSUE THREAD

**Issue by zsio** [antvis/X6#2996]
### 问题描述

导出时默认只有中心有效区域，而不是整个画布。

### 重现链接

暂无

### 重现步骤

使用导出png等图片的时候，只生成中心有效区域，而不导出整个画布。

### 预期行为

希望导出整个画布展示的样子

### 平台

- 操作系统: [macOS, Windows.]
- 网页浏览器: [Google Chrome, edge]
- X6 版本: [1.33.1]

**Comment by NewByVector** [comment]
可以通过配置 `viewBox` 达到导出整个画布的效果：
```ts
graph.exportPNG('filename', {
  viewBox: {
    x: 0,
    y: 0,
    width: 800,
    height: 500
  }
})
```
