### ISSUE TITLE
Add custom dblclick event

### ISSUE THREAD

**Issue by Fnxxxxo** [antvis/X6#2997]
### 功能描述

This handler helps to simplify event handler of node double clicking.

### 期望解决方案

We have, currently, data-click to define custom click on node elements. May be we can use data-dblclick to do the same job with double clicking.

**Comment by Fnxxxxo** [comment]
> data-event is not recommended. Although it is very convenient, it is not conducive to our subsequent maintenance.

But how to fire custom event through X6 api? I can catch dbclick by vue event. How to fire it to the main program?

**Comment by NewByVector** [comment]
You can use the same idea as vue by binding @dblclclick to the element.

**Comment by Fnxxxxo** [comment]
> You can use the same idea as vue by binding @dblclclick to the element.

Sorry for the late reply. I can do this. But I cannot fire the dbclick event to the X6 system. Build a custom globel event bus sames duplicated and ugly. It's good to have something like:
```
setup() {
  const graph = inject('graph');
  graph.fire({ name: 'custom-dbclick '});
}
```
