### ISSUE TITLE
2.X选中节点后不会触发节点的移出事件

### ISSUE THREAD

**Issue by natsul** [antvis/X6#2998]
### Describe the bug

选中节点后不会触发节点的移出事件

### Your Example Website or App

https://codesandbox.io/s/nifty-pare-15tl8h

### Steps to Reproduce the Bug or Issue

1.开启框选事件
2.监听节点的鼠标移出事件
3.选中节点
4.将鼠标移出节点

### Expected behavior

选中节点后应当触发节点的移出事件

### Platform

- OS: [ Windows]
- Browser: [ Chrome]
- Version: [91.1]

**Comment by NewByVector** [comment]
首先感谢你的问题💕 开启框选后会在节点上方盖一层 dom 元素，导致 mouseleave 无法触发。可以通过配置解决你的问题。
```ts
const selection = new Selection({
  enabled: true,
  pointerEvents: 'none',
})
```
