### ISSUE TITLE
使用manhattan路由，padding设置大一些，两个靠近的节点连接线变形

### ISSUE THREAD

**Issue by SunYuanOnly** [antvis/X6#3001]
### 问题描述

使用manhattan路由，padding设置大一些，两个靠近的节点连接线变形

### 重现链接

https://antv-x6.gitee.io/zh/examples/showcase/practices#flowchart

### 重现步骤

https://antv-x6.gitee.io/zh/examples/showcase/practices#flowchart

### 预期行为

希望两个节点靠近时，是直线。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/16498201/205573842-d291eb7a-3501-407c-b3e2-d53a71198a00.png)

### 补充说明（可选）

希望能达到这种效果
https://user-images.githubusercontent.com/16498201/204994876-ce78f033-5cc5-4fc5-83a6-f8e746405378.png

**Comment by NewByVector** [comment]
你这个场景，padding 配置成 50，两个节点距离已经小于 100 了，此时无法形成 manhattan 路由，此时降级为 orth 路由了，可以看下本地的打印日志。
