### ISSUE TITLE
新建node/edge的时候 如何使用自定义id?

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#3002]
### 功能描述

cell 构造函数会判断id是开发配置还是采用uuid,但是clone的时候就没办法开发自定义了。
希望提供一个机制，可以自己根据业务规则创建id

![image](https://user-images.githubusercontent.com/22650893/205580879-40dceef1-b301-4a3e-8b22-0a4b54e11e25.png)
![image](https://user-images.githubusercontent.com/22650893/205581164-886d8251-0f13-419e-95c2-52ea2657362d.png)

### 期望解决方案

新建node/edge的时候 如何使用自定义id?
希望提供一个机制，可以自己根据业务规则创建id

**Comment by cuidong626** [comment]
同需求问题 #2789

**Comment by g0ngjie** [comment]
自己替换确实很麻烦，如果官方能提供自定义id生成方式会好很多。
目前我是在通过 **createNode** 时，在 **metadata** 中手动设定一个id。如果是拖拽情况下，需要参考这篇文档 [https://x6.antv.vision/zh/docs/tutorial/basic/dnd#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98](https://x6.antv.vision/zh/docs/tutorial/basic/dnd#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。因为放置节点时，会重新生成 uuid

**Comment by NewByVector** [comment]
创建节点的时候是可以通过配置 id 属性自定义 id 的，如果是 dnd 拖拽场景，请参考 [常见问题](http://x6.antv.antgroup.com/tutorial/plugins/dnd#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by leechor** [comment]
``` 
  const validateNodeNew = function (
      droppingNode: Cell,
      options: any
  ): boolean | Promise<boolean> {
    const ctor = droppingNode.constructor as typeof Cell
    const props = droppingNode.getProp();
    const node =  new ctor({ ...props, "id": "abcd"})
    options.targetGraph.model.addCell(node)
    return false
  }

new Stencil({validateNode: validateNodeNew,})
```
