### ISSUE TITLE
请问在vue2 里使用 x6 vue-shape 2.0 的register函数注册VUE节点的话如何挂载ports 链接桩呢  

### ISSUE THREAD

**Issue by AALiujiajun** [antvis/X6#3003]
### 问题描述

请问在vue2 里使用 x6 vue-shape 2.0 的register函数注册VUE节点的话如何挂载ports 链接桩呢  

### 重现链接

x

### 重现步骤

1.3x

 Graph.registerNode(
        'dag-condition',
        {
          inherit: 'vue-shape',
          component: xxx,
          ports: {
// 链接桩
        },
        true
        )

2.x

register({
    shape: "normal-shape",
    component: xxx
  });

我该如何初始化链接桩

### 预期行为

注册VUE节点时可以初始化链接桩

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by AALiujiajun** [comment]
> 同样是配置 ports 属性。
大佬是这样子写嘛
register({
shape: "normal-shape",
component: xxx,
ports: { xxx }
});
不行耶  我看register.js 也是解构出了  shape, component, inherit  并没有地方传ports属性

**Comment by NewByVector** [comment]
@AALiujiajun 是那样写的，你可以把你的完整配置发出来看看。

**Comment by NewByVector** [comment]
可以参考 https://codesandbox.io/s/teleport-xuan-ran-8mtupj

**Comment by AALiujiajun** [comment]
好的 谢谢大佬

**Comment by menghaoG** [comment]
我也遇到了同样的问题，请问该怎么解决，似乎连接桩没有初始化成功
![image](https://github.com/antvis/X6/assets/87536545/5bf32c88-4be3-41c2-bdf5-23b01a71b9b8)

**Comment by nanfb** [comment]
> 我也遇到了同样的问题，请问如何解决，好像连接桩没有初始化成功 ![图像](https://user-images.githubusercontent.com/87536545/266243505-5bf32c88-4be3-41c2-bdf5-23b01a71b9b8.png)

我也遇到了，你解决了吗？

**Comment by menghaoG** [comment]
> > 我也遇到了同样的问题，请问如何解决，好像连接桩没有初始化成功 ![图像](https://user-images.githubusercontent.com/87536545/266243505-5bf32c88-4be3-41c2-bdf5-23b01a71b9b8.png)
> 
> 我也遇到了，你解决了吗？

解决了，在使用vue组件时增加ports
register({
  shape: 'er-table',
  component: erTable,
  ports: erTablePorts,
})
erTablePorts = {
  groups: {
    in: {
      position: {
        name: 'left',
        args: {
          strict: true,
          dy: 18
        }
      },
      attrs: {
        circle: {
          r: 4,
          magnet: true,
          stroke: '#409eff',
          strokeWidth: 1,
          fill: '#fff',
          style: {
            visibility: 'hidden',
          },
        },
      },
    },
    out: {
      position: {
        name: 'right',
        args: {
          strict: true,
          dy: 18
        }
      },
      attrs: {
        circle: {
          r: 4,
          magnet: true,
          stroke: '#409eff',
          strokeWidth: 1,
          fill: '#fff',
          style: {
            visibility: 'hidden',
          },
        },
      },
    },
  },
  attrs: {
    circle: {
      r: 4,
      magnet: true,
      stroke: '#409eff',
      strokeWidth: 1,
      fill: '#fff',
      style: {
        visibility: 'hidden',
      },
    },
  },
}

**Comment by nanfb** [comment]
> > > 我也遇到了同样的问题，请问如何解决，好像连接桩没有初始化成功 ![图像](https://user-images.githubusercontent.com/87536545/266243505-5bf32c88-4be3-41c2-bdf5-23b01a71b9b8.png)
> > 
> > 
> > 我也遇到了，你解决了吗？
> 
> 解决了，在使用vue组件时增加ports register({ shape: 'er-table', component: erTable, ports: erTablePorts, }) erTablePorts = { groups: { in: { position: { name: 'left', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, out: { position: { name: 'right', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }
并不行，我用的 register 这个函数，我看他的类型并没有ports这个参数，我想用Node.addPort添加节点也是失败

**Comment by menghaoG** [comment]
> > 我也遇到了同样的问题，请问如何解决，好像连接桩没有初始化成功 ![图像](https://user-images.githubusercontent.com/87536545/266243505-5bf32c88-4be3-41c2-bdf5-23b01a71b9b8.png)
> 
> 我也遇到了，你解决了吗？

解决了，在使用vue组件时增加ports
register({
  shape: 'er-table',
  component: erTable,
  ports: erTablePorts,
})
erTablePorts = {
  groups: {
    in: {
      position: {
        name: 'left',
        args: {
          strict: true,
          dy: 18
        }
      },
      attrs: {
        circle: {
          r: 4,
          magnet: true,
          stroke: '#409eff',
          strokeWidth: 1,
          fill: '#fff',
          style: {
            visibility: 'hidden',
          },
        },
      },
    },
    out: {
      position: {
        name: 'right',
        args: {
          strict: true,
          dy: 18
        }
      },
      attrs: {
        circle: {
          r: 4,
          magnet: true,
          stroke: '#409eff',
          strokeWidth: 1,
          fill: '#fff',
          style: {
            visibility: 'hidden',
          },
        },
      },
    },
  },
  attrs: {
    circle: {
      r: 4,
      magnet: true,
      stroke: '#409eff',
      strokeWidth: 1,
      fill: '#fff',
      style: {
        visibility: 'hidden',
      },
    },
  },
}

> > > > 我也遇到了同样的问题，请问如何解决，好像连接桩没有初始化成功 ![图像](https://user-images.githubusercontent.com/87536545/266243505-5bf32c88-4be3-41c2-bdf5-23b01a71b9b8.png)
> > > 
> > > 
> > > 我也遇到了，你解决了吗？
> > 
> > 
> > 解决了，在使用vue组件时增加ports register({ shape: 'er-table', component: erTable, ports: erTablePorts, }) erTablePorts = { groups: { in: { position: { name: 'left', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, out: { position: { name: 'right', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }
> > 并不行，我用的 register 这个函数，我看他的类型并没有ports这个参数，我想用Node.addPort添加节点也是失败

register这个函数是有ports这个参数的，在Node.Properties
![image](https://github.com/antvis/X6/assets/87536545/70235b7e-3d71-499f-bfb4-9f6ec5579bb4)
也有可能是版本问题，我用的是2.13.1

**Comment by nanfb** [comment]
> > > 我也遇到了同样的问题，请问如何解决，好像连接桩没有初始化成功 ![图像](https://user-images.githubusercontent.com/87536545/266243505-5bf32c88-4be3-41c2-bdf5-23b01a71b9b8.png)
> > 
> > 
> > 我也遇到了，你解决了吗？
> 
> 解决了，在使用vue组件时增加ports register({ shape: 'er-table', component: erTable, ports: erTablePorts, }) erTablePorts = { groups: { in: { position: { name: 'left', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, out: { position: { name: 'right', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }
> 
> > > > > 我也遇到了同样的问题，请问如何解决，好像连接桩没有初始化成功 ![图像](https://user-images.githubusercontent.com/87536545/266243505-5bf32c88-4be3-41c2-bdf5-23b01a71b9b8.png)
> > > > 
> > > > 
> > > > 我也遇到了，你解决了吗？
> > > 
> > > 
> > > 解决了，在使用vue组件时增加ports register({ shape: 'er-table', component: erTable, ports: erTablePorts, }) erTablePorts = { groups: { in: { position: { name: 'left', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, out: { position: { name: 'right', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }
> > > 并不行，我用的 register 这个函数，我看他的类型并没有ports这个参数，我想用Node.addPort添加节点也是失败
> 
> register这个函数是有ports这个参数的，在Node.Properties ![image](https://user-images.githubusercontent.com/87536545/275419205-70235b7e-3d71-499f-bfb4-9f6ec5579bb4.png) 也有可能是版本问题，我用的是2.13.1

![image](https://github.com/antvis/X6/assets/56207464/d318bd1a-1338-4bcf-abf7-9a4f718c6fbc)
![image](https://github.com/antvis/X6/assets/56207464/509e15b2-6ef4-49df-af4e-dd806c92f781)
我这样写的，我感觉没啥问题啊，我的版本也是2.x，佬，可以康康😥

**Comment by AALiujiajun** [comment]
> > > > 我也遇到了同样的问题，请问如何解决，好像连接桩没有初始化成功 ![图像](https://user-images.githubusercontent.com/87536545/266243505-5bf32c88-4be3-41c2-bdf5-23b01a71b9b8.png)
> > > 
> > > 
> > > 我也遇到了，你解决了吗？
> > 
> > 
> > 解决了，在使用vue组件时增加ports register({ shape: 'er-table', component: erTable, ports: erTablePorts, }) erTablePorts = { groups: { in: { position: { name: 'left', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, out: { position: { name: 'right', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }
> > > > > > 我也遇到了同样的问题，请问如何解决，好像连接桩没有初始化成功 ![图像](https://user-images.githubusercontent.com/87536545/266243505-5bf32c88-4be3-41c2-bdf5-23b01a71b9b8.png)
> > > > > 
> > > > > 
> > > > > 我也遇到了，你解决了吗？
> > > > 
> > > > 
> > > > 解决了，在使用vue组件时增加ports register({ shape: 'er-table', component: erTable, ports: erTablePorts, }) erTablePorts = { groups: { in: { position: { name: 'left', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, out: { position: { name: 'right', args: { strict: true, dy: 18 } }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }, }, attrs: { circle: { r: 4, magnet: true, stroke: '#409eff', strokeWidth: 1, fill: '#fff', style: { visibility: 'hidden', }, }, }, }
> > > > 并不行，我用的 register 这个函数，我看他的类型并没有ports这个参数，我想用Node.addPort添加节点也是失败
> > 
> > 
> > register这个函数是有ports这个参数的，在Node.Properties ![image](https://user-images.githubusercontent.com/87536545/275419205-70235b7e-3d71-499f-bfb4-9f6ec5579bb4.png) 也有可能是版本问题，我用的是2.13.1
> 
> ![image](https://user-images.githubusercontent.com/56207464/275448486-d318bd1a-1338-4bcf-abf7-9a4f718c6fbc.png) ![image](https://user-images.githubusercontent.com/56207464/275448528-509e15b2-6ef4-49df-af4e-dd806c92f781.png) 我这样写的，我感觉没啥问题啊，我的版本也是2.x，佬，可以康康😥

import { register } from "@antv/x6-vue-shape";

export const ports = {
  groups: {
    ...defaultPortAttrs
  },
  items: [
    {
      group: "top",
    },
    {
      group: "bottom",
    },
  ],
};

register({
  shape: "ftp-datasource",
  width: 150,
  height: 36,
  component: ftpDatasource,
  ports: ports,
});

找不到也直接写 注册出来就有了
