### ISSUE TITLE
希望能有办法统一设置边样式

### ISSUE THREAD

**Issue by Fnxxxxo** [antvis/X6#3004]
### 功能描述

当前的边样式必须每次addEdge的时候传入。其他关于边的配置如路由等，已经可以在graph统一配置。

### 期望解决方案

在graph中添加边的默认样式配置，比如：
```
new Graph({
  connecting: {
    line: {
      attrs: { stroke: '#000' }
    }
  }
})
```
同时保留addEdge的方案，可以覆盖公共样式。

**Comment by NewByVector** [comment]
[定制边](http://x6.antv.antgroup.com/tutorial/basic/edge#%E5%AE%9A%E5%88%B6%E8%BE%B9)了解一下呢。

**Comment by Fnxxxxo** [comment]
> [定制边](http://x6.antv.antgroup.com/tutorial/basic/edge#%E5%AE%9A%E5%88%B6%E8%BE%B9)了解一下呢。

虽然也可以。但配法不舒服，不是有一个connecting字段么，基于默认的改动不能同样都在这个字段里完成么？另外文档里居然用`registerNode`来注册自定义边，太诡异了
