### ISSUE TITLE
删除node的时候不删除和node连接的edge

### ISSUE THREAD

**Issue by weedxu** [antvis/X6#3005]
### 功能描述

删除node的时候连带删除了node关联的edge

### 期望解决方案

期望在删除node时不删除和node关联的edge，关联画布的node在拖动时可以吸附新的node

**Comment by NewByVector** [comment]
如果不删除的话，那么连接的边怎么展示呢？

**Comment by NewByVector** [comment]
可以:
```ts
graph.removeNode(node, {  disconnectEdges: true })
```
这样删除节点的时候，连接的边连接的那一端会定位到画布左上角。

**Comment by a-silent-guy** [comment]
我在使用过程中遇到这样一个问题，当我使用disconnectEdges: true时，edge的确保留了，但是edge上的source-arrowhead和source-targethead失效了，edge不能再被拖动了。

**Comment by NewByVector** [comment]
@a-silent-guy 所以还是建议如果要保留边的话，可以先通过 `edge.setSource` 或者 `edge.setTarget` 等方法先将边和节点解绑。

**Comment by a-silent-guy** [comment]
目前是这样处理的，谢谢解答。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月23日(周五) 晚上8:13
收件人: ***@***.***&gt;;
抄送: "Peng ***@***.******@***.***&gt;;
主题: Re: [antvis/X6] 删除node的时候不删除和node连接的edge (Issue #3005)




 
@a-silent-guy 所以还是建议如果要保留边的话，可以先通过 edge.setSource 或者 edge.setTarget 等方法先将边和节点解绑。
