### ISSUE TITLE
【BUG】官网提供的快速入门的案例中，在mac触控板上，双指横划，缩放会发生异常

### ISSUE THREAD

**Issue by zhump** [antvis/X6#3010]
### Describe the bug

官网提供的快速入门的案例中，在mac触控板上，双指【横划】，缩放会发生异常，1.3版本下是正常的

### Your Example Website or App

https://x6.antv.antgroup.com/tutorial/basic/graph

### Steps to Reproduce the Bug or Issue

正常在官网体验即可
https://x6.antv.antgroup.com/tutorial/basic/graph

### Expected behavior

可正常缩放

### Screenshots or Videos

https://user-images.githubusercontent.com/7962067/205923681-6d5ede50-de75-4daf-b4c2-393e0d1cf34e.mp4

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome 108]
- Version: [e.g 2.0]

**Comment by NewByVector** [comment]
建议配置 modifiers 禁用双指平移行为。
```ts
mousewheel: {
    enabled: true,
    modifiers: 'Ctrl'
  },
```

**Comment by cuijinyu** [comment]
缩放设置上下限就OK了
