### ISSUE TITLE
node/edge clone的时候 如何使用自定义id?

### ISSUE THREAD

**Issue by cuidong626** [antvis/X6#3011]
### 功能描述

cell 构造函数会判断id是开发配置还是采用uuid,但是调用 **clone** 方法的时候就没办法自定义了。
希望提供一个机制，可以自己根据业务规则创建 id
![image](https://user-images.githubusercontent.com/22650893/205580879-40dceef1-b301-4a3e-8b22-0a4b54e11e25.png)
![image](https://user-images.githubusercontent.com/22650893/205581164-886d8251-0f13-419e-95c2-52ea2657362d.png)

### 期望解决方案

node/edge 使用 **clone** 方法的时候 可以自定义的 **id** 
希望提供一个机制，可以自己根据业务规则创建id

**Comment by NewByVector** [comment]
这个的场景是什么呢？

**Comment by NewByVector** [comment]
如果是复制粘贴场景，提供一个思路：可以在粘贴后使用 `graph.updateCellId` 方法来修改节点的 ID。

**Comment by cuidong626** [comment]
> 如果是复制粘贴场景，提供一个思路：可以在粘贴后使用 `graph.updateCellId` 方法来修改节点的 ID。

那我是不是可以直接监听cell:added 事件对这个Id的进行修改？

**Comment by NewByVector** [comment]
@cuidong626 还是推荐粘贴方法执行后更新节点 id，因为与很多原因导致 `cell:added` 事件。

**Comment by cuidong626** [comment]
我还是希望能提供一个机制，用于自己生成id，或者可不可以在cell里面写一个生成Id的方法，开发者通过原型链重写？就像 generatePortId这个方法一样

**Comment by NewByVector** [comment]
@cuidong626 外部自定义 id 非常容易导致错误，比如 id 重复、id 匹配不上等。
