### ISSUE TITLE
2.0.6版本 node:added，cell:removed，edge:removed回调事件不执行

### ISSUE THREAD

**Issue by 893949088** [antvis/X6#3013]
### 问题描述

2.0.6版本 node:added，cell:removed，edge:removed回调事件不执行

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: 2.0.6

**Comment by NewByVector** [comment]
请提供一个可以复现的 demo。
