### ISSUE TITLE
x6 2.0.7版本  windows环境下本地运行有几个问题

### ISSUE THREAD

**Issue by damnright** [antvis/X6#3015]
### 问题描述

pnpm install没有异常，运行完后：

“进入到指定项目开发和调试
cd packages/x6
pnpm run build:watch”报错：
<img width="309" alt="e1" src="https://user-images.githubusercontent.com/17570651/206137128-d9072ea7-67a0-4375-a37c-1e5f406eedbc.PNG">
linux环境下只build一次成功  没有持续watch

"启动 example 查看效果
cd examples/x6-example-features
pnpm run start"报错：
<img width="399" alt="捕获2" src="https://user-images.githubusercontent.com/17570651/206137440-93a542e3-3d87-422a-805e-7e2cbdcb6803.PNG">
linux环境下也是同样问题

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: Windows10
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by kping** [comment]
遇到同样问题

**Comment by cuidong626** [comment]
看一下这个issue #809 
我是windows系统安装了linux子系统打包的

**Comment by NewByVector** [comment]
example 启动不成功需要再 pnpm-workspace 中将 example 放开，watch 模式失败我看一下。

**Comment by NewByVector** [comment]
watch 模式已修复：https://github.com/antvis/X6/pull/3035
