### ISSUE TITLE
2.0 版本是否考虑出英文文档？

### ISSUE THREAD

**Issue by KillenMr** [antvis/X6#3021]
### 功能描述

我们正在基于ETL开源工具 [Kestra](https://github.com/kestra-io/kestra) 开发可视化 ETL/ELT 工作流，其中可视化部分使用的 X6 实现。

当前 Kestra 团队也正规划开发可视化工作流，基于我们的经验，推荐他们使用 X6，但[他们顾虑X6 2.0 没有英文版本文档](https://github.com/kestra-io/kestra/discussions/799#discussioncomment-4332025)，X6 2.0 是否有英文文档的规划？

### 期望解决方案

2.0 规划英文文档

**Comment by NewByVector** [comment]
2.0 版本发布之后，我们所有的精力都在于完善文档、功能优化、丰富示例，我们暂时还没有人力来做翻译文档的事情，感谢你的提出，翻译文档可能是我们明年的一个重要工作。

**Comment by NewByVector** [comment]
与 https://github.com/antvis/X6/issues/3605 重复。
