### ISSUE TITLE
X6 ports 链接桩 线样式设置

### ISSUE THREAD

**Issue by zzw827** [antvis/X6#3026]
### 功能描述

好像没有 单独给 ports链接桩 连接线样式设置得api  

### 期望解决方案

期望可以设置 链接桩 链接出的线的样式

**Comment by NewByVector** [comment]
参考 [createEdge](http://x6.antv.antgroup.com/tutorial/basic/interacting#createedge)

**Comment by zzw827** [comment]
> 参考 [createEdge](http://x6.antv.antgroup.com/tutorial/basic/interacting#createedge)

感谢大佬  X6 2.0 挺好用的
