### ISSUE TITLE
1.x 导出 图片 有问题

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3036]
### Describe the bug

直接调用导出 生成的 图片不完整  需要加定时器 而且定时器 第二个参数也得加上 多少ms 才行 , 使用 async true 通过监听 render:done 也不行

### Your Example Website or App

https://antv-x6.gitee.io/zh/examples/node/native-node#cylinder

### Steps to Reproduce the Bug or Issue

```JavaScript
import { Graph, DataUri } from '@antv/x6'

const graph = new Graph({
  container: document.getElementById('container'),
  grid: true,
  async: true
})

graph.addNode({
  shape: 'cylinder',
  x: 320,
  y: 120,
  width: 80,
  height: 120,
  label: 'cylinder',
  attrs: {
    top: {
      fill: '#fe854f',
      fillOpacity: 0.5,
    },
    body: {
      fill: '#ED8A19',
      fillOpacity: 0.8,
    },
  },
})

setTimeout(() => {
  graph.toPNG(
    async (dataUri) => {
        DataUri.downloadDataUri(dataUri, 'chart.png')
    },
    {
        backgroundColor: 'rgba(0, 0, 0, 0)',
        copyStyles: true,
        quality: 1,
    }
)
}, 600)


// graph.on("render:done", () => {
//     graph.toPNG(
//     async (dataUri) => {
//         DataUri.downloadDataUri(dataUri, 'chart.png')
//     },
//     {
//         backgroundColor: 'rgba(0, 0, 0, 0)',
//         copyStyles: true,
//         quality: 1,
//     }
// )
// })
```

[直接复制代码在这个网址打开就行](https://antv-x6.gitee.io/zh/examples/node/native-node#cylinder)

### Expected behavior

我希望 在我调用 生成图片等方法 是对应节点生成完成的, 或者有 回调函数, 但是现在 addNode 后 直接调用 生成 图片是不全的。

### Screenshots or Videos

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/39638510/207207347-e83ca39d-4c26-4358-a075-507a2a507ff7.png">

### Platform

- OS:[macOS 13.0.1]
- Browser: [Chrome 版本 108.0.5359.98（正式版本） (arm64)]
- Version: [1.34.5]

**Comment by NewByVector** [comment]
出现上面现象的原因是文本渲染是异步的，而且无法用 render:done 监听到完成时间，但是按照道理，不应该有添加完节点马上导出的需求吧？

**Comment by JoeABCDEF** [comment]
@NewByVector 
新加的节点 我需要进来前 根据是否有新加的 有的话生成对应的缩略图 , 生成缩略图方法 就是让他 生成在画布中然后导出图片上传 然后就有马上导出的需求了

主要是 Stencil 样式不能太自定义了

<img width="454" alt="image" src="https://user-images.githubusercontent.com/39638510/210740049-612ac187-43ef-49af-86d2-78c64a75c740.png">

**Comment by NewByVector** [comment]
这个暂时没有好的办法解决，因为无法确定文字渲染完成时间，还是尽量从产品交互层面考虑来规避。

**Comment by JoeABCDEF** [comment]
> 这个暂时没有好的办法解决，因为无法确定文字渲染完成时间，还是尽量从产品交互层面考虑来规避。

了解了
