### ISSUE TITLE
Shape.Polygon设置points无效

### ISSUE THREAD

**Issue by kuangyuliang** [antvis/X6#304]
new Shape.Polygon({
    width: 50,
    height: 50,
    markup: [
        {
            tagName: 'polygon',
            selector: 'body',
            //points: '25,0 50,25 25,50 0,25'
            attrs: {
                points: '25,0 50,25 25,50 0,25'
            }
        },
        {
            tagName: 'path',
            selector: 'icon',
            attrs: {
                d: 'm 23,10 0,12.5 -12.5,0 0,5 12.5,0 0,12.5 5,0 0,-12.5 12.5,0 0,-5 -12.5,0 0,-12.5 -5,0 z',
                fill: 'black',
                strokeWidth: 1,
                stroke: 'black',
            },
        },
        {
            tagName: 'text',
            selector: 'label',
        }
    ],
    attrs: {
        body: {
            points: '25,0 50,25 25,50 0,25'
        }
    }
});

**Comment by bubkoo** [comment]
@kuangyuliang https://codesandbox.io/s/vigilant-paper-fk6me?file=/src/app.tsx

**Comment by kuangyuliang** [comment]
> @kuangyuliang https://codesandbox.io/s/vigilant-paper-fk6me?file=/src/app.tsx

@bubkoo https://codesandbox.io/s/quizzical-nash-o19pm?file=/src/app.tsx
如果是用new Shape.Polygon()这种方式是没效果的，new Shape.Rect()又可以，我不知道是这样设计的还是？
