### ISSUE TITLE
展开/折叠 group群组的问题

### ISSUE THREAD

**Issue by siguang1983** [antvis/X6#3040]
### 问题描述

展开/折叠 group群组的问题

他那可展开折叠的group，在序列化后保存了数据，在反序列化后，群组没有展开折叠的功能

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

步骤：
1、文档中示例创建一个自定义节点类
export class Group extends Node {
  ...
}

2、创建节点
const group = new Group({
    shape: item.shape,
    compName: item.compName,
    width: 200,
    height: 200,
    parent: true,
    x: 0,
    y: 0,
    attrs: {
      body: {
        fill: "#722ed1",
        stroke: "#000"
      },
      label: { text: item.name },
    },
    data: {
      ...item,
    },
  })
  console.log('group', group)
  this.graph.addNode(group)

3、保存序列化数据
  this.graph.toJSON()
  ... 存到库里

4、列表页面点编辑将存储的数据在反序列化
  this.graph.fromJSON(data)

5、问题
  反序列化不展示折叠组，只是展示组，这块需要怎么处理

### 预期行为

如果折叠组，反序列化后也展示的是折叠组

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome,]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

序列化前可折叠群组，
<img width="984" alt="截屏2022-12-13 15 29 29" src="https://user-images.githubusercontent.com/9248645/207253226-d950003d-b0a7-47ea-b517-17ff3e3772ea.png">

反序列化后不展示可折叠群组
<img width="967" alt="截屏2022-12-13 15 28 52" src="https://user-images.githubusercontent.com/9248645/207253124-7d478dcd-9fa0-4af6-a321-18700c106d74.png">

**Comment by NewByVector** [comment]
你给的重现连接和描述内容不一致。

**Comment by siguang1983** [comment]
项目用的是vue2的，连接的确不太好弄，请问一下折叠群组，反序列化还能原成折叠群组

**Comment by siguang1983** [comment]
项目用的是vue2的，连接的确不太好弄，请问一下折叠群组，反序列号也能还原成折叠群组

**Comment by oyal** [comment]
把群组做成自定义节点就可以了
`Graph.registerNode('group', Group)`
