### ISSUE TITLE
setSelectionFilter 设置无效

### ISSUE THREAD

**Issue by handsomeCarl** [antvis/X6#3041]
### 问题描述

用react 创建的节点 通过setSelectionFilter  筛选 节点的id ，然后再去操作节点，还是能被选中

### 重现链接

https://codesandbox.io/s/laughing-neco-d9pfg1?file=/src/app.tsx

### 重现步骤

进入页面，后点击节点，发现节点还能被选中

### 预期行为

希望过滤的节点不被选中

### 平台

   "@antv/x6": "^1.31.4",
    "@antv/x6-react-shape": "^1.6.0",

**Comment by handsomeCarl** [comment]
没人回复一下么？

**Comment by NewByVector** [comment]
1.x 版本中 filter 还不支持节点 id，只支持`节点对象`，`节点形状`以及`函数`,如果需要用节点 id 的话，使用函数方式。我们已经在 2.x 版本中修复了该问题。
