### ISSUE TITLE
修改框选选中的node的label，框选的大小没有改变

### ISSUE THREAD

**Issue by wukakakaka** [antvis/X6#3042]
### Describe the bug

修改框选选中的node的label框选的，大小没有改变

### Your Example Website or App

内网

### Steps to Reproduce the Bug or Issue

1.设置node为框选状态
2.清空node的label
3.node.attr('label', {
  text: 'hello'
})

### Expected behavior

node框随着label的改变，框选大小改变

### Platform

- Browser: [Chrome]

**Comment by NewByVector** [comment]
框选大小是和节点大小相关的，修改 label 后节点大小是否有调整呢？

**Comment by NewByVector** [comment]
因为无法复现该问题，暂时先关闭了，如果可以提供一个可以复现的 demo，请重新提一个新的 issue。

**Comment by Rubinhuang9239** [comment]
> 框选大小是和节点大小相关的，修改 label 后节点大小是否有调整呢？

那么如何获取内容文字的大小呢？
