### ISSUE TITLE
单击、双击节点，弹开鼠标后，会出现与节点大小一致的虚线框，随着鼠标的移动而移动。效果类似左键拖拽不放开鼠标。请问如何解决此bug？

### ISSUE THREAD

**Issue by FantasticLeo123** [antvis/X6#3049]
### Describe the bug

如题所述，左键单击或者左键双击节点，弹开鼠标后，会出现与节点大小一致的虚线框，随着鼠标的移动而移动。效果类似左键拖拽不放开鼠标。请问如何解决此bug？

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1. 单击或双击节点
2. 触发点击事件，但会出现与节点大小一致的虚线框，随着鼠标的移动而移动。或者不出现虚线框，而是整个节点跟着移动
3. 视频中的效果均是在双击后的实际效果，并没有进行拖拽，但实际效果如同拖拽

### Expected behavior

单击或者双击节点后，不会出现与节点大小相同的虚线框，也不要随着鼠标的移动而移动。

### Screenshots or Videos

https://user-images.githubusercontent.com/25195554/207762969-ee90f5e8-7ba1-4612-a0cf-a1cfe1f9a5ad.mp4

https://user-images.githubusercontent.com/25195554/207762995-8eaab242-19cc-4b8f-92a0-50ac2602b8d3.mp4

### Platform

- OS: [Windows]
- Browser: [Firefox]
- Version: [e.g. 1.31.1]

**Comment by hy9125** [comment]
遇到了相同的问题，不知道怎么解决

**Comment by cooljser** [comment]
+1
