### ISSUE TITLE
2.x 版本 缺少 createCellView 等方法

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3051]
### Describe the feature you'd like to request

类似 1.x 版本中 createCellView getCellView 等方法

### Describe the solution you'd like

使用 2.x 版本 没有 createCellView 方法 小地图没法自定义节点跟 边的渲染了

### Describe alternatives you've considered

无

**Comment by katherinehhh** [comment]
有解决办法了吗

**Comment by JoeABCDEF** [comment]
@katherinehhh  新版本好像是加上了
