### ISSUE TITLE
如何指定边的连线为虚线，是否支持type类型配置项

### ISSUE THREAD

**Issue by masterxl12** [antvis/X6#3055]
### 问题描述

edge边连线

### 重现链接

无

### 重现步骤

无

### 预期行为

虚线连接线实现

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以使用 `strokeDasharray` 属性来实现，参考 [demo](http://x6.antv.antgroup.com/examples/edge/edge/#edge)
