### ISSUE TITLE
自定义React节点无法感知画布上层Context的变化

### ISSUE THREAD

**Issue by xiaoweb** [antvis/X6#3057]
### 问题描述

使用 @antv/x6-react-shape 注册的react自定义节点无法获取到context中的最新值

### 重现链接

https://codesandbox.io/s/holy-fire-9ceuqo?from-embed=&file=/src/styles.css

### 重现步骤

可以看到红色自定义节点中的context value的值是旧的

### 预期行为

希望不要脱离react的context状态范围，能正常的获取到

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.0.7 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/3126352/208061995-cda65ac4-8379-4fdd-b242-d6a2bb920208.png)

**Comment by NewByVector** [comment]
如果需要使用 Context，请使用 [Portal](http://x6.antv.antgroup.com/tutorial/intermediate/react#portal-%E6%96%B9%E5%BC%8F) 方式。

**Comment by xiaoweb** [comment]
好的。谢谢
