### ISSUE TITLE
No option to obtain context of your main application using X6 Vue Shape

### ISSUE THREAD

**Issue by harshaktg** [antvis/X6#3059]
### Describe the feature you'd like to request

There is this option in React, but there is no support to obtain context of the main application in Vue. Couldn't find anything in the documentation too

### Describe the solution you'd like

Provide an option which will add it as a context value, while registering the Vue shape

### Describe alternatives you've considered

Provide an option which will add it as a context value, while registering the Vue shape

**Comment by NewByVector** [comment]
Which version do you use？

**Comment by harshaktg** [comment]
Can you share a sandbox demo of this working? It'll be really helpful to get along

**Comment by NewByVector** [comment]
You can refer to this [demo](https://codesandbox.io/s/teleport-xuan-ran-8mtupj?file=/src/App.vue).

**Comment by harshaktg** [comment]
Thank you @NewByVector . This is awesome. I have created a small one to demonstrate i18n in x6-vue-shape.
Please have a look [here](https://codesandbox.io/s/teleport-xuan-ran-forked-k6j792?file=/src/main.js)
