### ISSUE TITLE
燕子这可咋办呀，自定义 tool item 官网 示例  cell:mousemove 不起作用。

### ISSUE THREAD

**Issue by 0jinxing** [antvis/X6#3074]
### Describe the bug

自定义 tool item 官网 示例  cell:mousemove 不起作用

[https://x6.antv.antgroup.com/examples/edge/tool/#tooltip](https://x6.antv.antgroup.com/examples/edge/tool/#tooltip)

cell:mouseleave
cell:mouseenter
均正常
cell:mousemove 
没被调用。

### Your Example Website or App

https://x6.antv.antgroup.com/examples/edge/tool/#tooltip

### Steps to Reproduce the Bug or Issue

<img width="1076" alt="截屏2022-12-20 18 05 35" src="https://user-images.githubusercontent.com/32119282/208640619-b131bc14-b7e4-4c55-ae46-1ca72646894e.png">

1. 打开 [https://x6.antv.antgroup.com/examples/edge/tool/#tooltip](https://x6.antv.antgroup.com/examples/edge/tool/#tooltip)
2. 鼠标疯狂 在 edge view 移动
3. 🤔 cell:mousemove 不起作用

### Expected behavior

cell:mousemove 可以正常 trigger

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by 0jinxing** [comment]
x6 2.0 版本，

**Comment by NewByVector** [comment]
x6 中 `mousemove` 事件和通常的鼠标移动事件有所区别，它需要在鼠标按下后移动鼠标才能触发。参考[文档](https://x6.antv.antgroup.com/tutorial/basic/events)。
