### ISSUE TITLE
Align node by port position

### ISSUE THREAD

**Issue by lyon-liao** [antvis/X6#3077]
### Describe the feature you'd like to request

We'll add a lot of nodes with custom ports, which can be anywhere on the node. Sometimes, it is hard to connect a horizontal(or vertical) line if the ports are not on a horizontal(or vertical) line.  So I think,  The `X6` can support it.

BTW, I have implemented it in my business code, but the version is `V1.x`. I disabled the default `snapline`. I use the default `snapline` code and added some other logic to accomplish it. I think it's not a good way, So I think, It would be nice if the snapline plugin could support this.

### Describe the solution you'd like

During an alignment decision, I think we can get a distance value from the default align and we will get another value from aligning by ports. By doing that we can make a decision on which alignment strategy to use.
```
interface AlignArgs {
	dx: number
	dy: number
	line: {
	    verticalLeft,
	    verticalTop,
	    verticalHeight,
	    horizontalTop,
	    horizontalLeft,
	    horizontalWidth,
	 }
}

snapOnMoving(e) {
	...
	const portAlignArgs: AlignArgs = this.alignByPorts(e)
	const nodeAlignArgs: AlignArgs = this.alignByPosAndSize(e)

	...
}
```

**Comment by NewByVector** [comment]
Recently, we have been focusing on improving the stability and documentation of v2 version. We have not had the energy to do this for the time being. Welcome PR.

**Comment by lyon-liao** [comment]
@NewByVector Is there a function to get the `Port` position in `X6`? 

```
const ports = node.getPorts()
// Convert a port to a coordinate point
// the point is { x: number, y: number }
return ports.map(item => getPortPosition(item))
```

**Comment by NewByVector** [comment]
> I want to test it, but it seems the new version(version 2) can't support the simple configuration. The port is not displayed correctly.

fix it in https://github.com/antvis/X6/pull/3117.
