### ISSUE TITLE
2.x 没有 render:done

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3085]
### Describe the bug

<img width="2409" alt="image" src="https://user-images.githubusercontent.com/39638510/209072294-39809270-78ae-4531-b27b-58938809b358.png">

文档中写的方法并 实际并没有

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

有 render:done 方法

### Platform

- OS:[macOS 13.0.1]
- Browser: [Chrome 版本 108.0.5359.98（正式版本） (arm64)]
- Version: [2.0.8]

**Comment by NewByVector** [comment]
2.x 中已经将 `render:done` 事件删除，文档已经更新。请问使用这个事件的场景是？

**Comment by JoeABCDEF** [comment]
> 2.x 中已经将 `render:done` 事件删除，文档已经更新。请问使用这个事件的场景是？

当时 因为这个问题( #3086) 以为是未渲染完成时 调用导致的

**Comment by JoeABCDEF** [comment]
> 2.x 中已经将 `render:done` 事件删除，文档已经更新。请问使用这个事件的场景是？

@NewByVector  现在有个需求 是执行一些自定义动画, 当我 fromJSON 后。但是现在fromJSON后直接调 发现一些 path element 没创建完, 导致执行动画没法执行

**Comment by JoeABCDEF** [comment]
> 2.x 中已经将 `render:done` 事件删除，文档已经更新。请问使用这个事件的场景是？

@NewByVector   现在有个需求 是执行一些自定义动画, 当我 fromJSON 后。但是现在fromJSON后直接调 发现一些 path element 没创建完, 导致执行动画没法执行

**Comment by NewByVector** [comment]
感谢你的输入，该功能已经加入到我们的工作计划中了。

**Comment by NewByVector** [comment]
@JoeABCDEF 我的想法是增加两个事件，`cell:mounted` 和 `cell:unmounted`，也就是元素加到 DOM 和从 DOM 删除时触发，不知道是否能满足你的需求？

**Comment by JoeABCDEF** [comment]
> @JoeABCDEF 我的想法是增加两个事件，`cell:mounted` 和 `cell:unmounted`，也就是元素加到 DOM 和从 DOM 删除时触发，不知道是否能满足你的需求？

@NewByVector  这个也很实用

**Comment by NewByVector** [comment]
@JoeABCDEF 暂时还没有

**Comment by JoeABCDEF** [comment]
@NewByVector  大佬啥时候 会加上对应方法，下个版本会加吗
