### ISSUE TITLE
Svelte Support 

### ISSUE THREAD

**Issue by Immortalin** [antvis/X6#3087]
### Describe the feature you'd like to request

Bindings for the Svelte framework

https://svelte.dev/
https://kit.svelte.dev/

### Describe the solution you'd like

Svelte is a frontend framework that is growing in popularity. Having a first party Svelte binding for X6 would increase the usage and mindshare of X6.

### Describe alternatives you've considered

Maintaining a third party library

**Comment by lloydzhou** [comment]
x6的API实际上是框架无关的，你可以在其他的框架内使用（所以不存在对`svelte`支持的问题）。

官方文档给出了三个框架的demo，你要是有兴趣，可以通过提pr的方式给官方提供基于`svelte`的demo

这里是一个在`Svelte`内使用`x6`的一个demo，你要是有兴趣可以看看。
https://github.com/lloydzhou/antv-x6-svelte

**Comment by smallshen** [comment]
https://github.com/smallshen/x6-svelte-shape

**Comment by NewByVector** [comment]
@lloydzhou 可以加到 awsome-x6 里面了

**Comment by lloydzhou** [comment]
> @lloydzhou 可以加到 awsome-x6 里面了

中午已经加好了

**Comment by smallshen** [comment]
https://github.com/smallshen/x6-svelte-shape/issues/1
有人提了个issue想要把这个加到main仓库里头，有没有人愿意帮忙一下。

[NodeWrapper.svelte](https://github.com/smallshen/x6-svelte-shape/blob/main/NodeWrapper.svelte) 这个文件不是必须的
