### ISSUE TITLE
Workflow `mirror` run failed

### ISSUE THREAD

**Issue by yanglbme** [antvis/X6#309]
Hi @afc163 , I notice that the mirror workflow run failed.

Error log: https://github.com/antvis/X6/runs/1417107992 

![image](https://user-images.githubusercontent.com/21008209/99511137-d80c2180-29c2-11eb-887d-48ad367401c0.png)

Maybe you should follow gitee wechat subscription, bind you gitee account to receive the login notification :)

**Comment by afc163** [comment]
我绑定了微信，看看效果。

**Comment by afc163** [comment]
Fixed!

https://github.com/antvis/G6/pull/2269
