### ISSUE TITLE
自定义节点内纵向有多个定位过的元素时，以这些元素作为参照元素同时使用 refY refY2 定位位置计算错误

### ISSUE THREAD

**Issue by dukeP** [antvis/X6#3093]
### 问题描述

但是使用 g tag 包裹，并对 g tag 定位，其余元素位置计算正确
不确定是 bug，还是遇到知识盲区；
是否必须按照第二种写法使用

### 重现链接

https://codesandbox.io/s/musing-bardeen-ep3nus?file=/src/App.vue

### 重现步骤

可在 [codesandbox](https://codesandbox.io/s/musing-bardeen-ep3nus?file=/src/App.vue) 复现

### 预期行为

计算出正确位置

### 平台

- 操作系统: [Windows 11]
- 网页浏览器: [Google Chrome 108.0.5359.124]
- X6 版本: [2.x]

### 屏幕截图或视频（可选）

![2022-12-26 104716](https://user-images.githubusercontent.com/17401244/209493264-eac133ad-0cbc-4158-a8d5-05448f073a12.png)

**Comment by dukeP** [comment]
@NewByVector  感谢回复。你所说的也正是我比较疑惑的地方：
![屏幕截图 2023-01-09 105749](https://user-images.githubusercontent.com/17401244/211234468-152c9ed1-1efa-49dd-8535-23aff9dafe2b.png)
按照 [重现链接](https://codesandbox.io/s/musing-bardeen-ep3nus?file=/src/App.vue) 来配置的话，text 的 y 的计算结果应该是：
50 * 0.5 - 2 = 23, 但是实际结果是 123 ，没搞明白多出来的 100 是哪里加出来的

**Comment by NewByVector** [comment]
其实是：50 + (50 * 0.5) + (50 - 2) = 123

**Comment by dukeP** [comment]
> 其实是：50 + (50 * 0.5) + (50 - 2) = 123

噢，大概理解了，上面我少加了个 50 （ref 对应元素的 y）。
主要是 refY2 的计算方式没想到，看 [官方文档](https://x6.antv.vision/zh/docs/api/registry/attr#refy2) 的话直观的理解就是设置多少加多少 😄
