### ISSUE TITLE
zoomToFit()缩放后toSVG生成的图片不完整

### ISSUE THREAD

**Issue by JamesTing** [antvis/X6#3094]
### 问题描述

现象：使用 zoomToFit() 方法缩放画布后，使用 toSVG 导出的 svg 不完整。
X6版本：1.x

### 重现链接

https://amymind.com/view/graph/6XMJ25JlxOQBEW3V

### 重现步骤

1.  使用zoomToFit() 方法缩放画布
2. 使用toSVG导出svg图片

### 预期行为

导出的svg可以完整展示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
能否看下你导出 svg 方法传入的配置？

**Comment by JamesTing** [comment]
@NewByVector 就是最简单的配置
    graphObject.toSVG((dataUri: string) => {
        // 下载
        DataUri.downloadDataUri(DataUri.svgToDataUrl(dataUri), '画板.svg')
    })

我尝试过在 Export.ToSVGOptions 中指定viewBox，可能是坐标系不对，多次尝试也未成功。

**Comment by NewByVector** [comment]
看了下确实是 viewBox 的问题，设置正确的 viewBox，是可以正常显示的。
