### ISSUE TITLE
如何禁止节点拖动，文档中没找到设置的方法。

### ISSUE THREAD

**Issue by anyone0034** [antvis/X6#3095]
### 功能描述

如何禁止节点拖动

### 期望解决方案

如何禁止节点拖动

**Comment by JoeABCDEF** [comment]
[文档](https://antv-x6.gitee.io/zh/docs/api/graph/interaction/#interacting)

1.x 2.x 都适用

**Comment by tianjinhao** [comment]
@JoeABCDEF   可以使用 translating. restrict来限制节点的移动，具体可以看这个案例[限制子节点的移动范围](https://antv-x6.gitee.io/zh/examples/node/group#restrict-movement)， 将其中parent.getBBox()改为自身.getBBox() 即可；
