### ISSUE TITLE
antv/x6@2.1.3 版本代码会导致画布死递归

### ISSUE THREAD

**Issue by xuan-zhang** [antvis/X6#3097]
### Describe the bug

2.1.3 版本的 antv/x6 拖拽节点时会导致页面卡死， 但 2.1.2 版本中的代码并不会有此问题

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1. 在拖拽节点时，监听 `node:move` 事件
2. 在 `node:move` 事件中，清除 输入边与输出边的 vertices, 代码如下

```ts
 graph.on('node:move', options => {
    const {node} = options
    const edges = node.model.getConnectedEdges(node)
    edges.forEach(edge => {
      edge.setVertices([])
    })
  })
```
此时拖拽节点时， 页面会卡死，控制台会不停的输出 `left flag 128`

### Expected behavior

无此递归问题

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by cloudgaps** [comment]
我也碰见这个了，我是用递归生成节点时使用addCell方法，入参节是点和边,页面倒是没卡死，就是疯狂打印left flag 128...
