### ISSUE TITLE
请问为什么1.34.6版本的API中Graph的方法只有三个？

### ISSUE THREAD

**Issue by 18839965530** [antvis/X6#3102]
### 问题描述

请问为什么1.34.6版本的API中Graph的方法只有如下三个：startBatch、stopBatch、batchUpdate。
像addNode、addEdge等方法API中都没有写。

### 重现链接

https://x6.antv.vision/zh/docs/api/graph/graph

### 重现步骤

第一步打开链接地址：https://x6.antv.vision/zh/docs/api/graph/graph 即可看到。

### 预期行为

按说应该所有方法都有才对

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

<img width="960" alt="1" src="https://user-images.githubusercontent.com/24729221/210056780-01be6156-5458-4576-a36d-bc9d1ac1b367.png">

**Comment by NewByVector** [comment]
整个 Graph 目录下面的 API 都是 Graph 实例上的方法。
