### ISSUE TITLE
引入Addon报错

### ISSUE THREAD

**Issue by yueqiqi** [antvis/X6#3105]
### Describe the bug

@antv/x6版本号为^2.1.3， 无法使用拖拽 引入Addon报错没有导出成员Addon，
![image](https://user-images.githubusercontent.com/50952334/210328140-3d9d05e8-7fbf-4f0b-a1bd-4d9257811f39.png)

### Your Example Website or App

pc网站

### Steps to Reproduce the Bug or Issue

引入Addon报错

### Expected behavior

引入Addon报错

### Platform

- OS: Windows
- Browser: Chrome

**Comment by NewByVector** [comment]
dnd 的使用方式在 2.x 版本中有变化，具体参考[文档](http://x6.antv.antgroup.com/tutorial/plugins/dnd)。

**Comment by luowei6868** [comment]
你解决了吗，我也引入不了
