### ISSUE TITLE
关于validateConnection函数，在连接成功后，接收的参数中的targetPort和targetMagnet为null的情况

### ISSUE THREAD

**Issue by 565823371556Zsl** [antvis/X6#3106]
### 问题描述

从一个连接桩拖出线条到另一个链接桩，使用validateConnection做一些类型判断，但是连接成功后，期望得到的targetPort和targetMagnet却为null

### 重现链接

暂无

### 重现步骤

在连接的过程中，当鼠标没有移动到连接桩内部时，而是通过吸附的范围，在连接桩外围松开鼠标左键创建新的边时，此时targetPort和targetMagnet有值。
当鼠标移动到连接桩内部时，此时鼠标变成十字，松开鼠标左键创建新的边时，targetPort和targetMagnet为null

### 预期行为

期望无论何时都不为空

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
有可以复现的链接吗？
