### ISSUE TITLE
vite 打包后画布相关页面报错 graph undefined

### ISSUE THREAD

**Issue by Dntts** [antvis/X6#3107]
### 问题描述

vue3 vite 自定义vue-shape节点，本地开发时画布正常显示，正常使用。 
打包后 线上报错 :Cannot read properties of undefined (reading 'Graph')
页面无跳转

### 重现链接

无

### 重现步骤

无

### 预期行为

期望正常进入画布；
实际页面未跳转进入直接报错。

### 平台

- 操作系统: [macOS, Windows]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- "@antv/x6": "^1.32.0",
- "@antv/x6-vue-shape": "^1.4.2",
- "dagre": "latest",
- "vite": "^2.7.2"

### 屏幕截图或视频（可选）

![Uploading image.png…]()

### 补充说明（可选）

在一步步排查后发现：注释掉 layout （自动布局）和 registerNode （注册组件）相关 j s后 可以成功跳转进入页面，画布为空背景，没有节点等。
但是 以上两个js 查看后 并未发现异样。。代码贴上：
layout.js ：
`import dagre from "dagre";
/**
 * 自动布局
 * @param { Object } graph 画布实例
 * @param { String } dir 布局方向
 */
const layout_util = (graph, dir = "TB") => {
    const nodes = graph.getNodes();
    const edges = graph.getEdges();

    const g = new dagre.graphlib.Graph();
    g.setGraph({ rankdir: dir, nodesep: 16, ranksep: 16 });
    g.setDefaultEdgeLabel(() => ({}));

    const width = 320;
    const height = 200;
    nodes.forEach((node) => {
        g.setNode(node.id, { width, height });
    });

    edges.forEach((edge) => {
        const source = edge.getSource();
        const target = edge.getTarget();
        g.setEdge(source.cell, target.cell);
    });

    dagre.layout(g);

    graph.freeze();

    g.nodes().forEach((id) => {
        const node = graph.getCell(id);
        if (node) {
            const pos = g.node(id);
            node.position(pos.x, pos.y);
        }
    });

    edges.forEach((edge) => {
        const source = edge.getSourceNode();
        const target = edge.getTargetNode();

        const sourceBBox = source.getBBox();
        const targetBBox = target.getBBox();

        if ((dir === "LR" || dir === "RL") && sourceBBox.y !== targetBBox.y) {
            const gap =
                dir === "LR"
                    ? targetBBox.x - sourceBBox.x - sourceBBox.width
                    : -sourceBBox.x + targetBBox.x + targetBBox.width;
            const fix = dir === "LR" ? sourceBBox.width : 0;
            const x = sourceBBox.x + fix + gap / 2;
            edge.setVertices([
                { x, y: sourceBBox.center.y },
                { x, y: targetBBox.center.y },
            ]);
        } else if ((dir === "TB" || dir === "BT") && sourceBBox.x !== targetBBox.x) {
            const gap =
                dir === "TB"
                    ? targetBBox.y - sourceBBox.y - sourceBBox.height
                    : -sourceBBox.y + targetBBox.y + targetBBox.height;
            const fix = dir === "TB" ? sourceBBox.height : 0;
            const y = sourceBBox.y + fix + gap / 2;
            edge.setVertices([
                { x: sourceBBox.center.x, y },
                { x: targetBBox.center.x, y },
            ]);
        } else {
            edge.setVertices([]);
        }
    });

    graph.unfreeze();
};
export default layout_util;`
registerNode.js
`import Start from "../components/graphNode/Start.vue";

export default (Graph, createVNode) => {
    const width = 320;
    const height = 160;
    const nodeList = [
        {
            name: 'start-node',
            attrs: {
                inherit: "vue-shape",
                width: width,
                height: height,
                zIndex: 100,
                component: {
                    render: () => {
                        return createVNode(Start);
                    },
                },
            }
        },
    ];
    nodeList.forEach(child => {
        Graph.registerNode(child.name, child.attrs, true)
    })
}`

**Comment by Dntts** [comment]
有些迷，感觉是打包的问题，但是没见到有人问相关的问题。。

**Comment by NewByVector** [comment]
如果猜测是打包问题的话，是否可以提供完整的项目代码呢？

**Comment by Dntts** [comment]
最新发现：import dagre from "dagre";  这个插件只要注释后，线上就不会报错，但是自动布局这个功能也就没有了。我看了一下dagre 官方，发现已经不维护了，现在是发现了为题所在，不知怎么解决。。

**Comment by NewByVector** [comment]
可以使用 @antv/layout 这个库，也有 dagre 布局能力。

**Comment by Dntts** [comment]
resolve: {
      alias: [
        {
          find: '@antv/x6',
          replacement: '@antv/x6/dist/x6.js',
        },
        {
          find: '@antv/x6-vue-shape',
          replacement: '@antv/x6-vue-shape/lib',
        },
        {
          find: 'dagre',
          replacement: 'dagre/dist/dagre.js',
        },
      ],
