### ISSUE TITLE
主动添加连接桩的外围框

### ISSUE THREAD

**Issue by Fnxxxxo** [antvis/X6#3111]
### 功能描述

设计给的连接桩太小，不容易拉线操作。现在需要在node hover的时候，主动给连接桩添加一个外围框，扩大交互范围。
当前的解决办法只能改attrs/circle/r，但这样会影响连线位置。

### 期望解决方案

类似于highlighting那样，可以加一个node.portMagnetAvailable方法，方便事件触发的时候调用。 
  
   
**更新了一下connecting配置**
```
{
  snap: true,
  allowBlank: false,
  allowLoop: false,
  allowNode: false,
  allowEdge: false,
  highlight: true,
  connector: 'rounded',
  connectionPoint: 'anchor',
  router: {
    name: 'er',
    args: {
      offset: 'center',
      direction: 'V',
      min: 30
    }
  }
}
```

**Comment by NewByVector** [comment]
影响连线位置指的是什么？能具体描述一下？

**Comment by Fnxxxxo** [comment]
> 影响连线位置指的是什么？能具体描述一下？

我用了ER布局并且设置了center，直接改port的r属性，会导致连线整体被“挤开”，可以看到连线中折位置移动。但highlight属性配置的外围框就没有这个问题。

**Comment by NewByVector** [comment]
有 demo 看下效果吗？

**Comment by Fnxxxxo** [comment]
> 有 demo 看下效果吗？

抱歉代码是公司代码，但大致就是设置连线路由
```
router: {
  name: 'er',
  args: {
    offset: 'center',
    directive: 'V',
    min: 30
  }
}
```
再定义一个锚点
```
out: {
  circle: {
    magent: true,
    stroke: 0,
    r: 3
  }
}
```
然后添加事件处理
```
designer.on('node:mouseener', ({ node }) => {
  node.portProp('out', 'attrs/r', 6)
})
designer.on('node:mouseleave', ({ node }) => {
  node.portProp('out', 'attrs/r', 3)
})
```
这样鼠标飘到节点上，锚点能变大，但会改变ER连线的center的位置，导致连线移动

**Comment by NewByVector** [comment]
导致连线移动，我理解就是连线起点稍微会移动一点点，因为 port 的半径变大了，这个不可避免，其实我想知道这个对产品效果影响大吗？

**Comment by Fnxxxxo** [comment]
> 导致连线移动，我理解就是连线起点稍微会移动一点点，因为 port 的半径变大了，这个不可避免，其实我想知道这个对产品效果影响大吗？

本质上没啥问题，位置变了没啥影响。但需求硬说不能动

**Comment by Fnxxxxo** [comment]
> 设置connecting的connectionPoint为anchor，可解决此问题

加了没有变化，改r还是会影响连线的展示。目前勉强通过改strokeWidth能达到效果，但原来的连接桩必须足够小才能被完整覆盖掉，限制较大

**Comment by damnright** [comment]
> > 设置connecting的connectionPoint为anchor，可解决此问题
> 
> 加了没有变化，改r还是会影响连线的展示。目前勉强通过改strokeWidth能达到效果，但原来的连接桩必须足够小才能被完整覆盖掉，限制较大

不会啊，设置connecting的connectionPoint为anchor，连线会连到port的中心，r也没有改的理由了，没影响
[https://x6.antv.vision/en/docs/api/graph/interaction/#connecting](url)

**Comment by Fnxxxxo** [comment]
> > > 设置connecting的connectionPoint为anchor，可解决此问题
> > 
> > 
> > 加了没有变化，改r还是会影响连线的展示。目前勉强通过改strokeWidth能达到效果，但原来的连接桩必须足够小才能被完整覆盖掉，限制较大
> 
> 不会啊，设置connecting的connectionPoint为anchor，连线会连到port的中心，r也没有改的理由了，没影响 [https://x6.antv.vision/en/docs/api/graph/interaction/#connecting](url)

我尝试了修改connectionPoint，没效果，改r仍然会影响线的弯折位置，估计里面有bug？并没有链接至port中心

**Comment by NewByVector** [comment]
view 上是有这个方法的。参考[文档](https://x6.antv.vision/zh/docs/api/view/cellview/#highlight)。

**Comment by Fnxxxxo** [comment]
> view 上是有这个方法的。参考[文档](https://x6.antv.vision/zh/docs/api/view/cellview/#highlight)。

并没有。我需要的是让连接桩“变大”，方便hover时提示以及拖线交互，这个highlight不支持

**Comment by NewByVector** [comment]
@Fnxxxxo 那就只能用你的通过修改属性的方式，但是这样连线肯定会动的。
