### ISSUE TITLE
使用html渲染的节点期望可以进行手动连线

### ISSUE THREAD

**Issue by wellsmitch** [antvis/X6#3113]
### 功能描述

当前最新版本的node节点如果使用html渲染时 渲染后的结果foreignObject覆盖rect 导致无法使用手动连线功能（节点连接节点或节点节点连接 连接桩）。

### 期望解决方案

使用html渲染的节点时可以进行手动连线

**Comment by NewByVector** [comment]
将 foreignObject 元素设置为 magnet 即可。
```ts
attrs: {
  fo: {
    magnet: true
  }
}
```

**Comment by wellsmitch** [comment]
将 foreignObject 元素设置为 magnet 后  当前节点就不能够拖动了

**Comment by NewByVector** [comment]
那你需要区分拖动元素与连线元素了，总之，具备 magnet=true 的元素就是可以连线的。
