### ISSUE TITLE
dnd拖拽在mac开了三指拖拽后，需要点击两次才会触发getDropNode和validateNode事件

### ISSUE THREAD

**Issue by zhenghan2017** [antvis/X6#3114]
### 问题描述

dnd拖拽在mac开了三指拖拽后，需要点击两次才会触发getDropNode和validateNode事件

### 重现链接

https://codesandbox.io/s/dreamy-boyd-k2dztx?file=/src/App.js:1282-1294

### 重现步骤

1. 点击新增节点
2. 然后拖拽看控制台打印

### 预期行为

期望点一次即可

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.32.6]
- x6-react-shape版本: [1.4.5]

**Comment by NewByVector** [comment]
我在我的电脑试了一下，开启三指拖拽后，主要点击 1 次才会触发，你可以提供一些更详细的环境信息吗？

**Comment by NewByVector** [comment]
因为无法复现，先关闭这个 issue，如果能提供一个可以复现的 demo，请重新提一个 issue。
