### ISSUE TITLE
如何禁止节点拖动，可以画板全局拖动

### ISSUE THREAD

**Issue by zanmeipaul** [antvis/X6#312]
我有一个需求，编辑完有一个预览页面。 只显示图，不让节点拖动并能支持全局拖动位置。 是否有参数可以配置？文档没有看到

**Comment by bubkoo** [comment]
@zanmeipaul 看看 `interacting` 这个选项：https://x6.antv.vision/zh/docs/api/graph#interacting 。当编辑完成之后可以设置 `interacting` 中的 `nodeMovable` 选项为 `false`，这样节点就不能被移动。如果我理解的全局拖动是指拖拽画布的话，可以参看 Scroller 使用教程 https://x6.antv.vision/zh/docs/tutorial/basic/scroller，开启 `pannable` 就行。

**Comment by zanmeipaul** [comment]
@bubkoo   前面那个问题解决；后面使用 Scroller ，想把拖动条去掉，拖动能没有边界一直拖动，能实现吗？

![image](https://user-images.githubusercontent.com/20592867/99639799-094c2680-2a83-11eb-9997-ce62d3899f98.png)

**Comment by bubkoo** [comment]
@zanmeipaul 现在还不行，没有边界的画布必须借助 Scroller 组件，试试看是否可以通过定制 CSS 让滚动条不可见。

**Comment by NewByVector** [comment]
新的issue：https://github.com/antvis/X6/issues/339
