### ISSUE TITLE
导出功能 自定义组件导出的图片有问题

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3120]
### 问题描述

导出的样式与页面上的不匹配, 用的 有图表的 导出的是空白(用的 antv/g2plot)

### 重现链接

无

### 重现步骤

自定义注册任意 vue 组件

### 预期行为

可以与页面展示相符

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 2.1.4

### 屏幕截图或视频（可选）

<img width="215" alt="image" src="https://user-images.githubusercontent.com/39638510/211260231-3d15fade-1c9e-4633-81d2-42065a40be90.png">

### 实际导出的
<img width="343" alt="image" src="https://user-images.githubusercontent.com/39638510/211260270-94870dc6-d9e5-4ca4-b418-65f3f82ecee8.png">

**Comment by damnright** [comment]
样式表没有加进去
[https://x6.antv.vision/en/docs/tutorial/basic/graph/#stylesheet](url)

**Comment by JoeABCDEF** [comment]
> 
了解了
@damnright  大佬 在 请问 如果自定义组件是  图表的 导出空白是 什么情况 应该是咋处理
