### ISSUE TITLE
使用antvX6，拖拽渲染vue组件，有没有一种更好的方式，获取组件的宽高，并重置宽高

### ISSUE THREAD

**Issue by 565823371556Zsl** [antvis/X6#3121]
### 问题描述

使用antvX6，拖拽渲染vue组件，有没有一种更好的方式，获取组件的宽高，进行重置

使用dnd进行拖拽，必须对将节点的宽度和高度设置为和vue组件渲染后实际的宽度和高度一致，否则拖拽到画布上位置会闪现偏移，或者拖拽的时候vue组件显示不全

如果vue组件是写死的，倒还好说，可以将宽高写死。若vue组件中的内容是动态变化的，则必须等vue组件渲染完成后，获取其实际的宽高，然后再将宽高给节点，调用dndStart。

问题在于，调用dnd.start，才会渲染vue节点，此时虽能获取vue组件渲染完成后的实际宽高，但却无法更改拖拽的这个vue节点的宽高，我查阅了dnd的几个函数，发现没有拖拽的组件渲染完成后的回调

为了在调用dnd.start之前，获取vue组件的宽高，目前采用的方法是，在拖拽开始前，使用app.mount挂载一个app，在其中渲染即将拖拽的vue组件，获取其宽高，卸载app，将宽高赋给node节点，调用dnd.start

但是该方法感觉有些麻烦，所以想问一下有没有更好的办法

### 重现链接

暂无

### 重现步骤

1.在使用dnd.start(node,e)，若node的宽高，小于vue组件实际的宽高，vue组件会显示不完整，放置节点时位置会抖动
若node的宽高，大于vue组件实际的宽高，vue组件虽然显示完整，但放置节点时位置会抖动

### 预期行为

1.在拖拽出来节点的时候，有一个拖拽的节点渲染完成后的钩子函数，使用该钩子函数重置该节点的宽高
2.或者有其他更好的解决方法

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by lloydzhou** [comment]
你可以尝试将“vue组件渲染完成后，获取其实际的宽高，然后再将宽高给节点”这个逻辑放到你的自定义节点的逻辑里面应该就可以了。
如果你使用`@antv/x6-vue-shape`自定义节点，那么传进去的那个组件什么时候渲染好应该是可以知道的。在这个时间点去更新节点大小就可以了。
另外我自己的一个项目也有类似的功能，也有一个在内部的vue渲染完成后再更新节点大小的逻辑 [antv-x6-vue/src/VueShape.tsx](https://github.com/lloydzhou/antv-x6-vue/blob/master/src/VueShape.tsx#L35)
