### ISSUE TITLE
从其他页面切回画布，连线会偏移

### ISSUE THREAD

**Issue by donghuizhou** [antvis/X6#3124]
### 问题描述

如下图所示，
![image](https://user-images.githubusercontent.com/31002949/211444743-1c316ac3-bc4d-40f3-ba45-3363a819f20e.png)
![image](https://user-images.githubusercontent.com/31002949/211444965-fd2206ff-4604-415c-bd1d-1b2c1476164b.png)
页面顶部的tabs，控制画布页和表单也的显示/隐藏

### 重现链接

无

### 重现步骤

如图上所示

### 预期行为

希望无论tabs切来切去，画布上的连接始终在设置的连接桩上，不会发生偏移

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
切换 tabs 的时候，有什么操作呢？比如初始化画布或者销毁画布。
