### ISSUE TITLE
框选拖动空白区域无效？

### ISSUE THREAD

**Issue by grace-yue** [antvis/X6#3127]
### 问题描述

![image](https://user-images.githubusercontent.com/32642166/211705143-495ac55a-adc8-46b7-8803-0d572122022e.png)

### 重现链接

无

### 重现步骤

框选多选
框选区域，聚焦节点可以拖动，拖动空白区域框选就消失了，如图红色区域

### 预期行为

框选线范围内都可以移动

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
- 
"@antv/x6-plugin-selection": "^2.1.5",

**Comment by NewByVector** [comment]
对比下 drawio、keynote 等产品，其实都是拖拽节点的时候才能一起移动，这个是有特殊的场景要求吗？

**Comment by grace-yue** [comment]
> 对比下 drawio、keynote 等产品，其实都是拖拽节点的时候才能一起移动，这个是有特殊的场景要求吗？

感谢回复，这个没有特别的场景要求，就是这个选框范围（最外层蓝色线）包含了空白区域，但是直接拖动空白区域却会使得选框失效，感觉是不是有误导性了？

**Comment by NewByVector** [comment]
其实这种 `showNodeSelection` 是不推荐使用的，比较推荐实用 `className` 定义 select 样式，然后用 css 来定义每个节点的选中样式。
