### ISSUE TITLE
node节点导出svg片段

### ISSUE THREAD

**Issue by wangdi190** [antvis/X6#3129]
### 功能描述
const r1 = graph.createNode({
            shape: "rect",
            label: 'rect',
            width: 50,
            height: 60 });
请问r1如何导出下面这种svg的片段
`<g data-cell-id="a826cb1e-b76c-48d2-86cf-2aaf9e3b99d6" data-shape="rect" class="x6-cell x6-node" transform="translate(40,40)"><rect fill="#ffffff" stroke="#333333" stroke-width="2" width="120" height="60"></rect><text font-size="14" fill="#000000" text-anchor="middle" font-family="Arial, helvetica, sans-serif" transform="matrix(1,0,0,1,60,30)" xml:space="preserve"><tspan dy="0.3em" class="v-line">rect</tspan></text></g>
`
### 期望解决方案

我清楚怎么解决，希望能提供一个接口

**Comment by wangdi190** [comment]
<g data-cell-id="a826cb1e-b76c-48d2-86cf-2aaf9e3b99d6" data-shape="rect" class="x6-cell x6-node" transform="translate(40,40)"><rect fill="#ffffff" stroke="#333333" stroke-width="2" width="120" height="60"></rect><text font-size="14" fill="#000000" text-anchor="middle" font-family="Arial, helvetica, sans-serif" transform="matrix(1,0,0,1,60,30)" xml:space="preserve"><tspan dy="0.3em" class="v-line">rect</tspan></text></g>

**Comment by damnright** [comment]
`r1.findView(graph).container`

**Comment by wangdi190** [comment]
> `r1.findView(graph).container`

我想createNode的时候，就获取创建node的view，但为空。
graph.findView(r1) 这个是已经放到画布中了的。
相当于我是想做一个基于 node定义的 立即生成出svg。是一个编辑工具，通过修改node的json定义，然后得出svg

**Comment by NewByVector** [comment]
@wangdi190 createNode 的时候很多属性都无法确定，只有实际绘制的时候才能确定，所以在 createNode 中拿到 svg 片段是没法实现的。
