### ISSUE TITLE
dnd 可以设置代理画布的容器

### ISSUE THREAD

**Issue by siaikin** [antvis/X6#3132]
### 功能描述

我使用 web components 开发应用, 因此我的样式影响的区域只能在 shadow dom 中. 同时我使用 vue-shape 将自定义的 vue 组件作为拖拽节点.

但是我发现 dnd 创建的代理画布强制将自己添加在 document 下.
https://github.com/antvis/X6/blob/5c5f3e5319900340a42b9808bbc18269990f455b/packages/x6-plugin-dnd/src/index.ts#L68
这导致我的 vue 组件丢失了样式.

### 期望解决方案

可以自定义 dnd 创建的代理画布的容器.

**Comment by NewByVector** [comment]
可以使用 [draggingContainer](http://x6.antv.antgroup.com/tutorial/plugins/dnd#%E9%85%8D%E7%BD%AE) 配置。

**Comment by siaikin** [comment]
> 可以使用 [draggingContainer](http://x6.antv.antgroup.com/tutorial/plugins/dnd#%E9%85%8D%E7%BD%AE) 配置。

但我现在使用的是v1版本, 升级到v2需要做额外的工作.

**Comment by NewByVector** [comment]
@siaikin 提个 PR？

**Comment by NewByVector** [comment]
@siaikin 升级到 1.34.9 即可。
