### ISSUE TITLE
Background option in Graph canvas isn't applied as intended

### ISSUE THREAD

**Issue by harshaktg** [antvis/X6#3133]
### 问题描述

On applying the backgorund option while initialising the Graph, it gets applied to both `.x6-graph-scroller-background` as well as `.x6-graph-background`

So the problem here is the grid (spots) in the graph are hidden when the background color style is applied to `.x6-graph-background`

![image](https://user-images.githubusercontent.com/40317596/211986750-86303c5f-d9be-47eb-b424-ef44fd689ecc.png)

### 重现链接

NA

### 重现步骤

Initialise a Graph object with any background color. You'll be able to see a visible difference

### 预期行为

Ideally, the background property should not be applied to `.x6-graph-background`, and that will make sure grid is visible throughout along with the expected color

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
The grid is at a higher level than background, so theoretically your question should not arise. Can you provide a reproducible demo？

**Comment by jrs64** [comment]
> This problem occurs when Scroller is enabled

![Screenshot 2023-01-30 at 14 39 53](https://user-images.githubusercontent.com/44115045/215405757-eee2fde8-d36e-4919-a528-dd544f650ce1.png)

**Comment by jrs64** [comment]
@NewByVector https://codesandbox.io/s/damp-frog-f1kowr
<img width="1105" alt="Screenshot 2023-01-30 at 15 15 17" src="https://user-images.githubusercontent.com/44115045/215411452-8a8b11ff-32c4-4849-85ef-6eb1e20db934.png">
