### ISSUE TITLE
Padding option in centerCell method isn't working inX6 v2

### ISSUE THREAD

**Issue by harshaktg** [antvis/X6#3134]
### Describe the bug

`graph.centerCell(cell, { padding: { top: 300 } })`, is something which we use, and we upgraded X6 version, it all stopped working

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

Position a cell using padding option, it wouldn't work

### Expected behavior

Padding should be applied properly

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
Can you provide a reproducible codesanox？

**Comment by harshaktg** [comment]
Here's the sandbox [link](https://codesandbox.io/s/sad-murdock-68ec6r?file=/index.ts)

Please make sure you drag the node in the graph, and then click on center button on the right to center it

![image](https://user-images.githubusercontent.com/40317596/216909124-14f32665-e5da-48df-a81b-0a3c74630ceb.png)
