### ISSUE TITLE
The "@antv/x6-vue-shape" plug-in is introduced. After the output is packaged through vue-cli3.0, the page cannot run

### ISSUE THREAD

**Issue by foreverYyx** [antvis/X6#3136]
### Describe the bug

Project upgrade 2.0, import '@antv/x6-vue-shape' plug-in, through the vue-cli3.0 scaffolding package output, the page running console error "Cannot read properties of undefined (reading 'warn')"

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

1. Use vue-cli3.0 scaffolding to build the project
2. Install X6(2.0) plug-ins and import plug-ins
3. run build packages using npm
4. Preview the static html in a browser
5. Open the browser console, and an error message is displayed

### Expected behavior

Project upgrade 2.0, import "@antv/x6-vue-shape" plug-in, pack output through vue-cli3.0 scaffolding, page running console error "cannot read undefined properties (read as' warning ')"

### Screenshots or Videos

Import the "@antv/x6-vue-shape" plug-in and output it through the vue-cli3.0 scaffolding package.  The page runs normally and no error is reported by the console.

### Platform

- OS: Windows
- Browser: Chrome
- Version: [Chrome 107.0.5304.88]

**Comment by foreverYyx** [comment]
您好  邮件已收到！谢谢

**Comment by NewByVector** [comment]
Can you provide a demo that can be reproduced？

**Comment by foreverYyx** [comment]
您好  邮件已收到！谢谢
