### ISSUE TITLE
关于官方demo https://x6.antv.vision/zh/examples/showcase/practices#mindmap resetCell闪屏问题

### ISSUE THREAD

**Issue by aBrightWorld** [antvis/X6#3138]
### 问题描述

使用内置节点闪屏不明显，一旦使用自定义的节点 （我用的是vue-shape）就会明显闪屏，

### 重现链接

https://x6.antv.vision/zh/examples/showcase/practices#mindmap

### 重现步骤

1

### 预期行为

有一种新的方法，可以直接更新节点，就像g6 updataChildren 那样局部更新

### 平台

- 操作系统: [macOS, ]
- 网页浏览器: [Chrome]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以使用 `prop` 等方法更新单个节点，参考[文档](http://x6.antv.antgroup.com/tutorial/basic/node#%E4%BF%AE%E6%94%B9%E8%8A%82%E7%82%B9)。

**Comment by lloydzhou** [comment]
这里需要使用一个布局算法自动计算位置，所以需要在自己的组件里面维护整个图数据。然后需要实现一个**增量**（包含增删改，有点类似大多数前端框架的vdom的diff逻辑）更新图数据渲染到x6画布的逻辑。

> @NewByVector 之前我提过一个xflow的抽象需要到节点这一层。如果抽象到这一层，那就是把这里的“diff”逻辑交给react去处理。

我计划抽空更新一下这个demo
