### ISSUE TITLE
cell.getProp("position") 不做拷贝 直接使用 会影响 页面 节点位置更新

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3140]
### 问题描述

<img width="785" alt="image" src="https://user-images.githubusercontent.com/39638510/212521099-c27db1e2-0be0-4156-b435-efa8e4638d9d.png">
<img width="220" alt="image" src="https://user-images.githubusercontent.com/39638510/212520739-fb3bf686-1ae4-4eb3-b0e8-232f17456445.png">

```Typescript
// 未做拷贝 前这样更新页面 位置未做更新
const position = cell.getProp("position");

// 拷贝后 更新位置页面位置才会更新
const position = { ...cell.getProp("position") };

position[positionKey] += distance;

cell.setProp({ position });
```
需求是 通过上下左右键进行微调 更新成功的了 但是页面中 节点 的位置没有更新 没有更新

### 重现链接

无

### 重现步骤

cells.forEach(cell => {
      // 只要是 不做拷贝 就会有这问题
      const position = cell.getProp("position");

      position[positionKey] += distance;

      cell.setProp({ position });
  });

### 预期行为

可以正常使用

### 平台

- 操作系统: macOS
- 网页浏览器: Chrome
- X6 版本: 2.1.4

**Comment by NewByVector** [comment]
能否搞一个可以复现的 codesanbox，我这里重现一下，是可以更新的。

**Comment by JoeABCDEF** [comment]
> 能否搞一个可以复现的 [codesanbox](https://codesandbox.io/s/mo-ban-wchooy)，我这里重现一下，是可以更新的。
@NewByVector 
 [demo](https://codesandbox.io/s/mo-ban-forked-kjqoh3?file=/src/App.tsx)

<img width="787" alt="image" src="https://user-images.githubusercontent.com/39638510/215240801-2d8b1fff-bc1b-4c12-abf7-dd44f8db7754.png">

**Comment by NewByVector** [comment]
因为你设置的 ppsition 对象和节点本身的 position 对象引用是一致的，无法对比出差异，所以不会移动。正确写法：
```ts
cell.setProp({ position: {
 ...position,
  [positionKey]: position[positionKey] + distance 
}});
```
