### ISSUE TITLE
希望能提供和use相对应卸载组件的函数

### ISSUE THREAD

**Issue by lloydzhou** [antvis/X6#3142]
### 功能描述

当前的实现里面只有启用组件的use函数，期望能提供一个相对应的动态卸载组件的函数。
希望能通过这两个对应的函数，能做到动态的加载和卸载组件。

### 期望解决方案

我看了看现在的代码，只有一个use函数和getPlugin函数。另外似乎可以通过`plugin.dispose()`禁用功能，但是一旦禁用，似乎就不能再次启用。

所以，这里应该再提供一个卸载的函数，使得这个地方功能完备。

![image](https://user-images.githubusercontent.com/1826685/212548773-0b68040f-36fa-4cd8-a66e-afde6a06f37f.png)

**Comment by NewByVector** [comment]
其实就是提供一个卸载的方法，插件的启动和禁用都有配套的 `enable` 和 `disable` 方法。

**Comment by songhuijin** [comment]
请问和use相对应卸载组件的函数已经添加了嘛，目前看到了 enable 和 disable 方法，但是卸载小地图minimap没看到呢
