### ISSUE TITLE
render:done isn't working in X6 v2

### ISSUE THREAD

**Issue by harshaktg** [antvis/X6#3145]
### Describe the bug

I upgraded the version of X6 v1 to v2, and all of a sudden, I'm not able to access this `render:done` graph event.

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

Listen to `render:done` event and keep a debugger. You will not see that callback being called

### Expected behavior

It was supposed to execute the callback. Or is there any other better way to know if the graph has been fully rendered or not?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
Repeat with https://github.com/antvis/X6/issues/3085.
