### ISSUE TITLE
jumpover  连接同一平行节点，效果不同

### ISSUE THREAD

**Issue by grace-yue** [antvis/X6#3149]
### 问题描述

如截图所示，同一节点连向对齐的两个节点，但是连线交叉效果不同

### 重现链接

无

### 重现步骤

connector: {
    name: 'jumpover',
    args: {
      type: 'arc'
    }
  }

### 预期行为

两者效果应该相同

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

"@antv/x6": "^2.1.3",

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/32642166/212799755-da48c460-8e2d-4eee-b708-ae1241b08e0c.png)

**Comment by NewByVector** [comment]
我本地测试是好的，能否提供一个可以复现 demo。
![image](https://user-images.githubusercontent.com/20186737/216225740-d251a2bb-aa6b-4463-8c0c-d51eff5cea87.png)

**Comment by 18663872803** [comment]
![image](https://github.com/antvis/X6/assets/24237367/410d83ef-7a2e-48a4-9cb2-c7e4238170d1)
遇到类似的问题，经过同一路径节点，出现了跳线。demo代码如下：
