### ISSUE TITLE
V2.x 滚动画布的交互能否保持和 V1.x 一致

### ISSUE THREAD

**Issue by haohaio** [antvis/X6#3152]
### Describe the feature you'd like to request

V2.x 滚动画布的交互和 V1.x 保持一致。设置显示 grid 时，整个区域都显示 grid，滚动区域都是可操作的画布返回。

- 按照 V2.x 的交互，从 Stencil 拖动节点添加到画布时，只能拖动到画布区域
- 还需移动节点才能扩大画布范围，这种交互感觉并不友好
- 设置显示 grid 时，非画布区域网格点的样式反而更像是可操作的画布区域

### Describe the solution you'd like

V2.x 滚动画布的交互和 V1.x 保持一致

### Describe alternatives you've considered

- 设置显示 grid 时，仅画布区域显示网格点
- 从 Stencil 拖动节点添加到画布时，拖动到非画布范围时，自动扩充画布
- 移动节点扩充画布时，支持配置距离画布边界的距离阈值，离一定距离就触发

**Comment by jrs64** [comment]
升级2.0后，同样有这个问题

**Comment by haohaio** [comment]
升级到 2.2.1 版本后，交互方式并没有变化

**Comment by NewByVector** [comment]
@haohaio 确实没发包 估计机器人出 bug 了，我重新发布一下。

**Comment by NewByVector** [comment]
@haohaio 确实没发包 估计机器人出 bug 了，我重新发布一下。

**Comment by NewByVector** [comment]
@haohaio 升级到 @antv/x6-plugin-scroller@2.0.8
