### ISSUE TITLE
Stencil fullscreen mode, ::backdrop

### ISSUE THREAD

**Issue by lexoring** [antvis/X6#3157]
### Describe the bug

Hello. I am using Stencil. When I go into full screen mode I drag elements from Stencil to the graph window and during this dragging, the element itself is not visible. But when I release the left click, the element appears in the graph window.
If you do not use full screen, then everything is fine.

The whole problem is that when full screen mode is used, the browser adds the ::backdrop pseudo-element to the body, which does not show the div elements below. And while dragging an element into the window, it is just created below the ::backdrop pseudo-element. About the backdrop element https://developer.mozilla.org/ru/docs/Web/CSS/::backdrop

### Your Example Website or App

https://codesandbox.io/s/dreamy-jackson-ol3b2k?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1. I go to the test page https://ol3b2k.csb.app/
2. click on the fullscreen button
3. drag and drop elements onto the graph
4. during dragging, the element is not visible, it is hidden.

### Expected behavior

the element should be visible while dragging

### Screenshots or Videos

[recording (4).webm](https://user-images.githubusercontent.com/74623056/213266135-7248e386-d958-46a3-ba84-3821d0eb3663.webm)

### Platform

- OS: [Windows, Linux]
- Browser: [Chrome]
- Version: [109.0.5414.75]

**Comment by struggleRoue** [comment]
![image](https://user-images.githubusercontent.com/47975400/213342123-c0bc0089-2a22-42ce-853b-8b6131367f67.png)
hi,  you can refer to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen)
because this element is not in your element that used requestFullscreen()

**Comment by lexoring** [comment]
> Stencil

that's the thing, I can't control the "x6-widget-dnd dragging" class, it is created and deleted by the Stencil component.

All ant tips are also created, and they are also created at the bottom of the body and outside of my div.

And since it is created outside, it becomes outside the ::[backdrop ](https://developer.mozilla.org/ru/docs/Web/CSS/::backdrop) pseudo-element and is therefore not visible.
It is necessary to edit the Stencil ant component.
![6](https://user-images.githubusercontent.com/74623056/213435686-2969de26-a628-4f58-a34a-6eb51a735f1e.png)

**Comment by lexoring** [comment]
then the "x6-widget-dnd dragging" class was removed after the drag was finished.

![7](https://user-images.githubusercontent.com/74623056/213437486-fe5f4ef9-d8b9-4efe-96e4-d409f47c0058.png)

**Comment by struggleRoue** [comment]
you can use the draggingContainer param
![image](https://user-images.githubusercontent.com/47975400/213691742-6c7c6944-f803-4acf-b695-bc6df02ddf9b.png)

**Comment by struggleRoue** [comment]
> you can use the draggingContainer param ![image](https://user-images.githubusercontent.com/47975400/213691742-6c7c6944-f803-4acf-b695-bc6df02ddf9b.png)

but, current x6 use position: absolute
![image](https://user-images.githubusercontent.com/47975400/213695693-605857ae-a6b1-4a7c-812a-4d6c03404764.png)
so you need to make sure your position is not apper problem.

**Comment by lexoring** [comment]
> > вы можете использовать параметр draggingContainer![изображение](https://user-images.githubusercontent.com/47975400/213691742-6c7c6944-f803-4acf-b695-bc6df02ddf9b.png)
> 
> но текущая позиция использования x6: абсолютная , поэтому вам нужно убедиться, что ваша позиция не является проблемой. ![изображение](https://user-images.githubusercontent.com/47975400/213695693-605857ae-a6b1-4a7c-812a-4d6c03404764.png)

excellent thank you.
I added a draggingContainer for the stencil and fixed the position. With an absolute position, the work is incorrect.
```
  .x6-widget-dnd.dragging {
    position: fixed;
  }
```

**Comment by lexoring** [comment]
Now another problem. I use the Tulbar component https://x6.antv.vision/zh/docs/api/ui/toolbar
And with a full screen, the hints are not displayed. An example here https://ol3b2k.csb.app/ or https://codesandbox.io/s/dreamy-jackson-ol3b2k?file=/SRC/App.TSX

[recording (5).webm](https://user-images.githubusercontent.com/74623056/213868262-1bc0d0bd-5e4a-4582-81e8-afdcf1f4dc35.webm)

**Comment by struggleRoue** [comment]
> Now another problem. I use the Tulbar component https://x6.antv.vision/zh/docs/api/ui/toolbar And with a full screen, the hints are not displayed. An example here https://ol3b2k.csb.app/ or https://codesandbox.io/s/dreamy-jackson-ol3b2k?file=/SRC/App.TSX
> 
>  recording.5.webm
![image](https://user-images.githubusercontent.com/47975400/213869146-1c6ff5ba-7773-458d-b8b5-63110ec7a133.png)
it it look at is problem for antd

**Comment by struggleRoue** [comment]
you can try use the params with tooltipProps:  { getPopupContainer } for component that Item.

**Comment by lexoring** [comment]
> you can try use the params with tooltipProps: { getPopupContainer } for component that Item.

Thanks for your help, this is what I did:
```
      <Item
        name="zoomAdd"
        icon={<ZoomInOutlined />}
        tooltipProps={{
          getPopupContainer: (trigger) =>
            popupContainer
        }}
      />
```
