### ISSUE TITLE
React Portal功能不管用，渲染不出来，并且官网的Code sandbox例子也渲染不出来

### ISSUE THREAD

**Issue by codebdy** [antvis/X6#3160]
### Describe the bug

Portal下不渲染组件

### Your Example Website or App

https://codesandbox.io/s/2xqp7j?file=/App.tsx:1389-1410

### Steps to Reproduce the Bug or Issue

直接打开官网Code sandbox例子：
https://codesandbox.io/s/2xqp7j?file=/App.tsx:1389-1410

### Expected behavior

希望能够渲染组件

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
web

**Comment by NewByVector** [comment]
在 codesanbox 上面在初始化画布的时候需要设置 width 和 height 才能出现。

**Comment by rxdrag** [comment]
> 在 codesanbox 上面在初始化画布的时候需要设置 width 和 height 才能出现。还有一点就是 antd 的样式没有加载，导致进度条显示异常。

我本地放在对话框里渲染不出来，是不是需要设置zIndex？

**Comment by rxdrag** [comment]
![image](https://user-images.githubusercontent.com/18096128/213405406-98be698b-45b3-456f-a5c7-44e2dc74f5c2.png)
拖动的时候能渲染，放入画布就消失了

**Comment by NewByVector** [comment]
上面说到的在 codesanbox 中显示不正确问题，是文档的缺陷，已经新提了一个 [issue](https://github.com/antvis/X6/issues/3176)。你提的第二个问题，在对话框中不能正确显示，能否提供一个可以复现的 demo？

**Comment by rxdrag** [comment]
> 上面说到的在 codesanbox 中显示不正确问题，是文档的缺陷，已经新提了一个 [issue](https://github.com/antvis/X6/issues/3176)。你提的第二个问题，在对话框中不能正确显示，能否提供一个可以复现的 demo？

等文档修复了，我fork一个官网例子，在这个基础上修改重现，现在还不确定是哪里的问题
