### ISSUE TITLE
React组件的事件怎转发

### ISSUE THREAD

**Issue by codebdy** [antvis/X6#3161]
### 问题描述

版本1的时候可以这样直接把事件传出来：
![image](https://user-images.githubusercontent.com/18096128/213407093-aad07af2-8043-457f-9830-65f2dc576fe3.png)
版本2.0以后这种需求怎么实现？

### 重现链接

无

### 重现步骤

API文档没有发现相关描述

### 预期行为

希望找到解决方案

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
web

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/18096128/213407543-24cdae22-d0df-4d3f-b918-2790471e0b55.png)

**Comment by NewByVector** [comment]
可以通过 x6 的事件中转一下，比如：
```tsx
const NodeComponent = ({ node }: { node: Node }) => {
  return (
    <div onClick={() => node.trigger('custom-event')}>
      test
    </div>
  )
}
```

**Comment by rxdrag** [comment]
> 可以通过 x6 的事件中转一下，比如：
> 
> ```tsx
> const NodeComponent = ({ node }: { node: Node }) => {
>   return (
>     <div onClick={() => node.trigger('custom-event')}>
>       test
>     </div>
>   )
> }
> ```

非常感谢，抽时间试试

**Comment by basala** [comment]
> > 可以通过 x6 的事件中转一下，比如：
> > ```tsx
> > const NodeComponent = ({ node }: { node: Node }) => {
> >   return (
> >     <div onClick={() => node.trigger('custom-event')}>
> >       test
> >     </div>
> >   )
> > }
> > ```
> 
> 非常感谢，抽时间试试

你好，请问你的问题解决了嘛，我碰到了类似的问题，用上面给的例子，在外面用 graph.on("node:customevent")监听不到

**Comment by basala** [comment]
> 可以通过 x6 的事件中转一下，比如：
> 
> ```tsx
> const NodeComponent = ({ node }: { node: Node }) => {
>   return (
>     <div onClick={() => node.trigger('custom-event')}>
>       test
>     </div>
>   )
> }
> ```

你好，请问在graph上监听是通过graph.on("node:customevent")来进行监听吗，我这样写没有触发

**Comment by rxdrag** [comment]
> ```tsx
> node.trigger(
> ```

我刚开始没试，觉得有道理就关了，现在试了一下，还没成功

**Comment by rxdrag** [comment]
> > 可以通过 x6 的事件中转一下，比如：
> > ```tsx
> > const NodeComponent = ({ node }: { node: Node }) => {
> >   return (
> >     <div onClick={() => node.trigger('custom-event')}>
> >       test
> >     </div>
> >   )
> > }
> > ```
> 
> 你好，请问在graph上监听是通过graph.on("node:customevent")来进行监听吗，我这样写没有触发

目前暂时通过js事件系统来解决：
![image](https://user-images.githubusercontent.com/18096128/222957174-24ef44ba-e572-4ab6-910f-16fb158916da.png)

**Comment by NewByVector** [comment]
```ts
graph.trigger('event1')
graph.on('event1', () => {})
```
