### ISSUE TITLE
2.0文档搜索不管用

### ISSUE THREAD

**Issue by codebdy** [antvis/X6#3162]
### 问题描述

使用2.0的时候，文档搜索全部被定位到这个页面：
https://x6.antv.antgroup.com/tutorial/about#%E6%BC%94%E7%A4%BA

### 重现链接

https://x6.antv.antgroup.com/tutorial/about#%E6%BC%94%E7%A4%BA

### 重现步骤

搜索文档，点击搜索选项

### 预期行为

跳转到合适页面

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
web

**Comment by NewByVector** [comment]
2.x 文档目录有调整，现在看起来 algolia 的搜索内容还是老的，没有发生变化。

**Comment by NewByVector** [comment]
https://github.com/antvis/dumi-theme-antv/issues/203

**Comment by NewByVector** [comment]
与 https://github.com/antvis/X6/issues/3353 重复。
