### ISSUE TITLE
希望能拿到Port的点击事件

### ISSUE THREAD

**Issue by rxdrag** [antvis/X6#3163]
### 问题描述

从文档看，现在的port好像没有点击事件，怎么能拿到port的点击事件？

### 重现链接

无

### 重现步骤

看文档

### 预期行为

拿到port点击事件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
web

**Comment by NewByVector** [comment]
2.x 版本已经增加 `node:port:click` 事件，在 1.x 版本中可以通过监听 `node:click` 事件，然后判断 e.target 是否在连接桩内部来判断是否是连接桩点击。

**Comment by rxdrag** [comment]
> node:port:click

谢谢
