### ISSUE TITLE
1.34.6 版本，群组组件中节点manhattan连线初始渲染错误

### ISSUE THREAD

**Issue by tianjinhao** [antvis/X6#3173]
### 问题描述

画布连线使用router为manhattan模式，当节点位于群组组件中时，与其连接的节点的边，在初始渲染进入时显示错误，此时需要移动一下群组组件才可恢复正常；
v2版本没有这个问题；

### 重现链接

https://codesandbox.io/s/flamboyant-tdd-w8v5db?file=/package.json:74-80

### 重现步骤

1、进入页面；
2、此时连线不是manhattan模式；
3、需要移动一下群组组件，连线才会恢复正常；

若将package.json 中@antv/x6版本改为latest, 然后刷新页面，此时manhattan连线正常显示

### 预期行为

我期望连线router可以正常按照manhattan模式显示；
但是连线router显示有误；

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome 108.0.5359.124]
- X6 版本: [1.34.6 ]

**Comment by NewByVector** [comment]
1.x 现阶段的解决方案是：
1. 升级到最新版本
2. 使用 manhattan 的配置 excludeNodes 排除 group 节点的影响
```ts
const graph = new Graph({
  connecting: {
    router: {
      name: 'manhattan',
      args: {
        excludeNodes: ['da8c3549-f249-4bad-9fc4-bf951e3c2925']
      }
    }
  }
})
```

**Comment by tianjinhao** [comment]
> 

非常感谢，我查看了下文档，1.x版本excludeNodes只支持Node[]类型，不过我使用了excludeShapes，成功解决，多谢

**Comment by NewByVector** [comment]
昨天我发布了一个新的版本 1.34.9，已经支持了
