### ISSUE TITLE
怎么给桩（Port）的label加背景色？

### ISSUE THREAD

**Issue by rxdrag** [antvis/X6#3174]
### 问题描述

桩的label有时候会跟线重叠，怎么给桩的label加一个背景色遮挡一下？

### 重现链接

无

### 重现步骤

看文档

### 预期行为

希望能有背景色

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
web

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/18096128/215385267-c7e71db4-52ef-475c-8b87-7d06bf16bb01.png)

**Comment by struggleRoue** [comment]
http://x6.antv.antgroup.com/examples/node/group/#collapsable

**Comment by rxdrag** [comment]
> http://x6.antv.antgroup.com/examples/node/group/#collapsable

这个是普通label，不是桩的label

**Comment by struggleRoue** [comment]
那你可以给label定义markup

**Comment by struggleRoue** [comment]
http://x6.antv.antgroup.com/tutorial/basic/port

**Comment by rxdrag** [comment]
> 那你可以给label定义markup

不太会定义markup，研究一下，非常感谢

**Comment by rxdrag** [comment]
哎，没搞出来，有没有大佬有简单代码，参考一下

**Comment by NewByVector** [comment]
@rxdrag 参考这个 [demo](https://codesandbox.io/s/mo-ban-wchooy?file=/src/App.tsx)。

**Comment by rxdrag** [comment]
> @rxdrag 参考这个 [demo](https://codesandbox.io/s/mo-ban-wchooy?file=/src/App.tsx)。

谢谢，但是这个是Edge的label，我这边可以处理，就是处理不了port的label背景

**Comment by rxdrag** [comment]
> @rxdrag 参考这个 [demo](https://codesandbox.io/s/mo-ban-wchooy?file=/src/App.tsx)。

![image](https://user-images.githubusercontent.com/18096128/216735712-b3eae363-19fc-4c6a-b231-09290040ff44.png)
我这么用不行

**Comment by NewByVector** [comment]
port 的选择器不是 rect，应该是 circle。

**Comment by rxdrag** [comment]
> port 的选择器不是 rect，应该是 circle。

circle只能选择port，选择不了port的标签，怎么给port的标签加个个背景啊？

**Comment by NewByVector** [comment]
@rxdrag 参考这个 [demo](https://codesandbox.io/s/port-label-viwnos)
