### ISSUE TITLE
allowMulti设置为true 依然不能在 相同的 起始节点 和 终止节点之间 创建多条边

### ISSUE THREAD

**Issue by h5-Old-driver** [antvis/X6#3184]
### 问题描述

我在 connecting中配置了 allowMulti 为 true  但是 两个节点之间依然不能够创建多条连线  
`connecting: {
                  allowBlank: false,
                  allowMulti: true,
                  allowLoop: true,
                  allowNode: false,
                  allowEdge: false,
                  highlight: true,
                  connector: 'rounded',
                  snap: true,},`

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

两个节点之间 可以有多条边相连  

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/81205631/215707535-ecd5597b-299f-4160-ae01-670ae901bfe7.png)

**Comment by NewByVector** [comment]
请提供一个可以复现的 demo。
