### ISSUE TITLE
2.x开启画布滚动之后，stencil中的节点无法拖拽至画布上

### ISSUE THREAD

**Issue by ylxylxylx** [antvis/X6#3188]
### 问题描述

未开启画布滚动前，可正常拖拽节点至画布上，开启画布滚动之后就不行了

### 重现链接

https://codesandbox.io/s/stupefied-kirch-ob3ucl?file=/src/App.vue

### 重现步骤

1.进入页面
2.把stencil中的节点向画布拖拽
3.鼠标松开时，节点消失，无法拖拽至画布中

### 预期行为

希望可以正常拖拽至画布中

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

[Vite-App.webm](https://user-images.githubusercontent.com/87469737/215990316-1e34a47c-1280-4d59-90f9-027281e0d565.webm)

**Comment by ylxylxylx** [comment]
更新至2.2.1版本仍存在这个问题

**Comment by NewByVector** [comment]
@ylxylxylx 没有发布新的版本， 估计机器人出 bug 了，我重新发布一下。

**Comment by NewByVector** [comment]
@ylxylxylx 升级到 @antv/x6-plugin-scroller@2.0.8
