### ISSUE TITLE
stencil.load() 在有group的情况下，无法按照顺序load， group始终会在最前面。

### ISSUE THREAD

**Issue by IcarusRyy** [antvis/X6#3194]
### Describe the bug

import React from "react";
import { Graph, Addon, Shape, Node } from "@antv/x6";
import "./app.css";

const { Stencil } = Addon;
const { Rect, Circle } = Shape;
class NodeGroup extends Node {
  private collapsed: boolean =
    (this.store as any)?.data.attrs.buttonSign.d === "M 1 5 9 5 M 5 1 5 9";
  private expandSize: { width: number; height: number } = {
    width: (this.store as any)?.data.attrs.expandSize?.width || 100,
    height: (this.store as any)?.data.attrs.expandSize?.height || 36
  };

  protected postprocess() {
    this.toggleCollapse(
      (this.store as any)?.data.attrs.buttonSign.d === "M 1 5 9 5 M 5 1 5 9"
    );
  }

  isCollapsed() {
    return this.collapsed;
  }

  toggleCollapse(collapsed?: boolean) {
    const target = collapsed == null ? !this.collapsed : collapsed;
    if (target) {
      // this.attr('buttonSign', { d: 'M 1 5 9 5 M 5 1 5 9' })
      this.expandSize = this.getSize();
      this.resize(100, 36);
    } else {
      // this.attr('buttonSign', { d: 'M 2 5 8 5' })
      if (this.expandSize) {
        this.resize(this.expandSize.width, this.expandSize.height);
      }
    }
    this.collapsed = target;
  }
}

NodeGroup.config({
  shape: "rect",
  markup: [
    {
      tagName: "rect",
      selector: "body"
    },
    {
      tagName: "text",
      selector: "label"
    },
    {
      tagName: "g",
      selector: "buttonGroup",
      children: [
        {
          tagName: "rect",
          selector: "button",
          attrs: {
            "pointer-events": "visiblePainted"
          }
        },
        {
          tagName: "path",
          selector: "buttonSign",
          attrs: {
            fill: "none",
            "pointer-events": "none"
          }
        }
      ]
    }
  ],
  attrs: {
    body: {
      refWidth: "100%",
      refHeight: "100%",
      strokeWidth: 1,
      fill: "#ffffff",
      stroke: "none"
    },
    buttonGroup: {
      refX: 8,
      refY: 8
    },
    // button: {
    //   height: 14,
    //   width: 16,
    //   rx: 2,
    //   ry: 2,
    //   fill: '#f5f5f5',
    //   stroke: '#ccc',
    //   cursor: 'pointer',
    //   event: 'node:collapse',
    // },
    buttonSign: {
      refX: 3,
      refY: 2,
      stroke: "#808080"
    }
  },
  ports: {
    groups: {
      top: {
        position: "top",
        attrs: {
          circle: {
            r: 5,
            magnet: true,
            stroke: "#5F95FF",
            strokeWidth: 1,
            fill: "#fff",
            style: {
              visibility: "hidden"
            }
          }
        }
      },
      right: {
        position: "right",
        attrs: {
          circle: {
            r: 5,
            magnet: true,
            stroke: "#5F95FF",
            strokeWidth: 1,
            fill: "#fff",
            style: {
              visibility: "hidden"
            }
          }
        }
      },
      bottom: {
        position: "bottom",
        attrs: {
          circle: {
            r: 5,
            magnet: true,
            stroke: "#5F95FF",
            strokeWidth: 1,
            fill: "#fff",
            style: {
              visibility: "hidden"
            }
          }
        }
      },
      left: {
        position: "left",
        attrs: {
          circle: {
            r: 5,
            magnet: true,
            stroke: "#5F95FF",
            strokeWidth: 1,
            fill: "#fff",
            style: {
              visibility: "hidden"
            }
          }
        }
      }
    },
    items: [
      {
        group: "top"
      },
      {
        group: "right"
      },
      {
        group: "bottom"
      },
      {
        group: "left"
      }
    ]
  }
});
export default class Example extends React.Component {
  private container: HTMLDivElement;
  private stencilContainer: HTMLDivElement;

  componentDidMount() {
    const graph = new Graph({
      container: this.container,
      grid: true,
      snapline: {
        enabled: true,
        sharp: true
      },
      scroller: {
        enabled: true,
        pageVisible: false,
        pageBreak: false,
        pannable: true
      }
    });

    const source = graph.addNode({
      x: 130,
      y: 30,
      width: 100,
      height: 40,
      attrs: {
        label: {
          text: "Hello",
          fill: "#6a6c8a"
        },
        body: {
          stroke: "#31d0c6"
        }
      }
    });

    const target = graph.addNode({
      x: 320,
      y: 240,
      width: 100,
      height: 40,
      attrs: {
        label: {
          text: "World",
          fill: "#6a6c8a"
        },
        body: {
          stroke: "#31d0c6"
        }
      }
    });

    graph.addEdge({ source, target });

    graph.centerContent();
    const gr = new NodeGroup({
      shape: "groupNode",
      x: 0,
      y: 0,
      width: 100,
      height: 100,
      zIndex: -10,
      attrs: {
        body: {
          rx: 4,
          ry: 4
        },
        "edit-text": {
          title: "组"
        },
        text: {
          fontSize: 12,
          textWrap: {
            text: "组",
            code: "group",
            width: +73
          },
          refX: "50%",
          refY: "50%",
          textAnchor: "middle",
          textVerticalAnchor: "middle"
        }
        // buttonSign: {
        //   d: 'M 2 5 8 5',
        // },
      },
      data: {
        parent: true
      }
    });
    const stencil = new Stencil({
      title: "Components",
      target: graph,
      search(cell, keyword) {
        return cell.shape.indexOf(keyword) !== -1;
      },
      placeholder: "Search by shape name",
      notFoundText: "Not Found",
      collapsable: true,
      stencilGraphWidth: 200,
      stencilGraphHeight: 180,
      groups: [
        {
          name: "group1",
          title: "Group(Collapsable)"
        },
        {
          name: "group2",
          title: "Group",
          collapsable: false
        }
      ]
    });

    this.stencilContainer.appendChild(stencil.container);

    const r = new Rect({
      width: 70,
      height: 40,
      attrs: {
        rect: { fill: "#31D0C6", stroke: "#4B4A67", strokeWidth: 6 },
        text: { text: "rect", fill: "white" }
      }
    });

    const c = new Circle({
      width: 60,
      height: 60,
      attrs: {
        circle: { fill: "#FE854F", strokeWidth: 6, stroke: "#4B4A67" },
        text: { text: "ellipse", fill: "white" }
      }
    });

    const c2 = new Circle({
      width: 60,
      height: 60,
      attrs: {
        circle: { fill: "#4B4A67", "stroke-width": 6, stroke: "#FE854F" },
        text: { text: "ellipse", fill: "white" }
      }
    });

    const r2 = new Rect({
      width: 70,
      height: 40,
      attrs: {
        rect: { fill: "#4B4A67", stroke: "#31D0C6", strokeWidth: 6 },
        text: { text: "rect", fill: "white" }
      }
    });

    const r3 = new Rect({
      width: 70,
      height: 40,
      attrs: {
        rect: { fill: "#31D0C6", stroke: "#4B4A67", strokeWidth: 6 },
        text: { text: "rect", fill: "white" }
      }
    });

    const c3 = new Circle({
      width: 60,
      height: 60,
      attrs: {
        circle: { fill: "#FE854F", strokeWidth: 6, stroke: "#4B4A67" },
        text: { text: "ellipse", fill: "white" }
      }
    });

    stencil.load([r, c, gr], "group1");
    stencil.load([r2, r3, c3, gr], "group2");
  }

  refContainer = (container: HTMLDivElement) => {
    this.container = container;
  };

  refStencil = (container: HTMLDivElement) => {
    this.stencilContainer = container;
  };

  render() {
    return (
      <div className="app">
        <div className="app-stencil" ref={this.refStencil} />
        <div className="app-content" ref={this.refContainer} />
      </div>
    );
  }
}

### Your Example Website or App

https://codesandbox.io/s/angry-euler-qj3bud?file=/src/app.tsx:0-7776

### Steps to Reproduce the Bug or Issue

设置stencil.load()  数组内的元素的位置，可以确定渲染的顺序
但是在有gourp的情况，将group元素放在最后，渲染的结果依然是在最前面

### Expected behavior

希望group元素按照元素在数组的位置进行依次渲染

### Screenshots or Videos

https://loc.dingtalk.com/L1VzZXJzL2FwcGxlL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy8xMTk5MDMyMDQ5X3YyL0ltYWdlRmlsZXMvMTY3NTMwOTgwNDc4M18yMjk5MTJCRS02RjNDLTRFNkQtQkI4Ni1ERTMwQkNGMDVCRDAucG5n?renderWidth=1218&renderHeight=807&renderOrientation=1&isLocal=1

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

![image](https://user-images.githubusercontent.com/70784064/216227787-350f72cb-d001-4936-ba9e-f1dec74d60b1.png)

**Comment by NewByVector** [comment]
每个组其实就是一个画布，画布中元素的加载顺序是按照 zIndex 顺序加载的。所以会出现你的现象。

**Comment by IcarusRyy** [comment]
> 每个组其实就是一个画布，画布中元素的加载顺序是按照 zIndex 顺序加载的。所以会出现你的现象。

那该如何控制这个组的加载顺序呢？  我们现在业务上就是stencil.load([节点数据])， 然后通过这个数组元素的位置去控制这个加载顺序， 在同时存在组的情况下，请问该如何控制？

**Comment by NewByVector** [comment]
@IcarusRyy 你把 zIndex: -10 去掉就好了呀

**Comment by IcarusRyy** [comment]
> 每个组其实就是一个画布，画布中元素的加载顺序是按照 zIndex 顺序加载的。

好的 我试试 感谢🙏
