### ISSUE TITLE
Impossible to drag a new edge from a node port in firefox

### ISSUE THREAD

**Issue by rlembo06** [antvis/X6#3204]
### Describe the bug

In Chrome, it is possible to drag a new edge from any node port, but impossible to do so in firefox.

### Your Example Website or App

localhost

### Steps to Reproduce the Bug or Issue

- Hover a node
- Drag a edge to another node

### Expected behavior

Drag a new edge in firefor should be able

### Platform

- OS: [Ubuntu 22]
- Browser: [Firefox]
- AntV X6 Version: [2.2.1]
- React 18.2.0
- Node 14

**Comment by NewByVector** [comment]
I tried to reproduce locally, but I could not reproduce your problem. Could you please provide a demo that can be reproduced.

**Comment by rlembo06** [comment]
here is a recording where on the left side, it is the firefox browser, and on the right side chrome

https://user-images.githubusercontent.com/34583952/217756151-8802da5d-3671-4f13-87ad-dbf922d701af.mp4

**Comment by NewByVector** [comment]
I can't see the problem by looking at the recording.

**Comment by rlembo06** [comment]
The anchor in Nodes for drag a new  transition is not visible on Firefox (left side)

**Comment by NewByVector** [comment]
This is a style compatibility issue, you can provide a reproducible demo to see？
