### ISSUE TITLE
怎么给桩(Port)的label加背景色

### ISSUE THREAD

**Issue by rxdrag** [antvis/X6#3210]
### 问题描述

port的label跟线交叉，希望能加一个背景色遮挡一下，折腾了很长时间，一直没解决，希望有大佬能帮忙解决一下
![image](https://user-images.githubusercontent.com/18096128/217127019-1d23fbfc-650f-459f-8f7d-07ea51185dc1.png)
不是线的标签，线的标签我自己能解决，就是解决不了port的标签

### 重现链接

无

### 重现步骤

见图

### 预期行为

希望能给port的标签加背景色

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by struggleRoue** [comment]
注册节点的时候在ports的label中设置markup 然后在使用的时候在attrs里面给结构添加attrs    

ports: {
      groups: {
        top: {
          position: 'top',
          label: {
            markup: [
              {
                tagName: 'rect',
              },
              {
                tagName: 'text',
              },
            ],
            position: 'top'
          },
          attrs: {
            circle: {
              r: 4,
              magnet: true,
              stroke: '#c5c5c5',
              strokeWidth: 1,
              fill: '#fff',
            },
          },
        },
        bottom: {
          position: 'bottom',
          attrs: {
            circle: {
              r: 4,
              magnet: true,
              stroke: '#c5c5c5',
              strokeWidth: 1,
              fill: '#fff',
            },
          },
        },
      },
    },

![image](https://user-images.githubusercontent.com/47975400/217156960-714cdc8f-1f95-43ff-b720-107e0bee61e3.png)

大概实现应该是这个思路吧

**Comment by rxdrag** [comment]
唉，不停的尝试，就是试不出来
![image](https://user-images.githubusercontent.com/18096128/217403097-753d5982-a76d-4e10-95a3-c40b328f9e40.png)
![image](https://user-images.githubusercontent.com/18096128/217403214-0dd0688f-193f-422e-9f4f-b6ab6695225b.png)
感觉有点无能为力了，感谢大佬，这问题我放弃了

**Comment by NewByVector** [comment]
参考这个 [demo](https://codesandbox.io/s/port-label-viwnos)

**Comment by rxdrag** [comment]
> 参考这个 [demo](https://codesandbox.io/s/port-label-viwnos)

解决了，非常感谢
