### ISSUE TITLE
边属性的全局修改

### ISSUE THREAD

**Issue by yuanbolin** [antvis/X6#3211]
### 功能描述

除了全局定义默认的边属性样式外，想做一个用户自己选择全局使用什么样式的功能。

### 期望解决方案

能够提供方法全局修改边的默认属性样式

**Comment by NewByVector** [comment]
可以使用[全局定制边](http://x6.antv.antgroup.com/tutorial/basic/edge#%E5%AE%9A%E5%88%B6%E8%BE%B9)。
