### ISSUE TITLE
在vue中，使用Safari浏览器节点位置重叠

### ISSUE THREAD

**Issue by xuyang0723** [antvis/X6#3213]
### 问题描述

在vue中，使用Safari浏览器节点位置重叠，位置不对

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

进入页面新建节点

### 预期行为

我期望能修复下在Safari里这个重叠的问题

### 平台

- 操作系统: [macOS,]
- 网页浏览器: [ Safari]
- X6 版本: [1.34.10 ]

**Comment by xuyang0723** [comment]
已解决，修改 .x6-node foreignObject > body  样式    position: static;改成fixed

**Comment by tianjinhao** [comment]
> 已解决，修改 .x6-node foreignObject > body 样式 position: static;改成fixed

厉害厉害，我也遇到这个问题了，按照你的这个方法确实不重叠了，但是画布缩放的时候，vue节点大小不跟随缩放，这个有遇到吗，怎么解决呢！！！

**Comment by NewByVector** [comment]
是不是因为节点内部元素尺寸超过了节点设置的尺寸呢？我记得 safari 下面是有这个 bug 的。

**Comment by tianjinhao** [comment]
> 是不是因为节点内部元素尺寸超过了节点设置的尺寸呢？我记得 safari 下面是有这个 bug 的。

自定义节点宽高给的是100%，实际通过控制台看到的是变小了，但是页面上看到的节点宽高实际上始终是原本的像素大小，不会被放大或者缩小；
<img width="853" alt="image" src="https://user-images.githubusercontent.com/48881233/218354849-bd401422-5896-4bdc-bdf7-6769e0b16171.png">

**Comment by tianjinhao** [comment]
嗯嗯，好像是节点内部元素尺寸超过了，rect 的大小是缩放了，但是foreignobject的大小还是之前的，所以导致自定义节点100%也没有变化；这个有什么解决方案吗?

**Comment by NewByVector** [comment]
@tianjinhao 是需要保证内容不要超出节点尺寸的，不然浏览器渲染有 bug。

**Comment by ycx0303** [comment]
> 嗯嗯，好像是节点内部元素尺寸超过了，rect 的大小是缩放了，但是foreignobject的大小还是之前的，所以导致自定义节点100%也没有变化；这个有什么解决方案吗?

请问有解决吗？江湖救急！一模一样的问题

**Comment by lucyanddarlin** [comment]
遇到了同样的问题，请问有解决方案嘛
