### ISSUE TITLE
vue2 使用x6-vue-shape 报错Object(...) is not a function

### ISSUE THREAD

**Issue by keyalab** [antvis/X6#3219]
### 问题描述

node版本: v14.15.0
npm版本: 6.14.8
报错内容
<img width="571" alt="image" src="https://user-images.githubusercontent.com/22260480/217462860-d59c911f-ef0c-4500-bcaa-6a8094eb726a.png">
项目依赖
<img width="330" alt="image" src="https://user-images.githubusercontent.com/22260480/217462994-5161ad84-0a64-4ba5-9019-90c51ae59e56.png">

### 重现链接

无

### 重现步骤

npm构建项目运行错误

### 预期行为

无

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- x6-vue-shape 版本: [2.0.0]

**Comment by NewByVector** [comment]
可以在 https://github.com/antvis/X6/issues/3150 这下面问问，出现了同样的问题。
