### ISSUE TITLE
V2版本 boundary tools生效区域大小不正确

### ISSUE THREAD

**Issue by zhouxinyong** [antvis/X6#3228]
### 问题描述

升级v2后，同样的代码，boundary tools生效的区域大小不正确。

### 重现链接

https://codesandbox.io/s/x6-v2-0d35lw?file=/index.ts

### 重现步骤

1. 鼠标hover到每一个节点上，发现boundary生成的高亮区域太小，没有包裹住内容区域。
![image](https://user-images.githubusercontent.com/15569753/218018597-1613befa-0786-4722-b149-3c57ec8f8f59.png)

### 预期行为

v1的正常结果是这样：
![image](https://user-images.githubusercontent.com/15569753/218018689-7ce01b04-d09e-48fa-a19f-23c84004c543.png)

附上V1版本的代码：
https://codesandbox.io/s/x6-v1-smtkdy?file=/index.ts

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 2.3.0

**Comment by NewByVector** [comment]
已加入我们的修复列表中。

**Comment by zhouxinyong** [comment]
预计什么时候修复呢？
