### ISSUE TITLE
@antv/layout和@antv/x6中都有Model类，互相冲突

### ISSUE THREAD

**Issue by silentmissile** [antvis/X6#3229]
### Describe the bug

@antv/layout和@antv/x6这2个库都有Model类，但是这两个Model完全不同

这篇文档提供的案例当中
https://antv-x6.gitee.io/zh/examples/layout/general#dagre

data变量是Model类，这个Model类其实是@antv/layout的Model类，但是却是从@antv/x6中import的，所以在typescript编译时会无法通过类型检查。

用户使用的时候确实可以通过在import时加别名处理，不过这样很不方便。而且这两个库是你们同一个公司出品的

### Your Example Website or App

https://antv-x6.gitee.io/zh/examples/layout/general#dagre

### Steps to Reproduce the Bug or Issue

使用typescript编译，直接提示类型检测通不过

### Expected behavior

两个库都是你们同一家公司开发的，请你们互相协商一下，把这个冲突解决掉。

顺便更新一下文档

### Platform

- OS: [Windows]
- Browser: [typescript]
- Version: [4.9.5]

**Comment by silentmissile** [comment]
import { Graph, Node, Edge, Model  } from "@antv/x6";
import { DagreLayout} from "@antv/layout";
/* if you change to this, it can pass typescript check
import { Graph, Node, Edge } from "@antv/x6";
import { DagreLayout, Model as layoutModel } from "@antv/layout";
*/
const layoutData: Model = {
/* if you change to this, it can pass typescript check
const layoutData: layoutModel = {
*/
  "nodes": [
    {
      "id": "1",
      "shape": "rect",
      "width": 100,
      "height": 40,
      "attrs": {
        "body": {
          "fill": "#1E90FF",
          "stroke": "#FF4500"
        },
        "label": {
          "text": "start",
          "fill": "#000000",
          "fontSize": 13
        }
      },
      "x": 35,
      "y": 55,
      "_order": 0
    },
    {
      "id": "3",
      "shape": "rect",
      "width": 100,
      "height": 40,
      "attrs": {
        "body": {
          "fill": "#FFFF00",
          "stroke": "#87CEFA"
        },
        "label": {
          "text": "hr_review",
          "fill": "#000000",
          "fontSize": 13
        }
      },
      "x": 140,
      "y": 635,
      "_order": 1
    },
    {
      "id": "2",
      "shape": "rect",
      "width": 100,
      "height": 40,
      "attrs": {
        "body": {
          "fill": "#00FF00",
          "stroke": "#FF4500"
        },
        "label": {
          "text": "first_review",
          "fill": "#000000",
          "fontSize": 13
        }
      },
      "x": 35,
      "y": 200,
      "_order": 0
    },
    {
      "id": "4",
      "shape": "rect",
      "width": 100,
      "height": 40,
      "attrs": {
        "body": {
          "fill": "#00FF00",
          "stroke": "#FF4500"
        },
        "label": {
          "text": "engineer_manager_review",
          "fill": "#000000",
          "fontSize": 13
        }
      },
      "x": 35,
      "y": 490,
      "_order": 0
    },
    {
      "id": "5",
      "shape": "rect",
      "width": 100,
      "height": 40,
      "attrs": {
        "body": {
          "fill": "#FFFF00",
          "stroke": "#FF4500"
        },
        "label": {
          "text": "engineering_director_review",
          "fill": "#000000",
          "fontSize": 13
        }
      },
      "x": 35,
      "y": 635,
      "_order": 0
    },
    {
      "id": "6",
      "shape": "rect",
      "width": 100,
      "height": 40,
      "attrs": {
        "body": {
          "fill": "#FFFFFF",
          "stroke": "#FF4500"
        },
        "label": {
          "text": "sales_review",
          "fill": "#000000",
          "fontSize": 13
        }
      },
      "x": 120,
      "y": 345,
      "_order": 1
    },
    {
      "id": "7",
      "shape": "rect",
      "width": 100,
      "height": 40,
      "attrs": {
        "body": {
          "fill": "#FFFFFF",
          "stroke": "#FF4500"
        },
        "label": {
          "text": "finance_review",
          "fill": "#000000",
          "fontSize": 13
        }
      },
      "x": 120,
      "y": 490,
      "_order": 1
    }
  ],
  "edges": [
    {
      "source": "1",
      "target": "2",
      "router": {
        "name": "metro",
        "args": {
          "padding": 1,
          "startDirections": [
            "bottom"
          ],
          "endDirections": [
            "top"
          ]
        }
      },
      "connector": {
        "name": "rounded",
        "args": {
          "radius": 8
        }
      },
      "anchor": "center",
      "connectionPoint": "anchor",
      "allowBlank": false,
      "snap": {
        "radius": 20
      },
      "attrs": {
        "line": {
          "stroke": "#1890ff",
          "strokeDasharray": 10,
          "targetMarker": "classic",
          "style": {
            "animation": "ant-line 30s infinite linear"
          }
        }
      },
      "shape": "edge"
    },
    {
      "source": "2",
      "target": "4",
      "router": {
        "name": "metro",
        "args": {
          "padding": 1,
          "startDirections": [
            "bottom"
          ],
          "endDirections": [
            "top"
          ]
        }
      },
      "connector": {
        "name": "rounded",
        "args": {
          "radius": 8
        }
      },
      "anchor": "center",
      "connectionPoint": "anchor",
      "allowBlank": false,
      "snap": {
        "radius": 20
      },
      "attrs": {
        "line": {
          "stroke": "#1890ff",
          "strokeDasharray": 10,
          "targetMarker": "classic",
          "style": {
            "animation": "ant-line 30s infinite linear"
          }
        }
      },
      "shape": "edge"
    },
    {
      "source": "2",
      "target": "6",
      "router": {
        "name": "metro",
        "args": {
          "padding": 1,
          "startDirections": [
            "bottom"
          ],
          "endDirections": [
            "top"
          ]
        }
      },
      "connector": {
        "name": "rounded",
        "args": {
          "radius": 8
        }
      },
      "anchor": "center",
      "connectionPoint": "anchor",
      "allowBlank": false,
      "snap": {
        "radius": 20
      },
      "attrs": {
        "line": {
          "stroke": "#1890ff",
          "strokeDasharray": 10,
          "targetMarker": "classic",
          "style": {
            "animation": "ant-line 30s infinite linear"
          }
        }
      },
      "shape": "edge"
    },
    {
      "source": "4",
      "target": "5",
      "router": {
        "name": "metro",
        "args": {
          "padding": 1,
          "startDirections": [
            "bottom"
          ],
          "endDirections": [
            "top"
          ]
        }
      },
      "connector": {
        "name": "rounded",
        "args": {
          "radius": 8
        }
      },
      "anchor": "center",
      "connectionPoint": "anchor",
      "allowBlank": false,
      "snap": {
        "radius": 20
      },
      "attrs": {
        "line": {
          "stroke": "#1890ff",
          "strokeDasharray": 10,
          "targetMarker": "classic",
          "style": {
            "animation": "ant-line 30s infinite linear"
          }
        }
      },
      "shape": "edge"
    },
    {
      "source": "4",
      "target": "3",
      "router": {
        "name": "metro",
        "args": {
          "padding": 1,
          "startDirections": [
            "bottom"
          ],
          "endDirections": [
            "top"
          ]
        }
      },
      "connector": {
        "name": "rounded",
        "args": {
          "radius": 8
        }
      },
      "anchor": "center",
      "connectionPoint": "anchor",
      "allowBlank": false,
      "snap": {
        "radius": 20
      },
      "attrs": {
        "line": {
          "stroke": "#1890ff",
          "strokeDasharray": 10,
          "targetMarker": "classic",
          "style": {
            "animation": "ant-line 30s infinite linear"
          }
        }
      },
      "shape": "edge"
    },
    {
      "source": "6",
      "target": "7",
      "router": {
        "name": "metro",
        "args": {
          "padding": 1,
          "startDirections": [
            "bottom"
          ],
          "endDirections": [
            "top"
          ]
        }
      },
      "connector": {
        "name": "rounded",
        "args": {
          "radius": 8
        }
      },
      "anchor": "center",
      "connectionPoint": "anchor",
      "allowBlank": false,
      "snap": {
        "radius": 20
      },
      "attrs": {
        "line": {
          "stroke": "#1890ff",
          "strokeDasharray": 10,
          "targetMarker": "classic",
          "style": {
            "animation": "ant-line 30s infinite linear"
          }
        }
      },
      "shape": "edge"
    },
    {
      "source": "7",
      "target": "5",
      "router": {
        "name": "metro",
        "args": {
          "padding": 1,
          "startDirections": [
            "bottom"
          ],
          "endDirections": [
            "top"
          ]
        }
      },
      "connector": {
        "name": "rounded",
        "args": {
          "radius": 8
        }
      },
      "anchor": "center",
      "connectionPoint": "anchor",
      "allowBlank": false,
      "snap": {
        "radius": 20
      },
      "attrs": {
        "line": {
          "stroke": "#1890ff",
          "strokeDasharray": 10,
          "targetMarker": "classic",
          "style": {
            "animation": "ant-line 30s infinite linear"
          }
        }
      },
      "shape": "edge"
    }
  ]
}

const dagreLayout = new DagreLayout({
        type: "dagre",
        rankdir: "TB",
        align: "UL",
        ranksep: 35,
        nodesep: 15,
    });
const dagreModel = dagreLayout.layout(layoutData); // this line can't pass typescript check, unless you change the code by my comment
graph = new Graph({
        container: document.getElementById('container')!,
        panning: {
            enabled: true,
            eventTypes: ["leftMouseDown"],
        },
    });
graph.fromJSON(dagreModel);

**Comment by NewByVector** [comment]
两个库导出内容名称一致这个是无法避免的，as 一下就好了。

**Comment by silentmissile** [comment]
> 两个库导出内容名称一致这个是无法避免的，as 别名一下就好了。

如果这两个库是两家公司开发的，我自然不会要求任何一家来修改。

如果这个冲突的类不常用，我也不会提出。偶尔用一下别名不算大麻烦。

可是既然官方文档都这么用，就说明这是一个常用功能，每次都要这么别名一下实在是繁琐。而且对于团队合作开发很不友好，因为不同的开发者在初次遇到这个问题的时候会根据自己的习惯起不同的别名。诚然，项目开始的时候约定好可以解决这个问题，但是任何一个开发团队都不太可能在开始项目的时候就非常清楚技术栈里会有多少命名冲突的类，大概率都是遇到了以后再进行协调，如果部分成员已经写了很多了再返回去改，那就是一个大麻烦。

既然是同一家公司开发的两个库，而且还是很常用的功能，频繁出现冲突对用户实在是不友好。能改还是尽量改一下。

**Comment by lloydzhou** [comment]
1. 不同的库内部有相同的类，这个并不冲突
2. 不管是x6还是@antv/layout都是比较成熟的库，这种时候，因为这样可有可无的原因要改导出的类名。会带来相当大的麻烦（对之前使用这些库的开发者来说又是额外的负担）
