### ISSUE TITLE
2.x版本使用scroller后出现多个滚动条（3个）

### ISSUE THREAD

**Issue by MMMMoriaty** [antvis/X6#3230]
### Describe the bug

关键代码如下：
  const graphSize = useSize(graphRef)

const graph = new Graph({
        container: graphRef.current,
        width: graphSize?.width,
        height: graphSize?.height,
        panning: false,
        interacting: false,
        scroller: true,
      })

graph.use(
        new Scroller({
          enabled: true,
          minVisibleWidth: graphSize?.width,
          minVisibleHeight: graphSize?.height,
        })
      );

return <div id="graphNode" ref={graphRef} style={{ height: '100%', width: '100%' }}/>

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

暂无

### Expected behavior

期望只有一个滚动条

### Platform

- OS: macOS
- Browser: chrome
- Version: 103.0.5060.114

**Comment by NewByVector** [comment]
能否提供一个可以复现的 demo 呢？

**Comment by MMMMoriaty** [comment]
抱歉才看到，已经解决了，发现问题是多次调用scroller插件的use导致的




whhhhhhhhhq
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/X6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月16日(星期四) 下午5:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/X6] 2.x版本使用scroller后出现多个滚动条（3个） (Issue #3230)





 
能否提供一个可以复现的 demo 呢？
