### ISSUE TITLE
When a node was hide and soon show it on the graph,it'll cover all the other cells despite the higner zIndex.(Version: 1.34.10)

### ISSUE THREAD

**Issue by damnright** [antvis/X6#3232]
### Describe the bug

When a node was hide and soon show it on the graph,it'll cover all the other cells despite the higner zIndex.(Version: 1.34.10)

### Your Example Website or App

https://codesandbox.io/s/hide-show-node-ujcrct?file=/src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Add two nodes to the graph,one of it's zIndex is higher than another.
2. Overlap them.
3. Conceal the node with lower zIndex,and soon recover it.
4. Then we will see the node with lower zIndex,right in front of the other node!

### Expected behavior

render accord with zIndex

### Platform

- OS: Windows10
- Browser: Chrome
- Version: 1.34.10

**Comment by NewByVector** [comment]
这个问题已经在 2.x 版本中彻底解决，能否升级到 2.x 版本？

**Comment by damnright** [comment]
> 

好吧
