### ISSUE TITLE
Prevent overlapping edges when routing via Manhattan

### ISSUE THREAD

**Issue by mike-Yacoub** [antvis/X6#3233]
### Describe the feature you'd like to request

When routing edges via the manhattan or metro algorithm there is no attempt to prevent overlapping edges. This causes edges to become unreadable very quickly when many connections exist between nodes (especially with multiple edge-anchors on one node)

Feature request:
- Detect if an edge already exists on the grid and only allow crossing it, not overlapping with it when calculating an edge route

### Describe the solution you'd like

Add an option to enable "edge overlap prevention" on the manhattan (and maybe metro) router and detect when the path is already occupied by another edge when calculating the shortest path.

### Describe alternatives you've considered

Since the Graph has a registerRouter function, it is possible to write a custom router. My knowledge of how this feature could be implemented is very limited though, so I wanted to check if there is an interest in adding this feature in the future.

### Your Example Website or App

https://codesandbox.io/s/jolly-heyrovsky-ji83xz

### Screenshots or Videos

Codesandbox example:
![example1](https://user-images.githubusercontent.com/89195991/218455099-57a8e646-7738-4735-a59f-ed8596b838d4.png)

More complex example that breaks completely:
![example2](https://user-images.githubusercontent.com/89195991/218455186-cedb2516-f406-4dda-820a-6c34dbe00c7f.png)

**Comment by NewByVector** [comment]
Whether the unreadable problem can be solved by adding some interaction, such as changing the style of the edge while hovering. Because if you want to count the edges, the performance is going to be really bad.

**Comment by mike-Yacoub** [comment]
> Whether the unreadable problem can be solved by adding some interaction, such as changing the style of the edge while hovering. Because if you want to count the edges, the performance is going to be really bad.

That is the way I've solved it for now and it works reasonably well. Routing each frame would definitely take too much time, but for a hybrid solution with the routing only happening once elements have finished being moved around it would still be a lot better than the oneSide Router in my opinion. Thanks for your input :)

**Comment by cuijinyu** [comment]
same question

**Comment by cuijinyu** [comment]
How should I get all the edge routing data in the custom routing? I can not get other edge route points data via edgeview.
尝试过使用自定义路由（拷贝曼哈顿路由实现修改），无法通过 EdgeView 获取到其他 边的路由点信息，就无法进行边避障，这里有什么办法获取到这个信息吗

**Comment by NewByVector** [comment]
@cuijinyu 没有好的方式获取到经过的边的信息。
