### ISSUE TITLE
想咨询一下如何创建重叠图形的节点

### ISSUE THREAD

**Issue by alistuff** [antvis/X6#3246]
### 问题描述

![QQ截图20230216140508](https://user-images.githubusercontent.com/7888295/219282601-45119f7a-f9bc-4afe-80a4-1ba9b18d7d9e.png)

您好，我想实现一个自定义节点，是由多个椭圆形组成的形状，表达一个集合类型元素。我通过markup可以定义出包括两个椭圆类型svg元素，但不清楚如何设置元素大小及相对偏移量。

```
  markup: [
    {
      tagName: 'ellipse',
      selector: 'body'
    },
    {
      tagName: 'ellipse',
      selector: 'wrap',
      attrs: {
        fill: 'red'
      }
    },
    {
      tagName: 'text',
      selector: 'label'
    }
  ]
```

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by damnright** [comment]
refX,refWidth,refX2

**Comment by NewByVector** [comment]
可以参考这个 [demo](https://codesandbox.io/s/repeated-ellipse-nk819e)。

**Comment by alistuff** [comment]
> 可以参考这个 [demo](https://codesandbox.io/s/repeated-ellipse-nk819e)。

多谢，应该是我想实现的效果。
