### ISSUE TITLE
创建vue3节点，数组类型的数据，节点监听无法触发update:data

### ISSUE THREAD

**Issue by laterdayi** [antvis/X6#3249]
### Describe the bug

```
 const { content } = node.getData();
      const _content = content;
      _content[2] = 'test';
      node.replaceData({
        title: 'test1',
        content: _content
      });
```
```
  node.on('change:data', ({ current }) => {
    console.log(current);
    const { title, content } = current;
    console.log('update', title, content);
    title.value = title;
    cont.value = content;
  });
```

### Your Example Website or App

*

### Steps to Reproduce the Bug or Issue

创建vue3节点，数组类型的数据，节点监听无法触发update:data

### Expected behavior

可以处理数组类型的数据

### Platform

windows

**Comment by NewByVector** [comment]
现在 X6 的 data change 是基于对象引用是否一致来判断的，你可以将 content 设置为 { ..._content }，这个数据检测机制我们也在考虑优化。

**Comment by laterdayi** [comment]
@NewByVector  是的， 希望可以考虑数据不单单是对象 字符串 的情况， 很多情况下 是需要数组作为节点渲染的数据，所以很多时候需要更新数组或对象
