### ISSUE TITLE
一个页面中存在100或1000个 官方实例中的EAP图时，vue渲染节点和原始SVG创建节点哪个性能会更高

### ISSUE THREAD

**Issue by laterdayi** [antvis/X6#3250]
### Describe the feature you'd like to request

一个页面中存在100或1000个 官方实例中的EAP图时，vue渲染节点和原始SVG创建节点哪个性能会更高

### Describe the solution you'd like

一个页面中存在100或1000个 官方实例中的EAP图时，vue渲染节点和原始SVG创建节点哪个性能会更高

### Describe alternatives you've considered

一个页面中存在100或1000个 官方实例中的EAP图时，vue渲染节点和原始SVG创建节点哪个性能会更高

**Comment by NewByVector** [comment]
以我的经验来看，SVG 渲染更快，毕竟 vue 组件加载有一些性能损耗。选型的话可以参考[官网文档](http://x6.antv.antgroup.com/tutorial/basic/node#%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E6%96%B9%E5%BC%8F)，需要在性能和开发工作量上做一个权衡。

**Comment by laterdayi** [comment]
我对SVG和节点 在x6中渲染的效率并不是很熟悉，您能解释下这个性能损耗的大概差距吗 ？ 例如：100 或者 1000 之前的差距 ，一个大概描述就可以，这样我们可以更好的权衡 @NewByVector

**Comment by lloydzhou** [comment]
1. 使用vue自定义组件的时候，每一个组件都需要创建一个`foreignObject`而每一个`foreignObject`内部有一个`body`标签，你可以简单的将这个`body`标签类比`document.body`
2. 另外vue渲染自定义组件的时候，如果不使用teleport的情况下，每一个节点都会调用createApp，也就是说这种情况下，有多少个节点就有多少个vue的App

所以单纯的使用svg内置元素应该是比使用vue组件性能要好
