### ISSUE TITLE
想请教下,在这个模式下Addon.Stencil，不使用链接桩的话，如何触发连线

### ISSUE THREAD

**Issue by SasakiKan** [antvis/X6#3260]
### 问题描述

发现使用了Addon.Stencil，只能过链接桩来触发连线，这想点击节点触发连线模式

### 重现链接

https://codesandbox.io/s/m9fzwi

### 重现步骤

1.Addon.Stencil拖拽注册节点
2.点击链接桩连接节点有效
3.点击节点无触发连接的方法

### 预期行为

在Addon.Stencil下不仅点击链接桩触发连线，还能通过直接点击节点触发连线的模式

### 平台

- 操作系统: [Windows10]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.31.0]

**Comment by damnright** [comment]
设置attr的magnet:true

**Comment by SasakiKan** [comment]
> 设置attr的magnet:true
在自定义的HTML节点上添加了这个属性，试了过不行，点击长按拖拽还是移动，是不是还需要结合别的api使用，

**Comment by SasakiKan** [comment]
> magnet:true



> 设置attr的magnet:true
可以了，直接在html dom上的添加magnet 就可以了
