### ISSUE TITLE
如何创建堆叠图形带文本的节点，可动态添加和删除

### ISSUE THREAD

**Issue by laterdayi** [antvis/X6#3264]
### 问题描述

如何创建堆叠图形带文本的节点，可动态添加和删除

### 重现链接

*

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by laterdayi** [comment]
![Uploading 图片.png…]()
如果通过registerNode创建出这样的图形， 并可以动态创建每个矩形块中的文本内容

**Comment by Eve-Sama** [comment]
图片好像看不到?

**Comment by laterdayi** [comment]
![图片](https://user-images.githubusercontent.com/122137647/220231741-72a5e0a2-f607-47cb-a08a-fcc992520e9f.png)
类似于这种，红色区域如何能动态创建和删除

**Comment by laterdayi** [comment]
@Eve-Sama  期待帮助

**Comment by Eve-Sama** [comment]
我使用X6的时候是借助了HTML 节点的 所以这里的创建和删除在我这边的场景就是html里的节点变化. 你是用x6原生api去画的吗

**Comment by laterdayi** [comment]
是的，但不知道如何实现它
