### ISSUE TITLE
节点数大于100时, 渲染性能问题

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/X6#3266]
### Describe the bug

做了个测试, 点击按钮可以快速生成50个节点, 拖拽节点进行移动. 我发现50个节点的时候fps还是57, 而当节点增加到100个时, fps则为十几, 卡顿非常明显

<img width="1032" alt="图片" src="https://user-images.githubusercontent.com/30228406/220158853-019bef16-a268-4514-92b3-ef31c6cd1d69.png">

另外, 还有个有趣的现象. 如果拖拽的元素的编号越靠前, 则越顺畅, 反之越卡顿. 为什么fps会和拖拽元素的顺序有关系呢? 

想请问下在100个元素下, 拖拽卡顿是正常的吗? 

### Your Example Website or App

https://eve-sama.github.io/x6-angular-shape/#/x6

### Steps to Reproduce the Bug or Issue

1. 打开https://eve-sama.github.io/x6-angular-shape/#/x6
2. 点击2次生成50个节点的按钮, 产生100个节点.
3. 打开fps, 拖拽元素查看fps值会明显降低

### Expected behavior

始终保持60上下fps

### Screenshots or Videos

视频有点大, 我提供个[OSS](https://eve-sama.oss-cn-shanghai.aliyuncs.com/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B62023-02-21%2000.31.22.mov)吧

### Platform

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.4.0 ]

**Comment by Max-ChenFei** [comment]
@Eve-Sama 请问是否考虑过 d3, Konva, fabric or Pixijs 等呢？

**Comment by Eve-Sama** [comment]
> @Eve-Sama 请问是否考虑过 d3, Konva, fabric or Pixijs 等呢？

没有做过那几个lib的调研. 我的需求是实现流程图, 节点数多的话可能有几百个. 有什么好的推荐吗?

**Comment by Eve-Sama** [comment]
稍等, 为了更公平的对比, 我将x6和g6添加的节点都设置为了HTML类型.看发现在性能上差距并不明显, 怀疑可能和shape有关, 我再调试看看

**Comment by Max-ChenFei** [comment]
> 

你好，我是自己写了一个库基于canvas的，基于canvas的几百个节点还是可以的。 我也是在对比基于svg，canvas, webgl的一些库。

**Comment by Max-ChenFei** [comment]
> > @Eve-Sama 请问是否考虑过 d3, Konva, fabric or Pixijs 等呢？
> 
> 没有做过那几个lib的调研. 我的需求是实现流程图, 节点数多的话可能有几百个. 有什么好的推荐吗?

你好，我是自己写了一个库基于canvas的，基于canvas的几百个节点还是可以的。 我也是在对比基于svg，canvas, webgl的一些库。

**Comment by Eve-Sama** [comment]
将demo做了下改造, 以方便更加全面的对比. 
## G6
### 拖动性能

在HTML(准确的说是SVG)类型节点增加至1400时, 拖动时的FPS波动在50上下.
![图片](https://user-images.githubusercontent.com/30228406/220562003-9ae00d05-20fa-4646-ad57-0f1ed0eeadfb.png)

### 添加节点性能

在节点添加到200个时, 已经出现明显等待感. 随着数量的提升, 等待的时间越来越久. 当节点从1000添加至1050时耗时1.39秒.

## X6
### 拖动性能

在HTML类型添加至7000时, 拖动的FPS波动在50上下.
![图片](https://user-images.githubusercontent.com/30228406/220564402-3724953d-89c9-456c-b453-a0ffea27aee0.png)

但是Angular Component类型添加至2000时, FPS波动就已经到了50上下. 

### 添加节点性能

无论是HTML还是Component, 从0增加至7000, 全程都是秒完成, 无任何卡顿感, 不确定临界值.

## 说明
 - FPS低于60时会有明显卡顿感
 - HTML结构越复杂, 对渲染影响越大, 为了方便对比, 两边采用的结构是差不多的.
 - 拖拽速度越快, 对FPS要求越高. 我这里的拖拽速度是正常用鼠标的速度, 而非疯狂移动.
 - 不同的设备的结果也不一样, 我的设备是 `MBP-16inch-M1Max-64G-1TB`
