### ISSUE TITLE
咨询一下 React 的 draggable 失效问题

### ISSUE THREAD

**Issue by llllllllr** [antvis/X6#3268]
### 问题描述

antv/x6版本：1.31.0
使用graph属性使得节点拖动失效（不希望使用原本的拖动效果，想要react draggable的效果）
```
  // graph配置
  interacting={{
          nodeMovable: false,
    }}
```
node配置为 **react-shape**，使用自定义React节点，并配置 draggable 属性，无效

```
// 自定义 react 节点
    <div
        style={{ zIndex: 20 }}
        draggable
        onDragStart={() => {
          // 无法监听到
        }}
      >
....
</div>
```

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

预期的效果是能使用react原生的 draggable， 并且监听到相应 onDragEnter 事件，达到类似的拖动效果
![image](https://user-images.githubusercontent.com/35605494/220301390-19c0958f-41e5-444c-8f46-f7dfcba947da.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
不好意思，比较晚才来回答你的问题。
这里没有 draggable 的效果是因为我们为了避免用户拖拽和移动节点效果冲突，给节点加上了下面样式：
```css
.x6-node * {
    -webkit-user-drag: none;
}
```
你可以将这个样式覆盖来实现你的功能。

**Comment by NewByVector** [comment]
[这里](https://codesandbox.io/s/daraggable-bhjkyy) 我实现了一个使用 draggable 来实现元素拖拽的例子。
