### ISSUE TITLE
自定义节点的定制问题

### ISSUE THREAD

**Issue by qdgcswy** [antvis/X6#327]
自定义节点如何添加图标或者小图片啊，就是类似这种
![微信图片_20201124155159](https://user-images.githubusercontent.com/23414254/100064165-201cbf80-2e6d-11eb-97d0-e4e787d90c8a.png)

**Comment by bubkoo** [comment]
@qdgcswy 可以使用 HTML 或 React 来渲染节点，定制节点就相当于设计自己的 DOM 结构，参看文档：https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-html-%E8%8A%82%E7%82%B9

**Comment by qdgcswy** [comment]
> @qdgcswy 可以使用 HTML 或 React 来渲染节点，定制节点就相当于设计自己的 DOM 结构，参看文档：https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-html-%E8%8A%82%E7%82%B9
谢谢您的回答，问题终于解决了
