### ISSUE TITLE
项目中接入arms和senty后，画布无法渲染

### ISSUE THREAD

**Issue by caishuaijun** [antvis/X6#3271]
### 问题描述

项目中接入arms和senty后，画布无法渲染

### 重现链接

1

### 预期行为

期望解决

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
是否有可以复现的 demo？
