### ISSUE TITLE
display:none;时渲染画布，之后再转为display:block;连接线的连接点会出现在左上角

### ISSUE THREAD

**Issue by 1057189519** [antvis/X6#3273]
### Describe the bug

![image](https://user-images.githubusercontent.com/75262115/220532960-7869e4d1-8777-4be2-b2d6-98274e75b1d3.png)
渲染画布前设置display:none，渲染之后再改为display:block，会出现图中的状况。之前有提过bug，回复说在2.0版本已经修复，但是依旧存在这个现象。参考上次的问题https://github.com/antvis/X6/issues/2647

### Your Example Website or App

https://codesandbox.io/s/unruffled-chebyshev-bkwcsf?file=/index.html

### Steps to Reproduce the Bug or Issue

方法一：可以尝试将官网例子渲染之前的容器设置display:none，渲染之后设置为display:block，观察结果
方法二：打开我的例子直接看这个问题https://codesandbox.io/s/unruffled-chebyshev-bkwcsf?file=/index.html

方法二中在之前的版本可以展示出来问题，但是现在因为引用了官网的最新版本的CDN，如果调试会报错Uncaught TypeError: Class constructor Mh cannot be invoked without 'new'，造成渲染失败，所以这个问题之前应该先把这个报错解决掉

### Expected behavior

期望正常显示，如图
![image](https://user-images.githubusercontent.com/75262115/220534532-fecc4d7a-5ba2-4ec6-9c13-dd52e7a5cfd3.png)

### Platform

- OS: Windows
- Browser: Chrome
- Version: https://cdn.jsdelivr.net/npm/@antv/x6/dist/index.js

**Comment by lloydzhou** [comment]
你可以查一查  `display:none`与`visibility:hidden`的区别。看看`visibility:hidden`是否满足你的需求。

如果满足，你可以把`display:none`换成`visibility:hidden`，可能就不会出现这个问题了，

**Comment by 1057189519** [comment]
> 

不满足的，只能使用display来做转换，现在我只能打补丁，在画布渲染前display:block,渲染后dispay:block，然后立马再display:none;但是这个补丁应该是不存在的

**Comment by 1057189519** [comment]
> 你可以查一查 `display:none`与`visibility:hidden`的区别。看看`visibility:hidden`是否满足你的需求。
> 
> 如果满足，你可以把`display:none`换成`visibility:hidden`，可能就不会出现这个问题了，

不满足的，只能使用display来做转换，现在我只能打补丁，在画布渲染前display:block,渲染后dispay:block，然后立马再display:none;但是这个补丁应该是不存在的

**Comment by lloydzhou** [comment]
x6渲染的时候，需要通过dom的api获取一些大小/位置之类的信息。整个display:none会导致获取这些数据失败，这个时候x6渲染就会出现问题。

你还可以试试display:block的时候，手动调用一下graph.resize或者graph.resetCells之类的API触发一下x6画布重新渲染试试看？

**Comment by 1057189519** [comment]
> x6渲染的时候，需要通过dom的api获取一些大小/位置之类的信息。整个display:none会导致获取这些数据失败，这个时候x6渲染就会出现问题。
> 
> 你还可以试试display:block的时候，手动调用一下graph.resize或者graph.resetCells之类的API触发一下x6画布重新渲染试试看？

![image](https://user-images.githubusercontent.com/75262115/220546479-6a168c3e-664a-4171-b538-3fcd66145a27.png)
这个改动您觉得怎么样，会不会有其它潜在的危险

**Comment by 1057189519** [comment]
> x6渲染的时候，需要通过dom的api获取一些大小/位置之类的信息。整个display:none会导致获取这些数据失败，这个时候x6渲染就会出现问题。
> 
> 你还可以试试display:block的时候，手动调用一下graph.resize或者graph.resetCells之类的API触发一下x6画布重新渲染试试看？

![image](https://user-images.githubusercontent.com/75262115/220553242-3d34d757-7751-4e66-b397-0a115e3c9516.png)
![image](https://user-images.githubusercontent.com/75262115/220553329-5430bb34-611d-43b8-8a34-c93e6fb9b265.png)
这样更改可以避免这个问题，麻烦看一下可行吗

**Comment by 1057189519** [comment]
> x6渲染的时候，需要通过dom的api获取一些大小/位置之类的信息。整个display:none会导致获取这些数据失败，这个时候x6渲染就会出现问题。
> 
> 你还可以试试display:block的时候，手动调用一下graph.resize或者graph.resetCells之类的API触发一下x6画布重新渲染试试看？

不行，我把CDN里面的代码改了一下，上面的截图那样，可以解决display的问题，可以这样改吗

**Comment by lloydzhou** [comment]
不建议直接改CDN里面拿到的文件...

**Comment by 1057189519** [comment]
> 不建议直接改CDN里面拿到的文件...

我的意思是这样改可行的话，您能不能在源文件中进行更改

**Comment by 1057189519** [comment]
> 不建议直接改CDN里面拿到的文件...

![image](https://user-images.githubusercontent.com/75262115/221117562-c3691bc3-93db-49a4-ba19-e8c0fb576ba5.png)
在源码的packages\x6\src\util\index.ts中这样更改可以避免这个错误，不知道可行不

**Comment by gfYoboo** [comment]
一般我遇到这样的问题都是position:absolute;top:-9999;width:600px;width:600px;类似这样，让他跑外面，需要显示的时候再把top改回来

**Comment by 1057189519** [comment]
> 一般我遇到这样的问题都是position:absolute;top:-9999px;width:600px;width:600px;类似这样，让他显示在可视区域外面，需要显示的时候再把top改回来

可是这些解决方法都是属于后面打补丁的对吧，是绕过原来的问题

**Comment by NewByVector** [comment]
@1057189519 我试了一下 在 2.x 版本中是好的，此外，umd 包问题也修复了，版本号 2.6.1

**Comment by 1057189519** [comment]
> @1057189519 我试了一下 在 2.x 版本中是好的，此外，umd 包问题也修复了，版本号 2.6.1

试了一下，好了，非常感谢！
