### ISSUE TITLE
咨询一下自定义 React 节点之间能否进行通信

### ISSUE THREAD

**Issue by llllllllr** [antvis/X6#3276]
### 问题描述

自定义 React 节点之间能否进行通信？

某个节点修改了某个值，在不重新渲染画布节点的前提下，请问如何将这个值传给其他节点？

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by lloydzhou** [comment]
使用@antv/x6-react-shape的时候，默认应该是用portal进行渲染的，这个时候，节点内部的react节点应该都在一个统一的App下面，只是没有上下级的层级关系，这种时候，组件之间应该是可以使用redux之类库进行通信的。

**Comment by xiawenqi** [comment]
默认不带portal的，有通信需求的话要自己引用portal
https://x6.antv.vision/zh/docs/tutorial/advanced/react#%E8%8E%B7%E5%8F%96%E7%BB%84%E4%BB%B6%E4%B8%8A%E4%B8%8B%E6%96%87
https://x6.antv.antgroup.com/tutorial/intermediate/react#portal-%E6%96%B9%E5%BC%8F
