### ISSUE TITLE
升级到2.0后，拖动节点出现缺失现象，且连接桩显示不全

### ISSUE THREAD

**Issue by donghuizhou** [antvis/X6#3286]
### 问题描述

项目中原本是使用1.34.6版本X6，现在按照[指南](https://x6.antv.antgroup.com/tutorial/update)升级到2.0后，出现下面2个问题（如下视频所示）：
1. 群组节点在拖拽过程中，出现节点缺失现象
2. 节点一侧的连接桩时有时无

### 重现链接

如下视频

### 重现步骤

见视频

### 预期行为

1. 节点拖拽过程流畅，不出现节点缺失现象
2. 节点的连接桩一直存在，不出现显示一半的现象

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/31002949/220837906-c9dd8d8c-63ea-4c5b-86f0-30873960de1d.mp4

**Comment by donghuizhou** [comment]
排查了下dom，**代码中节点的宽度是固定220px**，在1.x版本中，dom中的宽度是228px，连接桩能显示出来，但在2.x版本中，dom中的宽度是220px，正好是节点宽度，两侧的部分连接桩就显示不出来，如下视频所示：

https://user-images.githubusercontent.com/31002949/220844094-15d58828-57dd-4d66-a96a-de90e5fb0b3f.mp4

**Comment by zhuanqingxiaobaicai** [comment]
我也遇到了一样的问题，期待早日解决

**Comment by donghuizhou** [comment]
已解决 [#3292](https://github.com/antvis/X6/issues/3292#issue-1596590885)
