### ISSUE TITLE
graph.toJSON()是否可以提供包含edge的路径点的数据

### ISSUE THREAD

**Issue by PineSongCN** [antvis/X6#3288]
### 功能描述

根据目前的cells数据无法生成bpmn的xml文件，缺少waypoint的数据

### 期望解决方案

graph.toJSON()提供包含路径点的edges数组，或者在cells.shape = edge的节点增加路径点属性

**Comment by PineSongCN** [comment]
请问有人在吗？

**Comment by PineSongCN** [comment]
哈喽？

**Comment by NewByVector** [comment]
toJSON 返回的数据是包括 vertices 数据的。你可以提供一个 demo 看下。

**Comment by PineSongCN** [comment]
> toJSON 返回的数据是包括 vertices 数据的。你可以提供一个 demo 看下。

你好：https://codesandbox.io/s/billowing-violet-nmlp66?file=/App.tsx

**Comment by PineSongCN** [comment]
> > toJSON 返回的数据是包括 vertices 数据的。你可以提供一个 demo 看下。
> 
> 你好：https://codesandbox.io/s/billowing-violet-nmlp66?file=/App.tsx
> 
> ![image](https://user-images.githubusercontent.com/39976617/222613365-f04d3d41-f6a0-404f-83d8-cfb54dbda6d8.png)

@NewByVector

**Comment by NewByVector** [comment]
@PineSongCN 你这个例子没有 vertices，vertices 的定义参考 http://x6.antv.antgroup.com/tutorial/basic/edge#vertices.

**Comment by PineSongCN** [comment]
我表达有问题，实际上应该是节点之间连接点的position数据，不过不纠结了，如果做bpmn还是LogicFlow似乎更方便些
