### ISSUE TITLE
图表示例，二次贝塞尔曲线，界面无法正常展示

### ISSUE THREAD

**Issue by social-uni** [antvis/X6#3290]
### Describe the bug

https://x6.antv.vision/zh/examples/edge/connector#curve

![image](https://user-images.githubusercontent.com/14007972/220856950-5f10360d-3dee-4fba-8c66-e7b78751566d.png)

### Your Example Website or App

https://x6.antv.vision/zh/examples/edge/connector#curve

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by social-uni** [comment]
> 你需要旋转一下节点吧，他这个二次贝塞尔应该是控制点生成的有问题

谢谢，但是我旋转了下 ，感觉也不是 二次贝塞尔曲线额


![image](https://user-images.githubusercontent.com/14007972/220859259-3a9c8d55-bbb4-451b-8a80-feade392af1a.png)


![image](https://user-images.githubusercontent.com/14007972/220859310-94155004-16a8-4d2e-9e8d-c593cbd23d0c.png)


不太一样呢

**Comment by struggleRoue** [comment]
图中这个是三次贝塞尔，文档写的有问题
二次贝塞尔是一个控制点， 就是demo里的样子
三次贝塞尔是两个控制点，就是你图片里的样子

**Comment by social-uni** [comment]
> 图中这个是三次贝塞尔，文档写的有问题 二次贝塞尔是一个控制点， 就是demo里的样子 三次贝塞尔是两个控制点，就是你图片里的样子

好的，谢谢科普
