### ISSUE TITLE
2.x版本增加Scroller配置后，节点拖动过程会消失

### ISSUE THREAD

**Issue by donghuizhou** [antvis/X6#3292]
### 问题描述

同样的场景，同样的数据，在1.x版本和2.x版本下的不同表现。

**下面是1.x版本下**，开启 `scroller` 配置，关闭 `panning` 配置的效果，可以看到拖动节点时，**节点正常显示，滚动条是实时跟着滚动的**：
```javascript
new Graph({
    scroller: {
        enabled: true,
        pannable: true
    },
    panning: false
})
```
https://user-images.githubusercontent.com/31002949/220874937-3192ff0a-4c8a-4a12-88f1-abcd07dc6029.mp4

 
 
 

**下面是2.x版本下**，开启 `scroller` 配置，关闭 `panning` 配置的效果，可以看到节点拖动时，**滚动条要等拖动结束才会滚动，并且节点拖动过程中会消失**：
```javascript
new Graph({
    panning: false
})
graph.use( // 滚动
  new Scroller({
    enabled: true,
    pannable: true
  })
)
```
https://user-images.githubusercontent.com/31002949/220876539-a4a2c489-2513-4475-b2f5-c8e83c4b94a6.mp4

**下面是2.x版本下**，关闭`scroller` 配置，开启`panning` 配置的效果，可以看到节点拖动过程显示正常：
```javascript
new Graph({
    panning: true
})
// graph.use( // 滚动
//   new Scroller({
//     enabled: true,
//     pannable: true
//   })
// )
```
https://user-images.githubusercontent.com/31002949/220878409-3839f1a4-ef55-4179-b596-f69011babe0d.mp4

我的猜测是，**2.x开启 `scroller` 后，由于滚动条没有跟着节点的移动而实时滚动，所以节点四周的区域不是当前可见区域，所以节点才会消失，等到滚动条滚动后，可见区域变成了当前节点所在区域，所以节点才能看到**，请问这种情况如何解决？

### 重现链接

无

### 重现步骤

如上描述

### 预期行为

在开启 `scroller` 配置后，拖动节点，不出现节点消失现象

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by donghuizhou** [comment]
官网示例里加了 `Scroller` 插件后，也出现拖动节点，滚动条不实时滚动，以及节点消失现象，如何解决呢

https://user-images.githubusercontent.com/31002949/221077677-466fc4a9-91b3-41b4-b5fc-040a3ea6f81b.mp4

**Comment by donghuizhou** [comment]
找到原因了，`scroller` 区分了当前页，如果节点拖拽出当前页，那超出部分的节点不会显示，要等当前页之外的页面渲染完后才展示节点，如下视频所示:

https://user-images.githubusercontent.com/31002949/221125454-1f182c4c-5c60-45ec-bb5f-0d3d89c305a7.mp4

视频末尾可以看到，节点正好拖动到当前页边缘时，`port` 被遮住了一半，体验不友好。

我现在的需求是： 当节点快被拖动到当前页边缘时，能否提前渲染其他页，防止出现节点被裁减现象

[demo](https://codesandbox.io/s/serene-bird-zgqokf?file=/index.ts)

**Comment by oyal** [comment]
之前我在官网示例复现过这个问题，但当时用的 1.x。并且 2.x 往新画布区域拖拽线也是这种情况

![20230307_173813](https://user-images.githubusercontent.com/88022434/223383284-43d7fbc2-ae6c-432c-bb83-9c124cc4e483.gif)

**Comment by lhC0** [comment]
版本1.X中有这个配置解决了当时发生在我代码中的预渲染问题
![image](https://user-images.githubusercontent.com/29115820/223946233-edf79484-c7e7-4779-bb0a-aff3038a71ba.png)
但是升级到2.0这个配置，这个配置似乎删掉了，而且，问题如上所示，比1.X版本更突出

**Comment by donghuizhou** [comment]
@NewByVector 请问那这个bug修的怎么样了

**Comment by nikbabchenko** [comment]
The problem with the scroller negatively affects the user experience, causing some minor glitches.

Would be really nice to have.

**Comment by jrs64** [comment]
> 版本1.X中有这个配置解决了当时发生在我代码中的预渲染问题 ![image](https://user-images.githubusercontent.com/29115820/223946233-edf79484-c7e7-4779-bb0a-aff3038a71ba.png) 但是升级到2.0这个配置，这个配置似乎删掉了，而且，问题如上所示，比1.X版本更突出

最新版本是有这个autoResizeOptions参数的，只是文档上没有写出来

```
   graph.use(
      new Scroller({
        enabled: true,
        pageVisible: true,
        pageBreak: true,
        pannable: true,
        autoResize: true,
          autoResizeOptions: {
            border: 200,
          },
      })
    )

**Comment by donghuizhou** [comment]
> > 版本1.X中有这个配置解决了当时发生在我代码中的预渲染问题 ![image](https://user-images.githubusercontent.com/29115820/223946233-edf79484-c7e7-4779-bb0a-aff3038a71ba.png) 但是升级到2.0这个配置，这个配置似乎删掉了，而且，问题如上所示，比1.X版本更突出
> 
> 最新版本是有这个autoResizeOptions参数的，只是文档上没有写出来
> 
> ```
>    graph.use(
>       new Scroller({
>         enabled: true,
>         pageVisible: true,
>         pageBreak: true,
>         pannable: true,
>         autoResize: true,
>           autoResizeOptions: {
>             border: 200,
>           },
>       })
>     )
> ```

nice

**Comment by QAQLC** [comment]
> border: 200,

设置这个还是无效啊，我是在是scroll插件里面配置的

**Comment by itwmike** [comment]
同问 ， 何时能修复

**Comment by itwmike** [comment]
> > 版本1.X中有这个配置解决了当时发生在我代码中的预渲染问题 ![image](https://user-images.githubusercontent.com/29115820/223946233-edf79484-c7e7-4779-bb0a-aff3038a71ba.png) 但是升级到2.0这个配置，这个配置似乎删掉了，而且，问题如上所示，比1.X版本更突出
> 
> 最新版本是有这个autoResizeOptions参数的，只是文档上没有写出来
> 
> ```
>    graph.use(
>       new Scroller({
>         enabled: true,
>         pageVisible: true,
>         pageBreak: true,
>         pannable: true,
>         autoResize: true,
>           autoResizeOptions: {
>             border: 200,
>           },
>       })
>     )
> ```

按照这个设置确实可以了

**Comment by hanjituan** [comment]
**我目前遇到的情况是:**
默认绘制了分页之外的节点和连线, 对画布不进行操作, 滚动之后, 不会渲染可视区域外的节点和连线.
必须拖动一下其他节点,好像才会重新渲染画布外的节点...
