### ISSUE TITLE
升级2.5.1后报错 throttle is not a function

### ISSUE THREAD

**Issue by rex-ll** [antvis/X6#3297]
### 问题描述

![image](https://user-images.githubusercontent.com/25000285/221078451-b2656570-58dd-462c-8cb3-f5e3bc9c070a.png)

![image](https://user-images.githubusercontent.com/25000285/221078546-8440057f-631c-4eec-b7b6-a9334e4cdaf0.png)

### 重现链接

...

### 重现步骤

直接使用就会报错

### 预期行为

期望不报错，但报错了

### 平台

- 操作系统: macOS, Windows
- 网页浏览器: Google Chrome
- X6 版本: 2.5.1

**Comment by NewByVector** [comment]
把整个 node_modules 删除重新装一下吧，看起来是 x6-common 包没有升级。

**Comment by DoubleRayWang** [comment]
> 把整个 node_modules 删除重新装一下吧，看起来是 x6-common 包没有升级。

问题依然存在

**Comment by DoubleRayWang** [comment]
> x6-common

是不是可以把x6-common作为显式依赖？

**Comment by NewByVector** [comment]
@DoubleRayWang 你的 x6-common 版本是多少？我修改下依赖，重新发一个包。

**Comment by DoubleRayWang** [comment]
> @DoubleRayWang 你的 x6-common 版本是多少？我修改下依赖，重新发一个包。

之前x6-common没声明在dependencies里，刚试了把x6-common作为显式依赖，版本用的最新的2.0.10，报错的问题就没有了

**Comment by NewByVector** [comment]
其实不需要用显示依赖的，x6 本身依赖了这个 我试了下，重新装整个 node_modules 是会重新加载最新的 x6-common 的。

**Comment by bodinsamuel** [comment]
I confirm I had the same issues and I had to `npm install -ED @antv/x6-common` to get rid of the error :relaxed:

**Comment by DoubleRayWang** [comment]
> I confirm I had the same issues and I had to `npm install -ED @antv/x6-common` to get rid of the error ☺️

In fact, there is nothing inappropriate as an explicit dependency, as long as the author does not modify the reference relationship of the underlying package in future upgrades.

**Comment by DoubleRayWang** [comment]
> 其实不需要用显示依赖的，x6 本身依赖了这个 我试了下，重新装整个 node_modules 是会重新加载最新的 x6-common 的。

@antv/x6的依赖表中  "@antv/x6-common": "^2.0.x" 改成 "@antv/x6-common": "^2.0.10" 应该就没问题了

**Comment by NewByVector** [comment]
If so, we should manually change the version number each time.
