### ISSUE TITLE
动态更改node大小时,小地图动态更新

### ISSUE THREAD

**Issue by luckyjiu9** [antvis/X6#3299]
### 问题描述

![image](https://user-images.githubusercontent.com/86637918/221098140-8696fe42-f95f-455a-bcea-ab44553b18d4.png)

### 重现链接

![image](https://user-images.githubusercontent.com/86637918/221098140-8696fe42-f95f-455a-bcea-ab44553b18d4.png)

### 重现步骤

node.resize更改节点宽高后 小地图未更新 宽度动态改变,高度及内容未更新

### 预期行为

小地图动态更新宽高

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

<img width="679" alt="99499e6c5cca648f70e1891eb1ecc50a" src="https://user-images.githubusercontent.com/86637918/221098434-4d6ca032-ed9b-4dff-8404-e1e7e3f57e1a.png">

### 补充说明（可选）

node.resize更改节点宽高后 小地图未更新 宽度动态改变,高度及内容未更新

**Comment by NewByVector** [comment]
我本地试了一下是可以动态更新的，能否提供一个可以复现的 demo 呢？
