### ISSUE TITLE
setAttrs sometimes do not work as expected 

### ISSUE THREAD

**Issue by bruceauyeung** [antvis/X6#3300]
### Describe the bug

~~~
      const attr = this.curCel.getAttrs(); 
      attr.text.text = 'bb';
      this.curCel.setAttrs(attr); // will not trigger canvas rendering

      this.curCel.setAttrs({ text: { text: 'bb' } }); // will  trigger canvas rendering
~~~

### Your Example Website or App

no website

### Steps to Reproduce the Bug or Issue

no steps needed

### Expected behavior

i expect that the first invocation would change node's text attr(as expected), and rerender canvas so i can see node's text being changed(not as expected)
i dont know what's under the hood, and i can not tell what's the differences between these two invocations.

### Platform

- OS: linux
- Browser: chrome  103
- antv/x6 2.4.0

**Comment by lloydzhou** [comment]
层级深的时候，想要做深层的diff是一个比较麻烦的事情。
如果强行逐层递归比较，往往带来性能问题。
如果不逐层比较，就会出现现在这种更新不了的情况。

所以建议使用`immer`这样的库来管理数据。

**Comment by NewByVector** [comment]
Now x6 determines attribute changes based on object references. The setAttrs parameter passed in your example above is the same as the attr parameter reference itself and will not be detected. But it does create a little bit of trouble here. We might do some optimization later.
