### ISSUE TITLE
【1.x】async为true时，渲染完成后把根容器隐藏，此时调用setAttr等可以重绘画布的API，连线会错位

### ISSUE THREAD

**Issue by linkun-wang** [antvis/X6#3302]
### 问题描述

1.x版本下，如果开启了async，隐藏画布容器后，执行会引发画布重绘的操作（比如setAttrs）,然后再展示画布容器，会发现连线错乱了：
正常情况：
![image](https://user-images.githubusercontent.com/33945539/221164769-4e1ec73f-527b-4a5b-b388-c0f5ab2e3407.png)
隐藏画布后更新节点状态：
![image](https://user-images.githubusercontent.com/33945539/221164922-f11416d2-3d35-4914-bf0b-47da3e8d0b1f.png)

### 业务场景
业务中执行一个流程可能时间比较长，所以允许用户隐藏流程页面，流程执行过程中节点会自动更新各节点状态，然后再次展示时更新过状态的节点就会出现连线错位的问题

### 重现链接

https://codesandbox.io/s/asyncce-shi-ct4fys?file=/src/app.tsx

### 重现步骤

1. 进入页面，x6版本1.x（demo中是1.32.8），开启```async```
2. 先点击某个节点
3. 点击【隐藏根容器】
4. 点击【更新节点】按钮
5. 点击【展示根容器】后，会发现更新后的节点连线错位了

### 预期行为

隐藏画布容器后，更新节点状态不会引发连线错位

### 平台

- 操作系统: [ Windows ]
- 网页浏览器: [ Google Chrome, v110.0.5481.104（正式版本64 位）]
- X6 版本: [ 1.32.8 ]

### 屏幕截图或视频（可选）

![隐藏容器连线错位](https://user-images.githubusercontent.com/33945539/221165308-2837cdcc-a088-48da-a400-b235eb0e9bfb.gif)

**Comment by NewByVector** [comment]
V1 版本需要避免这种场景，因为画布隐藏后，很多位置和尺寸计算(getBBox())就不正确了，这个是浏览器 API 决定的，所以 V1 版本应该从产品交互上避开这种行为。

**Comment by NewByVector** [comment]
其实也可以通过样式将画布移动到不可见范围。

**Comment by linkun-wang** [comment]
> V1 版本需要避免这种场景，因为画布隐藏后，很多位置和尺寸计算(getBBox())就不正确了，这个是浏览器 API 决定的，所以 V1 版本应该从产品交互上避开这种行为。

V2版本不存在这个问题吗？

**Comment by NewByVector** [comment]
@linkun-wang V2 也可能会出现这个场景。
