### ISSUE TITLE
createEdge表现不符合预期

### ISSUE THREAD

**Issue by lloydzhou** [antvis/X6#3304]
### 问题描述

createEdge表现不符合预期

### 重现链接

https://codesandbox.io/s/antv-x6-createedgebu-fu-he-yu-qi-epbo9q?file=/src/App.tsx

### 重现步骤

<p>１. 使用createNode,createEdge生成node1,node2,edge</p>
        <p>２. 添加node1: graph.addCell(node1.current);</p>
        <p>３. 添加edge: graph.addCell(edge.current)</p>
        <p>
          ４．虽然node2不存在，但是edge添加成功，model数据正常，svg里面只有g标签
        </p>
        <p>５. 延时100ms添加node2，edge还是不展示</p>

### 预期行为

1. edge = graph.createEdge()的时候，提示节点不存在
2. graph.addCell(edge)的时候要么完全不渲染，要么提示错误
3. 如果前面两个步骤能把边添加到model里面，那么后续graph.addCell(node2)的时候，edge需要正常展示

### 平台

- 操作系统: [Linux]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.5.1 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/1826685/221333816-0fc73192-9e8a-415b-be9f-ccd2f96fc903.png)

**Comment by lloydzhou** [comment]
async=false模式下会有报错信息

![image](https://user-images.githubusercontent.com/1826685/221340091-e9fc3266-dd85-4953-a399-b89d1927a591.png)

**Comment by JamesTing** [comment]
1、node、edge为什么要用useRef实现呢？感觉是useRef.current赋值导致的。
2、请使用addEdge这种写法
我修改了你的代码，现在生效了

```
import React from "react";
import { Graph } from "@antv/x6";
import "./styles.css";

const App = () => {
  const containerRef = React.useRef<HTMLDivElement>(null);

  React.useEffect(() => {
    const graph = new Graph({
      container: containerRef.current!,
      width: 800,
      height: 800,
      background: {
        color: "#F2F7FA"
      }
    });
   const node1 = graph.createNode({
      id: "1",
      shape: "rect",
      x: 100,
      y: 100,
      width: 100,
      height: 50,
      label: "source",
      attrs: {
        body: {
          stroke: "#8f8f8f",
          strokeWidth: 1,
          fill: "#fff",
          rx: 6,
          ry: 6
        }
      }
    });

    const node2 = graph.createNode({
      id: "2",
      shape: "circle",
      x: 300,
      y: 100,
      width: 50,
      height: 50,
      label: "target",
      attrs: {
        body: {
          stroke: "#8f8f8f",
          strokeWidth: 1,
          fill: "#fff"
        }
      }
    });
    graph.addNode(node1);
    graph.addNode(node2);

    graph.addEdge({
      source:'1',
      target:'2',
      attrs: {
        line: {
          stroke: '#A2B1C3',
          strokeWidth: 2,
        },
      },
    })
    
    console.log("graph", graph);
  }, []);

  return (
    <div className="app">
      <div className="toolbar">
        <p>１. 使用createNode,createEdge生成node1,node2,edge</p>
        <p>２. 添加node1: graph.addCell(node1.current);</p>
        <p>３. 添加edge: graph.addCell(edge.current)</p>
        <p>
          ４．虽然node2不存在，但是edge添加成功，model数据正常，svg里面只有g标签
        </p>
        <p>５. 延时100ms添加node2，edge还是不展示</p>
        {/* <button onClick={() => graph.removeCell(node2.current)}>移除node2</button> */}
      </div>
      <div className="graph" ref={containerRef}></div>
    </div>
  );
};

export default App;
```

**Comment by lloydzhou** [comment]
问题不在于是否使用了ref，而是node2不存在的时候添加edge，和预期表现不一致

![image](https://user-images.githubusercontent.com/1826685/221786999-64c4fe50-4d84-46de-aa2b-bb44bc6cac91.png)

**Comment by NewByVector** [comment]
这个需要统一抛出异常的。
