### ISSUE TITLE
router的manhattan算法中excludeShapes失去效果了？

### ISSUE THREAD

**Issue by gfYoboo** [antvis/X6#3305]
### Describe the bug

如题所示，然后我看源码，发现ManhattanRouterOptions中只有excludeTerminals和excludeNodes了是这个功能有哪里有缺陷吗？

### Your Example Website or App

http://flow.qyuit.com/

### Steps to Reproduce the Bug or Issue

因为我这个图形有叠加，需要排除所有的某类图形。
connecting是在实例化的时候就传入了，后续的图形都是addNode一个个的添加的，如果只能用Node或id那么需要添加的时候保存下来，然后再去修改connecting的router的excludeNodes。
excludeNodes() {
  return store.dutyCellIds;
}
不如原来用excludeShapes直观。

### Expected behavior

后续有计划吗？还是这个属性就直接删除了？

### Platform

主流

**Comment by WinterWoods** [comment]
同样遇到了该问题。group组件无法使用excludeShapes忽略

**Comment by WinterWoods** [comment]
什么时候能解决

**Comment by JerryWang24** [comment]
我遇到了无法使用excludeShapes忽略使用x6-vue-shape注册的shape。
下面是我的代码，使用了没有效果。
register({
  shape: 'tva',
  component: Tva
})

`const graph = new Graph({
      container: document.getElementById('dt-chart'),
      grid: true,
      connecting: {
        allowBlank: false, // 不允许连接到画布空白
        allowLoop: false,
        allowNode: false,
        router: {
          name: 'manhattan',
          excludeShapes: [
            'tva'
          ],
          args: {
            startDirections: ['top'],
            endDirections: ['top']
          }
        }
      }
    })`
