### ISSUE TITLE
不能主动设置port的x,y

### ISSUE THREAD

**Issue by Mrheqiang** [antvis/X6#3315]
### 问题描述

`rect.addPort({ id: 'port3', group: 'group1', args: {x: 50,y: 30} })`
`rect.portProp('port2', {args: {x: 50,y: 30}})`
`items: [{ id: 'port1', group: 'group1', args: {x,y} },{ id: 'port2', group: 'group1', args: {dy: 20,y: 600} }]`
以上三种设置port的x,y位置信息不能生效

### 重现链接

https://codesandbox.io/s/elegant-sinoussi-d628pi?file=/src/Antv.js

### 重现步骤

进入页面  添加port  设置port的 args 属性中的xy

### 预期行为

可以自由设置port的位置信息，但是只能设置port的偏移量，目前只有absolute可以设置其余预设的都不行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
[absolute](http://x6.antv.antgroup.com/api/registry/port-layout#absolute) 就能满足自由定位需求呀。
