### ISSUE TITLE
x6有没有类似于g6的紧凑树布局方式或者说自定义一个布局，脑图满足不了具体需求

### ISSUE THREAD

**Issue by 2510340910** [antvis/X6#3319]
### 问题描述

实现新添节点、删除节点等功能，可以达到和g6的紧凑树布局一样的效果

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
X6 和 G6 的布局都是基于 @antv/layout 这个库。

**Comment by ysqysq123** [comment]
你好，怎样学习@antv/layout这个库

**Comment by ysqysq123** [comment]
> X6 和 G6 的布局都是基于 @antv/layout 这个库。

你好，怎样学习@antv/layout这个库

**Comment by NewByVector** [comment]
@ysqysq123 可以参考[文档](https://g6.antv.antgroup.com/api/tree-graph-layout/compact-box)。
