### ISSUE TITLE
x6-common sourcemap  地址错误

### ISSUE THREAD

**Issue by yeyan1996** [antvis/X6#3321]
### Describe the bug

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/39046570/221825370-5d60651e-3a0d-409a-a1fd-c8bd9fd63a24.png">

x6-common 的 src 没有暴露出来，导致找不到 sourcemap

### Your Example Website or App

no url

### Steps to Reproduce the Bug or Issue

下载 @antv/x6-commmon@2.0.8

### Expected behavior

能找到 sourcemap

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by unforesndprson** [comment]
@antv/layout 1.x版本也是同样的问题，话说3.x支持@antv/x6 1.x吗. 找不到更新日志   😂
