### ISSUE TITLE
export 'Addon' (imported as 'Addon') was not found in '@antv/x6'

### ISSUE THREAD

**Issue by wojiushiqiji** [antvis/X6#3322]
### 问题描述

webpack打包时，提示export 'Addon' (imported as 'Addon') was not found in '@antv/x6'，在实际效果中因为这个错误导致报错

### 重现链接

https://codesandbox.io/s/reverent-proskuriakova-vfomyh?file=/src/index.js

### 重现步骤

在index.js中const stencil = new Addon.Stencil({报错，Cannot read properties of undefined (reading 'Stencil')，实际是@antv/x6中没有Addon

### 预期行为

希望可以获得解答

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![微信图片_20230228185650](https://user-images.githubusercontent.com/46197995/221834113-d8d29889-9fb2-4627-b120-8d430ba9cc84.png)

**Comment by xiawenqi** [comment]
X6版本错误或者你引用的方式错了，X6 2.0的插件在单独的包里了。

`import { Stencil } from "@antv/x6-plugin-stencil";
`

https://x6.antv.antgroup.com/tutorial/plugins/stencil

**Comment by 1148716206** [comment]
我也遇到同样的问题，axtv/x6里面没有Addon这个包 "export 'Addon' was not found in '@antv/x6'
