### ISSUE TITLE
2.x transform 插件没提供 通过方法进行选中

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3324]
### 功能描述

我有个图层,  希望点击图层调用方法 对这个点击的节点进行 图形变换,
目前是临时使用这个方法, 这个方法暂未暴露出来
graph.getPlugin('transform').onNodeClick({ node: graph.getCellById('5cd85fe4-74eb-4f54-8fb1-f678551d1db8') })

### 期望解决方案

可以提供一个专门的方法

**Comment by struggleRoue** [comment]
你希望把这个挂载到graph上？

**Comment by JoeABCDEF** [comment]
> 你希望把这个挂载到graph上？

不是, onNodeClick, clearWidgets  我使用 的时候 ts报错 , 怕以后 这些  api 你们会有所更改, 导致后期更新就报错了, 希望可以确定这个api 就是这个意思

**Comment by struggleRoue** [comment]
了解了

**Comment by NewByVector** [comment]
其实可以暴露两个方法出来的，createWidget 和 clearWidget

**Comment by hanyuesoyeon** [comment]
你好，请问现在有方法可以调用使当前点击的node取消或者设置图形变换吗？

**Comment by yi749027176** [comment]
> > 你好，请问现在有方法可以调用使当前点击的node取消或者设置图形变换吗？ @antv/x6-plugin-transform要多少版本有这个功能呀，急需要
> 
> @hanyuesoyeon 我用的这个 `GraphInstance.getPlugin("transform").onNodeClick({ node: cells[0] });`

onNodeClick is not a function，这个方法不是protected的，怎么调用得到？
