### ISSUE TITLE
自定义节点中，增加的text如何居中对齐

### ISSUE THREAD

**Issue by TalentJY** [antvis/X6#3326]
### 问题描述

我注册了节点，其中包含一个image和两个text，发现他们的位置是放在左上角，于是我想调整位置，但发现，只能使用固定的偏移来调整位置，但是我的text是有编辑的需求的，偏移量写死了，修改text又无法对齐了。

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

我想要将自定义节点中的text，放到image节点水平居中位置，同时编辑text后，依然能居中。
现在，将位置写死后，编辑text会导致又不居中对齐了。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.x ... ]

**Comment by struggleRoue** [comment]
你是如何自定义的节点

**Comment by TalentJY** [comment]
> 

            Graph.registerNode(
                deviceModel,
                {
      
                    markup: [
                        {
                            tagName: 'image',
                            selector: 'body',
                         },
                        {
                            tagName: 'text',
                            selector: 'text1',
                        },
                        {
                            tagName: 'text',
                            selector: 'text2',
                        },
                    ],
                    attrs: {
                     

                        body: {
                            'xlink:href': image,
                            height: size,
                            width: size,
                        },
                        text1: {
                            text: text1,
                            refY: -10,
                            fill: '#1993FF',
                            fontSize: 12,
                        },
                        text2: {
                            text: "text2",
                            refY: size + 2,


                        }
                    },
                },
                true,
            )

**Comment by TalentJY** [comment]
> 你是如何自定义的节点

如上

**Comment by struggleRoue** [comment]
import { Graph } from '@antv/x6'

Graph.registerNode(
  'custom-node',
  {
    width: 200,
    height: 60,
    attrs: {
      body: {
        stroke: '#5F95FF',
        strokeWidth: 1,
        fill: 'rgba(95,149,255,0.05)',
        refWidth: 1,
        refHeight: 1,
      },
      text: {
        text: 'this is cofdsfdsffdsntent text',
        fontSize: 12,
        refX: 100,
        refY: 23,
        fill: 'rgba(0,0,0,0.6)',
        'text-anchor': 'middle',
        'dominant-baseline': 'middle'
      },
    },
    markup: [
      {
        tagName: 'rect',
        selector: 'body',
      },
      {
        tagName: 'text',
        selector: 'text',
      },
    ],
  },
  true,
)

const graph = new Graph({
  container: document.getElementById('container')!,
  grid: true,
})

graph.addNode({
  x: 200,
  y: 160,
  shape: 'custom-node',
})

像这样？

**Comment by TalentJY** [comment]
> ```
> import { Graph } from '@antv/x6'
> 
> Graph.registerNode(
>   'custom-node',
>   {
>     width: 200,
>     height: 60,
>     attrs: {
>       body: {
>         stroke: '#5F95FF',
>         strokeWidth: 1,
>         fill: 'rgba(95,149,255,0.05)',
>         refWidth: 1,
>         refHeight: 1,
>       },
>       text: {
>         text: 'this is cofdsfdsffdsntent text',
>         fontSize: 12,
>         refX: 100,
>         refY: 23,
>         fill: 'rgba(0,0,0,0.6)',
>         'text-anchor': 'middle',
>         'dominant-baseline': 'middle'
>       },
>     },
>     markup: [
>       {
>         tagName: 'rect',
>         selector: 'body',
>       },
>       {
>         tagName: 'text',
>         selector: 'text',
>       },
>     ],
>   },
>   true,
> )
> 
> const graph = new Graph({
>   container: document.getElementById('container')!,
>   grid: true,
> })
> 
> graph.addNode({
>   x: 200,
>   y: 160,
>   shape: 'custom-node',
> })
> ```
> 
> 像这样吗？

是的 非常感谢， 'dominant-baseline': 'middle' 这个属性 在哪能看到呢，官网文档里面似乎没有

**Comment by struggleRoue** [comment]
参考svg的文档吧。
