### ISSUE TITLE
History does not work with vertices

### ISSUE THREAD

**Issue by bodinsamuel** [antvis/X6#3327]
### Describe the bug

Hey,

When using the History Plugin, it realised the vertices event are received by the `beforeAddCommand` but they are not actually handled by the plugin. Maybe it's a limitation of the plugin which would be sad, but maybe it's just a mistake. 

Currently when we add/remove vertices they are ignored by the undo/redo feature.

PS: the function `beforeAddCommand` sometimes receive one argument and sometimes two, but not the same order, which makes it harder to use and I didn't understand why.

### Your Example Website or App

https://codesandbox.io/s/new-sky-n37gp1?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1. Add a vertice
2. Click undo
3. The step before the vertice is undo but not the vertice

### Expected behavior

The vertice add/remove should be part of the stack.

### Screenshots or Videos

https://user-images.githubusercontent.com/1637651/222148276-39ffdfb1-3c0e-4710-98d3-f566c442c4d0.mov

### Platform

- OS: macOS
- Browser: Chrome
- Version: 110

**Comment by NewByVector** [comment]
Please upgrade to @antv/x6@2.11.5.
