### ISSUE TITLE
升级到 2.5.1 报错

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3328]
### 问题描述

![image](https://user-images.githubusercontent.com/39638510/222152340-6ff4b41a-c71e-414e-93ec-b20fcfe85065.png)
报这个错误

在回退到 2.1.4 正常没问题

### 重现链接

无

### 重现步骤

升级到 2.5.1

### 预期行为

希望可以正常使用

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 2.5.1

**Comment by NewByVector** [comment]
更新一下 x6-common 到最新版本即可。

**Comment by JoeABCDEF** [comment]
可以了
