### ISSUE TITLE
Use AntV/X6 in Angular

### ISSUE THREAD

**Issue by TangLisan** [antvis/X6#333]
### Expected Behavior
The Angular component implementing the example (https://x6.antv.vision/zh/docs/tutorial/getting-started)  should work

### Current Behavior
The dependencies referred in X6 cannot be compiled successfully

### Steps To Reproduce

1. Install X6 with command: npm install @antv/x6
2. Install dependencies:
2.1 jquery: npm install jquery, npm install @types/jquery
2.2 mousetrap: npm install mousetrap, npm install @types/mousetrap
3. start app using command: nv serve --open

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->

 additional asset processing copy-webpack-plugin    
    ERROR in ../../@antv/x6/lib/util/index.d.ts:1:8 - error TS1259: Module '"D:/oss/76_Angular/99_study/ts08/node_modules/@types/jquery/index"' can only be default-imported using the 'allowSyntheticDe
faultImports' flag
    1 import $ from 'jquery';
             ~
      ../../@types/jquery/index.d.ts:35:1
        35 export = jQuery;
           ~~~~~~~~~~~~~~~~
        This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
    ../../@antv/x6/lib/graph/keyboard.d.ts:8:25 - error TS2304: Cannot find name 'MousetrapInstance'.
    
    8     readonly mousetrap: MousetrapInstance;
                              ~~~~~~~~~~~~~~~~~
    ../../@antv/x6/lib/graph/keyboard.d.ts:40:51 - error TS2304: Cannot find name 'MousetrapInstance'.
    
    40     function createMousetrap(keyboard: Keyboard): MousetrapInstance;
```

</p></details>

### Your Environment

- x6: 1.0.7
- OS: Windows 10
- Browser: Chrome 87.0.4280.66

**Comment by bubkoo** [comment]
@TangLisan 给一个 CodeSandbox 的复现链接。

**Comment by TangLisan** [comment]
@bubkoo 
刚才测试了一下，在
1. CodeSandbox 可运行
2. 在我原来的Angular工程可运行
3. 在若干新建的Angular工程不可运行
问题出在我的开发环境，但目前还没找到原因，谢谢您的及时支持

**Comment by TangLisan** [comment]
麻烦您关闭此问题
