### ISSUE TITLE
文档优化意见收集

### ISSUE THREAD

**Issue by bubkoo** [antvis/X6#334]
你期待的好用的文档是怎么样的？
文档是否缺失了什么？
希望哪些部分更加详细？

关于文档的任何意见，欢迎直接反馈到这里，我们会持续优化。

**Comment by AK081KA** [comment]
是否有vue demo实现的计划

**Comment by bubkoo** [comment]
@AK081KA 有计划但是人手不够，是否可以贡献代码？

**Comment by NewByVector** [comment]
增加SVG基础栏目，虽然文档中有MDN链接，还是需要把一些常用的SVG知识说明一下，这样用户上后X6更有体感(完全没有上手难度)

**Comment by i5ting** [comment]
加一个使用x6的项目，比如 https://github.com/imgcook/imove ，大家互相链接一下。也可以扩展一下大家使用x6的应用场景

**Comment by bubkoo** [comment]
@i5ting 我们可以开个 issue 收集一下

**Comment by HelloToBe-San** [comment]
能否增加导出Word功能

**Comment by NewByVector** [comment]
> 能否增加导出Word功能

这个可以自己上层做一下，暂时没有增加这个功能的计划

**Comment by east119** [comment]
![image](https://user-images.githubusercontent.com/9639162/104431077-73380680-55c2-11eb-8f5a-734fd1229d21.png)
1.graph.on是不是应该监听上面自定义的事件port:click
2.“ndoe:click”拼写错误

**Comment by daigang666** [comment]
强烈建议做一个代码及效果分享的网站，例如[http://topology.le5le.com/search?q=](url) 或者echarts效果的网站，这样能减少上手成本，提高X6普及度

**Comment by NewByVector** [comment]
> 常见问题： [怎么监听连接桩的点击事件](https://antv-x6.gitee.io/zh/docs/tutorial/faq/epilog#%E6%80%8E%E4%B9%88%E7%9B%91%E5%90%AC%E8%BF%9E%E6%8E%A5%E6%A1%A9%E7%9A%84%E7%82%B9%E5%87%BB%E4%BA%8B%E4%BB%B6)
> 1.graph.on是不是应该监听上面自定义的事件port:click
> 2.“ndoe:click”拼写错误

文档错误，已解决

**Comment by poetwolf** [comment]
文档错误： [API History](https://x6.antv.vision/zh/docs/api/graph/history/#gatsby-focus-wrapper)
`
const graph = new Graph({
  history: {
    enable: true,
  },
})
`
enable 应该写成enabled

**Comment by little-snow-fox** [comment]
请问如何对绘制好的流程图格式化为JSON？同时，如何快速解析JSON重新渲染流程图？有这方面的文档吗？

**Comment by NewByVector** [comment]
> 文档错误： [API History](https://x6.antv.vision/zh/docs/api/graph/history/#gatsby-focus-wrapper)
> `const graph = new Graph({ history: { enable: true, }, })`
> enable 应该写成enabled

https://github.com/antvis/X6/pull/614 已经修复

**Comment by wangyubin91** [comment]
x6-app-draw 这个demo，如果节点文本过长或换行，流程图导出json后， 再将json导入至流程图，原来那个阶段的文本不显示了
必须双击后，才会显示
导出方法
const outJson = () => {
    const { graph } = FlowGraph
    var jsondata = JSON.stringify(graph.toJSON())
    console.log(jsondata)
    return true
   

 #导入方法
const inJson = () => {
    const { graph } = FlowGraph
    graph.fromJSON(graphData2)
    return true
  }

**Comment by NewByVector** [comment]
> x6-app-draw 这个demo，如果节点文本过长或换行，流程图导出json后， 再将json导入至流程图，原来那个阶段的文本不显示了
> 必须双击后，才会显示
> 导出方法
> const outJson = () => {
> const { graph } = FlowGraph
> var jsondata = JSON.stringify(graph.toJSON())
> console.log(jsondata)
> return true
> 
> #导入方法
> const inJson = () => {
> const { graph } = FlowGraph
> graph.fromJSON(graphData2)
> return true
> }

已经修复 https://github.com/antvis/X6/pull/653

**Comment by superbt** [comment]
请问 X6 对浏览器 的支持情况

**Comment by NewByVector** [comment]
> 请问 X6 对浏览器 的支持情况

"browserslist": [
    "last 2 versions",
    "Firefox ESR",
    "> 1%"
  ],

**Comment by demonskp** [comment]
现在文档中。关于每个API中的对象方法，描述还是太少了。比如：graph 里的 modal对象，和graph里addNode addEdge等等方法，文档里都没有。

**Comment by NewByVector** [comment]
> 现在文档中。关于每个API中的对象方法，描述还是太少了。比如：graph 里的 modal对象，和graph里addNode addEdge等等方法，文档里都没有。

文档里有的，可以是用官网的搜索功能

**Comment by caos0813** [comment]
请问怎么可以拖动左边的html标签到画布中呀，节点直接写html代码

**Comment by demohi** [comment]
目前的文档过于分散，期望有一个统一的 api 文档

**Comment by abao1994520** [comment]
> 是否有vue demo实现的计划

期待

**Comment by east119** [comment]
https://x6.antv.vision/zh/docs/api/model/cell#hastools
hasTools的参数也是字符串吗？试了一下不好使，应该是数组字符串吧，要不和hasTool没什么区别了

**Comment by tian3937** [comment]
getCellById 文档里好像没有，使用fromJSON的情况下 挺需要这种方式找cell的

**Comment by NewByVector** [comment]
@tian3937  已经优化文档 #975

**Comment by 1637410810** [comment]
文档Cell缺失postprocess

**Comment by Choicelin** [comment]
如何对同一个节点动态修改，删除，添加连接桩

**Comment by NewByVector** [comment]
@Choicelin addPort removePort portProp https://x6.antv.vision/zh/docs/api/model/node#%E9%93%BE%E6%8E%A5%E6%A1%A9-ports

**Comment by Choicelin** [comment]
有一个getCell的api实际是有的，但是搜索搜不到

**Comment by NewByVector** [comment]
@Choicelin getCell 后面版本会废弃，用 [getCellById](https://x6.antv.vision/zh/docs/api/graph/model/#getcellbyid) 替代

**Comment by NewByVector** [comment]
内容太多，有问题直接提 issue

**Comment by Mrheqiang** [comment]
目前有个需求，需要**动态修改连接桩标签**，但是目前只发现在增加Node的时候有个port属性，一旦初始化完成之后就没有看到修改连接桩信息的入口，求告知
