### ISSUE TITLE
有没有X6实现动画的案例。比如旋转，变大变小等

### ISSUE THREAD

**Issue by TalentJY** [antvis/X6#3345]
### 问题描述

看官网是有动画的API的，但是没有案例。之前用的G6的库，有几个动画的案例不知道在X6要怎么实现？

### 重现链接

https://g6.antv.antgroup.com/zh/examples/scatter/node/#node

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2 ... ]

**Comment by lloydzhou** [comment]
x6的元素是SVG的，可以通过CSS做动画
