### ISSUE TITLE
cell.prop('shape', type); 不起作用

### ISSUE THREAD

**Issue by jianjianghui** [antvis/X6#3349]
### Describe the bug

 // 有一个动态变更节点形状的需求；使用prop方法更新shape不起作用
代码如下： 
node.prop('shape', type); // 不起作用
node.prop("size", {width: 120, height: 50}) // 渲染正常

### Your Example Website or App

any demo

### Steps to Reproduce the Bug or Issue

let node = graph.getCellById(nodeId);
node.prop('shape', type);  // 不起作用

### Expected behavior

成功变更形状

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [110.0]

**Comment by JamesTing** [comment]
我之前也试过，cell.prop好像不支持改变shape。
最终，我将节点通过自定义react组件实现，根据cell的data属性渲染组件形状。

**Comment by lloydzhou** [comment]
x6内部将不同的shape注册成为不同的节点（应该算是一个继承自Node的class）
所以，简单的通过更改prop('shape')理论上应该是不能让一个object更改自己的class类型的。

**Comment by lloydzhou** [comment]
> x6内部将不同的shape注册成为不同的节点（应该算是一个继承自Node的class） 所以，简单的通过更改prop('shape')理论上应该是不能让一个object更改自己的class类型的。

不过从javascript使用[prototype chain](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)进行继承这个特性上来说，动态更改class类型似乎也是能实现的，但是不知道会不会有其他的副作用...

**Comment by NewByVector** [comment]
不支持修改 shape 属性的。
