### ISSUE TITLE
x6 2.0版本新增树节点报错，复制得示例

### ISSUE THREAD

**Issue by haosusu** [antvis/X6#3351]
### Describe the bug

![image](https://user-images.githubusercontent.com/41900402/223135439-4802e796-8327-4827-b191-cdec34354549.png)
![image](https://user-images.githubusercontent.com/41900402/223135635-28dd1dd9-5565-48f6-80bd-f21f4f6b9ebe.png)

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

新增树节点或者删除都会报这个错

### Expected behavior

版本1.0不报错，2.0报错，怎么兼容

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jianjianghui** [comment]
![28f78f0c6cca447d653d34614a74b9a](https://user-images.githubusercontent.com/62538668/223179939-1e3c639d-223e-4f05-a712-f5c315b8489e.png)
![77d157b23ecc7791f9e26ad94a0a320](https://user-images.githubusercontent.com/62538668/223179963-29ae4c37-2290-4d7e-83d3-a1f962a1f0fd.png)
同一套业务代码，左侧好的，右侧出问题了；右侧是流水线部署的，每次都会npm install！
所以这个问题??????

**Comment by jianjianghui** [comment]
经过测试 @antv/x6 2.5.3版本会出现该问题；指定2.5.1版本后该问题不存在；

**Comment by jianjianghui** [comment]
package.json

**Comment by jianjianghui** [comment]
https://github.com/antvis/X6/commit/1de8ebe77abe9820229c3e99f8b75ee6f6058112

**Comment by lloydzhou** [comment]
建议这里willRemoveViews直接变成`Set<ViewId>()`　访问view对象还是从`this.views`获取

**Comment by NewByVector** [comment]
更新到 @antv/x6@2.5.4
