### ISSUE TITLE
2.5.2版本使用报错

### ISSUE THREAD

**Issue by qu-niao** [antvis/X6#3355]
### Describe the bug

如下图所示
![image](https://user-images.githubusercontent.com/126561001/223330438-333d5b71-a460-4c25-b96e-8dcddc45c16c.png)

官方示例代码报错
![image](https://user-images.githubusercontent.com/126561001/223330472-bfd5e73a-8f44-4023-ad0f-2ee69a7c06ac.png)

### Your Example Website or App

官网示例

### Steps to Reproduce the Bug or Issue

官网示例

### Expected behavior

官网示例

### Screenshots or Videos

官网示例

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
2.5.2

**Comment by vivien8261** [comment]
x6 2.5.3，x6-vue-shape 1.5.4，Vue 2.5.11 复现

**Comment by oyal** [comment]
> x6-vue-shape

x6-vue-shape 用 2.x 版本

**Comment by vivien8261** [comment]
> > x6 2.5.3，x6-vue-shape 1.5.4，Vue 2.5.11 复现
> 
> x6-vue-shape 用 2.x 版本

可是直接install的就是1.5.4，具体版本是什么呢

**Comment by oyal** [comment]
> > > x6 2.5.3，x6-vue-shape 1.5.4，Vue 2.5.11 复现
> > 
> > 
> > x6-vue-shape 用 2.x 版本
> 
> 可是直接install的就是1.5.4，具体版本是什么呢

npm i @antv/x6-vue-shape@2

**Comment by vivien8261** [comment]
> > > > x6 2.5.3，x6-vue-shape 1.5.4，Vue 2.5.11 复现
> > > 
> > > 
> > > x6-vue-shape 用 2.x 版本
> > 
> > 
> > 可是直接install的就是1.5.4，具体版本是什么呢
> 
> npm i @antv/x6-vue-shape@2

谢谢

**Comment by NewByVector** [comment]
已经修复了 x6-react-shape 和 x6-vue-shape 两个包的 latest 指向，重新安装，会安装最新版本。
