### ISSUE TITLE
反序列化如何让连线按照全局设定的连线规则绘制？

### ISSUE THREAD

**Issue by yuanbolin** [antvis/X6#3360]
### Describe the bug

反序列数据连线不按照设置了设置的全局连线规则绘

### Your Example Website or App

未上线无法访问

### Steps to Reproduce the Bug or Issue

绘制时全局设置连线规则为：
      // 连线规则
      router: {
        // 连线路径点规则
        name: "manhattan", // 自动避开路径上的其他节点
        args: {
          padding: 40
        }
      },
因padding设置为40，连线都会按照规则绘制。 但序列化存储后再反序列存储的数据（观察序列化的数据并不会带有设置规则）。虽在反序列前也设置了同样的连线规则，但绘制的线路是按照padding：0进行绘制的。

### Expected behavior

希望反序列数据，也能按照全局设置的连线规则绘制。

### Screenshots or Videos

![1678179199153](https://user-images.githubusercontent.com/44077734/223372058-0f7e3dea-389f-46dd-9f58-26da4e32d284.png)
![1678179206114](https://user-images.githubusercontent.com/44077734/223372092-15836e1b-68a8-4a2f-9342-5c42e116f608.png)

### Platform

- OS: Windows
- Browser:Chrome
- Version:    "@antv/data-set": "^0.11.4",
    "@antv/x6": "1.34.6",
    "@antv/x6-vue-shape": "1.4.0",

**Comment by yuanbolin** [comment]
目前已找到替代方案。反序列话后对所有连线用setRouter方法进行修改即可

**Comment by NewByVector** [comment]
我本地试了一下，反序列化后恢复的效果和序列化之前是一致的，都是使用 padding: 40 这个属性，能否给一个可以复现的 demo 呢？
