### ISSUE TITLE
官方示例自定react节点：x6-react-shape 导入register报错

### ISSUE THREAD

**Issue by qu-niao** [antvis/X6#3361]
### Describe the bug

![image](https://user-images.githubusercontent.com/126561001/223604605-8657f15a-7a60-4668-86ee-b46f44edbea9.png)

### Your Example Website or App

如图所示

### Steps to Reproduce the Bug or Issue

如图所示

### Expected behavior

如图所示

### Screenshots or Videos

如图所示

### Platform

x6-react-shape@1.6.4

**Comment by LolipopJ** [comment]
刚刚遇到同样的问题。研究了一下，2.x 版本的 `@antv/x6` 应当对应 2.x 版本的 `x6-react-shape`，切换到 `2.1.0` 版本后正常。

![image](https://user-images.githubusercontent.com/42314340/223676791-b8c2b9b6-34b7-4d65-aade-8b964b7c7b08.png)

由于最近发布了 1.x 版本的修复包，所以通过 `yarn add @antv/x6-react-shape` 命令安装依赖时，会默认安装最新发布的 `1.6.4`，这是不符合预期的。

**Comment by LolipopJ** [comment]
考虑到此类错误的存在，建议在官方文档中添加指定版本的安装命令。

例如在 [React 节点](https://x6.antv.antgroup.com/tutorial/intermediate/react)文档中，添加安装指南：

```bash
yarn add @antv/x6-react-shape@^2.0.0
```

**Comment by NewByVector** [comment]
已经修复latest 指向，并且在官网增加标注。
