### ISSUE TITLE
No method to identify if the graph processing is still happening or is complete?

### ISSUE THREAD

**Issue by harshaktg** [antvis/X6#3362]
### Describe the feature you'd like to request

Currently in x6 v2, since it's async by default and since all the frozen methods are removed, right now there is no way to know if the graph processing is still happening or complete.
Can we have two methods to serve this purpose?
* It'll be helpful if we have a util method to identify if the graph is still being processed
* Method to stop interactions in the graph until the first one is `false`

### Describe the solution you'd like

A method to check if the graph processing is complete or still in process
A method to freeze and unfreeze the graph interaction

### Describe alternatives you've considered

None so far.

**Comment by NewByVector** [comment]
We recommend driving view updates based on data. If you need to get the view to complete mounting, you can use these [two events](http://x6.antv.antgroup.com/tutorial/basic/events#%E8%A7%86%E5%9B%BE).
