### ISSUE TITLE
首屏：向画布同时添加父子节点，节点（自定义react节点）均不显示(V2.0)

### ISSUE THREAD

**Issue by lhC0** [antvis/X6#3365]
### Describe the bug

问题描述：
首屏：向画布添加父节点，后循环添加子节点，1.0版本正常显示，升级到版本2.0后，父子节点均不显示；
删除循环添加子节点代码，父节点显示；

偶发：
绘制出部分子节点或边，部分缺失

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

节点完全显示

### Screenshots or Videos

无

### Platform

- OS: Windows
- Browser: Chrome
- Version: v2.0

**Comment by NewByVector** [comment]
能否给一个可以复现的 demo 呢？
