### ISSUE TITLE
embedding.findParent 需要加 防抖

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3369]
### 功能描述

版本 2.x
当节点变多的时候  每次都执行 影响性能, 并且 当嵌套成功后 如果子节点 的zIndex 比父节点底 会显示在底层

### 期望解决方案

希望 embedding.findParent 可以加上防抖, 并且类似的 方法 有性能问题的都可以加上防抖, 并且 可以解决嵌套中 zIndex 比 父节点底的情况  可以处理下 改变下层级 或者其他方法

**Comment by NewByVector** [comment]
防抖可以外部来实现：

```ts
const graph = new Graph({
  embedding: {
    enabled: true,
    findParent: FunctionExt.debounce((node) => {
      return [target]
    }, 500, { leading: true }) as any,
  }
})
```

**Comment by nanfb** [comment]
> 防抖可以外部来实现：
> 
> ```ts
> const graph = new Graph({
>   embedding: {
>     enabled: true,
>     findParent: FunctionExt.debounce((node) => {
>       return [target]
>     }, 500, { leading: true }) as any,
>   }
> })
> ```

外部实现高亮总有延迟，不知道啥原因，高亮会在下一个调用中显示，不会再延迟结束显示，我看代码实现好像也没问题
[demo](https://codesandbox.io/p/sandbox/zi-ding-yi-embedding-de-padding-forked-4q7ty3?file=%2Fsrc%2FApp.tsx%3A34%2C41)
