### ISSUE TITLE
2.x 没有动态更改 画布大小的 方法

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3370]
### 功能描述

![image](https://user-images.githubusercontent.com/39638510/224255392-e8f78c29-3331-4856-8220-a5a21e56f8de.png)

我做的是一个编辑器, 需要动态更改 这个图层大小
在 1.x 中 是没问题的
在 2.x 用了 scroller 插件 然后想动态更改这个大小 试了 resizePage 不行 dragBackground 改变的不是画布大小了, 直接改 options 也不行 只能去 重新加载

### 期望解决方案

希望可以出一个动态更改 画布大小的方法

**Comment by DanielLeefu** [comment]
能提供一个codesandbox的 demo 吗

**Comment by JoeABCDEF** [comment]
> 能提供一个codesandbox的 demo 吗? 你可以尝试一下 graph.resize

@DanielLeefu   resize 改变的不是这个画布的大小
[codesandbox](https://codesandbox.io/s/mo-ban-forked-kjqoh3?file=/src/App.tsx)
![image](https://user-images.githubusercontent.com/39638510/225302741-e792e7f4-d24c-4dd7-8cf0-79273fd695fe.png)

蓝色 这个是 graph 的 container,  resize 是改这个的大小, 而我想动态改 绿色 这个 大小 也就是红色圈出来的

**Comment by xiaozisong** [comment]
解决了吗，我最后选择了定宽，以为当我打开控制台进行调试的时候，会造成绿色画布的size变小，但是关闭控制台后也没有复原...

**Comment by JoeABCDEF** [comment]
> 解决了吗，我最后选择了定宽，以为当我打开控制台进行调试的时候，会造成绿色画布的size变小，但是关闭控制台后也没有复原...

@xiaozisong  解决了
例如: 更改 高度
1. 先执行 `graph.options.height = 300`
2. 在执行 graph.getPlugin("scroller").resizePage(1920, 300)
3. 在执行 graph.scale(1,1)
---

**Comment by liaoyoujia** [comment]
@JoeABCDEF 大佬 还有其他方法吗?这样操作画布大小 不会被记录到历史记录中 撤销 还原 不起作用。
