### ISSUE TITLE
"export 'Scheduler' was not found in '@antv/x6'

### ISSUE THREAD

**Issue by xxwhca** [antvis/X6#3371]
### Describe the bug

报错信息如下：
WARNING in ../node_modules/@antv/x6-vue-shape/es/view.js 13:12-21
"export 'Scheduler' was not found in '@antv/x6'

原因：
 ../node_modules/@antv/x6-vue-shape/es/view.js文件中有如下代码：
 import { NodeView, Scheduler } from '@antv/x6'
 但@antv/x6没有Scheduler 
 
 版本号如下：
"@antv/x6": "^2.5.5",
"@antv/x6-vue-shape": "^1.5.4",

### Your Example Website or App

无，打包时就会出现

### Steps to Reproduce the Bug or Issue

安装相应版本

### Expected behavior

是否@antv/x6和@antv/x6-vue-shape版本不匹配导致的？能否提供正确可用的版本

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
x6 是 x6-vue-shape 统一使用 1.x 版本或者 2.x 版本。
