### ISSUE TITLE
2.0使用cell.removeTools没有使页面tools移除

### ISSUE THREAD

**Issue by haosusu** [antvis/X6#3372]
### 问题描述

同一个节点配置自定义点击事件和mouseenter、mouseleave事件，点击节点后再鼠标离开节点，mouseleave监听到并执行了cell.removeTools，但是tools还显示在页面上，移除节点时也会偶现这种情况

### 重现链接

https://codesandbox.io/s/dreamy-leaf-qwybho?file=/src/x6

### 重现步骤

1.同一个节点配置自定义点击事件和mouseenter、mouseleave事件
2.点击节点后再鼠标离开节点
3.mouseleave监听到并执行了cell.removeTools
4.但是tools还显示在页面上，移除节点时也会偶现这种情况

### 预期行为

希望鼠标离开节点后，执行cell.removeTools可以移除tools

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]
操作系统: Windows
网页浏览器: Google Chrome
 X6 版本: 2.5.5

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/41900402/224265900-7927ad04-953d-4553-b3bf-6f980381c80b.mp4

### 补充说明（可选）

https://codesandbox.io/s/dreamy-leaf-qwybho?file=/src/x6这个链接里有完整代码

**Comment by NewByVector** [comment]
你的例子 codesanbox 跑不起来，没有展示效果，能否提供一个可以运行的例子。
