### ISSUE TITLE
Stencil拖拽一个自定义的Vue3组件，渲染尺寸如何自定义缩放。

### ISSUE THREAD

**Issue by psrheartache** [antvis/X6#3379]
### 问题描述

基础配置：
自定义Vue3组件：200 x 200， 
Stencil中的
createNode({
    shape: 'diy',
    label: 'Vue3组件',
    width: 100,
    height: 100
  })。

场景1:
自定义组件设置定宽：200 x 200，
createNode中的width， height属性失效。

场景2:
自定义组件设置定宽： 100% x 100%，
createNode的宽高生效， 但Stencil侧画布也会按照createNode中的100 x 100渲染。

场景3:
自定义组件设置定宽： 100% x 100%，
createNode中width， height属性设置100 x 100，
使用Stencil -> groups -> layoutOptions -> resizeToFit: true
渲染结果会是Stencil画布的图例尺寸会缩小到一个舒适的规格，但拖拽后会按在缩小的尺寸渲染，不会按照设置的100 x 100 渲染。
![question](https://user-images.githubusercontent.com/13062319/224981727-fb8b9f6f-9635-425e-8aee-b0504cda9052.png)
![200](https://user-images.githubusercontent.com/13062319/224982381-df751be3-71e7-4b94-82ae-6778627c51d7.png)

### 重现链接

-

### 重现步骤

-

### 预期行为

group中的画布可以小尺寸适配渲染一个图例， 拖拽到右侧画布中按照createNode中的width x height尺寸显示或者组件本身宽高显示
![Uploading 正常.png…]()

### 平台

packages:

"@antv/x6": "^2.5.5",
"@antv/x6-plugin-stencil": "^2.0.2",
"vue": "^3.2.45",

### 补充说明（可选）

请问如何实现预期的效果？（多次调试无法实现， 文档中的参数也全都进行了尝试。）

**Comment by psrheartache** [comment]
![正常](https://user-images.githubusercontent.com/13062319/224983991-05f82669-f14a-473d-8de8-326c943c3736.png)

预期的效果。

**Comment by NewByVector** [comment]
可以参考[常见问题 3](http://x6.antv.antgroup.com/tutorial/plugins/dnd#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。

**Comment by basejs** [comment]
能否给Stencil插件增加一个缩放比例的参数，让左侧面板跟画布显示尺寸不一个尺寸？
