### ISSUE TITLE
图元初次拖入画布时无法实现自动选中

### ISSUE THREAD

**Issue by yi749027176** [antvis/X6#3382]
### Describe the bug

当前的操作是监听画布节点新增，在新增完后，重新选中节点，事件成功进入了，但是没有实现选中；

### Your Example Website or App

https://x6.antv.antgroup.com/zh/examples/showcase/practices/#flowchart

### Steps to Reproduce the Bug or Issue

1.打开官方demo:https://x6.antv.antgroup.com/zh/examples/showcase/practices/#flowchart
2.加入代码
graph.on('node:added', ({ e, cell, node, options }: any) => {
     graph.resetSelection(cell.id)
})
3.拖入图元，无法实现选中

### Expected behavior

期待可以自动选中图元，在用户需要进行属性修改时不用进行二次点击选中图元

### Platform

- Version: 
"@antv/x6": "^2.5.5",
"@antv/x6-plugin-selection": "^2.1.5",

**Comment by yi749027176** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DanielLeefu** [comment]
其实已经选中了，只是样式没展示而已

**Comment by yi749027176** [comment]
> 事件触发后，其实已经选中了，只是官网将选中的样式修改了而已 修改官网css查看
> 
> ```
> .x6-widget-selection-box {
>     opacity: 1;
>  }
> ```

选中时应该包含的x6-widget-transform样式都没有诶，样式主要还是想要transform的

**Comment by DanielLeefu** [comment]
> > 事情触发后，其已经选中了，只是官网将选中的样式修改了并且已修改官网css查询
> > ```
> > .x6-widget-selection-box {
> >     opacity: 1;
> >  }
> > ```
> 
> 选择中时应包含的x6-widget-transform样式都没有，样式主要还是想transform的

我尝试理解一下，你是想在拖入节点的时候，实现transform 选中的那种效果是吗？
如果是这样的话，目前transform并没有api 可以利用node选中，后续官网应该会透出这个方法，
目前你可以尝试一下 graph.getPlugin("transform").onNodeClick({ node: cell })，而不是使用graph.resetSelection

**Comment by yi749027176** [comment]
> > > 事情触发后，其已经选中了，只是官网将选中的样式修改了并且已修改官网css查询
> > > ```
> > > .x6-widget-selection-box {
> > >     opacity: 1;
> > >  }
> > > ```
> > 
> > 
> > 选择中时应包含的x6-widget-transform样式都没有，样式主要还是想transform的
> 
> 我尝试理解一下，你是想在拖入节点的时候，实现transform 选中的那种效果是吗？ 如果是这样的话，目前transform并没有api 可以利用node选中，后续官网应该会透出这个方法， 目前你可以尝试一下 graph.getPlugin("transform").onNodeClick({ node: cell })，而不是使用graph.resetSelection

好的，感谢！
