### ISSUE TITLE
使用@antv/x6-vue-shape注册自定义组件报错。

### ISSUE THREAD

**Issue by psrheartache** [antvis/X6#3383]
### Describe the bug

register({
  shape: 'my-box',
  width: 200,
  height: 200,
  component: BoxVue,
})

按照[官网例子](https://x6.antv.antgroup.com/tutorial/intermediate/vue)开发了一个demo，开发环境组件正常渲染，打包时@antv报错。
![err](https://user-images.githubusercontent.com/13062319/225227701-6dfa1803-250e-4d1b-beb6-e2fcdcd4a772.png)
![antv-err](https://user-images.githubusercontent.com/13062319/225228879-24290cdd-bcf9-430e-95ef-c4705c32f672.png)

@antv-92492dbc.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'reactive')
    at @antv-924

### Your Example Website or App

https://x6.antv.antgroup.com/tutorial/intermediate/vue

### Steps to Reproduce the Bug or Issue

<template>
  <div class="app-content">
    <div id="container"></div>
    <TeleportContainer />
  </div>
</template>

<script lang="ts">
  import { defineComponent } from "vue";
  import ProgressNode from "./components/ProgressNode.vue";
  import { Graph } from "@antv/x6";
  import { register, getTeleport } from "@antv/x6-vue-shape";

  register({
    shape: "custom-vue-node",
    width: 100,
    height: 100,
    component: ProgressNode,
  });
  const TeleportContainer = getTeleport();

  export default defineComponent({
    name: "App",
    components: {
      TeleportContainer,
    },
    mounted() {
      const graph = new Graph({
        container: document.getElementById("container")!,
        background: {
          color: "#F2F7FA",
        },
        autoResize: true,
      });

      graph.addNode({
        shape: "custom-vue-node",
        x: 100,
        y: 60,
      });
    },
  });
</script>

### Expected behavior

如何使打包正常

### Platform

"@antv/x6": "^2.5.5",
"@antv/x6-plugin-dnd": "^2.0.4",
"@antv/x6-plugin-minimap": "^2.0.2",
"@antv/x6-plugin-scroller": "^2.0.8",
"@antv/x6-plugin-stencil": "^2.0.2",
"@antv/x6-vue-shape": "^2.0.10",
"vue": "^3.2.45",
"vite": "^2.9.2",

**Comment by lloydzhou** [comment]
@antv/x6-vue-shape依赖 [vue-demi](https://github.com/vueuse/vue-demi)，可以检查一下这里vue-demi使用的是哪个版本。试试切换到vue3看看

![image](https://user-images.githubusercontent.com/1826685/225258426-453aeea8-6aec-414b-aef3-9dba37b2ae23.png)

**Comment by psrheartache** [comment]
> @antv/x6-vue-shape依赖 [vue-demi](https://github.com/vueuse/vue-demi)，可以检查一下这里vue-demi使用的是哪个版本。试试切换到vue3看看
> 
> ![image](https://user-images.githubusercontent.com/1826685/225258426-453aeea8-6aec-414b-aef3-9dba37b2ae23.png)

![image](https://user-images.githubusercontent.com/13062319/225542762-c2f1ad6c-e43d-401e-9556-45f51f0365ce.png)
这是我看的x6-vue-shape /src中teleport的代码，
不知道是不是这里影响的。

我使用了npx vue-demi-switch 3 vue3 ， npx vue-demi-fix 无法解决这个问题。  能否告知下详细的操作步骤， 感谢。

**Comment by lloydzhou** [comment]
1. 你运行vue-demi-xxx命令的时候，可以进入node_modules/@antv/x6-vue-shape文件夹运行试试。
2. 看看node_modules/@antv/x6-vue-shape/node_modules下面是不是也有一个vue文件夹，这个vue的版本可能和node_modules/vue是不一样的。你可以把内层的那个vue的目录删掉试试。

**Comment by psrheartache** [comment]
> 

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/13062319/225792886-2becd65a-04d3-489a-8215-89f33a57f6b9.png">
1. 未在node_modules/@antv/x6-vue-shape/node_modules中并无/vue目录。

![image](https://user-images.githubusercontent.com/13062319/225794333-8c49448a-5eda-4e5d-8fd2-32895f015337.png)
2. vue-demi中显示v as Vue已经废弃，本地 "typescript": "4.5.4"，"vue-tsc": "0.29.8"。

![image](https://user-images.githubusercontent.com/13062319/225796622-283b096e-418b-448a-9e2b-bfdf2c1ab24f.png)
3.在x6-vue-shape中yarn后，项目打包报错如上。

**Comment by lloydzhou** [comment]
方便弄一个最小的复现的demo，发到github吗？想要搞一样的环境复现一下。

**Comment by psrheartache** [comment]
> 方便弄一个最小的复现的demo，发到github吗？想要搞一样的环境复现一下。

ok， 我需要把项目文件全部剔除掉。稍后我去我自己的仓库创建个项目，上传完后我会贴出demo地址。

**Comment by psrheartache** [comment]
> 方便弄一个最小的复现的demo，发到github吗？想要搞一样的环境复现一下。

[一个用来复现Antv X6 Vue3自定义组件渲染报错的MVP DEMO](https://github.com/psrheartache/test-x6-vue-shape-build-error-mvp-demo)
人麻了，我把代码抽离出来写了个纯净的demo的，打包本地node-server跑了一下， 没有报错。  但在公司的工程文件下面还是打包报错， 我把node_modules都清除了，重新安装存在问题。  初步怀疑是否是异步路由加载导致， 前辈可否方便私信一个邮箱，远程跟踪下我的这个问题， 我自己也先动手排查下。  感恩🥹～

**Comment by psrheartache** [comment]
> 方便弄一个最小的复现的demo，发到github吗？想要搞一样的环境复现一下。

前辈能否留个邮箱地址？

**Comment by lloydzhou** [comment]
我给你github主页留的邮箱发了一封邮件，估计你没收到
 lloydzhou@qq.com

**Comment by psrheartache** [comment]
> 我给你github主页留的邮箱发了一封邮件，估计你没收到 [lloydzhou@qq.com](mailto:lloydzhou@qq.com)

已回复邮件，感谢。

**Comment by lloydzhou** [comment]
@suqinye 打包部署报错，用这个链接搜索一下  https://github.com/search?q=repo%3Aantvis%2FX6+vue+%E6%89%93%E5%8C%85&type=issues&p=1
