### ISSUE TITLE
非 scroller 模式下支持画布拖拽

### ISSUE THREAD

**Issue by bubkoo** [antvis/X6#339]
目前画布只能在开启 scroller 后才支持画布滚动和拖拽，而部分用户需要在常规画布下也能拖拽画布 或者 不太习惯 scroller 自带的浏览器原生滚动条。

可能的方式是通过下面选项来兼容
```ts
new Graph(
  scroller: {
    enabled: false,  // 不开启 scroller
    pannable: true, // 支持画布拖拽
  },
)
```

看起来有点奇怪，因为 `pannable` 毕竟是 `scroller` 下面的一个选项。

是否有其他方案，欢迎讨论。

**Comment by NewByVector** [comment]
const graph = new Graph({
      interacting: {
        graphMoveable: true,
      }
    })
画布拖动属于画布的交互，可以作为interacting的一个属性来配置，原因有两个
1. 配置更加符合用户直觉
2. 实现起来应该比去模拟scroller更简单一些

**Comment by bubkoo** [comment]
与其他交互配置保持一致，提供一个  `panning` 配置项

```ts
 export interface PanningOptions {
    enabled?: boolean
    modifiers?: string | ModifierKey[] | null
  }
```

例如：
```ts
const graph = new Graph({
  panning: {
      enabled: true,
  }
})
```

或者 
```ts
const graph = new Graph({
  panning: true,
})
```

**Comment by theBestNotes** [comment]
panning能否用鼠标右键长按。 鼠标左键用来selection。

**Comment by NewByVector** [comment]
@theBestNotes  支持 `modifiers` 设置快捷键，只有按下快捷键的同时拖动鼠标，才能拖动画布。
