### ISSUE TITLE
有没有框选结束的事件

### ISSUE THREAD

**Issue by TalentJY** [antvis/X6#3394]
### 问题描述

我想要在框选结束后触发事件。
目前找到一个node:selected，但是框选多个节点时，这个监听事件会被多次触发，但我只想触发一次

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2 ... ]

**Comment by TalentJY** [comment]
> 这个触发多次是正常的，你的具体场景是啥呀？

我想框选完以后，获取当前被选中的节点，然后对整体选中的节点进行操作，但是写到node:select里，再调用getselectionCells，就会对同一个节点操作很多次。

**Comment by TalentJY** [comment]
> 这个触发多次是正常的，你的具体场景是啥呀？

我需要获取框选的位置，并在框选位置显示工具栏

**Comment by DanielLeefu** [comment]
目前并没有提供一个框选结束的事件
你或者可以尝试通过监听`selection:changed` 结合鼠标抬起事件来进行处理

**Comment by NewByVector** [comment]
@TalentJY 框选配置 [content](content) 是否能解决你问题呢？

**Comment by Hideer** [comment]
这些事件文档哪里有明细文档  比如`node:selected`
