### ISSUE TITLE
多个path自定义组件设置refD后显示错误

### ISSUE THREAD

**Issue by hanyuesoyeon** [antvis/X6#3398]
### Describe the bug

![image](https://user-images.githubusercontent.com/31118061/225962086-c16d520e-57a5-4d4c-8fb3-375401804a0c.png)
代码：markup:[
                {
                    tagName: 'path',
                    selector: 'body'
                },
                {
                    tagName: 'path',
                    selector: 'inner'
                }
            ],
            attrs: {
                body:{
                    refD:"M 1 5 C 16 1 46 1  58 5 L 58 34 C 43 38 16 38  1 34 Z",
                    stroke:"#A2B1C3"
                },
                
                inner:{
                    refD:"M 1 5 C 16 9 46 9  58 5",
                    stroke:"#A2B1C3",
                }
            }
            当我设置inner的refD属性则显示错误，当我设置inner的d属性，则显示正确

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

暂无

### Expected behavior

期待
![image](https://user-images.githubusercontent.com/31118061/225962856-01a02c10-70b8-4625-a4d7-553956b4898e.png)

设置redD是错误的
![image](https://user-images.githubusercontent.com/31118061/225962946-159d8403-689c-45a5-91b0-58e5e36d53e4.png)

### Screenshots or Videos

暂无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

暂无

**Comment by NewByVector** [comment]
参考 refD 的[定义](http://x6.antv.antgroup.com/api/registry/attr#refdresetoffset)，实际显示 path 的时候，会将 pathData 按照参照物进行平移和缩放，所以图形会变形。

**Comment by NewByVector** [comment]
@hanyuesoyeon 需要设置相对 path。
