### ISSUE TITLE
项目 直接挂掉，我已经准备 明天 去财务处领钱了💰

### ISSUE THREAD

**Issue by 0jinxing** [antvis/X6#3402]
### Describe the bug

![截屏2023-03-19 下午3 11 09](https://user-images.githubusercontent.com/32119282/226159934-09602c98-4a42-4d8f-877b-9dc376686ab1.png)

https://github.com/antvis/X6/blob/913897891850aafb6b6d329e9cd3994c4ed764fd/packages/x6/src/graph/virtual-render.ts#L6

### Your Example Website or App

https://github.com/antvis/X6/blob/913897891850aafb6b6d329e9cd3994c4ed764fd/packages/x6/src/graph/virtual-render.ts#L6

### Steps to Reproduce the Bug or Issue

https://github.com/antvis/X6/blob/913897891850aafb6b6d329e9cd3994c4ed764fd/packages/x6/src/graph/virtual-render.ts#L6

### Expected behavior

Property 'throttle' does not exist on type 'typeof import("/Users/lin/Desktop/X6/packages/x6-common/lib/function/main")'.ts(2339)

### Screenshots or Videos

https://github.com/antvis/X6/blob/913897891850aafb6b6d329e9cd3994c4ed764fd/packages/x6/src/graph/virtual-render.ts#L6

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

https://github.com/antvis/X6/blob/913897891850aafb6b6d329e9cd3994c4ed764fd/packages/x6/src/graph/virtual-render.ts#L6

**Comment by 0jinxing** [comment]
🤔 为啥 还能 publish 上去

**Comment by 0jinxing** [comment]
x6 v2.5.5

**Comment by NewByVector** [comment]
删除 node_modules，重新安装依赖。配套的 x6-common 需要升级。

**Comment by 0jinxing** [comment]
非常难过

**Comment by 0jinxing** [comment]
![截屏2023-03-19 下午3 23 06](https://user-images.githubusercontent.com/32119282/226160318-7c322409-c09c-422e-b358-dd358ce85019.png)

**Comment by 0jinxing** [comment]
这个依赖 是不是 有点不太稳重了

**Comment by 0jinxing** [comment]
如果 我没删除 node_modules 升级 就有问题，
是不是 这个 package.json 依赖有问题
ci 流程 每次构建都需要 重新 删除 node_modules 吗 😭
要不紧急修复一般
@NewByVector

**Comment by NewByVector** [comment]
@0jinxing 正常情况下 ci 每次回重新安装依赖的。

**Comment by 0jinxing** [comment]
... 我怕运维老哥喷我

**Comment by 0jinxing** [comment]
这个 package.json 声明的就有问题吧

**Comment by 0jinxing** [comment]
不说了，我准备去公司收拾东西了 [可怜唧唧]

**Comment by NewByVector** [comment]
我暂时发一个版本，想想后续这种怎么处理。

**Comment by 0jinxing** [comment]
https://github.com/antvis/X6/pull/3404 这里 🐶

**Comment by 0jinxing** [comment]
@NewByVector

**Comment by NewByVector** [comment]
已经发布新版本，x6@2.5.6。
