### ISSUE TITLE
node-editor setText 双击编辑，编辑框位置不对。

### ISSUE THREAD

**Issue by TalentJY** [antvis/X6#3408]
### 问题描述

我定义了一个节点有image和text，text偏移到image下方。双击节点时编辑时，编辑框会显示在图片正中心，而不是text的位置。
编辑框似乎没有找到偏移的方法。

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2 ]

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/82206115/226926551-bcf16bc8-c3f2-46b6-b697-b42dfe03c74d.mp4

_No response_

**Comment by NewByVector** [comment]
升级到 2.8.x 版本后，增加了 x 和 y 配置，具体参考[文档](http://x6.antv.antgroup.com/api/registry/node-tool)。
