### ISSUE TITLE
Cannot read properties of undefined (reading 'ToolItem')     at

### ISSUE THREAD

**Issue by wzy2775** [antvis/X6#3409]
### 问题描述

"@antv/x6": "^2.5.6",
"@antv/x6-plugin-dnd": "^2.0.4",
"@antv/x6-vue-shape": "^2.0.10",
安装完x6-plugin-dnd或者x6-vue-shape，都会报错Cannot read properties of undefined (reading 'ToolItem')     at
vue3+quasar的项目中使用

### 重现链接

本地

### 重现步骤

安装完直接报错

### 预期行为

不报错

### 平台

windows

**Comment by oyal** [comment]
看一下这个 https://github.com/vitejs/vite/issues/3413#issuecomment-1180169375
