### ISSUE TITLE
自定义vue节点，如何区分Stencil和画布里的节点

### ISSUE THREAD

**Issue by qq1170623178** [antvis/X6#3411]
### 问题描述

自定义vue节点，添加右键菜单的功能，期望效果是：只有在画布里的节点有这个功能，而Stencil里的节点没有这个功能。
但是无论是Stencil还是画布都出现了这个功能

### 重现链接
自定义节点代码
![image](https://user-images.githubusercontent.com/43264733/226792535-2ab63e69-5726-4f71-a96f-4927a5013783.png)

![image](https://user-images.githubusercontent.com/43264733/226792566-a3137ae2-adfe-44c8-8880-a3ef730ed901.png)

### 重现步骤

无

### 预期行为

只有在画布里的节点有右键菜单，而Stencil里的节点没有右键功能。

### 平台

所有

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/43264733/226790405-001e46e5-8a70-4625-9cb9-ecc8c118fdac.png)

**Comment by qq1170623178** [comment]
自定义节点如下：
<template>
  <div class="node" @contextmenu.prevent="onContextmenu" content="I'm the default tooltip!" @mouseenter="mouseenter" @mouseleave="mouseleave">
    {{ data.label }}
    <div>
      <svg-icon :icon-class="iconArr[data.data.index]" class="b-icon"></svg-icon>
    </div>
  </div>
</template>

<script>

export default {
  name: 'VueNode',
  inject: ['getNode','getGraph'],
  data() {
    return {
      data: {},
      iconArr: [
        "linux",
        "windows",
        "AIX",
        "hp-ux",
        "freeBSD",
        "lyq",
        "fhq",
        "wxsb",
        "aqsb",
      ]
    }
  },
  created() {
    console.log(this.getNode(), 'vvvv')
    this.data = this.getNode().store.data
  },
  methods: {
    mouseenter() {
      const node = this.getNode()
      console.log(node)
    console.log(this.getGraph(), 'graph')

      const ports = node.getPorts() || []
      ports.forEach((port) => {
        node.setPortProp(port.id, 'attrs/circle/style', {
          visibility: 'visible',
        })
      })
    },
    mouseleave(){
      const node = this.getNode()
      const ports = node.getPorts() || []
      ports.forEach((port) => {
        node.setPortProp(port.id, 'attrs/circle/style', {
          visibility: 'hidden',
        })
      })
    },
    onContextmenu(event) {
      this.$contextmenu({
        items: [
          {
            label: "返回(B)",
            onClick: () => {
              this.message = "返回(B)";
              console.log("返回(B)");
            }
          },
          { label: "删除节点", disabled: true },
          { label: "查看详情", divided: true, icon: "el-icon-refresh" },
          { label: "跳转至..." },
          { label: "打印(P)...", icon: "el-icon-printer" },
          { label: "投射(C)...", divided: true },
          {
            label: "使用网页翻译(T)",
            divided: true,
            minWidth: 0,
            children: [{ label: "翻译成简体中文" }, { label: "翻译成繁体中文" }]
          },
          {
            label: "截取网页(R)",
            minWidth: 0,
            children: [
              {
                label: "截取可视化区域",
                onClick: () => {
                  this.message = "截取可视化区域";
                  console.log("截取可视化区域");
                }
              },
              { label: "截取全屏" }
            ]
          },
          { label: "查看网页源代码(V)", icon: "el-icon-view" },
          { label: "检查(N)" }
        ],
        event,
        //x: event.clientX,
        //y: event.clientY,
        customClass: "custom-class",
        zIndex: 3,
        minWidth: 230
      });
      return false;
    }
  },
  components: {

  }
}
</script>

**Comment by NewByVector** [comment]
vue 组件内部可以获取到 graph 实例（通过 getGraph provider），判断 graph 实例和主画布的 graph 实例是否相等，就可以判断了。

**Comment by songhuijin** [comment]
可以在Stencil里的节点加一个data属性代表是Stencil节点，在右键事件判断一下里面的值是否为Stencil，进行添加右击菜单
