### ISSUE TITLE
resetCells的时候报错

### ISSUE THREAD

**Issue by KidGrow** [antvis/X6#3419]
### 问题描述

https://user-images.githubusercontent.com/80673172/227134263-25beeb01-15d9-4488-a2ff-e7bbc174ee53.png

### 重现链接

无

### 重现步骤

进入页面渲染就报错了

### 预期行为

我期望能正常reset但是报错了

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.0.0 ... ]

### 屏幕截图或视频（可选）

<img width="781" alt="image" src="https://user-images.githubusercontent.com/80673172/227134263-25beeb01-15d9-4488-a2ff-e7bbc174ee53.png">

**Comment by KidGrow** [comment]
@NewByVector

**Comment by NewByVector** [comment]
升级一下 @antv/x6, 之前解决了这个问题。
