### ISSUE TITLE
使用resetCells时报错

### ISSUE THREAD

**Issue by wojiushiqiji** [antvis/X6#3423]
### 问题描述

在使用resetCells时发生了报错，
Unhandled exception rendering component: t.on is not a function
TypeError: t.on is not a function

X6版本是2.5.1

### 重现链接

![image](https://user-images.githubusercontent.com/46197995/227163708-aeb0b547-1ea4-43fd-9eac-dd49c09ccc95.png)

### 重现步骤

在使用resetCells时发生了报错，

### 预期行为

希望得到解决

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.5.1 ... ]

### 屏幕截图或视频（可选）

![1679564164838](https://user-images.githubusercontent.com/46197995/227162485-df054dab-fb1a-4f12-841f-0bbd65e284b5.png)

![image](https://user-images.githubusercontent.com/46197995/227163708-aeb0b547-1ea4-43fd-9eac-dd49c09ccc95.png)

![image](https://user-images.githubusercontent.com/46197995/227163010-c1b111b9-b0c9-40bf-ac87-896cfcd03961.png)

**Comment by NewByVector** [comment]
因为没有可以复现的 demo，这个 issue 先关闭了，如果能提供可以复现的 demo，请 reopen 该 issue。
