### ISSUE TITLE
minimap中的小地图视口错位

### ISSUE THREAD

**Issue by 565823371556Zsl** [antvis/X6#3434]
### Describe the bug

在vue3中使用minimap，为什么小地图的视口显示不正确
![image](https://user-images.githubusercontent.com/119397527/227848149-1ad72a4c-d115-4411-962b-dbd6f00feb8d.png)

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

暂无

### Expected behavior

预期的结果是文档演示中minimap的示例一样，小地图视口有个固定尺寸

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/119397527/227848450-ecaf750d-3700-4d0e-90c1-1b9cc427c1b6.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
windows11 chrome

**Comment by NewByVector** [comment]
能否提供一下 X6 的版本，最好有一个可以复现的 demo。

**Comment by dongongfeiyu** [comment]
遇到了同样问题？请问解决了吗
