### ISSUE TITLE
Will you probably provide a mindmap editor app example?

### ISSUE THREAD

**Issue by Kaijun** [antvis/X6#344]
### Expected Behavior
Mindmap editor is also a significant scenario, will you probably provide a mindmap editor app example?

### Possible Solution
N/A

### Additional Context
N/A

**Comment by NewByVector** [comment]
Developing MindMap with X6 is a good idea, we will develop a plan to support

**Comment by NewByVector** [comment]
https://github.com/antvis/X6/blob/master/examples/x6-example-features/src/pages/connector/xmind-curve.tsx
