### ISSUE TITLE
vue3+vite+x6-vue-shape 自定义vue节点中registerNode和registerVueComponent不生效

### ISSUE THREAD

**Issue by deji2012** [antvis/X6#3442]
### 问题描述

我在Vue3下引入antv-x6-vue，
场景1. 使用Graph.registerVueComponent()方法报错Graph.registerVueComponent is not a function
`Graph.registerVueComponent(
    "count",
    {
      render: () => {
        return h(Count);
      },
    },
    true
  );`
![image](https://user-images.githubusercontent.com/61216726/228491889-b3244f67-0d6a-4add-b022-14994613bb26.png)

场景2. 使用Graph.registerNode()方法报错Uncaught TypeError: Cannot destructure property 'component' of 'shapeMaps[node.shape]' as it is undefined
`Graph.registerNode(
    "count",
    {
      inherit: "vue-shape",
      x: 200,
      y: 150,
      width: 150,
      height: 100,
      component: {
        render: () => {
          return h(Count);
        },
      },
    },
    true
  );`
![image](https://user-images.githubusercontent.com/61216726/228498949-354a55d3-a1ec-4728-ba93-1718c36bd391.png)
![image](https://user-images.githubusercontent.com/61216726/228499503-59bb1804-079e-44b9-b897-3e9648091886.png)
![image](https://user-images.githubusercontent.com/61216726/228499570-e24a5a2f-58a9-48c5-8461-940ae6597857.png)

[个人认为场景1导致未注册节点，场景2则是注册节点未生效，代码都是按](https://antv-x6.gitee.io/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93-vue-%E8%8A%82%E7%82%B9)来写的

全部js代码：
`onMounted(() => {
  const container = document.getElementById("container");
  graph = new Graph({
    container: container,
    grid: true,
    width: 600,
    height: 400,
  });
  Graph.registerNode(
    "count",
    {
      inherit: "vue-shape",
      x: 200,
      y: 150,
      width: 150,
      height: 100,
      component: {
        render: () => {
          return h(Count);
        },
      },
    },
    true
  );
  graph.addNode({
    id: "1",
    shape: "count",
    x: 400,
    y: 150,
    width: 150,
    height: 100,
    data: {
      num: 0,
    },
  });
})`

### 重现链接

暂无

### 重现步骤

1.进入页面
2.加载出画布
3.报错

### 预期行为

期望渲染自定义节点成功，但实际上页面是空有一个画布
![image](https://user-images.githubusercontent.com/61216726/228502343-93d07353-1666-4bae-ae81-52ee3c8982c8.png)

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [EdgeGoogle Chrome]
- X6 版本: [2.8.0]
- X6-vue-shape 版本: [2.0.10]
- vite 版本: [3.2.3]
- vue 版本: [3.2.45]

**Comment by deji2012** [comment]
http://x6.antv.antgroup.com/tutorial/intermediate/vue文档在这。没找到2版本的文档之前

**Comment by HaiT-a** [comment]
怎么关闭了，请问解决了吗？我也遇到这样的情况

**Comment by deji2012** [comment]
> 怎么关闭了，请问解决了吗？我也遇到这样的情况

我用的2版本的x6，解决方案是安装最新的x6-vue-shape版本，然后按照2版本的文档去写就行了，从x6-vue-shape里面引入俩方法去注册，我之前看的文档是1版本的，不适用，想用1版本的得用vue2，并把版本降到1版本才能用，[这是文档链接](http://x6.antv.antgroup.com/tutorial/intermediate/vue)
