### ISSUE TITLE
在移动端模式下，点击连线中的label会报错

### ISSUE THREAD

**Issue by autumnshine** [antvis/X6#3445]
### Describe the bug

在移动端模式下，点击连线中的label会报错

### Your Example Website or App

http://x6.antv.antgroup.com/examples/edge/label#render-with-html 使用官方例子，浏览器切换到移动端模式后，点击边上的label就会复现

### Steps to Reproduce the Bug or Issue

在移动端模式下，点击连线中的label会报错

### Expected behavior

在移动端模式下，点击连线中的label不报错

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/28615195/228718390-24b8b0ac-174f-48fe-af0b-ca3b6a371198.png)
![image](https://user-images.githubusercontent.com/28615195/228718581-8db923c2-0b5d-48ec-b032-c81825494a09.png)

### Platform

- OS: Windows
- Browser: Edge
- Version:  2.5.7

**Comment by autumnshine** [comment]
http://x6.antv.antgroup.com/examples/edge/label#render-with-html 使用官方例子，浏览器切换到移动端模式后，点击边上的label就会复现

**Comment by NewByVector** [comment]
最新版本已经修复该问题。
