### ISSUE TITLE
X6源码报错，源码存在问题，希望修改重新发包

### ISSUE THREAD

**Issue by wangxiang666** [antvis/X6#3454]
### 问题描述

![image](https://user-images.githubusercontent.com/52997798/229088738-3303d58b-ac6e-46a5-a852-f86b4d75b7fc.png)
processEmbedding方法中这里犯了很常见的错误：['1','2','3'].map(parseInt) !==[1,2,3]
这里导致embedding: { frontOnly: true}有时会报错，影响我的程序

### 重现链接

无

### 重现步骤

无

### 预期行为

希望能改正发个版本

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.9.1 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/52997798/229089965-76322f8b-49cd-40ec-be62-954f7b5c9700.png)

**Comment by NewByVector** [comment]
首先对给你造成困扰道歉，请更新到 @antv/x6@2.9.3 版本。
