### ISSUE TITLE
源码processEmbedding 方法仍有问题，可能是由于zIndex自动生成的方式有问题

### ISSUE THREAD

**Issue by wangxiang666** [antvis/X6#3458]
### 问题描述

https://github.com/antvis/X6/issues/3454#issue-1649069786
仍然是这个方法报错，不清楚zIndex自动生成的方法怎样的，但是可以确定有时会生成16位以上的字符串（详情见截图），这种情况下parseInt转数字会失真，导致candidates为undefined，希望可以彻底修改，非常感谢

### 重现链接

无

### 重现步骤

无

### 预期行为

希望可以正常运行不报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.9.3 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/52997798/229278752-e10befe0-e6fd-42e2-aaf4-678694df1eec.png)

**Comment by NewByVector** [comment]
能否发下你截图上面 zIndexMap 的值呢？理论上不应该出现这样的 zIndex。

**Comment by wangxiang666** [comment]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/52997798/229399184-557e2f32-9acf-46f5-abca-6c2da3da9ac9.png">
我觉得是zIndex +1是某个地方基于字符串计算了，因为我看有时候是9后面一堆1

**Comment by wangxiang666** [comment]
> 能否发下你截图上面 zIndexMap 的值呢？理论上不应该出现这样的 zIndex。

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/52997798/229399343-090517d1-c159-4214-81e4-0a4e39a1c495.png">
我觉得是zIndex +1是某个地方基于字符串计算了，因为我看有时候是9后面一堆1

**Comment by NewByVector** [comment]
能否发一下你的画布数据呢?  可以通过打印 `graph.toJSON()` 获取。 我排查了很久，没有发现出现字符串和数字混用的情况。

**Comment by wangxiang666** [comment]
> 能否发一下你的画布数据呢? 可以通过打印 `graph.toJSON()` 获取。 我排查了很久，没有发现出现字符串和数字混用的情况。

[数据.txt](https://github.com/antvis/X6/files/11136293/default.txt)
原来的数据没了，这里有一份类似的比较复杂
![image](https://user-images.githubusercontent.com/52997798/229454348-7a2a4f62-6466-4940-9ec0-53891ce8565a.png)
最后一条

**Comment by NewByVector** [comment]
你好，最近投入到一些其他事情中了，我们继续看这个问题，我猜测是你们在某些地方给节点的 zIndex 设置为字符串类型数据，能否先检查一下呢？

**Comment by wangxiang666** [comment]
> 你好，最近投入到一些其他事情中了，我们继续看这个问题，我猜测是你们在某些地方给节点的 zIndex 设置为字符串类型数据，能否先检查一下呢？

在提交issue前我就已经全部排查过我们这边的代码了
![image](https://user-images.githubusercontent.com/52997798/230260845-9683a3b8-1730-4a93-b15a-3fd05e287870.png)
![image](https://user-images.githubusercontent.com/52997798/230261023-546afca2-03a9-49c4-b418-7924e32a68f3.png)

仅这两个地方对节点zIndex进行过操作，均是调用的官网api，我再找一下必现步骤

**Comment by NewByVector** [comment]
因为无法复现该问题，先关闭 issue，如果后续有复现的 demo，请重新 reopen。
