### ISSUE TITLE
embed嵌入功能是否缺乏结果校验

### ISSUE THREAD

**Issue by wangxiang666** [antvis/X6#3467]
### 问题描述

embed功能缺乏校验，通过随机手动嵌入，较小概率出现了以下截图数据
![image](https://user-images.githubusercontent.com/52997798/229668025-21177d65-6cdb-42c1-bd31-e20c472c45ae.png)
节点的父子节点是同一个节点，然后结果就是浏览器奔溃，是不是应该在嵌入完成添加属性前进行一下校验，这个现象几率较小，但是问题很严重，希望官方大佬能解决或者给个规避思路

### 重现链接

无

### 重现步骤

随机事件，暂未找到必现条件

### 预期行为

浏览器不崩

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.9.3 ]

**Comment by wangxiang666** [comment]
[data.txt](https://github.com/antvis/X6/files/11143986/data.txt)
这是完整的数据，我去掉了样式和一些无用属性

**Comment by NewByVector** [comment]
请问一下你的 `embedding` 配置是怎么样的？

**Comment by NewByVector** [comment]
因为没有可以复现的 demo，无法定位到具体问题，先关闭这个 issue，如果后续可以复现，可以重新提一个新的 issue。针对于你的这个问题，推荐在 validate 中先做一层校验。
