### ISSUE TITLE
optimize the bundle size

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#347]
### Expected Behavior

size: 795K  --->   ?

**Comment by bubkoo** [comment]
先列举哪些可优化，再来看看优化方法
@NewByVector

**Comment by NewByVector** [comment]
![image](https://user-images.githubusercontent.com/20186737/107049339-eec55600-6804-11eb-89f0-c09e81c16456.png)
上面是不压缩条件下 umd 打包大小分析，可优化点在：
1. JQuery (V2 去掉)
2. lodash (lodash现在已经是按需的了，但是 tree shaking 程度还是不够)

**Comment by NewByVector** [comment]
尝试使用 babel-plugin-lodash 做更细粒度的按需，只能在原来基础上减少2K。后面想这些方法自己去实现了。
