### ISSUE TITLE
在2.9.1版本之后 render/scheduler.ts 中的createViewHook附近有一段代码存在问题

### ISSUE THREAD

**Issue by windivi** [antvis/X6#3472]
### Describe the bug

在2.9.1版本之后 render/scheduler.ts 中的createViewHook附近有一段代码存在问题
```
# render/scheduler.ts

if(ret) return new ret(...)
```
在chrome浏览器中控制台报错提示`ret is not a constructor`

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

捕获右键菜单后渲染自定义的vue jsx使用antd的menu组件,然后报错

### Expected behavior

希望得到修复，可以正确更新至2.9.1之后的版本

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
win10 chrome 108.0.5359.125

### Additional context

无

**Comment by windivi** [comment]
> 在 2.9.2 版本之后，createCellView 配置类型发生了变化，不需要传入具体的 view 实例，而是传入 view class。这个对于使用者来说降低了复杂度。不过这个是一个 break change，对你造成的困扰感到十分抱歉。具体的使用方式参考 [demo](http://x6.antv.antgroup.com/tutorial/plugins/minimap#%E6%BC%94%E7%A4%BA)。

按照demo的修改后，出现之前没有出现的俩个新问题
1.在个别实体元素删除后，vue的runtimecompiler报错找不到nextSibling。

**Comment by NewByVector** [comment]
收到你的问题，请先把版本锁定在 2.9.1，我们继续排查一下新的问题。

**Comment by NewByVector** [comment]
@windivi 我尝试复现你的问题，并没有发现问题，能否提供一个可以复现的 demo 呢？

**Comment by windivi** [comment]
由于当时的代码情况没有留存，在开发一段时间后，我这次尝试升级至最新版后，已经无法复现该问题了。
