### ISSUE TITLE
使用manhattan 算法 报警告 Unable to execute manhattan algorithm, use orth instead

### ISSUE THREAD

**Issue by forever0714yuan** [antvis/X6#3473]
### 问题描述

连线之后，移动节点，就会触发警告，请问怎么解决呢？padding也没有很大，就是默认的。如果有空，可以解答一下疑惑吗？

### 重现链接

https://codesandbox.io/s/serene-cori-og3ont?file=/index.ts

### 重现步骤

1.将两个节点连线
2.拖动节点，查看控制台，会出现警告

### 预期行为

不应该出现警告

### 平台

- 操作系统: [Windows11]
- 网页浏览器: [Google Chrome 111.0.5563.147]
- X6 版本: [2.8.0 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/60290893/230077913-d9324ca3-c3e1-4241-948a-c125f5cfb8b4.png)

**Comment by forever0714yuan** [comment]
那请问有办法让这个警告忽略或者其他之类的办法吗？

**Comment by NewByVector** [comment]
可以忽略其实和终止节点，使用 [excludeTerminals](http://x6.antv.antgroup.com/api/registry/router#manhattan) 配置。

**Comment by forever0714yuan** [comment]
好的，谢谢解答，麻烦了
