### ISSUE TITLE
2.x删除了render:done事件，能否加上

### ISSUE THREAD

**Issue by songhuijin** [antvis/X6#3474]
### 功能描述

现在有个需求，节点间的跳转，点击节点跳转到**另一个页面**的节点，在所有节点异步加载完成之后，对画布进行居中，并且定位到这个节点的位置（监听所有节点渲染完成后，对页面进行其他操作，没有这个事件，导致无法知道相关节点有没有渲染完成，view:mounted不满足此需求）

### 期望解决方案

希望加上render:done事件或者有其他处理方法

**Comment by NewByVector** [comment]
首先感谢你的提问，有两个点先申明一下：
1. 对画布的居中、定位等操作不需要等节点渲染完成，X6 内部已经做了处理。
2. 大部分场景可以直接通过操作数据层来实现，而不是等渲染完成后操作 dom，必要时使用 `view:mounted` 事件拿到节点完成渲染的时机。

从你的描述中，并没有看到现在无法实现的问题，请明确一下。

**Comment by songhuijin** [comment]
好的谢谢，已经解决了，用的view:mounted监听拿到所需要的数据进行对比，之前因为数据量特别大，考虑到太多的监听是否影响性能
