### ISSUE TITLE
网格布局preventOverlap不生效

### ISSUE THREAD

**Issue by webgitguo** [antvis/X6#3475]
### 问题描述

配置了preventOverlap，但是初始化节点依旧重叠

### 重现链接

https://codesandbox.io/s/naughty-wind-z69qp2

### 重现步骤

     官网demo:https://codesandbox.io/s/naughty-wind-z69qp2, 进入页面初始化

### 预期行为

节点不重叠

### 平台

- 操作系统:  Windows,
- 网页浏览器: Google Chrome
- X6 版本: [2.9.4  ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/59195633/230288562-06b53a55-1e0e-4cd3-a89b-36437ae86982.png)

**Comment by NewByVector** [comment]
发生重叠现象是因为你的布局配置中设置了:
```ts
{
  width: 480,
  height: 260,
}
```
已经无法不重叠而且放下所有内容。
