### ISSUE TITLE
数据更新后 如何重新生成图表 

### ISSUE THREAD

**Issue by 542473232** [antvis/X6#3476]
### 问题描述

我在vue中使用了一个筛选按钮，来控制泳道图的数据更新，怎么在数据更新后 使图表重新刷新呢

### 重现链接

暂无

### 重现步骤

vue组件中 有一个筛选按钮 控制数据过滤
点击按钮异步请求数据后 将原来的图表更新

### 预期行为

希望在点击过滤数据按钮后 使用过滤后的数据 生成图表

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
请问筛选后节点、边数量是否有变化，如果有变化的话，建议使用筛选后的数据重新渲染画布，可以使用下面的 API：
- graph.fromJSON()
- graph.resetCell()
如果考虑到渲染性能，可以业务层做一层数据的 diff，然后增量渲染。可以使用下面的 API：
- grpah.addNode()
- graph.addEdge()
- graph.removeNode()
- graph.removeEdge()
