### ISSUE TITLE
2.x官网示例“文本编辑” 双击节点无法编辑

### ISSUE THREAD

**Issue by Aolcycle** [antvis/X6#3479]
### 问题描述

打开官网的“文本编辑”示例，双击节点或线条无法编辑文本，双击之后是有一瞬间有编辑框，然后就消失了。

### 重现链接

http://x6.antv.antgroup.com/examples/node/tool#editable
https://codesandbox.io/s/z9xj4k

### 重现步骤

1.进入官网示例页面
2.双击节点
3.编辑文本

### 预期行为

我的预期是点击之后编辑文本，完成后保存

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome\edge
- X6 版本: 2.x

### 屏幕截图或视频（可选）

[Uploading Video_2023-04-08_111238.wmv…]()

### 补充说明（可选）

https://user-images.githubusercontent.com/65211558/230700880-28b8d4b0-1324-4230-9a02-764c258d0a74.mp4

**Comment by NewByVector** [comment]
已经修复。

**Comment by wh356667852** [comment]
我也遇到了这个问题，请问是怎么解决的呢？

**Comment by zoey0423** [comment]
我把addtools加到自己的代码里后，还是有这个问题
