### ISSUE TITLE
how to change imageUrl of a Shape.Image node

### ISSUE THREAD

**Issue by zz112** [antvis/X6#3483]
### Describe the bug

我想用prop()动态改变内置Image节点的imageUrl属性，但是好像没生效

### Your Example Website or App

https://codesandbox.io/s/competent-orla-gj144k?file=/index.ts

### Steps to Reproduce the Bug or Issue

1. add an Image node to the graph
2. change imageUrl by using prop('imageUrl', 'xxxxx')

### Expected behavior

i want to know how to change imageUrl

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [112.0.5615.49]

**Comment by Tabris7777** [comment]
node.prop(
  "imageUrl",
  "https://mdn.alipayobjects.com/huamei_f4t1bn/afts/img/A*A1g0RaZ-GJcAAAAAAAAAAAAADtOHAQ/original"
);
改成
node.attr('image/xlink:href', "https://mdn.alipayobjects.com/huamei_f4t1bn/afts/img/A*A1g0RaZ-GJcAAAAAAAAAAAAADtOHAQ/original")

**Comment by NewByVector** [comment]
可以这样使用，会触发 propHooks 的执行：
```ts
node.prop({
  imageUrl: 'xx'
})
```
已经将这个说明标注在文档中。
