### ISSUE TITLE
当同时启用节点编辑和框选的时，编辑时有点问题

### ISSUE THREAD

**Issue by wtjperi2003** [antvis/X6#3488]
### Describe the bug

见图：
![Snipaste_2023-04-11_15-19-55](https://user-images.githubusercontent.com/10322892/231085830-3ec12513-69bc-4665-80c1-a252d9059873.png)
框选没对齐

### Your Example Website or App

http://x6.antv.antgroup.com/examples/node/custom-node/#custom-with-svg

### Steps to Reproduce the Bug or Issue

```javascript
import { Graph } from '@antv/x6'
import { Transform } from '@antv/x6-plugin-transform'
import { Selection } from '@antv/x6-plugin-selection'
Graph.registerNode(
  'custom-node',
  {
    width: 200,
    height: 60,
    attrs: {
      body: {
        stroke: '#5F95FF',
        strokeWidth: 1,
        fill: 'rgba(95,149,255,0.05)',
        refWidth: 1,
        refHeight: 1,
      },
      image: {
        'xlink:href':
          'https://gw.alipayobjects.com/zos/antfincdn/FLrTNDvlna/antv.png',
        width: 16,
        height: 16,
        x: 12,
        y: 12,
      },
      title: {
        text: 'Node',
        refX: 40,
        refY: 14,
        fill: 'rgba(0,0,0,0.85)',
        fontSize: 12,
        'text-anchor': 'start',
      },
      text: {
        text: 'this is content text',
        refX: 40,
        refY: 38,
        fontSize: 12,
        fill: 'rgba(0,0,0,0.6)',
        'text-anchor': 'start',
      },
    },
    markup: [
      {
        tagName: 'rect',
        selector: 'body',
      },
      {
        tagName: 'image',
        selector: 'image',
      },
      {
        tagName: 'text',
        selector: 'title',
      },
      {
        tagName: 'text',
        selector: 'text',
      },
    ],
  },
  true,
)

const graph = new Graph({
  container: document.getElementById('container')!,
  grid: true,
})
graph

      .use(
          new Selection({
            enabled: true,
            rubberband: false,
            showNodeSelectionBox: true,
          }),
      )
graph.addNode({
  x: 200,
  y: 160,
  shape: 'custom-node',
  tools: [
      {
        name: 'node-editor',
      },
    ],
})

```

### Expected behavior

框框和节点边框对齐

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NongfuWinter** [comment]
我的用的vue3，编辑都无法使用。然后用的x6 1版本的方法注册的编辑工具，但是双击编辑后，什么都不做，点一下画板空白处后，节点标签文字直接消失。难受啊！

**Comment by NewByVector** [comment]
release x6@2.9.7 and selection@2.1.7.

**Comment by zzzhanga** [comment]
> 我的用的vue3，编辑都无法使用。然后用的x6 1版本的方法注册的编辑工具，但是双击编辑后，什么都不做，点一下画板空白处后，节点标签文字直接消失。难受啊！

编辑之后，你们在哪个事件去向后端发请求啊，求告知

**Comment by NongfuWinter** [comment]
> > 我的用的vue3，编辑都无法使用。然后用的x6 1版本的方法注册的编辑工具，但是双击编辑后，什么都不做，点一下画板空白处后，节点标签文字直接消失。难受啊！
> 
> 编辑之后，你们在哪个事件去向后端发请求啊，求告知

这和后端有什么关系，想保存的话，调用graph的toJSON方法，存到数据库里

**Comment by zzzhanga** [comment]
> > > 我的用的vue3，编辑都无法使用。然后用的x6 1版本的方法注册的编辑工具，但是双击编辑后，什么都不做，点一下画板空白处后，节点标签文字直接消失。难受啊！
> > 
> > 
> > 编辑之后，你们在哪个事件去向后端发请求啊，求告知
> 
> 这和后端有什么关系，想保存的话，调用graph的toJSON方法，存到数据库里
编辑之后不是点击空白处关闭编辑吗。我想知道在哪个钩子里面去保存

**Comment by NongfuWinter** [comment]
> > > > 我的用的vue3，编辑都无法使用。然后用的x6 1版本的方法注册的编辑工具，但是双击编辑后，什么都不做，点一下画板空白处后，节点标签文字直接消失。难受啊！
> > > 
> > > 
> > > 编辑之后，你们在哪个事件去向后端发请求啊，求告知
> > 
> > 
> > 这和后端有什么关系，想保存的话，调用graph的toJSON方法，存到数据库里
> > 编辑之后不是点击空白处关闭编辑吗。我想知道在哪个钩子里面去保存

这个是自动保存的，但是我觉得不好用自己搞了一个input锚定在默认标签上，数据搞了个双向绑定，就做好了。

**Comment by wu0211** [comment]
> > 我的用的vue3，编辑都无法使用。然后用的x6 1版本的方法注册的编辑工具，但是双击编辑后，什么都不做，点一下画板空白处后，节点标签文字直接消失。难受啊！
> 
> 编辑之后，你们在哪个事件去向后端发请求啊，求告知

node:changed
