### ISSUE TITLE
npm最新版@antv/x6@2.9.5的依赖@antv/x6-geometry@2.0.4没有暴露出src

### ISSUE THREAD

**Issue by Hexrt** [antvis/X6#3492]
### Describe the bug

相关修复的issue #3333，代码确实修复了但貌似又没修复
以下是报错，找到了相关 问题issue #3321，应该更新一下geometry就ok
![image](https://user-images.githubusercontent.com/57286895/231134209-11c569a1-b087-41a1-9604-5b9351358b7f.png)
**通过npm官网找到的资源**
![image](https://user-images.githubusercontent.com/57286895/231134627-1cd1dd19-4724-4d11-bc5f-af67cf9a7fe4.png)
**顺着往下找**
![image](https://user-images.githubusercontent.com/57286895/231134662-c806dcac-9e43-45af-9457-c58cbca10611.png)

### Your Example Website or App

npm install @antv/x6

### Steps to Reproduce the Bug or Issue

npx create-react-app xxxxxx --template=typescript
cd xxxxxx 
npm install @antv/x6
npm run start

### Expected behavior

正常运行

### Platform

- OS: [Windows]
- Browser: [Edge]
- Version: [@antv/x6@2.9.5]

**Comment by NewByVector** [comment]
已经发布了新的包，重新更新一下吧。
