### ISSUE TITLE
@antv/x6-plugin-transform插件问题

### ISSUE THREAD

**Issue by woshiwhy** [antvis/X6#3493]
### Describe the bug

官网实例：
restricted为false 调整大小边界是否可以超出画布边缘。
![image](https://user-images.githubusercontent.com/21192448/231326479-8cce4fd5-c44b-4b85-b36f-771082a13cca.png)
调整节点大小发现依然可以超过画布

### Your Example Website or App

https://x6.antv.antgroup.com/tutorial/plugins/transform

### Steps to Reproduce the Bug or Issue

官网示例操作

### Expected behavior

restricted为false 调整节点大小边界不能超出画布边缘。是否支持拖拽的时候，也不能超过画布边缘。

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/21192448/231327180-35afde62-646e-4925-aa58-45a674761fa4.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

@antv/x6-plugin-transform
antv/x6: 2.0

**Comment by NewByVector** [comment]
这个配置名称修改，文档没有修改过来，对内造成困惑，十分抱歉。
