### ISSUE TITLE
自定义vue节点 节点太多  渲染卡顿 怎么办

### ISSUE THREAD

**Issue by xufenghu** [antvis/X6#3494]
### 问题描述

自定义vue节点 节点太多  渲染卡顿 怎么办

### 重现链接

暂无

### 重现步骤

1. 自定义的vue组件节点  节点上 有很多扩展功能 
2. 新增节点 超过50个的时候  任何节点操作都会使页面渲染卡顿
3. 节点很多的时候  拖拽中心节点 让所有节点跟着一起拖拽 会有残影出现 

### 预期行为

我期望  自定义节点 不管数量有多少  渲染都不会卡顿   拖拽也不会有残影

### 平台

操作系统: [Windows]
网页浏览器: [Google Chrome]
X6 版本: [1.32.3]

**Comment by NewByVector** [comment]
建议升级到 2.x 版本，性能会有比较大的提升，不过看你的描述，现在只有50 节点，理论上不应该出现上述情况，能否提供一个可以复现的 demo，我们排查一下。

**Comment by xufenghu** [comment]
2.x版本 我之前试过  老是有bug  跟我的项目 不兼容    数据越多的时候   渲染就是会很卡

**Comment by NewByVector** [comment]
50 个不应该很卡的，能否提供一个 demo 看下呢？你也可以试试 async 模块，看下是否有性能提升。

**Comment by xufenghu** [comment]
async 模块 我试过了  差不多的感觉    因为我的vue组件里  定制了很多功能  每次渲染都是  把所有数据全都重新渲染  所有很卡   我不知道有没有方法可以 进行局部渲染  没改过的节点 不渲染

**Comment by NewByVector** [comment]
最好做局部渲染的，每次都重新渲染肯定有性能问题的。这个需要你们自己来实现。

**Comment by 565823371556Zsl** [comment]
> 50 个不应该很卡的，能否提供一个 demo 看下呢？你也可以试试 async 模块，看下是否有性能提升。

我在graph中的渲染的节点是vue节点，我使用的 多选框插件，多选节点，并进行拖拽时，节点数如果有50个就会非常卡顿

**Comment by 565823371556Zsl** [comment]
> 50 个不应该很卡的，能否提供一个 demo 看下呢？你也可以试试 async 模块，看下是否有性能提升。

有没有办法，框选移动节点的时候，不移动节点，只移动那个框，等松开鼠标的时候再把节点移动过去

**Comment by damnright** [comment]
> > 50 个不应该很卡的，能否提供一个 demo 看下呢？你也可以试试 async 模块，看下是否有性能提升。
> 
> 有没有办法，框选移动节点的时候，不移动节点，只移动那个框，等松开鼠标的时候再把节点移动过去

可以自己实现，先获取节点包围框，松开鼠标了移动过去即可

**Comment by NewByVector** [comment]
@qiufeihong2018 如果是 2.x 版本，开启 virtual 就具备可视区域渲染能力。

**Comment by Mephistol** [comment]
> 最好做局部渲染的，每次都重新渲染肯定有性能问题的。这个需要你们自己来实现。

请教一下，我的1.34.13版本，通过创建节点时候visible和拖拽画布时候setVisible模拟了virtual功能，不过minimap功能就废了，minimap没办法展示初次可视区域以外的节点，有啥好办法吗？🥺
