### ISSUE TITLE
x6节点编辑未完成时，再次双击，会出现新的文本输入框

### ISSUE THREAD

**Issue by wj438144271** [antvis/X6#3497]
### 问题描述

节点编辑时未编辑完成时再次双击会出现新的文本输入框，样式错乱
![image](https://user-images.githubusercontent.com/30406562/231398922-1837ce46-9adc-4847-9940-688892039956.png)

### 重现链接

https://codesandbox.io/s/new)

### 重现步骤

节点编辑时未编辑完成时再次双击会出现新的文本输入框，样式错乱

### 预期行为

文本样式正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/30406562/231399890-a0e5e787-c2d3-4d1e-a9fc-5589f76b11b0.png)

**Comment by qiufeihong2018** [comment]
@wj438144271 重现链接有问题吧？可以重新发一下吗

**Comment by NongfuWinter** [comment]
> release x6@2.9.7 and selection@2.1.7.

节点编辑是没问题了，但是边的标签编辑还是有问题。你们官网2.x，api，注册，边上工具，edge-editor，那个示例图，什么都不做，一直双击那个边的标签就可以看见bug。

**Comment by NewByVector** [comment]
@NongfuWinter 具体是什么问题呢？
