### ISSUE TITLE
button-remove 删除二次确认怎么加呢

### ISSUE THREAD

**Issue by liyangyangi** [antvis/X6#3498]
### 问题描述

```
graph.on('cell:mouseenter', (item: any) => {
    const cell = item.cell
      cell.addTools([
        {
          name: 'button-remove',
          args: {
            x: 0,
            y: 0,
            offset: { x: 45, y: 0 },
          },
        },
      ])   
 })
```
通过addTools加的工具 删除的时候想加个弹框 二次确认后再删除怎么加呢

### 重现链接

无

### 重现步骤

无

### 预期行为

有方案吗

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以在 `button-remove` 的 args 中重写 `onClick` 配置来覆盖默认行为。

**Comment by liyangyangi** [comment]
可以了 感谢
