### ISSUE TITLE
选择框的层级太高，覆盖住了下层节点的弹层

### ISSUE THREAD

**Issue by qiufeihong2018** [antvis/X6#3500]
### 问题描述

首先，节点hover的时候，该svg层级是toFront的（最高的）。
其次，我选中了上一个节点，悬浮到下一个节点，下一个节点产生的弹层被覆盖了。
原因不知道是选择框的层级太高还是选择框脱离了svg列表的原因，覆盖住了下层节点的弹层

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

层级优先级：弹层> 选择框>节点

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 1.32.3

### 屏幕截图或视频（可选）

<img width="491" alt="image" src="https://user-images.githubusercontent.com/36500514/231455584-41bbb11e-ea0e-4700-a384-74657c73701f.png">

**Comment by NewByVector** [comment]
没看懂你的描述和图对应的关系，能否描述清晰一点呢？

**Comment by qiufeihong2018** [comment]
其实跟这个issue有些类似：https://github.com/antvis/X6/issues/1297 就是选择框的层级太高了，呈现在最上面，最后的解决方案是限制节点禁止脱离画布，有没有更好的解决方案？

- 问题：
    层级：选择框>弹层>节点
- 想调整如下：
层级等级：弹层>选择框>节点
-  但是有问题：

1. 首先，节点hover的时候，该svg层级是toFront的（最高的）。
2. 其次，我选中了上一个节点，悬浮到下一个节点，下一个节点产生的弹层被覆盖了。原因不知道是选择框的层级太高还是选择框在svg dom下面的原因，覆盖住了下层节点和弹层


后来，我调整了下，是否可以将x6-widget-selection dom放到svg之前？我看问题就解决了，不知道可以吗？

<img width="937" alt="image" src="https://user-images.githubusercontent.com/36500514/231640870-a971ce1c-0389-4f3c-9b33-13215657133b.png">

**Comment by qiufeihong2018** [comment]
感谢大佬的解答，问题已解决，我这个场景选择框不需要 showNodeSelectionBox
```
        // 不显示节点的选择框，这里使用定制方法去定制自己的选择框样式
        showNodeSelectionBox: false,
```
给选中的节点增加一个 
```
  // 选择框
  .x6-node-selected {
    outline: 3px solid #efsdcd;
    border-radius: 4px;

    // tip：解决节点抖动的问题
    .x-node,
    .y-node,
    .z-node {
      border: 1px solid transparent
    }
  }
```
这个issue可以close了
