### ISSUE TITLE
历史记录功能 需要将 一组操作设置为一个 撤销栈

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3506]
### 功能描述

<img width="757" alt="image" src="https://user-images.githubusercontent.com/39638510/231921690-30a9a138-8f0a-4f38-a592-59591dc4a77f.png">

我现在有一个群组组件, 拖拽出来就是这样, 但是撤销的时候 想都删除, 不是一个一个回退, 请问有相关api吗, 没找到

### 期望解决方案

可能希望 可以简便一点
history.groupListenerStart();
graph.xxxx;
graph.xxxx;
graph.xxxx;
graph.xxxx;
history.groupListenerStop();

希望 开启 groupListener后 在stop前所有的 执行的操作 都 可以为一个 撤销栈, 撤销一次是撤销中间记录的所有操作   🙏🏻

**Comment by JoeABCDEF** [comment]
> 看看这个是否满足需求
> 
> https://x6.antv.vision/zh/docs/api/graph/graph#startbatch

@Akimyou  这个意思是指将一组操作保存起来吗, 执行的时候 执行这一组操作吗?

**Comment by NewByVector** [comment]
@JoeABCDEF 
![image](https://github.com/antvis/X6/assets/20186737/2917252c-7988-4305-b818-df53851ccfd9)
http://x6.antv.antgroup.com/tutorial/plugins/history
