### ISSUE TITLE
同一份数据，使用左右布局卡顿，ELK绝对布局不卡

### ISSUE THREAD

**Issue by Mrheqiang** [antvis/X6#3508]
### 问题描述

使用同一份数据，data1为ELK布局后的数据，data2为X6自带的左右布局数据。在使用x6自带的左右布局，移动节点时，会很卡顿。然而使用ELK绝对布局后，改数据又可以正常的移动，卡顿现象不存在。目前发现有个manhattan连线问题，改成orth卡顿明显减少。

### 重现链接

https://codesandbox.io/s/suspicious-brook-5nd01u?file=/src/App.js

### 重现步骤

1.进入页面
2.选择不同的数据展示
3.移动节点，观察

### 预期行为

期望都正常移动不卡顿，但是左右布局的卡顿，找不到具体原因

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.32.3-beta.1 ]

**Comment by NewByVector** [comment]
使用 `manhattan` 路由移动过程中会持续计算边的位置进行避开障碍物，所以比较卡顿。
