### ISSUE TITLE
框选太离谱了 都能选到elemet-ui

### ISSUE THREAD

**Issue by luocong2016** [antvis/X6#3509]
### 问题描述

![image](https://user-images.githubusercontent.com/25705196/231975932-02e759cd-ffa9-4f1e-a6e5-b2df6cf80c23.png)

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

1. el-input 居然被加了.selected

### 预期行为

局限在cell 类或继承类中

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by luocong2016** [comment]
加了这个才取消 window.getSelection ? window.getSelection().removeAllRanges() : document.selection.empty();

**Comment by lloydzhou** [comment]
这个重现链接是不是有问题？

**Comment by hhzhldhjl** [comment]
ctrl+a全选时也有这问题，请问你是怎么解决的

**Comment by NewByVector** [comment]
重现链接有问题呀。
