### ISSUE TITLE
scale 和 zoom 方法的焦虑

### ISSUE THREAD

**Issue by bubkoo** [antvis/X6#351]
目前 [`scale`](https://x6.antv.vision/zh/docs/api/graph/#scale) 方法用户缩放基础画布，[`zoom`](https://x6.antv.vision/zh/docs/api/graph/#zoom) 方法用于缩放带 scroller 的画布，其中 `zoom` 方法内部调用了 `scale` 方法。两个方法的参数和行为不一致，对用户极其不友好。可能的优化方式：
1. 统一为一个方法，将其中一个标记为 `deprecated `，但可能存在不兼容的更新。
2. 加强文档说明，并指出将在下一个大版本(V2)中，进行优化。

另外列举了一下只有在启用 scroller 后，在 graph 才可使用的方法，如果没有开启 scroller 调用这些方法将抛出异常：
- scrollToPoint
- scrollToContent
- scrollToCell

- center                          
- centerPoint
- centerContent
- centerCell

- positionContent
- positionCell
- positionRect
- positionPoint

- zoom
- zoomTo
- zoomToRect
- zoomToFit

- transitionToPoint
- transitionToRect

这些方法是否可以进一步兼容到普通画布上？

**Comment by NewByVector** [comment]
#### 通用方法
- zoom(scale还保留，设置为deprecated)
- zoomTo
- zoomToRect
- zoomToFit
- center
- centerPoint
- centerContent
- centerCell
- positionContent
- positionCell
- positionRect
- positionPoint
- transitionToPoint 
- transitionToRect

#### scroller独有
- lockScroller
- unlockScroller
- updateScroller
- getScrollbarPosition
- setScrollbarPosition
- scrollToPoint
- scrollToContent
- scrollToCell
