### ISSUE TITLE
2.x删除了render:done事件，能否加上

### ISSUE THREAD

**Issue by GrayLinTouchWorld** [antvis/X6#3512]
### 问题描述

场景：编辑流程的画布和展示流程的画布大小不一致，需要等到画布渲染完毕再进行居中处理，如果编辑画布宽高大于展示画布，直接进行居中处理会导致流程图超出画布，这个情况用view:mounted也不是很好解决，希望能够恢复该api

### 重现链接

无

### 重现步骤

编辑流程的画布和展示流程的画布大小不一致，需要等到画布渲染完毕再进行居中处理，如果编辑画布宽高大于展示画布，直接进行居中处理会导致流程图超出画布

### 预期行为

希望能够恢复[该](render:done) api

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
增加了两个事件 [view:mounted](http://x6.antv.antgroup.com/tutorial/basic/events#%E8%A7%86%E5%9B%BE) 以及 view:unmounted。

**Comment by favorite58** [comment]
同样遇到该问题，需要怎么解决？view:mounted触发的非常频繁，没法判断画布渲染完毕

**Comment by NewByVector** [comment]
@favorite58 升级到 2.15.1，增加了 render:done 事件。
