### ISSUE TITLE
x6-2.x在撤销回退无法对新增的属性进行抹除

### ISSUE THREAD

**Issue by yi749027176** [antvis/X6#3514]
### 问题描述

在对图元进行属性修改时，如果是新增的属性，则无法实现撤销的效果；
例如将边框的线段类型设置成stroke-dasharray="8"，在撤销时无法将stroke-dasharray="8"抹去。

### 重现链接

https://x6.antv.antgroup.com/examples/showcase/practices/#flowchart

### 重现步骤

1.进入官网demo，https://x6.antv.antgroup.com/examples/showcase/practices/#flowchart
2.加入下列代码
`graph.on('node:added', ({ e, cell, index, node, options }: any) => {
  setTimeout(()=>{
    node.setAttrs({body:{strokeDasharray:8}})
  },10)
  setTimeout(()=>{
    node.setAttrs({body:{strokeDasharray:20}})
  },300)

  setTimeout(()=>{
    console.log('---执行撤销1')
    graph.undo()
  },3000)
    setTimeout(()=>{
    console.log('---执行撤销2')
    graph.undo()
  },2000)
})`
3.图元在第一次撤销时，能正常进行，第二次撤销时无法将strokeDasharray:8抹去。

### 预期行为

期望在撤销时，可以将新增的属性抹除

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome ]
- X6 版本:2.x

**Comment by NewByVector** [comment]
更新到 @antv/x6-plugin-history@2.2.2 版本。

**Comment by yi749027176** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
