### ISSUE TITLE
 stencil responsive layout

### ISSUE THREAD

**Issue by jiang-zhong-xi** [antvis/X6#3517]
### Describe the feature you'd like to request

number of columns can auto adjust when stencil size change.
when components overflow, there should be a scrollbar.

### Describe the solution you'd like

provide a switch in layout option

### Describe alternatives you've considered

none

### Screenshots or Videos
![image](https://user-images.githubusercontent.com/59865643/232987579-b7a387ac-abd5-4bb2-8dc7-ba831cfdcef5.png)

**Comment by jiang-zhong-xi** [comment]
> when you set `stencilGraphHeight = 0`, the height of the graph is adaptive,moreover, stencil provides `resizeGroup` method to dynamically resize the group.
but the columns of nodes can not change when I change the graph width, afterall scrollbar is not good experience.

**Comment by NewByVector** [comment]
If you need a flexible layout, use dnd to customize it. @jiang-zhong-xi
