### ISSUE TITLE
X6 1.x手册打不开

### ISSUE THREAD

**Issue by louhaojie99** [antvis/X6#3522]
### 问题描述

![image](https://user-images.githubusercontent.com/61346611/233277289-bf9a01bf-2c19-49e1-af5c-7a9e6c149163.png)
![image](https://user-images.githubusercontent.com/61346611/233277319-a1f7e3bd-4504-43c6-80e1-4d10d6b71e21.png)
一直加载中中~

### 重现链接

https://x6.antv.vision/

### 重现步骤

X6(1.x版本手册): https://x6.antv.vision/

### 预期行为

预期能看到1.x的文档

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
X6 1.x 文档部署在 gh-pages 上面，访问比较慢，可以直接访问 [2.0](http://x6.antv.antgroup.com/)，2.0 在 API 层改动并不大。
