### ISSUE TITLE
Incorrect edge position two ports of different nodes are linked within the same level

### ISSUE THREAD

**Issue by harshaktg** [antvis/X6#3525]
### Describe the bug

When there is an edge which connects two ports of two different nodes within the same level, then the edge is overlapping on the nodes and it disturbs the graph

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

1. Have two nodes on the same level
2. Have ports within them
3. Draw and edge which connects either of these ports

### Expected behavior

The edges shouldn't overlap on the nodes

### Screenshots or Videos

<img width="285" alt="image" src="https://user-images.githubusercontent.com/40317596/233359996-7df15250-a405-4e5c-acfb-2b9993ecc5b6.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
You can set the level of edge a little lower, like -1.

**Comment by harshaktg** [comment]
What do you mean by level of edge? Can you share an example? @NewByVector

**Comment by damnright** [comment]
> What do you mean by level of edge? Can you share an example? @NewByVector

The "edge" also has attr:"z-index",use like that:"edge.zIndex=-1;"

**Comment by harshaktg** [comment]
No, this isn't regarding the z-index? As you see above I basically need the arrow position to be perfect. Right now, it's direction is right to left. But I need the direction to be left to right, when the edge is connecting @damnright @NewByVector

**Comment by damnright** [comment]
The edge above seems like a Cubic Bézier curve with 4 control points.Perhaps you should refine the edge's connector to ensure the path in proper way.
