### ISSUE TITLE
多个简单图元，组合为一个新图元问题

### ISSUE THREAD

**Issue by light-years-run** [antvis/X6#3530]
### 问题描述

想实现，鼠标拖动到画布上，然后组合为一个新的图元。
目前有两个思路：
1、把每个图元的markup和attrs组合，然后放在一个新的node里面
2、使用Group组，拖出来的图元挂在新node的子节点下

第一种方案，需要转换已有图元为markup，第二种方案，实现图元多状态不知用什么办法

想咨询有没有更好的方案，实现拖动简单图元组合为一个新图元

### 重现链接

test

### 重现步骤

拖动简单图元到画布
形成新的图元

### 预期行为

拖动简单图元到画布
形成新的图元

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by JoeABCDEF** [comment]
我也有这个需求, 我是多个组合一起 拖拽出还是多个(群组), 这样可以自己在进行修改
点击保存的时候 自己保存下信息 使用原生拖拽, 然后drop 后在 自己根据信息自己addNode

<img width="592" alt="image" src="https://user-images.githubusercontent.com/39638510/233892191-29fecca2-4a1f-4c02-a859-860d40bdeda2.png">
![image](https://user-images.githubusercontent.com/39638510/233892202-e538e1c2-715a-4ed6-8a98-0bc21087dda4.png)

**Comment by light-years-run** [comment]
> 我也有这个需求, 我是多个组合一起 拖拽出还是多个(群组), 这样可以自己在进行修改 点击保存的时候 自己保存下信息 使用原生拖拽, 然后drop 后在 自己根据信息自己addNode
> 
> <img alt="image" width="592" src="https://user-images.githubusercontent.com/39638510/233892191-29fecca2-4a1f-4c02-a859-860d40bdeda2.png">
> 
> ![image](https://user-images.githubusercontent.com/39638510/233892499-f19b8b0f-eefd-47d9-b6fc-e9dd6b6a35c9.png)

你是通过群组实现的吗？针对线段有好的解决方案吗？我是组合markup，但是线段path 使用refD后会撑满整个组合图形，使用polyline 的refPoints 存在同样问题......

**Comment by JoeABCDEF** [comment]
> > 我也有这个需求, 我是多个组合一起 拖拽出还是多个(群组), 这样可以自己在进行修改 点击保存的时候 自己保存下信息 使用原生拖拽, 然后drop 后在 自己根据信息自己addNode
> > <img alt="image" width="592" src="https://user-images.githubusercontent.com/39638510/233892191-29fecca2-4a1f-4c02-a859-860d40bdeda2.png">
> > ![image](https://user-images.githubusercontent.com/39638510/233892499-f19b8b0f-eefd-47d9-b6fc-e9dd6b6a35c9.png)
> 
> 你是通过群组实现的吗？针对线段有好的解决方案吗？我是组合markup，但是线段path 使用refD后会撑满整个组合图形，使用polyline 的refPoints 存在同样问题......

@light-years-run   不清楚你那个问题 我就是群组 , 保存 了层级关系到后端, 前端根据这个再去处理渲染, 没有遇到你那个问题
