### ISSUE TITLE
原生大驼峰属性被解析, 导致属性不生效

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3534]
### 问题描述

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/39638510/233891281-7bc9d887-9dd1-4178-87df-35a18d44baef.png">

这种本身就是大驼峰属性 `gradientUnits`, 但最终解析后被转换成 `gradient-units`, 导致属性不生效, 影响 使用

### 重现链接

无

### 重现步骤

无

### 预期行为

本身是大驼峰的属性不要解析

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.9.7]

**Comment by bighhhh** [comment]
问题解决了吗？我也遇到这个问题了

**Comment by bighhhh** [comment]
preserveAspectRatio这个属性也需要加入白名单
