### ISSUE TITLE
如何限制节点在画布可视区域内拖动

### ISSUE THREAD

**Issue by JoeWrights** [antvis/X6#3537]
### 问题描述

我看官网的例子都是节点可以拖到画布可视区域外，想看到节点就只能拖动画布，是否可以直接限制节点在当前画布区域内拖动呢

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

希望能限制节点在当前画布区域内拖动

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
可以使用 [restrict](http://x6.antv.antgroup.com/api/model/interaction#restrict) 配置。
