### ISSUE TITLE
x6 edge连线贴着rect节点的边的问题

### ISSUE THREAD

**Issue by 2193531059** [antvis/X6#3538]
### 问题描述

你好，项目中有几个rect节点，通过连接桩port连线， 会有连线贴着节点边的问题，请问这个怎么优化？下面我贴下连线相关的代码：
`// 创建Graph的时候的配置
connecting: {
snap:true, // 是否自动吸附节点的连接桩
allowNode: (options) => {
// 定义哪些节点允许连线
console.log('connecting allowNode =====> options: ', options)
return true;
},
// 连接点 ConnectionPoint 与锚点 Anchor 共同确定了边的起点或终点。
connectionPoint: {
name:'anchor',
args: {
sticky:true,
}
},
anchor: {
name: "center",
args: {
dx: 10,
},
},
// 定义连线的路由样式
router: {
name: 'manhattan',
args: {
step: 20,
}
},
// 定义连线的弯折点样式
connector: {
name: 'rounded',
args: {
radius: 8,
},
},
allowBlank: false,
allowEdge: false,
allowLoop: false,
allowMulti: false,

  validateEdge({ edge }) {
    console.log('connecting validateEdge =====> edge: ', edge)
    // 校验连线
    return true
  },
},
// 创建几个普通的rect节点
baseAddNode() {
// 使用构造方式创建节点
const rect1 = new Shape.Rect({
x: 100,
y: 200,
width: 80,
height: 40,
attrs: {
body: {
fill: 'white',
},
label: {
text: 'rect1',
fill: 'black',
},
},
ports,
})
this.graph.addNode(rect1)

  const rect2 = new Shape.Rect()
  rect2
      // 设置节点位置
      .position(200, 250)
      // 设置节点大小
      .resize(80, 40)
      // 设置节点样式
      .attr({
        body: {
          fill: 'white',
        },
        label: {
          text: 'rect2',
          fill: 'black',
        },
      })
  this.graph.addNode(rect2)

  this.graph.addNode({
    shape: 'rect', // 指定使用何种图形，默认值为 'rect'
    x: 350,
    y: 300,
    width: 80,
    height: 40,
    attrs: {
      body: {
        fill: 'white',
      },
      label: {
        text: 'rect3',
        fill: 'black',
      },
    },
    ports,
  })
},`

### 重现链接

无

### 重现步骤

1.创建几个rect节点；
2.用edge给它们之间连线；
3.拖动rect节点，发现与其相连的线有贴着它的边的问题。

### 预期行为

在拖动节点的过程中，能避免edge连线贴节点的问题。

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.0.0]

**Comment by 2193531059** [comment]
在路由里面过滤掉起始节点就行

**Comment by imtzx** [comment]
> 

用什么路由好一点呢
