### ISSUE TITLE
2.X版本  在1个大矩形背景下2个矩形间曼哈顿路由连线不自然问题

### ISSUE THREAD

**Issue by lessgeek** [antvis/X6#3540]
### Describe the bug

![QQ图片20230425221035](https://user-images.githubusercontent.com/21116669/234303600-38da6504-bc79-4005-8a03-7bc735fd44df.png)
如上面官网demo的截图所示，如果在1个大矩形背景上进行2个小矩形的曼哈顿路由连线，连线的轨迹和终点箭头方向都不自然，期望的是截图下方的连线效果。
请问有没有什么办法让连线始终自然么？使用的是X6 2.0版本官网的demo。

### Your Example Website or App

https://x6.antv.antgroup.com/examples/showcase/practices#flowchart

### Steps to Reproduce the Bug or Issue

1. 进入官网demo地址https://x6.antv.antgroup.com/examples/showcase/practices#flowchart；
2. 先拖入一个矩形A作为背景，并在矩形A上拖入矩形B和矩形C；
3. 在矩形B右边的桩上连线到矩形C的左边桩上；
4. 发现连出的线条轨迹和终点箭头方向不对，更像是要连到背景矩形A中的效果。

### Expected behavior

我期望在一个矩形背景上，对矩形进行连线，连线的轨迹和终点箭头方向应该自然。

### Platform

操作系统: [Windows]
网页浏览器: [Google Chrome,]
X6 版本: [2.x ]

**Comment by 2193531059** [comment]
我也遇到这种问题了，我调了下connecting的connectionPoint，anchor，router增加padding等，好像效果好些了，但还是没有根治

**Comment by yi749027176** [comment]
同遇到次问题，没有解决方案，官方可以分析一下原因，让我们规避吗？

**Comment by SunYuanOnly** [comment]
遇到相同的问题

**Comment by yi749027176** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by NewByVector** [comment]
问题原因：因为大节点的存在，连线无法避开障碍物(也就是大节点)，所以路由降级为 orth，也就是上图表现，其实控制台也有打印 `Unable to execute manhattan algorithm, use orth instead`。

解决办法：使用 [manhattan](http://x6.antv.antgroup.com/api/registry/router#manhattan) 的 `excludeShapes` 或者 `excludeNodes` 配置将大节点排除掉，不计入障碍物。
