### ISSUE TITLE
vue2中，通过Graph.registerNode注册自定义节点，组件内inject时报injection "getNode" not found

### ISSUE THREAD

**Issue by code-37** [antvis/X6#3544]
### 问题描述

vue2中，通过Graph.registerNode注册自定义节点，组件内inject时报injection "getNode" not found

### 重现链接

-

### 重现步骤

组件注册：
 
![image](https://user-images.githubusercontent.com/57384296/234549336-a07fe0a2-86bb-402d-9aaa-e71538a6b716.png)

创建节点：
![image](https://user-images.githubusercontent.com/57384296/234549486-9b14d601-1435-4fda-8959-d37c3c32dfc6.png)

组件内：
![image](https://user-images.githubusercontent.com/57384296/234549566-2942a92e-f95b-4102-a6ff-bcc23e473b97.png)

版本：     "@antv/x6": "1.34.6",
    "@antv/x6-vue-shape": "1.1.4",

### 预期行为

正常使用getnode

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]

     "@antv/x6": "1.34.6",
    "@antv/x6-vue-shape": "1.1.4",

**Comment by JNlike** [comment]
你试试在vue组件的mounted里面，这样写一下if(this.getNode){const node=this.getNode();}好像就没了

**Comment by NewByVector** [comment]
请问这个问题解决了吗，如果还有问题，请重新提一个新的 issue。
