### ISSUE TITLE
希望在1.x版本更新节点合并的判定选项

### ISSUE THREAD

**Issue by nanfb** [antvis/X6#3547]
### 功能描述

目前画布的节点合并最大是支持到bbox但是很多需求是需要更大的范围的，甚至可以说大部分的嵌套节点的判定都会比bbox大，在一定的范围内可以触发吸附，或者直接吧吸附的判定距离加到判定的盒子上，可以给个选项。群里直播的时候提过这个问题，希望可以在1.x也实现。

### 期望解决方案

/

**Comment by NewByVector** [comment]
参考 [demo](https://codesandbox.io/s/zi-ding-yi-embedding-de-padding-f9y9jj)。

**Comment by nanfb** [comment]
> 参考 [demo](https://codesandbox.io/s/zi-ding-yi-embedding-de-padding-f9y9jj)。

可以的，谢谢😊

**Comment by nanfb** [comment]
> 参考 [demo](https://codesandbox.io/s/zi-ding-yi-embedding-de-padding-f9y9jj)。

因为这个配置导致【监听添加节点后为其添加子节点】后单独移动子节点会导致关联消失。但是我看太懂，为什么移动父节点的子节点会让子节点脱离，

**Comment by nanfb** [comment]
> > 参考 [demo](https://codesandbox.io/s/zi-ding-yi-embedding-de-padding-f9y9jj)。
> 
> 因为这个配置导致【监听添加节点后为其添加子节点】后单独移动子节点会导致关联消失。但是我看太懂，为什么移动父节点的子节点会让子节点脱离，

感觉开启embedding后，子节点配置就会很混乱
