### ISSUE TITLE
插件Dnd添加节点，在getDropNode方法里手动修改节点的zIndex值无效

### ISSUE THREAD

**Issue by ajesses** [antvis/X6#3548]
### Describe the bug

在 使用插件 Dnd 进行拖拽添加节点时，在 getDropNode 方法里，手动修改节点的 zIndex 值，发现添加后节点的 zIndex 不是手动设置的值，代码如下
```
getDropNode(node) {
      // 返回一个新的节点作为实际放置到画布上的节点
      const { width, height } = node.size();
      let n = node.clone().size(width * 3, height * 3);
      console.log(n);
      n.setZIndex(1);
      return n;
},
```

### Your Example Website or App

https://codesandbox.io/s/determined-worker-m163tf?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1. 打开官网例子：https://x6.antv.vision/zh/docs/tutorial/basic/dnd/#gatsby-focus-wrapper
2. 在 实例 dnd 里加上 `getDropNode` 方法
![image](https://user-images.githubusercontent.com/20083799/234778744-20c1a59c-3f35-4948-afc0-e2e68a970d9b.png)
3. 添加节点，点击打印节点的 zIndex 值

### Expected behavior

期望，zIndex 值是手动设置的值

### Platform

- OS: Windows
- Browser: Chrome
- Version: @antv/x6  1.34.13

**Comment by NewByVector** [comment]
参考[常见问题 5](https://x6-site-pre.alipay.com/tutorial/plugins/dnd#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。
