### ISSUE TITLE
Graph highlighting cannot render rounded rectangle using rx and ry

### ISSUE THREAD

**Issue by johnnylc** [antvis/X6#3549]
### Describe the bug

Set the highlighting parameter as below:
```
highlighting: {
    magnetAvailable: {
      name: "stroke",
      args: {
        rx:4,
        ry:4,
        padding: 4,
        attrs: {
          "stroke-width": 2,
          stroke: "red",
        },
      },
    },
  },
```
the box is just a rectangle without rounded corners.

### Your Example Website or App

xxx

### Steps to Reproduce the Bug or Issue

Set highlighting parameter as above, then check the rendered scene.

### Expected behavior

Rectangle rendered correctly with rounded corners.

### Platform

- OS: macOS, Windows
- Browser: Chrome
- Version: 112.0.5615.138

**Comment by NewByVector** [comment]
我本地试了一下 rx 和 ry 是生效的，如果还有问题，请重新提一个新的 issue。
