### ISSUE TITLE
流程图左侧下拉菜单是否可以支持二级下拉菜单

### ISSUE THREAD

**Issue by Rong-ZS** [antvis/X6#3550]
### 功能描述

目前流程图里面的左侧的下拉就只有一级菜单，业务比较多的时候只有一级菜单就显得结构不是很清晰

### 期望解决方案

配置参数里面多增加childern等可以配置二级菜单

**Comment by Rong-ZS** [comment]
> 👋 @Rong-ZS
> 
> Thanks for opening your first issue here! If you're reporting a 🐞 bug, please make sure you include steps to reproduce it. To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/antvis/X6/blob/master/CONTRIBUTING.md). We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.

no! it not a bug, it's a new demand

**Comment by NewByVector** [comment]
不支持多级菜单的，可以使用 dnd 来实现，这样会更加灵活。
