### ISSUE TITLE
DOCS：文档和API中的fromJSON()传参不一致的情况

### ISSUE THREAD

**Issue by entireyu** [antvis/X6#3551]
### Describe the bug

![image](https://user-images.githubusercontent.com/73976915/234880862-ce9a9119-6efd-46cd-9024-e4af7d8ad852.png)
![image](https://user-images.githubusercontent.com/73976915/234881020-2b1a6ddb-489a-4a0c-9840-6c9162afc203.png)

### Your Example Website or App

https://x6.antv.antgroup.com/api/model/model#fromJSON

### Steps to Reproduce the Bug or Issue

如描述所示
在文档->基础->数据中fromJSON函数的传参与API Model的fromJSON函数传参不一致

### Expected behavior

如描述所示。

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
文档已经更新。
