### ISSUE TITLE
Antv X6 Stencil Drag and Drop Feature

### ISSUE THREAD

**Issue by salihkesepara** [antvis/X6#3554]
### 功能描述

I'm trying to do a simple behavior with stencil. In this example I create two nodes Node 1 and Node 2

The case is like this;

Drag and drop Node 1 into the graph.
User should see Node 2 into the graph.

https://codesandbox.io/s/ancient-river-w7n77x?file=/src/App.vue

![image](https://user-images.githubusercontent.com/9534850/235168994-08ab3fdc-cf41-4067-8d50-a75d2346b309.png)

![image](https://user-images.githubusercontent.com/9534850/235169025-7c0810f2-5dc3-43c8-9b88-99dc8e8d844f.png)

### 期望解决方案

Drag and drop Node 1 into the graph.
User should see Node 2 into the graph.

**Comment by NewByVector** [comment]
You can use `getDropNode` options to replace droped node like [this](https://codesandbox.io/s/strange-heisenberg-6e07sd?file=/src/App.vue).

**Comment by salihkesepara** [comment]
> You can use `getDropNode` options to replace droped node like [this](https://codesandbox.io/s/strange-heisenberg-6e07sd?file=/src/App.vue).

It worked thanks

**Comment by salihkesepara** [comment]
> You can use `getDropNode` options to replace droped node like [this](https://codesandbox.io/s/strange-heisenberg-6e07sd?file=/src/App.vue).

Basic solutions is fine but I can't create a node group. How to do this?

![image](https://user-images.githubusercontent.com/9534850/235196402-094edac9-0d1d-4a6c-95a1-2f8df84737f2.png)

**Comment by lloydzhou** [comment]
@salihkesepara 
https://github.com/antvis/X6/issues/2532
https://github.com/antvis/X6/issues/2349#issuecomment-1185422192
