### ISSUE TITLE
graph监听鼠标双击会多次触发单击事件

### ISSUE THREAD

**Issue by willYang1215** [antvis/X6#3558]
### 问题描述

node:dbclick会多次触发node:click
定时器只能解决多次的问题 
有没有人知道双击触发单击事件怎么解决

### 重现链接

https://stackblitz.com/edit/vue-ccyk8n?file=src%2FApp.vue

### 重现步骤

 graph.value.on("cell:dblclick", ({ cell }) => {
    clearTimeout(timeOut)
    console.log(’这里是双击事件‘)
  });
  graph.value.on('cell:click', ({ cell }) => { 
    clearTimeout(timeOut)
    timeOut = setTimeout(()=>{
     console.log(’这里是单击事件‘)
    },200)
  })

### 预期行为

双击不要触发单击事件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by willYang1215** [comment]
timeOut

**Comment by ajesses** [comment]
节点双击事件也会触发该节点的单击事件
![image](https://github.com/antvis/X6/assets/20083799/dd72bc9d-9d3e-4f9f-9e46-73dfc14adee6)

https://codesandbox.io/s/dawn-sky-vnj525
怎么只触发双击事件呢？
