### ISSUE TITLE
修改带有关系线的节点形状，有好的方式么？

### ISSUE THREAD

**Issue by avrinfly** [antvis/X6#3560]
### 问题描述

目前遇到一个问题，我要修改一个节点的形状，该节点和其他节点有关系线

因为图谱要求关系线不能连到画布的空白区域，导致现在的做法是：

先把这个点有关的线都记下来，然后删掉，修改完节点形状后，再把线重新连上

这个操作很低级，我想问问大佬们有没有好的方案

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by JamesTing** [comment]
我的做法，仅供参考。
1. 所有的节点，使用自定义react节点实现。
2. react节点，通过node/data定义节点形状，比如node/data下shape:rect表示改节点是个矩形。
3. 切换节点形状，就是直接修改node/data下shape的取值。

具体效果，可以这里查看 https://amymind.com/graph/new

**Comment by NewByVector** [comment]
暂时还没有内置方法来修改节点的形状，可以参考上面 @JamesTing 的做法。
