### ISSUE TITLE
关于使用polyline做一个多折线画笔遇到的问题求助

### ISSUE THREAD

**Issue by dinghaining** [antvis/X6#3562]
### Describe the bug

在做多折线画笔的时候遇到的问题，过程是这样的，points应该属于node节点xy的绝对定位，如果按照寻常的代码理解应该是直接用鼠标拖拽改变points的位置，这样就会发生node节点xy坐标默认为0的情况，Transform会出现在画布（0，0）的位置，为了解决这个问题我们将第一次鼠标点击作为xy轴初始点，后期所有拖拽点击全部新的鼠标点击减去xy轴坐标，这个时候出现了两个新的问题
1：我利用每一次点击把坐标点存储下来，xy轴最小点最大点都做出来了以后，相减做出来了宽度和高度利用resize重新赋予了node节点，可是因为是自由画笔，有可能出现polyline是负数的情况，会画到第四象限之外的位置，这样宽度高度确实是准确的，但是无法准确的包裹住node节点图形。
2：就算我完全画在第四象限，在拉大缩小的时候Transform的时候，node节点图形无法跟随框选一起拉大缩小，但是旋转是可以的，同时在同一块画布上面，我初始化直接一次性画好的节点就没有问题，可以拉大缩小旋转。
不知道以上是我配置不对还是bug，求教

### Your Example Website or App

vue3.2.47     vite4.2.0

### Steps to Reproduce the Bug or Issue

在做多折线画笔的时候遇到的问题，过程是这样的，points应该属于node节点xy的绝对定位，如果按照寻常的代码理解应该是直接用鼠标拖拽改变points的位置，这样就会发生node节点xy坐标默认为0的情况，Transform会出现在画布（0，0）的位置，为了解决这个问题我们将第一次鼠标点击作为xy轴初始点，后期所有拖拽点击全部新的鼠标点击减去xy轴坐标，这个时候出现了两个新的问题

### Expected behavior

1：要么出一个改变Transform背景选框调整位置的api，要么出一个自适应高度位置的api
2：自定义画出来的图像也可以通过选中放大缩小

### Platform

vue  3.2.47
x6  2.9.4
vite   4.2.0

**Comment by NewByVector** [comment]
如果要 `polyline` 节点能随着 `transfrom` 变化，需要将 `points` 属性设置成 `refPoints`，参考 [官网示例](http://x6.antv.antgroup.com/examples/node/native-node#polyline) 第一个例子。
