### ISSUE TITLE
两个节点可以重复连线，删除连线有很多层

### ISSUE THREAD

**Issue by XueMeijing** [antvis/X6#3565]
### 问题描述

两个节点可以重复连线，删除连线有很多层，按理说可以通过validateConnection 和 getOutgoingEdges判断来去掉，官方是否需要通过增加个配置来实现或者默认实现？

### 重现链接

官网demo可复现，如视频

### 重现步骤

https://user-images.githubusercontent.com/35559153/236598071-18c578d6-8c21-4685-83a2-2152e6bd6e8a.mp4

### 预期行为

两个节点应该只有一条连线

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by JamesTing** [comment]
allowMulti ：是否允许在相同的起始节点和终止之间创建多条边，默认为 true 。
https://x6.antv.antgroup.com/api/interacting/interaction#allowmulti

**Comment by XueMeijing** [comment]
> allowMulti ：是否允许在相同的起始节点和终止之间创建多条边，默认为 true 。 https://x6.antv.antgroup.com/api/interacting/interaction#allowmulti

非常感谢，我记得好像在哪见过这个配置，之前没找到。。刚才试了下可以啦
