### ISSUE TITLE
edge的edge-editor和vertices工具，有冲突

### ISSUE THREAD

**Issue by jennyxu520** [antvis/X6#3575]
### 问题描述

同时使用vertices和edge-editor工具,有冲突

必现：
1、一直单击，然后双击不出现文本编辑框

偶现：
1、双击不出现文本
2、重新编辑已存在的文本，文本内容不回显

### 重现链接

https://codesandbox.io/s/pedantic-galileo-r93r9b?file=/src/index.ts

### 重现步骤

在创建边的时候，添加内置工具vertices和edge-editor
1、单击边，一直单击
2、编辑文本框，再次双击编辑，文本消失

### 预期行为

期望结果：
1、双击边，可以出现文本编辑框；同时路径点消失
2、单击边出现路径点
3、点击空白处，清空或隐藏路径点

实际结果：
1、双击边，偶现文本编辑框，且有时点不动
2、一直单击边，后双击不出现文本框

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.9.4 ]

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/103815673/236777004-2b3273b7-20a7-4100-98d0-d363201bd006.mp4

### 补充说明（可选）

用户想在边上双击进行文本编辑，同时也想单击边可以调整路径位置，点击空白处可以清楚路径点

**Comment by JamesTing** [comment]
我也有类似的问题

**Comment by hylerrix** [comment]
@NewByVector 这个改动在 1.x 版本也遇到了，可以将 pr 也更新到 v1.x 版本中吗？
