### ISSUE TITLE
关于连接线的hover/selected状态，是否后续有相关的API支持

### ISSUE THREAD

**Issue by hexiaomin496** [antvis/X6#3576]
### 问题描述

在用户鼠标hover到节点之间的连接线时，目前连接线时没有相关的hover样式；

在用户鼠标点击到节点之间的连接线时，目前连接线没有相关的选中样式；

不知道后续是否有相关的API支持，优化用户体验。

### 重现链接

https://codesandbox.io/s/swso1x

### 重现步骤

1.进入以上CodeSandbox地址，此为antv/x6的官方示例，

2.可以对连接线进行hover/点击操作

### 预期行为

希望后期有相关API支持hover/selected样式

### 平台

- 操作系统: [macOS,]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.5.2]

**Comment by NewByVector** [comment]
可以通过修改边的 `attr` 达到你的效果。参考[官网](http://x6.antv.antgroup.com/tutorial/basic/edge#%E4%BF%AE%E6%94%B9%E8%BE%B9)。
