### ISSUE TITLE
parent and setParent not take effect

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#358]
### Expected Behavior

1. 节点的parent属性以及setParent 方法 没有效果

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
节点的parent属性  以及 setParent 方法不对外暴露？因为对外没有实质上的效果

**Comment by NewByVector** [comment]
改动影响现在设计，V2 重新设计

**Comment by bubkoo** [comment]
使用 `embed` 和 `unembed` 方法来设置嵌套关系
