### ISSUE TITLE
node和连接桩之间连线，source，target没问题，就是连接线显示不对，拖动的时候才会连到源和目标

### ISSUE THREAD

**Issue by Bigdaniel123** [antvis/X6#3582]
### Describe the bug

node和连接桩之间连线，source，target没问题，就是连接线显示不对

### Your Example Website or App

我本地项目

### Steps to Reproduce the Bug or Issue

 {
nodes: [
    {
      type: "stopValve",
      id: "fb1-1",
      position: {
        x: 80,
        y: 50,
      },
      ports: portsPositionFix(portsLFCenter, {
        left: { dx: 0, dy: 0.6, id: "fb1-1-port-1" },
        right: { dx: 1, dy: 0.6, id: "fb1-1-port-2" },
      }),
    },
    {
      type: "tee",
      id: "t1",
      angle: -90,
      position: {
        x: 180,
        y: 50,
      },
    },
    {
      type: "stopValve",
      id: "fb1-2",
      angle: 90,
      position: {
        x: 160,
        y: 110,
      },
      ports: portsPositionFix(portsLFCenter, {
        left: { dx: 0, dy: 0.5, id: "fb1-2-port-1" },
        right: { dx: 1, dy: 0.5, id: "fb1-2-port-2" },
      }),
    },
],
edges: [
    {
      id: "1",
      source: {
        cell: "fb1-1",
        port: "fb1-1-port-1",
      },
      target: "t1",
    {
      id: "2",
      // source: { x: 180, y: 60 },
      // target: { x: 180, y: 100 },
      source: "t1",
      target: {
        cell: "fb1-2",
        port: "fb1-2-port-1",
      },
    },]}

### Expected behavior

源和目标能正确连接

### Screenshots or Videos

![Uploading 微信截图_20230511153822.png…]()

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [e.g. 2.x]

**Comment by NewByVector** [comment]
和 https://github.com/antvis/X6/issues/3581 重复。
