### ISSUE TITLE
vue3+vite+@antv/x6-vue-shape打包后自定义vue节点不存在报错

### ISSUE THREAD

**Issue by mollyhappy** [antvis/X6#3583]
### 问题描述

1. 按照官方Vue 节点使用@antv/x6-vue-shape注册组件，自定义组件使用vue3setup语法糖，开发环境节点正常展示，打包后，报错Node with name '自定义节点' does not exist

### 重现链接

1

### 重现步骤

打包线上报错

### 预期行为

期望生产环境和开发环境表现一样，节点渲染正常

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- X6 版本: 2.9.7
- @antv/x6-vue-shape版本：2.0.11

### 屏幕截图或视频（可选）

![22222](https://github.com/antvis/X6/assets/30994029/2feb83e5-27ce-4411-9f7a-7037623e43e0)

**Comment by NewByVector** [comment]
之前好像遇到过，好像是 vite 配置问题，可以搜索一下相关 issue。

**Comment by mollyhappy** [comment]
按照其他的issue也没有解决，之前的配置和x6的包也不一样，没办法了

**Comment by NewByVector** [comment]
可以用 [CodeSandbox](https://codesandbox.io/dashboard) 弄一个可以复现的 demo，我们排查一下。

**Comment by mollyhappy** [comment]
多次实验重新配置了vite,项目中多个x6版本兼容性问题

**Comment by damnright** [comment]
alias: {
        vue: 'vue/dist/vue.esm-bundler.js'
      },
