### ISSUE TITLE
x6 V2版本没有找到关于x6-react-components的文档

### ISSUE THREAD

**Issue by XueMeijing** [antvis/X6#3589]
### 问题描述

x6 V2版本没有找到关于x6-react-components的文档，x6-react-components 对于2.0 版本有更新吗？ V1地址在这里 https://x6.antv.vision/zh/docs/tutorial/advanced/components

### 重现链接

无

### 重现步骤

无

### 预期行为

找到x6 v2版本关于x6-react-components的文档

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
V2 相对于 V1 只有一点更新，支持了 React 18 和 antd5，使用方式和 V1 相同，我后续会同步文档过来。
