### ISSUE TITLE
resizing配置后边框错位

### ISSUE THREAD

**Issue by cqMySong** [antvis/X6#359]
在配置中
const graph = new Graph({
  container,
  grid: true,
  resizing: {
    enabled: true,
    minWidth: 100,
    minHeight: 80,
    maxWidth: 200,
    maxHeight: 100,
    orthogonal: true,
    restricted: false,
    autoScroll: true,
    preserveAspectRatio: false
  }
})

出现外边框与节点错位

而且当在拖拉节点改变节点大小后，lable的位置没有发生更新处理

问题出现场景：
https://x6.antv.vision/zh/examples/shape/nodes#rect
配置的resizing

**Comment by NewByVector** [comment]
新版本没有上述问题

**Comment by Gilbert5210** [comment]
@NewByVector 
在vue节点上，出现了改变节点大小以后。边框线没有跟随变化的问题
resizing: true
已经是最新版本的了。

现象复现地址： https://codesandbox.io/s/delicate-dawn-mqthu?file=/src/components/HelloWorld.vue

步骤： 

改变边框的颜色，再进行节点大小的改变
就会出现边框的大小没有跟随变化
![image](https://user-images.githubusercontent.com/17983736/109092836-46931500-7752-11eb-9315-484fa2e68228.png)

**Comment by NewByVector** [comment]
这里是因为你修改边框颜色用了 updateAttrs, 它的实现是一个浅层的赋值：
![image](https://user-images.githubusercontent.com/20186737/109243458-ec5c8780-7817-11eb-9c31-501839bcfb0e.png)
这样导致 body 的 refWidth 和 refHeight 属性被移除了。
可以这样修改： node.attr('body/stroke', '#000')
