### ISSUE TITLE
自定义注册节点在safari浏览器显示，样式乱套

### ISSUE THREAD

**Issue by jennyxu520** [antvis/X6#3590]
### 问题描述

1、用的vuetify UI组件注册了一个图片节点
2、在谷歌浏览器能正常显示，但是在safari浏览器样式搓掉
3、小地图样式同样

### 重现链接

无

### 重现步骤

1、用的vuetify UI组件注册了一个图片节点
2、在谷歌浏览器能正常显示，但是在safari浏览器样式搓掉

### 预期行为

在safari浏览器能正常显示节点样式和小地图样式

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.9.7 ]

### 屏幕截图或视频（可选）

![1](https://github.com/antvis/X6/assets/103815673/ad04bdc8-46cc-4627-a1d8-072c368e89ea)

**Comment by NewByVector** [comment]
是不是[这个](https://www.yuque.com/antv/x6/be9pfx#bQIG5)问题。

**Comment by NewByVector** [comment]
上面回复有没有解决你的问题呢？如果还有问题，请重新提一个新的 issue，并且提供一个可以复现的链接。
