### ISSUE TITLE
选择框层级问题

### ISSUE THREAD

**Issue by lloydzhou** [antvis/X6#3594]
### Describe the bug

1. 节点按添加顺序有zIndex
2. 选择框selection整个在svg上层
3. 所以会出现一种情况，选择的节点位于某个节点下层，但是选中之后selection的`nodeSelectionBox`位于最上层。
4. 这个时候会出现层级交叉的情况

### Your Example Website or App

https://x6.antv.antgroup.com/tutorial/plugins/selection

### Steps to Reproduce the Bug or Issue

1. 打开官方文档示例
2. 将`Hello`节点和`Rect`节点拖动到有部分重叠
3. 此时选择处于底层的`Rect`节点
4. 这个时候，`Rect`节点处于`Hello`节点后面，但是和`Rect`节点应该是一体的`nodeSelectionBox`却位于`Hello`节点上层

### Expected behavior

N/a

### Screenshots or Videos

![image](https://github.com/antvis/X6/assets/1826685/bdc3b4ba-282f-4648-b9b3-80e6b238d140)

### Platform

- OS: [Linux]
- Browser: [Chrome]
- Version: [e.g. 91.1]

**Comment by lloydzhou** [comment]
https://codesandbox.io/s/html-shape-for-x6-0y71sv?file=/html.ts:2989-2995

可以考虑参考 `x6-html-shape`这个包的逻辑，在选中的时候，将当前节点的zIndex临时设置到最顶层？或者调用toFront将选择的节点放到最顶层？

**Comment by NewByVector** [comment]
我理解上面的现象是正常的，选择框是标记该节点被选中的状态，应该是显示在最上层，它和节点是否在最上层没有关系，这样用户很明显发现被选中的元素，特别是一个元素被完全覆盖在另一个节点内部的场景中会比较实用。也可以参考 drawio、excalidraw 的交互。

![image](https://github.com/antvis/X6/assets/20186737/7bd3507a-cfdc-4047-8a69-a479c54028ff)

**Comment by lloydzhou** [comment]
如果与业界其他产品的交互一致，那还是保持原样吧
