### ISSUE TITLE
选择框超出画布

### ISSUE THREAD

**Issue by lloydzhou** [antvis/X6#3595]
### Describe the bug

选择框超出画布

### Your Example Website or App

https://x6.antv.antgroup.com/zh/examples/showcase/practices/#flowchart

### Steps to Reproduce the Bug or Issue

1. 使用官方demo创建节点
2. 选中一个节点，出现边框上的操作按钮等
3. 拖动选中节点到画布边缘
4. 可以看到，节点不能超出画布，但是节点工具会超出画布，

### Expected behavior

n/a

### Screenshots or Videos

![image](https://github.com/antvis/X6/assets/1826685/706871b9-a0da-49ba-978f-2b2fc543fa98)

### Platform

- OS: [Linux]
- Browser: [Chrome]
- Version: [e.g. 91.1]

**Comment by lloydzhou** [comment]
selection和transform插件的框，都会超出范围

![image](https://github.com/antvis/X6/assets/1826685/cbaf093c-2fa4-408d-8927-3f613755026f)

**Comment by NewByVector** [comment]
有什么好的交互建议吗？

**Comment by lloydzhou** [comment]
1. 这里节点被边缘遮挡的情况是合理的。
2. 所以，上层的widget应该也有一个一样的边缘，超过之后应该也被遮挡才合理

实现方式只要给`x6-graph`这个class设置`overflow: hidden`应该就可以了

![image](https://github.com/antvis/X6/assets/1826685/bcc30c6f-3452-4ce5-8898-97fdbcfeb8c3)

**Comment by NewByVector** [comment]
来个 PR？
