### ISSUE TITLE
【BUG】【严重问题】异步渲染的画布，使用工具调整edge的起点并设置label后，先撤销再重做，代码报错页面卡死

### ISSUE THREAD

**Issue by linkun-wang** [antvis/X6#3601]
### Describe the bug

【1.32.8】异步渲染的画布，使用工具调整edge的起点并设置label后，先撤销再重做，代码报错页面卡死

### Your Example Website or App

https://codesandbox.io/s/lian-xian-qi-dian-zhong-dian-gong-ju-she-zhi-biao-qian-chong-zuo-li-shi-ji-lu-bao-cuo-mnthtt?file=/src/app.tsx

### Steps to Reproduce the Bug or Issue

1. 进入页面，悬浮到edge上，拖动起点到另一个节点
2. 点击画布下方【撤销】按钮，使连线恢复到初始状态
3. 点击画布下方【重做】按钮
4. 出现报错
这个例子是我们当前真实的业务场景：画布是异步渲染（async:true），页面上的edge可以调整起点/终点，调整edge的起点/终点后edge上的label会更新，然后又提供了撤销和重做功能，当用户调整edge的起点导致label更新后，撤销再重做就会报错，此问题必现。

### Expected behavior

异步渲染的画布，使用工具调整edge的起点并设置label后，不管如何撤销/重做，不要报错，不要影响正常功能的使用

### Screenshots or Videos

![撤销重做后报错](https://github.com/antvis/X6/assets/33945539/ac2d0651-eff9-4d71-8476-ae58d19f274d)

### Platform

- OS: Windows
- Browser: Chrome 113.0.5672.127
- X6 Version: 1.32.8

**Comment by NewByVector** [comment]
请更新到 x6@1.34.14。
