### ISSUE TITLE
官方demo编辑就会报错，昨天之前使用还正常

### ISSUE THREAD

**Issue by oldturkey** [antvis/X6#3603]
### Describe the bug

![屏幕录制2023-05-19 10 26 15](https://github.com/antvis/X6/assets/23737028/1c0fafb3-1ddd-4f46-af70-d71ce359b645)

### Your Example Website or App

chrome

### Steps to Reproduce the Bug or Issue

打开官网demo
拖拽一个节点
点击操作， 见视频

### Expected behavior

可以正常编辑

### Platform

macOS

**Comment by NewByVector** [comment]
已经修复。
https://github.com/antvis/dumi-theme-antv/pull/229
https://github.com/antvis/dumi-theme-antv/issues/230
