### ISSUE TITLE
连接桩 zIndex 无效

### ISSUE THREAD

**Issue by zhangyucha0** [antvis/X6#3604]
### Describe the bug

连接桩zIndex设置后未生效

### Your Example Website or App

https://codesandbox.io/s/gallant-lewin-n0kdzg?file=/App.tsx

### Steps to Reproduce the Bug or Issue

目前已知，连接桩拖出新edge后，由于edge的层级高于port，会导致port被挡住一部分区域。再次拖出新edge时，此区域不可用，连接桩可操作区域变小，难以选中并拖出新edge。

### Expected behavior

希望在保持各Cell默认拖入层级不变的情况下，只改变port的层级，使其始终处于edge上层，解决以上问题。

### Screenshots or Videos

![screenshot](https://github.com/antvis/X6/assets/24715477/71636789-758a-4833-af11-f676c47895d2)

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: ["@antv/x6": "^2.9.7"]

**Comment by NewByVector** [comment]
port 是有 zIndex，但是 port 的 zIndex 是代表它在节点内部的层级，它是无法高于节点层级的。你的场景中只要将连线的 zIndex 设置小一点（比如 -1），这样就不会有问题了。

**Comment by lwstudy** [comment]
![image](https://github.com/antvis/X6/assets/58960791/86f352d5-2988-412a-aaec-6879747e4369)
我通过zIndex设置，无法让node在除了绿色以外的区域（比如text和port区域【这两个层级在node的rect层级之上？】）进行magnet连线（port覆盖在node之上）。
