### ISSUE TITLE
Add English version of the -  https://x6.antv.antgroup.com/ 

### ISSUE THREAD

**Issue by nikbabchenko** [antvis/X6#3605]
### Describe the feature you'd like to request

Would be great to have the official website also in English in order to have larger community and users. 

It scares developers and contributors to use the library because of absence of the docs in English.

### Describe the solution you'd like

add English locale to the https://x6.antv.antgroup.com/

### Describe alternatives you've considered

Other libraries mostly have the English language support. Even have less features.

**Comment by NewByVector** [comment]
We don't have the energy to do that yet, and chatgpt might be able to help 🧐.

**Comment by alexturt** [comment]
Check out [https://x6.antv.vision/en](x6.antv.vision)

**Comment by nikbabchenko** [comment]
@alexturt , @NewByVector, 
Translation from Google Translate works really well.
If I could also assist on translation, please guide me. 

Google Translate works really well. The point to have an English version - just to improve community support. 

The library itself is really great and comments inside the source code are in English.

It's seems like the Chinese could scare dev's from choosing this lib against 'FlowChart.js' or similar one, even this one has much more features and more modern.

**Comment by NewByVector** [comment]
I'm really sorry to answer your message so long. We really don't have the energy to translate this work now. If you are willing to help translate this project, that would be great. The translation method is: create a new md document and name it xx.en.md, and then translate its contents.

**Comment by nanfb** [comment]
> @alexturt , @NewByVector, Translation from Google Translate works really well. If I could also assist on translation, please guide me.
> 
> Google Translate works really well. The point to have an English version - just to improve community support.
> 
> The library itself is really great and comments inside the source code are in English.
> 
> It's seems like the Chinese could scare dev's from choosing this lib against 'FlowChart.js' or similar one, even your lib has much more features and more modern.

It's seems like the Chinese could scare dev's from choosing this lib against 'FlowChart.js' or similar one, even your lib has much more features and more modern.

**Comment by tmarsik42** [comment]
I use this library a lot and docs in english would be great so I won't have to use translate all the time.
I'm considering contributing with translations. Do you prefer PR per page, bulk, or it doesn't matter?

**Comment by NewByVector** [comment]
@tmarsik42 First of all thank you for the idea of pr, actually we don't care PR per page or bulk.

**Comment by v-xiao** [comment]
Could you please incorporate x6 English documents task into the AntV Open Source Contribution Plan? 
like  https://github.com/antvis/G2/issues/2353
