### ISSUE TITLE
插件Stencil，用户自定义悬浮显示拖拽元素名

### ISSUE THREAD

**Issue by lifeihub** [antvis/X6#3606]
### 功能描述

用户自定义拖拽元素后，希望可以有api或者其他方式来定义tooltip，如果是纯图片或其他无文本拖拽的类型的话，方便用户了解所拖拽元素信息。
![image](https://github.com/antvis/X6/assets/87174373/f04ce517-ca77-4e14-ac78-0efe273f6a15)
类似于这种
![image](https://github.com/antvis/X6/assets/87174373/a26e8f84-7f7d-4cec-889f-6434ce05800d)

### 期望解决方案

增加插件Stencil中tooltip更开放的拖拽元素配置项，让开发者可以配置tooltip或者类似画布事件api，比如鼠标移入移出事件，点击事件，拖动事件，可以让用户在对应的事件回调里面自定义内容。

**Comment by XueMeijing** [comment]
你自定义元素外面套个Tooltip就可以了吧
![image](https://github.com/antvis/X6/assets/35559153/33fceff6-6012-4b88-bb3a-d6d521f9715b)

**Comment by NewByVector** [comment]
有两种解决方案：
1. 如 @XueMeijing 所说，tooltip 放到节点中，不过这样的话，节点添加到画布后，任然存在 tooltip。
2. 不使用 stencil 插件，而是使用 dnd 插件来自定义实现，这样自由度更大。

**Comment by NewByVector** [comment]
上面回复有没有解决你的问题呢？如果还有问题，请重新提一个新的 issue，并且提供一个可以复现的链接。
