### ISSUE TITLE
1.x版本，toPNG 设置viewBox，生成空白图片

### ISSUE THREAD

**Issue by lhC0** [antvis/X6#3612]
### 问题描述

1.x版本，生成图片时设置viewBox，生成空白图片，删掉viewBox设置，可正常生成画布区域内所有节点的图片，只是无法指定区域；
2.x版本，设置viewBox，正常生成指定区域图片。

### 重现链接

暂无

### 重现步骤

无

### 预期行为

期望与2.x一样，可正常生成固定区域内节点的图片

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.26.1]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/X6/assets/29115820/b3e5d6c6-c9ae-4963-be57-42bb9e52e4b3)

**Comment by NewByVector** [comment]
能否提供一个可以复现的 demo？
