### ISSUE TITLE
如何实现节点文本，只修改部分字体的颜色和大小

### ISSUE THREAD

**Issue by TalentJY** [antvis/X6#3614]
### 问题描述

如题，之前看到draw.io，用的mxgraph是可以实现的。

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2 ... ]

**Comment by NewByVector** [comment]
看了下，drawio 是这样实现的：
![image](https://github.com/antvis/X6/assets/20186737/e17ecc56-1289-4164-83a5-87cca6cc3832)
如果要实现这个功能，可以考虑自定义节点。

**Comment by TalentJY** [comment]
> 看了下，drawio 是这样实现的： ![image](https://user-images.githubusercontent.com/20186737/240566759-e17ecc56-1289-4164-83a5-87cca6cc3832.png) 如果要实现这个功能，可以考虑自定义节点。
自定义节点 只能定死吧，能做到事实修改吗，在node-editor中 选中部分文字 然后修改大小颜色
