### ISSUE TITLE
node-editor 不支持dominant-baseline；'text-anchor': 'middle', 调整位置

### ISSUE THREAD

**Issue by TalentJY** [antvis/X6#3618]
https://github.com/antvis/X6/assets/82206115/a334254f-2a0c-47a5-a1dc-20b13f725506

### 问题描述

如题，目前只用x，y固定偏移量调整位置，导致我的文本内容长度不一样时，双击编辑的时候  不能完全覆盖原来的位置。

### 重现链接

暂无

### 重现步骤

                node.addTools({
                    name: "node-editor",

                    args: {
                        x: 0,
                        y: size,
                        attrs: {
                            fontFamily: '微软雅黑',
                            fontSize: 16,
                            'text-anchor': 'middle',
                            'dominant-baseline': 'middle'
                        },
                        'text-anchor': 'middle',
                        'dominant-baseline': 'middle',

                        getText: 'label/text',
                        setText: 'label/text'
                    }
                });

### 预期行为

双击编辑能完全覆盖原来的位置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2 ... ]

**Comment by NewByVector** [comment]
能否提供一个可以复现的 demo？

**Comment by TalentJY** [comment]
> 能否提供一个可以复现的 demo？

复现有些难写 我贴了个视频。 因为我是在定义节点里给text加了dominant-baseline；'text-anchor': 'middle'，让文本能相对图像居中

**Comment by NewByVector** [comment]
可以基于这个 [模板](https://codesandbox.io/s/mo-ban-55i8dp) 写一个例子。

**Comment by TalentJY** [comment]
> 可以基于这个 [模板](https://codesandbox.io/s/mo-ban-55i8dp) 写一个例子。

https://codesandbox.io/s/mo-ban-forked-6jk90j?file=/src/App.tsx代码差不多是这样，但是装不了最新的x6
