### ISSUE TITLE
使用定制交互行为interacting时，所有api均可生效，唯独nodeMovable不生效

### ISSUE THREAD

**Issue by dinghaining** [antvis/X6#3619]
### 问题描述

使用定制交互行为interacting时，所有api均可生效，唯独nodeMovable不生效
const graph = new Graph({
  container: document.getElementById('container'),
  grid: true,
   interacting: function (cellView: CellView) {
      return { 
        nodeMovable: false,
        vertexAddable: false,
        arrowheadMovable: false,
        edgeMovable: false,
      }
  },
})

### 重现链接

无，x6版本2.11.1

### 重现步骤

希望禁止所有节点移动，但api无法生效

### 预期行为

希望禁止所有节点移动

### 平台

x6版本2.11.1

**Comment by liuhuanlearn** [comment]
我这边没问题，可以给个实现看下吗，如果交互都为false的话不传函数直接给interacting: false试试呢

**Comment by NewByVector** [comment]
我本地也试了一下，`nodeMovable` 是生效的，可以根据这个[模板](https://codesandbox.io/s/mo-ban-55i8dp)给出一个可以复现的 demo，并重新提一个 issue。

**Comment by dinghaining** [comment]
[tt.zip](https://github.com/antvis/X6/files/11597443/tt.zip)
@NewByVector @liuhuanlearn
