### ISSUE TITLE
how to support lower version browsers

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#362]
### Expected Behavior

在一些版本比较低的浏览器中，有极少的 js 方法不被支持，常见的
1. chrome51 之前不支持 NodeList.prototype.forEach（解决方案：[Polyfill](https://developer.mozilla.org/zh-CN/docs/Web/API/NodeList/forEach))
2. chrome54 之前不支持ParentNode.append (解决方案：[Polyfill](https://developer.mozilla.org/zh-CN/docs/Web/API/ParentNode/append))

遇到js方法不支持的情况，先去[MDN](https://developer.mozilla.org/zh-CN/)查找浏览器兼容情况以及polyfill。相信会找到解决方案。如果遇到不能解决的兼容性问题，欢迎大家在下面评论，我们会尽快提供解决方案！

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
类似这种兼容性问题直接按照指引在我们的仓库中兼容掉。
