### ISSUE TITLE
vue3按照官网给的例子，使用x6-vue-shape渲染节点，报错，使用的都是模板的代码

### ISSUE THREAD

**Issue by liuxiaokai666** [antvis/X6#3624]
### Describe the bug

报这个错：：Uncaught TypeError: Cannot destructure property 'component' of 'shapeMaps[node.shape]' as it is undefined.，不知道怎么解决使用

### Your Example Website or App

import Count from 'Count.vue'  const graph = new Graph({   container: document.getElementById("app"),   width: 600,   height: 400,   grid: true, });  Graph.registerNode("my-count", {   inherit: "vue-shape",   x: 200,   y: 150,   width: 150,   height: 100,   component: {     template: `<Count />`,     components: {       Count,     },   }, });  graph.addNode({   id: "1",   shape: "my-count",   x: 400,   y: 150,   width: 150,   height: 100,   data: {     num: 0,   }, });

### Steps to Reproduce the Bug or Issue

报这个错：：Uncaught TypeError: Cannot destructure property 'component' of 'shapeMaps[node.shape]' as it is undefined.

### Expected behavior

初始化的时候，就直接无法初始化

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
x6使用的是2.11.1的版本
x6-vue-shape使用的是2.0.11版本

**Comment by ainuo5213** [comment]
我也是这个问题，按照官方文档写的。但是就是报错

**Comment by lloydzhou** [comment]
https://x6.antv.antgroup.com/tutorial/intermediate/vue
看一下，是不是按照2.x的文档写的？

**Comment by lily97** [comment]
import { register, getTeleport } from '@antv/x6-vue-shape'

  register({
    shape: 'custom-vue-node',
    width: 100,
    height: 100,
    component: ProgressNode,
  })
  我的也是同样的问题，就是注册节点没成功，所以拖拽的时候也报错了，使用这个写法就能解决了！！！！！！
