### ISSUE TITLE
request the background image multiple times when panning enabled

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#363]
### Current Behavior

![image](https://user-images.githubusercontent.com/20186737/100886163-7386b180-34ee-11eb-8063-c1cd0dee52f5.png)

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
尝试将图片缓存到Image对象中吧

**Comment by bubkoo** [comment]
移动画布时，画布的网格会重新计算，所有请求都是 base64 请求，不影响。
