### ISSUE TITLE
对Node 节点中的 text 增加 title 划过功能

### ISSUE THREAD

**Issue by wellsmitch** [antvis/X6#3631]
### 功能描述

          attrs: {
              body: {
                  fill: "#f0f"
              },
              label: {
                  title: "我是划过的title",
                  textWrap: {
                      text: `qweq
                  asdaaaaaaaaaaa
                  ddd
                  `,
                      ellipsis: true,
                     title: "或者我是划过的title",
                      breakWord: false, 
                  }
              }
          },

### 期望解决方案

期望增加字段   rect.attr('body/title', 'Description of the rectangle')  并不能达到期望效果

<text font-size="14" fill="#000000" text-anchor="middle" font-family="Arial, helvetica, sans-serif" text="sss" transform="matrix(1,0,0,1,100,20)" xml:space="preserve">
    <tspan dy="-0.2em" class="v-line">qweq</tspan>
    <tspan dy="1em" x="0" class="v-line"> 是我文本…</tspan>
    <title>我是title</title>
</text>

类似这种结构

**Comment by NewByVector** [comment]
你是要实现能显示文本 title 吗？能详细描述一下吗？

**Comment by jk199548** [comment]
> 你是要实现能显示文本 title 吗？能详细描述一下吗？
