### ISSUE TITLE
当进行缩放 graph.options.width 被影响

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/X6#3633]
### 问题描述

graph.options.width 正常设置的 是 1920
当执行 graph.scale(1.2) 的时候, 发现获取的 graph.options.width * 1.2 的数, 但是 由于 这个width 跟height 是 有配置的地方 导致 被影响 后 显示的不准确了

### 重现链接

https://codesandbox.io/s/mystifying-currying-3oijbg?file=/index.ts

### 重现步骤

需要加上 Scroller 才可以
正常不加 是没有问题的

### 预期行为

展示的 还是 正常 所设置的 width 跟height

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 2.11.1

**Comment by NewByVector** [comment]
在 scroller 模式下，画布被重新 resize,所以出现你上述情况。但是我理解这个不是问题，options.width 就是画布真正宽度。

**Comment by JoeABCDEF** [comment]
> 在 scroller 模式下，画布被重新 resize,所以出现你上述情况。但是我理解这个不是问题，options.width 就是画布真正宽度。

@NewByVector  因为我有个画布配置页面,  有宽高配置 需要显示的正常 1:1 情况下的宽高, 现在没有 可以获取正常情况下 宽高的 配置的地方, 只能自己手动去处理展示。个人认为 缩放 宽高跟  scale 都变了 感觉没必要

**Comment by JoeABCDEF** [comment]
> @JoeABCDEF 这里获取的 width 和 height 就是画布容器的真实 dom 尺寸，你需要获取的是什么元素的尺寸。

我想要 获取 我设定画布的尺寸, 不是 dom 的实际大小; 为啥加上Scroller width height 就是 获取dom 的尺寸 没加 就 不是获取的dom尺寸来
