### ISSUE TITLE
不能在节点中使用element-plus中组件(已全局注册)Failed to resolve component: el-button

### ISSUE THREAD

**Issue by anyanyan07** [antvis/X6#3634]
### Describe the bug

在节点中使用全局组件，报错Failed to resolve component:xxx。必须重新按需导入import才可以使用。

### Your Example Website or App

2.x官方示例

### Steps to Reproduce the Bug or Issue

2.x官方示例

### Expected behavior

可以识别全局组件，不用在节点组件中再import

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lloydzhou** [comment]
如果使用vue3，请使用teleport

**Comment by anyanyan07** [comment]
解决了，vue3得使用teleport才能使用全局组件。官方文档能不能说明这一点啊

**Comment by NewByVector** [comment]
我们在[新官网](http://x6.antv.antgroup.com/tutorial/intermediate/vue)中唯一推荐的就是 teleport 使用方式。
