### ISSUE TITLE
v2.x Selection插件选择框样式与连接桩节点样式冲突

### ISSUE THREAD

**Issue by Ya2gLu** [antvis/X6#3637]
### 问题描述

Selection 选择框的层级样式与连接桩层级冲突，z-index不起作用

### 重现链接

待补充

### 重现步骤

Selection插件与连接桩样式冲突

### 预期行为

预期：鼠标移入Node节点时显示连接桩，移出时隐藏，
结果：因为Selection显示层级的问题，在选中之后鼠标移入节点后无法显示连接桩.

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: 2.x

### 屏幕截图或视频（可选）

![Peek 2023-06-01 17-23](https://github.com/antvis/X6/assets/48912522/29d0228e-edd0-4911-a7c9-6cccfb2186aa)

**Comment by XueMeijing** [comment]
给 **.x6-widget-selection-box** 加    pointer-events: none; 试试，不确定会不会有其他影响
