### ISSUE TITLE
registerHTMLComponent函数缺失

### ISSUE THREAD

**Issue by silentmissile** [antvis/X6#3638]
### Describe the bug

在官方文档中
https://antv-x6.gitee.io/zh/docs/tutorial/advanced/react

有registerHTMLComponent函数，但是现在的新版本已经丢失，提示 找不到该函数

### Your Example Website or App

https://antv-x6.gitee.io/zh/docs/tutorial/advanced/react

### Steps to Reproduce the Bug or Issue

在VScode中，输入Graph.后提示的函数清单中没有该函数registerHTMLComponent

### Expected behavior

不知道是X6更新造成的，还是文档未更新造成的，希望更新时加上

### Platform

Windows11
nodejs20
vscode1.78
X6-2.11.1

**Comment by NewByVector** [comment]
2.x 版本 HTML 节点使用方式参考[文档](http://x6.antv.antgroup.com/tutorial/intermediate/html)。

**Comment by wxwqslsdsh** [comment]
方法缺失这么大的改动，在升级2x版本的文档中为什么没有指出呢，这升级风险太大了
