### ISSUE TITLE
使用 HTML/React/Vue/Angular 渲染的文档已经落后，希望更新

### ISSUE THREAD

**Issue by silentmissile** [antvis/X6#3639]
### 功能描述

https://antv-x6.gitee.io/zh/docs/tutorial/advanced/react
这篇文档中，涉及到vue的部分，是基于vue-cli+JavaScript的

### 期望解决方案

希望能够更新到vite+typescript

**Comment by lloydzhou** [comment]
https://x6.antv.antgroup.com/

**Comment by NewByVector** [comment]
请使用最新的文档 http://x6.antv.antgroup.com/tutorial/intermediate/vue。
