### ISSUE TITLE
node:port:mousedown事件无法触发

### ISSUE THREAD

**Issue by 312681223** [antvis/X6#3644]
### 问题描述

node:port:mousedown事件无法触发

### 重现链接

暂无

### 重现步骤

    graph.on('node:port:mousedown', () => {
      console.log(1)
    })

### 预期行为

没有输出1

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
这个事件是在 2.x 版本中新增的，1.x 没有这个事件，可以使用 `node:mousedown` 事件来代替，然后判断 e.target 是否为连接桩。

**Comment by 312681223** [comment]
> 这个事件是在 2.x 版本中新增的，1.x 没有这个事件，可以使用 `node:mousedown` 事件来代替，然后判断 e.target 是否为连接桩。

我使用的x6版本就是2.11.1的，node:port:mousedown和node:port:mouseup两个事件都无法触发，node:port:click是可以触发的，是不是点击port时候的自动连线功能把这两个事件阻止掉了呢？

**Comment by NewByVector** [comment]
@312681223 是的 如果可以触发拖拽，是不会触发 port 的 `mousedown` 和 `mouseup` 事件。

**Comment by 312681223** [comment]
> @312681223 是的 如果可以触发拖拽，是不会触发 port 的 `mousedown` 和 `mouseup` 事件。

好的，那有没有办法解决这个问题呢？因为我需要监听port的mousedown事件去触发一些动作，另外我看port默认都是自带连线的功能的吧

**Comment by NewByVector** [comment]
@312681223 你的场景是什么呢？如果 port 的 `magnet` 属性为 false，不会触发连线的。

**Comment by 312681223** [comment]
> @312681223 你的场景是什么呢？如果 port 的 `magnet` 属性为 false，不会触发连线的。

我的场景是：当mousedown某一个port的时候，我需要将所有的node上的port显示出来，因为连线的时候需要看到port，其他时候不需要看到port，我看官方有一个示例是在mouseenter某一个node的时候，会把其他node的port显示出来，但这个需求满足不了我的场景，我需要port mousedown的时候再显示所有其他port

**Comment by NewByVector** [comment]
可以换个思路，在 `validateMagnet` 里面可以拿到这个时机。
```ts
const graph = new Graph({
    connecting: {
      validateMagnet({ magnet }) {
        console.log('xxx')
        return true
      }
    }
  })
```

**Comment by LiLy970307** [comment]
我给你说个办法 我的需求和你的是一样的：// 控制连接桩显示/隐藏
 graph.on("node:mouseenter", ({ e, node }) => {
    showPorts(true);
  });

  graph.on("node:mouseleave", () => {
    showPorts(false);
  });
const showPorts = (show) => {
  const container = document.getElementById("graph-container");
  const ports = container.querySelectorAll(".x6-port-body");

  for (let i = 0, len = ports.length; i < len; i += 1) {
    ports[i].style.visibility = show ? "visible" : "hidden";
  }
};  获取到所有的链接桩，当鼠标移入移出的时候控制链接桩的显示和隐藏就行

**Comment by zlecheng** [comment]
> > @312681223 你的场景是什么呢？如果 port 的 `magnet` 属性为 false，不会触发连线的。
> 
> 我的场景是：当mousedown某一个port的时候，我需要将所有的node上的port显示出来，因为连线的时候需要看到port，其他时候不需要看到port，我看官方有一个示例是在mouseenter某一个node的时候，会把其他node的port显示出来，但这个需求满足不了我的场景，我需要port mousedown的时候再显示所有其他port

大佬最后是咋解决的？
