### ISSUE TITLE
能够设置preserveAspectRatio的方法

### ISSUE THREAD

**Issue by SunYuanOnly** [antvis/X6#3646]
### Describe the feature you'd like to request

有能够设置preserveAspectRatio的方法吗

### Describe the solution you'd like

这边有个需要在调整节点大小时，希望按下shift键盘，能够设置preserveAspectRatio为按比例缩放

### Describe alternatives you've considered

看示例是需要先销毁画布，不想销毁画布，再重新渲染

### Screenshots or Videos

![image](https://github.com/antvis/X6/assets/16498201/c04dda3a-cdfd-4ae8-8174-91ac1e7dfa02)

**Comment by damnright** [comment]
preserveAspectRatio放在节点data里  去更新节点data即可
graph resizing配置：
preserveAspectRatio: (node)=>{
        return !!node.getData()?.preserveAspectRatio
      },

**Comment by SunYuanOnly** [comment]
> preserveAspectRatio放在节点data里 去更新节点data即可 graph resizing配置： preserveAspectRatio: (node)=>{ return !!node.getData()?.preserveAspectRatio },

明白了，谢谢
