### ISSUE TITLE
在使用vertices和segments工具时，无法框选edge，使用stopPropagation: true后，删除边，并没有删除小工具

### ISSUE THREAD

**Issue by SunYuanOnly** [antvis/X6#3649]
### Describe the bug

- vertices和segments和框选无法一起使用。不能选中edge。
- 使用stopPropagation: false后，无法将vertices，segments，一起删除。
- ## 
```
cell.addTools([
          {
            name: 'vertices',
            args: {
              stopPropagation: false
            }
          },
          {
            name: 'segments',
            args: {
              stopPropagation: false
            }
          }
        ])
```
- ## 

```
 new Selection({
          enabled: true,
          multiple: true,
          rubberband: true,
          movable: true,
          showEdgeSelectionBox: true,
          showNodeSelectionBox: true
        })
```

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

1. 使用cell.addTools新增vertices，segments工具后，开启框选，无法选中edge。
2. 增加`stopPropagation: false`，开启冒泡事件，可以选中edge
3. 删除edge后，vertices和segments还是存在

### Expected behavior

删除edge后，工具vertices和segments一起删除

### Screenshots or Videos

![image](https://github.com/antvis/X6/assets/16498201/faae9a20-2853-4111-a892-061165fafa5d)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by light-years-run** [comment]
我也遇到了同样问题，请问你解决了吗

**Comment by light-years-run** [comment]
> ### Describe the bug
> * vertices和segments和框选无法一起使用。不能选中edge。
> * 使用stopPropagation: false后，无法将vertices，segments，一起删除。
> * 
> 
> ```
> cell.addTools([
>           {
>             name: 'vertices',
>             args: {
>               stopPropagation: false
>             }
>           },
>           {
>             name: 'segments',
>             args: {
>               stopPropagation: false
>             }
>           }
>         ])
> ```
> 
> * 
> 
> ```
>  new Selection({
>           enabled: true,
>           multiple: true,
>           rubberband: true,
>           movable: true,
>           showEdgeSelectionBox: true,
>           showNodeSelectionBox: true
>         })
> ```
> 
> ### Your Example Website or App
> 
> ### Steps to Reproduce the Bug or Issue
> 1. 使用cell.addTools新增vertices，segments工具后，开启框选，无法选中edge。
> 2. 增加`stopPropagation: false`，开启冒泡事件，可以选中edge
> 3. 删除edge后，vertices和segments还是存在
> 
> ### Expected behavior
> 删除edge后，工具vertices和segments一起删除
> 
> ### Screenshots or Videos
> ![image](https://user-images.githubusercontent.com/16498201/243343185-faae9a20-2853-4111-a892-061165fafa5d.png)
> 
> ### Platform
> * OS: [e.g. macOS, Windows, Linux]
> * Browser: [e.g. Chrome, Safari, Firefox]
> * Version: [e.g. 91.1]
> 
> ### Additional context
> _No response_

我也遇到了同样问题，请问你解决了吗

**Comment by SunYuanOnly** [comment]
> > ### Describe the bug
> > 
> > * vertices和segments和框选无法一起使用。不能选中edge。
> > * 使用stopPropagation: false后，无法将vertices，segments，一起删除。
> > 
> > 
> > ```
> > cell.addTools([
> >           {
> >             name: 'vertices',
> >             args: {
> >               stopPropagation: false
> >             }
> >           },
> >           {
> >             name: 'segments',
> >             args: {
> >               stopPropagation: false
> >             }
> >           }
> >         ])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 
> > 
> > ```
> >  new Selection({
> >           enabled: true,
> >           multiple: true,
> >           rubberband: true,
> >           movable: true,
> >           showEdgeSelectionBox: true,
> >           showNodeSelectionBox: true
> >         })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Your Example Website or App
> > ### Steps to Reproduce the Bug or Issue
> > 
> > 1. 使用cell.addTools新增vertices，segments工具后，开启框选，无法选中edge。
> > 2. 增加`stopPropagation: false`，开启冒泡事件，可以选中edge
> > 3. 删除edge后，vertices和segments还是存在
> > 
> > ### Expected behavior
> > 删除edge后，工具vertices和segments一起删除
> > ### Screenshots or Videos
> > ![image](https://user-images.githubusercontent.com/16498201/243343185-faae9a20-2853-4111-a892-061165fafa5d.png)
> > ### Platform
> > 
> > * OS: [e.g. macOS, Windows, Linux]
> > * Browser: [e.g. Chrome, Safari, Firefox]
> > * Version: [e.g. 91.1]
> > 
> > ### Additional context
> > _No response_
> 
> 我也遇到了同样问题，请问你解决了吗

我的问题是把graph connecting的createEdge方法写在另一个公用类里去引用导致的。
