### ISSUE TITLE
x6 v2 文档搜索功能异常

### ISSUE THREAD

**Issue by qiufeihong2018** [antvis/X6#3650]
### 问题描述

<img width="1114" alt="image" src="https://github.com/antvis/X6/assets/36500514/914c3b7e-14ce-4b15-b5bb-b60a13397c88">

### 重现链接

https://x6.antv.antgroup.com/tutorial/update

### 重现步骤

打开https://x6.antv.antgroup.com/tutorial/update
在搜索框中输入关键词
点击搜索、回车搜索无效

### 预期行为

支持搜索

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- X6 版本: [2]

**Comment by NewByVector** [comment]
已经修复。
