### ISSUE TITLE
Chrome怎么安装了AntV X6 Dev Tool，重启没有这个标签页

### ISSUE THREAD

**Issue by qiufeihong2018** [antvis/X6#3654]
### 问题描述

<img width="1677" alt="image" src="https://github.com/antvis/X6/assets/36500514/49320389-a04e-4b3a-94f3-7b2b0f0ec35e">

### 重现链接

暂无

### 重现步骤

1. 开启AntV X6 Dev Tool
2. 打开开发者模式
3. 没有看到AntV X6 Dev Tool

### 预期行为

希望可以使用上AntV X6 Dev Tool

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome 版本 114.0.5735.90（正式版本） (x86_64)
- X6 版本: 1

**Comment by 171h** [comment]
+1

**Comment by NewByVector** [comment]
@lloydzhou 帮忙看下这个开发工具问题呀。

**Comment by lloydzhou** [comment]
@qiufeihong2018 参考前面回答，需要在将x6的graph对象放到　`window.__x6_instances__` 数组内部

**Comment by qiufeihong2018** [comment]
嗯嗯，graph放进window里就有了，感谢

**Comment by jackieyoho** [comment]
<img width="626" alt="image" src="https://github.com/antvis/X6/assets/26887980/132bd5a2-8344-4daf-b73a-820c4bf412a6">
<img width="703" alt="image" src="https://github.com/antvis/X6/assets/26887980/de7a40e0-f222-4f74-90b4-3cffd6e7e776">
为什么还是空白
