### ISSUE TITLE
https://github.com/antvis/X6/issues/2385#issue-1310745144  这个manhattan路由 出现不理想路径的问题，请问有修复吗？

### ISSUE THREAD

**Issue by 2193531059** [antvis/X6#3657]
### Describe the bug

https://github.com/antvis/X6/issues/2385#issue-1310745144  这个manhattan路由 出现不理想路径的问题，请问有修复吗？

### Your Example Website or App

https://github.com/antvis/X6/issues/2385#issue-1310745144  这个manhattan路由 出现不理想路径的问题，请问有修复吗？

### Steps to Reproduce the Bug or Issue

https://github.com/antvis/X6/issues/2385#issue-1310745144  这个manhattan路由 出现不理想路径的问题，请问有修复吗？

### Expected behavior

https://github.com/antvis/X6/issues/2385#issue-1310745144  这个manhattan路由 出现不理想路径的问题，请问有修复吗？

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
https://github.com/antvis/X6/issues/2385#issue-1310745144  这个manhattan路由 出现不理想路径的问题，请问有修复吗？

**Comment by NewByVector** [comment]
提供一个复现链接呢？

**Comment by 2193531059** [comment]
https://codesandbox.io/s/unruffled-edison-1m9ndx?file=/src/components/HelloWorld.vue  这个是具体的实现

**Comment by NewByVector** [comment]
确实两者一起使用会有问题。

**Comment by 2193531059** [comment]
@NewByVector 这个导致这个现象的具体原因大概是什么？这个场景后续会排期修复吗？

**Comment by NewByVector** [comment]
@2193531059 manhattan 算法避障只考虑了节点，不会考虑边的影响，如果计算边，那么肯定会有性能问题，我们思考一下怎么处理这种场景，暂时还没有好的思路哈。

**Comment by NewByVector** [comment]
和 https://github.com/antvis/X6/issues/3660 问题重复。
