### ISSUE TITLE
关于X6的几点建议

### ISSUE THREAD

**Issue by wangzhe90100** [antvis/X6#366]
1、功能方面，希望能给Cell加一个可编辑的属性，开启属性后，让label可以编辑。
2、文档方面，控件的方法调用希望做一个更为全面的文档，加入API手册中。现在查找可使用方法，教程中有一部分，API中有一部分，还有的只在DEMO中体现，使用起来很困难。
3、请增加一下原生JS调用的文档，通过原生的调用也能实现与VUE等的交互。DEMO中很多例子，都使用了内部调用，原生调用的时候经常不过全靠猜

**Comment by NewByVector** [comment]
第一点我们有计划在开发，第二个问题也在优化中。第三个原生调用指的是？

**Comment by vicalloy** [comment]
第3点原生JS调用，应当是指不使用React的的情况下作为一个普通JS库使用。

**Comment by jave-joe** [comment]
vue版什么时候出呢

**Comment by zhangwenwu** [comment]
> vue版什么时候出呢

+1

**Comment by panzirongg** [comment]
兼容ie问题

**Comment by NewByVector** [comment]
> 兼容ie问题

我们支持的版本是 IE11

**Comment by NewByVector** [comment]
> vue版什么时候出呢

x6-vue-component 已经在启动中

**Comment by wh12345** [comment]
vue组件啥时候出啊，老大哥们
