### ISSUE TITLE
为什么创建的节点不能通过边Edge手动连接?

### ISSUE THREAD

**Issue by 18839965530** [antvis/X6#3661]
### 问题描述

我往画布中添加了两个节点，但是不能手动连接这两个节点，我看connecting.allowNode的配置项默认是true啊，必须设置连接桩才能手动连接吗？

### 重现链接

https://codesandbox.io/embed/sharp-mopsa-92hhxd?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

1.创建两个node
2.无法手动连接

### 预期行为

预期可以手动连接

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
具备 `magnet: true` 属性的元素才能手动连线。你可以这样实现：
```ts
graph.addNode({
  xxx,
  attrs: {
    body: { magnet: true }
  }
})
```
