### ISSUE TITLE
@antv/x6-react-shape 2.x react 16支持

### ISSUE THREAD

**Issue by Ryuurock** [antvis/X6#3666]
### 功能描述

很多老项目还在react 16 或者17，期望能在这些版本上使用 @antv/x6-react-shape 2.x

### 期望解决方案

很多老项目还在react 16 或者17，期望能在这些版本上使用 @antv/x6-react-shape 2.x

**Comment by NewByVector** [comment]
参考[常见问题](https://www.yuque.com/antv/x6/tox1ukbz5cw57qfy#bQIG5)。

**Comment by lloydzhou** [comment]
@Ryuurock 
可以看看这个issue： https://github.com/antvis/X6/issues/3487
我抽象了一个第三方的shape，这个shape同时支持不同的react版本，也支持portal 模式进行渲染

https://github.com/lloydzhou/x6-html-shape
![image](https://github.com/antvis/X6/assets/1826685/c9c184ca-7a38-4f27-92c3-9381b812c07c)
