### ISSUE TITLE
x6的V2版本，开启可视区域渲染，如果节点消失在可视区域外面，那么节点和连接器就会隐藏

### ISSUE THREAD

**Issue by qiufeihong2018** [antvis/X6#3668]
### 问题描述

x6的V2版本，开启可视区域渲染，如果节点消失在可视区域外面，那么节点和连接器就会隐藏

### 重现链接

https://codesandbox.io/s/x6de-v2ban-ben-de-si-wei-dao-tu-de-demo-jthvgq?file=/index.ts

### 重现步骤

在「分支主题1」多次tab下，生成子节点，将「中心主题」和「分支主题2」节点挤到可视区域外部，这「中心主题」和「分支主题2」两个节点和连接器就会消失。

### 预期行为

希望可以和不开启可视区域渲染一样

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 2.11.1

### 屏幕截图或视频（可选）

![067FDDAA-018A-48D7-8048-B21E9D364582_1_102_o](https://github.com/antvis/X6/assets/36500514/6b014d27-5a3e-45c8-9471-1e0ce48b1bc5)

<img width="1661" alt="image" src="https://github.com/antvis/X6/assets/36500514/a2eae102-c4aa-4405-8194-8ec9c0d6fda0">

<img width="1672" alt="image" src="https://github.com/antvis/X6/assets/36500514/19989e99-f70f-4218-b2c6-c3503a0d9e3b">

**Comment by qiufeihong2018** [comment]
思考并讨论后，觉得适合的方案是：更改源码，修复virtual的问题，将连接器完全呈现。仅呈现可视区域内的节点，不进行渲染不可视区域内的节点，这将提高性能并解决问题。

**Comment by qiufeihong2018** [comment]
@NewByVector 有没有好的方案？我可以帮忙贡献代码

**Comment by NewByVector** [comment]
@qiufeihong2018 不好意思，这么晚才来看这个问题，我打算增加一个新的配置来控制是否显示这种连线(起点或者终点不在可视区域内)。
