### ISSUE TITLE
连续进行history.undo()时会报错

### ISSUE THREAD

**Issue by zhangjiaqing** [antvis/X6#367]
### Expected Behavior

https://codesandbox.io/s/restless-paper-w5upb?file=/src/app.tsx

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@zhangjiaqing  已经修复，使用最新版试试。
