### ISSUE TITLE
使用调整边起点/终点的工具，在拖拽中无法让链接桩一直显示

### ISSUE THREAD

**Issue by oyal** [antvis/X6#3673]
### 问题描述

在拖出新边的过程中，链接桩可以一直显示
![image](https://github.com/antvis/X6/assets/88022434/13e18022-8fc6-4d1a-9f2d-13f5702c0832)

修改起点/终点的过程中，链接桩无法显示
![image](https://github.com/antvis/X6/assets/88022434/cdca9be3-87ed-4bed-ae21-0c78ad696aa9)

### 重现链接

https://x6.antv.antgroup.com/zh/examples/showcase/practices/#flowchart

### 重现步骤

[官网示例](https://x6.antv.antgroup.com/zh/examples/showcase/practices#flowchart)加上这段代码：

```js
graph.on('edge:mouseenter', ({ cell }) => {
  cell.addTools([
    {
      name: 'source-arrowhead'
    },
    {
      name: 'target-arrowhead',
      args: {
        attrs: {
          fill: 'red'
        }
      }
    }
  ])
})

graph.on('edge:mouseleave', ({ cell }) => {
  cell.removeTools()
})
```

### 预期行为

在修改起点或者终点时，链接桩始终显示

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- X6 版本: 2.11.1

**Comment by zzyyu** [comment]
可以配合connecting、highlighting属性
代码我贴下面了，样式你还需要再调整下
```
    highlight: true,
    //不允许连接到节点
    allowNode: false,
```
```
    magnetAvailable: {
      name: 'stroke',
      args: {
        attrs: {
          stroke: '#5F95FF',
        },
      },
    },
```
![image](https://github.com/antvis/X6/assets/33147972/ea887204-faa0-4d50-9abf-5c6942f1609b)
![image](https://github.com/antvis/X6/assets/33147972/f7c84e41-df1c-4f56-9241-9615f30935a5)
![image](https://github.com/antvis/X6/assets/33147972/267bb0b2-d9cd-4ccb-919b-5c9d499b85ba)

**Comment by oyal** [comment]
@zzyyu 我的业务场景不能开启自动吸附，你再把snap设置为false，会发现就不能修改起点/终点了，识别不到
我排查到的原因是修改时链接桩依然为隐藏状态，造成无法识别，而新拖出一条边过程链接桩是显示的

![image](https://github.com/antvis/X6/assets/88022434/44cd3443-ee1b-4960-af81-f2017a5fbfa7)

![image](https://github.com/antvis/X6/assets/88022434/5c51c2a7-cc25-465b-bd42-3a7a182d75ae)

**Comment by zzyyu** [comment]
连接桩的显隐是被事件定义过的，原本是节点的移入移出事件
直接操作线是不触发的，建议你将移入移出事件改成cell（包含节点与线），这样无论是操作节点还是单独操作线都可以显示连接桩
![image](https://github.com/antvis/X6/assets/33147972/592067f3-3ec3-41b0-b838-14ccaef581ff)

**Comment by oyal** [comment]
@zzyyu 我现在是对单个节点鼠标悬停显示/隐藏链接桩，不适用于显示全部链接桩，一百多个节点会非常卡顿。而新增/修改边过程中又无法触发 `node:mouseenter` 事件

![image](https://github.com/antvis/X6/assets/88022434/67d89995-57b8-468b-91af-5bdfc1b9a17d)

**Comment by zzyyu** [comment]
你可以增加对cell的判定，如果cell是节点，则显示本身的连接桩
如果cell是边，显示该边的source节点与target节点的连接桩

**Comment by NewByVector** [comment]
在你定义的两个事件中分别添加上显示连接桩和隐藏连接桩的代码就可以了。

```ts
graph.on('edge:mouseenter', ({ cell }) => {
  showPort()
  cell.addTools([
    {
      name: 'source-arrowhead'
    },
    {
      name: 'target-arrowhead',
      args: {
        attrs: {
          fill: 'red'
        }
      }
    }
  ])
})

graph.on('edge:mouseleave', ({ cell }) => {
  hidePort()
  cell.removeTools()
})
```
