### ISSUE TITLE
MiniMap + React Component Portal模式， 画布不渲染组件只渲染edge

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/X6#3675]
### 问题描述

MiniMap + React Component Portal模式， 画布不渲染组件只渲染edge

### 重现链接

https://github.com/antvis/X6/discussions/3622

### 重现步骤

MiniMap + React Component Portal模式， 画布不渲染组件只渲染edge

### 预期行为

画布正常渲染

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![83ed2421-dffc-4705-9cbb-c9f4badcfbf9](https://github.com/antvis/X6/assets/20533727/bc4874b7-469f-4aba-a4a7-26679bef4c70)

**Comment by lloydzhou** [comment]
看了下在线的demo，应该是和 #2947 一样的问题。在#3591 已经修复了

![image](https://github.com/antvis/X6/assets/1826685/b68fefc9-56f4-4cdb-9d45-d788df60ea78)


我试了试将在线demo的x6-react-shape版本升级到2.2.2就正常了

![image](https://github.com/antvis/X6/assets/1826685/598b1b03-23f5-4cb9-8e25-1204235dffdf)

**Comment by Superzzw1994** [comment]
> 看了下在线的demo，应该是和 #2947 一样的问题。在#3591 已经修复了
> 
> ![image](https://user-images.githubusercontent.com/1826685/245670138-b68fefc9-56f4-4cdb-9d45-d788df60ea78.png)
> 
> 我试了试将在线demo的x6-react-shape版本升级到2.2.2就正常了
> 
> ![image](https://user-images.githubusercontent.com/1826685/245670758-598b1b03-23f5-4cb9-8e25-1204235dffdf.png)

不好意思，我的react是16版本的，x6是1.x，这个2.2.2貌似不兼容啊，有低版本能用的吗？

**Comment by lloydzhou** [comment]
react16的话，那我给你推荐一个
https://github.com/lloydzhou/x6-html-shape

我在这个issue里面也有提到过 #3487

react18以下的版本，可以使用这两种模式都可以
![image](https://github.com/antvis/X6/assets/1826685/feda047d-a0e8-4700-9b97-5dc329e8a90c)

**Comment by lloydzhou** [comment]
@Superzzw1994 
按x6的逻辑。Edge，可以连接Node, NodePort, 或者是画布上的Point，但是不能是dom元素

**Comment by Superzzw1994** [comment]
> @Superzzw1994 按x6的逻辑。Edge，可以连接Node, NodePort, 或者是画布上的Point，但是不能是dom元素

那可以用point试试哈，谢谢回复。
