### ISSUE TITLE
jest 单元测试 Uncaught [TypeError: this.viewport.getCTM is not a function]

### ISSUE THREAD

**Issue by LemonYo** [antvis/X6#3676]
### 问题描述

我的组件基于 @antv/x6开发，在进行单元测试的 时候 会报错，请问如何解决

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [2.11.1]

### 屏幕截图或视频（可选）

<img width="1074" alt="image" src="https://github.com/antvis/X6/assets/18257478/97c89248-0478-4f73-8d4c-093549b95179">

**Comment by NewByVector** [comment]
x6 是基于 svg dom 的，jest 不能完全模拟浏览器环境，也就是没有一些浏览器 api，比如 viewport.getCTM。可以使用一些可以完全模拟浏览器 api 的测试框架或者直接使用无头浏览器进行测试。
