### ISSUE TITLE
右键菜单例子中菜单的位置问题

### ISSUE THREAD

**Issue by issacsonjj** [antvis/X6#3681]
### 问题描述

官方的右键菜单例子中，生成的菜单位置一直在左上角

### 重现链接

https://codesandbox.io/s/4sordy

### 重现步骤

右键点击node

### 预期行为

菜单应该出现在光标旁边，但实际上一直出现在左上角

### 平台

- 操作系统: [win10]
- 网页浏览器: [Google Chrome, Firefox]
- X6 版本: [2.11.1 ]

**Comment by ZHP0512** [comment]
看下这个链接：https://www.yuque.com/sxd_panda/antv/x6#NIQ4t，希望对你有帮助

**Comment by NewByVector** [comment]
@issacsonjj 能否提供一个可以复现的链接看下呢？

**Comment by NewByVector** [comment]
因为无法复现，先关闭，如果有复现的 demo，请重新提一个新的 issue。

**Comment by sandianshui** [comment]
X6官网提供的示例就能复现这个问题
https://codesandbox.io/s/4llly5

**Comment by issacsonjj** [comment]
> @issacsonjj 能否提供一个可以复现的链接看下呢？

官网上放的例子就有这个问题：https://codesandbox.io/s/4sordy
