### ISSUE TITLE
监听 mousewheel 不起作用，已开启enabled

### ISSUE THREAD

**Issue by light-years-run** [antvis/X6#3685]
### 问题描述

无法监听到 mousewheel

### 重现链接

test

### 重现步骤

const graph = new Graph({
container: document.getElementById('container'),
grid: true,
mousewheel: {//开启
enabled: true,
modifiers: 'ctrl',
}
})

graph.on('node:mousewheel', ({ node }) => {
console.log(node); //控制台没有任何输出
})
graph.on('cell:mousewheel', ({ node }) => {
console.log(node); //控制台没有任何输出
})
graph.on('blank:mousewheel', ({ node }) => {
console.log(node); //控制台没有任何输出
})
graph.on('blank:mousewheel', ({ node }) => {
console.log(node); //控制台没有任何输出
})
graph.on('edge:mousewheel', ({ node }) => {
console.log(node); //控制台没有任何输出
})

### 预期行为

能监听到

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
并没有这个事件哇。

**Comment by light-years-run** [comment]
> 并没有这个事件哇。

官方文档上是有的，
![image](https://github.com/antvis/X6/assets/25027143/627ed3a2-be4a-4360-b5cd-a9f24bcbea9f)

**Comment by NewByVector** [comment]
哦哦，你如果开启 mousewheel 功能，这个事件是不会触发的，我在文档上标记一下。

**Comment by light-years-run** [comment]
> 哦哦，你如果开启 mousewheel 功能，这个事件是不会触发的，我在文档上标记一下。

那如果我想监听鼠标滚动事件，就没法监听了是吗？

**Comment by NewByVector** [comment]
可以使用 [scale](http://x6.antv.antgroup.com/tutorial/basic/events#%E7%94%BB%E5%B8%83%E7%BC%A9%E6%94%BE%E5%B9%B3%E7%A7%BB) 事件来实现。
