### ISSUE TITLE
麻烦看下，初始化的时候先从左上角渲染 然后移动到中间

### ISSUE THREAD

**Issue by ABCDdouyaer** [antvis/X6#3687]
### Describe the bug

**初始渲染节点会在左上角闪动下 可以看下视频第一帧左上角闪动**

**layout布局**
![image](https://github.com/antvis/X6/assets/31639964/8e5cb22a-4a4a-43c3-8730-8dcc2ca0462d)

https://github.com/antvis/X6/assets/31639964/80cede6e-6696-4b8b-8a10-72ed3280a746

<img width="1637" alt="image" src="https://github.com/antvis/X6/assets/31639964/54e627d0-0319-4bee-89dd-9861e5b8d28b">

### Your Example Website or App

: https://stackoverflow.com/help/mcve.

### Steps to Reproduce the Bug or Issue

看描述

### Expected behavior

初始化页面

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ABCDdouyaer** [comment]
**还有一个问题 我怎么让某个节点最后一个渲染，因为group和shape提供了zIndex和sort
但不知道节点zIndex和排序吗 不然我的激活节点会被其他的覆盖 或者提供力方法让激活节点周围的点离得远一点也行 设置distance  nodeSpacing效果不太好**
<img width="1088" alt="image" src="https://github.com/antvis/X6/assets/31639964/e05b54dd-abdd-4386-b3f0-e28e868ed523">
<img width="851" alt="image" src="https://github.com/antvis/X6/assets/31639964/ca841dfc-f45b-4d8a-9971-916de93ed534">

**Comment by ABCDdouyaer** [comment]
**问题2 有些image类型的shape不知道为啥img没加载 但我set的确实是正确的图 并且图片很小 而且我也不知道它是否在canvas绘制成功了，如何解决**
<img width="681" alt="image" src="https://github.com/antvis/X6/assets/31639964/3e1a6ac2-fcf4-4698-b892-2889cba086ce">

**Comment by ABCDdouyaer** [comment]
**问题3：很多个节点，我要保证某个节点渲染在最上面 不被其他节点覆盖 ， group和shape都有zIndex和sort，node节点是根据数组顺序来渲染的吗**
**问题4：动画的easing只能定义d3库的字符串，但是d3库的动画都是可以入参的 我们这个只能局限在字符串 没法随意定制某个d3动画的入参吗**

**Comment by NewByVector** [comment]
我依次回答你的问题吧。
1. 力导向布局会持续执行 onLayoutEnd 方法，即使第一次布局位置在左上角也会执行一次，所以你这里需要做好防抖。
2. image 没有加载可以浏览器审查一下 dom 元素排查一下。
3. 节点在画布上的层级是由  zIndex 决定的，zIndex 大的在上面。
4. 有具体的参考例子吗，timing 不仅支持字符串，还支持自定义函数的，不知道能否满足你需求。

**Comment by ABCDdouyaer** [comment]
@NewByVector 
**问题1.** force2刚开始不是一直onTick直到布局完成才会执行onLayoutEnd方法吗，我初始设置的从canvas中间扩散开，第一帧动画所有节点出现在左上角（0,0）位置闪动了一下，没明白你说的防抖是怎么做
**问题2.**我看了network里面的img是加载出来的 但是canvas画的时候确实画了个空白，但我并不知道它画了个空白 如果我可以确定这个图片没画出来 我会手动update，但目前确实不知道
**问题4.** 动画类型参数只能传string类型，但是d3的每个都是个函数，可以入参，不知道如何自定义
<img width="1309" alt="image" src="https://github.com/antvis/X6/assets/31639964/d26c6687-a051-4d24-83a9-f57c0846486c">
<img width="1598" alt="image" src="https://github.com/antvis/X6/assets/31639964/4b9d0ddf-5edd-4416-9449-6df6dfc81687">

**Comment by NewByVector** [comment]
怎么感觉你用的是 @antv/G6 呀？这里是 X6.
