### ISSUE TITLE
node:click事件是否需要初始化画布？？

### ISSUE THREAD

**Issue by GeorGeWzw** [antvis/X6#369]
现在有一个问题如果我不在画布内部操作一次，会发生node:click等事件点击不生效，具体演示代码在此仓库https://github.com/DestinyCore/DestinyCore.Flow.Design

**Comment by bubkoo** [comment]
给 codesandbox 复现问题的链接。

**Comment by NewByVector** [comment]
使用你提供的demo与你描述的不符合，不需要操作就可以触发node:click
