### ISSUE TITLE
删除连线前确认

### ISSUE THREAD

**Issue by Mafiti** [antvis/X6#3692]
### 问题描述

需求是：删除连线前需要弹出确认，确认才能删除，否则不能删除。

目前没有找到删除事件前的钩子，尝试过validateEdge，但是该方法只能用于创建连线，或者连线过程中。

是否有其它方式可以实现这个需求呢。

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
你的删除交互是怎么样的呢？

**Comment by Mafiti** [comment]
> 你的删除交互是怎么样的呢？

就是删除前先弹窗让用户确认是否删除，确认才删除，否则不删除

**Comment by NewByVector** [comment]
我的意思是你是通过哪种方式来触发删除动作。
