### ISSUE TITLE
泳道图 三个节点的label展示在了同一条线上，导致我不知道label 对应的是那条路径，这个如何解决呢？

### ISSUE THREAD

**Issue by 542473232** [antvis/X6#3693]
### 问题描述

![image](https://github.com/antvis/X6/assets/65716967/152d4b93-de4d-45b9-9261-a0788965ec13)
如图，我有三个节点的label 展示在了一条线上，导致我不知道label 对应的是那条路径，这个如何解决呢？

### 重现链接

暂无

### 重现步骤

见问题描述

### 预期行为

我期望看到三条线 而不是合并在一条线 或者有其他的办法能展示出来 label和对应的路径

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
设置连接点偏移能否满足你的需求呢？参考[例子](http://x6.antv.antgroup.com/tutorial/intermediate/connection-point)。

**Comment by 542473232** [comment]
您说的这个方案 我试了一下 效果还是不好 
![image](https://github.com/antvis/X6/assets/65716967/0f9e5b14-0504-4635-96cd-b0672d3fb78d)
![image](https://github.com/antvis/X6/assets/65716967/1f9fbba4-c400-4e32-af43-14d6dcf0217f)

我现在想通过 高亮路径时展示不同的高亮颜色和不同的颜色的路径label来区分 这个路径abel的颜色如何在点击节点时 让它和路径一起变色呢

**Comment by 542473232** [comment]
我这个图表是基于 官网中的泳道图实现的 如果还有其他的修改办法 麻烦告诉我

**Comment by NewByVector** [comment]
@542473232 
同时修改边和标签需要分别设置：
```ts
graph.on('edge:mouseenter', ({edge}) => {
  edge.attr('line/stroke', 'red')
  edge.prop('labels/0/attrs/label/fill', 'red')
})
```

**Comment by 542473232** [comment]
好的 谢谢
