### ISSUE TITLE
设置async后，性能反而比之前差

### ISSUE THREAD

**Issue by qiufeihong2018** [antvis/X6#3694]
### 问题描述

【大数据量】差不多1000多个节点，设置async后，性能反而比之前差，表现为之前毫秒级的增加节点，变成了异步增加（先增加连接器，后面增加节点，花费差不多1.5s的时间）

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

符合文档中对async的定义

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- X6 版本: [^1.32.3]

**Comment by qiufeihong2018** [comment]
demo我之后补一下

**Comment by NewByVector** [comment]
要不升级一下 2.x 版本，相比 1.x 性能有较大的提升。

**Comment by qiufeihong2018** [comment]
@NewByVector 迁移2.x遇到了不少问题

**Comment by qiufeihong2018** [comment]
@NewByVector 加入了async，tab新增节点，会出现明显卡顿
https://codesandbox.io/s/x6de-v1ban-ben-de-she-zhi-asynchou-xing-neng-fan-er-bi-zhi-qian-chai-5z8t32?file=/index.tsx

**Comment by NewByVector** [comment]
增加 `async` 属性并不会比没有加 `async` 加载更快，而是异步加载，不会阻塞浏览器，也就是不会出现卡屏现象。我看了你的例子，有 6000+节点，可以考虑使用虚拟渲染, 参考 [demo](https://github.com/antvis/X6/blob/v1/examples/x6-example-features/src/pages/performance/async.tsx)。
