### ISSUE TITLE
文档中缺少对onViewUpdated、onViewPostponed的说明

### ISSUE THREAD

**Issue by qiufeihong2018** [antvis/X6#3695]
### 问题描述

文档中缺少对onViewUpdated、onViewPostponed的说明

### 重现链接

暂无

### 重现步骤

文档中缺少对onViewUpdated、onViewPostponed的说明

### 预期行为

补全

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
这两个方法不推荐外部使用，所以不在文档透出。
