### ISSUE TITLE
node-editor 参数中的 x 不起作用

### ISSUE THREAD

**Issue by changjunhao** [antvis/X6#3698]
### Describe the bug

在添加Node时，添加 node-editor 工具，对工具的位置进行了修改：`{ x: 0, y:0}`，但只有y起作用了

### Your Example Website or App

https://codesandbox.io/s/pedantic-tharp-hmtmff?file=/src/App.js

### Steps to Reproduce the Bug or Issue

如示例

### Expected behavior

希望 node-editor 工具的 x 参数能起作用

### Platform

- OS: [macOS]
- Browser: [Chrom]
- Version: [2.11.1]

**Comment by changjunhao** [comment]
看源码发现是生效的，但 工具的 style 是动态生成的，能不能提供一个方法让调用者自己确定工具的位置

**Comment by NewByVector** [comment]
看了你的例子，x y 参数都是生效的，文本编辑开始位置在中间位置是因为 `text-aligin:center` 属性影响的，如果你想从左侧开始编辑，可以覆盖该属性。

**Comment by TalentJY** [comment]
> 看了你的例子，x y 参数都是生效的，文本编辑开始位置在中间位置是因为 `text-aligin:center` 属性影响的，如果你想从左侧开始编辑，可以覆盖该属性。
如何从左上角顶格开始呢？现在 垂直方向是默认居中的

**Comment by TalentJY** [comment]
> 看了你的例子，x y 参数都是生效的，文本编辑开始位置在中间位置是因为 `text-aligin:center` 属性影响的，如果你想从左侧开始编辑，可以覆盖该属性。

包括 我想在不同的节点实现不一样的效果，该怎么办

**Comment by NewByVector** [comment]
@TalentJY 那你需要根据不同节点设置不同的样式了。

**Comment by aflext** [comment]
@NewByVector 借个楼问下，能否针对这个node-editor，新增 width、height的设置参数，类似x和y？场景是双击时，node-editor的宽高全等于节点的宽高；目前只能通过全局样式hack，但是如果每个节点的宽高不一样，就比较繁琐
![image](https://github.com/antvis/X6/assets/3211461/32caf9a9-2771-44f3-bb05-95bd5f53fcb8)

**Comment by wu0211** [comment]
> @NewByVector 借个楼问下，能否针对这个node-editor，新增 width、height的设置参数，类似x和y？场景是双击时，node-editor的宽高全等于节点的宽高；目前只能通过全局样式hack，但是如果每个节点的宽高不一样，就比较繁琐 ![image](https://user-images.githubusercontent.com/3211461/256127362-32caf9a9-2771-44f3-bb05-95bd5f53fcb8.png)

hello,你这个有解决方案了吗

**Comment by aflext** [comment]
> > @NewByVector 借个楼问下，能否针对这个node-editor，新增 width、height的设置参数，类似x和y？场景是双击时，node-editor的宽高全等于节点的宽高；目前只能通过全局样式hack，但是如果每个节点的宽高不一样，就比较繁琐 ![image](https://user-images.githubusercontent.com/3211461/256127362-32caf9a9-2771-44f3-bb05-95bd5f53fcb8.png)
> 
> hello,你这个有解决方案了吗



hack方式：

1、动态设置node-editor父节点宽高
```js
if (event === 'node:click') {
    editorDom = options?.view?.tools?.tools?.[0];
    if (editorDom && editorDom.container) {
        editorDom.container.style = 'width: 100px; height: 100px;';
    }
}
```
2、设置node-editor的宽高为100%
```css
.x6-node-tool {
    .x6-node-tool-editor {
        width: 100%;
        height: 100%;
        text-align: left;
    }
}
```

**Comment by aflext** [comment]
hack2:

监听双击事件，能拿到editor的dom引用，即可动态设置宽高
```js
if (event === 'node:dblclick') {
    const editorDom = options?.view?.tools?.tools?.[0];
    if (editorDom && editorDom.editor) {
        editorDom.editor.style.width = '100px';
        editorDom.editor.style.height = '100px';
        editorDom.editor.style.textAlign = 'left';
    }
}
```
