### ISSUE TITLE
Win下无法用delete键删除元素，只能使用Backspace键删除元素

### ISSUE THREAD

**Issue by loongmxbt** [antvis/x6#37]
Win下无法用delete键删除元素，只能使用Backspace键删除元素
### Expected Behavior
Win下可以使用Delete按键删除元素

### Current Behavior
Win下无法用delete键删除元素

### Possible Solution
删除元素也绑定Delete键

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: 0.1.5
- OS: Win10
- Browser: chrome

**Comment by bubkoo** [comment]
嗯，我在 demo 中加一下快捷键。
