### ISSUE TITLE
x6获取节点和边连接

### ISSUE THREAD

**Issue by liyu-2502189494** [antvis/X6#3700]
### 问题描述

如何获取节点和边的连接位置，那个点的x，y值是多少

### 重现链接

无

### 重现步骤

任意一个节点和一条连接边，关于它的连接点位置获取

### 预期行为

 我希望获取任意一个节点和一条连接边，关于它的连接点位置获取，它的x，y值是多少

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
可以使用以下方式获取：
```ts
view.getTerminalConnectionPoint('source')
```

不过需要等待连线完成渲染后才能获取到正确的位置。

**Comment by liyu-2502189494** [comment]
您好，这个方法使用时报错，view.getTerminalConnectionPoint('source') is not function，在文档中也没有找到这个函数方法，

**Comment by liyu-2502189494** [comment]
this.graph = new Graph({
                container: document.getElementById("container"),
                width: 800,
                height: 600
            });
            this.graph.fromJSON(this.data)
            this.graph.on('node:click',({e,x,y,node,view})=>{
                // console.log(view.getTerminalConnectionPoint('source'));
                console.log(node.getTerminalConnectionPoint('source'));
            })
我是在这里看到报错

**Comment by NewByVector** [comment]
@liyu-2502189494 这个是 edgeView 上的方法，而不是 nodeVIew。
