### ISSUE TITLE
vue2+vite+antv/x6编译后网页打开时报错

### ISSUE THREAD

**Issue by linjiayu2012** [antvis/X6#3704]
### 问题描述

vue2+vite+antv/x6编译后网页打开时报错。
这个文件@babel/runtime/regenerator/index.js下的这行代码报错require("../helpers/regeneratorRuntime")()。报错信息是is not a function。实际上 require 进来后还有一层 default。请问是得如何配置 vite.config.js？还是说得引入什么插件解析呢？

### 重现链接

-

### 重现步骤

-

### 预期行为

-

### 平台

- 操作系统: [macOS, Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.9.7]
- vue 版本: [2.6.14]
- vite 版本: [4.3.9]

**Comment by NewByVector** [comment]
是不是这个问题呢？https://github.com/antvis/X6/issues/2912
