### ISSUE TITLE
自定义的非path节点怎样拖拽大小

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/X6#3705]
### 问题描述

自定义节点怎样才能拖拽调整大小，path的形式我知道可以用refD，但是像官网图表示例中的开关这种通过多个圆形和矩形的形式组合的应该怎样做呢

### 重现链接

https://x6.antv.antgroup.com/zh/examples/node/custom-node/#switch

### 重现步骤

https://x6.antv.antgroup.com/zh/examples/node/custom-node/#switch

### 预期行为

https://x6.antv.antgroup.com/zh/examples/showcase/practices/#flowchart

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by leechor** [comment]
同问, V1中文档中有  resizing: {
    enabled: true,
  },设置, v2中好像没了.

**Comment by leechor** [comment]
https://x6.antv.antgroup.com/tutorial/plugins/transform#%E8%B0%83%E6%95%B4%E5%B0%BA%E5%AF%B8

**Comment by hhzhldhjl** [comment]
> 具备修改元素尺寸的条件是：节点内部的元素的尺寸、位置是通过相对属性来赋值的，比如 refWidth、refX，这样才能做到拖拽的时候自适应大小。

好的，谢谢
