### ISSUE TITLE
自定义组件开启resizing后选择框宽高都为1px

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/X6#3706]
### Describe the bug

官网自定义开关节点开启resizing后，选中节点选择框的宽高都是1px

### Your Example Website or App

https://antv-x6.gitee.io/zh/examples/node/custom-node#switch

### Steps to Reproduce the Bug or Issue

https://antv-x6.gitee.io/zh/examples/node/custom-node#switch

### Expected behavior

正常应该是选择框大小跟节点大小一样

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

### Additional context

![微信图片_20230625180952](https://github.com/antvis/X6/assets/26075113/a2ab11ba-c367-4f6b-8abc-395f7be63eb2)

**Comment by NewByVector** [comment]
是因为节点定义的时候没有指定宽高，所以 resizing 的尺寸不对，而且在这个图中，所有元素的宽高都是绝对尺寸，是不能通过 resizing 来改变大小的。

**Comment by hhzhldhjl** [comment]
> 是因为节点定义的时候没有指定宽高，所以 resizing 的尺寸不对，而且在这个图中，所有元素的宽高都是绝对尺寸，是不能通过 resizing 来改变大小的。

好的，谢谢
