### ISSUE TITLE
关于dnd的 getDropNode 问题

### ISSUE THREAD

**Issue by AK081KA** [antvis/X6#371]
### Expected Behavior
new Dnd({ target: this.graph, animation: true,validateNode:this.validate,getDropNode:this.dragNode})
dragNode(node){
  return node
}
validate(node){
  return true
}

### Current Behavior
添加画布不成功，也不报错

### Possible Solution
去除getDropNode就可以
另外拖拽多次，会多次触发getDropNode事件

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
需要 clone 一下，如果不 clone，`node` 将会从所有画布中移除。
```ts
dragNode(node){
  return node.clone()
}
```

**Comment by AK081KA** [comment]
> 需要 clone 一下，如果不 clone，`node` 将会从所有画布中移除。
> 
> ```ts
> dragNode(node){
>   return node.clone()
> }
> ```

嗯嗯，可以了。还有个问题，拖拽多次，会多次触发getDropNode事件，麻烦看下

**Comment by bubkoo** [comment]
每次拖拽结束释放到画布都会触发这个方法

**Comment by AK081KA** [comment]
> 每次拖拽结束释放到画布都会触发这个方法

第一次拖拽结束触发1次，第二次拖拽结束会触发两次，以此类推，触发多次，然后我在getDropNode方法里添加节点，就会触发多次

**Comment by bubkoo** [comment]
> > 每次拖拽结束释放到画布都会触发这个方法
> 
> 第一次拖拽结束触发1次，第二次拖拽结束会触发两次，以此类推，触发多次，然后我在getDropNode方法里添加节点，就会触发多次

给一下复现代码的 codesandbox 我本地复现不了。

**Comment by bubkoo** [comment]
@AK081KA 我们在另一个 issue 中发现了类似问题 #360，并已经修复，你再看看你那边是否还有这个问题。

**Comment by AK081KA** [comment]
> @AK081KA 我们在另一个 issue 中发现了类似问题 #360，并已经修复，你再看看你那边是否还有这个问题。

可以了，谢谢大佬

**Comment by yutian0414** [comment]
这个怎么让其id不变啊，不生成一个新的uuid，或者使用我自己生成的uuid
