### ISSUE TITLE
怎么自适应设置节点宽高

### ISSUE THREAD

**Issue by PalmerShuai** [antvis/X6#3711]
### 问题描述

页面初始化的时候，自定义固定宽高的节点,点击自定义节点，弹框配置相关内容，关闭弹框重新新绘制画布上节点，怎么实现自定义节点的宽高由弹框配置的内容撑
求方法！！！

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]
暂无

**Comment by PalmerShuai** [comment]
目前实现的方式是重绘之前根据配置内容的字数，使用js计算出大概高度，但是这样的计算是不太准确的，想请教一下有没有其他的实现方式

**Comment by NewByVector** [comment]
提供两个思路：
1. 使用 [textWrap](https://x6.antv.antgroup.com/api/registry/attr#textwrap) 来实现超出部分...显示。
2. 使用 `Dom.measureText` 获取文本总长度 l,然后 l / nodeWidth * lineHeight 就是新的节点高度。
