### ISSUE TITLE
自定义节点里面有svg图片，在使用toPNG导出成png图片后，svg图片没有渲染出来

### ISSUE THREAD

**Issue by li522021642** [antvis/X6#3712]
### Describe the bug

vue3，使用自定义节点里面有svg图片，在导出成png图片后，svg图片没有渲染出来

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

画布中可以正常渲染 svg图片，但是使用 toPNG 导出图片后，图片里面没有正确渲染

### Expected behavior

无

### Platform

- OS: [Windows,]
- Browser: [Chrome,]
- Version: [109.0.5414.120（正式版本） （64 位）]

**Comment by li522021642** [comment]
上传不了图片 后面我补上

**Comment by li522021642** [comment]
@NewByVector 麻烦看看这个问题，或者有没有替他暂时代替的方案

**Comment by NewByVector** [comment]
已知问题，可以考虑将 svg 图片转换为 base64 格式图片来导出。

**Comment by NewByVector** [comment]
已经有很多类似的 issue，导出的图片无法显示，导出插件暂时对路径图片处理能力还不够，推荐使用 base64 格式图片。

**Comment by mankeheaven** [comment]
这就关了?

**Comment by mankeheaven** [comment]
原来原理是这个。为难你们了，这东西，肯定是整不好的，所以，导出图片整个插件，肯定是永远有bug的。html2canvas， 这个思路是个死胡同。
![image](https://github.com/antvis/X6/assets/17426397/91046f99-7d63-4786-92a4-381817ebd5df)
