### ISSUE TITLE
有没有根据svg代码自动转换为可注册节点代码的方法

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/X6#3713]
### 问题描述

我这可能需要往我编辑器注册几百个图元，有的复杂图元可能代码就忒十几行，一个一个转换成markup代码再注册进入实在太难了，而且要想可变形还需要把属性转换为ref形式，不知道有没有一个方法可以根据svg代码转换成markup形式代码

### 重现链接

无

### 重现步骤

无

### 预期行为

自动解析svg代码

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
没有的，因为还没有通用的方法将 svg 结构转换为 x6 的 markup 结构和样式。

**Comment by hhzhldhjl** [comment]
> 没有的，因为还没有通用的方法将 svg 结构转换为 x6 的 markup 结构和样式。
我直接把我svg文件的属性，比如x、y、width、height原样不动变成refX、refY、refWidth、refHeight,发现图形就乱套了，是不能使用原数据吗？需要进行计算后变成ref形式吗？

**Comment by NewByVector** [comment]
不能直接原封不动的使用，因为 ref 开头的属性是相对属性，需要重新计算的，参考[文档](http://x6.antv.antgroup.com/api/registry/attr)。

**Comment by hhzhldhjl** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="224" height="97" viewBox="0 0 224 97" version="1.1">
    <title>水管</title>
    <defs>
        <linearGradient x1="50.0486855%" y1="0%" x2="50.0486855%" y2="100%" id="linearGradient-1">
            <stop stop-color="#2C2C2C" stop-opacity="0" offset="0%"/>
            <stop stop-color="#2C2C2C" stop-opacity="0.1" offset="100%"/>
        </linearGradient>
    </defs>
    
            <g id="水管">
                <rect id="矩形" fill="#3BA7FF" x="158.054734" y="0" width="33.4943519" height="6.6779856" rx="1.22"/>
                <path d="M163.637126,30.0119586 L185.901479,30.0119586 L185.901479,33.9096156 C185.901479,34.8352407 185.148179,35.5856081 184.218936,35.5856081 L165.254454,35.5856081 C164.808216,35.5856081 164.380255,35.4090308 164.064717,35.0947212 C163.749178,34.7804117 163.571911,34.3541164 163.571911,33.9096156 L163.571911,30.0119586 L163.637126,30.0119586 Z" id="路径" fill="#BCBCBC" transform="translate(174.736695, 32.798783) scale(-1, 1) rotate(-180.000000) translate(-174.736695, -32.798783) "/>
                <rect id="矩形" fill="#383838" x="166.428322" y="24.4642935" width="16.747176" height="5.56065727"/>
                <path d="M162.698032,6.6779856 L186.879702,6.6779856 C187.600045,6.6779856 188.183999,7.25966575 188.183999,7.97720458 L188.183999,24.4642935 L161.393735,24.4642935 L161.393735,7.97720458 C161.393735,7.25966575 161.977688,6.6779856 162.698032,6.6779856 Z" id="路径" fill="#2791FD" transform="translate(174.788867, 15.571140) scale(-1, 1) rotate(-180.000000) translate(-174.788867, -15.571140) "/>
                <rect id="矩形" fill="url(#linearGradient-1)" x="161.393735" y="6.6779856" width="26.7902644" height="4.44332894"/>
                <polygon id="路径" fill="#E2E2E2" transform="translate(100.137417, 53.911092) scale(-1, 1) translate(-100.137417, -53.911092) "  points="152.459299 92.9980951 47.8155351 73.4578416 47.8155351 34.3643422 152.459299 14.8240886"/>
                <rect id="矩形" fill="#E2E2E2" x="152.459299" y="34.3643422" width="52.3153604" height="39.0805071"/>
                <rect id="矩形" fill="#E2E2E2" x="8.58227553" y="14.8240886" width="39.2332596" height="78.1740065"/>
                <rect id="矩形" fill="#989898" x="38.4245953" y="11.563049" width="13.8777221" height="84.6830936" rx="4.27"/>
                <rect id="矩形" fill="#989898" x="6.67910172e-13" y="11.563049" width="13.8777221" height="84.6830936" rx="4.27"/>
                <rect id="矩形" fill="#383838" x="204.787702" y="31.1162947" width="6.53452894" height="45.6025865" rx="1"/>
                <rect id="矩形" fill="#989898" x="211.322231" y="24.5942154" width="12.6777687" height="58.6337529" rx="1"/>
            </g>
</svg>`请问我这个图元为什么我用ref注册为一个可变形节点就是不对呢，我该怎样重新计算，弄帮忙给弄一下吗？谢谢，弄了好久都不行
