### ISSUE TITLE
x6 能否支持svg pattern 定义

### ISSUE THREAD

**Issue by YGodFather** [antvis/X6#3714]
### 问题描述

x6 API 以及源码未找到可以支持 创建 svg  pattern 元素的方法， x6 是否能提供一个自定义 pattern 方法

### 重现链接

无

### 重现步骤

无

### 预期行为

x6  能都创建 自定义的pattern，泪如类似如下的效果
```html

<svg id="10015.io" viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg"><defs><pattern id="svg-pattern" x="0" y="0" width="10" height="10" patternUnits="userSpaceOnUse" patternTransform="translate(0, 0) rotate(145) skewX(-45)"><svg width="10" height="10" viewBox="0 0 100 100"><g fill="#47d3ff" opacity="1"><rect y="60" width="20" height="100" transform="rotate(-90 0 60)"></rect></g></svg></pattern></defs><rect x="0" y="0" width="100%" height="100%" fill="#474bff"></rect><rect x="0" y="0" width="100%" height="100%" fill="url(#svg-pattern)"></rect></svg>`
```

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/X6/assets/30761435/21e279fd-fd23-4afa-9f3a-9ab2e5fedbb1)

![image](https://github.com/antvis/X6/assets/30761435/19118f45-3d37-4024-aa69-71e1497a3737)

**Comment by NewByVector** [comment]
是不支持 pattern 的，不过你可以使用背景图片来实现这个功能。
