### ISSUE TITLE
Scroller 插件滚动条不应该出现

### ISSUE THREAD

**Issue by 171h** [antvis/X6#3715]
### Describe the bug

使用 scroller 插件时，我设置插件 padding: 0。当 graph 宽度、高度小于 scroller content 宽度时，按理说不应该出现滚动条，但是由于 scroller 默认将 graph 的 local (0,0) 坐标作为 scroller content 的左上角坐标，结果就出现了滚动条。

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

是不是可以提供一个选项，让 scroller 的 content 尺寸永远与 graph 尺寸一样？

### Screenshots or Videos

[.](https://github.com/antvis/X6/assets/40647432/cad40a05-3283-4467-9952-5765dbd951a7)

### Platform

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.3.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.4
- Builder:          vite
- User Config:      ssr, modules, css, devtools
- Runtime Modules:  @unocss/nuxt@0.51.13, @pinia/nuxt@0.4.11, @nuxthq/ui@2.3.0, @element-plus/nuxt@1.0.5
- Build Modules:    -
------------------------------

### Additional context

.

**Comment by NewByVector** [comment]
可以覆盖 scroller 容器的样式来实现。
```css
.x6-graph-scroller {
  overflow: auto;
}

**Comment by 171h** [comment]
> 可以覆盖 scroller 容器的样式来实现。
> 
> ```css
> .x6-graph-scroller {
>   overflow: auto;
> }
> ```

试了，不行，我是通过以下方法解决的，但是还是希望 `scroller` 能够内置一个选项。

```ts
scroller.value = graph.value.getPlugin('scroller') as Scroller
scrollerContent.value = scrollerContainer.value.querySelector('.x6-graph-scroller-content') as HTMLDivElement
graph.value.on('resize', ({ width, height }) => {
    Dom.css(scrollerContent.value, { width, height })
})
```

**Comment by NewByVector** [comment]
@171h padding 有设置为 0 吗？

**Comment by 171h** [comment]
> @171h padding 有设置为 0 吗？

是的

**Comment by NewByVector** [comment]
@171h https://codesandbox.io/s/mo-ban-forked-c2pjzq?file=/src/App.tsx  并不是呀。

**Comment by 171h** [comment]
> @171h https://codesandbox.io/s/mo-ban-forked-c2pjzq?file=/src/App.tsx 并不是呀。

你看看我这个，在你的基础上修了一下，在 -x 区域添加了一个节点就是了
https://codesandbox.io/s/mo-ban-forked-9j9r48?file=/src/App.tsx

**Comment by 171h** [comment]
> @171h 这种场景出现滚动条是正常的吧 感觉你的业务场景应该是不需要 scroller 插件能力的？

这种情况下，graph尺寸小于scroller插件的content区域尺寸，不显示滚动条完全可以，其实这完全是因为scroller插件将graph的local坐标原点作为content的初始左上角导致的，将graph的视口左上角作为初始左上角就行了。

**Comment by NewByVector** [comment]
滚动条的作用就是让用户对页面上所有元素的位置有个清晰的定位，像上面的场景，肯定是想让用户了解左侧 -x 区域还有元素，我理解用 local 坐标原点作为左上角并没有问题的。

**Comment by 171h** [comment]
> 滚动条的作用就是让用户对页面上所有元素的位置有个清晰的定位，像上面的场景，肯定是想让用户了解左侧 -x 区域还有元素，我理解用 local 坐标原点作为左上角并没有问题的。

我的意思是，不用显示滚动条，直接让隐藏的部分可见就行了。因为在不显示滚动条的情况下，完全可以让要显示的内容完全可见。你在看看我最初上传的视频，只需要移动一下 -x 区域的元素到 +x 区域，滚动条就消失了，这时候即使再让这个元素回到 -x区域的原位置，滚动条也不会出现了，所以，我的意思是这个滚动条在这个情况下没必要出现。

**Comment by NewByVector** [comment]
是不是调用一下画布内容居中就可以了。
```ts
graph.centerContent()
```

**Comment by 171h** [comment]
> 是不是调用一下画布内容居中就可以了。
> 
> ```ts
> graph.centerContent()
> ```

也是可以的，但是无法从根本上解决问题，因为这样 padding=0 在 graph 尺寸小于 scroller content 的情况下就没有了意义，我觉得最好能提供一个选择，让  scroller content 的尺寸与 graph 永远保持一致，就向我下面代码实现的效果一样：
```ts
scroller.value = graph.value.getPlugin('scroller') as Scroller
scrollerContent.value = scrollerContainer.value.querySelector('.x6-graph-scroller-content') as HTMLDivElement
graph.value.on('resize', ({ width, height }) => {
    Dom.css(scrollerContent.value, { width, height })
})
```
