### ISSUE TITLE
节点双击触发单击事件

### ISSUE THREAD

**Issue by ajesses** [antvis/X6#3716]
### 问题描述

当双击节点时，会先触发两次单击事件，然后再触发单击事件。

### 重现链接

https://codesandbox.io/s/dawn-sky-vnj525

### 重现步骤

1. 监听节点双击和单击事件
2. 双击节点
3. 控制台打印

### 预期行为

能区分双击和单击事件，双击节点不触发单击事件

### 平台

- 操作系统: Windows, Linux
- 网页浏览器: Google Chrome
- X6 版本: 1.34.13

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/X6/assets/20083799/dd72bc9d-9d3e-4f9f-9e46-73dfc14adee6)

**Comment by NewByVector** [comment]
触发双击事件之前会触发两次 click 事件是标准的事件流，html dom 元素也是这样的。
