### ISSUE TITLE
X6ER图如果获取节点内部数据？

### ISSUE THREAD

**Issue by qushencn** [antvis/X6#3719]
### 问题描述

https://x6.antv.antgroup.com/zh/examples/showcase/practices#er
![1688109044532](https://github.com/antvis/X6/assets/29895395/83cd46a9-95e9-4209-9ca4-f7aab29edb04)
点击NAME，如何获取正在点击的NAME行信息

### 重现链接

https://x6.antv.antgroup.com/zh/examples/showcase/practices#er

### 重现步骤

1.点击name

### 预期行为

1.获取正在点击的name行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by qushencn** [comment]
更新描述

**Comment by NewByVector** [comment]
业务数据建议放在 [data](http://x6.antv.antgroup.com/api/model/cell#data) 属性中。
```ts
node.setData({ xxx }) // 设置数据
node.getData() // 获取数据
```
