### ISSUE TITLE
使用graph.centerContent()居中，实际内容以画布左上角为中心居中

### ISSUE THREAD

**Issue by magic-hya** [antvis/X6#3720]
### 问题描述

使用graph.centerContent()居中，实际内容以画布左上角为中心居中
没有以画布的中心居中

### 重现链接

集成工程项目中

### 重现步骤

    graph = new Graph({
        container: document.getElementById('graph-container')!,
        grid: true,
        mousewheel: {
            enabled: true,
            zoomAtMousePosition: true,
            modifiers: 'ctrl',
            minScale: 0.5,
            maxScale: 3,
        },
        connecting: {
            router: {
                name: 'manhattan',
                args: {
                    padding: 1,
                },
            },
            connector: {
                name: 'rounded',
                args: {
                    radius: 8,
                },
            },
            anchor: 'center',
            connectionPoint: 'anchor',
            allowBlank: false,
            snap: {
                radius: 20,
            },
            createEdge() {
                return new Shape.Edge({
                    attrs: {
                        line: {
                            stroke: '#A2B1C3',
                            strokeWidth: 2,
                            targetMarker: {
                                name: 'block',
                                width: 12,
                                height: 8,
                            },
                        },
                    },
                    zIndex: 0,
                })
            },
            validateConnection({ targetMagnet }) {
                return !!targetMagnet
            },
        },
        highlighting: {
            magnetAdsorbed: {
                name: 'stroke',
                args: {
                    attrs: {
                        fill: '#5F95FF',
                        stroke: '#5F95FF',
                    },
                },
            },
        },
        resizing: true,
        rotating: true,
        selecting: {
            enabled: true,
            rubberband: true,
            showNodeSelectionBox: true,
        },
        snapline: true,
        keyboard: true,
        // clipboard: true,
    })

const saveJob = () => {
    console.log("saveJob")
    // console.log(graph.toJSON())
    graph.centerContent()

}

### 预期行为

想得到跟demo一样的居中效果
想知道是什么地方影响到了画布的居中

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

### 屏幕截图或视频（可选）

居中前
![1688109595267](https://github.com/antvis/X6/assets/85269941/35be1e3b-93d4-4ffb-9658-4e44a98ab6cd)
居中后
![image](https://github.com/antvis/X6/assets/85269941/9af86832-c915-47a8-8b73-cc9b9d8b8c2a)

**Comment by jiash1998** [comment]
我也遇到这个问题，我是先重置节点this.graph.resetCells(cells); 然后调用this.graph.centerContent(); 发现也是在左上角。然后我是通过settimeout，设置了一个100毫秒的延迟之后再调用centerContent。我猜测可能是因为新建节点和计算位置居中需要保证一个顺序关系。

**Comment by magic-hya** [comment]
> 我也遇到这个问题，我是先重置节点this.graph.resetCells(cells); 然后调用this.graph.centerContent(); 发现也是在左上角。然后我是通过settimeout，设置了一个100毫秒的延迟之后再调用centerContent。我猜测可能是因为新建节点和计算位置居中需要保证一个顺序关系。

我的居中事件，是按钮触发的，有足够多的时间，所以不存在你说的先后问题，也非常感谢你了

**Comment by NewByVector** [comment]
能否提供一个可以复现的 demo 看下呢？

**Comment by lwstudy** [comment]
![image](https://github.com/antvis/X6/assets/58960791/4cea2405-9c7c-49a2-969b-300289844e7f)
![image](https://github.com/antvis/X6/assets/58960791/dec95ded-cba1-49b4-ba73-a071a307b5a8)
我也遇到同样的问题。如果在mounted中初始完画布与节点后直接居中是会以0，0为中心点

**Comment by flycran** [comment]
我也有这个问题，但我是使用fromJSON后调用centerContent，诡异的是垂直位置跟你们一样在顶部，水平的位置接近居中，但不完全居中
![image](https://github.com/antvis/X6/assets/86134803/c3537792-5784-4dac-882d-23f1bfadc3fa)

**Comment by flycran** [comment]
> 我也有这个问题，但我是使用fromJSON后调用centerContent，诡异的是垂直位置跟你们一样在顶部，水平的位置接近居中，但不完全居中 ![image](https://private-user-images.githubusercontent.com/86134803/291281339-c3537792-5784-4dac-882d-23f1bfadc3fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDMzNDMsIm5iZiI6MTcwMjkwMzA0MywicGF0aCI6Ii84NjEzNDgwMy8yOTEyODEzMzktYzM1Mzc3OTItNTc4NC00ZGFjLTg4MmQtMjNmMWJmYWRjM2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEyMzcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NjgxZjAxY2NjNWYwODFjZjBmZWY3NDkwNDQyZmRjOWJjMjNjOGQyYjg2MWMwZTBmOWVjYTRiZTZmOWQ1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CjCWQYcmHloHdLgYqgj2fQNC2rxKfV5UscudIC8jrl0)

我通过设置容器的高度为100%解决了这个问题，但是它有一些偏移，我不知道这是为什么
![image](https://github.com/antvis/X6/assets/86134803/126443e7-e6c1-4776-a94f-0e3271817fee)
