### ISSUE TITLE
取消或设置选中不会进入resizing状态

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/X6#3724]
### Describe the bug

使用select方法或者unselect方法，不会进入或取消resizing状态

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

使用select方法或者unselect方法，不会进入或取消resizing状态

### Expected behavior

使用select方法或者unselect方法，不会进入或取消resizing状态

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by NewByVector** [comment]
框选和 `resizing` 功能现在是分离的，这个可以自己来实现，比如兼容 node:selected 事件，然后通过 `graph.createTransformWidget(node)` 手动创建  resizing。

**Comment by hhzhldhjl** [comment]
> 框选和 `resizing` 功能现在是分离的，这个可以自己来实现，比如兼容 node:selected 事件，然后通过 `graph.createTransformWidget(node)` 手动创建 resizing。

好的，谢谢

**Comment by zenkiray** [comment]
> 框选和 `resizing` 功能现在是分离的，这个可以自己来实现，比如兼容 node:selected 事件，然后通过 `graph.createTransformWidget(node)` 手动创建 resizing。

能给出例子吗，试过不行，selection和resizing只能二选一，而且graph.select(node)不会触发相关事件，包括node:selected还是selection:changed都不会触发
