### ISSUE TITLE
创建Stencil拖拽模块报错，Uncaught TypeError: Cannot read properties of undefined (reading 'Stencil')

### ISSUE THREAD

**Issue by ouyang091X** [antvis/X6#3734]
### Describe the bug

![image](https://github.com/antvis/X6/assets/40138672/234a0dfb-6f5d-4aa2-9363-c859a9a3a52d)

![image](https://github.com/antvis/X6/assets/40138672/e4d2246b-ef3e-4263-b6a2-619225ff7886)

![image](https://github.com/antvis/X6/assets/40138672/a60a9a57-db3c-4f23-a92b-4ff1e8e252fd)
有引入 但还是报错 Uncaught TypeError: Cannot read properties of undefined (reading 'Stencil') 这是为什么呢

### Your Example Website or App

new Addon.Stencil

### Steps to Reproduce the Bug or Issue

1：安装X6
2：引入Addon
3:  报Uncaught TypeError: Cannot read properties of undefined (reading 'Stencil')

### Expected behavior

不报错，能展示拖拽模块

### Platform

google

**Comment by NewByVector** [comment]
你用的 x6 2.x 版本吧，相关使用方法参考[文档](http://x6.antv.antgroup.com/tutorial/plugins/stencil)。
