### ISSUE TITLE
小地图会影响vue组件，导致vue组件会进两次mounted，性能上可能会有影响。

### ISSUE THREAD

**Issue by liu-leizhi** [antvis/X6#3738]
### Describe the bug

用vue绘制的节点，发现修改数据，监听node.on("change:data", ({ current }) => {console.log(current)}）每次都会输出两个current，我在在mounted的时候去订阅的数据变更，我发现mounted进了两次，逐步排查之后，发现把小地图去掉就不会进两次mounted了。其他的节点暂时还不知道有没有影响，希望排查下。

### Your Example Website or App

https://codesandbox.io/p/sandbox/quirky-forest-7j89x6?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A23%2C3-23%2C78

### Steps to Reproduce the Bug or Issue

graph.use(new MiniMap({ container: document.getElementById("minimap")! })); vue节点会进入两次mounted。

### Expected behavior

加小地图应该不影响节点绘制

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by liu-leizhi** [comment]
![image](https://github.com/antvis/X6/assets/45058642/c73ba426-c295-4a7a-8eab-6c29d063576c)

**Comment by lloydzhou** [comment]
这里。小地图也是一样的组件。进行两次mount是正常的。


你这里的需求，可以参考https://x6.antv.antgroup.com/tutorial/plugins/minimap　文档中针对小地图生成简单的view，这样小地图中的view可以更简单。不用走复杂的逻辑。

**Comment by liu-leizhi** [comment]
> 这里。小地图也是一样的组件。进行两次mount是正常的。
> 
> 你这里的需求，可以参考 [https://x6.antv.antgroup.com/tutorial/plugins/minimap 文档中针对小地图生成简单的view，这样小地图中的view可以更简单。不用走复杂的逻辑。](https://x6.antv.antgroup.com/tutorial/plugins/minimap%E3%80%80%E6%96%87%E6%A1%A3%E4%B8%AD%E9%92%88%E5%AF%B9%E5%B0%8F%E5%9C%B0%E5%9B%BE%E7%94%9F%E6%88%90%E7%AE%80%E5%8D%95%E7%9A%84view%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%B0%8F%E5%9C%B0%E5%9B%BE%E4%B8%AD%E7%9A%84view%E5%8F%AF%E4%BB%A5%E6%9B%B4%E7%AE%80%E5%8D%95%E3%80%82%E4%B8%8D%E7%94%A8%E8%B5%B0%E5%A4%8D%E6%9D%82%E7%9A%84%E9%80%BB%E8%BE%91%E3%80%82)

我这个是小地图一开始应该就创建好了，后面创建的vue节点每次都会进两次mounted，是自定义vue节点的mounted。

**Comment by liu-leizhi** [comment]
> 这里。小地图也是一样的组件。进行两次mount是正常的。
> 
> 你这里的需求，可以参考 [https://x6.antv.antgroup.com/tutorial/plugins/minimap 文档中针对小地图生成简单的view，这样小地图中的view可以更简单。不用走复杂的逻辑。](https://x6.antv.antgroup.com/tutorial/plugins/minimap%E3%80%80%E6%96%87%E6%A1%A3%E4%B8%AD%E9%92%88%E5%AF%B9%E5%B0%8F%E5%9C%B0%E5%9B%BE%E7%94%9F%E6%88%90%E7%AE%80%E5%8D%95%E7%9A%84view%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%B0%8F%E5%9C%B0%E5%9B%BE%E4%B8%AD%E7%9A%84view%E5%8F%AF%E4%BB%A5%E6%9B%B4%E7%AE%80%E5%8D%95%E3%80%82%E4%B8%8D%E7%94%A8%E8%B5%B0%E5%A4%8D%E6%9D%82%E7%9A%84%E9%80%BB%E8%BE%91%E3%80%82)

![image](https://github.com/antvis/X6/assets/45058642/b984cef8-bd7f-4abc-9764-49381b69dc21)

**Comment by lloydzhou** [comment]
小地图，也是一个画布。
节点需要在主画布展示，同时也需要在小地图展示。
所以，这个节点需要挂载两次，这是正常流程。

**Comment by liu-leizhi** [comment]
> 小地图，也是一个画布。 节点需要在主画布展示，同时也需要在小地图展示。 所以，这个节点需要挂载两次，这是正常流程。
明白了，谢谢。那我用那个简单视图展示，用这个绘的节点多了明显的有感觉变慢了。
