### ISSUE TITLE
怎样让指定节点高亮

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/X6#3744]
### 问题描述

cellView.highlight(elem, { 
  highlighter: {
    name: 'stroke',
    args: {
      padding: 4,
      attrs: {
        'stroke-width': 2,
        stroke: 'red',
      }
    },
  },
})
文档每太看懂，我cellView是使用graph.findView(cell)获取到的，其中cell是我要高亮的节点。后边这个elem参数应该传什么？我传的cell这个参数也没有效果

### 重现链接

无

### 重现步骤

无

### 预期行为

cell这个节点可以高亮

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by hhzhldhjl** [comment]
解决了，第一个参数需要传view.container

**Comment by love666** [comment]
所以怎么实现的高亮呀~
