### ISSUE TITLE
v1和v2自定义节点注册区别

### ISSUE THREAD

**Issue by recolzhao** [antvis/X6#3745]
### 问题描述

v1注册
![image](https://github.com/antvis/X6/assets/93312109/4130d586-deac-44fd-83ca-e1cc7e502177)
v1渲染
![image](https://github.com/antvis/X6/assets/93312109/18e5e1cd-868b-4b0b-9b89-ffa1f05fa9c3)
v2注册
![image](https://github.com/antvis/X6/assets/93312109/c32ce9ee-23d6-4c6b-8b29-8e7c1acf6076)
v2渲染
![image](https://github.com/antvis/X6/assets/93312109/9a3f2b7c-a325-40e9-b793-93bcbc5ae5df)

都在attrs里的body写了但是v2的无效

### 重现链接

无

### 重现步骤

/

### 预期行为

和v1版本一样

### 平台

- 操作系统: Windows,
- 网页浏览器: Google Chrome
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
v2 中默认去掉了这个 rect 元素，你可以通过在注册的时候添加 `primer:rect` 来实现之前的效果。
