### ISSUE TITLE
fromJSON在页面节点渲染完成后的事件监听有吗？

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/X6#3746]
### 问题描述

需要在页面渲染完成后给指定节点增加高亮效果，但是highlight(ele)函数的第一个参数需要是element节点，fromJSON还没有渲染完成导致高亮失败，我给高亮函数外套个定时器就可以高亮，所以想问下有没有渲染完成的事件监听，render:done函数在2.0没有执行

### 重现链接

无

### 重现步骤

无

### 预期行为

fromJSON后在页面节点渲染完成后的监听

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
可以使用[视图](http://x6.antv.antgroup.com/tutorial/basic/events#%E8%A7%86%E5%9B%BE)事件。
