### ISSUE TITLE
removeCells()之后再addCell()添加的节点数据没有任何关系，报错getZIndex

### ISSUE THREAD

**Issue by King-zuimx** [antvis/X6#3748]
### 问题描述

Uncaught TypeError: Cannot read properties of null (reading 'getZIndex')

我在使用的过程中有这么一个场景，我需要删除一些节点然后再添加一些节点数据。

代码中
![image](https://github.com/antvis/X6/assets/12727375/d44a8780-c023-4c65-b72c-450fdc91f862)

会出现下面的错误
![image](https://github.com/antvis/X6/assets/12727375/aa0aab66-b5c1-4cda-9586-255c756e6306)

### 重现链接

无

### 重现步骤

1、我把一些节点数据保存为json
2、我通过遍历我的数据，来修改这个json
3、再把这个json用parseJSON转成节点数组
4、我更新我自己的数据，来修改这个json，在修改中会删除原来的节点，根据新数据添加成新的节点。
5、接下来就出现了上面的错误。

### 预期行为

我期望删除和添加节点之后，不报错。

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- X6 版本: [1.34.13]

**Comment by NewByVector** [comment]
能否提供一个可以复现的 demo？

**Comment by King-zuimx** [comment]
我下个星期抽个时间给你写个

**Comment by lloydzhou** [comment]
看一下版本号，我映像中之前v1.x有出现过类似的问题。好像处理过

**Comment by NewByVector** [comment]
因为无法复现，暂时关闭。

**Comment by jiang-zhong-xi** [comment]
这有个链接：https://codesandbox.io/s/zealous-sid-pps33n?file=/src/index.ts  浮现了类似问题。 @NewByVector
