### ISSUE TITLE
x6-vue-shape是否可以支持除了provide，在h渲染函数通过props传入方法

### ISSUE THREAD

**Issue by gxy5202** [antvis/X6#3756]
### Describe the feature you'd like to request

由于是机密项目，所以无法提供源码环境，但是可以描述现在的问题。项目是vue3+X6。通过webpack进行模块联邦打包，作为一个微前端应用提供给其他项目使用，但是经过webpack打包后，由于作用域的原因，x6-vue-shape插件通过provide提供的方法无法注册到vue实例上，导致inject获取不到getNode方法。

### Describe the solution you'd like

在我研读源码后，发现x6-vue-shape在通过h函数渲染时可以将getNode等方法直接通过props传入，即可解决该问题

### Describe alternatives you've considered

由于构建和打包工具的不同，我们无法预测用户使用的哪种打包环境，而由于Vue在不同构建工具下打包出来的作用域可能会有所不同，特别是模块联邦这种比较特殊的场景，所以希望插件能提供一种较稳定的方式。

**Comment by NewByVector** [comment]
期待 vue 大神来解决该问题。👩‍💻

**Comment by gxy5202** [comment]
> 期待 vue 大神来解决该问题。👩‍💻

已提交pr

**Comment by NewByVector** [comment]
请升级 @antv/x6-vue-shape 到 2.1.1 版本。
