### ISSUE TITLE
关于Scroller插件的transitionToRect()方法无法正常使用

### ISSUE THREAD

**Issue by jefferyjeff** [antvis/X6#3757]
### 问题描述

在Vue加载Scroller插件和 单独使用Scroller插件时，
插件的transitionToRect()按1.0版本代入参数使用，在node:collapse点击后，动画开始时正常执行，执行到最后一步是出现错误，导致动画回退到错误发生时的状态，节点大小和布局都被打乱

### 重现链接

//

### 重现步骤

1. 设置node的collapse展开关闭状态，并在模型上定义button的node:collapse事件
2. 监听node:collapse事件，并点击
3. 获取node的box后传递给transitionToRect()
4. 动画开始执行，执行到快完成时报错length undefined
5. 错误位置在于 x6-common/src/dom/event/core.ts，在传入事件时，最后一个handles没有传入

### 预期行为

transitionToRect能同1.0版本一样使用

### 平台

- 操作系统: Windows
- 网页浏览器: [Google Chrome, Safari, Firefox ]
- X6 版本: [2.11.1]

### 屏幕截图或视频（可选）

![TRANS错误](https://github.com/antvis/X6/assets/41991947/c6c6dec8-b36c-4377-9e0a-712f467f4d69)
![core错误](https://github.com/antvis/X6/assets/41991947/325c1335-fcb5-4ec2-9229-1a1b192feb7d)

**Comment by NewByVector** [comment]
能否基于这个[模板](https://codesandbox.io/s/mo-ban-55i8dp)提供一个可以复现的 demo?
