### ISSUE TITLE
请问2.0的animation插件包大约需要多久发布，挺着急用这块的

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/X6#3759]
### 问题描述

请问2.0的animation插件包大约需要多久发布，挺着急用这块的

### 重现链接

无

### 重现步骤

请问2.0的animation插件包大约需要多久发布，挺着急用这块的

### 预期行为

请问2.0的animation插件包大约需要多久发布，挺着急用这块的

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
请问你需要哪些功能？

**Comment by hhzhldhjl** [comment]
> 请问你需要哪些功能？

需要添加动画animate和animateTransform都需要，这个2.0好像在核心包里给删掉了，但是插件包好像一直还没有发布

**Comment by NewByVector** [comment]
我这两天发布一个最简单的心得动画插件，包含你的功能。

**Comment by hsyxxi** [comment]
我也是需要这个animation，用了2.0版本没想到这个被干掉了，要不是这条，我都准备降版本了

**Comment by hhzhldhjl** [comment]
> 我这两天发布一个最简单的心得动画插件，包含你的功能。
好的，谢谢

**Comment by ajesses** [comment]
你好，请问这个动画插件发布是在哪里，我没找到，目前也需要这个功能

> 我这两天发布一个最简单的心得动画插件，包含你的功能。

**Comment by NewByVector** [comment]
十分抱歉，最近带宽实在不够，这个要延期了，抱歉。

**Comment by bighhhh** [comment]
> 十分抱歉，最近带宽实在不够，这个要延期了，抱歉。

请问这个大约要多久上线啊？简单版的也可以，我其他功能都做完了，就差这个动画了
