### ISSUE TITLE
关于在图层外添加按钮，图层失去焦点按钮点不到问题

### ISSUE THREAD

**Issue by qq12157138** [antvis/X6#3762]
### 功能描述

我有个需求如图，我需要在图层外添加按钮。
效果：鼠标移入图层显示按钮，鼠标移出就隐藏按钮。
问题：图层和按钮之间有缝隙，那么移到缝隙处还没接触到按钮的时候，图层鼠标移出事件触发了就把按钮隐藏了，然后按钮就点不到了。

<img width="304" alt="image" src="https://github.com/antvis/X6/assets/15812485/7f36edb1-b88c-4420-835e-e81bd44a2b2c">

### 期望解决方案

希望效果：图层和按钮之间是不是应该有个隐藏层把这两部分化为一个整体。但是在点击图层的时候给图层高亮的时候不要把隐藏图层算进去。这样的话，按钮事件也能独立处理了，不会点击按钮就触发图层的事件了

**Comment by NewByVector** [comment]
上面的节点是什么类型的节点呢？如果是 react/vue 节点，这个问题本身就是一个 react/vue 问题。

**Comment by qq12157138** [comment]
> 上面的节点是什么类型的节点呢？如果是 react/vue 节点，这个问题本身就是一个 react/vue 问题。

vue

**Comment by NewByVector** [comment]
可以参考这个 [demo](https://codesandbox.io/s/jie-dian-jia-hao-jqyxhd)。
