### ISSUE TITLE
使用vue自定义节点时，toPNG导出的图片无法获取写在style中的样式

### ISSUE THREAD

**Issue by YUST2020** [antvis/X6#3764]
### Describe the bug

在自定义vue组件内，如果写成<di-v class="node"></div>形式，导出图片时样式不生效，只有以内联样式的形式写在里面才生效

### Your Example Website or App

no inline

### Steps to Reproduce the Bug or Issue

1.绘制
2.调用graph.toPNG
3.回调获取src，显示在页面上，发现样式缺失

### Expected behavior

无

### Screenshots or Videos

![222](https://github.com/antvis/X6/assets/73179372/731c0756-0482-4e7a-a08f-6eaf38a6fa2e)

### Platform

- OS:Windows
- Browser: Chrome
- Version:
- vue@2.7.14
├── @antv/x6-plugin-clipboard@2.1.6       
├── @antv/x6-plugin-export@2.1.6
├── @antv/x6-plugin-history@2.2.3
├── @antv/x6-plugin-keyboard@2.2.1        
├── @antv/x6-plugin-scroller@2.0.9
├── @antv/x6-plugin-selection@2.1.7
├── @antv/x6-plugin-snapline@2.1.7
├── @antv/x6-plugin-stencil@2.0.3
├── @antv/x6-plugin-transform@2.1.7
├── @antv/x6-vue-shape@2.0.11
├── @antv/x6@2.11.1

**Comment by NewByVector** [comment]
可以在导出配置中将缺少的样式补充上。
```ts
this.graph.toSVG((dataUri: string) => {
  // todo
}, {
  stylesheet: `
    rect {
      fill: red;
    }
  ` 
})
```
