### ISSUE TITLE
Shadow filter issues with straight lines

### ISSUE THREAD

**Issue by tmarsik42** [antvis/X6#3766]
### Describe the bug

Straight line disappears when applying a shadow filter to it.

Possibly relevant information on why it happens.
https://www.w3.org/TR/SVG/coords.html#ObjectBoundingBoxUnits
> Keyword objectBoundingBox should not be used when the geometry of the applicable element has no width or no height, such as the case of a horizontal or vertical line, even when the line has actual thickness when viewed due to having a non-zero stroke width since stroke width is ignored for bounding box calculations. When the geometry of the applicable element has no width or height and objectBoundingBox is specified, then the given effect (e.g., a gradient or a filter) will be ignored.

### Your Example Website or App

https://codesandbox.io/s/intelligent-http-cmwghc?file=/index.ts

### Steps to Reproduce the Bug or Issue

 In a reproduction I've copied an example from here https://x6.antv.vision/en/docs/api/registry/filter and made three lines.
1. straight line with a shadow
2. line crooked vertically by 1px with a shadow
3. straight line without shadow

### Expected behavior

visible straight line with a shadow

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome, Safari, Firefox,...]
- Version: [e.g. 2.11.1]

**Comment by NewByVector** [comment]
使用 filterUnits 属性可以解决该问题。

```ts
filter: {
  name: 'dropShadow',
  args: {
    dx: 2,
    dy: 2,
    blur: 3,
    color: 'skyblue',
  },
  attrs: {
    width: "100%",
    height: "100%",
    filterUnits: "userSpaceOnUse"
  }
}
```
可以参考这个 [demo](https://codesandbox.io/s/lian-xian-de-lu-jing-xiao-guo-7byd7b?file=/src/App.tsx:1127-1283)。

**Comment by tmarsik42** [comment]
I see, I can say I understand it much better on how it works now. Thank you. Sorry I could not figure it out from docs but some things are hard to translate from chinese to english for me .
