### ISSUE TITLE
使用vue自定义节点时注入方法没有了getGraph方法，1.x的版本是有的，2.x的没有了

### ISSUE THREAD

**Issue by zhangsab** [antvis/X6#3771]
### 问题描述

从自定义节点获取画布，原来有getGraph方法，现在没有了，那应该怎么在节点内获取画布？

### 重现链接

无

### 重现步骤

1.创建自定义vue节点
2.inject getGraph方法
3.提示getGraph不是一个方法

### 预期行为

期望能正常获取到graph

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by zhangsab** [comment]
使用的版本是2.0.0，以上写的有误

**Comment by NewByVector** [comment]
更新到最新版本，是有的。

**Comment by zhangsab** [comment]
> 更新到最新版本，是有的。

生效了，感谢
