### ISSUE TITLE
x6-react-shape安装后启动报错

### ISSUE THREAD

**Issue by reiken** [antvis/X6#3774]
### Describe the bug

安装 @antv/x6-react-shape 后启动报错

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

tnpm install @antv/x6-react-shape --save
import '@antv/x6-react-shape';
![image](https://github.com/antvis/X6/assets/3362469/d2358a82-ff9b-4e8e-bbe8-0e7a83bbf2e3)

### Expected behavior

安装 @antv/x6-react-shape 后启动报错

### Platform

- OS: macOS
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by NewByVector** [comment]
最新版本的 react-shape 只支持 react 18 。如果你的项目中用了 react < 18, 请把 @antv/x6-react-shape 版本锁定在 2.0.8。

**Comment by mocha-opts** [comment]
> 最新版本的 react-shape 只支持 react 18 。如果你的项目中用了 react < 18, 请把 @antv/x6-react-shape 版本锁定在 2.0.8。

您好，我认为这个问题最好在文档中说明一下，因为大部分 react 项目都还在 18 版本以下，这个报错很容易造成 V2 版本不支持 react 18 以下的误解。
