### ISSUE TITLE
关于edge边禁用框选和选择能力以后还是会出现框选的问题

### ISSUE THREAD

**Issue by dinghaining** [antvis/X6#3781]
### Describe the bug

在graph开启showEdgeSelectionBox以后，我做了一个双击开启工具tools，然后同时使用disableSelection以及disableRubberband禁用了选择能力和框选，但是一旦使用选择路径点的工具黄色的选择框就会又出现了

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

开启showEdgeSelectionBox
画一条边
关闭选择能力和框选
使用tools增加路径点或者移动路径点
黄色选择框再次出现

### Expected behavior

禁止选择之后不再出现选择框

### Screenshots or Videos

https://github.com/antvis/X6/assets/77276311/d89a9c5c-938e-4632-be2a-1f4b5f4bee97

### Platform

无

**Comment by NewByVector** [comment]
我本地试了一下，`disableSelection` 后使用 `vertices` 工具任然无法出现框选现象。请提供一个可以复现的 demo。

**Comment by NewByVector** [comment]
因为无法复现，暂时关闭。
