### ISSUE TITLE
开启滚动及小地图后画布显示不全，元素被隐藏

### ISSUE THREAD

**Issue by Theseven87** [antvis/X6#3782]
### Describe the bug

![image](https://github.com/antvis/X6/assets/20855910/a8dae25a-91db-49ec-a753-3ff687aaba8b)
从右下小地图能看出，可视区域非常窄，平移画布的时候会导致元素显示不全甚至是完全被遮挡

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1：实例化graph
2：启用滚动和小地图
3：画布中添加元素
4：平移画布

注：在我的例子中实例化graph时只接受了一个el，然后通过动态创建dom的为画布和小地图创建容器，并添加至el容器中

### Expected behavior

元素不该被剪切或隐藏

### Platform

- OS: [ Windows]
- Browser: [ Chrome]
- Version: [2.11.5]

### Additional context

已解决，当开启画布滚动和小地图的时候，实例化Graph时需要将panning设置为false就好了

_No response_

**Comment by NewByVector** [comment]
能否可以基于 [demo](https://codesandbox.io/s/mo-ban-55i8dp) 提供一个可以复现的例子。

**Comment by Theseven87** [comment]
> 能否可以基于 [demo](https://codesandbox.io/s/mo-ban-55i8dp) 提供一个可以复现的例子。

https://codesandbox.io/p/sandbox/x6tooldemo-832m4f?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A16%2C48
这个是demo场景
但是功能我是写了一个包，通过npm安装的

**Comment by TLovers** [comment]
确实有这个问题，但是不开启搞滚动，小地图显示就异常了

**Comment by JackieCheung** [comment]
> panning

同样的问题
 ```
graph.use(
        new Scroller({
          enabled: true,
          pannable: true
        })
      )
      .use(
        new MiniMap({
          container: minimapRef.value,
          scalable: false,
          width: 200,
          height: 120
        })
      )
```
开启scroller的滚动和minimap就会显示不全，画布的 panning 不设置默认就是 false 的，有什么解决方案吗？

**Comment by zm9913** [comment]
这个问题关了是解决了吗？
