### ISSUE TITLE
能否支持动态显隐小地图？

### ISSUE THREAD

**Issue by sh4wmoo** [antvis/X6#3784]
### 问题描述

个人认为小地图的初衷，应该是在用户无法完整的看到所有元素的情况下才需要的。那么能否支持提供一个参数，来根据当前画布与元素的容纳情况，来动态显隐小地图？

退而求其次：
![image](https://github.com/antvis/X6/assets/34166509/975c32e2-327d-40cc-92f2-e1b873171e9d)
根据上述api可以直接设置容纳所有元素。

请问能否提供API可以监听当前画布是否容纳了所有元素？

### 重现链接

无

### 重现步骤

预期无法实现

### 预期行为

方案1：当画布没有容纳所有元素时，自动触发小地图的显示，画布容纳了所有元素后，自动隐藏。
方案2：提供API可以监听当前画布是否容纳了所有元素，开发者自行完成期望目标

### 平台

- 操作系统: [Windows.]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.2.1]
- minimap版本:[2.0.5]

**Comment by NewByVector** [comment]
1. 判断是否所有节点都处于可视区域内部可以通过节点的坐标来计算。
2. 显示隐藏小地图可以通过 css 样式来显隐小地图容器。

**Comment by sh4wmoo** [comment]
> 
css隐藏小地图没问题，但是只通过“节点的坐标"来判断是否所有节点都处于可视区域内，是否有待商榷?用户的行为可能是：拖拽

**Comment by NewByVector** [comment]
判断的逻辑就是计算所有节点的坐标是否在可视区域内部，大致代码：
```ts
const nodes = graph.getNodes()
const allInView = nodes.every((node) => {
  return node.getBBox().intersectsWithRect(graph.getGraphArea())
})
```
不过你上面也说了，后面会有很多操作会改变上面结果，所以你需要监听 `节点增删`、`画布平移`、`画布缩放` 等事件去重新计算上面结果。

**Comment by sh4wmoo** [comment]
> 判断的逻辑就是计算所有节点的坐标是否在可视区域内部，大致代码：
> 
> ```ts
> const nodes = graph.getNodes()
> const allInView = nodes.every((node) => {
>   return node.getBBox().intersectsWithRect(graph.getGraphArea())
> })
> ```
> 
> 不过你上面也说了，后面会有很多操作会改变上面结果，所以你需要监听 `节点增删`、`画布平移`、`画布缩放` 等事件去重新计算上面结果。

好的 我先按照这种方式试一下。

**Comment by sh4wmoo** [comment]
> 判断的逻辑就是计算所有节点的坐标是否在可视区域内部，大致代码：
> 
> ```ts
> const nodes = graph.getNodes()
> const allInView = nodes.every((node) => {
>   return node.getBBox().intersectsWithRect(graph.getGraphArea())
> })
> ```
> 
> 不过你上面也说了，后面会有很多操作会改变上面结果，所以你需要监听 `节点增删`、`画布平移`、`画布缩放` 等事件去重新计算上面结果。

这个方案被否定了，暂时不考虑这个需求。还有个问题请问一下，issue#3778的，我看到已经对vertices tool进行了完善，增加了[modifiers]。那么请问有没有发布计划？何时才能发布到NPM上？

**Comment by NewByVector** [comment]
@sh4wmoo 已经发布了哈。
