### ISSUE TITLE
请问，我该如何判断某个节点是否被连线了？

### ISSUE THREAD

**Issue by qq12157138** [antvis/X6#3786]
### Describe the feature you'd like to request

需求：节点A、节点B，节点A连线了节点B，如果有连线节点B删除的时候要带着节点A一起删除。
效果：我删除节点B的时候如何知道节点B是否被连线了？连线的源头又是哪个？

### Describe the solution you'd like

我删除节点B的时候如何知道节点B是否被连线了？连线的源头又是哪个？

### Describe alternatives you've considered

看API好像没合适的方法。这个我从哪个方面去找呢

**Comment by snail88** [comment]
https://x6.antv.antgroup.com/api/mvc/model#getoutgoingedges

**Comment by qq12157138** [comment]
只能从全部中遍历吗，有没有办法逆向推导呢。

> https://x6.antv.antgroup.com/api/mvc/model#getoutgoingedges

**Comment by xingke55** [comment]
const edges = graph.model.getIncomingEdges(nodeB)
for(let edge of edges){
}

**Comment by xingke55** [comment]
const edges = graph.model.getIncomingEdges(nodeB)
for(let edge of edges){
let source =edge.getSourceCell()

}
