### ISSUE TITLE
2.x版本出现的问题

### ISSUE THREAD

**Issue by sunyanqing01** [antvis/X6#3790]
### Describe the bug

使用2.x版本使用ER图案例渲染节点出现错误的，但使用1.x版本不会报错，但是渲染出的节点无法拖动，节点数量166个，
![image](https://github.com/antvis/X6/assets/43230630/7f86ed13-ead1-4cec-9d4b-c66069731a71)
使用1.X版本
![image](https://github.com/antvis/X6/assets/43230630/6d3a2930-bddb-4b9d-83f1-9bbef636e751)
这是否是版本BUG？
节点过多怎么支持流畅运行呢，现在是直接卡住，无法拖动

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

1

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by America-first-melon** [comment]
mark

**Comment by NewByVector** [comment]
官网案例并没有出错，能否提供一个可以复现的 demo？

**Comment by NewByVector** [comment]
因为无法复现问题，暂时关闭。
