### ISSUE TITLE
使用vue2自定义的节点 如何对自定义节点的数据进行保存和初始化时赋值呢

### ISSUE THREAD

**Issue by History-1024** [antvis/X6#3791]
### 问题描述

如何对自定义节点的数据进行保存和初始化时赋值呢

### 重现链接

暂无

### 重现步骤

对官网的数据加工DVG图进行了些修改 让节点变成了使用vue2组件自定义开发的，我想知道如何将每个节点中的数据，提取出来并保存为json。在下次打开图表时，渲染节点对vue组件进行传值并将值展示图表的节点上。

这是我写的demo示例图
![image](https://github.com/antvis/X6/assets/65716967/2f904b86-7f38-454e-a5c3-1e215a7960b7)
这是我自定义组件部分
![image](https://github.com/antvis/X6/assets/65716967/d59ed42c-1762-40ee-9da1-4d867255e73a)
这是我引入组件自定义节点部分
![image](https://github.com/antvis/X6/assets/65716967/418aade8-535f-4f7b-8fb5-e98aba7785d7)

### 预期行为

我期望可以给我提供一些方案或者api以解决眼前这个问题，非常感谢

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by cnyballk** [comment]
toJSON+fromJSON不就可以了么

**Comment by History-1024** [comment]
能发个示例吗 谢谢

**Comment by cnyballk** [comment]
https://x6.antv.antgroup.com/api/mvc/model#tojson
https://x6.antv.antgroup.com/api/mvc/model#fromJSON
