### ISSUE TITLE
examples 无法启动

### ISSUE THREAD

**Issue by BinWu1989** [antvis/x6#38]
根据项目中的源代码,运行examples-drawio项目时，无法编译项目,启动时也无法启动
(1)npm install时出错,提示可能是权限问题,yarn install无该错误
(2)启动项目时出错,无法正常启动

**Comment by BinWu1989** [comment]
烦请提供一个example的相关文档，如何编译，启动服务

**Comment by bubkoo** [comment]
> 烦请提供一个example的相关文档，如何编译，启动服务

按照下面步骤试试：
1. 在根目录 yarn bootstrap
2. cd ./examples/x6-example-drawio
3. yarn start

**Comment by loongmxbt** [comment]
@BinWu1989 比较简单的方法可以将examples目录的文件夹单独复制出去，安装依赖运行。

**Comment by BinWu1989** [comment]
@bubkoo 根据您的操作指引，在根目录下运行yarn bootstrap时仍然有错误信息,详见如下，平台:window

`$ lerna bootstrap && yarn build:core
lerna notice cli v3.19.0
lerna info versioning independent
lerna info bootstrap root only
[1/4] Resolving packages...
success Already up-to-date.
$ lerna run build --ignore @antv/x6-example-* --parallel
lerna notice cli v3.19.0
lerna info versioning independent
lerna notice filter excluding "@antv/x6-example-*"
lerna info filter [ '!@antv/x6-example-*' ]
lerna info Executing command in 2 packages: "yarn run build"
@antv/x6-components: $ run-s lint clean
@antv/x6: $ run-s lint clean
@antv/x6: $ run-s lint:ts lint:es
@antv/x6-components: $ run-s lint:ts lint:es lint:style
@antv/x6: $ tslint -c tslint.json -p tsconfig.json --fix
@antv/x6-components: $ tslint -c tslint.json -p tsconfig.json --fix
@antv/x6-components: $ eslint --ext .js scripts --fix
@antv/x6-components: $ stylelint 'src/**/*.less' --syntax less --fix
@antv/x6-components: Error: No files matching the pattern "'src/**/*.less'" were found.
@antv/x6-components:     at globby.then (D:\git\x6\packages\x6-components\node_modules\stylelint\lib\standalone.js:211:12)
@antv/x6-components: error Command failed with exit code 1.
@antv/x6-components: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@antv/x6-components: ERROR: "lint:style" exited with 1.
@antv/x6-components: error Command failed with exit code 1.
@antv/x6-components: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@antv/x6-components: ERROR: "lint" exited with 1.
@antv/x6-components: error Command failed with exit code 1.
@antv/x6-components: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@antv/x6-components'
lerna ERR! yarn run build stdout:
$ run-s lint clean
$ run-s lint:ts lint:es lint:style
$ tslint -c tslint.json -p tsconfig.json --fix
$ eslint --ext .js scripts --fix
$ stylelint 'src/**/*.less' --syntax less --fix
Error: No files matching the pattern "'src/**/*.less'" were found.
    at globby.then (D:\git\x6\packages\x6-components\node_modules\stylelint\lib\standalone.js:211:12)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
error Command failed with exit code 1.
ERROR: "lint:style" exited with 1.
error Command failed with exit code 1.
ERROR: "lint" exited with 1.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@antv/x6-components'`

**Comment by BinWu1989** [comment]
@bubkoo @loongmxbt 请问该问题是否有进展了？
