### ISSUE TITLE
官网draw例子开启scroller：true之后，网格背景被覆盖

### ISSUE THREAD

**Issue by daigang666** [antvis/X6#380]
![84AB945A-C3AD-485a-9E67-3633C4A7D653](https://user-images.githubusercontent.com/42136433/101432430-d55a7780-3943-11eb-9fd7-f1d381d3b1fc.png)
![E1DBBA24-E753-44b7-9C96-5F481D12ECB8](https://user-images.githubusercontent.com/42136433/101432440-da1f2b80-3943-11eb-98bf-c99bbcc17dd3.png)

**Comment by NewByVector** [comment]
先css修改下 x6-graph-grid 的 z-index

**Comment by daigang666** [comment]
> 先css修改下 x6-graph-grid 的 z-index

设置x6-graph-grid的z-index之后就无法选中节点了
