### ISSUE TITLE
本月有没有发布计划

### ISSUE THREAD

**Issue by sh4wmoo** [antvis/X6#3800]
### 问题描述

针对issue#3778，我看到已经对vertices tool进行了完善，增加了[modifiers]。那么请问有没有发布计划？何时才能发布到NPM上？

### 重现链接

-

### 重现步骤

-

### 预期行为

-

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
@antv/x6@2.13.1
