### ISSUE TITLE
图片节点中的图在缩放过程中始终等比例缩放

### ISSUE THREAD

**Issue by wenhaoxu1** [antvis/X6#3801]
### 问题描述

图片节点中的图在缩放过程中始终等比例缩放
![image](https://github.com/antvis/X6/assets/107562946/049fd755-18f6-4249-b7c5-34a06030f45f)

### 重现链接

https://x6.antv.antgroup.com/zh/examples/node/native-node/#image

### 重现步骤

随便缩放一下

### 预期行为

我期望它的效果是这样的
![image](https://github.com/antvis/X6/assets/107562946/5498e231-da0d-4f3d-b27f-12adad65ef89)

### 平台

- 操作系统: [Windows.]
- 网页浏览器: [Google Chrome.]
- X6 版本: [2.11.1 ...]

**Comment by wenhaoxu1** [comment]
> 可以考虑使用 rect 节点，然后图片只是背景。

尝试过但是并不可以

**Comment by zfy171** [comment]
svg图标都不支持放大缩小

**Comment by zfy171** [comment]
> > 可以考虑使用 rect 节点，然后图片只是背景。
> 
> 尝试过但是并不可以

有后续解决办法吗

**Comment by zfy171** [comment]
我已经解决该问题 我通过手动改变dom样式进行解决 
手动给svg画布中的image标签添加属性 preserveAspectRatio
![image](https://github.com/antvis/X6/assets/70139873/68334171-089f-422a-ada1-da91a5474278)

**Comment by wh356667852** [comment]
我也遇到了同样的问题，但是感觉上面通过定时器的方式不太好，还有其他更好的方式吗？

**Comment by zfy171** [comment]
> 我也遇到了同样的问题，但是感觉上面通过定时器的方式不太好，还有其他更好的方式吗？

暂时没有 除非手动去改本地引用的包 我现在写法是监听节点增加 同时为了避免获取不到新增的节点 我才手动加了延时计时器

**Comment by NewByVector** [comment]
感谢 @zfy171 提供的思路，直接这样就可以了：
```ts
graph.addNode({
  shape: 'image',
  x: 320,
  y: 120,
  width: 94,
  height: 28,
  imageUrl:
    'https://gw.alipayobjects.com/os/s/prod/antv/assets/image/logo-with-text-73b8a.svg',
  attrs: {
    image: {
      preserveAspectRatio:'none'
    }
  }
})

```

**Comment by wh356667852** [comment]
> 感谢 @zfy171 提供的思路，直接这样就可以了：
> 
> ```ts
> graph.addNode({
>   shape: 'image',
>   x: 320,
>   y: 120,
>   width: 94,
>   height: 28,
>   imageUrl:
>     'https://gw.alipayobjects.com/os/s/prod/antv/assets/image/logo-with-text-73b8a.svg',
>   attrs: {
>     image: {
>       preserveAspectRatio:'none'
>     }
>   }
> })
> ```

这个方案可行，我已经测试成功了，成功解决了我的问题。
