### ISSUE TITLE
树形布局Hierarchy在没有文档

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/X6#3809]
### 问题描述

树形布局Hierarchy在没有文档

### 重现链接

无

### 重现步骤

树形布局Hierarchy在没有文档

### 预期行为

在哪能找到完整的布局文档，官网的文档有点简单而且很多布局没有找到对应的文档呢

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
可以结合 [d3-hierarchy](https://github.com/d3/d3-hierarchy#hierarchy) 来看。

**Comment by aimilu** [comment]
G6有完整文档，可以参考https://g6.antv.antgroup.com/api/tree-graph-layout/mindmap
