### ISSUE TITLE
边上工具 - [source-arrowhead] - [tagName]参数无效

### ISSUE THREAD

**Issue by sh4wmoo** [antvis/X6#3811]
### 问题描述

边上工具 - [source-arrowhead] - [tagName]参数无效

### 重现链接

-

### 重现步骤

![image](https://github.com/antvis/X6/assets/34166509/360d78ef-4d64-48ce-ac64-5d687d458f59)

```
cell.addTools([
        {
          name: 'source-arrowhead',
          args:{
            tagName:'circle',
            attrs: {
              fill: 'red',
            },
          }
        },
      ])
```

使用如上代码，渲染出的箭头仍然是path类型。

### 预期行为

期望根据传参改变箭头样式，兼容内置的箭头类型即可

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.13.1]

**Comment by NewByVector** [comment]
有没有复现 demo 呢，我看官网例子 https://codesandbox.io/s/rhppls 是好的呀。

**Comment by sh4wmoo** [comment]
> 有没有复现 demo 呢，我看官网例子 https://codesandbox.io/s/rhppls 是好的呀。

知道了，是需要再注册一个自定义边上工具，然后声明tagName，再使用就可以了。直接写tagName是无效的
