### ISSUE TITLE
请问morkup中可以用自定义vue节点吗？自定义vue节点的自定义属性应该怎样设置呢？也是用setProp吗？组件内怎样接收呢

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/X6#3812]
### 问题描述

请问morkup中可以用自定义vue节点吗？自定义vue节点的自定义属性应该怎样设置呢？也是用setProp吗？组件内怎样接收呢

### 重现链接

无

### 重现步骤

请问morkup中可以用自定义vue节点吗？自定义vue节点的自定义属性应该怎样设置呢？也是用setProp吗？组件内怎样接收呢

### 预期行为

想要将多个vue节点通过morkup组合为一个节点
想要通过node或cell对象给自定义vue节点设置自定义属性

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by hhzhldhjl** [comment]
自定义vue节点在removeAttrByPath的时候，节点消失了，断点查看是node.js的render方法中，empty方法清空内容但renderMarkup重新插入节点失败了好像

**Comment by hhzhldhjl** [comment]
removeAttrByPath时节点移除了，但是没有重新走view.js的renderVueComponent方法

**Comment by NewByVector** [comment]
自定义 vue 节点参考[文档](http://x6.antv.antgroup.com/tutorial/intermediate/vue)。
