### ISSUE TITLE
edge:added 事件里面 edge.target.cell取不到值

### ISSUE THREAD

**Issue by liu136149** [antvis/X6#3814]
### 问题描述

graph.on('edge:added', (item) => {
            const edge = item.edge;
            console.log(edge);
            console.log(edge.source);
            console.log(edge.target);
            console.log(edge.target.cell);
})
新增一个edge后，source可以正常取到，target取到的值发生了变化

### 重现链接

https://x6.antv.vision/zh/examples/showcase/faq#validate-connection%E5%8F%AF%E5%A4%8D%E7%8E%B0%E9%97%AE%E9%A2%98

### 重现步骤

1. 进入页面：https://x6.antv.vision/zh/examples/showcase/faq#validate-connection%E5%8F%AF%E5%A4%8D%E7%8E%B0%E9%97%AE%E9%A2%98
2.把这串代码加到最后
graph.on('edge:added', (item) => {
            const edge = item.edge;
            console.log(edge);
            console.log(edge.source);
            console.log(edge.target);
            console.log(edge.target.cell);
})
3.取到的target不符合预期  没有cell和port

### 预期行为

期望打印出的target对象是{cell: "xxx", port: "xxx"}
实际打印出来的target对象是{x: number, y: number}

### 平台

- 操作系统: [win10]
- 网页浏览器: [Google Chrome114.0.5735.199.]
- X6 版本: [1.31.0]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/X6/assets/139738070/ca25a79a-6ac3-41da-9bbe-1144dead44bf)

**Comment by liu136149** [comment]
console.log(edge.getTarget());
console.log(edge.getTargetCell());
console.log(edge.getTargetCellId())
console.log(edge.getTargetPortId());
这些方法也都无法顺利取到值
![image](https://github.com/antvis/X6/assets/139738070/299b2878-2dc4-423f-9b6f-4febe74bc543)

**Comment by cnyballk** [comment]
那是创建开始的 target没有cell了，你可以监听  edge:connected  事件

**Comment by liu136149** [comment]
> 那是创建开始触发的，所以没有，你可以监听 edge:connected 事件

好的  谢谢
