### ISSUE TITLE
[Bug] [ER图] er更新坐标后执行 graph.resetCell() 后并未更新位置

### ISSUE THREAD

**Issue by thl3538** [antvis/X6#3822]
### Describe the bug

我在初始化的时候绘制了 ER 图，然后改变了数据，更新了数据中的postion坐标但是图表坐标位置并未更改

### Your Example Website or App

e.g: https://codesandbox.io/s/serene-water-d8fj3y?file=/index.ts

### Steps to Reproduce the Bug or Issue

1. 在如上的 codesandbox 中 其实我们能看到页面闪了一下， 我使用定时器更改了图表位置然后重新执行 graph.resetCells()， 单图表坐标位置并未修改
![image](https://github.com/antvis/X6/assets/59004749/239d3592-741b-461d-9644-30bcea2a5bf9)

### Expected behavior

1. 希望更改坐标位置重新执行 graph.resetCells(), 图表更新到指定位置

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [2.11.1]

**Comment by NewByVector** [comment]
你的 cells 对象有问题呀，需要重置一下，你可以打印看下。
