### ISSUE TITLE
transfrom多选缩放问题

### ISSUE THREAD

**Issue by shenxiaozhong** [antvis/X6#3825]
### Describe the feature you'd like to request

请问一下， 有没有什么方法能实现同时选择多个节点并且他们的transfrom的缩放框都能出现，而不是只能通过方法选中一个

### Describe the solution you'd like

期望可以选择多个节点，但是所有节点出现缩放，同时只能缩放一个。

![image](https://github.com/antvis/X6/assets/41930264/9dfb36b1-33ef-4fb4-9183-43b1faac960b)

### Describe alternatives you've considered

期望可以选择多个节点，但是所有节点出现缩放，同时只能缩放一个。

![image](https://github.com/antvis/X6/assets/41930264/9dfb36b1-33ef-4fb4-9183-43b1faac960b)

**Comment by NewByVector** [comment]
与 https://github.com/antvis/X6/issues/3824 重复。
