### ISSUE TITLE
使用node-editor后，删除节点报错。

### ISSUE THREAD

**Issue by lzqtxwd** [antvis/X6#3839]
### Describe the bug

版本：2.9.5
报错：Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

应该是对于editor重复删除了，使用editor后点击其他位置会删除editor的dom节点，再次删除节点，会重复删除。导致报错。。。

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1、 创建节点并添加node-editor
2、触发editor，挂载editor的dom
3、失焦。
4、选中该节点并删除
5、删除失败报错。

### Expected behavior

正常删除节点

### Platform

- OS:Windows
- Browser: Chrome
- Version: 115

**Comment by lzqtxwd** [comment]
使用editor后。点击其他地方会删除editor。。。应该是只删除了dom节点，view对象中的editor没有处理。。后续删除节点时会误以为editor还存在，重复删除。。导致报错。。。

**Comment by NewByVector** [comment]
新版本修复了该问题。
