### ISSUE TITLE
链接桩变成rect 把文字放入 超出宽度显示省略号会出现有时候不显示文字

### ISSUE THREAD

**Issue by DividingLine** [antvis/X6#3842]
### Describe the bug

代码
<img width="486" alt="image" src="https://github.com/antvis/X6/assets/33141363/00e0ffc4-8fd3-4c47-8a02-fb4129403f8b">
<img width="596" alt="image" src="https://github.com/antvis/X6/assets/33141363/d1d2b24e-0942-4882-9980-c46babe588c4">
效果
![image](https://github.com/antvis/X6/assets/33141363/dbcdb9ba-cfb1-4eec-8af8-e86ab17ec8a8)

### Your Example Website or App

x

### Steps to Reproduce the Bug or Issue

如图所示

### Expected behavior

这是什么问题导致的呢？把textWrap去掉就可以正常显示，但是去掉后文字会超出？链接桩在2.x版本可不可以使用react节点进行渲染呢？

### Platform

Chrome

**Comment by NewByVector** [comment]
连接桩不可以使用  react 渲染的。你的问题可能是文本长度计算出错，能否提供一下不显示的文本呢。
