### ISSUE TITLE
请问 自定义vue节点支持设置连接桩吗

### ISSUE THREAD

**Issue by wu74** [antvis/X6#3843]
### 问题描述

使用了自定义vue节点  然后发现节点之间好像没有连接桩 不能进行连线, 然后看了一下文档好像没有提到相关信息

### 重现链接

1

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.13.1 ...]

**Comment by NewByVector** [comment]
vue 节点时支持连接桩的，和普通节点的连接桩一样的使用。
