### ISSUE TITLE
官方案例react 自定义节点进去报 Error: Node with name 'algo-node-1' does not exist.

### ISSUE THREAD

**Issue by myBoringCode** [antvis/X6#3844]
### 问题描述

官方案例react 自定义节点进去报
Error: Node with name 'algo-node-1' does not exist.

### 重现链接

1

### 重现步骤

1. 下载官方源码2.11.3
2. pnpm install 按照依赖
3. 启动 example 查看效果
cd examples/x6-example-features
pnpm run start
4. 点击react进入react 自定义子页面

### 预期行为

react 自定义子页面能够正常运行

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- X6 版本: 2.11.3

### 屏幕截图或视频（可选）

1

### 补充说明（可选）

1

**Comment by myBoringCode** [comment]
不止http://localhost:8000/react,http://localhost:8000/group, http://localhost:8000/react/portal,http://localhost:8000/case/dag
都会报错
![image](https://github.com/antvis/X6/assets/129058082/4ae05fde-7274-42fc-b2c9-07503a01d6ed)

**Comment by myBoringCode** [comment]
'@antv/x6-react-shape' register 
 register({
      shape: 'algo-node-1',
      width: 144,
      height: 28,
      effect: ['data'],
      component: NodeComponent,
    })
调用的文件是http://localhost:8000/node_modules/.pnpm/registry.npmmirror.com+@antv+x6@2.13.1/node_modules/@antv/x6/es/registry/registry.js,
但是在读取的时候
const node = graph.addNode({
      shape: 'algo-node-1',
      x: 80,
      y: 80,
      data: {
        name: '逻辑回归',
      },
    })
调用的是http://localhost:8000/packages/x6/es/registry/registry.js 文件

**Comment by myBoringCode** [comment]
可能缓存的原因, 或者版本的原因, 升级pnpm版本到8.8.12后正常了

**Comment by jiangxin829** [comment]
我也遇到了，感谢。pnpm从8.6.12升级到8.8.0后，删除nodemodule/.vite后重新生成依赖，解决问题
