### ISSUE TITLE
同一节点现存的两个链接桩如何互相交换位置？

### ISSUE THREAD

**Issue by 13033445320** [antvis/X6#3846]
### 功能描述

现在有一个节点有一个链接桩组，组中分别由A，B两个连接桩，现在要求这两个连接桩可以互相交换位置

### 期望解决方案

node.port.ports.reverse() 后，有没有更新节点视图的方法？或者别的可以修改位置方法？

**Comment by NewByVector** [comment]
可以先删除再添加：
```ts
const ports = source.getPorts()
  source.removePorts(ports)
  source.addPorts(ports.reverse())
```

**Comment by 13033445320** [comment]
先删除的话，链接桩上的连线会断掉，还需要重新连线，数据量大的情况，不太友好。有没有更好的办法？
