### ISSUE TITLE
在2.x版本中依赖的是react18+版本，但是这个版本的react没有ReactDOM.render

### ISSUE THREAD

**Issue by DividingLine** [antvis/X6#3849]
### Describe the bug

![image](https://github.com/antvis/X6/assets/33141363/42e78e61-a493-4a1f-9295-e136aa8eb68c)

### Your Example Website or App

#

### Steps to Reproduce the Bug or Issue

2.x版本官方文档中https://x6.antv.antgroup.com/api/mvc/view#onportrendered 中有使用ReactDOM.render()方法

### Expected behavior

希望能解决react18版本中的ReactDOM.render

### Screenshots or Videos

#

### Platform

web

### Additional context

#

**Comment by lloydzhou** [comment]
推荐使用  https://github.com/lloydzhou/x6-html-shape  解决react不同版本的问题

**Comment by NewByVector** [comment]
如果是 react18，那么切换成 react18 的渲染方式。
