### ISSUE TITLE
文档-群组-通过交互创建嵌套  代码没看明白

### ISSUE THREAD

**Issue by 905868332** [antvis/X6#385]
new Graph({
  embedding: {
    enabled: true,
    findParent({ node }) {
      const bbox = node.getBBox()
      return this.getNodes().filter((node) => {
        // 只有 data.parent 为 true 的节点才是父节点
        const data = node.getData<any>()
        if (data && data.parent) {
          const targetBBox = node.getBBox()
          return bbox.intersect(targetBBox)
        }
        return false
      })
    }
  }
})

const data = node.getData<any>()  这行是什么意思
源文档是   const data = node.getData  <  any >()    （忽略空格，无空格会被解析成上方所示）

**Comment by NewByVector** [comment]
```ts
const node = addNode({
    data: {} // 业务数据
})
const data = node.getData() //拿到数据
```
