### ISSUE TITLE
开启async后，会出现飞线

### ISSUE THREAD

**Issue by lunar9621** [antvis/X6#3852]
### 问题描述

使用fromJSON渲染所有节点和边，开启异步渲染（async为true）后，会出现飞线的情况，去掉后就正常渲染

### 重现链接

无

### 重现步骤

const graph=new Graph({ async:true,...otheroptions });
graph.fromJSON(data)

### 预期行为

希望没有飞线，正常渲染

### 平台

- 操作系统: [macOS,]
- 网页浏览器: [Google Chrome]
- X6 版本: [1.34.13]

### 屏幕截图或视频（可选）

<img width="897" alt="截屏2023-08-15 11 13 39" src="https://github.com/antvis/X6/assets/34565468/4f0978e9-f03e-426f-9b21-9af6dc033c3f">

**Comment by NewByVector** [comment]
这条线本来是不该存在的？能否提供一个可以复现的 demo 看下？

**Comment by lunar9621** [comment]
> 这条线本来是不该存在的？能否提供一个可以复现的 demo 看下？

不是 是没有链接到对应的node上，猜测可能是node没渲染完就渲染edge 导致，改成先addNode，监听render:done后再渲染edge可解决
