### ISSUE TITLE
希望能支持框选时是否能够选中边的配置项

### ISSUE THREAD

**Issue by YUST2020** [antvis/X6#3856]
### 功能描述

目前有一个需求要求把流程图中的一部分框选并独立出来保存为一个新流程，为了获取流程的起点以及合法性校验需要框选时能将线也一起获取进来

### 期望解决方案

目前框选只能选中节点而不能够选中边，希望能开放选中边的配置项

**Comment by NewByVector** [comment]
框选是可以选中边的，其中还有一个配置：showEdgeSelectionBox
