### ISSUE TITLE
X6力导图的demo拖拽节点的时候整个页面能有动态的效果吗

### ISSUE THREAD

**Issue by kevindurant-source** [antvis/X6#3858]
### 问题描述

https://g6.antv.antgroup.com/zh/examples/net/forceDirected/#basicForceDirectedDragFix  G6的整个拖拽某个节点，其他节点都有动态拖拽的效果，但是X6的官方demo没有https://x6.antv.antgroup.com/zh/examples/layout/general#force。
![image](https://github.com/antvis/X6/assets/67896847/7773d6ea-91de-4aff-b91f-47222f30ded6)
好像是这几行代码生效，拖动节点，重新布局，但是X6里面我看好像不行。目前能支持吗一下。

### 重现链接

https://g6.antv.antgroup.com/zh/examples/net/forceDirected/#basicForceDirectedDragFix  

### 重现步骤

https://g6.antv.antgroup.com/zh/examples/net/forceDirected/#basicForceDirectedDragFix  G6的整个拖拽某个节点，其他节点都有动态拖拽的效果，但是X6的官方demo没有https://x6.antv.antgroup.com/zh/examples/layout/general#force。
![image](https://github.com/antvis/X6/assets/67896847/7773d6ea-91de-4aff-b91f-47222f30ded6)
好像是这几行代码生效，拖动节点，重新布局，但是X6里面我看好像不行。目前能支持吗一下。

### 预期行为

X6力导图类似G6这种拖拽节点，其他节点重新布局https://g6.antv.antgroup.com/zh/examples/net/forceDirected/#basicForceDirectedDragFix

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/X6/assets/67896847/a852d288-6e7a-4930-a284-add63ffcdb86)

**Comment by xxuyang** [comment]
试试监听node:mousemove,节点按下并移动时触发

**Comment by NewByVector** [comment]
其实就是在布局 tick 回调中一直修改节点位置就行。
