### ISSUE TITLE
html引用umd包的形式,如何引用插件呢?

### ISSUE THREAD

**Issue by POKEZHANG** [antvis/X6#3859]
### 问题描述

我现在是html引用的umd包
但是那些插件都是通过npm下载的,我应该如何使用呢?

### 重现链接

暂无

### 重现步骤

无需重现

### 预期行为

我希望html可以引用插件的包

### 平台

- 操作系统: [Windows.]
- 网页浏览器: [Chrome]
- X6 版本: [2.11.1 ]

**Comment by NewByVector** [comment]
引入后直接通过全局变量访问，比如 Selection 插件:
```ts
const selection = new X6PluginSelection({})
```
