### ISSUE TITLE
when node embed into anohter node ,the dom also in stage

### ISSUE THREAD

**Issue by dingjinhong** [antvis/X6#3863]
### Describe the bug

是否有方法更改，因为zindex关系，先添加的节点embed到后添加的节点中，无法点击选中

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

1

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by NewByVector** [comment]
embed 后，修改被 embed 节点的 zIndex 就可以了。
