### ISSUE TITLE
绘制的svg如何设置大小

### ISSUE THREAD

**Issue by zfy171** [antvis/X6#3866]
### 问题描述

自定义节点为svg 绘制完成后 大小无法控制

### 重现链接

1

### 重现步骤

![image](https://github.com/antvis/X6/assets/70139873/149bd813-260f-4f83-accc-6c1bef695d16)

### 预期行为

svg渲染出来的大小无法控制

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by zfy171** [comment]
手动修改也不行

**Comment by zfy171** [comment]
已改方案 将svg当着图片渲染

**Comment by NewByVector** [comment]
svg 结构和 X6 markup 是不兼容的，使用图片方式渲染是合理的。

**Comment by AMhehe** [comment]
可以用  transform:"scale(0.02,0.02)",
![image](https://github.com/antvis/X6/assets/30047724/72bed023-32cc-4c56-8eeb-4234b23ae008)
