### ISSUE TITLE
设置 allowLoop: false 后，相同起止节点之间依然可以创建循环连线

### ISSUE THREAD

**Issue by wp98986** [antvis/X6#3868]
### 问题描述

如题目所述，connecting 中设置allowLoop为false 后，依然可以创建循环连线

### 重现链接

无

### 重现步骤

无

### 预期行为

期望无法创建循环线条

### 平台

- 操作系统: [macOS, ]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.13.1 ...]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/X6/assets/43988310/2cdeb319-ebd7-410a-a123-36d73cb1e1c1)

**Comment by TalentJY** [comment]
这个循环的意思 是自己拉出一条线连自己。你这个估计得自己代码控制了

**Comment by NewByVector** [comment]
@wp98986 正如 @TalentJY 所说，这个和你理解的 loop 不是同一个意思。你可以找一找检测图上存在环路的算法来判断你的问题。
