### ISSUE TITLE
如何获取已注册的自定义节点名称列表？Error: Node with name 'custom-node' already registered.

### ISSUE THREAD

**Issue by SnowfungusWang** [antvis/X6#3872]
### 问题描述

请问有什么办法可以获取当前注册过的自定义节点列表吗？
在vue2.x中当想在一个页面中使用两个不同的图时，由于在每个图中分别注册了自定义节点custom-node，遇到了报错：
[Vue warn]: Error in created hook: "Error: Node with name 'custom-node' already registered."
![image](https://github.com/antvis/X6/assets/37967256/c9b5b998-b71b-4fe2-aeaa-ddb91fc5d1e0)

### 重现链接

无

### 重现步骤

同时渲染两个图会出现该问题

### 预期行为

期望：在同一个页面存在两个不同的图，有各自的注册节点列表
实际：同一页面的第二个图报错同名节点已被注册

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 1.31

**Comment by zzjjbbaa** [comment]
`registerNode(name,cfg,true);//第三个参数设为true?`
