### ISSUE TITLE
dnd插件配置draggingContainer后，拖动节点位置有偏移

### ISSUE THREAD

**Issue by ShirlyKong** [antvis/X6#3873]
### 问题描述

1. 复现链接demo，拖动左侧节点，节点不跟随鼠标而是有偏移，鼠标mouseup时 节点又会在鼠标松开位置绘制。

### 重现链接

https://codesandbox.io/s/hardcore-shadow-q8cwtg

### 重现步骤

1. 上述复现链接demo，拖动左侧节点，节点不跟随鼠标而是有偏移，鼠标mouseup时 节点又会在鼠标松开位置绘制。

### 预期行为

配置draggingContainer后，预期mousemove时节点跟随鼠标移动，最终松开时在松开位置创建节点。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by cyrilluce** [comment]
@NewByVector 这个什么时候能发布版本呢？我看dnd插件没有更新
