### ISSUE TITLE
history插件使用undo撤销连线的bug

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/X6#3877]
### Describe the bug

![image](https://github.com/antvis/X6/assets/54572770/be6c4efd-c213-4fe1-b949-5e9088046b31)
上面的函数是绑定到grpah.on('edge:removed')回调中的；

1. 通过graph.removeEdge操作，可以在回调中捕获edge的target;
2. 通过graph.undo撤销edge，不能在回调中捕获edge的target，如上图所示;

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

很容易理解，不赘述

### Expected behavior

undo 连线，也能捕获移除的edge的target

### Screenshots or Videos

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

### Additional context

无

**Comment by NewByVector** [comment]
我本地试了一下是可以获取到的，请提供一个可以复现的 demo。

**Comment by NewByVector** [comment]
因为无法复现你的问题，暂时关闭。
