### ISSUE TITLE
使用vue渲染节点，性能问题

### ISSUE THREAD

**Issue by goldenfireking** [antvis/X6#3879]
### Describe the bug

使用vue组件来渲染节点，UI使用的element plus，节点点击显示个详细信息的弹窗，一开始只有几个节点的时候没有问题，当节点超过10个，性能开始逐渐下降，30个节点左右弹窗内容就出现滚动卡顿甚至浏览器卡死现象，为了确认是否是vue节点造成的，去除vue节点用内置的节点来渲染，然后通过点击事件来弹出详细信息弹窗，非常流畅，没有性能问题。

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1、用vue组件渲染一个节点
2、节点点击弹窗，弹窗内容滚动（放了些echarts图表，大概4-5个）
3、当节点数增多，弹窗内容滚动卡顿甚至卡死

### Expected behavior

vue节点渲染性能，不应该十几个就造成卡顿

### Platform

OS: macOS
Browser: Chrome

**Comment by qiufeihong2018** [comment]
首先得看下你用的是哪个版本的X6？

**Comment by lloydzhou** [comment]
@goldenfireking 能否提供一个复现的demo?

**Comment by NewByVector** [comment]
因为无法复现，issue 先关闭。
