### ISSUE TITLE
通过getNodes方法获取的节点无法获取到节点的x和y属性？

### ISSUE THREAD

**Issue by GeorGeWzw** [antvis/X6#388]
### 通过getNodes方法获取的节点无法获取到节点的x和y属性
![image](https://user-images.githubusercontent.com/46982191/101755217-9547f000-3b0f-11eb-9f63-c801bf3fb318.png)

**Comment by bubkoo** [comment]
这个方法返回了，所有节点的实例，如果想获取每个节点的位置 可以通过 `node.position()` 方法获取。

如果想获取单个节点的 JSON 数据，可以调用 `node.toJSON()` 方法。

如果想获取整个画布的数据，可以调用 `graph.toJSON()` 方法。

**Comment by GeorGeWzw** [comment]
@bubkoo 好的，明白了，想请教一个其他的问题，我想在链接桩拖拽生成线的时候显示其他Node内的连接点应该怎么写？

**Comment by bubkoo** [comment]
参考一下
- https://x6.antv.vision/zh/examples/showcase/practices#validate-connection
- https://x6.antv.vision/zh/examples/showcase/practices#algo-flow

这两个 demo 做的是链接桩高亮，同样可以通过 css className 来控制显示隐藏
