### ISSUE TITLE
addEdge操作时source或者target如果是Edge的话，那么toJSON再fromJSON会无法正确渲染

### ISSUE THREAD

**Issue by sjw1228** [antvis/X6#3880]
### 问题描述

addEdge操作时source或者target如果是Edge的话，那么toJSON再fromJSON会无法正确渲染，控制台会报错，且addEdge的那条边不显示

### 重现链接

无

### 重现步骤

1、使用addEdge方法在Edge和Node之间创建连线
2、使用toJSON方法导出数据
3、使用fromJSON方法导入数据
4、控制台报错，画布无法正确渲染

### 预期行为

正确渲染

### 平台

版本1.34.6

**Comment by NewByVector** [comment]
能否提供可以可以复现的 demo？

**Comment by NewByVector** [comment]
因为无法复现，这个 issue 先关闭。
