### ISSUE TITLE
快速上手中的边->图形Demo无法运行

### ISSUE THREAD

**Issue by Z-eddy** [antvis/X6#3881]
### Describe the bug

快速上手中的边->图形Demo无法运行，在默认打开的CodeSandbox中打开报错，我本地尝试了也是一样的错：The `shape` should be specified when creating a node/edge instance

### Your Example Website or App

谷歌浏览器 版本 116.0.5845.112（正式版本） （64 位）
antv/x6:  2.13.1

### Steps to Reproduce the Bug or Issue

1、打开快速上手的边->使用图形：https://antv-x6.gitee.io/zh/docs/tutorial/getting-started#%E4%BD%BF%E7%94%A8%E5%9B%BE%E5%BD%A2-1
2、选择默认的在 CodeSandbox 中打开
![image](https://github.com/antvis/X6/assets/54835865/a2762ea6-40c4-4a7b-8cbb-17d2e690a978)

3、编译报错：The `shape` should be specified when creating a node/edge instance
![image](https://github.com/antvis/X6/assets/54835865/a5fdc469-f09e-4873-8f56-57227625f46c)

### Expected behavior

快速上手的范例还是需要修复下嘛

### Platform

- OS:  Windows
- Browser: Chrome
- Version: 版本 116.0.5845.112（正式版本） （64 位）

**Comment by qiufeihong2018** [comment]
@Z-eddy 是的，因为没有注册边「double-edge」，建议 @NewByVector 更改 CodeSandbox，
参考https://codesandbox.io/s/fix-kuai-su-shang-shou-zhong-de-bian-tu-xing-demowu-fa-yun-xing-3881-3wc4wn

**Comment by Z-eddy** [comment]
> @Z-eddy 是的，因为没有注册边「double-edge」，建议 @NewByVector 更改 CodeSandbox， 参考https://codesandbox.io/s/fix-kuai-su-shang-shou-zhong-de-bian-tu-xing-demowu-fa-yun-xing-3881-3wc4wn

看完了快速上手，体验不太好，以后有机会再用

**Comment by NewByVector** [comment]
已经同步，问题已修复。

**Comment by nanfb** [comment]
> 已经同步，问题已修复。

我想问一下为什么会有这个问题，我自己的项目也有这个问题，但是定位不到原因

**Comment by nanfb** [comment]
> > 已经同步，问题已修复。
> 
> 我想问一下为什么会有这个问题，我自己的项目也有这个问题，但是定位不到原因

好像是Clipboard这个复制粘贴插件的问题，具体不知道什么原因

**Comment by nanfb** [comment]
> > > 已经同步，问题已修复。
> > 
> > 
> > 我想问一下为什么会有这个问题，我自己的项目也有这个问题，但是定位不到原因
> 
> 好像是Clipboard这个复制粘贴插件的问题，具体不知道什么原因

好像是useLocalStorage这个属性读取了剪切板的数据，但是我的节点还没初始化完成
