### ISSUE TITLE
连线时浏览器卡死

### ISSUE THREAD

**Issue by wuhongru222** [antvis/X6#3884]
### Describe the bug

创建模型后，连线浏览器卡死，浏览器无报错，其他模型没问题，只有图片模型有问题，疑似死循环了

### Your Example Website or App

http://218.61.32.87:1006/

### Steps to Reproduce the Bug or Issue

账号 密码 admin ，点击性能仿真，点击新版拖拽，点击添加节点，选择图片节点，输入参数创建节点，连线时 浏览器卡死。控制台无报错。部件节点连线时就没问题。用的一个new Graph配置

### Expected behavior

我想修复这个问题

### Platform

- OS: [ Windows
- Browser: [Chrome]
- Version: [2.11.5]
- vue2+vite

**Comment by zzjjbbaa** [comment]
没浮现成功
