### ISSUE TITLE
使用vue节点声明自定义节点时，会出现长度不会自动更新的情况

### ISSUE THREAD

**Issue by YUST2020** [antvis/X6#3885]
### 问题描述

声明了一个自定义vue节点，按照http://x6.antv.antgroup.com/tutorial/intermediate/group#%E5%B1%95%E5%BC%80%E4%B8%8E%E6%8A%98%E5%8F%A0%E7%88%B6%E8%8A%82%E7%82%B9 的内容增加了节点大小变化的实时监听
![image](https://github.com/antvis/X6/assets/73179372/59460f2b-304d-44a4-a73b-bcada6e05553)
出现了通过parent.prop修改size时，foreignObject标签没有自动同步更新大小的情况
但通过Transform插件改变节点大小后就能正常响应大小的自适应变化了，后续再更改prop也能正常改变大小，可能是vueshape内部有某些响应式的问题？
求解这是什么原因，或者有什么办法手动触发tranform插件的拖拽大小吗？

### 重现链接

暂无

### 重现步骤

1.声明一个vue自定义节点
2.加入http://x6.antv.antgroup.com/tutorial/intermediate/group#%E5%B1%95%E5%BC%80%E4%B8%8E%E6%8A%98%E5%8F%A0%E7%88%B6%E8%8A%82%E7%82%B9中的代码
3.发现通过prop修改size时foreignObject标签没有同步发生变化

### 预期行为

期望第一次修改prop.size时能够自适应改变foreignObject标签的长宽

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
能否提供一个可以复现的 demo？

**Comment by NewByVector** [comment]
因为无法复现你的问题，暂时关闭。
