### ISSUE TITLE
Svg图片的节点如何拖动边框改变图片大小？

### ISSUE THREAD

**Issue by wh356667852** [antvis/X6#3889]
### 问题描述

参考官方示例的“使用 SVG 自定义图标https://x6.antv.antgroup.com/zh/examples/node/custom-node/#custom-icon-with-svg，使用的本地SVG图片作为节点，也配置了resizing:true，但是还是不能改变图片的大小，求解。

### 重现链接

https://x6.antv.antgroup.com/zh/examples/node/custom-node#custom-icon-with-svg

### 重现步骤

1、配置resizing : true 属性
2、拖动节点边框，图片尺寸不变化
![image](https://github.com/antvis/X6/assets/67091425/2f62d995-1f88-4693-9e67-4bdfd3698382)

### 预期行为

希望图片的尺寸与拖动的节点尺寸一致

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by ZouYuLong** [comment]
刚好做了这个，一个方法是设置transom:scale属性，但是对于path绘制的线条图案比如接线图，他的线条粗细会被一同放大，然后就需要第二方法，遍历svg下所有节点，对path的d属性内部所有绘制进行想乘积运算重绘，同样rect，circle这些节点的w,h,x,y,rx,ry也需要做同样转换
![image](https://github.com/antvis/X6/assets/17397507/b18ae599-e6ee-4247-a55e-29f7a2ffdf20)

**Comment by wh356667852** [comment]
> 刚好做了这个，一个方法是设置transom:scale属性，但是对于path绘制的线条图案比如接线图，他的线条粗细会被一同放大，然后就需要第二方法，遍历svg下所有节点，对path的d属性内部所有绘制进行想乘积运算重绘，同样rect，circle这些节点的w,h,x,y,rx,ry也需要做同样转换 ![image](https://user-images.githubusercontent.com/17397507/265865065-b18ae599-e6ee-4247-a55e-29f7a2ffdf20.png)

明白了，谢谢大佬
