### ISSUE TITLE
请问如何监听流程图text编辑的事件？

### ISSUE THREAD

**Issue by noirlyrik** [antvis/X6#389]
添加如下的监听事件，但是在编辑流程图的text内容后并没有获取到修改后的text
```
graph.on('cell:changed', ({ cell, options }) => { 
      console.log(graph.toJSON())
   })
```

![image](https://user-images.githubusercontent.com/39143373/101852620-13040e00-3b99-11eb-9556-b22940a1cd75.png)

修改内容“起始节点”为新的内容后打印出来的数据依然是之前的数据
```
{
attrs:
body: {rx: 24, ry: 24}
text: {text: "起始节点", style: {…}}
...
```

**Comment by SunshineH2** [comment]
请问大佬我也遇到这个问题了，怎么解决呢，求回复，万分感谢！
