### ISSUE TITLE
TypeError: graph.bindKey is not a function

### ISSUE THREAD

**Issue by shenjilina** [antvis/X6#3891]
### 问题描述

在版本中（"@antv/x6": "^2.13.1"），graph实例化对象下找不到 bindKey 方法
官网中的示例也报同样的错误

### 重现链接

https://codesandbox.io/s/f987w0?file=/index.ts

### 重现步骤

可以直接运行官网思维导图的示例：https://codesandbox.io/s/f987w0?file=/index.ts

### 预期行为

希望尽快解决该bug

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/X6/assets/32736088/a2a51433-3210-4cd7-a9c3-59bacff9314e)

**Comment by GitHdu** [comment]
怎么关了，有什么解决方法吗
