### ISSUE TITLE
Edge设置label换行后label不显示

### ISSUE THREAD

**Issue by dlspacezero** [antvis/X6#3892]
### 问题描述

正常情况：
![image](https://github.com/antvis/X6/assets/39867886/818406cf-32d8-4fb5-b1b1-5ab509532784)

label不显示，异常的情况：
![image](https://github.com/antvis/X6/assets/39867886/b2de2ebe-b12a-4557-8902-0a076e24ba11)

### 重现链接

https://codesandbox.io/s/smoosh-lake-5lq826?file=/index.ts

### 重现步骤

无

### 预期行为

边的label超出一定宽度时候，能够换行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by qiufeihong2018** [comment]
@dlspacezero 有个临时方案：你可以在textWrap里加入text，参考这个https://codesandbox.io/s/fix-edgeshe-zhi-labelhuan-xing-hou-labelbu-xian-shi-3892-6ff3gx?file=/index.ts。

**Comment by qiufeihong2018** [comment]
@dlspacezero 对，要设置高度，不然可能获取到的高度为0
