### ISSUE TITLE
调用画布dispose方法后退出界面 重新进入创建节点点击会触发上次退出的节点回调

### ISSUE THREAD

**Issue by arroganceeagle** [antvis/X6#3893]
### 问题描述

创建节点后保存到后端 退出界面后 重新进入这个界面 然后拉出一个节点放入 点击这个节点会触发上一次退出之前的节点回调事件，会触发多次退出后重新进入的节点数回调

### 重现链接

项目暂无

### 重现步骤

本地项目 无法重置

### 预期行为

本地项目 无法重置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
能否提供一个可以复现的 demo?

**Comment by NewByVector** [comment]
因为无法复现你的问题，暂时关闭。
