### ISSUE TITLE
切换页面时，重新打开原来的页面画布数据丢失

### ISSUE THREAD

**Issue by wh356667852** [antvis/X6#3894]
### 问题描述

使用Vue3开发时，打开一个带有画布的界面后不关闭，同时打开另外一个页面，然后再切换至原来的界面，画布上数据丢失，一片空白，不知道是啥原因
正常的页面：
![8377ab5d2846b2d85cb03a86bcc1f2d](https://github.com/antvis/X6/assets/67091425/7e555c84-1a35-4525-a5cf-c8d832fdeacd)
打开其他页面后，再切换回来
![67c6088ca6c569e01fccaf86dfa24e5](https://github.com/antvis/X6/assets/67091425/4658e653-e06e-43fc-89e4-e489c166d90e)

### 重现链接

无

### 重现步骤

见“问题描述”

### 预期行为

原来的页面画布数据都保持不变

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by qiufeihong2018** [comment]
你尝试将“单例模式”变成“多例模式”

**Comment by wh356667852** [comment]
>
> 你尝试将“单例模式”变成“多例模式”
什么意思呢，意思是重新打开的时候，再创建一个画布吗？但是那样的话，我原来画布上画的就都没了

**Comment by Mafiti** [comment]
盲猜和autoResize有关，可以控制台看下编辑器的宽度是否为0，如果为0应该就是autoResize的问题。

可以把autoResize设置为false，或者样式控制父容器宽度。

**Comment by qiufeihong2018** [comment]
@wh356667852 有demo更好排查问题。我是猜目前的两个tab下的画布是冲突的。可以试试打开每个tab，实例化出一个画布，两者互不冲突啊，不会影响到原来画布上的内容。

**Comment by Hantongya** [comment]
我遇到了同样的问题，但不是数据丢失，而是滚动条位置移到了最顶点，如果和我的情况一下，我是这么解决的，如下图所示：
![image](https://github.com/antvis/X6/assets/115331996/7fa31212-93b9-4c8f-bcf9-f48c04d94e38)
造成这样的原因，主要是因为keep-active的影响，解决方案就是利用keep-active的两个生命周期，离开时记住滚动条的位置，激活状态重新复制即可即可，希望对你有用。

**Comment by NewByVector** [comment]
因为无法复现你的问题，暂时关闭。
