### ISSUE TITLE
@antv/x6-plugin-export插件导出的png图片清晰度太低

### ISSUE THREAD

**Issue by qiufeihong2018** [antvis/X6#3900]
### 问题描述
<img width="884" alt="image" src="https://github.com/antvis/X6/assets/36500514/159599d8-9d8e-437c-832c-3fcd26f0cff3">

导出图片

![image](https://github.com/antvis/X6/assets/36500514/431d90c9-2c12-463b-9d64-b16a349fb59e)

### 重现链接

examples/x6-example-features/src/pages/scroller/index.tsx

### 重现步骤

examples/x6-example-features/src/pages/scroller/index.tsx

### 预期行为

希望导出的是清晰的图片

### 平台

- 操作系统: [macOS
- 网页浏览器: [Google Chrome]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
`width` 和 `height` 设置大一点，导出的图片会清晰一些。
