### ISSUE TITLE
addEdge的时候，如果提供vetices，就可以在连接到节点后拖拽edge。

### ISSUE THREAD

**Issue by yangge24926** [antvis/X6#3903]
### 功能描述

我的需求是两个节点互相连接上后，可以拖拽连接的这根线。
测试发现如果vetices有值，那么就可以拖拽，但是也因为有vetices这个值，导致拖拽节点的时候，edge变化不如人意。有没有一种方式，能既支持拖拽，又可以使用manhattan的结果呢。

### 期望解决方案

希望可以支持拖拽edge。

**Comment by NewByVector** [comment]
拖拽 edge 是指修改起点或者终点位置还是？
