### ISSUE TITLE
连线能不能自动绕靠节点，不和节点重叠在一起

### ISSUE THREAD

**Issue by 13033445320** [antvis/X6#3908]
### 问题描述

画布节点很多，线和很多，如何能让线自动绕开节点，两者不重叠

### 重现链接

无

### 重现步骤

节点和边多的时候，就会重叠

### 预期行为

就像官网示例地铁路由那样，自动避开节点

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

### 屏幕截图或视频（可选）

![1694593665486](https://github.com/antvis/X6/assets/44597556/2fa33a48-2676-4f48-97b5-b696ba79e00f)

**Comment by NewByVector** [comment]
提供几个思路：
1. 使用 manhattan 路由，避开障碍物，实现比较简单，但是线的走向是否符合需求需要实际测试
2. 使用 vertices 将线分开
