### ISSUE TITLE
Path 画圆弧， 属性d 改为refD后，图形变形

### ISSUE THREAD

**Issue by light-years-run** [antvis/X6#3909]
### 问题描述

用画弧度方式绘制了一个圆，d属性可以正常显示，修改为refD后，变形
只有在大角度的时候才有此问题，比如超过180度，小角度，锐角的时候没有问题
d属性时
![image](https://github.com/antvis/X6/assets/25027143/23531527-9ba7-44ab-9464-8dc32edabba1)
refD 时：
![image](https://github.com/antvis/X6/assets/25027143/71cbe81c-dc2f-4774-ac2e-4ea744051b81)

### 重现链接

代码如下

### 重现步骤

import { Graph } from '@antv/x6'

const graph = new Graph({
  container: document.getElementById('container'),
  grid: true,
})

graph.addNode({
  shape: 'path',
  x: 0,
  y: 0,
  width: 541.82,
  height: 541.82,
  label: 'path',
  attrs: {
    body: {
      fill: '#efdbff',
      stroke: '#9254de',
      // 指定 refD 属性，pathData 随图形大小自动缩放
      // https://x6.antv.vision/zh/docs/api/registry/attr#refdresetoffset
      
     d: 'M517.73,241.31 L703.9,438.12 A270.91 270.91 0 1 1 732.73,406.14Z',
     //refD:'M517.73,241.31 L703.9,438.12 A270.91 270.91 0 1 1 732.73,406.14Z',
    },
  },
})

### 预期行为

希望refD和 d一致

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
[refD](http://x6.antv.antgroup.com/api/registry/attr#refdresetoffset) 是相对的 d，和 d 本身就不是一致的。

**Comment by light-years-run** [comment]
> [refD](http://x6.antv.antgroup.com/api/registry/attr#refdresetoffset) 是相对的 d，和 d 本身就不是一致的。

是的refD是相对的d，但是从官网给的例子和文档看，当refD和d路径点一致时，refD成图效果和d是一致的，只是d不会跟随图形缩放，refD可以，按照您的回复，refD难道和d成图效果会有偏差吗？那我用refD改怎么绘制出一个半椭圆呢？

**Comment by light-years-run** [comment]
> [refD](http://x6.antv.antgroup.com/api/registry/attr#refdresetoffset) 是相对的 d，和 d 本身就不是一致的。

我用的是 path中的 A绘制的椭圆，是否是因为 X6将A转成了C造成的呢？

**Comment by NewByVector** [comment]
将 refD 的内容横向和纵向进行拉伸，拉伸到和节点大小一致，产生的图像才是最终的 path d。你的那个图形我现在没办法通过 refD 绘制出来。

**Comment by NewByVector** [comment]
X6 中 path 对 A 支持不太好，可以使用下面方式规避：
```ts
const d = new Path()
  .moveTo(704.24, 79.95)
  .arcTo(5.10, 5.10, 0, 0, 1, 704.24, 90.15)
  .close()
  .serialize();
```

**Comment by light-years-run** [comment]
> X6 中 path 对 A 支持不太好，可以使用下面方式规避：
> 
> ```ts
> // M517.73,241.31 L703.9,438.12 A270.91 270.91 0 1 1 732.73,406.14Z
> const d = new Path()
>   .moveTo(517.73, 241.31)
>   .lineTo(703.9, 438.12)
>   .arcTo(270.91, 270.91, 0, 0, 1, 732.73, 406.14)
>   .close()
>   .serialize();
> ```
非常好用，感谢

**Comment by light-years-run** [comment]
> X6 中 path 对 A 支持不太好，可以使用下面方式规避：
> 
> ```ts
> // M517.73,241.31 L703.9,438.12 A270.91 270.91 0 1 1 732.73,406.14Z
> const d = new Path()
>   .moveTo(517.73, 241.31)
>   .lineTo(703.9, 438.12)
>   .arcTo(270.91, 270.91, 0, 0, 1, 732.73, 406.14)
>   .close()
>   .serialize();
> ```
再次感谢以上的解答，对于rx和ry相同的时候，arcTo转换出来已经没有问题了，今天下午又走了一个rx和ry不同的情况，转换出来的路径点是没有问题的，但是x6渲染的时候不对；
转换后的路径点是：
M361.56 226.29 L 651.56 227.68 C650.56 276.57 596.83 321.66 509.81 346.65 C 422.78 371.64 315.07 372.9 225.63 349.99 Z

将上面路径点直接用svg成图和采用 d方式成图 如下
![image](https://github.com/antvis/X6/assets/25027143/614860e9-5b65-47f9-b0f0-39c10e08031c)

但是采用refD渲染就有会偏差，从结果看，是rx和ry相同了，弧度大于90的时候才有这种情况
![image](https://github.com/antvis/X6/assets/25027143/3c499a6e-45e2-4e9b-98b6-8d7930e91caa)

希望rx和ry不同的情况下，refD能够正确渲染
