### ISSUE TITLE
path解析弧 Uncaught Error: Invalid path segment type "N"

### ISSUE THREAD

**Issue by festalstar** [antvis/X6#3920]
### 问题描述

创建path节点，解析path: 'M704.24,79.95 A 5.10 5.10 0 0 1 704.24 90.15'报错，解析path: 'M704.24,79.95 A 5.10 5.10 0 0 1 704.24 90.14'不报错。

![image](https://github.com/antvis/X6/assets/4541271/f4ab582e-e0a0-48df-b2b4-bb05b3961965)

### 重现链接

https://x6.antv.antgroup.com/zh/examples/node/native-node/#path

### 重现步骤

import { Graph } from '@antv/x6'

const graph = new Graph({
container: document.getElementById('container'),
grid: true,
})

graph.addNode({
shape: 'path',
x: 40,
y: 40,
width: 100,
height: 80,
path: 'M704.24,79.95 A 5.10 5.10 0 0 1 704.24 90.15',
attrs: {
body: {
fill: '#efdbff',
stroke: '#9254de',
},
},
})

官方url路径下，执行后报错，控制台提示：Uncaught Error: Invalid path segment type "N"。
将 path属性值的改为:'M704.24,79.95 A 5.10 5.10 0 0 1 704.24 90.14', 执行无错误。

### 预期行为

path: 'M704.24,79.95 A 5.10 5.10 0 0 1 704.24 90.15' 无报错。

### 平台

OS: [Windows]
Browser: [e.g]
Version: [e.g. 116.0.1938.69 (正式版本) (64 位)]

**Comment by NewByVector** [comment]
X6 中 path 对 A 支持不太好，可以使用下面方式规避：
```ts
const d = new Path()
  .moveTo(704.24, 79.95)
  .arcTo(5.10, 5.10, 0, 0, 1, 704.24, 90.15)
  .close()
  .serialize();
```
