### ISSUE TITLE
Cannot read properties of null (reading 'nextSibling')

### ISSUE THREAD

**Issue by TyCoding** [antvis/X6#3923]
### Describe the bug

使用自定义vue节点，直接使用graph.removeNode()删除节点时会报错Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')

请问这是什么原因，节点是被正常删除了，但是这个错误怎么避免

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

1

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]
antv x6 2.x

**Comment by tianye19941001** [comment]
我也遇到这样的问题 @TyCoding 想问下你解决了吗

**Comment by xiebanglong** [comment]
@tianye19941001 我也遇到这样的问题，想问下你解决了吗？
