### ISSUE TITLE
path路径点渲染问题，C 方式

### ISSUE THREAD

**Issue by light-years-run** [antvis/X6#3925]
### 问题描述

再次感谢对 [#3909](https://github.com/antvis/X6/issues/3909) 的解答，对于rx和ry相同的时候，arcTo转换出来已经没有问题了，今天下午又做了一个rx和ry不同的情况，转换出来的路径点是没有问题的，但是x6渲染的时候不对；
转换后的路径点是：
M361.56 226.29 L 651.56 227.68 C650.56 276.57 596.83 321.66 509.81 346.65 C 422.78 371.64 315.07 372.9 225.63 349.99 Z

将上面路径点直接用svg成图和采用 d方式成图 如下
![image](https://github.com/antvis/X6/assets/25027143/614860e9-5b65-47f9-b0f0-39c10e08031c)

但是采用refD渲染就有会偏差，从结果看，是rx和ry计算有误，rx和ry不应该相同，但是却相同了
![image](https://github.com/antvis/X6/assets/25027143/3c499a6e-45e2-4e9b-98b6-8d7930e91caa)

希望rx和ry不同的情况下，refD能够正确渲染

### 重现链接

test

### 重现步骤

如上图

### 预期行为

期望正确显示rx和ry不同的情况

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
修改为 refD 后，会将图形按照节点的长和宽进行拉伸。所以和用 d 的样式不一致是正常的。

**Comment by light-years-run** [comment]
> 修改为 refD 后，会将图形按照节点的长和宽进行拉伸。所以和用 d 的样式不一致是正常的。

这种情况在角度小于90的时候没问题，大于90度就不行了。如果按照您说的这样，该怎么绘制一个rx和ry不同的扇形呢？

**Comment by NewByVector** [comment]
你的节点尺寸是多少？

**Comment by light-years-run** [comment]
> M361.56 226.29 L 651.56 227.68 C650.56 276.57 596.83 321.66 509.81 346.65 C 422.78 371.64 315.07 372.9 225.63 349.99 Z

width:100, height:100

**Comment by NewByVector** [comment]
![image](https://github.com/antvis/X6/assets/20186737/6996aa48-5bfb-4feb-b5ec-e7b9d551f1ee)
如果jie节点的 rx 和 ry 不一致，需要将节点尺寸做相应的修改(和实际图形的尺寸比例一致)。

**Comment by light-years-run** [comment]
> ![image](https://user-images.githubusercontent.com/20186737/270564311-6996aa48-5bfb-4feb-b5ec-e7b9d551f1ee.png) 如果节点的 rx 和 ry 不一致，需要将节点尺寸做相应的修改(和实际图形的尺寸比例一致)。

是的 谢谢，是因为我高度没计算对导致的，谢谢你的回复
