### ISSUE TITLE
[v1.34.6]复制并粘贴自定义节点 报错 Cannot read property 'foContent' of undefined

### ISSUE THREAD

**Issue by steamfeifei** [antvis/X6#3927]
### Describe the bug

在复制并粘贴自定义节点的时候，报错foContent ，无法完成征程复制。经过Debug发现，是下面这段代码执行时报的错误：
```bash
this.graph.bindKey("ctrl+v", () => {
        console.log('开始粘贴。。。')
        if (!this.graph.isClipboardEmpty()) {
          const cells = this.graph.paste({ offset: 32, useLocalStorage:true, });  // 这行代码报错
          cells.forEach(cell => {
            console.log("copy cell:", cell);
            cell.setData({ id: "" });
            cell.setData({ name: "" });
            cell.setData({ content: "" });
          });
          this.graph.cleanSelection();
          this.graph.select(cells);
        }
        return false;
      });
```

### Your Example Website or App

follow below

### Steps to Reproduce the Bug or Issue

在issue中发现，在2.0版本中是解决了这个问题，解决方式如下：
![image](https://github.com/antvis/X6/assets/44861931/14597435-2765-4fdf-9bf5-18f667969301)

### Expected behavior

none

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 1.34.6]

**Comment by NewByVector** [comment]
升级到 1.35.0。
