### ISSUE TITLE
绑定事件未解绑问题，导致操作过多事卡顿

### ISSUE THREAD

**Issue by bighhhh** [antvis/X6#3930]
### Describe the bug

目前发现transform.js中startListening()方法绑定的事件为解绑，所以在选中节点然后点击空白处取消选中，重复以上操作就会绑定非常多的事件，导致越操作越卡顿，当刷新页面后虽然画布节点完全一致时也会变的非常流畅，目前只查看了这一个插件的事件绑定问题，其他插件是否有同样问题不确定

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

可以查看我发送的断点图片，反复选中节点取消选中后，事件列表中的时间数量是不断增长的，而且我在transform.js的update中打了日志断点后，日志输出数量也会跟随事件数量不断增多，导致重复调用，而stopListening()函数却从来没调用过

### Expected behavior

取消选中后解除事件绑定

### Screenshots or Videos

![1](https://github.com/antvis/X6/assets/26075113/fa7dc019-8436-4db6-875e-02b9fd536d6b)
![2](https://github.com/antvis/X6/assets/26075113/26215ba9-04e9-4528-b47a-83b1c84d5a37)
![3](https://github.com/antvis/X6/assets/26075113/fafadcea-ad9c-47d3-8d7d-2b7b8bb0d372)
![4](https://github.com/antvis/X6/assets/26075113/be0b7243-f155-4065-a143-39c4326ba77b)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.1.7]

**Comment by NewByVector** [comment]
升级到 1.35.0。

**Comment by bighhhh** [comment]
> 升级到 1.35.0。

我是用的2.0的啊，我的x6-plugin-transform是用的2.1.7

**Comment by NewByVector** [comment]
@bighhhh 2.x 也修改了 等待版本发布哈。

**Comment by bighhhh** [comment]
> @bighhhh 2.x 也修改了 等待版本发布哈。

好的，谢谢
