### ISSUE TITLE
Console error when using mousewheel: "Unable to preventDefault inside passive event listener invocation"

### ISSUE THREAD

**Issue by blinky1994** [antvis/X6#3932]
### Describe the bug

When using the mousewheel to zoom, the console logs an error: Unable to preventDefault inside passive event listener invocation. It seems to be coming from node_modules\@antv\x6\src\util\dom\mousewheel.ts, where event.preventDefault is being called.

This is because of the default passive event listeners. Reference: https://developer.chrome.com/blog/scrolling-intervention-2/

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

1. Enable zooming feature and use mousewheel to scroll. 

2. The console will log an error when scrolling.

### Expected behavior

As a user, I am expecting to prevent double scrolling by stopping the default scrolling behaviour of the page when I am using the zooming on the graph.

### Platform

- OS: Windows 10 pro 64-bit
- Browser: Chrome, Edge
- Version: 
   Chrome (Version 116.0.5845.188 (Official Build) (64-bit)), 
   Edge (Version 117.0.2045.36 (Official build) (64-bit))

**Comment by NewByVector** [comment]
x6 2.x fixes the issue, please upgrade to 2.x version.

**Comment by blinky1994** [comment]
Thank you, it's resolved :)

**Comment by History-1024** [comment]
这个问题现在还是有警告的 怎么做能没有警告
![image](https://github.com/antvis/X6/assets/65716967/6c681d9a-6221-4403-a4cd-2cdaedea1c4f)

**Comment by nanfb** [comment]
> x6 2.x 修复了该问题，请升级到 2.x 版本。1.x 现在仅接受公共 pr。

这个问题在2.x也有，我不确定是不是我代码写的有问题，鼠标拖动时mouseup还是会有提示吗，但是其他的行为没有
