### ISSUE TITLE
动态更新画布的配置

### ISSUE THREAD

**Issue by dujuncheng** [antvis/X6#3935]
### 功能描述

需求背景：画布的连线模式希望由用户配置，在画布渲染之后，可以支持切换为 'manhattan' 或者 'normal' 的路由。

目前看文档，x6 router 只支持在初始化 new Graph 时配置，不支持动态设置

### 期望解决方案

期望提供 graph.setRouter 的 api

**Comment by NewByVector** [comment]
暂时没有全局更新的方法，不过可以支持通过 edge 来单独更新。
```ts
// http://x6.antv.antgroup.com/api/model/edge#setrouter
edge.setRouter(xx)
```

**Comment by dujuncheng** [comment]
> 暂时没有全局更新的方法，不过可以支持通过 edge 来单独更新。
> 
> ```ts
> // http://x6.antv.antgroup.com/api/model/edge#setrouter
> edge.setRouter(xx)
> ```



嗯嗯，看到文档了。edge.setRouter(xx) 只能修改“已渲染”  edge 的路由。没办法实现，“新拽出来线”是新设置的路由

**Comment by NewByVector** [comment]
新拖出来的线可以在 createEdge 配置中重新配置路由。
