### ISSUE TITLE
x6-react-shape 和 xflow的差异点是啥

### ISSUE THREAD

**Issue by kemisstep** [antvis/X6#3936]
### 问题描述

xflow是基于x6开发的，但是好像不维护了

### 重现链接

x6-react-shape 和 xflow的差异点是啥

### 重现步骤

x6-react-shape 和 xflow的差异点是啥

### 预期行为

x6-react-shape 和 xflow的差异点是啥

### 平台

x6-react-shape 和 xflow的差异点是啥

### 屏幕截图或视频（可选）

x6-react-shape 和 xflow的差异点是啥

### 补充说明（可选）

x6-react-shape 和 xflow的差异点是啥

**Comment by NewByVector** [comment]
x6-react-shape 是支持使用 react 渲染节点内容的库。XFlow 是使用申明式方式对 X6 进行封装。
