### ISSUE TITLE
Nextjs ReferenceError: window is not defined

### ISSUE THREAD

**Issue by kemisstep** [antvis/X6#3939]
### Describe the bug

Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.

### Your Example Website or App

window is not defined

### Steps to Reproduce the Bug or Issue

```
"use client";
import { register } from '@antv/x6-react-shape'

const NodeComponent = () => {
  return (
    <div className="react-node">
      <Progress type="circle" percent={30} width={80} />
    </div>
  )
}

register({
  shape: 'custom-react-node',
  width: 100,
  height: 100,
  component: NodeComponent,
})

graph.addNode({
  shape: 'custom-react-node',
  x: 60,
  y: 100,
})
```

### Expected behavior

正常运行

### Platform

nextjs

**Comment by NewByVector** [comment]
You need to render after the page has loaded, rather than putting render logic in useEffect.
