### ISSUE TITLE
标签层级问题

### ISSUE THREAD

**Issue by ywywZhou** [antvis/X6#3945]
### 问题描述

产品要求标签盖到黑线上面
![image](https://github.com/antvis/X6/assets/67539158/8fd6bc59-6964-4cb4-b37e-3b74782f7ca3)

### 重现链接

https://x6.antv.antgroup.com/zh/examples/edge/label/#multi-labels

### 重现步骤

![image](https://github.com/antvis/X6/assets/67539158/d789f1c6-45cb-434c-a923-a50b38dd282c)
添加这部分即可
graph.addEdge({
  source: [280, 20],
  target: [280, 500],
  attrs: {
    line: {
      stroke: '#000',
    },
  },
})

### 预期行为

希望可以给标签添加层级，可以盖住重合的连线

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by Hantongya** [comment]
给zIndex即可。
<img width="1235" alt="image" src="https://github.com/antvis/X6/assets/115331996/721629cd-9b92-49b7-b0fe-925fcd7fd423">

**Comment by Hantongya** [comment]
> 给zIndex即可。 <img alt="image" width="1235" src="https://user-images.githubusercontent.com/115331996/271153727-721629cd-9b92-49b7-b0fe-925fcd7fd423.png">

@ywywZhou

**Comment by ywywZhou** [comment]
> 给zIndex即可。 <img alt="image" width="1235" src="https://user-images.githubusercontent.com/115331996/271153727-721629cd-9b92-49b7-b0fe-925fcd7fd423.png"> @ywywZhou

感谢大佬
