### ISSUE TITLE
selection框选不能选中，不显示包围框

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/X6#3949]
### 问题描述

如题

### 重现链接

https://codesandbox.io/s/vibrant-wind-k3g2g3?file=/src/app.tsx

### 重现步骤

尝试鼠标框选

### 预期行为

选中node，且显示正确的包围框

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
显示包围框需要增加 `showNodeSelectionBox` 配置。
