### ISSUE TITLE
使用  node.setAttrs({label:{text:''}}) 不起作用

### ISSUE THREAD

**Issue by worthworld** [antvis/X6#3955]
### Describe the bug

 x6版本2.15.1初始化渲染数据，当节点值为 {label:{text:''}} 时显示 -
 使用 node.setAttrs({label:{text:''}}) 不起作用
 

### Your Example Website or App

//

### Steps to Reproduce the Bug or Issue

1、节点部分数据 {label:{text:''}} ，使用graph.fromJson渲染节点
2、使用 node.setAttrs({label:{text:''}}) 修改label的值

### Expected behavior

作为用户，我希望fromJson渲染节点正常显示label值为空字符串的情况、node.setAttrs({label:{text:''}}) 生效把label的值置为空；但我看到的是fromJson渲染节点空字符串时为'-',node.setAttrs({label:{text:''}}) 时不生效

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.15.1]

### Additional context

注： 不一定是label元素，其它具有text属性的元素也存在上述问题

**Comment by worthworld** [comment]
`node.setAttrs( {label:{ text:0 }} )` 也不起作用

**Comment by NewByVector** [comment]
我本地试了一下是好的呀，你的测试 demo 发一下？

**Comment by worthworld** [comment]
> 我本地试了一下是好的呀，你的测试 demo 发一下？

https://codesandbox.io/s/html-css-js-t245jd?file=/src/index.js

**Comment by worthworld** [comment]
> 我本地试了一下是好的呀，你的测试 demo 发一下？
嗯，写了一个简单的，你看看； 版本 2.15.x
https://codesandbox.io/s/html-css-js-t245jd?file=/src/index.js

**Comment by worthworld** [comment]
> 我本地试了一下是好的呀，你的测试 demo 发一下？

**Comment by worthworld** [comment]
> ### Describe the bug
> x6版本2.15.1初始化渲染数据，当节点值为 {label:{text:''}} 时显示 - 使用 node.setAttrs({label:{text:''}}) 不起作用
> 
> ### Your Example Website or App
> https://codesandbox.io/s/html-css-js-t245jd?file=/src/index.js //
> 
> ### Steps to Reproduce the Bug or Issue
> 1、节点部分数据 {label:{text:''}} ，使用graph.fromJson渲染节点 2、使用 node.setAttrs({label:{text:''}}) 修改label的值
> 
> ### Expected behavior
> 作为用户，我希望fromJson渲染节点正常显示label值为空字符串的情况、node.setAttrs({label:{text:''}}) 生效把label的值置为空；但我看到的是fromJson渲染节点空字符串时为'-',node.setAttrs({label:{text:''}}) 时不生效
> 
> ### Screenshots or Videos
> _No response_
> 
> ### Platform
> * OS: [e.g. macOS, Windows, Linux]
> * Browser: [e.g. Chrome, Safari, Firefox]
> * Version: [e.g. 2.15.1]
> 
> ### Additional context
> 注： 不一定是label元素，其它具有text属性的元素也存在上述问题

**Comment by worthworld** [comment]
demo：  https://codesandbox.io/s/html-css-js-t245jd?file=/src/index.js
