### ISSUE TITLE
node-editor在手机端，输入文字后，点击画布空白区域，不会退出编辑模式，修改不生效

### ISSUE THREAD

**Issue by mapengfei** [antvis/X6#3957]
### 问题描述

用手机浏览器打开官网：https://x6.antv.antgroup.com/api/registry/node-tool
滑动页面找到node-editor的demo，双击节点，输入文字，点击画布空白区域，不会退出编辑模式，修改不生效，只有点击其他节点，才会退出编辑模式，修改生效。

### 重现链接

https://x6.antv.antgroup.com/api/registry/node-tool

### 重现步骤

1、用手机浏览器打开官网：https://x6.antv.antgroup.com/api/registry/node-tool
2、滑动页面找到node-editor的demo
3、双击节点，输入文字
4、点击空白区域
5、不会退出编辑模式，修改不 生效，只有点击另外一个节点，才会退出编辑模式，修改才会生效

### 预期行为

在手机端，点击空白区域，退出编辑模式，修改可以生效

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.15.1 ]

**Comment by mapengfei** [comment]
请问下，这个 PR 发版了吗？

**Comment by NewByVector** [comment]
这个 https://www.yuque.com/antv/x6/bbfu6r#PSlfD。

**Comment by mapengfei** [comment]
已验证，2.15.4 已解决
