### ISSUE TITLE
2.15版本使用dnd插件2.1版本 ，在调用dnd.start的时候报错提示 “Cannot read properties of null (reading 'model')”

### ISSUE THREAD

**Issue by nanfb** [antvis/X6#3967]
### 问题描述

执行按下事件的时候触发dnd.start，但是会有报错，我看到之前有issus说是引入问题，当作插件抽出来也还是有这个问题吗？

### 重现链接

https://codesandbox.io/s/beautiful-bush-kpykjl?file=/src/components/content/Content.vue

### 重现步骤

点击按下dnd面板元素

### 预期行为

元素clone，正常走

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
你 `new Dnd` 的时候传的 graph 是 null

**Comment by nanfb** [comment]
> 你`new Dnd`的时候传的图为空

真的，我是若只，昨晚通宵了。给大伙添麻烦了😭
