### ISSUE TITLE
使用edge-editor插件双击编辑label时，再次双击label消失，或出现多个label

### ISSUE THREAD

**Issue by Nplayers** [antvis/X6#3973]
### Describe the bug

使用edge-editor插件配置项tools: ['edge-editor']时，编辑状态再次双击时label消失。
另外，使用edge.addTools双击编辑label时，连续双击出现多个label。在label上和边上双击都一样，双击进入编辑状态，再次双击编辑状态关闭，再次双击时出现双倍label标签。在编辑状态点击其他地方关闭标签后，再次双击边上又多了一个label输入框。

### Your Example Website or App

https://codesandbox.io/s/upbeat-bush-2j5zxm?file=/App.tsx:1627-1650  和  https://codesandbox.io/s/interesting-archimedes-ktdczq?file=/App.tsx

### Steps to Reproduce the Bug or Issue

使用edge-editor插件配置项tools: ['edge-editor']时，编辑状态再次双击时label消失。
另外，使用edge.addTools双击编辑label时，连续双击出现多个label。在label上和边上双击都一样，双击进入编辑状态，再次双击编辑状态关闭，再次双击时出现双倍label标签。在编辑状态点击其他地方关闭标签后，再次双击边上又多了一个label输入框。
  graph.on("edge:mouseenter", ({ edge }) => {
      edge.addTools({
        name: "edge-editor"
      });
    });

### Expected behavior

同一时间只存在一个label框，且再次双击时不会消失

### Screenshots or Videos

![image](https://github.com/antvis/X6/assets/72301621/70f0add8-7b16-4bce-9209-be66c35e0df6)

![image](https://github.com/antvis/X6/assets/72301621/849b7fe4-c940-4681-8358-37fbfee213ed)

### Platform

- OS: Windows
- Browser: Chrome
- Version:  2.15.2

**Comment by NewByVector** [comment]
这个 https://github.com/antvis/X6/pull/3968 中已经修复，但是我发包发错了，我重新发一下，你升级到 2.15.4。

**Comment by yanghui123** [comment]
移动端双击事件无效呀
