### ISSUE TITLE
vue2创建port连接桩写法

### ISSUE THREAD

**Issue by nanfb** [antvis/X6#3975]
### 问题描述

我看了很多issus，没办法解决我的问题
引入创建组件
![image](https://github.com/antvis/X6/assets/56207464/ae3468b6-1a44-4670-86f3-f1e7ecc7e042)
![image](https://github.com/antvis/X6/assets/56207464/f542bf39-6cb3-4381-ae43-2c8083cf2492)
在这里添加或者生成的时候添加，都没什么效果，会在左上角出现个没法操作的圆圈

![image](https://github.com/antvis/X6/assets/56207464/57f599da-a7a0-4e7b-b001-f3fce2db4922)

### 重现链接

1

### 重现步骤

1

### 预期行为

生成连接桩

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by nanfb** [comment]
我会了，2.x的文档缺太多东西了

**Comment by Cai-Bring** [comment]
请问是怎么实现的

**Comment by nanfb** [comment]
> 请问是怎么实现的

看1.x的文档，要创建连接桩首先要有组

**Comment by CoderMonkie** [comment]
直接复制粘贴文档里的代码，出不来，遇到同样问题，画了四个只出来左上角一个（应该是重叠在这了），

使用以下（极简）配置正常：

```js
ports: {
  groups: {
    group1: {
      position: 'top',
    },
    group2: {
      position: 'right',
    },
    group3: {
      position: 'bottom',
    },
    group4: {
      position: 'left',
    },
  },
  items: [
    {
      group: 'group1',
    },
    {
      group: 'group2',
    },
    {
      group: 'group3',
    },
    {
      group: 'group4',
    },
  ],
},
```

**Comment by CoderMonkie** [comment]
![8E4D7954-7F34-4ca2-8894-816322EBA7D8](https://github.com/user-attachments/assets/09c3ff0c-3183-4b0e-bf38-1358f707cadf)
