### ISSUE TITLE
添加节点后的撤销重做问题

### ISSUE THREAD

**Issue by GuangZ96** [antvis/X6#3982]
### 问题描述

从Stencil侧边栏拖拽三个不同的节点(A、B、C)并按从左到右放置到画布中，调用graph.addEdge方法从左到右添加edge。调用撤销方法到画布只剩下A节点时再调用重做方法，只能恢复B节点，C节点不能恢复。此时graph.canRedo()为false，graph.getRedoStackSize()返回值为0

### 重现链接

.

### 重现步骤

从Stencil侧边栏拖拽三个不同的节点(A、B、C)并按从左到右放置到画布中，调用graph.addEdge方法从左到右添加edge。调用撤销方法到画布只剩下A节点时再调用重做方法，只能恢复B节点，C节点不能恢复。此时graph.canRedo()为false，graph.getRedoStackSize()返回值为0

### 预期行为

重做时能恢复三个节点到画布里

### 平台

操作系统: [macOS, Windows, Linux]
网页浏览器: [Google Chrome, Safari, Firefox ...]
X6 版本: 2.15.2

**Comment by NewByVector** [comment]
能否提供一个可以复现的 codesanbox 链接？

**Comment by GuangZ96** [comment]
> 能否提供一个可以复现的 codesanbox 链接？

问题已经解决了~
