### ISSUE TITLE
给节点添加子节点为什么移动子节点后就没有关联了

### ISSUE THREAD

**Issue by nanfb** [antvis/X6#3984]
### 问题描述

![image](https://github.com/antvis/X6/assets/56207464/62ba5f72-51d2-4d6c-910f-d6563edf5763)
给页面上的节点添加子节点，然后拖动子节点后父节点上就没有子节点了

### 重现链接

1

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]
1

**Comment by NewByVector** [comment]
子节点需要是添加到画布上的元素，而不是 `createNode` 创建出来的对象。
