### ISSUE TITLE
fromJSON toJSON转换异常

### ISSUE THREAD

**Issue by mingmingshiliyu** [antvis/X6#4002]
### Describe the bug

[{"params":{"clazz":"","label":"","type":"","shape":"","description":"","view":""},"attrs":{"text":{"fill":"#000000","fontFamily":"Arial, helvetica, sans-serif","fontSize":"","refX":"","refY":"","text":"hellookdawodjaod","textAnchor":"middle","textVerticalAnchor":"middle"},"body":{"stroke":"","strokeWidth":0,"fill":"","rx":0,"ry":0}},"id":"3b5cb057-6698-42b6-aa36-9e6cd3348817","Ports":{"groups":null,"items":null},"position":{"x":200,"y":200},"shape":"circle","size":{"width":0,"height":0},"visible":true,"zIndex":4,"source":{"cell":""},"target":{"cell":""},"task":{"extendedParams":null,"params":null,"actionName":"","successProbe":null,"failProbe":null,"retryProbe":null,"relayKeys":null},"clazz":"","assignType":"","assignValue":"","businessID":0,"businessType":"","promoterID":0,"operatorID":0},{"params":{"clazz":"","label":"","type":"","shape":"","description":"","view":""},"attrs":{"text":{"fill":"#000000","fontFamily":"Arial, helvetica, sans-serif","fontSize":"","refX":"","refY":"","text":"hello","textAnchor":"middle","textVerticalAnchor":"middle"},"body":{"stroke":"#8f8f8f","strokeWidth":1,"fill":"#fff","rx":6,"ry":6}},"id":"node1","Ports":{"groups":null,"items":null},"position":{"x":40,"y":40},"shape":"rect","size":{"width":0,"height":0},"visible":true,"zIndex":4,"source":{"cell":""},"target":{"cell":""},"task":{"extendedParams":null,"params":null,"actionName":"","successProbe":null,"failProbe":null,"retryProbe":null,"relayKeys":null},"clazz":"","assignType":"","assignValue":"","businessID":0,"businessType":"","promoterID":0,"operatorID":0},{"params":{"clazz":"","label":"","type":"","shape":"","description":"","view":""},"attrs":{"text":{"fill":"#000000","fontFamily":"Arial, helvetica, sans-serif","fontSize":"","refX":"","refY":"","text":"world","textAnchor":"middle","textVerticalAnchor":"middle"},"body":{"stroke":"","strokeWidth":0,"fill":"","rx":0,"ry":0}},"id":"node2","Ports":{"groups":null,"items":null},"position":{"x":160,"y":180},"shape":"rect","size":{"width":0,"height":0},"visible":true,"zIndex":4,"source":{"cell":""},"target":{"cell":""},"task":{"extendedParams":null,"params":null,"actionName":"","successProbe":null,"failProbe":null,"retryProbe":null,"relayKeys":null},"clazz":"","assignType":"","assignValue":"","businessID":0,"businessType":"","promoterID":0,"operatorID":0},{"params":{"clazz":"","label":"","type":"","shape":"","description":"","view":""},"attrs":{"text":{"fill":"#000000","fontFamily":"Arial, helvetica, sans-serif","fontSize":"","refX":"","refY":"","text":"开始","textAnchor":"middle","textVerticalAnchor":"middle"},"body":{"stroke":"#8f8f8f","strokeWidth":1,"fill":"#fff","rx":0,"ry":0}},"id":"2f087b43-9b01-4b74-b795-dc671fe98876","Ports":{"groups":null,"items":null},"position":{"x":50,"y":170},"shape":"image","size":{"width":0,"height":0},"visible":true,"zIndex":5,"source":{"cell":""},"target":{"cell":""},"task":{"extendedParams":null,"params":null,"actionName":"","successProbe":null,"failProbe":null,"retryProbe":null,"relayKeys":null},"clazz":"start","assignType":"user","assignValue":",1,","businessID":0,"businessType":"","promoterID":0,"operatorID":0},{"params":{"clazz":"","label":"","type":"","shape":"","description":"","view":""},"attrs":{"text":null,"body":{"stroke":"","strokeWidth":0,"fill":"","rx":0,"ry":0}},"id":"3933fa23-321d-4de3-9d8e-9d9d625ee698","Ports":{"groups":null,"items":null},"position":{"x":0,"y":0},"shape":"edge","size":{"width":0,"height":0},"visible":false,"zIndex":4,"source":{"cell":"node1"},"target":{"cell":"node2"},"task":{"extendedParams":null,"params":null,"actionName":"","successProbe":null,"failProbe":null,"retryProbe":null,"relayKeys":null},"clazz":"","assignType":"","assignValue":"","businessID":0,"businessType":"","promoterID":0,"operatorID":0},{"params":{"clazz":"","label":"","type":"","shape":"","description":"","view":""},"attrs":{"text":null,"body":{"stroke":"","strokeWidth":0,"fill":"","rx":0,"ry":0}},"id":"6d098a53-d91a-4964-b1c3-3dba99cb99d7","Ports":{"groups":null,"items":null},"position":{"x":0,"y":0},"shape":"edge","size":{"width":0,"height":0},"visible":false,"zIndex":6,"source":{"cell":"2f087b43-9b01-4b74-b795-dc671fe98876"},"target":{"cell":"node1"},"task":{"extendedParams":null,"params":null,"actionName":"","successProbe":null,"failProbe":null,"retryProbe":null,"relayKeys":null},"clazz":"","assignType":"","assignValue":"","businessID":0,"businessType":"","promoterID":0,"operatorID":0}]

<img width="475" alt="image" src="https://github.com/antvis/X6/assets/143821597/7f5200d4-2c45-49a2-b9bf-e536eb5e9e18">

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

我把图片tojson然后保存到mysql,取出后fromjson(json.parse(content)),然后报错怎么办
<img width="440" alt="image" src="https://github.com/antvis/X6/assets/143821597/eebbe635-67e5-426b-8d1d-384898e63bda">

### Expected behavior

正常展示

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by mingmingshiliyu** [comment]
解决了

**Comment by leo0807** [comment]
如何解决，我也遇到了转换异常的问题
