### ISSUE TITLE
使用调整边起点/终点的工具重复连接不能触发edge:connected事件

### ISSUE THREAD

**Issue by nanfb** [antvis/X6#4006]
### 问题描述

这个工具如果连接两次同一个cell只会触发一次，但是这个事件内我有修改连接到edge的length

### 重现链接

https://codesandbox.io/s/antv-x6-source-target-arrowhead-forked-ty8vnn?file=/src/index.ts

### 重现步骤

1

### 预期行为

每次连接都触发

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by a1235** [comment]
<img width="757" alt="微信图片_20231103004013" src="https://github.com/antvis/X6/assets/29188013/317cc296-33a6-49b6-8cf0-db9489cb5fcc">

因为2次连接到了同一个节点上了吧

**Comment by nanfb** [comment]
> <img alt="微信图片_20231103004013" width="757" src="https://user-images.githubusercontent.com/29188013/280064487-317cc296-33a6-49b6-8cf0-db9489cb5fcc.png">
> 因为2次连接到了同一个节点上了吧

对，我上面说了 ，已经解决，更换了不同的实现方式。
https://github.com/antvis/X6/issues/2779
