### ISSUE TITLE
Stencil添加新组，组内的节点无法拖动至画布

### ISSUE THREAD

**Issue by msojocs** [antvis/X6#4007]
### Describe the bug

示例都是在构造方法初始化分组；
但是，我使用 `addGroup` 向Stencil添加新组，
然后，添加节点，发现组内的节点无法拖动至画布。

![image](https://github.com/antvis/X6/assets/20937135/3e12f110-09bc-41cd-9c9f-41617abec5a8)

![image](https://github.com/antvis/X6/assets/20937135/c1c35ee1-deb7-4a5c-a528-67851fde6683)

### Your Example Website or App

https://codesandbox.io/s/peaceful-leftpad-vljfgv?file=/App.tsx

### Steps to Reproduce the Bug or Issue

1. Go to example url
2. 拖动构造方法中的分组 `Group(OK)` 中的节点，正常
3. 拖动额外添加的分组 `Group(Error)` 中的节点，无法拖动

### Expected behavior

拖动额外添加的分组 `Group(Error)` 中的节点，也能拖动。

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

参考codesandbox中的版本信息

**Comment by inside5545** [comment]
同问

**Comment by HujiaoBo** [comment]
同问
