### ISSUE TITLE
@antv/x6-vue-shape为什么没有index.cjs.js文件，我需要用commonjs形式引入

### ISSUE THREAD

**Issue by bighhhh** [antvis/X6#4012]
### 问题描述

我的项目vue使用commonjs形式引入的，现在使用@antv/x6-vue-shape包后编译组件有问题，vue-demi报错vue.util.warn找不到util，vue-demi使用commonjs文件其中时util是从default中获取的

### 重现链接

无

### 重现步骤

不兼容commonjs形式引入vue

### 预期行为

需要index.cjs.js文件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by NewByVector** [comment]
从 lib 目录引入就是 cjs。

**Comment by bighhhh** [comment]
> 从 lib 目录引入就是 cjs。

好的，谢谢
