### ISSUE TITLE
Safari浏览器上渲染节点时位置错误，chrome浏览器正常

### ISSUE THREAD

**Issue by doom-9** [antvis/X6#4020]
### Describe the bug

Safari浏览器上渲染vue节点时位置错误，chrome浏览器正常
![image](https://github.com/antvis/X6/assets/110001160/558e9fec-2f65-4d87-b592-4a78c634d327)

### Your Example Website or App

内部网站

### Steps to Reproduce the Bug or Issue

直接渲染用x6 export方法导出的json数据

### Expected behavior

节点位置正常

### Screenshots or Videos

Safari的
![image](https://github.com/antvis/X6/assets/110001160/0058e7df-21bb-49e0-906b-20034abe3ca3)
chrome的
![image](https://github.com/antvis/X6/assets/110001160/13000a09-bf8c-4eb4-94ef-94a6e7d7ef52)

### Platform

- OS: [macOS]
- Browser: [ Safari]
- Version: [17.1]

**Comment by 9t5c** [comment]
往你的 Vue 节点最外层的容器的样式添加 `position: fixed;`

**Comment by doom-9** [comment]
@9t5c 感谢老哥，解决了
