### ISSUE TITLE
使用html绘制节点，节点空白

### ISSUE THREAD

**Issue by Elias-cug** [antvis/X6#4055]
### 问题描述

使用html方式自定义节点，节点空白，没有插入html

### 重现链接

https://codesandbox.io/s/kwsu6m?file=/index.ts

### 重现步骤

这个是x6官方示例

### 预期行为

可以插入html

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- X6 版本: [2.15.5]

### 屏幕截图或视频（可选）

<img width="1512" alt="image" src="https://github.com/antvis/X6/assets/38312452/b0cdc37e-a660-41d1-9be3-e02e65230604">

**Comment by havenothingtosay** [comment]
请问这个问题解决了吗？我的版本是2.17.1，依然存在问题
