### ISSUE TITLE
API 优化

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#408]
API 设计原则：
1. 简单易用：用尽可能少的 api 和参数完成完备的功能
2. 语义清晰：API的命名约定具有一致性和精确性，便于记忆

欢迎大家在下面留言 x6 API 不合理的地方

例如
1. 所有配置中 filter 的使用和 js 中 数组要保持一致

**Comment by NewByVector** [comment]
rotating 选项中每次旋转的角度：grid -> angle

**Comment by qingchiapp** [comment]
能否支持针对单个节点的事件添加方式，而不是在全局去监听事件

举例：
```
graph.addEdge({
          source: {},
          target: {},
          onClick(()=>{})
        })
```
底层原理是否允许不太清楚，但以一种语法糖的形式去是否可行呢。

当用户以这种方式添加事件时，可以为edge对象生成全局uuid（目前是有这个逻辑的），然后将这个事件注册到全局，
内部判断，只有uuid为这个uuid时，才触发他的事件， 比如内部维护一个map对象，key为uuid，value为uuid对应的事件。

当触发全局的 graph.on时，获取当前对象的uuid，根据他的uuid去map中查找是否存在当前对象专属的事件，存在执行。

这种实现方式是否可行呢，盼回复，谢谢
