### ISSUE TITLE
自定义react/vue节点，在safari中存在兼容性问题

### ISSUE THREAD

**Issue by xianchangjie** [antvis/X6#4093]
### Describe the bug

节点无法移动，固定显示在画布左上角
<img width="663" alt="1" src="https://github.com/antvis/X6/assets/24728987/1be0258e-7ce6-4ffa-9279-b3a455055e71">

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-hxrsek?file=package.json,src%2FApp.css,src%2Findex.css,src%2FApp.jsx&terminal=dev

### Steps to Reproduce the Bug or Issue

自定义react节点，实用的是ant design react组件
将节点添加到graph中即可看到，组件处于画布左上角，且无法移动

### Expected behavior

自定义react节点，组件处于画布左上角，且无法移动

### Screenshots or Videos

<img width="663" alt="1" src="https://github.com/antvis/X6/assets/24728987/1be0258e-7ce6-4ffa-9279-b3a455055e71">

### Platform

- OS: macOS
- Browser: Safari
- Version: 17.1 (18616.2.9.11.10, 18616)

**Comment by lloydzhou** [comment]
在issue列表搜索一下就有好几个相关的

#4060 #2863 #751

**Comment by xianchangjie** [comment]
🙏感谢
