### ISSUE TITLE
transform插件配置仅某些节点不可改变

### ISSUE THREAD

**Issue by zzxming** [antvis/X6#4121]
### 功能描述

对配置了某些属性的节点才可选中并进行transform，未配置此属性的节点不会出现可交互进行transform的点

### 期望解决方案

希望和插件 @antv/x6-plugin-selection 配置中的 filter 类似

**Comment by AllenMRbai** [comment]
这个有解决方案了吗。我们这边也有这方面的需求，只有画布里面的容器节点可以缩放大小，其他的节点不可一缩放。

**Comment by tong822218** [comment]
这个为啥给close了，我感觉这个需求很常见，到现在也没知道解决方案
