### ISSUE TITLE
2.x 版本的 x6-angular-shape 如何支持 Angular 12 的 ngOnChanges，非常急，球球了！！！

### ISSUE THREAD

**Issue by Vibing** [antvis/X6#4122]
### Describe the bug

![image](https://github.com/antvis/X6/assets/10387532/69c5e583-b4d9-4062-be5c-28e4e1892ac0)

我们公司Angular版本是 v12，x6 是 v2.0.2

如何在 `ngArguments` 改变时能触发 `ngOnChanges`？ 求大佬给个demo，非常着急，感谢！！！

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

1. ngArguments的变化, 对 TemplateRef的场景并不生效. 虽然对Component生效但是无法触发ngOnChanges.

### Expected behavior

给个能触发 ngOnChanges 的 hack

### Platform

- OS: macOS
- Browser: Chrome
- Version: 2.15.2

**Comment by Eve-Sama** [comment]
https://github.com/Eve-Sama/x6-angular-shape/issues/2#issuecomment-1871701424
