### ISSUE TITLE
没有导出成员Addon

### ISSUE THREAD

**Issue by Prixii** [antvis/X6#4127]
### 问题描述

在vue3，ts下，我尝试使用Addon，但是报错说没有导出成员Addon
![image](https://github.com/antvis/X6/assets/87805157/641caf17-11ad-4827-8738-43a6dec43f37)

### 重现链接

null

### 重现步骤

import { Addon } from '@antv/x6'

### 预期行为

在我找到的即使是官方示例中，似乎也没有明确写道Addon有其他来源，都是直接通过 `import {Addon} from '@antv/x6'` 就行的了

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.16.1]

**Comment by sangjunke** [comment]
![image](https://github.com/antvis/X6/assets/36063198/6f0a0438-22cf-46db-a143-9b2e393af2ee)
![image](https://github.com/antvis/X6/assets/36063198/d71e4ca5-71ad-4354-a7a0-72d6dd5edd5e)

真的离谱，引入了2.x版本的X6做开发，发现官方文档两次使用了 Addon 方法，却没有说从哪里导入的此方法
全局搜索文档也没有说明如何引入  没人维护的吗？我翻了issues发现好几次有人提出此问题，并没有人解决 真是可笑

**Comment by Prixii** [comment]
如果你也有这个问题，可以去文档的 [插件] 目录中找（虽然两个版本的文档其中一个文档里面没写），Addon 本身是一个插件，需要另外下载导入

**Comment by TimelyRainX** [comment]
怎么引入呢 没有看到相关 Addon文档呢？

**Comment by Prixii** [comment]
> 怎么引入呢 没有看到相关 Addon文档呢？

怪了，可能记错了...
但是 Addon 似乎在文档中只被引用了两次，一次是`Addon.Dnd`，一次是`Addon.Stencil`，但是实际上这两个 class 都可以不需要 Addon 就能直接创建
说不定 Addon 是一个被移除的东西，但是文档没来得及更新
