### ISSUE TITLE
关于 dag demo 中 getNodes 方法返回节点不一致问题

### ISSUE THREAD

**Issue by eivmosn** [antvis/X6#413]
首次调用 getNodes 方法时可以返回画布的所有节点，一但操作如删除一个节点后返回的值就是上次的结果 

getNodes = (): N[] => {
    return (this.graph?.getNodes() as N[]) || []
}

尝试 getEdges 方法好像也存在这个问题... 不知道是不是我的用法不对

**Comment by lyn-boyu** [comment]
删除后没有更新model上的数据，我们fix下

**Comment by Gakki-f** [comment]
请问官方实例的draw有源码吗
