### ISSUE TITLE
使用@antv/x6-plugin-scroller插件后，节点的默认定位x:0,y:0不就不在左上角了

### ISSUE THREAD

**Issue by alamhubb** [antvis/X6#4132]
### Describe the bug

使用@antv/x6-plugin-scroller插件后，节点的默认定位x:0,y:0不就不在左上角了

不开启，scroller位置正确

![image](https://github.com/antvis/X6/assets/14007972/d19fd4bd-2b93-46d8-9108-701b8eb1d12a)

```
    graph.use(
        new Scroller({
          enabled: true,
          pannable: true
        }),
    )
```

开启后

![image](https://github.com/antvis/X6/assets/14007972/fa1a2993-f5f6-4510-a7d6-1ab83ac5fdc5)

位置异常，跑右上角去了

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-rdk5bt?file=package.json,src%2FApp.vue,src%2Fcomponents%2FHelloWorld.vue&terminal=dev

### Steps to Reproduce the Bug or Issue

使用@antv/x6-plugin-scroller插件后，节点的默认定位x:0,y:0不就不在左上角了

### Expected behavior

期望在左上角

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by cnyballk** [comment]
给container设置一下跟可视窗口一样的宽高呗

**Comment by alamhubb** [comment]
> 给container设置一下跟可视窗口一样的宽高呗

好的 谢谢
