### ISSUE TITLE
xflow1版本中的NodeCollapsePanel组件，也就是左侧折叠面板，自定义组件时，click事件无法触发，怎么解决

### ISSUE THREAD

**Issue by shanglingyi111** [antvis/X6#4137]
### Describe the bug

1版本中的NodeCollapsePanel组件，也就是左侧折叠面板，自定义组件时，click事件无法触发

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

none

### Expected behavior

点击事件被触发

### Platform

谷歌浏览器

**Comment by NewByVector** [comment]
XFlow 1.x 已经不维护了，请升级到 2.x。
