### ISSUE TITLE
tsc && vite build ；Report node_modules/@antv/x6/**/*.ts errors

### ISSUE THREAD

**Issue by hsbtr** [antvis/X6#4138]
### Describe the bug

![image](https://github.com/antvis/X6/assets/46487804/e723f959-f27d-4ee0-a05f-1d76f3b87157)
![image](https://github.com/antvis/X6/assets/46487804/cb265a97-04ca-4b77-8e30-045e7f90db7b)
Packaging is directly interrupted. Is there any way to avoid it?

### Your Example Website or App
https://github.com/hsbtr/my-vite-react

### Steps to Reproduce the Bug or Issue

tsc && vite build 
or
This error will be reported when used in create-react-app

### Expected behavior

No error reported

### Screenshots or Videos

no

### Platform

@antv/xflow@2.0.3
@antv/x6@2.16.1

### Additional context

no

**Comment by hsbtr** [comment]
Supplement; typescript5.x

**Comment by cyrilluce** [comment]
为什么你引用到了 src 目录下的文件? 按道理应该是 lib 或 es 目录的

**Comment by hsbtr** [comment]
> 为什么你引用到了 src 目录下的文件? 按道理应该是 lib 或 es 目录的

昨天下午发现了，今台正准备关闭该问题，注册元素的时候有个声明从注册方法源码里瞧，造成了这个大乌龙，后面才发现使用Node就可以了。非常感谢回复此问题

![Snipaste_2024-01-08_09-08-17](https://github.com/antvis/X6/assets/46487804/1185f690-08b6-42a2-97bb-584d972e9c09)
