### ISSUE TITLE
2.17.1 这个类型是不是应该非必填

### ISSUE THREAD

**Issue by America-first-melon** [antvis/X6#4147]
### Describe the bug

![image](https://github.com/antvis/X6/assets/21686182/dde49eec-1cfd-4576-aa03-5e3059a496ec)
既然已经默认了 anchor 是不是非必填，版本自动升了级， eslint 直接error了。
 `snap: boolean | { radius: number; anchor: 'center' | 'bbox' }`

### Your Example Website or App

null

### Steps to Reproduce the Bug or Issue

null

### Expected behavior

null

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.17.1]

**Comment by NewByVector** [comment]
@xiawenqi 作者来解决一下？
