### ISSUE TITLE
antv x6上的连线怎么允许重连到其他节点

### ISSUE THREAD

**Issue by ziqiflow** [antvis/X6#4162]
### 功能描述

<img width="389" alt="image" src="https://github.com/antvis/X6/assets/16557978/db267815-0226-4d5e-a9cf-e27d4999e909">
我看了所有文档和案例都没有涉及重连到其他port点

### 期望解决方案

增加这个功能。gojs里面都有的

**Comment by chinaBerg** [comment]
同问，这是一个很重要的需求场景，但是整个问题没有提到如何解决
