### ISSUE TITLE
Dnd插件一定要clone吗

### ISSUE THREAD

**Issue by America-first-melon** [antvis/X6#4169]
### Describe the bug

dnd 一定要 clone 吗？

场景： 拖动前与拖动后的attr样式不一致，getDropNode 后需要修改 attrs

```
// 示例没有问题。
const dnd = new Addon.Dnd({
  getDropNode(node) {
    const { width, height } = node.size()
    // 返回一个新的节点作为实际放置到画布上的节点
    return node.clone().size(width * 3, height * 3)
  },
})
```

```
// 这样写没有作用，必须clone后replaceAttrs才有作用
const dnd = new Addon.Dnd({
  getDropNode(node) {
    node.replaceAttrs({})
    return node
  },
})
```

### Your Example Website or App

null

### Steps to Reproduce the Bug or Issue

null

### Expected behavior

null

### Screenshots or Videos

null

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

### Additional context

null

**Comment by NewByVector** [comment]
是的，需要 clone 一份的。

**Comment by America-first-melon** [comment]
`dndStart` 之前的 `createNode`  就是在生成新的  Node 了，`getDropNode` 的时候又使用 cloneNode,    忽然感觉前面的createNode没有了Node作用，只是作为一个拖动的形状（但是却又生成了图形Node）。 

不知道这样理解是否偏差了。

我这里拖动的图形数据非常大，携带的data，如果json格式有时候几百K，所以drop的时候不是太想再clone一遍，目前已经通过其他方式处理了。

**Comment by NewByVector** [comment]
`getDragNode`: 返回拖拽过程中的节点，可以是任意节点，默认是 clone 原始节点。
`getDropNode`: 返回放置到画布的节点，可以是任意节点，默认是 clone 拖拽节点。

**Comment by America-first-melon** [comment]
> `getDragNode`: 返回拖拽过程中的节点，可以是任意节点，默认是 clone 原始节点。 `getDropNode`: 返回放置到画布的节点，可以是任意节点，默认是 clone 拖拽节点。

close了，api clone 只是默认行为，也支持自定义控制，已经处理了。 
感谢。
