### ISSUE TITLE
节点拖动的时候会出现卡顿

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#417]
### Current Behavior

1. 测试出现卡顿的地方
2. 方案
     1）用选择框代替节点移动

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by HelloToBe-San** [comment]
拖动大量节点时候会出现卡顿，script引入x6时候，也是框选拖动
