### ISSUE TITLE
yarn add @antv/x6 时报错，提示“证书过期”？

### ISSUE THREAD

**Issue by Aolcycle** [antvis/X6#4178]
### 问题描述

yarn add v1.22.19
warning package.json: License should be a valid SPDX license expression
warning demo@1.0.0: License should be a valid SPDX license expression
[1/6] Validating package.json...
warning demo@1.0.0: License should be a valid SPDX license expression
[2/6] Resolving packages...
error An unexpected error occurred: "https://registry.npm.taobao.org/@antv%2fx6-plugin-dnd: certificate has expired".
info If you think this is a bug, please open a bug report with the information provided in "@.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### 重现链接

yarn add @antv/x6

### 重现步骤

新建vue项目
add x6
报错

### 预期行为

xx

### 平台

- 操作系统: [Windows]
- X6 版本: [2.x.]
- nodeJS版本: [18.16.0]

**Comment by gdutwyg** [comment]
我也遇到了，然后我换回官方源，我用的yarn。

**Comment by CasoMemory** [comment]
taobao.org 域名很久之前就通知说不维护了，配置下 registry 就行了。https://npmmirror.com/
