### ISSUE TITLE
请问限制节点拖拽时，就不能给节点添加自定义节点工具了吗？

### ISSUE THREAD

**Issue by sunjiesama** [antvis/X6#4215]
### 问题描述

当我添加了nodeMovable:false时，节点上的自定义工具都不见了，或许是我哪里写的不对，请指导一下，谢谢了

### 重现链接

https://x6.antv.antgroup.com/examples/node/tool/#button-remove

### 重现步骤

在第四行代码下添加 interacting: false,左侧demo节点上的自定义工具消失

### 预期行为

禁用节点拖拽时，节点上的自定义工具仍正常使用

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

### 屏幕截图或视频（可选）

<img width="1363" alt="image" src="https://github.com/antvis/X6/assets/54022918/3c8a85eb-9f5f-4583-81dd-054af6ba63a6">

<img width="1799" alt="image" src="https://github.com/antvis/X6/assets/54022918/11b8946a-6d86-4e99-9f69-94ea27a4408d">

**Comment by sunjiesama** [comment]
纠正：重现步骤重现步骤的interacting为false

**Comment by fuxichen** [comment]
你应该加
```
interacting: {
    nodeMovable:false
},
```
而不是`interacting:false`,这个是禁止所有交互行为，包括删除、移动等等

**Comment by sunjiesama** [comment]
> 你应该加
> 
> ```
> interacting: {
>     nodeMovable:false
> },
> ```
> 
> 而不是`interacting:false`，这是禁止所有交互行为，包括删除、移动等等

好的，谢谢，怪我没仔细阅读文档=。=
