### ISSUE TITLE
页面切换，画布重复载入Vue节点，会多次重复调用onMounted方法

### ISSUE THREAD

**Issue by songday** [antvis/X6#4216]
### Describe the bug

大家好。
我使用Vue3配合@antv/x6-vue-shape
在使用AntV X6过程中，发现当Vue页面切换，来回进入到画布里时
画布里的Vue节点，调用自身的onMounted方法，会成倍的增加

### Your Example Website or App

https://github.com/songday/antvx6vue

### Steps to Reproduce the Bug or Issue

1. git clone https://github.com/songday/antvx6vue.git
2. cd antvx6vue
3. npm i
4. npm run dev
5. 打开浏览器，并请求
6. 启用浏览器的`检查模式`
7. 点击页面上的`Go to Graph`按钮，跳转到另外一个页面，能看到`node loaded`在console打印了一次
8. 点击页面上的`Go to Home`按钮，返回
9. 再点击页面上的`Go to Graph`按钮，跳转到另外一个页面，能看到`node loaded`打印了多次
10. 点击页面上的`Go to Home`按钮，返回
11. 再点击页面上的`Go to Graph`按钮，跳转到另外一个页面，能看到`node loaded`打印了更多次
12. 以此往复，会看到到达`Graph`页面，打印`node loaded`的次数会成倍增加

### Expected behavior

希望重复进入，一个节点只调用一次`onMounted`方法

### Platform

- OS: Windows 10 家庭中文版 22H2
- Browser: Firefox（Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0）
- Version: @antv/x6: ^2.18.1，@antv/x6-vue-shape: ^2.1.2

**Comment by lloydzhou** [comment]
https://github.com/songday/antvx6vue/pull/1/files
![image](https://github.com/antvis/X6/assets/1826685/ce0d9424-d27e-4c33-a801-05462b23e894)

组件销毁的时候，主动调用一下dispose()否则不会正常销毁graph以及内部的节点
