### ISSUE TITLE
change:data 事件部分情况下不触发

### ISSUE THREAD

**Issue by fuxichen** [antvis/X6#4217]
### Describe the bug

# change:data 事件部分情况下不响应
![image](https://github.com/antvis/X6/assets/17411462/312dc6c5-0a42-424d-935e-67361bb0a688)

![image](https://github.com/antvis/X6/assets/17411462/faadb982-8842-4ff5-af54-b6f7e4f703d4)
如上图，第一种修改方式会触发change:data，第二种修改方式不会。

### Your Example Website or App

https://codesandbox.io/p/sandbox/mo-ban-forked-kfgrt9?file=%2Fsrc%2FApp.tsx%3A66%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt2j5hla0006356hu2zbzxo4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt2j5hl90002356hx92tgc2o%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt2j5hl90003356h9agcur4e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt2j5hla0005356h856aa9is%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt2j5hl90002356hx92tgc2o%2522%253A%257B%2522id%2522%253A%2522clt2j5hl90002356hx92tgc2o%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt2j829i0002356ga2ugzlqy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A66%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A66%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clt2j829i0002356ga2ugzlqy%2522%257D%252C%2522clt2j5hla0005356h856aa9is%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt2j5hl90004356hcaqcczfb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clt2j5hla0005356h856aa9is%2522%252C%2522activeTabId%2522%253A%2522clt2j5hl90004356hcaqcczfb%2522%257D%252C%2522clt2j5hl90003356h9agcur4e%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt2j5hl90003356h9agcur4e%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce the Bug or Issue

1. 创建节点A
2. 监听change:data事件
3. 在节点A的 data 中设置一个对象类型的数据list
4. 获取节点A的data
5. 修改list中的数据然后设置回去
6. change:data未触发

### Expected behavior

触发change:data事件

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [2.18.1, 2.15.5....]

### Additional context
大多数情况下会有将节点数据取出来，然后传递给别的组件或方法处理（如编辑数据的组件），修改后设置回节点，然后再实时监听图以及数据的改变，并将当前的图缓存起来，所以需要正确监听到这个数据改变的事件

**Comment by cuidong626** [comment]
第二种方式改了引用对象的值，所有值比对会认为没有改变。
![image](https://github.com/antvis/X6/assets/22650893/297bfd03-f9bd-4aaf-9b64-23bbc7523b9f)

**Comment by cuidong626** [comment]
你在浏览器上断点调试一下这边的逻辑，你就知道为啥第二个方案不行了。
![image](https://github.com/antvis/X6/assets/22650893/a2caa165-cfee-48d3-8940-53fbace5089a)

**Comment by yi-ge** [comment]
我也遇到这个问题。

**Comment by fuxichen** [comment]
> 我也遇到这个问题。

我看了他源码，他触发事件的条件是set的数据不能和旧数据相同，然后旧数据没做深拷贝，然后对象数据因为引用问题你在外面修改了，导致他里面的旧数据也改了，所以set的时候他一对比，数据是一样的，就不出发changedata事件了
