### ISSUE TITLE
导入 vue 组件自定义节点和 html 自定义节点时，无法控制节点大小，始终会渲染成一个固定尺寸

### ISSUE THREAD

**Issue by FullStackPlayer** [antvis/X6#4219]
### Describe the bug

我在画布上放置了 3 个节点，两个 html 节点一个 vue 节点，均存在同样的问题，节点大小无法自定义。
具体可以参见 stackblitz 链接。

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-rvfiv6?file=src%2FApp.vue

更详细内容请参见 README.md 文档。

### Steps to Reproduce the Bug or Issue

1、把鼠标放到自定义节点上的时候，鼠标呈现四向箭头形状，点击可以挪动节点位置；
2、继续往下或者往右移动鼠标至超出节点的可视区域，此时依然是四向箭头形状，依然可以按住鼠标拖拽挪动节点；
3、向右向下直至移出去很远（具体来说就是以节点左上角为起始点，宽度超出 320，高度超出 100vh）才会恢复为手型（为了方便验证可以按住 ctrl 滚动鼠标滚轮缩小画布）。

### Expected behavior

希望这两种自定义节点的实际尺寸可以与可视部分相吻合。

### Platform

- OS: Windows
- Browser: Chrome
- Version: 2.18.1

**Comment by fuxichen** [comment]
![image](https://github.com/antvis/X6/assets/17411462/d034797e-8a7a-4f07-90a8-8dd4beb05d2b)
应该是你自己代码问题哦，
他渲染的节点里面用了body标签，然后你代码里设置了body标签的最小宽高，所以才会变得很大

**Comment by FullStackPlayer** [comment]
> ![image](https://private-user-images.githubusercontent.com/17411462/308779749-d034797e-8a7a-4f07-90a8-8dd4beb05d2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODE2MTAsIm5iZiI6MTcwOTI4MTMxMCwicGF0aCI6Ii8xNzQxMTQ2Mi8zMDg3Nzk3NDktZDAzNDc5N2UtOGE3YS00ZjA3LTkwYTgtOGRkNGJlYjA1ZDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA4MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMTAxNWIxYjIxMmU2YjJmZmJhNjhmYmUwNWUwNWQzY2QyNzJjMjUyNWNjNTYzNzVkZDE5YTAwY2VlMDlmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k7cHwjfvX_uInP4QyFGhdil2uYn9hoOTC8T-kwbiRPs) 应该是你自己代码问题哦， 他渲染的节点里面用了body标签，然后你代码里设置了body标签的最小宽高，所以才会变得很大

感谢您的分析和提示，实在没想到问题竟然出在这里，svg 下的 foreignObject 下面的 body 竟然应用了我的全局 body style，现在我知道怎么处理了，非常感谢。

**Comment by FullStackPlayer** [comment]
问题已经解决，这不是个 bug，属于一种边界情况，感谢 @fuxichen 的帮助。
