### ISSUE TITLE
在Safari浏览器中边上的箭头渲染问题

### ISSUE THREAD

**Issue by gitzjy** [antvis/X6#4224]
### 问题描述

1、切换箭头不会更新。2、箭头添加label，重新渲染箭头消失

![WechatIMG44](https://github.com/antvis/X6/assets/56381688/4c68f7f1-6858-42e1-860c-f691d4416c57)

### 重现链接

https://x6.antv.antgroup.com/examples/edge/marker/#native-markers

### 重现步骤

进入官网选择边下的箭头

### 预期行为

预期在safari中箭头可以正常渲染并更新

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Safari]
- X6 版本: [2.18.1]

**Comment by gitzjy** [comment]
> 你更新下safari浏览器的版本试试？版本16.3 (18614.4.6.1.6)这个版本是好的 <img alt="image" width="280" src="https://private-user-images.githubusercontent.com/36500514/311712768-4810845f-3a6b-4e2e-b610-c79efb10d5b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTYwNDgsIm5iZiI6MTcxMDQ5NTc0OCwicGF0aCI6Ii8zNjUwMDUxNC8zMTE3MTI3NjgtNDgxMDg0NWYtM2E2Yi00ZTJlLWI2MTAtYzc5ZWZiMTBkNWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA5NDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNzlhMmJlZTMwMjUzMmE3ODJlNDZkNzg5MTdiOTljMzE0YWFiZTU0YzVmZTIzOWU4MDQ3NmI0ZmJlYjkwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fx9HfRRl9ZYUkElawGIH1DXkl-RUkgOxoejbK9OeBNc">

**Comment by gitzjy** [comment]
![image](https://github.com/antvis/X6/assets/56381688/e2ba15e5-32b8-4641-9650-d453b3fff632)
最新版本的不行

**Comment by Jim-0** [comment]
Try
https://github.com/antvis/X6/issues/4053#issuecomment-1943133374
