### ISSUE TITLE
npm ERR! request to https://registry.npm.taobao.org/@antv%2fx6 failed, reason: certificate has expired  

### ISSUE THREAD

**Issue by MRFengC** [antvis/X6#4225]
### 问题描述

npm install @antv/x6 --save 无法下载

### 重现链接

null

### 重现步骤

终端输入npm install @antv/x6 --save 

### 预期行为

npm install @antv/x6 --save 可以正常下载

### 平台

- 操作系统: [Windows]
-

**Comment by mewcoder** [comment]
淘宝 NPM 镜像站切换了新域名， `npm config set registry https://registry.npmmirror.com`
