### ISSUE TITLE
鼠标离开edge时，清除其他小工具，会使edge-editor消失，编辑会失败

### ISSUE THREAD

**Issue by Li-0221** [antvis/X6#4239]
### Describe the bug

- 在edge上添加edge-editor工具
- 在鼠标移入edge时添加['vertices', 'segments', 'button-remove']工具
- 鼠标移出时移除['vertices', 'segments', 'button-remove']工具
- edge-editor消失，编辑失败

复现连接 https://codesandbox.io/p/sandbox/mo-ban-forked-9fzfqs?file=%2Fsrc%2FApp.tsx%3A66%2C12

### Your Example Website or App

https://codesandbox.io/p/sandbox/mo-ban-forked-9fzfqs?file=%2Fsrc%2FApp.tsx%3A66%2C12

### Steps to Reproduce the Bug or Issue

- 在edge上添加edge-editor工具
- 在鼠标移入edge时添加['vertices', 'segments', 'button-remove']工具
- 鼠标移出时移除['vertices', 'segments', 'button-remove']工具
- edge-editor消失，编辑失败

### Expected behavior

鼠标移出edge，清楚其他工具，edge-editor不消失

### Screenshots or Videos

https://github.com/antvis/X6/assets/75083207/649ab587-dbe0-4d9d-99d4-215d01425b27

### Platform

- OS:macOS
- Browser: Edge
- Version: 版本 123.0.2420.53 (正式版本) (arm64)

**Comment by Li-0221** [comment]
我看到与 https://github.com/antvis/X6/issues/3574 类似

**Comment by gthdweb** [comment]
我是使用延迟方法能够解决此问题，希望有更好的方式能够解决这个问题。  
// edge hover移除删除按钮
  graph.on('edge:mouseleave', ({ edge }) => {
    setTimeout(() => {
      //立即移除会导致edge-editor输入内容消失
      edge.removeTool('button-remove');
    }, 499);
  });

**Comment by JoryPai** [comment]
+1
