### ISSUE TITLE
节点大小调节

### ISSUE THREAD

**Issue by young-mu** [antvis/X6#425]
**点选节点后，可以用鼠标拖动的方式进行节点大小的调节**

背景：准备用 X6 实现一个组态/看板的编辑器，因此将组件拖拽进来可以用鼠标对节点进行大小调节（而非只是右边栏输入属性宽高的方式）。类似下面的效果图 ![image](https://user-images.githubusercontent.com/7543236/102428598-4d642400-404d-11eb-8293-29e840cc4bd7.png)。其它的功能评估下来都满足，唯一遗憾的就是没有原生支持这个功能，希望后续支持。

**Comment by bubkoo** [comment]
@young-mu 目前是支持的 https://x6.antv.vision/zh/docs/api/graph/transform#resizing

**Comment by young-mu** [comment]
@bubkoo 好的，感谢🙏
