### ISSUE TITLE
官网实例开启拖拽异步验证函数之后，同一个位置出现多个图元被添加，并且建议优化异步添加操作的效果

### ISSUE THREAD

**Issue by daigang666** [antvis/X6#429]
### Expected Behavior
从工具栏拖拽节点可以实现正常异步添加

![image](https://user-images.githubusercontent.com/42136433/102454437-fc6a2500-4078-11eb-81de-5781a3cafa3a.png)

### Current Behavior
开启异步验证函数之后，拖入节点，单击确认位置之后，拖拽的效果没有消失（也就是鼠标移动还有图跟着动，感觉没有放上去，建议改为确认位置之后出现一个加了loading的图元）
同时等待异步结束之后确认位置的地方出现多个图元重叠

### Steps To Reproduce

1. 官方x6-app-draw实例在class FlowGraph 的initStencil函数，添加工具栏异步验证函数
2. 
  private static initStencil() {
    this.stencil = new Addon.Stencil({
      target: this.graph,
      stencilGraphWidth: 280,
      search: { rect: true },
      collapsable: true,
      validateNode:(node) => {
        console.log('validateNode')
        console.log(node)
        return new Promise((resolve,reject) => {
          setTimeout(() => {
            resolve(true)
          }, 2000);
        })
      },
      groups: [
        {
          name: 'basic',
          title: '基础节点',
          graphHeight: 180,
        },
        {
          name: 'combination',
          title: '组合节点',
          layoutOptions: {
            columns: 1,
            marginX: 60,
          },
          graphHeight: 260,
        },
        {
          name: 'group',
          title: '节点组',
          graphHeight: 100,
          layoutOptions: {
            columns: 1,
            marginX: 60,
          },
        },
      ],
    })
    const stencilContainer = document.querySelector('#stencil')
    stencilContainer?.appendChild(this.stencil.container)
  }

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@daigang666 我们修复了异步验证的问题，异步验证时的更多体验细节可以在 `validateNode` 方法中去实现，比如你说的显示一个 loading 的状态，可以在 `validateNode` 方法中拿到 `node` 去更新 `node` 的样式。

**Comment by bubkoo** [comment]
@daigang666 看文档中最新的demo，拖拽圆形时触发异步验证，并给了 loading 效果。https://x6.antv.vision/zh/docs/tutorial/basic/dnd
