### ISSUE TITLE
Html类型Node拖拽不能正确生成

### ISSUE THREAD

**Issue by saperliu** [antvis/X6#430]
拖拽Node为Html类型的Node拖拽不能正确生成在画布里

### Expected Behavior
将一个Node为html类型的点拖拽到画布里，只生成了基本的rect类型，并没有html的内容生成。

### Additional Context

此示例可以复现这个问题，那个Circle就是没有生成html内容

https://codesandbox.io/s/jovial-galileo-rg8zp?file=/src/app.tsx

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@saperliu 参考这个 https://codesandbox.io/s/focused-thompson-phiks?file=/src/app.tsx

**Comment by saperliu** [comment]
确实可以解决这个问题。下面给出解决办法。

这样的不可以生成：
`new Circle({
            width: 60,
            height: 60,
            shape: "html",
            html: () => {
              const wrap = document.createElement("div");
              wrap.style.width = "100%";
              wrap.style.height = "100%";
              wrap.style.display = "flex";
              wrap.style.alignItems = "center";
              wrap.style.justifyContent = "center";
              wrap.style.border = "2px solid #9254de";
              wrap.style.background = "#3a3a3a";
              wrap.style.borderRadius = "4px";
              wrap.innerText = "Hello Circle ";
              return wrap;
            }
          });`

下面的node可以拖拽生成：
`this.graph.createNode({
            width: 60,
            height: 60,
            shape: "html",
            html: () => {
              const wrap = document.createElement("div");
              wrap.style.width = "100%";
              wrap.style.height = "100%";
              wrap.style.display = "flex";
              wrap.style.alignItems = "center";
              wrap.style.justifyContent = "center";
              wrap.style.border = "2px solid #9254de";
              wrap.style.background = "#3a3a3a";
              wrap.style.borderRadius = "4px";
              wrap.innerText = "Hello Circle ";
              return wrap;
            }
          });`
