### ISSUE TITLE
增加图算法

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#432]
### Expected Behavior

增加图算法，比如
1. 删除一个节点的所有后续节点

**Comment by bubkoo** [comment]
@NewByVector 这个算法默认在 graph 上就有，增加 DEMO 就行了，比如 hover 一个 DAG 图中的节点是，高亮所有路径上的节点和边，就会使用到上面的图算法。

在高级教程文档中可以写一遍文档，来说说常用的图算法。graph 上最短路径算法也是有的，看看还缺什么再补。

**Comment by zmzimpl** [comment]
> @NewByVector 这个算法默认在 graph 上就有，增加 DEMO 就行了，比如 hover 一个 DAG 图中的节点是，高亮所有路径上的节点和边，就会使用到上面的图算法。
> 
> 在高级教程文档中可以写一遍文档，来说说常用的图算法。graph 上最短路径算法也是有的，看看还缺什么再补。

请问对应的 API 是哪个？

**Comment by NewByVector** [comment]
@zmzimpl 这块有很多相关 [api](https://x6.antv.vision/zh/docs/api/graph/model#searchcell)
