### ISSUE TITLE
使用React节点重绘画布时会报Warning: Attempted to synchronously unmount a root while React was already rendering

### ISSUE THREAD

**Issue by gdtdpt** [antvis/X6#4328]
### 问题描述

使用React节点已经生成流程图后，加载了不同的流程图数据后重绘流程图时会出现以下警告：Warning: Attempted to synchronously unmount a root while React was already rendering。先使用graph.dispose()再重新生成画布也会出现同样警告，伪代码如下：
```js
// ...
useEffect(() => {
    if (graph) {
        graph.dispose();
    }
    graph = new Graph({...});
    graph.fromJSON(data);
    // ....
}, [data]);  // data由react-redux控制
// ...
```

### 重现链接

无

### 重现步骤

使用以上代码重现

### 预期行为

警告消失

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: 2.18.1

**Comment by gdtdpt** [comment]
使用Portal方式解决了。

**Comment by pot-code** [comment]
> 使用Portal方式解决了。

正解

**Comment by fkc-alt** [comment]
您好，请问有示例吗，我也遇到同样的问题。如果可以的话，非常感谢您可以帮助到我~

**Comment by gdtdpt** [comment]
> 您好，请问有示例吗，我也遇到同样的问题。如果可以的话，非常感谢您可以帮助到我~

我是在Node定义和注册的地方导出X6ReactNodeProvider
```jsx
import { register, Portal } from '@antv/x6-react-shape';

const XxxNode = (props) => { ... }

register({
  shape: 'xxx-node',
  component: XxxNode,
});

export const X6ReactNodeProvider = Portal.getProvider();

export default EditFlowNode;
```

在画布处的Context.Provider中导入
```jsx
import { X6ReactNodeProvider } from '...';

...

export const XxxProvider = (props) => {
  ...
  return (
    <Context.Provider>
       <X6ReactNodeProvider />
       ....
    </Context.Provider>
  );
}
```
在[官方文档](https://x6.antv.antgroup.com/tutorial/intermediate/react)的`Portal方式`下方图形中也有示例代码
