### ISSUE TITLE
自定义节点数据更新视图无法更新

### ISSUE THREAD

**Issue by amysxhuang** [antvis/X6#4330]
### Describe the bug

在使用@antv/x6-vue3-shape自定义vue3节点, 通过node的change:data事件更新了vue组件内的数据，但是视图不更新，代码片段如下
1、注册节点
Graph.registerNode(‘task', {
  width: 220,
  height: 52,
  inherit: "vue3-shape",
  component: NodeBase,
  ports: {
    ...PORTS,
    items: [
      {
        id: X6_PORT_OUT_RIGHT,
        group: X6_PORT_OUT_RIGHT
      }
    ]
  },
  tools: [
    {
      name: 'contextmenu'
    }
  ]
})

2、自定义NodeBase
<template>
  <div class="node-base" :key="vueKey">
    <div class="content">
      <img
        class="node-type-img"
        :src="getAssetsFile(`images/node-type-icons/${state.data.taskType}.png`)"
        @error="errorImgHandler"
      />
      <div class="title">{{ state.data.taskName || '--' }}</div>
    </div>
    <div v-if="state.data.desc" class="desc">{{ state.data.desc || '--' }}</div>
  </div>
</template>

<script setup lang='ts'>
import { getAssetsFile } from '@/utils/universal'
import { cloneDeep } from 'lodash'
import { inject, onMounted, ref, reactive, nextTick } from 'vue'
// import eventBus from '@/utils/eventBus'

// const getGraph: any = inject("getGraph")
const getNode: any = inject("getNode")
const vueKey = ref(Date.now())

const node = getNode()
const data = node?.getData()
const state: any = reactive({
  data: { ...data }
})

const errorImgHandler = (e) => {
  e.target.onerror = null
  e.target.src = getAssetsFile('images/node-type-icons/DATA_COLLECTION.png')
}

onMounted(() => {
  node?.on("change:data", async (e) => {
    Object.assign(state.data, e?.current)
    console.log(state.data)
  })
})

</script>
<style lang='less'>
.node-base {
  width: 195px;
  background: #FFFFFF;
  border-radius: 16px;
  border: 1px solid #DCDFE6;
  padding: 0 12px;
  cursor: pointer;
  z-index: 1000;
  .content {
    display: flex;
    height: 52px;
  }
  .node-type-img {
    width: 28px;
    height: 28px;
    padding: 12px 0;
    margin-right: 8px;
  }
  .title {
    width: 160px;
    height: 52px;
    font-size: 14px;
    font-family: PingFangSC-Medium, PingFang SC;
    font-weight: 500;
    color: #384150;
    line-height: 52px;
  }
  .desc {
    width: 170px;
    height: 30px;
    background: #F3F4F6;
    border-radius: 12px;
    padding: 12px;
    margin-bottom: 12px;
    word-wrap: break-word;
    overflow-y: auto;
    font-size: 12px;
    font-family: PingFangSC-Regular, PingFang SC;
    font-weight: 400;
    color: #6B7280;
    line-height: 17px;
  }
  &:hover {
    box-shadow: 0 2px 8px 0 rgba(0, 0, 0, 0.15);
    border: 1px solid #165DFF;
  }
}
</style>

3、通过graph.fromJSON(...)初始化节点

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

1、当在画布外编辑了desc字段时
2、通过node?.prop('data/desc', payload.description)变更数据
3、通过change:data监听数据变更更新state.data
node?.on("change:data", async (e) => {
    Object.assign(state.data, e?.current)
    console.log(state.data)
  })
4、 console.log(state.data数据是最新的，但是视图没有跟新

### Expected behavior

希望desc数据变化后视图可以更新

### Screenshots or Videos

暂无

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [^1.0.0]

### Additional context

暂无

**Comment by amysxhuang** [comment]
![Uploading WechatIMG482.jpg…]()

**Comment by yi-ge** [comment]
是的，确实存在这个问题，新增数据可以，部分情况下的数据更新vue视图没有渲染。

**Comment by sxdPanda** [comment]
用`node.updateData()`方法更新数据也不行？

**Comment by amysxhuang** [comment]
> 使用`node.updateData()`此方法更新数据也不行？

试了一下，node.updateData()也是只能更新数据，但是视图没有根据数据更新

**Comment by sxdPanda** [comment]
> > 使用`node.updateData()`此方法更新数据也不行？
> 
> 试了一下，node.updateData()也是只能更新数据，但是视图没有根据数据更新

有demo吗

**Comment by amysxhuang** [comment]
> > > 使用`node.updateData()`此方法更新数据也不行？
> > 
> > 
> > 试了一下，node.updateData()也是只能更新数据，但是视图没有根据数据更新
> 
> 有demo吗

是项目内发现的问题，demo可以写一个自定义vue3组件，然后传参，再做参数变更，如issue的流程

**Comment by sxdPanda** [comment]
我的项目也是vue3，用的也是vue节点，更新数据用的是updateData



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月03日 17:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [antvis/X6] 自定义节点数据更新视图无法更新 (Issue #4330) |

使用node.updateData()此方法更新数据也不行？

试了一下，node.updateData()也是只能更新数据，但是视图没有根据数据更新

有demo吗

是项目内发现的问题，demo可以写一个自定义vue3组件，然后传参，再做参数变更，如issue的流程

**Comment by amysxhuang** [comment]
> > > 我的项目也是vue3，用的也是vue节点，更新数据用的是updateData
> > > […](#)
> > > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2024年06月03日 17:17 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [antvis/X6] 自定义节点数据更新视图无法更新 (Issue #4330) | 使用node.updateData()此方法更新数据也不行？ 试了一下，node.updateData()也是只能更新数据，但是视图没有根据数据更新 有demo吗 是项目内发现的问题，demo可以写一个自定义vue3组件，然后传参，再做参数变更，如issue的流程 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > 可以看一下你怎么注册节点、渲染节点、更新节点的代码吗
> 
> ![image](https://private-user-images.githubusercontent.com/42574059/336018857-a125a0af-dcb9-4da6-b8e6-ceaa651c69bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDkzNDYsIm5iZiI6MTcxNzQwOTA0NiwicGF0aCI6Ii80MjU3NDA1OS8zMzYwMTg4NTctYTEyNWEwYWYtZGNiOS00ZGE2LWI4ZTYtY2VhYTY1MWM2OWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1M2NjMjM4NTRlNWRiNTUyNDExNTk4NTE4MzQ2ZTIwMGZkODY3ZDBlYTliNWIxZDkyNmZkODM4YzllN2E1MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nTbpZFoBsSsbFof_BBq3yp48puKS6inlkQfhaNqX4xk) ![image](https://private-user-images.githubusercontent.com/42574059/336019192-4500ce8b-3199-425a-9c58-a5371f3b3e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDkzNDYsIm5iZiI6MTcxNzQwOTA0NiwicGF0aCI6Ii80MjU3NDA1OS8zMzYwMTkxOTItNDUwMGNlOGItMzE5OS00MjVhLTljNTgtYTUzNzFmM2IzZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYzU1NDM0N2E4NDg2NjkzMmYyNDAzZGQ1OTMwMTRiYzM1ZDk0MGVkMDIxMGRmNzc0M2FjN2VhZjI4MTNhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IwgQgDPFLICRbXR3h0dJVF50RXtujbWIPZ18QPNgxc)
> 
> 你写个简单的demo把源码发我看看，感觉是你那个浅合并那里有问题，currentNode就是点击节点的时候赋值的，我就是根据点击的节点进行数据更新的
> 
> 留言地址：https://www.yuque.com/forms/share/0e925ffb-79ff-46b1-a060-06c833d182be 踩坑文档：https://www.yuque.com/sxd_panda/antv/x6
我们两注册节点的方法不一样，具体的给您留言了，谢谢

**Comment by yi-ge** [comment]
我的问题解决了，是组件内外多个失去焦点事件干扰到。

**Comment by zlecheng** [comment]
> > > > 我的项目也是vue3，用的也是vue节点，更新数据用的是updateData
> > > > […](#)
> > > > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2024年06月03日 17:17 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [antvis/X6] 自定义节点数据更新视图无法更新 (Issue #4330) | 使用node.updateData()此方法更新数据也不行？ 试了一下，node.updateData()也是只能更新数据，但是视图没有根据数据更新 有demo吗 是项目内发现的问题，demo可以写一个自定义vue3组件，然后传参，再做参数变更，如issue的流程 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > > 
> > > 
> > > 可以看一下你怎么注册节点、渲染节点、更新节点的代码吗
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/42574059/336018857-a125a0af-dcb9-4da6-b8e6-ceaa651c69bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDkzNDYsIm5iZiI6MTcxNzQwOTA0NiwicGF0aCI6Ii80MjU3NDA1OS8zMzYwMTg4NTctYTEyNWEwYWYtZGNiOS00ZGE2LWI4ZTYtY2VhYTY1MWM2OWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1M2NjMjM4NTRlNWRiNTUyNDExNTk4NTE4MzQ2ZTIwMGZkODY3ZDBlYTliNWIxZDkyNmZkODM4YzllN2E1MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nTbpZFoBsSsbFof_BBq3yp48puKS6inlkQfhaNqX4xk) ![image](https://private-user-images.githubusercontent.com/42574059/336019192-4500ce8b-3199-425a-9c58-a5371f3b3e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDkzNDYsIm5iZiI6MTcxNzQwOTA0NiwicGF0aCI6Ii80MjU3NDA1OS8zMzYwMTkxOTItNDUwMGNlOGItMzE5OS00MjVhLTljNTgtYTUzNzFmM2IzZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYzU1NDM0N2E4NDg2NjkzMmYyNDAzZGQ1OTMwMTRiYzM1ZDk0MGVkMDIxMGRmNzc0M2FjN2VhZjI4MTNhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IwgQgDPFLICRbXR3h0dJVF50RXtujbWIPZ18QPNgxc)
> > 你写个简单的demo把源码发我看看，感觉是你那个浅合并那里有问题，currentNode就是点击节点的时候赋值的，我就是根据点击的节点进行数据更新的
> > 留言地址：https://www.yuque.com/forms/share/0e925ffb-79ff-46b1-a060-06c833d182be 踩坑文档：https://www.yuque.com/sxd_panda/antv/x6
> > 我们两注册节点的方法不一样，具体的给您留言了，谢谢

你的vue-shape什么版本的？

**Comment by amysxhuang** [comment]
> 我的问题解决了，是组件内外多个失去焦点事件干扰到。

我的x6和vue-shape都是v1的版本，你是啥版本？

**Comment by amysxhuang** [comment]
> > > > > 我的项目也是vue3，用的也是vue节点，更新数据用的是updateData
> > > > > […](#)
> > > > > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2024年06月03日 17:17 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [antvis/X6] 自定义节点数据更新视图无法更新 (Issue #4330) | 使用node.updateData()此方法更新数据也不行？ 试了一下，node.updateData()也是只能更新数据，但是视图没有根据数据更新 有demo吗 是项目内发现的问题，demo可以写一个自定义vue3组件，然后传参，再做参数变更，如issue的流程 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > > > 
> > > > 
> > > > 可以看一下你怎么注册节点、渲染节点、更新节点的代码吗
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/42574059/336018857-a125a0af-dcb9-4da6-b8e6-ceaa651c69bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDkzNDYsIm5iZiI6MTcxNzQwOTA0NiwicGF0aCI6Ii80MjU3NDA1OS8zMzYwMTg4NTctYTEyNWEwYWYtZGNiOS00ZGE2LWI4ZTYtY2VhYTY1MWM2OWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1M2NjMjM4NTRlNWRiNTUyNDExNTk4NTE4MzQ2ZTIwMGZkODY3ZDBlYTliNWIxZDkyNmZkODM4YzllN2E1MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nTbpZFoBsSsbFof_BBq3yp48puKS6inlkQfhaNqX4xk) ![image](https://private-user-images.githubusercontent.com/42574059/336019192-4500ce8b-3199-425a-9c58-a5371f3b3e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDkzNDYsIm5iZiI6MTcxNzQwOTA0NiwicGF0aCI6Ii80MjU3NDA1OS8zMzYwMTkxOTItNDUwMGNlOGItMzE5OS00MjVhLTljNTgtYTUzNzFmM2IzZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYzU1NDM0N2E4NDg2NjkzMmYyNDAzZGQ1OTMwMTRiYzM1ZDk0MGVkMDIxMGRmNzc0M2FjN2VhZjI4MTNhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IwgQgDPFLICRbXR3h0dJVF50RXtujbWIPZ18QPNgxc)
> > > 你写个简单的demo把源码发我看看，感觉是你那个浅合并那里有问题，currentNode就是点击节点的时候赋值的，我就是根据点击的节点进行数据更新的
> > > 留言地址：https://www.yuque.com/forms/share/0e925ffb-79ff-46b1-a060-06c833d182be 踩坑文档：https://www.yuque.com/sxd_panda/antv/x6
> > > 我们两注册节点的方法不一样，具体的给您留言了，谢谢
> 
> 你的vue-shape什么版本的？

vue-shape是v1.1.4，x6是v1.34.1

**Comment by amysxhuang** [comment]
版本变更后视图可以更新了，以下是更新后的版本
"@antv/x6": "1.30.2",
"@antv/x6-vue-shape": "1.3.2",

**Comment by amysxhuang** [comment]
问题已解决，初始化变量结构的节点的data值导致的
以下是导致不更新的代码
let data = node?.getData()
const state: any = reactive({
  data: { ...data }
})

**Comment by amysxhuang** [comment]
问题已解决，初始化变量结构的节点的data值导致的
以下是导致不更新的代码
let data = node?.getData()
const state: any = reactive({
data: { ...data }
})
改成以下定义即可

**Comment by amysxhuang** [comment]
问题已解决，初始化变量结构的节点的data值导致的
以下是导致不更新的代码
let data = node?.getData()
const state: any = reactive({
data: { ...data }
})
改成以下初始化即可
const state: any = reactive({
  data: node?.getData()
})

**Comment by yi-ge** [comment]
> > 我的问题解决了，是组件内外多个失去焦点事件干扰到。
> 
> 我的x6和vue-shape都是v1的版本，你是啥版本？

我的是2.x
