### ISSUE TITLE
1.35.0   版本， 在创建 图形界面的时候 使用 new Function(t)，涉及 csp，unsafe-eval 执行代码。 新版本是否已经修正

### ISSUE THREAD

**Issue by shenjiangbo** [antvis/X6#4333]
### 问题描述

1.35.0   版本

### 重现链接

暂无

### 重现步骤

1.35.0   版本， 在创建 图形界面的时候 使用 new Function(t)，涉及 csp，unsafe-eval 执行代码。 新版本是否已经修正

### 预期行为

1.35.0   版本， 在创建 图形界面的时候 使用 new Function(t)，涉及 csp，unsafe-eval 执行代码。 新版本是否已经修正

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

### 屏幕截图或视频（可选）

暂无

**Comment by NewByVector** [comment]
在这个 https://github.com/antvis/X6/pull/1921 中已经修复，更新到最新版本吧。
