### ISSUE TITLE
已经连接到节点的边可以再移动么

### ISSUE THREAD

**Issue by yinhangfeng** [antvis/X6#4338]
### 问题描述

1. 已经连接到节点的边可以再移动么
2. 如何移动边的 source 端点
edge view 的 [startArrowheadDragging](https://github.com/antvis/X6/blob/37b71d18c2b69d9643ac6f48689a2d61f9912054/packages/x6/src/view/edge.ts#L2285) 好像没被使用?

### 重现链接

https://x6.antv.antgroup.com/zh/examples/showcase/practices/#flowchart

### 重现步骤

没找到相关文档，而且我看 demo 中也是这样的，但是在已经连接到节点的边上拖动时确实会触发 edge:moving 事件

### 预期行为

1. 连接到节点的边可被移动
2. 边的 source 端点可以移动

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- X6 版本: [2.11.1 ...]

**Comment by XueMeijing** [comment]
1. 边是根据两端的节点port确定位置的吧，port位置变了，边的位置也会跟着变
2. 更新节点port位置可以使用 setPortProp 这个属性

```javascript
const nodePorts = node.getPorts();
nodePorts.forEach((nodePort) => {
  node.setPortProp(nodePort.id, 'args', {
    x: LEFT_PORT_WIDTH,
  });
});
```

**Comment by yinhangfeng** [comment]
是我的问题，没看到边的辅助工具 arrowhead
arrowheadMovable 必须配合 arrowhead 工具使用
https://x6.antv.antgroup.com/zh/examples/edge/tool/#arrowheads
