### ISSUE TITLE
node setData后触发了node:change:data 事件，但是node:dbclick中没有拿到最新值

### ISSUE THREAD

**Issue by lunar9621** [antvis/X6#4367]
### Describe the bug

有个需求 在node setData设置业务数据后，在双击该节点拿到最新数据进行后续交互：

但发现 在node:change:data事件的回调中 node的store已拿到了最新值且画布已重新渲染为最新值，但在node:dblclick回调中拿到的还是旧值

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

1.   node.setData(
    {
      data:{ time: new Date().getTime() },
    },
    {
      deep: false,
    },
  )
2.    graph.on('node:dblclick', ({ node }) => {
      console.log('dblclickdata', node.getData());
    });

### Expected behavior

 graph.on('node:dblclick', ({ node }) => {
     //拿到最新业务数据
    });

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by linqiqi077** [comment]
请问这个解决了吗？有解决方案吗？@lunar9621
