### ISSUE TITLE
版本2.18.1  无法绑定键盘事件

### ISSUE THREAD

**Issue by rabbitao** [antvis/X6#4382]
### Describe the bug

版本2.18.1  无法绑定键盘事件

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

以下为错误1: 
const graph = new Graph({...options})

graph.bindKey('ctrl', () => {}) // 此处报错: 类型“Graph”上不存在属性“bindKey”

以下为错误2:
const graph = new Graph({
  keyboard: true  // 此处报错 : 对象字面量只能指定已知属性，并且“keyboard”不在类型“Partial<Manual>”中
})

### Expected behavior

按照文档所示 https://x6.antv.vision/zh/docs/tutorial/basic/keyboard
预期应正确绑定键盘事件

### Platform

- OS: [macOS, Windows]
- Browser: [ Chrome]
- Version: [2.18.1]

**Comment by rabbitao** [comment]
https://x6.antv.antgroup.com/tutorial/plugins/keyboard
由插件包提供此功能
文档过于混乱

**Comment by cmxbg** [comment]
你好，这个问题有解决吗
