### ISSUE TITLE
dynamic import() which is available in all CommonJS modules.

### ISSUE THREAD

**Issue by KongWeidongSJZ** [antvis/X6#4383]
### Describe the bug

我在引用X6的时候遇到一个问题，x6-common 中 是通过 require引用的lodash-es ,请问如何解决
![1723020938146](https://github.com/user-attachments/assets/79a8fe83-4fe3-4e5b-ae3f-64e13aea6b89)

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

1.  pnpm 安装 vue3 nuxt3
2. 安装x6

### Expected behavior

展示x6示例

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by hellolsk** [comment]
同问， 怎么解决的。 我在使用next安装也出现了上面的问题
