### ISSUE TITLE
修改了label标签属性不会自动更新视图，更新之后获取属性也是正确的

### ISSUE THREAD

**Issue by zw-store** [antvis/X6#4440]
### 问题描述

修改了label标签属性不会自动更新视图，更新之后获取属性也是正确的，这些问题好搞人，没有群么，动不动提issue，还要复现场景，我的例子都是一整套的，单独布置真麻烦，相关例子解决方案又没有帖子。github 的问题一堆没关闭。弄得心好累。一个修改label的例子弄一天了都

### 重现链接

无

### 重现步骤

```javascript
    propertyLabelChange(index, property, value) {
      const originLabel = this.nodeData.getLabelAt(index)
      const label = util.merge(originLabel, transformInput(property, value), true)
      this.nodeData.setLabelAt(index, label)
      console.log(this.nodeData.getLabelAt(index))
      /**
        {
            "attrs": {
                "text": {
                    "text": "Hello Labdasdelmmdasdam",
                    "fill": "#211C1C"
                }
            },
            "position": {
                "distance": 0.1,
                "offset": [
                    0,
                    0
                ]
            }
        }
       */
            }
```
拖拽标签的时候会修改视图刚刚打印的值

### 预期行为

能有更新视图属性，当保存时可以将修改的属性 toJSON 。
可以有交流群吗，有个小问题，文档看一天，issue 也难翻

### 平台

操作系统: [macOS, Windows, Linux, React Native ...]
网页浏览器: [Google Chrome, Safari, Firefox ...]
X6 版本: [1.35.1 ...]

**Comment by zw-store** [comment]
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/f49d0a69-05a0-4d9a-843f-8ae9f22a6188">
我补充一下，我属性修改了，还是没有触发页面改动，在这一刻鼠标拖动标签就能应用刚刚修改的属性，我查询文档也没手动更新的节点相关的方法，还有标记一些 cell节点的 label 时，第一次不会更新，多次修改就会再执行更新，这个是 bug 么。

**Comment by zw-store** [comment]
代码地址上传到github：https://github.com/zw-store/vite-x6-vue2.git

**Comment by cnyballk** [comment]
1. 关于移动才能触发修改，可以看看 const originLabel = this.nodeData.getLabelAt(index)  深拷贝一下再修改
2.关于第一次不会更新可以看看表单绑定的v-model，也深拷贝一下再设置
![image](https://github.com/user-attachments/assets/08b3ff7f-d1fa-4c5a-8e13-c6899fc251cb)

建议复杂数据类型的修改都拷贝一下再给vue（vue需要监听对象，可能会对属性修改，从而做一些处理导致问题产生），以及修改设置

**Comment by cnyballk** [comment]
交流群有钉钉哈，![image](https://github.com/user-attachments/assets/91617c7e-eadb-46dc-8948-1ae3e187ca7a)

**Comment by zw-store** [comment]
> 1. 关于移动才能触发修改，可以看看 const originLabel = this.nodeData.getLabelAt(index)  深拷贝一下再修改
>    2.关于第一次不会更新可以看看表单绑定的v-model，也深拷贝一下再设置
>    ![image](https://private-user-images.githubusercontent.com/25214319/367488972-08b3ff7f-d1fa-4c5a-8e13-c6899fc251cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjM3MDgsIm5iZiI6MTcyNjYyMzQwOCwicGF0aCI6Ii8yNTIxNDMxOS8zNjc0ODg5NzItMDhiM2ZmN2YtZDFmYS00YzVhLThlMTMtYzY4OTlmYzI1MWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAxMzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4Y2ZkN2EzZjYyYTQxM2RkYjYzZDY1MGVhYTczNGNhNjc5ZWJhZTRjMGNlYjVmMzI3Mzc2MmM2ZTM2MDljYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sE2bjvZeKBMnjKxXCBu_H7Yi9zB6YijegOJgCX2HWAo)
> 
> 建议复杂数据类型的修改都拷贝一下再给vue（vue需要监听对象，可能会对属性修改，从而做一些处理导致问题产生），以及修改设置

感谢你的回答。我参考你这个方法进行了调整，将属性需要深克隆一份再进行调整，成功解决了我的问题。
