### ISSUE TITLE
当页面发生滚动后，dnd中的节点拖拽到画布中会延迟一会儿才显示

### ISSUE THREAD

**Issue by wuweinero** [antvis/X6#4461]
### 问题描述

当页面发生滚动后（不是画布滚动，是整个网页页面上下滚动），dnd中的节点立即拖拽到画布中会延迟一会儿才显示。
补充1：如果滚动之后，过两三秒再拖拽节点，则没有延迟。
补充2：如果滚动后，立即拖拽到页面中，然后迅速手动再滚动一次页面，则会立即渲染该节点。

### 重现链接

https://x6.antv.antgroup.com/tutorial/plugins/dnd

### 重现步骤

1.进入上述官方示例网页
2.用鼠标滑轮滚动页面后，迅速拖拽一个节点到画布中，就可以看到延迟的现象
3.滚动后静置2-3s，再拖拽节点到画布中，则没有延迟
注意，每次滚动后，只有首次拖拽会出现这个现象。

### 预期行为

我期望页面滚动后，立即拖拽节点到画布中时，不要延迟长达2s左右，而是控制在1s以内

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- X6 版本: 2.18.1

**Comment by zlecheng** [comment]
楼主解决了吗

**Comment by EasonYeang** [comment]
这个问题是否有解决办法？

**Comment by xielinhan** [comment]
我也遇到这个问题了，当鼠标滚轮滚动后，针对元素的修改方法会延迟生效。但是拖动滚动条没问题

**Comment by zlecheng** [comment]
没人解决啊😂

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月04日 14:57 |
| 收件人 | ***@***.***> |
| 抄送人 | zlecheng ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [antvis/X6] 当页面发生滚动后，dnd中的节点拖拽到画布中会延迟一会儿才显示 (Issue #4461) |

我也遇到这个问题了，当鼠标滚轮滚动后，针对元素的修改方法会延迟生效。但是拖动滚动条没问题

**Comment by xielinhan** [comment]
@zlecheng 难顶，我就算把滚动条隐藏了，只要用了鼠标滚动就能复现

**Comment by zlecheng** [comment]
是的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月04日 15:06 |
| 收件人 | antvis/X6 ***@***.***> |
| 抄送人 | zlecheng ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [antvis/X6] 当页面发生滚动后，dnd中的节点拖拽到画布中会延迟一会儿才显示 (Issue #4461) |

@zlecheng 难顶，我就算把滚动条隐藏了，只要用了鼠标滚动就能复现

**Comment by wuweinero** [comment]
换成1.x版本可以解决

**Comment by zlecheng** [comment]
> 换成1.x版本可以解决

那这也不现实啊

**Comment by NyuuuuOrz** [comment]
> > 换成1.x版本可以解决
> 
> 那这也不现实啊

似乎是异步渲染导致的。
初始化画布时async属性设置为false试试呢？这个属性在2.x版本中被默认置为true了。

**Comment by EasonYeang** [comment]
> > > 换成1.x版本可以解决
> > 
> > 
> > 那这也不现实啊
> 
> 似乎是异步渲染导致的。 初始化画布时async属性设置为false试试呢？这个属性在2.x版本中被默认置为true了。

async:false似乎可以解决这个问题(未充分测试)，但是会引发其它问题，比如自定义vue节点拖拽渲染时，在mounted中获取node.attr()中绑定的自定义数据为undefined
