### ISSUE TITLE
graph.fromJSON数据多时太慢

### ISSUE THREAD

**Issue by tianee** [antvis/X6#4483]
### 问题描述

graph.fromJSON数据多时太慢,50个节点需要1分钟

### 重现链接

无

### 重现步骤

graph.fromJSON数据多时太慢,50个节点需要1分钟

### 预期行为

优化速度

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.5]

**Comment by apankun** [comment]
有demo么
