### ISSUE TITLE
minimap导航窗口超出范围

### ISSUE THREAD

**Issue by saperliu** [antvis/X6#450]
### Expected Behavior
当设置了graph的宽和高，然后启用scroller，设置pagevisible为true,且设置了pageWidth和pageHight，这时候minimap的导航窗口就出问题了。

### Additional Context
下面示例可以复现问题:
https://codesandbox.io/s/thirsty-shtern-kfhmd?file=/src/app.tsx

![image](https://user-images.githubusercontent.com/2297765/102743662-ddc69f80-4392-11eb-8340-aadd669e3fdb.png)

### Your Environment

- x6: [1.5.1]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@saperliu 导航器的大小由容器大小决定，容器别那么大吧 4000x2000，有点太大了吧

**Comment by saperliu** [comment]
@bubkoo  呃..... 这貌似不是解决问题的办法。如果我不设置pageWidth和pageHight，貌似还可以，所以这个情况并不是单纯的把graph的宽高改小就行了。

个人认为最好用的是：
1、在现有基础上把导航窗的宽和高也开放设置，这样可以把控与minimap的宽和高的比例。
2、缩放只是背景图比例的缩放，与导航窗口大小无关。

本人的业务场景是做一个类似DataV的功能，所以页面大小是客户显示器分辨率大小决定的，所以 4000x2000 也不一定比实际大多少。我又细测试一下，我不设置这个4000x2000，依然是有问题。重点成了pageWidth和pageHight，但这个大小是我的业务需要的决定的。

见下面示例
https://codesandbox.io/s/thirsty-shtern-kfhmd?file=/src/app.tsx

**Comment by bubkoo** [comment]
导航窗的宽和高一定是与视口的大小对等比例，不能放开设置。

codesandbox 的容器被自动压缩了，项目demo中测试你上面的设置没问题。
