### ISSUE TITLE
两个节点使用manhattan斜着连线时，segments工具不显示

### ISSUE THREAD

**Issue by fu827707013** [antvis/X6#4516]
### Describe the bug

两个节点使用连线时，segments工具不显示，水平连线才显示，但我router使用的是manhattan，是自动变成正交线段组成，都是水平和垂直线段
1. 初始化画布：
```js
const graph = new Graph({
    container: document.getElementById('graph-container')!,
    grid: true,
    connecting: {
        router: 'orth',
        createEdge() {
            return new Shape.Edge({
                attrs: {
                    line: {
                        stroke: '#A2B1C3',
                        strokeWidth: 2,
                        targetMarker: {
                            name: 'block',
                            width: 12,
                            height: 8,
                        },
                    },
                },
                zIndex: 0,
            })
        },
    },
})
```
2.控制工具显示隐藏
```js
graph.on('edge:mouseenter', ({cell}) => {
    cell.addTools([
        {
            name: 'segments',
            args: {
                attrs: {
                    fill: '#444',
                },
            }
        },
    ], 'segments')
    // cell.addTools(['segments'], 'onhover')
})
```

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1. 拖拽两个节点到画布
2. 放置非水平或垂直位置
3. 连接两个节点，连接线自动变成两段正交线段
4. 鼠标移动到线段上，segments工具未显示
![1732981556055](https://github.com/user-attachments/assets/1a90fd27-ebd4-4f79-8d38-3a4a8e8e7eaa)
在实际业务中如果 流程节点比较多，路线就会交叉，需要拖动线段做些微调

### Expected behavior

1. 拖拽两个节点到画布
2. 放置非水平或垂直位置
3. 连接两个节点，连接线自动变成两段正交线段
4. 鼠标移动到线段上，segments工具正常显示

### Platform

- OS: Windows
- Browser: Microsoft Edge 
- Version: 版本 131.0.2903.70 (正式版本) (64 位)
- "@antv/x6": "^2.18.1",

**Comment by dingyun2020** [comment]
请问这个解决方法是什么

**Comment by wangchenyi1996** [comment]
> 可能不够智能，目前用其他办法解决了
我也遇到这个问题了，请问下是怎么解决的呀
