### ISSUE TITLE
vue中使用X6数据改变画布视图刷新重叠

### ISSUE THREAD

**Issue by JustForSmiling** [antvis/X6#452]
1. 使用fromJSON方法渲染的数据
2. 更新数据后重新调用该方法视图渲染会重叠
3. 没有在文档中找到刷新画布的API, 希望有人指点下, 谢谢哈

问题效果如下图:

![Y2}51XT63%Z8ARTY8ZV ZUY](https://user-images.githubusercontent.com/39959627/102753378-1de34d80-43a6-11eb-8523-dd30cfd6379d.png)

**Comment by NewByVector** [comment]
提供一个复现的demo？
