### ISSUE TITLE
从1.x升级到2.x时，折叠组合节点时不会隐藏自定义边上工具tools，1.x版本时会正常隐藏

### ISSUE THREAD

**Issue by Jason-oo** [antvis/X6#4530]
### 问题描述

按指引从1.x升级至2.x
在1.x版本中折叠节点时tools会被隐藏，升级以后tools折叠后仍然会显示在画布上
有什么方法可以主动隐藏边上工具tools，看2.x版本文档只提供了remove方法，并删除了不常用的Graph.hideTools()，不清楚是否与这个有关系，但是我的代码里并没有使用此方法
请问有没有什么方法能够主动控制tools的显示隐藏

### 重现链接

无

### 重现步骤

无

### 预期行为

升级至2.x版本折叠节点时能正常隐藏tools

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox ...]
- X6 版本: [2.11.1 ...]

**Comment by Jason-oo** [comment]
直接操作dom隐藏了，但是为什么2.x版本在调用edge.hide()的时候不会同步隐藏边上工具呢，有没有大佬给解释一下

**Comment by hustcc** [comment]
@Jason-oo 看起来是一个小 bug，有兴趣来 PR 试试解决吗？

**Comment by zhangxilong-43** [comment]
认领。
@hustcc 请大佬看下修改思路。

修改文件：X6/src/renderer/scheduler.ts
 ```
 protected toggleVisible(cell: Cell, visible: boolean) {
    const edges = this.model.getConnectedEdges(cell)

    // ....

    const viewItem = this.views[cell.id]
    if (viewItem) {
      Dom.css(viewItem.view.container, {
        display: visible ? 'unset' : 'none',
      })

      if (visible) {                                    // 在此做判断，控制显隐
        viewItem.view.showTools()
      } else {
        viewItem.view.hideTools()
      }
    }
  }
```
