### ISSUE TITLE
图片节点的默认宽度和高度能根据图片来自适应

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#455]
### Expected Behavior

图片节点的默认宽度和高度能根据图片来自适应

**Comment by bubkoo** [comment]
@NewByVector 图片的宽高从哪里得到？

**Comment by bubkoo** [comment]
不作为内部实现，因为要考虑的情况太多。

提供了一个 DEMO https://x6.antv.vision/zh/examples/showcase/faq#flex-image，实际业务可以仿照 DEMO 再定制
