### ISSUE TITLE
X6 有 commonJS 版本吗？

### ISSUE THREAD

**Issue by arvinxx** [antvis/X6#457]
由于一些特殊原因，导致我目前使用的一个脚手架没法支持对 node_moudules 中 ES6 模块的编译。所以想问下 X6 有相应的 Common JS 版本吗？

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@arvinxx  dist 目录就是

**Comment by arvinxx** [comment]
> @arvinxx dist 目录就是

但是 dist 没有类型定义？

**Comment by bubkoo** [comment]
@arvinxx 直接引用源码吧

**Comment by arvinxx** [comment]
> @arvinxx 直接引用源码吧

直接引用不就变成我最初的问题了？没法直接引入源码是因为项目比较特殊，脚手架吧支持对 node_modules 的 es6 模块编译，然后我又没法去改这个脚手架。

**Comment by bubkoo** [comment]
@arvinxx lib 目录是 ES5，es 目录才是 es6 的。
