### ISSUE TITLE
收集 X6 的使用场景

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#464]
为了让 X6 更好的支持各类业务场景，帮助 X6 在 V2.0 之路上收集更多的 idea，欢迎大家(在不涉及泄密的情况下)贴出使用 X6 的项目地址、视觉稿，一起把 X6 做的更好！

**Comment by NewByVector** [comment]
iMove: https://github.com/imgcook/imove

**Comment by daigang666** [comment]
正好涉密，类似于Visio，UML建模，为guo防事业做建设
希望官方给出更多参考node，尤其是复杂图元，其实可以做一个示例或者效果网站，可以上传分享代码，减少接入一般业务的时间成本
