### ISSUE TITLE
toPNG在保存弹框弹出来之前，会影响到别的元素的样式

### ISSUE THREAD

**Issue by Zql-mll** [antvis/X6#474]
### Expected Behavior
默认我的样式是
![image](https://user-images.githubusercontent.com/44664780/103184891-e66c2800-48f4-11eb-8566-87d95e93c34f.png)
当我点击了保存，调用了toPNG方法后，在另存为的弹窗未弹出之前，发现我按钮的样式被影响了。
![image](https://user-images.githubusercontent.com/44664780/103184923-0e5b8b80-48f5-11eb-821c-7957703b2304.png)

### Additional Context

我去查看了 https://x6.antv.vision/apps/draw/ 官方示例的效果，属性栏发现了同样的样式影响问题。

### Your Environment

- x6: [1.5.1]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by SmallStoneSK** [comment]
遇到同样的问题 +1

**Comment by eschervr-dev** [comment]
遇到同样的问题 +1

**Comment by NewByVector** [comment]
在 toPNG 的过程中，默认有个耗性能的操作：将外部样式表中的所有相关CSS声明存储到SVG文档节点的 style属性中，在此过程中会禁止所有样式表，在性能比较差的环境会出现上面问题。如果要解决上面问题，可以设置 [copyStyles](https://x6.antv.vision/zh/docs/tutorial/basic/graph#copystyles) 为 false，然后检测导出结果样式是否合理。

**Comment by Zql-mll** [comment]
> 禁止所有样式

好的，谢谢，已经试过了，可以的。
