### ISSUE TITLE
custom node

### ISSUE THREAD

**Issue by Doifo** [antvis/X6#478]
### Current Behavior

class CustomNode extends Node{}
CustomNode.config({})
Graph.register('customNode',CustomNode) //error

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
具体什么错误，或者试试

Graph.register('customNode',CustomNode，true）

**Comment by Doifo** [comment]
同样不行，错误是没有重载函数，CustomNode 不能赋值给typeof Node。



---Original---
