### ISSUE TITLE
 JavaScript heap out of memory when using Meteor JS

### ISSUE THREAD

**Issue by laubonghaudoi** [antvis/X6#485]
I am using [Meteor JS](https://www.meteor.com/) with React to build an X6 app. But I couldn't even initialize a graph. 

### Steps To Reproduce

(To create a new Meteor app, install Meteor first and run `meteor create --typescript example-app`. and then run `meteor npm install @antv/x6` to add X6 as a package. The `App.tsx` is located at `/imports/ui/App.tsx` ) 

I tried the most basic codes, simply replacing the `App.tsx` in Meteor's starter codes with my codes below:

```ts
// App.tsx
import { Graph } from '@antv/x6'
import React, { useEffect } from "react";

export const App = () => {
  useEffect(() => {
    const graph = new Graph({
      container: document.getElementById("graph")!,
    });
  }, []);

  return (
    <div id="graph" />
  );
}
```
However, even this simplest initialization doesn't work. Whenever I create a new graph object with `new Graph()`, it crashes instantly. Error messages below.

### Current Behavior

Whenever I run `meteor` to start developing, the app instantly crashes and returns a fatal error message like below:

```bash
PS C:\Users\username\Documents\GitHub\simple-todos-react> meteor
[[[[[ C:\Users\username\Documents\GitHub\simple-todos-react ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.


<--- Last few GCs --->

[9968:0000020F8FB75700]   166326 ms: Scavenge 1130.4 (1164.9) -> 1114.4 (1164.9) MB, 0.4 / 0.0 ms  (average mu = 0.932, current mu = 0.726) allocation failure 
[9968:0000020F8FB75700]   166333 ms: Scavenge 1130.4 (1164.9) -> 1114.4 (1164.9) MB, 0.4 / 0.0 ms  (average mu = 0.932, current mu = 0.726) allocation failure 
[9968:0000020F8FB75700]   166341 ms: Scavenge 1130.4 (1164.9) -> 1114.4 (1164.9) MB, 0.6 / 0.0 ms  (average mu = 0.932, current mu = 0.726) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF79EC3B49D]
Security context: 0x0151054008d1 <JSObject>
    1: findPossibleIndexes(aka findPossibleIndexes) [000000F2A05FEFB1] [C:\Users\username\AppData\Local\.meteor\packages\meteor-tool\1.12.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\reify\lib\utils.js:~98] [pc=000000ABBFDAADEB](this=0x017a00d004b1 <undefined>,0x00d1a683f451 <String[423]\: import $ from 'jquery';\nimport './polyfill';\nexport * from './...

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 00007FF79E025F0F napi_wrap+114095
 2: 00007FF79DFD0B96 v8::base::CPU::has_sse+66998
 3: 00007FF79DFD1996 v8::base::CPU::has_sse+70582
 4: 00007FF79E7E6E9E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF79E7CEF71 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF79E69B1DC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF79E6B81FB v8::internal::Factory::NewFixedArrayWithFiller+59
 8: 00007FF79E6B81B1 v8::internal::Factory::NewFixedArray+65
 9: 00007FF79E5951CF v8::Object::GetIsolate+8527
10: 00007FF79E44582A v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+162938
11: 00007FF79EC3B49D v8::internal::SetupIsolateDelegate::SetupHeap+546637
12: 000000ABBFDAADEB
```

I opened the F12 dev console, and it kept poping up error messages like this:

![image](https://user-images.githubusercontent.com/11172180/103241839-42d94280-4909-11eb-9331-5d5d4f439b3f.png)

What is this `sockjs`? I am not sure whether this is an issue from Meteor or X6, hope the information helps.

### Your Environment

- x6: 1.7.7
- OS: I tried both Windows 10 and Ubuntu 20.04
- Browser: Any, app crashes instantly.
- meteor-node-stubs: 1.0.1

**Comment by laubonghaudoi** [comment]
Update: Instead of importing from node modules, I tried [using the CDN link](https://stackoverflow.com/questions/43747443/how-to-use-a-cdn-inside-a-react-component) to import X6, and it worked. This is so strange, is this because the NPM package is corrupted or some other reasons?

Right now my code editor is full of error prompts `Cannot find namespace 'X6'` (even the project is running perfectly), because I can't just `import { Graph } from "@antv/x6"`, and then `const graph = new Graph()` . I have to `const graph = new X6.Graph()` every time I need to invoke the X6 package.

**Comment by NewByVector** [comment]
> I am using [Meteor JS](https://www.meteor.com/) with React to build an X6 app. But I couldn't even initialize a graph.
> 
> ### Steps To Reproduce
> (To create a new Meteor app, install Meteor first and run `meteor create --typescript example-app`. and then run `meteor npm install @antv/x6` to add X6 as a package. The `App.tsx` is located at `/imports/ui/App.tsx` )
> 
> I tried the most basic codes, simply replacing the `App.tsx` in Meteor's starter codes with my codes below:
> 
> ```ts
> // App.tsx
> import { Graph } from '@antv/x6'
> import React, { useEffect } from "react";
> 
> export const App = () => {
>   useEffect(() => {
>     const graph = new Graph({
>       container: document.getElementById("graph")!,
>     });
>   }, []);
> 
>   return (
>     <div id="graph" />
>   );
> }
> ```
> 
> However, even this simplest initialization doesn't work. Whenever I create a new graph object with `new Graph()`, it crashes instantly. Error messages below.
> 
> ### Current Behavior
> Whenever I run `meteor` to start developing, the app instantly crashes and returns a fatal error message like below:
> 
> ```shell
> PS C:\Users\username\Documents\GitHub\simple-todos-react> meteor
> [[[[[ C:\Users\username\Documents\GitHub\simple-todos-react ]]]]]
> 
> => Started proxy.
> => Started MongoDB.
> => Started your app.
> 
> => App running at: http://localhost:3000/
>    Type Control-C twice to stop.
> 
> 
> <--- Last few GCs --->
> 
> [9968:0000020F8FB75700]   166326 ms: Scavenge 1130.4 (1164.9) -> 1114.4 (1164.9) MB, 0.4 / 0.0 ms  (average mu = 0.932, current mu = 0.726) allocation failure 
> [9968:0000020F8FB75700]   166333 ms: Scavenge 1130.4 (1164.9) -> 1114.4 (1164.9) MB, 0.4 / 0.0 ms  (average mu = 0.932, current mu = 0.726) allocation failure 
> [9968:0000020F8FB75700]   166341 ms: Scavenge 1130.4 (1164.9) -> 1114.4 (1164.9) MB, 0.6 / 0.0 ms  (average mu = 0.932, current mu = 0.726) allocation failure 
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
>     0: ExitFrame [pc: 00007FF79EC3B49D]
> Security context: 0x0151054008d1 <JSObject>
>     1: findPossibleIndexes(aka findPossibleIndexes) [000000F2A05FEFB1] [C:\Users\username\AppData\Local\.meteor\packages\meteor-tool\1.12.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\reify\lib\utils.js:~98] [pc=000000ABBFDAADEB](this=0x017a00d004b1 <undefined>,0x00d1a683f451 <String[423]\: import $ from 'jquery';\nimport './polyfill';\nexport * from './...
> 
> FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
>  1: 00007FF79E025F0F napi_wrap+114095
>  2: 00007FF79DFD0B96 v8::base::CPU::has_sse+66998
>  3: 00007FF79DFD1996 v8::base::CPU::has_sse+70582
>  4: 00007FF79E7E6E9E v8::Isolate::ReportExternalAllocationLimitReached+94
>  5: 00007FF79E7CEF71 v8::SharedArrayBuffer::Externalize+833
>  6: 00007FF79E69B1DC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
>  7: 00007FF79E6B81FB v8::internal::Factory::NewFixedArrayWithFiller+59
>  8: 00007FF79E6B81B1 v8::internal::Factory::NewFixedArray+65
>  9: 00007FF79E5951CF v8::Object::GetIsolate+8527
> 10: 00007FF79E44582A v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+162938
> 11: 00007FF79EC3B49D v8::internal::SetupIsolateDelegate::SetupHeap+546637
> 12: 000000ABBFDAADEB
> ```
> 
> I opened the F12 dev console, and it kept poping up error messages like this:
> 
> ![image](https://user-images.githubusercontent.com/11172180/103241839-42d94280-4909-11eb-9331-5d5d4f439b3f.png)
> 
> What is this `sockjs`? I am not sure whether this is an issue from Meteor or X6, hope the information helps.
> 
> ### Your Environment
> * x6: 1.7.7
> * OS: I tried both Windows 10 and Ubuntu 20.04
> * Browser: Any, app crashes instantly.
> * meteor-node-stubs: 1.0.1

It seems that this error is related to your framework configuration, will it run out of memory if you do not introduce X6？

**Comment by laubonghaudoi** [comment]
@NewByVector No it won't. Everything runs perfectly even after I `import { Graph } from '@antv/x6'` in the beginning of my files. The disaster begins whenever I call `new Graph()`. What makes it stranger is that this problem doesn't occur if I use a CDN link instead of importing the NPM package. That's why I am not sure whether this is caused by Meteor or X6. Can you reproduce my error? I have posted a more detailed steps for reproducing in this issue https://github.com/meteor/meteor/issues/11279 Thanks a bunch!

Also, I have tried running the exact same codes with the create-react-app framework, as well as plain JavaScript in an HTML. Both worked as they are supposed to be. So this excludes the possibility of error from my system or environments. I guess it is due to X6 using some techs which is incompatible with the MeteorJS framework?

**Comment by laubonghaudoi** [comment]
@NewByVector I think I have figured out the root cause. According to https://github.com/meteor/meteor/issues/11279#issuecomment-761829915 , X6 uses jQuery and imports it with `import $ from 'jquery'`, while `$` could be an invalid ES module name and thus triggers this issue. I fixed it by replacing the `$` with `jQuery`: https://github.com/meteor/meteor/issues/11279#issuecomment-761859485 . 

So could you change the `$` in X6's jQuery import into another valid module name? I think this should be an easy fix. Thank you!
