### ISSUE TITLE
渲染出来的vue组件比react组件多一层div，导致无法设置百分百高度和宽度

### ISSUE THREAD

**Issue by qingchiapp** [antvis/X6#493]
渲染出来的vue组件比react组件多一层div，导致无法设置百分百高度和宽度

vue渲染
![image](https://user-images.githubusercontent.com/14007972/103345601-c2633f00-4acc-11eb-973a-ea3d168bf1d5.png)
react渲染
![image](https://user-images.githubusercontent.com/14007972/103345622-d313b500-4acc-11eb-88c2-8d8a85b29419.png)

**Comment by NewByVector** [comment]
新增的div设置成100%
