### ISSUE TITLE
增加编辑  节点/边  文字的能力

### ISSUE THREAD

**Issue by SmallStoneSK** [antvis/X6#500]
### Expected Behavior

官方例子中已经提供了一段编辑文字的示例代码片段： [右键菜单](https://github.com/antvis/X6/blob/master/examples/x6-app-draw/src/pages/Graph/index.ts#L287) + [自定义 markup 加入 editable html](https://github.com/antvis/X6/blob/master/examples/x6-app-draw/src/pages/Graph/shape.ts#L51)

这很棒，希望 x6 能够内置上述的这些编辑能力，从而降低开发成本。另外：
  - 希望设计编辑文字功能时，可参照 ppt 中的图形编辑文字交互，当点击在节点文字上时自动切换到 editable 模式（非文字区域时交互为选中该节点），失去焦点时切换回 preview 模式（上文中的 demo 交互是右键切换 editable 模式，不太符合日常习惯）
  - graph 实例暴露一个新的 api，让开发者可以指定节点切换为 editable 模式（节点的右键菜单会有 **编辑文字** 选项）

**Comment by NewByVector** [comment]
开发计划中
