### ISSUE TITLE
节点文字内容较多时，可以根据节点的宽度自动换行显示

### ISSUE THREAD

**Issue by SmallStoneSK** [antvis/X6#501]
### Expected Behavior

目前，当节点中的文字较多时，文字内容会直接超出节点范围，不会根据节点的宽度自动换行显示。

这点上，希望体验能够进一步提升

**Comment by NewByVector** [comment]
在节点 label 中可以增加 textWrap  属性来支持更精确的文本换行。还有 text-block 类型节点默认支持文本换行

**Comment by bubkoo** [comment]
可以使用 `Dom.breakText(text, { width, height }): string` 方法来切断文字，返回添加了换行符的文本，再将其作为节点或边的 label。

**Comment by SmallStoneSK** [comment]
可以设置节点 `attrs/label/textWrap` 属性为 100%
```js
{
  attrs: {
    label: {
      textWrap: { width: '100%' }
    }
  }
}
```
