### ISSUE TITLE
draggingNode.position is not a function

### ISSUE THREAD

**Issue by hellobq** [antvis/X6#503]
### Expected Behavior
实现自定义边的拖拽

### Current Behavior
通过 createEdge 创建的自定义边，拖拽进 dnd 后，直接报错了：`Uncaught TypeError: draggingNode.position is not a function`

### Steps To Reproduce
1. 直接修改 https://codesandbox.io/s/woklp 站点下的 app.tsx
2. 在 jsx 内加入：
```
<div
    data-type="edge"
    className="dnd-edge"
    onMouseDown={startDrag}
  />
```
3. 在 startDrag 回调内加入：
```
if (type === 'edge') {
   // 自定义边
  Graph.registerEdge(
    'org-edge',
    {
      // zIndex: -1,
      attrs: {
        line: {
          stroke: '#585858',
          strokeWidth: 3,
          sourceMarker: null,
          targetMarker: null,
        },
      },
    },
    true,
  )
  node = graph.createEdge({
    shape: 'org-edge',
    source: { x: -100, y: -100 },
    target: { x: 200, y: -100 },
  })
}
```
4. 然后拖拽后就报错了：
![image](https://user-images.githubusercontent.com/29953650/103519276-38421e80-4eb0-11eb-838d-79a826fa9850.png)

### Your Environment
win10、chrome87

**Comment by NewByVector** [comment]
dnd只支持节点的拖拽，如果有边的业务场景的话，可以用 [path节点](https://x6.antv.vision/zh/examples/node/native-node#path) 去模拟

**Comment by xuwenjia** [comment]
> dnd只支持节点的拖拽，如果有边的业务场景的话，可以用 [path节点](https://x6.antv.vision/zh/examples/node/native-node#path) 去模拟

registerHTMLComponent 配合dnd使用拖拽开始时会报sourcenode.clone is not a function 我看了一下因为返回的node是个dom元素所以没有clone方法，registerHTMLComponent  不支持dnd是吗？
