### ISSUE TITLE
按着dome渲染vue组件报错。

### ISSUE THREAD

**Issue by woshiwhy** [antvis/X6#507]
![image](https://user-images.githubusercontent.com/21192448/103603844-83a90b00-4f4a-11eb-8376-1fef35f7065e.png)
![image](https://user-images.githubusercontent.com/21192448/103603867-928fbd80-4f4a-11eb-97a1-2442f9b0e18f.png)

vue.runtime.esm.js?2b0e:619 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)

**Comment by NewByVector** [comment]
![image](https://user-images.githubusercontent.com/20186737/103610616-8d873a00-4f5b-11eb-8079-99bd4151ad13.png)

**Comment by woshiwhy** [comment]
谢谢，已经解决。
