### ISSUE TITLE
通过fromJSON生成的画布没有触发cell:added、node:added 和 edge:added事件

### ISSUE THREAD

**Issue by chorin959** [antvis/X6#509]
### Expected Behavior
调用`graph.fromJSON('...')`生成各种图形后，相应的 `cell:added`、`node:added` 和 `edge:added`事件应该要被触发

### Current Behavior
没有触发相应的 cell:added、node:added 和 edge:added事件

### Your Environment

- x6: [e.g. 1.9.3]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
@bubkoo  这个是否有必要？

**Comment by NewByVector** [comment]
@bubkoo  这个是否有必要

**Comment by chorin959** [comment]
> @bubkoo 这个是否有必要

 在X6的文档里对fromJSON这个API是这样描述的：
>```typescript
>fromJSON(data: (Node.Metadata | Edge.Metadata)[], options?: FromJSONOptions): this
>```
> 当 options.silent 为 true 时，不触发 cell:added、node:added 和 edge:added 事件和画布重绘。

我的理解是：
`options.silent`为`false`时应该要触发`cell:added`、`node:added` 和 `edge:added` 事件和`画布重绘`，
但当前的行为是画布会重绘而事件没有触发, 故我认为这是缺陷。

目前我们基于X6在开发一个产品，我们定制了一些节点，这些节点拥有我们定制的一些特性，这些特性需要在节点添加进画布之后才会加载进来。
所以需要这样：
```js
graph.on("node:added", ({cell})=>{
    // TODO
});
```
数据会通过JSON方式进行保存，当需要回显的时候会通过`fromJSON`这个方法进行回显，如果没有added事件，这些特性就会丢失。

目前的解决方案就是通过同步的方式调用fromJSON后遍历graph下的listener，找到所有added事件回调方法，调用之。

**Comment by bubkoo** [comment]
@NewByVector @chorin959 fromJSON 这里可能是有问题，但现在我们不能这样直接改，改了之后可能会影响其他业务，因为在其他业务中可能监听了 cell：added 事件来持久化新添加的节点到数据库。另外上面描述的问题可以直接遍历 fromJSON 的data，然后调用 addCell 方法 添加到画布，这样就会触发相应的事件。
