### ISSUE TITLE
增加 历史记录中配置忽略某一个或多个属性的变化

### ISSUE THREAD

**Issue by Zql-mll** [antvis/X6#520]
### Expected Behavior
我配置了创建线的时候是虚线
![image](https://user-images.githubusercontent.com/44664780/103969716-7f2a5f80-51a1-11eb-8894-20333f3e5926.png)
当连接成功之后变为实线
![image](https://user-images.githubusercontent.com/44664780/103969772-a719c300-51a1-11eb-8afe-f0b65bd093d3.png)
这个信息会被记录到历史记录中，所以看到的效果就是：

1. 连接过程中的状态
![image](https://user-images.githubusercontent.com/44664780/103970022-3a52f880-51a2-11eb-9dcb-22bd4ad11248.png)

2. 连接成功之后
![image](https://user-images.githubusercontent.com/44664780/103970039-4474f700-51a2-11eb-94ae-227b9cbe9575.png)
3. 回退的时候表现为：
![image](https://user-images.githubusercontent.com/44664780/103970079-56ef3080-51a2-11eb-8485-25dc807f61d5.png)
4. 再次点击回退
![image](https://user-images.githubusercontent.com/44664780/103970124-78501c80-51a2-11eb-9c6a-eaf4e4fd3c4c.png)

### Possible Solution
历史记录中，当前是针对某一行为或属性的全部忽略
![image](https://user-images.githubusercontent.com/44664780/103969330-a7658e80-51a0-11eb-8afd-7b43525b32d3.png)
就上面的例子，可不可以添加配置忽略某个或多个事件/属性进行针对性忽略呢？
或者添加手动删除历史记录的方法？

**Comment by NewByVector** [comment]
可以在 beforeAddCommand 方法中根据属性来判断是否添加到 undo 队列

**Comment by NewByVector** [comment]
是否解决了你的问题？

**Comment by bubkoo** [comment]
@Zql-mll 

初始化画布时

```ts
new Graph({
      container: this.container,
      width: 800,
      height: 600,
      grid: true,
      panning: true,
      history: {
        enabled: true,
        beforeAddCommand(event, args: any) {
          // 忽略历史变更
          if (args.options.ignoreHistory) {
            return false
          }
        },
      },
      connecting: {
        createEdge() {
          // 指定新创建的边为虚线样式
          return Edge.create({
            attrs: {
              line: {
                strokeDasharray: '5 5',
              },
            },
          })
        },
      },
    })
```

边链接成功时
```ts
graph.on('edge:connected', ({ edge }) => {
   // 传入自定义的 ignoreHistory 选项来忽略历史变更
   edge.attr('line/strokeDasharray', null, { ignoreHistory: true })
})
```

**Comment by bubkoo** [comment]
@NewByVector 这个方案可以收纳到常见问题中。
