### ISSUE TITLE
使用graph.toJSON()导出vue组件数据，回显报错。

### ISSUE THREAD

**Issue by woshiwhy** [antvis/X6#522]
1.使用graph.toJSON()导出vue组件数据，反序列化回显报错。
![image](https://user-images.githubusercontent.com/21192448/103980601-249dfd00-51bb-11eb-8e88-2b8a43d6bd08.png)
2.组件上定义的回调方法 not defing
![image](https://user-images.githubusercontent.com/21192448/103980831-98400a00-51bb-11eb-9460-a4a5d87ea2ea.png)
发现是导出数据methods里面的值是空。
![image](https://user-images.githubusercontent.com/21192448/103980915-bb6ab980-51bb-11eb-9e8f-db6dd701cb3a.png)

**Comment by qingchiapp** [comment]
1.13.3 版本依然存在此错误
