### ISSUE TITLE
官方示例DAG框选工具bug

### ISSUE THREAD

**Issue by AriaLiang** [antvis/X6#524]
### Current Behavior
除了之前的issue里提到的框选时画布会随之偏移、建组后边被覆盖等情况，还有以下问题：
1. 框选一些节点，建组之后，有时无法选中当前组进行解组；
![image](https://user-images.githubusercontent.com/53068214/104010625-c1768f80-51e7-11eb-941d-b38779a3b057.png)
2. 建组之后，再次框选整组，无法正常移动；
![image](https://user-images.githubusercontent.com/53068214/104010829-161a0a80-51e8-11eb-8f09-7c892b0c65c5.png)

**Comment by bubkoo** [comment]
@lyn-boyu 这个问题好久了，上次有个issue 也是同样的问题，找北岛，他处理过这个问题，一行代码的事。
