### ISSUE TITLE
Edge:dblclick双击事件未触发

### ISSUE THREAD

**Issue by GeorGeWzw** [antvis/X6#528]
### Expected Behavior
Edge:dblclick双击事件未触发

https://user-images.githubusercontent.com/46982191/104113222-571e3600-5332-11eb-99e0-e4d71012bafa.mp4

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
能提供一个codesanbox吗，视频播放不了

**Comment by GeorGeWzw** [comment]
> 能提供一个codesanbox吗，视频播放不了

@NewByVector https://github.com/DestinyCore/DestinyCore.Flow.Design/tree/main/destinycore.flow.design   
在这个仓库里面您看一下

**Comment by NewByVector** [comment]
不要在 edge:click 里面去修改 edge 的 zIndex

**Comment by GeorGeWzw** [comment]
> 不要在 edge:click 里面去修改 edge 的 zIndex

是因为这个导致的对吗？

**Comment by NewByVector** [comment]
> > 不要在 edge:click 里面去修改 edge 的 zIndex
> 
> 是因为这个导致的对吗？

是的

**Comment by GeorGeWzw** [comment]
> > > 不要在 edge:click 里面去修改 edge 的 zIndex
> > 
> > 
> > 是因为这个导致的对吗？
> 
> 是的

@NewByVector 后面会考虑一下优化这个吗？这个z-index 在我的需求中是需要改变他的层级的

**Comment by NewByVector** [comment]
可以加一个 setTimeout 去修改 zIndex，因为修改 zIndex 时元素在 dom 树中会移动，双击事件会失效。这是一个普遍问题。
