### ISSUE TITLE
限制子node移出父node与select冲突报错

### ISSUE THREAD

**Issue by eschervr-dev** [antvis/X6#533]
### Expected Behavior

限制子node移出父node与select冲突报错

### Steps To Reproduce

1.添加限制子node移出父node的代码 ,能够正常运行 
```js
const graph = new Graph({
      container: document.getElementById("container"),
      grid: true,
      width: 500,
      height: 500,
     
      translating: {
        restrict(view) {
            const cell = view.cell;
            if (cell.isNode()) {
              const parent = cell.getParent();
              if (parent) {
                return parent.getBBox();
              }
            }
          return null;
        },
      },
    });
```
2.添加select代码
```js
selecting: {
        enabled: true,
        showNodeSelectionBox: true,
        multiple: false,
      },
```

3. 直接拖动子node，一切正常。但是如果先选中子node或父node再拖动，就会报错，错误如下 ：

<details><summary>Error Message & Stack Trace</summary><p>

```txt
undefined is not an object (evaluating 'view.cell')
```
</p></details>

4.如果加入if判断，不会报错，但是会子node会直接拖出父node。
```js
 translating: {
        restrict(view) {
          if (view) {
            const cell = view.cell;
            if (cell.isNode()) {
              const parent = cell.getParent();
              if (parent) {
                console.log(parent.getBBox())
                return parent.getBBox();
              }
            }
          }
          return null;
        },
```

### Additional Context
测试demo：https://codesandbox.io/s/tender-sea-o9qqe

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by eschervr-dev** [comment]
测试demo：https://codesandbox.io/s/tender-sea-o9qqe

**Comment by NewByVector** [comment]
可以在 selecting 配置中增加 movable: false 来解决上面问题

**Comment by eschervr-dev** [comment]
如果movable: false 的话，那框选多个移动的功能岂不是无效了

**Comment by eschervr-dev** [comment]
> 可以在 selecting 配置中增加 movable: false 来解决上面问题

如果movable: false 的话，那框选多个移动的功能岂不是无效了

**Comment by eschervr-dev** [comment]
我发现添加 
.x6-widget-selection-selected {
    pointer-events: none;
}
可以解决
