### ISSUE TITLE
无法使用快捷键

### ISSUE THREAD

**Issue by xuchaoying** [antvis/X6#535]
### Expected Behavior

https://x6.antv.vision/demos/tutorial/basic/keyboard/playground/ 官方demo下可以进行复制粘贴

### Current Behavior

实际选中`ctrl+c` `ctrl+v`没有任何反应，没有报错。

### Possible Solution

不清楚是不是系统原因，我是 ubuntu+chrome/firefox，在同电脑 windows 虚拟机+edge 下也无法复制粘贴。 

但是快捷键复制粘贴其它东西是可以的（不是键盘坏了）。

找 mac 试了下是 ok 的。QAQ

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0] - 
- OS: [e.g. macOS Sierra 10.12.3]  Linux version 5.4.0-61-generic (buildd@lcy01-amd64-018) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))
- Browser: [e.g. chrome 78.0.3904.108] Chrome Version 87.0.4280.88 (Official Build) (64-bit)    /   firefox 84.0.2 (64-bit)

**Comment by NewByVector** [comment]
绑定的快捷键是 meta+c，在 windows 下面应该是 Win + C / Win + V 这么描述要修改一下

**Comment by xuchaoying** [comment]
> 绑定的快捷键是 meta+c，在 windows 下面应该是 Win + C / Win + V 这么描述要修改一下

所以没有人能复制成功 233
