### ISSUE TITLE
基于ant design 的右键菜单监听事件异常

### ISSUE THREAD

**Issue by LCHLOGO** [antvis/X6#537]
[https://x6.antv.vision/zh/examples/edge/tool#context-menu](url)
理论第三个选项能够实现跳页，但未响应。
我在我的环境中

按照ant design 文档的方式绑定oncClick事件也未能正常响应。。
似乎是组件的监听将事件拦截了

**Comment by bubkoo** [comment]
@LCHLOGO 先看这个 DEMO，https://x6.antv.vision/zh/examples/node/tool#contextmenu，反馈的问题暂时没有找到原因和解法。
