### ISSUE TITLE
开启scroller后,画布背景色的问题

### ISSUE THREAD

**Issue by saperliu** [antvis/X6#538]
### Expected Behavior

开启scroller以后，设置背景色是整个容器的背景色，非画布的背景色。

### Current Behavior

`  this.graph = new Graph({
      container: this.container,
      scroller: {
        enabled: true,
        pageVisible: true,
        pageBreak: false,
        pannable: false,
        pageWidth: 20,
        pageHeight: 20,
        background: {
          color: 'green'
        }
      },
      grid: { visible: true },
      background: { 
        color: 'red' 
      },
    })`

### Possible Solution

增加两个背景色分别设置的函数

### Additional Context

https://codesandbox.io/s/f6rgy?file=/src/app.tsx:258-639

这个例子就是容器的背景是绿色，画布的背景色是红色。

本来想设置画布的背景色，结果改的是容器的背景色。

### Your Environment

- x6: [1.11.3]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
只需要在外部指定 `background` 即可，不需要在 scroller 中指定 `background`。
```ts
    this.graph = new Graph({
      container: this.container,
      grid: { visible: true },
      scroller: {
        enabled: true,
        pageVisible: true,
        pageBreak: false,
        pannable: false,
        pageWidth: 20,
        pageHeight: 20,
        // background: { color: "green" }
      },
      grid: { visible: true },
      background: { color: "red" }
    });
```

**Comment by saperliu** [comment]
> 只需要在外部指定 `background` 即可，不需要在 scroller 中指定 `background`。
> 
> ```ts
>     this.graph = new Graph({
>       container: this.container,
>       grid: { visible: true },
>       scroller: {
>         enabled: true,
>         pageVisible: true,
>         pageBreak: false,
>         pannable: false,
>         pageWidth: 20,
>         pageHeight: 20,
>         // background: { color: "green" }
>       },
>       grid: { visible: true },
>       background: { color: "red" }
>     });
> ```

这样的话，两者是同一个颜色了，能给区分开吗？
并且默认如果设置了背景色，那这两个的颜色是不一样的，一改背景色两个颜色成一种颜色了，这是不是感觉怪怪的？

**Comment by bubkoo** [comment]
@saperliu 

如果设置了两个背景色，修改可以使用下面方法
```ts
drawBackground(options?: Background.Options, onGraph?: boolean)
```
通过 `onGraph` 参数来控制背景色是画布上还是 scroller 上

**Comment by saperliu** [comment]
> @saperliu
> 
> 如果设置了两个背景色，修改可以使用下面方法
> 
> ```ts
> graph.drawBackground(options?: Background.Options, onGraph?: boolean)
> ```
> 
> 通过 `onGraph` 参数来控制背景色是画布上还是 scroller 上

嗯，确实可以。
