### ISSUE TITLE
已连线的链接桩无法链接第三个链接桩

### ISSUE THREAD

**Issue by monijiang** [antvis/X6#540]
### Expected Behavior

单个链接桩可以连线多个链接桩

### Current Behavior

链接桩有一条连线后，无法继续链接

### Steps To Reproduce

1.官网链接可复现: https://x6.antv.vision/apps/draw/

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
这个demo是这样限制的，默认情况链接桩可以连接多条边

**Comment by monijiang** [comment]
我这边自定义了几个节点，是基于内置节点的，出现了一样的情况，连线配置并没有配置相关限制，默认不能连接多个连接桩，能说一下官方demo是怎么做的限制吗，没有找到相关代码,connecting配置中没有看到限制
