### ISSUE TITLE
求助，关于更新vue节点数据问题。

### ISSUE THREAD

**Issue by woshiwhy** [antvis/X6#541]
当shape: 'vue-shape',vue组件有什么方法和节点data值进行双向绑定。节点data值改变，vue组件更新

**Comment by saperliu** [comment]
1、自定义的vue的组件增加一个setOption的方法，这个方法就是更新Vue组件内数据的。
2、你在node增加到画布的时候增加一个事件监听。如下：

     this.getNode().on('change:data', function(node) {
          console.log(' x6  node change:data ', node)
          _this.setOption(node.current.chartOption)
        })

这样当node的数据更新时，自动更新vue组件本身的数据。

**Comment by woshiwhy** [comment]
> 1，自定义的vue的组件增加一个setOption的方法，这个方法就是更新Vue组件内部数据的
> 。2，你在节点上增加到画布的时候增加一个事件监听。如下：
> 
> ```
>  this.getNode().on('change:data', function(node) {
>       console.log(' x6  node change:data ', node)
>       _this.setOption(node.current.chartOption)
>     })
> ```
> 
> 这样当node的数据更新时，自动更新vue组件本身的数据。
 _this执行的是vue组件吗？请问通过什么方法获取这个对象？

**Comment by NewByVector** [comment]
```ts
const data = {}
graph.addNode({
  shape: 'vue-shape',
  data,
  component: {
    data() {
      return data
    }
  }
})
```
这样应该是双向绑定的。

**Comment by woshiwhy** [comment]
> ```ts
> const data = {}
> graph.addNode({
>   shape: 'vue-shape',
>   data,
>   component: {
>     data() {
>       return data
>     }
>   }
> })
> ```
> 
> 这样应该是双向绑定的。

如果是这样的写法，我初始化注册的组件，应该怎么注入到当前添加的节点？

**Comment by saperliu** [comment]
> > 1，自定义的vue的组件增加一个setOption的方法，这个方法就是更新Vue组件内部数据的
> > 。2，你在节点上增加到画布的时候增加一个事件监听。如下：
> > ```
> >  this.getNode().on('change:data', function(node) {
> >       console.log(' x6  node change:data ', node)
> >       _this.setOption(node.current.chartOption)
> >     })
> > ```
> > 
> > 
> > 这样当node的数据更新时，自动更新vue组件本身的数据。
> > _this执行的是vue组件吗？请问通过什么方法获取这个对象？

_this指的是node包含的那个vue组件。

具体组件内的关键代码如下：

```
export default {
  name: 'TopMenu',
  inject: ['getNode'],
  data() {
    return {
      message: ''
    }
  },
  mounted() {
    // 兼容X6的数据更新
    this.x6Change()
  },
  methods: {
    x6Change() {
      const _this = this
      this.getNode().on('change:data', function(node) {
        console.log('   node change:data ', node)
        _this.setOption('设置message')
      })
    },
    setOption(option) {
      console.log('message set option', option)
      this.message = option
    }
  }
}
```

**Comment by woshiwhy** [comment]
> > > 1，自定义的vue的组件增加一个setOption的方法，这个方法就是更新Vue组件内部数据的
> > > 。2，你在节点上增加到画布的时候增加一个事件监听。如下：
> > > ```
> > >  this.getNode().on('change:data', function(node) {
> > >       console.log(' x6  node change:data ', node)
> > >       _this.setOption(node.current.chartOption)
> > >     })
> > > ```
> > > 
> > > 
> > > 这样当node的数据更新时，自动更新vue组件本身的数据。
> > > _this执行的是vue组件吗？请问通过什么方法获取这个对象？
> 
> _this指的是node包含的那个vue组件。
> 
> 具体组件内的关键代码如下：
> 
> ```
> export default {
>   name: 'TopMenu',
>   inject: ['getNode'],
>   data() {
>     return {
>       message: ''
>     }
>   },
>   mounted() {
>     // 兼容X6的数据更新
>     this.x6Change()
>   },
>   methods: {
>     x6Change() {
>       const _this = this
>       this.getNode().on('change:data', function(node) {
>         console.log('   node change:data ', node)
>         _this.setOption('设置message')
>       })
>     },
>     setOption(option) {
>       console.log('message set option', option)
>       this.message = option
>     }
>   }
> }
> ```

谢谢
