### ISSUE TITLE
使用eachart组件，拖拽节点被遮挡

### ISSUE THREAD

**Issue by woshiwhy** [antvis/X6#545]
![image](https://user-images.githubusercontent.com/21192448/104439727-6ae4c900-55cc-11eb-98c8-ea325d11cc5b.png)

 使用eachart，Vue组件。拖拽节点显示不全。
 
![image](https://user-images.githubusercontent.com/21192448/104439757-720bd700-55cc-11eb-8d24-40881c7e053b.png)
当和其他组件相交时，节点可显示。但相交组件被遮盖。

**Comment by NewByVector** [comment]
有线上地址可以看下吗

**Comment by saperliu** [comment]
![image](https://user-images.githubusercontent.com/2297765/104553717-1d249b00-5676-11eb-8d9a-8ac468e6a04b.png)

背景色透明就不遮盖了吧，不过我的是选择框有问题，我把选择后的边框自己添加，弃用的官方的选择框。

**Comment by woshiwhy** [comment]
eachart使用SVG方式渲染，解决问题。
