### ISSUE TITLE
reopen issue 540

### ISSUE THREAD

**Issue by monijiang** [antvis/X6#546]
### Expected Behavior

单个链接桩可以连线多个链接桩

### Current Behavior
链接桩有一条连线后，无法继续链接

我这边也自定义了几个节点，是基于内置节点的，出现了一样的情况，连线配置并没有配置相关限制，默认不能连接多个连接桩，能说一下官方demo是怎么做的限制吗，没有找到相关代码,connecting配置中没有看到限制

### Steps To Reproduce

1.官网链接可复现: https://x6.antv.vision/apps/draw/
2. 关闭540issue后，已实践过fix代码，只在页面刚进入时链接第二个链接桩有效，其余时候仍然无法操作
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
试了下官网 demo 是可以的。
![image](https://user-images.githubusercontent.com/20186737/104464857-603b2b80-55ee-11eb-877b-d267d18cf504.png)

它之前不能连接第二条，是因为连接桩比较小，鼠标会触碰到连接到连接桩的线，碰到线之后就判定离开了连接桩。修改逻辑是把连线的 zIndex 设置低些

**Comment by monijiang** [comment]
@NewByVector   感谢，设置以后，就可以正常多连接了
