### ISSUE TITLE
包的版本问题

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#549]
### Current Behavior

![image](https://user-images.githubusercontent.com/20186737/104566411-844b4b00-5688-11eb-84eb-b9cb27b1165d.png)
![image](https://user-images.githubusercontent.com/20186737/104566461-94632a80-5688-11eb-8231-5a6f9f3d47cf.png)

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@NewByVector 发了 1.1.1
