### ISSUE TITLE
删除|隐藏工具，不能指定具体的工具。

### ISSUE THREAD

**Issue by MrLiuleizhi** [antvis/X6#552]
当有多个工具时，想针对某个工具做隐藏|删除操作，例如，自定义了一个右键菜单工具，同时使用了连接线拖拽的工具，右键连接线做操作的同时，鼠标移出连接线，右键菜单工具也被干掉了。

**Comment by zaiMoe** [comment]
有同样的需求

**Comment by MrLiuleizhi** [comment]
> 有同样的需求

目前我是换了种方式实现了这个效果，自己加了一个removeTool方法，传递Cell对象和要删除的工具名称，方法里面先调了cell.getTools()获取到了Cell对象的所有工具，然后调removeTools()给Cell对象所有工具删除，然后再循环刚刚获取的工具再加回去,目前没有删除单个工具的方法可以先这么用吧。
