### ISSUE TITLE
希望布局能兼容最原始的javascript引入和调用

### ISSUE THREAD

**Issue by HelloToBe-San** [antvis/X6#553]
布局能支持原生版的javascript引入和调用，像X6引入调用<script src="https://unpkg.com/@antv/x6@1.1.1/dist/x6.js"></script>
### Additional Context

这问题会导致我能不能用X6，因为要兼容老项目，只能用最原始的调用引入。实现不了布局，会影响用户体验，最终导致另觅方案

**Comment by NewByVector** [comment]
https://cdn.jsdelivr.net/npm/@antv/layout@0.1.2/dist/layout.js
https://unpkg.com/@antv/layout@0.1.2/dist/layout.js
