### ISSUE TITLE
resizeGraph 画布后，拖动节点后，自动重置为初始化

### ISSUE THREAD

**Issue by saperliu** [antvis/X6#564]
### Expected Behavior

resizeGraph 画布后，拖动节点后，自动重置为初始化

### Current Behavior

resizeGraph 画布后，拖动节点后，自动重置为初始化

### Possible Solution

画布调用resizeGraph 后，拖动节点后，画布依然保持 resizeGraph的值。

### Additional Context

https://codesandbox.io/s/4jm12?file=/src/app.tsx
上面是示例，点击“设置大小”按钮后，画布变小了，但是一拖动节点，画布又变成了初始化时的大小。

- x6: [ 1.12.2]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@saperliu 给的链接中没有看到你说的按钮，链接是不是错了。

**Comment by saperliu** [comment]
> @saperliu 给的链接中没有看到你说的按钮，链接是不是错了。

https://codesandbox.io/s/loving-river-2lzov?file=/src/app.tsx

上面确实没有。可能是没有fork的缘故。这个有了。

**Comment by bubkoo** [comment]
@saperliu 同样没有呢

**Comment by saperliu** [comment]
> @saperliu 同样没有呢
> 
> ![image](https://user-images.githubusercontent.com/6045824/105150109-4e520f00-5b3f-11eb-8ecf-f53c04bdf879.png)

https://codesandbox.io/s/loving-x6-2lzov

无语，我打开是有的，你再打开上面这个看一下。我重新建立了一个。如果还没有，可以用下面代码替换了里面的app.tsx里的代码。


    const graph = new Graph({
      container: this.container,
      width: 500,
      height: 500,
      autoResize: false,
      grid: { visible: true },
      scroller: {
        enabled: true,
        pageVisible: true,
        pageBreak: false,
        pannable: false,
        background: {
          color: "#3a3a30"
        },
        ...options
      },
      background: {
        color: "#ffffff" // 设置画布背景颜色
      }
    });


`  onCenter = () => { 
    this.graph.resizeGraph(200, 150);
  };`

`<Button onClick={this.onCenter}>设置大小</Button>`

上面是app.tsx里改的3处代码。

**Comment by bubkoo** [comment]
@saperliu 上次的修复引发了更多 BUG，只能回退修复了。你给的 DEMO 出现问题的原因是，新设置的画布的大小小于 scroller 的 `pageWidth` 和 `pageHeight`（默认值为初始化时画布容器的大小，也等于画布大小），当移动节点时，由于 scroller 的 `autoResize` 选项为 `true`，我们会自动调整画布大小，调整后的画布大小一定是 `pageWidth` 和 `pageHeight` 的整倍数。

所以，你上面 DEMO 中需要手动设置画布大小的业务背景是什么？另外，可以在设置画布大小时同时调用一下 `graph.resizePageSize()` 来修改分页大小，或者将 `autoResize` 选项设置为 `false`。
