### ISSUE TITLE
path类型的节点中文本显示不出来

### ISSUE THREAD

**Issue by blacksola** [antvis/X6#567]
### Current Behavior

path类型的节点中文本显示不出来

### Steps To Reproduce

官网demo可重现
https://x6.antv.vision/zh/examples/node/native-node#path
![image](https://user-images.githubusercontent.com/16145619/105176927-e2809e00-5b60-11eb-893c-b663969ac811.png)

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: 1.12.4
- Browser: chrome 88.0.4324.96

**Comment by bubkoo** [comment]
test
