### ISSUE TITLE
给画布graph导出的不同JSON序列，添加一个diff算法比较的API？？？

### ISSUE THREAD

**Issue by BrunaDeLafel** [antvis/X6#570]
项目中使用到x6的编辑器，可能存在diff比较JSON序列，做到流程图的刷新。

**Comment by bubkoo** [comment]
@BrunaDeLafel 上面的描述没有看太明白，详细描述一下api的输入和输出，如何使用

**Comment by odysa** [comment]
你是说，一个快速比对出导出json不同的api？

**Comment by BrunaDeLafel** [comment]
就是，X6可以将画布序列化，变成JSON字符串。不同的画布，会有不同的JSON字符串嘛，X6有没有一个方法，比如说叫diff，它可以比较两个JSON字符串的差异点（eg：diff(JSON1, JSON2) 得出差异的对象）

**Comment by BrunaDeLafel** [comment]
> @BrunaDeLafel 上面的描述没有看太明白，详细描述一下api的输入和输出，如何使用
就是，X6可以将画布序列化，变成JSON字符串。不同的画布，会有不同的JSON字符串嘛，X6有没有一个方法，比如说叫diff，它可以比较两个JSON字符串的差异点（eg：diff(JSON1, JSON2) 得出差异的对象）

**Comment by BrunaDeLafel** [comment]
> 你是说，一个快速比对出导出json不同的api？
对

**Comment by NewByVector** [comment]
x6 没有这个方法，这个用其他开源的库去实吧。
