### ISSUE TITLE
【建议】强烈要求，官方demo增加vue模板的demo

### ISSUE THREAD

**Issue by Gilbert5210** [antvis/X6#576]
### Expected Behavior
1. 首先，强烈要求官方demo需要有vue语言的demo,面对只有react很难受
2. 在使用过程中，出现问题一直没有人解答。希望官方有推出解答疑难问题相关团队，作为使用者很揪心
3. 对于我们的er图，希望可以完善下所有的功能点，包括节点里面的可编辑，设置事件等等

**Comment by NewByVector** [comment]
https://codesandbox.io/s/aged-frog-8ciig   已经在官网 vue 章节增加 demo 入口
