### ISSUE TITLE
mac os的safari上锚点对不齐

### ISSUE THREAD

**Issue by quicklearning123** [antvis/X6#578]
看截图
![image](https://user-images.githubusercontent.com/70048681/105452258-fa6b3580-5cb8-11eb-9378-0f7114fe0326.png)

![image](https://user-images.githubusercontent.com/70048681/105452489-62ba1700-5cb9-11eb-822c-dd14f89f01ed.png)

### Expected Behavior

和chrome Firefox一致，线和锚点能对齐，不存在缺口
![image](https://user-images.githubusercontent.com/70048681/105452694-b593ce80-5cb9-11eb-9066-d853872b4eae.png)

### Current Behavior

如图红框所示

### Steps To Reproduce

必现

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0] 官网demo：https://x6.antv.vision/apps/dag/
- OS: [e.g. macOS Sierra 10.12.3] 
![image](https://user-images.githubusercontent.com/70048681/105452372-2981a700-5cb9-11eb-9c7b-14fc4122e429.png)
- Browser: [e.g. chrome 78.0.3904.108]![image](https://user-images.githubusercontent.com/70048681/105452350-21c20280-5cb9-11eb-827f-1fb67d9d07fe.png)

**Comment by NewByVector** [comment]
`foreignObject` 元素在 `safari` 下方法 `getBBox` 有误差，在 X6 内部暂时无法做到兼容，可以在业务中做兼容，兼容代码：
```ts
connecting: {
    sourceAnchor: {
      name: 'bottom',
      args: {
        dx: Platform.IS_SAFARI ? 5 : 0,
      }
    },
    targetAnchor: {
      name: 'center',
      args: {
        dx: Platform.IS_SAFARI ? 5 : 0,
      }
    },
}
```
详情见：https://x6.antv.vision/zh/examples/showcase/practices#algo-flow
