### ISSUE TITLE
使用X6制作流程图Edge，某个节点有多个线的绘制，都是在同一个起点上

### ISSUE THREAD

**Issue by mayunyi** [antvis/X6#580]
### Expected Behavior
期望的是通过json数据时期生成的流程图的线不重合，链接桩均匀分布

如何设置开始节点到目标节点的链接桩的位置。

比如 当前节点有2个目标节点，如何设置当前节点top位置指向其中一个目标，bootm位置指另一个目标源，或者当前节点都在top上（在top上平局分布的形式）指向这2个目标源节点

### Additional Context

![image](https://user-images.githubusercontent.com/26814094/105456523-47063f00-5cc0-11eb-803c-4dc1977b65f6.png)

**Comment by bubkoo** [comment]
@mayunyi 看看这个demo 是否能解决问题。 https://x6.antv.vision/zh/examples/edge/router#er-center

这样配置路由。

```ts
  router: {
    name: 'er',
    args: {
      offset: 'center',
    },
  },
```

**Comment by mayunyi** [comment]
解决了 谢谢
