### ISSUE TITLE
基于节点设置是否可连接线，每个节点可以连接几条线。而不是全局graph上设置。

### ISSUE THREAD

**Issue by cc8992** [antvis/X6#588]
在同一个画布上，希望可以单独设置每个节点是否可以连线。如果可以，可以设置每个节点可以连几条线

**Comment by cc8992** [comment]
可以在connecting 中allowMulti设置节点连线个数。没有找到单独设置每个节点是否可以设置链接

**Comment by NewByVector** [comment]
参考 https://x6.antv.vision/zh/examples/showcase/faq#validate-connection

**Comment by Eve-Sama** [comment]
@NewByVector  我觉得在节点上设置还是有意义的.  虽然你的案例解决了在节点上定义数量的问题, 但是这本质上, 还是在画布上解决的. 因为你需要在画布的`validateMagnet`当中写逻辑. 为什么不把`validateMagnet`等连接线相关的属性放在节点(或者port)上呢? 这两种方式有着本质的区别. 我们来假设一个场景. 
拖拽的节点类型假如有100种, 而用户可以生成其中的1种节点或更多, 而每种节点的连线规则都不一样, 不止是数量, 包括可以连接的节点类型都不同. 但是目前的API很显然需要在graph的属性上把这100种节点对应的情况写一遍. 以我个人业务(我的场景是3种节点, 在`validateConnection`中写了30行判断逻辑)推算的话, 100种大约在1000行代码量. 现有设计有以下几个坏处.

(1). 代码很难维护, 会充斥着各种if else. 比如我想修改第88种节点的连线规则, 我需要在这3000行代码里到处找. 虽然代码可以优化抽象成函数之类的, 但是总归没有写在节点上的方便. 如果写在节点上, 我只需要去找产生第88种节点的函数中修改.

(2). 代码运行时效率低, 因为每次连线的时候都会运行这3000行代码, 虽然返回值是boolean, 可以提前返回, 不需要全部走完. 但如果把连线规则配置在节点上, 那么每一行的代码都是必须应该走的, 不会造成浪费. 

当然, 如果放在节点上, 造成的问题就是无法复用. 比如这100种节点都是同一套逻辑, 那么显然是写在画布上更合适. 是否可以在port, node, graph上都开放出来这些接口, 然后遵从一个优先级port>node>graph来实现呢? 这样就可以解决复用和维护的问题.
