### ISSUE TITLE
textWrap设置ellipsis，若为字母与汉字混合，缩略的计算会不正确

### ISSUE THREAD

**Issue by zaiMoe** [antvis/X6#596]
### Expected Behavior
缩略计算正常

### Current Behavior
https://codesandbox.io/s/practical-night-9kmf0?file=/src/app.tsx

chrome 83.0.4103.61
![image](https://user-images.githubusercontent.com/31397840/105936384-87820600-608e-11eb-84bc-bb08ed0cdde5.png)

firefox 84.0.2
![image](https://user-images.githubusercontent.com/31397840/105936647-08d99880-608f-11eb-84ec-d8ec96a38eff.png)

**Comment by bubkoo** [comment]
@zaiMoe 中英文混排时中间加一下空格吧，拆分加省略号的逻辑是以单词为单位拆分，以单词为单位裁剪

**Comment by zaiMoe** [comment]
> @zaiMoe 中英文混排时中间加一下空格吧，拆分加省略号的逻辑是以单词为单位拆分，以单词为单位裁剪

文案是用户输入的，是否可以通过拆分单个字符，然后累加宽度来和textwrap设定的宽度比较

**Comment by bubkoo** [comment]
@zaiMoe 按字符的话会把一个完整的单词拆开，不符合逻辑吧。

**Comment by bubkoo** [comment]
@zaiMoe 再看看最新版本是否满足预期。

**Comment by zaiMoe** [comment]
@bubkoo 可以的，这样没问题了，但是在firefox以汉字开头会显示异常

![image](https://user-images.githubusercontent.com/31397840/106686707-c3284d00-6605-11eb-944b-6f6379827ed9.png)

**Comment by bubkoo** [comment]
@zaiMoe 我再看看汉子开头的问题

**Comment by zaiMoe** [comment]
@bubkoo 非常感谢！

**Comment by zaiMoe** [comment]
@bubkoo 辛苦了，非常感谢！

今天测试的时候发现了以字母开头也有问题，但是上面那个demo复现不出来，刚刚用文档里的demo测试了下，发现也有问题 
- -！ 麻烦你在看看，我也会尝试查一下原因


![image](https://user-images.githubusercontent.com/31397840/106770700-2f906400-6679-11eb-8c76-145888ae253a.png)

**Comment by zaiMoe** [comment]
@bubkoo

https://github.com/antvis/x6/blob/master/packages/x6/src/util/dom/text.ts#L634

![image](https://user-images.githubusercontent.com/31397840/109776781-ec0c2400-7c3d-11eb-8c9e-74065271ae9b.png)

渲染汉字的时候，`text.getBBox().height > tspan.getBBox().height `，所以被当做太长截断了。
这里考虑至少渲染一行，而不是直接返回空字符串？
或者高度改为计算tspan的高度。

**Comment by zaiMoe** [comment]
@bubkoo  这个问题还没处理吧，被机器人给关了
