### ISSUE TITLE
增加节点的text 竖排显示并自动竖排自动换行

### ISSUE THREAD

**Issue by HelloToBe-San** [antvis/X6#597]
增加节点的text 竖排显示并自动竖排自动换行

例子：
![1611718368(1)](https://user-images.githubusercontent.com/74885930/105939088-71c30f80-6093-11eb-955a-b41d3e1d190a.jpg)

**Comment by NewByVector** [comment]
用 html 节点实现吧，如果要用 svg text 标签实现，可以使用
```ts
attrs: {
    text: {
      transform: 'rotate(90, 0, 0)',
      rotate: -90,
    }
  }
```

**Comment by HelloToBe-San** [comment]
> 用html源码实现吧，如果要用svg text标签实现，可以使用
> 
> ```ts
> ATTRS：{
>     文本：{
>       变换：'旋转（90，0，0）' ，
>       旋转：- 90 ，
>     } 
>   }
> ```

想用svg，用你说的方法，但换不了行

**Comment by NewByVector** [comment]
> > 用html源码实现吧，如果要用svg text标签实现，可以使用
> > ```ts
> > ATTRS：{
> >     文本：{
> >       变换：'旋转（90，0，0）' ，
> >       旋转：- 90 ，
> >     } 
> >   }
> > ```
> 
> 想用svg，用你说的方法，但换不了行

https://codesandbox.io/s/vertical-text-53rg8  看下这个

**Comment by HelloToBe-San** [comment]
> > > 用html源码实现吧，如果要用svg text标签实现，可以使用
> > > ```ts
> > > ATTRS：{
> > >     文本：{
> > >       变换：'旋转（90，0，0）' ，
> > >       旋转：- 90 ，
> > >     } 
> > >   }
> > > ```
> > 
> > 
> > 想用svg，用你说的方法，但换不了行
> 
> https://codesandbox.io/s/vertical-text-53rg8 看下这个

很感谢你的帮忙，我意思是用你的方法能竖排文字，但不会自动换行，text会直接超出节点框

**Comment by bubkoo** [comment]
@HelloToBe-San
可以通过 `textWrap` 属性来设置自动换行，其他参数自行调整到最佳显示效果
https://codesandbox.io/s/vertical-text-forked-it54m?file=/src/App.js

```ts
    graph.addNode({
      x: 200,
      y: 200,
      width: 40,
      height: 200,
      label: "我是一个竖排文本，能不能自动换行一下呢",
      attrs: {
        label: {
          transform: "rotate(90, 0, 0)",
          rotate: -90,
          refX: 16,
          refY: 14,
          lineHeight: 16,
          textAnchor: "left",
          textWrap: {
            width: 200,
            height: 40
          }
        }
      }
    });
```

**Comment by HelloToBe-San** [comment]
> @HelloToBe-San
> 可以通过 `textWrap` 属性来设置自动换行，其他参数自行调整到最佳显示效果
> https://codesandbox.io/s/vertical-text-forked-it54m?file=/src/App.js
> 
> ```ts
>     graph.addNode({
>       x: 200,
>       y: 200,
>       width: 40,
>       height: 200,
>       label: "我是一个竖排文本，能不能自动换行一下呢",
>       attrs: {
>         label: {
>           transform: "rotate(90, 0, 0)",
>           rotate: -90,
>           refX: 16,
>           refY: 14,
>           lineHeight: 16,
>           textAnchor: "left",
>           textWrap: {
>             width: 200,
>             height: 40
>           }
>         }
>       }
>     });
> ```
> 
> ![image](https://user-images.githubusercontent.com/6045824/106573810-11414000-6575-11eb-9f11-ca73a3327948.png)

这个我试过，但好像旋转后，改变不了文字方向，怎么设都是从右到左，无法从左到右
