### ISSUE TITLE
能把vue-shape的包分离出仓库吗

### ISSUE THREAD

**Issue by 775146061** [antvis/X6#599]
想看vue-shape的源码的话，需要下载整个v6仓库，但是整个v6公司网络不好，下载不下来。

**Comment by bubkoo** [comment]
@775146061 如果只是阅读代码，可以使用 `git clone --depth=1` 来下载最近一次提交，这样会小很多很多。

**Comment by 775146061** [comment]
> @775146061 如果只是阅读代码，可以使用 `git clone --depth=1` 来下载最近一次提交，这样会小很多很多。

好的，可以
