### ISSUE TITLE
Using X6 connectors and routers in G6 dagre layout

### ISSUE THREAD

**Issue by PoojaUppalapati** [antvis/X6#617]
### Possible Solution
Provide an example on creating X6 edge in G6 layout

### Steps To Reproduce

1. ...Add a X6 edge connector to G6 dagre layout

    G6.registerEdge(
      "cEdge",
      {
        drawShape: function drawShape(cfg, group) {
          const connectorEdge = new Shape.Edge({
            connector: {
              name: 'jumpover',
              args: {
                type: 'gap',
              },
            },
          });
          return connectorEdge;
        },             
      },
      "edge"
    );

<details><summary>Error Message & Stack Trace</summary><p>
(method) drawShape?(cfg?: ModelConfig, group?: Group): IShape
Type '(cfg: ModelConfig, group: Group) => Edge<Properties>' is not assignable to type '(cfg?: ModelConfig, group?: Group) => IShape'.
  Type 'Edge<Properties>' is missing the following properties from type 'IShape': isHit, isClipShape, getCanvas, getShapeBase, and 29 more.ts(2322)
shape.d.ts(30, 5): The expected type comes from property 'drawShape' which is declared here on type 'Partial<{ [key: string]: any; options: ModelConfig; type: string; itemType: string; shapeType: string; labelPosition: string; labelAutoRotate: boolean; jsx: ShapeDefine; draw(cfg?: ModelConfig, group?: Group): IShape; ... 13 more ...; getPathPoints: (cfg: ModelConfig) => ModelConfig; }>'

**Comment by NewByVector** [comment]
X6 和 G6 不要混用，不是一个框架
