### ISSUE TITLE
Node节点xy为0的时候边框问题

### ISSUE THREAD

**Issue by eschervr-dev** [antvis/X6#629]
### Expected Behavior

Node节点xy为0的时候边框左边和上边会变细
<img width="712" alt="436F4429-A667-47A5-8537-64D07C058D7D" src="https://user-images.githubusercontent.com/55189592/106441301-d7106980-64b4-11eb-8116-71a1f4746a65.png">

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
这个是 svg 内图形的一个特性，x 或 y 设置为 0 的时候，边框只有一半位于 svg 内部。
![image](https://user-images.githubusercontent.com/20186737/106460975-19df3b00-64cf-11eb-90e5-d7c266f66406.png)
