### ISSUE TITLE
增加节点在画布拖动时，限制拖出画布

### ISSUE THREAD

**Issue by HelloToBe-San** [antvis/X6#632]
增加节点在画布拖动时，限制拖出画布范围，拖动节点到边框就限制鼠标移出画布范围并画布边框高亮显示

**Comment by bubkoo** [comment]
@HelloToBe-San 目前可以限制移除画布范围，高亮画布边框需要自己监听移动节点事件来实现。

https://antv-x6.gitee.io/zh/docs/api/graph/transform#translating

![image](https://user-images.githubusercontent.com/6045824/106570304-aa218c80-6570-11eb-9658-815b1df75a08.png)
