### ISSUE TITLE
vue渲染支持文档补全

### ISSUE THREAD

**Issue by chenshuipeng123** [antvis/X6#633]
使用vue渲染节点时，是否支持如下图react案例一样的入参传递做双向绑定？

目前业务需求是从外层面板传递参数触发内部样式和数据的实时改变。
![微信截图_20210202094045](https://user-images.githubusercontent.com/76413756/106540477-fc47bb00-653a-11eb-98dd-05b84de3d729.png)

**Comment by NewByVector** [comment]
vue 中不建议直接把整个 node 传给子组件，监听变化的性能消耗很大，可以把关键数据提取出来。我修改了一下这个demo。可以做到数据的双向绑定 https://codesandbox.io/s/vue-shape-8ciig
