### ISSUE TITLE
elementUI的<el-dialog>与x6面板顺序触发展示时，节点会出现异常。

### ISSUE THREAD

**Issue by chenshuipeng123** [antvis/X6#634]
![image](https://user-images.githubusercontent.com/76413756/106541346-d7ecde00-653c-11eb-8c3e-5e36822dacf9.png)
我的graph被创建在model-container中，嵌套于<el-dialog>标签中。初次打开弹窗，操作一切正常。关闭弹窗，再次打开弹窗，问题出现。

操作应与第一次打开弹窗功能一致。

节点被点击时，会出现粘连鼠标的问题，再次点击会被放下。双击也会出现此问题，我绑定了双击弹窗事件，弹窗操作内容结束后，点击确定关闭弹窗时，发现节点已被拖动到弹窗点击确定按钮的位置。

后续发现进入项目后，只要先打开一次任意<el-dialog>弹窗，再进入graph编辑框页面，就会出现此问题。

我在视图交互事件 'node:click'中打印提示语，出现bug 的状态时，单击鼠标，提示语仅会被打印第一次，后续单击不再会被打印。 但双击事件正常打印。。是否是上一次的弹窗的遮罩或者其它影响了graph中的单击事件？

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Additional Context

这导致我双击打开节点内容编辑框，操作后关闭后，图形被拉扯变形。

![image](https://user-images.githubusercontent.com/76413756/106542410-c4db0d80-653e-11eb-81a0-899d79e7fe86.png)
![image](https://user-images.githubusercontent.com/76413756/106542459-d91f0a80-653e-11eb-9215-42e34300c3c7.png)
![image](https://user-images.githubusercontent.com/76413756/106542487-e20fdc00-653e-11eb-8d44-938775c9fb6b.png)

### Your Environment

![image](https://user-images.githubusercontent.com/76413756/106542618-1be0e280-653f-11eb-96b7-051d87dd3853.png)

- x6: ^1.12.14
- OS: win10家庭中文版
- Browser: chrome 84.0.4147.105

**Comment by NewByVector** [comment]
在对话框 closed 的事件中将画布销毁。可以看下这个 demo；https://codesandbox.io/s/currying-shadow-x6700
