### ISSUE TITLE
【edge】连线使用渐变颜色的时候，水平方向上没渲染出来

### ISSUE THREAD

**Issue by Gilbert5210** [antvis/X6#635]
我在给线自定义渐变颜色的时候，发现水平方向上的线没有渲染出来

![image](https://user-images.githubusercontent.com/17983736/106564521-485d2480-6568-11eb-9ffb-128bf1fc4f3e.png)

当前有demo在这里：
https://codesandbox.io/s/gallant-http-pl445?file=/src/app.tsx

初步查了一下，好像是因为水平方向的时候，存在问题。
https://www.cnblogs.com/677a/p/11732499.html

看下我们是不是有对应的解决方案？

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@Gilbert5210 先使用下面代码，后面我加一下默认值。

```ts
          stroke: {
            type: 'linearGradient',
            stops: [
              { offset: '0%', color: '#13C2C1' },
              { offset: '100%', color: '#3366FF' },
            ],
            attrs: { gradientUnits: 'userSpaceOnUse' },
          },
```

**Comment by Gilbert5210** [comment]
![image](https://user-images.githubusercontent.com/17983736/106576707-6e8ac080-6578-11eb-92ea-db80907253f8.png)


这里的加了这个值后，渐变颜色很奇怪啊？你有去demo验证过来吗 @bubkoo

**Comment by bubkoo** [comment]
@Gilbert5210 我再思考一下。其实原来的第一个DEMO 中渐变的方向应该也有问题，你应该要的是从边的起点到终点的渐变方向

**Comment by Gilbert5210** [comment]
@bubkoo 
是的，我在想解决线显示的问题的话，我会使用规避方案来给线的渐变色覆盖一下。

不过最好是内组件内部就可以解决这个问题。这样业务代码就不需要太冗余

&^&
辛苦晒，有方案记得告诉我。（多久多远都等你）

**Comment by bubkoo** [comment]
沿路径的渐变比较难搞，看到的方案都是将路径拆分为 n 份，通过插值计算渐变颜色，最终效果都有毛刺。

- https://gist.github.com/mbostock/4163057
- https://medium.com/@cereallarceny/getting-gradients-to-follow-along-svg-paths-in-javascript-45357b60bed7

再思考一下。

**Comment by bubkoo** [comment]
@Gilbert5210 

https://codesandbox.io/s/elastic-fog-7mdsg?file=/src/app.tsx

![image](https://user-images.githubusercontent.com/6045824/106612009-93485d80-65a3-11eb-993e-b0aad9b06bc9.png)

X6 更新到最新版。

**Comment by Gilbert5210** [comment]
已经解决了吗，太棒了
