### ISSUE TITLE
通过mousewheel缩放画布报错

### ISSUE THREAD

**Issue by Doifo** [antvis/X6#639]
### Current Behavior

使用mousewheel缩放画布报错：Unable to preventDefault inside passive event listener invocation. （mousewheel.js:62）
chrome 88.0.4324.104 win10 

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by bubkoo** [comment]
@Doifo X6 什么版本？这个问题很早之前就解决过。

**Comment by Doifo** [comment]
最新版1.12.24就有



---原始邮件---
发件人: "问崖"<notifications@github.com&gt;
发送时间: 2021年2月2日(周二) 晚上10:24
收件人: "antvis/X6"<X6@noreply.github.com&gt;;
抄送: "Doifo"<644748799@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [antvis/X6] 通过mousewheel缩放画布报错 (#639)




 
@Doifo X6 什么版本？这个问题很早之前就解决过。

**Comment by bubkoo** [comment]
@Doifo 好的，我们在虚拟机中再试试，系统是 win10 没错吧

**Comment by Doifo** [comment]
是的



---原始邮件---
发件人: "问崖"<notifications@github.com&gt;
发送时间: 2021年2月2日(周二) 晚上10:28
收件人: "antvis/X6"<X6@noreply.github.com&gt;;
抄送: "Doifo"<644748799@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [antvis/X6] 通过mousewheel缩放画布报错 (#639)




 
@Doifo 好的，我们在虚拟机中再试试，系统是 win10 没错吧

**Comment by bubkoo** [comment]
@Doifo 在 win10 + chrome(版本 88.0.4324.146（正式版本） （64 位）) 测试没有报错，这是测试连接 https://codesandbox.io/s/new-moon-cbtmm?file=/package.json

你那边给一个可以复现的 codesandbox 吧

**Comment by JAVPHP** [comment]
您好，请问这个问题解决了么？我这儿1.12.30版本，也报同样的错误

**Comment by JAVPHP** [comment]
> @Doifo 好的，我们在虚拟机中再试试，系统是 win10 没错吧

您好，请问这个问题解决了么？我这儿1.12.30版本，也报同样的错误

**Comment by JAVPHP** [comment]
> @Doifo 好的，我们在虚拟机中再试试，系统是 win10 没错吧

您好，请问这个问题解决了么？我这儿1.12.30版本，鼠标左键点击画布空白处，也报同样的错误：Unable to preventDefault inside passive event listener invocation.
