### ISSUE TITLE
x6-vue-shape 支持 vue3.0

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#645]
### Expected Behavior

x6-vue-shape 支持 vue3.0

**Comment by WXCWHY** [comment]
这个现在支持了吗？

**Comment by ShirlyKong** [comment]
这个大概什么时候会做呢？考虑新项目基于vue3是否能够支持

**Comment by antonreshetov** [comment]
I'm also waiting for the implementation. After using Vue 3 + Vite, I don't want to go back 😀

**Comment by worthworld** [comment]
vue@3.0.5 版本下，安装@antv/x6-vue-shape@1.2.9   时，报错了
![image](https://user-images.githubusercontent.com/50362460/148488146-e2c50d2b-996d-4f5a-be1f-87b16a814ce4.png)

**Comment by a982246809** [comment]
我也遇到了这个报错

**Comment by HuangJinxing2019** [comment]
vue3,0用这个 x6-vue3-shape
