### ISSUE TITLE
修复文本编辑demo文本换行以及画布缩放文本框位置问题

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#646]
### Expected Behavior

修复文本编辑demo文本换行以及画布缩放文本框位置问题

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by HelloToBe-San** [comment]
画布缩放后打印，节点位置也有问题，直接消失一部分
