### ISSUE TITLE
dbclick事件无效

### ISSUE THREAD

**Issue by sscfaith** [antvis/X6#649]
拷贝了官方的例子，node:click改成了node:dbclick，双击无效
### Current Behavior

[https://codesandbox.io/s/loving-brahmagupta-ehq6i?file=/src/app.tsx](https://codesandbox.io/s/loving-brahmagupta-ehq6i?file=/src/app.tsx)

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
node:dblclick 你的拼写错了
