### ISSUE TITLE
设置节点拖动不能超过画布无效

### ISSUE THREAD

**Issue by woshiwhy** [antvis/X6#651]
全局组成注册连线桩节点
![image](https://user-images.githubusercontent.com/21192448/106722993-95f99000-6641-11eb-88f1-44d0c5207f5a.png)

拖动添加该类型的节点时候，发现拖动禁止超过画布设置无效

**Comment by bubkoo** [comment]
@woshiwhy 用 codesandbox 给一下完整的 demo，

**Comment by woshiwhy** [comment]
https://codesandbox.io/s/blazing-water-s7win?file=/src/components/HelloWorld.vue

**Comment by woshiwhy** [comment]
> @woshiwhy用codesandbox给一下完整的demo

https://codesandbox.io/s/immutable-currying-d43lc

**Comment by bubkoo** [comment]
@woshiwhy 你这里的问题是拖动这个椭圆时 会自动扩展画布，导致画布不停的变大（按照 pageWidth 和 pageHeight 的设置扩展画布大小），而实际上是想将节点限制在一页之内？

**Comment by woshiwhy** [comment]
> @woshiwhy你这里的问题是转化为这个椭圆时会自动扩展画布，导致画布不停的变大（按照pageWidth和pageHeight的设置扩展尺寸），而实际上是想将如何限制在一页之内？

是的，没有设置pageWidth和pageHeight默认按照画布高宽自动扩展吗？

**Comment by bubkoo** [comment]
@woshiwhy 是的，默认 `pageWidth` 和 `pageHeight` 就是画布大小，可以尝试下面这样配置来解决。
```ts
      translating: {
        restrict: -20, // 将移动范围限制在画布距离画布边缘 20px 处
      }
```

更新到 1.12.29，DEMO 链接
https://codesandbox.io/s/jolly-benz-ue10s?file=/src/components/HelloWorld.vue
