### ISSUE TITLE
id配置规则自定义

### ISSUE THREAD

**Issue by Vacny** [antvis/X6#655]
###

**Comment by NewByVector** [comment]
要设置拖拽组件的 ID 的原因是？

**Comment by Vacny** [comment]
> 要设置拖拽组件的 ID 的原因是？

流程图业务需要根据id来走，现在自动生成的id规则和系统的不匹配。

**Comment by NewByVector** [comment]
> > 要设置拖拽组件的 ID 的原因是？
> 
> 流程图业务需要根据id来走，现在自动生成的id规则和系统的不匹配。

业务数据放在节点的 data 属性里面。自己定义 id 容易出错

**Comment by Vacny** [comment]
> > > 要设置拖拽组件的 ID 的原因是？
> > 
> > 
> > 流程图业务需要根据id来走，现在自动生成的id规则和系统的不匹配。
> 
> 业务数据放在节点的 data 属性里面。自己定义 id 容易出错

也行，我让后台改改看
