### ISSUE TITLE
edge tools ['vertices','segments] confilict with edge select

### ISSUE THREAD

**Issue by Picktarget** [antvis/X6#659]
when I use edge tools ['vertices','segments] ,I can't select Edge After setting  showEdgeSelectionBox: true,

**Comment by NewByVector** [comment]
```ts
graph.addEdge({
    source,
    target,
    tools: [
      {
        name: 'vertices',
        args: { stopPropagation: false  },
      }
    ]
  })
```

https://x6.antv.vision/zh/docs/api/registry/edge-tool#vertices

**Comment by Picktarget** [comment]
event when I set args: { stopPropagation: false  }, It alse doesn't work perfectly withing the selected status

**Comment by Picktarget** [comment]
event when I set args: { stopPropagation: false }, It alse doesn't work perfectly withing the selected status,when I try to doubleclick to remove the vertices
