### ISSUE TITLE
garah.centerContent()没有按预期实现把任意content自动缩放平移居中显示完全，基于现有api实现了一个，希望后期有类似api

### ISSUE THREAD

**Issue by Asular** [antvis/X6#661]
centerAndZoomGraph(graph) 
        if(graph){
            return
        }
        try {
            const box = graph.getContentBBox();//实际内容大小
            const width = graph.options.width;//画布宽度
            const height = graph.options.height;//画布高度
            let scale = Math.min(width/box.width,height/box.height); 
            scale = Math.floor(scale*100)/100;
            if(scale<1){
                graph.scale(scale);
                //平移X、Y使得内容对齐左上角
                graph.translate(-box.x*scale,-box.y*scale);
            }
        }catch (e){
            console.error(e)
        }
    }

**Comment by NewByVector** [comment]
能否给一下 garah.centerContent() 不能正常工作的 demo
