### ISSUE TITLE
X6引入Echarts

### ISSUE THREAD

**Issue by WXCWHY** [antvis/X6#666]
X6自定义节点支持Echarts引入作为渲染节点吗？

**Comment by NewByVector** [comment]
理论上可以，之前社区有人这么实现过。

**Comment by WXCWHY** [comment]
> 理论上可以，之前社区有人这么实现过。

有具体方案吗？属下比较愚钝

**Comment by woshiwhy** [comment]
> > 理论上可以，之前社区有人这么实现过。
> 
> 有具体方案吗？属下比较愚钝

http://whyfreedom.51vip.biz/dist/#/

**Comment by woshiwhy** [comment]
> X6自定义节点支持Echarts引入作为渲染节点吗？

http://whyfreedom.51vip.biz/dist/#/.
这里有个dome

**Comment by WXCWHY** [comment]
cuo

> > X6自定义节点支持Echarts引入作为渲染节点吗？
> 
> http://whyfreedom.51vip.biz/dist/#/.
> 这里有个dome

非常感谢

**Comment by WXCWHY** [comment]
> > X6自定义例程支持Echarts？
> 
> http://whyfreedom.51vip.biz/dist/#/。
> 这里有个dome

有实现图表那块的源码吗
