### ISSUE TITLE
selection modifiers don't work

### ISSUE THREAD

**Issue by Picktarget** [antvis/X6#667]
as the introduction: 修饰键('alt'、'ctrl'、'meta'、'shift')，设置修饰键后需要点击鼠标并按下修饰键才能触发框选。修饰键在某些场景下非常有用，比如同时开始框选和拖拽画布时，而框选和拖拽画布的触发时机都是鼠标左键在画布空白位置按下，这时可以为框选和拖拽画布设置不一样的修饰键，达到同时开启又不冲突的效果。

even I don't press modifier,it  still could be selected 
preview Url:
https://codesandbox.io/s/jgye7

**Comment by NewByVector** [comment]
```ts
this.graph = new Graph({
      container: this.container,
      grid: { visible: true },
      selecting: {
        enabled: true,
        multiple: true,
        rubberband: true,
        movable: true,
        showNodeSelectionBox: true,
      },
    })
```
你的demo中并没有设置modifier

**Comment by Picktarget** [comment]
我使用的是官方的示例
https://antv-x6.gitee.io/zh/docs/tutorial/basic/selection


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/X6"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月7日(星期天) 中午11:33
收件人:&nbsp;"antvis/X6"<X6@noreply.github.com&gt;;
抄送:&nbsp;"count on me"<327561990@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/X6] selection modifiers don't work (#667)





 this.graph = new Graph({       container: this.container,       grid: { visible: true },       selecting: {         enabled: true,         multiple: true,         rubberband: true,         movable: true,         showNodeSelectionBox: true,       },     })
 
你的demo中并没有设置modifier

**Comment by NewByVector** [comment]
> 我使用的是官方的示例 https://antv-x6.gitee.io/zh/docs/tutorial/basic/selection

我试过是可以的。是不是你这边理解的偏差，按下快捷键时启用框选，是指按下快捷键后，在空白处点击，然后拖动鼠标，进行框选。

**Comment by Picktarget** [comment]
额 ，那我理解的不一样，我是在Edge使用了tools button的vertices工具，发现selection和这个工具的双击取消路径点，存在冲突，即使我设置了stopPropagation:true。感觉交互起来也不是太理想
