### ISSUE TITLE
Translate documentation and use english by default

### ISSUE THREAD

**Issue by pierre-moire** [antvis/X6#671]
This library appears very promising but the usage of chinese makes it very difficult to use outside China. 

Do you think you could use the english language by default? Examples, documentation and comments in english would benefit the library and boost massively its usage.

**Comment by NewByVector** [comment]
We will try our best to use English for the following issue and comments. As for the document, we have no energy to maintain the English version now.

**Comment by ThreeLambs** [comment]
you can use jointjs
