### ISSUE TITLE
graph无法自动重绘

### ISSUE THREAD

**Issue by glmsb** [antvis/X6#673]
在fromjson 生成的graph中，调用node.resize()方法或者node.updateAttrs(）方法都不会触发graph自动重绘，有没有手动重绘的方法和api可以调用。
补充：node节点为 image类型

**Comment by NewByVector** [comment]
我试了下可以的，能提供一个 demo？

**Comment by glmsb** [comment]
let detail = JSON.parse(this.topological.flowData);
this.graph.fromJSON(detail,{silent:false})

this.graph.getNodes().forEach(node => {
            let attrs = node.getAttrs();
            let splitElement = attrs['image']['xlink:href'];
            let iconName = splitElement.substring(4, splitElement.indexOf("."))
            attrs['image']['xlink:href'] = require(`../../icons/svg/classify-status/${iconName}-Dangerous.svg`)
            node.updateAttrs(attrs, {silent: false})
}

**Comment by glmsb** [comment]
如下这段代码也不生效，是否可以帮忙看一下是不是用法有问题 
const view2 = this.graph.findView(node)
            if (view2) {
              view2.animate('image', {
                attributeType: 'CSS',
                attributeName: 'xlink:href',
                from: require(`../../icons/svg/classify-status/${iconName}-Dangerous.svg`),
                to: require(`../../icons/svg/classify-status/${iconName}-Working.svg`),
                dur: '1s',
                repeatCount: 'indefinite',
              })
            }

**Comment by NewByVector** [comment]
```ts
import { Graph, ObjectExt } from '@antv/x6'

const graph = new Graph({
  container: document.getElementById('container'),
  grid: true,
})

graph.addNode({
  shape: 'image',
  x: 320,
  y: 120,
  width: 94,
  height: 28,
  attrs: {
    image: {
      'xlink:href': 'https://gw.alipayobjects.com/os/s/prod/antv/assets/image/logo-with-text-73b8a.svg'
    }
  }
})

graph.getNodes().forEach(node => {
  const  attrs = node.getAttrs();
  const newAttrs = { image: { 'xlink:href': 'xxx' } }
  node.updateAttrs(ObjectExt.merge({}, attrs, newAttrs), {silent: false})
})
```

> let detail = JSON.parse(this.topological.flowData);
> this.graph.fromJSON(detail,{silent:false})
> 
> this.graph.getNodes().forEach(node => {
> let attrs = node.getAttrs();
> let splitElement = attrs['image']['xlink:href'];
> let iconName = splitElement.substring(4, splitElement.indexOf("."))
> attrs['image']['xlink:href'] = require(`../../icons/svg/classify-status/${iconName}-Dangerous.svg`)
> node.updateAttrs(attrs, {silent: false})
> }

```ts
import { Graph, ObjectExt } from '@antv/x6'

const graph = new Graph({
  container: document.getElementById('container'),
  grid: true,
})

graph.addNode({
  shape: 'image',
  x: 320,
  y: 120,
  width: 94,
  height: 28,
  attrs: {
    image: {
      'xlink:href': 'https://gw.alipayobjects.com/os/s/prod/antv/assets/image/logo-with-text-73b8a.svg'
    }
  }
})

graph.getNodes().forEach(node => {
  const  attrs = node.getAttrs();
  const newAttrs = { image: { 'xlink:href': 'xxx' } }
  node.updateAttrs(ObjectExt.merge({}, attrs, newAttrs), {silent: false})
})
```
