### ISSUE TITLE
缩放后，grid对齐异常

### ISSUE THREAD

**Issue by RougeGentleman** [antvis/X6#680]
### Expected Behavior
初始网格对齐正常，进行多次缩放后，网格对齐异常

![image](https://user-images.githubusercontent.com/24186351/108467827-cb98ad00-72c0-11eb-811a-4f4935427004.png)

https://codesandbox.io/s/boring-currying-uxhez

**Comment by NewByVector** [comment]
你指的网格对齐异常是指？
