### ISSUE TITLE
x6 html 渲染 无法连线 

### ISSUE THREAD

**Issue by JohnTao** [antvis/X6#688]
x6 html 渲染 无法连线

**Comment by JohnTao** [comment]
`            const source = graph.addNode({
            x: 200,
            y: 40,
            width: 100,
            height: 40,
            shape: 'html',
            html() {
                const wrap = document.createElement('div')
                wrap.style.width = '100%'
                wrap.style.height = '100%'
                wrap.style.background = '#f0f0f0'
                wrap.style.display = 'flex'
                wrap.style.justifyContent = 'center'
                wrap.style.alignItems = 'center'

                wrap.innerText = 'Hello'

                return wrap
            },
            attrs:{
                body:{
                        magnet:true
                    }
            }
            })`

开启 magnet:true，后 鼠标放到html的元素上 没有十字光标  ，而普通的rect 图形 就有十字光标

**Comment by NewByVector** [comment]
```ts
attrs:{
  fo: {
    magnet: true
  }
}
```
