### ISSUE TITLE
stencil.load([r1, c1, c2, r2.clone()], 'group1')  load html 的自定义元素 就会与 easyui冲突

### ISSUE THREAD

**Issue by JohnTao** [antvis/X6#689]
stencil.load([r1, c1, c2, r2.clone()], 'group1')  load html 的自定义node 就会与 easyui冲突，easyui 样式被改变，按钮点击事件报错

**Comment by JohnTao** [comment]
[index.html.txt](https://github.com/antvis/X6/files/6023197/index.html.txt)
![1613742551(1)](https://user-images.githubusercontent.com/1073365/108733019-0e7cae00-7569-11eb-9268-a661e9b90a86.jpg)

**Comment by NewByVector** [comment]
只要执行 x6 的 createNode 方法就会出现这个问题。
