### ISSUE TITLE
节点内部的一些拖拽事件，如何跟外部的节点的移动事件完美的兼容

### ISSUE THREAD

**Issue by Gilbert5210** [antvis/X6#695]
当前的节点是使用vue来渲染节点的，然后再节点内我放了一个div是可以被拖拽的，但是发现拖拽事件会跟外部整个节点的移动事件冲突。

目的： 主要是为了能实现进行行拖拽连线的功能（我们的er图demo）
![image](https://user-images.githubusercontent.com/17983736/109095489-c9b66a00-7756-11eb-9600-e50fbb418813.png)

我们是不是有更好的方案来解决这个问题
@bubkoo

我写了大概的一个demo： https://codesandbox.io/s/delicate-dawn-mqthu?file=/src/components/Count.vue

如果我没描述清楚的话，可以跟我沟通下

**Comment by NewByVector** [comment]
内部元素的拖拽可以用 mouseup（在这里取消冒泡就可以防止与外部事件冲突） 和 mousemove 事件来实现。不过你的功能可以直接用连接桩来实现呀。

**Comment by Gilbert5210** [comment]
我是想要指定表格中的行数据进行连接，所以连接桩应该没法做到；
mouseup我这边试试看哈

**Comment by Gilbert5210** [comment]
@NewByVector 
这个问题能不能帮我看下？
https://github.com/antvis/X6/issues/359

**Comment by ThreeLambs** [comment]
> 我是想要指定表格中的行数据进行连接，所以连接桩应该没法做到；
> mouseup我这边试试看哈

给表格行添加连接桩，一般都这样实现的。

**Comment by Gilbert5210** [comment]
@NewByVector 
这个类似的需求，我发现用你说的mouse的事件不好整啊
![表格内的行拖拽](https://user-images.githubusercontent.com/17983736/109965934-96617580-7d2a-11eb-8a46-11c09c90fb66.gif)

跪求解决方案

**Comment by NewByVector** [comment]
看下这个 demo ：https://codesandbox.io/s/drag-l3zos
