### ISSUE TITLE
是否考虑支持angular

### ISSUE THREAD

**Issue by breezefaith** [antvis/X6#696]
### Expected Behavior
目前源码中有x6-vue和x6-react，是否考虑增加x6-angular?

**Comment by NewByVector** [comment]
暂时没有计划支持，有兴趣来一波 pr ？🥳

**Comment by breezefaith** [comment]
> 暂时没有计划支持，有兴趣来一波 pr ？🥳

 my pleasure

**Comment by Eve-Sama** [comment]
+1

**Comment by Eve-Sama** [comment]
angular/angular#42621
