### ISSUE TITLE
菱形节点是否可以支持这样的自动布局方式，如果支持使用哪些API

### ISSUE THREAD

**Issue by duyu123** [antvis/X6#697]
![image](https://user-images.githubusercontent.com/21079129/109116470-90dcbc00-777b-11eb-809a-aa8254aed9b9.png)

**Comment by NewByVector** [comment]
支持的。布局的时候只需要知道节点的尺寸。

**Comment by duyu123** [comment]
是用dagre方法自动布局，貌似不太行，一定要用连线桩才行吗

**Comment by duyu123** [comment]
> 支持的。布局的时候只需要知道节点的尺寸。

有demo吗

**Comment by NewByVector** [comment]
布局和形状没有关系，和节点的尺寸有关。
