### ISSUE TITLE
深度复制节点怎么做？

### ISSUE THREAD

**Issue by duyu123** [antvis/X6#701]
### Additional Context
![image](https://user-images.githubusercontent.com/21079129/109444860-2d070b80-7a79-11eb-8aee-1bfec334a1b4.png)
类似这样的流程图
![image](https://user-images.githubusercontent.com/21079129/109444946-650e4e80-7a79-11eb-87b5-739cf89664de.png)
要选中黑框内的菱形，顺便深度复制红框内子孙节点和edge，如何做
1. 是不是要维护每个node和edge的parent和children属性？
2. 是否有demo让我更好的理解？

**Comment by NewByVector** [comment]
看下这个 demo：https://codesandbox.io/s/get-sub-graph-604eq
