### ISSUE TITLE
dist方式引入，registerVueComponent没有挂载到Graph上

### ISSUE THREAD

**Issue by Cyycl** [antvis/X6#702]
### Expected Behavior

dist方式引入，registerVueComponent可以挂载到Graph上

### Current Behavior

RT

### Steps To Reproduce

```js
import { Graph, FunctionExt, Shape, Addon } from "@antv/x6/dist/x6";
import "@antv/x6-vue-shape/dist/x6-vue-shape";
```

### Your Environment
- x6: [1.12.29]
- x6-vue-shape[1.1.6]
- OS: [macOS 10.14.6]
- Browser: [chrome 77.0.3865.120]

**Comment by NewByVector** [comment]
这里为什么要从 `dist` 目录引入？

**Comment by Cyycl** [comment]
> 这里为什么要从 `dist` 目录引入？

因为现在项目中使用了uglifyJs进行混淆压缩，不识别X6/lib中的es6语法。不过问题已经解决了，使用babel对X6/lib进行转译。
