### ISSUE TITLE
「BUG」layoutClass is not a constructor

### ISSUE THREAD

**Issue by EmiyaYang** [antvis/X6#705]
运行布局 demo 代码出错，报错：layoutClass is not a constructor，将 @antv/layout 降级至 0.0.19 则可以解决。

### Expected Behavior

布局 demo 代码正常运行

### Current Behavior

布局 demo 代码无法运行

### Steps To Reproduce

https://codesandbox.io/s/vibrant-goldstine-6lcst?file=/package.json:177-182

**Comment by antonreshetov** [comment]
@NewByVector Unfortunately, it is still an old version of the documentation  https://x6.antv.vision/en/docs/tutorial/advanced/layout

**Comment by NewByVector** [comment]
> @NewByVector Unfortunately, it is still an old version of the documentation https://x6.antv.vision/en/docs/tutorial/advanced/layout

Have a cache?

**Comment by antonreshetov** [comment]
I tried to force refresh the page earlier. The documentation is updated now, thank you.

**Comment by haolic** [comment]
目前来看，问题还是存在的。
```javascript
// package.json
{
  "@antv/layout": "0.1.9",
  "@antv/x6": "^1.13.4",
}
```
但是有一个解决方案：
```javascript
import { Layout } from '@antv/layout';
// 改为
import { DagreLayout } from '@antv/layout'; // 使用哪个布局就引入哪个layout。
```
