### ISSUE TITLE
采用ref相对位置后，大小不会改变

### ISSUE THREAD

**Issue by eschervr-dev** [antvis/X6#707]
采用ref实现node的宽跟随内容的输入而变化，但是获取node.size的时候发现size没有改变。
demo:https://codesandbox.io/s/shy-paper-eo9t8?file=/src/components/HelloWorld.vue

**Comment by lantaozi** [comment]
这是因为node本身没有变化，变化的是node下面的rect矩形背景。

我也在找解决这个问题的方法。目前没有找到怎么获取渲染后的节点的大小的解决方法。

**Comment by zdc1111** [comment]
@eschervr-dev 需要触发 rect 更新  增加body 配置即可 
 this.node.setAttrs({
      label: {
        text: e.target.value
      },
      body: {
        refWidth: "100%",
      }
    })

**Comment by eschervr-dev** [comment]
@zdc1111 你在我发的demo上试试，没效果的，还是一样

**Comment by eschervr-dev** [comment]
@lantaozi  可以用const box = this.graph .findView(cell).findOne("body").getBBox();  这种方式来获取，但是我还是希望官方能修复这个问题 ，毕竟自己处理比较麻烦

**Comment by NewByVector** [comment]
上述场景暂时使用以下方式获取真实尺寸：
```ts
const { width, height } = graph.findViewByCell(child).getBBox()
```

**Comment by eschervr-dev** [comment]
> 上述场景暂时使用以下方式获取真实尺寸：
> 
> ```ts
> const { width, height } = graph.findViewByCell(child).getBBox()
> ```

这个获取的只是text的大小，并不是整体的大小，想要整体的还是得用const box = graph .findView(cell).findOne("body").getBBox()

**Comment by NewByVector** [comment]
```ts
const { width, height } = graph.findViewByCell(node).getBBox()
```
这样是获取 `g` 元素的尺寸。这样比较准确。

**Comment by eschervr-dev** [comment]
> ```ts
> ```ts
> const { width, height } = graph.findViewByCell(node).getBBox()
> ```
> 
> 
> 这样是获取 g 元素的尺寸。这样比较准确。
> ```

但是这个 获取的并不是node的尺寸，我想要的是获得node真实的尺寸
