### ISSUE TITLE
Typescript support for toJSON output data type

### ISSUE THREAD

**Issue by laubonghaudoi** [antvis/X6#713]
Right now the exported data type from `toJSON` has no corresponding type. I checked the `@antv/x6/lib/graph/graph.d.ts`, it only contains the definition:
```typescript
    toJSON(options?: Model.ToJSONOptions): {
        cells: Cell.Properties[];
    };
```

So is
```typescript
{
    cells: Cell.Properties[];
}
```
a class type? I try to define a type for the output data, and read them again, like this:
```typescript
interface OutputData {
    cells: Cell.Properties[];
}

const initData: OutputData = graph.toJSON();

const MyComponent = () => {
    [readData, setReadData] = useState<OutputData>(initData)

    return (
        ...
    )
}

```
However, it returns type error like this (it can compile and run tho): 
![image](https://user-images.githubusercontent.com/11172180/109612660-ed760900-7ae4-11eb-9d1e-8db75d8fc85c.png)

I have used textWrap in the cells. 

So what are the output types of `toJSON`?

**Comment by NewByVector** [comment]
Can you provide your data?
