### ISSUE TITLE
节点shape为html且html为function时，节点更新updateData无法刷新节点

### ISSUE THREAD

**Issue by fanyongchao01** [antvis/X6#717]
Graph.registerNode(
  'kpi-node',
  {
    inherit: 'html',
    width: 180,
    height: 32,
    html ({ data }) {
      return `<div style="width:100%;height:100%">
          <div class="nodeElement___1_-v0">
            <div class="node-icon ${data.icon}"></div>
            <div class="notation___35FHi">${data.name}</div>
          </div>
        </div>`
    },
    tools: [
      {
        name: 'button-remove',
        args: {
          x: '100%',
          y: 0,
          offset: { x: -10, y: 10 },
        },
      },
    ],
    ports: {
      groups: {
        in: {
          attrs: {
            circle: {
              r: 4,
              magnet: true,
              stroke: '#31d0c6',
              fill: '#fff',
              strokeWidth: 1,
            },
          },
          position: { name: 'top' },
        }
      },
      items: [
        { id: 'in', group: 'in' },
      ],
    }
  }
  , true)
### Expected Behavior

调用节点updateData方法后，节点内容并没有更新
### Current Behavior

期望更新布局
### Possible Solution

临时解决：

Graph.Hook.prototype.shouldUpdateHTMLComponent = function () {
  return true
}

这样子写就可以更新

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
使用下面这种方式注册 html 节点，可以实现修改 data 的时候重新渲染：
```ts
const node = graph.addNode({
  x: 80,
  y: 80,
  width: 160,
  height: 60,
  shape: 'html',
  data: {
    time: new Date().toString(),
  },
  html: {
    render(node: Cell) {
      const data = node.getData() as any
      return(
        `<div>
          <span>${data.time}</span>
        </div>`
      )
    },
    shouldComponentUpdate(node: Cell) {
      // 控制节点重新渲染
      return node.hasChanged('data')
    },
  },
})
```

**Comment by 905868332** [comment]
> 使用下面这种方式注册 html 节点，可以实现修改 data 的时候重新渲染：
> 
> ```ts
> const node = graph.addNode({
>   x: 80,
>   y: 80,
>   width: 160,
>   height: 60,
>   shape: 'html',
>   data: {
>     time: new Date().toString(),
>   },
>   html: {
>     render(node: Cell) {
>       const data = node.getData() as any
>       return(
>         `<div>
>           <span>${data.time}</span>
>         </div>`
>       )
>     },
>     shouldComponentUpdate(node: Cell) {
>       // 控制节点重新渲染
>       return node.hasChanged('data')
>     },
>   },
> })
> ```

updateData 重绘后， HTML 中的 img 由于重绘闪烁，怎么处理？

**Comment by Eve-Sama** [comment]
It works for me.
