### ISSUE TITLE
同时开启 scroller 和 autoResize，画布会逐渐消失。

### ISSUE THREAD

**Issue by septlog** [antvis/X6#718]
在创建 graph 对象的时候，设置 scroller 和 autoResize 为 true。
代码：
```js
const graph = new Graph({
  container: this.container,
  scroller: true,
  autoResize: true
});
```
### Expected Behavior
有 scroller，并且画布的大小会根据窗口的大小而改变。

### Current Behavior
画布会逐渐消失。
![1](https://user-images.githubusercontent.com/25605220/109645033-3f746880-7b91-11eb-98a4-8a5b8a9a4849.gif)

codesandbox 链接：
[同时开启 scroller 和 autoResize，画布会逐渐消失。](https://codesandbox.io/s/wonderful-surf-56o64)

**Comment by Gilbert5210** [comment]
我也发现了这个问题，导致我现在每次都重新resize画布

**Comment by Gilbert5210** [comment]
升级版本就可以了吗

**Comment by NewByVector** [comment]
> 升级版本就可以了吗
👉 1.13.4

**Comment by septlog** [comment]
> > 升级版本就可以了吗
> > 👉 1.13.4

autoResize 失效了，缩小窗口再放大，画布大小没变。
![3](https://user-images.githubusercontent.com/25605220/109768333-b8c49780-7c33-11eb-9eea-96d039c7ab06.gif)

**Comment by Gilbert5210** [comment]
@NewByVector 
确实有问题，不能根据外层div的宽度自适应，你整完整个demo看下？

**Comment by NewByVector** [comment]
> > > 升级版本就可以了吗
> > > 👉 1.13.4
> 
> autoResize 失效了，缩小窗口再放大，画布大小没变。
> ![3](https://user-images.githubusercontent.com/25605220/109768333-b8c49780-7c33-11eb-9eea-96d039c7ab06.gif)

https://codesandbox.io/s/great-poitras-3v53k

![image](https://user-images.githubusercontent.com/20186737/109773775-8cf8e000-7c3a-11eb-9b95-44a694c0adf4.png)

**Comment by Gilbert5210** [comment]
@NewByVector 
https://codesandbox.io/s/zidingyidevuezujianjiedianzidingyixian-mqthu?file=/src/components/HelloWorld.vue
你看下我这个要怎么才能实现画布大小跟随适应？

**Comment by septlog** [comment]
但是我在 css 里面已经指定了样式为 flex，还是有问题。
![image](https://user-images.githubusercontent.com/25605220/109779717-2e833000-7c41-11eb-846f-86c3eb189f8a.png)

我看到你的代码里好像有两层 flex box。这样确实没问题。
![image](https://user-images.githubusercontent.com/25605220/109780337-e1538e00-7c41-11eb-9883-6d41ab1087dc.png)

**Comment by Gilbert5210** [comment]
> 但是我在 css 里面已经指定了样式为 flex，还是有问题。
> ![image](https://user-images.githubusercontent.com/25605220/109779717-2e833000-7c41-11eb-846f-86c3eb189f8a.png)
> 
> 我看到你的代码里好像有两层 flex box。这样确实没问题。
> ![image](https://user-images.githubusercontent.com/25605220/109780337-e1538e00-7c41-11eb-9883-6d41ab1087dc.png)

我刚刚在验证这个，确实因为这个。只有使用style方式直接加在标签上面的方式才会生效
![image](https://user-images.githubusercontent.com/17983736/109780715-38f1f980-7c42-11eb-9081-107ccf1b11dc.png)

**Comment by Gilbert5210** [comment]
https://codesandbox.io/s/zidingyidevuezujianjiedianzidingyixian-mqthu?file=/src/components/HelloWorld.vue
但是我这个需要切换的场景，还是没法自适应。高度会一直为0
