### ISSUE TITLE
节点间连线成功后，如何通过js修改target箭头位置到指定锚点？

### ISSUE THREAD

**Issue by qingchiapp** [antvis/X6#725]
选中源节点，链接到目标节点，并未选中目标节点连接桩，线会连到节点而非连接桩上。

如果通过js修改目标箭头到指定的连接桩上呢？

我尝试在 graph.on('edge:connected', (o) => { 事件中修改

o.edge.target.port = 'a1-in'  但是不生效，请问正确的修改方式是什么呢？

**Comment by qingchiapp** [comment]
graph.on('edge:connected', (o) => {
      // {previousView, currentView}
      //需要获取是哪个锚点连接的
      const filedName = o.view.sourceMagnet.getAttribute('port').split('-')[0]
      const tableData = o.view.sourceView.cell.component.data().data
      const rowData = tableData.find(item => item.name === filedName)
      const convertTable = o.currentCell.component.data().data
      convertTable.push(rowData)

      o.edge.remove()
      this.graph.addEdge({
        source: {
          cell: o.view.sourceView.cell.id,
          port: o.view.sourceMagnet.getAttribute('port')
        },
        target: {
          cell: o.currentCell.id,
          port: filedName + '-in'
        }
      })
    })

我现在通过先删除线，再添加线的方式实现了，但这样正确吗，我理解应该可以直接修改锚点的啊，请帮忙解答，谢谢了

**Comment by NewByVector** [comment]
我这里写了一个 demo，你看下： https://codesandbox.io/s/stupefied-sky-604eq?file=/src/app.tsx

**Comment by qingchiapp** [comment]
> 我这里写了一个 demo，你看下： https://codesandbox.io/s/stupefied-sky-604eq?file=/src/app.tsx

您好这个例子怎么没了啊

**Comment by NewByVector** [comment]
> > 我这里写了一个 demo，你看下： https://codesandbox.io/s/stupefied-sky-604eq?file=/src/app.tsx
> 
> 您好这个例子怎么没了啊

https://codesandbox.io/s/change-target-5sj05?file=/src/index.tsx
