### ISSUE TITLE
x6 graph.toJson 不支持 vue2 class 方式创建的组件

### ISSUE THREAD

**Issue by qingchiapp** [antvis/X6#727]
x6 graph.toJson 不支持 vue2 class 方式创建的组件

以官方示例自定义vue组件基础demo，vue count的举例

以此种方式渲染的组件
<template>
  <div>
    <div>{{ num }}</div>
    <button @click="click">add</button>
  </div>
</template>

<script>
export default ({
  name: 'Count',
  props: {
    num: Number
  },
  inject: ['getGraph', 'getNode'],
  methods: {
    click() {
      this.$emit('add')
      this.getNode().attr('body/strokeWidth', this.num + 1)
    }
  }
});
</script>
，tojson后导出内容为：

{
  'cells': [{
    'position': { 'x': 100, 'y': 100 },
    'size': { 'width': 200, 'height': 200 },
    'view': 'vue-shape-view',
    'attrs': { 'body': { 'stroke': 'red', 'width': 200, 'height': 200, 'strokeWidth': 12 } },
    'shape': 'vue-shape',
    'id': 'c5f78cca-4bd2-46de-913e-211ed5037c4c',
    'component': {
      'template': '<count :num="num" @add="add()"></count>',
      'methods': {},
      'components': {
        'Count': {
          'name': 'Count',
          'props': { 'num': {} },
          'inject': { 'getGraph': { 'from': 'getGraph' }, 'getNode': { 'from': 'getNode' } },
          'methods': {},
          'staticRenderFns': [],
          '_compiled': true,
          'beforeCreate': [null],
          'beforeDestroy': [null],
          '__file': 'src/components/Count.vue',
          '_Ctor': {}
        }
      }
    },
    'zIndex': 1
  }]
}

以class方式创建的vue count组件，代码如下
<template>
  <div>
    <div>{{ num }}</div>
    <button @click="click">add</button>
  </div>
</template>

<script lang="ts">
import {Component, Inject, Prop, Vue} from 'vue-property-decorator'

@Component
export default class Count extends Vue {
  @Inject() getGraph!: Function
  @Inject() getNode!: Function
  @Prop() num: number

  click() {
    this.$emit('add')
    this.getNode().attr('body/strokeWidth', this.num + 1)
  }
}
</script>

graph.toJson导出的内容为：
{
  'cells': [{
    'position': { 'x': 110, 'y': 100 },
    'size': { 'width': 200, 'height': 200 },
    'view': 'vue-shape-view',
    'attrs': { 'body': { 'stroke': 'red', 'width': 200, 'height': 200, 'strokeWidth': 5 } },
    'shape': 'vue-shape',
    'id': '91b41f59-a42e-49b4-bb91-b058a7fba496',
    'component': { 'template': '<count :num="num" @add="add()"></count>', 'methods': {}, 'components': {} },
    'zIndex': 1
  }]
}

**Comment by qingchiapp** [comment]
另外，如果我的自定义组件里面依赖了其他的自定义组件，该如何处理呢，是里面嵌套的每个自定义组件都需要这样写一下吗，如果我写的自定义组件里面依赖了 10个其他ui库的ui组件，ui库的组件也需要定义吗

**Comment by NewByVector** [comment]
Graph.registerVueComponent(...) 使用这种方式注册 vue 组件。看下文档。

**Comment by qingchiapp** [comment]
> Graph.registerVueComponent(...) 使用这种方式注册 vue 组件。看下文档。

是使用了这种方式注册的
