### ISSUE TITLE
toJSON出来的节点id与画布上的id不一致

### ISSUE THREAD

**Issue by zlc-Moon** [antvis/X6#728]
我利用stencil拖拽插件从侧边栏拖入了一个节点, 并利用getDropNode()函数, 自定义了这个节点的id值为我需要的值.
```javascript
getDropNode: (nodeTemplate) => {
    let node = nodeTemplate.clone();
    node.id = 'updateNode' + this.nodeNumber.updateNode;
    this.nodeNumber.updateNode++;
    return node;
}
```

在拖入节点后, 通过Graph.getCell(id)函数,我能拿到这个节点的信息.
![image](https://user-images.githubusercontent.com/61084457/109928424-68ffd200-7d00-11eb-9faa-e3d9ab659598.png)
但当我用Graph.toJSON()保存数据时,却发现该节点的id并非我设置id的值.
![image](https://user-images.githubusercontent.com/61084457/109928649-9fd5e800-7d00-11eb-95cc-3d26d4fade6e.png)

**Comment by NewByVector** [comment]
节点的 id 不要修改，自定义的标记信息放到 data 属性里面。如果要拿到新拖动到画布的节点，可以监听 node:added 事件。
