### ISSUE TITLE
使用graph.toJSON()导出vue组件数据，回显报错。 #522  Closed

### ISSUE THREAD

**Issue by qingchiapp** [antvis/X6#729]
#522 

1.13.3版本依然存在此错误

**Comment by qingchiapp** [comment]
导出内容如下

{
    "cells": [{
        "position": {"x": -30, "y": -100},
        "size": {"width": 200, "height": 200},
        "view": "vue-shape-view",
        "attrs": {"body": {"stroke": "red", "width": 200, "height": 200, "strokeWidth": 3}},
        "shape": "vue-shape",
        "id": "13c9a69b-796c-43ff-8e77-88e96501a5f3",
        "component": {
            "template": "<count :num=\"num\" @add=\"add()\"></count>",
            "methods": {},
            "components": {
                "Count": {
                    "name": "Count",
                    "props": {"num": {}},
                    "inject": {"getGraph": {"from": "getGraph"}, "getNode": {"from": "getNode"}},
                    "methods": {},
                    "staticRenderFns": [],
                    "_compiled": true,
                    "beforeCreate": [null],
                    "beforeDestroy": [null],
                    "__file": "src/components/Count.vue",
                    "_Ctor": {}
                }
            }
        },
        "zIndex": 1
    }]
}

**Comment by qingchiapp** [comment]
[Vue warn]: Property or method "num" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.esm.js?a026:628
warnNonPresent @ vue.esm.js?a026:2047
has @ vue.esm.js?a026:2092
eval @ VM3418:3
Vue._render @ vue.esm.js?a026:3557
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
Vue._init @ vue.esm.js?a026:5027
Vue @ vue.esm.js?a026:5094
renderVueComponent @ view.js?1718:47
eval @ view.js?1718:29
handleAction @ cell.js?b865:160
confirmUpdate @ view.js?1718:29
updateView @ renderer.js?000e:302
updateViewsBatch @ renderer.js?000e:374
updateViews @ renderer.js?000e:310
unfreeze @ renderer.js?000e:676
resetViews @ renderer.js?000e:697
onModelReseted @ renderer.js?000e:63
apply @ function.js?b9bc:8
call @ events.js?4ed1:80
trigger @ events.js?4ed1:56
notify @ model.js?6dd5:24
eval @ model.js?6dd5:58
apply @ function.js?b9bc:8
call @ events.js?4ed1:80
trigger @ events.js?4ed1:56
reset @ collection.js?fbe1:146
resetCells @ model.js?6dd5:166
fromJSON @ model.js?6dd5:902
fromJSON @ graph.js?114c:101
importJson @ HomeX6Graph.vue?a211:268
invokeWithErrorHandling @ vue.esm.js?a026:1863
invoker @ vue.esm.js?a026:2188
invokeWithErrorHandling @ vue.esm.js?a026:1863
Vue.$emit @ vue.esm.js?a026:3897
handleClick @ element-ui.common.js?5c96:9417
invokeWithErrorHandling @ vue.esm.js?a026:1863
invoker @ vue.esm.js?a026:2188
original._wrapper @ vue.esm.js?a026:7565
Show 14 more frames
vue.esm.js?a026:628 [Vue warn]: Error in beforeCreate hook: "TypeError: Cannot read property 'call' of null"

found in

---> <Count> at src/components/Count.vue
       <Root>
warn @ vue.esm.js?a026:628
logError @ vue.esm.js?a026:1893
globalHandleError @ vue.esm.js?a026


报错内容如下

**Comment by NewByVector** [comment]
提供一个 简单的 codesanbox？

**Comment by qingchiapp** [comment]
> 提供一个 简单的 codesanbox？

ok

**Comment by webpig** [comment]
这个解决了吗？我现在也有这个问题，提示属性和方法都没有定义

**Comment by SillyBoyXZH** [comment]
同问
