### ISSUE TITLE
别人有的，希望X6也可以有

### ISSUE THREAD

**Issue by HelloToBe-San** [antvis/X6#731]
![1](https://user-images.githubusercontent.com/74885930/109954974-e6d1d680-7d1c-11eb-980f-d4ca39a22cfe.png)
…]()

对齐方式：这个好像有居中，但左右对齐好像没看见相关文档。如果有的话，麻烦发一下连接

刻度对齐：这个应该和那个grid有关吧，设了网格后，节点拖动是不是会受影响，有时候想对齐一个节点，那个对齐线就是对齐不到，始终都差一点。所以问问有没有直接根据刻度对齐的或者不受背景网格影响，毕竟设不开启网格后，体验感差了很多。

最后 真的需要那个setFollowing和showNodeSelectionBox动态开启 @NewByVector 应该没@错人

**Comment by HelloToBe-San** [comment]
对，还有一个问题，能不能实现那种使用布局后，当节点超出了画布，自动扩大画布的大小，如果有，麻烦给下链接我瞅瞅

**Comment by jiangnan-ten** [comment]
@HelloToBe-San 这是什么工具

**Comment by liyunhechn** [comment]
> 对，还有一个问题，能不能实现那种使用布局后，当节点超出了画布，自动扩大画布的大小，如果有，麻烦给下链接我瞅瞅

https://x6.antv.vision/zh/docs/tutorial/basic/scroller#%E6%BC%94%E7%A4%BA
这个满足要求吗？
