### ISSUE TITLE
[Docs]: transform page 404

### ISSUE THREAD

**Issue by antonreshetov** [antvis/X6#737]
Error 404 when opening https://x6.antv.vision/en/docs/api/graph/transform

### Expected Behavior

Successful page opening

### Current Behavior

Error 404

### Steps To Reproduce

Open link https://x6.antv.vision/en/docs/api/graph/transform

**Comment by antonreshetov** [comment]
@bubkoo Issue was closed, but the page is still unavailable

**Comment by NewByVector** [comment]
> @bubkoo Issue was closed, but the page is still unavailable

There's something wrong with the deployment of the site. I'll take care of it

**Comment by NewByVector** [comment]
> @bubkoo Issue was closed, but the page is still unavailable

You can access it now.
