### ISSUE TITLE
[QUESTIONS]: add new nodes in layout graph

### ISSUE THREAD

**Issue by antonreshetov** [antvis/X6#742]
Is there a way to add nodes and edges programmatically to a graph when using layout?

According to the documentation a new graph is built by

```js
const newModel = gridLayout.layout(model)

graph.fromJSON(newModel)
```

However, call `graph.addNode()` method will not update the graph. 

As I understand it, I need to reassemble the nodes and edges into a variable and render graph again?

```js
const newModel = gridLayout.layout(modelUpdated)

graph.fromJSON(newModel)
```

**Comment by antonreshetov** [comment]
https://codesandbox.io/s/boring-feather-xxzku?file=/index.js

Probably need to clarify, graph is not updated according to the layout after adding a new node and edge.

**Comment by NewByVector** [comment]
> https://codesandbox.io/s/boring-feather-xxzku?file=/index.js
> 
> Probably need to clarify, graph is not updated according to the layout after adding a new node and edge.

After adding nodes, you need to modify the data and then layout it

**Comment by antonreshetov** [comment]
> After adding nodes, you need to modify the data and then layout it

I.e., reassemble the nodes and edges into a variable and render graph again?
```js
const newModel = gridLayout.layout(modelUpdated)
graph.fromJSON(newModel)
```

I thought there was something like this method `graph.layoutRefresh()`

**Comment by NewByVector** [comment]
> > After adding nodes, you need to modify the data and then layout it
> 
> I.e., reassemble the nodes and edges into a variable and render graph again?
> 
> ```js
> const newModel = gridLayout.layout(modelUpdated)
> graph.fromJSON(newModel)
> ```
> 
> I thought there was something like this method `graph.layoutRefresh()` after add new node by `graph.addNode()`

This can do by your self, using the same logic as you said above.

**Comment by antonreshetov** [comment]
That's what I do, it's no big deal. I just thought there was another way to update the layout after adding new nodes and edges. Thanks for the clarification.
