### ISSUE TITLE
如何让线与节点的链接点事指定锚点，并且自适应？

### ISSUE THREAD

**Issue by Gilbert5210** [antvis/X6#749]
没错，我们现在可以支持
![image](https://user-images.githubusercontent.com/17983736/110302037-c31bd280-8033-11eb-953f-96d73a0bdca0.png)

但是现在存在这么个场景，就是节点上只有链接桩可以作为连接连线的点。
当我的节点发生位置改变的话，自适应最合适的链接桩

需求： 
指定节点的链接桩，比如上下左右。
节点位置发生变化的时候，自动找到最佳的链接桩进行切换

也就是我们需要结合port和connectionPoint。

这边看下有没有现有的实现方案可以整?

**Comment by NewByVector** [comment]
在 `midSide` node-anchor 中增加配置:
```ts
direction: 'H' | 'V
```

**Comment by Gilbert5210** [comment]
哥，你太强了吧 。
我今晚還在想着要怎么实现来的。
我后面一定要学习一波源码，然后给我们强大的库做贡献。

非常感谢
