### ISSUE TITLE
使用Stencil往Graph

### ISSUE THREAD

**Issue by MouXinyue** [antvis/X6#761]
### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by eevin** [comment]
相同的问题
在Modal 或者 Drawer 使用、拖拽代理无法显示、放下能正常显示拖拽图形。
修改Modal 或者 Drawer 的zIndex 参数<=100 能够正常显示

**Comment by NewByVector** [comment]
@eevin 
```css
.x6-widget-dnd {
  z-index: 3000
}
```
