### ISSUE TITLE
当格式为x6使用toJSON导出的结果时无法识别，希望toJSON能可以导出layout识别的格式

### ISSUE THREAD

**Issue by belongwqz** [antvis/X6#765]
### Additional Context

x6的graph.toJSON()导出的格式为{cells:[xxxx]}，而layout只能识别{nodes:[xx],edges:[xx]}。而x6的graph.fromJSON可以识别两种格式。

要么增强layout组件，能识别x6的toJSON导出格式，要么x6的toJSON能导出layout能识别的格式。

# [当格式为x6使用toJSON导出的结果时无法识别](https://github.com/antvis/layout/issues/23)

**Comment by NewByVector** [comment]
可参考这个 demo 进行数据转换：https://codesandbox.io/s/layout-data-qlkg8?file=/src/app.tsx

**Comment by belongwqz** [comment]
转换也不是为一种方案，只是感觉绕弯路，如果layout直接内部支持就好了。
