### ISSUE TITLE
如果将Stencilh侧边栏（带Node节点）和Graph被放置在较高图层，拖拽时生成的代理节点的不可见

### ISSUE THREAD

**Issue by MouXinyue** [antvis/X6#766]
### 将侧边框和画布的dom放到一个图层较高的div中，我是放到了iview的modal对话框中了，这时拖拽侧边框中的节点，生成的代理节点不可见，被对话框遮罩住了。查看发现代理节点div的class为.x6-widget-dnd.dragging，默认z-index为100导致看不见。

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
前台没有报错
```

</p></details>

### Additional Context

![x61](https://user-images.githubusercontent.com/50064863/110911842-2bc5c080-834e-11eb-8d40-5ce6b9afc364.png)

![x62](https://user-images.githubusercontent.com/50064863/110912631-21f08d00-834f-11eb-948b-cf64f0b9bd4f.png)

### Vue

- x6: [e.g. 1.0.0]
- OS: win10
- Browser: 谷歌浏览器

**Comment by MouXinyue** [comment]
添加样式也不生效
<style scoped>
    /deep/ .x6-widget-dnd.dragging {
        z-index: 99999 !important;
    }
</style>

**Comment by MouXinyue** [comment]
使用<style></style>去掉scoped属性就可以了

**Comment by eevin** [comment]
问题同 #761 ，在Modal 或者 Drawer 使用、拖拽代理无法显示、放下能正常显示拖拽图形。
修改Modal 或者 Drawer 的zIndex 参数<=100 能够正常显示
