### ISSUE TITLE
createNode方法入参的data无法接收[object Object]对象，却能接收{...[object Object]}对象

### ISSUE THREAD

**Issue by qingchiapp** [antvis/X6#771]
Can only serialize node with plain-object props, but got a "[object Object]" type of key "data" on node "0ea44e82-b608-4676-a0b3-9fe7ac7c5b40"

报错

```
const nodeData: NodeDataVO = new NodeDataVO()
const node = this.graph.createNode({
      shape: 'vue-shape',
      width: 350,
      height: 250,
      // view: 'table-node-view',
      data: nodeData,
      ports: portsStyle,
      component: 'x-table-component'
    })
```

不报错

```
const nodeData: NodeDataVO = new NodeDataVO()
const node = this.graph.createNode({
      shape: 'vue-shape',
      width: 350,
      height: 250,
      // view: 'table-node-view',
      data: {
        ...nodeData
      },
      ports: portsStyle,
      component: 'x-table-component'
    })

```

**Comment by NewByVector** [comment]
节点的 `data` 只支持 `plainObject`,你传入一个 `new NodeDataVO()` 肯定是不行的。

**Comment by qingchiapp** [comment]
> 节点的 `data` 只支持 `plainObject`,你传入一个 `new NodeDataVO()` 肯定是不行的。

是因为业务需要，所以必要要求plainObject吗，传入类对象会造成什么问题吗，如果可以不限制，或不限制没什么坏影响的话，为什么要有这样的限制呢

**Comment by NewByVector** [comment]
这里限制只能是 plainObject 的，如果是类对象，推荐外部来维护这个数据。因为 x6 内部有对 data 改变做监听，如果存入类对象，会影响内存和性能。

**Comment by qingchiapp** [comment]
> 这里限制只能是 plainObject 的，如果是类对象，推荐外部来维护这个数据。因为 x6 内部有对 data 改变做监听，如果存入类对象，会影响内存和性能。

好的了解了，希望未来可以在性能允许的范围内支持吧，辛苦

**Comment by social-uni** [comment]
今天又遇到这个问题了，都忘了怎么解决的了，记录下， 不要使用new 创建对象，使用 = {}方式创建，然后可以new一个临时对象，遍历他的key，给{}赋值为null，实现响应式，不需要响应式直接 ={}就行
