### ISSUE TITLE
vue组件反序列化时cell的size属性的width和height使用字符串会出现问题，无法设置宽度

### ISSUE THREAD

**Issue by qingchiapp** [antvis/X6#772]
反序列化时使用vue组件渲染

使用数值设置宽高，正确代码：

```
'size': {
      'width': 350,
      'height': 250
    },
```

显示效果正确

![image](https://user-images.githubusercontent.com/14007972/111025473-5d5a8c80-841f-11eb-8855-894618ae8b62.png)

使用字符串设置宽高错误：
```
'size': {
      'width': '350',
      'height': '250'
    },
```
![image](https://user-images.githubusercontent.com/14007972/111025516-9abf1a00-841f-11eb-8fbc-386785a26b39.png)

因为宽度与预期不符，所以右侧的锚点也没有显示出来

**Comment by NewByVector** [comment]
还是业务做数据正确性保证，这里不做过度防御编程。

**Comment by qingchiapp** [comment]
> 还是业务做数据正确性保证，这里不做过度防御编程。

基于js弱类型，和这部分数据会入库存储转为xml，json等形式，类型很容易发生变化，认为做容错是合适的
