### ISSUE TITLE
【严重影响业务】悬浮连接桩闪烁，点击连接桩滚动条会滚动到头部

### ISSUE THREAD

**Issue by qingchiapp** [antvis/X6#776]
点击port滚动到顶部的问题，比较严重，会造成无法连线，想要连接两个滚动底部的port，因为这个问题，会无法实现。

比较严重，麻烦官方能回复下，目前有没有什么方式可以规避这个问题？

使用vue的el-table开发的。

存在滚动条的时候，两个table连线的效果。 鼠标悬浮到连接桩上，table会闪烁。

点击连接桩的节点，滚动条会始终滚动到顶部

**Comment by qingchiapp** [comment]
钉钉群里，有其他开发者也遇到了相同问题

附图

![image](https://user-images.githubusercontent.com/14007972/111101777-89901d80-8585-11eb-937e-f3d1b436cdf9.png)

**Comment by wangminqinag** [comment]
我也遇到这个问题了

**Comment by NewByVector** [comment]
```ts
const graph = new Graph({
  sorting: 'approx'
})
```

**Comment by qingchiapp** [comment]
> ```ts
> const graph = new Graph({
>   sorting: 'approx'
> })
> ```

您好， 测试了，点击滚动到顶部的问题解决了，

可是划过锚点，界面闪烁的问题依然存在

**Comment by NewByVector** [comment]
麻烦给个 codesanbox 看下

**Comment by overpowerFish** [comment]
@social-uni 你好，我也碰到这个问题了 鼠标移入或者移出连接桩时 界面某些图片会闪烁，请问怎么解决的

**Comment by personalZhang** [comment]
@social-uni 用react开发遇到相同问题，请问有解决吗

**Comment by social-uni** [comment]
> @social-uni 你好，我也碰到这个问题了 鼠标移入或者移出连接桩时 界面某些图片会闪烁，请问怎么解决的

闪烁问题没解决，官方让提供demo

**Comment by social-uni** [comment]
> @social-uni 用react开发遇到相同问题，请问有解决吗

闪烁问题没解决，官方让提供demo

**Comment by NewByVector** [comment]
@social-uni @personalZhang  闪烁问题是浏览器渲染 foreignObject 内容的bug，检查一下节点内是否有 position: 'relative' 或者 position: 'absolute' 的样式，使用其他布局替换

**Comment by kongxiangyan** [comment]
> @social-uni @personalZhang 闪烁问题是浏览器渲染 foreignObject 内容的bug，检查一下节点内是否有 position: 'relative' 或者 position: 'absolute' 的样式，使用其他布局替换

被闪烁整烦了，非常感谢
