### ISSUE TITLE
电脑系统缩放至125%以上渲染画布文字节点会丢失，数据也获取不到

### ISSUE THREAD

**Issue by cenchengcong** [antvis/X6#777]
### Expected Behavior

应正常完整渲染画布
### Current Behavior

画布渲染丢失文字节点，显示空白，并且获取不到数据
[](url)
### Possible Solution

目前获取设备缩放，然后反向将页面缩放，但是连线会错位，以及产生其他偏移问题
### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
请问这边你是怎么操作电脑系统缩放到125%的。我这边试了一下没有问题

**Comment by cenchengcong** [comment]
右键桌面 - 显示设置 - 缩放与布局，笔记本小屏

**Comment by cenchengcong** [comment]
![未命名1615798170](https://user-images.githubusercontent.com/20202750/111127188-7d6c8600-85ae-11eb-9093-c13a070942a4.png)
![未命名1615798142](https://user-images.githubusercontent.com/20202750/111127205-82c9d080-85ae-11eb-894b-af4a8c77205a.png)
![未命名1615798069](https://user-images.githubusercontent.com/20202750/111127211-852c2a80-85ae-11eb-9cf2-b32d19cba57e.png)
![未命名1615798104](https://user-images.githubusercontent.com/20202750/111127218-865d5780-85ae-11eb-9579-88766e7693b7.png)

**Comment by cenchengcong** [comment]
样式被设置成隐藏了，修改样式就能出来

**Comment by NewByVector** [comment]
windows 系统是吧 等我回去看下

**Comment by zdc1111** [comment]
@cenchengcong 老哥 无法复现 提供一下电脑分辨率 ，在codeSandbox 写一个demo?
