### ISSUE TITLE
Rendering HTML Button in Edge Label alignment Issue, in VUE

### ISSUE THREAD

**Issue by dhiliphvenkatesan** [antvis/X6#783]
I am referring  rendering the HTML button in the edge label from the examples provided in this package. But the alignment of the HTML button varies according to the position of edge. since the elements are in SVG, I can't align the button with edge.
I have also used a custom tool button in my demo and it is too not getting aligned. If you hover over the edge, you can see the "X" custom button.

Please check my demo link below:
https://codesandbox.io/s/nervous-clarke-plqkl?file=/src/app.tsx

I have used this example: 
https://x6.antv.vision/zh/examples/edge/label#render-with-html

I have used the below demo provided by newByVector Account:
https://codesandbox.io/s/html-tools-yzwkp

**Comment by NewByVector** [comment]
Please use the following method：https://codesandbox.io/s/html-label-hq3ge?file=/src/app.tsx

**Comment by dhiliphvenkatesan** [comment]
Its Working Fine. Thanks
