### ISSUE TITLE
layout期望可以对父子关系进行布局,或者有没有解决方案

### ISSUE THREAD

**Issue by railgun20001** [antvis/X6#784]
### Expected Behavior
当节点存在父子关系时,layout.layout()布局后希望字节点在父节点内部

### Additional Context

![image](https://user-images.githubusercontent.com/22837283/111566409-0fa3a280-87d8-11eb-9379-2863c121e671.png)
这是现在layout的效果, 可以看见子节点不在父节点内部
```
let data = {
  nodes: [],
  edges: [],
}
for (let index = 1, max = 10; index < max; index++) {
  data.nodes.push({
    id: index + '',
    shape: 'parent-node',
    width: 90,
    height: 90,
    label: index,
    children: ['child' + index],
  })
  data.nodes.push({
    id: 'child' + index,
    shape: 'child-node',
    label: 'child' + index,
    parent: index,
  })
  if (index < max - 1) {
    data.edges.push({
      shape: 'solid-edge',
      source: index + '',
      target: (index + 1) + '',
    })
  }
}

const layout = GridLayout({
  preventOverlap: true,
  nodeSize: 110,
})
graph.fromJSON(layout.layout(data))
```

**Comment by belongwqz** [comment]
确实是个问题，布局的时候可以不申明位置坐标比较方便，但是使用群组的时候布局就显示不对了。

**Comment by NewByVector** [comment]
这个需要筛选父节点出来进行布局，如果父节点下面存在多个子节点，再局部对子节点进行布局。

**Comment by refuse-c** [comment]
> Hiya!
> 
> This issue has gone quiet. Spooky quiet. 👻
> 
> We get a lot of issues, so we currently close issues after 60 days of inactivity. It’s been at least 20 days since the last update here. If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not-stale" to keep this issue open!
> 
> As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [contribute](https://github.com/antvis/X6/blob/master/CONTRIBUTING.md) for more information about opening PRs, triaging issues, and contributing!
> 
> Thanks for being a part of the AntV community! 💪💯

可以详细说明一下?就是群组嵌套了群组  然后没有各种非群组的子节点 嵌套层级比较多  比如群组的size 怎么计算
