### ISSUE TITLE
Windows系统，在项目根目录执行yarn bootstrap报错

### ISSUE THREAD

**Issue by breezefaith** [antvis/X6#809]
根目录下执行yarn bootstrap命令时报错如下。看起来像是node_modules\@antv\stylelint-config\node_modules\.bin\run-s脚本中文件路径的问题 ```"$basedir/../../../../node_modules/npm-run-all/bin/run-s/index.js"```
![image](https://user-images.githubusercontent.com/20924601/112415391-b6e78300-8d5e-11eb-8939-9c966d40e391.png)
![image](https://user-images.githubusercontent.com/20924601/112415729-4d1ba900-8d5f-11eb-96dc-3c72e26dffb1.png)

### Your Environment

- OS: Windows Server 2016 Standard

**Comment by breezefaith** [comment]
好像是lerna的bug，在linux环境下lerna bootstrap安装完依赖后会创建可执行脚本的软链接，但是在windows环境下，是直接把可执行脚本复制到了相应的目录下，这就导致了找不到文件的问题

**Comment by NewByVector** [comment]
感谢你提出的问题，有好的解决方案吗🧐

**Comment by zaiMoe** [comment]
> 好像是lerna的bug，在linux环境下lerna bootstrap安装完依赖后会创建可执行脚本的软链接，但是在windows环境下，是直接把可执行脚本复制到了相应的目录下，这就导致了找不到文件的问题

发现是yarn的问题：https://github.com/yarnpkg/yarn/issues/4564，挂了好几年了都没解决的问题......

**Comment by breezefaith** [comment]
> > 好像是lerna的bug，在linux环境下lerna bootstrap安装完依赖后会创建可执行脚本的软链接，但是在windows环境下，是直接把可执行脚本复制到了相应的目录下，这就导致了找不到文件的问题
> 
> 发现是yarn的问题：[yarnpkg/yarn#4564](https://github.com/yarnpkg/yarn/issues/4564), 挂了好几年了都没解决的问题......

**Comment by breezefaith** [comment]
> > 好像是lerna的bug，在linux环境下lerna bootstrap安装完依赖后会创建可执行脚本的软链接，但是在windows环境下，是直接把可执行脚本复制到了相应的目录下，这就导致了找不到文件的问题
> 
> 发现是yarn的问题：[yarnpkg/yarn#4564](https://github.com/yarnpkg/yarn/issues/4564), 挂了好几年了都没解决的问题......

**Comment by breezefaith** [comment]
> > 好像是lerna的bug，在linux环境下lerna bootstrap安装完依赖后会创建可执行脚本的软链接，但是在windows环境下，是直接把可执行脚本复制到了相应的目录下，这就导致了找不到文件的问题
> 
> 发现是yarn的问题：[yarnpkg/yarn#4564](https://github.com/yarnpkg/yarn/issues/4564), 挂了好几年了都没解决的问题......

**Comment by breezefaith** [comment]
> 感谢你提出的问题，有好的解决方案吗🧐

根据zaiMoe所说的这是yarn的bug，我把lerna.json配置文件里的npmClient配置节改成了“npm”，然后执行```npm run bootstrap```，虽然速度慢点，但总算是把依赖都安装成功了

**Comment by zaiMoe** [comment]
> 感谢你提出的问题，有好的解决方案吗🧐

可以把`bootstrap`改一下：
```
"bootstrap": "yarn install --ignore-scripts && lerna run preinstall && yarn build:dev"
```
再把其他命令中的`"prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'"`中的单引号改成双引号，就能跑通过了，但是由ts编译错误

![image](https://user-images.githubusercontent.com/31397840/112863722-b85fd500-90e9-11eb-8e80-2520e687048a.png)

**Comment by jerry-f** [comment]
使用了命令之（yarn install --ignore-scripts && lerna run preinstall && yarn build:dev）后可以下载依赖了；
但是去到 examples/x6-app-draw 下执行yarn start 命令之后会报错； 依赖找不到（@antv/x6-react-components/es/toolbatr/style/index.css）

**Comment by ChendayUP** [comment]
> > 感谢你提出的问题，有好的解决方案吗🧐
> 
> 根据zaiMoe所说的这是yarn的bug，我把lerna.json配置文件里的npmClient配置节改成了“npm”，然后执行`npm run bootstrap`，虽然速度慢点，但总算是把依赖都安装成功了

然后执行`npm run bootstrap` 后还是报错
![企业微信截图_16328163778987](https://user-images.githubusercontent.com/20022523/135048479-41f08a51-2fcf-485b-909a-c29c206929dc.png)
了

**Comment by zaiMoe** [comment]
window10的话试试使用[WSL](https://docs.microsoft.com/zh-cn/windows/wsl/install)

**Comment by zaiMoe** [comment]
> > > 感谢你提出的问题，有好的解决方案吗🧐
> > 
> > 
> > 根据zaiMoe所说的这是yarn的bug，我把lerna.json配置文件里的npmClient配置节改成了“npm”，然后执行`npm run bootstrap`，虽然速度慢点，但总算是把依赖都安装成功了
> 
> 然后执行`npm run bootstrap` 后还是报错 ![企业微信截图_16328163778987](https://user-images.githubusercontent.com/20022523/135048479-41f08a51-2fcf-485b-909a-c29c206929dc.png) 了

window10试试用[WSL](https://docs.microsoft.com/zh-cn/windows/wsl/install)

**Comment by zhjIvy** [comment]
win10 有人试过什么办法可以解决这个bug

**Comment by iceytea** [comment]
### 在 windows 上使用 wsl2 进行编译通过。下面是要注意的点：

1. 请使用 wsl 下的文件系统，否则会遇到权限问题
2. 在国内的网络，遇到sharp下载报错：可以配置 sharp 中国镜像[链接](https://sharp.pixelplumbing.com/install#chinese-mirror)
```sh
npm config set sharp_binary_host "https://npm.taobao.org/mirrors/sharp"
npm config set sharp_libvips_binary_host "https://npm.taobao.org/mirrors/sharp-libvips"
npm install sharp
```

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢

**Comment by cuidong626** [comment]
装了wsl 终于可以了。。。

**Comment by zyzweb** [comment]
> > 感谢你提出的问题，有好的解决方案吗🧐
> 
> 可以把`bootstrap`改一下：
> 
> ```
> "bootstrap": "yarn install --ignore-scripts && lerna run preinstall && yarn build:dev"
> ```
> 
> 再把其他命令中的`"prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'"`中的单引号改成双引号，就能跑通过了，但是由ts编译错误
> 
> ![image](https://user-images.githubusercontent.com/31397840/112863722-b85fd500-90e9-11eb-8e80-2520e687048a.png)

执行yarn build:sites还是有问题

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢

**Comment by Trojanpa** [comment]
> 

你好，我对wsl2不了解，我应该如何使用wsl2解决这个安装报错问题呀？有没有相关步骤教程呢

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢

**Comment by Trojanpa** [comment]
> 装了wsl 终于可以了。。。

兄弟，wsl怎么弄？

**Comment by ibertli** [comment]
兄弟你这个问题是怎么解决的？

**Comment by Skypow2012** [comment]
我是在 X6-master/examples/x6-app-dag 目录运行 yarn 报了这个错，下面这个评论是正解，把 examples 里的文件复制到其他文件夹再 yarn，就没有报错了，亲测能在 Windows 10 跑官方示例了
https://github.com/antvis/X6/issues/38#issuecomment-565814633

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢

**Comment by NewByVector** [comment]
windows 下有一些兼容问题，推荐使用 wsl 进行安装。

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢
