### ISSUE TITLE
开启resizing调整节点大小后，节点连接桩位置漂移

### ISSUE THREAD

**Issue by noirlyrik** [antvis/X6#812]
开启resizing，调整节点大小后，节点连接桩位置漂移，主要是菱形和自定义的平行四边形有这个现象

### Current Behavior
原始大小时：
![image](https://user-images.githubusercontent.com/39143373/112444988-9c76cf00-8d89-11eb-8f57-396873433790.png)

放大节点后：
![image](https://user-images.githubusercontent.com/39143373/112445023-a7316400-8d89-11eb-854f-9f16e2f2b0e5.png)

port配置项中的dx和dy是否可以支持百分比？

![image](https://user-images.githubusercontent.com/39143373/112445213-dba52000-8d89-11eb-8d95-4848c0ca47f9.png)

**Comment by NewByVector** [comment]
支持的，设置成 `0-1` 以内的小数即可。

**Comment by noirlyrik** [comment]
> 支持的，设置成 `0-1` 以内的小数即可。

设置了，没有生效

**Comment by NewByVector** [comment]
https://codesandbox.io/s/yemmf?file=/src/app.tsx 使用这个 demo 尝试一下

**Comment by noirlyrik** [comment]
0-1之间的小数无法将连接桩设置在菱形顶点，如果是用数字设置，缩放节点会使连接桩漂移
demo： https://codesandbox.io/s/vigilant-carson-4rrkp?file=/src/settings.tsx

**Comment by NewByVector** [comment]
https://x6.antv.vision/zh/examples/node/native-node#polygon  绘制菱形使用 polygon 节点 吧

**Comment by noirlyrik** [comment]
菱形问题已经解决，感谢。平行四边形也是用polygon自定义的，还是有漂移问题。

**Comment by NewByVector** [comment]
可以使用 `absolute` 来定位，它是支持百分比的。https://codesandbox.io/s/port-position-i0k8c
