### ISSUE TITLE
连续框选和其他使用需求

### ISSUE THREAD

**Issue by HelloToBe-San** [antvis/X6#814]
1、点击空白处拖动可以框选节点，按快捷键后再框选（支持框选和点选），原有节点选中不取消

2、selection的following动态开启，业务场景：following是用来框选拖动大量节点使用，框选拖动小量节点时想用原来的movable

3、框选时最好能屏蔽连接桩的影响，业务特殊，一个节点上下左右都有连接桩，只显示了一个，其余隐藏，大量的节点靠近在一起，框选时候由于太靠近，节点本身大小加上连接桩大小导致节点范围大，开启strict时，由于隐藏的连接桩导致用户使用时候没全部框选到，没能选中，用户反映框选有问题。不开启strict时，节点范围太大，隐藏的连接桩在另外节点上面，没框选到该节点，但由于隐藏节点连接桩的缘故，导致有交互，框选到该节点

**Comment by HelloToBe-San** [comment]
等候大哥解决，拜托拜托

**Comment by breezefaith** [comment]
框选点选不是都支持吗
https://x6.antv.vision/apps/draw/

**Comment by HelloToBe-San** [comment]
> 框选点选不是都支持吗
> https://x6.antv.vision/apps/draw/

我的意思是框选后按快捷键再框选（之前的节点选中后不取消），不是点选，X6目前只支持框选加点选，我要框选加框选
