### ISSUE TITLE
X6希望支持导出PDF

### ISSUE THREAD

**Issue by looklookseesee** [antvis/X6#815]
1、X6希望支持导出PDF
2、使用画布居中，再使用positionContent("top")有时候会丢失一点点内容，但导出图片却不会，能用导出图片的方法打印吗？

**Comment by NewByVector** [comment]
可以使用 `jspdf` 来实现，可以参考下面 demo：https://codesandbox.io/s/pdf-g7hwy。
第二个问题可提供一个可复现的在线 demo？

**Comment by looklookseesee** [comment]
> 可以使用 `jspdf` 来实现，可以参考下面 demo：[https://codesandbox.io/s/pdf-g7hwy。](https://codesandbox.io/s/pdf-g7hwy%E3%80%82)
> 第二个问题可提供一个可复现的在线 demo？

用JSPDF要设图片大小，导出的图片能确定大小吗？
第二个问题偶然性发生，我还是继续排查自己的原因

**Comment by NewByVector** [comment]
这个大小是定义绘制在pdf上的大小，可以根据实际情况设置。

**Comment by looklookseesee** [comment]
> 这个大小是定义绘制在pdf上的大小，可以根据实际情况设置。

你的意思我能理解成每次都根据实际情况设置，而不是根据获得的图片大小设置？
如果是这样的话就好像不对吧，我能自定义，但用户不能啊。

**Comment by NewByVector** [comment]
我理解你是要知道原来图片的宽度和高度吧，https://codesandbox.io/s/pdf-g7hwy?file=/src/app.tsx 看下这个
