### ISSUE TITLE
custom node is conflict to graph rotating property

### ISSUE THREAD

**Issue by liyunheasap** [antvis/X6#821]
### Expected Behavior

No Error.

### Current Behavior

When Graph's property `rotating: true`, Register a custom node. Then `AddNode` to graph. 
When Rendered, Click This node.

### Possible Solution

Error Not Limited to rotating property. When trigger **`Transform.render`**  Function

### Steps To Reproduce

example: https://codesandbox.io/s/custom-node-rotating-conflict-7p8f3?file=/src/app.tsx

<details><summary>Error Message & Stack Trace</summary><p>

```txt
ERROR TypeError: Cannot read property 'addClass' of undefined
    at Transform.render (index.js:67)
    at Transform.init (index.js:21)
    at new Widget (widget.js:40)
    at new Transform (index.js:6)
    at Hook.createTransform (hook.js:122)
    at Hook.descriptor.value (hook.js:71)
    at TransformManager.onNodeSelected (transform.js:48)
    at Module.apply (function.js:8)
    at Object.call (events.js:80)
    at Graph.trigger (events.js:56)
```

</p></details>

### Additional Context

None.

### Your Environment

- x6: [latest 1.18.0]
- OS: [e.g. Windows 10]
- Browser: [e.g. Edge 89.0.774.63 (官方内部版本) (64 位)]

**Comment by liyunheasap** [comment]
Error Not Limited to rotating property. When trigger **`Transform.render`**  Function

**Comment by NewByVector** [comment]
你这里 `es` 和 `lib` 导出模块混用了，可以：
```ts
import { Graph, Shape } from '@antv/x6'
const RedRect = Shape.Rect.define({
  attrs: {
    body: {
      stroke: "red"
    }
  }
})
```

**Comment by NewByVector** [comment]
或者：`import { Rect } from "@antv/x6/es/shape/standard";`

**Comment by liyunheasap** [comment]
果然是这样…… 感谢你的协助👍
