### ISSUE TITLE
非 scroller 模式下支持画布拖拽，以及画布的miniMap

### ISSUE THREAD

**Issue by Gilbert5210** [antvis/X6#823]
非 scroller 模式下支持画布拖拽，以及画布的miniMap

因为突然出现的滚动条会很不习惯，并且也很丑 ；

原本在G6那边的处理方式就很舒服

现在是开启miniMap的时候必须要开启scroll

想要不开启scroll且能开启miniMap的功能

**Comment by HelloToBe-San** [comment]
有画布拖拽https://x6.antv.vision/zh/docs/tutorial/basic/graph

**Comment by Gilbert5210** [comment]
> 有画布拖拽https://x6.antv.vision/zh/docs/tutorial/basic/graph

get,但是主要点事miniMap好像没法
