### ISSUE TITLE
x6 没有提供保存方法吗？像G6的 gragh.save()方法一样

### ISSUE THREAD

**Issue by sbzkp** [antvis/X6#824]
x6 没有提供保存方法吗？像G6的 gragh.save()方法一样

_Originally posted by @yumenglong in https://github.com/antvis/X6/issues/332#issuecomment-757820176_

**Comment by NewByVector** [comment]
保存为json: `graph.toJSON()`
保存为图片：https://x6.antv.vision/zh/docs/tutorial/basic/graph#%E5%AF%BC%E5%87%BA-pngjpeg
