### ISSUE TITLE
使用Stencil不能拖拽

### ISSUE THREAD

**Issue by 599218337** [antvis/X6#825]
如题，使用Stencil的时候，如果拖拽里面的节点，会报错
![IMG_4944](https://user-images.githubusercontent.com/56375648/112943855-9fe0d080-9164-11eb-93d9-ead0cca3d026.PNG)

**Comment by NewByVector** [comment]
提供一个复现的 codesanbox?

**Comment by 599218337** [comment]
问题解决了 ，原因是IDE自动导包的时候导错了  节点对象本应该从Shape模块引用，IDE自动从这个路径导：
import { Circle, Rect } from "@antv/x6/lib/shape/basic";
