### ISSUE TITLE
X6官网-图表示例-文本编辑

### ISSUE THREAD

**Issue by ZYX518** [antvis/X6#828]
### Expected Behavior
对话框，边得输入框获取焦点后光标应再字符串最后得位置。
报警输入框输入内容换行，计数器也应换行
计数器输入框获取焦点应可用鼠标再框内点击调整光标位置

### Current Behavior

报表输入框焦点在字符串前面得位置
坐标输入框如果输入Enter换行，则第一次输入有效，之后获取焦点再失去焦点，不做任何操作，则没有换行效果转换器
输入框首次获取焦点鼠标可调整光标位置，在此操作则无效

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by TaiKyo** [comment]
**Expected Behavior**
开启 minimap，对节点进行编辑，失去焦点之后，编辑成功

**Current Behavior**
对节点进行编辑，失去焦点后，节点空白，等一会儿之后，节点还原为原先的文本，编辑不成功

**Your Environment**
x6： ^1.18.0
OS: windows 10
Browser: Chrome  89.0.4389.90
