### ISSUE TITLE
火狐(Firefox)浏览器下拖动带有image的node表现异常的情况

### ISSUE THREAD

**Issue by railgun20001** [antvis/X6#831]
### Current Behavior

生产中碰到了问题,然后去官网看看也有同样的问题
https://antv-x6.gitee.io/zh/examples/showcase/practices#org
在火狐浏览器下,拖动这个页面的node的文字部分,表现正常
拖动node的image会出现异常情况,打开图片的新tab,放开node也在拖动状态等

win10 64
火狐版本 Firefox Browser 87.0 (64 位)

### Steps To Reproduce

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

**Comment by Gilbert5210** [comment]
追加

firefox下使用内部layout的库。导致页面报错，请求解决方案

**Comment by railgun20001** [comment]
> /cib

参照你的代码可以了,谢谢指导
image设置pointerEvents: 'none'
再加个透明rect设置pointerEvents: 'visiblePainted'

**Comment by java-qgsmn** [comment]
image 设置pointer-events:none没有效果啊

**Comment by railgun20001** [comment]
> image 设置pointer-events:none没有效果啊

https://github.com/antvis/X6/commit/a42c9c092ccc14c7599d8bbfbe9998a11041d3b0
这样的
