### ISSUE TITLE
react 节点下 foreignObject > body 下的一级标签能改为 span 吗？

### ISSUE THREAD

**Issue by EmiyaYang** [antvis/X6#832]
使用 div 标签会出现部分图元渲染失败的情况，参考[statckoverflow](https://stackoverflow.com/questions/46561099/div-inside-svg-foreignobject-loses-its-position-and-not-visible-in-latest-chrome)。

硬编码替换则会导致组件节点事件监听失效。

![image](https://user-images.githubusercontent.com/22047765/113130732-faeef200-924e-11eb-9c06-32240d4fd3c6.png)

**Comment by NewByVector** [comment]
修改为 span 也会有问题：https://bugs.webkit.org/show_bug.cgi?id=93358 出现渲染问题，可以检查一下是否有元素使用
```css
position: relative
```
样式，在 foreignObject 里面 `relative` 和 `absolute` 兼容性不太好。
