### ISSUE TITLE
ER例子中的foreignObject中body层级不对

### ISSUE THREAD

**Issue by imjamespond** [antvis/X6#833]
https://x6.antv.vision/apps/er/ 中
![image](https://user-images.githubusercontent.com/12231940/113233074-02ef7600-92d1-11eb-954f-3c4b06916029.png)
如果将以下position属性改为fixed,就正常, 不知道是啥原理
```
.x6-node foreignObject > body {
    position: fixed;
```
![image](https://user-images.githubusercontent.com/12231940/113233214-4ba72f00-92d1-11eb-83aa-ff8552adfa14.png)

**Comment by NewByVector** [comment]
@imjamespond  可以暂时使用这个方式解决，是 foreignObject 内元素渲染问题。
