### ISSUE TITLE
折叠树结构添加新节点重新绘图，现有节点位置有时会发生改变

### ISSUE THREAD

**Issue by su-miao** [antvis/X6#837]
example：

  根节点下有四个子节点，在四个子节点的任意一个节点下新增下一级子节点，此时四个子节点的位置顺序有时会发生变化

  注：树结构的数据没有坐标，是通过自动布局绘制的，添加子节点时也是通过改变原有数据，然后自动布局重新绘图

**Comment by NewByVector** [comment]
提供一个可以复现的 demo ？
