### ISSUE TITLE
使用自动布局渲染大量数据浏览器响应时间过长

### ISSUE THREAD

**Issue by su-miao** [antvis/X6#838]
知道节点及节点间的关系，但坐标未知，通过自动布局进行绘图，节点数据可能达上千条，此时浏览器响应时间过长

**Comment by HelloToBe-San** [comment]
用画布异步加载或者弄个定时器fromJSON时候，显示加载中，我就是这样解决，先出画布，后出数据

**Comment by NewByVector** [comment]
先看下是布局计算耗时久还是渲染耗时久，如果布局计算耗时比较久，可以将计算逻辑放到 worker 中去执行。

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/115818513-7b100e00-a42f-11eb-8714-66e32fc7f269.png)
我这里现在耗时最久的是反序列化创建节点时候merge默认设置。。。
