### ISSUE TITLE
How to change connection ports dynamically by dragging edge?

### ISSUE THREAD

**Issue by dhiliphvenkatesan** [antvis/X6#839]
I am connecting nodes via ports. I want to change the ports of the connected edge by dragging the edge and connecting to the port. I achieved the port change by calling the edge.setSource() and edge.setTarget() Method in edge click function.

See my demo link from below:
https://codesandbox.io/s/nervous-clarke-plqkl?file=/src/app.tsx

Please click on the edge to see the change in the input and output ports. I want to achieve the same thing via dragging the edge and connecting to the port. And also Please mention the event when port changes.

**Comment by NewByVector** [comment]
you can use this [tool](https://x6.antv.vision/zh/docs/api/registry/edge-tool#source-arrowhead-%E5%92%8C-target-arrowhead) ,after change the edge terminal，you can listen for the event:
```ts
graph.on("edge:change:target", () => {
  //
});
```

**Comment by dhiliphvenkatesan** [comment]
Worked Fine Thanks
