### ISSUE TITLE
自定义节点reszing失效

### ISSUE THREAD

**Issue by iamwelk** [antvis/X6#840]
![image](https://user-images.githubusercontent.com/6983075/113469945-1db61c00-9484-11eb-9e7d-f7a13ebf1f45.png)

如上图所示，开启了resizing属性，调整大小并没有生效，节点还是原来的效果

**Comment by NewByVector** [comment]
要实现可以 `resizing` 的 path 元素，需要使用 `refD` 属性，可以看这个demo：https://codesandbox.io/s/resizing-path-82qrh
