### ISSUE TITLE
Can X6 Zoom in / out by using mousewheel ?

### ISSUE THREAD

**Issue by No54** [antvis/X6#841]
Hi, 

I start up a X6 demo, but I find that the canvas would be scolled up / down when using the mousewheel? 

Is it a default feature? 

How to change it  to zoom in / out the canvas by using mousewheel directly?

**Comment by NewByVector** [comment]
https://x6.antv.vision/zh/docs/tutorial/basic/mousewheel

**Comment by No54** [comment]
Thanks！I ll track the doc
