### ISSUE TITLE
No Instructions in english

### ISSUE THREAD

**Issue by brettforbes** [antvis/X6#842]
I really like the capability of your software, but unfortunately using it carries too much risk as there are no instructions in English. I wish you had English documentation for all of your packages

In general, packages written in another language need an English copy of the manual and api defintions, or the package is only usable by those who can speak the language. Your package looks really great, but it is unusable by >half of the worlds population, since there is no English translation

You should put in the very small effort required to translate your manuals into English. Seriously, this is mostly automated so it should be very easy.

Instead you have a great product that is completely unusable, how sad!!!!
Great looking product, completely useless documentation

**Comment by NewByVector** [comment]
First of all, I'm sorry for the trouble you have caused. We are also preparing to optimize the official website, including the support of English documents。

**Comment by blahah** [comment]
@brettforbes what a terrible attitude and unpleasant way to talk to people. You're rude and arrogant, and you should apologise. Software and documentation written in English is the standard, meaning English speakers generally are always catered for. Nobody has any obligation to translate their language to English for you. 

Anyone is free to translate the docs, and as you said it's easy to do. So do it yourself. Or learn Chinese.

**Comment by brettforbes** [comment]
@blahah perhaps you are right, I must admit to being impressed with the capabilities, and then annoyed that i couldn't accees it because of language, especially when one considers the breadth of capabilities. But perhaps you are right, I shouldn't have said anything really. Unfortunately, I am too busy to learn Chinese at present, thanks for your kind advice

**Comment by blahah** [comment]
@brettforbes thanks for being humble. It's OK to request a translation. What's not OK is to insult people who worked incredibly hard to provide something to you completely free. Bring positive energy and appreciation, the other stuff has no place here.
