### ISSUE TITLE
力导向布局 demo 能达到跟 G6 实例一样的动态布局吗？

### ISSUE THREAD

**Issue by EmiyaYang** [antvis/X6#845]
[X6示例](https://x6.antv.vision/en/examples/layout/general#force) | [G6示例](https://g6.antv.vision/zh/examples/net/forceDirected#forceDirectedFunctionalParams)

G6 是这样监听的，那么换到 X6 要怎么实现呢？

```js
    graph.on('node:dragstart', function (e) {
      graph.layout();
      refreshDragedNodePosition(e);
    });
    graph.on('node:drag', function (e) {
      refreshDragedNodePosition(e);
    });
    graph.on('node:dragend', function (e: any) {
      e.item.get('model').fx = null;
      e.item.get('model').fy = null;
    });

```

### Expected Behavior

在力导向布局里，拖动任一节点能触发重新布局，

**Comment by NewByVector** [comment]
尝试过在 `graph.on('node:move')` 事件中处理，效果不是很好。有这块的业务场景吗？
