### ISSUE TITLE
使用dagre布局时，已经写在异步操作里了，但是当数据上千条时，布局时间仍过长

### ISSUE THREAD

**Issue by chengzizhi00** [antvis/X6#847]
使用dagre布局时，已经写在异步操作里了，但是当数据上千条时，布局时间仍过长，还有什么 优化方案吗？

**Comment by BrunaDeLafel** [comment]
> 使用dagre布局时，已经写在异步操作里了，但是当数据上千条时，布局时间仍过长，还有什么 优化方案吗？

我在项目中遇到过类似的问题，建议在循环中，尽量不要使用node.position和edge.setVertices类似的API，执行时间很长。方案是将dagre给到的节点，线的位置信息，存在一个数组，最后统一反序列化一下（graph.fromJSON）

**Comment by chengzizhi00** [comment]
> > 使用dagre布局时，已经写在异步操作里了，但是当数据上千条时，布局时间仍过长，还有什么优化方案吗？
> 
> 我在项目中遇到过类似的问题，建议在循环中，尽量不要使用node.position和edge.setVertices类似的API，执行时间很长。一个数组，最后统一反序列化一下（graph.fromJSON）

你好，麻烦再问一下，因为我的数据里边没有给节点x,y坐标，就是通过这二个api来计算给出的坐标位置，那还有其他的方式计算坐标吗，

**Comment by BrunaDeLafel** [comment]
> > > 使用dagre布局时，已经写在异步操作里了，但是当数据上千条时，布局时间仍过长，还有什么优化方案吗？
> > 
> > 
> > 我在项目中遇到过类似的问题，建议在循环中，尽量不要使用node.position和edge.setVertices类似的API，执行时间很长。一个数组，最后统一反序列化一下（graph.fromJSON）
> 
> 你好，麻烦再问一下，因为我的数据里边没有给节 点 x,y坐标，就是通过这二个api来计算给出的坐标位置，那还有其他的方式计算坐标吗，

你的代码就是用node.position和setVertices来进行计算的吗？X6我记得应该没有别的方式吧，建议节点数据量很大的时候，建议不要用这两个API，耗时比较长，建议统一fromJSON

**Comment by NewByVector** [comment]
@chengzizhi00 建议先布局计算好位置后，统一 `fromJSON` 渲染。如果布局计算耗时，可以将计算逻辑放到 `worker` 中。布局计算可以参考这个 [demo](https://codesandbox.io/s/layout-data-qlkg8)
