### ISSUE TITLE
dager布局时，为什么现有节点的位置会变，本来节点顺序是1.2.3，当新增节点后，需要重新布局，然后节点就会变成132

### ISSUE THREAD

**Issue by chengzizhi00** [antvis/X6#849]
dager布局时，为什么现有节 点 的位置排序会变，本来现有节点的顺序是1.2.3，当新增节点后，需要重新布局一次，然后节点位置就会变成1.3.2。这个dager的布局规则是什么呀，

**Comment by BrunaDeLafel** [comment]
> dager布局时，为什么现有节 点 的位置排序会变，本来现有节点的顺序是1.2.3，当新增节点后，需要重新布局一次，然后节点位置就会变成1.3.2。这个dager的布局规则是什么呀，

https://www.yuque.com/antv/g6-blog/xxp5nl参考这篇文章，dagre布局的原理

**Comment by chengzizhi00** [comment]
那有没有什么办法可以避免现在的情况呀，其实也没进行什么操作，就是新增了子节点，

**Comment by NewByVector** [comment]
@chengzizhi00 有 demo 看下吗？

**Comment by BrunaDeLafel** [comment]
> 那有没有什么办法可以避免现在的情况呀，其实也没进行什么操作，就是新增了子节点，

关注下dagre算法同层级节点防交叉部分

**Comment by xinzi1990** [comment]
楼主，解决了吗？

**Comment by taojiangcb** [comment]
我们把 钉钉 & 宜搭 的有向无环流程图用 x6 复刻实现了，但是在排布布局碰到了瓶颈。
1. 布局会有抖动 和这个问题类似。
2. 第二问题不好用文字描述， 分支节点 在不等高的情况下，节点对齐时底部优先。

**Comment by NewByVector** [comment]
@taojiangcb 可以新提一个 issue

**Comment by ripeBoy** [comment]
所以有什么解决方案吗

**Comment by thinkmix** [comment]
请问这种问题怎么解决
