### ISSUE TITLE
对于Node的编辑操作，Delete键删除contenteditable内容时候，会把Node一起删掉？

### ISSUE THREAD

**Issue by beyond-life-flux** [antvis/X6#850]
对于编辑状态下的删除键也绑定了对Node删除的操作，这两个行为冲突了，我觉得应该默认优先内容编辑。

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by jasonhu-crypto** [comment]
`graph.bindKey('backspace', () => {
    const cells = graph.getSelectedCells();
    if (cells.length) {
      const cell = cells[0];
      if ((((cell as any).store.data.tools || {}).items || []).length) {
        // 处于编辑状态
        return;
      }
    }
    if (cells.length) {
      graph.removeCells(cells);
    }
  });

  graph.on('cell:dblclick', ({ cell, e }) => {
    const isNode = cell.isNode();
    const name = cell.isNode() ? 'node-editor' : 'edge-editor';
    cell.removeTool(name);
    cell.addTools({
      name,
      args: {
        event: e,
        attrs: {
          backgroundColor: isNode ? '#EFF4FF' : '#FFF',
        },
      },
    });
  });`
