### ISSUE TITLE
在边上同时添加单击、双击和右击事件，双击事件会不时失效

### ISSUE THREAD

**Issue by noirlyrik** [antvis/X6#853]
节点同时有单击拖拽边，双击编辑标签和右击删除边的选项。

mouseenter事件与click事件冲突；单击事件会使双击事件不容易触发。

请问怎么处理比较好？

codesandbox: https://codesandbox.io/s/youthful-sanne-snovg?file=/src/app.tsx

**Comment by NewByVector** [comment]
@noirlyrik 可以使用这种方式: https://codesandbox.io/s/many-tools-42yiv

**Comment by noirlyrik** [comment]
> @noirlyrik 可以使用这种方式: https://codesandbox.io/s/many-tools-42yiv

非常感谢！不过我已经将其中两个功能都放到右键菜单里了，也可以解决冲突问题。
