### ISSUE TITLE
如何使用vue渲染连接桩？

### ISSUE THREAD

**Issue by social-uni** [antvis/X6#864]
官网的例子是使用react实现的，使用vue该如何实现呢？

const graph = new Graph({
  container: this.container,
  onPortRendered(args) {
    const selectors = args.contentSelectors
    const container = selectors && selectors.foContent
    if (container) {
      ReactDOM.render(
        <Tooltip title="port">
          <div className="my-port" />
        </Tooltip>,
        container,
      )
    }
  },
})

**Comment by social-uni** [comment]
https://antv-x6.gitee.io/zh/docs/tutorial/advanced/react#%E6%B8%B2%E6%9F%93%E9%93%BE%E6%8E%A5%E6%A1%A9

**Comment by NewByVector** [comment]
建议使用 svg 来渲染连接桩，如果用 vue，可以使用以下方式：
```ts
const instance = new Vue({
  el: `<div>11<div>`,
})
container.appendChild(instance.$el)
```

**Comment by social-uni** [comment]
> 建议使用 svg 来渲染连接桩，如果用 vue，可以使用以下方式：
> 
> ```ts
> const instance = new Vue({
>   el: `<div>11<div>`,
> })
> container.appendChild(instance.$el)
> ```

好的谢谢

**Comment by LZCaaT** [comment]
> > 建议使用 svg 来渲染连接桩，如果用 vue，可以使用以下方式：
> > ```ts
> > const instance = new Vue({
> >   el: `<div>11<div>`,
> > })
> > container.appendChild(instance.$el)
> > ```
> 
> 好的谢谢



> 建议使用 svg 来渲染连接桩，如果用 vue，可以使用以下方式：
> 
> ```ts
> const instance = new Vue({
>   el: `<div>11<div>`,
> })
> container.appendChild(instance.$el)
> ```





> 



> 
请问vue渲染连接桩具体怎么做呢
![image](https://user-images.githubusercontent.com/28329423/143986459-9df69291-e1f5-4578-8917-e1754533bdd0.png)
![image](https://user-images.githubusercontent.com/28329423/143986518-408dad51-7393-4ce1-9aa1-d20f6aae1eb4.png)
