### ISSUE TITLE
如何保证被可扩展（父子节点1）影响的父子节点一起移动且保持相对位置

### ISSUE THREAD

**Issue by cherry-web** [antvis/X6#870]
两个相邻的父子节点，都具备子节点可扩展父节点{x,y,width,height}，且两个父节点之间的{x,y,width,height}相互影响，如其中一组子节点扩展父节点时，父节点边框超过另一组父节点边框，此时如何操作才能保证被影响的父子节点一起移动且保持相对位置？

**Comment by NewByVector** [comment]
@cherry-web  监听 `node:change:position` 事件，当一个父节点位置修改时，动态修改另一个父节点位置。

**Comment by cherry-web** [comment]
那另外一个父节点中的子节点呢？如何保证该子节点与父节点有一个相对位置，共同移动？

**Comment by cherry-web** [comment]
@NewByVector 是通过监听实现修改相邻父节点的{x,y,width,height}的，但是我想请教的是这两个父节点中的子节点如何与其父节点保持相对位置，共同移动，还得有父子关系，刚接触x6，不知道这个怎么解决

**Comment by NewByVector** [comment]
position 支持相对偏移位置：https://x6.antv.vision/zh/docs/api/model/node#position-1
