### ISSUE TITLE
【急】请问有手动创建连线，并且能高亮锚点的例子吗，无法实现就要改需求了

### ISSUE THREAD

**Issue by social-uni** [antvis/X6#871]
参照这个例子写了个，手动创建连线的功能，可是发现无法高亮锚点。如果这个功能无法实现，就能改需求了，但感觉这种方式比较好，用户体验好

https://antv-x6.gitee.io/zh/examples/interaction/edge#create

请问有办法解决吗

**Comment by NewByVector** [comment]
https://x6.antv.vision/zh/examples/showcase/practices#validate-connection

**Comment by social-uni** [comment]
> https://x6.antv.vision/zh/examples/showcase/practices#validate-connection

您好，您这个是基于锚点连线的，当然是可以的，我说的是通过js自己创建一条线，就这个链接里这种方式
https://antv-x6.gitee.io/zh/examples/interaction/edge#create

**Comment by social-uni** [comment]
我在解释下为什么会有这个需求吧，主要原因就是锚点范围小，不好选择， 我们的设置是想，在table一行内右半部分就可以开始连线，这样连线操作比较容易。

如果把锚点变大，也会存在几个问题，我们设计让锚点在table内部，太大会覆盖内容，还比较丑，不连线的时候可以隐藏，连线时在table内部展示的话，如果已有连线，就会导致位置偏移，也比较丑。所以才想的这种手动创建连线的方式
