### ISSUE TITLE
是否可以支持配置锚点大小以及配置锚点禁用一些锚点的默认?

### ISSUE THREAD

**Issue by wejilamb** [antvis/X6#878]
### Expected Behavior
1. 期望支持通过参数配置锚点的大小,或者鼠标靠近时可以看到一个更大的锚点.
![image](https://user-images.githubusercontent.com/53458193/115055017-85a04400-9f13-11eb-8b91-96295945ed72.png)
2. 期望可以控制某些锚点就作为起始/结束锚点
  - 例如:A仅能作为起始锚点,B只能作为结束锚点
![image](https://user-images.githubusercontent.com/53458193/115056788-d31db080-9f15-11eb-8621-8492e3f7e403.png)

**Comment by NewByVector** [comment]
参考这个 demo：https://codesandbox.io/s/port-connection-2bb2i

**Comment by wejilamb** [comment]
@NewByVector 感谢老哥的帮助🌹🌹!!
