### ISSUE TITLE
React组件节点，画布渲染出现异常

### ISSUE THREAD

**Issue by BrunaDeLafel** [antvis/X6#880]
![image](https://user-images.githubusercontent.com/40431920/115106629-7fa07680-9f98-11eb-9fd8-9b56db7260c6.png)
![image](https://user-images.githubusercontent.com/40431920/115106698-d9a13c00-9f98-11eb-8dda-90772fd3dd61.png)
![image](https://user-images.githubusercontent.com/40431920/115106720-ea51b200-9f98-11eb-98b4-1f10a281880a.png)

x6: [^1.18.4]
OS: [macOS Big Sur 11.2.2]
Browser: [chrome 90.0.4430.72]

**Comment by BrunaDeLafel** [comment]
问了antv x6相关的人，foreignObject相关的浏览器bug，我close了，不过感觉这块有点被坑了

**Comment by haolic** [comment]
有没有解决方案老哥?

**Comment by haolic** [comment]
![D8E2818D-B2C4-406D-8902-3DD838706216](https://user-images.githubusercontent.com/29769647/115505237-b386df00-a2ab-11eb-9b6e-cd3e43b9dedf.png)
