### ISSUE TITLE
扩展GROUP展开/折叠父节点

### ISSUE THREAD

**Issue by cherry-web** [antvis/X6#882]
展开/折叠父节点，子节点。组成父子关系，如何实现子节点移动到GROUP展开/折叠父节点边缘，超出边缘，扩展GROUP展开/折叠父节点,对于群组来说，不知道如何实现子元素扩展父元素

**Comment by NewByVector** [comment]
看下这个 demo：https://x6.antv.vision/zh/examples/node/group#expand-shrink

**Comment by cherry-web** [comment]
`export class NodeGroup extends Node {
  // private collapsed: boolean = true

  // protected
  postprocess() {
    this.collapsed = true
    this.toggleCollapse(true)
  }

  isCollapsed() {
    return this.collapsed
  }

  toggleCollapse(collapsed) {
    const target = collapsed == null ? !this.collapsed : collapsed
    if (target) {
      this.attr('buttonSign', { d: 'M 1 5 9 5 M 5 1 5 9' })
      this.resize(200, 40)
    } else {
      this.attr('buttonSign', { d: 'M 2 5 8 5' })
      this.resize(240, 240)
    }
    this.collapsed = target
  }
}

NodeGroup.config({
  shape: 'rect',
  markup: [
    {
      tagName: 'rect',
      selector: 'body'
    },
    {
      tagName: 'image',
      selector: 'image'
    },
    {
      tagName: 'text',
      selector: 'text'
    },
    {
      tagName: 'g',
      selector: 'buttonGroup',
      children: [
        {
          tagName: 'rect',
          selector: 'button',
          attrs: {
            'pointer-events': 'visiblePainted'
          }
        },
        {
          tagName: 'path',
          selector: 'buttonSign',
          attrs: {
            fill: 'none',
            'pointer-events': 'none'
          }
        }
      ]
    }
  ],
  attrs: {
    body: {
      refWidth: '100%',
      refHeight: '100%',
      strokeWidth: 1,
      fill: 'rgba(95,149,255,0.05)',
      stroke: '#5F95FF'
    },
    image: {
      'xlink:href': 'https://gw.alipayobjects.com/mdn/rms_0b51a4/afts/img/A*X4e0TrDsEiIAAAAAAAAAAAAAARQnAQ',
      width: 16,
      height: 16,
      x: 8,
      y: 12
    },
    text: {
      fontSize: 12,
      fill: 'rgba(0,0,0,0.85)',
      refX: 30,
      refY: 15
    },
    buttonGroup: {
      refX: '100%',
      refX2: -25,
      refY: 13
    },
    button: {
      height: 14,
      width: 16,
      rx: 2,
      ry: 2,
      fill: '#f5f5f5',
      stroke: '#ccc',
      cursor: 'pointer',
      event: 'node:collapse'
    },
    buttonSign: {
      refX: 3,
      refY: 2,
      stroke: '#808080'
    }
  }
})

Graph.registerNode('flowGroupNode', NodeGroup)`
请问这种节点，如何重新设置{x,y,width,height},我知道`parent.prop(
                        {
                            position: { x, y },
                            size: { width: cornerX - x, height: cornerY - y },
                        }
                    )`这样修改，但上面的节点不知道怎样更改对应的值，

**Comment by cherry-web** [comment]
是我写错了，可以用prop来更改节点的{x,y,width,height},谢谢您的回复
