### ISSUE TITLE
画布拖拽功能和节点移动功能冲突

### ISSUE THREAD

**Issue by OpportunityLiu** [antvis/X6#883]
### Expected Behavior

当启用画布拖拽功能时，无法在节点上进行拖拽操作移动画布，即使为 scroller 设置了 modifiers 也会进行节点移动操作

### Possible Solution

当设置了 modifiers 时，即使在节点上进行拖拽，也应该进行画布拖拽操作而非节点移动操作。

如果能将画布拖拽功能放到鼠标中键或右键上就更好了。

### Additional Context

在搭建复杂模型的时候，会使用分组功能将节点放到几个大的父节点中，这些节点的尺寸经常超过一屏的大小，导致无法进行拖拽操作。

**Comment by NewByVector** [comment]
我在这里开了一个 Discussions，可以把这块需求拿出来讨论。
