### ISSUE TITLE
自定义链接桩和数据一一对应

### ISSUE THREAD

**Issue by frienkiss** [antvis/X6#889]
x6的自定义节点，链接桩能否跟数据一一对应，并且可随数据滚动
参考G6 ：https://g6.antv.vision/zh/examples/case/simpleCase#ER   节点内容可滚动的ER图

![image](https://user-images.githubusercontent.com/28303439/115505234-b2ee4880-a2ab-11eb-84a0-162612fac70a.png)

**Comment by NewByVector** [comment]
可以参考这个 demo：https://github.com/antvis/X6/tree/master/examples/x6-example-features/src/pages/react/table

**Comment by frienkiss** [comment]
好的，我研究下，麻烦了
