### ISSUE TITLE
updateData 触发重绘后，HTML节点中 img 闪烁，如何处理？

### ISSUE THREAD

**Issue by 905868332** [antvis/X6#895]
updateData 触发重绘后，HTML节点中 img 闪烁，如何处理？

**Comment by NewByVector** [comment]
因为要重新渲染，html 中 img 会重新加载绘制，可以使用 base64 图片

**Comment by 905868332** [comment]
> 因为要重新渲染，html 中 img 会重新加载绘制，可以使用 base64 图片

还有没有别的方法了

**Comment by OpportunityLiu** [comment]
直接上service worker，一劳永逸，一堆重复加载的问题全解决了

**Comment by NewByVector** [comment]
@905868332  但是我验证了一下，并没有出现图片闪烁问题：https://codesandbox.io/s/html-node-drb8n

**Comment by 905868332** [comment]
> @905868332 但是我验证了一下，并没有出现图片闪烁问题：https://codesandbox.io/s/html-node-drb8n

我这边的处理逻辑是这样的，节点是 html的，html 中的 img 的 src 是取的 data中的一个值
你这个是个固定的字符串，和 data 没有关联，是因为这个原因吗。
我刚把 F12 打开后，图片就开始一直闪烁了，和这个是不是也有关系，我开发的时候F12是一直打开的状态，等我再去试一下把F12关掉看看是否闪烁
~

**Comment by 905868332** [comment]
> @905868332 但是我验证了一下，并没有出现图片闪烁问题：https://codesandbox.io/s/html-node-drb8n

关闭F12就不闪烁了，解决了

**Comment by Eve-Sama** [comment]
我也遇到了, 使用html渲染的Node. 最后使用base64解决的.
