### ISSUE TITLE
showEdgeSelectionBox属性不生效

### ISSUE THREAD

**Issue by social-uni** [antvis/X6#899]
启用了rubberband，使用了showEdgeSelectionBox 属性，想要框选线，不生效

开启 showNodeSelectionBox 就可以框选节点

**Comment by OpportunityLiu** [comment]
线目前应该只能点击选中，ctrl+点击多选，框选的时候用的那个 `findViewsInArea` 方法压根就不返回 edge view，名字很误导

https://github.com/antvis/X6/blob/49ae52af207ae43eb5ea0d5bfc141ad36f19e78e/packages/x6/src/addon/selection/index.ts#L499-L511


https://github.com/antvis/X6/blob/49ae52af207ae43eb5ea0d5bfc141ad36f19e78e/packages/x6/src/graph/renderer.ts#L1149-L1168
