### ISSUE TITLE
直接下载流程图示例代码，安装包时报错

### ISSUE THREAD

**Issue by xiaorunbao** [antvis/X6#900]
https://github.com/antvis/X6/blob/master/examples/x6-app-draw/package.json
示例中引用的 @antv/x6-react-components 找不到对应版本。

目前下载的最新版本是 1.1.7

**Comment by wtzeng1** [comment]
@xiaorunbao 可以先 `git clone` 整个项目的源码，之后 `yarn bootstrap` 再启动 example 中的项目
