### ISSUE TITLE
设置智能路由后，当边重叠时，是否可以只展示一条边

### ISSUE THREAD

**Issue by wkz18895356792** [antvis/X6#901]
![image](https://user-images.githubusercontent.com/32668278/115846288-52e6d600-a454-11eb-8873-f677db0ee6e9.png)
可以明显看到重叠的边颜色被加粗，且另外的edge直接穿过了标签

**Comment by NewByVector** [comment]
本地没有重现线重叠导致颜色加深的现象，希望你提供一个 demo。第二个遮挡 label 的问题，可以将有 label 的边 的 `zIndex` 设高一点来解决。
