### ISSUE TITLE
x6-react-components， mac 渲染不了antd table，window可以渲染antd table

### ISSUE THREAD

**Issue by itotoo** [antvis/X6#905]
### Steps To Reproduce

参考demo地址
http://react.liushengjie.cn/E-R

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
chrome 在 mac 下渲染兼容性问题，解决方案：https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99

![image](https://user-images.githubusercontent.com/20186737/116034267-98deac80-a695-11eb-853c-37cd6e566d48.png)
