### ISSUE TITLE
dagreLayout demo 提示Not possible to find intersection inside of the rectangle

### ISSUE THREAD

**Issue by social-uni** [antvis/X6#906]
项目数据，使用 https://antv-x6.gitee.io/zh/docs/tutorial/advanced/layout#dagre 
报错
Not possible to find intersection inside of the rectangle

**Comment by NewByVector** [comment]
业务数据和布局所需要数据不匹配，布局所需要数据格式:https://github.com/antvis/layout
如果存在不一致，可以操作这个 demo 进行转换：https://codesandbox.io/s/layout-data-qlkg8
