### ISSUE TITLE
谷歌更新之后，画布元件部分渲染失败（谷歌版本为90.0.4430.85）

### ISSUE THREAD

**Issue by duyu123** [antvis/X6#912]
![EDA37049-106C-446d-B188-5272885BCA60_LI](https://user-images.githubusercontent.com/21079129/116021426-bfdbb500-a67a-11eb-95ed-7cf20546afb7.jpg)

**Comment by NewByVector** [comment]
google 90 对 foreignObject 渲染兼容性问题： https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99
