### ISSUE TITLE
V1.18.5 ,  当创建 EdgeTool 拖住 Edge 中的节点， 然后到一个Node上，释放鼠标。 这时， 鼠标再点击NOde 无效，不能拖动， 不能产生事件 

### ISSUE THREAD

**Issue by cringha** [antvis/X6#916]
V1.18.5 ,  当创建 EdgeTool 拖住 Edge 中的节点， 然后到一个Node上，释放鼠标。 这时， 鼠标再点击NOde 无效，不能拖动， 不能产生事件 

**如下图 1 ， 鼠标左键点击，移动（不释放） ， 然后鼠标移动到  2 NOde 上， 释放鼠标左键。 
这时， 所有的Node 都不能响应鼠标事件。** 

![image](https://user-images.githubusercontent.com/1596848/116208927-f812ee80-a773-11eb-9af7-76214810a899.png)

1，  EdgeTool

```
tools: {
                items: [
                {
                    name: 'vertices',
                    args: {
                    attrs: { fill: '#666' },
                    },
                },
            ],
```

**Comment by NewByVector** [comment]
能提供一个可复现的 demo 吗，本地无法复现这个问题。
