### ISSUE TITLE
期望支持批量设置节点属性，且undo时批量恢复数据

### ISSUE THREAD

**Issue by WeiJianZhou** [antvis/X6#920]
节点配置了业务数据data，且data里的数据和节点的其他属性相关（例如attes/label/text），期望能同时修改，并且undo时同时恢复。

#### step 1：我有一个节点cell，配置了业务数据data，且期望data/nodeName与attes/label/text同步，数据如下：
```JSON
{
  "attrs": {
    "label": {
      "text":  "自定义节点A"
    } 
  },
  "data": {
    "nodeName": "自定义节点A",
    ...
  },
  ...
}
```
##### 2.1 分别修改attrs和data
```JavaScript
cell.prop('data/nodeName', "自定义节点B")
cell.attr('label/text', "自定义节点B")
```
此时的cell结构如下：
```JSON
{
  "attrs": {
    "label": {
      "text":  "自定义节点B"
    } 
  },
  "data": {
    "nodeName": "自定义节点B",
    ...
  },
  ...
}
```
##### 2.2 然后再执行一次undo操作，label已经恢复，但data没有，cell的数据如下：
```JSON
{
  "attrs": {
    "label": {
      "text":  "自定义节点A"
    } 
  },
  "data": {
    "nodeName": "自定义节点B",
    ...
  },
  ...
}
```
##### 2.3 再执行一次undo操作，得到的cell才是期望的结果：
```JSON
{
  "attrs": {
    "label": {
      "text":  "自定义节点B"
    } 
  },
  "data": {
    "nodeName": "自定义节点B",
    ...
  },
  ...
}
```
#### step 3：回到step 2，按照[常见问题中：在历史记录中忽略某个属性的修改](https://x6.antv.vision/zh/docs/tutorial/epilog#%E5%9C%A8%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95%E4%B8%AD%E5%BF%BD%E7%95%A5%E6%9F%90%E4%B8%AA%E5%B1%9E%E6%80%A7%E7%9A%84%E4%BF%AE%E6%94%B9)修改代码：
```JavaScript
new Graph({
  history: {
    enabled: true,
    beforeAddCommand(event, args: any) {
      // 忽略历史变更
      if (args.options.ignoreHistory) {
        return false
      }
    },
  },
  ...
}
cell.prop('data/nodeName', "自定义节点B", { ignoreHistory: true })
cell.attr('label/text', "自定义节点B")
```
##### 3.1 再次执行一次undo操作，依然是label恢复，data没有恢复，cell数据如下：
```JSON
{
  "attrs": {
    "label": {
      "text":  "自定义节点A"
    } 
  },
  "data": {
    "nodeName": "自定义节点B",
    ...
  },
  ...
}
```
### Possible Solution

建议提供一个批量修改节点数据的api

**Comment by OpportunityLiu** [comment]
有的，把所有操作包在一个 batch 里就可以了

https://x6.antv.vision/zh/docs/api/graph/graph#startbatch

**Comment by WeiJianZhou** [comment]
> 有的，把所有操作包在一个 batch 里就可以了
> 
> https://x6.antv.vision/zh/docs/api/graph/graph#startbatch

哦哦，的确可以，怪自己没仔细看。谢谢了~
