### ISSUE TITLE
history.executeCommand无效

### ISSUE THREAD

**Issue by WeiJianZhou** [antvis/X6#921]
设置了history.executeCommand，执行undo和redo时，并没有触发

### Expected Behavior

[demo url: https://codesandbox.io/s/reverent-solomon-zx239?file=/src/App.js:296-310](https://codesandbox.io/s/reverent-solomon-zx239?file=/src/App.js:296-310)

```JavaScript
    const graph = new Graph({
      container: document.getElementById("container"),
      grid: true,
      history: {
        enabled: true,
        executeCommand(cmd, resert, options) {
          alert("执行了executeCommand");
          console.log("executeCommand:", cmd, resert, options);
        }
      }
    });
    const rect = graph.createNode({
      shape: "rect",
      position: { x: 100, y: 100 },
      size: { width: 100, height: 100 }
    });
    graph.addNode(rect);
    setTimeout(() => {
      // 2s后执行撤回
      graph.undo();
    }, 2000);
```

### Current Behavior

执行undo和redo操作时，没有触发executeCommand

**Comment by OpportunityLiu** [comment]
这个钩子是用来处理 History 插件本身不支持的操作的，支持的操作（`cell:add`、`cell:remove`、`cell:change:*`）它自己内部就处理了。

要监控这些操作应该使用对应的事件 https://x6.antv.vision/zh/docs/api/graph/history#undo-1

**Comment by WeiJianZhou** [comment]
> 这个钩子是用来处理 History 插件本身不支持的操作的，支持的操作（`cell:add`、`cell:remove`、`cell:change:*`）它自己内部就处理了。
> 
> 要监控这些操作应该使用对应的事件 https://x6.antv.vision/zh/docs/api/graph/history#undo-1

好的，谢谢
