### ISSUE TITLE
如何在Vue组件中使用Vuex？

### ISSUE THREAD

**Issue by IATF** [antvis/X6#930]
Graph.registerVueComponent注册的Vue组件中需要使用store来动态更新自定义的Node，但是直接在组件中使用this.$store行不通，我应该怎么做才行？

**Comment by NewByVector** [comment]
节点组件不支持 vuex

**Comment by IATF** [comment]
如果想在Vue组件中监听node data变化而更新Vue组件内容，有什么解决办法吗？或者文档可以参考吗？

**Comment by NewByVector** [comment]
可以看下这个 demo：https://codesandbox.io/s/change-vue-style-747ys?file=/src/components/Count.vue

**Comment by IATF** [comment]
感谢！这个demo非常好，解决了我的问题。
在Vue组件中通过监听change:data来监听node的data数据变化，达到了当node数据发生变化的时候同步更新Vue组件的效果。

另外说明一下，一开始`node`的`data`修改时我没有使用`node.setData()`来更改node数据，这种情况下`change:data`是监听不到数据变化的，所以如果要实现想要的效果需要使用`node.setData`来更新node数据data
