### ISSUE TITLE
Add `contextMenuThreshold` options

### ISSUE THREAD

**Issue by OpportunityLiu** [antvis/X6#942]
### Expected Behavior
Add `contextMenuThreshold` options, like `clickThreshold`, to prevent unwanted contextmenu events.

### Additional Context

After #940 merged, right mouse button has dragging handlers, which will affect context menu handlers.

**Comment by NewByVector** [comment]
如果需要实现这个的话 contextmenu 事件需要使用 mousedown 事件来模拟了，这个我加入讨论区，讨论一下

**Comment by OpportunityLiu** [comment]
挺好的，也能更好的配合选中状态相应键盘触发的contextmenu

**Comment by OpportunityLiu** [comment]
please keep it open

**Comment by OpportunityLiu** [comment]
好像也并不会把stale标签去掉啊。。。

**Comment by OpportunityLiu** [comment]
please keep it open
