### ISSUE TITLE
x6-vue3-shape enable to render Vue3 components

### ISSUE THREAD

**Issue by Abbyzhoum** [antvis/X6#958]
### Description
Added x6-vue3-shape code to enable X6 to render Vue3 components, like element-plus
demo Link：  [https://codesandbox.io/s/infallible-pine-nig00?file=/src/main.js](url)

ui style  is not displayed properly, console panel prompt : `[Vue warn]: Failed to resolve component: el-button `

### Types of changes

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [ x]   New feature (non-breaking change which adds functionality)
 - [ ]  Breaking change (fix or feature that would cause existing functionality to change)
 - [ ]  Enhancement (changes that improvement of current feature or performance)
- [ ]   Refactoring (changes that neither fixes a bug nor adds a feature)
 - [ ]  Test Case (changes that add missing tests or correct existing tests)
 - [ ]  Code style optimization (changes that do not affect the meaning of the code)
 - [ ]  Docs (changes that only update documentation)
 - [ ]  Chore (changes that don't modify src or test files)

**Comment by NewByVector** [comment]
Component provided template option but runtime compilation is not supported in this build of Vue. Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js"

**Comment by Abbyzhoum** [comment]
Where and how to configure？

**Comment by NewByVector** [comment]
存在重复 issue：https://github.com/antvis/X6/issues/968
