### ISSUE TITLE
[Issue]: embedding 和 selecting 冲突

### ISSUE THREAD

**Issue by tiancihe** [antvis/X6#962]
https://codesandbox.io/s/jovial-hill-6hgtr?file=/index.js

同时启用 embedding 和 selecting 会出现多个问题：

1. 选中父节点后，无法点选其内部的子节点
2. 选中子节点后，将其拖拽出父节点，没有正确触发 change:parent 事件，且不会高亮显示父节点
3. 选中多个节点并拖拽，也无法正常保证父子关系

预期的行为应该是选中与否不应影响父子关系的调整

**Comment by tiancihe** [comment]
此外被选中的节点移动时也不会遵循 translating.restrict 规则

**Comment by OpportunityLiu** [comment]
> 此外被选中的节点移动时也不会遵循 translating.restrict 规则

是的，只有正在拖的那个节点会受控，跟着动的节点就放飞自我了

**Comment by tiancihe** [comment]
> > 此外被选中的节点移动时也不会遵循 translating.restrict 规则
> 
> 是的，只有正在拖的那个节点会受控，跟着动的节点就放飞自我了

所以这是 feature 还是 bug

**Comment by tiancihe** [comment]
另外选中的节点拖拽也不会触发 node:move node:moving node:moved 事件

**Comment by NewByVector** [comment]
增加了 `pointerEvents: 'none'` 配置，解决你上面提的所有问题

**Comment by tiancihe** [comment]
> 增加了 `pointerEvents: 'none'` 配置，解决你上面提的所有问题

设置 pointerEvents: 'none' 并不能很好地解决问题，SelectionBox是需要的，能够支持选中父节点后，在任意位置进行拖拽

**Comment by NewByVector** [comment]
如果要实现你这个功能，可以使用你之前的方式，通过位置找到对应元素来实现，x6 内部先不实现，后面会对这一块进行重构。
