### ISSUE TITLE
群组在折叠状态时，拆分群组，会删除群组内的所有node

### ISSUE THREAD

**Issue by mqbmeng** [antvis/X6#963]
1.  新建群组
2. 折叠群组
3. 拆分群组

预期结果： 群组拆分
实际结果： 群组内所有node被删除

**Comment by NewByVector** [comment]
提供一个 demo 看下？

**Comment by mqbmeng** [comment]
https://x6.antv.vision/apps/dag   这个示例demo里就可以复现

**Comment by mqbmeng** [comment]
> 提供一个 demo 看下？
https://x6.antv.vision/apps/dag 这个示例demo里就可以复现

**Comment by NewByVector** [comment]
@mqbmeng 这个示例 demo 不支持折叠群组吧？
