### ISSUE TITLE
dnd 文档优化，自定义拖拽图形样式

### ISSUE THREAD

**Issue by NewByVector** [antvis/X6#967]
### Expected Behavior

优化 dnd 文档，支持自定义拖拽、放置图形样式

**Comment by aBuBili** [comment]
我实现了 1- 从旁边一侧拖拽进去 使用的左侧是div 原生的drag 然后根据 拖拽结束后的坐标 计算出应该在x6的坐标实现的 = - =
2- 可以把image作为节点 我是抄的它源码的组合的那部分代码 实现的 
如果想要详细的代码 可以联系我 邮箱 1669640473@qq.com 我私发给你 = - =
