### ISSUE TITLE
x6-vue3-shape 不能正常渲染element-plus 样式

### ISSUE THREAD

**Issue by Abbyzhoum** [antvis/X6#968]
### 描述：

所使用的框架：vue3，element-plus，需要的功能:  定制化渲染 vue 节点时, 如el-button(vue3)等， element-plus 样式不显示

示例链接：[https://codesandbox.io/s/infallible-pine-nig00?file=/src/main.js](url)

Types of changes
 -  Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 -   Breaking change (fix or feature that would cause existing functionality to change)
-   Enhancement (changes that improvement of current feature or performance)
-   Refactoring (changes that neither fixes a bug nor adds a feature)
 - [x] Test Case (changes that add missing tests or correct existing tests)
 -  Code style optimization (changes that do not affect the meaning of the code)
 - [x]  Docs (changes that only update documentation)
 -  Chore (changes that don't modify src or test files)

### 渲染 vue节点  -文档说明需增加：
请在X6 渲染 vue节点中 增加 vue3 与 组件库的demo，组件库如element-plus 或 ant design vue 

![image](https://user-images.githubusercontent.com/38661489/117748925-7925b780-b243-11eb-89e9-3544d5371e45.png)

**Comment by NewByVector** [comment]
vue3 支持还有问题，和 https://github.com/antvis/X6/issues/1165 重复，先关闭。

**Comment by a47781402** [comment]
vue3 在自定义的vue节点中，要使用ant design vue的ui控件，需要重新按需导入，才能使用
![WX20220803-164724](https://user-images.githubusercontent.com/35242745/182566128-2ad5a693-1091-4c30-a529-19275d5c37b6.png)
