### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by afc163** [antvis/X6#97]
使用 jQuery 性价比太低。

**Comment by bubkoo** [comment]
目前依赖的 jQuery 特性：
-  Dom 事件
- data 方法
- style 方法
- attr 方法

去掉 jQuery 的话，要把这些方法重新实现。或者自己打包一个简单版本的 jQuery 来减少文件大小。

**Comment by afc163** [comment]
直接用 DOM 原生的就好，改造成本应该不高。

**Comment by JohnTao** [comment]
确实 ，去掉以后说不定和easyui 或者layui 就不冲突了

**Comment by Eve-Sama** [comment]
有预计完成时间吗?

**Comment by NewByVector** [comment]
@wflixu 去除 jquery 还有一段时间，有没有 le5le-com/topology和 antv/x6 的对比报告呢？🤒

**Comment by Eve-Sama** [comment]
> 希望官方能提高优先级，目前做产品方案调研，备选方案le5le-com/topology和 antv/x6 ，本来是更倾向于x6，但看到依赖jQuery，我们可能要用 le5le-com/topology

之前我也看过这个le5le的方案, 最终我们选择的X6. 作为过来人, 我只能说, X6的官网写的非常好, 很利于推进项目.

**Comment by kiki-oo** [comment]
> @wflixu 去除 jquery 还有一段时间，有没有 le5le-com/topology和 antv/x6 的对比报告呢？🤒

400个节点，fps只有15，看到jquery里面curCss耗时较长，有没有啥办法自己先优化一下。本人不是专业前端o(╥﹏╥)o

**Comment by wflixu** [comment]
> @wflixu 去除 jquery 还有一段时间，有没有 le5le-com/topology和 antv/x6 的对比报告呢？🤒

有一个汇报时的简单总结，算是使用感受吧，最近尝试了3个库，我们计划用G6。 

![image](https://user-images.githubusercontent.com/37231473/141444678-90b2b8e2-ca32-4fe5-83de-379c8022749e.png)

**Comment by wflixu** [comment]
> > @wflixu 去除 jquery 还有一段时间，有没有 le5le-com/topology和 antv/x6 的对比报告呢？🤒
> 
> 400个节点，fps只有15，看到jquery里面curCss耗时较长，有没有啥办法自己先优化一下。本人不是专业前端o(╥﹏╥)o

感觉这个自己优化，工作量太大了，其实g6 用canvas 渲染的，性能还可以，想不明白都是antv家族，为什么不在g6的基础上做

**Comment by NewByVector** [comment]
@wflixu 感谢你的报告，我们后面会持续优化。关于为什么使用 svg，是因为 x6 面向的场景是节点内容比较复杂的图编辑场景，使用 svg 更加容易上手。

**Comment by lijing666** [comment]
持续等待去掉jquery的版本，本来也选定了x6，突然发现有jquery依赖，有点懵逼，现在很犹豫。。。。。。

**Comment by caozhong1996** [comment]
感觉可以参考下这篇文章，如果你没有看过的话
https://mp.weixin.qq.com/s?__biz=MzUxMzcxMzE5Ng==&mid=2247489496&idx=1&sn=ec3d379d62e80991858055c42ea298ae&chksm=f951a29bce262b8dbcdffe5e8800f0917602f7257b733c0ab84e95f0146d2aa9db2116f3c54c&token=1416664194&lang=zh_CN#rd

**Comment by gz65555** [comment]
两年了，来看看进展怎么样。

**Comment by NewByVector** [comment]
@gz65555 ^_^ 2.0 分支已经去掉了，但是还在做其他优化。

**Comment by NewByVector** [comment]
2.0 版本已经去除。
