### ISSUE TITLE
如果同一页有多个图表，在其中一个执行粘贴命令，在其他图也会触发。

### ISSUE THREAD

**Issue by dzut** [antvis/X6#970]
![image](https://user-images.githubusercontent.com/9347499/117810479-098ae900-b292-11eb-8597-663f7b7bb69f.png)
在同时存在多个实例时，根据这个现象，应该其他事件也会传递，需要检测当前激活的是哪个图。

**Comment by NewByVector** [comment]
能提供一个复现的 codesanbox 吗，我在本地测试没有复现你的问题，测试代码：https://codesandbox.io/s/graphs-copy-rdvc4
