### ISSUE TITLE
@antv/x6-react-components 1.1.9版本没发布到npm平台

### ISSUE THREAD

**Issue by SmileLifeIven** [antvis/X6#974]
安装@antv/x6-react-components 1.1.9 失败，最新的只有1.1.7

### Expected Behavior

将新版本发布到npm平台

### Steps To Reproduce

npm i @antv/x6-react-components

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @antv/x6-react-components@^1.1.9.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Your Environment
- @antv/x6-app-draw: [1.1.4]

**Comment by SmileLifeIven** [comment]
执行命令
$ npm i @antv/x6-react-components@latest

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @antv/x6-react-components@1.1.7 requires a peer of antd@>=4.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN @antv/x6-react-components@1.1.7 requires a peer of react@>=16.8.6 || >=17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @antv/x6-react-components@1.1.7 requires a peer of react-dom@>=16.8.6 || >=17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-dropdown@3.2.0 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN rc-dropdown@3.2.0 requires a peer of react-dom@* but none is installed. You must install peer dependencies yourself.
npm WARN react-color@2.19.3 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN react-resize-detector@6.7.1 requires a peer of react@^16.0.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-resize-detector@6.7.1 requires a peer of react-dom@^16.0.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-trigger@5.2.7 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-trigger@5.2.7 requires a peer of react-dom@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-util@5.12.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-util@5.12.2 requires a peer of react-dom@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-motion@2.4.3 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-motion@2.4.3 requires a peer of react-dom@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-util@5.12.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-util@5.12.2 requires a peer of react-dom@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-align@4.0.9 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-align@4.0.9 requires a peer of react-dom@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-util@5.12.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-util@5.12.2 requires a peer of react-dom@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN @icons/material@0.2.4 requires a peer of react@* but none is installed. You must install peer dependencies yourself.

+ @antv/x6-react-components@1.1.7
added 35 packages from 146 contributors and audited 35 packages in 18.622s


最新只有1.1.7

**Comment by NewByVector** [comment]
已经发布最新的 1.1.10
