### ISSUE TITLE
x6图表示例问题

### ISSUE THREAD

**Issue by Devilzhaozheng** [antvis/X6#978]
图表示例里的 展开/折叠树 在 Macbook Pro 里边打不开，崩溃。浏览器为Chrome

**Comment by NewByVector** [comment]
国内站点吗

**Comment by NewByVector** [comment]
应该是国内镜像没有同步，我同步一下

**Comment by NewByVector** [comment]
谢谢反馈，已经修复！

**Comment by Devilzhaozheng** [comment]
![image](https://user-images.githubusercontent.com/58406871/118449616-eba40500-b725-11eb-88b5-01614ffed725.png)
您好，是国内站点。刚刚我刷新试了试还不行呀

**Comment by NewByVector** [comment]
已经好了 是不是本地缓存原因

**Comment by Devilzhaozheng** [comment]
嘿嘿😋好了，应该是本地缓存的事- -
