### ISSUE TITLE
在节点的port刚刚准备连线的时候就直接触发了validateConnection, 为什么不是连入的时候触发?

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/X6#980]
### Expected Behavior
当点击out port时没必要调用这个函数吧, 是否允许连出, 已经有validateMagnet做校验了不是吗?

### Current Behavior
当node的port刚刚准备连线的时候, 就触发了validateConnection, 而且里面的targetCell是相距非常远的一个节点
![image](https://user-images.githubusercontent.com/30228406/118504971-90dacf80-b75e-11eb-8f44-5b4464ec2ad8.png)
![image](https://user-images.githubusercontent.com/30228406/118505624-2aa27c80-b75f-11eb-9b41-2133251df28a.png)

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by Eve-Sama** [comment]
在只有一个节点的时候, 不会触发这个函数

**Comment by Eve-Sama** [comment]
把highlight关掉就可以了, 但我不理解这两者有啥关系?

**Comment by NewByVector** [comment]
`validateConnection` 的逻辑是拖拽边的过程中，根据 `snap` 给定的吸附范围获取该范围内的元素，然后根据 `validateConnection` 来判断是否能连接，刚准备连线的时候就触发这个函数是因为存在循环连线的场景，就是自己连自己，所以这里需要做判断。这个和 `validateMagnet ` 没有关系，`validateMagnet ` 只是用来判断是否能从当前的 magnet 拉出连线。

**Comment by Eve-Sama** [comment]
你所说的`因为存在循环连线的场景，就是自己连自己，所以这里需要做判断`, 请问如何做判断呢? 当线连出来的时候就触发了`validateConnection`, 当接近`snap`时又触发了一次`validateConnection`, 在运行时参数上好像并没有区别. 我如何知道是刚刚连出来还是即将连入时呢?

**Comment by Eve-Sama** [comment]
所以这是bug吗?

**Comment by Eve-Sama** [comment]
cell:added 事件也是一样, 按理来说, 是添加cell之后触发的, 如果cell是node, 那么添加是一瞬间的事情, 没问题. 但是如果cell是edg, 当edge被拖出的时候就已经触发了cell:added, 此时他是没有target的, 而连上了另一个节点后, 该事件并未触发.

**Comment by NewByVector** [comment]
1. validateConnection 运行参数上是有区别的，开始连线的时候 sourceCell 和 targetCell 都是自己
2. 拖出线的一刻触发 `cell:added` 是正常的，连线另一个节点后，触发 `edge:connected`
