### ISSUE TITLE
node:selected为什么只触发一次?

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/X6#984]
### Expected Behavior
每次点击node的时候都应该触发node:selected, 但是现在是必须unselected之后, 再次点击才触发, 如果在选中的状态下继续点击则不会触发这个方法. 
这是很奇怪的事情. 因为每次点击我可能去计算一些内容, 而node:selected只触发一次, 那后面就没法计算了, 必须先取消才行, 这个交互很奇怪

**Comment by NewByVector** [comment]
感觉你需要点击事件呀

**Comment by Eve-Sama** [comment]
嗯, 刚刚看了源码, 发现存在node:click事件, 我在官方文档的search input中输入没有找到, 不知道是不是官网忘记写了. 既然提供了click, 那还是说的过去的.

**Comment by Eve-Sama** [comment]
但是我发现第一次点击的时候, 只会触发selected, 那为什么第一次不顺便触发click呢?

**Comment by iceytea** [comment]
当 node 处于 selected 状态时，同样不会响应 node:click 事件

**Comment by NewByVector** [comment]
1. `node:selected` 只触发一次的逻辑是对的
2. 如果需要处理每次点击事件，可以监听 `node:click` 事件，如果开启了 `showNodeSelectionBox` 会阻止 `click` 事件的触发，此时可以通过以下样式来解决：
```tss
.x6-widget-selection-box {
  pointer-events: none;
}
