### ISSUE TITLE
支持群组鼠标事件

### ISSUE THREAD

**Issue by tgshell** [antvis/X6#986]
群组节点是否可以支持鼠标事件？

### 期望

群组作为整体，派发 group:mouseenter、group:mouseleave、group:click 事件

### 场景

群组节点在 mouseenter、mouseleave 时控制节点工具栏的展示和隐藏

**Comment by wtzeng1** [comment]
@tgshell 可以在群组节点里添加类似 `isGroup()` 的方法，之后从事件参数里拿到 cell 调用 `cell?.isGroup()` 然后进行判断
