### ISSUE TITLE
IE兼容性

### ISSUE THREAD

**Issue by east119** [antvis/X6#989]
https://x6.antv.vision/zh/docs/tutorial/epilog#%E6%80%8E%E4%B9%88%E5%85%BC%E5%AE%B9-ie
已按照常见问题中兼容IE配置
在IE11中可以正常显示，但是在连接节点时会报错
![1](https://user-images.githubusercontent.com/9639162/118901504-03f26a80-b946-11eb-8aa3-420f1d84f87b.png)

想知道x6现在还支持IE11吗？
IE不支持DOMMatrix API, x6是如何polyfill

- x6: [1.21.5]
- OS: [Windows 10 专业版  x64]
- Browser: [IE 11.0.10240.17394]

**Comment by Gilbert5210** [comment]
这个确实是个问题啊，而且ie上嵌套vue组件也存在各种兼容性问题没解决
