### ISSUE TITLE
画布包含大量React节点时，layout重新布局，重新渲染会有一小时间段空白卡顿。

### ISSUE THREAD

**Issue by BrunaDeLafel** [antvis/X6#994]
之前是没有这个问题的

但是现在不知道是升级了浏览器，foreignObject bug还是x6的版本问题
每次重新布局，React节点重新渲染时，渲染中间有一小段空白的间隔

不影响功能，但空白闪烁体验比较差
![image](https://user-images.githubusercontent.com/40431920/119122297-f41b7900-ba60-11eb-8ce9-e5d6da6ad094.png)
![image](https://user-images.githubusercontent.com/40431920/119122336-fed60e00-ba60-11eb-8731-78654f6745dd.png)

- x6: [^1.21.7]
- OS: [e.g. macOS Big Sur 11.2.3]
- Browser: [chrome 90.0.4430.212]

**Comment by BrunaDeLafel** [comment]
为什么x6-bot把关掉了？

**Comment by NewByVector** [comment]
应该是 chrome90 的兼容性问题，https://x6.antv.vision/zh/docs/tutorial/epilog#htmlreactvue%E8%8A%82%E7%82%B9%E6%B8%B2%E6%9F%93%E5%87%BA%E9%94%99 检查下是否有这些样式
