### ISSUE TITLE
Using connection ports in Dagre layout

### ISSUE THREAD

**Issue by dhiliphvenkatesan** [antvis/X6#995]
I am using Dagre layout in my project and want to connect the nodes via connection ports
### Expected Behavior

It should work If i give edges as

{
  source: { cell: 'rect1', port: 'out-port-1' },  // 源节点和链接桩 ID
  target: { cell: 'rect2', port: 'in-port-1' }, // 目标节点 ID 和链接桩 ID
}

instead of

{
  source: 'rect1'
  target: 'rect2'
}

### Current Behavior

It is throing error like type of undefined in     ** const model = dagreLayout.layout(data);**     code

### Steps To Reproduce

This is my sandbo code. https://codesandbox.io/s/quizzical-mccarthy-rb4wy?file=/src/app.tsx:1211-1230

1. ... in app.ts file go to line no: 72
2. ... give source and target as   
   source: { cell: 'rect1', port: 'out-port-1' },  // 源节点和链接桩 ID
    target: { cell: 'rect2', port: 'in-port-1' }, // 目标节点 ID 和链接桩 ID
} instead of
{
  source: 'rect1'
  target: 'rect2'
}
you'll get the error

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [Ubuntu 20]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
You can look at this demo：https://codesandbox.io/s/layout-data-qlkg8
