### ISSUE TITLE
Moving across pages hides the node

### ISSUE THREAD

**Issue by rajesh-ally** [antvis/X6#999]
### Expected Behavior
When scrolling is enabled and moving the nodes across pages should retain its visibility

### Current Behavior
But the node is getting invisible when moving across pages and getting visible only in the page which it is created.

![image](https://user-images.githubusercontent.com/76042038/119318247-b0aa5000-bc96-11eb-90d1-222ddd8d33f2.png)

### Possible Solution

NA
### Steps To Reproduce

 NA

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Additional Context

1.This happens only when scrolling is enabled.
2.Also I am using a custom react-shape as node(with elements contains styling position:relative,position:absolute).

Found this under **common problems** section of documentation. I guess my issue is related to this one.

![image](https://user-images.githubusercontent.com/76042038/119454005-a4d19300-bd55-11eb-8be4-687e00a2d4ab.png)

Is there any workaround for this issue ??

### Your Environment

- x6: 1.21.5
- OS: macOS Catalina
- Browser: chrome 90.0

**Comment by NewByVector** [comment]
Can you provide a reproducible codesanbox?
